### ISSUE TITLE
FileTarget rotation is not multiprocess-safe

### ISSUE THREAD

**Issue by Xharze** [NLog/NLog#100]
I found (unfortunately in the hardest way possible - by receiving a useless set of logs from a production issue) that FileTarget rotation is not multiprocess-safe - there may be races between one process checking that rotation is needed, another process performing rotation, yet another process also performing rotation etc.

I implemented a fix in "double-checked locking" style: I use a multiprocess mutex and double-check ShouldAutoArchive within the mutex.

This seems to work fine: I did a test where several instances of an app were constantly writing consecutive numbers to the same log file, with a small rotation threshold (20kb), and I checked that not a

single number was missed.

Without double-checked locking, or without the solution altogether, there were large gaps.

See my implementation in commit https://github.com/jkff/NLog/commit/8399f0467f1fcffb657db3e72c82f8e1748f75c7 .

The fix I introduced has since survived several months of extremely heavy production testing, so I think it should be safe to merge.

**Comment by 304NotModified** [comment]
@Xharze do you think we should do something with this old issue?

**Comment by Xharze** [comment]
@304NotModified I think we should decide if we want to support multiple processes writing to the same file. By supporting this we decreases performance. I don't think we should support this scenario.

**Comment by 304NotModified** [comment]
I think also no support. Performance is important and also I think writing multiple processes to the same file isn't a good idea.

**Comment by 304NotModified** [comment]
So closing for now.

**Comment by snakefoot** [comment]
Resolved by #1771
