### ISSUE TITLE
NLog's  'internalLogFile' destination question

### ISSUE THREAD

**Issue by Sal420** [NLog/NLog#1004]
Parameter: internalLogFile="c:\temp\nlog-internal.log" 

can this destination be 
1) a database 
2) or use a syntax of '~\App_Data\Logs\nlog-internal.log" . I tried but failed. Was this a user error on my end?

**Comment by 304NotModified** [comment]
It's limited to an absolute file path. 

Why not use the FileTarget/DatabaseTarget?

**Comment by Sal420** [comment]
The destination file is not the 'application' target but NLog's target see last line below

<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="true"     
      internalLogLevel="Info" 
      internalLogFile="c:\temp\nlog-internal.log" >

**Comment by 304NotModified** [comment]
OK. I'm curious, in which case do you need this?

Because the internalLog is only needed when analyzing NLog's behavior

**Comment by Sal420** [comment]
as you mentioned for analyzing - just curious if it can be stored elsewhere - perhaps review the log on an initial deployment. This not a road block - more a curiosity.
