### ISSUE TITLE
Android Xamarin support

### ISSUE THREAD

**Issue by polipo** [NLog/NLog#1007]
Dear,
When NLOG is compatible with Android Xamarin ?

I have found some prj fork but don't compile...

**Comment by 304NotModified** [comment]
We try to implement that in 4.3. But we need some help from users who are using Xamarin. Can you help with that?

**Comment by polipo** [comment]
Yes if my skill permit that..

**Comment by 304NotModified** [comment]
:+1:  that will be fine. More which tools I can use and maybe you can test it :) 

We never used xamarin, so supporting is a bit tricky. What do I need to compile it besides visual studio?

**Comment by 304NotModified** [comment]
PS I applied for the Xamarin Tools for OSS projects: https://xamarin.com/faq#q36

**Comment by 304NotModified** [comment]
- [ ] configure Xamarin in Appveyor: http://www.appveyor.com/docs/lang/xamarin
- [ ] fix builds
- [ ] Releasing it as a component on the Xamarin Component Store: http://components.xamarin.com

**Comment by polipo** [comment]
Dear,

for compile NLog in Visual Studio you can install the Xamarin framework,

this framework is not free but you can have a 30 day trial before purchase it.

 

This framework have a plugin for visual studio or you can use the ide “Xamarin Studio” (I prefer vs..)

 

Link for downloading

https://xamarin.com/download

 

I have a commercial Xamarin License.

 

 

Da: Julian Verdurmen [mailto:notifications@github.com] 
Inviato: mercoledì 28 ottobre 2015 19.20
A: NLog/NLog
Cc: Andrea Falappi
Oggetto: Re: [NLog] NLOG android XAMARIN (#1007)

 

 :+1: <https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png> that will be fine. More which tools I can use and maybe you can test it :) 

We never used xamarin, so supporting is a bit tricky. What do I need to compile it besides visual studio?

**Comment by polipo** [comment]
Great I read in previous posts you've joined the project Xamarin!
I wait for news on the release of NLog for Android

**Comment by 304NotModified** [comment]
FYI,  WIP in https://github.com/NLog/NLog/pull/1009

**Comment by 304NotModified** [comment]
Android + WinPhone8: https://www.nuget.org/packages/NLog/4.3.0-alpha1

Can you try it? Not sure if:

- The nupkg is correct
- The assembly Full name needs a version number

**Comment by 304NotModified** [comment]
Any experience with xamarin ios? And what about xamarin android with unit tests?

**Comment by davidkaya** [comment]
@304NotModified Hi, is there any estimate for the Xamarin iOS? I would like to use it for remote logging. If you need help with testing on iOS, I can give it a try.

**Comment by 304NotModified** [comment]
Hi @davidkaya ,

I can release a new alpha for 4.3 this week with Xamarin iOS. Some tests would really help us.

**Comment by 304NotModified** [comment]
This branch is already building for iOs (and Android)

https://github.com/NLog/NLog/tree/xamarin5

See https://ci.appveyor.com/project/nlog/nlog/branch/xamarin5

**Comment by davidkaya** [comment]
Ok! As soon as it is released as an alpha for 4.3, I will test it.

One more question:
Is some kind of "log caching" planned?
Use case:
When an application wants to log something to remote target, but the network/endpoint is not available. It should cache the logs locally and send them as soon as the network/endpoint is available.

**Comment by 304NotModified** [comment]
you can try https://github.com/NLog/NLog/wiki/RetryingWrapper-target

but it was not designed for long timeouts

**Comment by 304NotModified** [comment]
@davidkaya 

https://www.nuget.org/packages/NLog/4.3.0-alpha2

Please let us know how you experience NLog on iOs Xamarin!

**Comment by 304NotModified** [comment]
Close as this has been merged in 4.3 (trunk, not released yet)

**Comment by polipo** [comment]
I have installed NLog v4.3.3 via nuget, but on compile on my project. 
The compiler search the System.Configure assmbly this doesnt exist in Xamarin.

This problem doesn't exist if i use the reference of the sources of NLog.Android project.

**Comment by 304NotModified** [comment]
That's strange as System.Configuration is not referenced:

![image](https://cloud.githubusercontent.com/assets/5808377/15189585/d97b9678-17ab-11e6-93a2-d8904921e621.png)

**Comment by polipo** [comment]
yes, my error i found and old reference in my project excuse me. Close this.

**Comment by 304NotModified** [comment]
OK glad it has been solved!
