### ISSUE TITLE
How can Configuration File Variables be accessed in code

### ISSUE THREAD

**Issue by Sal420** [NLog/NLog#1010]
I've tried a couple of variations of the below
var x = logger.Factory.Configuration.Variables ?????

**Comment by 304NotModified** [comment]
Hey

use:

```C#
LogManager.Configuration.Variables["password"] = "123";
```

etc

**Comment by Sal420** [comment]
Hi
you steered me in the right direction. I was looking  to read variable (use it as input to drive logging). The solution:

if (logger.Factory.Configuration.Variables["password"].Text) = "mypassword"

**Comment by 304NotModified** [comment]
:+1: 

Thanks for the feedback!
