### ISSUE TITLE
Parsing a layout in NLog.Config does not work

### ISSUE THREAD

**Issue by Sal420** [NLog/NLog#1013]
Layout for user id:  <parameter name="@userName" layout="${identity}" />
produces: auth:NTLM:domaninName\\userID

I want only userID. To remove the unwanted characters I tried:

```xml
<parameter name="@userName" layout="${identity}.Replace('auth:NTLM:domainName\\', '')/>
```

This did not work. Is it possible to remove the unwanted characters?

**Comment by 304NotModified** [comment]
Which NLog version?

You need to escape the colon, so:

```xml
<parameter name="@userName" layout="${identity}.Replace('auth\:NTLM:domainName\\', '')/>
```

This only works in NLog 4.2+

**Comment by Sal420** [comment]
using ver Nlog4.2
there are 2 colons. Do they all need to be escaped (I assume yes) what about the  \ or any other characters.

**Comment by Sal420** [comment]
BTW - the code is in the NLog.Config file

Escaping the colon did not work. The test code is:
<parameter name="@userName" layout="${identity}.Replace('auth\:NTLM', '')" />

**Comment by Sal420** [comment]
Should have posted the results

auth:NTLM:domainName\userId.Replace('auth\:NTLM', ''

**Comment by 304NotModified** [comment]
You need the ${replace} layout renderer and to escape the colon.

Something like this:

```xml
${replace:searchFor=auth\:NTLM:replaceWith=:regex=false:inner=${identity}}
````

**Comment by Sal420** [comment]
thanks for your help the final working version below needed to escape all colons and back slash

<parameter name="@userName" layout="${replace:searchFor=auth\:NTLM\:domainName\\:replaceWith=:regex=false:inner=${identity}}" />

**Comment by 304NotModified** [comment]
OK great!
