### ISSUE TITLE
Add overflow action for EventLogTarget when the message is larger than the max message size of the Event Log

### ISSUE THREAD

**Issue by epignosisx** [NLog/NLog#1014]
I noticed that EventLogTarget truncates messages when it reaches the max message size. Has it been considered to split the message and write the chunks to the event log?

This is the method in question:

https://github.com/NLog/NLog/blob/master/src/NLog/Targets/EventLogTarget.cs#L214

**Comment by 304NotModified** [comment]
Hi,

We never considered that, because it's IMO a strange effect to create 2 events for 1 log message. Although, it's easy to implement. 

Any way, this max size should be documented well.

**Comment by epignosisx** [comment]
I see your point about creating 2 events for 1 log message, specially if you are expecting log messages in a particular format like JSON and you do not get a properly formatted message. 

We have been hit by this limitation with our homegrown logger and we are splitting the message. We care more about getting the entire message than getting two entries. I would think we are not the only ones. We have been talking about moving to something more robust and flexible like NLog and I particularly was testing long messages when I noticed they were being truncated.

You may ask what are we logging that is so large? We tend log web services responses (raw XML or JSON) in error scenarios.

I know I can overcome this behavior by inheriting from EventLogTarget and overriding the Write method, but I was wondering if you would be interested in making this an option of EventLogTarget that consumers could opt in to? I could help with a pull request.

**Comment by 304NotModified** [comment]
I think it's nice of we create a "overflow"  option. With possible values (enum) : truncate,  create multiple events. 

The big benefit is that the truncate is more transparent.  

What do you think?

**Comment by epignosisx** [comment]
I like it. I'll work on the change. Do you think a third value "Ignore" as in ignore the log message altogether would be useful? I'm thinking of those scenarios where we wouldn't like to have incorrectly formatted entries in the logs. Maybe we are rigorously expecting XML or JSON in the logs.

**Comment by 304NotModified** [comment]
I think Ignore is also useful (in some rare cases) :+1:

**Comment by epignosisx** [comment]
Closing as feature has been implemented and merged in #1041

**Comment by 304NotModified** [comment]
Thanks!

**Comment by 304NotModified** [comment]
docs: https://github.com/NLog/NLog/wiki/EventLog-target (up-to-date)
