### ISSUE TITLE
Overhaul ExceptionLayoutRenderer Methods

### ISSUE THREAD

**Issue by Page-Not-Found** [NLog/NLog#1016]
*Modify the Delegates to be func.

Delegate Definition / Signature:

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
private delegate void ExceptionDataTarget(StringBuilder sb, Exception ex);
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Methods which will be affected by this

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
AppendMessage
AppendMethod
AppendStackTrace
AppendToString
AppendType
AppendShortType
AppendData
CompileFormat
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by 304NotModified** [comment]
Do you mean to change the exception layout renderer? And to introduce funcs instead of a big switch? 

(PS func is always prefererred by delegate nowadays)

**Comment by Page-Not-Found** [comment]
Yes. I meant **ExceptionLayoutRenderer**. The switch will still be there, but just replace the delegates with func.

Do you have any proposal of totally removing the switch case?

PS: I corrected the title.

**Comment by 304NotModified** [comment]
In my opinion the current code is too much coupled.

But I'm doubting if removing the switch is overdesign, let me know:

1. create an enum for the Format values (please keep the string format backwardscompatibe)
2. create a method for parsing the format string to list of enum
3. create a static dictionary from enum to func
4. CompileFormat is now just a `foreach` over the result of 2 and using 3.

Benefits: 

- no switch (good for cyclomatic complexity)
- configure from API would be nice with enum-list instead of string.

**Comment by Page-Not-Found** [comment]
Let me try to get a proposed code change in.

**Comment by Page-Not-Found** [comment]
@304NotModified Sorry for mis-stating in the initial thread of this issue. What I actually meant was to replace with Action delegates instead of func delegates.

**Comment by 304NotModified** [comment]
Yes action is also OK. :)

**Comment by Page-Not-Found** [comment]
Okie. I am working on it. Will try to get the code ready by this week.

**Comment by 304NotModified** [comment]
:+1:

**Comment by Page-Not-Found** [comment]
@304NotModified 
>configure from API would be nice with enum-list instead of string.

How do see we can test this once the enums are created?

**Comment by 304NotModified** [comment]
What do you mean? 

To be more clear, I propose to use a `list<ExceptionInnerFormat>` instead of a string. 

We should keep it backwards compatible though

**Comment by Page-Not-Found** [comment]
Yes I have added them into the Layour Renderer, but how do cover those lists for unit testing when we do the configuration through the API?

**Comment by 304NotModified** [comment]
Let's chat about this when you have time. There is no problem with testing this IMO.

**Comment by Page-Not-Found** [comment]
Sure. I will IM you now, if you have time.

**Comment by Page-Not-Found** [comment]
Will you be having time to PR and push this in 4.3? if yes I can create PR for pushing this change into the master branch.

**Comment by 304NotModified** [comment]
Yes I have. :)
