### ISSUE TITLE
Improve mocking of file target (current date) 

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#1022]
There are/were some bugs with file archiving which are difficult to (unit)  test. Most of the time this has to do with the usage of current date(times) . 

Proposal : inject "current"  date into file target for better and more robust testing. 

Related: #859, #888, #964.

**Comment by 304NotModified** [comment]
Maybe use timesource? It's already (misused) for current date in the filetarget

**Comment by bhaeussermann** [comment]
I'm looking into this. Some of the mentioned issues above are not yet resolved, so some tests are going to fail. I shall have these tests Skipped for now. Will that be in order?

**Comment by 304NotModified** [comment]
Great! 

Those issues are indeed not (all) fixed. 

I was thinking :

- make mockable, pr and merge 
- for every issue, create unit test, fix if needed, and that in one PR. (TTD) 

It's okay to add unit tests with ignore if you have them already.
