### ISSUE TITLE
NLog doesn't throw exception to application

### ISSUE THREAD

**Issue by nirajdoshi1985** [NLog/NLog#1024]
I want NLog to throw exceptions and pass to my application whenever database target has a connection failure.

This is my NLog config file:
```
<nlog autoReload="true"
      throwExceptions="true"
      internalLogLevel="Debug" internalLogFile="c:\temp\nlog-internal.log">
```

Now, it does throw run-time exceptions when config when there is error in config file. Also it does log exceptions about connection failures in internal log file, but it doesn't throw exceptions back to the calling application.

I also tried wrapping Logger.Log method inside a try-catch just to be sure that it doesn't swallow it, but the Logger.Log statement is executed successfully.  I have also verified that LogManager.ThrowException is true at run-time too.

Is there anything more to it to catch an exception within application. I just want to prepare a cache of the log-events which aren't logged and then log back to the SQL Server when the connection is again available.

NLog-version (v4.0). 
Application-type: WPF
Database: SQL Server

**Comment by 304NotModified** [comment]
I'm afraid that isn't working well, yet.

We're working on it: https://github.com/NLog/NLog/pull/915

What you use the Fallback target: https://github.com/NLog/NLog/wiki/FallbackGroup-target

**Comment by nirajdoshi1985** [comment]
Thank you for your prompt response. I will have a look at Fallback target and waiting for resolution of `HandleException()`.
