### ISSUE TITLE
File target with  concurrentWrites="True" and enableArchiveFileCompression="True" does not function

### ISSUE THREAD

**Issue by jonreis** [NLog/NLog#1028]
Here is my File target specification:

     <target name="FileLogger" xsi:type="File" header = "------ Connexion v${assembly-version} ------" layout="${longdate} (${threadid}) ${level} ${event-context:eventId} [${logger}] ${share.TruncateLayout:${message}} ${exception:format=tostring}" fileName="${specialFolder:folder=CommonApplicationData}/ConnexionV14/logs/Connexion.txt" archiveFileName="${specialFolder:folder=CommonApplicationData}/ConnexionV14/logs/Connexion.{#}.zip" archiveNumbering="Date" archiveEvery="Day" archiveDateFormat="yyyyMMdd" maxArchiveFiles="10" enableArchiveFileCompression="true" concurrentWrites="true" keepFileOpen="true" encoding="iso-8859-2" />

The offending line in void ArchiveFile(string fileName, string archiveFileName, bool enableCompression) appears to here

                using (var originalFileStream = new FileStream(fileName, FileMode.Open, FileAccess.Read))

An exception occurs because another file is using it.

If I change this to

               using (var originalFileStream = new FileStream(fileName, FileMode.Open, FileAccess.Read, FileShare.ReadWrite | FileShare.Delete))
 
Which matches the original sharing specification when the file was opened. My understanding, and I know I have found documentation on this before, is that the FileShare specification needs to match the currently opened file exactly, or the share will fail.

At any rate, the exception is thrown and I am left with a bunch of 0  length zip files. The main log file never rotates.

If I remove the enableArchiveFileCompression flag, everything works, but there is no compression.

Also, do you think it would be better to perform the compression after the file has been rotated? This could be done in a background thread.

**Comment by 304NotModified** [comment]
Hi, 

Can you post the full exception and relevant internal logs? See https://github.com/NLog/NLog/blob/master/CONTRIBUTING.md

Thx!

**Comment by jonreis** [comment]
The version is 4.2. The stack trace is:
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at NLog.Targets.FileTarget.ArchiveFile(String fileName, String archiveFileName, Boolean enableCompression) in J:\Projects\NLog-master\src\NLog\Targets\FileTarget.cs:line 985
   at NLog.Targets.FileTarget.RollArchiveForward(String existingFileName, String archiveFileName, Boolean allowCompress) in J:\Projects\NLog-master\src\NLog\Targets\FileTarget.cs:line 1006
   at NLog.Targets.FileTarget.ArchiveByDate(String fileName, String pattern) in J:\Projects\NLog-master\src\NLog\Targets\FileTarget.cs:line 1257
   at NLog.Targets.FileTarget.DoAutoArchive(String fileName, LogEventInfo eventInfo) in J:\Projects\NLog-master\src\NLog\Targets\FileTarget.cs:line 1422
   at NLog.Targets.FileTarget.Write(LogEventInfo logEvent) in J:\Projects\NLog-master\src\NLog\Targets\FileTarget.cs:line 680
   at NLog.Targets.Target.Write(AsyncLogEventInfo logEvent) in J:\Projects\NLog-master\src\NLog\Targets\Target.cs:line 440

There is nothing relevant in the nlog log file. Just 2015-11-20 15:58:27.4591 Info Archiving C:\ProgramData\ConnexionV14\logs\Connexion.txt to zip-archive C:\ProgramData\ConnexionV14\logs\Connexion.20151119.zip. But the exception is expected so it is not logged.

**Comment by jonreis** [comment]
The issue is the FileShare.Delete option. From MSDN:

https://msdn.microsoft.com/en-us/library/windows/desktop/aa363858(v=vs.85).aspx

"You cannot request a sharing mode that conflicts with the access mode that is specified in an existing request that has an open handle. CreateFile would fail and the GetLastError function would return ERROR_SHARING_VIOLATION."

Since the file was first opened the file with FileShare.Delete, subsequent opens must also have FileShare.Delete because if the second open of the file were allowed to open it without FileShare.Delete, then there would be a conflict with the first process which could no longer delete the file, because the second process opened it without allowing deletes.

**Comment by jonreis** [comment]
BTW,
The compression should happen after the file has been moved, and in a background thread. The matching of the FileShare.Delete still applies, however.

**Comment by jonreis** [comment]
This would be my fix

    /// <summary>
    /// Creates an archive copy of source file either by compressing it or moving to a new location in the file
    /// system. Which action will be used is determined by the value of <paramref name="enableCompression"/> parameter.
    /// </summary>
    /// <param name="fileName">File name to be archived.</param>
    /// <param name="archiveFileName">Name of the archive file.</param>
    /// <param name="enableCompression">Enables file compression</param>
    /// <param name="enableDelete">Enables file deletion</param>
    private static void ArchiveFile(string fileName, string archiveFileName, bool enableCompression, bool enableDelete)
    {
      string archiveFolderPath = Path.GetDirectoryName(archiveFileName);
      if (!Directory.Exists(archiveFolderPath))
        Directory.CreateDirectory(archiveFolderPath);

#if NET4_5
      if (enableCompression)
      {
        var tempFileName = archiveFileName + ".tmp";
        File.Move(fileName, tempFileName);
        Task.Run(async () =>
        {
          var share = FileShare.ReadWrite;
          if (enableDelete)
            share |= FileShare.Delete;

          try
          {
            InternalLogger.Info("Archiving {0} to zip-archive {1}", fileName, archiveFileName);
            using (var archiveStream = new FileStream(archiveFileName, FileMode.Create))
            using (var archive = new ZipArchive(archiveStream, ZipArchiveMode.Create))
            using (var originalFileStream = new FileStream(tempFileName, FileMode.Open, FileAccess.Read, share, 4096, FileOptions.DeleteOnClose))
            {
              var zipArchiveEntry = archive.CreateEntry(Path.GetFileName(fileName));
              using (var destination = zipArchiveEntry.Open())
              {
                await originalFileStream.CopyToAsync(destination);
              }
            }
          }
          catch(Exception)
          {
          }
        });
      }
      else
#endif
      {
        InternalLogger.Info("Archiving {0} to {1}", fileName, archiveFileName);
        File.Move(fileName, archiveFileName);
      }
    }

**Comment by jonreis** [comment]
This fix does not actually work because for some reason the file at tempFileName remains locked by one of the processes sharing the file. Using the code in bug #1029, and setting keepFileOpen="false" seems to fix this problem, so it is probably related to that bug.

**Comment by 304NotModified** [comment]
Thanks for the update.  We will look at this,  probably before Monday.

**Comment by 304NotModified** [comment]
> Using the code in bug #1029, and setting keepFileOpen="false" seems to fix this problem, so it is probably related to that bug.

What do you mean exactly with this? There is no code proposed in #1029?

**Comment by jonreis** [comment]
> What do you mean exactly with this? There is no code proposed in #1029?

I mean using the test code in #1029. ie. to reproduce the issue.

**Comment by 304NotModified** [comment]
Will looks at this upcoming week.
