### ISSUE TITLE
Directory paths should be normalized when read from the App.config

### ISSUE THREAD

**Issue by jonreis** [NLog/NLog#1030]
NLog 4.2
While looking into another issue I noticed that my app.config contained the forward slash character '/' instead of the back slash character '\' in the path of the file. i.e, I had

fileName="${basedir}/logs/ConcurrentFileTargetTest.txt"

instead of 

fileName="${basedir}\logs\ConcurrentFileTargetTest.txt"

I noticed in the FileTarget.cs function: 

```javascript
        private void RollArchiveForward(string existingFileName, string archiveFileName, bool allowCompress)
```

that the file was being looked for in the initializedFiles dictionary.

The look up always failed because in the dictionary the file path was

/logs/ConcurrentFileTargetTest.txt

where as the lookup key was

\logs\ConcurrentFileTargetTest.txt

I didn't track it down further, but it would appear that when the config file is read in, the paths should be normalized to have the '\' character.

Also, I noticed that the initializedFiles was not using a case insensitive dictionary. This may also cause problems when looking up the file if there is a case mismatch.

**Comment by 304NotModified** [comment]
Thanks for this report! Also this one before Monday.

**Comment by 304NotModified** [comment]
> Also, I noticed that the initializedFiles was not using a case insensitive dictionary. This may also cause problems when looking up the file if there is a case mismatch.

I think this is by design. We do support Mono and with non-Windows system, the casing is important.

**Comment by 304NotModified** [comment]
I tried to unit test this, but all succeeded. Any idea how to unit test this? See https://github.com/NLog/NLog/pull/1032

**Comment by jonreis** [comment]
> I tried to unit test this, but all succeeded. Any idea how to unit test this? See #1032

It is something I noticed in the debugger. Just try setting the '/' in the config file and set a break point in RollArchiveForward, you will see what I mean. You can use the test code from #1029 and roll the date by changing the date on your computer. Not sure how to unit test this.

**Comment by jonreis** [comment]
Julian, thank you very much for taking the time to look at the bugs that I reported. It is much appreciated.

>> Also, I noticed that the initializedFiles was not using a case insensitive dictionary. This may also cause problems when looking up the file if there is a case mismatch.

>I think this is by design. We do support Mono and with non-Windows system, the casing is important.

It could be #ifdef'd for those platforms.

```javascript
        private readonly Dictionary<string, DateTime> initializedFiles
#if !Mono && !NET_CF
            = new Dictionary<string, DateTime>(StringComparer.OrdinalIgnoreCase);
#else
            = new Dictionary<string, DateTime>();
#endif
```

**Comment by 304NotModified** [comment]
That's a good idea!

**Comment by 304NotModified** [comment]
Was thinking about this:

- If everything wen well, then StringComparer.OrdinalIgnoreCase isn't needed?
- I can run Mono on a Windows system, and .Net in the future on a non-windows...

**Comment by 304NotModified** [comment]
> It is something I noticed in the debugger.

I believe you of course, but if the unit test isn't failing, well then the code is OK, or the unit test is bad. I really like to fix the unit test before I fix the code (TDD)

**Comment by jonreis** [comment]
> If everything wen well, then StringComparer.OrdinalIgnoreCase isn't needed?
> I can run Mono on a Windows system, and .Net in the future on a non-windows...

It may be fine without. The function Path.GetFullPath will probably normalize it for you. However; since windows is not case sensitive with respect to the file system, it seems safer to #ifdef the OrdinalIgnoreCase for that platform.

**Comment by jonreis** [comment]
For the main issue reported in the bug, using Path.GetFullPath does normalize the directory separators (both for direction and number). eg '/' gets converted to '\' and a double slash: '//' to '\'


```
    [Test]
    public void GetFullPath()
    {
      var p1 = Path.GetFullPath("c:/temp/ConcurrentTest/log.txt");
      var p2 = Path.GetFullPath(@"c:\temp\ConcurrentTest\log.txt ");
      Assert.AreEqual(p1, p2);
    }

    [Test]
    public void GetFullPath2()
    {
      var p1 = Path.GetFullPath("c://temp/ConcurrentTest//log.txt");
      var p2 = Path.GetFullPath(@"c:\\temp\ConcurrentTest\\log.txt ");
      Assert.AreEqual(p1, p2);
    }
```

**Comment by 304NotModified** [comment]
Yes I also think this is normalized by path.GetFullPath. 

Because if I wrote a normalize method, I would use `GetFullPath` ;)

**Comment by 304NotModified** [comment]
But so, there is no bug?

**Comment by 304NotModified** [comment]
I we have a unit test for this,  I will fix the code.

**Comment by 304NotModified** [comment]
I don't think here is a problem and so we don't have to fix things.
