### ISSUE TITLE
Handle relative path, or at least warn when detecting one

### ISSUE THREAD

**Issue by serbrech** [NLog/NLog#1045]
When using a relative path in the config as follow : 

    <target xsi:type="File" fileName="Logs\myapp.${shortdate}.log" name="file"
            layout="${longdate}|${level:uppercase=true}|${logger}|${message}" />

The expected behavior from the user point of view is always to log in a folder relative to where the application executes.

This can be easily detected and either pro-actively understand that it is a relative path
or emit a warning in the internal log file.

**Comment by 304NotModified** [comment]
I agree with this. Thanks for the suggestion. 

We will fix this, if we can keep this backwards-compatible.

**Comment by Page-Not-Found** [comment]
Do we really want to allow for Relative Path or we just need to add warning to the internal log?

**Comment by 304NotModified** [comment]
This has been fixed and will be released in 4.3

**Comment by 304NotModified** [comment]
docs: https://github.com/NLog/NLog/wiki/File-target
