### ISSUE TITLE
Limit messages per hour (or other time span)

### ISSUE THREAD

**Issue by jonbprime** [NLog/NLog#1049]
Would be great if you could specify a limit on the number of emails that will go out in a given period from an Email target. For example, if you the system email you for each error log, and the error is in a tight loop, you don't want to get 1000's of emails. 

So you could have a target config parameter like maxEmailsPerHour="20". As soon as 20 emails have been sent in the last hour, the target ignores any future errors until enough time has passed such that only 19 emails (or less) have been sent in the past hour

Version: 4.2

**Comment by 304NotModified** [comment]
I agree! I thinking it should be a WrapperTarget. I was thinking we have it already, but not one with timing. What do you think?

What happens when the program stops and restarts?

**Comment by jonbprime** [comment]
Never used wrappers, but it makes sense since then it could be used by all targets.

When the program restarts (looses it "count") it just resets as if no logs had gone out in the last period. This mechanism is just to stop 1000's of emails from flooding your inbox. If ti's not perfect (loosing count, not exactly 60 minutes, etc), it's OK.

**Comment by UgurAldanmaz** [comment]
Is it good idea to keep the count of sent email at the temp file? (Also last sent time.)

**Comment by 304NotModified** [comment]
> When the program restarts (looses it "count") it just resets as if no logs had gone out in the last period. This mechanism is just to stop 1000's of emails from flooding your inbox. If ti's not perfect (loosing count, not exactly 60 minutes, etc), it's OK

Yes, I was also thinkiing that. 

> Is it good idea to keep the count of sent email at the temp file? (Also last sent time.)

That would be also possible, but you need write rights etc. I was more curious if resetting was OK. 

@jonbprime 

Just one other question, to be sure:

- limit is 20
- 1st hour is 25 message are logged
- 2nd hour 5 message are logged
- the first hour we send 20 mails
- what do we send the 2nd hour? 5 of 10? Or configurable?

**Comment by UgurAldanmaz** [comment]
If we send 20 emails per hour;
First hour, emails ignored (5) that exceed the limit (20).
Second hour, it is the new session. Send until 20.

**Comment by 304NotModified** [comment]
Maybe that's the best case. Less memory consumption. We van build persistently  in a later phase). 

@jonbprime if you agree, please add to NLog.uservoice.com

**Comment by UgurAldanmaz** [comment]
Why did you renamed the title with `messages`? Limit will contain all type of message or just email? :)

**Comment by 304NotModified** [comment]
> BTW, Is van dutch? :) (Which you wrote as We van)

Typo, should be "We can"

> Why did you renamed the title with messages?

Because this behavior is better to have it generic (not only email) - the WrapperTargets are created for that purpose.

**Comment by Jeinhaus** [comment]
I was just about to get started on this, but realized, that the AsyncTargetWrapper pretty much already has this functionality.

If you set the BatchSize to the number of Emails you want to receive and the TimeToSleepBetweenBatches to the time you want the interval to be, then you have that exact behaviour.

Or am I missing something here?
Maybe we could add a new TimeSpan property to the AsyncTargetWrapper, so it is easier to define intervals of hours, etc. by doing TimeSpan.FromHours(1) instead of having to define the interval in Milliseconds.

**Comment by jonbprime** [comment]
I have not used those batch parameters before. I'll give it a try.

**Comment by 304NotModified** [comment]
Well there's a difference, all the messages will be delayed. Eg. If the timeout is 30min, you recieve the first message after at least 30min

I do agree on tge timeout property.  From sec is unneeded difficult.

**Comment by 304NotModified** [comment]
Also the this wrapper would write (optional) on the main thread.

**Comment by Jeinhaus** [comment]
Ah, ok. I think I misunderstood the requirements a bit. I thought the intention was to gather up to "limit" messages, and then write them all at once.
I thought a bit about the requirements you specified and would like to give it a shot at implementing them. 
I think the easiest and most obvious solution would be to reset the Interval in which messages are counted, every time a new message comes in after the previous interval has expired.

Just so we are on the same boat regarding the behaviour, I'll give a quick example how I think the behaviour should be.
Assuming (like in the above example) we set `LimitingTargetWrapper.Interval = TimeSpan.FromHours(1)` and the `LimitingTargetWrapper.MessageLimit = 20` I would expect the wrapper to behave like this:

Between 8:00 - 9:00am:

- 25 messages incoming at 8:15 -> 20 messages are written and 5 messages are discarded.

- First interval is set to go from 8:15 to 9:15

Between 9:00 - 10:00am: 

- 5 messages incoming before 9:15-> 5 messages ignored (still in old interval)

- 20 messages incoming after 9:15-> 20 messages written

- new interval is started at first message after 9:15

Between 10:00 - 11:00 am:

- No messages (no new interval is started)

Between 11:00 - 12:00 am:
- 5 messages at 11:45 -> 5 messages written

- new interval is set from 11:45 to 12:45

Between 12:00 - 1:00 pm:
- 20 message at 12:00 -> 15 message written, 5 messages discarded (5 messages were already written in interval)

Do you agree with that behaviour? If yes, I will go ahead and implement some tests and the wrapper.

**Comment by 304NotModified** [comment]
Sounds good to me! Nice use cases :) 

I think its wise to print to the internal log (debug)  the start of the interval and (trace) when logs are discarded.

**Comment by Jeinhaus** [comment]
Yeah, sounds good to me. I'll get started on this in the next days.

**Comment by 304NotModified** [comment]
Cool :+1:

**Comment by snakefoot** [comment]
Guess this issue is now resolved?

**Comment by 304NotModified** [comment]
yes thanks @snakefoot !
