### ISSUE TITLE
IWcfLogReceiverClient LogReceiverWebServiceTarget.CreateLogReceiver() should be virtual

### ISSUE THREAD

**Issue by jonreis** [NLog/NLog#1050]
NLog 4.2

The virtual method that has been obsoleted is:

        [Obsolete("Ths may be removed in a future release.  Use CreateLogReceiver.")]
        protected virtual WcfLogReceiverClient CreateWcfLogReceiverClient()

The new method that is supposed to be used instead is as follows, and therefore needs to be made virtual so it can, in fact, be overridden.

```Javascript
        /// <summary>
        /// Creating a new instance of IWcfLogReceiverClient
        /// 
        /// Inheritors can override this method and provide their own 
        /// service configuration - binding and endpoint address
        /// </summary>
        /// <returns></returns>
        protected IWcfLogReceiverClient CreateLogReceiver()
        {
#pragma warning disable 612, 618

            return this.CreateWcfLogReceiverClient();

#pragma warning restore 612, 618

        }
```

**Comment by 304NotModified** [comment]
Agree,  will fix it.

**Comment by 304NotModified** [comment]
fixed, release ETA: within a week

**Comment by 304NotModified** [comment]
NLog 4.2.1 has been released! https://www.nuget.org/packages/NLog/4.2.1
