### ISSUE TITLE
Memory Allocations in BaseFileAppender

### ISSUE THREAD

**Issue by epignosisx** [NLog/NLog#1051]
While profiling #1038 I noticed that this [line](https://github.com/NLog/NLog/blob/master/src/NLog/Internal/FileAppenders/BaseFileAppender.cs#L163) was incurring in three memory allocations:

1- boxing of the parameter boolean allowFileSharedWriting
2- creating the object[] args.
3- the boxed boolean is converted to string when used in string.Format

This line of code is executed every time a message is logged if the **RetryingMultiProcessFileAppender** is used, which I think is the default option.

There are two things we can do here:
1- Remove the method call and avoid the three memory allocations.
2- Explicitly call allowFileSharedWriting.ToString() and avoid the boxing allocation.

I want to know your thoughts, before submitting a pull request.

**Comment by 304NotModified** [comment]
I know boxing can take some performance. But is this not a problem with all the Loggers ATM? (e.g. 

```
Logger.Info("{0}", true);
```

(then we should fix it also there)

**Comment by epignosisx** [comment]
Yes, it is a problem overall. However, since this is the internal logger I thought that removing this method call was not a big deal and could save a few allocations.

I don't see a way to go around the boxing problem. I looked into having generic arguments overloads and calling `ToString()` on them but that doesn't work well with the existing **params object[] args** because if an array is used it will be resolved to the `Write<T1>`(...) overload instead.

This is how it looks:

![image](https://cloud.githubusercontent.com/assets/697377/11215233/2d6a6d78-8d13-11e5-92cb-cf801c25a5de.png)

**Comment by 304NotModified** [comment]
But isn't the case nr 2?

(yes `params` is evil with overload resolution)

**Comment by epignosisx** [comment]
Sorry, I didn't get what you mean by:

> But isn't the case nr 2?

**Comment by 304NotModified** [comment]
I mean with the 2nd case: 

![image](https://cloud.githubusercontent.com/assets/5808377/11250685/f511f9b6-8e2d-11e5-90ce-fb54d9670643.png)

**Comment by epignosisx** [comment]
Oh yes. That should have called ToString(), But I was actually showing that having generic arguments would not work well with params object[] overload.

**Comment by 304NotModified** [comment]
This is good news as the Logger has already the methods.  

I'm curious what the results are for `T[] ` (instead of `T`

**Comment by epignosisx** [comment]
Funny. Ayende just posted about [this]
(http://ayende.com/blog/172545/the-hidden-costs-of-allocations?Key=08667b02-cf92-4cb5-bb3e-583509653019&utm_source=feedburner&utm_medium=twitter&utm_campaign=Feed%3A+AyendeRahien+%28Ayende+%40+Rahien%29)

**Comment by 304NotModified** [comment]
Nice post. I think the bad creation of arrays is also in the core logger.

**Comment by 304NotModified** [comment]
https://github.com/NLog/NLog/blob/master/src/NLog/Logger.cs

**Comment by 304NotModified** [comment]
https://github.com/NLog/NLog/blob/master/src/NLog/Logger.cs#L288

**Comment by 304NotModified** [comment]
Not sure to I understand the full blog. This can't be prevented? Is that the conclusion? (well only in client code)

**Comment by epignosisx** [comment]
I think that's his conclusion. There is no way to go around this allocations.

**Comment by 304NotModified** [comment]
OK Thanks for the info :)

**Comment by snakefoot** [comment]
Resolved by #1702 + #1719 in NLog v4.3.10
