### ISSUE TITLE
Load different NLog configuration file at runtime

### ISSUE THREAD

**Issue by jgodfrey** [NLog/NLog#1053]
I have a NLog-based .NET application that installs with a number of "configuration-related" files, including app.exe.config, nlog.config, and a handful of domain-specific XML config files.

At some point, after the application is running, I'd like to completely reconfigure it by loading a new set of configuration files from a completely different folder. I've been able to successfully reload all config related data except for the NLog configuration.

I don't want to **change** the current NLog.config file, I simply want to load a new (static) file from a different folder. Is that possible? So far, I haven't found a way to do so...

**Comment by 304NotModified** [comment]
Yeah sure that could be done :) 

On mobile short in short:

Create a new http://nlog-project.org/documentation/v4.0.0/html/M_NLog_Config_XmlLoggingConfiguration__ctor.htm

Assign it to LogManager.configuration

**Comment by jgodfrey** [comment]
Great - thanks for the tip.  Unfortunately, I'm currently using version 2.01.  Looking there, I don't see any equivalent object.  Is it possible in 2.01, or do I need to look at upgrading?

Thanks again.

**Comment by 304NotModified** [comment]
http://nlog-project.org/documentation/v2.0.1/

But would recommend updating. We don't support 2 anymore and some bugs with (reloading) config files are fixed in NLog 4. 

Some info for upgrading: http://nlog-project.org/2015/06/09/nlog-4-has-been-released.html

**Comment by jgodfrey** [comment]
OK - I've upgraded the project to 4.2.0 and I've managed to reload my config data using the mechanism mentioned above. So, problem solved!

Thank you for your assistance.

**Comment by 304NotModified** [comment]
Have fun with the new release :)
