### ISSUE TITLE
How  to choose Target?

### ISSUE THREAD

**Issue by zwy2014** [NLog/NLog#1059]
I studied the source code,But I am a little in doubt.Are written to the log of the last call method Write, here has a note:Writes log event to the log target. Must be overridden in inheriting classes.   My question is how to choose the Subclass of Target?

**Comment by UgurAldanmaz** [comment]
Hi @zwy2014 
What do you mean by "Subclass of Target". You mean that target type? Database, file, email etc...
If so, [target wiki page] (https://github.com/NLog/NLog/wiki/Targets) can help you.

**Comment by 304NotModified** [comment]
Or maybe you are looking for the `<rules>` in the configuration, see https://github.com/NLog/NLog/wiki/Configuration-file

**Comment by zwy2014** [comment]
Thanks @UgurAldanmaz @304NotModified , I solved the problem,I should learn from these documents more carefully
