### ISSUE TITLE
ILogReceiverServer ProcessLogMessages

### ISSUE THREAD

**Issue by Xharze** [NLog/NLog#106]
<p>Under the OperationContract attribute definition, IsOneWay = false (the default). I don&#39;t know if this is the intended behavior, because it prevents the ability to use MSMQ.</p>
<p>&nbsp;</p>
<p>&quot;If the IsOneWay property is set to false (the default), even methods that return void result in a reply message. In this case, the infrastructure creates and sends an empty message to indicate to the caller that the method has returned. (Using this approach enables the infrastructure to send SOAP faults back to the client.) Setting IsOneWay to true is the only way to cancel the creation and dispatch of a response message.&quot;</p>

**Comment by 304NotModified** [comment]
Closed by #565
