### ISSUE TITLE
NuGet package file versions

### ISSUE THREAD

**Issue by TheMetalMonkey** [NLog/NLog#1065]
I have just encountered a deployment issue caused by NLog. We use an msi installer produced with wixtoolkit. Upgrade installs require increasing file version number's.

Version 4.2.1 has File Version 4.0.1251.0, while 4.2.0 has File Version 4.2.0
In all previous versions, the File Version matched the release version number. I.e. Version 4.2.0 has File Version 4.2.0

**Comment by 304NotModified** [comment]
Thanks for reporting this issue.

I never create installers. Can you tel me what goes wrong when executing the installer?

And do you need a new release or can you work around the problem?

**Comment by TheMetalMonkey** [comment]
The wix toolkit uses the assembly 'File Version' number to determine which
is the latest version of a file (to support patching updates etc).

The installer works fine with a fresh install. On an upgrade install, the
4.2.0 NLog was removed, however the 4.2.1 (which was versioned as 4.0....)
was not put in the target directory. NLog dll was completely missing
causing my service and application to crash.

I don't think the installer did a good job either - it should have left at
least left what it thought was the latest. I am not sure what the procedure
is if I have a legitimate reason to downgrade (if I found a new version
dependency really was broken and wanted to roll back). But that is another
story.

As long as increasing versions actually increase in the file version it all
works well.

My current workaround was to roll NLog back to 4.2.0.

**Comment by 304NotModified** [comment]
OK thanks for the info.

I'm thinking about releasing a 4.2.2.

**Comment by TheMetalMonkey** [comment]
Thanks.

**Comment by 304NotModified** [comment]
This has been fixed. New file version is 4.2.2.1251. https://www.nuget.org/packages/NLog/4.2.2
