### ISSUE TITLE
High CPU usage with async (with timeToSleepBetweenBatches="0")

### ISSUE THREAD

**Issue by Bidou44** [NLog/NLog#1069]
I have the problem that the CPU has 20-30% usage all the time.
To reproduce the problem, you can simply create a project with just a Log statement and the following configurations:

    <nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" throwExceptions="true">
      <targets>
        
            <target name="Database" xsi:type="Database">
              <connectionStringName>XXX</connectionStringName>
              <commandText>XXX</commandText>
            </target>
        
      </targets>
      <rules>
        ....
      </rules>
    </nlog>

Someone already reports this bug a few years ago https://github.com/NLog/NLog/issues/162. Not sure that is was correctly fixed. I'm using version 4.2.1

**Comment by Bidou44** [comment]
Changing timeToSleepBetweenBatches to "100" seems to fix the problem....
Not sure if this is a bug ?!

**Comment by 304NotModified** [comment]
Hi,

I don't think this is a bug, because you don't give the CPU any rest when setting `timeToSleepBetweenBatches` on zero. Default is 50 I see

**Comment by 304NotModified** [comment]
Do you have some example code?

**Comment by 304NotModified** [comment]
@Bidou44 

can you give some more info?

**Comment by Bidou44** [comment]
Not sure to understand want you need from me. The problem is fixed when setting a value different from 0. I think that one should not be able to set this value to 0 (exception?)... At least, I don't see any scenario where it would make sense...

**Comment by 304NotModified** [comment]
OK thanks for the info. It's  a bit strange,  because 0 should throw an exception : https://msdn.microsoft.com/en-us/library/system.timers.timer.interval(v=vs.90).aspx

**Comment by 304NotModified** [comment]
Todo: 
- [ ] prevent / check 0 value

**Comment by vincechan** [comment]
On why it's not getting an exception:

https://msdn.microsoft.com/en-us/library/system.timers.timer.interval(v=vs.90).aspx
This is the System.Timers.Timer which will throw an exception on 0 value

https://msdn.microsoft.com/en-us/library/system.timers.timer.interval(v=vs.90).aspx
The NLog code is using the System.Threading.Timer, which does not throw an exception on 0 value 
*this.lazyWriterTimer.Change(this.TimeToSleepBetweenBatches, Timeout.Infinite);*

**Comment by 304NotModified** [comment]
Indeed! Thanks!

**Comment by 304NotModified** [comment]
So we need to throw our own exception (NLogConfigurationException) if timeToSleepBetweenBatches=0
