### ISSUE TITLE
Performance FileTarget (10 million messages)

### ISSUE THREAD

**Issue by varunkumarmnnit** [NLog/NLog#1071]
Hello I have recently started using Nlog .I am getting a serious performance issue with Nlog .Bleow is my code 
Programm.cs 

```c#
using System;
using System.Collections.Generic;
using System.Data.SqlTypes;
using System.Diagnostics;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Security.Cryptography.X509Certificates;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using NLog;
using NLog.Common;
using NLog.Targets;
using NLog.Targets.Wrappers;

namespace NLogTest
{
    class Program
    {
        static void Main(string[] args)
        {
            
            Stopwatch sw = Stopwatch.StartNew();
            TestLoggerHierarchy();
            sw.Stop();
            Console.WriteLine("Time taken: {0}ms", sw.Elapsed.TotalMilliseconds);
            
        }

        

        private static void TestLoggerHierarchy()
        {
            for (var i = 0; i < 1; i++)
            {
                string jobId = System.Guid.NewGuid().ToString();
                NLog.GlobalDiagnosticsContext.Set("jobId", jobId);
              
           
              ILogger mipLogger = LogManager.GetLogger("mipLogger");
              
                mipLogger.Info("MIP Started");
       
                for (var line = 0; line < (10000000 + (i * 100)); line++)
                {
                    mipLogger.Info("MIP : " + line);
                }

                mipLogger.Info("MIP Finished");
            
            }
        }


   
    }
}
```

App.config

```xml
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <configSections>
    <section name="nlog" type="NLog.Config.ConfigSectionHandler, NLog"/>
  </configSections>
  <nlog xmlns="http://nlog-project.org/schemas/NLog.xsd"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <extensions>
        <add assembly ="NLogTest"/>
    </extensions>
    <targets async="true">      
  
         <target name="asyncWrapper" xsi:type="AsyncWrapper"   overflowAction="Discard" queueLimit="1000000" batchSize="1000" timeToSleepBetweenBatches="0"> 
        <target name ="mipLoggertarget" xsi:type="File" fileName="D:/Log/${gdc:item=jobId}/MIP/MipLogger.log" layout="${message}" keepFileOpen="true" />
         </target> 

   </targets>

    <rules>
      <logger name="mipLogger" minlevel="Info" writeTo="mipLoggertarget"/>
    
    </rules>
  </nlog>

  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5" />
  </startup>
</configuration>
```

.You can see above I am using async way also to genearte the logs .I am generating 
141Mb file and its taking 
503537.2786ms which is very high if I write a simple program to write same  thing in a file with normal file io operations .(i have generated 1 Gb file in less time in what log stash is genearting above .

Please give me the fed back where I am doing wrong .And I am not sure async version is working or not .

**Comment by 304NotModified** [comment]
Thanks for the report and demo code! It should be fast. We will look at your example into detail.

**Comment by varunkumarmnnit** [comment]
Hello ,
I could not get your point .U mean I should change the timesleep between batches to 50ms or something else u are referring to

**Comment by 304NotModified** [comment]
Yes that's what I mean!

**Comment by varunkumarmnnit** [comment]
Hello,
Please find the timing after u suggested the chages 
105620.0587ms (nlogger)
2449 ms ( without nlogger)
You can see there is a huge timing difference .
Can u suggest where is the issue .

**Comment by 304NotModified** [comment]
I checking this out.

Of course is an application which don't anything, is razor fast ;)

Can you compare it the meantime with a file.writeline?

**Comment by varunkumarmnnit** [comment]
Hello 304,
Thanks for our effort.The above Nlog progra I am comparing with below program which is nothing but file write operation .


class Program
    {
        static void Main(string[] args)
        {
            Stopwatch sw = Stopwatch.StartNew();
            string folderName = @"D:\Log";
            string jobId = System.Guid.NewGuid().ToString();
            jobId = jobId + "\\MIPS"; 
            string pathString = System.IO.Path.Combine(folderName, jobId);
            System.IO.Directory.CreateDirectory(pathString);

            string fileName = "Mipslogger.log";
            pathString = System.IO.Path.Combine(pathString, fileName);
            using (System.IO.FileStream fs = System.IO.File.Create(pathString))
            {
               
            }
            using (System.IO.StreamWriter file =
           new System.IO.StreamWriter(pathString))
            {
                for (var line = 0; line < (10000000 + (1 * 100)); line++)
                {
                    file.WriteLine("MIP : " + line);
                }
            }
            sw.Stop();
            Console.WriteLine("Time taken: {0}ms", sw.Elapsed.TotalMilliseconds);
            
        }

This is exactly writing the same content as Nlogger .

**Comment by 304NotModified** [comment]
Which timing you have with that?

**Comment by 304NotModified** [comment]
> 105620.0587ms (nlogger)
> 2449 ms ( without nlogger)

So 105 sec vs 2 sec? (not sure if the , is here the thousand separator)

**Comment by varunkumarmnnit** [comment]
Yes .

**Comment by 304NotModified** [comment]
What timing you have with file.writeline?

**Comment by varunkumarmnnit** [comment]
Hello,
I have mentioned above .Its 2 seconds vs with nlogger (with change in the configuration u have suggested) its 105 seconds

**Comment by 304NotModified** [comment]
Ah OK, did not understood that well

**Comment by 304NotModified** [comment]
I see anyway a performance issue, just finishing first tests

**Comment by varunkumarmnnit** [comment]
Hello Julian,
Really appreciate your effort.Did you figure it out what should be done to improve performance .Is there any bug in the code or  this required some config parameter changes .

**Comment by 304NotModified** [comment]
224 secs (10 million, 24sec for 1 million)

```xml
    <targets async="true" >

      <target name="asyncWrapper" xsi:type="AsyncWrapper"   overflowAction="Discard" queueLimit="1000000" batchSize="1000" timeToSleepBetweenBatches="0">
        <target name ="mipLoggertarget" xsi:type="File" fileName="c:/temp/Log/${gdc:item=jobId}/MIP/MipLogger.log" layout="${message}" keepFileOpen="true" />
      </target>
      <!--<target name ="mipLoggertarget" xsi:type="File" fileName="c:/temp/Log/${gdc:item=jobId}/MIP/MipLogger.log" layout="${message}" keepFileOpen="true" />-->

    </targets>
```
----

40 secs (10 million) -  4 secs for 1 milion

```xml
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <configSections>
    <section name="nlog" type="NLog.Config.ConfigSectionHandler, NLog"/>
  </configSections>
  <nlog xmlns="http://nlog-project.org/schemas/NLog.xsd"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <!--<extensions>
      <add assembly ="NLogTest"/>
    </extensions>-->
    <targets async="true" >

      <!--<target name="asyncWrapper" xsi:type="AsyncWrapper"   overflowAction="Discard" queueLimit="1000000" batchSize="1000" timeToSleepBetweenBatches="0">
        <target name ="mipLoggertarget" xsi:type="File" fileName="c:/temp/Log/${gdc:item=jobId}/MIP/MipLogger.log" layout="${message}" keepFileOpen="true" />
      </target>-->
      <target name ="mipLoggertarget" xsi:type="File" fileName="c:/temp/Log/${gdc:item=jobId}/MIP/MipLogger.log" layout="${message}" keepFileOpen="true" />

    </targets>

    <rules>
      <logger name="mipLogger" minlevel="Info" writeTo="mipLoggertarget"/>

    </rules>
  </nlog>

  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5" />
  </startup>
</configuration>
```

**Comment by varunkumarmnnit** [comment]
Hello Julian,
Thanks for your help .But in the second config when u see the log file generated it misses the numbers .I dont want to miss any numbers being generated in the log file .Have u noticed this thing

**Comment by 304NotModified** [comment]
Which numbers?

**Comment by 304NotModified** [comment]
4 sec:
```xml
 <target name ="mipLoggertarget" xsi:type="File" fileName="c:/temp/Log/${gdc:item=jobId}/MIP/MipLogger.log" layout="${message}" keepFileOpen="true" />

```

2 sec:
```xml
 <target name ="mipLoggertarget" xsi:type="File" fileName="c:/temp/Log/fixed/MIP/MipLogger.log" layout="${message}" keepFileOpen="true" />
```

4 sec
```xml
   <target name ="mipLoggertarget" xsi:type="File" fileName="c:/temp/Log/${gdc:item=jobId}/MIP/MipLogger.log" layout="fixed" keepFileOpen="true" />
```

**Comment by varunkumarmnnit** [comment]
Hello Julian.
When u see the code I am writing below  lines in the log file 
MIP : 3903
MIP : 3904
MIP : 3905
MIP : 3906
MIP : 3907
MIP : 3908
MIP : 3909


.Changing the codfig file as u are suggesting will miss the sequence of numbers being generated in the log file .You can yourself check that to confirm .

Thanks and Regards 
Varun

**Comment by 304NotModified** [comment]
Yes, I see it. Its the discard I think. 

The async sets the wrapper automatically with the following values:

```xml
 overflowAction="Discard" queueLimit="10000" batchSize="100" timeToSleepBetweenBatches="50"
```

**Comment by varunkumarmnnit** [comment]
Hello Julian,
Yeas .This could be the reason .I dont want to loose the data and have good performance .Thais what I am looking for .

**Comment by varunkumarmnnit** [comment]
Hello Julian,
Is there any solution for this .

**Comment by 304NotModified** [comment]
Not found yet. Also, I don't get it why

```xml
    <targets >

      <target name="asyncWrapper" xsi:type="AsyncWrapper">
        <target name ="mipLoggertarget" xsi:type="File" fileName="c:/temp/Log/${gdc:item=jobId}/MIP/MipLogger.log" layout="${message}" keepFileOpen="true" />
      </target>

``` 

has different performance/charitics vs

```xml
    <targets async="true" >
      <target name ="mipLoggertarget" xsi:type="File" fileName="c:/temp/Log/${gdc:item=jobId}/MIP/MipLogger.log" layout="${message}" keepFileOpen="true" />
    </targets>
```

It should be the same.

**Comment by varunkumarmnnit** [comment]
Yeah .Thats also one issue

**Comment by 304NotModified** [comment]
8 seconds (instead of 24) - no loss of data:

```xml
    <targets  >

      <target name="asyncWrapper" xsi:type="AsyncWrapper"   overflowAction="Discard" queueLimit="1000000" batchSize="1000" timeToSleepBetweenBatches="50">
        <target name ="mipLoggertarget" xsi:type="File" fileName="c:/temp/Log/${gdc:item=jobId}.log" layout="${message}" keepFileOpen="true" AutoFlush="false" ConcurrentWrites="false" />
      </target>

    </targets>
```

Not super fast yet.

**Comment by 304NotModified** [comment]
Without `CleanupInvalidFileNameChars` in FileTarget, I get it to 5 sec.

**Comment by 304NotModified** [comment]
just write file.writeline 0,5 sec. So still 10 time slower

**Comment by 304NotModified** [comment]
Still testing and looking at performance diagnostics

**Comment by 304NotModified** [comment]
from 3 -> 2 seconds (50%). Replace datetime.now with datetime.utcnow in FileTarget.InitializeFile.

See http://stackoverflow.com/questions/1561791/optimizing-alternatives-to-datetime-now

**Comment by 304NotModified** [comment]
renderedText is still taking some CPU, we should drop that if not needed.

**Comment by 304NotModified** [comment]
Done for today. If I run it with release, I get 10 million records within 10 seconds, with some changes in code and with this config:

```
   <targets  >

      <target name="asyncWrapper" xsi:type="AsyncWrapper"   overflowAction="Grow">
        <target name ="mipLoggertarget" xsi:type="File" fileName="c:/temp/Log/test4.log" layout="${message}" keepFileOpen="true" AutoFlush="false" ConcurrentWrites="false" />
      </target>
    </targets>
    <rules>
      <logger name="mipLogger" minlevel="Info" writeTo="mipLoggertarget"/>
    </rules>
```

So important: ConcurrentWrites + AutoFlush= false , and Async wrapper should not remove messages. Also I used a fixed string for the file name to have a fair comparison. 

Changes in code (only in `FileTarget`)

- disabled `CleanupInvalidFileNameChars`
- replaced 2 `DateTime.Now` with 1 `var now = DateTime.UtcNow;` (`InitializeFile`) - this need some other changes of course. 

Without those 2 changes, it's 34sec.

**Comment by 304NotModified** [comment]
With above changes and writing to file without intermediate byte[] , 7,5 sec. (10 million)

**Comment by 304NotModified** [comment]
> Not found yet. Also, I don't get it why
> 
>     <targets >
> 
>       <target name="asyncWrapper" xsi:type="AsyncWrapper">
>         <target name ="mipLoggertarget" xsi:type="File" fileName="c:/temp/Log/${gdc:item=jobId}/MIP/MipLogger.log" layout="${message}" keepFileOpen="true" />
>       </target>
> has different performance/charitics vs
> 
>     <targets async="true" >
>       <target name ="mipLoggertarget" xsi:type="File" fileName="c:/temp/Log/${gdc:item=jobId}/MIP/MipLogger.log" layout="${message}" keepFileOpen="true" />
>     </targets>
> It should be the same.

The issue is here that we have to write (in `<rules>`) to "asyncWrapper" instead of  "mipLoggertarget". 

> Yeas .This could be the reason .I dont want to loose the data and have good performance

Then you should not use async with Discard. (discard is default for the async attribute).

Last but not least, writing non-async is the best for performance, which is not strange as the test program doesn't do anything besides logging.

**Comment by varunkumarmnnit** [comment]
Hello Julian,
I really appreciate the effort that you have put in which  wull help every other person who are using Nlog.Can you tell how you have done CleanupInvalidFileNameChar .Rest fixes I am not sure whthere apply or not but this could work for every other scenario.

**Comment by 304NotModified** [comment]
I will test the fix this week, and if it is a good improvement, I will release it. :)

**Comment by varunkumarmnnit** [comment]
Hello Julian ,
I have done the changes in the config file as suggested by you and I am seeing some improvement in the running time .But Not done any code changes as I am confused in that .

**Comment by 304NotModified** [comment]
I will make within a few days a new branch so you can test it.

**Comment by 304NotModified** [comment]
@varunkumarmnnit 

if you like to test: https://github.com/NLog/NLog/tree/4.2.3. It has fixes for both bottlenecks. 
It builds (and unit tests are succeeding): https://ci.appveyor.com/project/nlog/nlog/build/4.0.1345
I didn't test the performance yet.

It would be great if you can give some feedback on this change :)

**Comment by varunkumarmnnit** [comment]
Hello Julian,
Thanks for your comment .I am using the following configuration 
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <configSections>
    <section name="nlog" type="NLog.Config.ConfigSectionHandler, NLog"/>
  </configSections>
  <nlog xmlns="http://nlog-project.org/schemas/NLog.xsd"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <extensions>
        <add assembly ="NLogTest"/>
    </extensions>
    <targets>      
      <target name="asyncWrapper" xsi:type="AsyncWrapper"   overflowAction="Grow" >  
        <target name ="mipLoggertarget" xsi:type="File" fileName="D:/Log/${gdc:item=jobId}/MIP/MipLogger.log" layout="${message}" keepFileOpen="true" AutoFlush="false" ConcurrentWrites="false"/>
       </target> 
   </targets>
    <rules>
      <logger name="mipLogger" minlevel="Info" writeTo="mipLoggertarget"/>
      
    </rules>
  </nlog>

And I am unsig the Nlog  and after compiling the  NLog.netfx45 ,I am ussing the below Nlog Lib 
\NLog-4.2.3\NLog-4.2.3\build\bin\Debug\.NET Framework 4.5\NLog.dll in my test program .I am generating 1.47 GB file .Below is the timing I am getting 
 717894 ms .I feel its still slow .
Are you sure your fix  will work or am I doing something wrong in my testing 

Thanks and Regards 
Varun

**Comment by 304NotModified** [comment]
To get it faster:

- Use a release build
- Don't use async writing. (well the asyncWrapper isn't used in your example)
- Templating the fileName is taking some resource. Maybe you can set it from the API? 
```c#
  LogManager.Configuration.FindTargetByName<FileTarget>("mipLoggertarget").FileName = @"c:\temp\somewhere.log";
```

**Comment by 304NotModified** [comment]
I will test this also this week. It should be ~10 sec for 10 million rows. If not, then I will add an option to disable the "clearFileName"

**Comment by varunkumarmnnit** [comment]
Hello Julian ,
I have done the last two changes suggested by you .But  I am not seeing any significance improvement .May be I am doing something wrong .Anyways you test also by yourself and let me confirm the result .I will officilay download the Nuget once things get working .

Thanks and Regards 
Varun

**Comment by 304NotModified** [comment]
Hi, 

I did tested the test program. I took 22 sec for 10 million messages. That was not enough. I updated 4.2.3 with a filename cache (works only if the filename is a fixed string! So no `$...`). Now I get < 10 sec for 10 million rows.

![image](https://cloud.githubusercontent.com/assets/5808377/11642249/28a6f4f2-9d3d-11e5-9af0-1e541cf23f21.png)

I tested it with the following config:

```xml
    <targets>
      <target name ="mipLoggertarget" xsi:type="File" fileName="c:/temp/Log/test10.log" layout="${message}" keepFileOpen="true" AutoFlush="false" ConcurrentWrites="false" />

    </targets>
    <rules>
      <logger name="mipLogger" minlevel="Info" writeTo="mipLoggertarget"/>

    </rules>

```

If you view the whole test program I use, it is in the (1071-test-program-diag-tryouts branch)[https://github.com/NLog/NLog/tree/1071-test-program-diag-tryouts]. (project PerformanceTest).

NB: In DEBUG  it's a lot slower!

PS I test with the following stack:
- .Net 4.5
- Windows x64
- VS 2015 RTM
- Core i7 5500U (laptop i7)
- 16 GB ram (but CPU is bottleneck)
- SSD (and not a good one, thanks to Dell)

**Comment by varunkumarmnnit** [comment]
Hello Julian ,
I myslef has verified teh result and its working as you have told but performance is lot depending on the filename is fixed or not .Is there any way that that i can speed up the thing with the way i have written the file name above.The thing that I have written in above way as my folder name known based on some certain id .that the reason i have mentioned file name as above

**Comment by varunkumarmnnit** [comment]
Hello Julian ,
I have observed the fix that u have suggested really improves timing when filename is fixed otherwise its degrading the performance .You can also check if you want.

**Comment by 304NotModified** [comment]
Can't you set the filename from the api (as shown above)?

**Comment by varunkumarmnnit** [comment]
I did i will try again but havnt got improvement.In fact with your new changes its worsening the result if the file name is not fixed .U can also verify at ur end to avoid any mistake from my side .

**Comment by 304NotModified** [comment]
I will test that also this week. 

Anyway, fixed file name will be always faster. 

Van you tell me why you need a log file of millions of lines?

**Comment by varunkumarmnnit** [comment]
I am working on a project that can generated this much such of file.Thats why i am testing

**Comment by varunkumarmnnit** [comment]
Hello Julian,
Any update on the testing result .

**Comment by 304NotModified** [comment]
Not yet. Will test this weekend.

**Comment by 304NotModified** [comment]
Hey Varun,

I timed 50 seconds for 10 million records with:

```
  fileName="c:/temp/Log/gdc1_${gdc:item=jobId}.log" 
```

I added the option `CleanupFileName`, so you can skip this option for performance reason. Also I did a small tweak in the GDC.

Now with the following config:

```xml
    <targets>
      <target name ="mipLoggertarget" xsi:type="File" 
              fileName="c:/temp/Log/gdc1_${gdc:item=jobId}.log" 
              layout="${message}" keepFileOpen="true" AutoFlush="false" 
              ConcurrentWrites="false"
              CleanupFileName="false"/>

    </targets>
    <rules>
      <logger name="mipLogger" minlevel="Info" writeTo="mipLoggertarget"/>

    </rules>
```

I will be take 15 seconds (10 million messages). Commited to [4.2.3](https://github.com/NLog/NLog/tree/4.2.3).

Please test in your environment. If it's good enough, I will release it. I don't think we can get it faster than this without a big change.

**Comment by 304NotModified** [comment]
@varunkumarmnnit do you have time to validate my results?

I will improve the testprogram for the future, but for now it's funny that sync writing is faster then async.

With the fixed name, i'm happy with the results with sync writing+fixed name. 

![image](https://cloud.githubusercontent.com/assets/5808377/11827295/471119aa-a38b-11e5-87ca-a73dde1f7084.png)

But there should be some improvement done with `ConcurrentWrites="true` and `async`. We will looks at that in the future.

**Comment by varunkumarmnnit** [comment]
Hello Julian 
Apart from above config changes do I need to use your fixed files also

**Comment by 304NotModified** [comment]
I think you need `  LogManager.Flush();`

My testprogram: https://github.com/NLog/NLog/blob/1071-test-program-diag-tryouts/src/PerformanceTest/Program.cs

**Comment by 304NotModified** [comment]
It checked the content of the file, it is all present. 

With the GDC item in the path:

![image](https://cloud.githubusercontent.com/assets/5808377/11881821/7f17e46c-a509-11e5-9691-5af5fe2f4372.png)

**Comment by 304NotModified** [comment]
4.2.3 has been released.

**Comment by stephenpatten** [comment]
Has all the work that was done here been moved to https://github.com/NLog/NLog-Performance-tests? If so, then the settings that I would find in the configs are for ultimate throughput

**Comment by 304NotModified** [comment]
Yes, although there has been some changes in the  performance test repo

**Comment by stephenpatten** [comment]
Changes for the good, right?
