### ISSUE TITLE
Fire NLog event

### ISSUE THREAD

**Issue by GClaudio** [NLog/NLog#1072]
Hello to all,
this isn't an issue but an help request.
I need to activet Nlog event, to intercept when it writes an error or a trace or an info (any level action), but i don't know how do it.
Is the LogEventInfo the class to use ? I watched into forum, but i didn't find anything (or better i didn't understand very well).
Could You help me or send me a bit of sample code, please ? 
Thank's very much
Regards Claudio

**Comment by 304NotModified** [comment]
Hey! 

Please check the tutorial: https://github.com/NLog/NLog/wiki/Tutorial

No need to create an instance of logeventinfo. 

If you have further questions, let me know.

**Comment by GClaudio** [comment]
Hi Julian,
thank's for your answer, but I didn't find the statement or a sample for my purpose (or I didn't understand); I would need to handle the following scenario:

NLog_common_Class
public Logger LOG = LogManager.GetCurrentClassLogger();
public User {get;set;}
Public Log event()
{
If (this.User ==' Iron')
	Log.Info(……)
}

I need to fire the Nlog event in the common class, used from other applications, but not all user of application(s) will be able to write or not the NLog target.
Could You Help me, please?
Thank You very much
Regards      (I hope that you understand my English).

**Comment by 304NotModified** [comment]
So you like to log only for a particular user?

I think the above code should work then? Or is `event()` not called?

**Comment by GClaudio** [comment]
Ok, 
but i implemented a Dll with NLOG (wreppered), used from some applications, i don't want to check the user setups in every applicatiion, i would like to check it only in my Nlog dll, but  i don't know (if it's possible) to trap the nlog event (in my dll).
Thank's

**Comment by 304NotModified** [comment]
I think you like to filter messages dependent on which user has been logged in. 

Is it a web application (asp.net  / asp.net mvc)? 

Then you can filter the calls in the nlog.config. You need then [nlog.web](https://www.nuget.org/packages/NLog.Web package) also

- https://github.com/NLog/NLog/wiki/When-filter
- https://github.com/NLog/NLog/wiki/AspNetUserIdentity-Layout-Renderer


e.g. 

```xml
<rules>
  <logger writeto="your_target" >
    <filters>
      <when condition="${aspnet-user-identity} != 'Iron'" action="Ignore"/>
    </filters>
  </logger>
</rules>
```

**Comment by GClaudio** [comment]
Really my applications are Windows Forms, but it would be a good idea the filter messages, is it available for Windows Forms ? Or, a better solution, could be crate a filter like as:
condition=<when condition=${myVariable} != true" action="Ignore"/>
what do you think about this possibility ?


P.S. Is it possible to show a messagebox with Nlog when an error occurs ?

Thank's

**Comment by GClaudio** [comment]
HI Julian,
I resolved the NLOG messagebox with Nlog.Windows.Forms package.

For the other problem, is it possible to create a filter like as:
condition ="${myvariable} != True action = "Ignore"    (?)

Thank's

**Comment by 304NotModified** [comment]
Yes, you can use:

[`${windows-identity}` ](https://github.com/NLog/NLog/wiki/Layout-Renderers)

See https://github.com/NLog/NLog/wiki/When-filter

PS: please post you code between backticks, see the your posts I have edited before.

**Comment by 304NotModified** [comment]
@GClaudio does it work?

**Comment by GClaudio** [comment]
Sorry, but I couldn't try it these days, next week I will be send you an answer

**Comment by GClaudio** [comment]
OK, it's work
thank you
Happy New Year

**Comment by 304NotModified** [comment]
Thanks for the feedback! 

Happy new year!
