### ISSUE TITLE
async attribute is different behaving vs async wrapper

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#1073]
As seen in https://github.com/NLog/NLog/issues/1071:

```xml
    <targets >
      <target name="asyncWrapper" xsi:type="AsyncWrapper">
        <target name ="t1" xsi:type="File"
                    fileName="c:/temp/test.log" layout="${message}"
                    keepFileOpen="true" />
      </target>
``` 

Has different behavior vs 

```xml
    <targets async="true" >
      <target name ="t1" xsi:type="File" 
                  fileName="c:/temp/test.log"
                  keepFileOpen="true" />
    </targets>
```

With many writes the attribute version loses faster the messages. (looks wrong)

The properties set on the FileTarget and AsyncWrapper are the same (checked with debugger).

There is one difference, the aync attribute is calling `InitializeTarget` first on `FileTarget` and then the `AsyncTargetWrapper`. The wrapper calls first on `AsyncTargetWrapper` and after the the `FileTarget`

With 10.000.000 writes, we get with the attribute version very soon:
```
2015-12-05 02:03:32.7568 Debug Async queue is full
2015-12-05 02:03:32.7568 Debug Discarding one element from queue

```

This is not the case with the wrapper

**Comment by 304NotModified** [comment]
Differences in init log and rules:

![image](https://cloud.githubusercontent.com/assets/5808377/11605118/a220c49a-9af7-11e5-874e-c98ccbb5fb0e.png)

**Comment by 304NotModified** [comment]
it looks like `AsyncWrapper.Write()` is never called when using the wrapper version...

**Comment by 304NotModified** [comment]
It's late. With the wrapper we should edit the logger rule of course...

**Comment by 304NotModified** [comment]
I will retest it, and close it probably

**Comment by 304NotModified** [comment]
This was a (common) config mistake.

**Comment by elandau1260** [comment]
Hi.   I am having a "Async queue is full" issue. I've tried "Async=true" and the wrapper.  I don't really understand what you are saying above. Can you explain it a little?  I believe I have the same issue but can't see how to solve.  right now I am using this:

   	<target name="asyncWrapper" xsi:Type="AsyncWrapper" queueLimit="200000">
            <target name="LogFile"
                xsi:type="File"
                fileName="C:\QRT\Logs\QRTLog-${shortdate}.log"
                layout="${date:format=yyyy-MM-dd HH\:mm\:ss.fff}|${level}|${threadid}|${threadname}|${event-properties:item=FromID}|${message}${exception:format=tostring} "
                concurrentWrites="true" />
       </target>

Any help would be greatly appreciated!

**Comment by 304NotModified** [comment]
Yeah the notes were more intended for internal use. 

So summarize: the `async=true` is a shorthand for the async-wrapper. With the async-wrapper you can set multiple options, like the queuelimit. 

So in your case you need the wrapper. If you never want to loose any message, set the `overflowAction=` on `Block` (costs memory) or `Grow` (costs CPU). But if you need this with a queue of `200000`, then you are writing a lot in a short time! 

Can you also post the `<rules>` section of your config to double check?

**Comment by mshibani7** [comment]
hi, wee are using nlog with async attribute to true for the file target. from last few day, we have been noticing issue to database logging. attaching the nlog config below. file logging is working good, but seeing database logging issue. so the issue is we dont see any logging to database, it gets stopped until we restart the service. Can you please help?

 <nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" throwExceptions="true" internalLogFile="D:/ThomsonReuters/imint/log/nlog_internal.txt" internalLogLevel="Error" internalLogIncludeTimestamp="true">
    
    <extensions>
      <add assembly="SmfTarget"/>
    </extensions>

   <targets async="true">
        
        <target name="file" xsi:type="File"
                fileName="D:/ThomsonReuters/imint/log/Imintservice_${shortdate}.txt"
                archiveFileName="D:/Thomsonreuters/imint/log/Imintservice_${shortdate}_{#}.txt"
                archiveAboveSize="50000000"
                archiveEvery="Day"
                archiveNumbering="Rolling"
                maxArchiveFiles="30"
                concurrentWrites="false"
                keepFileOpen="false"
                encoding="iso-8859-2"
                layout="${longdate}|${level:uppercase=true}|${logger}|${event-context:item=RssGroup}|${message}}|${exception:format=tostring:maxInnerExceptionLevel=3}" />
       <target name="database" xsi:type="Database"
                      connectionStringName="IMINTConnection">
               <commandText>
                 EXEC [dbo].[imintInsertRSSLog] @rssGroup, @moduleName, @severity, @detail, @isSummary
               </commandText>
               <parameter name="@rssGroup" layout="${event-context:item=RssGroup}"/>
               <parameter name="@moduleName" layout="${logger}"/>
               <parameter name="@severity" layout="${level:uppercase=true}"/>
               <parameter name="@detail" layout="${message}"/>
               <parameter name="@isSummary" layout="${event-context:item=IsSummary}"/>
        </target>
        
        <target name="smf" type="SMF" host="localhost" port="8603" queueSize="5000" logFileName="D:\ThomsonReuters\IMINT\log\imintsvc_smf.log"
                applicationName="xvs-imint"
                layout="${message}|${exception:format=tostring}" />
      </targets>
      <rules>
        <logger name="imintlog" minlevel="Debug" writeTo="file" />
        <logger name="imintlog.db" minlevel="Info" writeTo="database" />
        <logger name="imintlog.smf" minlevel="Error" writeTo="smf" />
      </rules>
  </nlog>

**Comment by 304NotModified** [comment]
Please check the internal log first. https://github.com/nlog/nlog/wiki/Internal-logging

**Comment by mshibani7** [comment]
we have enabled internal logging but dont see any error and exception there on the day/time it happens

**Comment by mshibani7** [comment]
Does anyone has faced similar issue?

**Comment by 304NotModified** [comment]
Please create an new Github issue and fill in the template.
