### ISSUE TITLE
Log unused targets to internal logger

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#1074]
When using xml configuration, (maybe also non xml),  log a warning or info for targets that aren't used in the rules.  

This is useful for detecting miscongurations, like forgetting the asyncwrapper. See https://github.com/NLog/NLog/issues/1073, https://github.com/NLog/NLog/issues/1071 and https://github.com/NLog/NLog/issues/865

We should do this efficient, so use a dictionary or hashset.

**Comment by UgurAldanmaz** [comment]
Targets adding to the related `LogginRule` class instance. Every `LogginRule` instance is adding to the `LoggingRules` property of the `LoggingConfiguration` class.

We should check the `LoggingRules` property I guess.

> We should do this efficient, so use a dictionary or hashset.

Where do we should use dictionary or hashset? In the `LoggingRule` class?

Do you mean [there] (https://github.com/NLog/NLog/blob/master/src/NLog/Config/LoggingRule.cs#L112).

**Comment by 304NotModified** [comment]
> We should check the LoggingRules property I guess.

Yes I think also



> Where do we should use dictionary or hashset? In the LoggingRule class?

I think: loops over targets and then check the rules. The "check the rules" should be efficient, so we have built a dictionary or hashset first. (I think `hashset<string>` from the rules which contains the target names)

**Comment by UgurAldanmaz** [comment]
While checking (in the method scope) or create a new class?
