### ISSUE TITLE
FileTarget write async

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#1076]
We can run the `FileTarget` in a async wrapper, but the messages aren't written async to the file. 

E.g. we should use `StreamWriter.WriteLineAsync`. This can be a major change, as all methods should be `async` then. (write, log etc)

**Comment by snakefoot** [comment]
By default when writing to a filestream, then one is writing directly into Windows File Cache. Thus memory to memory, and then Windows File Cache can decide when to perform the actual disk write.

**Comment by 304NotModified** [comment]
No plans for now in improving this. File logging is blazing fast ATM
