### ISSUE TITLE
Documentation improvings for Thread and Async Writing in general

### ISSUE THREAD

**Issue by UgurAldanmaz** [NLog/NLog#1078]
Subjects:
* AsyncTargetWrapper
* How should be Target and Rule configrations
* AspNetTrace target
* Performance suggestions (?)

Related issues: https://github.com/NLog/NLog/issues/865, https://github.com/NLog/NLog/issues/1073, https://github.com/NLog/NLog/issues/1071, https://github.com/NLog/NLog/issues/1074

**Comment by 304NotModified** [comment]
We could write a news post on it? (for nlog-project.org), and then include it in the wiki

**Comment by UgurAldanmaz** [comment]
Why news? For feature development?

**Comment by 304NotModified** [comment]
Well more a "blog post" then.

**Comment by 304NotModified** [comment]
This wiki has been updated
