### ISSUE TITLE
NLog.Config and NLog.Schema packages don't work as expected with Nuget 3 (Visual Studio 2015)

### ISSUE THREAD

**Issue by dls314** [NLog/NLog#1080]
Hi,

When I install NLog.Config 4.2.2 and/or NLog.Schema 4.2.1 into a DNX project, the content (NLog.config or NLog.xsd) isn't copied into the project.

I think this is fixable with a nuspec that targets nuget 3.3 using the nuget content v2 (contentFiles) nuspec element.

http://docs.nuget.org/create/nuspec-reference#contentfiles-with-visual-studio-2015-update-1-and-later

I'm sure the issue is a known thing.
Am I right that this is causing my issue?
Any plans to fix?

**Comment by 304NotModified** [comment]
Thanks for reporting.  

So you know if the package is still nuget 2.8 compatible? Or do we have create a new (separate) package?

**Comment by dls314159** [comment]
Having read some more about nuget 3.3, I'm not even sure it's a good answer.
http://blog.nuget.org/20151118/nuget-3.3.html

It sounds like there's no model yet for not-immutable content.

**Comment by 304NotModified** [comment]
I think it should work with buildaction =none and copyToOutput=true. 

Can you tests that for us? (you can configure a local folder in visual studio) . Otherwise I will look at this,  probably this weekend or next week

**Comment by 304NotModified** [comment]
I think the nuspec for NLog.Config should be:

```xml
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2011/08/nuspec.xsd">
  <metadata>
    <id>NLog.Config</id>
    <version>4.2.2</version>
    <title>NLog Configuration</title>
    <authors>Kim Christensen,Julian Verdurmen</authors>
    <owners>Kim Christensen</owners>
    <licenseUrl>http://raw.github.com/NLog/NLog/master/LICENSE.txt</licenseUrl>
    <projectUrl>http://nlog-project.org/</projectUrl>
    <iconUrl>http://nlog-project.org/NConfig.png</iconUrl>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>Empty NLog.config file.</description>
    <summary>Empty NLog.config file for use with NLog.</summary>
    <releaseNotes>NLog 4.2.2</releaseNotes>
    <language>en-US</language>
    <tags>nlog xml config</tags>
    <dependencies>
      <dependency id="NLog" version="4.2.2" />
      <dependency id="NLog.Schema" version="4.0" />
    </dependencies>
    <contentFiles>
      <files include="content\NLog.config" buildAction="None" copyToOutput="true" flatten="true" />
    </contentFiles>
  </metadata>
  <files>
    <file src="content\NLog.config" target="content\NLog.config" />
    <file src="tools\Install.ps1" target="tools\Install.ps1" />
  </files>

</package>
```

See attachment nuspec and nupkg.

**Comment by 304NotModified** [comment]
This seems to be fixed at nuget. The same package won't give any errors now.

See https://www.nuget.org/packages/NLog.Config/4.2.3.1

@dls314159 can you confirm this package is working with DNX? Then I will also publsh the NLog.schema. Thanks in advance

**Comment by dls314159** [comment]
I don't think it's working--at least not in a useful way--in DNX style projects.
I'm not sure I can explain, but I'll try!

I have two goals when I include the NLog.Config package in my project as a dependency:
1. Get a template NLog.Config file that I can modify.
2. Have that NLog.Config file put somewhere useful so that I can modify it and have it work with my current project.

The first goal is satisfied now in the same way it was when I noted the issue. DNU restore puts the NLog.Config file at a path like this one:

    C:\Users\dave\.dnx\packages\NLog.Config\4.2.3.1\content\NLog.Config

But not so much for the second goal since that path is just my local package cache.

**Comment by dls314159** [comment]
I think the lacking feature in Nuget is best being tracked by this issue:

    https://github.com/NuGet/Home/issues/1792

**Comment by 304NotModified** [comment]
Thanks for testing @dls314159 !

I unlisted the package. Saving it too the package cache isn't useful. 

Will try to fix it when I know the solution.

**Comment by dls314159** [comment]
I've abandoned using the NLog.Config file in DNX style projects because of this issue:
https://github.com/NLog/NLog/issues/1091

So the NLog.Config package hasn't been a problem :-)

**Comment by 304NotModified** [comment]
Yeah we hoping to release DNX support within 1-2 months. See #1160

**Comment by 304NotModified** [comment]
I see Nuget has updated the docs. 

https://docs.nuget.org/create/nuspec-reference#contentfiles-with-visual-studio-2015-update-1-and-later

I think I need 2 times `any` added

**Comment by 304NotModified** [comment]
Will close this as this is a known issue as it's polluting the issue list - there is no action for us here.
