### ISSUE TITLE
How to get database id of inserted log statement?

### ISSUE THREAD

**Issue by proxteam** [NLog/NLog#1085]
I have configured nlog to log errors into a database table. I would like to get the id of the log record from the database. How could I achieve this?
Thx.

**Comment by 304NotModified** [comment]
You can use `@@IDENTITY` (SQL server) in your command, but you can't do anything with it.

**Comment by proxteam** [comment]
I cannot retrieve the @@IDENTITY value from the database? I need to show the @@IDENTITY value to the user.

**Comment by UgurAldanmaz** [comment]
Are you trying something like log monitoring?
What is your scenario? Such as, log something and show it to the user immediatly or just monitor the logs from database at anytime?
Who is the user? Operator, end user or another?

Could you give some more detail?

**Comment by proxteam** [comment]
When an exception occurs in my mvc application it logs the exception message into a database table using nlog. I would like to show a message to the user like "An error occured. Contact system administrator and pass log id @@IDENTITY", such that the id of the log message that has been just inserted into the log table is displayed to the user.

**Comment by 304NotModified** [comment]
Too bad this isn't possible yet. You can add a feature request to https://nlog.userecho.com

**Comment by rellis-of-rhindleton** [comment]
You could define another logging target that only catches errors like this, so it's easy for an admin to look them up by user & approximate time without knowing an exact ID.  That's the approach I would take.

Another option would be to make your own unique ID (a new GUID maybe) and add it to the log event as a property (saving the property in the table along with everything else).  It'd go unused/empty most of the time, but for a case like this it would serve as your own ready-made ID that you already know, without needing to add functionality to the logging framework.  Adding a feature to access a stored procedure's return value (the inserted identity in this case) would be cleaner, certainly, but this is something you can do now.

**Comment by 304NotModified** [comment]
I think this question has been answered, so closing this one. If you have more questions, just let us know.
