### ISSUE TITLE
4.2.2 assembly versioning issue

### ISSUE THREAD

**Issue by chrisrestall** [NLog/NLog#1087]
Just updated NLog via nuget to 4.2.2 and am now getting warnings during compilation about a conflict with NLog 4.0.0.0.  My application also will not run.  Here is the snippet from my build log:

There was a conflict between "NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c" and "NLog, Version=4.2.2.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c". (TaskId:12)
      "NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c" was chosen because it was primary and "NLog, Version=4.2.2.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c" was not. (TaskId:12)
      References which depend on "NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c" [C:\Projects\myProject\trunk\Blocks\API\Source\packages\NLog.4.2.2\lib\net45\NLog.dll]. (TaskId:12)
          C:\Projects\myProject\trunk\Blocks\API\Source\packages\NLog.4.2.2\lib\net45\NLog.dll (TaskId:12)
           Project file item includes which caused reference "C:\Projects\myProject\trunk\Blocks\API\Source\packages\NLog.4.2.2\lib\net45\NLog.dll". (TaskId:12)
             NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c, processorArchitecture=MSIL (TaskId:12)
      References which depend on "NLog, Version=4.2.2.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c" []. (TaskId:12)
          C:\Projects\myProject\trunk\Blocks\API\Source\proj_models \bin\Debug\proj_models.dll (TaskId:12)
           Project file item includes which caused reference "C:\Projects\myProject\trunk\Blocks\API\Source\proj_models \bin\Debug\proj_models.dll". (TaskId:12)
              C:\Projects\myProject\trunk\Blocks\API\Source\proj_models \bin\Debug\proj_models.dll (TaskId:12)
          C:\Projects\myProject\trunk\Blocks\API\Source\proj_model2\bin\Debug\proj_model2.dll (TaskId:12)
            Project file item includes which caused reference "C:\Projects\myProject\trunk\Blocks\API\Source\proj_model2\bin\Debug\proj_model2.dll". (TaskId:12)
              C:\Projects\myProject\trunk\Blocks\API\Source\proj_model2\bin\Debug\proj_model2.dll (TaskId:12)
              C:\Projects\myProject\trunk\Blocks\API\Source\proj_models\bin\Debug\proj_models.dll (TaskId:12)

I have no references to NLog 4.0.0.0 but it looks like when you add a reference to the new 4.2.2 the version is 4.0.0?  I'm seeing that in the property window for the nLog 4.2.2. dll and in the build og above.  This causes the following issue when I run my app:

Could not load file or assembly 'NLog' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) 

I have set up a assemblyBinding in my config:

  assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1" 
			dependentAssembly
				assemblyIdentity name="NLog" publicKeyToken="5120E14C03D0593C" culture="neutral" 
				bindingRedirect oldVersion="0.0.0.0-4.2.2.0" newVersion="4.2.2.0" 
			/dependentAssembly

and I can see that it attempts to map to the newVersion, however I still get the exception.  I noticed on 4.1, the version of the assembly was 4.1.  Not sure why it's adding with 4.0.0.0 from nuget now?

**Comment by 304NotModified** [comment]
Hi, 

From which version are you upgrading? 

Please test with newversion=4.0.0.0 (and same old version) in your config. That should solve it. 

The assembly version of 4.2.2 is still 4.0.0.0. That has a good reason. But first resolve your issue and then I can tell about it :)

**Comment by chrisrestall** [comment]
I upgraded from 4.1.0.  Here is what the old reference looke dlike:

 Reference Include="NLog, Version=4.1.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c, processorArchitecture=MSIL"
      HintPath>..\packages\NLog.4.1.0\lib\net45\NLog.dll HintPath
      Private>True</Private
    /Reference

The new reference looks like this:

  Reference Include="NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c, processorArchitecture=MSIL"
      HintPath>..\packages\NLog.4.2.2\lib\net45\NLog.dll HintPath
    /Reference

**Comment by 304NotModified** [comment]
Yes this is a know issue of 4.1.0. 

Your assembly binding config is wrong. You should change it (change the newversion) .

**Comment by 304NotModified** [comment]
related https://github.com/NLog/NLog/issues/921

**Comment by 304NotModified** [comment]
See for more detail: http://nlog-project.org/2015/09/12/nlog-4-1-1-has-been-released.html

**Comment by chrisrestall** [comment]
Thank you!  After reading through these I've confirmed I'm not insane :)  I'll give this a try as soon as I get to my workstation.  Appreciate the quick response.
Chris

**Comment by 304NotModified** [comment]
I added the issue to the FAQ: https://github.com/NLog/NLog/blob/master/README.md#frequently-asked-questions-faq

Please let us know if you get it working or if you need further assistance!

**Comment by 304NotModified** [comment]
Any luck @chrisrestall ?

**Comment by chrisrestall** [comment]
Sorry, yes adjusting assembly binding worked great.  Thanks!

Sent from Outlook




On Thu, Dec 17, 2015 at 1:03 PM -0800, "Julian Verdurmen" <notifications@github.com> wrote:





Any luck @chrisrestall ?

---

**Comment by 304NotModified** [comment]
OK glad to hear!
