### ISSUE TITLE
I just lose the log when i use NLog 

### ISSUE THREAD

**Issue by a14907** [NLog/NLog#1088]
The code is in a console application.
code is simple :

            for (int i = 0; i < 26130; i++)
            {
                NLog.LogManager.GetLogger("mylog").Debug(i.ToString());
            }

the config setting :
1.

```xml 
<target name="f" xsi:type="File" fileName="${basedir}/log/${logger}/${shortdate}.log"
                  layout="${longdate} ${callsite}  ${uppercase:${level}} ${message}"  />
  </targets>
```

2.
```xml
<default-wrapper xsi:type="AsyncWrapper">  
      <wrapper-target xsi:type="RetryingWrapper"/>  
    </default-wrapper>  
    <target name="f" xsi:type="File" fileName="${basedir}/log/${logger}/${shortdate}.log"
                  layout="${longdate} ${callsite}  ${uppercase:${level}} ${message}"  />
  </targets>
```

There is no problem in the first ,I get all 26130 log message,with a file size:1.58MB
But in the second ,I just get a log file with the size of :687KB....
I really confused about that . Can anybody tell me why?

**Comment by 304NotModified** [comment]
That is expected behaviour.  The async wrapper will discard messages (configurable) when you write faster than it can handle. Writing only log messages I a for loop is of course not a real case you would use in practice.  

Please check the internal log (set internal log level on trace) and see the docs of async wrapper.

**Comment by a14907** [comment]
I did not expect it so. Why it can not record all the information?

**Comment by 304NotModified** [comment]
Please read https://github.com/NLog/NLog/wiki/AsyncWrapper-target

**Comment by 304NotModified** [comment]
Is everything clear now @a14907 ?

**Comment by a14907** [comment]
Yes

**Comment by a14907** [comment]
Yes.@304NotModified

**Comment by 304NotModified** [comment]
OK, I will close this one then :)
