### ISSUE TITLE
Autoloading assemblies doesn't work with .NET Core

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#1091]
Internal log:

```
2015-12-15 09:56:50.1268 Debug ScanAssembly('NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c')
2015-12-15 09:56:50.1629 Debug Start auto loading, location: C:\Users\{user}\.dnx\packages\NLog\4.2.2\lib\net45
2015-12-15 09:56:50.1629 Debug Auto loading done
```

The location is wrong "C:\Users{user}.dnx\packages\NLog\4.2.2\lib\net45", so it won't find the other packages.

From: https://github.com/NLog/NLog/issues/767

related #641

**Comment by phenixdotnet** [comment]
Hi.
The paths management in ASP.NET has been changed and we must adapt the way we retrieve the paths.
I will have a look at this as part of the work on dnx/coreclr work.
The best approach is to use
```csharp
var platformService = PlatformServices.Default;
if (platformService == null)
{
     throw new Exception("Unable to get the platform service !");
}
platformService.Application.ApplicationBasePath
```

but it's only suitable for dnx/coreclr

**Comment by 304NotModified** [comment]
Thanks for the info @phenixdotnet !

To fix it for CoreCLR doesn't sound like a problem. But how do we now that we are using DNX? Dnx is also possible with .net45?

**Comment by phenixdotnet** [comment]
Yes, you can use the dnxcore lib in your .NET 4.5 project but, today, it's not working (no error but the config doesn't seem to be loaded). You can have a look at the examples added in coreCLR branch

For this issue the project is running ASP.NET 5 so I think it also use dnx. This is why the path is wrong and why we can use the PlatformServices class.

**Comment by 304NotModified** [comment]
party fixed by https://github.com/NLog/NLog/pull/1356?

**Comment by 304NotModified** [comment]
helpful link: http://shazwazza.com/post/custom-assembly-loading-with-aspnet-core/

**Comment by snakefoot** [comment]
@304NotModified Think this can be resolved with the release of NLog 5.0 BETA7

**Comment by 304NotModified** [comment]
have you tested this one? Not sure if it's works as the directory layout of .NET core application is different (not one bin folder). AFAIK we needed another API / library for it.

**Comment by snakefoot** [comment]
@304NotModified I'm guessing that if it scans the directory where the NLog.dll is placed, then it is in pretty good shape to find any other assemblies placed next to the NLog.dll.

**Comment by 304NotModified** [comment]
All the DLLs are in different folders ;)

**Comment by 304NotModified** [comment]
Folder per nuget package as far as I remember

**Comment by 304NotModified** [comment]
I looked at this, but can't find `Microsoft.Extensions.PlatformAbstractions.IAssemblyLoader`  /`DefaultAssemblyProvider`  any more (from https://shazwazza.com/post/custom-assembly-loading-with-aspnet-core/)

**Comment by ericnewton76** [comment]
I just caught this issue and wondering if NLog AppBuilder like concept proposed in #2334 helps here too?

**Comment by snakefoot** [comment]
@ericnewton76 It is already possible to register custom NLog-extensions-dlls manually:

`NLog.Config.ConfigurationItemFactory.Default.RegisterItemsFromAssembly(typeof(NLog.CustomExtension).GetTypeInfo().Assembly);`

This issue is about it is no longer possible for NLog to do it automatically, because Nuget-packages behaves differently.

**Comment by snakefoot** [comment]
Think this issue has been partially resolved by: #2493 (And #2497 + #2519)

When using nuget-packages, then references are automatically added, and then one can just scan the loaded assemblies for any NLog-extension-dlls.

NetCore is now also able to scan for NLog-extension-dlls in the current basedirectory, and load these automatically. Resolved by #2431

**Comment by snakefoot** [comment]
Another direction could be to stop autoloading assembly, but only load those explicitly specified in nlog.config. This would also make NLog less promiscuous to security attacks.

See also #3674 that trieds to fix the performance overhead from scanning and loading assemblies, which hurts startup performances when using NLog in Azure Functions or AWS Lambdas.

**Comment by 304NotModified** [comment]
> Another direction could be to stop autoloading assembly, but only load those explicitly specified in nlog.config.

I think that's a good idea. Still I prefer "trying" to reload the NLog officials but remove the autoload is a good approach for NLog 5.
