### ISSUE TITLE
Unit test and cleanup FileTarget.GetFileAppenderFactory

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#1093]
Write unit tests and cleanup `FileTarget.GetFileAppenderFactory` (code duplication in conditionals)

**Comment by snakefoot** [comment]
Think we have lots of unit tests, and the method is looking cleaner. Probably going to be removed completely with NLog ver. 6

**Comment by 304NotModified** [comment]
Don't think this is really important.
