### ISSUE TITLE
Max message length option for Eventlog target

### ISSUE THREAD

**Issue by UgurAldanmaz** [NLog/NLog#1102]
Default value should be 16,384 for backwards-compatible. It can be changed in NLog v5. However, there are [various message length limit that depends on the OS.](https://support.microsoft.com/en-us/kb/957662 "Recommended settings for event log sizes in Windows") Therefore, should be careful for changing the default.

**Comment by 304NotModified** [comment]
I think configurable is the best solution, backwards compatible and easy to implement.

**Comment by UgurAldanmaz** [comment]
Closed because of merged #1127
