### ISSUE TITLE
Include File in Remote locations

### ISSUE THREAD

**Issue by paddyhamilton** [NLog/NLog#1106]
Guys, 

I want to be able to control the NLog.config file from a central location, in this case an AWS s3 bucket.

Is it possible to configure include files to look in remote locations at all?

Thanks,

Paddy

**Comment by 304NotModified** [comment]
Can you give an example of a remote location? We do support network shares, but not sure if that's what you need.

**Comment by paddyhamilton** [comment]
An Amazon AWS bucket.  So the file location will be for example "https://s3storage-eu-west-1.amazonaws.com/NLog/NLog.config"

**Comment by 304NotModified** [comment]
And then we have to read it as an HTTP GET?

**Comment by paddyhamilton** [comment]
Yeah, thats what I thought.
Ill have a go at it and see what i can come up with.

Cheers for the help
