### ISSUE TITLE
Default value for maxArchiveFiles

### ISSUE THREAD

**Issue by Xharze** [NLog/NLog#111]
<p>maxArchiveFiles hidden away in configuration and can be major clusterf@ck if trying to log anything where list of archived files )over the default value of 9) is important.</p>
<p>&nbsp;</p>
<p>Please change default value to not throw anything away</p>

**Comment by ie-zero** [comment]
Can we please close this issue? Pull Request "Max archived files default value 0" #385 has been merged into v4.0 branch.

**Comment by Xharze** [comment]
@ie-zero thanks for noticing
