### ISSUE TITLE
Enable auto reload config by default 

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#1114]
Auto reload is now off by default. This gives issues when starting the program without config. Also if we forgot the turn it on,  a restart is needed. 

Maybe we should enable it by default in NLog 5

**Comment by bhaeussermann** [comment]
I'm not too sure about this. When the config file is not found during startup, we won't know where the config file is supposed to be found, because there are a number of [candidate file paths](https://github.com/NLog/NLog/wiki/Configuration-file#configuration-file-locations). 

If we would want to cater for this, we could watch all of the candidate file paths, if the config file is initially not found, but that would be a separate feature (not a config-value as `autoReload`).

**Comment by 304NotModified** [comment]
> I'm not too sure about this. When the config file is not found during startup, we won't know where the config file is supposed to be found, because there are a number of candidate file paths.
> 
> If we would want to cater for this, we could watch all of the candidate file paths, if the config file is initially not found, but that would be a separate feature (not a config-value as autoReload).

Good point. I was thinking to only watch one path. (discussion which one). 

Although, what will go wrong if we just watch all candidate paths? The filewatch is efficient implemented (at least in Windows, dunno other platforms)

**Comment by bhaeussermann** [comment]
I don't foresee a problem in watching all candidate paths. Even if there is considerable overhead involved, it is only for the exceptional case where the config file is initially not found. As soon as the config file is found (through watching all candidate paths) we shall stop watching the candidate paths. 
Does this sound sensible?

**Comment by bhaeussermann** [comment]
I only notice now your question was probably rhetorical and I did not have to answer :P.

**Comment by 304NotModified** [comment]
Well I was more thinking out loud. So good to hear I'm not thinking nonsense :) 

So thanks!

**Comment by 304NotModified** [comment]
Added discussion, as this is a good point:

> If we would want to cater for this, we could watch all of the candidate file paths, if the config file is initially not found, but that would be a separate feature (not a config-value as autoReload).

**Comment by snakefoot** [comment]
I think it is a bad idea to have autoreload by default. It requires filewatcher (which is not available on all platforms). Prefer that NLog-core is without FileWatcher and global Mutex-logic.

Emerging platforms like cloud-functions and docker images doesn't need this functionality. Mobile-platforms like UWP / Xamarin also don't need this functionality.

Instead it should be in an external assembly that hooks into the LogFactory and monitors when Nlog.config is loaded and automatically monitors the file and triggers reload. So all NLog.config loaded are automatically monitored unless the NLog.config explictly states (autoReload=false).

**Comment by 304NotModified** [comment]
I think we could resolve this if we could (easily) enable it in code

E.g.
```c#
LogManager.WatchPath(dirOrFile)
```

**Comment by snakefoot** [comment]
I was thinking something like this:

`LogManager.Setup().EnableLoggingConfigurationFileWatcher();`

Or:

`LogManager.Setup(b => b.EnableLoggingConfigurationFileWatcher();`

**Comment by 304NotModified** [comment]
Sounds good! I prefer the last syntax :)

**Comment by snakefoot** [comment]
Guess the new API would be:

```c#
LogManager.Setup().LoadConfigurationFromFile(forceAutoReload: true);
```

By adding new extension-method (and the needed plumbing):

```c#
public static ISetupBuilder LoadConfigurationFromFile(this ISetupBuilder setupBuilder, string configFile = null, bool optional = true, forceAutoReload = false)
{
  setupBuilder.LogFactory.LoadConfiguration(configFile, optional, forceAutoReload);
  return setupBuilder;
}
```

**Comment by snakefoot** [comment]
Planning to remove File-Watcher logic with NLog v6, so `autoreload` will not work out of the box, but will require additonal helper-logic.
