### ISSUE TITLE
Send error to multiple target (part programmatically)

### ISSUE THREAD

**Issue by GClaudio** [NLog/NLog#1118]
I wrote the follow code, with a part of my NLog.Config:

```c#
 MessageBoxTarget target = new MessageBoxTarget();
            target.Layout = "${longdate}: ${message}: ${stacktrace}";
            target.Caption = "ERRORE APPLICAZIONE, tipo: ${level} message";
            NLog.Config.SimpleConfigurator.ConfigureForTargetLogging(target, NLog.LogLevel.Error);

            int i = 1;
            int k = 0;
            int x;
            
            try 
            { x = i / k; }
            catch (Exception ex) 
            { 
                ICS.LOG.Error(ex, LogErrorMessage); 
            }
```
NLog.config (only rules part)

```xml
<rules>
    <logger name="*" minlevel="Info" writeTo="db" />
  </rules>
```

The code above, function correctly, but it isn’t send the error do db, it’s show only the error. If I comment the MessageBoxeTarget code, the error is sent correctly to the db.
The question is : How can send the error to both, MessageBox and db ? In my scenario, I need to create the MessgaBoxTarget  programmatically.
Thank’s very much and Happy New Year
G. Claudio Orlandi

**Comment by 304NotModified** [comment]
Hi!  Which NLog (nuget) versions are you using? Can you check the internal log for errors?

**Comment by 304NotModified** [comment]
I think I found the problem:

```c#
        /// <summary>
        /// Configures NLog for to log to the specified target so that all messages 
        /// above and including the specified level are output.
        /// </summary>
        /// <param name="target">The target to log all messages to.</param>
        /// <param name="minLevel">The minimal logging level.</param>
        public static void ConfigureForTargetLogging(Target target, LogLevel minLevel)
        {
            LoggingConfiguration config = new LoggingConfiguration();
            LoggingRule rule = new LoggingRule("*", minLevel, target);
            config.LoggingRules.Add(rule);
            LogManager.Configuration = config;
        }
```

the "simple" approach replaces the whole config.

So you have to go to the "non-simple approach" (which isn't that more difficult IMO)

something like (note no compiler in github comments ;)) :

```c#
  LogManager.Configuration.AddTarget(target);
  LoggingRule rule = new LoggingRule("*", LogLevel.Error, target);
  LogManager.Configuration.LoggingRules.Add(rule);
```

**Comment by GClaudio** [comment]
Versions:

Nlog  			(4.0.0.0) Runtime: v4.0.30319
Nlog.Extended		(4.0.0.0) Runtime: v4.0.30319
NLog.Windows.Forms 	(4.0.0.0) Runtime: v2.0.50727

MessageBoxTarget target = new MessageBoxTarget();
target.Layout = "${longdate}: ${message}: ${stacktrace}";
target.Caption = "ERRORE APPLICAZIONE, tipo: ${level} message";

LoggingConfiguration config = new LoggingConfiguration();
LoggingRule rule = new LoggingRule("*", LogLevel.Error, target);
config.LoggingRules.Add(rule);
LogManager.Configuration = config;

int i = 1;
int k = 0;
int x;
try { x = i / k; }
catch (Exception ex) { ICS.LOG.Error(ex, LogErrorMessage); }


\<rules>
    <logger name="*" minlevel="Info" writeTo="db" />
    <logger name="*" minlevel="Info" writeTo="fi" />
    <logger name="*" minlevel="Warn" writeTo="MailProd" />
    <logger name="*" minlevel="Error" writeTo="MailIT" />
\</rules>

With the code and the Nlog.Config above, I've always and only the MessageBox error, but not the db registration.
Thank's

**Comment by 304NotModified** [comment]
Please update to the latest (patch) versions. At least NLog 4.0.1 is needed.

I have edited you start post with code highlighting ;)

**Comment by GClaudio** [comment]
Sorry, i updated Nlog 4.2.3, without result (always and only messagebox). But the version on c# reference is 4.0.0.0 and runtime (v4.0.30319), and the pathname of dll is:C:\Users\claudio\Documents\Visual Studio2015\Projects\NLogTest\packages\NLog.4.2.3\lib\net40\NLog.dll. 
How is it possible ? 
I create a new c# project, .Net 4.0, and i've the same results (version 4.0.0.0).

**Comment by 304NotModified** [comment]
I think the config gets overwritten when loading the XML.

Can you add the programmic rules/targets at the following events:

- `LogManager.ConfigurationReloaded`
- `LogManager.ConfigurationChanged`

no sure if both are needed.

**Comment by 304NotModified** [comment]
PS: It's correct that the assembly versions are 4.0. That's because of strong naming. Otherwise every library who's using NLog, should release a new version with every release of NLog.

**Comment by GClaudio** [comment]
Thanks for the clarification !

**Comment by GClaudio** [comment]
Thanks for your help, i will be in holiday up to 2016-01-07, I will try your last suggestions from that date.
Happy new year 2016 :)

**Comment by 304NotModified** [comment]
Thanks for letting us know! Have a good new year!

**Comment by GClaudio** [comment]
Hello to everyone and happy new year 2016 !!!
Ok, about this problem, i tried the following code, but without success:

            MessageBoxTarget target = new MessageBoxTarget();
            target.Layout = "${longdate}: ${message}: ${stacktrace}";
            target.Caption = "APPLICATION ERROR, tipo: ${level} message";
            LogManager.Configuration.AddTarget("Msg", target);
            LoggingRule rule = new LoggingRule("*", LogLevel.Error, target);
            LogManager.Configuration.LoggingRules.Add(rule);

            var targetdb = new DatabaseTarget();
            targetdb.Name = "dbx";
            targetdb.ConnectionString = "Data Source=MyDB;Initial Catalog=MyCatalog;User=MyUser;Password=MyPassword";
            targetdb.CommandText = " insert into MyTable(Application, Level, Message," +
                                   " Username" +
                                   " ) values( @Application, @Level, @Message, @Username); ";

            DatabaseParameterInfo paramDB;

            paramDB = new DatabaseParameterInfo();
            paramDB.Name = string.Format("@Application");
            paramDB.Layout = string.Format("${{processname}}");
            targetdb.Parameters.Add(paramDB);

            paramDB = new DatabaseParameterInfo();
            paramDB.Name = string.Format("@Level");
            paramDB.Layout = string.Format("${{level}}");
            targetdb.Parameters.Add(paramDB);

            paramDB = new DatabaseParameterInfo();
            paramDB.Name = string.Format("@Message");
            paramDB.Layout = string.Format("${{message}}");
            targetdb.Parameters.Add(paramDB);

            paramDB = new DatabaseParameterInfo();
            paramDB.Name = string.Format("@Username");
            paramDB.Layout = string.Format("${{windows-identity}}");
            targetdb.Parameters.Add(paramDB);

            LoggingConfiguration config = new LoggingConfiguration();
            LoggingRule ruledb = new LoggingRule("*", LogLevel.Error, targetdb);
            config.LoggingRules.Add(ruledb);
            LogManager.Configuration = config;


            int i = 1;
            int k = 0;
            int x;
            try { x = i / k; }
            catch (Exception ex)
            {
                ICS.LOG.Error(ex, LogErrorMessage);
            }

At this point, i've the row into db table, but the Nlog MessageTarget, doesn't display anything. 
It seems that a target (Message) exclude the other (db), I tried the same code in LogManager_ConfigurationChanged event, but nothing changes.
Thanks

**Comment by GClaudio** [comment]
Sorry, I was wrong, I did not want to close the issue

**Comment by UgurAldanmaz** [comment]
I am just thinking out loud...

I guess, MessageBox would block the thread, doesn't it? When it block, other codes doesn't continue to work until to close the msgBox. So database logger does not works because of that. (When you close the msgBox, is database log written?)

**Comment by GClaudio** [comment]
The messagebox doesn't appear, this is the problem
No message, but only writing in db, if  i comment db target code, the messagebox appears correctly.

**Comment by 304NotModified** [comment]
Your code:

```c#
 MessageBoxTarget target = new MessageBoxTarget();
            target.Layout = "${longdate}: ${message}: ${stacktrace}";
            target.Caption = "APPLICATION ERROR, tipo: ${level} message";
            LogManager.Configuration.AddTarget("Msg", target);
            LoggingRule rule = new LoggingRule("*", LogLevel.Error, target);
            LogManager.Configuration.LoggingRules.Add(rule);

            var targetdb = new DatabaseTarget();
            targetdb.Name = "dbx";
            targetdb.ConnectionString = "Data Source=MyDB;Initial Catalog=MyCatalog;User=MyUser;Password=MyPassword";
            targetdb.CommandText = " insert into MyTable(Application, Level, Message," +
                                   " Username" +
                                   " ) values( @Application, @Level, @Message, @Username); ";

            DatabaseParameterInfo paramDB;

            paramDB = new DatabaseParameterInfo();
            paramDB.Name = string.Format("@Application");
            paramDB.Layout = string.Format("${{processname}}");
            targetdb.Parameters.Add(paramDB);

            paramDB = new DatabaseParameterInfo();
            paramDB.Name = string.Format("@Level");
            paramDB.Layout = string.Format("${{level}}");
            targetdb.Parameters.Add(paramDB);

            paramDB = new DatabaseParameterInfo();
            paramDB.Name = string.Format("@Message");
            paramDB.Layout = string.Format("${{message}}");
            targetdb.Parameters.Add(paramDB);

            paramDB = new DatabaseParameterInfo();
            paramDB.Name = string.Format("@Username");
            paramDB.Layout = string.Format("${{windows-identity}}");
            targetdb.Parameters.Add(paramDB);


//<----------------------your are creating here a new config and overwrite the messagebox! -------!!!
            LoggingConfiguration config = new LoggingConfiguration();
            LoggingRule ruledb = new LoggingRule("*", LogLevel.Error, targetdb);
            config.LoggingRules.Add(ruledb);
            LogManager.Configuration = config;


            int i = 1;
            int k = 0;
            int x;
            try { x = i / k; }
            catch (Exception ex)
            {
                ICS.LOG.Error(ex, LogErrorMessage);
            }

```

You're overwriting the config overhere!

**Comment by GClaudio** [comment]
Sorry, but that code it's an old code (old test), with the follow code i've the same problem:

            var targetdb = new DatabaseTarget();
            targetdb.Name = "dbx";
            targetdb.ConnectionString = "Data Source=INDICOM3;Initial         Catalog=ConservazioneSostitutiva;User=scan;Password=$scan";
            targetdb.CommandText = " insert into Indicom_LOG (Application, Level, Message," +
                                   " Username" +
                                   " ) values( @Application, @Level, @Message, @Username); ";

            DatabaseParameterInfo paramDB;

            paramDB = new DatabaseParameterInfo();
            paramDB.Name = string.Format("@Application");
            paramDB.Layout = string.Format("${{processname}}");
            targetdb.Parameters.Add(paramDB);

            paramDB = new DatabaseParameterInfo();
            paramDB.Name = string.Format("@Level");
            paramDB.Layout = string.Format("${{level}}");
            targetdb.Parameters.Add(paramDB);

            paramDB = new DatabaseParameterInfo();
            paramDB.Name = string.Format("@Message");
            paramDB.Layout = string.Format("${{message}}");
            targetdb.Parameters.Add(paramDB);

            paramDB = new DatabaseParameterInfo();
            paramDB.Name = string.Format("@Username");
            paramDB.Layout = string.Format("${{windows-identity}}");
            targetdb.Parameters.Add(paramDB);
            NLog.Config.SimpleConfigurator.ConfigureForTargetLogging(targetdb, NLog.LogLevel.Error);
            
            MessageBoxTarget target = new MessageBoxTarget();
            target.Layout = "${longdate}: ${message}: ${stacktrace}";
            target.Caption = "ERRORE APPLICAZIONE, tipo: ${level} message";
            NLog.Config.SimpleConfigurator.ConfigureForTargetLogging(target, NLog.LogLevel.Error);

            int i = 1;
            int k = 0;
            int x;
            try { x = i / k; }
            catch (Exception ex)
            {
                ICS.LOG.Error(ex, LogErrorMessage);
            }

Actually in my NLog.config i've other two target (BufferingWrapper) and I ute them to send error mail: Both functions correctly even if i run the code above. But the code above doesn't write to db, because the last Nlog.Config.SImpleConfigurator for Messagebox target, seems to overwrite the NLog.Config.Simpleconfigurator for the db target. If i change the position of both NLog.Congig.SImpleConfigurator, the messagebox target not run, but the db target run correctly. In  both cases, my two BufferingWrapper targets defined in Nlog.config (error mail), always work correctly.

**Comment by 304NotModified** [comment]
yeah, **don't** use the simple configurator. I overwrites the config. 

use 

```c#
  LogManager.Configuration.AddTarget(target);
  LoggingRule rule = new LoggingRule("*", LogLevel.Error, target);
  LogManager.Configuration.LoggingRules.Add(rule);
```

**Comment by GClaudio** [comment]
Finally, the correct code is this:

            MessageBoxTarget target = new MessageBoxTarget();
            target.Layout = "${longdate}: ${message}: ${stacktrace}";
            target.Caption = "ERRORE APPLICAZIONE, tipo: ${level} message";
            LogManager.Configuration.AddTarget("Msg", target);
            LoggingRule rule = new LoggingRule("*", LogLevel.Error, target);
            LogManager.Configuration.LoggingRules.Add(rule);

            LogManager.ReconfigExistingLoggers();

            int i = 1;
            int k = 0;
            int x;
            try { x = i / k; }
            catch (Exception ex)
            {
                ICS.LOG.Error(ex, LogErrorMessage);
            }

The 'ReconfigExistingLoggers', resolve the problem ! In this way I can programmatically, create all extra target i need without overwrite the common existing Nlog.Config.
ReconfigExistingLoggers --->>> (Loops through all loggers previously returned by GetLogger. and recalculates their target and filter list. Useful after modifying the configuration programmatically to ensure that all loggers have been properly configured).

Thanks !!!

**Comment by 304NotModified** [comment]
OK glad to hear :)
