### ISSUE TITLE
LogFactory.ConfirationgChanged is passed old,new parameters in reverse order

### ISSUE THREAD

**Issue by Sarafian** [NLog/NLog#1122]
The code is
```
this.OnConfigurationChanged(new LoggingConfigurationChangedEventArgs(value, oldConfig));
```

but the contructor is
```
internal LoggingConfigurationChangedEventArgs(LoggingConfiguration oldConfiguration, LoggingConfiguration newConfiguration)
```

**Comment by 304NotModified** [comment]
That's a bit pity. Thanks for reporting, but we cannot change this due to backwards compatibility.

**Comment by Sarafian** [comment]
As a workaround can you please describe the conditions of when the ConfigurationReloaded event fires?

**Comment by UgurAldanmaz** [comment]
`ConfigurationReloaded` event fires when your configuration file changed.

You need to enable auto reload:

```
<nlog autoReload="true">
```

See for more info: https://github.com/NLog/NLog/wiki/Configuration-file

**Comment by 304NotModified** [comment]
Has your question being answered @Sarafian ?

**Comment by Sarafian** [comment]
Yes after some further investigation into the code.
Let me explain for future reference. We have some unit tests over some additional to NLOG functionality that configures targets loaded from the config file.

We want to make sure that if the file changes then the configuration is re-applied. Therefore we used to depend on the ConfigurationChanged event but after the upgrade to v4 and the bug mentioned we switched to ConfigurationReloaded. The reason I asked was because after modifying the file the event did not fire. It turns out that it takes some time as expected. The test needs to wait a bit, let nlog do its job and then check if the reloaded targets are re-configured.

Thank you very much.

**Comment by 304NotModified** [comment]
Will mark this as know issue

**Comment by UgurAldanmaz** [comment]
Can I close this one due to wontfix?

**Comment by 304NotModified** [comment]
Yes indeed

**Comment by Sarafian** [comment]
Forgot to answer. Somehow I had missed the email. Ok from me.
