### ISSUE TITLE
Diagnostic improvements for wrong variable node placement

### ISSUE THREAD

**Issue by UgurAldanmaz** [NLog/NLog#1128]
When `<variable>` node written at wrong place, they cannot be parsed, therefore targets cannot access and use their values. This situtation ends up with throwing `System.TypeInitializationException`, but `NLogConfigurationException` would be useful.

Example for wrong configuration file:

```xml
<variable name="messageLayout" value="${longdate:universalTime=True}Z..."/>

   <target name="console" xsi:type="ColoredConsole" layout="${messageLayout}"/>

   <target name="messagesLogFile" xsi:type="File" layout="${messageLayout}"/>
```

    An unhandled exception of type 'System.TypeInitializationException' occurred in Microsoft.VisualStudio.HostingProcess.Utilities.dll

user feedback and my investigation results here: https://github.com/NLog/NLog/issues/1121

- [x] unit test

**Comment by 304NotModified** [comment]
@UgurAldanmaz are you still working on this?

**Comment by UgurAldanmaz** [comment]
I cannot start yet. If you want, I can do within today.

**Comment by 304NotModified** [comment]
That would be great :)

**Comment by UgurAldanmaz** [comment]
Actually it already throw `NLogConfigurationException`. Mentioned exception (`System.TypeInitializationException`) throw because of `NLogConfigurationException` in the constructor method.

[Troubleshooting Exceptions: System.TypeInitializationException](https://msdn.microsoft.com/en-us/library/ms242144(VS.80).aspx)

> When a class initializer fails to initialize a type, a TypeInitializationException is created and passed a reference to the exception thrown by the type's class initializer. The InnerException property of the TypeInitializationException holds the underlying exception.

Therefore, I wrote an unit test that tests `NLogConfigurationException` throw or not.

**Comment by Page-Not-Found** [comment]
That looks to be valid for me. Can as think something in the line of
validating the XML with schema?

**Comment by UgurAldanmaz** [comment]
Thanks @Page-Not-Found! 

You are right. Validating the configuration before initializing would be nice. I will try but probably I will need help to do this.

**Comment by Page-Not-Found** [comment]
I have done some schema validation using an XSD and XML. We can always work
together.

**Comment by UgurAldanmaz** [comment]
Working together would be awesome! Let's discuss at gitter.
