### ISSUE TITLE
Publish latest version of NLog.Schema to Nuget

### ISSUE THREAD

**Issue by brdmllr** [NLog/NLog#1129]
The current version of NLog.Schema (4.2.1) does not contain a definition for element "cleanupFileName".

**Comment by 304NotModified** [comment]
Thanks for reporting.  Will fix this soon.

**Comment by 304NotModified** [comment]
This has been done: https://www.nuget.org/packages/NLog.Schema/4.2.3

**Comment by brdmllr** [comment]
Thank you!
