### ISSUE TITLE
NLog.UnitTests.Targets.FileTargetTests.DateArchive_SkipPeriod fails sometimes

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#1133]
See https://ci.appveyor.com/project/nlog/nlog/build/4.0.1517 and https://ci.appveyor.com/project/nlog/nlog/build/4.0.1514, reported.

Running the same commit in another time window is succeeding. 

around 01:00 (UTC+1) but also in another time 

![image](https://cloud.githubusercontent.com/assets/5808377/12139117/507d725c-b45e-11e5-9a5d-1a0bec58445a.png)

**Comment by UgurAldanmaz** [comment]
Nice catch :+1: 

It would be helpful if we can see the list of actual archive file names. 

I can add a line to list them tonight.

**Comment by 304NotModified** [comment]
What do you mean with "list of actual archive file names."  @ugur?

Fixed already nice!

**Comment by UgurAldanmaz** [comment]
I mean writing an assertion message that contains the produced file names by test. If we can see the file names, then we can figure out the problem, I think. Because, if I am not wrong, archive files named with date time values. And this problem related with datetime.

Anyway, it already fixed!
