### ISSUE TITLE
${callsite} broken - Hide assemblies won't work well

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#1134]
`${callsite}` renders "NLog.LoggerImpl.Write"

Even if I set

```c#
LogManager.AddHiddenAssembly(Assembly.GetAssembly(typeof(NLog.Logger)));
```

**Comment by dodexahedron** [comment]
This might be a lot more broken than that, on 4.4.0.
I'm getting NLog.LoggerImpl.Write on literally ALL usages of callsite.

**Comment by 304NotModified** [comment]
On which platform?

**Comment by dodexahedron** [comment]
.net 4.6.1 x64

-----Original Message-----

**Comment by 304NotModified** [comment]
4.4 is 4.4 beta 2?

Is it possible to test it with 4.3 rc?

**Comment by 304NotModified** [comment]
If this is an issue in 4.3 rc, I will fix it before the final release of 4.3

**Comment by dodexahedron** [comment]
Yep. This also happens in 4.3 RC1.

-----Original Message-----

**Comment by 304NotModified** [comment]
- Can you post relevant code and config?
- Is it also possible to test it with 4.2.3? I'm curious if this is 100% the same issue. 

Also, we need better unit tests on this, as all the unit tests succeed. Can you help us with that?

**Comment by 304NotModified** [comment]
Can confirm this with some tests in 4.3.1

reported " LoggerImpl.Write", but should be " RobotBase`1.DoExecuteAction"


stacktrace (`${stracktrace}`)
```
TimerQueue.AppDomainTimerCallback 
 TimerQueue.FireNextTimers 
 TimerQueueTimer.Fire 
 TimerQueueTimer.CallCallback 
 ExecutionContext.Run 
 ExecutionContext.RunInternal 
 TimerQueueTimer.CallCallbackInContext 
 Timer.MyTimerCallback 
 RobotBase`1.OnElapsedTime 
 RobotBase`1.DoExecuteAction <--- should be this one
 LoggerImpl.Write   --- was this one
```

It would be helpful if:

- You can also try to use stacktrace renderer (`${stacktrace:topFrames=50:format=raw}`) and check if the frame is 1 to late
- someone can reproduce this in an unit test.

**Comment by 304NotModified** [comment]
edit: this isn't an issue in 4.2.1 (not tested in 4.2.3 yet)

**Comment by 304NotModified** [comment]
You can see there are at least 2 calls inlined.  That would explain the succeeding unit tests.

**Comment by dodexahedron** [comment]
Works fine in 4.2.3. That's what we rolled back to, to resolve it.

-----Original Message-----

**Comment by 304NotModified** [comment]
Fix is ready, hopefully not influencing performance a lot.

**Comment by 304NotModified** [comment]
@dodexahedron this has been fixed in NLog 4.3 rc2 and is on Nuget now.

Working on getting this fix into NLog 4.4 beta ATM

**Comment by 304NotModified** [comment]
@dodexahedron also merged into NLog 4.4 - beta 3 is now live!

**Comment by 304NotModified** [comment]
@dodexahedron would be great if you could confirm the fix :)

**Comment by dodexahedron** [comment]
Sure thing.
Out of the office today, but will verify tomorrow.

**Comment by 304NotModified** [comment]
OK thanks!

**Comment by 304NotModified** [comment]
Will reopen and close if confirmed.

**Comment by dodexahedron** [comment]
Confirmed this is working in 4.3 RC2

**Comment by 304NotModified** [comment]
Thanks!

**Comment by verysimplenick** [comment]
${callsite} in cross domain application sometime not working (using with Akka.net):
```
2016-10-04 11:00:11.2872 ERROR NLog.LoggerImpl.Write [akka://RuleProcessor/user/AggregateRuleGroupActor#388440039] Test!  (CrossContextChannel.SyncProcessMessage => Thread.InternalCrossContextCallback => CrossContextChannel.SyncProcessMessageCallback => ServerContextTerminatorSink.SyncProcessMessage => ServerObjectTerminatorSink.SyncProcessMessage => StackBuilderSink.SyncProcessMessage => StackBuilderSink._PrivateProcessMessage => NLogAdapter.Error => Logger.Error => LoggerImpl.Write)
```
Use:
```
public NLogAdapter()
{
    LogManager.AddHiddenAssembly(Assembly.GetExecutingAssembly());
    LogManager.AddHiddenAssembly(Assembly.GetAssembly(typeof(NLog.Logger)));
...
}
```

**Comment by 304NotModified** [comment]
Please open a new ticket! Thanks!
