### ISSUE TITLE
Improve error logging (breaking change)

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#1150]
See 
fix: `//TODO NLog 5, check MustBeRethrown()`
- [ ] src\NLog\Config\ConfigSectionHandler.cs(62):  
- [ ] src\NLog\Config\ConfigurationItemFactory.cs(280):  
- [x] src\NLog\LogFactory.cs(196):  
- [ ] src\NLog\Targets\FileTarget.cs(617):

**Comment by snakefoot** [comment]
Seems resolved by #3356, since there are no more TODOs about `MustBeRethrown()`
