### ISSUE TITLE
Cannot install NLog 4.3.0-alpha3 in Xamarin iOS Projects

### ISSUE THREAD

**Issue by SMavr** [NLog/NLog#1152]
I am trying to add the package in my Xamarin Solution using Xamarin Studio. There is not a problem adding the library to a Xamarin Android Project. But it seems that NLog can not be added to my Xamarin iOS Project. 

Package Console:

Adding NLog...
Adding 'NLog 4.3.0-alpha3' to TestApp.iOS.
Could not install package 'NLog 4.3.0-alpha3'. You are trying to install this package into a project that targets 'Xamarin.iOS,Version=v1.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by 304NotModified** [comment]
can you try alpha-2 ?

**Comment by 304NotModified** [comment]
The nuget package looks good to me, but I did not tested it:

![image](https://cloud.githubusercontent.com/assets/5808377/12231525/993b3076-b858-11e5-8c60-7edd53aca37b.png)

**Comment by SMavr** [comment]
The problem is in Xamarin Studio. I don't think that is possible to install the alpha2 version by Xamarin Studio via Nuget.

**Comment by SMavr** [comment]
Shouldn't be Xamarin.iOS10 instead of MonoTouch10
http://stackoverflow.com/questions/34718144/could-not-install-package-nlog-4-3-0-alpha3-in-xamarin-ios-project?noredirect=1#comment57183286_34718144

**Comment by 304NotModified** [comment]
I think you're right.

I will try to create a new package today

**Comment by SMavr** [comment]
Thanks!

**Comment by 304NotModified** [comment]
It's online! https://www.nuget.org/packages/NLog/4.3.0-alpha4

**Comment by SMavr** [comment]
Thanks it works! ... I am trying to test it but I cannot I see something at the Application Output either in iOS or Android Projects. 

Inside Main:
LogManager.GetCurrentClassLogger().Info("Hello from iOS NLog");

Do I need to set any configuration?
Is the NLog.config file working for the Android and iOS projects?

**Comment by 304NotModified** [comment]
Yes, you need some configuration. XML config is supported for Xamarin.

Some example XML to get started with:

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <targets>
        <target name="logfile" xsi:type="File" fileName="file.txt" />
        <target name="console" xsi:type="Console" />
    </targets>

    <rules>
        <logger name="*" minlevel="Trace" writeTo="logfile" />
        <logger name="*" minlevel="Info" writeTo="console" />
    </rules>
</nlog>
```

I would recommend to read the [tutorial](https://github.com/NLog/NLog/wiki/Tutorial).

**Comment by 304NotModified** [comment]
As you have created an new issue (good choice), this one can be closed?
