### ISSUE TITLE
Some static methods are not thread-safe

### ISSUE THREAD

**Issue by brutaldev** [NLog/NLog#1153]
When configuring loggers in a parallel loop for example, internal collections being used by the static methods are not actually thread-safe.
```
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at NLog.Config.LoggingConfiguration.ValidateConfig()
   at NLog.Config.LoggingConfiguration.InitializeAll()
   at NLog.LogFactory.ReconfigExistingLoggers()
```
In some cases internal objects can be modified which breaks other threads during configuration.
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at NLog.LogFactory.GetTargetsByLevelForLogger(String name, IEnumerable`1 rules, TargetWithFilterChain[] targetsByLevel, TargetWithFilterChain[] lastTargetsByLevel, Boolean[] suppressedLevels)
   at NLog.LogFactory.GetConfigurationForLogger(String name, LoggingConfiguration configuration)
   at NLog.LogFactory.ReconfigExistingLoggers()
```
Static methods should be made thread-safe or at least advertised as not being safe to call from multiple threads.

**Comment by 304NotModified** [comment]
Indeed, this should be fixed

**Comment by brutaldev** [comment]
Any idea how to work around this? I have this problem in a production application now and trying to figure out how to add configuration dynamically in code and call `ReconfigExistingLoggers` safely without crashing the application...

**Comment by 304NotModified** [comment]
If you post some current c# code, I can try to find a work around.

**Comment by brutaldev** [comment]
I would if it wasn't so complicated :(

Using MEF plugins on which multiple instances are created. A parallel loop runs requesting each instance to configure it's internal settings, each of these instances configures a unique file target for logging and without the call to `ReconfigExistingLoggers` nothing is written to disk.

For now I've wrapped all of these sections in a `lock` statement with a static variable in hopes that is a temporary solution to modifying configuration and calling `ReconfigExistingLoggers` from multiple threads.

If I get some time I will add a unit test for this. Should be simple enough to fire off multiple threads which all make a modification to the rules collection and calls `ReconfigExistingLoggers`. At the moment I'm dealing with the chaos of this breaking in production.

**Comment by 304NotModified** [comment]
I think this can be easily fixed. I'm thinking about a patch release.

**Comment by 304NotModified** [comment]
This should be fixed in beta2

 https://www.nuget.org/packages/NLog/4.3.0-beta2
