### ISSUE TITLE
Problem using NLog.Config with Xamarin

### ISSUE THREAD

**Issue by SMavr** [NLog/NLog#1158]
I am trying to use the NLog.Config with Xamarin.iOS and Xamarin.Android Projects. 
I downloaded the NLog.Config package from nuget and I added inside the NLog.Config file:
```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <targets>
        <target name="console" xsi:type="Console" />
    </targets>
    <rules>
        <logger name="*" minlevel="Info" writeTo="console" />
    </rules>
</nlog>
```

and inside the Main

```c#
	static void Main (string[] args)
		{
			Logger logger = LogManager.GetCurrentClassLogger ();
			logger.Trace("Sample trace message");
			logger.Debug("Sample debug message");
			logger.Info("Sample informational message");
			logger.Warn("Sample warning message");
			logger.Error("Sample error message");
			logger.Fatal("Sample fatal error message");
			// if you want to use a different Application Delegate class from "AppDelegate"
			// you can specify it here.
			UIApplication.Main (args, null, "AppDelegate");
		}
```

But it does not work. It seems that the logger doesn't load the configuration file. If I set the LoggingConfiguration inside the Main, it works prefectly. What I am missing?

**Comment by 304NotModified** [comment]
I think auto reload won't work in xamarin (need to check that) , so you need a application restart after editing the config. Did you tried that?

**Comment by SMavr** [comment]
In Xamarin.iOS it worked after setting the Build Action to Content. But the problem remains in Xamarin.Android. I tried to create a file giving:
```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="true"
       >
      <targets>
        <target name="logfile" xsi:type="File" fileName="/data/data/com.mycompany.testapp/files/configTest.txt" />
    </targets>

    <rules>
        <logger name="*" minlevel="Info" writeTo="logfile" />
    </rules>
</nlog>
```

But the file is not created even if I restart the application.

**Comment by 304NotModified** [comment]
you need probably an absolute path in filename or ${basedir}. Please check the internal log, I can help you better if I see a good error message.

**Comment by SMavr** [comment]
Well I think the problem is that setting the build action to content is not yet supported for Xamarin.Android!
http://community.monogame.net/t/what-build-action-should-be-set-for-android-content/2409

**Comment by 304NotModified** [comment]
So you need to copy the config manual to the `/bin` ?

**Comment by SMavr** [comment]
Well the only way to make it work was to put then NLog.config inside Assets (so in /bin) and then creating a new file inside the files direcory:
```c#
using (Stream stream = Assets.Open ("NLog.config"))
			{

				
				using (FileStream output = new FileStream ("/data/data/com.mycompany.testnlogapp/files/NLog.config", FileMode.OpenOrCreate)) {
					stream.CopyTo (output);
				}
			}
		
       
			XmlLoggingConfiguration xmlConfiguration
			= new XmlLoggingConfiguration("/data/data/com.mycompany.testnlogapp/files/NLog.config");
			LogManager.Configuration = xmlConfiguration;
```
Trying to access  to the Assets folder using the file path in XmlLogginConfiguration seems to be not possible.

**Comment by 304NotModified** [comment]
> Trying to access to the Assets folder using the file path in XmlLogginConfiguration seems to be not possible (gives also an UnsupportedException).

Which line gives a `UnsupportedException`?

**Comment by SMavr** [comment]
This line throws System.NotSupportedException:
```c#
XmlLoggingConfiguration test = 
				new XmlLoggingConfiguration ("assets:/NLog.config");
```
If I pass something like:
"file:///android_asset/NLog.config" or "assets/NLog.config" 

I get a System.IO.DirectoryNotFoundException

**Comment by 304NotModified** [comment]
Thanks for the info. Do you think I can reproduce this in regular .Net45? (unit test). I never used assets like this.

**Comment by SMavr** [comment]
I am not sure ... but I think that this only is a Xamarin.Android problem.

**Comment by 304NotModified** [comment]
Maybe it's only a Xamarin problem. But if I could use assets like this in a regular .net project, then I can test if it works at least in other platforms (probably not and we have to write some code for it).  If we get that one working, it's probably easier to fix it for Xamarin.

So how do you make the asset?

**Comment by SMavr** [comment]
In Android there is a special folder called Assets where you can put raw files (They are compiled int an .apk file as-is). You copy paste the NLog.config file there. But the thing is that you cannot access those files by the file path ... you can only take the stream of this file using AssetManager. 

So I copy the file on runtime to the private folder of the app where I can access the file using the file path. 

Is there any way to set the LogManager.Configuration via a Stream?

**Comment by 304NotModified** [comment]
There is a 

```c#
public XmlLoggingConfiguration(XmlReader reader,	string fileName)
```

You need to create a XmlReader from your stream/string. 

You can do that with

```c#
public XmlTextReader(Stream input) //or
public XmlTextReader(string input)
```

if you got it working, can you send the code or a PR (on CoreCLR branch)? 

We should add it here:

https://github.com/NLog/NLog/blob/coreCLR/src/NLog/Config/XmlLoggingConfiguration.cs#L81-L104


and use `#if __ANDROID__  `

**Comment by 304NotModified** [comment]
Related information: https://developer.xamarin.com/guides/android/application_fundamentals/resources_in_android/part_6_-_using_android_assets/

**Comment by SMavr** [comment]
It is working!
```c#
XmlLoggingConfiguration xmlLoggingConfiguration = new XmlLoggingConfiguration (XmlTextReader.Create(Assets.Open ("NLog.config")), null);
```

So  I think something like should be added:
```c#
#if __ANDROID__
using Android.App;
#endif

 public XmlLoggingConfiguration(string fileName)
        {
#if __ANDROID__
   Stream stream = Application.Context.Assets.Open (fileName);
    using (XmlReader reader = XmlReader.Create(stream))
            {
                this.Initialize(reader, null, false);
            }
#else
            using (XmlReader reader = XmlReader.Create(fileName))
            {
                this.Initialize(reader, fileName, false);
            }
        }
#endif

```

Also in the documentation should be mentioned that the config file should be placed in the Assets folder

**Comment by 304NotModified** [comment]
Cool! 

I think the assets folder is readonly?

**Comment by 304NotModified** [comment]
And is the asset the only folder you can use in xamarin Android? 

Thanks in advance!

**Comment by 304NotModified** [comment]
I have created a new feature request for this: https://github.com/NLog/NLog/issues/1172

We will fix this in 4.3

**Comment by 304NotModified** [comment]
This is added in beta2: https://www.nuget.org/packages/NLog/4.3.0-beta2

**Comment by mk352** [comment]
Was anyone able to successfully get the log file created? I was able to load the configuration in Xamarin.Android but when I go to log something, the file is never created. I tried a couple of different directories included the ExternalFiledir and CacheDir. I Also tried manually creating the file and writing to it prior to logging but that did not work as well. I didn't see any errors in the LogCat either. Any ideas?

**Comment by 304NotModified** [comment]
Please check 4.3.8. 4.3.9 seems to be broken in xamarin. See also internal log.

**Comment by Shiva799** [comment]
Hi,
I'm facing the issue with the NLog.config file.
i have installed the nlog, nlog config and nlog schema in xamarin android
the nlog config file is in assets folder

i get following error at line 
NLog.LogManager.Configuration = new XmlLoggingConfiguration("nlog.config");
The name 'new global::NLog.Config.XmlLoggingConfiguration("assets/nlog.config")' does not exist in the current context.

and this line var basedirPath = AppDomain.CurrentDomain.BaseDirectory; the value is null
I'm not getting what im doing wrong initializing the nlog configurations
What i need now is how should i try to initialize nlog config using the existing config file. Also im trying this for first time so please let me know if im making some beginners mistake

thanks

**Comment by snakefoot** [comment]
@Shiva799 Better to start new issue than to wake up sleeping giants. You have already received many answers here:

https://stackoverflow.com/questions/55488453/cannot-load-nlog-config-in-xamarin/55503067

And the NLog wiki also shows how to load NLog.config from project-resources:

https://github.com/NLog/NLog/wiki/Explicit-NLog-configuration-loading#loading-nlog-configuration-from-xamarin-resource
