### ISSUE TITLE
Max Level Rule through API

### ISSUE THREAD

**Issue by Sharpiro** [NLog/NLog#1164]
```
//info file
            var generalFileTarget = new FileTarget();
            config.AddTarget("general", generalFileTarget);
            generalFileTarget.FileName = string.Format("${{basedir}}/logs/{0}_GENERAL_${{shortdate}}.log", _appGuid);
            generalFileTarget.Layout = @"${longdate} ${uppercase:${level}} ${event-context:appGuid} ${event-context:exceptionType} ${event-context:exceptionType} ${logger} ${message}";
            var rule2 = new LoggingRule("*", LogLevel.Debug, generalFileTarget);
            config.LoggingRules.Add(rule2);
```

I need to be able to give this FileTarget a rule where it logs everything LogLevel.Debug and higher, and lower than LogLevel.Error.  But I do not see any way through the API to limit the "max level".

I have a requirement to not use .config files.

Is there a way to do this?

**Comment by Sharpiro** [comment]
As of right now I found a workaround where I am using to Loggers in 1 class ,and then creating LoggingRules based off of the "loggerNamePattern", but I would like to avoid this.

**Comment by 304NotModified** [comment]
What about http://nlog-project.org/documentation/v4.0.0/html/M_NLog_Config_LoggingRule_DisableLoggingForLevel.htm

**Comment by Sharpiro** [comment]
@304NotModified That actualy is a good solution, thank you!

I'd still like to throw out a request for an overload to "LoggingRule" to allow for a "maxLevel" parameter.

**Comment by 304NotModified** [comment]
A new ctor? 

I was also thinking, we have a addTarget on config,  maybe we need also addRule (both are needed in the api)

**Comment by Sharpiro** [comment]
@304NotModified 

Yes, that was what I was looking for before I made this post.  Not needed now that I know about that disable line you gave me, but to me that would be a good future solution.

**Comment by 304NotModified** [comment]
OK thanks for the feedback!

**Comment by 304NotModified** [comment]
I think I could close this. If you have some further questions, just open a new issue.

**Comment by 304NotModified** [comment]
Added a new issue for the things we have discussed: https://github.com/NLog/NLog/issues/1169
