### ISSUE TITLE
CsvLayout should support multi line text in excel

### ISSUE THREAD

**Issue by suntsu42** [NLog/NLog#1165]
I'm using the following CsvLayout, and the output is written into logile.csv

```
CsvLayout layout = new CsvLayout();
            layout.Columns.Add(new CsvColumn("Date","${longdate}"));
            layout.Columns.Add(new CsvColumn("Level", "${level}"));
            layout.Columns.Add(new CsvColumn("Message", "${message}"));
            layout.Columns.Add(new CsvColumn("Exception", "${exception:format=tostring}"));
            layout.Columns.Add(new CsvColumn("Stacktrace", "${stacktrace}"));
```

But when the exception has several lines, and you open the csv file in excel, it will show only the first line. 
It seems excel handles csv multiline a bit different. 
Is there a way to configure NLog in order to use excel for analysing log files?

**Comment by epignosisx** [comment]
It does look like Excel is handling it differently. There are a few solutions that worked for people in this (stackoverflow question)[http://stackoverflow.com/questions/2668678/importing-csv-with-line-breaks-in-excel-2007].
Can you try them out and let us know if any worked for you?

**Comment by suntsu42** [comment]
I know how i can create a csv which can handle multiline entries in excel. It's mainly masking column entries with a apostrophe. 
The problem is that the multi line entries from the exception are written directly by nlog. It seems i'm unable to alter the exception text before it is written into the file. 
Or is there a way to set a hook/handle OnBeforeWrite where i could alter the string?

**Comment by UgurAldanmaz** [comment]
Do you need to replace new line chars from the exception message?

**Comment by Page-Not-Found** [comment]
>Or is there a way to set a hook/handle OnBeforeWrite where i could alter the string?
You can create a custom exception layout renderer and add them to the NLog.
Take a look at https://github.com/NLog/NLog/wiki/Extending-NLog#how-to-write-a-custom-layout-renderer. Instead of inheriting from `LayoutRenderer` you might want to inherit from `ExceptionLayoutRenderer`

There are test cases in NLog repo for this take a look at https://github.com/NLog/NLog/blob/master/tests/NLog.UnitTests/LayoutRenderers/ExceptionTests.cs#L683

**Comment by suntsu42** [comment]
Given is the following exception message:
```
System.ArgumentNullException: Value cannot be null.
Parameter name: foo
   at ConsoleApplication1xx.Program.Main(String[] args) in C:\temp\ConsoleApplication1xx\ConsoleApplication1xx\Program.cs:line 16
   ```
   
   
And for excel to display it properly from a csv file, it shoul be masked like this: 
```
"System.ArgumentNullException: Value cannot be null.
Parameter name: foo
   at ConsoleApplication1xx.Program.Main(String[] args) in C:\temp\ConsoleApplication1xx\ConsoleApplication1xx\Program.cs:line 16"
   ```
   
The linebreaks don't even matter. Only the quotation mark.

**Comment by UgurAldanmaz** [comment]
You can use quoting options. Take a look https://github.com/NLog/NLog/wiki/CsvLayout#csv-options

**Comment by suntsu42** [comment]
@UgurAldanmaz this. 
Thanks a lot.

**Comment by UgurAldanmaz** [comment]
You are welcome @suntsu42. I am closing this issue. If you need help again, feel free to create a new issue.

Have a good day.

**Comment by 304NotModified** [comment]
Can someone add this to the wiki? https://github.com/NLog/NLog/wiki/CsvLayout#csv-options

**Comment by UgurAldanmaz** [comment]
@304NotModified Yes I can. Just as a remark?

**Comment by UgurAldanmaz** [comment]
[I did.](https://github.com/NLog/NLog/wiki/CsvLayout/_compare/45082881d325a90b185a599ca3f858e437b7a83b#diff-6c67307f73ccdb36f2f08a6d255b9227R40)  Thanks @304NotModified.

**Comment by 304NotModified** [comment]
Thanks @UgurAldanmaz !
