### ISSUE TITLE
Running NLog in ASP.net shared hosting environment

### ISSUE THREAD

**Issue by Xharze** [NLog/NLog#117]
<p>NLog does not currently run in ASP.NET partial trust. The issue has been reported multiple times on the forum:</p>

<p>http://n2.nabble.com/Running-NLog-in-ASP-net-shared-hosting-environment-td1685842.html#a1685842</p>

<p>&nbsp;</p>

<p>Security Exception </p>

<p>Description: The application attempted to perform an operation not allowed by the security policy. To grant this application the required permission please contact your system administrator or change the application&#39;s trust level in the configuration file. </p>

<p>&nbsp;</p>

<p>Exception Details: System.Security.SecurityException: That assembly does not allow partially trusted callers. </p>

<p>&nbsp;</p>

<p>Source Error: </p>

<p>&nbsp;</p>

<p>An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below. </p>

<p>&nbsp;</p>

<p>Stack Trace: </p>

<p>&nbsp;</p>

<p>[SecurityException: That assembly does not allow partially trusted callers.] </p>

<p> MyAssembly.MyClass..cctor() +0</p>

Comments:
I've been able to get NLog to run in Partial Trust environments without a problem.

A couple of things I've had to do. 
1. Add the "AllowPartiallyTrustedCallers" attribite to the assembly.
2. Strong Name sign the assembley
3. Made a change to bypass the "WindowsCreateFile" in BaseFileAppender - This causes File logging to fail

Of course under partial trust, you can only log to a file or directory under the current application.

Happy to send you my code if you want.

**Comment by kshkrao3** [comment]
Could you please send code or could you please let know how exactly you've made changes?

**Comment by 304NotModified** [comment]
@kshkrao3 this issue has been closed for more than 3 years. Is your question in the right issue?

**Comment by kshkrao3** [comment]
@304NotModified Sorry to say but yes. I have hosted my application in a shared hosting wherein I cannot override full trust configuration and hence application is in partial trust mode. But I am getting the said exception because of above reasons. So, I would be glad if I receive any help on this.. :)

**Comment by 304NotModified** [comment]
A new issue would be the best. Please provider the requested info and exception details/traces. Thanks!

**Comment by kshkrao3** [comment]
Should I be opening new issue for this? Because I think this has been resolved as per @Xharze's workaround and I was asking for detailed help on same as he has mentioned at the end **Happy to send you my code if you want.** :)

**Comment by 304NotModified** [comment]
Yes please. I don't know of the same fixes would work in NLog 4. A lot has been changed.

**Comment by kshkrao3** [comment]
I must say then, I have to copy the same exception details as above in a new issue.. :) Please give me a Go or No Go.. :)

**Comment by 304NotModified** [comment]
New one please. :)
