### ISSUE TITLE
Support loading nlog.config from Xamarin "assets" folder

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#1172]
Support for the "assets" folder with Xamarin, for the nlog.config. See https://github.com/NLog/NLog/issues/1158

This is working:
```c#
var reader = XmlTextReader.Create(Assets.Open ("NLog.config"));
var config = new XmlLoggingConfiguration (reader, null); //filename is not required.
LogManager.Configuration = config;
```

So  I think something like should be added:
```c#
#if __ANDROID__
using Android.App;
#endif

 public XmlLoggingConfiguration(string fileName)
        {
#if __ANDROID__
   Stream stream = Application.Context.Assets.Open (fileName);
    using (XmlReader reader = XmlReader.Create(stream))
            {
                this.Initialize(reader, null, false);
            }
#else
            using (XmlReader reader = XmlReader.Create(fileName))
            {
                this.Initialize(reader, fileName, false);
            }
        }
#endif

```

> Also in the documentation should be mentioned that the config file should be placed in the Assets folder

**Comment by 304NotModified** [comment]
@SMavr we have still no success when running the unit tests on Xamarin.

Can you test this for use if we create a new beta nuget package?

**Comment by SMavr** [comment]
Yes sure ... tell me when the package is uploaded into the nuget server

**Comment by 304NotModified** [comment]
@SMavr 

I was working on this. One question, how should we execute this? 

I was thinking of:

```c#
LogManager.Configuration = new XmlLoggingConfiguration("assets/nlog.config");
```

so it should start with `assets/`. What do you think?

**Comment by SMavr** [comment]
No you don't need to give assets ... just give the file name. 
```
Stream stream = Application.Context.Assets.Open (fileName);
```
This line of code looks into the Assets folder for the given file name and opens a stream to it. I don't think that you will be allowed to access the assets folder given just the name of it!

**Comment by 304NotModified** [comment]
But if in the future we can read normal files (non assets or other folders), we have a problem. 

I remove the prefix when calling `Application.Context.Assets.Open (fileName);`

Maybe the prefix `assets:` is better.

**Comment by SMavr** [comment]
I don't think it will work. The only way to access assets files is via getting them as a Stream from the current Application Context.

**Comment by 304NotModified** [comment]
> I don't think it will work.

What won't work?

**Comment by SMavr** [comment]
Sorry my mistake :( ... I thought you wanted to remove completely that line. I think the prefix ```assets/``` is ok!

**Comment by 304NotModified** [comment]
Ok thanks for the feedback :)

**Comment by 304NotModified** [comment]
This is added in beta2: https://www.nuget.org/packages/NLog/4.3.0-beta2

**Comment by SMavr** [comment]
It works! 
```
LogManager.Configuration = new XmlLoggingConfiguration("assets/nlog.config");
````

**Comment by 304NotModified** [comment]
Thanks!

**Comment by 304NotModified** [comment]
Also for the initial code :)

**Comment by 304NotModified** [comment]
Hi @SMavr ,

After some thoughts I think auto loading (convention based) is an important feature in NLog. Therefor I added assets/nlog.config (Xamarin only), to the auto load feature. (see #1357). 

If I push NLog 4.3-rc3 to Nuget, is it possible to test it? (in short, remove `LogManager.Configuration = new XmlLoggingConfiguration("assets/nlog.config");`)

**Comment by SMavr** [comment]
Ok I will test it at the weekend!

**Comment by 304NotModified** [comment]
Thanks! Will release rc3 before the weekend then :)

**Comment by 304NotModified** [comment]
@SMavr RC3 is now online! Thanks in advance for checking!

**Comment by SMavr** [comment]
It works fine! It would be cool as well if the NLog.config could to be added automatically into the Assets folder with a Build Action as an AndroidAsset, instead of the main folder of the Application!

**Comment by 304NotModified** [comment]
Cool! Thanks for testing! 

The latter is the NLog.config package I guess?

**Comment by 304NotModified** [comment]
Close this one as it has been fixed &  confirmed :)

**Comment by soroshsabz** [comment]
ITNOA

Hi

When you think NLog.Config change to NLog.config could to be added automatically into the Assets folder? is it right work? or bad practice to place NLog.config into Assets folder?
