### ISSUE TITLE
Exception vs StackTrace vs CallSite

### ISSUE THREAD

**Issue by skironDotNet** [NLog/NLog#1177]
I work with NLog for a few years, but recently I looked into the source code.

Logging Exception using ${exception:format=tostring} returns exception type name, exception message and the stack trace "at ClassName.Method in C:\... line 1"

Using ${stacktrace} return Class.MethodA => SubClass.MethodB. I would expect to get stack trace "at ClassName.Method in C:\... line 1"

Now if there is only one level in stackframes, the callsite is same as stacktrace. I would expect 
${callsite:className=true:fileName=false:includeSourcePath=false:methodName=true} 
to return Exception.TargetSIte.ToString(), still no too much relevant defrence between CallSite and StackTrace, but both renderers use .StackTrace.GetFrame(x) instead of getting this information from the Exception class. I know for some logging without passing Exception that would not work. But is there a way to access each property of the exception via layout string {$exception.Message} {$exception.TargetSite} and so on?

Sorry this not a true issue, or a question likely because it's too broad aspect of logging, but maybe someone can sort it out

**Comment by Page-Not-Found** [comment]
Yes. There is a way to render each part of the exception class seperately. Check this link https://github.com/NLog/NLog/wiki/Exception-Layout-Renderer

**Comment by skironDotNet** [comment]
Yeah, I did notice that. I was just confused by StackTrace / CallSite, also I thought those comes from Exception but those are in case of non exception logging.

Thanks!

**Comment by skironDotNet** [comment]
Yeah, I did notice that. I was just confused by StackTrace / CallSite, also I thought those comes from Exception but those are in case of non exception logging.

Thanks!

**Comment by Page-Not-Found** [comment]
Happy that I was able to answer the question.
