### ISSUE TITLE
[Question] Get all logs that will be sent in email flush

### ISSUE THREAD

**Issue by shaggygi** [NLog/NLog#1178]
Is there a way to get all the logs that will be included in a target email?  For example, let's say I logged 10 infos, 4 warns, 2 errors and 1 fatal, before doing a email flush.  Is there a way to query that list?  If so, how?

The reason I'm asking it would be nice to query this list to know if there was a certain severity reached during the process.  As a result, I could alter the email subject/body with other information based on the severity.

The only other way to do this would be to add extra flags in code with each log call.

Any help is appreciated.

**Comment by Page-Not-Found** [comment]
You probably can a create a custom target and configure the desired level you want to add the additional information. Custom Target https://github.com/NLog/NLog/wiki/Extending-NLog#how-to-write-a-custom-target

Hope I have understood and answered your question.

**Comment by shaggygi** [comment]
Here is a little bit more info in example...

_logger = LogManager.GetCurrentClassLogger();
_logger.Info("Info added.");
_logger.Info("More info added.");
_logger.Warn("Warning occurred.");
_logger.Info("More info added.");
_logger.Error("Error is bad.");
_logger.Info("One last info added.");

At this point, I would like to query the logger to see all the logs added in this instance.  Meaning, it would be nice to have a method (e.g. _logger.GetCurrentLogs(), etc.) to return a List<Logs> or similar of the 4 infos, 1 warn and 1 error that was logged above.  This would allow the ability to determine if certain log was added before doing a flush.

**Comment by Page-Not-Found** [comment]
I am new NLog and from what I know you cannot do that with the current Nlog version. 

I would wait for others to say whether we have any workaround to do this.

**Comment by bhaeussermann** [comment]
The logger does not store past logs and it would take up too much memory, especially if many logs are written. Consider the following:
* Use the [Database target](https://github.com/NLog/NLog/wiki/Database-target) to write the logs to a database. Then query the logs from your database.
* If you don't expect to have a lot of logs between the emails, you can write your own "in-memory target" ([How to write a custom target](https://github.com/NLog/NLog/wiki/Extending-NLog#how-to-write-a-custom-target)) to store the logs in memory until they are "flushed" to email.

**Comment by shaggygi** [comment]
Thanks for the input.

**Comment by 304NotModified** [comment]
@shaggygi Did you checked the memoryTarget /bufferedTargetWrapper? See https://github.com/NLog/NLog/wiki/Targets

If those won't fix your question, I'm pretty sure you can write some custom target based on those targets.
