### ISSUE TITLE
LogManager.GetClassFullName() does not work for Release with deleted .pdb files

### ISSUE THREAD

**Issue by skironDotNet** [NLog/NLog#1180]
current code does not work. for Asp.NET froms somethimes the name is Control, sometimes CalliEventHandlerDelegateProxy

When I use this simple code I get correct name. 

            try 
            { 
                StackFrame frame = new StackFrame(2);
                var method = frame.GetMethod();
                return method.DeclaringType.FullName;
            }
            catch 
            {
                return "Unknown";
            }

**Comment by 304NotModified** [comment]
So it does work when the pdb files aren't deleted?

**Comment by skironDotNet** [comment]
Seems like PDB files does not matter. But NLog 4 also does not provide CallSite and StackTrace in release mode (for sure does not without PDB files)

Because I was working with NLog in the past, I tried version 3.2 and totally better behavior. CallSite and StackTrace present.

Web applications also works weird in this exmaple SourceWrapper is a class that has CauseError method that throws and error within try/catch and in catch nlog is used to log that

version 3.2 Callsite example (Release mode / deleted PDB on IIS with exception being logged):
Control.LoadRecursive => _default.Page_Load => SourceWrapper.CauseError 

version 3.2 Callsite example (Release mode / deleted PDB on IIS NO exception being logged, just .Info("message")):
_default.Page_Load => SourceWrapper.CauseError => Logger.LogMessage 

version 4.2.1 Callsite example (Release mode / PDB Present on IIS with exception being logged):
Control.LoadRecursive

version 4.2.1 Callsite example (Release mode / PDB Present on IIS NO exception being logged, just .Info("message")):
_default.Page_Load

version 4.2.1 Callsite example (Release mode / deleted PDB on IIS with exception being logged):
Control.LoadRecursive

version 4.2.1 Callsite example (Release mode / PDB Present on IIS NO exception being logged, just .Info("message")):
Control.LoadRecursive

In version 4.2.1 also GetCurrentClassName() gives names like "CalliEventHandlerDelegateProxy" and "Control"

I think name is relevant to skipframes (3) while release mode may not have so many frames, etc, but for CallSite and StackTrace looks like old version was utilizing reflection much better

**Comment by skironDotNet** [comment]
Seems like PDB files does not matter. But NLog 4 also does not provide CallSite and StackTrace in release mode (for sure does not without PDB files)

Because I was working with NLog in the past, I tried version 3.2 and totally better behavior. CallSite and StackTrace present.

Web applications also works weird in this exmaple SourceWrapper is a class that has CauseError method that throws and error within try/catch and in catch nlog is used to log that

version 3.2 Callsite example (Release mode / deleted PDB on IIS with exception being logged):
Control.LoadRecursive => _default.Page_Load => SourceWrapper.CauseError 

version 3.2 Callsite example (Release mode / deleted PDB on IIS NO exception being logged, just .Info("message")):
_default.Page_Load => SourceWrapper.CauseError => Logger.LogMessage 

version 4.2.1 Callsite example (Release mode / PDB Present on IIS with exception being logged):
Control.LoadRecursive

version 4.2.1 Callsite example (Release mode / PDB Present on IIS NO exception being logged, just .Info("message")):
_default.Page_Load

version 4.2.1 Callsite example (Release mode / deleted PDB on IIS with exception being logged):
Control.LoadRecursive

version 4.2.1 Callsite example (Release mode / PDB Present on IIS NO exception being logged, just .Info("message")):
Control.LoadRecursive

In version 4.2.1 also GetCurrentClassName() gives names like "CalliEventHandlerDelegateProxy" and "Control"

I think name is relevant to skipframes (3) while release mode may not have so many frames, etc, but for CallSite and StackTrace looks like old version was utilizing reflection much better

**Comment by skironDotNet** [comment]
Console app in release mode with and without PDB 
Nlog 3.2 CallSite :
Program.Main => Logger.ErrorDb

Nlog 4.2.1 CallSite :
[nothing]

**Comment by 304NotModified** [comment]
I made some big improvements on the callsite logger last weeks. Is it possible to test with nlog 4.3 beta? If the problem is also there, it's easier to fix. 

Also relevant c# lines and (xml)  config would help. 

Last but not least, if we can create an unit tests for this, I'm sure we can fix it for NLog 4.3 RTM. 

PS. I'm a few days off,  holiday. Will be back Monday.

**Comment by skironDotNet** [comment]
testes briefly 4.4.0-alpha under web/IIS, CallSite works in Debug but in Release "Control.LoadRecursive"

If this helps, I use .NET 4.0 (maybe this matters)

**Comment by 304NotModified** [comment]
You should try 4.3 beta. 4.4 alpha isn't up to date yet (regarding callsite) . 4.4 alpha is primary used for coreclr.

**Comment by skironDotNet** [comment]
Oh, ok, but I discovered something additional (it' may apply only to my case). I use now NLog 3.2.1 and I noticted that having this code in my custom wrapper (you would have to likely see whole code, so sorry if it makes no sense):

		private static string GetClassName()
		{
			try
			{
				StackFrame frame = new StackFrame(2);
				var method = frame.GetMethod();
				return method.DeclaringType.Name;
			}
			catch
			{
				return "Unknown";
			}
		}

StackFrame is set to 2 and in Debug gives correct Class name, in release parent. Now when debugged stepped thru and checked method.DeclaringType.Name it was lat say X but logged name was Y (and it does not make full sense to me on how NLog i affecting my custom code). I did notice that having CallSite target layout like this  ${callsite:className=true:fileName=true:includeSourcePath=true:methodName=true:skipFrames=1}
Now if I change skipFrames it's affecting my Class name, like it's adjusting globally for the whole application stackframe reference.

Again that may be just the way I have wired together

**Comment by skironDotNet** [comment]
One more thing, and big sorry for my mistake. I originally wanted to log ${CallSite} as {$StackTrace} didn't seem to work, I logged both as one field to have visual comparison, so my layout is

${stacktrace:skipFrames=2} + ${callsite:className=true:fileName=true:includeSourcePath=true:methodName=true:skipFrames=2}" 

What I wan't explain now is I was under impression I put CallSite + StackTrace, while it was StackTrace + CallSite. SO all the comment above I put that my CallSite looks like X were actually {$StackTrace}

My code became big mess after so many Try/Fail of  Layout vs NLog version vs Relerase/Debug that I'm lost myself...

**Comment by skironDotNet** [comment]
I'm closing the issue. Too broad. Also release mode will apply optimization that changes StackTrace so even if using skipFrame=x the result will be different in release/debug   

http://stackoverflow.com/questions/7585010/exception-stack-trace-difference-between-debug-and-release-mode

**Comment by skironDotNet** [comment]
I'm closing the issue. Too broad. Also release mode will apply optimization that changes StackTrace so even if using skipFrame=x the result will be different in release/debug   

http://stackoverflow.com/questions/7585010/exception-stack-trace-difference-between-debug-and-release-mode
