### ISSUE TITLE
Logger to extend an ILogger interface to ease unit-testing and mocking of loggers

### ISSUE THREAD

**Issue by Xharze** [NLog/NLog#119]
<p>If I had one wish for NLog 2 it would be for an ILogger interface that Logger would implement. This would help greatly with testing, mocking, stubbing and wrapping of Logger objects.</p>
<p>&nbsp;</p>
<p>Coming from the Java world where every method is virtual by default I find trying to write tests in C# when using classes that aren&#39;t completely virtual or don&#39;t implement an interface quite frustrating.</p>

**Comment by ilya-g** [comment]
@Xharze, could you tag this with v4.0 milestone, so we don't forget to get this done before releasing v4.0?

**Comment by Xharze** [comment]
Done

**Comment by 304NotModified** [comment]
Done so close
