### ISSUE TITLE
FileTarget Rules to ArchiveAboveSize OR ArchiveEvery

### ISSUE THREAD

**Issue by Sharpiro** [NLog/NLog#1190]
```
var generalFileTarget = new FileTarget
 {
	ArchiveAboveSize = 200000,
	MaxArchiveFiles = Int32.MaxValue,
	 ArchiveFileName = "xxx.log",
	ArchiveEvery = FileArchivePeriod.Minute
};
```

Above is my current FileTarget.  It currently archives above 200 KB **AND** archives every minute.

I have a requirement to implement a FileTarget that archives above say 200 KB **OR** archives say every minute.

I have not seen a way to do this, is there a workaround or a feature I'm missing?

Thanks.

**Comment by 304NotModified** [comment]
Hi,

This is too bad not possible yet. Any idea how we should configure this feature? (from the end-user viewpoint)

**Comment by bhaeussermann** [comment]
@Sharpiro What exactly is your requirement?  
Archive the file at 200 KB, but archive every minute *only* if the file did not reach 200 KB within that minute. Is that what you had in mind?

**Comment by Sharpiro** [comment]
@bhaeussermann 

yes, essentially once 1 of the 2 conditions is met, perform the archive and then reset the conditions, i.e reset file size back to 0 and ideally time back to 0.

**Comment by 304NotModified** [comment]
I assume your question has been answered. If not, please let us know!
