### ISSUE TITLE
add onException to catch exceptions in targets etc

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#1193]
add Configuration.OnException to handle exceptions async.

**Comment by snakefoot** [comment]
Maybe introduce a InternalLogger-delegate that includes origin-target-type + exception-object. See also #2710

**Comment by snakefoot** [comment]
Resolved by #3796 that added `InternalLoggerLogMessageReceived`-event.

Improved by 3823 that adds context with target-type + target-name. And improved further by #4256 to make it easier for all targets to provide proper context.
