### ISSUE TITLE
InternalLogger,  document TextWriter property

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#1196]
allow writing to custom `TextWriter`, so that user can decide where to store the internal logs.

**Comment by bhaeussermann** [comment]
It looks like `InternalLogger` already supports this. See the `LogWriter` property.

**Comment by 304NotModified** [comment]
Cool,  then we need to update https://github.com/NLog/NLog/wiki/Internal-Logging

**Comment by bhaeussermann** [comment]
I updated the page.

**Comment by jamesmckenzie** [comment]
I assume this issue can be closed now @304NotModified ?

**Comment by 304NotModified** [comment]
yes, thanks @jamesmckenzie  & @bhaeussermann !
