### ISSUE TITLE
Use a specific nlog configuration file for each dll

### ISSUE THREAD

**Issue by mad4hit** [NLog/NLog#1198]
Hello, thanks for this amazing tool.
Here my problem:
I've a complex visual studio solution with 9 different projects, my goal is to set for each project and indipendent nlog.config. 
6 projects (each ot them have nlog linked) are dlls so i put the nlog configuration in the app.config (this after a build will produce a dllname.dll.config), i link all this projects to a console application (anonther projects in that solution), the build action create correctly the dllsname.dll.config files within the nlog configuration but nlod doesn't works.
Any idea?

Thanks!

**Comment by 304NotModified** [comment]
are those projects have on executable project? (MVC, API, Windows service etc)?

You can set a config per exexecutable project. If you have one, maybe you should filter log messages.

**Comment by mad4hit** [comment]
Hi, yes of course i've a project executable but my intent was to provide a log environment for each project, so each project produce it's log dispite the location or the link.

**Comment by 304NotModified** [comment]
Ow I meant "one" . So does it have one or more executables?

**Comment by mad4hit** [comment]
Hi, yes it have.
But my goal is to have one nlog configuration for each project independently.
I've uploaded an example solution for describe my problem.
Thanks for the support!
Alex

[Test_Nolg.zip](https://github.com/NLog/NLog/files/106496/Test_Nolg.zip)

**Comment by 304NotModified** [comment]
structure:
![image](https://cloud.githubusercontent.com/assets/5808377/12612945/93948d2a-c4f6-11e5-9541-bee5741db684.png)


What you can do:

1. Work with one nlog.config for every executable project and filter the log messages if needed in the nlog.config, or
2. Load in every project the nlog.config (on different locations) with some c# code, or
3. don't use nlog.config and use [the API to configure NLog](https://github.com/NLog/NLog/wiki/Configuration-API).

**Comment by mad4hit** [comment]
Hi, 
thanks for the tip!!
I'll use the n°3, i think will be the best solution that fit my needs!

Thanks a lot for the help!
Regards
Alex

**Comment by 304NotModified** [comment]
OK glad to hear!
