### ISSUE TITLE
Nlog Date layout need to get the datetime offset with the long date

### ISSUE THREAD

**Issue by joepauly** [NLog/NLog#1199]
Tried `${longdate:format=yyyy-MM-ddTHH\:mm:ss.ffffK}` but its not writing in offset into the file using Nlog. Tried `${date:format=yyyy-MM-ddTHH\:mm:ss.ffffK}` it gives the offset and the time output. Even tried `zzz` instead of `K`. Can we give any other usage for getting the UTC offset in Nlog consoleLayout.Text.

**Comment by 304NotModified** [comment]
Can you give an example of the desired output/

**Comment by 304NotModified** [comment]
I think you can use `K` because:

> public DateTimeKind Kind { get; }
> The default is Unspecified.

https://msdn.microsoft.com/en-us/library/system.datetime.kind(v=vs.110).aspx

and 
> The "K" Custom Format Specifier
> For a time from an unspecified time zone (a time whose DateTime.Kind property equals DateTimeKind.Unspecified), the result is equivalent to String.Empty.

https://msdn.microsoft.com/en-us/library/8kb3ddd4(v=vs.110).aspx#KSpecifier

**Comment by joepauly** [comment]
I tried the date part with
${date:format=yyyy-MM-ddTHH\:mm:ss.ffffK} but it gives only the part of minute part of the time with the offset.
Is there any length specified?? do we need to spilt this to 2 variable to get both date,time and offset 
${ date format:yyyy-MM-ddTHH\:mm:ss.ffffK}

**Comment by joepauly** [comment]
consoleLayout.Text = "${longdate}|${date:format= K}| worked fine

**Comment by joepauly** [comment]
Thanks @304NotModified  for the help. :+1:
