### ISSUE TITLE
add throwExceptions on target or rule level

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#1201]

**Comment by snakefoot** [comment]
Would be easier to implement this on the LoggingRule. Then it would be a matter of creating a custom `AsyncContinuation`.

Maybe combined a special Logger.Log-method (Ex Audit) that only returns when logging-operation has completed (succesful or not)

**Comment by 304NotModified** [comment]
That's also a nice idea :)

Anyway, I think this idea is very low on the prio list.

**Comment by snakefoot** [comment]
Think this has been resolved by #3823 and #4256
