### ISSUE TITLE
How to re-enable logging after shutdown

### ISSUE THREAD

**Issue by Ninja4Code** [NLog/NLog#1204]
If I call LogManager.Shutdown() how would I re-enable logging? Currently I'm getting a null reference on the logger when I try to access it after calling shutdown.  I'm thinking this may be caused by calling LogManager.GetCurrentClassLogger() within a static constructor.  In that case the answer may be to eschew the static constructor and use a public constructor instead to initialize the LogManager.  This is being implemented in a thread timer.

**Comment by Page-Not-Found** [comment]
As of now I am not seeing any method to "Restart" the logging.

If you would like to stop the logging intermediately, you can see if `EnableLogging` & `DisableLogging` will be helpful for your question.

**Comment by Page-Not-Found** [comment]
@Ninja4Code Is your question answered?

**Comment by Ninja4Code** [comment]
I was able to resolve the issue by using a public constructor instead of a static constructor to invoke the LogManager.GetCurrentClass().  I'm no longer getting the Null Reference.  In retrospect, this makes sense.  By placing the initialization in a static constructor I was probably creating a dangling pointer when I called shutdown.   You can close out this one.  Thanks for following up.

**Comment by 304NotModified** [comment]
OK thanks for the feedback!
