### ISSUE TITLE
Need to get the ${guid} - Globally-unique identifier (GUID) into NLog.LogEventInfo

### ISSUE THREAD

**Issue by joepauly** [NLog/NLog#1205]
can we get the** ${guid}** in  **NLog.Layouts.SimpleLayout.Text**  to** NLog.LogEventInfo** object so that we can get the guid whereever Logeventinfo is referenced.

**Comment by joepauly** [comment]
@304NotModified

**Comment by Page-Not-Found** [comment]
While we are in the process of discussing, here are suggestions which I feel could be a work around

- Would adding this value to the GDC OR MDC be a workaround for this?
- Would something like below will work
```
<target name="jsonFile" xsi:type="File" fileName="${basedir}/logs/${shortdate}.json">
    <layout xsi:type="JsonLayout">
        <attribute name="time" layout="${guid}" />       
    </layout>
</target>
```

**Comment by 304NotModified** [comment]
I was thinking of the logeventinfo properties.

**Comment by joepauly** [comment]
logeventinfo properties contains other variables,that is being pushed as part of logging.

Time variable cannot be manipulated as time is also passed.

**Comment by Page-Not-Found** [comment]
>Time variable cannot be manipulated as time is also passed.
The above was just example. Now I see why there is a confusion. The variable name can be anything of your choice.

**Comment by 304NotModified** [comment]
I'm a bit lost in this one. What are we trying to achieve?

**Comment by 304NotModified** [comment]
Let us know if this is still an issue.

**Comment by snakefoot** [comment]
NLog v4.5 introduced `${guid:GeneratedFromLogEvent=true}`. See also: https://github.com/NLog/NLog/wiki/Guid-Layout-Renderer

This ensures the same Guid is shown across all targets for the same LogEvent.
