### ISSUE TITLE
Nlog gives "Service Unavailable  HTTP Error 503. The service is unavailable." in Microsoft Dynamic CRM.

### ISSUE THREAD

**Issue by ebegen** [NLog/NLog#1209]
We are using NLog for logging an exeptions in dynamic crm 2011. I used `[Anotar.NLog.LogToErrorOnException]` attribute for a method. And this method using a web service for sending data. Also we have a try catch in this method. And this catch writing log to crm service. Some people saying because of nested try catch like below, crm server is too busy. Because these try catches trying handle exception after and after again. So they are thinking, there is recursive exception method because of NLog. 

Is this Possible?

For example;

```c#
[Anotar.NLog.LogToErrorOnException]
public void SendYKS(...)
{
   ...
   ...
   ...
   try
  {
   ...
   ...
  }catch(Exception ex)
  {
   ...
   WriteToCRM(ex.message);
  }
}
```

**Comment by 304NotModified** [comment]
If the catch won't rethrow the exception, then recursive would be unlikely.  

But we can't be sure without knowing the code of LogToErrorOnExceptionAttribute.  Is the code somewhere?

**Comment by 304NotModified** [comment]
Has you question being answered?

**Comment by 304NotModified** [comment]
Let us know if this is still an issue.
