### ISSUE TITLE
RichTextBox Target in WPF application

### ISSUE THREAD

**Issue by Xharze** [NLog/NLog#121]
Hello,

 How can I use RichTextBox Target in WPF application?

I don't want to have a separate window with log, I want all log messages to be outputted in richTextBox located in WPF dialog.

I've tried to use WindowsFormsHost with RichTextBox box inside but that does not worked for me.

**Comment by 304NotModified** [comment]
Closing this one due to the lack of activity.

**Comment by rolaxxxx** [comment]
are there any news to this issue ?
