### ISSUE TITLE
internalLogger, write to System.Diagnostics.Debug / System.Diagnostics.Trace

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#1217]
Allow InternalLogger write to `System.Diagnostics.Debug` / `System.Diagnostics.Trace`

It should be one option (WriteToDiagnostics?). When enabled:
- trace messages to `System.Diagnostics.Trace`
- others to `System.Diagnostics.Debug`

**Comment by bryjamus** [comment]
This changes solve this issue.

**Comment by 304NotModified** [comment]
docs: 

- https://github.com/NLog/NLog/wiki/Configuration-file
