### ISSUE TITLE
An exception was thrown by the type initializer for NLog.Config.ConfigurationItemFactory

### ISSUE THREAD

**Issue by nbyh** [NLog/NLog#1219]
Unhandled Exception: System.TypeInitializationException: An exception was thrown by the type initializer for NLog.Config.ConfigurationItemFactory。

![error](https://cloud.githubusercontent.com/assets/7239908/12816835/9ed6752e-cb89-11e5-8a68-44c390c6c324.png)

**Comment by 304NotModified** [comment]
There is something wrong in your config.  We can't throw a better exception too bad (the nlogconfiguration exception is masked by the TypeInitializationException)

**Comment by 304NotModified** [comment]
See also http://stackoverflow.com/questions/34994470/better-typeinitializationexception-innerexception-is-also-empty

**Comment by nbyh** [comment]
But I don't want to load the config. I want to use the Configuration API. Is it preferred loading config? How to bypass config?

**Comment by 304NotModified** [comment]
Can you read the innerException? That should give a glue what's wrong.

**Comment by 304NotModified** [comment]
This is fixed in 4.3 as we won't throw config exceptions anymore.
