### ISSUE TITLE
Known issue: MailTarget + SSL + port 465 isn't working

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#1226]
> This could be a .Net bug,  described at: http://blogs.msdn.com/b/webdav_101/archive/2008/06/02/system-net-mail-with-ssl-to-authenticate-against-port-465.aspx
> 
> TL;DR: SSL + port 465 (implicit SSL) is not supported in .Net. You can only use SSL + port 25 (explicit SSL)

See http://stackoverflow.com/questions/35228313/nlog-mail-target-timeouts/35235850#35235850

**Comment by 304NotModified** [comment]
Mail api which support implicit ssl

https://www.nuget.org/packages/AIM

**Comment by 304NotModified** [comment]
https://github.com/jstedfast/MailKit

**Comment by 304NotModified** [comment]
Will close this as this is a known issue as it's polluting the issue list - there is no action for us here.

**Comment by 304NotModified** [comment]
There is now a NLog.MailKit package: 

https://www.nuget.org/packages/NLog.MailKit

**Comment by StevenLiSiwei** [comment]
NLog.MailKit Works like charm on net 4.5. thanks !!

**Comment by neooleg** [comment]
@304NotModified, could you pls elaborate how to use SSL (gmail) with NLog.MailKit?

**Comment by 304NotModified** [comment]
Install the package: Install-Package NLog.MailKit and add to your nlog.config:

```xml
<extensions>
    <add assembly="NLog.MailKit"/>
</extensions>
```

See https://github.com/NLog/NLog.MailKit/blob/master/README.md

**Comment by neooleg** [comment]
I did it and did follow the link which mentions

> Note: port 465 isn't working with SSL.

**Comment by 304NotModified** [comment]
https://github.com/NLog/NLog/wiki/Examples

**Comment by 304NotModified** [comment]
So use port 587

**Comment by gaazkam** [comment]
@304NotModified  

Why does https://github.com/NLog/NLog/wiki/Mail-Target still say:

> Note: port 465 isn't working with SSL. See issue 1226

My understanding is that as long as MailKit is used there should be no problems with port 465 and SSL?

I just tested it and it seems to work fine:

```xml
<target name="logmail" xsi:type="Mail"
        subject="Email logging test"
        to="redacted"
        from="redacted"
        smtpUserName="redacted"
        enableSsl="true"
        secureSocketOption="SslOnConnect"
        smtpPassword="redacted"
        smtpAuthentication="Basic"
        smtpServer="redacted"
        smtpPort="465"
        timeout="100000"/>
```

**Comment by 304NotModified** [comment]
Thanks, please update the wiki. It is indeed working for NLog mailkit (thanks for the confirm!). 

PS: The page is shared for the mail target in NLog and NLog mailkit

**Comment by gaazkam** [comment]
[Done](https://github.com/NLog/NLog/wiki/Mail-target/_compare/6f3a81e87a85cd4357ba171e1d5e6cdd77c33048...c8d38e6af4e0afdf6f86aecbf0503d69f05d31e0).

**Comment by 304NotModified** [comment]
Thanks!
