### ISSUE TITLE
processname layout renderer not being replaced

### ISSUE THREAD

**Issue by chillitom** [NLog/NLog#1228]
Using the `processname` layout renderer as follows:

     <variable name="logname" value="${appsetting:name=LogName:default=${processname}}" />

The variable `logname` ends up being the string "`${processname}`"

Using NLog 4.2.3 and NLog.Extended 4.0.0.1.

Any ideas?

**Comment by 304NotModified** [comment]
Too bad `default` is a `string` and not a `Layout` in [`${appsetting}`](https://github.com/NLog/NLog/wiki/AppSetting-Layout-Renderer), and so it's rendered as string.

**Comment by 304NotModified** [comment]
Or add your own appSetting class:

something like this (not checked in Visual Studio)

```c#


#if !SILVERLIGHT

namespace NLog.LayoutRenderers
{
	using System.Text;
	using Config;
	using Internal;

	/// <summary>
	/// Application setting.
	/// </summary>
	/// <remarks>
	/// Use this layout renderer to insert the value of an application setting
	/// stored in the application's App.config or Web.config file.
	/// </remarks>
	/// <code lang="NLog Layout Renderer">
	/// ${appsetting:name=mysetting:default=mydefault} - produces "mydefault" if no appsetting
	/// </code>
	[LayoutRenderer("appsetting")]
	public class AppSettingLayoutRenderer : LayoutRenderer
	{
		private IConfigurationManager configurationManager = new ConfigurationManager();

		///<summary>
		/// The AppSetting name.
		///</summary>
		[RequiredParameter]
		[DefaultParameter]
		public string Name { get; set; }

		///<summary>
		/// The default value to render if the AppSetting value is null.
		///</summary>
		public Layout Default { get; set; } //changed

		internal IConfigurationManager ConfigurationManager
		{
			get { return configurationManager; }
			set { configurationManager = value; }
		}

		/// <summary>
		/// Renders the specified application setting or default value and appends it to the specified <see cref="StringBuilder" />.
		/// </summary>
		/// <param name="builder">The <see cref="StringBuilder"/> to append the rendered data to.</param>
		/// <param name="logEvent">Logging event.</param>
		protected override void Append(StringBuilder builder, LogEventInfo logEvent)
		{
			if (Name == null)
				return;

			string value = AppSettingValue;
			if (value == null && Default != null)
				value = Default.Render(logEvent); //changed

			if (string.IsNullOrEmpty(value) == false)
				builder.Append(value);
		}

		private bool _cachedAppSettingValue = false;
		private string _appSettingValue = null;
		
		private string AppSettingValue
		{
			get
			{
				if (_cachedAppSettingValue == false)
				{
					_appSettingValue = ConfigurationManager.AppSettings[Name];
					_cachedAppSettingValue = true;
				}
				return _appSettingValue;
			}
		}
	}
}

#endif

```

**Comment by chillitom** [comment]
Could we create a second property on the existing AppSettingLayoutRenderer something like DefaultLayout `${appSetting:foo:defaultLayout=${processName}}` and fall back to Default if it isn't set?

**Comment by 304NotModified** [comment]
Doubting. It certainly doesn't looks nice from the API perspective. But changing `string` to `layout` is also a (small) breaking change.

**Comment by chillitom** [comment]
Yeah agreed. It would be nicer if "default" just worked for both. Have there been examples in the past where as string parameter has changed to a layout parameter?   Did it adversely affect anybody?

**Comment by 304NotModified** [comment]
yes we did some changes in minor releases, but it's too bad not full backwardscompatible. in 4.3 we changed the RegistryLayoutRenderer. 

I was thinking to change **all**  properties of  **all**  layout renders to `Layout` in NLog 5. Too bad, there is a small performance impact. 

Or maybe we should think of something smart, e.g. `"${a}"` and `$"${a}"` aren't the same in C#

**Comment by chillitom** [comment]
Yeah, I think it would be best to go for consistency across the board, just now I'm hitting the same problem with `VariableLayoutRenderer`.

In the case of fixed text what is the cause of the small performance impact? An indirect method call to GetFormattedMessage?

The breaking change I guess is that anyone relying on literal printing of `$` characters would need to escape them in NLog 5

**Comment by 304NotModified** [comment]
Funny, I'm certain I have responded on this one...



> In the case of fixed text what is the cause of the small performance impact? An indirect method call to GetFormattedMessage?

The good news is that there is almost no loss in performance when calling `GetFormattedMessage` for `SimpleLayouts` (fixed strings) - no locks and the call isn't `virtual`.

The performance impact would be only for caching purpose, e.g. if something is a string, we now for sure that it won't change (until the setter is used). But we can do something with the FixedText property of a layout. 

So concluding, the performance impact for fixed layouts (SimpleLayouts) should be marginal. 



> The breaking change I guess is that anyone relying on literal printing of $ characters would need to escape them in NLog 5

ps: There is a [`SimpleLayout .Escape(string)` method](https://github.com/NLog/NLog/blob/1899e6a4a5ab4ee0b23129d5b950cad519db19b4/src/NLog/Layouts/SimpleLayout.cs#L171). Maybe we can use that for backwards-compatibly. (e.g. when setting reading the XML)

**Comment by 304NotModified** [comment]
I'm gonna close this one as there is a better GitHub issue for this ( https://github.com/NLog/NLog/issues/1234)
