### ISSUE TITLE
Directory created even if internalLogLevel set to off?

### ISSUE THREAD

**Issue by kpstolk** [NLog/NLog#1229]
I noticed that the directory _c:\temp\_ of value `internalLogFile="c:\temp\nlog-internal.log"` is created even when `internalLogLevel` is set to `"Off"`:
```
internalLogLevel="Off"
internalLogFile="C:\temp\nlog-internal.log"
```

Is this on purpose or should the directory _c:\temp\_ only be created when the `internalLogLevel` is not set to `"Off"`? It's a minor issue but now I have an empty _temp_ directory and I didn't know what caused it at first..

Tested with NLog version: 4.2.3.

**Comment by 304NotModified** [comment]
That a good one! We will check this and fix it in 4.3.

**Comment by kpstolk** [comment]
Thanks for your acknowledgement!

I'm afraid that I'm not able to pick this up shortly, but it's good to know where to start ;)

**Comment by eduardorascon** [comment]
Hi, I want to help you fixing this bug, I'm new to github and open source in general.

Do you need me to write a test for this case? Or is there something more for me to do.

**Comment by 304NotModified** [comment]
@eduardorascon That would be great! We will help you to the process.

We really need unit tests for bugs. I would recommend to write a test before the bug is fixed, (TDD style), so we are sure the bug is solved.

In this case you can alter the current unit test to see the bug.

Steps

1. Create a new branch of master in your fork
2. Change the CreateDirectoriesIfNeededTests](
https://github.com/NLog/NLog/blob/18a7e20d2de44ae9aad0783ba64c5e859504845b/tests/NLog.UnitTests/Common/InternalLoggerTests.cs#L397) unit test with this as a start (please note, we use xUnit1)

```c#
  [Theory]
        //todo InlineData for all loglevels

        [InlineData("trace", true)]

        public void CreateDirectoriesIfNeededTests(string rawLoglevel, bool shouldCreateDirectory)
        {

            var loglevel = LogLevel.FromString(rawLoglevel);

//todo change unit test so it uses loglevel  and shouldCreateDirectory
            string expected =
                    "Warn WWW" + Environment.NewLine +
                    "Error EEE" + Environment.NewLine +
                    "Fatal FFF" + Environment.NewLine +
                    "Trace TTT" + Environment.NewLine +
                    "Debug DDD" + Environment.NewLine +
                    "Info III" + Environment.NewLine;

```

3. fix the bug
4. send PR

**Comment by eduardorascon** [comment]
Hi @304NotModified 

I think I got the fix done, buuut there's something strange. [AssertFileContents](https://github.com/eduardorascon/NLog/blob/fix-create-directories/tests/NLog.UnitTests/Common/InternalLoggerTests.cs#L441) is failing beacuse sometimes the message its not written to log file.

Here's the code in [InternalLogger.cs](https://github.com/eduardorascon/NLog/blob/fix-create-directories/src/NLog/Common/InternalLogger.cs#L212) that exits before writing to the log file:

`if (level < LogLevel)
{
return;
}`

**Comment by eduardorascon** [comment]
To expanda little bit more.

Seems to me that this happens beacuse LogLevel is set to "Trace" before any changes were made. Now, with the new changes LogLevel is set using rawLoglevel.

`LogLevel.FromString(rawLoglevel);`

**Comment by 304NotModified** [comment]
I think the unit test is testing too much (more then the name suggests). Maybe I a better idea to copy the unit test and create a new one? (no ` [InlineData("trace", true)]` etc needed). What do you think?

If so, please do create a new branch (from master), so the current commits won't pollute the history.

**Comment by eduardorascon** [comment]
I think AssertFileContents should be removed from this test because we should only be testing if the directory its created or not.

Also, there is a WriteToFileTests method in the InternalLoggerTest class already and this method also calls the AssertFileContents method.

**Comment by 304NotModified** [comment]
That's also fine to me :)

**Comment by kpstolk** [comment]
Nice one, that was quick! Thanks @eduardorascon  @304NotModified
