### ISSUE TITLE
Error with LogManger in a DLL

### ISSUE THREAD

**Issue by GClaudio** [NLog/NLog#1230]
Hi to everyone,
I've a strange error using the LogManager.Configuration.Variables method, from a DLL
Here the scenario:
DLL Code:
// GOOD, the code works properly

```c#
LogManager.ConfigurationReloaded += LogManager_ConfigurationReloaded;
LogManager.ConfigurationChanged += LogManager_ConfigurationChanged;
string tName = LogManager.Configuration.FindTargetByName("MailIT").ToString();


//BAD, this code doesn’t run
LogManager.Configuration.Variables["myVar"] = "myValue";
```

The exception is:

```
Missing method: NLog.Config.LoggingConfiguration.get_Variables()
```

If I use the same NLog method, out of my DLL, it works properly, but not if it called fromDLL.
Do you have some idea for this ?

Thanks
Regards
Claudio

**Comment by 304NotModified** [comment]
Hi,

Are you using (indirect) multiple versions of NLog in your solution? If so, which versions?

It seems that there are 2 incompatible versions, e.g. in one project it's compiled with NLog 3.2 and another with NLog 4.1.

**Comment by GClaudio** [comment]
Fantastic, you have hit the problem, now my solution with dll, works properly !

Thank You very much !

**Comment by 304NotModified** [comment]
:)
