### ISSUE TITLE
Add Swallow(Task task)

### ISSUE THREAD

**Issue by breyed** [NLog/NLog#1231]
Feature suggestion: A `Forget` method that is similar to `Logger.SwallowAsync` except that it would return `void` instead of `Task`. Its use would be in fire-and-forget situations where the calling code intentionally does not await an async method. It would prevent the code from having to use some other means of suppressing this warning:

> Warning CS4014: Because this call is not awaited, execution of the current method continues before the call is completed. Consider applying the 'await' operator to the result of the call.

I'd be happy to submit a PR if there is consensus that this is a good idea.

**Comment by 304NotModified** [comment]
is this the `async` version of `Swallow(Action action)`?

**Comment by breyed** [comment]
You could think of it that way. In fact, `Swallow` would probably be a better name for it than `Forget`. Its signature would be `void Swallow(Task task)`.

**Comment by 304NotModified** [comment]
OK good idea. We are almost ready with 4.3, maybe we can merge it before the release.
