### ISSUE TITLE
Possible bug with downgrading NLog version and permissions

### ISSUE THREAD

**Issue by Mekimuraosu** [NLog/NLog#1235]
Greetings,

Thus far I've had a great time using NLog with a windows service, but had (a bit carelessly) made the project with .NET 4.5.2, and having to install the service on servers only able to run higher than 4.0 I had to downgrade the Framework, and which in turn gave me an error with NLog (since it was still targeting the old version of the Framework), and being a bit new to C# still, I downgraded the NLog to 4.0.0 instead of just reinstalling it to begin with to re-target it to the new framework.

And after doing that I realized my mistake and then re-installed the 4.0.0 to re-target it to .NET 4.0

However now there is no logs being written at all, neither internal logs or otherwise.
The Config file is identical to the one I was running with when it was working previously, and I can see the service, is running according to plan.

I've also tried re-upgrading to 4.2.3 and have that targeted to .NET 4.0, and same result. 
No permissions have changed since it was working (Or at least I did not change any manually)

I've installed it through NuGet but did the re-installing to re-target the framework through the Package Manager Console

So is it me completely missing something obvious, or did something break in the transition? 
Or are you perhaps using some feature that require newer than .NET 4.0 to handle the permissions?

Thanks in advance

**Comment by 304NotModified** [comment]
I think you need to reinstall all packages after a framework change 

`update-package -reinstall`  in the package manager Console should do the trick. Could take some time

**Comment by Mekimuraosu** [comment]
> I've installed it through NuGet but did the re-installing to re-target the framework through the Package Manager Console

Not trying to be rude, but this is exactly what I've already done when I re-targeted them to the 4.0 framework as I followed the guide found on Microsoft's page about NuGet's and .NET versioning.
Sadly to no effect.
I'll continue to see if I can find a working solution

**Comment by 304NotModified** [comment]
> Not trying to be rude, but this is exactly what I've already done when I re-targeted them to the 4.0 framework as I followed the guide found on Microsoft's page about NuGet's and .NET versioning.

I missed that in the initial post, sorry about that. 

Can you post the XML config?

**Comment by Mekimuraosu** [comment]
Thanks for the quick reply.
After messing around with it a bit, I can see that at least while running it locally in Debug mode on VS2015 I can now get the internal log too work. So I might have a chance to figure out what's going wrong through that as well

The config file is the same I used when it was working initially, only with the change now that I've enabled the internal log since it stopped working

<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="true"
      internalLogLevel="Trace" internalLogFile="c:\temp\nlog-internal.log" >


  
  <variable name="myvar" value="myvalue"/>

  
  <targets>

    

    

    <target xsi:type="File" name="error" fileName="${basedir}/logs/${shortdate}.log"
            layout="${longdate} ${uppercase:${level}} ${message}" />
    </targets>

  <rules>
    

    
    <logger name="*" minlevel="Trace" writeTo="error" />
  </rules>
</nlog>

**Comment by 304NotModified** [comment]
The config looks good (no surprise I guess).

If you have still problem, the internal log would be helpful .

**Comment by Mekimuraosu** [comment]
Got it fixed now.
Turns out I had some remnants from the first attempt to try and change NLog version that wasn't correctly cleared when I had tried downgrading through the NuGet Manager. But after my TFS check-in it showed the 4.0.1 version still laying around as a second check-in and undoing that fixed both.

Sorry for the confusion, and thanks for the help!

**Comment by 304NotModified** [comment]
OK thanks for the up!

**Comment by Mekimuraosu** [comment]
Just a quick note on this, in case others check back on this topic with the same or similar error.
Though slightly off topic of NLog itself

After getting this fixed, I was installing it and still not getting the logs once I had installed it with an installShield project, but was getting the logs in debug mode.
If others run into this problem, you should check the properties of the NLog.config and see if it's sent as Content or Compile. 

If it's set to Content, then you need to add it under content in the Installer as well, or set it to Compile so it will be included in the .dll

**Comment by 304NotModified** [comment]
:+1: thanks, that could be helpful indeed :)
