### ISSUE TITLE
NLog.config file in Xamarin.iOS ignored

### ISSUE THREAD

**Issue by davidkaya** [NLog/NLog#1243]
Hello.

I have tried this simple NLog.config with network target:
```xml
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <targets>
    <target name="networkTarget" xsi:type="Network" address="udp://x.x.x.x:xxxxx"/>
  </targets>

  <rules>
    <logger name="*" minlevel="Debug" writeTo="networkTarget" />
  </rules>
</nlog>
```

It **works** correctly in iOS Simulator -> message is sent and delivered to receiver.
It **does not** work in actual iOS device -> message is not delivered.

I set Build Actions to "Content" and Quick Properties to "Copy to Output Directory".

However when I set the configuration in code:
```cs
var config = new LoggingConfiguration();

var networkTarget = new NetworkTarget();
networkTarget.Address = "udp://x.x.x.x:xxxx";
config.AddTarget("Network", networkTarget);

var rule = new LoggingRule("*", LogLevel.Debug, networkTarget);
config.LoggingRules.Add(rule);

LogManager.Configuration = config;
```
it **works** correctly in iOS Simulator and also in actual iOS device.

NLog v4.3.0-beta2

**Comment by 304NotModified** [comment]
Hi,

AFAIK you can't read files in iOs? 

We fixed in Android with the assets folder, see https://github.com/NLog/NLog/pull/1212

**Comment by davidkaya** [comment]
Hi,
you can read files, as long as they are bundled in project. Output from the console (ran on actual device):
```
2016-02-16 13:16:21.323 ApplicationiOS[1902:818639] <?xml version="1.0" encoding="utf-8"?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<targets>
		<target name="networkTarget" xsi:type="Network" address="udp://xxxxxx" />
	</targets>
	<rules>
		<logger name="*" minlevel="Debug" writeTo="networkTarget" />
	</rules>
</nlog>
```

**Comment by davidkaya** [comment]
Update:

```cs
LogManager.Configuration = new XmlLoggingConfiguration("NLog.config");
```
works just fine and logs are correctly sent and LogManager is configured.

**Comment by 304NotModified** [comment]
OK thanks, then it's a bug.
