### ISSUE TITLE
Bulk pushing logs to database

### ISSUE THREAD

**Issue by pjone** [NLog/NLog#1244]
Hello.

My C# application needs to push about 500 to 3000 log entries to database per second. Currently, I have (log configuration is created programmatically) a database target and I am pushing the code from my wrapper class one by one. 

Is there a way to bulk push all the (say, 3000) logs into the database, rather than pushing it one by one? Or is there a way to use memory target to bulk push to database?

**Comment by 304NotModified** [comment]
yes, you can use the [BufferingTargetWrapper](http://nlog-project.org/documentation/v4.0.0/html/Properties_T_NLog_Targets_Wrappers_BufferingTargetWrapper.htm) .

But if performance is very important (and those are a lot of logs!), you can optimize a lot in a specific case. I would recommend to write your own databasetarget and implement 

```c#
/// <summary>
/// Writes an array of logging events to the log target. By default it iterates on all
/// events and passes them to "Write" method. Inheriting classes can use this method to
/// optimize batch writes.
/// </summary>
/// <param name="logEvents">Logging events to be written out.</param>
protected virtual void Write(AsyncLogEventInfo[] logEvents)

```

**Comment by 304NotModified** [comment]
@pjone has you question being answered?

**Comment by 304NotModified** [comment]
Let us know if this is an issue.

**Comment by pjone** [comment]
Hi 304NotModified. Sorry for the late reply. Yes, the problem got solved. I used AsyncTargetWrapper and it seems to be working now. Thank you.

**Comment by voroninp** [comment]
@304NotModified Is it sufficient to override  `protected virtual void Write(AsyncLogEventInfo[] logEvents)` or are there any additional requirements for enabling batches?

**Comment by 304NotModified** [comment]
> are there any additional requirements for enabling batches?

you need a target wrapper that buffers, e.g. asyncTargetWrapper or the BufferingTargetWrapper
