### ISSUE TITLE
httpexception happening 1-2 times a week

### ISSUE THREAD

**Issue by cadeguzman98c** [NLog/NLog#1257]
- Possible Bug
**NLog version**: 4.2.3

**Platform**: .Net 4.5 

In case of a BUG:

- What is the current result?

Unhandled Execution error

- What is the expected result?

- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?

yes, but nothing that can explain this exception

- Please post full exception details (message, stacktrace, inner exceptions)

I'm getting 

```
HttpException (0x80004005)
at System.Web.CachedPathData.GetPhysicalPath(VirtualPath virtualPath) 
at System.Web.CachedPathData.GetConfigPathData(String configPath) 
at System.Web.HttpContext.GetFilePathData() at System.Web.HttpContext.GetSection(String sectionName) at System.Configuration.ConfigurationManager.get_AppSettings() 
at NLog.Common.InternalLogger.GetSettingString(String configName, String envName) 
at NLog.Common.InternalLogger.GetSetting[T](String configName, String envName, T defaultValue) 
at NLog.Common.InternalLogger..cctor()

```

maybe 1-2 times a week

- Are there any work arrounds? yes/no

recycle app pool will fix it

**Comment by 304NotModified** [comment]
Thanks for this report.

This seems to be a bug in ASP.NET


To quote:

> The problem is described in: [kb 2848799][1]

> to fix it you need to contact microsoft for a hotfix. The short term solution is to recycle the application domain.


> **ASP.NET issue 1** 
>
> In some cases, the first call to HttpUtility in a web
> application may cause incorrect type initialization. This leads to
> later failures when you use HttpUtility methods. When you experience
> this issue, you have to recycle the application domain to resolve the
> issue. Additionally, you find the following message in the System log:
> 
> 
> 
> Getting Error Message for Exception System.Web.HttpUnhandledException
> (0x80004005): Exception of type 'System.Web.HttpUnhandledException'
> was thrown. ---> System.TypeInitializationException: The type
> initializer for 'System.Net.WebUtility' threw an exception. --->
> System.Web.HttpException  at
> System.Web.CachedPathData.GetPhysicalPath(VirtualPath virtualPath)  at
> System.Web.CachedPathData.GetConfigPathData(String configPath)  at
> System.Web.CachedPathData.GetConfigPathData(String configPath)


  [1]: http://support.microsoft.com/kb/2848799/en-us


http://stackoverflow.com/questions/21540282/asp-net-system-web-cachedpathdata-getphysicalpathvirtualpath-virtualpath-excep

Can you try installed that KB?

**Comment by cadeguzman98c** [comment]
It has been a week since we applied the hot fix and so far we haven't got the exception. Looks like your solution works. Thanks!

**Comment by 304NotModified** [comment]
Thanks for the feedback!
