### ISSUE TITLE
Using both file based and api for configuration

### ISSUE THREAD

**Issue by mhsimkin** [NLog/NLog#1263]
Hi! Thanks for reporting this feature/bug/question! Please keep / fill in the relevant info from this template so that we can help you as best as possible.

**Type** (choose one): Question

**NLog version**: 4.2.3

**Platform**: .Net 4.6.1

**Current NLog config** (xml or C#, if relevant) Both

```xml
  <configSections>
    <section name="nlog" type="NLog.Config.ConfigSectionHandler, NLog"/>
  </configSections>
  <nlog throwExceptions="true" internalLogFile="nlog-internal.log">
    <targets>
      <target name="logfile" type="File" fileName="file.log" layout="${date:format=HH\:mm\:ss} ${logger} ${message} ${exception:format=tostring} ${event-context:item=MyValue}" />
    </targets>
    <rules>
      <logger name="*" minlevel="Trace" writeto="logfile"/>
    </rules>
  </nlog>
```

Is it possible to configure NLog using both a file (app/web.config) and the API? If so, is it possible to provide and example.  What I have put together, doesn't seem to work as nothing is appearing in the console.

Thanks

marc

**Comment by mhsimkin** [comment]
I have attempted to upload a zip of the solution.  For some reason it is not being accepted. Is there an email address I can send the zip file to? 

Thanks

marc

**Comment by 304NotModified** [comment]
Hey,


> Is it possible to configure NLog using both a file (app/web.config) and the API?

Yes it it :)

Let's try first without emailing as I try to keep my e-mail address private.

You need to (re-)configure the configuration programmatically when the XML get's (re)loaded. You can do that with these two events

- LogManager.ConfigurationChanged
- LogManager.ConfigurationReloaded

See http://nlog-project.org/documentation/v4.0.0/html/Events_T_NLog_LogManager.htm

I'm not sure if you need both. 

Too bad if haven't got an example for now. If you can't get above working, let me know!

**Comment by mhsimkin** [comment]
Hi Julian:

Thank you for your guidance.  Unfortunately the LogManager.ConfigurationChanged and LogManager.ConfigurationReloaded events are being raised too late in the process.

In my little sample app, ConfigurationChanged didn't get raised until program exit.

I did find a solution, after I modify the configuration, I need to call LogFactory.ReconfigExistingLoggers().

After that, everything works as expected.

Here is the little sample code:

    class Program
    {
        // Define a static logger variable so that it references the logger instanced named "Scribe"
        private static readonly Logger log = LogManager.GetCurrentClassLogger();

        static void Main(string[] args)
        {
            var consoleTarget = new ColoredConsoleTarget();
            consoleTarget.Name = "console";
            log.Factory.Configuration.AddTarget("console", consoleTarget);

            consoleTarget.Layout = @"${date:format=HH\:mm\:ss} ${logger} ${message} ${exception} ${event-context:item=MyValue}";
            var rule1 = new LoggingRule("*", LogLevel.Debug, consoleTarget);
            log.Factory.Configuration.LoggingRules.Add(rule1);
            log.Factory.ReconfigExistingLoggers();

            log.Info("Entering Application.");

            Bar bar = new Bar();
            bar.DoIt();

            log.Info("Exiting application.");

            Console.WriteLine("Press any key to exit ...");
            Console.Read();
        }
    }

    public class Bar
    {
        private static readonly Logger log = LogManager.GetCurrentClassLogger();

        public void DoIt()
        {
            LogEventInfo theEvent = new LogEventInfo(LogLevel.Debug, "", "Oops! I did it again");
            theEvent.LoggerName = "log4netexample.Bar";
            theEvent.Properties.Add("MyValue", "Another really bad song.");
            log.Log(theEvent);

            theEvent = new LogEventInfo(LogLevel.Error, "", "Exception Test");
            theEvent.Exception = new ArgumentException("Some exception");
            log.Log(theEvent);
        }
    }

Here is my app config:

<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <configSections>
    <section name="nlog" type="NLog.Config.ConfigSectionHandler, NLog"/>
  </configSections>
  <nlog throwExceptions="true" internalLogFile="nlog-internal.log">
    <targets>
      <target name="logfile" type="File" fileName="file.log" layout="${date:format=HH\:mm\:ss} ${logger} ${message} ${exception:format=tostring} ${event-context:item=MyValue}" />
    </targets>
    <rules>
      <logger name="*" minlevel="Trace" writeto="logfile"/>
    </rules>
  </nlog>
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.6.1" />
  </startup>
</configuration>

Thank you for all your help.

-marc

**Comment by 304NotModified** [comment]
Thanks ! 

So this is tricky when auto-reload is enabled. Maybe if auto-reload is enabled, are the events in time. 

PS: I enabled syntax highlighting in your post.

**Comment by mhsimkin** [comment]
@304NotModified yes if I replace log.Factory.Configuration with LogManager.Configuration, it will work also.

I have not tried the Configuration events.

I understand that depending upon my usage scenario, I might need to merge the file based and API based configurations every time the configuration events are fired.

I have not thought though all scenarios yet, I'm working on a prototype and understanding NLog.

Thanks for all the help and guidance.

-marc

**Comment by 304NotModified** [comment]
I think the events will work, but not in a console as you have only one thread (and there is a delay of ~1000ms)

So it should be something like this, which can be tested in a website

```c#
using System;
using NLog;
using NLog.Config;
using NLog.Targets;

class Program
{
    // Define a static logger variable so that it references the logger instanced named "Scribe"
    private static readonly Logger log = LogManager.GetCurrentClassLogger();

    static void Main(string[] args)
    {
        ExtendNLogConfig();

        LogManager.ConfigurationReloaded += LogManager_ConfigurationReloaded;
        LogManager.ConfigurationChanged += LogManager_ConfigurationChanged; ;

        log.Info("Entering Application.");

        Bar bar = new Bar();
        bar.DoIt();

        log.Info("Exiting application.");

        Console.WriteLine("Press any key to exit ...");
        Console.Read();
    }

    private static void LogManager_ConfigurationChanged(object sender, LoggingConfigurationChangedEventArgs e)
    {
        ExtendNLogConfig();
    }

    private static void LogManager_ConfigurationReloaded(object sender, LoggingConfigurationReloadedEventArgs e)
    {
        ExtendNLogConfig();
    }

    /// <summary>
    /// Extend the logging rules in the nlog.config with programmically rules.
    /// </summary>
    private static void ExtendNLogConfig()
    {
        //don't set  LogManager.Configuration because that will overwrite the nlog.config settings
        var consoleTarget = new ColoredConsoleTarget();
        consoleTarget.Name = "console";
        LogManager.Configuration.AddTarget("console", consoleTarget);

        consoleTarget.Layout = @"${date:format=HH\:mm\:ss} ${logger} ${message} ${exception} ${event-context:item=MyValue}";
        var rule1 = new LoggingRule("*", LogLevel.Debug, consoleTarget);
        LogManager.Configuration.LoggingRules.Add(rule1);
        LogManager.ReconfigExistingLoggers();
    }
}

public class Bar
{
    private static readonly Logger log = LogManager.GetCurrentClassLogger();

    public void DoIt()
    {
        LogEventInfo theEvent = new LogEventInfo(LogLevel.Debug, "", "Oops! I did it again");
        theEvent.LoggerName = "log4netexample.Bar";
        theEvent.Properties.Add("MyValue", "Another really bad song.");
        log.Log(theEvent);

        theEvent = new LogEventInfo(LogLevel.Error, "", "Exception Test");
        theEvent.Exception = new ArgumentException("Some exception");
        log.Log(theEvent);
    }
}

```

**Comment by mhsimkin** [comment]
@304NotModified Thanks for the example.  I will give it a try.

**Comment by 304NotModified** [comment]
Thanks for testing!

**Comment by snakefoot** [comment]
See also wiki: https://github.com/NLog/NLog/wiki/Combine-XML-config-with-C%23-config
