### ISSUE TITLE
archiving would not work if we have a date in the filename

### ISSUE THREAD

**Issue by umu24013** [NLog/NLog#1271]
With this configuration, it never archives/compresses the old log files. Normal log files are working as expected with this config. Tried different config options like archiveEvery, archiveNumbering, archiveEvery, archiveFileName. still no luck

- Bug?

**NLog version**:  4.2.3

**Platform**:  .Net 4.5.1 and .Net 4.5

**Current NLog config

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

  <!-- 
  See https://github.com/nlog/nlog/wiki/Configuration-file 
  for information on customizing logging rules and outputs.
   -->
  <targets async="true">
    <target xsi:type="File"
            name="file"
            fileName="${basedir}/logs/${logger}_${shortdate}.log"
            archiveFileName="${basedir}/archives/log.{#}.txt"
            archiveEvery="Day"
            archiveNumbering="Rolling"
            maxArchiveFiles="7"
            enableArchiveFileCompression="true"
            layout="${longdate} ${logger} ${message}"  />
    <target xsi:type="ColoredConsole"
          name="console"
          layout="${longdate} ${logger} ${message}"  />
  </targets>
  <rules>
    <logger name="*" minlevel="Trace" writeTo="file,console" />
  </rules>
</nlog>
```

**Comment by umu24013** [comment]
Just found out that archiving would not work, if we have a date in the original log filename

**Comment by 304NotModified** [comment]
That sounds like a bug?

**Comment by umu24013** [comment]
I did not know that archiving would not work if the fileName parameter contains a date. This is not mentioned in the docs, and this is not something that can be easily guessed. After I opened this issue, I found a post at StackOverflow describing this specific behavior of NLog. Anyway, thanks for the great product!

**Comment by 304NotModified** [comment]
Thanks for info! We consider this as a bug, so reopen :)

**Comment by bhaeussermann** [comment]
I shall look into it ;)

**Comment by 304NotModified** [comment]
:+1:
