### ISSUE TITLE
Integrating custom thread safe target

### ISSUE THREAD

**Issue by LeonidVasilyev** [NLog/NLog#1272]
I developed custom target for Azure Storage Table. It's thread safe. Throughput under load is pretty bad If I use my target without `AsyncWrapper`. And It seems like that is because only single `Write(LogEventInfo logEvent)` call execute at the same time. I've noticed that `Write(LogEventInfo logEvent)` call is surrounded by `lock (SyncRoot)` in NLog source code. Are all calls to all targets are blocking? It is possible to provide non-blocking access to my target? Or should I use only `Write(NLog.Common.AsyncLogEventInfo[] logEvents)` method together with `AsyncWrapper` to get higher throughput?

**Type** (choose one):

- Question

**NLog version**: (e.g. 4.2.3)

**Platform**: .Net 4.5

**Comment by 304NotModified** [comment]
> . I've noticed that Write(LogEventInfo logEvent) call is surrounded by lock (SyncRoot) in NLog source code. Are all calls to all targets are blocking?

Yes, for the order of the events.

> Or should I use only Write(NLog.Common.AsyncLogEventInfo[] logEvents)

That is indeed the way to improve performance. :+1:

**Comment by 304NotModified** [comment]
Has your question being answered?

**Comment by LeonidVasilyev** [comment]
@304NotModified, yes, thank you.

**Comment by 304NotModified** [comment]
Cool, will close this issue :)
