### ISSUE TITLE
Archive file not created

### ISSUE THREAD

**Issue by Bidou44** [NLog/NLog#1277]
With the following configuration, the archive file is not created (I do not have any error message). I tested for this month (february/march) so it may have something to do with the 29 february (?). I'm using NLog 4.2.3 with .Net 4.6

    <target name="File" xsi:type="File" fileName="${basedir}/${shortdate}.log" 
          keepFileOpen="false" encoding="iso-8859-2"
          layout="${longdate}|${pad:padding=5:inner=${level:uppercase=true}}|${message} ${exception:format=tostring}"
          archiveFileName="${basedir}/archive.{#}.zip" archiveNumbering="Date"
          archiveDateFormat="MMMMyyyy" archiveEvery="Month" 
          maxArchiveFiles="24" enableArchiveFileCompression="true" />

Edit: this could be related to https://github.com/NLog/NLog/issues/1271

**Comment by 304NotModified** [comment]
I'm pretty sure this is https://github.com/NLog/NLog/issues/1271
which will be fixed in https://github.com/NLog/NLog/pull/1274


@bhaeussermann can you confirm this? Any idea when this bug has been introduced?

**Comment by 304NotModified** [comment]
@Bidou44 can you test this with NLog 4.3-RC2?

**Comment by 304NotModified** [comment]
This is probably fixed in 4.3. If not, just let us know
