### ISSUE TITLE
Archives are named with the previous date of the current date 

### ISSUE THREAD

**Issue by FBoCP** [NLog/NLog#1278]
**Type** (choose one):
- Bug

**NLog version**: 4.1.2

**Platform**: .Net 4.6.1

**Current NLog config** (xml or C#, if relevant)

**Procedure to reproduce the issue**:
- with an appli that uses NLog
- Start the appli (make sure appli.log and appli.errors.log files have been created)
- Note the date of the day [example: 02/03/2016)
- Close the appli
- wait several days (or change the PC date) [example: 22/03/2016]
- Start the appli
- Check the archives name

**Current result**:
- The file that was created on 02/03/2016 has been archived: that's OK.
- The file has been renamed with a suffix. This suffix contains the date of the previous day of the current one and not the one when the file was created.
[example: appli.2016-03-21.log and appli.errors.2016-03-21]

**Expected result**:
- When archiving a .log file and a .error.log file, NLog should use the modification or creation date but not the previous day of today. If the appli is not started everyday, file names are not correct.

- Are there any work arrounds? No
- Is there a version in which it did worked? Don't know (1st version I try)

**Comment by DuAell** [comment]
Config used for this test : 

<target name="logfile" xsi:type="File" fileName="${basedir}/logs/appli.log" layout="${longdate} ${uppercase:${level}} ${logger} ${message} ${exception} -> ${callsite}" archiveEvery="Day" archiveNumbering="Date" archiveFileName="${basedir}/logs/archives/appli.{#}.log" archiveDateFormat="yyyy-MM-dd" maxArchiveFiles="9" />

**Comment by 304NotModified** [comment]
Hi, 

This has been fixed in 4.3. Will release a beta or RC this week.

**Comment by 304NotModified** [comment]
Fixed so close. If this is still an issue, please let us know
