### ISSUE TITLE
Integrate SQL commands within layout of a parameter

### ISSUE THREAD

**Issue by bivokasaju** [NLog/NLog#1280]
I am aware my current NLog.config file doesn't work because of the line:
```xml
 <parameter name="@logtype_id"         layout="${select id from dbo.tracelog where lookup_category = 'Tracelog' and description = '${level}'}" />
```

However, I want to make this work, and this would make my work so much simpler if the layout section executed SQL commands the way I have put it. I want to use the return value from that SELECT statement and pass it to @logtype_id parameter that is of type int, which depends on what ${level} returns.

Is there a better way of doing this? I don't seem to get the concept of making custom Layout Renderers or custom Targets because they can't use the "${level}" on which the whole SQL command depends.

**Type** (choose one):

- Question

**NLog version**: (e.g. 4.2.3)

**Platform**: .Net 4.5 
**Current NLog config** (xml or C#, if relevant)

```xml

<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="false"
      internalLogLevel="Trace" internalLogFile="C:\logs\nlog-internal.log" >

  <targets>

    <target name="database" xsi:type="Database"
            dbUserName="internwebuser"
            dbProvider="System.Data.SqlClient"
            connectionStringName="SECURE"
            connectionString="Data Source=server.com;Initial Catalog=Db;User ID=userId;Password=password"
            commandText="insert into dbo.tracelog (logtype_id, page_name, custom_message, excep_message, insertdate) 
            values 
            (@logtype_id, @page_name, @custom_message, @excep_message, @insertdate);" >
      

      <parameter name="@logtype_id"         layout="${select id from dbo.tracelog where lookup_category = 'Tracelog' and description = '${level}'}" />
      <parameter name="@page_name"          layout="${aspnet-request:serverVariable=Url}" />
      <parameter name="@custom_message"     layout="${exception}" />
      <parameter name="@excep_message"      layout="${exception:tostring}" />
      <parameter name="@insertdate"         layout="${date}" />

    </target>

    <target name="file" xsi:type="File"
            layout="${longdate} ${uppercase:${level}} ${callsite} from Line: ${callsite-linenumber} ${newline} 
${exception} ${newline}
${exception:tostring} ${newline}"
            fileName="${basedir}/logs/${shortdate}-${level}.log" />
    
  </targets>  
  
  <rules>

    <logger name="*" minlevel="Debug" writeTo="file" />
    <logger name="*" minlevel="Debug" writeTo="database" />
    
  </rules>
</nlog>

```

**Comment by 304NotModified** [comment]
Well you need some C# code on this.

You can set the of course the layout for the @logtype_id from the API.

But if we like a more generic approach (which needs also some c#). I was thinking of

1. Create a custom TargetWrapper (inherit from [`WrapperTargetBase`](https://github.com/NLog/NLog/blob/master/src/NLog/Targets/Wrappers/WrapperTargetBase.cs)
2. Config which settings to set in the wrapped target ("database" in this case")
3. Do the query (from config) on install (or `InitializeTarget`). For the first you need `IInstallable`

**Comment by bivokasaju** [comment]
@304NotModified Would you be able to provide with some examples? I'm using NLog for the first time and I have very little idea on what you're talking about. My only C# code that's NLog related is:
`private static Logger logger = LogManager.GetCurrentClassLogger();`
and inside a catch:
` logger.Error(e);`
where e is the exception.

I tried creating a custom Layout Renderer but I don't seem to get it working:

 ```
[LayoutRenderer("logtype_id")]
    public class NLogLayoutRenderer : LayoutRenderer
    {
        SqlConnection conn = new SqlConnection("Data Source=sqlservtest.starledger.com;User ID=user;Password=password;");
        SqlDataReader rdr = null;
       
        int logtype_id = 0;

        protected override void Append(StringBuilder builder, LogEventInfo logEvent)
        {
            try
            {
                if (conn.State != ConnectionState.Open) conn.Open();
            }
            catch (Exception e)
            {
                <!-- some catch statement -->
            }

            string sql = "select id from dbo.tracelog where lookup_category = 'Tracelog' and description = '${level}'";
            SqlCommand cmd = new SqlCommand(sql, conn);

            rdr = cmd.ExecuteReader();

            while (rdr.Read())
            {
                logtype_id = System.Convert.ToInt16(rdr["id"]);
            }

            builder.Append(logtype_id);
        }
    }
```

and then I tried using ${logtype_id} as the layout for the @logtype_id parameter but it doesn't work.

**Comment by 304NotModified** [comment]
Ah,

well it's advanced level ;)

Any way, please check this post http://nlog-project.org/2015/06/30/extending-nlog-is-easy.html

And let me afterwards know what sentences are unclear.

**Comment by bivokasaju** [comment]
@304NotModified  Thanks for the link, but I have been there already and based on that I have written my custom Layout Renderer code above. That's the best I could from that page.

**Comment by 304NotModified** [comment]
> @304NotModified Thanks for the link, but I have been there already and based on that I have written my custom Layout Renderer code above. That's the best I could from that page.

OK! Let's check your code.

I think your "logtype_id" layout renderers is also nice. It's less generic (as the query is in the layout renderer), but you should get it working.

What isn't working? Is there an exception?

Any way what I think is wrong or missing:

1. Register the `NLogLayoutRenderer` (maybe you did that already)
2. `${level}` won't work in your query. Replace this with `logEvent.Level` (and string.format)
3. if you can't get it working, just log your custom logger. e.g. `InternalLogger.Debug("init")` etc. (and [set-up the internal logger](https://github.com/NLog/NLog/wiki/Logging-troubleshooting#internal-logging))

PS:
you can also use `ExecuteScalar` instead of `ExecuteReader`

**Comment by bivokasaju** [comment]
@304NotModified Thanks for the pointer no. 2, I knew that string wouldn't work but I had no idea what else to put.

I don't think my custom Layout Renderer is being read by the NLog.config file so I'm getting this error:

`LayoutRenderer cannot be found: 'logtype_id'`

Where should I put my customer Layout Renderer code? Currently it's in a class in the Data Access Layer folder.

**Comment by 304NotModified** [comment]
You should register your layout renderer

e.g. in `main()` or `app_start`

```c#
//register
    ConfigurationItemFactory.Default.LayoutRenderers
          .RegisterDefinition("logtype_id", typeof(NLogLayoutRenderer);

```

**Comment by bivokasaju** [comment]
@304NotModified YESSSSS!!! I needed that!!  A bunch of other errors that I could figure out myself! Thank YOU so much! I got what I needed now! You're the best.....

**Comment by 304NotModified** [comment]
:)

**Comment by 304NotModified** [comment]
Can we close this issue?

**Comment by bivokasaju** [comment]
yes definitely
