### ISSUE TITLE
Callsite render bug in NLog 4.3

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#1287]
See https://github.com/castleproject/Core/issues/146#issuecomment-192170388

**Comment by 304NotModified** [comment]
@jeremymeng / @jonorossi

Can you help us with a proper unit test?

**Comment by 304NotModified** [comment]
@jeremymeng / @jonorossi

Found it already :) And Fixed :)

**Comment by jeremymeng** [comment]
Thanks for the quick fix @304NotModified! Any chance of a new alpha package with the fix? :smiley:

**Comment by 304NotModified** [comment]
Will try that this week :) 

(needs merge master => coreclr branch)

**Comment by 304NotModified** [comment]
@jeremymeng

This has been fixed in NLog 4.3.0-beta3 and NLog 4.4.0-alpha4 and released now on [NuGet](https://www.nuget.org/packages/NLog).
