### ISSUE TITLE
How to pass only one Logger to write to a file/db?

### ISSUE THREAD

**Issue by bivokasaju** [NLog/NLog#1288]
**Type** (choose one):

- Question

**NLog version**: (e.g. 4.2.3)

**Platform**: . .Net 4.5

If I have the following code in my controller:

```
namespace MyReport.Controllers
{
    public class ReportController : Controller
    {
        private static Logger customMsg = LogManager.GetCurrentClassLogger();
        private static Logger excepMsg = LogManager.GetCurrentClassLogger();
        public ActionResult Index()
        {
         try 
         { --- statement --- }
         catch (Exception e)
            {
                customMsg.Error("Custom message");
                excepMsg.Error(e);
            }   
            return View();
        }
}


```

What should my rules look like in order to write only customMsg to a file/db, or only excepMsg, but not both?

**Comment by 304NotModified** [comment]
Is the full name (including namespace) of the class.  

If you log `${logger}` to your logs, you can see it :)

**Comment by bivokasaju** [comment]
So is it only upto the controller name? `MyReport.Controllers.ReportController` in my case? How do I specifically call the `customMsg` logger from my NLog.config file?

**Comment by 304NotModified** [comment]
You need then `LogManager.GetLogger("name1")`

**Comment by 304NotModified** [comment]
Keep in mind your can't "pass"  loggers. You write to loggers, and with rules the messages get passed to targets. 

Loggers has names, and the currentClassLogger is a logger with a name from the current class.

**Comment by bivokasaju** [comment]
By name1 in `LogManager.GetLogger("name1")` do you mean the full name including namespace? I

**Comment by 304NotModified** [comment]
I was thing of

```c#
        private static Logger customMsg = LogManager.GetLogger("custom");
        private static Logger excepMsg = LogManager.GetLogger("excep");
```

and in your config:

```xml
  <rules>
<!-- control here what get logged to the file target, use enabled attribute for example, or filters -->
    <logger name="custom" minlevel="Trace" writeTo="file" enabled="true" />
    <logger name="excep" minlevel="Trace" writeTo="file" enabled="true"/>
  </rules>

```

**Comment by Page-Not-Found** [comment]
Do you mean, you want to have multiple files but still use the one logger.

**Comment by 304NotModified** [comment]
Ah that could also be the case.

**Comment by bivokasaju** [comment]
I need a custom message as well as the exception of catch statement written to a database table, but I can only send one at a time as the parameter. Therefore I'm thinking of using two loggers, one to send exception message and the other to send a string of custom message. Then, both loggers would write to the same table simultaneously in different columns (I will configure the config file accordingly in `<target>` and `<rules>` for that. @304NotModified I will try your method and let you know how it goes. @Page-Not-Found It's exactly the opposite case, one database table but multiple loggers.

**Comment by bivokasaju** [comment]
@Page-Not-Found If I could, I would do it with only one logger, that doesn't matter. I'm using multiple loggers only because I can't seem to get the work done with one, i.e. passing a string of custom message as well as the exception (from catch statement) both together for logging into the database table.

**Comment by bivokasaju** [comment]
@304NotModified Working perfectly as I wanted. One problem though, it is writing in two separate rows, I want to combine them into single one.

```
<target name="DbCustom" xsi:type="Database"
           commandText="insert into dbo.tracelog (custom_message) 
            values 
            (@custom_message);" >
      <parameter name="@custom_message"         layout="${message}" />
    </target>

<target name="DbExcep" xsi:type="Database"
           commandText="insert into dbo.tracelog (excep_message) 
            values 
            (@excep_message);" >
      <parameter name="@excep_message"         layout="${exception}" />
    </target>

<rules>
<logger name="excep" minlevel="Debug" writeTo="DbExcep" />
<logger name="custom" minlevel="Debug" writeTo="DbCustom" />
</rules>
```

Any suggestions?

**Comment by 304NotModified** [comment]
Yes, every entry will be a log record.

Can you elaborate on your case? As I don't fully understand what we're trying to achieve.

**Comment by bivokasaju** [comment]
My database table has custom_msg and excep_msg columns. I want to pass a custom string for custom_msg column, and the catch statement's exception for excep_msg column, both in a single row of the table for each error/exception that occurs. The above method is logging custom and excep messages into two different rows, rendering the other one NULL in each case. So, in the table, instead of 
```
excep_msg     custom_msg
``` 
I get
```
excep_msg     NULL
NULL          custom_msg
```

**Comment by 304NotModified** [comment]
Well that's a common thing :)

You can:

1. Use 1 logger and 1 write statement: `logger.Error(e,"Custom message"); //e = exception. In the logger you use [`${exception}`](https://github.com/NLog/NLog/wiki/Exception-Layout-Renderer) and `${message}

2. You use logevent-properties. E.g.

```
LogEventInfo theEvent = new LogEventInfo(LogLevel.Debug, "", "Pass my custom value");
theEvent.Properties["MyValue"] = "My custom string";
log.Log(theEvent);
```

You can then use [`${event-properties}`](https://github.com/NLog/NLog/wiki/EventProperties-Layout-Renderer).. 

3. and/or you can use the fluent interface: http://nlog-project.org/2015/01/20/have-you-seen-our-new-fluent-interface.html

**Comment by bivokasaju** [comment]
I am 100% sure I had tried passing it that way `logger.Error(e, "Custom message")` and it had given me some weird error saying I can only pass one parameter. Maybe coz I'm using `GetLogger('name') `instead of `GetCurrentClassLogger()` that's why I'm not getting error. Anyways, my code is working perfectly, can't thank you enough. :100:  :+1:   :)

**Comment by 304NotModified** [comment]
GetLogger and GetCurrentClassLogger retuning the same type.  The only difference is the name. 

I'm glad that it all works now :)

**Comment by bivokasaju** [comment]
I have no idea why I got the error then, and not now! Anyways, I'm glad too. :) Thanks mucho!
