### ISSUE TITLE
How to remove a Logger from LogManager ?

### ISSUE THREAD

**Issue by alex1github** [NLog/NLog#1289]
**Type** 

- Question

**NLog version**:  4.2.3

**Plattform**:  Net 4.5

I need a Logger per object instance (with different names like 'TypeName+UniqueInstanceName'). How i can remove the associated Logger from LogManager after disposing of object instance? 
Alternatively: Can i create a Logger without LogManager?

**Comment by 304NotModified** [comment]
Hi, 

You can't remove loggers, but that's also never needed. You can filter messages in the NLog config rules, or just remove/disable the rule to the target.  

You can also use LogFactory to create a logger. 
See http://nlog-project.org/documentation/v4.0.0/html/T_NLog_LogFactory.htm

**Comment by 304NotModified** [comment]
Has your question being answered?

**Comment by alex1github** [comment]
yes, thank you
