### ISSUE TITLE
Confusing behavior when logging exceptions

### ISSUE THREAD

**Issue by StevenLiekens** [NLog/NLog#1290]
**Type**
Improvement

**NLog version**
4.0 and up

**Platform**: all supported platforms

**Current NLog config**
Console target with all default options.
```c#
var loggingConfiguration = new LoggingConfiguration();
var consoleTarget = new ConsoleTarget { Name = "console" };
loggingConfiguration.AddTarget(consoleTarget);
loggingConfiguration.LoggingRules.Add(new LoggingRule("*", LogLevel.Trace, consoleTarget));
LogManager.Configuration = loggingConfiguration;
```
The important bit for this issue is the default layout renderer: **exceptions are not rendered by default**.
```powershell
${longdate}|${level:uppercase=true}|${logger}|${message}
```

This results in confusing behavior between...
```c#
try
{
    throw new Exception("Oops!");
}
catch (Exception e)
{
    logger.Error(e);
}
// 2016-03-05 10:29:33.5846|ERROR|ConsoleApplication1.Program|System.Exception: Oops!
//   at ConsoleApplication1.Program.RealMain() in d:\users\steven\documents\visual studio 2015\Projects\ConsoleApplication1\ConsoleApplication1\Program.cs:line 31
```
and...
```c#
try
{
    throw new Exception("Oops!");
}
catch (Exception e)
{
    logger.Error(e, "Something went wrong");
}
// 2016-03-05 10:29:33.5846|ERROR|ConsoleApplication1.Program|Something went wrong
```
In the first sample, only the exception is passed to `Error(...)`
 - Call resolves to `ILogger.Error<T>(T)` where `T` is the exception type
 - NLog renders `${message}` as the return value of `T.ToString()`
 - **NLog does not invoke `${exception}` layout renderers** (if any)

In the second sample, the exception and a message were passed to `Error(...)`
 - Call resolves to `ILogger.Error(Exception, string, object[])`
 - NLog renders `${message}` as the value of the second argument after formatting
 - NLog **would have** rendered `${exception}` as the value of `Exception.Message`
     - **The default layout does not contain the `${exception}` layout renderer**

**Comment by StevenLiekens** [comment]
Suggested fixes:

1. Add `${exception}` to the default layout
2. Change implementation of `ILoggerBase.Log<T>(LogLevel, T)` to call `ILoggerBase.Log(LogLevel, Exception, string, object[])` when `T is Exception`

**Comment by 304NotModified** [comment]
Thanks! 

Can you split this into 2 issues? That makes it easier to discuss and fix.  Thanks in advance!

**Comment by 304NotModified** [comment]
Thanks! I will close this one as there are 2 new issues.
