### ISSUE TITLE
Add special handling for exceptions in Log<T>(...)

### ISSUE THREAD

**Issue by StevenLiekens** [NLog/NLog#1291]
NLog should **never** render `${message}` as the return value of `Exception.ToString()`. Instead render `${message}` as the value of `Exception.Message` when no other message is specified by  the caller.

``` c#
catch(Exception e)
{
    // No message was passed -> render ${message} as e.Message instead of e.ToString()
    logger.Error(e);
}
```

Relates to #1290

**Comment by 304NotModified** [comment]
I guess this is the same as https://github.com/NLog/NLog/issues/1034? (or at least highly related).

**Comment by StevenLiekens** [comment]
Yes, looks like it is about the same with one difference: the `message:withException` option. I'm not sure what problem this option is meant to solve.

**Comment by StevenLiekens** [comment]
I just tried it and I think that `message:withException=true` is broken.

The result of `Error(Exception)` with this option is that `${message}` is rendered as
`Exception.ToString() + "\r\n" + Exception.ToString()`
