### ISSUE TITLE
System.OutOfMemoryException on NLog which causes our application to hang

### ISSUE THREAD

**Issue by luckytester** [NLog/NLog#1293]
Hi! Thanks for reporting this feature/bug/question! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

**Type** (choose one):
- Bug

**NLog version**: 4.2.0

**Platform**:  .Net 4.5 (.NET FRAMEWORK 4.6.1 Installed)

**Current NLog config** (xml or C#, if relevant)

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="true"
      internalLogLevel="Off" internalLogFile="c:\temp\nlog-internal.log" >
	<variable name="LogHome" value="D:/Logs/BusinessEngine"/>
    <targets>
        <target name="file" xsi:type="File"
            layout="${longdate}|${threadid}|${level}|${callsite}	${message}	${exception:format=ToString}" 
            fileName="${LogHome}/log.txt"
			archiveAboveSize="26214400"			
            archiveFileName="${LogHome}/Archive/{#}.txt"
            archiveEvery="Hour"
            archiveNumbering="DateAndSequence"
			archiveDateFormat="yyyyMMdd_HH_mm"
            maxArchiveFiles="168"
            concurrentWrites="true"
            keepFileOpen="false"
            encoding="iso-8859-2" />
    </targets>
    <rules>
        <logger name="*" minlevel="Info" writeTo="file" />
    </rules>
</nlog>
```

In case of a BUG:

- What is the current result?
Our application is running as Windows Service in Windows Server 2012 R2 and uses NLog as the logging platform for application logs, We could see that the application runs for 8-10 hours and then hangs itself due to OutofMemoryException.

Request to help this issue as we have to always restart the application when OutofMemoryException is thrown.

- What is the expected result?
No out of memory issue from Logger and application must smoothly work with logger.

- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
Not yet but added and waiting for results

- Please post full exception details (message, stacktrace, inner exceptions)

```
An exception being caught Exception of type 'System.OutOfMemoryException' was thrown. System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.IO.FileStream.Write(Byte[] array, Int32 offset, Int32 count)
   at NLog.Internal.FileAppenders.RetryingMultiProcessFileAppender.Write(Byte[] bytes)
   at NLog.Targets.FileTarget.WriteToFile(String fileName, LogEventInfo logEvent, Byte[] bytes, Boolean justData)
   at NLog.Targets.FileTarget.Write(LogEventInfo logEvent)
   at NLog.Targets.Target.Write(AsyncLogEventInfo logEvent)
   at NLog.Targets.Target.WriteAsyncLogEvent(AsyncLogEventInfo logEvent)
   at NLog.LoggerImpl.WriteToTargetWithFilterChain(TargetWithFilterChain targetListHead, LogEventInfo logEvent, AsyncContinuation onException)
   at NLog.LoggerImpl.Write(Type loggerType, TargetWithFilterChain targets, LogEventInfo logEvent, LogFactory factory)
   at NLog.Logger.WriteToTargets(LogLevel level, IFormatProvider formatProvider, String message)
   at NLog.Logger.Info(String message
```

- Are there any work arrounds? yes
Restart the application after 'System.OutOfMemoryException' Exception

- Is there a version in which it did worked? 
No, we went Live recently and able ti identify after that only

- Can you help us by writing an unit test?
Yes, of course We need an urgency to fix this as our production run is seriously affected.

in case of a FEATURE REQUEST:
 
 - Why do we need it?
 - An example of the XML config, if relevant.

**Comment by 304NotModified** [comment]
Hi, 

Can you try without the archiving feature? 

I use a related config for months in Windows services, without a memory leak

**Comment by luckytester** [comment]
Yes we can do it temporarily, but worried about loosing some important data which says how the application is behaving currently and any errors has happened during run. Try without archiving in production setup is the last thing we would like do.

**Comment by luckytester** [comment]
Was reviewing the code to check any NLog configuration missing out or for wrong usage, We have the following usage in many module classes (38 exactly) and not from a single Utils class file

private static Logger logger = LogManager.GetCurrentClassLogger();

Could it be issue with above usage as we having multiple logger instances (38) writing same NLog target file ? All are static objects.

**Comment by 304NotModified** [comment]
> Was reviewing the code to check any NLog configuration missing out or for wrong usage, We have the following usage in many module classes (38 exactly) and not from a single Utils class file

That isn't a problem. At work we have windows services with +50 of those.

> Yes we can do it temporarily, but worried about loosing some important data which says how the application is behaving currently and any errors has happened during run. Try without archiving in production setup is the last thing we would like do.

Well you don't have to remove old logs files.

What I trying to propose:

Use the filetarget, but without the archiving feature. We write to separate logs every day. Downside, you need to clean up log files manually or with another process. 

e.g.

```xml
 <target name="file" xsi:type="File" fileName="${logDirectory}\${date:format=yyyy-MM}\log_4_${shortdate} (${date:format=ddd:culture=nl}).txt" 

```

**Comment by luckytester** [comment]
This configuration helped us and it seems to be System.OutOfMemoryException is coming from a particular module in our code so we guess its not a NLog related problem.

Thanks for the help !

**Comment by 304NotModified** [comment]
OK thanks for the feedback!
