### ISSUE TITLE
Create constructors with name for every target

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#1297]
For easier API usage.

~ 38 targets

- [ ] Add Constructor with `string name`. Call `this()`, after the default ctor
- [ ] Add default constructor if it isn't there
- [ ] write unit test with reflection to test all constructors (default + named). test also that default+named ctor will yield the same results.

NB: no extra contructor needed in base class (Target) because this will lead to (more) code duplication.

Before:

```c#
/// <summary>
/// Initializes a new instance of the <see cref="FileTarget" /> class.
/// </summary>
/// <remarks>
/// The default value of the layout is: <code>${longdate}|${level:uppercase=true}|${logger}|${message}</code>
/// </remarks>
public FileTarget()
{
	this.ArchiveNumbering = ArchiveNumberingMode.Sequence;
	this.maxArchiveFiles = 0;
	this.ConcurrentWriteAttemptDelay = 1;
	....
}  
```

after
```c#
/// <summary>
/// Initializes a new instance of the <see cref="FileTarget" /> class.
/// </summary>
/// <remarks>
/// The default value of the layout is: <code>${longdate}|${level:uppercase=true}|${logger}|${message}</code>
/// </remarks>
public FileTarget()
{
	this.ArchiveNumbering = ArchiveNumberingMode.Sequence;
	this.maxArchiveFiles = 0;
	this.ConcurrentWriteAttemptDelay = 1;
      ....
}
/// <summary>
/// Initializes a new instance of the <see cref="FileTarget" /> class.
/// </summary>
/// <param name="name">Name of the target.</param>
/// <remarks>
/// The default value of the layout is: <code>${longdate}|${level:uppercase=true}|${logger}|${message}</code>
/// </remarks>
public FileTarget(string name) : this()
{
	this.Name = name;
}    
```

**Comment by tetrodoxin** [comment]
The tricky part is, to compare resulting objects, because if you compare them property-wise by reflection, you have to deep-compare `Layout` objects, since they do not implement a customized `Equals` method.

**Comment by 304NotModified** [comment]
The layout is a simple case, as those are mostly simplelayout and a tostring is sufficient.  Anyway, those are addressed in the PR. :)
