### ISSUE TITLE
MailTarget and configure Nlog programatically, am I missing something?

### ISSUE THREAD

**Issue by venkateshsj** [NLog/NLog#1300]
**Type** (choose one):
- Question

**NLog version**: (e.g. 4.2.3)
- Runtime version - v4.0.30319
- Version - 4.0.0.0

**Platform**: 
- .Net 4.5

The attachment contains code of the following:
1. Nlog.config
2. NlogConfig.cs
3. web.config
[additional-info.txt](https://github.com/NLog/NLog/files/171425/additional-info.txt)

******************************************************************************************************************************
MY QUESTION:
******************************************************************************************************************************
I must tell you that I am fairly new to ASP.NET MVC. So maybe I might have done some silly mistake. I have integrated Nlog in my application just as given on your site. The .html file gets generated properly as expected whenever an expection occurs. I am using this along with the Common.Logging package.

Issue 1:
The MailTarget does not work for me. I am not receiving emails whenever an exception occurs. The credentials mentioned in the code above are junk, but I have mentioned valid credentials in the actual code. The same credentials works correctly for sending email from code on certain events.

Issue 2:
I am trying to override the Nlog.config settings by writing the same in a class file. Now I am not understanding as to how to override the Nlog.config settings with the one written in the class. I wrote the class as given in the help. The debugger does not go this class, so the actions are taking place as mentioned in the Nlog.config. If I exclude the config file, then nothing happens. Where should I mention the reference of the class file instead of the Nlog.config file? 

I need  your assistance on these difficulties that I am facing. I hope to receive your reply at the earliest. Thanks in advance.

**Comment by venkateshsj** [comment]
My MailTarget issue has got resolved. I had missed to mention the MailTarget name in the rules section in the Nlog.config file. 

Refer the attachment for the .html file that has been generated. 
[Log-2016-03-14.zip](https://github.com/NLog/NLog/files/171436/Log-2016-03-14.zip)

There are certain errors that are being generated due the the MailTarget. I am not understanding those. Due to this I am receiving a lot many emails along with the actual error everytime an exception is generated. Have I missed something again or is there any other reason for these errors being generated? Please guide on this one too.Thanks in advance.

**Comment by venkateshsj** [comment]
**Issue 1** stands resolved completely. Sorry for the additional comments. I had mentioned the <system.diagnostics> section in the web.config which was causing the additional errors being generated along with the actual one. Now I am not sure whether this section is really essential or not.

Kindly please guide me on my **Issue 2** as mentioned earlier. Thanks in advance.

**Comment by 304NotModified** [comment]
Hi! Glad your first issue has been solved. 

About 2, do you need https://github.com/NLog/NLog/wiki/Configuration-API ?

**Comment by venkateshsj** [comment]
Firstly I would like to thank you for your prompt reply, secondly I am sorry to reply late, was tied up in a priority task.

Like I mentioned in my question, I have already done as you mentioned in the link,
https://github.com/NLog/NLog/wiki/Configuration-API

Refer the NlogConfig.cs class, in the attachment provided earlier, for the code as written by me to configure Nlog programatically. 

I have this class file in a folder called as 'Classes' in my MVC application. Whenever I run the application, it refers the settings from the Nlog.config file and logs the error accordingly. When I exclude the Nlog.config file, no error is logged even when I have this NlogConfig.cs class in my application, this means the application is not getting the reference to the settings as defined in the NlogConfig.cs class file.

Now where should I give the reference of this class so that the application refers the settings mentioned in the class instead of those mentioned in the Nlog.config file?

**Comment by 304NotModified** [comment]
Do you like to configure NLog from **both** API (C#) and nlog.config?

Note:

```
 // Step 5. Activate the configuration
            LogManager.Configuration = config;
```

Will discard the nlog.config settings (as you overwrite the config object).

**Comment by venkateshsj** [comment]
The version of NLog that is installed is **4.2.3**.

It does not have a provision to give the "path to nlog.config" like you mentioned. It gives an error that the **"'LoggingConfiguration' does not contain a constructor that takes 1 argument."**.

Yes, I do want to configure NLog from API (C#). Nlog.config (xml) is not essential for me and can be skipped/excluded if not required.

I have now mentioned different settings in the API and in the .config file. Still errors are being logged as per those in the .config file. The debugger never goes to the NLogConfig.cs. So my question still stands the same - do I need to provide a reference of this class anywhere so that the application overrides the settings defined in the .config file.

I know I may be asking too much, but is it possible for you to provide me with a working sample where the configuration settings in .config (XML) file are being overridden by those written in API (C#)? This way I can at least compare and check what I may be doing wrong.

Thanks in advance.

**Comment by venkateshsj** [comment]
**Just in case you might need this info:**
I have created an ASP.NET MVC 5 application in which I am trying to integrate Nlog. I have also integrated JSNLog. Both work fine and log javascript as well as server side exceptions when the configuration resides in the Nlog.config file located in the root folder of the application. I have removed the Nlog.config file from the 'Bin' folder.

**Comment by 304NotModified** [comment]
> It does not have a provision to give the "path to nlog.config" like you mentioned. It gives an error that the "'LoggingConfiguration' does not contain a constructor that takes 1 argument.".

I mean [`new XmlLoggingConfiguration`](https://github.com/NLog/NLog/blob/5c679c3779786f3c8c034ef3da12e10a2474abfa/src/NLog/Config/XmlLoggingConfiguration.cs#L87)

**Comment by venkateshsj** [comment]
Nope. Didn't work. I changed the code as follows,
// Step 1. Create configuration object 
//var config = new LoggingConfiguration();
var config = new XmlLoggingConfiguration("~/NLog.config");

Rest of the code remains same. I hope I have done it right as above. It is still referring the settings as defined in the Nlog.config file and not as overridden in the API (C#).

I would really appreciate if a working sample is provided. This way I will know exactly what I am missing. I know I am asking a bit too much, but then it would really be helpful and solve my problem once and for all.

Thanks in advance...

**Comment by 304NotModified** [comment]
I think I don't fully understand the problem.  

Is you configuration made in the api (c#) not applied? How can you see that? As the aren't calls to a logger.

**Comment by venkateshsj** [comment]
Kindly refer the attached code that I have extracted to create a sample appn for your perusal. Currently MailTarget is not working, ignore the same. I have mentioned junk details for MailTarget. Then.html file is getting generated as per settings mentioned in the Nlog.config file located at the root. I have written a class 'NologConfig.cs' located in the 'Classes' directory. This class contains the settings written to be overridden over those written in the Nlog.config file.

Now where should I give reference of this class so that the xml settings are overridden by those written in the API (C#)? The 2nd attachment is the list of packages that existed in the sample, had to delete those to upload here.

[NlogJsnLogIntegration_folder.zip](https://github.com/NLog/NLog/files/179379/NlogJsnLogIntegration_folder.zip)
![packages-list](https://cloud.githubusercontent.com/assets/7588513/13874163/02aa9144-ed1c-11e5-987b-fc28daf34e56.jpg)

**Comment by 304NotModified** [comment]
> Kindly refer the attached code that I have extracted to create a sample appn for your perusal. Currently MailTarget is not working, ignore the same.

I would be great to post the relevant code. Sorry, but I don't have time to debug every program submitted by users.

**Comment by venkateshsj** [comment]
I am so sorry for the inconvenience caused. I had already posted the relevant code in my first post. I thought that it was not enough to understand, hence uploaded the sample code too.

I am again resending you the attachment.
[Nlog-issue.zip](https://github.com/NLog/NLog/files/179454/Nlog-issue.zip)

The attachment contains code of the following:
1. Nlog.config (Nlog XML configuration)
2. NlogConfig.cs (Nlog configuration API in C#)
3. web.config

Please let me know if you need any code other than that provided above. Refer by earlier posts to know the exact problem faced by me.

**Comment by 304NotModified** [comment]
Yeah, so I'm missing calls to the logger. Where are those?

**Comment by venkateshsj** [comment]
That's exactly what I need to know. Where do I mention the call to the API? Where is the call to the Nlog.config mentioned?

**Comment by venkateshsj** [comment]
**Issue 2** is also resolved. I created a public static method containing the configuration override settings and called it prior to every call to Nlog for logging the exceptions. Thank you anyways for the valuable time you spent trying to help me.
