### ISSUE TITLE
File header

### ISSUE THREAD

**Issue by NN---** [NLog/NLog#1301]
**Question**
Is it possible to configure a file header ?
A string that will be printed only once when file is created or when it is rolled.
Very useful for CSV format where the headers must be printed only once in the file and not for each log entry.

**Comment by 304NotModified** [comment]
Yes,  see https://github.com/NLog/NLog/wiki/File-target#layout-options

**Comment by 304NotModified** [comment]
I assume your question has been answered. If not, please let us know!
