### ISSUE TITLE
Allow  "nlog.config.path" in <AppSettings>

### ISSUE THREAD

**Issue by deadlydog** [NLog/NLog#1305]
**Type**: Feature request

**NLog version**: 4.2.3

**Platform**: .Net 4.5

It would be nice if NLog was able to specify a different location for the NLog.config file; right now it is constrained to being located in the root of the project's output directory.  By convention we typically store our config files in a Config directory. e.g. MyProject\bin\debug\Config\NLog.config. With the currently implementation we are forced to put the file at MyProject\bin\debug\NLog.config, where there are typically hundreds of other files located.

Log4Net provides this feature by allowing the location to be specified in the app.config file's appSettings section:

```
	<appSettings>
		<!-- Reference the Log4net configuration from an external file in the Config directory to keep the app.config nice and clean. -->
		<add key="log4net.Config" value="Config\Log4net.config"/>
	</appSettings>
```

If NLog could provide a similar feature and syntax, that would be awesome.

**Comment by 304NotModified** [comment]
you can do it in C#,

`LogManager.Configuration = new XmlLoggingConfiguration("Config\Log4net.config")`

**Comment by deadlydog** [comment]
Hmmmm, I guess that's a relatively easy work around to the problem. We could just define "Config\NLog.config" as an appSetting in the app.config file, and then do something like this in code:

```
LogManager.Configuration = new XmlLoggingConfiguration(System.Configuration.ConfigurationManager.AppSettings[appSettingKeyForNLogConfigFilePath])
```

Still, it would be nice if NLog had parity with Log4Net in this regard to avoid the additional boilerplate code.

**Comment by 304NotModified** [comment]
Yes that's a nice solution. 

Agree with the feature request. How is it configured in log4net?

**Comment by deadlydog** [comment]
In Log4Net you have 2 options:
1. Put the <log4net> section directly in the app.config file itself.
2. Define the a "log4net.Config" appSetting key that specifies the path to the external file to use (as I showed above in the original question).

NLog is a little nicer in that you default to looking for an external NLog.Config file in the executable's directory without *requiring* the app setting key.  The app setting key would be nice to have for when we want to look for the external NLog.Config file in a non-standard place.

Just my 2 cents, but for the feature request, I would probably say you should look for the NLog config to use in this order:
1. The <nlog> section defined in the app.config file itself.
2. At the path defined by the "Log4Net.Config" app settings key (if the key is present and a file exists at the path).
3. At one of the other default external config file locations (e.g. NLog.config in the executable's directory).

This would preserve backwards compatibility, and make it obvious which NLog configuration was being used. i.e. it would be confusing if the NLog.Config file in the executable's directory was used instead of the one explicitly defined by the app setting key.

**Comment by 304NotModified** [comment]
> At the path defined by the "Log4Net.Config" app settings key (if the key is present and a file exists at the path).

I would prefer a nlog.config setting ;)

Maybe even "nlog.config.path" is better?

**Comment by deadlydog** [comment]
Lol, sorry, that was a copy-paste-forgot-to-modify problem there :P 
I like "nlog.config.path" as it's a little more descriptive, but that's just my personal opinion. Either one is fine :)

**Comment by 304NotModified** [comment]
yes more descriptive is preferred :)

**Comment by deadlydog** [comment]
I just updated the title to also include looking for the config file in a parent directory as well.  The NLog.config file typically doesn't change; you set it up once and forget about it.  However, we typically run multiple versions of our services, so it would be nice to have many different versions all refer to the same config file if possible, as it would mean only having to update 1 file instead of X in the case where we want to enable/disable additional logging for all versions.  Ideally it would be best to allow the "nlog.config.path" setting in the app.config to specify any relative or absolute path, as that's the most flexible. From there the client can decide how they want to use it and are not limited.

**Comment by 304NotModified** [comment]
I think the NLog.config.path in the .config is a nice feature.  

But the parent directory sentence is a bit confusing. You mean relative or absolute path and it should be possible to configure a path outside the project directory?

**Comment by deadlydog** [comment]
Yeah. It would be nice if it could handle all of the following scenarios:
`Config\NLog.config` - The config file in a Config directory that is in the same directory as the exe.
`..\NLog.config` - The config file in the parent directory of the exe.
`..\Config\NLog.config' - The config file in a Config directory in the parent directory.
`C:\NLogSettings\NLog.config` - An absolute path to the config file.

In terms of implementation, I think it's pretty straight forward when using System.IO. Even though most people won't use an absolute path, it's just nice to have the option for the rare occasion that someone does want it, although maybe that's just me going overboard now :P.

For me specifically it would be nice to have `..\Config\NLog.config' work, as our services are versioned, so we would have something like:
\MyService\1.0.0\MyService.svc
\MyService\1.0.1\MyService.svc
\MyService\2.0.0\MyService.svc
\MyService\Config\NLog.config - NLog config used by all versions of the service.

We sometimes have 20+ versions all active in production at a time, so being able to edit a single file instead of 20+ would be helpful.

**Comment by 304NotModified** [comment]
@deadlydog I was thinking about this, 

you could use [`<include`](https://github.com/nlog/NLog/wiki/Configuration-file#include-files) to load an external file and then it is possible to use layout renderers (e.g. [`${appsetting}`](https://github.com/nlog/NLog/wiki/AppSetting-Layout-Renderer) and [`${environment}`](https://github.com/nlog/NLog/wiki/Environment-Layout-Renderer). 

It think it's a nice work around. Please share your opinion :)

**Comment by deadlydog** [comment]
Hmmm, I'm not sure I follow quite what you mean and how it would look.  Are you talking about having nlog support the configSource attribute (or maybe it already does?), so you could do [something like this](http://stackoverflow.com/a/3638180/602585)?

**Comment by 304NotModified** [comment]
I don't understand.  The `<include` is almost the same as the proposed appsetting. Why doesn't it work for your use case?

**Comment by deadlydog** [comment]
Hmmm, maybe I just don't understand it fully. Can you give a link to some documentation or example of it being used?

**Comment by 304NotModified** [comment]
Currently only this example https://github.com/nlog/NLog/wiki/Configuration-file#include-files

**Comment by deadlydog** [comment]
Oh, so you could still have the entire nlog config defined in a separate file and just include it that way. Yeah, that looks like it would work. I'll give it a quick try and let you know how it goes. Thanks.

**Comment by deadlydog** [comment]
Yeah, I just tested it and it worked fine. In my app.config I had:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
	<configSections>
		<sectionGroup name="common">
			<section name="logging" type="Common.Logging.ConfigurationSectionHandler, Common.Logging" />
		</sectionGroup>
		<section name="nlog" type="NLog.Config.ConfigSectionHandler, NLog" />
	</configSections>

	<common>
		<logging>
			<factoryAdapter type="Common.Logging.NLog.NLogLoggerFactoryAdapter, Common.Logging.NLog32">
				<arg key="configType" value="INLINE" />
			</factoryAdapter>
		</logging>
	</common>

	<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" autoReload="true">
		<include file="Config\NLog.config"/>
	</nlog>
</configuration>
```
And then in Config\NLog.config I had my entire NLog config file:
```
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
			xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
			autoReload="true"
			throwExceptions="false"
			internalLogLevel="Off" internalLogFile="c:\temp\nlog-internal.log" >

	<targets>
		<target name="console" xsi:type="ColoredConsole" />
	</targets>

	<rules>
		<logger name="*" minlevel="Info" writeTo="console" />
	</rules>
</nlog>
```
That seemed to work. I'm not sure which of the <nlog> attributes would be obeyed though; the ones in the app.config vs. the ones in the external file. e.g. if `autoReload` was true in the app.config, but false in the external file, I'm not sure which one would be applied.

I think this existing functionality is good enough though to not require the additional `nlog.config.path` appSetting that we've been discussing here, so I think you can close this issue, unless you can think of another reason to keep it. Thanks!

**Comment by 304NotModified** [comment]
I think closing is the best.  No need for duplicate functionality.  

Thanks for posting the example.  About the NLog element config, I have to check the code for that.

**Comment by 304NotModified** [comment]
The `<nlog` attributes of the included file will override the ones of the parent. The lastest included file can overwrite the settings. If the include won't have any attributes, I wont reset the settings. 

In the internal log you can see which files got parsed first (you can recursively include an include etc)

**Comment by 304NotModified** [comment]
Closing this as we can use `<include ` .
