### ISSUE TITLE
Nested JSON Layouts configured in NLog.config

### ISSUE THREAD

**Issue by mccabela** [NLog/NLog#1306]
Hi,

I'm trying to output my exception detail in a JSON structure with the config being done in the NLog.config.  

At the moment the, in the example below, the exception is being rendered as a string.

I had a look at https://github.com/NLog/NLog/wiki/JsonLayout#advanced-examples which shows that it can be done, and an example of doing it using the API, and it does mention 'This is also possible with the XML config.' but there is no example and I cannot get it working.

If you could provide me with an example of Nested JSON Layouts configured in the NLog.config that would be great.

Many Thanks,

Lach

NLog version: 4.2.3

Platform: .Net 4.6.2

Current NLog config

```xml
    <target name="file" xsi:type="AsyncWrapper" queueLimit="5000" overflowAction="Discard">
      <target xsi:type="File" fileName="${logFilePath}web.txt"
              maxArchiveFiles="100"
              archiveNumbering="Sequence"
              archiveAboveSize="${archiveFileAboveBytes}"
              archiveFileName="${logFilePath}archive/web-{#####}.txt">
        <layout xsi:type="JsonLayout">
          <attribute name="datetime" layout="${iso8601dateformat}" />
          <attribute name="level" layout="${level:uppercase=true}" />
          <attribute name="logger" layout="${logger}" />
          <attribute name="thread" layout="${threadid}" />
          <attribute name="machine" layout="${machinename}" />
          <attribute name="message" layout="${message}" />
          
          <attribute name="exception" layout="${onexception:${exception:maxInnerExceptionLevel=5:innerFormat=tostring:format=tostring}}" />
        </layout>
      </target>
    </target>
```

**Comment by 304NotModified** [comment]
Hi,

I have to agree that I also don't know how to configure this exactly from the XML config. We have to test this first.

**Comment by 304NotModified** [comment]
Hi, I have edit the wiki: https://github.com/NLog/NLog/wiki/JsonLayout

It is working as can be seen in https://github.com/NLog/NLog/pull/1309

**Comment by mccabela** [comment]
Thanks!
