### ISSUE TITLE
list of named variables

### ISSUE THREAD

**Issue by hsalim1** [NLog/NLog#1307]
Hi! 
Where can i get a list of named variables (is that what they are called?) such as basedir or shortdate?
I want to one logfile per month - so fileName="${basedir}/logs/${YearMonth}.log"

**Comment by 304NotModified** [comment]
Do you mean [layout renderers](https://github.com/NLog/NLog/wiki/Layout-Renderers) ?

**Comment by hsalim1** [comment]
Thanks.  that is what i meant.
Any chance we could have a wrapper for formatting a date so that we could say ${DateFormat:yyyy-MM}

**Comment by 304NotModified** [comment]
`${date:format=yyyy-MM} ` :)

**Comment by hsalim1** [comment]
neat!  thanks.

**Comment by 304NotModified** [comment]
:+1:
