### ISSUE TITLE
Get Layout string as it is, not rendered one

### ISSUE THREAD

**Issue by mspace** [NLog/NLog#1308]
- Question

**NLog version**: 4.2.3

**Platform**: .Net 4.5

Is there any API method that returns Layout as it is, not rendered value.

```
var runningNLogConfig = NLog.LogManager.Configuration; // running configuration
runningNLogConfig.AllTargets.Where(t => t is NLog.Targets.FileTarget).ToList().ForEach(t =>
{
  NLog.Targets.FileTarget fileTarget = t as NLog.Targets.FileTarget;
  string filename = fileTarget.FileName.ToString(); // works ok, returns in my case: "D:\\${date:format=yyyy-MM}\\${date:format=dd-MM-yyyy}_log.txt"
```

FileName.ToString() returns what I need, but is this correct approach?

**Comment by 304NotModified** [comment]
you need `fileTarget.FileName.Render(...)`

**Comment by mspace** [comment]
One solution is to cast it to SimpleLayout which has method **OriginalText**. Of course if default layout is SimpleLayout, which I suppose it is.

**Comment by 304NotModified** [comment]
Yes, that is what you need. 

All Layoutable properties of a target are `SimpleLayouts`

**Comment by mspace** [comment]
By all target you mean also DatabaseTarget, SmtpTarget. . . all targets that exist in NLog.Targets namespace ?


Just curious how come this is allowed:
```NLog.Targets.DatabaseTarget t = newNLog.Targets.DatabaseTarget();
t.CommandText = "insert into logevent .  ."; // CommandText is of type NLog.Layouts.Layout```

How can string be accepted as layout. Does c# makes this transformation or does NLog implement such convertion (some method that handles this: if typeof string returm new SimpleLayout...)

**Comment by 304NotModified** [comment]
Yes I mean a properties (with type `layout`)  of all targets like file, database. All of them are in the that namespace indeed. 

The `string` to `layout` is an implicit conversion. A c# feature.  :)

**Comment by mspace** [comment]
Thank you for pointing to source code. I see now, it creates SimpleLayout, thank you.
