### ISSUE TITLE
Get all key-values pairs from Diagnostics Context classes

### ISSUE THREAD

**Issue by tiljanssen** [NLog/NLog#1315]
**Type** :  Feature request

**NLog version**: >=4.1.1

**Platform**: .NET4.5, mono

**Description**:
I am investigating the use of GlobalDiagnosticsContext and MappedDiagnosticsLogicalContext (MDLC) for our system. 

We use a custom layout renderer that transforms the log to a json message that will be sent to a remote log collecting system. I would like to add _all_ values available in MDLC to this json message, but the methods the MDLC class only allow retrieval of a specific item.

I would like a way to get a public readonly dictionary from these classes that contain all values.

Note that MappedDiagnosticsContext makes its dictionary "internal", so that renderers in the NLog package can access the data.

**Comment by 304NotModified** [comment]
Thanks for the feature request.

We were in the middle of overhauling the context classes a few months ago, but that process has been halted due to other (more critical) features/issues. See #969 

PR accepted for the new classes/interfaces.

**Comment by tiljanssen** [comment]
It looks more like it has been halted because there is no good solution available right now. Is it an option that I supply a pull request to just update the current implementation?
It would oblige you to implement the feature after refactoring...
I am proposing 
`public static ICollection<string> GetItems()`

**Comment by 304NotModified** [comment]
Indeed it's halted to bad. 

Your proposal sounds good,but I think the type should be `readonlydictionary<string, object >`

**Comment by tiljanssen** [comment]
My intention was to only return the keys (so I should change my proposal to GetKeys()). What are the advantages and disadvantages of returning the dictionary vs returning the keys?

Wouldn't making the dictionary read-only involve copying the data?
If there is some filtering process in the layout renderer, returning only the keys might save some data being copied for nothing?

**Comment by 304NotModified** [comment]
Ow yes, I think the keys only is a better proposal :) 

I think `iset<string>` is then better,do you agree?

**Comment by tiljanssen** [comment]
Returning a set would better indicate that we will have no duplicates. However, I have been looking for a built-in (and efficient) way to return the keys of a dictionary as an ISet, but I cannot find this (I am rather new to c# and may have missed something...)

Also I can return the keys as a IReadOnlyCollection, but there does not seem to be an IReadOnlySet.

How much added value has returning an ISet over an ICollection if we add the readonly-ness? 

So my new proposal would be
`public static IReadOnlyCollection<string> GetKeys()`

**Comment by 304NotModified** [comment]
> Returning a set would better indicate that we will have no duplicates. However, I have been looking for a built-in (and efficient) way to return the keys of a dictionary as an ISet, but I cannot find this (I am rather new to c# and may have missed something...)

No indeed, you should create it yourself. Too bad ISet is .NET 4+ (HashSet is .Net 3.5+), but I think `IReadOnlyCollection` is also nice. An user could create his own HashSet to efficient check the keys. 

> By the way, would you prefer getKeys or getItems, since item is the name of the parameter used everywhere for the "key", but it may also be easily misinterpreted as the "name+value" combination.

`GetNames()`, as we use indeed "name" everywhere.

**Comment by tiljanssen** [comment]
IReadOnlyCollection is not supported on .NET 3.5, maybe also not on .NET 4.0.
So, shall I just revert back to the original ICollection?

**Comment by 304NotModified** [comment]
Or you can use `#if NET3_5`
