### ISSUE TITLE
NLog.Schema v4.0.0 gets installed instead of NLog.Schema v4.2.3

### ISSUE THREAD

**Issue by jhaamit6666** [NLog/NLog#1318]
**Type**: Feature request

**NLog.Config version** : 4.2.3

**Platform**: .Net 4.6.1

I have installed NLog.Config version : 4.2.3 using NuGet. It installs NLog.Schema v4.0.0, which is older version. Kindly have it changed to NLog.Schema v4.2.3.

**Comment by 304NotModified** [comment]
Thanks for the report! We will fix this in 4.3
