### ISSUE TITLE
Issue with database target and Mono.Data.Sqlite

### ISSUE THREAD

**Issue by tidusjar** [NLog/NLog#1319]
**Type** :
- Bug

**NLog version**: 
- 4

**Platform**:
- .Net 4.6

**Current NLog config** (xml or C#, if relevant)

```
  <target name="Database" xsi:type="Database"
         dbProvider="Mono.Data.Sqlite" keepConnection="false"
         connectionString="Data Source=PlexRequests.sqlite"
         commandText="INSERT into Log(Date, Level, Logger, Callsite, Message) 
          values(@Date, @Loglevel, @Logger, @Callsite, @Message)">
    <parameter name="@Date" layout="${longdate}"/>
    <parameter name="@Loglevel" layout="${level:uppercase=true}"/>
    <parameter name="@Logger" layout="${logger}"/>
    <parameter name="@Callsite" layout="${callsite:filename=true}"/>
    <parameter name="@Message" layout="${message}"/>
  </target>
```

In case of a BUG:

- What is the current result? Nothing is logged to the DB
- Please post full exception details (message, stacktrace, inner exceptions)

```Error during initialization of Database Target[Database_wrapped]
    Could not load type 'Mono.Data.Sqlite' from assembly 'NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c'.
    at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName)
   at System.RuntimeType.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark)
   at System.Type.GetType(String typeName, Boolean throwOnError)
   at NLog.Targets.DatabaseTarget.InitializeTarget()
   at NLog.Targets.Target.Initialize(LoggingConfiguration configuration)
   at NLog.Targets.Target.NLog.Internal.ISupportsInitialize.Initialize(LoggingConfiguration configuration)
   at NLog.Config.LoggingConfiguration.InitializeAll()```

**Comment by 304NotModified** [comment]
What is the Nuget version?

I guess you have to load the assembly yourself. Not sure.

**Comment by tidusjar** [comment]
Version is below. How would I load the assembly myself? 

     version="4.2.3" targetFramework="net452"

**Comment by 304NotModified** [comment]
Just checked the code.

It doing:


`Type.GetType("Mono.Data.Sqlite")` (see [code](https://github.com/NLog/NLog/blob/f34eeda2d8df0bea1386a496557cdb93a213eed5/src/NLog/Targets/DatabaseTarget.cs#L368).

You need to add the assembly name to "dbProvider", e.g. something like this:

```
Mono.Data.Sqlite, MyAssembly
```
or

```
Mono.Data.Sqlite, MyAssembly, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31BF3856AD364E34
```

**Comment by tidusjar** [comment]
Thanks for the assistance, sorry but I am not 100% following, for `MyAssembly` what am I actually entering? The Assembly that contains a reference to `Mono.Data.Sqlite`?

**Comment by 304NotModified** [comment]
yes indeed

**Comment by tidusjar** [comment]
Getting `Could not load type 'Mono.Data.Sqlite' from assembly 'PlexRequests'.` even know the `PlexRequests` assembly has a reference to `Mono.Data.Sqlite`.

     dbProvider="Mono.Data.Sqlite, PlexRequests"

**Comment by 304NotModified** [comment]
Well then the name isn't correct. ;)

It should be a "Fully Qualified Type name". You can find the fullname in your program with `typeof(Mono.Data.Sqlite).AssemblyQualifiedName`

- http://stackoverflow.com/questions/4744837/how-to-get-the-full-type-name
- http://platinumdogs.me/2010/01/05/net-5-part-or-fully-qualified-type-and-assembly-names/
- https://msdn.microsoft.com/en-us/library/yfsftwz6(v=vs.110).aspx



PS: I'm not sure if "Mono.Data.Sqlite" is the correct type. In SQL Server it is "system.data.SqlClient"

**Comment by tidusjar** [comment]
Got it!

So this worked for me `"Mono.Data.Sqlite.SqliteConnection, Mono.Data.Sqlite, Version=4.0.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756"` 

Since `Mono.Data.Sqlite` is a namespace. 

Also `Mono.Data.Sqlite` is the mono version of `System.Data.Sqlite`.

Thanks for your help.

**Comment by 304NotModified** [comment]
Nice! Can you add this to the wiki?

**Comment by tidusjar** [comment]
Will do!

**Comment by 304NotModified** [comment]
Thanks!

**Comment by OskarKlintrot** [comment]
Sorry for posting on an old thread but I had a similar issue but with dotnet core 2.0. I hade to use `Microsoft.Data.Sqlite.SqliteConnection, Microsoft.Data.Sqlite, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60` to get it working. I'm not sure it's dotnet core 2.0 specific or just bad luck, should I add it to the wiki or can someone verify that this is the best way to do it for dotnet core 2.0?

**Comment by 304NotModified** [comment]
Please add it to the wiki, thx!

**Comment by 304NotModified** [comment]
Thx!
