### ISSUE TITLE
includeTimestamp in configuration file not present

### ISSUE THREAD

**Issue by jhaamit6666** [NLog/NLog#1320]
**Type**: Feature request

**NLog.Config version** : 4.2.3

**Platform**: .Net 4.6.1

**includeTimestamp** not present in NLog.config. Also, it cannot be accessed, i.e, it gives error.

![2](https://cloud.githubusercontent.com/assets/16834561/13951153/11ec86b2-f055-11e5-9dcf-b6c936547ba0.png)

**Comment by 304NotModified** [comment]
That's a bug

We should include it here:

https://github.com/NLog/NLog/blob/3718a3ef52a8dd7fa4177bde85547fd6bbe79ee4/src/NLog/Config/XmlLoggingConfiguration.cs#L517

**Comment by 304NotModified** [comment]
Thanks for reporting!

**Comment by 304NotModified** [comment]
This will be fixed in 4.3. It has been renamed to `internalLogIncludeTimestamp` (for consistency)
