### ISSUE TITLE
New Line creation in logs

### ISSUE THREAD

**Issue by jhaamit6666** [NLog/NLog#1322]
**Type**: Question

**NLog.Config version** : 4.2.3

**Platform**: .Net Framework 4.6.1

How to create new line in logs? I tried [var](https://github.com/nlog/NLog/wiki/Var-Layout-Renderer) in [Layout Renderers](https://github.com/nlog/NLog/wiki/Layout-Renderers)

**Comment by 304NotModified** [comment]
`${newline}` ?

**Comment by jhaamit6666** [comment]
Oh!!! Missed!
