### ISSUE TITLE
Mandatory `rules` attributes

### ISSUE THREAD

**Issue by jhaamit6666** [NLog/NLog#1325]
**Type**: Question

**NLog.Config version** : 4.2.3

**Platform**: .Net Framework 4.6.1

Mandatory `rules` attributes should be written about in [documents](https://github.com/NLog/NLog/wiki/Configuration-file#rules). Also, `minlevel` attribute in `rules` should not be present by default. Program can run without `minlevel` also (all levels are true this way).

**Comment by 304NotModified** [comment]
> Mandatory rules attributes should be written about in documents

Agree, please add it to the wiki.



> Also, minlevel attribute in rules should not be present by default.

You mean in NLog.config package? It is used a lot, so therefor it's added to the example.
