### ISSUE TITLE
Is `FallbackGroup` a wrapper?

### ISSUE THREAD

**Issue by jhaamit6666** [NLog/NLog#1326]
**Type**: Question

**NLog.Config version** : 4.2.3

**Platform**: .Net Framework 4.6.1

Is [FallbackGroup](https://github.com/NLog/NLog/wiki/FallbackGroup-target) a wrapper? 
![2](https://cloud.githubusercontent.com/assets/16834561/13980769/3552a5a8-f106-11e5-8a27-571ddd87f86c.png)

**Comment by 304NotModified** [comment]
yes, as it wraps another target.

See also: https://github.com/NLog/NLog/tree/master/src/NLog/Targets/Wrappers

**Comment by jhaamit6666** [comment]
OK.

> Too bad of the inconsistent name.

Same applies to some other wrappers also.
