### ISSUE TITLE
Ambiguity in wiki docs?

### ISSUE THREAD

**Issue by jhaamit6666** [NLog/NLog#1327]
Type: Question

NLog.Config version : 4.2.3

Platform: .Net Framework 4.6.1

There is some ambiguity between the lines marked and **Accuracy** and **Speed** columns marked in the snapshot.
![1](https://cloud.githubusercontent.com/assets/16834561/13984554/f259f582-f11c-11e5-8b1f-8bfc0cb9b703.png)

**Comment by 304NotModified** [comment]
The sentence tells use:

`speed(FastLocal) < speed (FastUtc) `and
`speed(AccuratetLocal) < speed (AccurateUtc) `.

That's consistent with the table? 

Mabye you read the sentence as `speed(Local) < speed (Fast) `, which isn't true

**Comment by jhaamit6666** [comment]
OK.
Then, the speed of execution should be in the order `AccurateUTC` < `AccurateLocal` < `FastUTC` < `FastLocal`

**Comment by 304NotModified** [comment]
Well the difference between FactUTC and FastLocal isn't that big, so therefor they are both "fastest"

**Comment by 304NotModified** [comment]
Anyway, ambiguity is bad and so I updated the text:

![image](https://cloud.githubusercontent.com/assets/5808377/14082606/37405cac-f511-11e5-86eb-76f96b5dad79.png)

https://github.com/NLog/NLog/wiki/Time-Source

Is this more clear?

**Comment by jhaamit6666** [comment]
Yes. Thanks.
