### ISSUE TITLE
[Feature Request] Support for something like log4net IRawLayout for targets that need objects.

### ISSUE THREAD

**Issue by veleek** [NLog/NLog#1332]
- Why do we need it?
  I'm currently working to create an NLog target for a logging system that takes objects in a specific structure.  Many of the properties on the structure are non string (e.g. int, DateTime, etc.), and right now if I would like to take advantage of the Layout renderers to provide a bit more flexibility to users from the configuration I will need to take the string produced by the renderer and parse it back into the appropriate type.

In many cases such as the MDC or MDLC, the structure has all the properties I need in the proper types, so I can just manually lookup the properties myself, but if the MDC layout renderer supported a way to get the raw object version of a property I could skip the costly parsing and also my code won't need to checking in many different locations for values.

```
public interface IRawLayout
{
    public object RenderRaw(LogEventInfo logEvent);
}
```

Anything that supports IRawLayout should essentially be able to fall back to ILayout by just ToStringing the object, but we could also derive IRawLayout from ILayout to force the implementers to ensure they provide for the lowest common denominator.

I haven't looked TOO deeply into how this would work between the Layout/Renderer layer, so I'm not sure how easy it would be, but wanted to start a conversation to find out if this is something that has been discussed already.

log4net `IRawLayout`: https://svn.apache.org/viewvc/logging/log4net/trunk/src/Layout/IRawLayout.cs?view=markup

**Comment by 304NotModified** [comment]
Hi!

Can you give a short example? It's not fully clear how to use this.

Are the event properties not a good alternative for this?

**Comment by veleek** [comment]
Event properties gives me the same benefit of using the MDC/MDLC.  My custom target would still need to know to look in the event properties and/or MDC/MDLC, etc., and I lose the ability to easily remap properties from the log call side to the log output side.

So, a more concrete example.  For the log system that I'm targeting, each log 'type' derives from a base class (e.g. `class RequestCompleteLog : Log`).

```
public class Log
{
    public Guid ServiceId { get; set; }
    public CorellationVector Correlation { get; set; }
    public DateTime RequestTime { get; set; }
}

public class RequestCompleteLog : Log
{
    public int RequestLatencyMs { get; set; }
    public string UserAgent { get; set; }
}
```

Now this is just an example, not exactly what it looks like, but you get the gist.  After constructing the object, you call `Log.Send()` or whatever.  The backend logging system processes it, may or may not using the various values to do work etc.  The point is that it's mostly a black box after you send the log.  We don't like the system, and it has a lot of overheard so we would like to use a more flexible intermediary like NLog to make it easier to a) change in the future, b) debug the service in production more easily, c) test logging on the local machine more easily, and more.

Now my custom target that is producing these logs could 'force' the user to put all the properties in the event properties, or into the MDC using hardcoded names, and then the target can look in each place for the appropriate values.  But with some sort of RawLayout, I could have something potentially like: 

```
<target ...>
  <log type="RequestCompleteLog">
    <property Name="ServiceId" Layout="${mdc:item=ServiceIdentifier}" />
    <property Name="RequestLatencyMs" Layout="${event-property:item=latency} />
    ...
  </log>
</target>
```

This just gives us a bit more flexibility from the services side around where they're getting values from, and how they're logging stuff.  

Now, maybe it's perfectly reasonable to just say that the target shouldn't use layouts and should just depend on looking in an explicit set of locations.  I've been comparing and contrasting NLog and log4net, and I believe that I could accomplish something similar using what's available in log4net and thought I'd see if it was something that NLog might support.

*phew* - Hope you got through the wall of text and that it all makes sense.  I'm still exploring here so I don't have anything super concrete at the moment.

**Comment by 304NotModified** [comment]
> I'm still exploring here so I don't have anything super concrete at the moment.

A super concrete example would really help us. 

Is it correct that the only thing we would like to prevent is, is a parse ? (e.g. parse string to datetime).

**Comment by veleek** [comment]
Sorry I got pulled off this project and haven't had much time the past few weeks to investigate.  

By super concrete, I meant I don't have an example of what I would like the implementation on the nlog side to look like (because it doesn't exist yet).  The sample of code that I gave you of a RequestComplete log is a very good example because all of the services that we have will be using it.

Without access to the Raw Value the value is converted to a string, parsed, converted to a string, and potentially parsed again.  Some of the services that will be using this are very high TPS, and the RequestComplete log is really the only _required_ log.  Most of the other logs can be throttled - e.g. only 10% of requests being logged - and temporarily enabled for debugging purposes, but not the RequestComplete ones, so the extra overhead of ToString and Parse for many parameters is going to be adding a bunch of overhead.

If I can avoid it at all it would help me convince the team to use a proper framework like this as opposed to building our own much less flexible maintainable system.

**Comment by 304NotModified** [comment]
Thanks for the reply. I get the case now :)

The bad thing is that everything is based on strings, when combining stuff (e.g. 2 layout renderers) and sometimes even optimized for string building (e.g. we don't build an object, but write to a stringbuilder).


If we support `IRawLayout `, this will have probably the following consequences: 

- initial we use still 'Render' instead of `RenderRaw`
- In some LayoutRenderes we have the code twice.

**Comment by 304NotModified** [comment]
working on this in #2856
