### ISSUE TITLE
How to delete log files based on maximum number of files

### ISSUE THREAD

**Issue by pjone** [NLog/NLog#1337]
Hi,

I want to limit log files to a maximum number so that if the number of log files exceed, and a new log file comes, the oldest gets deleted. I could do it using log file archiving, but I am trying to avoid archiving. 

This is my present code:-

NLog.Targets.FileTarget target = new NLog.Targets.FileTarget();
fileTarget.FileName = "${basedir}/logfile.${shortdate}.log";
fileTarget.AutoFlush = true;
fileTarget.ArchiveFileName =  "${basedir}/ArchivedLogs/logfile.${shortdate}.log";
fileTarget.MaxArchiveFiles = 3;
fileTarget.ArchiveEvery = NLog.Targets.FileArchivePeriod.Day;
fileTarget.ArchiveNumbering = NLog.Targets.ArchiveNumberingMode.Date;
fileTarget.ConcurrentWrites = true;
fileTarget.KeepFileOpen = true;

This will work, but I would like to avoid archiving (so that my application would only have log files and not log archives which is not required for my application).

Please let me know if you need additional info. Thanks.

**Type** :
- Question

**NLog version**:
- 4.0.0.0

**Platform**: 
- .Net 4.0

**Comment by 304NotModified** [comment]
This is currently only possible with archiving.

**Comment by snakefoot** [comment]
PR #1993 will allow you to specify only FileTarget.FileName and FileTarget.MaxArchiveFiles, and it will cleanup old files within the same folder.
