### ISSUE TITLE
Nlog files not getting created sequentially

### ISSUE THREAD

**Issue by jhaamit6666** [NLog/NLog#1339]
**Type**: Bug

**NLog.Config version** : 4.2.3

**Platform**: .Net Framework 4.6.1

The log file are not running sequentially. The code I am running is here: https://gist.github.com/jhaamit6666/3e3af19e6cf61fd1c8d7. Kindly ask for clarifications.

**Comment by 304NotModified** [comment]
Can you give an example what goes wrong? 

There is a big change that this has been fixed in NLog 4.3. Is it possible to test with nlog 4.3 rc2?

**Comment by jhaamit6666** [comment]
The result of the code pasted in the link is 
![1](https://cloud.githubusercontent.com/assets/16834561/14084105/df31a61c-f536-11e5-942a-53f9b84188b4.png). 
Contents of file.0.txt
Contents of file.0.txt
Contents of file.0.txt
Contents of file.0.txt
Contents of file.0.txt
Contents of file.0.txt
Contents of file.0.txt
Contents of file.0.txt

**Comment by 304NotModified** [comment]
>Rolling - Rolling style numbering (the most recent is always #0 then #1, ..., #N.

It seems correct?

**Comment by 304NotModified** [comment]
No first .0 is created, and rolls to . 1 and later to .2 etc. That's the rolling part.

**Comment by jhaamit6666** [comment]
OK.
