### ISSUE TITLE
Logging is slowing down application when writing to non-existing disk

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#1340]
When (synchronously) writing to a non-existing, NLog can slow down your application.

E.g.

```xml
<nlog> 

  <targets>
    <target xsi:type="File" name="file" 
               fileName="X:/logs/${shortdate}.log"   /> <!-- no X: on this computer! -->
 </targets>
```

Not sure how to fix this We could detect that the disk/location is not-existent or don't have rights to write, but should we then disable this target? And for how long?

**Comment by anton-gogolev** [comment]
You could do `DriveInfo.GetDrives()` on startup and then listen for device change events.
There's a `RegisterDeviceNotification` API (see [example](http://stackoverflow.com/a/16245901/60188), but:

1. It is Windows-only
2. Requires a window, so not sure how this will work in, say ASP.NET scenario

**Comment by 304NotModified** [comment]
Thanks ! The issue here AFAIK also NLog specific, it retries creating the file/folder which leads to this delay.

**Comment by Page-Not-Found** [comment]
@304NotModified may be a flag say if the folder is found. If not we can write to a null logger.

**Comment by 304NotModified** [comment]
@Page-Not-Found do you mean adding an option to the filetarget?

I think that's not needed, this bug could be fixed without new option AFAIK

**Comment by Page-Not-Found** [comment]
@304NotModified I mean, a private flag with in the class to see if it is non existent.

**Comment by 304NotModified** [comment]
Fixed by https://github.com/NLog/NLog/pull/1621
