### ISSUE TITLE
Config file not found when running via .NET Core

### ISSUE THREAD

**Issue by bhaeussermann** [NLog/NLog#1342]
We have a DNX application that we run through Visual Studio or via the command line as in 

```
dnx.exe --project "[path to my project.json]" run
```

There is an _NLog.config_ file in the project's folder, but NLog does not find it. This is because NLog is looking in the `BaseDirectory` of the current app domain, and under this environment that directory is the directory of DNX (where dnx.exe resides). In this scenario the correct directory is given by `Directory.GetCurrentDirectory()`.

**Type**:
- Bug

**NLog version**: 4.2.3 (current build also)

**Platform**: DNX 1.0.0-RC1-Final

**Comment by 304NotModified** [comment]
Is this the same as https://github.com/NLog/NLog.Extensions.Logging/issues/24?

**Comment by bhaeussermann** [comment]
> Is this the same as NLog/NLog.Extensions.Logging#24?

I don't think so. This is not an IIS app and the issue occurs in development (when running the app from Visual Studio).

**Comment by 304NotModified** [comment]
@bhaeussermann do you know of Basedirectory is the same as GetCurrentDirectory in non-dnx?

**Comment by phenixdotnet** [comment]
@304NotModified GetCurrentDirectory mustn't be used as it could be changed by somethings simple as OpenFileDialog for example.

The problem with dnx is that the behavior is different between "desktop" app and web app. Getting the right value for the right scenario will be the challenge.

**Comment by 304NotModified** [comment]
Thanks @phenixdotnet 

So this is still an issue :( 

(also counts for https://github.com/NLog/NLog/pull/1362)

**Comment by jp7677** [comment]
I'm seeing the same issue with RC2 when executing
"dotnet run -p [projectfolder]"
What about looking for an NLog.config in the location of the entry assembly using `System.Reflection.Assembly.GetEntryAssembly().Location`?

PS: Not really related to that issue, but would you consider looking for an "nlog.config" file as well? Linux is quite case sensitive and quite some samples on the Internet refer to an nlog.config instead of NLog.config. Would be nice if both variations would be supported.

**Comment by 304NotModified** [comment]
I will add the possibility to inject the file names soon in NLog. Then we can proper fix this issue :)

**Comment by snakefoot** [comment]
Created PR #2846 that should resolve this (By checking both Entry-Assembly-Location and NLog-Assembly-Location).
