### ISSUE TITLE
Nlog and serialization problem 

### ISSUE THREAD

**Issue by rajeevajayalingappa** [NLog/NLog#1345]
HI All, 

am getting this error 

Type 'NLog.Logger' in Assembly 'NLog, Version=2.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c' is not marked as serializable.

please let me know wht should i have to do for resolving this issue

**Comment by 304NotModified** [comment]
Hi,

When do you get this? Also, NLog 2.0 is not supported anymore.

**Comment by rajeevajayalingappa** [comment]
i should have to use NLOG 4.0 ?

**Comment by 304NotModified** [comment]
I would recommend the latest stable, 4.2.3

**Comment by 304NotModified** [comment]
Is this still an issue?

**Comment by 304NotModified** [comment]
Closing due too inactivity
