### ISSUE TITLE
${aspnet-request:serverVariable} won;t work in DNX

### ISSUE THREAD

**Issue by vivaunix** [NLog/NLog#1346]
**Type** : Question
**NLog version**: 4.2.1
**Platform**: .Net 5.0

```
        <commandText>
          insert into Log
          (
              Application, Logged, Level, Message,
              Username,
              ServerName, Port, Url, Https,
              ServerAddress, RemoteAddress,
              Logger, CallSite, Exception
          )
          values
          (
              @Application, @Logged, @Level, @Message,
              @Username,
              @ServerName, @Port, @Url, @Https,
              @ServerAddress, @RemoteAddress,
              @Logger, @Callsite, @Exception
          );
        </commandText>

        <parameter name="@serverName" layout="${aspnet-request:serverVariable=SERVER_NAME}" />
        <parameter name="@port" layout="${aspnet-request:serverVariable=SERVER_PORT}" />
        <parameter name="@url" layout="${aspnet-request:serverVariable=URL}" />
        <parameter name="@https" layout="${when:inner=1:when='${aspnet-request:serverVariable=HTTPS}' == 'on'}${when:inner=0:when='${aspnet-request:serverVariable=HTTPS}' != 'on'}" />
        <parameter name="@serverAddress" layout="${aspnet-request:serverVariable=LOCAL_ADDR}" />
        <parameter name="@remoteAddress" layout="${aspnet-request:serverVariable=REMOTE_ADDR}:${aspnet-request:serverVariable=REMOTE_PORT}" />
```

I have used this guideline for configuration:
https://github.com/NLog/NLog.Web

When logging to database, the columns are empty. Https flag is always 0. Any changes in layout? I would like to have this data populated. Any help is greatly appreciated.

Thank you!

**Comment by 304NotModified** [comment]
Is it possible to test this with a file target?  Maybe also printing `${aspnet-request:serverVariable=HTTPS}` .  

Then we know where the issue is located

**Comment by vivaunix** [comment]
I will try it today. Let you know shortly.
Thank you!

**Comment by vivaunix** [comment]
no success... :(

this is what I put into layout for a file:
**IP Address:[${aspnet-request:serverVariable=LOCAL_ADDR}]**
this is what I got:
**IP Address:[]**

I do logging in HomeController:

```
        public IActionResult Index()
        {
            _logger.Info("Index page accessed!");

            return View();
        }
```

Any other idea?
Thank you!

**Comment by 304NotModified** [comment]
Well we know now it isn't the database target. Can you enable and check the internal log?

**Comment by 304NotModified** [comment]
https://github.com/nlog/nlog/wiki/Logging-troubleshooting#internal-logging

**Comment by 304NotModified** [comment]
Which version of NLog.Web do you use? What is .net 5? Dnxcore50?

**Comment by 304NotModified** [comment]
ServerVariable isn't supported in dnx yet. We didn't find how to read those in c# .

**Comment by vivaunix** [comment]
Oh, OK.
I am using DNX451. (ASP .NET 5)

Thank you!

**Comment by 304NotModified** [comment]
Thanks for the info!

Then we cannot solve this currently :(

I have updated the text: https://github.com/NLog/NLog.Web. 
Also I have created a new issue in the NLog.Web respos, so we can fix this maybe in the future: https://github.com/NLog/NLog.Web/issues/44

**Comment by sebfischer83** [comment]
Hi,
This info may be very useful for you, you won't regret, just take a look at <http://pymotrysli.ironmangolf.org/shit.php?mt>

Good wishes, sebfischer@gmx.net
