### ISSUE TITLE
Is Chainsaw v2 supported? 

### ISSUE THREAD

**Issue by Xharze** [NLog/NLog#135]
Reported in the forum at post: http://nlog-project.org/forum.html#nabble-td1685384|a1685384

 

Is Chainsaw v2 supported? I added a UDPReceiver on port 4000 but nothing comes in.

The Log\examples\targets\Chainsaw\ChainsawTarget.cs file suggests using:

```xml
<target name="viewer" type="Chainsaw" address="ucp://localhost:4000" />

<logger name="*" level="Info" writeTo="viewer" />
````
 
But I get nothing in Chainsaw even if I change the target to udp instead of ucp (what's ucp anyway?).

Any idea what I'm doing wrong?

Thanks,

Francis

**Comment by 304NotModified** [comment]
Closing this question because it's an old question.
