### ISSUE TITLE
File target: can't use absolute path at root

### ISSUE THREAD

**Issue by jods4** [NLog/NLog#1350]
**Type**: Bug
**NLog version**: 4.2.3
**Platform**: .Net 4.5
**Current NLog config** 
```xml
    <target fileName="D:\log.txt"  />
```
**What is the current result?**
`log.txt` is created in the current directory on D: drive.
**What is the expected result?**
`log.txt` is created at the root of D: drive.
**Workaround?**
Use `cleanupFileName="false"`.

The reason why it doesn't work is this line of code:
https://github.com/NLog/NLog/blob/master/src/NLog/Targets/FileTarget.cs#L1997

When cleaning up the filename, the current value is split in two but the last separator `\` isn't kept (on purpose or as an off-by-one error, I don't know).
For instance: 
- `some\path\log.txt` becomes `some\path` + `log.txt`
- `d:\log.txt` becomes `d:` + `log.txt`.

The pieces are later put back together with `Path.Combine`, but it won't give the expected results:
- `some\path\log.txt` is ok because the missing separator is added.
- `d:log.txt` is not ok! It becomes: `log.txt` in the current directory of the `d:` folder.

You can fix the line 1997 by keeping the last separator in the path.
But completely parsing Win32 paths properly is very hard! I suggest that you use `Path.GetFileName()` to extract the filename to clean and `Path.GetDirectoryName()` to get the path to the file. Doing so would fix the bug reported here.

**EDIT**: Also, since you seem to try allocations as much as possible in the code of `CleanupInvalidFileNameChars`. If the file was not cleaned up (there was no invalid char), there is no need to build a new result by combining the path and filename. The original can just be returned as is.

**Comment by 304NotModified** [comment]
This is indeed a bug. Is it possible to send a PR for this?

**Comment by jods4** [comment]
Oh sorry, I didn't see you did a PR already, sorry for the duplicate :frowning: 
The code 99% identical, except you have added tests and I did not!

Just for the record, though: I did _not_ use `Path.GetDirectoryName()` as I proposed, because the following case would not work: `\\fs01\log.txt`. As the MSDN documentation unclearly points out `Path.GetDirectoryName()` actually returns `null` in this case :angry:

**Comment by 304NotModified** [comment]
Yes indeed I also didn't used `Path.GetDirectoryName()` for those cases ;)

Thanks for the new PR, but I won't accept it. :evil:
