### ISSUE TITLE
Feature: allow specifying wildcard for autoloading extensions

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#1355]
Extensions are now loaded automatically with the following convention: "NLog*.dll", see [ConfigurationItemFactory.cs#L253](https://github.com/NLog/NLog/blob/d87bc70f176356c6f5bcb48f598e1b67fb7f0b61/src/NLog/Config/ConfigurationItemFactory.cs#L253)

It should be possible to extend / replace this. E.g.:
- replace with "*.nlog.dll"
- replace with "myext.dll"
- extend with  "_.nlog.dll", so the it will scan for  "_.nlog.dll" and "NLog*.dll".

**Comment by snakefoot** [comment]
Another direction could be to stop autoloading assembly, but only load those explicitly specified in nlog.config. This would also make NLog less promiscuous to security attacks.

See also #3674 that trieds to fix the performance overhead from scanning and loading assemblies, which hurts startup performances when using NLog in Azure Functions or AWS Lambdas.

**Comment by 304NotModified** [comment]
wontfix for now, as autoloading won't work in .NET Core. #1091
