### ISSUE TITLE
Logging does not work on coreclr when ${specialfolder} is present

### ISSUE THREAD

**Issue by aplex** [NLog/NLog#1365]
When "${specialfolder:folder=ApplicationData}" is present in nlog config, logging does not work at all on corelcr.  In the example below, it is used in a variable. And the variable is not actually used anywhere. 

When specialfolder is present, nothing is logged. When it is absent, logging works fine.

**Type** (choose one): bug
**NLog version**: 4.4.0-beta3
**Platform**:   coreclr 1.0.0-rc1-update1 x86
OS: Windows 10 x64 (also seen on OS X)

**Current NLog config** 

``` xml
<?xml version="1.0" encoding="utf-8"?>

<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <variable name="logFolder"
          value="${specialfolder:folder=ApplicationData}/TestApp" />

    <targets>
        <target
            name="console"
            xsi:type="Console"
            layout="${logger:shortName=true} | ${message} ${exception:format=ToString}" />

    </targets>
    <rules>

        <logger name="*" minlevel="Debug" writeTo="console" />
    </rules>
</nlog>

```

Sample progam

```

    public class Program
    {
        private static readonly Logger Logger = LogManager.GetCurrentClassLogger();
        public static void Main(string[] args)
        {
            Console.WriteLine("Direct console output from app - before");

            var configPath = @"C:\NLog.config";
            if (!File.Exists(configPath)) throw new InvalidOperationException("Config file not found");

            LogManager.Configuration = new XmlLoggingConfiguration(configPath);

            Console.WriteLine("Direct console output from app - logging initialized");

            Logger.Debug("Message from logger " + DateTime.Now);

            Console.WriteLine("Direct console output from app - after");

            Console.ReadLine();
        }
    }
```

Output when  variable definition is absent in nlog.config:

```
Direct console output from app - before
Direct console output from app - logging initialized
Program | Message from logger 4/7/2016 10:33:14 AM
Direct console output from app - after
```

Output when  variable definition is present in nlog.config:

```
Direct console output from app - before
Direct console output from app - logging initialized
Direct console output from app - after
```

**Comment by 304NotModified** [comment]
Too bad special folders aren't supported in core clr. You can see that when checking the internal log or enabling throwConfigExceptions

**Comment by aplex** [comment]
Oh, adding  throwExceptions="true" indeed showed that renderer is not found.
Before that, I had <nlog  internalLogToConsole="true" internalLogLevel="Trace" ... > in config, but that didn't output any errors to the console.

**Comment by aplex** [comment]
I guess I can get similar result by just using environment variables:
```
<variable name="logFolder"
     value="${environment:variable=APPDATA:whenEmpty=${environment:variable=HOME}}/Log" />
```

**Comment by 304NotModified** [comment]
Will close this as this is a known issue as it's polluting the issue list - there is no action for us here.

**Comment by 304NotModified** [comment]
note: this *is * supported in .NET standard 2, but not in .NET standard 1 because of the missing API. We are using: Environment.GetFolderPath
