### ISSUE TITLE
Using NLog for ASP.NET Core to write custom information to the database

### ISSUE THREAD

**Issue by dr-noise** [NLog/NLog#1366]
In the previous versions of NLog it was easily possible to map custom log properties to custom database columns using `LogEventInfo` and `${event-properties}` layout renderer:

```
LogEventInfo evt = new LogEventInfo(logLevel, "", message);
evt.Properties["custom"] = "some data";
log.Log(evt);
```

I cannot make this work using ASP.NET Core and `NLog.Extensions.Logging.NLogLogger`.

I am using standard [ASP.NET Core logging infrastructure](https://docs.asp.net/en/latest/fundamentals/logging.html) and `NLog.Extensions.Logging` package. At the runtime, my `Microsoft.Extensions.Logging.ILogger` contains additional `NLog.Extensions.Logging.NLogLogger` instance, configured to write all the events to the database. I want to pass some dictionary-like object to `Microsoft.Extensions.Logging.ILogger.Log()` to make this information available to NLog layout renderers. Is it supported?

**Comment by phenixdotnet** [comment]
Hi @dr-noise 
May be you can use the state parameter of Log method to send the dictionary but you should have to write your own ILogger implementation to write it in NLog logger.

Actually we can't handle this scenario because the ILogger interface is part of .NET Core and we can't extend the method signature

**Comment by dr-noise** [comment]
Thanks @phenixdotnet 
I'll have deeper look into this, I thought that `state` parameter already supported by the `NLog.Extensions.Logging.NLogLogger`.

For example, `NLogLogger` can check if `state` is instance of `Dictionary<string, string>` and push all data from there to the underlying `LogEventInfo`.

**Comment by phenixdotnet** [comment]
> For example, NLogLogger can check if state is instance of Dictionary<string, string> (or Dictionary<object, object>) and push all data from there to the underlying LogEventInfo.Properties.

It will fit your need but it seem hard to generalize this. That why I suggest you use your own implementation. We can work on push some extension point on the actual class but I don't think its a good idea to implement this idea directly in NLog lib

**Comment by dr-noise** [comment]
I agree on this @phenixdotnet — it's not a good idea to enforce API users to be aware of this implementation detail.

**Comment by 304NotModified** [comment]
I think we should do something about this is the near future.  The aspnet logging is prepared for structural logging, but NLog not. 

Related http://nlog.userecho.com/topics/21-make-structural-logging-possible/

**Comment by 304NotModified** [comment]
I think it's a good idea to allow programmatically overwrite the current behaviour.  (by DI into nloglogger)

**Comment by phenixdotnet** [comment]
@304NotModified Agree.
We can define an interface to allow injection or add a secondary constructor which allow passing an Action.
Something like that
```public NlogLogger(Action<LogEventInfo, object> stateProcessor)```

**Comment by 304NotModified** [comment]
I think DI is the new way, but I have to agree I don't know how to set-up the default DI binding (so that we user only have to set the DI binding if he needs to overrule the default).

I was thinking of an interface like this

```c#
interface INLogConvertToLogEventInfo
{
 LogEventInfo convert(Microsoft.Extensions.Logging.LogLevel logLevel, int eventId, object state, Exception exception); 
}
```

**Comment by 304NotModified** [comment]
I think we can fix this with some c# extensions.  Will try to look at this when we update the NLog.Extensions.Logging package for rc2

(structural logging is also still on the road)

**Comment by hetjoshi87** [comment]
Did we figure out this or is there any example which i can look onto?

**Comment by snakefoot** [comment]
Added documentation about how to include NLog properties:

https://github.com/NLog/NLog.Extensions.Logging/wiki/NLog-properties-with-Microsoft-Extension-Logging
