### ISSUE TITLE
Enforce single-line log entries

### ISSUE THREAD

**Issue by DumboJetEngine** [NLog/NLog#1371]
**Type** (choose one):
- Question

**NLog version**: (e.g. 4.2.3)

**Platform**: .Net 3.5 / .Net 4.0 / .Net 4.5

**Current NLog config** (xml)

**Question** :
I need to have my logs formatted in such a way so that each log entry is in a single line.
I need this because we use some software that reads these log entries and expects them to be formatted like that.
Basically, I could probably do this by wrapping NLog in a custom class or static function(s) and replace new lines, but I was wondering if there is something built-in already for this case inside NLog.

Thanks. :)

**Comment by 304NotModified** [comment]
You can use 

`{replace-newlines:replacement=}`, See https://github.com/NLog/NLog/wiki/Replace-NewLines-Layout-Renderer

**Comment by DumboJetEngine** [comment]
Thank you! :)
