### ISSUE TITLE
Logging InnerException Separately

### ISSUE THREAD

**Issue by shortstuffsushi** [NLog/NLog#1375]
Hi all,

This is just a quick question -- the answer may be obvious, and I may not be looking in the right place.

I'm looking to have a database target where `Exception`, `InnerException`, and `ExceptionData` are stored in separate columns, if possible. I have something like the following, which is not working. Is there a way to do this? A brief bit of Googling / SO'ing, it doesn't seem anyone else has a solution for this.

```
<target xsi:type="Database" name="database" connectionString="AuditDB">
    <commandText>
       INSERT
         INTO LogTable
       (Exception, InnerException, ExceptionData)
       VALUES
       (@Exception, @InnerException, @ExceptionData);
    </commandText>

    <parameter name="@Exception" layout="${exception:format=ToString}" />
    <parameter name="@InnerException" layout="${exception:innerFormat=ToString}" />
    <parameter name="@ExceptionData" layout="${exception:format=Data}" />
</target>
```

The output currently seems to be the primary exception message (the default format value).

**Comment by 304NotModified** [comment]
Yes that's possible, see https://github.com/NLog/NLog/wiki/JsonLayout#from-the-api
as example

**Comment by shortstuffsushi** [comment]
Ah yes, that's exactly what I'm looking for. Thank you.

**Comment by 304NotModified** [comment]
:)

**Comment by b0wter** [comment]
I'm have a little bit of trouble getting this to work.
In my config I've added the following parameter:

`<parameter name="@InnerExceptionType" layout="${exception:format=:innerFormat=Type}"/>`

The internal logging doesn't show any errors. I am deliberately creating a new exception with:

`new NotImplementedException("test", new InvalidOperationException("inner test")); ` 

But my database only shows an empty column.

**Comment by 304NotModified** [comment]
Are you catching and logging the exception? That won't be automatic. If it's still an issue, please open a new issue.
