### ISSUE TITLE
createDirs doesn't seem to be working when run from debug mode in VS 2010

### ISSUE THREAD

**Issue by Xharze** [NLog/NLog#138]
<p>Not sure if this an issue with nLog or Visual Studio, but with most recent build of version 2 from 7/13/2010 it seems that createDirs is not actually creating the directory when I run in debug mode.</p>
<p>&nbsp;</p>
<p>Error:</p>
<p> at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)</p>
<p> at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath)</p>
<p> at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)</p>
<p> at NLog.Internal.FileAppenders.BaseFileAppender.TryCreateFileStream(Boolean allowConcurrentWrite) in c:\NLogBuild\src\NLog\Internal\FileAppenders\BaseFileAppender.cs:line 234</p>
<p>&nbsp;</p>
<p>snippet from config</p>
<p>&lt;target name=&quot;file&quot; createDirs=&quot;true&quot; xsi:type=&quot;File&quot; maxArchiveFiles=&quot;100&quot;</p>
<p> archiveFileName=&quot;${basedir}/logs/archive/application_{#####}.log&quot;</p>
<p> archiveEvery=&quot;Hour&quot; fileName=&quot;${basedir}/logs/application.log&quot;</p>
<p>&nbsp;</p>
<p>What&#39;s interesting is that my WPF app can create the folders either way when I do a Directory.CreateDirectory, so why does nlog not have permission? Weird.</p>

Comments:
xfighter wrote Jun 24 2011 at 2:41 AM

I have the same issue and adding the nlog source file it errors on the line 225 of the basefileappender.cs for me which is inside the "WindowsCreateFile" method:
var safeHandle = new Microsoft.Win32.SafeHandles.SafeFileHandle(handle, true);

**Comment by 304NotModified** [comment]
This seems a permissions issue. Closing this on.

**Comment by ilya-g** [comment]
This can be a first chance exception — an exception that is thrown, but caught by NLog later and handled. If the directory is created eventually, than it works as designed.
