### ISSUE TITLE
Why the method Error(Exception exception, string message, params object[] args) can't log the detail of exception?

### ISSUE THREAD

**Issue by kinshines** [NLog/NLog#1380]
Why the method `Error(Exception exception, string message, params object[] args)` can't log the detail of exception but only the message?
When I call the method `logger.Error(new Exception("Exception"))`, it can log the detail of Exception.
But When I call the method `logger.Error(new Exception("Exception"), "message with Exception")`, it only log the message for "message with Exception",and it do not log the detail of Exception.
Is it a bug?

**Comment by 304NotModified** [comment]
Hi,

please use the template, as we now missing important informatie, like version etc

**Comment by kinshines** [comment]
**Type** 
- Question


**NLog version**: (e.g. 4.2.3)

**Platform**: .Net 4.0 

**Current NLog config** 

```xml
<nlog>
  <targets>
   <target xsi:type="File" name="f" fileName="${basedir}/logs/${shortdate}.log"
                layout="${longdate} ${uppercase:${level}} ${message}" />
  </targets>
  <rules>
   <logger name="*" minlevel="Debug" writeTo="f" />
  </rules>
</nlog>

```

**The code goes as** 
```C#
    class Program
    {
        private static Logger logger = LogManager.GetCurrentClassLogger();

        static void Main(string[] args)
        {
            logger.Error(new Exception("the detail of Exception"));
            logger.Error("message with Exception", new Exception("the detail of Exception"));
        }
    }
```
**The output as** 
2016-04-20 11:44:42.1649 ERROR System.Exception: the detail of Exception
2016-04-20 11:44:42.2949 ERROR message with Exception

So my question is that:
Since the first method can log the detail of Exception.
But Why the second method can't log the detail of Exception?
Is it a bug?

**Comment by 304NotModified** [comment]
Hi,

this is party a bug.

- to log exceptions, you need [`${exception}`](https://github.com/NLog/NLog/wiki/Exception-Layout-Renderer) in your config. See [How to Log Exceptions](also https://github.com/NLog/NLog/wiki/How-to-log-exceptions).

- there is a bug that `logger.Error(new Exception("Exception"))` is also logging to `${message}`. We will fix this in NLog 5 because this is a breaking change. See https://github.com/NLog/NLog/issues/1034

**Comment by 304NotModified** [comment]
We assume this question has been answered. If not, just let us know!
