### ISSUE TITLE
**Question** Method to disable all logging

### ISSUE THREAD

**Issue by shaggygi** [NLog/NLog#1382]
Type: Question
NLog version: 4.2.3
Platform: .Net 4.6

Is there a method to disable logging?  We have different log types setup (e.g. database, file, etc.) and there are times we don't want to log info while troubleshooting/developing/testing.  It would be nice to have the ability to write an extra line of code to disable (or ignore) logging commands if it is disabled.

Is this type of feature already included to quickly disable/enable?  If so, are there any examples?  Thanks in advance.

**Comment by 304NotModified** [comment]
You can use http://nlog-project.org/documentation/v4.3.0/html/M_NLog_LogManager_DisableLogging.htm

Or set `LogManager.configuration` to `null`

**Comment by shaggygi** [comment]
Thanks @304NotModified.  This is what I was looking for!
