### ISSUE TITLE
Multiple rules doesnt seem to work

### ISSUE THREAD

**Issue by jordyvaneijk** [NLog/NLog#1388]
**Type**
- Bug

**NLog version**: 4.3.1

**Platform**: .Net 4.0 / .Net 4.5.2

**Current NLog config**: 

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="false"
      internalLogLevel="Off" internalLogFile="c:\temp\nlog-internal.log" >
  <variable name="stdLayout" value="${longdate} [${uppercase:${level}}] : ${logger} : ${message}"/>
  <targets>
    <target xsi:type="File" name="fileLogger" fileName="${basedir}/logs/${shortdate}.log" layout="${var:stdLayout}" />
    <target xsi:type="ColoredConsole" name="consoleLogger" layout="${var:stdLayout}" />
  </targets>
  <rules>
    <logger name="NLogSandbox.ModuleA.*" minlevel="Error" final="true" writeTo="consoleLogger" />
    <logger name="NLogSandbox.ModuleB" minlevel="Info" final="true" writeTo="consoleLogger" />
    <logger name="*" minlevel="Debug" final="true" writeTo="consoleLogger" />
  </rules>
</nlog>
```

It looks like the Rules are not working when using multiple rules with wildcards
See attached example:
[NLogSandbox.zip](https://github.com/NLog/NLog/files/227878/NLogSandbox.zip)

I think that if i use `final=true` on the first 2 rules that on the last catch all rule these are not processed but it looks like it is always doing so.
Can you please tell me what i'm doing wrong or is this a bug inside NLog?

**Comment by 304NotModified** [comment]
hi,

Can you give me an example of what isn't working? Please use the template; (what expected, current result)

Debugging a project is really a lot of work.

**Comment by 304NotModified** [comment]
FYI,


the `final=true` works records that get matched for the rule. In this case name and minlevel. E.g. an ERROR on "NLogSandbox.ModuleA.test" will match only the first rule, and DEBUG on "NLogSandbox.ModuleA.test" will match only match the 3rd rule.

**Comment by 304NotModified** [comment]
Closing this as we can't help without more info
