### ISSUE TITLE
.NET Core Debug Output Target

### ISSUE THREAD

**Issue by AgeingJester** [NLog/NLog#1389]
**Type** (choose one): Question
**NLog version**: 4.4 beta
**Platform**: .Net Core
**Current NLog config** (xml or C#, if relevant)

```code
            var debuggerTarget = new DebugTarget() { Name = "Debugger" };
            config.AddTarget(debuggerTarget);
            debuggerTarget.Layout = @"${date:format=HH\:mm\:ss} ${logger} ${message}";
            config.LoggingRules.Add(new LoggingRule("*", LogLevel.Debug, debuggerTarget));
```

I am using VS 2015 Update 2, Enterprise.  I am attempting to get log output to show up in the debug output window on a .Net Core console app using code configuration.  I searched the posts here and did not see any reports of issues with this feature.  My console logs and rolling files are working just fine - but the debug output window does not.  Can someone point me in the right direction?

Thanks!  (And awesome work on NLog!)

**Comment by 304NotModified** [comment]
The DebugTarget is only a target which keeps the last message as an property, for debugging purpose. 

To which debug output do you like to write? Do you have an C# example (if you would write it yourself)

**Comment by AgeingJester** [comment]
Ahh, I see - I completely misunderstood the DebugTarget.  Thank you for clarifying. :)

I was looking to get my logs to show up in the debug output panel inside visual studio.  Yes, System.Diagnostics has a mechanism to write to the debug output panel, I could write my own Target to accomplish this. 

Thanks again for the clarification!

**Comment by 304NotModified** [comment]
Well we have a trace and debug**ger**target, but those are absent in .NET core because the needed classes aren't available at that platform

**Comment by 304NotModified** [comment]
Or has that changed recently?

**Comment by AgeingJester** [comment]
I am not sure if anything has changed in core that would enable the DebuggerTarget.  Sorry I cant speak to that specifically.  

We will likely just write something that passes the logged message to Debug.Writeline in addition to passing to the logger.  We can just put it in our façade.
