### ISSUE TITLE
LogReceiverService - Dropping logevents for sequential log calls

### ISSUE THREAD

**Issue by Xharze** [NLog/NLog#139]
Moved from http://nlog.codeplex.com/workitem/5366

The following will result in a random number of log events getting posted to a LogReceiver Service
 
```
for(int i=0; i<1000; i++)
{
  logger.Debug(i);
}

NLog.LogManager.Flush();

 ```

To Verify the issue wasn't in the service code:

Added a log message to capture when the `ProcessLogMessages()` call was made from the client and the number of logevents passed to each call.

The results showed that a the total number of logevents passed through ProcessLogMessage() varied with each run.

**Comment by 304NotModified** [comment]
This is tested with `WebserviceTest_restapi_httppost_checkingLost` for months and never failed. This needs a retest.

**Comment by 304NotModified** [comment]
> This is tested with WebserviceTest_restapi_httppost_checkingLost for almost a year (may 2015) and never failed. This needs a retest.

So close
