### ISSUE TITLE
Feature: Provide overloads for extensions to lessen memory allocation

### ISSUE THREAD

**Issue by bjornbouetsmith** [NLog/NLog#1395]
**Type** Feature request:

**NLog version**: Latest

**Platform**: All

NLog when used in a service that logs a lot is generating a lot of "garbage" that has to be collected by the garbage collector.

To prevent this its common to use pooling and it is somewhat possible to do this by creating custom code and reference that from nlog,  e.g. creating a subclass of FileTarget and overwrite Write and GetBytesToWrite, and GetBytesToWrite is where the problem occurs.

When you write to a stream, there are overloads that take either a byte array or ArraySegment<byte>

stream.Write takes a byte array, an index and a length.

If GetBytesToWrite or a new method returned a struct with the bytestream, index and length, then it would be possible to return a part of a huge reusable byte array and stop the allocation the GetBytesToWrite have to do.

Alternatively a new method could be added that returned an ArraySegment<byte> which would accomplish the same, since its possible to wrap the array segment around a large array that could be used and reused by multiple threads at the same time, also cutting down on allocations.

All allocations that is being done every is adding memory pressure and every time a GC happens, there is a risk that something gets promoted a generation, so any allocation not done is good, and as a framework for logging, it would be nice if nlog could cut down on the allocations it does, so that the logging framework itself does not contribute to allocations.

Naturally most of the allocation would be gen0 allocations, but I am working with a service that services several thousands request per second on top of processing hundreds of thousand calculations and when we profile memory, nLog is the top 20 most allocating code.

Of course we could "just" hand roll our own non allocating logging framework, but that would be a major undertaking if we had to support the same features as nlog, so I would rather see this added to NLog, which would be a nice addition.

**Comment by bjornbouetsmith** [comment]
I can change the code myself, and make a pull request, so that its perhaps easier to see what I mean?

**Comment by 304NotModified** [comment]
Yes that's a good idea. Anyway, I'm not sure if the byte arrays are even needed. https://github.com/NLog/NLog/issues/1075

**Comment by bjornbouetsmith** [comment]
It has to end as a byte array eventually, since the File/Stream api's takes byte arrays.

But I see the Filetarget.Write(AsyngLogEventInfo[] is actually also allocating a memory stream, so not only is it allocating a lot of bytes for each log event, it also allocates the byte array for the memory stream. That could be changed so that the memory stream get a chunk of a big shared array of bytes, anyway I will try to make non-breaking changes in the FileTarget and add overloads so that extenders of nlog can provide other means of give the bytes that have to be writte, i.e. ArraySegment or something similar.

**Comment by 304NotModified** [comment]
FYI

I tried in the past writing without converting to byte array, and got a performance improvement of 25% .

**Comment by bjornbouetsmith** [comment]
I have made some changes and new classes to help with allocations when using the async file wrapper, i.e. FileTarget.Write(AsyncLogEventInfo[]

My initial testing shows that when using current version 4.3.1,then performance degradates with increasing message size up to the point that an out of memory exception is thrown. Furthermore the original code does heaps and heaps of garbage collection.

the new code does not degrade in performance using same message sizes and garbage collections is low and ever slightly increasing up towards the larger message sizes.

My code probably still need a few corners softened and there are probably coding style issues, since I am not used to the NLog code style.

All tests build and Run and I added a few tests to test some of the support classes I have built.

I have made a Fork of NLog: https://github.com/bjornbouetsmith/NLog and will be committing my code there, if you have time please take a look and see if thats something that could be merged into the main branch.

Naturally it has to be changed, so its configurable, whether or not to use and there are still rough edges that need to taken off, but the principle is sound.

**Comment by 304NotModified** [comment]
Hey! Sounds good! 

Please open a PR, so we can easily discuss your changes.  No problem if it isn't finished yet.

**Comment by bjornbouetsmith** [comment]
Okay Pull Requst done, with output from my tests, so there are some numbers to discuss from.

**Comment by snakefoot** [comment]
@304NotModified Think this has been closed with #1799

**Comment by 304NotModified** [comment]
Yes! Thx!

**Comment by 304NotModified** [comment]
Also thx to @bjornbouetsmith for the initial code!
