### ISSUE TITLE
${basedir} refers to C:\Users\...\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-update1\bin

### ISSUE THREAD

**Issue by NidNormal** [NLog/NLog#1398]
you are probably still using the old AppDomain.CurrentDomain.BaseDirectory

i had the same problem:
under VNext you can obtain the BaseDirectory from IHostingEnvironment
but in a library it's easier to obtain it from: PlatformServices.Default.Application.ApplicationBasePath
(i had the same problem)

at the moment i'm using fullpathes in the NLog.config, which is undesired, i'm awaiting this fix soon,

thanks in advance

**Comment by 304NotModified** [comment]
Hi,

Which version of DNX is this? Rc1? Rc2?

**Comment by 304NotModified** [comment]
related #1354 and #1367

**Comment by NidNormal** [comment]
Rc1
