### ISSUE TITLE
unable to log data by AzureAppendBlob target

### ISSUE THREAD

**Issue by Tejpal2** [NLog/NLog#1399]
Hi,

We are usnig "azureAppentBlob" target to log data on the Azure Blob. We are not getting any exception and data is not uploading to the Azure container "demo".  So please help. 

Following is the nlog code i have written in the nlog file : 

```
<target xsi:type="AzureAppendBlob"
         name="Azure"
         layout="${newline} ${longdate} ${level} ${aspnet-user-identity} ${message}"
         connectionString="DefaultEndpointsProtocol=http;AccountName=accoutname;
                                       AccountKey=<accountkey>"
         container="demo"
         blobName="${date:format=yyyy-MM-dd}.log" />

<rules>
<logger name="*" minlevel="Debug" writeTo="Azure" />
 </rules>
```

Thanks 
Tejpal singh

**Comment by 304NotModified** [comment]
Please use the template.

**Comment by Tejpal2** [comment]
it started working. Issue was at Azure Account end. It is a permission issue.
