### ISSUE TITLE
NLog does not append logs to existing log file

### ISSUE THREAD

**Issue by pawlin** [NLog/NLog#1405]
**Type**: Bug

**NLog version**: 4.1.2

**Platform**: .Net 4.5

**Current NLog config**

```xml
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <targets>
    <target name="main" xsi:type="File" fileName="main.log"
     layout="${longdate} [${uppercase:${level}}] ${logger} [${threadid}-${threadname}] ${message} ${exception:format=tostring}"
            archiveFileName="main.log.{#}" 
            archiveNumbering="Date" 
            archiveEvery="Day" 
            archiveDateFormat="yyyy-MM-dd" 
            maxArchiveFiles="20"/>
</targets>
<rules>   
<logger name="*" minlevel="INFO" writeTo="main" />
</rules>
</nlog>
```

In case of a BUG:

- What is the current result?

if there is no log file, first run, everything works fine. nlog creates new log file and appends logs to it. when there is an existing log file, new logs doesn't append to this log file. when I delete old log file manualy and run application again everything works fine again? why with this configuration nlog doesn't append logs to existing log file?

- What is the expected result?
every log append to logfile

**Comment by 304NotModified** [comment]
Hi,

Can you test this with NLog 4.3? (releasing 4.3.2 this night), as lot of filetarget bugs are fixed

**Comment by pawlin** [comment]
thanks, it is working with nlog 4.3.2

**Comment by 304NotModified** [comment]
Glad to hear! Thanks for the feedback!
