### ISSUE TITLE
Variable not evaluated?

### ISSUE THREAD

**Issue by tinudu** [NLog/NLog#1406]
**Type**: Bug (?)
**NLog version**: 4.3.2
**Platform**: .Net 4.5
**Current NLog config**

``` xml
<nlog ...>
  <variable name="env" value="DEV"/>
  <variable name="logFile" value="C:\temp\logs\${var:env}\test.log"/>
  <targets>
    <target name="file" xsi:type="File" fileName="${var:logFile}" layout="${message}"/>
  </targets>
  <rules>
    <logger minlevel="Info" writeTo="file"/>
  </rules>
</nlog>

```
- What is the current result? Logs to "C:\temp\logs\test.log"
- What is the expected result? Logs to "C:\temp\logs\DEV\test.log"
- Are there any workarounds? well, replace the variable reference with the actual value, but...

Strangely, referencing the "logFile" variable elsewhere (e.g. layout="${logFile}:${message}") makes NLog to behave as expected...

**Comment by 304NotModified** [comment]
I guess recursively variables are sometimes problematic.  Work around, use `${env}`

**Comment by 304NotModified** [comment]
The filename value is probably evaluates too soon. Will try to fix this.  If you could help with an unit test, that would be great!

**Comment by 304NotModified** [comment]
If you like to get this fixed, you can help is by writing an unit test. :)

**Comment by 304NotModified** [comment]
PS there is a possibility this has been fixed in NLog 4.3.4. We changed something for interpreting filetarget.filename

**Comment by Ninja4Code** [comment]
I've determined that this is working >=4.3.4 but not working <=4.3.0 to 4.3.3.  I'll take a look at it.  I'm assuming this feature was introduced on 4.3.0?  That's the first evidence I could see in the Release Notes.

**Comment by 304NotModified** [comment]
We have changed something with the filename for archiving in 4.3

**Comment by 304NotModified** [comment]
> I've determined that this is working >=4.3.4

For these reasons I will close this one :) 

If this is still a problem in NLog 4.3.4+, let us know!
