### ISSUE TITLE
BufferingTargetWrapper - Race condition

### ISSUE THREAD

**Issue by snakefoot** [NLog/NLog#1410]
Bug
- What is the current result? Multiple threads calling BufferingTargetWrapper causes message loss, and message reordering.
- What is the expected result? No message loss and messages written in delivered order.
- Are there any work arrounds? Wrap the BufferingTargetWrapper within AsyncTargetWrapper
- Is there a version in which it did worked? No

BufferingTargetWrapper.Write() has a race-condition between calling buffer.Append() and checking count >= this.BufferSize. If two threads are racing and first thread calls buffer.Append() with element 100 and will succeed, but before first thread calls buffer.GetEventsAndClear() then second thread calls buffer.Append() and element 101 is discarded by buffer.

BufferingTargetWrapper.Write() has a race-condition together with BufferingTargetWrapper.FlushCallback(). First-thread calls buffer.Append() with element 100, and because buffer is full then calls buffer.GetEventsAndClear(). Second-thread calls buffer.Append() and writes single element. Timer-Thread calls buffer.GetEventsAndClear() and writes the last element to target. First-thread writes the other 100 elements to target. Ordering is now wrong.

Both problems are solved by doing a lock (this.SyncRoot) inside BufferingTargetWrapper.Write()

**Comment by 304NotModified** [comment]
Thanks for this report!

Can you send a PR for this one?

**Comment by snakefoot** [comment]
Think I need to read more code, before I think. There is no issue as Target.WriteAsyncLogEvent() protects BufferingTargetWrapper.Write()

**Comment by 304NotModified** [comment]
Thanks for the feedback!
