### ISSUE TITLE
unble to initialise nlog in class library c#, vs10,12,13

### ISSUE THREAD

**Issue by yashfale** [NLog/NLog#1414]
Hi! Thanks for reporting this feature/bug/question! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

**Type** (choose one):

- Bug
- Feature request
- Question

**NLog version**: (e.g. 4.2.3)

**Platform**: .Net 3.5 / .Net 4.0 / .Net 4.5 / Mono 4 / Silverlight 4 / Silverlight 5 / Xamarin Android / Xamarin iOs

**Current NLog config** (xml or C#, if relevant)

```xml
<nlog>
  <targets>
  </targets>
  <rules>
  </rules>
</nlog>

```

In case of a BUG:

- What is the current result?
- What is the expected result?
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
- Please post full exception details (message, stacktrace, inner exceptions)
- Are there any work arrounds? yes/no
- Is there a version in which it did worked? 
- Can you help us by writing an unit test?

in case of a FEATURE REQUEST:
 
 - Why do we need it?
 - An example of the XML config, if relevant.

**Comment by 304NotModified** [comment]
Please provide the requested info

**Comment by 304NotModified** [comment]
If you post the needed info, I will re-open the ticket.
