### ISSUE TITLE
NLog calls Thread.Abort() to exit simple thread loop. It should not

### ISSUE THREAD

**Issue by jonreis** [NLog/NLog#1415]
Type: Bug
NLog. 4.3.3
Platform: all

Using Thread.Abort() is just bad practice. Especially for a simple processing loop. It would be better to use a ManualResetEvent, or its more efficient version ManualResetEventSlim

I have attached an example of how this would be implemented. I am not sure about the locking in the FileTarget as there does not seem to be any in this area, but I have added it just in case.

In general, I am not sure about the idea of spinning up a thread like this in the first place, but I do not know enough about the code to figure out a better way. In our application we have 4 log files, so there are 4 threads being spun up. These are looping every 200ms to do something very simple. Would a timer not be a better approach? Why a dedicated thread?

[FileTarget.txt](https://github.com/NLog/NLog/files/243333/FileTarget.txt)

**Comment by jonreis** [comment]
Here is a version using a Timer. I believe Compression is only available in .NET 4.5 so I have used Task.Run().

[FileTarget.cs.txt](https://github.com/NLog/NLog/files/243357/FileTarget.cs.txt)

Probably an improvement over spinning up a dedicated thread, but then I see the event on the FileAppenderCache:

        private void ExternalFileArchivingWatcher_OnChange(object sender, FileSystemEventArgs e)
        {
            if ((e.ChangeType & WatcherChangeTypes.Created) == WatcherChangeTypes.Created)
                logFileWasArchived = true;
        }

It seems that the goal of all this code is to detect when logFileWasArchived == true and to do something.

Why not trigger directly off of this event rather than checking the value of logFileWasArchived every 200ms? Thoughts?

**Comment by 304NotModified** [comment]
hey! I have to look more deep into this, but I think a timer is indeed better. 

> Why not trigger directly off of this event rather than checking the value of logFileWasArchived every 200ms? Thoughts?

I has to do with file locking AFAIK. The code is introduced in https://github.com/NLog/NLog/pull/1183

**Comment by 304NotModified** [comment]
PS: it would be great to send a PR instead of the attachments, it's easier to review and saves a lot of time for me (and so you get earlier feedback :))

**Comment by jonreis** [comment]
Sorry, by PR, I thought you meant Problem Report, but now I get it Push Request. Sorry about that.

I am in the middle of a product release, but will try and get a push request together in the next week.

**Comment by 304NotModified** [comment]
yeah, I meant Pull Request (PR) in GitHub.

**Comment by 304NotModified** [comment]
I moved your proposals to PR's, see #1424 and #1425

**Comment by jonreis** [comment]
Thank you Julian. I am going to try and get to this on the weekend. I have a couple of questions for the author of the code, just to make sure I am not missing something.

1) In FileAppenderCache there is an externalFileArchivingWatcher. It is detecting changes in the log directory. When a new file is created, it sets:

logFileWasArchived = true;

FileTarget creates a thread which periodically calls:

 this.fileAppenderCache.InvalidateAppendersForInvalidFiles();

Who's implementation is as follows:

             if (logFileWasArchived)
            {
                CloseAppenders();
                logFileWasArchived = false;
            }

So, why doesn't FileAppenderCache.ExternalFileArchivingWatcher_OnChange internally call InvalidateAppendersForInvalidFiles() when the event is triggered? I have having difficulty see where the advantage of doing this in another thread, or at a different time is. 

I am probably missing something, so I was hoping you could explain.

**Comment by bhaeussermann** [comment]
> So, why doesn't FileAppenderCache.ExternalFileArchivingWatcher_OnChange internally call InvalidateAppendersForInvalidFiles() when the event is triggered?

My memory is vague, but I believe it is the only way we could avoid deadlocks due to file locking and/or locking on `SyncRoot`.

**Comment by 304NotModified** [comment]
@jonreis, @bhaeussermann and me are thinking the `ManualResetEvent` (#1424)  is the best solution. Will try to get it working.

**Comment by 304NotModified** [comment]
Thanks @jonreis !

This will be fixed in 4.3.4
