### ISSUE TITLE
Zip archives with .NET 3.5

### ISSUE THREAD

**Issue by PeterHric** [NLog/NLog#1420]
Hi! Thanks for reporting this feature/bug/question! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

**Type** 
- Feature request
  Support for zipping archive files with .NET 3.5 would greatly help :) We need it since we have to be backward compatible due to many target environments which run on .NET 3.5
- Question
  In on the web site: 
  https://github.com/nlog/NLog/wiki/File-target  
  there is statement:
  "Compress won't work due to .Net restrictions. You can use enableArchiveFileCompression."
  And later below:
  "enableArchiveFileCompression - Indicates whether to compress the archive files into the zip files. Boolean Default: False > Supported in: > \* NLog v4.0 for .NET 4.5"
  My Q:  Is it intrinsically given (which I rather doubt), or just that NLog compiled with .NET 3.5 simply does not have that part of code ?

**Comment by 304NotModified** [comment]
Hi,

We use 'System.IO.Compression.ZipFile`, which is introduced in .Net 4.5.

https://msdn.microsoft.com/en-us/library/system.io.compression.ziparchive(v=vs.110).aspx

**Comment by PeterHric** [comment]
Dear all,

Thank you for the good answer.
Do you think there would be any chance to use DotNetLib
<http://stackoverflow.com/questions/593026/is-there-a-built-in-zip-library-in-net-3-5>
for earlier .NET releases and incorporate it to NLog.dll somehow, so that
the option  enableArchiveFileCompression="Boolean"   would work too ?

Even if third party would get involved :)

Regards,

Peter

2016-05-02 14:11 GMT+02:00 Julian Verdurmen <notifications@github.com>:

**Comment by 304NotModified** [comment]
I will check if I can include this in a separate package.

**Comment by PeterHric** [comment]
Thanx Julian,

That is highly esteemed ! :)

BR,

Peter

2016-05-02 18:57 GMT+02:00 Julian Verdurmen <notifications@github.com>:

**Comment by PeterHric** [comment]
Hi again,

A small suggestion:
 Using System.IO.Compression.GZipStream, and/or  System.IO.Compression.DeflateStream  for archive files compression with .NET 3.5  would be a good option in my opinion.

See here for more data:
https://msdn.microsoft.com/en-us/library/ms404280(v=vs.90).aspx

**Comment by 304NotModified** [comment]
@PeterHric NLog 4.3.4 is released with the option to inject your own file compressor.
Big thanks to @AndreGleichner! 

See #1423.  Example Usage with DotNetZip.Reduced 1.9.1.8   


```c#

using Ionic.Zip;
        protected class CustomFileCompressor : IFileCompressor
        {
           static CustomFileCompressor 
           {
                //register
                FileTarget.FileCompressor = new CustomFileCompressor();
           }

            public void CompressFile(string fileName, string archiveFileName)
            {
                using (ZipFile zip = new ZipFile())
                {
                    zip.AddFile(fileName);
                    zip.Save(archiveFileName);
                }
            }
        }
```

@AndreGleichner , I think it would be nice to create a NuGet package (and GitHub repos) for above example?

**Comment by AndreGleichner** [comment]
In your example above, I don't think the static ctor is useful. Somebody would need to reference CustomFileCompressor to kick off FileCompressor registration.
Maybe we could better add a static Register() method to CustomFileCompressor which has to be called early in Main().

Concerning the NuGet package...why not just add new project in NLog/examples?

**Comment by 304NotModified** [comment]
> In your example above, I don't think the static ctor is useful. Somebody would need to reference CustomFileCompressor to kick off FileCompressor registration.

You're right on that. Maybe I should create a hook in LogManager (or somewhere else), so a component could register itself.

**Comment by PeterHric** [comment]
Guys,

Once again big thanks for your effort !  I use it and it works just fine - so far :)

I don't mind referencing the CustomFileCompressor as 
I have to do it in the very setup line:

FileTarget.FileCompressor = new CustomFileCompressor();

And somehow you must register what you want anyhow, especially if you have more options.
Or did I miss anything important ?

**Comment by 304NotModified** [comment]
That line should do it :)

**Comment by PeterHric** [comment]
Hi @all again,

Just one small complain: 
When I set up archive file name: 
fTarget.ArchiveFileName = logDir + logFileName + "_${shortdate}.{##}.zip";

The zip file contains the unzipped raw .txt file in once again same directory path as was the original .txt.
I.e inside the .zip its nested to that same path :-o 

Example:

This file is being zipped (using DotNetZip):
D:/Destination/To/App/Logs/LogFileToBeZipped.log

Result:   This is the zip:
D:/Destination/To/App/Logs/LogFileToBeZipped.log_2016-05-30.00.zip

Problem: When I open the .zip -> inside it I have to dive all the way down to:
D:/Destination/To/App/Logs/**LogFileToBeZipped.log_2016-05-30.00.zip**/Destination/To/App/Logs/**LogFileToBeZipped.log**

See the attached zip file.
[NW2DBLogger.log2016-05-30.00.zip](https://github.com/NLog/NLog/files/289963/NW2DBLogger.log2016-05-30.00.zip)


I wonder:  Could the problem be that I missuse DotNetZip, or could it be a bug in NLog release ???

**Comment by PeterHric** [comment]
One info: If I set up archive file name: 
fTarget.ArchiveFileName = logFileName + "_${shortdate}.{##}.zip";

i.e. I omit the logDir, then the zipper puts my file to the .exe location, not where it found my source .log file... But ! The nested path inside .zip persists...
This is too bad :-(    I am afraid, it could be a problem of DotNetZip, or just incompatibility between how NLog sets up default Zip library in .NET  , and how 3rd party DotNetZip is defaultly set up..

**Comment by AndreGleichner** [comment]
Just change your impl of IFileCompressor so that it has "zip.AddFile(fileName, string.Empty);" instead of "zip.AddFile(fileName);"

**Comment by 304NotModified** [comment]
Closing this as supported with FileTarget.FileCompressor
