### ISSUE TITLE
Doesn't create day archive

### ISSUE THREAD

**Issue by pawlin** [NLog/NLog#1422]
**Type**:

- Bug

**NLog version**: 4.3.3

**Platform**: .Net 4.5

**Current NLog config** (xml or C#, if relevant)

```xml
	<targets>
        <target name="main" xsi:type="File" fileName="main.log"
                layout="${longdate} [${uppercase:${level}}] ${logger} [${threadid}-${threadname}] ${message} ${exception:format=tostring}"
                archiveFileName="main.log.${shortdate}" archiveEvery="Day"/>
    </targets>
    <rules>        
        <logger name="*" minlevel="DEBUG" writeTo="main" />
    </rules>
```

In case of a BUG:
- What is the current result?
all logs append to main.log everyday

- What is the expected result?
archive main.log to main.log.YYYY-MM-DD every day

is something wrong in my configuration?

**Comment by 304NotModified** [comment]
you need ` archiveFileName="main.log.{######}" ` instead of ` archiveFileName="main.log.${shortdate}" `, see https://github.com/NLog/NLog/wiki/File-target#archival-options

**Comment by pawlin** [comment]
thx, it is working with main.log.{#} and archiveNumbering="Date"

**Comment by 304NotModified** [comment]
:+1:
