### ISSUE TITLE
My rules are being ignored.

### ISSUE THREAD

**Issue by niemyjski** [NLog/NLog#1427]
If you take a look at my rules:

```xml
  <rules>
    <logger name="Exceptionless.Core.Jobs.EventPostsJob" minlevel="Warn" writeTo="file,exceptionless" final="true" />
    <logger name="*" minlevel="Info" writeTo="file,exceptionless" />
  </rules>
```
I keep getting log messages for all my sources. I've triple checked things. Any ideas what could be wrong?

![screen shot 2016-05-02 at 3 25 18 pm](https://cloud.githubusercontent.com/assets/1020579/14966927/5657d4d8-107a-11e6-81fa-186a1280fdb5.png)

**Comment by 304NotModified** [comment]
I guess this is a common mistake (didn't checked the screenshot).

You're writing for both rules to both targets, and also the final rule is determined by loggerpattern + loglevel

- WARN, ERROR and FATAL logevents of 'Exceptionless.Core.Jobs.EventPostsJob' will go only to through rule1 and log to file + exceptionless
- WARN, ERROR and FATAL logevents of NON-'Exceptionless.Core.Jobs.EventPostsJob' will go only through rule2 and log to file + exceptionless
- INFO logevents of 'Exceptionless.Core.Jobs.EventPostsJob' will go only through rule2 and log to file + exceptionless

**Comment by niemyjski** [comment]
From the documentation and from some previous versions of nlog I can remember this working. The docs state that the rules will be ran in order and as soon as final=true is hit, no more targets will be written to. Is this an invalid assumption? If so then the final docs need to be updated.

**Comment by 304NotModified** [comment]
> final – make this rule final. No further rules are processed when any final rule matches

https://github.com/nlog/nlog/wiki/Configuration-file

This is correct. Is this unclear?

**Comment by niemyjski** [comment]
Yes

```
Log routing rules are defined in the <rules /> section. It is a simple routing table, where we define the list of targets that should be written to for each combination of source/logger name and log level. Rules are processed starting with the first rule in the list. When a rule matches, log messages are directed to target(s) in that rule. If a rule is marked as final, rules below it are not processed.
```

I have two rules, the first is a rule for EventPostsJob with a min level of Warn and a final attribute of true. The rule below it should never run..

**Comment by niemyjski** [comment]
So I guess my rule doesn't match because it's an Info log and there for final=true doesn't match.  I guess I was completely wrong and I need to use max level on it with an empty target list
