### ISSUE TITLE
Add Configuration.CombineConfig(config => config)

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#1429]
Combining XML config with C# config is now tricky, as autoreload/load of the XML file could overwrite the C# config.

We can use the events for the on LogManager, but it will be more clear to create a method with receives a lambda. 

e.g.

``` c#
LogManager.Configuration.Combine(logConfig => 
                                  {
                                      logConfig.AddTarget(..);
                                  });
```

currently needed, the `ConfigurationReloaded` event

```c#
using System;
using NLog;
using NLog.Config;
using NLog.Targets;

class Program
{
    // Define a static logger variable so that it references the logger instanced named "Scribe"
    private static readonly Logger log = LogManager.GetCurrentClassLogger();

    static void Main(string[] args)
    {
        ExtendNLogConfig();

        LogManager.ConfigurationReloaded += LogManager_ConfigurationReloaded;

        log.Info("Entering Application.");

        Console.WriteLine("Press any key to exit ...");
        Console.Read();
    }


    private static void LogManager_ConfigurationReloaded(object sender, LoggingConfigurationReloadedEventArgs e)
    {
        ExtendNLogConfig();
    }

    /// <summary>
    /// Extend the logging rules in the nlog.config with programmically rules.
    /// </summary>
    private static void ExtendNLogConfig()
    {
        //don't set  LogManager.Configuration because that will overwrite the nlog.config settings
        var consoleTarget = new ColoredConsoleTarget();
        consoleTarget.Name = "console";
        LogManager.Configuration.AddTarget("console", consoleTarget);

        consoleTarget.Layout = @"${date:format=HH\:mm\:ss} ${logger} ${message} ${exception} ${event-context:item=MyValue}";
        var rule1 = new LoggingRule("*", LogLevel.Debug, consoleTarget);
        LogManager.Configuration.LoggingRules.Add(rule1);
        LogManager.ReconfigExistingLoggers();
    }
}

```

**Comment by 304NotModified** [comment]
Need good name for it

**Comment by MikeFH** [comment]
A few remarks :
- Should the new method be on `LogManager` or `LogManager.Configuration` ?
- I suppose the overload would be applied on config reload but should it be also applied on config change ?
- Can the existing events on `LogManager` (`ConfigReloaded `and `ConfigChanged`) be used since we might want the overload to be applied before registered handlers to these events are executed ?
- Maybe `Overload` or `OverloadConfiguration` could be good names for the method
- Not directly related but there seems to be something strange with instantiations of `LoggingConfigurationChangedEventArgs`. If I'm not mistaken, arguments seems to be inverted (new config is passed as `oldConfiguration`).

**Comment by snakefoot** [comment]
Another idea could be to move the Variables from LoggingConfiguration to LogFactory.

Then have a marking on the variable-value whether it has been assigned from Nlog.config or by updating LogFactory.Variables from code.

Then one can assign LogFactory.Variables from code without them being overridden by NLog.config. Also variables will be applied correctly when loading NLog.config after having assigned a Nlog-variable (The variables will be available while parsing the Nlog.config).

**Comment by snakefoot** [comment]
I would think one would have the following scenarios:

1) Default configuration in code, that can be overridden by external Nlog.config. Solution check if LogManger.Configuration != null before loading configuration from code.

2) Default configuration in NLog.config that can be overridden by environment-config. This is usually changing variables according to environment. Solution apply the above solution to allow variables assigned from code to work while loading nlog.config.

**Comment by snakefoot** [comment]
Made an attempt to resolve this with `NLog.LogManager.Setup()`. See  #3871

**Comment by 304NotModified** [comment]
replace with `applyOnReload`

```
       // Act
            logFactory.Setup().
                LoadConfigurationFromFile().
                LoadConfiguration(applyOnReload, b =>
                {
                    b.Configuration.AddRuleForAllLevels("target1");
                })

```
