### ISSUE TITLE
Nlog mysql5.6 error

### ISSUE THREAD

**Issue by lovheot** [NLog/NLog#1437]
Hi! Thanks for reporting this question! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

**Type** (choose one):

- Question

**NLog version**: (e.g. 4.2.3)

**Platform**:  .Net 4.5
**Current NLog config** (xml)

Error 
Error when writing to database MySql.Data.MySqlClient.MySqlException (0x80004005): When @@GLOBAL.ENFORCE_GTID_CONSISTENCY = 1, the statements CREATE TEMPORARY TABLE and DROP TEMPORARY TABLE can be executed in a non-transactional context only, and require that AUTOCOMMIT = 1.
   在 MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   在 MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   在 MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   在 MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   在 NLog.Targets.DatabaseTarget.WriteEventToDatabase(LogEventInfo logEvent)
   在 NLog.Targets.DatabaseTarget.Write(AsyncLogEventInfo[] logEvents)

MySQL5.6

**Comment by 304NotModified** [comment]
Please post the xml config (without connectionstring)

**Comment by lovheot** [comment]
<target xsi:type="Database" name="errordb"
            dbProvider="MySql.Data.MySqlClient"
            commandText="Insert into ErrorMsg(Id,Ip, HostName, Time, Message, ErrorType, StackTrace, Level,Created) Values(@Id,@Ip, @HostName, @Time, @Message, @ErrorType, @StackTrace, @Level,getdate());"
            connectionString="">
      <parameter name="@Id" layout="${event-context:item=Guid}" />
      <parameter name="@Ip" layout="${event-context:item=LocalIP} " />
      <parameter name="@HostName" layout="${event-context:item=HostName}" />
      <parameter name="@Time" layout="${longdate}"  />
      <parameter name="@Message" layout="${message}" />
      <parameter name="@ErrorType" layout="${exception:format=type}" />
      <parameter name="@StackTrace" layout="${onexception:${exception:format=tostring} ${newline} ${stacktrace} ${newline}" />
      <parameter name="@Level" layout="${level}" />
    </target>


    <logger name="*" level="Error" writeTo="errordb" />

**Comment by 304NotModified** [comment]
Dunno where CREATE TEMPORARY TABLE and DROP TEMPORARY Table come from. 

Can you disable @@GLOBAL.ENFORCE_GTID_CONSISTENCY?

**Comment by 304NotModified** [comment]
Or `SET autocommit = 1`

**Comment by lovheot** [comment]
Mysql is used in the cloud 
not support

SET autocommit = 1   No effect

**Comment by lovheot** [comment]
I can provide test connectionstring  .  need?

**Comment by 304NotModified** [comment]
I'm not sure if we can help you with this.  Sounds a mysql thing

**Comment by lovheot** [comment]
Well it seems that I should re-select a cloud provider, thank you!
