### ISSUE TITLE
NLog Custom Target Guidance

### ISSUE THREAD

**Issue by ShaneCourtrille** [NLog/NLog#1438]
Is there any guidance for how an NLog Custom target should log exceptions that occur in it's processing? 

I can see an obvious infinite loop potential right off the bat for instance.

**Comment by 304NotModified** [comment]
There is no guide, but those exceptions should be written to the `InternalLogger`, e.g. ` InternalLogger.Log(exception, level, "Error has been raised.");`.

In NLog we use helpers like `exception.MustBeRethrown()`, but those are `internal`.

**Comment by ShaneCourtrille** [comment]
I took a look at the targets on github and they don't do any error catching.  The internalLogger is great to know about though as I do need to do some logging.

One specific case that would be good to know about is how the normal targets handle errors which would result in a message not being logged.

**Comment by 304NotModified** [comment]
> One specific case that would be good to know about is how the normal targets handle errors which would result in a message not being logged.

Well that's handled in the base classes, like Target, or LayoutRenderer

**Comment by 304NotModified** [comment]
Is this still an issue?
