### ISSUE TITLE
archiveOldFileOnStartup is not present in the wiki, had to find it through an SO issue

### ISSUE THREAD

**Issue by SoonDead** [NLog/NLog#1443]
The configuration option exists, but the [File target](https://github.com/nlog/nlog/wiki/File-target) wiki page does not list it.

The wiki page should list the configuration option.

**Comment by 304NotModified** [comment]
Thanks,

The docs has been added to the wiki https://github.com/NLog/NLog/wiki/File-target

PS: You can also edit the wiki.
