### ISSUE TITLE
settings lost when updating nuget package

### ISSUE THREAD

**Issue by jhaamit6666** [NLog/NLog#1447]
**Type**: Question

**NLog.Config version** : 4.3.3

**Platform**: .Net Framework 4.6.1

Does updating Nlog overwrites Nlog.config file? This way all the settings are lost. I was saved as I use TFS.

**Comment by 304NotModified** [comment]
Only if you update the NLog.config package 
, and visual studio should warn you.

**Comment by jhaamit6666** [comment]
OK.
So no improvement to be done?

**Comment by 304NotModified** [comment]
I don't think so, this is built-in Visual Studio
