### ISSUE TITLE
LoggingRule.ToString() produces any empty list of levels

### ISSUE THREAD

**Issue by jimrl** [NLog/NLog#1451]
- Bug

- 4.3.3

- Current result: `LoggingRule.ToString()` produces any empty list of levels, UNLESS `logLevels[0] == true`.

- Expected result: should list all selected levels.

I guess the culprit is NLog/src/NLog/Config/LoggingRule.cs:267
`               if (this.logLevels[0])`
 

I'm an utter github-n00b, so I don't know how to go about fixing this myself yet, sorry.

**Comment by 304NotModified** [comment]
Can you give a C# example of a LoggingRule instance where it goes wrong?

**Comment by jimrl** [comment]
Sure can:
`foreach (var rule in LogManager.Configuration.LoggingRules)
Console.WriteLine("rule: {0}", rule);
`
The corresponding part of my NLog.config is:
`  <rules>
    <logger name="*" minlevel="Info" writeTo="logfile" />
  </rules>
`

**Comment by 304NotModified** [comment]
Thanks! 


Found and fixed the bug! Will be released in 4.3.4!
