### ISSUE TITLE
NullReferenceException in LogManager.Shutdown()

### ISSUE THREAD

**Issue by lukaseckert** [NLog/NLog#1452]
Type: Bug
NLog Version: 4.3.3 (NuGet)
Platform: .Net 4.0
NLog config: (not applicable)

I have a console application which crashes on exit with a NullReferenceException in LogManager.Shutdown(). To reproduce:

1) Create a new console application project
2) Add the "NLog" NuGet package
3) Insert the following program:

```csharp
class Program
{
    static void Main(string[] args)
    {
        try
        {
            if (true)   // here are some conditions which check the requirements to load the application
            {
                Console.WriteLine("Press any key to exit!");
                Console.ReadLine();
                return;
            }
        } finally
        {
            LogManager.Shutdown();
        }
    }
}
```

Note that there is a NLog config file, but is has a custom name. The program is exited before
`LogManager.Configuration = new XmlLoggingConfiguration("...");`
was executed.

- What is the current result?
NullReferenceException in LogManager.Shutdown()

- What is the expected result?
Shutdown() should be able to handle the absence of a default config file and should not throw an exception.

- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
No, because there is no config file to turn it on.

- Please post full exception details (message, stacktrace, inner exceptions)
No inner exception, the stack trace only contains LogManager.Shutdown() after the last frame of my own code.

- Are there any work arrounds?
Catch and ignore the exception, but I consider this a rather ugly solution.

- Is there a version in which it did worked? 
Problem occurs with v2.x, v3.x and v4.x

**Comment by 304NotModified** [comment]
Thanks! This is fixed in #1453
