### ISSUE TITLE
Support .NET Core RC2 (CLI, dotnet)

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#1458]
Support new .NET Core stuff.

update after update of Microsoft's dependencies 

-  [x] CLI / dotnet instead of DNX
- [x] RC1 => RC2
- [x] support for netstandard (initital 1.4, future 1.2)
- [x] Update NLog.Extensions.Logging https://github.com/NLog/NLog.Extensions.Logging/
- [x] Update NLog for ASP.NET5 and rename https://github.com/NLog/NLog.web/

See CoreCLR / RC1 discussion: #641

**Comment by jacksontbryan** [comment]
I saw that the RC1 NLog extensions is not compatible with RC2.  RC2 dropped today.  Is there an ETA on when the 4.4 pre-release nuget will be updated to include RC2 support?

**Comment by phenixdotnet** [comment]
@jacksontbryan We need to evaluate the changes and update the build tools to support the RC2
Stay connected :)

**Comment by 304NotModified** [comment]
I hope on release next week, but maybe that's to optimistic.  Beside a lot of breaking changes for NLog there are also breaking changes for NLog.Extensions.Logging

**Comment by 304NotModified** [comment]
helpful link: https://github.com/StackExchange/dapper-dot-net/commit/ee615c0cc32f09d1f992f75ddbb0ee9150977ad4

**Comment by 304NotModified** [comment]
Info https://docs.asp.net/en/latest/migration/rc1-to-rc2.html

**Comment by phenixdotnet** [comment]
and 
http://dotnet.github.io/docs/core-concepts/dnx-migration.html
http://dotnet.github.io/docs/core-concepts/app-types.html

**Comment by phenixdotnet** [comment]
And now this is time to choice which frameworks we want to support:
https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md#mapping-the-net-platform-standard-to-platforms

netstandard1.0 and netstandard1.5 seem to be good candidates

**Comment by 304NotModified** [comment]
as low as possible ;)

AFAIK netstandard1.4 is now feasible and in the future (by splitting packages),  netstandard1.1/ netstandard1.2

**Comment by phenixdotnet** [comment]
^^
I started to work on netstandard1.0 and netstandard1.5.
Netstandard1.5 seem to be ok but netstandard1.0 has just about 2000 errors ^^'

coreCLR branch is updated with this work

**Comment by 304NotModified** [comment]
what about Netstandard1.4?

**Comment by phenixdotnet** [comment]
not tried for the moment :)

**Comment by jacksontbryan** [comment]
My vote would be 1.4 or 1.5 for a first pass so that downstream users of Core RC2 can be unblocked.  Then take a pass at tightening down to a lower version.

**Comment by 304NotModified** [comment]
well we have now netplatform 5.4 so I expect netstandard 1.4 is easy to get. But indeed, tightening down is something for the future

**Comment by 304NotModified** [comment]
working on this.

vs2015 is really unstable :(

**Comment by 304NotModified** [comment]
https://www.nuget.org/packages/NLog/4.4.0-beta6

Beta6 is now live. Please give feedback.  Didn't got xunit working yet.

**Comment by kae** [comment]
https://github.com/NLog/NLog/commit/52bd669fc5e11615f6ae07d234ccdf0cb5b9d47e

In this commit you changed define name from DOTNET54 to DOTNET5_4.
But didn't change it at least at some code files. 
Like here https://github.com/NLog/NLog/blob/bfc52e1540f48dd262524398b3a0efd5bee0a546/src/NLog/Targets/ColoredConsoleTarget.cs#L34

So there is some missing functionally in resulting build

**Comment by 304NotModified** [comment]
Thanks, inconsistent names are bad.

**Comment by kae** [comment]
I don't know what was the intension, but https://www.nuget.org/packages/NLog/4.4.0-beta7 still doesn't have Console or ColoredConsole

**Comment by 304NotModified** [comment]
> I don't know what was the intention, but https://www.nuget.org/packages/NLog/4.4.0-beta7 still doesn't have Console or ColoredConsole targets

Fixed in beta8 and on NuGet :)

**Comment by kae** [comment]
Confirmed!
Thanks for quick response!

**Comment by 304NotModified** [comment]
And thanks for the report & confirm! :+1:

**Comment by 304NotModified** [comment]
NLog.Web.ASPNET5 has been upgraded and renamed to NLog.Web.AspNetCore

https://www.nuget.org/packages/NLog.Web.AspNetCore/4.2.3

This is all done now

**Comment by niemyjski** [comment]
Question, what about .net standard support?

**Comment by 304NotModified** [comment]
It has now netstandard1.3 support. See nuget
