### ISSUE TITLE
About the target framework version

### ISSUE THREAD

**Issue by niaoked** [NLog/NLog#1465]
Official documents says that Nlog supports multiple versions of the.NET framework, how to get the components of the specified.Net Framework version from Nuget? for example,I want to use in a target .net framework 4.0 version.

**Comment by 304NotModified** [comment]
Yes NLog had specialised builds for Silverlight, net35, net40, net45 etc. 

Those builds are in one nuget package and nuget will handle that for you.  Just unzip and nupkg and you can see it.

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, let us know!
