### ISSUE TITLE
Custom properties in Csv header

### ISSUE THREAD

**Issue by Bubuhubu87** [NLog/NLog#1473]
**Type: Question**

**NLog version: 4.3.4**

**Platform: .Net 4.5.2**

Hello again,

I have another question about header in csv layout. Is it possible to put some custom properties in csv header?

I tried:

```
<layout xsi:type="CsvLayout" withHeader="true"
              header="Column1;Column2; Column3;${newline}
              ${event-properties:item=prop1}; ${longdate}; ${windows-identity}; 
```
```
<layout xsi:type="CsvLayout" withHeader="true"
              header="Column1;Column2; Column3;${newline}
              ${event-context:item=prop1}; ${longdate}; ${windows-identity}; 
```
```
<layout xsi:type="CsvLayout" withHeader="true"
              header="Column1;Column2; Column3;${newline}
              ${event-properties:prop1}; ${longdate}; ${windows-identity}; 
```

and as far as ${longdate} and ${windows-identity} are working correctly, I couldn't pass my own parameter. Maybe someone have any idea how to do it?

**Comment by 304NotModified** [comment]
You can use the layout renderers which aren't dependent of logevents.

**Comment by Bubuhubu87** [comment]
If I remember correctly, I used layout renderes and I had similar problems, but I managed that issue by variables.

` <variable name="prop1" value=""  />`

in header 

`${var:prop1}`

and code

`LogManager.Configuration.Variables["prop1"] = myValue;`

and its working prefectly.

But I have another problem, Is it possible to update header ? 

"myValue" will change lot of time while program is executed, and I need to update this variable in header.

**Comment by 304NotModified** [comment]
> But I have another problem, Is it possible to update header ?
> 
> "myValue" will change lot of time while program is executed, and I need to update this variable in header.

yes, by `LogManager.Configuration.Variables["prop1"] = myValue;`. When the header is written, `${var:prop1}` is rendered with the current data in `LogManager.Configuration.Variables`

**Comment by Bubuhubu87** [comment]
Simple example, 

Config

```
<targets>
    <target xsi:type="File" name ="Log" fileName="${basedir}/Log.csv" encoding="utf-8">
      <layout xsi:type="LayoutWithHeaderAndFooter" >
        <header xsi:type="SimpleLayout" text= "Name1;Name2;Name3 
                      ${newline}
                      ${var:prop1}; ${var:prop2}; ${var:prop3}
                      ${newline}${newline}
                      Details
                      ${newline}
                      Name1; Name2; Name3"
        />
        <layout xsi:type="CsvLayout" delimiter="Semicolon">
          <column layout="Column1" />
          <column layout="Column2" />
          <column layout="Column3" />
        </layout>
      </layout>
    </target>
  </targets>
```

Code

 ```
var eventInfo = new LogEventInfo(LogLevel.Info, "", "");
LogManager.Configuration.Variables["prop1"] = "1";
LogManager.Configuration.Variables["prop1"] = "2";
LogManager.Configuration.Variables["prop1"] = "5";

LogManager.Configuration.Variables["prop2"] = "a";
LogManager.Configuration.Variables["prop2"] = "b";
LogManager.Configuration.Variables["prop2"] = "6";

LogManager.Configuration.Variables["prop3"] = "x";
LogManager.Configuration.Variables["prop3"] = "y";
LogManager.Configuration.Variables["prop3"] = "7";
LogManager.GetCurrentClassLogger().Log(eventInfo);
```

That code like you said will update every property first time, but if you use GetCurrentClassLogger().Log()  before 

LogManager.Configuration.Variables["prop3"] = "x";

in Log.csv file you will get empty value for prop3.

**Comment by 304NotModified** [comment]
Well the header is already written? You can't edit the file header once it got written

**Comment by 304NotModified** [comment]
Is this still an issue?

**Comment by 304NotModified** [comment]
We assume this question has been answered. If not, just let us know!
