### ISSUE TITLE
Logging exceptions in case of exceptions.

### ISSUE THREAD

**Issue by qchroman** [NLog/NLog#1478]
**Type**: Question
**NLog version**: 4.3.4
**Platform**: Silverlight

Hello all,

Please, let me know if there is a way to catch an exception inside a custom target and push it up in the hierarchy so I could get a notification in my main application and log it.

The case is simple, I have a webclient making requests to my service. The webclient target is a custom target wrapped in async wrapper which is wrapped in retrying wrapper.

In case of an exception I call 

`logEvent.Continuation.Invoke(ex);`

To let the retrying wrapper know that it needs to retry, but, when I for some reason fail to reach the service I'm calling, I want to log in a file the reason (response code from the server, for example).

Is it something that can be done?

The code inside the target is very simple:

```c#
protected override void Write(Common.AsyncLogEventInfo logEvent)
{
    WebClient wc = new WebClient();

    wc.UploadStringAsync(Url, "POST", Layout.Render(logEvent.LogEvent));
    wc.UploadStringCompleted += (o, e) =>
    {
        try
        {
            var result = e.Result;

            // Do something with result.
        }
        catch (Exception ex) 
        {
            if (ex.InnerException is WebException)
            { 
                // Get status
            }

            // Let other wrappers know that there was an exception here so they could do their job like retry, for example.
            logEvent.Continuation.Invoke(ex);
        }
    };
}
```

Thank you.

**Comment by 304NotModified** [comment]
> I want to log in a file the reason

Do you need to log it to a file or thrown an exception?

**Comment by qchroman** [comment]
Anything will do. If the _logger.Log() will throw an exception that I ca throw inside my custom target - great. If I can use some internal logger inside the target which I can first configure to write in a specific file with a specific layout (or even use the logger of the main application which I use to log main app events and errors) - will also work.

**Comment by 304NotModified** [comment]
I'm not sure if I fully understand your case, but the error patern in our targets is:

```c#
 catch (Exception ex)
 {
  //error/warn. Optional, if skipped, written as error to the InternalLogger
     InternalLogger.Warn(ex, "reading 'From' from .config failed.");

     if (ex.MustBeRethrown())
     {
         throw;
     }

 }

```

**Comment by qchroman** [comment]
Thank you for that. The use case is simple. I have my app in which I setup two loggers - one logs data into the file. Another logs different events using remote API. For the first one I use file target. For the second one I needed to create customer target because I needed to send custom headers to the API.

What I want to be able to do is log exceptions in a file using file logger in case API logger failed for some reason (API responded with 404 or some other HTTP code, for example). So, the question is - is it possible to log exception which happens in my custom API logger and log it using my file logger?

Thank you.

**Comment by 304NotModified** [comment]
> o, the question is - is it possible to log exception which happens in my custom API logger and log it using my file logger?

In you custom API logger:

```c#
var logger = LogManager.GetLogger("myCustomApiLogger").
```

and in your config 

```xml
  <rules>
    <logger name="myCustomApiLogger" minlevel="Trace" writeTo="myOtherTarget" />

```

?

**Comment by qchroman** [comment]
I will give it a try with rules. Thank you.

**Comment by qchroman** [comment]
Worked perfectly. Thank you very much!

**Comment by 304NotModified** [comment]
:+1:
