### ISSUE TITLE
RunSynchronously get stuck when calling .Factory.Flush()

### ISSUE THREAD

**Issue by amitbarkai** [NLog/NLog#1480]
Hi 
it is seems like when calling the  logger.Factory.Flush();
the RunSynchronously function is called and get stuck and affecting the calling thread
ev.WaitOne();  seems the be the reason .
am i doing somthng wrong ?

problem started after upgrading the version to 4.3.3 before is was 3.1.0 and everything worked fine

```
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <extensions>
      <add assembly="NLogTest" />
    </extensions>
    <targets async="true">
      <target xsi:type="NLogRichViewer" name="ctrl" />
    </targets>
    <rules>
      <logger name="*" minlevel="Trace" appendTo="ctrl" />
    </rules>
  </nlog>
```

**Comment by 304NotModified** [comment]
That seems to be a bug. It there an exception thrown (see internal log)?

It this also the case without the extension?

**Comment by amitbarkai** [comment]
when i removed the extentions the problem was resolved.

**Comment by amitbarkai** [comment]
do you recommend to removed them or there is a diffrent workarrownd that could prevent 
the calling thread from getting stuck.

** just to be clear the thread is stuck untill the flush is done ( all write call are executed ) , when the expected behaviour is that the flush will be down asynchronously

**Comment by amitbarkai** [comment]
i've created an example of tartget that could cause the issue
```
public class LongTarget : Target
    {
        protected override void Write(LogEventInfo logEvent)
        {
           Thread.Sleep(1000); <- mock a long write action
        }
        
    }
logger.Factory.Flush(e=> {});  <- also solved the issue
```

**Comment by 304NotModified** [comment]
Too be clear:
> i've created an example of tartget that could cause the issue
> 
> public class LongTarget : Target
>     {
>         protected override void Write(LogEventInfo logEvent)
>         {
>            Thread.Sleep(1000); <- mock a long write action
>         }
> 
>     }

This will block more then 1 second (1000ms)? 

> logger.Factory.Flush(e=> {});  <- also solved the issue

This will work even with the ` Thread.Sleep(1000);` and `logger.Factory.Flush();` doesn't?

**Comment by amitbarkai** [comment]
this is the full code usage , in addition to the previous one
`            var logger = LogManager.GetCurrentClassLogger();
            var stopWatch = new Stopwatch();
            stopWatch.Start();
            for (var i = 0; i < 10; i++)
            {
                logger.Info(i);
            }
            // option 1. takes 10 secounds logger.Factory.Flush();
            logger.Factory.Flush(e=> {});
            Console.WriteLine(stopWatch.ElapsedMilliseconds);`

since i used an async target the logger.info calls dosent execute the write function.
when the first part is executed ( we will need to wait 10 secounds )
if the secound option is called the write calls will be done asynchronously

**Comment by 304NotModified** [comment]
AFAIK this is expected behaviour?

`logger.Factory.Flush();` will do a synchronously call. You need that sometimes, other wise the program will be stopped before everything is written. If there is a processtime of 10 sec, then it will take indeed 10 sec. 

`logger.Factory.Flush(e => {});` is the async call. 

` logger.Factory.Flush(TimeSpan.FromSeconds(2));` will stop after 2 second or before, disregarding if everything is written.

**Comment by 304NotModified** [comment]
Is this still an issue?

**Comment by amitbarkai** [comment]
We removed the flush call.
For now.
The stacked logs are executed asynchronously later without affecting the
performance
