### ISSUE TITLE
Using NLog from within Webservice - does not output messages

### ISSUE THREAD

**Issue by gpdoud** [NLog/NLog#1485]
I want to use NLog from within a WCF service to write to a database table. I created a console application, included NLog within it, created the NLog.config file, and was able to successfully log messages to the database. I then included NLog in my WCF service, used the same NLog.config file, but no messages are written to the database with exactly the same NLog.config.

Can anyone help?

**Comment by 304NotModified** [comment]
Please use the template.  Needed info is now missing.

**Comment by gpdoud** [comment]
I want to use NLog from within a WCF service to write messages to a database table and possibly a file. I created a console application, included NLog within it, created the embedded NLog.config file, and was able to successfully log messages to the database and the file. I then included NLog in my WCF service, used the same NLog.config file, but no messages are written to the database or the file with exactly the same NLog version and NLog.config.

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

**Type** (choose one): Question

**NLog version**: 4.3.4

**Platform**: .Net 4.5

**Current NLog config** (xml or C#, if relevant)

<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="true"
      internalLogLevel="On" internalLogFile="c:\temp\nlog-internal.log" >


  
  <variable name="myvar" value="myvalue"/>

  
  <targets>

    

	  <target xsi:type="File" name="f" fileName="${basedir}/logs/Log-${shortdate}.log"
		 layout="${longdate} ${logger} ${uppercase:${level}} ${message}" />
	  
	  <target xsi:type="Database" name="db2" connectionStringName="MRIDEV2" commandText="[dbo].[MRI_ERROR_LOGGING]" commandType="StoredProcedure">
		  <parameter name="@LogLogger" layout="${logger}" />
		  <parameter name="@LogDateTime" layout="${date}" />
		  <parameter name="@LogSource" layout="${callsite}:${callsite-linenumber}" />
		  <parameter name="@LogLevel" layout="${level}" />
		  <parameter name="@LogMessage" layout="${message}" />
		  <parameter name="@LogVariable1" layout="${literal:text=Log Var 1}" />
		  <parameter name="@LogVariable2" layout="${literal:text=Log Var 2}" />
		  <parameter name="@LogVariable3" layout="${literal:text=Log Var 3}" />
	  </target>
	  
  </targets>

  <rules>
    
	  <logger name="*" minlevel="Trace" writeTo="f" />
	  <logger name="*" minlevel="Trace" writeTo="db2" />
    
  </rules>
</nlog>

In case of a BUG:

- What is the current result?
No records are written to either the file or the database.
- What is the expected result?
Database and file records would be written.
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
Yes. Nothing is in the file.
- Please post full exception details (message, stacktrace, inner exceptions)
No exception appears to be generated.
- Are there any work arounds? No
- Is there a version in which it did worked? 
The current version is the only one I've used.
- Can you help us by writing an unit test?
If I can.


in case of a FEATURE REQUEST:
 
 - Why do we need it?
 - An example of the XML config, if relevant.

**Comment by 304NotModified** [comment]
Please set the `internalLogLevel` to `debug` and check again. `on` isn't a valid loglevel.

**Comment by gpdoud** [comment]
That allowed me to see an exception that was being thrown which allowed me to correct it and now I'm getting the messages in the database.

Thank you.

**Comment by 304NotModified** [comment]
:+1: glad it has been solved :)
