### ISSUE TITLE
Async methods with a return value have incorrect method name at callsite

### ISSUE THREAD

**Issue by PELNZ** [NLog/NLog#1491]
**Type**: Bug
**NLog version**: 4.3.4

**Platform**: .Net 4.5

**What is the current result?**
Async methods with a return value (i.e. Task<T> return type) result in the method builder method being logged as the callsite (e.g. class.+<method>._dX.MoveNext()) instead of the expected method name. Void (i.e. Task return type) work as expected.

**FIX**:
Line 163 of LoggerImpl.cs needs to change from:

`if (declaringType == typeof(System.Runtime.CompilerServices.AsyncTaskMethodBuilder))`

to

`if (declaringType == typeof(System.Runtime.CompilerServices.AsyncTaskMethodBuilder) || declaringType == typeof(System.Runtime.CompilerServices.AsyncTaskMethodBuilder<>))`

**What is the expected result?**
It should log the async method name as the callsite

**Can you help us by writing an unit test?**
    
        [Fact]
        public void CallSiteShouldWorkForAsyncMethodsWithReturnValue()
        {
            var callSite = GetAsyncCallSite().GetAwaiter().GetResult();
            Assert.Equal("NLog.UnitTests.LayoutRenderers.CallSiteTests.GetAsyncCallSite", callSite);
        }
        
        public async Task<string> GetAsyncCallSite()
        {
            Type loggerType = typeof(Logger);
            var stacktrace = StackTraceUsageUtils.GetWriteStackTrace(loggerType);
            var index = LoggerImpl.FindCallingMethodOnStackTrace(stacktrace, loggerType);
            var logEvent = new LogEventInfo(LogLevel.Error, "logger1", "message1");
            logEvent.SetStackTrace(stacktrace, index);

            await Task.Delay(0);

            Layout l = "${callsite}";
            var callSite = l.Render(logEvent);
            return callSite;
        }

**Comment by 304NotModified** [comment]
Thanks!

**Comment by PELNZ** [comment]
Sorry, I'll let you kindly do the merge as I'm not certain of how to do it!

**Comment by 304NotModified** [comment]
OK np!

**Comment by 304NotModified** [comment]
Works well! I have created a PR :)
