### ISSUE TITLE
NLog didn't install on WinPhone + UWP + PCL

### ISSUE THREAD

**Issue by reader-man** [NLog/NLog#1492]
Hi,
I tried installing NLog nuget to a Xamarin.Forms Portable Solution

**Type** 
- Bug

**NLog version**: 4.3.4

**Platform**: WinPhone + UWP + PCL

In case of a BUG:

- What is the current result?
Could not install package 'NLog 4.3.4'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

- What is the expected result?
I thought that it will install in WinPhone + PCL and was hoping for UWP.

- Is there a version in which it did worked? 
first try
- Can you help us by writing an unit test?
There is no need as this is an installation.

![nlog](https://cloud.githubusercontent.com/assets/12806275/15727251/f6acff58-285d-11e6-9e53-bf78d73b8664.jpg)

**Comment by 304NotModified** [comment]
Too bad PCL isn't supported. With nlog 4.4 there is support for netstandard, which replaces PCL

**Comment by 304NotModified** [comment]
See https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md

**Comment by 304NotModified** [comment]
So could you try the latest NLog beta?

**Comment by reader-man** [comment]
yes, this error after trying to install the beta to **all projects**:
`Could not install package 'NLog 4.4.0-beta11'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.`

And this was given when trying to install it on only the **.Droid + .iOS projects**:
`Could not install package 'Microsoft.NETCore.Runtime.Native 1.0.2-rc2-24027'. You are trying to install this package into a project that targets 'Xamarin.iOS,Version=v1.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.`

and this is what came after trying with **only .Droid Project**:
`Could not install package 'Microsoft.NETCore.Runtime.Native 1.0.2-rc2-24027'. You are trying to install this package into a project that targets 'MonoAndroid,Version=v6.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.`

and this is what came after trying with **only .iOS Project**:
`Could not install package 'Microsoft.NETCore.Runtime.Native 1.0.2-rc2-24027'. You are trying to install this package into a project that targets 'Xamarin.iOS,Version=v1.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.`

and this is what came after trying **a normal PCL class library**:
`Could not install package 'NLog 4.4.0-beta11'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.`

**Comment by 304NotModified** [comment]
the netstandard is a fail then. It should support Xamarin, but it doesn't it seems. Not sure if that will be fixed in .NET Core RTM.

The "bait and switch" for PCL could work, but I dunno if I can generate the "the bait", see http://log.paulbetts.org/the-bait-and-switch-pcl-trick/

**Comment by 304NotModified** [comment]
Is this in Visual Studio or Xamarin Studio? Is Visual Studio 2015 up-to-date (update 2) and with the latest NuGet?

**Comment by reader-man** [comment]
Yes, the "Bait" idea/trick needs rethinking.

and I am using VS 2015 u2, And the latest Nuget "3.4.3.855".

**Comment by 304NotModified** [comment]
Is it possible to test with Xamarin Studio?

**Comment by reader-man** [comment]
I don't have Xamarin Studio, and i have never used it, only used VS, and with VS i am developing Xamarin.Forms apps.

**Comment by 304NotModified** [comment]
Do you have experience with "bait and switch" PCL's?

**Comment by reader-man** [comment]
No, But i read about it before.

**Comment by 304NotModified** [comment]
closing this, feature request is at https://github.com/NLog/NLog/issues/155
