### ISSUE TITLE
how to Log every request and responses using httphandler 

### ISSUE THREAD

**Issue by RIIMLLC** [NLog/NLog#1501]

**Comment by RIIMLLC** [comment]
<?xml version="1.0" encoding="utf-8" ?>

<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" autoReload="true">
  <targets async="true">
    <target name="database" xsi:type="Database"
            connectionStringName="NlogSql"
            commandText="INSERT INTO [dbo].[NLog] ([MachineName], [Level], [UserName], [Message], [Logger],[Callsite],[Exception])
            VALUES(@MachineName,@Level,@Username,@Message,@Logger,@CallSite,@Exception);">

      

      <parameter name="@MachineName" layout="${machinename}" />
      <parameter name="@Level" layout="${level}" />
      <parameter name="@Username" layout="${windows-identity:domain=true}" />
      <parameter name="@Message" layout="${message}" />
      <parameter name="@Logger" layout="${logger}" />
      <parameter name="@CallSite" layout="${callsite:filename=true}" />
      <parameter name="@Exception" layout="${exception}" />
    </target>
  </targets>
  <rules>
    <logger name="databaseLogger" minlevel="Trace" writeTo="database"/>
  </rules>

</nlog>

**Comment by 304NotModified** [comment]
You need NLog.Web

See https://github.com/NLog/NLog.Web/wiki/Log-HTTP-calls

**Comment by 304NotModified** [comment]
If you have further questions, please use the template.
