### ISSUE TITLE
logging with BufferingWrapper and big flushTimeout

### ISSUE THREAD

**Issue by Bouki6** [NLog/NLog#1505]
Hello.
I'm trying to use the `BufferingWrapper` in order to log the events. but when i set the `flushTimeout` more than 700 milliseconds it doesn't write any thing.
 i reduce the `flushTimeout` to 500 and its working. but it writes to file in completely unregulated time stamps. mostly after about 5 or 6 seconds!!!
I'm trying to reach the maximum performance in logging without losing any line. do you have any suggestions?
**Type** : Question
**NLog version:** (4.3.4)
**Platform**: .Net 4.5
**Current NLog config**
```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="false"
      internalLogLevel="Off" internalLogFile="c:\temp\nlog-internal.log" >

	<variable name="logDirectory" value="C:\Logs" />
	<variable name="layout" value="[${level:uppercase=true}];[${longdate}];[${processid}];[${threadid}];${message}" />

	<targets>
		<target xsi:type="BufferingWrapper" name="allasync" slidingTimeout="true" bufferSize="100000" flushTimeout="500">
			<target name="all" xsi:type="File" encoding="utf-8"  layout="${layout}" fileName="${logDirectory}\All#${shortdate}.log"/>
		</target>
		<target xsi:type="BufferingWrapper" name="errorsasync" slidingTimeout="true" bufferSize="100000" flushTimeout="500">
			<target name="errors" xsi:type="File" encoding="utf-8"  layout="${layout}" fileName="${logDirectory}\Errors#${shortdate}.log"/>
		</target>
	</targets>

	<rules> 
		<logger name="*" minlevel="Trace" maxlevel="Fatal" writeTo="allasync"/> 
		<logger name="*" minlevel="Error" maxlevel="Fatal" writeTo="errorsasync"/> 
	</rules> 
	
</nlog>
```

**Comment by 304NotModified** [comment]
I don't kboe you logging cofe but I guess slidingTimeout should be on false?

**Comment by Bouki6** [comment]
Thank you very much for the prompt reply. but as you can see in my log.config file sliding-timeout set true. i just test my code in 4 different machines and funny thing is i get the different result in each!!! i guess something is wrong about `BufferingWrapper ` or i miss something .

**Comment by 304NotModified** [comment]
http://nlog-project.org/documentation/v4.0.0/html/P_NLog_Targets_Wrappers_BufferingTargetWrapper_SlidingTimeout.htm

>This value determines how the inactivity period is determined. If sliding timeout is enabled, the inactivity timer is reset after each write, if it is disabled - inactivity timer will count from the first event written to the buffer.

 If there are log events written  constantly, it wont write to the target (file) .
