### ISSUE TITLE
Getting a valid ${callsite} with ASP.NET Core RC2

### ISSUE THREAD

**Issue by EltonInAtlanta** [NLog/NLog#1512]
Question - 

I'm using NLog with asp.net core rc2. 
("NLog.Extensions.Logging": "1.0.0-rc2-final-2016-05-21") 
I'm having difficulty getting the location of the logging event using the ${callsite} tag in the layout. 

I'm using the full .net, not the core library.

Here's my startup:
`Public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
    {
        loggerFactory.AddNLog();
        env.ConfigureNLog("NLog.config");`

Here's my config:
`<target xsi:type="File" name="infolog" fileName="${basedir}/logs/info-${shortdate}.log"
      layout="${longdate}|${level}|${callsite:className=true:methodName=true}|${machinename}|${message}" />`

My output always has the MS logging extension wrapper....
`2016-06-20 16:00:03.4458|Info|Microsoft.Extensions.Logging.Logger.Log ...`

**Comment by 304NotModified** [comment]
Hi, 

Which platform are you using (in project.json)

**Comment by EltonInAtlanta** [comment]
"frameworks": {
    "net461": {

**Comment by 304NotModified** [comment]
I guess it works in netcoreapp. The root problem is here that we don't know if we are running on netcore. Its unclear how to fix this.  Is this something you can confirm?

**Comment by EltonInAtlanta** [comment]
Hi.  Thanks for looking at this with me.  I'm on the East coast, so we might be out of sync timezone wise.  I'm running only on the full .net framework.  Right now I have an experimental API and can look at anything you want.  I'm new to the ASP.NET Core environment though, and somewhat new to NLog (which is great!).  I'd be happy to try a demo app for you if that would help.  Also, I ran across this on SO and it seemed on point (http://stackoverflow.com/questions/7412156/how-to-retain-callsite-information-when-wrapping-nlog?rq=1).  I'm hesitant to dive into your source code though.

**Comment by 304NotModified** [comment]
Yeah, well I'm on holiday and I'm in UTC+1/+2 ;)

Work around is the use `${logger}` in some cases, but the loggername is not the same as the callsite.

**Comment by EltonInAtlanta** [comment]
We are on different schedules!  Thanks for taking time on your holiday.

**Comment by 304NotModified** [comment]
hey! Sorry I has been a while, more busy then expected.

Looking at this. Do you have some C# call examples?

**Comment by 304NotModified** [comment]
Confirmed.

This was working:

```c#
//typeof logger: NLog.Logger
Logger.Info("Index page says hello");
```

this wasn't working:

```c#
//typeof _logger: Microsoft.Extensions.Logging.ILogger
 _logger.LogInformation("info 2 with DI");
```


Work around:

```
  LogManager.AddHiddenAssembly(Assembly.Load(new AssemblyName("Microsoft.Extensions.Logging")));
            LogManager.AddHiddenAssembly(Assembly.Load(new AssemblyName("Microsoft.Extensions.Logging.Abstractions")));

            loggerFactory.AddNLog();

```

Will fix this

**Comment by 304NotModified** [comment]
fixed in https://www.nuget.org/packages/NLog.Extensions.Logging/1.0.0-rtm-alpha3

**Comment by EltonInAtlanta** [comment]
Excellent.
Async methods look slightly funny.  In ASP.Net Core 1.0 (.Net 4.6 target) I see this:
```
[HttpGet]
 public async Task<IActionResult> Get()
        {
...
            Logger.LogTrace("Wallet Get");
...
       }

[Route("/api/wallet/choices")]
[HttpGet]
public IActionResult Choices()
{
     {
...
         Logger.LogTrace("Choices");
...
 }
```
```
layout="${logger}|${message}|${callsite:className=true:methodName=true}"

wallet.Controllers.WalletController|Wallet Get|wallet.Controllers.WalletController+<Get>d__6.MoveNext
wallet.Controllers.WalletController|Choices|wallet.Controllers.WalletController.Choices
```

**Comment by 304NotModified** [comment]
OK, If you create a new issue, I will try to look at that.

This one can be closed right?

**Comment by EltonInAtlanta** [comment]
Yes.
