### ISSUE TITLE
Please update for .netcore 1.0

### ISSUE THREAD

**Issue by MihaMarkic** [NLog/NLog#1519]
This is the error I'm getting from a .net core console app after upgrade from RC2 to RTM

Error: assembly specified in the dependencies manifest was not found -- package: 'System.Diagnostics.TraceSource', version: '4.0.0-rc2-24027', path: 'runtimes/unix/lib/netstandard1.3/System.Diagnostics.TraceSource.dll'

**Comment by 304NotModified** [comment]
Thanks for the report.  Haven't had time to test it. Will try to fix it this week

**Comment by MihaMarkic** [comment]
The reference to TraceSource.dll or something is outdated, nothing big. At least it seems so. 
What branch is used? I might try it on my own.

**Comment by phenixdotnet** [comment]
Hi.

You can test (and make a PR ;)) using the coreCLR branch.

**Comment by MihaMarkic** [comment]
Of course, now that I know which of the million branches is used :-)

**Comment by phenixdotnet** [comment]
ah ah ah, yes @304NotModified really loveeee branches ;)

Thanks !

**Comment by 304NotModified** [comment]
thanks @phenixdotnet 

working on this @MihaMarkic ? I'm now looking at it.

**Comment by MihaMarkic** [comment]
@304NotModified Just forked it, but probably won't have time today as it kinda late.

**Comment by 304NotModified** [comment]
OK thanks for the feedback @MihaMarkic !

Now updating on my machine. It builds for now, now let's see what the unit tests will do

**Comment by MihaMarkic** [comment]
@304NotModified Awesome.

**Comment by 304NotModified** [comment]
beta12 is on NuGet: https://www.nuget.org/packages/NLog/4.4.0-beta12

**Comment by 304NotModified** [comment]
The unit tests where only showing some outstanding issues, so it seems to work. Feedback on usage will be appreciated :)

**Comment by MihaMarkic** [comment]
Works, thanks.

**Comment by 304NotModified** [comment]
Cool! Thanks for the feedback!
