### ISSUE TITLE
Failure to install on Visual Studio 2013 Update 5

### ISSUE THREAD

**Issue by mallim** [NLog/NLog#1522]
**Type** (choose one):

- Question

**NLog version**: NLog 4.4.0-beta12

**Platform**: .Net Core 4.5.1 

We are not looking at a suitable logging framework for our dot net core project and will like to try nlog out.

Upon using the NuGet from VS 2013 update 5 to install, we are getting the error message below:

````
Successfully uninstalled 'NLog 4.4.0-beta12'.
Install failed. Rolling back...
Could not install package 'NLog 4.4.0-beta12'. You are trying to install this package into a project that targets '.NETCore,Version=v4.5.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
````

Any advice is much appreciated.
Ian Lim

**Comment by 304NotModified** [comment]
Could you post your project.json?

**Comment by mallim** [comment]
We don't have project.json in our VS project

**Comment by 304NotModified** [comment]
I'm confused. You need VS2015 for .NET Core?

**Comment by 304NotModified** [comment]
Is this still an issue?

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, let us know!
