### ISSUE TITLE
${machinename} breaks NLog in .NET Core

### ISSUE THREAD

**Issue by akatz0813** [NLog/NLog#1523]
Hi! Thanks for reporting this feature/bug/question! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

**Type** (choose one): Bug

**NLog version**: 4.4.0-beta12

**Platform**: .Net Core 1.0

**Current NLog config** (xml or C#, if relevant)

This breaks:
    <target name="file"
           xsi:type="File"
           fileName="${logDirectory}/${machinename}-HttpS2SProcessor.log"
           archiveFileName="${logDirectory}/${machinename}-HttpS2SProcessor.{#####}.log"
           archiveEvery="Hour"
           archiveNumbering="Sequence"
           keepFileOpen="true"
           maxArchiveFiles="999"
           layout="${date:format=yyyy-MM-dd HH\:mm\:ss}|${threadid}|${level:fixedLength=true:padding=1:uppercase=true}|${logger:shortname=true}|${message} ${exception:format=tostring}" />

This works:
    <target name="file"
           xsi:type="File"
           fileName="${logDirectory}/abc}-HttpS2SProcessor.log"
           archiveFileName="${logDirectory}/abc-HttpS2SProcessor.{#####}.log"
           archiveEvery="Hour"
           archiveNumbering="Sequence"
           keepFileOpen="true"
           maxArchiveFiles="999"
           layout="${date:format=yyyy-MM-dd HH\:mm\:ss}|${threadid}|${level:fixedLength=true:padding=1:uppercase=true}|${logger:shortname=true}|${message} ${exception:format=tostring}" />

This is all despite not even using the target.   The only logger I have is:

   <logger name="*" minlevel="Debug" writeTo="console" />

Desired Result is for ${machinename} to work on .NET Core.

**Comment by 304NotModified** [comment]
This one is indeed not supported yet: https://github.com/NLog/NLog/wiki/platform-support

Any idea how we get the machine name in c# with netcore?

**Comment by 304NotModified** [comment]
Looks like it has been added in rc2

https://github.com/dotnet/corefx/pull/5428

**Comment by akatz0813** [comment]
Yep! Was just going to reply with that. 






On Thu, Jun 30, 2016 at 1:53 PM -0700, "Julian Verdurmen" <notifications@github.com> wrote:












Looks like it has been added in rc2



dotnet/corefx#5428

**Comment by akatz0813** [comment]
Although this will bump you up to netstandard 1.5. You'll probably want to conditionally target 1.5. 






On Thu, Jun 30, 2016 at 2:06 PM -0700, "Andrew Katz" <akatz@mparticle.com> wrote:










Yep! Was just going to reply with that. 






On Thu, Jun 30, 2016 at 1:53 PM -0700, "Julian Verdurmen" <notifications@github.com> wrote:












Looks like it has been added in rc2



dotnet/corefx#5428

**Comment by 304NotModified** [comment]
Ah good to know. Any idea where you  could see that netstandard1.5 is needed?

**Comment by akatz0813** [comment]
http://packagesearch.azurewebsites.net/?q=Machinename






On Thu, Jun 30, 2016 at 2:19 PM -0700, "Julian Verdurmen" <notifications@github.com> wrote:












Ah good to know. Any idea where you  could see that netstandard1.5 is needed?

**Comment by 304NotModified** [comment]
PR would be nice (coreCLR branch) 

My VS is broken after update3. Can't open any project :(

**Comment by akatz0813** [comment]
@304NotModified would you point me to the area of code.  Will get PR submitted immediately.

**Comment by akatz0813** [comment]
@304NotModified https://github.com/NLog/NLog/pull/1526

**Comment by akatz0813** [comment]
When do you think you'll push to Nuget?

**Comment by 304NotModified** [comment]
This weekend. Build pc not fixed yet.

**Comment by 304NotModified** [comment]
https://www.nuget.org/packages/NLog/4.4.0-beta13

Published from AppVeyor :)

Thanks for the submit!
