### ISSUE TITLE
Support Android 4.4

### ISSUE THREAD

**Issue by programatix** [NLog/NLog#1527]
**Type** (choose one): Question
**NLog version**: 4.3.2 and above
**Platform**: Xamarin Android

I noted that NLog version 4.3.0 and 4.3.1, the target Android version is 5. NLog version 4.3.2 and above are targeting Android 6.

Is it possible to reduce the target to Android 4.4?

Thanks.

**Comment by 304NotModified** [comment]
Why is this closed? Not needed anymore?

**Comment by programatix** [comment]
I found out that this is somehow a non-issue if we have the latest Android SDK. We just need to compile using the Android SDK version equal or higher than used to compile NLog. The compiled app/dll still work for target earlier than the SDK version.

**Comment by 304NotModified** [comment]
Ok thanks for the update

**Comment by 304NotModified** [comment]
FYI supported 4.4 in https://github.com/NLog/NLog/pull/1531

**Comment by programatix** [comment]
Thank you.
