### ISSUE TITLE
NLog Extension Security

### ISSUE THREAD

**Issue by INotDisposable** [NLog/NLog#1530]
**Type** (choose one):  Feature request
**NLog version**: 4.3.5
**Platform**: All

Currently NLog will load any extension files mentioned in the config XML, or any DLL with the name 'NLog*.dll'.  Our product is sometimes installed on systems that use the FAT32 or exFAT filesystem, and thus does not have any integrated filesystem security.  Placing a rogue NLog*.dll file in our application folder would allow someone to inject code into our logger.

All of our files are signed and timestamped according to Microsoft's Authenticode standards.  It would be nice if we could have a callback or something executed when NLog wants to load an extension; our application could then check the validity of the extension before allowing it to load.  Perhaps something like this:

```
void LogManager.RegisterExtensionValidator(Func<string, bool> validator)
```

The string passed to the method would be the path to the extension DLL, and it would return 'true' to continue loading the extension or 'false' to prevent it from loading.  I could then use this to validate the file's signature against our signing certificate and the timestamp on the file.

**Comment by 304NotModified** [comment]
I see the problem.  But a path validation still looks unsecure? We can replace files. 

More thinking of public key validation or disabling loading.

**Comment by 304NotModified** [comment]
Also, as an attacker I could easily fork nlog, add the evil code and replace the full dll. 

;)

**Comment by INotDisposable** [comment]
LOL that's true.  For our product specifically, however, one of the first things we do at startup is validate the signature on all files in our installation directory; if any DLL or EXE does not appear to be signed with our code-signing certificate or if the timestamp is wrong, we shut down.  I think that prevents the NLog.dll replacement issue.

My thought with path validation was giving the host application the ability to validate files in whatever way makes sense for the application.  For our application, the Authenticode validation we perform on all other installed files could also be run on any extension classes NLog finds and wants to load.  Other applications might simply check the file hash, or hard-code a return value of 'false' if they never want extensions to load.

**Comment by 304NotModified** [comment]
Perhaps it's neater to fire an event and reading the return value?

e.g.

```c#
LogManager.OnExtensionLoaded += loaded;


loaded(CancelEventArgs e) //todo more context
{
  .. e.Cancel = ...
}
```

**Comment by INotDisposable** [comment]
I like it.  I can take a stab at implementing it if that would be helpful.  Thanks!

**Comment by 304NotModified** [comment]
That's would be nice :)

**Comment by 304NotModified** [comment]
event will be added in 4.4.4!
