### ISSUE TITLE
Factory.Flush doesn't work if fileTarget.KeepFileOpen = true

### ISSUE THREAD

**Issue by JasonGLYao** [NLog/NLog#1532]
Hi! Thanks for reporting this feature/bug/question! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

**Type** (choose one):
- Question

**NLog version**: (e.g. 4.0)

**Platform**: . .Net 4.0 

**Current NLog config** (xml or C#, if relevant)
      var conf = new LoggingConfiguration();

            var target = new FileTarget();
            target.ConcurrentWrites = true;
            target.KeepFileOpen = true;
            target.CreateDirs = true;
            target.AutoFlush = true;
            target.Encoding = Encoding.UTF8;
            target.OpenFileCacheSize = 1;
            

            target.BufferSize = 65535;
            target.ArchiveAboveSize = 1024 * 1024 * 64;
            target.FileName = "${basedir}/log/${shortdate}.log";
            target.Layout = "${message}";
            target.Name = "FileTarget";
            target.CleanupFileName = true;

            conf.AddTarget(target);
            var rule = new LoggingRule("*", NLog.LogLevel.Debug, target);
            conf.LoggingRules.Add(rule);
            NLog.LogManager.Configuration = conf;
            return NLog.LogManager.GetCurrentClassLogger();

In case of a BUG:

- What is the current result?
- What is the expected result?
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
- Please post full exception details (message, stacktrace, inner exceptions)
- Are there any work arrounds? yes/no
- Is there a version in which it did worked? 
- Can you help us by writing an unit test?

in case of a FEATURE REQUEST:
 
 - Why do we need it?
 - An example of the XML config, if relevant.

**Comment by 304NotModified** [comment]
Please answer the questions.

**Comment by 304NotModified** [comment]
Without more info we cannot help you. Feel free to post more info and then I will reopen the issue
