### ISSUE TITLE
NLog.Schema and NLog.Config not working with .Net Core

### ISSUE THREAD

**Issue by vladimirlapacek** [NLog/NLog#1534]
**Type** (choose one):
- Bug

**NLog version**: 4.3.5

**Platform**: .Net Core

In case of a BUG:

**What is the current result?**
I am trying to include the NLog.Schema and NLog.Config NuGet packages in my ASP.Net Core project (in project.json). Unfortunately, the package restore fails and no files (NLog.Config, NLog.Schema) are included in my project.

**What is the expected result?**
The relevant files should be included in the project.

**Comment by 304NotModified** [comment]
this is expected. It's not supported by nuget v3 :(

**Comment by vladimirlapacek** [comment]
Is there anything that can be done to address the problem in the future?

**Comment by 304NotModified** [comment]
Maybe complaining at Nuget. ;)

**Comment by 304NotModified** [comment]
The issue on nuget github https://github.com/NuGet/Home/issues/1792

**Comment by 304NotModified** [comment]
Will close this as this is a known issue as it's polluting the issue list - there is no action for us here.
