### ISSUE TITLE
Missing assembly info for netstandard 1.5

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#1536]
We are missing info in netstandard1.5 (but maybe it's a NPE bug)
   ![image](https://cloud.githubusercontent.com/assets/5808377/17681409/ce57bade-6345-11e6-8c81-235a63162a1f.png)

in netstandard1.3 it is correct:
![image](https://cloud.githubusercontent.com/assets/5808377/17681403/c7536dbe-6345-11e6-81b0-b69bfdf71295.png)

**Comment by 304NotModified** [comment]
still an issue in NLog 4.4.0-betaV15

**Comment by 304NotModified** [comment]
@ghost

> I cloned [NuGetPackageExplorer](https://github.com/NuGetPackageExplorer/NuGetPackageExplorer) and debug the netstandard1.5 issue and it doesn't seems like the bug in NPE, but with Assembly.GetCustomAttributesData throwing at [CodeExecutor/AppDomainWorker.cs#L64](https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/0df06e7/CodeExecutor/AppDomainWorker.cs#L64):
> 
> > -      {"Could not load file or assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.":"System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"}  System.Exception {System.IO.FileNotFoundException}
> 
>  So far, steps to reproduce are:
> 
> ``` cmd
> mkdir \temp
> cd \temp
> git clone https://github.com/NLog/NLog --single-branch -b coreCLR --recursive
> cd NLog
> dotnet restore
> dotnet build src/NLog -f netstandard1.3 -c Release
> dotnet build src/NLog -f netstandard1.5 -c Release
> ```
> 
> Then create an additional application to test assembly loading:
> 
> ``` cmd
> mkdir \temp\test-asm
> cd \temp\test-asm
> dotnet new 
> ```
> 
> Replace Program.cs with:
> 
> ``` c#
> using System.Reflection;
> 
> public class Program
> {
>   public static void Main(string[] args)
>   {
>     Assembly.Load
>     (
>         AssemblyName.GetAssemblyName(@"\temp\NLog\src\NLog\bin\Debug\netstandard1.5\NLog.dll")
>         // change 1.5 to 1.3 and won't have any exception thrown
>     )
>     .GetCustomAttributesData();
>   }
> }
> ```
> 
> and project.json with:
> 
> ``` json
> {
>   "buildOptions": { "emitEntryPoint": true },
>   "frameworks": { "net45": { } }
> }
> ```
> 
> Then `dotnet run` to reproduce the exception.
> 
> Would be nice if we could narrow the issue down and make a self-contained example for coreclr issue tracker. I can't reproduce, for example, with assembly produced by new lib project: `dotnet new -t lib && notepad project.json && dotnet restore && dotnet run` and having netstandard1.3 and netstandard1.5 simultaneously in the project.json.
>

**Comment by luigiberrettini** [comment]
As I said in #2263 I have this problem also with .NET Standard 2.0:
http://github.com/dotnet/sdk/issues/1555

**Comment by 304NotModified** [comment]
thanks for the reminder!

**Comment by luigiberrettini** [comment]
I think that you should check if you see AssemblyInfo using an ILSpy CI build version to see if this issue should be closed i.e. if it is a NPE bug ;)

**Comment by 304NotModified** [comment]
I assume it's a NPE bug, so close :)
