### ISSUE TITLE
Initializing EventLog target procudes internal error logs

### ISSUE THREAD

**Issue by MichalCadecky** [NLog/NLog#1537]
**Type**:
- Question (I'm currently starting with NLog so I would call it ask for help or explanation)

**NLog version**: 4.3.3

**Platform**: .Net 4.5 

Hello. I'm having a little trouble with **EventLogTarget** after I've deployed application to the test server. I'm getting internal logs like these after I've started my application:

```
Error Error initializing target 'EventLog Target[eventlog]'. Exception: System.Security.SecurityException: The source was not found, but some or all event logs could not be searched.  Inaccessible logs: Security.
   at System.Diagnostics.EventLog.FindSourceRegistration(String source, String machineName, Boolean readOnly, Boolean wantToCreate)
   at System.Diagnostics.EventLog._InternalLogNameFromSourceName(String source, String machineName)
   at System.Diagnostics.EventLog.LogNameFromSourceName(String source, String machineName)
   at NLog.Targets.EventLogTarget.InitializeTarget()
   at NLog.Targets.Target.Initialize(LoggingConfiguration configuration)
The Zone of the assembly that failed was:
MyComputer
```

**EventLogTarget Definition**

```xml
<target xsi:type="EventLog"
        name="eventlog"
        layout="${var:messageLayout}"
        log="Application"
        onOverflow="Split" />   
```

I've looked for solution and I found that IIS user does not have permission to read from nor write into Security Log. I just don't understand why is EventLogTarget trying to access Security Log instead of Application Log during Initialization. Yes, I can permit IIS user to access Security Log but I won't be able to do this on the production server. Is there any other way how to avoid this problem? Maybe should I specify Source in the config? I like the default (FriendlyName from AppDomain) option.

**Comment by 304NotModified** [comment]
Hi,

this has probable to do with registering the event source. I'm not sure if we can by pass this issue. Any ideas on that?

**Comment by MichalCadecky** [comment]
Hi,
I apologize for delayed response because I was on holiday.

I had looked for more info and here is what I've found. `EventLog.LogNameFromSourceName` requires access permission `EventLogPermissionAccess.Administer`. Exception was thrown from `InitializeTarget()` method.
```c#
protected override void InitializeTarget()
{
    base.InitializeTarget();

    var fixedSource = GetFixedSource();

    if (string.IsNullOrEmpty(fixedSource))
    {
        InternalLogger.Debug("Skipping creation of event source because it contains layout renderers");
    }
    else
    {
        var currentSourceName = EventLog.LogNameFromSourceName(fixedSource, this.MachineName);
        if (!currentSourceName.Equals(this.Log, StringComparison.CurrentCultureIgnoreCase))
        {
            this.CreateEventSourceIfNeeded(fixedSource, false);
        }
    }
}
```
Also [Microsoft](https://msdn.microsoft.com/en-us/library/6s7642se(v=vs.110).aspx) has note for this  (documentation for `EventLog.LogNameFromSourceName` misses this note ... sigh):
> To search for an event source in Windows Vista and later or Windows Server 2003, you must have administrative privileges.

>The reason for this requirement is that all event logs, including security, must be searched to determine whether the event source is unique. Starting with Windows Vista, users do not have permission to access the security log; therefore, a SecurityException is thrown.

>Starting with Windows Vista, User Account Control (UAC) determines the privileges of a user. If you are a member of the Built-in Administrators group, you are assigned two run-time access tokens: a standard user access token and an administrator access token. By default, you are in the standard user role. To execute the code that accesses performance counters, you must first elevate your privileges from standard user to administrator. You can do this when you start an application by right-clicking the application icon and indicating that you want to run as an administrator.
In my opinion we should check if application has required permission and return more detailed error message because that exception is bit confusing.

>A service that is executing under the LocalSystem account does not have the privileges required to execute this method. The solution is to check whether the event source exists in the ServiceInstaller, and if it does not exist, to create the source in the installer.

Anyway from my point of view these permission requirements should be documented in wiki.

Thank you for your help

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, let us know!
