### ISSUE TITLE
Any plans for Windows 10? (uwp)

### ISSUE THREAD

**Issue by zumicts** [NLog/NLog#1540]

**Comment by 304NotModified** [comment]
It should be supported in NLog 4.4 with the support of netstandard 1.3, see https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md#mapping-the-net-platform-standard-to-platforms

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, let us know!

**Comment by snakefoot** [comment]
Resolved with the release of NLog 5.0 BETA7
