### ISSUE TITLE
Nested layouts (Json layout)

### ISSUE THREAD

**Issue by luigiberrettini** [NLog/NLog#1543]
**Type**:
Question

**NLog version**
4.3.5

**Platform**: .Net 4.5

I wonder if there is a way to configure NLog to have nested layouts.
My use case is having a key under which I nest a JSON layout, with the key not wrapped in quotes:

```xml
<nlog>
  <targets>
    <target name='file' type='File' fileName='log.txt'>
      <layout type='SimpleLayout' text="myAmazingText: ">
        <layout type='JsonLayout'>
          <attribute name='time' layout='${longdate}' />
          <attribute name='level' layout='${level:upperCase=true}'/>
          <attribute name='nested' encode='false'  >
            <layout type='JsonLayout'>
              <attribute name='message' layout='${message}' />
              <attribute name='exception' layout='${exception}' />
            </layout>
          </attribute>
        </layout>
      </layout>
    </target>
  </targets>
  <rules>
  </rules>
</nlog>
```

```json
myAmazingText: { "time": "2016-10-30 13:30:55.0000", "level": "INFO", "nested": { "message": "this is message", "exception": "test" } }
```

If this is not currently possible where do you think it would be most useful to add the feature?
JsonLayout.cs adding a public string Name { get; set; } property?

Thanks!
Luigi

**Comment by 304NotModified** [comment]
yes this is possible already,

you need encode=false

see https://github.com/nlog/nlog/wiki/JsonLayout#advanced-examples

**Comment by luigiberrettini** [comment]
Sorry @304NotModified but with only one attribute and encoded set to false the attribute will be wrapped by curly braces:
```json
{ myAmazingText: { "time": "2016-10-30 13:30:55.0000", "level": "INFO", "nested": { "message": "this is message", "exception": "test" } } }
```

What I am looking for is instead this:
```json
myAmazingText: { "time": "2016-10-30 13:30:55.0000", "level": "INFO", "nested": { "message": "this is message", "exception": "test" } }
```

**Comment by 304NotModified** [comment]
> myAmazingText: { "time": "2016-10-30 13:30:55.0000", "level": "INFO", "nested": { "message": "this is message", "exception": "test" } }

but that isn't valid JSON?  

See also http://jsonlint.com/

**Comment by luigiberrettini** [comment]
On the [wiki page](https://github.com/nlog/nlog/wiki/JsonLayout): "Currently the layout will always create an non-nested object with properties"

I think it could be useful to have nesting and since Layouts are not composable I also think it would be useful to have a workaround, i.e. suppose I want to output a valid JSON with some text before it: how would I do?

**Comment by 304NotModified** [comment]
Don't think this is possible right now.

**Comment by luigiberrettini** [comment]
Would a CompoundLayout work in your opinion?

```xml
<nlog>
  <targets>
    <target name='file' type='File' fileName='log.txt'>
      <layout type='CompoundLayout'>
        <innerLayout type= layout=='SimpleLayout' text="myAmazingText: " />
        <layout type='JsonLayout'>
          <attribute name='time' layout='${longdate}' />
          <attribute name='level' layout='${level:upperCase=true}'/>
          <attribute name='nested' encode='false'  >
            <layout type='JsonLayout'>
              <attribute name='message' layout='${message}' />
              <attribute name='exception' layout='${exception}' />
            </layout>
          </attribute>
      </layout>
    </target>
  </targets>
  <rules>
  </rules>
</nlog>
```

**Comment by 304NotModified** [comment]
Yes! I was also thinking into that direction. PR would be great!

**Comment by luigiberrettini** [comment]
See PR #1551

**Comment by luigiberrettini** [comment]
This can be close now ;)

**Comment by 304NotModified** [comment]
Yes indeed! Thanks! Will releases soon!

**Comment by 304NotModified** [comment]
Fixed by
https://github.com/NLog/NLog/pull/1551
