### ISSUE TITLE
${callsite} method name in async api calls a bit odd

### ISSUE THREAD

**Issue by EltonInAtlanta** [NLog/NLog#1544]
Async methods look slightly funny. In ASP.Net Core 1.0 (.Net 4.6 target) I see this:
```
[HttpGet]
 public async Task<IActionResult> Get()
        {
...
            Logger.LogTrace("Wallet Get");
...
       }

[Route("/api/wallet/choices")]
[HttpGet]
public IActionResult Choices()
{
     {
...
         Logger.LogTrace("Choices");
...
 }
```

`layout="${logger}|${message}|${callsite:className=true:methodName=true}"`

Output:
```
wallet.Controllers.WalletController|Wallet Get|wallet.Controllers.WalletController+<Get>d__6.MoveNext
wallet.Controllers.WalletController|Choices|wallet.Controllers.WalletController.Choices
```
project.json:
```
"tools": {
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": {
      "version": "1.0.0-preview2-final"
    }
  },

  "frameworks": {
    "net461": {
      "dependencies": {
...
      },
      "frameworkAssemblies": {
        "System.Configuration": "4.0.0.0"
      }
    }
  },

```

**Comment by 304NotModified** [comment]
Thanks for the new issue!

**Comment by 304NotModified** [comment]
Is it possible to test this with the fullframework and NLog 4.3.5? 

Which versions are you using? (All NLog packages) Something related has been fixed a few weeks ago

**Comment by 304NotModified** [comment]
related: https://github.com/NLog/NLog/pull/1504

**Comment by EltonInAtlanta** [comment]
Using "NLog.Extensions.Logging": "1.0.0-rtm-alpha3"
![2016-07-14_14-05-21](https://cloud.githubusercontent.com/assets/18667923/16850230/299a2a5a-49cc-11e6-9f84-6194222c40f0.jpg)

I can try to put together a web api 2.0 project on the traditional framework.  Might take a day to fit it in.

**Comment by 304NotModified** [comment]
so it's already fixed in 4.3.5 (and you're using 4.3.**4**), see #1504 :)

**Comment by EltonInAtlanta** [comment]
I tweaked the .nuspec file and restored packages.  That seems to have brought down 4.3.5 :)

**Comment by EltonInAtlanta** [comment]
Yup.  Working perfectly now.

**Comment by 304NotModified** [comment]
Thanks for the confirm! Glad it has been resolved so soon :)

**Comment by EltonInAtlanta** [comment]
Thanks for you help!

**Comment by 304NotModified** [comment]
@EltonInAtlanta you aren't experiencing issues like https://github.com/NLog/NLog.Extensions.Logging/issues/52?

**Comment by EltonInAtlanta** [comment]
No, but I’m not creating that project type.  I’m doing a .Net Core project (with project.json, etc), targeting 4.6.x, so slightly different.  I do see the Nlog package is pulling in System.Xml (4.0.0) and System.Xml.XmlSerializer (4.0.10) as dependencies.

 

Here is the dependency list from project.json

"dependencies": {

   "AutoMapper": "5.0.2",

   "EntityFramework": "6.1.3",

   "Microsoft.AspNetCore.Authentication.JwtBearer": "1.0.0",

   "Microsoft.AspNetCore.Authorization": "1.0.0",

   "Microsoft.AspNetCore.Diagnostics": "1.0.0",

   "Microsoft.AspNetCore.Identity": "1.0.0",

   "Microsoft.AspNetCore.Mvc": "1.0.0",

   "Microsoft.AspNetCore.Mvc.ApiExplorer": "1.0.0",

   "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",

   "Microsoft.AspNetCore.Server.Kestrel": "1.0.0",

   "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",

   "Microsoft.Extensions.Configuration.FileExtensions": "1.0.0",

   "Microsoft.Extensions.Configuration.Json": "1.0.0",

   "Microsoft.Extensions.Logging": "1.0.0",

   "Microsoft.Extensions.Logging.Console": "1.0.0",

   "Microsoft.Extensions.Logging.Debug": "1.0.0",

   "NETStandard.Library": "1.6.0",

   "Newtonsoft.Json": "9.0.1",

   "NLog.Extensions.Logging": "1.0.0-rtm-alpha3"

 },

**Comment by 304NotModified** [comment]
Thanks!
