### ISSUE TITLE
Support Portable Class Libraries (PCL) 

### ISSUE THREAD

**Issue by Iristyle** [NLog/NLog#155]
I know this isn't trivial, but thought I would throw it out there anyhow.

http://msdn.microsoft.com/en-us/library/gg597391(v=vs.110).aspx

**Comment by laazyj** [comment]
Also interested

**Comment by Xharze** [comment]
A lot of work has to be done to make NLog support portable libraries, the work is in progress, but it will take some time before this is done

**Comment by akobr** [comment]
I am interested, too.

**Comment by 304NotModified** [comment]
Nice blog post about PCL : http://alxandr.me/2014/07/20/the-problems-with-portable-class-libraries-and-the-road-to-solving-them/

**Comment by 304NotModified** [comment]
I looked at this in short. I'm not sure if it's possible to have a PLC with some basic functionality.

The problems as I see from now:
- There is no `File` or `Filestream`. So writing to files (most basic operation) or reading config from a config file is impossible.
- There is no `StackFrame` thus, `LogManager.GetCurrentClassLogger` won't work (or we have to change it's behaviour. The [Caller attributes](https://msdn.microsoft.com/en-us/library/hh534540.aspx) won't help as it's missing the class name.

**Comment by 304NotModified** [comment]
See https://github.com/304NotModified/NLog/tree/pcl

**Comment by 304NotModified** [comment]
Some info: http://stackoverflow.com/questions/18110324/streamreader-and-portable-class-library

**Comment by 304NotModified** [comment]
Interesting lib: https://github.com/dsplaisted/pclstorage

**Comment by 304NotModified** [comment]
Some info: http://blogs.msdn.com/b/dotnet/archive/2014/04/21/sharing-code-across-platforms.aspx

**Comment by fubar-coder** [comment]
A core library with a logger interface and a way to get the logger through the log manager would be enough for the use in a PCL.

**Comment by 304NotModified** [comment]
any idea how to fix `LogManager.GetCurrentClassLogger` in PCL (see before) ?

**Comment by fubar-coder** [comment]
There are (AFAIK) three solutions:

1. Remove it and allow only something like ```LogManager.GetLogger<T>()```.
2. Provide the function as stub (which throws an exception when called). This function will only be implemented for the ```net40```, etc... variants of the library.
3. Provide an ILogManager interface that has a ```GetCurrentClassLogger```, but needs to be injected (IoC).

I'd choose the second solution, but it'd be nice if the first and third solutions would be available too.

**Comment by 304NotModified** [comment]
We gonna probable skip this when netstandard is introduced. See https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md

**Comment by 304NotModified** [comment]
We have experienced some pain with netstandard and maybe we still need PCLs.

**Comment by 304NotModified** [comment]
https://github.com/NLog/NLog/issues/1412 and https://github.com/NLog/NLog/issues/1492 are votes for this

**Comment by 304NotModified** [comment]
Like to do this, but too little time for NLog 4.4.

**Comment by tofutim** [comment]
a vote for this

**Comment by 304NotModified** [comment]
@tofutim could you help with this?

**Comment by tofutim** [comment]
I'll take a look, is the main issue StackTrace from PCL?

**Comment by 304NotModified** [comment]
Well no, with PCL we could make a click and bait library, so implementing the needed classes and add as body `throws new NottimplementedException`

**Comment by soroshsabz** [comment]
ITNOA

Hi, I think some helpful info is in the [Xamarin Plugins Documentaion](https://github.com/jamesmontemagno/Xamarin.Plugins) for PCL packaging.

**Comment by 304NotModified** [comment]
Thanks for the info. Currently this has low prio , but PRs are accepted

**Comment by Jowindebondt** [comment]
Hi,
Any improvements on this thread?

**Comment by snakefoot** [comment]
@Jowindebondt Now just me guessing. But the task seems to be creating a PCL-project that extract the standard NLog-classes as interfaces/abstract classes. Then change the current NLog-implementation to be dependent on this new PCL-dll, and implement these extracted interfaces. Sounds like major refactoring that has to be postponed until after NLog ver. 5 (NET Core).

**Comment by 304NotModified** [comment]
PCL would be nice, but it's a lot of work to do it well.

And because netstandard is replaces PCL, this will be the way we're going. Netstandard 2 is near and so NLog 5 RTM. The issues with Xamarin/UWP should be fixed with dotnet tools RTM.

**Comment by snakefoot** [comment]
@JohannesRudolph Guess a different workaround would be to find a common-logging-interface library. One that provides a common interface to several specific logging-libraries (NLog, Log4net, Serilog). Then fix that common-logging-interface-library to be a PCL-project (If not already).

**Comment by 304NotModified** [comment]
I think common logging supports PCL.

**Comment by solset-ccochran** [comment]
+1 for PCL support. I LOVE NLog but need to include a PCL library in my .NET 4.5 Web API.

**Comment by 304NotModified** [comment]
netstandard 2.0 will be there soon. This should fix the issue also
