### ISSUE TITLE
The Username is coming  NT AUTHORITY\SYSTEM

### ISSUE THREAD

**Issue by mahikkp** [NLog/NLog#1550]
Hi,

in NLog.config file i am already mention 

```
<parameter name="@username" layout="${windows-identity}" />
```
but the username stored in database is  NT AUTHORITY\SYSTEM
Why it's coming NT AUTHORITY\SYSTEM.

Thanks

**Comment by 304NotModified** [comment]
It's the user of your .net application (apppool user in the case of iis)

**Comment by 304NotModified** [comment]
Has your question being answered?

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, let us know!
