### ISSUE TITLE
Duplicate complexType Layout in NLog XSD

### ISSUE THREAD

**Issue by luigiberrettini** [NLog/NLog#1554]
**Type**: Bug

**NLog version**: 4.3.6

**Platform**: All

The NLog XSD contains two definition for the complexType Layout.
After the compound layout:
```xml
  <xs:complexType name="Layout">
    <xs:choice minOccurs="0" maxOccurs="unbounded" />
  </xs:complexType>
```

**Comment by 304NotModified** [comment]
Thanks for reporting! Does this break anything? 

The XSD is auto generated, dunno why this happens

**Comment by luigiberrettini** [comment]
Breaks only intellisense: if you download NLog.Schema as an help not to do wrong things you cannot be helped

**Comment by 304NotModified** [comment]
It should be fixed. Can you confirm that?

https://www.nuget.org/packages/NLog.Schema/4.3.6.1

**Comment by luigiberrettini** [comment]
Fixed, thanks!

**Comment by 304NotModified** [comment]
Thanks for the confirm!
