### ISSUE TITLE
Finalize .NET Core implementation (NLog 5)

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#1559]
See [open tasks for .NET Core](https://github.com/NLog/NLog/labels/.NET%20core%20%2F%20DNX)

Most important stuff to be done:
- Fix getCurrentClassLogger (stacktrace ctor issue)
- Fix ${basedir}
- Fix Autoloading packages
- Fix running tests on AppVeyor

as continuation of https://github.com/NLog/NLog/issues/641

**Comment by 304NotModified** [comment]
@phenixdotnet maybe some time to help finishing this?  Got the tests almost running on AppVeyor (locally 95% works)

**Comment by phenixdotnet** [comment]
@304NotModified I can try to get some time to help you with this but I can't promise anything

Anyway, thanks you to have pushed this you're doing an amazing work !

**Comment by 304NotModified** [comment]
This was indeed for the coreCLR branch.

**Comment by snakefoot** [comment]
These could be considered fixed on NLog 5-branch

- [x] Fix getCurrentClassLogger (stacktrace ctor issue)
- [x] Fix ${basedir}
- [x] Fix running tests on AppVeyor

**Comment by 304NotModified** [comment]
> The autoloading packages is very hard, because of the new nuget-style, so almost unfixable.

Indeed, and this is https://github.com/NLog/NLog/issues/1091, so I will close this one. thx!
