### ISSUE TITLE
How to get the line number where the exception was thrown

### ISSUE THREAD

**Issue by ghost** [NLog/NLog#1563]
- Question

${callsite-linenumber:skipFrames=Integer}, this one is get The call site source line number but not exact error line number.
example,

``` c#
 1        int i = 0;
 2         try
 3          {
 4               int j = 5 / i;
 5          }
 6           catch (Exception e)
 7          {
 8               logger.Error(e);
 9           }
```

Using ${callsite-linenumber} output is 8 but i want error line number output here is line number 4.

**Comment by 304NotModified** [comment]
the linenumber is indeed the line number of the call and not the exception.

This is currently not supported. Work around:


```
catch (Exception ex)
{
    // Get stack trace for the exception with source file information
    var st = new StackTrace(ex, true);
    // Get the top stack frame
    var frame = st.GetFrame(0);
    // Get the line number from the stack frame
    var line = frame.GetFileLineNumber();
   Log.Error().Exception(ex).Property("line-number", line).Write(); //using NLog.Fluent, .NET 4.5 
}
```

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, let us know!

**Comment by linflux** [comment]
I would like to know: this line error still currently not supported?
What is the best approach using .NET Core and NLog.Extensions for don't repeat this lines in every single catch block?

**Comment by patja** [comment]
Coming from log4net I was also surprised by the lack of a specific line number from the stack trace in Nlog.  I share the question raised by @linflux of what is the best approach to generalize this to all exception logging using Nlog

**Comment by 304NotModified** [comment]
AFAIK this isn't possible in c#? And thus not in NLog. 

But if you have the working c# code, we would be haooy to implement it!

**Comment by patja** [comment]
On closer examination I now realize that I have no problem getting the line that triggered the exception from the exception stacktrace (rather than the callsite) using NLog when my code is wrapped in a try/catch block.  The problem is when unhandled exceptions hit the Application_Error method of global.asax.cs in my MVC application.

In this situation, log4net helpfully includes the file name and line number that caused the exception, but Nlog just has information such as:

```
Exception: Exception of type 'System.Web.HttpUnhandledException' was thrown.    at System.Web.UI.Page.HandleError(Exception e)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest()
   at System.Web.UI.Page.ProcessRequest(HttpContext context)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)             
Stack Trace: RecordError at offset 73 in file:line:column <filename unknown>:0:0
RaiseOnError at offset 211 in file:line:column <filename unknown>:0:0
Application_Error at offset 1585 in file:line:column C:\Users\me\Documents\Visual Studio 2013\Projects\myproject\myproject\Global.asax.cs:317:9
```

log4net logs this:

```
System.Web.HttpUnhandledException (0x80004005): Exception of type 'System.Web.HttpUnhandledException' was thrown. ---> System.Data.Entity.Validation.DbEntityValidationException: Validation failed for one or more entities. See 'EntityValidationErrors' property for more details.
   at System.Data.Entity.Internal.InternalContext.SaveChanges()
   at UpdateCalendar.btnCalendarCurrent_Clicked(Object sender, EventArgs e) in C:\Users\me\Documents\Visual Studio 2013\Projects\myproject\myproject\MyPage.aspx.cs:line 26
```

**Comment by 304NotModified** [comment]
@patja that looks like you should enable the inner-exception printing for ${exception},  set `maxInnerExceptionLevel`  like `${exception:format=toString,Data:maxInnerExceptionLevel=10}`

AFAIK

> 1        int i = 0;
>  2         try
>  3          {
>  4               int j = 5 / i;
>  5          }
>  6           catch (Exception e)
>  7          {
>  8               logger.Error(e);
>  9           }
> Using ${callsite-linenumber} output is 8 but i want error line number output here is line number 4.

isn't possible in .NET and therefor this as closed.

**Comment by patja** [comment]
I think you are right.  I did some testing and `maxInnerExceptionLevel` is what I was missing.  Thanks!

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, let us know!
