### ISSUE TITLE
How to NLog C# library consumed from unmanaged C++ application?

### ISSUE THREAD

**Issue by chuckleplant** [NLog/NLog#1567]
**Type** :  Question

**NLog version**: 4.2.3

**Platform**: .Net 4.0 / .Net 4.5 

Hi, 
I have a .NET C# library that I want to log. But it is consumed from an unmanaged C++ application (exe). How can I setup the NLog.config for the unmanaged C++ application so that I can choose where the logs will be output to?

Thanks and great library!

**Comment by 304NotModified** [comment]
That's not supported (anymore). NLog 2 did support c++.

**Comment by chuckleplant** [comment]
What about logging a c# library without defining Nlog.config in the application?

* Application.csproj 
    * Produces .exe, has no NLog.config file defined
    * Consumes the Lib library 
* Lib.csproj 
    * C# .net library
    * Has NLog.config defined and uses NLog

Can this library be logged to a file?

**Comment by 304NotModified** [comment]
Good question. I really don't know if this would work. I think you get better response when posting this on stackoverflow.com

**Comment by phenixdotnet** [comment]
Hi. One point I don't understand, the NLog.config file is embedded in Lib or deployed with the lib ? If it's the second case it should work.

About the original question, you can use a C++.NET dll to load and use NLog. This dll must act as a proxy between your unmanaged app and NLog.

**Comment by chuckleplant** [comment]
Thanks! Closing this one. Did not manage to make it work with my unmanaged application and I understand it's not officially supported on this version.
