### ISSUE TITLE
All Logging methods may throw exceptions?

### ISSUE THREAD

**Issue by tishion** [NLog/NLog#1568]
**Type** :  Question

**NLog version**: 4.3.6

**Platform**: .Net 3.5 / .Net 4.0 / .Net 4.5 / Mono 4 / Silverlight 4 / Silverlight 5 / Xamarin Android / Xamarin iOs

I noted that  all the logging methods could throw exceptions when there are something goes wrong in the Target implementation.

For example in the FileTarget:
```
private void ReplaceFileContent(string fileName, byte[] bytes, bool firstAttempt)
{
    try
    {
        using (FileStream fs = File.Create(fileName))
        {
            byte[] headerBytes = this.GetHeaderBytes();
            if (headerBytes != null)
            {
                fs.Write(headerBytes, 0, headerBytes.Length);
            }

            fs.Write(bytes, 0, bytes.Length);

            byte[] footerBytes = this.GetFooterBytes();
            if (footerBytes != null)
            {
                fs.Write(footerBytes, 0, footerBytes.Length);
            }
        }
    }
    catch (DirectoryNotFoundException)
    {
        if (!this.CreateDirs || !firstAttempt)
        {
            throw;
        }
        Directory.CreateDirectory(Path.GetDirectoryName(fileName));
        //retry.
        ReplaceFileContent(fileName, bytes, false);
    }
}
```
This function may throw exception: UnauthorizedAccessException, and then this exception will be thrown
to the user's code scope, if the user doesn't catch this exception the application will crash.
And the API documents didn't show this throwing behavior to the user.

So is this a bug of NLog?

**Comment by 304NotModified** [comment]
These exceptions should be catched on a higher level, depending on the throwexcepions option. If that isn't the case, then it's a bug ;)

**Comment by tishion** [comment]
Hi @304NotModified, Thanks for your information. I agree with you. But I don't know the meaning of the **higher lever**.

 Do you mean these exceptions should be caught in the scope of user code? If so I think we should add one more section about exception handling into the document, right?

If you mean the exceptions should be caught within the scope of NLog framework, I am afraid this is absolutely a bug.
I put only one file name in the config file, and then NLog will try to generate the log file in to the **Current Directory of the process**, but the Current Directory of process will be changed by the progress, for example when we change to **C:\windows\system**, then NLog will try to create log file in this folder, but the process has no write permission for this directory, and then it will throw the exception. Unfortunately, this exception is not handled by anyone, it just be propagated to the user's code field and the user didn't try to catch it, then the user's application crashed.

**Comment by 304NotModified** [comment]
The higher level is in NLog.

A short summary of the levels:

1. UserCode
2. Global NLog code (initialize, configure, routing)
3. Layout and Target NLog code.

The exceptions are catched in 2 (if throwExceptions = false, the default). 

> Do you mean these exceptions should be caught in the scope of user code?

No this is not needed. Set `throwExceptions = false`

**Comment by tishion** [comment]
@304NotModified Thanks a lot! I will check this.
