### ISSUE TITLE
[Feature request] Add full url layout renderer for ASP.NET MVC

### ISSUE THREAD

**Issue by MichaelLogutov** [NLog/NLog#157]
Currently HTTP_URL for MVC applications does not hold the querystring at all. So the only way to output full url is to write something like this:

${aspnet-request:serverVariable=URL}?${aspnet-request:serverVariable=QUERY_STRING}

Which not only brings unnecessary performance overhead but also always prints "?" no matter if there was a query string specified or not.

Full url is a very common thing for loggin web applications so I think there should be some simple layout rendered like ${url:queryString=true}

**Comment by 304NotModified** [comment]
@monomial  it seems that this has been fixed. If not, then just re-open the issue.

**Comment by doabil** [comment]
Hi, I use Nlog my ASP MVC project. But. I dont get URL ? 
The codes in the responses are not working
I'm waiting for help

**Comment by 304NotModified** [comment]
Please create a new github issue and fill in the template.
