### ISSUE TITLE
Zombie file handles when using keepFileOpen="true" and date/time in logfile name

### ISSUE THREAD

**Issue by breischl** [NLog/NLog#1571]
**Summary**: If you configure a FileTarget with the `keepFileOpen="true"` option and also use a date or datetime pattern in the filename, then the files are never closed properly. This happens even if file archiving is enabled, as long as the archiving time period is equal to the precision in the file name (eg, daily archive and the filename contains the date but not time).

**Type**: Bug
**NLog version**: ~~4.2.3~~ 4.3.6. Also tested in 3.1.0.
**Platform**: .NET 4.6, Windows 10

- What is the current result? 
Logfiles that are no longer in use still have open file handles, which prevents operations on them such as deleting them. 

- What is the expected result?
File handles should be closed when logfile is no longer in use. 

- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
Yes, it does not indicate that the old files are ever closed. 

- Please post full exception details (message, stacktrace, inner exceptions)
No exceptions

- Are there any workarounds? 
Yes, don't use the combination of options that provoke the problem.

- Is there a version in which it did worked? 
Not that I know of - I tried ~~4.2.3~~ 4.3.6 and 3.1.0

- Can you help us by writing an unit test?
No, but I did write a (slightly manual) repro. See [attached zipfile](https://github.com/NLog/NLog/files/389116/LogRollingTest.zip) or [this repo](https://github.com/breischl/LogRollingTest/tree/master).

**Comment by 304NotModified** [comment]
Hi, there has been a lot of changes regarding file writing and archiving in NLog 4.3.  Could you test with 4.3.6?

**Comment by breischl** [comment]
Actually I did test with 4.3.6. Then for some reason I typed 4.2.3 into the bug report.

**Comment by 304NotModified** [comment]
Looking at this right now

**Comment by 304NotModified** [comment]
I dont see the problem? (as the powershell isn't printing anything?)

![image](https://cloud.githubusercontent.com/assets/5808377/17306453/6f795a9c-5830-11e6-99af-a7396310e0a7.png)

**Comment by 304NotModified** [comment]
ow got now something, but looks like Resharper

![image](https://cloud.githubusercontent.com/assets/5808377/17306485/98615482-5830-11e6-8f5b-c413bdede717.png)

**Comment by 304NotModified** [comment]
Win10x64 here

**Comment by 304NotModified** [comment]
NLog 4.2.3:

![image](https://cloud.githubusercontent.com/assets/5808377/17306567/0aa0fb10-5831-11e6-9290-bea2b9a89bb6.png)


So solved in 4.3.6?

**Comment by breischl** [comment]
Hm. May be due to not running the Powershell as an administrator. Try just running `handle.exe` with no args and see if it reports an error. Or just launch an Admin Powershell and try again.

**Comment by 304NotModified** [comment]
It's running Powershell as an administrator.

**Comment by 304NotModified** [comment]
Can you post a screenprint of what you're seeing?

**Comment by breischl** [comment]
![ss 2016-08-01 at 01 48 24](https://cloud.githubusercontent.com/assets/93974/17306711/b779eab0-57ee-11e6-9cda-f7ca0f1a18bc.png)

**Comment by 304NotModified** [comment]
Will try release then

**Comment by 304NotModified** [comment]
Guess you not crazy ;)

![image](https://cloud.githubusercontent.com/assets/5808377/17307011/4699d824-5833-11e6-8bc0-ba35df071d81.png)

**Comment by breischl** [comment]
Oh good, I was starting to wonder. :)

It does seem like the handles get closed eventually, but I'm not sure how or why. My desktop seems to keep ~5 open. Our servers kept about that, but they were rolling once/day so it's more of a problem there.

**Comment by 304NotModified** [comment]
mmm what about

> openFileCacheSize - Number of files to be kept open. Setting this to a higher value may improve performance in a situation where a single File target is writing to many files (such as splitting by level or by logger). Integer Default: 5

https://github.com/NLog/NLog/wiki/File-target

**Comment by 304NotModified** [comment]
So looks like a feature ;)

Never used it

**Comment by breischl** [comment]
Well heck. That does appear to be the culprit, if I can apply that word to a feature. Sorry to bug you about it.

**Comment by 304NotModified** [comment]
No problem! Advanced feature, was almost forgotten about it. 

I assume I can close this one. If not, let me know
