### ISSUE TITLE
The dependency NLog.Framework.Logging >= 1.0.0-rc1-final-2016-02-06 could not be resolved.

### ISSUE THREAD

**Issue by eriksendc** [NLog/NLog#1572]
Question: We use Visual Studio Team Services (TFS in the cloud) to do builds. All of a sudden we are getting the error "The dependency NLog.Framework.Logging >= 1.0.0-rc1-final-2016-02-06 could not be resolved." when building. Local builds are still running, but our local development environments probably haven't had to go out and get a fresh version of the RC1-Final (we've probably got it cached). Did this get pulled out of nuget? If so, can it please be put back?

**NLog version**: From project.json: "NLog.Framework.Logging": "1.0.0-rc1-final-2016-02-06"

**Platform**: .NET 5 RC1 (pre-.NET CORE)

**Current NLog config** (xml or C#, if relevant)

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

  <targets>
    <target name="logfile" xsi:type="File" fileName="..\..\gyp.log" />
  </targets>

  <rules>
    <logger name="*" minlevel="Trace" writeTo="logfile" />
  </rules>

</nlog>
```

**Comment by 304NotModified** [comment]
It's still there? 

https://www.nuget.org/packages/NLog.Framework.logging/1.0.0-rc1-final-2016-02-06

**Comment by eriksendc** [comment]
Sorry for the noise. This turned out to be an internal issue with Visual Studio Team Services:

https://blogs.msdn.microsoft.com/vsoservice/?p=11975

They'd upgraded to a new beta version of NuGet and it broke several things, including pulling this version of NLog.

Again, sorry for any distractions.

-Brian Eriksen

**Comment by 304NotModified** [comment]
NP! Thanks for the feedback!
