### ISSUE TITLE
Priority Logging

### ISSUE THREAD

**Issue by kejvi-doko** [NLog/NLog#1576]
Hello,
It is possible to define a base logger in rules and log there all the errors but if that fails another backup logger will be used. 
For example:

- `<logger name="*" levels="Warn,Error,Fatal" writeTo="database"/>`

- `<logger name="*" levels="Warn,Error,Fatal" writeTo="file"/> `

If the log was recorded in database everything is ok, so don't save in file. If logging in database failed for many reasons save the log to file. Is it possible to realize this ? Thanks in advance !

**Comment by 304NotModified** [comment]
Yes, that's the FallBackgroup: https://github.com/NLog/NLog/wiki/FallbackGroup-target

See also other target wrappers: https://github.com/NLog/NLog/wiki/Targets#wrappers
