### ISSUE TITLE
Feature Request: Support inner text in <variable> tags

### ISSUE THREAD

**Issue by anton-gogolev** [NLog/NLog#1577]
Currently, with complex expressions, `<variable>` syntax gets pretty unwieldy :

```xml
<!-- Adding linebreaks for readability -->
<variable name="mailBodyLayout" 
    value="${onexception:inner=${exceptionMailBodyLayout}:whenempty=${standardMailBodyLayout}}
    ${newline}${newline}---${newline}${application-name} v${application-version}
    ${newline}${newline}Server: ${machinename}${newline}Date: ${longdate}${newline}
    ${when:when=length('${iis-site-name}') > 0:inner=${iisApplicationInformation}}
    Base Directory: ${basedir}${newline}Identity: ${windows-identity}${newline}
    Process Time: ${processtime}" />
```

It would be nice if NLog could use inner text (and interpret `CR`/`LF` as `${newline}`) in `<variable>` tags (maybe wrapped in `<![CDATA[`/`]]>`) instead of `value` attribute. This would make things much easier on the eye:

```xml
<variable name="mailBodyLayout">
<![CDATA[${onexception:inner=${exceptionMailBodyLayout}:whenempty=${standardMailBodyLayout}}

---
${application-name} v${application-version}

Server: ${machinename}
Date: ${longdate}
${when:when=length('${iis-site-name}') > 0:inner=${iisApplicationInformation}}
Base Directory: ${basedir}
Identity: ${windows-identity}
Process Time: ${processtime}]]></variable>
```

**Comment by 304NotModified** [comment]
Thanks, I like the idea! 

I you could help in writing a unit test for it (check the current unit tests), that would boost the implementation!

**Comment by anton-gogolev** [comment]
Absolutely. Is `NLog.UnitTests.Config.VariableTests` the correct place to start looking?

**Comment by 304NotModified** [comment]
Yes indeed

**Comment by 304NotModified** [comment]
Need any help on this?

**Comment by anton-gogolev** [comment]
Welp, my bad for not following through. Please, do not close this just yet :)

**Comment by snakefoot** [comment]
You can already do this with NLog:

```xml
<variable name="mailBodyLayout">
<value>
<![CDATA[${onexception:inner=${exceptionMailBodyLayout}:whenempty=${standardMailBodyLayout}}

---
${application-name} v${application-version}

Server: ${machinename}
Date: ${longdate}
${when:when=length('${iis-site-name}') > 0:inner=${iisApplicationInformation}}
Base Directory: ${basedir}
Identity: ${windows-identity}
Process Time: ${processtime}]]>
</value>
</variable>
```

**Comment by 304NotModified** [comment]
> You can already do this with NLog 4.1 (using `<value>`-element instead of value-attribute):
> 
> ```
> <variable name="mailBodyLayout">
> <value>
> <![CDATA[${onexception:inner=${exceptionMailBodyLayout}:whenempty=${standardMailBodyLayout}}
> 
> ---
> ${application-name} v${application-version}
> 
> Server: ${machinename}
> Date: ${longdate}
> ${when:when=length('${iis-site-name}') > 0:inner=${iisApplicationInformation}}
> Base Directory: ${basedir}
> Identity: ${windows-identity}
> Process Time: ${processtime}]]>
> </value>
> </variable>
> ```

Are you sure? `Xml_configuration_with_inner_returns_defined_variables` fails on the current master ... (and it fixed in #3459)

**Comment by snakefoot** [comment]
@304NotModified Well `Xml_configuration_with_inner_returns_defined_variables` works fine for me with this XML-input (Notice `<value>`) when running on master-branch:

```c#
        [Fact]
        public void Xml_configuration_with_inner_returns_defined_variables()
        {
            var configuration = XmlLoggingConfiguration.CreateFromXmlString(@"
<nlog throwExceptions='true'>
    <variable name='prefix'><value><![CDATA[
newline
]]></value></variable>
    <variable name='suffix'><value>]]</value></variable>
</nlog>");

            var nullEvent = LogEventInfo.CreateNullEvent();

            // Act & Assert
            Assert.Equal("\nnewline\n", configuration.Variables["prefix"].Render(nullEvent).Replace("\r", ""));
            Assert.Equal("]]", configuration.Variables["suffix"].Render(nullEvent));
        }
```

**Comment by 304NotModified** [comment]
Or yes indeed, I missed the `<value>` I guess.

We need to check if we should update the xsd for this

**Comment by 304NotModified** [comment]
XSD needs an update

![image](https://user-images.githubusercontent.com/5808377/59309399-be31bf80-8ca3-11e9-8cca-36e1dcdce146.png)

**Comment by snakefoot** [comment]
Yes this should be supported:
```
<variable name="a">
   <value>
   </value>
</variable>
```
Strange how required properties must be provided as attributes. Since XML-config has always allowed properties to be provided as single-xml-element.

**Comment by 304NotModified** [comment]
With NLog 4.6.5 this will be also supported in the XSD :)

**Comment by snakefoot** [comment]
This is no longer a breaking change. Unless you see changing XSD as breaking.


Sent from my Sony Xperia


---- Julian Verdurmen wrote ----


With NLog 4.6.5 this will be also supported in the XSD :)

**Comment by 304NotModified** [comment]
Good  one, thanks!

**Comment by 304NotModified** [comment]
NLog 4.6.5 has been released!  https://www.nuget.org/packages/NLog/4.6.5 :)
