### ISSUE TITLE
 count operation on AsyncRequestQueue is not thread-safe

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#1591]
**Type** 

- Bug

**NLog version**: (4.3.7)

**Platform**: all

as discussed in https://github.com/NLog/NLog/issues/1586

@luigiberrettini:
> Maybe: I do not have the big picture about what it does, but the [count operation on AsyncRequestQueue](https://github.com/NLog/NLog/blob/cdb1fcf14f6e505317ab9cdd00322fe60ba4b4ca/src/NLog/Targets/Wrappers/AsyncRequestQueue-T.cs#L74) is not thread-safe

> Moreover [ProcessPendingEvents](https://github.com/NLog/NLog/blob/cdb1fcf14f6e505317ab9cdd00322fe60ba4b4ca/src/NLog/Targets/Wrappers/AsyncTargetWrapper.cs#L284-L296) could have issues.

This seems to be a bug and could lead to missing message.

**Comment by snakefoot** [comment]
This has now been resolved with  #1669

**Comment by 304NotModified** [comment]
\o/
