### ISSUE TITLE
writing a lot to null target, unneeded expensive methods

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#1594]
When writing a lot to nulltarget, with `logger.Debug("message {0}", messageNumber)`

total time for 10 million messages: 2843ms while tracing

These methods are relative expensive, while they don't do a lot
### PrepareLogEventInfo

just getting default culture when culture is `null`

![image](https://cloud.githubusercontent.com/assets/5808377/17652678/26734f6c-6283-11e6-9102-a22029ef3eab.png)

![image](https://cloud.githubusercontent.com/assets/5808377/17652684/5259fc16-6283-11e6-8e1a-ce00a87d5f6a.png)
### IsSafeToDeferFormatting

We now in the logger most of the time if a type is "IsSafeToDeferFormatting"

![image](https://cloud.githubusercontent.com/assets/5808377/17652693/9813b1c0-6283-11e6-816a-3fe75144ec3d.png)

![image](https://cloud.githubusercontent.com/assets/5808377/17652701/ca303bec-6283-11e6-9cab-47a2381ef0c8.png)
### MergeEventProperties

We should know at forehand if MergeEventProperties is needed sometimes. 

![image](https://cloud.githubusercontent.com/assets/5808377/17652707/021a6c94-6284-11e6-947d-1b5aeae36710.png)

![image](https://cloud.githubusercontent.com/assets/5808377/17652711/187ad7c6-6284-11e6-8f42-7828efe2f6c2.png)

**Comment by snakefoot** [comment]
MergeEventProperties has been improved a little with #1700. No longer allocates enumerator, when checking Parameters-array.

**Comment by 304NotModified** [comment]
That's indeed a nice improvement.:)

But we know sometimes from the loging method the properties that are calculated here. We should pass that all the way down.

**Comment by 304NotModified** [comment]
Split up to #1986, #1987 and #1988
