### ISSUE TITLE
Thread Specific Memory Target

### ISSUE THREAD

**Issue by vipiniitrmca** [NLog/NLog#1598]
Hi! Thanks for reporting this feature/bug/question! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.
- Question

NLog version  4.3.7

Platform : .Net 4.0

  <variable name="LogFolder" value="${basedir}\${mdc:item=LogsDirectory}_${mdc:item=ScenarioId}"/>
  <variable name="Scenario" value="${mdc:item=ScenarioId}" />

    <target name="LogFile"
            xsi:type="File"
            fileName="${var:LogFolder}\logfile.txt"
            layout="${message}"
            maxArchiveFiles="10"
            archiveAboveSize="20000000"
            archiveNumbering="Sequence"
            archiveFileName="${var:LogFolder}\logfile.{#}.txt"/>
    <target name="Memory_${var:Scenario}" xsi:type="Memory" layout="${message}"/>

    <logger name="LogFile" minlevel="Debug" writeTo="LogFile" />
    <logger name="LogFile" minlevel="Info" writeTo="Memory_${var:Scenario}" />

I am running a service in which, for every new thread invocation I create log instance, I want to attach memory target to a file Target(LogFile) specific to thread.

Currently if i use memory target programmatically
var memoryTarget = NLog.LogManager.Configuration.AllTargets.OfType<MemoryTarget>().Last();

Logs are getting written on all memoryTarget
Please let me know, What wrong i am doing.

**Comment by 304NotModified** [comment]
${var} could not be used at name and write. A fixed name should be used.

**Comment by vipiniitrmca** [comment]
Please find my complete code snippet after removing usage of var
I have mentioned the current output and expected output too
I want separate memory logger per thread, they should not interact with each other. 

Config

<targets>
    <target name="LogFile"
            xsi:type="File"
            fileName="${mdc:item=LogsDirectory}\logfile.txt"
            layout="${message}"
            maxArchiveFiles="10"
            archiveAboveSize="20000000"
            archiveNumbering="Sequence"
            archiveFileName="${mdc:item=LogsDirectory}\logfile.{#}.txt"/>
    <target name="Memory" xsi:type="Memory" layout="${message}"/>
</targets>

<rules>
    
    <logger name="LogFile" minlevel="Debug" writeTo="LogFile" />
    <logger name="LogFile" minlevel="Info" writeTo="Memory" />
</rules>


Code Snippet:

static void Main(string[] args)
{
    List<Task> tasks = new List<Task>();
    for (int ctr = 1; ctr <= 3; ctr++)
    {
       tasks.Add(Task.Factory.StartNew(FirstWorldTask));
    }
    Task.WaitAll(tasks.ToArray());
}

private static void FirstWorldTask()
{
    var folderName = rnd.Next();
	var scenarioId = rnd.Next().ToString();
	
	Console.WriteLine(scenarioId);
				
    NLog.MappedDiagnosticsContext.Set("LogsDirectory", folderName);
	ILog logger = LogManager.GetLogger("LogFile");
	var memoryTarget = (MemoryTarget)NLog.LogManager.Configuration.FindTargetByName("Memory");
	memoryTarget.Logs.Clear();
	for (int i = 0; i < 5; i++)
    {
        logger.Info(i + " " + scenarioId);
        Thread.Sleep(10);
    }
	
	for (int i = 0; i < memoryTarget.Logs.Count; i++)
    {
        Console.WriteLine(memoryTarget.Logs[i] + " " + scenarioId);
    }

    memoryTarget.Logs.Clear();
}


Current Output

960258078
879841817
1123570211
1 960258078  960258078
0 1123570211 960258078
1 879841817  960258078
2 960258078  960258078
1 1123570211 960258078
2 879841817  960258078
3 960258078  960258078
2 1123570211 960258078
3 879841817  960258078
4 960258078  960258078
3 1123570211 960258078
4 879841817  960258078
4 1123570211 1123570211


Expected Output

960258078
879841817
1123570211
0 960258078  960258078
1 960258078  960258078
2 960258078  960258078
3 960258078  960258078
4 960258078  960258078
0 879841817  879841817
1 879841817  879841817
2 879841817  879841817
3 879841817  879841817
4 879841817  879841817
0 1123570211  1123570211
1 1123570211  1123570211
2 1123570211  1123570211
3 1123570211  1123570211
4 1123570211  1123570211

**Comment by vipiniitrmca** [comment]
I had also tried it programmatically
Please find the code snippet of my program

```

private static void FirstWorldTask()
{
    var folderName = rnd.Next();
    var scenarioId = rnd.Next().ToString();

    Console.WriteLine(scenarioId);

    NLog.MappedDiagnosticsContext.Set("LogsDirectory", folderName);
    ILog logger = LogManager.GetLogger("LogFile");

    var memoryTarget = new MemoryTarget();
    memoryTarget.Name = "Memory_" + scenarioId;
    memoryTarget.Layout = "${message}";

    var config = NLog.LogManager.Configuration;
    config.AddTarget(memoryTarget.Name, memoryTarget);

    var rule = new LoggingRule("LogFile", LogLevel.Info, memoryTarget);
    config.LoggingRules.Add(rule);

    NLog.LogManager.Configuration = config;

    for (int i = 0; i < 5; i++)
    {
        logger.Info(i + " " + scenarioId);
        Thread.Sleep(10);
    }

    while (memoryTarget.Logs.Count > 0)
    {
        int i = 0;

        while (memoryTarget.Logs.Count > 0 && i < 5)
        {
            Console.WriteLine(memoryTarget.Logs.First() + " " + scenarioId);
            memoryTarget.Logs.RemoveAt(0);
            i++;
        }
    }
}

```

Output with this snippet:

903471573
560466050
898036495
0 560466050     560466050
1 560466050     560466050
0 898036495     560466050
0 903471573     560466050
1 898036495     560466050
1 903471573     560466050
2 560466050     560466050
2 903471573     560466050
3 560466050     560466050
2 898036495     560466050
3 903471573     560466050
3 898036495     560466050
4 560466050     560466050
4 903471573     560466050
0 560466050     903471573
1 560466050     903471573
0 898036495     903471573
0 903471573     903471573
1 898036495     903471573
1 903471573     903471573
2 560466050     903471573
2 903471573     903471573
3 560466050     903471573
2 898036495     903471573
3 903471573     903471573
3 898036495     903471573
4 560466050     903471573
4 903471573     903471573
0 560466050     898036495
1 560466050     898036495
0 898036495     898036495
0 903471573     898036495
1 898036495     898036495
1 903471573     898036495
2 560466050     898036495
2 903471573     898036495
3 560466050     898036495
2 898036495     898036495
3 903471573     898036495
3 898036495     898036495
4 560466050     898036495
4 903471573     898036495
4 898036495     898036495

Logs are getting written on all the memoryTargets, instead of only one

**Comment by vipiniitrmca** [comment]
I am pasting my code snippet using log4Net,
Just in brief:
I am creating a new rolling appender and a memory appender and attaching them to a logger in logger repository for every new thread.
Whatever I write in rolling appender, automatically got in memory appender of specific thread.
I want to achieve same using NLog

```
class Program
{
    private static Random rnd = new Random();
    private static object sync = new object();

    static void Main(string[] args)
    {
        List<Task> tasks = new List<Task>();
        // Execute the task 10 times.
        for (int ctr = 1; ctr <= 5; ctr++)
        {
            tasks.Add(Task.Factory.StartNew(FirstWorldTask));
            Thread.Sleep(10);
        }
        Task.WaitAll(tasks.ToArray());
    }

    private static void FirstWorldTask()
    {
        string loggerName = "Logger";
        string randomName = rnd.Next().ToString();

        lock (sync)
        {
            loggerName += randomName;
            Console.WriteLine(loggerName);
        }

        log4net.Layout.PatternLayout patternLayout = new log4net.Layout.PatternLayout("%message%newline");
        patternLayout.ActivateOptions();

        RollingFileAppender rollingFileAppender = new RollingFileAppender();
        rollingFileAppender.AppendToFile = false;
        rollingFileAppender.RollingStyle = RollingFileAppender.RollingMode.Size;
        rollingFileAppender.MaxSizeRollBackups = 0;
        rollingFileAppender.MaximumFileSize = "20MB";
        rollingFileAppender.Layout = patternLayout;
        rollingFileAppender.File = "./" + randomName + "/logfile.txt";
        //appender.File = GlobalSettings.FOLDER_NAME + "logfile" + currentCount.ToString() + ".txt";
        rollingFileAppender.ActivateOptions();

        MemoryAppender memoryAppender = new MemoryAppender();
        memoryAppender.AddFilter(new log4net.Filter.LevelRangeFilter() { LevelMin = log4net.Core.Level.Info, LevelMax = log4net.Core.Level.Fatal });
        
        log4net.Repository.Hierarchy.Hierarchy hierarchy = (log4net.Repository.Hierarchy.Hierarchy)log4net.LogManager.GetRepository();
        log4net.Repository.Hierarchy.Logger logger = hierarchy.GetLogger(loggerName) as log4net.Repository.Hierarchy.Logger;

        logger.AddAppender(rollingFileAppender);
        logger.AddAppender(memoryAppender);
        hierarchy.Configured = true;

        var m_log = log4net.LogManager.GetLogger(loggerName);


        for (int i = 0; i < 5; i++)
        {
            m_log.Info(i + " " + randomName);
            Thread.Sleep(10);
        }

        StringBuilder stringBuilder = new StringBuilder();
        foreach (var loggingEvent in memoryAppender.GetEvents())
        {
            stringBuilder.AppendLine(loggingEvent.MessageObject.ToString());
        }

        memoryAppender.Clear();
        Console.WriteLine(stringBuilder.ToString());
    }
}
```

**Comment by 304NotModified** [comment]
This code is easy to translate. Will try to post it tomorrow

**Comment by 304NotModified** [comment]
Something like this. Not tested


```c#
 private static void FirstWorldTask()
        {
            string loggerName = "Logger";
            string randomName = rnd.Next().ToString();
            string targetFileName = "File";
            string targetMemoryName = "Memory";

            lock (sync)
            {
                //or using threadid here?
                loggerName += randomName;
                targetFileName += randomName;
                targetMemoryName += randomName;
                Console.WriteLine(loggerName);
            }

            var MB20 = 20 * 1024 * 1024;
            var fileTarget = new FileTarget(targetFileName)
            {
                ArchiveAboveSize = MB20,
                Layout = "${message}",  //probably you need more here
                FileName = "./" + randomName + "/logfile.txt",


            };

            LogManager.Configuration.AddTarget(fileTarget);
            LogManager.Configuration.AddRule(LogLevel.Info, LogLevel.Fatal, fileTarget, loggerName); //filter on loggerName;


            var memTarget = new MemoryTarget(targetMemoryName)
            {
                Layout = "${message}", //probably you need more here
            };

            LogManager.Configuration.AddTarget(memTarget);
            LogManager.Configuration.AddRule(LogLevel.Info, LogLevel.Fatal, memTarget, loggerName); //filter on loggerName;

         

            var m_log = LogManager.GetLogger(loggerName);


            for (int i = 0; i < 5; i++)
            {
                m_log.Info(i + " " + randomName);
                Thread.Sleep(10);
            }

            StringBuilder stringBuilder = new StringBuilder();
            
            foreach (var loggingEvent in memTarget.Logs)
            {
                stringBuilder.AppendLine(loggingEvent);
            }
            memTarget.Logs.Clear();
          
            Console.WriteLine(stringBuilder.ToString());
        }
```

**Comment by vipiniitrmca** [comment]
Thanks Julian for quick response

I will test this tomorrow and update you, some more questions. 
Can we achieve this using NLog.Config file?
Can we have different loggerName at run time using config? For Ex : logger name="LogFile${mdc:item=ScenarioId}" or logger name="LogFile${var:ScenarioId}"

**Comment by 304NotModified** [comment]
Too bad not. The targets should have fixed names. But most of the time you will use 1 target and filter afterwards.

**Comment by 304NotModified** [comment]
I'm not sure. Did I have answered all your questions?

**Comment by vipiniitrmca** [comment]
Thanks Team.
Above things are working for me.

**Comment by 304NotModified** [comment]
:+1:
