### ISSUE TITLE
Target cannot be found: 'LogReceiverService'

### ISSUE THREAD

**Issue by liamyue** [NLog/NLog#1600]
I use NLog(version:4.4.0-betaV15) in my dotnet core application,but it looks like NLog doesn't provider LogReceiverService target now.I want to kown about when can I use it.thanks

**Comment by 304NotModified** [comment]
That's correct as there is a limited set implemented. Microsoft did dropped a lot of functionality in .net core. See https://github.com/nlog/nlog/wiki/platform-support

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, let us know!
