### ISSUE TITLE
${windows-identity} or ${identity} doesn't give windows user name info while sending nlog exception email

### ISSUE THREAD

**Issue by valcs007** [NLog/NLog#1601]
Hi,

Please find the issue details.

**Type** (choose one):

- Bug?

**NLog version**: (4.2.3)

**Platform**: .Net Core 1.0

**Current NLog config** (xml or C#, if relevant)

 
  <targets>
    
    <target xsi:type="File" name="allfile" fileName="c:\temp\nlog-all-${shortdate}.log"
                 layout="${longdate}|${event-properties:item=EventId.Id}|${logger}|${uppercase:${level}}|${message} ${exception}" />

   
    <target xsi:type="File" name="ownFile-web" fileName="c:\temp\nlog-own-${shortdate}.log"
             layout="${longdate}|${event-properties:item=EventId.Id}|${logger}|${uppercase:${level}}|  ${message} ${exception}" />

   
    <target name="Outlook" xsi:type="Mail"
            smtpServer="mail.test.com"
            smtpPort="25"
            smtpAuthentication="None"                                
            layout="DATE=${longdate} ${newline}                    
                    LEVEL=${uppercase:${level}}
                    ${machinename}
                    **_${windows-identity:userName=Boolean:domain=Boolean}
                   ${identity:authType=Boolean:separator=String:name=Boolean
          :isAuthenticated=Boolean}_**

                    LOCATION=${callsite:className=true:includeSourcePath=true:methodName=true} ${newline}               
                    MESSAGE=${message}${newline}    EXCEPTION=${exception:format=tostring,StackTrace}${newline}"
            from="abc@Test.com"
            to="xyz@test.com"        
          />
   <target xsi:type="Null"  name="blackhole" />  
  </targets>
  
  <rules>
    
    <logger name="*"  minlevel="Trace" writeTo="allfile" />
    <logger name="*"  minlevel="Error" writeTo="Outlook" />

    
    <logger name="Microsoft.*" minlevel= "" writeTo="blackhole" final="true" />
    <logger name="*" minlevel="Trace" writeTo="ownFile-web" />
  </rules>
</nlog>

**Expectation:**
 - Trying to send windows user name (My Asp.net Core 1.0 uses Windows Authentication) as part of exception email

  ${machinename} - To Give the deployment web server name (Where this process runs)
  ${windows-identity} or ${identity} - Gives the current windows user that got this exception

**Current Behavior:**

 ${machinename} - To Give the deployment web server name (Where this process runs) - **Works**
 ${windows-identity} or ${identity} - **Fails and no email generated**

**Comment by valcs007** [comment]
Based on the internal nlog, i found out that i forgot to replace the keyword "Boolean" with the actual boolean value and now {windows-identity:} works and i am getting email.

What is thee difference between 

**

- {windows-identity:}
- {identity:}
- {aspnet-user-identity:}

**

Which one should we use to get user info?

Thanks,

**Comment by 304NotModified** [comment]
You're using asp.net and need the logged in user right?

Windows-identity will print the apppool name. Identity the name of the thread user, which is also the apppool user. 

You need aspnet-user-indentity and the NLog.web.aspnetcore package. Don't forget to use the extension in the config, see https://github.com/NLog/NLog.Web#usage

**Comment by valcs007** [comment]
Thanks and that thread was very helpful.  Sorry, i have 1 last question reg nlog and ELMAH. 

As per my understanding  reading multiple articles, ELMAH captures (Unhandled exception but not currently supported for ASP.Net Core 1.0) and Nlog doesn't log things automatically (Can force to log messages using the below code

 logger.Warn("Sample warning message, k={0}, l={1}", k, l);
 logger.Error("Sample error message, k={0}, l={1}", k, l);

**My Experience from Project::**

Nlog alone captures unhanded exception (ELMAH is not needed anymore) as well along with manual logging if needed.

Is my understanding correct or am i missing something?

Thanks,

**Comment by 304NotModified** [comment]
AFAIK when using nlog.extensions.logging, all unhanded exception are logged. See https://github.com/NLog/NLog.Extensions.Logging

**Comment by valcs007** [comment]
Thanks for confirming.
