### ISSUE TITLE
highlight-word pattern to match multiline log message

### ISSUE THREAD

**Issue by Kimi-Arthur** [NLog/NLog#1604]
**Type** (choose one):
- Feature request

**NLog version**: 4.3.7

**Platform**: .Net 4.6

in case of a FEATURE REQUEST:
- Why do we need it?
  - There are multiline log messages, but the coloring of highlight-word doesn't work well for them. Only last line is matched, or as structure is different, the pattern will differ.

**Comment by UgurAldanmaz** [comment]
If coloring of highlight-word doesn't work well for the multiline log messages, maybe it is a bug.

I skimed through the related codes. I need to test this scenario.

**Comment by 304NotModified** [comment]
Ps this is for the console target

**Comment by UgurAldanmaz** [comment]
Thanks @304NotModified, it is not colored console target?

**Comment by 304NotModified** [comment]
Yes indeed :)

**Comment by Kimi-Arthur** [comment]
See my xml in the related bug #1603. It doesn't work for color console for me.

**Comment by jp7677** [comment]
@Kimi-Arthur Would you mind to provide your configuration, a sample log statement and a screenshot where you describe what's wrong in it? I would love to check my alternative implementation (colorizing using ansi codes, see https://github.com/NLog/NLog/pull/1495) for this isssue.

**Comment by 304NotModified** [comment]
Good idea!

**Comment by bhaeussermann** [comment]
@Kimi-Arthur Take note that the regex dot (.) metacharacter does **not** match line breaks. Could you try using the expression ` (.|\r|\n)*$` instead?

**Comment by 304NotModified** [comment]
good point :)

**Comment by snakefoot** [comment]
@304NotModified If there are issues with multi-line coloring then they will resolved with #3018

**Comment by 304NotModified** [comment]
:+1: ok close then :)

**Comment by 304NotModified** [comment]
close as this has been fixed in NLog 4.6
