### ISSUE TITLE
Conflict of DeleteOldFileOnStartup and ThrowExceptions options

### ISSUE THREAD

**Issue by sungam3r** [NLog/NLog#1605]
**Type**: Bug

**NLog version**: 4.3.7

**Platform**: .Net 4.5

**Current NLog config**:

```xml
<nlog throwExceptions="true">
    <targets>
      <target name="svc-startup" encoding="UTF-8" type="File"  deleteOldFileOnStartup="true" fileName="logs/svc-startup.log" layout="${date:format=HH\:mm\:ss\.ffff} ${level:uppercase=true} ${message} ${exception:format=tostring}" />
    </targets>
    <rules>
      <logger name="Startup" minlevel="Trace" writeTo="svc-startup" />
    </rules>
</nlog>

```
Note that directory 'logs' initially does not exist. In such a case we have DirectoryNotFoundException in method void FileTarget.ProcessOnStartup(string fileName, LogEventInfo logEvent)

- What is the current result:
DirectoryNotFoundException
- What is the expected result:
Normal operation without exceptions
- Full exception details
An unhandled exception of type 'System.IO.DirectoryNotFoundException' occurred in NLog.dll
в System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   в System.IO.File.InternalDelete(String path, Boolean checkHost)
   в System.IO.File.Delete(String path)
   в NLog.Targets.FileTarget.ProcessOnStartup(String fileName, LogEventInfo logEvent)
   в NLog.Targets.FileTarget.InitializeFile(String fileName, LogEventInfo logEvent, Boolean justData)
   в NLog.Targets.FileTarget.WriteToFile(String fileName, LogEventInfo logEvent, Byte[] bytes, Boolean justData)
   в NLog.Targets.FileTarget.ProcessLogEvent(LogEventInfo logEvent, String fileName, Byte[] bytesToWrite)
   в NLog.Targets.FileTarget.Write(LogEventInfo logEvent)
   в NLog.Targets.Target.Write(AsyncLogEventInfo logEvent)
   в NLog.Targets.Target.WriteAsyncLogEvent(AsyncLogEventInfo logEvent)
   в NLog.LoggerImpl.WriteToTargetWithFilterChain(TargetWithFilterChain targetListHead, LogEventInfo logEvent, AsyncContinuation onException)
   в NLog.LoggerImpl.Write(Type loggerType, TargetWithFilterChain targets, LogEventInfo logEvent, LogFactory factory)
   в NLog.Logger.WriteToTargets(LogLevel level, Exception ex, String message, Object[] args)
   в NLog.Logger.Fatal(Exception exception, String message, Object[] args)

- Are there any work arrounds?
yes, do not use DeleteOldFileOnStartup="true" and ThrowExceptions="true" together

**Comment by 304NotModified** [comment]
Agree, Throwing an exception is a bit wierd in this case.

**Comment by 304NotModified** [comment]
If you could help with an unit test or PR, that would be great!

**Comment by sungam3r** [comment]
[ConsoleApplication8.zip](https://github.com/NLog/NLog/files/439609/ConsoleApplication8.zip)

**Comment by 304NotModified** [comment]
4.3.8 is now live!

**Comment by sungam3r** [comment]
Thank you!
