### ISSUE TITLE
How can I include ASP.NET post data in the layout?

### ISSUE THREAD

**Issue by jckh1234** [NLog/NLog#1607]
**Type** (choose one):
- Question

**NLog version**:  4.2.7

**Platform**:  .Net 4.5 

I want to log all whole post data body to a log, my post data is in json format, what renderer should I use?

**Comment by 304NotModified** [comment]
You need also the NLog.web package and https://github.com/nlog/nlog/wiki/AspNetRequest-Layout-Renderer

**Comment by 304NotModified** [comment]
And I think you need the 'form' option.

**Comment by 304NotModified** [comment]
Has your question being answered?

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, let us know!

**Comment by zbmcz** [comment]
I want to log all whole post data body to a log, my post data is in json format, what renderer should I use?

There doesn't have any method i can use to log all post data in  https://github.com/nlog/nlog/wiki/AspNetRequest-Layout-Renderer

**Comment by 304NotModified** [comment]
@zbmcz please open a new issue, or maybe even better, a question on stackoverflow. Thanks!
