### ISSUE TITLE
WebAPI method as target logging.

### ISSUE THREAD

**Issue by muralinit** [NLog/NLog#161]
Hi,

When i am logging from my Console application, I wanted to call an action (i.e.; Post) in an WebAPI. Does NLog will provide this functionality. Because I have seen one example with Webservices. I want the same behavior with WebAPI.

It it is already implemented please refer to a site or if you guys have already recorded some videos please post those links. It will help me in understanding NLog very well.

Thanks & Regards,
N.Murali Krishna.

**Comment by 304NotModified** [comment]
This is nowadays possible with WebserviceTarget and so closing this issue.
