### ISSUE TITLE
Weird mutable dictionary in MappedDiagnosticsLogicalContext

### ISSUE THREAD

**Issue by sungam3r** [NLog/NLog#1610]
**Type**: Bug

**NLog version**: 4.3.7

**Platform**: .Net 4.5

**Current NLog config**: without config

- What is the current result? - Nondeterministic, random behavior
- What is the expected result? - True async-local behavior
- Are there any work arrounds? - Yes, use NLog Custom Layout Renderer instead of MdlcLayoutRenderer and MappedDiagnosticsLogicalContext in it

The example in the Appendix
[ConsoleApplication1.zip](https://github.com/NLog/NLog/files/450773/ConsoleApplication1.zip)

P.S. This link can help http://blog.stephencleary.com/2013/04/implicit-async-context-asynclocal.html
"You should only use immutable types as logical call context data values"

**Comment by 304NotModified** [comment]
This is an know issue. There are some more related Github issues over it. 

Fix is planned for NLog 4.5, but if you could help us, then maybe we could add it to the next release

**Comment by 304NotModified** [comment]
See #934 and http://stackoverflow.com/questions/39040688/nlog-mappeddiagnosticslogicalcontext-not-working-in-async-await-with-configureaw/39111531#comment65762857_39111531

**Comment by 304NotModified** [comment]
fixed by #1640

**Comment by 304NotModified** [comment]
NLog 4.3.9 is live! https://www.nuget.org/packages/NLog/4.3.9
