### ISSUE TITLE
${callsite} and Common.Logging

### ISSUE THREAD

**Issue by plutext** [NLog/NLog#1611]
If I set up NLog 4 (on .NET 4) programmatically, for example:

```
            NLog.Config.LoggingConfiguration config = new NLog.Config.LoggingConfiguration();
            NLog.Targets.Target t = new NLog.Targets.FileTarget();
                ((NLog.Targets.FileTarget)t).FileName = System.IO.Path.GetTempPath() + "plutext_Docx4jHelper.txt";
                ((NLog.Targets.FileTarget)t).AutoFlush = true;
            config.AddTarget("ds", t);

            setRule("org.docx4j.XmlUtils", NLog.LogLevel.Info, config, t);
            setRule("org.docx4j.utils.ResourceUtils", NLog.LogLevel.Warn, config, t);
            setRule("org.docx4j.jaxb.Context", NLog.LogLevel.Info, config, t);

            NLog.LogManager.Configuration = config;
```
with Common.Logging then routed to it:

```
            // Route Common.Logging to NLog
            NameValueCollection commonLoggingproperties = new NameValueCollection();
            commonLoggingproperties["showDateTime"] = "false";
            commonLoggingproperties["level"] = "INFO";

            Common.Logging.LogManager.Adapter = new Common.Logging.NLog.NLogLoggerFactoryAdapter(commonLoggingproperties);
```

I get ${callsite} set as I'd expect, for example to "org.docx4j.jaxb.Context"

`2016-09-02 18:35:39.8477|INFO|org.docx4j.jaxb.Context|Using Java 6/7 JAXB implementation`

If I use an NLog config file + the same code to route Common.Logging to NLog,

${callsite} always comes out as com.plutext.slf4jNetCommonsLogging.NetCommonsLoggerAdapter, for example

`2016-09-02 18:25:31.0396 - com.plutext.slf4jNetCommonsLogging.NetCommonsLoggerAdapter.info - INFO: Using Java 6/7 JAXB implementation`

Any idea why this would be, and what I might do about it?

What I'd likeis the same logger name that I get from the programmatic config.

**Comment by 304NotModified** [comment]
I think you need to hide/blacklisted the Assembly, see http://nlog-project.org/2015/01/12/nlog-3-2-0-is-released.html

**Comment by 304NotModified** [comment]
And for logger name, use `${logger}`

**Comment by plutext** [comment]
thanks, that's great
