### ISSUE TITLE
Implement MailTarget for .NET Core

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#1614]
Feature

> The mail target isn't supported in net core as Microsoft didn't port the mail classes. See link platform support.
https://github.com/NLog/NLog/wiki/platform-support

SMTPClient is not supported, see https://github.com/dotnet/corefx/issues/1006
but we could use MailKit https://www.nuget.org/packages/MailKit/

**Comment by 304NotModified** [comment]
how to implemented this:

1. fork
2. create new branch from `coreCLR` branch
3. implement using mailkit for `UWP10` (we still have to rename it)
4. add/enable unit tests
5. send PR to  `coreCLR` branch

**Comment by UgurAldanmaz** [comment]
I see two coreCLR branches with git bash; `upstream/coreCLR` and `NLog/coreCLR`.  I am not sure which branch I need.

Also master branch is used to rebase in [contributing.md](https://github.com/NLog/NLog/blob/master/CONTRIBUTING.md#sync-back).

    git rebase upstream/master

Do I need to rebase with coreCLR instead of master?

    git rebase upstream/coreCLR

**Comment by 304NotModified** [comment]
I think NLog/coreCLR , but please post the output of

`git remote -v` (in the nlog folder)

**Comment by UgurAldanmaz** [comment]
Thanks Julian.

I will able to take look at weekend.

**Comment by UgurAldanmaz** [comment]
Hey @304NotModified.

Here is the output of `git remote -v`  command:

```
$ git remote -v
NLog    https://github.com/NLog/NLog.git (fetch)
NLog    https://github.com/NLog/NLog.git (push)
origin  https://github.com/UgurAldanmaz/NLog.git (fetch)
origin  https://github.com/UgurAldanmaz/NLog.git (push)
upstream        https://github.com/NLog/NLog.git (fetch)
upstream        https://github.com/NLog/NLog.git (push)

**Comment by 304NotModified** [comment]
So NLog and upstream are the same. If there aren't the same locally, use `git fetch -a` (fetch all).

You could drop one of the remotes, I would remove "upstream" 

You could do that in TortioseGit (contextmenu -> settings)
![image](https://cloud.githubusercontent.com/assets/5808377/18817392/5745c7bc-835f-11e6-888f-186d2688eace.png)

or 

```
git remote rm upstream
```

**Comment by UgurAldanmaz** [comment]
I added upstream according to our [contributing instructions](https://github.com/NLog/NLog/blob/master/CONTRIBUTING.md#sync-back) :)

Ok. I will be available next week.

**Comment by mb2140** [comment]
Looking forward to this!  Is there a branch available that I can test out?

**Comment by UgurAldanmaz** [comment]
Hi @mb2140. Thanks for your interest. Unfortunately I could not find free time to work on this yet.

But I will complete as soon as possible.

**Comment by 304NotModified** [comment]
@mb2140 if you like to test it soon, maybe it's easier to create your own extension. We could guide you how to set this up.

**Comment by spottedmahn** [comment]
[MailKit Officially Replaces .NET’s SmtpClient](https://www.infoq.com/news/2017/04/MailKit-MimeKit-Official)

**Comment by spottedmahn** [comment]
hello - any updates on this issue/missing feature?  We would really like to use the mail target!!

**Comment by 304NotModified** [comment]
Nope. It should not to be difficult to implement though. I could help you with that.

**Comment by 304NotModified** [comment]
I have created an additional package for this - the [NLog.MailKit package](https://www.nuget.org/packages/NLog.MailKit)

With your config it should work :)

Also add this to your config:

    <extensions>
        <add assembly="NLog.MailKit"/>
    </extensions>

Currently not implemented:

- Encoding
- PickupDirectory
- NTLM auth

**Comment by M-R-Bishop** [comment]
@304NotModified Installed and working great so far.  Thanks for working on this!

**Comment by 304NotModified** [comment]
Thanks! Encoding also added :)

**Comment by 304NotModified** [comment]
If everything works well, I will create a final release soon.
