### ISSUE TITLE
Nlog created file get locked by session.

### ISSUE THREAD

**Issue by nchandranlog** [NLog/NLog#1624]
Hi,

**Type** (choose one): Bug

**NLog version**: All version

Issue:
File created by nlog was locked by user when rolling operation occurs which result in logging stopped (Error in Procmon - File is locked). We have set for rolling operation to occurs when file reaches it max size and current file will be renamed and new file get created. All the users are writing in same files, so at the time of roll out if file is get locked by user A then all the data for user B is get lost as nlog is not able to rename the old file and new file not created. So solve this user A has to kill the session which allows nlog to rename file and created new one as will.
- User B data is lost during this time interval.
- User A has to kill the session to solve this issue.

Now user A has not idea that issue is occurred or not because only way to see issues status is to check nlog file every time after some interval. 

Workaround:
There was one key named as "KeepFileOpen" when we set its value to "false" file is not getting locked as may be it open and close file for every operation but this key will impact performance. We have 300-400 concurrent user so we can't test this key as it will result in major performance/slowness. Current value of the key is True.

Please help us with any other workaround or any other solution if you can think off. I have tested with latest nlog DLL and issue is present in it too. We are using 2.1.0.0 version right now. 
Let me know if you have any query or need more information on this issue. We are facing critical issues and since logging is stopped in b/w any time its very difficult to get logs.

I'll appreciate your time on this issue. Thanks in advance.

-Nikhilesh Chandra
+91-9033291366

**Comment by 304NotModified** [comment]
Hi, please post the important parts the config

**Comment by nchandranlog** [comment]
Is it OK if I upload only nlog section because I can't share entire config file due to security issues and company policy.

Sent from YU

On 5 Sep 2016 16:18, Julian Verdurmen <notifications@github.com> wrote:

Hi, please post the important parts the config

-

**Comment by 304NotModified** [comment]
Sure

**Comment by nchandranlog** [comment]
Here:

  <configSections>
    <section name="nlog" type="NLog.Config.ConfigSectionHandler, NLog,Version=2.1.0.0,   Culture=neutral, PublicKeyToken=5120e14c03d0593c" />
  </configSections>
....
....
<nlog autoReload="false" xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <targets>
      <target name="asyncWrapper" xsi:type="AsyncWrapper" queueLimit="5000" overflowAction="Grow">
        <target name="file" xsi:type="File" layout="${message}" filename="${gdc:logdir}/Log/xyzl.log" archiveFileName="${gdc:logdir}/Log/xyz.{##}.log" archiveAboveSize="25194304" archiveNumbering="Rolling" concurrentWrites="true" maxArchiveFiles="50" keepFileOpen="true" encoding="iso-8859-2" enableFileDelete="false" />
      </target>
    </targets>
    
    <rules>
      <logger name="*" minlevel="Info" writeTo="asyncWrapper" />
    </rules>
  </nlog>




- Thanks for such quick action on this one !!!

**Comment by nchandranlog** [comment]
Attached at website as well☺

**Comment by 304NotModified** [comment]
OK will check it in depth soon

What is the platform/architecture? IIS on Windows on one server?

**Comment by nchandranlog** [comment]
Windows Server 2012R2
IIS8.5
Nlog : 2.1.0.0

**Comment by nchandranlog** [comment]
Hi,

Just checking for any update or more information required from my side !!!

**Comment by 304NotModified** [comment]
I'm just back from Holiday, I will try to release a test package on Nuget today (evening probably)

**Comment by nchandranlog** [comment]
Great..
Thanks

**Comment by 304NotModified** [comment]
Sorry about the delay.

See here (it's hidden) https://www.nuget.org/packages/NLog/4.3.9-test-retry-archive

**Comment by nchandranlog** [comment]
So now should I need to reproduce the issue in my environment after installing package and is there any change required in config file ?

**Comment by 304NotModified** [comment]
Yes indeed and no config changes are needed.

**Comment by nchandranlog** [comment]
Hi,

I have tested in my internal environment with Nuget provided by you but i can still able to reproduce the issue i.e. when multiple users try to write on same log file it get locked by the user A. When User A close his  session logging start again.

One Observation:
This lock operation is always happen when log file with logfilename00.log is deleted. When we perform operation in our exe and log files are started creating, so when logfilename.log is reached it max size limit it renamed to logfilename00.log. When we continue with operations logfilename.log is reached it max size limit again so now logfilename00.log renamed into logfilename01.log successfully but logfilename.log is not able to renamed into logfilename00.log.

Here in short summary:

1. logfilename ->(when reached max size limit)-> logfilename00 [Successful Renamed]
2. logfilename00 -> logfilename01 [Successful Renamed]
3. logfilename -> logfilename00 [Failed - File locked]

File Exist at time of lock : logfilename, logfilename01
Missing File at time of lock : logfilename00

The above observation is guess which might help you to find root cause. Please let me know if any more information is required.

Thanks,
Nikhilesh Chandra

**Comment by 304NotModified** [comment]
OK thanks for testing, will try another way.

**Comment by 304NotModified** [comment]
I checked the code. We only doing File.Move, so

1. logfilename ->(when reached max size limit)-> `File.Move(logfilename, logfilename00)`
2. (when reached max size limit) 
  - `File.Move(logfilename00, logfilename01) `
  - `File.Move(logfilename, logfilename00)` //fails, logfilename00?? locked

Is logfilename or logfilename00 locked?

Could you post an internal log?

**Comment by nchandranlog** [comment]
Hi,
Can you please provide the location for 4.3.9-test package.

This logfilename00 scenario is a guess observation, every time when file get locked logfilename00 was deleted/hidden i.e. logfilename00 was not there in log folder. I think we should not focus more on logfilename00.log.
-------
File.Move(logfilename, logfilename00) //fails, logfilename00??locked -> 

**logfilename00 -> Missing**
-------
**Logfilename.log is file which is get locked every time when this issue of file lock occurs because logfilename.log is the current file in which write operation has been performed every time.** There is no internal logs as logging is stopped due to lock. 

We have find below error from process monitor -
![image](https://cloud.githubusercontent.com/assets/22000740/18501963/ac3edd54-7a71-11e6-90b5-53528e2c6b09.png)

![image](https://cloud.githubusercontent.com/assets/22000740/18501971/c2a056fe-7a71-11e6-99b0-dbcd6c633b12.png)

Thanks!!!!

**Comment by nchandranlog** [comment]
One important thing we should consider here is when we set KEEPFILEOPEN = FALSE issue is not reproducible i.e. file is not kept open for all the time and file is not get locked but we can't set it to False because of the performance impact of this key.

So we can focus on what's operation performed when it set to "True" and "False". So we can find the difference and may be we get some thing to focus on to this issue.

**Comment by 304NotModified** [comment]
yes indeed, I was think to change the keepfileopen before archiving, but that's difficult.

There is also another option, which is bit more limited in functionality, but very good in performance.

1. Disable archiving
2. Write to one file with the date in the name, so you could split the logs files per day/hour.
3. Let an external process cleanup the old files.

At my work we do it like that, and we create a new folder for each month, so something like this:


```xml
<target name="file" xsi:type="File" fileName="${logDirectory}\${date:format=yyyy-MM}\log_${shortdate} (${date:format=ddd:culture=nl}).log" layout="${longdate} ${callsite} ${level} ${message} ${exception}"/>
```

**Comment by nchandranlog** [comment]
So no exact solution to real problem of locking log file :(
I think your idea of changing keepfileopen before archiving is good and it can solve this problem.
Do you considered finding the difference of code with True and False value of keepfileopen.

Thanks !!

**Comment by nchandranlog** [comment]
Hi,

We are getting below after making changes suggested by you.

**<target name="file" xsi:type="File" 
            fileName="${logDirectory}\${date:format=yyyy-MM}\log_${shortdate} (${date:format=ddd:culture=nl}).log" 
            layout="${longdate} ${callsite} ${level} ${message} ${exception}"/>**

Error: Tool.exe is crashed after replacing above section in nlog-

![image](https://cloud.githubusercontent.com/assets/22000740/18545574/6334fd14-7b57-11e6-85b9-0e403f9a4b3e.png)

Current target section:

<targets>
      <target name="asyncwrapper" xsi:type="asyncwrapper" queuelimit="5000" overflowaction="grow">
        <target name="file" xsi:type="file" layout="${message}" filename="${gdc:logdir}/log/uishell.log" archivefilename="${gdc:logdir}/log/uishell.{##}.log" archiveabovesize="25194304" archivenumbering="rolling" concurrentwrites="true" maxarchivefiles="50" keepfileopen="true" encoding="iso-8859-2" enablefiledelete="false" />
      </target>
    </targets>	
	
It will be great if you can update above section according to your suggestion of creating one file. We can test it but I really appreciate if we can able to fix the real issue. 
Please let me know if I can help in any way.

**Comment by 304NotModified** [comment]
I would recommend:


```xml
<targets>
      <target name="asyncwrapper" xsi:type="asyncwrapper" queuelimit="5000" overflowaction="grow">
        <target name="file" xsi:type="file" layout="${message}" filename="${gdc:logdir}/log/uishell.log" archivefilename="${gdc:logdir}/log${date:format=yyyy-MM}\log_${shortdate} (${date:format=ddd}).log" concurrentwrites="true" keepfileopen="true" encoding="iso-8859-2" enablefiledelete="false" />
      </target>
    </targets> 

```

**Comment by nchandranlog** [comment]
Sure l'll proceed testing with your recommendation.
Any thought on changing keepfileopen value at run time ? or any other approach because proceeding with this workaround would not be feasible for long run.

**Comment by nchandranlog** [comment]
I have couple of questions:
1. if I'm correct as per your statement now there will be only one log file ? 
2. archivefilename="${gdc:logdir}/log${date:format=yyyy-MM}\log_${shortdate} (${date:format=ddd}).log" archivefilename is there but we are missing archiveabovesize in your recommendation?

---
Write to one file with the date in the name, so you could split the logs files per day/hour.
log file names will be contain day and hours right ?
---

 I just want to know the flow, how this will work.

**Comment by 304NotModified** [comment]
> I have couple of questions:
> 1. if I'm correct as per your statement now there will be only one log file ?

In my prosaically you get one file a day and every month a folder. So in you year you get 365 (or 366) files and 12 folders. 

> 2. archivefilename="${gdc:logdir}/log${date:format=yyyy-MM}\log_${shortdate} (${date:format=ddd}).log" archivefilename is there but we are missing archiveabovesize in your recommendation?

that was a mistake, no archivefilename


> Write to one file with the date in the name, so you could split the logs files per day/hour.
> log file names will be contain day and hours right ?

I my proposal the filename doesn't have a hour and containing only the day, dayname and month. You could also use the hour in the logfile, but then you will get 24 files per day. 

> Any thought on changing keepfileopen value at run time ? or any other approach because proceeding with this workaround would not be feasible for long run.

Technically that would be very difficult. "Keeping file open" or not isn't a setting we could change while running. We need to stop the logging, change it and restart. But then you will get problems when logging while it's stopped, so we need an buffer etc. Things get pretty complicated.

Last but not least, IMO writing to a file with high concurrent traffic isn't maybe the best idea. Writing files is on Windows mostly designed for single thread usage. A database would be a better choice IMO.

**Comment by nchandranlog** [comment]
Hi,

I'm trying below configuration but archive is happening after everyone minute which should happen according to this article.
----------------------------------------------------------------------------------------
archiveEvery - Indicates whether to automatically archive log files every time the specified time passes.
Possible values:

Day - Archive daily.
Hour - Archive every hour.
Minute - Archive every minute.
Month - Archive every month.
None - Don't archive based on time.
Year - Archive every year.
Files are moved to the archive as part of the write operation if the current period of time changes. For example if the current hour changes from 10 to 11, the first write that will occur on or after 11:00 will trigger the archiving. Caution: Enabling this option can considerably slow down your file logging in multi-process scenarios. If only one process is going to be writing to the file, consider setting ConcurrentWrites to false for maximum performance.

archiveDateFormat - Specifies the date format used for archive numbering. Default format depends on the archive period.

This option works only when the "ArchiveNumbering" parameter is set to Date
----------------------------------------------------------------------------------------

My target:

<targets>
			<target name="asyncWrapper" xsi:type="AsyncWrapper" queueLimit="5000" overflowAction="Grow">
				<target name="file" xsi:type="File" layout="${message}" filename="${gdc:logdir}/Log/UIShell.log" archiveFileName="${gdc:logdir}/Log/UIShell.{##}.log" archiveNumbering="Date" archiveEvery="Minute"
            archiveDateFormat="yyyyMMdd" concurrentWrites="true" maxArchiveFiles="50" keepFileOpen="true" encoding="iso-8859-2" enableFileDelete="false"></target>
			</target>
		</targets>

Let me know if you find something which I'm missing in above target section.

**Comment by nchandranlog** [comment]
One more query:

**archiveNumbering key**
DateAndSequence - Combination of Date and Sequence .Archives will be stamped with the prior period (Year, Month, Day) datetime. The most recent archive has the highest number (in combination with the date). 
**The date is formatted according to the value of archiveDateFormat.**

archiveDateFormat - Specifies the date format used for archive numbering. Default format depends on the archive period.
**This option works only when the "ArchiveNumbering" parameter is set to Date.**

If I want to use "DateAndSequence" archiveNumbering it say like date is formatted according to archiveDateFormat but archiveDateFormat says it will only work with Date as achiveNumbering. I have bold out that part and its a contradict to each other statement.
https://github.com/nlog/NLog/wiki/File-target

**Comment by 304NotModified** [comment]
> I'm trying below configuration but archive is NOT happening after everyone minute which should happen according to this article.

I could delay if there are a lot of writes AFAIK.


> This option works only when the "ArchiveNumbering" parameter is set to Date.

yeah that's old-dated. DateAndSequence is later added. I have updated the wiki.

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, let us know!
