### ISSUE TITLE
(ExceptionLayoutRenderer) How to specify separator for format "data"?

### ISSUE THREAD

**Issue by FroggieFrog** [NLog/NLog#1625]
**Type**: Question
**NLog version**:  4.3.6
**Platform**: .Net 4.0 / .Net 4.5
**Current NLog config**
```xml
<nlog>
  <targets>
<target name="TraceLogger" xsi:type="File" layout="${pad:padding=-24:inner=${longdate}}||${pad:padding=-5:inner=${level:uppercase=true}}||${logger}||${message:whenEmpty=(no message)}${onexception:${newline}${exception:format=Message}${newline}${newline}${exception:format=Data}${newline}${newline}${exception:format=StackTrace:maxInnerExceptionLevel=3}${newline}${newline}${newline}${newline}${exception:format=ToString}" fileName="${var:logDirectory}/${var:traceLogFileName}.txt" archiveFileName="${var:archiveDirectory}/${var:traceLogFileName}.{####}.txt" maxArchiveFiles="7" footer="----------|${pad:padding=-24:inner=${longdate}}|Ende Programm" />
  </targets>
  <rules>
  </rules>
</nlog>
```

When rendering an excepetion with format=data, then the data is logged with a ";" as separator.
**How can I change this behaviour to logging each entry in exception.Data on a new line?**
Also the Data of an InnerException is not logged.

**Comment by 304NotModified** [comment]
You should set the options separator and maxInnerExceptionLevel.  
 
Eg `${exception:format=Data:maxInnerExceptionLevel=10:separator=|}`

See https://github.com/nlog/nlog/wiki/Exception-Layout-Renderer

**Comment by FroggieFrog** [comment]
Thank you! I did not know "maxInnerExceptionLevel" defaults to 0.

**NLog version:** 4.3.8

But neither
``
${exception:format=Data:maxInnerExceptionLevel=10:seperator=${newline}}
``
nor
``
${exception:format=Data:maxInnerExceptionLevel=10:seperator=|}
``
is working.

The Data is always seperated by ";". I want them seperated by a new line.

**Comment by 304NotModified** [comment]
Yes sorry,

I see in the code that the separator for the data is fixed. 
You should create a subclass for that, e.g.:


```c#
    [LayoutRenderer("exception-custom")]
    [ThreadAgnostic]
    public class CustomExceptionLayoutRendrer : ExceptionLayoutRenderer
    {
        protected override void AppendMessage(System.Text.StringBuilder sb, Exception ex)
        {
            base.AppendMessage(sb, ex);
            sb.Append("\r\ncustom-exception-renderer");
        }

        protected override void AppendData(System.Text.StringBuilder sb, Exception ex)
        {
            base.AppendData(sb, ex);
            sb.Append("\r\ncustom-exception-renderer-data");
        }
    }
```

register it (application_start/main)
```
ConfigurationItemFactory.Default.LayoutRenderers.RegisterDefinition("exception-custom", typeof(CustomExceptionLayoutRendrer));
```

**Comment by 304NotModified** [comment]
I think you could also overwrite the `${exception}` (so register with the same name).

**Comment by 304NotModified** [comment]
Fixed by https://github.com/NLog/NLog/pull/1628

**Comment by 304NotModified** [comment]
Will release this week!

**Comment by 304NotModified** [comment]
Thanks for the contribution!!
