### ISSUE TITLE
EasyLOB, an Archetype for LOB Applications

### ISSUE THREAD

**Issue by EasyLOB** [NLog/NLog#1630]
Thanks for creating NLog!
I just published EasyLOB, an Open Source Archetype for building ASP.NET MVC LOB Application, at GitHub:

https://github.com/EasyLOB/EasyLOB/wiki

NLog is the library I use for Logging.

**Comment by 304NotModified** [comment]
please add your name here: https://github.com/NLog/NLog/wiki/Who-Is-Using-NLog
