### ISSUE TITLE
Write Internal Log to EventLog

### ISSUE THREAD

**Issue by ferrt123** [NLog/NLog#1636]
Hi Guys,

Is it possible to save a internal Log in a EventLog target? not just in internalLogFile

**Comment by 304NotModified** [comment]
Nope, but you could write it by using the writer property.

**Comment by 304NotModified** [comment]
We could add eventhooks to the internal log so it's easier to accomplish. What do you think?

**Comment by ferrt123** [comment]
I'll study it. Then i try, thanks 304NotModified

**Comment by UgurAldanmaz** [comment]
Hi @ferrt123. Did you have a chance to try?

**Comment by ferrt123** [comment]
Not yet. For now I am using File. When i improve the part of log in my application probably. Sorry @UgurAldanmaz

**Comment by UgurAldanmaz** [comment]
No problem. I just wanted to know whether you got your question's answer. 

Please let me know when you get a chance to try.

**Comment by 304NotModified** [comment]
@UgurAldanmaz I think it would be nice to add an event handler to the internal log. What do you think?

**Comment by UgurAldanmaz** [comment]
InternalLogger used to diagnostic, therefore it should be as simple as possible. There are some options to log to Console and Trace in the InternalLogger, and they are enough in my opinion.

Event handler is a good idea. But I am not sure if it will make InternalLogger complicated. 
If someone decide to use this event handler for writing to database and when database error occured, then InternalLogger try to tell there is a database problem to database, InternalLogger will fail. :)

Event handler will expose InternalLogger to the user side. For internal things, staying in the NLog is better than allowing user to manage internal logs.

Also NLog users need to write code to handle this event (if she want, of course) for every new project.

I suggest different way. Maybe we can develop something like this:

```xml
<nlog internalLogFile="c:\log.txt" internalLogLevel="Trace" internalLogToTarget="myEventLogTarget">
   <targets>
   <target xsi:type="EventLog"
          name="myEventLogTarget"
          layout="${message}${newline}${exception:format=ToString}"
          />
   // other targets
   </targets>
   <rules>
      <logger name="*" minlevel="Trace" writeTo="myEventLogTarget" />
   </rules>
</nlog>
```

We can add an option like `internalLogToTarget` that internal logger uses it to write logs. This way would be more easy to handle an event at the user side and this way allows us to stay in NLog. 

What do you think about it?

**Comment by 304NotModified** [comment]
That could lead to infinite loops, as the targets write to the internal log

**Comment by UgurAldanmaz** [comment]
Good catch! So we can consider event handler option.

**Comment by snakefoot** [comment]
Have implemented an idea for allowing InternalLogger to write to normal non-async target. Example nlog.config:

```
  <rules>
    <logger name="NLog.InternalLogger" minlevel="Trace" writeTo="console" final="true" />
    <logger name="*" minlevel="Debug" writeTo="file" />
  </rules>
```

**Comment by 304NotModified** [comment]
Cool, but how this well work if the target writes to the internal log?

**Comment by snakefoot** [comment]
The lock on internalLogEventThreadId-array ensures only one threads writes to the Target.

The thread writing to the target saves its threadid in the first array-item, so it can detect a cyclic call if the target triggers yet another write to the InternalLogger. I guess one could attempt to defer the writing of the internal-logger-messages generated by its own Target by saving them to a temporary list.

**Comment by 304NotModified** [comment]
> The lock on internalLogEventThreadId-array ensures only one thread writes to the InternalLogger-Target.

Smart one. I was thinking to detect the loop by passing the loggername or adding an extra property to the logEventInfo.

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, let us know!

**Comment by biiiipy** [comment]
@304NotModified I'm not able to get https://github.com/NLog/NLog/issues/1636#issuecomment-254071703 solution to work. Is this still possible?

**Comment by 304NotModified** [comment]
The only way now to do this is by listening to this event:

https://nlog-project.org/documentation/v4.7.0/html/E_NLog_Common_InternalLogger_LogMessageReceived.htm

**Comment by snakefoot** [comment]
Again it is SUPER important not to call/use NLog Logger-objects when attaching to `LogMessageReceived`-EventHandler

**Comment by 304NotModified** [comment]
@snakefoot sure, that seems obvious to me
