### ISSUE TITLE
[Linux][Docker]how to write log file In an absolute path

### ISSUE THREAD

**Issue by zuosc** [NLog/NLog#1638]
my  program run on docker.  I  need write log file in an absolute path, Like /data/logs/XXXX

This my config file

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true">	  
  <variable name="logDir" value="/data/logs/app"/>
  <targets>
    <target name="production" xsi:type="File"
            fileName="${logDir}/${shortdate}.log" />
  </targets>
  <rules>
    <logger name="*" minlevel="Info" writeTo="production" />
  </rules>
</nlog>
```

but it not Work correctly

can  you  help  me？

**Comment by 304NotModified** [comment]
What isn't working? No logs at all? Your config looks fine. Please check the internal log and the location and caps of the config file name.

**Comment by zuosc** [comment]
OK  OK  It's OK     I was careless。

my config file name  is   nlog.config.   but in program I write Nlog.config.  

on windows it's ok.  but on linux  it's error. 


Thank You!  Your Nlog  is very good!!!!

**Comment by 304NotModified** [comment]
OK glad it has been solved!
