### ISSUE TITLE
Set to the default value when given MaxMessageLength value is zero or negative

### ISSUE THREAD

**Issue by UgurAldanmaz** [NLog/NLog#1653]
If given value is zero or negative, then Exception will throw. I developed in this way but I have noticed that it is not an elegant solution.

Set to default would be more elegant then throwing an exception.

**Comment by snakefoot** [comment]
Closing since the ArgumentException have not caused any complaints. I guess an alternative approach would be doing the option-validation inside `InitializeTarget()`
