### ISSUE TITLE
Logger configuration attributes issue with duplicate attributes

### ISSUE THREAD

**Issue by Falconwatch** [NLog/NLog#1659]
**Type**: Bug

**NLog version**: 4.3.9

**Platform**: Net 4.6 

**Current NLog config**: xml 

``` xml
<nlog throwExceptions="false" internalLogFile="nloglog.txt" internalLogLevel="Trace">
    <targets>
      <target name="Console" type="ColoredConsole" useDefaultRowHighlightingRules="true" layout="${longdate} | ${message}"/>
    </targets>
    <rules>
      <logger name="*" minlevel="Info" writeTo="Console" minLevel="Info"/>
    </rules>
  </nlog>

```

The logger declaration contains two attributes with names different only in case ("minlevel" and "minLevel")
- What is the current result?
  Logger does not log anything
- What is the expected result?
  Logger writes logs or throws an exception
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
  Yes. Logger does not write even an internal log
- Are there any work arrounds?
  No
- Is there a version in which it did worked? 
  Don't know
- Can you help us by writing an unit test?
  https://github.com/Falconwatch/NLogAttributes

**Comment by 304NotModified** [comment]
Coukd you test with throwExceptions or throwConfigExceptions enabled?

**Comment by Falconwatch** [comment]
Same result

**Comment by 304NotModified** [comment]
thanks for testing! 

Could you help us with writing an unit test? It would boost the development. You could copy & edit an test in https://github.com/NLog/NLog/blob/master/tests/NLog.UnitTests/Config/RuleConfigurationTests.cs and send a PR

**Comment by Falconwatch** [comment]
I get a permission error trying to push to NLog repo, according to trouble shooting guide I need to be added as a collaborator: https://help.github.com/articles/error-permission-to-user-repo-denied-to-other-user/

**Comment by 304NotModified** [comment]
If you push to your own fork, you should create a PR.

**Comment by 304NotModified** [comment]
See https://github.com/NLog/NLog#contributing

**Comment by 304NotModified** [comment]
need any help on this?
