### ISSUE TITLE
unseal DatabaseTarget

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#1661]
Request: Remove `sealed`  from `DatabaseTarget`
as discussed at https://github.com/NLog/NLog/issues/98#issuecomment-249496857

Misiu commented:
> @304NotModified I've googled a bit and I found that there is no performance benefits from using sealed - http://stackoverflow.com/a/390627/965722 maybe this could be changed? This way it would be easier to build EntityFrameworkTarget

**Comment by 304NotModified** [comment]
there are a many targets `sealed`

https://github.com/NLog/NLog/search?l=csharp&p=8&q=sealed&utf8=%E2%9C%93

**Comment by 304NotModified** [comment]
@Misiu do we need to change some methods from `private` to `protected` for this?

**Comment by Misiu** [comment]
@304NotModified I'll download NLog and try to create new target by extending DatabaseTarget, I'll change methods if needed and get back to You.
