### ISSUE TITLE
FileTarget fails to write to primary log file when archive files do not match DateAndSequence numbering pattern

### ISSUE THREAD

**Issue by mzboray** [NLog/NLog#1664]
I am seeing that when DateAndSequence numbering option and the prior archive files do not match the DateAndSequence pattern then the FileTarget fails to write to the primary log file.

My scenario is that having used Date numbering pattern in a prior version of my application, I would like to change it to use DateAndSequence numbering. However the users previous archive files do match the date and sequence numbering, causing this issue to come up unless a work around is employed.

This was suggested as work around to issue #1645. Perhaps more generally FileTarget should not fail to log to the primary file when there problems with archiving.

**Type**: Bug
**NLog version**: 4.3.9
**Platform**: .Net 4.5 

Here is some code to reproduce the issue:

	static void Main(string[] args)
	{
		foreach(var file in Directory.EnumerateFiles(Environment.CurrentDirectory, "log*.txt"))
		{
			File.Delete(file);
		}

		// log file access times the same way as when this issue comes up.
		var oldTime = DateTime.Now.AddDays(-2);

		string logFile = "log.txt";
		File.WriteAllText(logFile, "some content");
		File.SetCreationTime(logFile, oldTime);
		File.SetLastWriteTime(logFile, oldTime);
		File.SetLastAccessTime(logFile, oldTime);

		string archiveFileName = $"log-{oldTime.ToString("yyyyMMdd")}.txt";
		File.WriteAllText(archiveFileName, "some archive content");

		// enable internal logging to the console
		InternalLogger.LogToConsole = true;
		InternalLogger.LogLevel = LogLevel.Error;

		// configure nlog
		var fileTarget = new FileTarget("file")
		{
			FileName = "log.txt",
			ArchiveEvery = FileArchivePeriod.Day,
			ArchiveFileName = "log-{#}.txt",
			ArchiveNumbering = ArchiveNumberingMode.DateAndSequence,
			ArchiveAboveSize = 50000,
			MaxArchiveFiles = 7
		};

		var rule = new LoggingRule("*", LogLevel.Trace, fileTarget);

		var config = new LoggingConfiguration();
		config.AddTarget(fileTarget);
		config.LoggingRules.Add(rule);

		LogManager.Configuration = config;

		// write
		var logger = LogManager.GetLogger("Main");
		logger.Info("Log message");

		string logContents = File.ReadAllText("log.txt");
		Console.WriteLine("Log contents: {0}", logContents);
	}

This produces the following output:

>2016-09-28 07:59:07.8775 Error Error has been raised. Exception: System.ArgumentOutOfRangeException: Length cannot be less than zero.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at NLog.Targets.FileTarget.TryParseDateAndSequence(String archiveFileNameWithoutPath, String dateFormat, FileNameTemplate fileTemplate, DateTime& date, Int32& sequence)
   at NLog.Targets.FileTarget.<FindDateAndSequenceArchives>d__18.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NLog.Targets.FileTarget.ArchiveByDateAndSequence(String fileName, String pattern, LogEventInfo logEvent)
   at NLog.Targets.FileTarget.DoAutoArchive(String fileName, LogEventInfo eventInfo)
   at NLog.Targets.FileTarget.TryArchiveFile(String fileName, LogEventInfo ev, Int32 upcomingWriteSize)
   at NLog.Targets.FileTarget.ProcessLogEvent(LogEventInfo logEvent, String fileName, Byte[] bytesToWrite)
   at NLog.Targets.FileTarget.Write(LogEventInfo logEvent)
   at NLog.Targets.Target.Write(AsyncLogEventInfo logEvent)
Log contents: some content

- What is the current result?
Writing to the primary log file fails.
- What is the expected result?
Writing to the primary log file should not fail.
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
Yes see the repro code output.
- Are there any work arrounds? 
Yes. Removing the old archive files or choosing a different naming pattern for archive files will resolve the issue.
- Is there a version in which it did worked? Not that I am aware of.
- Can you help us by writing an unit test? If the repro code, is not enough I can write a test.

**Comment by 304NotModified** [comment]
This should be fixed in the master. I will write an unit test for it

**Comment by 304NotModified** [comment]
I wrote an unit test that failed in 4.3.7. (and probable also 4.3.9). It should work in 4.3.10: https://github.com/NLog/NLog/issues/1664

**Comment by 304NotModified** [comment]
> FileTarget should not fail to log to the primary file when there problems with archiving.

Agree with that, #1697

**Comment by 304NotModified** [comment]
Fixed and live, NLog 4.3.10: https://www.nuget.org/packages/NLog/4.3.10
