### ISSUE TITLE
NLOG Database Target Logs are dropping when writing more than 5000 logs consecutively with async true

### ISSUE THREAD

**Issue by venkatesupunugupati** [NLog/NLog#1665]
NLOG Database Target Logs are dropping when writing more than 6000 logs consecutively with async true. I am not sure this is bug (or) known limitation.

**NLOG  Config:**

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

  <!-- 
  See http://nlog-project.org/wiki/Configuration_file 
  for information on customizing logging rules and outputs.
   -->
  <targets async="true">
    <!-- add your targets here -->
    <target name="f" xsi:type="File"
       layout="${longdate} ${logger} ${level} ${message} ${exception:format=tostring}"
       fileName="${basedir}/logs/current.log"
       archiveFileName="${basedir}/logs/archive.{#}.log"
       archiveEvery="Day"
       archiveNumbering="Rolling"
       maxArchiveFiles="7"
       concurrentWrites="true"
       keepFileOpen="true"
       autoFlush="true"
       encoding="iso-8859-2" />

      <target xsi:type="Database" name="db" keepConnection="false">
        <!-- SQL command to be executed for each entry -->
        <commandText>INSERT INTO [LogTable](time_stamp, Level, Logger,Message) VALUES(getutcdate(),@level, @logger,@msg)</commandText>
        <!-- parameters for the command -->
        <parameter name="@msg" layout="${message}" />
        <parameter name="@level" layout="${level}" />
        <parameter name="@logger" layout="${logger}" />

        <!-- connection string -->
        <dbProvider>System.Data.SqlClient</dbProvider>
        <connectionString>server=.\SQLEXPRESS;database=NLOGDB;integrated security=sspi</connectionString>
      </target>
   
  </targets>

  <!-- Add your logging rules here.  -->
  <rules>
    <logger name="*" minlevel="Info" writeTo="f" />
    <logger name="*" minlevel="Info" writeTo="db" />
  </rules>

</nlog>
```

**C# Code:**

```c#
 static void Main(string[] args)
        {
            Logger logger = LogManager.GetCurrentClassLogger();          
            for (int i = 0; i < 15000; i++)
            {
                logger.Error("sample log message"+i);
                //if(i%1000 == 0)
                //LogManager.Flush();
            }           
            Console.WriteLine("Completed");
      

}
```

NLog Configuration won't allow any flush for targets but file target it will allow flush.
if i use LogManager to flush then it is working database target as Log Manager works with all Targets.

**Comment by 304NotModified** [comment]
Hi, this is by design and configurable. See https://github.com/NLog/NLog/wiki/AsyncWrapper-target#async-attribute-will-discard-by-default

**Comment by venkatesupunugupati** [comment]
Thanks for quick response.. Appreciate your Efforts..

Changed NLog Config:

<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

  
  <targets>
      
    
    

    <target xsi:type="AsyncWrapper" name="dbwrapper" queueLimit="20000" timeToSleepBetweenBatches="50" batchSize="100" overflowAction="Discard">
      <target xsi:type="Database">
        
        <commandText>INSERT INTO [LogTable](time_stamp, Level, Logger,Message) VALUES(getutcdate(),@level, @logger,@msg)</commandText>
        
        <parameter name="@msg" layout="${message}" />
        <parameter name="@level" layout="${level}" />
        <parameter name="@logger" layout="${logger}" />

        
        <dbProvider>System.Data.SqlClient</dbProvider>
        <connectionString>server=.\SQLEXPRESS;database=NLOGDB;integrated security=sspi</connectionString>
      </target>
    </target>
   
  </targets>

  
  <rules>
    
    <logger name="*" minlevel="Info" writeTo="dbwrapper" />
  </rules>

</nlog>

I tried that previously also...Even now also i tried, It is not working consistently. It will work 1 in 20 times..Do you any idea about this?. All the examples of AsyncWrapper applied to File Target not to Database Target. I am interested in Database Target. do you got chance to try AsyncWrapper with Database Target?.

**Comment by 304NotModified** [comment]
Has your question being answered?

**Comment by venkatesupunugupati** [comment]
Yes..Thanks for the response..
