### ISSUE TITLE
Add MaximumKilobytes property for eventlog

### ISSUE THREAD

**Issue by Sing303** [NLog/NLog#1673]
It is impossible to change the setting MaximumKilobytes in eventlog. Please add this parameter

**Comment by 304NotModified** [comment]
Could you explain your question?

There is a `MaxMessageLength` property on the EventLog, but that is not what you mean?

**Comment by Sing303** [comment]
No, I want to change this property
https://msdn.microsoft.com/en-us/library/system.diagnostics.eventlog.maximumkilobytes(v=vs.110).aspx

**Comment by 304NotModified** [comment]
You could do that with c#  of course. But you like to configure this from the XML config? How would the config look like?

**Comment by Sing303** [comment]
Something like this
```
<targets>
  <target xsi:type="EventLog"
          name="String"
          layout="Layout"
          machineName="String"
          source="Layout" 
          category="Layout"
          eventId="Layout"
          log="String"
          maxMessageLength="Integer"
          maximumKilobytes="Integer"/>
</targets>
```

**Comment by 304NotModified** [comment]
And then we set the `maximumKilobytes` on first usage? (init)

**Comment by Sing303** [comment]
Yes exactly

**Comment by ajitpeter** [comment]
I  would like to implement this feature, I hope somebody could guide me through the process.

**Comment by 304NotModified** [comment]
Cool!

Will give some more info tomorrow!

**Comment by 304NotModified** [comment]
Firstly, please read https://github.com/NLog/NLog/blob/master/CONTRIBUTING.md

1. start with the NLog.netfx45.sln, in folder src

2. You need a new property on [EventLogTarget](https://github.com/NLog/NLog/blob/master/src/NLog/Targets/EventLogTarget.cs) (probably Layout type) 
3. Use the property OR in `Write` or in `Install` (latter if is only needed once or admin rights needed). Use YourProperty.Render(event) (and maybe `int.TryParse`)
4. Add new tests in [`EventLogTargetTests`](https://github.com/NLog/NLog/blob/master/tests/NLog.UnitTests/Targets/EventLogTargetTests.cs)
5. If you add new files (not this case), sync the .sln files, see https://github.com/NLog/NLog/blob/master/CONTRIBUTING.md#sync-projects

If you have more questions, let us know!

**Comment by ajitpeter** [comment]
Thanks for information. I will start on it and surely will be in contact if I face any issues/questions.

**Comment by ajitpeter** [comment]
I have made a few changes on my branch (https://github.com/ajitpeter/NLog/commit/bc44f79df5d0913042904ca2823c73af12e35309) thought of getting an opinion from @304NotModified on whether I am going in the right direction. I do apologise if it is wildly different from what you meant. If it is looks right I had a question on whether MaxKilobytes should have a default value??

**Comment by 304NotModified** [comment]
Please send a PR (pull request) :)

**Comment by 304NotModified** [comment]
Fixed in #1810

**Comment by 304NotModified** [comment]
docs added to https://github.com/NLog/NLog/wiki/Eventlog-target

**Comment by 304NotModified** [comment]
Added in 4.4.10 and the release is queued. Will be online in a few hours!

thanks @ajitpeter !

**Comment by ajitpeter** [comment]
Thanks Julian. That was my first pr.
