### ISSUE TITLE
Upgrade code/projects to C#7 / vs2017

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#1699]
Upgrade projects and code:
- [ ] use `?.`
- [x] use lambda expressions - https://github.com/NLog/NLog/pull/2361
- [x] prefix privates with `_`  - core: https://github.com/NLog/NLog/pull/2327
- and others
- no functional changes.

**Comment by ie-zero** [comment]
I would like very much to start working on this but I cannot figure out what needs to be done on the configuration of AppVeyor to accept C# 6 syntax. 

I tried the adding the following in various combinations
```os: Visual Studio 2015```

```
install:
  - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH% 
```

and 
```image: Visual Studio 2015```

Would it be possible for someone more experienced with MSBuild to assist please?

PS. If someone would like to see what it has been attempted see at https://github.com/ie-zero/NLog/tree/UpgradeCode_FileInfoExt

**Comment by 304NotModified** [comment]
Strange, I have more c#6 projects building. Will look at it soon.

**Comment by 304NotModified** [comment]
The msbuild project needed a change. (horrible thing).

See https://github.com/NLog/NLog/commit/98af2d994fbc938f2b4baaa7ec06c82b24a0bea0  and 

https://ci.appveyor.com/project/nlog/nlog/build/4.4.4040

**Comment by 304NotModified** [comment]
NB: We have to be sure that this won't give use many conflicts on the coreCLR branch

**Comment by ie-zero** [comment]
Nice one!

**Comment by 304NotModified** [comment]
@ie-zero are you using Resharper? A lot of these points could be done for the full project in a few clicks.

**Comment by ie-zero** [comment]
No I do not. I will leave it to someone else than.

**Comment by 304NotModified** [comment]
Or get a Free OSS license of Resharper (https://www.jetbrains.com/buy/opensource/?product=resharper)

You are doing great work @ie-zero ! I you like it, I could add you to the NLog organization!

**Comment by 304NotModified** [comment]
This is done :)
