### ISSUE TITLE
4.3.10 Does not log to console under Mono

### ISSUE THREAD

**Issue by jaebird** [NLog/NLog#1704]
Hi! Thanks for reporting this feature/bug/question! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

For .NET Core users, please check the platform support: https://github.com/NLog/NLog/wiki/platform-support

**Type** (choose one):
- Bug

**NLog version**: 4.3.10

**Platform**: Mono 4 (Ubuntu 64bit)

In case of a BUG:

- What is the current result? Doesn't log to Console or ColoredConsole
- What is the expected result? Log to console
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)? No
- Please post full exception details (message, stacktrace, inner exceptions): N/A
- Are there any work arrounds? yes/no: Revert to 4.3.9
- Is there a version in which it did worked? 4.3.9
- Can you help us by writing an unit test? N/A?

It worked fine under 4.3.9 and stopped as soon as I updated to 4.3.10. Log files are still being created.

**Comment by snakefoot** [comment]
Sounds like you are not using the MONO-build. But workaround is to add detectConsoleAvailable="false" to your console-target-configuration.

**Comment by snakefoot** [comment]
How do you want to solve this?
- Add a IsMono-check (Type.GetType("Mono.Runtime") != null) to IsConsoleAvailable ? (Not sure how .NET Core/Standard etc. works out)
- Change default-value of DetectConsoleAvailable to false?

**Comment by 304NotModified** [comment]
Yes, one of those ;)

Try to improve the detection, otherwise default to false :)

**Comment by jaebird** [comment]
Thanks for the swift response.

**Comment by 304NotModified** [comment]
This has been fixed in NLog 4.3.11: https://www.nuget.org/packages/NLog/4.3.11

Thanks @snakefoot !
