### ISSUE TITLE
Log the payload the NLogViewer/network target to the InternalLogger

### ISSUE THREAD

**Issue by PureKrome** [NLog/NLog#1708]
**Type**: Question
**NLog version**: 4.3.10
**Platform**: .Net 4.5 
**Current NLog config**

``` xml

<?xml version="1.0" encoding="utf-8"?>

<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      throwExceptions="true"
      internalLogFile="c:\temp\nlog-debug-log.txt"
      internalLogLevel="Trace"
      >

  <!-- NLog example: https://github.com/nlog/nlog/wiki/Examples -->
  <targets async="true">
    <target name="Sentinel"
            xsi:type="NLogViewer"
            address="udp://127.0.0.1:9999"
            layout="ssss-seeing-if-this-overrides"/>
  </targets>

  <rules>
    <logger name="*" minlevel="Trace" appendTo="Sentinel" />
  </rules>

</nlog>
```

Hi 👋 
   I'm trying to figure out a way to see the payload that is sent over the wire when using an `NLogViewer` target. My reasoning is that we use a viewer called Sentinal and I'm starting to use properties to attach more meta data, per log entry. (We use Serilog + Serilog.sinks.nlog right now).

If i can see the exact payload that is sent over the wire to sentinal I can then determine if it's worth my time in trying to fix their application to handle dynamic columns (1 per property, for example) or maybe flatten the properties into the end of the rendered Message.

So - is there an easy way to see this data? 

I'm used to using FIDDLER for snooping this type of info but this isn't HTTP traffic.

NOTE: If you noticed, i've added a `internalLogLevel="Trace"` attribute to see if the internal tracing might output/dump the payload context, but it doesn't. (I don't put that on any of my nlog files .. just this R&D).

cheers!

**Comment by 304NotModified** [comment]
It looks like this isn't logged to the InternalLogger. We could add it in the next version. The code should added to the `NetworkTarget`

**Comment by PureKrome** [comment]
Oh nice then :)

1) would an example be provided if it's added, in the next release?
2) could this issue be updated (with a link to a PR) if it's added in, please?

**Comment by 304NotModified** [comment]
> 1) would an example be provided if it's added, in the next release?

Do you mean, how to enable? That will be ` internalLogLevel="Trace"`

**Comment by PureKrome** [comment]
I said
>1) would an example be provided if it's added, in the next release?

and you said
> Do you mean, how to enable? That will be internalLogLevel="Trace"

and I was actually _really_ trying to say ..

would an example be provided that uses this `NetworkTarget` if that is the way we will need to see this payload data. Otherwise, what does `NetworkTarget` have to do with it?

**Comment by 304NotModified** [comment]
Sorry about the confusion.

NLogViewer inherits from NetworkTarget, so if we log at NetworkTarget level, this is fixed for NLogViewer :)

**Comment by 304NotModified** [comment]
I have added some internal logs in NLog 4.3.11. https://www.nuget.org/packages/NLog/4.3.11

**Comment by PureKrome** [comment]
Thank you kindly!
