### ISSUE TITLE
UnauthorizedAccessException when trying to create a simple FileTarget on Android

### ISSUE THREAD

**Issue by mikegottlieb** [NLog/NLog#1709]
**Type** (choose one):
- Bug

**NLog version**:
4.3.10

**Platform**: 
Xamarin Android (tested on device running Nougat, works on emulator running Marshmallow)

**Current NLog config** (xml or C#, if relevant)

``` c#
NLog.Config.LoggingConfiguration config = new NLog.Config.LoggingConfiguration();
NLog.Targets.FileTarget f = new NLog.Targets.FileTarget("f");           
```

In case of a BUG:
- What is the current result?

```
System.UnauthorizedAccessException
Access to the path "/" is denied.
 at System.IO.Directory.GetFileSystemEntries (System.String path, System.String searchPattern, System.IO.FileAttributes mask, System.IO.FileAttributes attrs) [0x00050] in /Users/builder/data/lanes/3819/96c7ba6c/source/mono/mcs/class/corlib/System.IO/Directory.cs:496 
  at System.IO.Directory.GetFiles (System.String path, System.String searchPattern) [0x00000] in /Users/builder/data/lanes/3819/96c7ba6c/source/mono/mcs/class/corlib/System.IO/Directory.cs:296 
  at NLog.Config.ConfigurationItemFactory.BuildDefaultFactory () [0x00084] in <dbf750d0ee3b4193a151c4e9f00bd425>:0 
  at NLog.Config.ConfigurationItemFactory.get_Default () [0x00007] in <dbf750d0ee3b4193a151c4e9f00bd425>:0 
  at NLog.Layouts.Layout.FromString (System.String layoutText) [0x00000] in <dbf750d0ee3b4193a151c4e9f00bd425>:0 
  at NLog.Layouts.Layout.op_Implicit (System.String text) [0x00000] in <dbf750d0ee3b4193a151c4e9f00bd425>:0 
  at NLog.Targets.TargetWithLayout..ctor () [0x00006] in <dbf750d0ee3b4193a151c4e9f00bd425>:0 
  at NLog.Targets.TargetWithLayoutHeaderAndFooter..ctor () [0x00000] in <dbf750d0ee3b4193a151c4e9f00bd425>:0 
  at NLog.Targets.FileTarget..ctor () [0x00016] in <dbf750d0ee3b4193a151c4e9f00bd425>:0 
  at NLog.Targets.FileTarget..ctor (System.String name) [0x00000] in <dbf750d0ee3b4193a151c4e9f00bd425>:0 
  at Droid.MainActivity.ConfigureLogging () [0x00023] in 
/Droid/MainActivity.cs:143 
  at Droid.MainActivity.OnCreate (Android.OS.Bundle bundle) [0x00002] 
/Droid/MainActivity.cs:77 
  at Android.Support.V4.App.FragmentActivity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x00011] in <27c17fe440cf491ba8255bcefade6e02>:0 
  at (wrapper dynamic-method) System.Object:b5e891a4-6415-4583-b917-ff0357faa071 (intptr,intptr,intptr)
```
- What is the expected result?

Not an exception
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?

Not possible
- Please post full exception details (message, stacktrace, inner exceptions)

See above
- Are there any work arrounds? yes/no

No
- Is there a version in which it did worked? 

No

**Comment by UgurAldanmaz** [comment]
Hi @mikegottlieb.

Thanks for reporting.

Did you give the permission in manifest file?

**Comment by mikegottlieb** [comment]
@UgurAldanmaz My app has the WRITE_EXTERNAL_STORAGE permission. I've been trying to figure out if something changed in Nougat and I might need another permission or something.

Also it seems kind of strange that just instantiating a FileTarget immediately triggers the error.

**Comment by mikegottlieb** [comment]
I just found this in the Nougat behavior changes description.

> Legacy applications may end up with an unaccessible path when accessing COLUMN_LOCAL_FILENAME. Apps targeting Android 7.0 or higher trigger a SecurityException when attempting to access COLUMN_LOCAL_FILENAME.

[https://developer.android.com/about/versions/nougat/android-7.0-changes.html](url)

I'm not sure if this is the issue, but it is interesting.

**Comment by UgurAldanmaz** [comment]
Could you post your config file? I want to check the fileName. Also I will write some tests that using your configuration. We may need to evaluate another conditions. If so, I will add appropriate unit tests to the NLog.

Thanks!

**Comment by mikegottlieb** [comment]
I wasn't using a config file. At first I was, but I was getting the same exception trying to load the config. I assumed it had to do with reading the config, which I now believe is incorrect, so I switched to do the config entirely in code.

The 2 lines of C# I posted in the original post were the entirety of my config code that was execute prior to the error.

Thanks for looking into this!

**Comment by 304NotModified** [comment]
Is seems that the filename parameter of the target isn't set?

**Comment by mikegottlieb** [comment]
Correct, but that is because it cannot be until after instantiated. Later in the code I set a file name as well as the rest of the properties, but it doesn't matter because execution never gets that far.

**Comment by UgurAldanmaz** [comment]
It seems that error is not about FileTarget and its configuration. It is about calling the `Directory.GetFiles` method from the [ConfigurationItemFactory.BuildDefaultFactory](https://github.com/NLog/NLog/blob/43eca983676d87f1d9d9f28872304236393827ba/src/NLog/Config/ConfigurationItemFactory.cs#L258). Call stack of FileTarget instantiation hits the `ConfigurationItemFactory.BuildDefaultFactory`.


See error log at the first post. First code line at the error log refers the Mono source code:

` at System.IO.Directory.GetFileSystemEntries (System.String path, System.String searchPattern, System.IO.FileAttributes mask, System.IO.FileAttributes attrs) [0x00050] in /Users/builder/data/lanes/3819/96c7ba6c/source/mono/mcs/class/corlib/` **System.IO/Directory.cs:496**

[Look at mono source code, line 496](https://github.com/mono/mono/blob/master/mcs/class/corlib/System.IO/Directory.cs#L496). Error occured there, so that FileTarget cannot be instantiated.

Actually we need to know what is the value of this line:
[`var assemblyLocation = Path.GetDirectoryName(new Uri(nlogAssembly.CodeBase).LocalPath);`](https://github.com/NLog/NLog/blob/43eca983676d87f1d9d9f28872304236393827ba/src/NLog/Config/ConfigurationItemFactory.cs#L246)
Because `Directory.GetFiles` method executing with the `assemblyLocation`. Probably this line returns '/' which error log says it is unauthorized. 

I do not know what means of '/' path for Android. Anybody know? Maybe we need to consider different way to lookup NLog assemblies for Android.

**Comment by mikegottlieb** [comment]
'/' means the root of the filesystem which is definitely off limits unless your Android device is rooted.

**Comment by 304NotModified** [comment]
Nice findings @UgurAldanmaz !

**Comment by UgurAldanmaz** [comment]
Thanks @304NotModified :)

So, how unit tests successfully work for Xamarin build? Maybe there is an exceptional case for this bug report. If everytime `ConfigurationItemFactory` is looking to '/' path for NLog assemblies, then it should fail for the same reason.

**Comment by xklech** [comment]
Any progress on this issue? Our customers already started to complain about application startup crash. We need to solve this fast. Thank you.

**Comment by 304NotModified** [comment]
Not yet. Thanks for bumping, will try to look at it this evening.

**Comment by 304NotModified** [comment]
Or do have a solution @UgurAldanmaz ?

**Comment by xklech** [comment]
From my observation this exception happens when instantiating 

var fileTarget = new FileTarget();

When I comment this line out, application won't crash.
And happens only in Release mode. In debug mode application won't crash. Android 7.0, 7.1.

**Comment by 304NotModified** [comment]
It will also crash if you init another type of target, right?

**Comment by xklech** [comment]
You are absolutely right, `var consoleTarget = new ConsoleTarget();` also crashes application.

**Comment by 304NotModified** [comment]
Thanks for the confirm! 

Looking at this now

**Comment by 304NotModified** [comment]
This should be fixed (I don't have Xamarin apps to test), in NLog 4.3.11: https://www.nuget.org/packages/NLog/4.3.11

Please confirm! Thx!

**Comment by xklech** [comment]
@304NotModified I have just tested your fix, and it is awesome! No crashes, logs are arriving. Everything is working correctly. Thank you very much.

**Comment by 304NotModified** [comment]
\0/ thanks for the confirm!

**Comment by 304NotModified** [comment]
Also thanks to @UgurAldanmaz for checking the code. Really helped me :)

**Comment by UgurAldanmaz** [comment]
You are welcome @304NotModified. And thanks to you for fixing. 👍

**Comment by UgurAldanmaz** [comment]
By the way, I am still worried about that:

> So, how unit tests successfully work for Xamarin build? Maybe there is an exceptional case for this bug report. If everytime ConfigurationItemFactory is looking to '/' path for NLog assemblies, then it should fail for the same reason.

**Comment by 304NotModified** [comment]
> So, how unit tests successfully work for Xamarin build?

No, they can't run on a CI environment.

**Comment by UgurAldanmaz** [comment]
CI enviroment cannot run any Xamarin tests or only this case?

Is this why we did not notice this problem?

**Comment by 304NotModified** [comment]
> CI enviroment cannot run any Xamarin tests or only this case?

First one, so can't run them on e.g. AppVeyor or Travis. Really annoying. AFAIK this is still not possible and not expected in the future.

> Is this why we did not notice this problem?

Yes indeed.

**Comment by UgurAldanmaz** [comment]
> First one, so can't run them on e.g. AppVeyor or Travis. Really annoying. AFAIK this is still not possible and not expected in the future.

So we need to find a way to run tests of not supported builds. Would you like to follow this subject with a new issue?

**Comment by 304NotModified** [comment]
https://github.com/NLog/NLog/issues/1186 ;)

**Comment by SlyNet** [comment]
This code 

```
var pathToLocalDirectory = Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments);
var fileName = Path.Combine(pathToLocalDirectory, "Logs", "${shortdate}.log");
var fileTarget = new FileTarget("logFile")
            {
                FileName = fileName,
                Layout = "${longdate}[${logger}][${level}][${message}][${onexception:${exception:format=tostring}|${stacktrace}}]"
            };
```
Still crashes with exception `System.UnauthorizedAccessException: Access to the path "/" is denied.` on version 4.3.11. Why does it even tries to access that path?

**Comment by mikegottlieb** [comment]
Are you sure this is fixed? I'm still see this in my logcat and I'm on NLog 4.4.1
```
01-16 13:23:22.060: I/mono-stdout(5353): 2017-01-16 13:23:21.6398 Error Error has been raised. Exception: System.UnauthorizedAccessException: Access to the path "/" is denied.
01-16 13:23:22.061: I/mono-stdout(5353):   at System.IO.Directory.GetFileSystemEntries (System.String path, System.String searchPattern, System.IO.FileAttributes mask, System.IO.FileAttributes attrs) [0x00062] in <6c47f90075884643a22be3a6d1146333>:0 
01-16 13:23:22.061: I/mono-stdout(5353):   at System.IO.Directory.GetFiles (System.String path, System.String searchPattern) [0x00000] in <6c47f90075884643a22be3a6d1146333>:0 
01-16 13:23:22.061: I/mono-stdout(5353):   at NLog.Config.ConfigurationItemFactory.BuildDefaultFactory () [0x00090] in <5f9d52feaca84820bedbbaf33b55f89c>:0 
```

**Comment by 304NotModified** [comment]
Is throw exceptions=true ? Then it's correct you're seeing that exception. 

 Also please check the internal log

**Comment by yeoupooh** [comment]
I'm still see this error on NLog 4.4.9 (Nexus 9 Android 7.0).
`Info (30546) / MonoDroid: UNHANDLED EXCEPTION:
Info (30546) / MonoDroid: NLog.NLogConfigurationException: Exception when parsing assets/nlog.config.  ---> System.UnauthorizedAccessException: Access to the path "/" is denied.
Info (30546) / MonoDroid:   at System.IO.Directory.GetFileSystemEntries (System.String path, System.String searchPattern, System.IO.FileAttributes mask, System.IO.FileAttributes attrs) [0x00062] in <74df0bdaedce44249d38e4e3d2c69845>:0 
Info (30546) / MonoDroid:   at System.IO.Directory.GetFiles (System.String path, System.String searchPattern) [0x00000] in <74df0bdaedce44249d38e4e3d2c69845>:0 
Info (30546) / MonoDroid:   at NLog.Config.ConfigurationItemFactory.BuildDefaultFactory () [0x000a8] in <04c71610dbcd4e68b2233166e09de556>:0 
Info (30546) / MonoDroid:    --- End of inner exception stack trace ---
`

**Comment by 304NotModified** [comment]
is this error in the internal log?
