### ISSUE TITLE
how to route System.Diagnostics.TraceSource logs through NLog in .NET Core

### ISSUE THREAD

**Issue by guilhermelabigalini** [NLog/NLog#1711]
**Type**:  Question
**NLog version**: 4.4.0-betaV15
**Platform**: .NET Core 

Hi, is there anyway to route System.Diagnostics.TraceSource logs through NLog in .NET Core? Using the NLog for .Net 4.5 we could setup NLog.NLogTraceListener in the app.config file as remonstrated in this post http://nlog-project.org/2010/09/02/routing-system-diagnostics-trace-and-system-diagnostics-tracesource-logs-through-nlog.html , but we dont have app.config in .net core anymore.

I've setup libraries that are outputting logs with TraceSource and I would like to route it to NLog targets.

Suggestions are welcome.

Thanks!

**Comment by 304NotModified** [comment]
Good question. Too bad I have no idea as I don't use .NET core a lot yet. 

I think this question will earlier get answered on StackOverflow

**Comment by 304NotModified** [comment]
I see you did :)

http://stackoverflow.com/questions/40052355/how-to-route-system-diagnostics-tracesource-logs-through-nlog-in-net-core

**Comment by guilhermelabigalini** [comment]
Yeah, hope we received some feedback :)

**Comment by guilhermelabigalini** [comment]
There are differences between TraceSource from .net core/regular .net. In core, TraceSource is always loaded without any listener: 
https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.TraceSource/src/System/Diagnostics/TraceSource.cs#L72-L86

While in regular .net it reads the listeners from app.config file [as we can see here](https://github.com/Microsoft/referencesource/blob/master/System/compmod/system/diagnostics/TraceSource.cs#L71-L107)

Most of applications/libs that use TraceSource, create it expecting the listeners to be attached automatically:
 
`var logger=new TraceSource("LibraryName");`

It seems that we can only include another listener in TraceSource if we have access to the instance of that class, by adding a new element on the Listeners collection, which may not be possible without impacting applications/libs that rely on TraceSource for logging....

**Comment by 304NotModified** [comment]
Is there something we could do in NLog here?

**Comment by guilhermelabigalini** [comment]
I don't think there is anything that could be done at this point, based on the last investigation over  TraceSource code, currently its not allowing listeners from configuration, just by code on the target object instance. I think we can close this issue.

Thanks again.

**Comment by 304NotModified** [comment]
Thanks for the feedback!
