### ISSUE TITLE
MDC Unsafe to use in ASP.Net?

### ISSUE THREAD

**Issue by ShaneCourtrille** [NLog/NLog#1714]
Question

**NLog version**: All?

**Platform**:  ASP.Net

Based on my research into storing things in a thread safe manner (and an urge to throw my hands in the air and just use NLog MDC in the background for now) I took a look into MDC and it appears to have a problem when used in ASP.Net.  

The problem is caused by the fact that ASP.Net will switch the thread that is handling a request at a specific point.  Because of this it's recommended that you use CallContext for non-ASP.Net code and HttpContext.Current.Items for any code running in ASP.Net but when I read the MDC code it only uses CallContext.

Am I missing something that makes MDC safe to use or are there any guidelines on how to use it safely within ASP.Net?

A few sources:
http://www.lhotka.net/weblog/ASPNETThreadSwitching.aspx
http://piers7.blogspot.ca/2005/11/threadstatic-callcontext-and_02.html

Thanks

**Comment by 304NotModified** [comment]
If you mean with "safe", "async-safe", then you should use the MDLC instead of the MDC

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, let us know!

**Comment by HowardHoffman** [comment]
There is a real issue in the MDLC functionality, when used in ASP.NET.   This blob post (not by me or anyone in our organization; a colleague in our group found it) discusses w/ examples:  https://tpodolak.com/blog/2016/07/05/nlog-tracking-flow-of-requests-using-mappeddiagnosticslogicalcontext/.

Our case is slightly different:  we have code in Global.asax.cs `Application_BeginRequest` / `Application_EndRequest` that creates a `correlationId` and calls `MappedDiagnosticsLogicalContext.Set("correlationIdKey", value);` during `Application_BeginRequest`.  Code in `Application_EndRequest` logs the "end of the request" as a marker.  That log statement sometimes emits a value for correlationIdKey and sometimes does not.  This pattern is reproducible.

**Comment by snakefoot** [comment]
See also: https://github.com/NLog/NLog/issues/2158#issuecomment-306874240 (Use `${aspnet-item}` instead)
