### ISSUE TITLE
Save running configuration

### ISSUE THREAD

**Issue by msanchez71** [NLog/NLog#1715]
Hi! Thanks for reporting this feature/bug/question! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

For .NET Core users, please check the platform support: https://github.com/NLog/NLog/wiki/platform-support

**Type** (choose one):
- Question
  Is there a way to (re)configure programmatically and save the new resulting configuration to nlog.config or another file?  Any way to save it and reload it would be sufficient.

**NLog version**: 4.3.6

**Platform**:  .Net 4.5 
**Current NLog config** both??

``` xml
<nlog>
  <targets>
  </targets>
  <rules>
  </rules>
</nlog>

```

In case of a BUG:
- What is the current result?
- What is the expected result?
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
- Please post full exception details (message, stacktrace, inner exceptions)
- Are there any work arrounds? yes/no
- Is there a version in which it did worked? 
- Can you help us by writing an unit test?

in case of a FEATURE REQUEST:
- Why do we need it?
- An example of the XML config, if relevant.

**Comment by UgurAldanmaz** [comment]
Hi @msanchez71,

> Question Is there a way to (re)configure programmatically and save the new resulting configuration to nlog.config or another file? Any way to save it and reload it would be sufficient.

Yes, you can reload the configuration file [by `autoReload` option.](https://github.com/NLog/NLog/wiki/Configuration-file#automatic-reconfiguration)

Actually your question is not clear. 
* What do you mean by _programmatically_? 
* What do you mean by _save_?

When your configuration file changes?

**Comment by msanchez71** [comment]
Hello,

I am sorry I was not clear.  I want to make changes to the NLog config at runtime using the NLog.Config Namespace classes.  Then I need persist those changes to a file, preferably to the NLog.config file but any file would be OK.

Thanks in advance,

Mike

**Comment by UgurAldanmaz** [comment]
Ok, I get it now. Unfortunately it is not possible yet. But it would be useful feature. 

If you want, you can try to develop this feature and make a pull request to us.

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, let us know!

**Comment by TsakiDev** [comment]
Are there any updates on this?

**Comment by 304NotModified** [comment]
@TsakiDev please open a new issue, or if it's a question, preferable on stackoverlfow.
