### ISSUE TITLE
Mail target async batches not seperated by newlines

### ISSUE THREAD

**Issue by gguillen** [NLog/NLog#1717]
Hi! Thanks for reporting this feature/bug/question! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

For .NET Core users, please check the platform support: https://github.com/NLog/NLog/wiki/platform-support

**Type** (choose one): Question

**NLog version**: 4.3.10

**Platform**: .Net 4.6.2

**Current NLog config** (xml or C#, if relevant)

```xml
<nlog>
  <targets async="true">
     <target xsi:type="Mail"
            name="mailLog"
            layout="..."
            subject="subject"
            to="someone@somewhere.com"
            from="somemachine@somewhere.com"
            smtpServer="smtp.somewhere.com" />
  </targets>
  <rules>
  </rules>
</nlog>

```

I have several different systems sending mail that are using the async modifier on the targets section.  Everything works just fine, but when emails come through with a batch of messages, they run up on each other (i.e. no newlines between the end of one and the beginning of the next).  I know I could just add newlines at the end of the message, but these messages are also being logged to a database and I dont want to be saving those extra characters for every message.

This isnt a big issue, just wondering if there is a way to make this better.

Thanks!

**Comment by 304NotModified** [comment]
You could add ${newline} to the layout? Or am I missing something?

**Comment by gguillen** [comment]
Like I said, I could just add newlines at the end of the layout, but since these exact same messages are also being logged to the database, and the logging is pretty verbose, I don't want to save the extra 2 bytes for hundreds of thousands of messages.  If that is the only solution, I would rather just have the emails as they are since we only log to email above a specific level.  However, the database will usually log all levels.

**Comment by 304NotModified** [comment]
How are the messages send to the database? Not with the database target? Is this the full config?

So info is missing as mail <> database

**Comment by gguillen** [comment]
Its one of those days... I feel stupid now... I have no idea why I was thinking the layout was shared between the two... added 2 newlines to the email layout and all is good.  Nothing to see here...  Carry on...

**Comment by 304NotModified** [comment]
Lol
