### ISSUE TITLE
Write exceptions in InvariantCulture to log file

### ISSUE THREAD

**Issue by habakuk007** [NLog/NLog#172]
If you ever got a log file from Japan you got the problem.

Exceptions (and other strings that come from a resource) should be written to the log file with the CultureInfo.InvariantCulture.

**Comment by srollinet** [comment]
This is an old issue but it seems the fix done for https://github.com/NLog/NLog/issues/152 doesn't work.

The problem is when using a layout like `${exception:format=tostring}` the exception is written in the `CurrentUICulture`. It would be great to have the option to set the CultureInfo to avoid this problem.

This behavior occurs even when setting `useInvariantCulture="true"`

Now the workaround is to switch the `CurrentUICulture` before each call to the logger and restore it after.

**Comment by 304NotModified** [comment]
Hi @srollinet,

I think https://github.com/NLog/NLog/issues/1528 is related? See also PR: https://github.com/NLog/NLog/pull/1556

**Comment by srollinet** [comment]
Hi @304NotModified ,

I'm not sure it is the same. What I expect is the possibility to have exactly the same exception message + stack trace regardless of the CurrentUICulture

Something like that:

```
[Fact]
public void ExceptionTest()
{
    var target = new MemoryTarget {Layout = @"${exception:format=tostring}"};
    SimpleConfigurator.ConfigureForTargetLogging(target);
    var logger = LogManager.GetCurrentClassLogger();

    try
    {
        throw new InvalidOperationException();
    }
    catch (Exception ex)
    {
        Thread.CurrentThread.CurrentUICulture = new CultureInfo("en-US");
        logger.Error(ex, CultureInfo.InvariantCulture, "");

        Thread.CurrentThread.CurrentUICulture = new CultureInfo("de-DE");
        logger.Error(ex, CultureInfo.InvariantCulture, "");

        Assert.Equal(target.Logs[0], target.Logs[1]);
    }
}
```

**Comment by 304NotModified** [comment]
@srollinet I added the unit tests to #1556 but it works for me locally (let see what appVeyor tells)

#1556 didn't changed the ExceptionLayoutRenderer, so it also works on master then. 

Can you give an example of the visual differences you get? (please do a toString on `target.Logs[0]` and `target.Logs[1]` and post them here

**Comment by srollinet** [comment]
Tested with V4.3.6 (oops, I haven't seen that #1556 is not part of this release) so maybe the problem is simply here...

```
System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at TestsSRO.ExceptionCultureTest.ExceptionTest() in C:\Users\sro\Documents\Visual Studio 2015\Projects\TestsSRO\TestsSRO\ExceptionCultureTest.cs:line 22
```

```
System.InvalidOperationException: Operation is not valid due to the current state of the object.
   bei TestsSRO.ExceptionCultureTest.ExceptionTest() in C:\Users\sro\Documents\Visual Studio 2015\Projects\TestsSRO\TestsSRO\ExceptionCultureTest.cs:Zeile 22.
```

**Comment by 304NotModified** [comment]
this is master (works):
![image](https://cloud.githubusercontent.com/assets/5808377/17146724/b82788f2-535f-11e6-8bfb-d8aa7abba592.png)


But I think it works as I don't have any non-english languages installed on my machine.  (or on AppVeyor)

**Comment by 304NotModified** [comment]
is it possible to test with an beta package?

**Comment by 304NotModified** [comment]
Dived into to this,

it seems not to be possible to pass the culture to the exception.toString or something like that. See http://stackoverflow.com/questions/209133/exception-messages-in-english

**Comment by srollinet** [comment]
@304NotModified I cloned the repository and the test fails as well. So yes it is probably because I have non-english languages installed.

![image](https://cloud.githubusercontent.com/assets/12350967/17146968/d495c142-5360-11e6-9e59-7374fa0ae3bb.png)

I have seen the StackOverflow question and also ask a new one specific to NLog http://stackoverflow.com/questions/38585028/configure-nlog-to-write-exception-messages-in-english

As I say in my question, I wanted to use a better solution than switching manually the CurrentUICulture. But if it is not possible I will probably wrap the logger and switch the culture. It won't be hard as I inject it as an ILogger

**Comment by 304NotModified** [comment]
the fancy way to fix is, is writing a LayoutWrapper which switches the Culture. 

Something like this:

using System.Globalization;
using System.Threading;
using NLog.Layouts;

namespace NLog.LayoutRenderers.Wrappers
{
    using NLog.Conditions;
    using NLog.Config;

 
    [LayoutRenderer("SwitchCulture")]
    [AmbientProperty("Culture")]
    [ThreadAgnostic]
    public sealed class SwitchCultureLayoutRendererWrapper : WrapperLayoutRendererBase
    {
        
        [RequiredParameter]
        public CultureInfo Culture { get; set; }
        
        /// <summary>
        /// Transforms the output of another layout.
        /// </summary>
        /// <param name="text">Output to be transform.</param>
        /// <returns>Transformed text.</returns>
        protected override string Transform(string text)
        {
            return text;
        }

        /// <summary>
        /// Renders the inner layout contents.
        /// </summary>
        /// <param name="logEvent">The log event.</param>
        /// <returns>
        /// Contents of inner layout.
        /// </returns>
        protected override string RenderInner(LogEventInfo logEvent)
        {
            var oldCulture = Thread.CurrentThread.CurrentUICulture;
            Thread.CurrentThread.CurrentUICulture = Culture;
            //maybe also a new thread ? 
            try
            {
                var value = base.RenderInner(logEvent);
                return value;
            }
            finally
            {
                Thread.CurrentThread.CurrentUICulture = oldCulture;
            }
        }
    }
}

**Comment by srollinet** [comment]
@304NotModified Okay, I like this idea because it doesn't involve too much code :)

But I am probably missing something. I have the following exception: "LayoutRenderer cannot be found: 'InvariantCulture'"

using System.Globalization;
using System.Threading;
using NLog.Config;

```
// ReSharper disable once CheckNamespace
namespace NLog.LayoutRenderers.Wrappers //Is it mandatory to use this namespace?
{
    [LayoutRenderer("InvariantCulture")]
    [ThreadAgnostic]
    public sealed class InvariantCultureLayoutRendererWrapper : WrapperLayoutRendererBase
    {
        protected override string Transform(string text)
        {
            return text;
        }

        protected override string RenderInner(LogEventInfo logEvent)
        {
            var currentCulture = Thread.CurrentThread.CurrentUICulture;
            try
            {
                Thread.CurrentThread.CurrentUICulture = CultureInfo.InvariantCulture;
                var value = base.RenderInner(logEvent);
                return value;
            }
            finally
            {
                Thread.CurrentThread.CurrentUICulture = currentCulture;
            }
        }
    }
}
```

and the config

```
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useInvariantCulture="true"  throwExceptions="true">

  <targets>
    <target name="console" xsi:type="ColoredConsole" />
    <target name="logfile" xsi:type="File"
            layout="${longdate}|${level:uppercase=true}|${logger}|${message}|${InvariantCulture:${exception:format=tostring}}"
            archiveNumbering="Date"
            archiveEvery="Day"
            archiveDateFormat="yyyyMMdd"/>
  </targets>

  <rules>... </rules>

</nlog>

```

**Comment by 304NotModified** [comment]
You need to register it manually or creating an assembly.

e.g.

```c#
  ConfigurationItemFactory.Default.LayoutRenderers
          .RegisterDefinition("hello-universe", typeof(MyNamespace.HelloUniverseLayoutRenderer
```

See http://nlog-project.org/2015/06/30/extending-nlog-is-easy.html

**Comment by srollinet** [comment]
Works like a charm. Thanks for your help

**Comment by 304NotModified** [comment]
Glad to hear!

**Comment by Peter-Optiway** [comment]
This should be part of NLog!

**Comment by 304NotModified** [comment]
we don't like to change the global "Thread.CurrentThread" in NLog. Sounds like a bad idea, so not supported out-of-the-box.

**Comment by GibbOne** [comment]
Thx for library and suggested solution of the problem.

@304NotModified  
Are you sure that it's correct to link logging culture to Thread culture?
Maybe globalization concern should be managed on some other place on NLog?
Am I wrong?
Thx
