### ISSUE TITLE
ASPNETCORE_ENVIRONMENT env variable and full NET framework (non-core)

### ISSUE THREAD

**Issue by naymore** [NLog/NLog#1721]
Question.

**NLog version:** 4.3.10

**Platform**: .NET 4.6.2

Is it possible to use this environment variable in the full framework as well?
For example on my Staging system I want NLog to use NLog.Staging.Config.

I've seen there's an extension method for IAppBuilder but my application is not using OWIN and is not a web application.

Edit: I know. The environment variable clearly says ASP... it's still better than rolling your own I guess :)

**Comment by 304NotModified** [comment]
Could you elaborate what you are trying to achieve? I don't understand it well. 

Printing ASPNETCORE_ENVIRONMENT environment variable in a log file?

**Comment by naymore** [comment]
Noooo :) See https://docs.asp.net/en/latest/fundamentals/environments.html

I want to use this environment variable for NLog to decide (internally) which NLog config file to load.

**Example**: ASPNETCORE_ENVIRONMENT = "Staging"
--> NLog tries to load NLog.Staging.Config, if no file is found fall back to NLog.Config...

**Comment by 304NotModified** [comment]
What about

```xml
<nlog>
  ...
  <include file="${basedir}/NLog.${environment:ASPNETCORE_ENVIRONMENT}.config" ignoreErrors="true"/>

<targets> ... </targets>
  ...
</nlog>
```

**Comment by naymore** [comment]
There is an *include* directive!  
This is even better :-)

**Comment by 304NotModified** [comment]
👍
