### ISSUE TITLE
What will be the best place to log the user name and other details in SQL Server whenever any user access the .net core application

### ISSUE THREAD

**Issue by vijaykumartk** [NLog/NLog#1723]
Am using NLog for logging in my .net core mvc application. My requirement is I need to log the user information to SQL server DB whenever any user access the application for the first time. We are using Windows authentication. User can directly access any page of the application using the URLs (may not be the home page always). In .net core which will be the right place to capture this info and log into SQL Server DB using NLog?

Thanks in advance!

**Comment by 304NotModified** [comment]
Sorry for the late response.


This isn't really a NLog question and currently we don't know the answer ;)

I would recommend to post it on Stackoverflow is this is still an issue.
