### ISSUE TITLE
MDLC support for .NET Core

### ISSUE THREAD

**Issue by zhangsiy** [NLog/NLog#1729]
Feature Inquiry/Request

NLog version: 4.4.0 - *

Platform: .Net Core

According to the Platform Support page, it seems that there is not yet planned support of MDLC for .Net Core yet, is this correct? And if so, do we know when can we expect the support to be available? 

Ask because we currently rely on MDLC to track things like correlation IDs and stuff, to keep them "logic context safe" and the render layout is really convenient to output them. 

Thanks.

**Comment by 304NotModified** [comment]
> According to the Platform Support page, it seems that there is not yet planned support of MDLC for .Net Core yet, is this correct? And if so, do we know when can we expect the support to be available?

The platform support page only shows the current support. We prefer to support everything which is available in NLog 4, but not everything has the same prio.

Currently the development for .NET core is limited 'cause:
- The tools are not stable (not one my local machine, not on AppVeyor)
- We are missing some needed classes in .NET core (planned for netstandard 2)
- The non-core version of NLog (4.3.x) needs also some time (questions, bugs etc)

**Comment by 304NotModified** [comment]
Will check now why MDLC is not implemented yet

**Comment by 304NotModified** [comment]
it uses [`system.runtime.remoting.messaging.logicalcallcontext`](https://msdn.microsoft.com/en-us/library/system.runtime.remoting.messaging.logicalcallcontext(v=vs.110).aspx), which isn't available on .NET Core?

**Comment by zhangsiy** [comment]
Thanks for the response.  And yes CallContext probably won't be on .NET Core due to its tie to remoting. Though it seems like possible to add a branch of implementation under MDLC API to use AsyncLocal for 4.6/Core CLR. I'll see if I can put together something for this.

**Comment by 304NotModified** [comment]
That would be great! We like to support this!

**Comment by 304NotModified** [comment]
Any luck in this?

**Comment by benchaikin** [comment]
I'm also interested in the status of this, and possibly submitting a pull request if it isn't already in the works. It seems like something along these lines (with AsyncLocal<> as mentioned above) could do the trick: http://theburningmonk.com/2015/05/a-consistent-approach-to-track-correlation-ids-through-microservices/

**Comment by 304NotModified** [comment]
PR would be great ! 

AFAIK nobody is working in it

**Comment by snakefoot** [comment]
@304NotModified Has now been resolved

**Comment by 304NotModified** [comment]
Yes!
Have to fix #2033 and then it will be releases (beta 7 )

**Comment by snakefoot** [comment]
@304NotModified Think this can be resolved with the release of NLog 5.0 BETA7

**Comment by 304NotModified** [comment]
\0/ nice
