### ISSUE TITLE
Support for log4jxmlevent on dotnetcore

### ISSUE THREAD

**Issue by marcwittke** [NLog/NLog#1731]
**Feature Request**

**NLog version**: 4.4.0-betaV15

**Platform**:  .NET Core 

**Current NLog config** (xml or C#, if relevant)

``` xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" autoReload="true">

  <targets async="true">
    <target name="xmlFilePerDay" keepFileOpen="true" xsi:type="File" fileName="${shortdate}.log" layout="${log4jxmlevent}">
    </target>
  </targets>

  <rules>
    <logger name="*" minlevel="Info" writeTo="xmlFilePerDay" />
  </rules>
</nlog>

```
## Why do we need it?

Well, the log4j XML Format is well being adapted by numerous tools, therefore it would be pretty nice to have it. Is there a specific reason to leave this layout out?

**Comment by 304NotModified** [comment]
Will check this!

**Comment by 304NotModified** [comment]
I think we could add this, it now needed an appdomain (which isn't there on .NET Core), but we could implement it without it.

**Comment by 304NotModified** [comment]
This has been added to the first beta of NLog 5! (the new name for .NET core support)

https://www.nuget.org/packages/NLog/5.0.0-beta01
