### ISSUE TITLE
How to expand/flatten an AggregateException using the layout

### ISSUE THREAD

**Issue by robdcgnx** [NLog/NLog#1738]
Feature Request
 - Why do we need it?
When more than one sub task has throws an exception an AggregateException is formed with each exception stored in the property, AggregateException.InnerExecption**s** (note the s)
At present I can only get NLog to recursively log the InnerExpection (singular)

Given the all the TPL programming these days, I expect other people to run into the same problem where exception data is lost when multiple sub tasks throw exceptions.

**NLog version**: 4.3.10
**Platform**: .Net 4.6
**Current NLog config** C# -> See attach unit test

- What is the current result?
Recursively logs only the InnerException (singular)

- What is the expected result?
Handles the AggregateException.InnerException**s** property to log all inner exceptions.

- Are there any workarounds? 
No, other than manually expanding out the InnerExceptions and writing them separately.

- Is there a version in which it did worked? 
No

- Can you help us by writing an unit test?
Done, see attached. [AggregateExceptionTests.zip] https://github.com/NLog/NLog/files/567541/AggregateExceptionTests.zip)

**Comment by snakefoot** [comment]
Calling the method AggregateException.Flatten() and then calling NLog for each exception should "solve" the problem. But that would require you to sprinkle AggregateException-catch-blocks every where.

Yes it would be nicer if NLog ExceptionLayoutRenderer could do this automatically.

**Comment by 304NotModified** [comment]
> Yes it would be nicer if NLog ExceptionLayoutRenderer could do this automatically.

Agree, if someone knows a good way to configure/implement it, let us know :)
