### ISSUE TITLE
Logging takes a long time even though targets are wrapped in AsyncWrappers

### ISSUE THREAD

**Issue by aireq** [NLog/NLog#1743]
- **Type**: Question
- **NLog version**: 4.3.10
- **Platform**: .Net 4.5
 - **Current NLog config**: See post below

I'm using NLog to log user activity to Elasticsearch and a Kibana dashboard using the Elasticsearch target.

I want my plug-in to be as non-invasive as possible. So in the places where I'm logging user events I've followed the follow pattern to profile how much time it takes to actually log the message. If it takes more then some threshold time for the event handler to complete I log this to a separate internal log as an error.

    void SomeEvent(object sender, EventArgs e)
    {
            Stopwatch eventHandlerStopWatch = Stopwatch.StartNew();
            try
            {
                 //Perform some other tasks here to collect data from the application to log
                 _activityLogger.Info("Message goes here");
            }
            catch (Exception exp)
            {
                _internalLog.Error(exp, exp.GetType().Name + "thrown in ViewActivated()");
            }
            finally
            {
                eventHandlerStopWatch.Stop();
                if(eventHandlerStopWatch.ElapsedMilliseconds > _errorThreshold)
                {
                    _internalLog.Error("SomeEvent Handler elapsed: " + eventHandlerStopWatch.ElapsedMilliseconds);
                }
            }
    }

I only have two targets in my NLog.config file. An Elasticsearch target and a local File target to record debug information on the users local machine. Both of these are wrapped in AsyncWrappers, and the timeToSleepBetweenBatches of the wrapper around the Elasticsearch target is increased to 1000ms. The overflowAction is set to the default of discard. I'd rather loose log message, then effect the users experience in the software.

I rolled this out to a number of users today, and for the most part it worked. However, I did record a number of Errors where  the event handler time was went over the threshold time. Sometimes it logged over a minute in the event handler. I looked further into the debug logs and found that this time was indeed spent in the  call to `_activityLogger.Info()`.

If I'm logging to async wrappers that discard if the buffer fills up, why would logging take any time at all? Shouldn't the AsyncWrapper just buffer the message and allow the code the continue on immediately?

**Comment by 304NotModified** [comment]
Please post the full config, perhaps there is a mistake in it.

**Comment by aireq** [comment]
Here's the config file:

```
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="false"
      internalLogLevel="Off"
      internalLogFile="nlog-internal.log" >

  <variable name ="fileTimeStamp" value="${date:universalTime=False:format=yyyy-MM-dd HH\:mm\:ss}"/>
  <variable name="logFileLayout" value="${fileTimeStamp} | ${level:uppercase=true} | ${logger} | ${message} ${exception:format=toString}"/>

  <!--Include User Specific config if available-->
  <include ignoreErrors="true" file="${specialfolder:folder=ApplicationData}/ActivityLog/Nlog.config"/>

  <!--Include Machine Specific config if available-->
  <include ignoreErrors="true" file="${specialfolder:folder=CommonApplicationData}/ActivityLog/Nlog.config"/>
  
  <targets>
    <target xsi:type="AsyncWrapper" name="debugFileAsync">
      <target name="debugFile" xsi:type="File"
              layout="${logFileLayout}"
              fileName="${specialfolder:folder=LocalApplicationData}/ActivityLog/Debug Logs/${shortdate} - ActivityLog Debug.txt"
              archiveFileName ="${specialfolder:folder=LocalApplicationData}/ActivityLog/Debug Logs/${shortdate} ({###}) - ActivityLog Debug.txt"
              keepFileOpen ="true"
              maxArchiveFiles ="100"
              archiveOldFileOnStartup="true"
              archiveNumbering="Sequence"
            />
    </target>
    <target name="udp" xsi:type="NLogViewer" address="udp4://MACHINE:7071" layout="${message} | ${all-event-properties}" />
    <target name="elastic_async" xsi:type="AsyncWrapper" queueLimit="10000" timeToSleepBetweenBatches="1000" batchSize="100" overflowAction="Discard">
      <target name="elastic" index="activity-${shortdate:universalTime=true}" xsi:type="ElasticSearch" documentType="log" uri="http://SERVER:9200" includeAllProperties="true">
        <field name="message" layout="${message}" />
        <field name="Machine" layout="${machinename}" />
        <field name="ApplicationSessionId" layout="${gdc:item=ApplicationSessionId}" />
        <field name="ActivityLogVersion" layout="${gdc:item=ActivityLogVersion}" />
        <field name="WindowsUser" layout="${windows-identity:userName=True:domain=False}" />
        <field name="logger" layout="${logger}" />
        <field name ="sequence" layout="${counter}"/>
      </target>
    </target>
  </targets>
  <rules>
    <logger enabled="true" name="*" minlevel="Info" writeTo="elastic_async" >
      <filters>
        <when condition="equals('${event-properties:item=Event}','FailureProcessing')" action="Ignore"/>
        <when condition="equals('${event-properties:item=Event}','DialogBoxShowing')" action="Ignore"/>
      </filters>
    </logger>
    <logger enabled="true" name="*" minlevel="Debug" writeTo="debugFileAsync"  />
    <logger enabled="false" name="*" minlevel="Debug" writeTo="udp"  />
  </rules>
</nlog>
```

**Comment by snakefoot** [comment]
Your layout includes windows-identity, which is very slow. Before posting to the async-wrapper then logger-thread has to capture its currrent username.

After the capture of current username, then it discovers that it should be discarded.

**Comment by 304NotModified** [comment]
Thanks snakefoot, I did know that. 

If that's the case,  maybe the value could be cached. (Cache wrapper)

**Comment by snakefoot** [comment]
Seems for ASP.NET then the ClaimsIdentityFactory should be faster than WindowsIdentity.GetCurrent

https://github.com/rahulgarg1985/CodeNode.Identity/blob/master/CodeNode.Identity/Utilities/IdentityClaimsHelper.cs

Maybe consider to add a custom  layout-renderer that is based on ClaimsIdentityFactory, and use that instead of WindowsIdentityLayoutRenderer

**Comment by snakefoot** [comment]
Guess a simple solution, would be to cache the process user, then it is just a matter of checking if impersonating:

```
        private IIdentity _processIdentity = null;

        protected override void Append(StringBuilder builder, LogEventInfo logEvent)
        {
            IIdentity currentIdentity;
#if NET4_5
            currentIdentity = System.Security.Claims.ClaimsPrincipal.Current.Identity;
            if (!currentIdentity.IsAuthenticated || string.IsNullOrEmpty(currentIdentity.Name))
                currentIdentity = null;
#endif
            if (currentIdentity == null)
                currentIdentity = WindowsIdentity.GetCurrent(true);
            if (currentIdentity == null)
            {
                // Not impersonating, take user-identity from process
                if (_processIdentity == null)
                    _processIdentity = WindowsIdentity.GetCurrent(false);
                currentIdentity = _processIdentity;
            }
```

**Comment by aireq** [comment]
I tried to resolve this problem by caching the user name and machine name in the GDC rather then having NLog retrieve it each time an event is logged.

Now I have the following code when my application starts up:

```
NLog.GlobalDiagnosticsContext.Set('WindowsUser", System.Environment.UserName);
NLog.GlobalDiagnosticsContext.Set("Machine", System.Environment.MachineName);
```

And then in my NLog.config file I have the following fields that reference the values in the GDC rather then using the built-in `machinename` and `windows-identity` layouts.

```
<field name="Machine" layout="${gdc:item=Machine}" />
<field name="WindowsUser" layout="${gdc:item=WindowsUser}" />
```

However, I'm still having the same problem as before where logging seems to randomly block for up a minute, which in turn also freezes the GUI for the user.

It wouldn't surprise me if the ElasticSearch target I'm using is slow or unreliable. If for some reason a client can't connect to the server then it will probably just block until it times out. However, I thought because I've wrapped this in an AsyncWrapper this would happen on another thread, and thus not block at the original call to the NLog Logger? Why would an AsyncWrapper set to discard ever block the calling code?

The application I'm logging is actually a .NET based plug-in with-in another piece of commercial software. Does that make a difference? Is it possible that the thread NLog is creating is interfering with the native application in some way?

**Comment by snakefoot** [comment]
The actually logging happens on a Timer-thread, so if you experience that your application freezes. Then it is most likely caused by interactive garbage collection.

Have you activated concurrent garbage collection mode in the app.config:

```
  <runtime>
    <gcServer enabled="true"/>
  </runtime>
```

**Comment by aireq** [comment]
I mentioned at the end of my last message that I'm actually working on a plug-in for another commercial application. I'm writing code again its API and logging when specific events are fired such as when a user opens, closes, and saves files. So I don't have control over what thread my code runs on. 

If event handler methods for these events block then the main application will hang until the event completes. I've tested this by adding a "Thread.Sleep()" call and as expected the application will freeze for the specified time.

The native application's config file does not have a `gcServer` element, but I'm hesitant to change anything about how the native application works. I'm trying to make my logging plug-in as non-invasive as possible.

I'm not very experienced with how timer threads and garbage collection works in .NET. Is there some way i can confirm this is the issue? I'm logging freezes over 60 seconds long. Does garbage collection really take this long? 

This is difficult to debug because the issue does not happen very often. Yesterday I logged 3345 events out of which 212 took more then 2 seconds to log. So only about 6%

**Comment by 304NotModified** [comment]
Could you post all the info requested in "template" when creating a new issue?

**Comment by aireq** [comment]
Sorry about that. I updated the original question.

**Comment by 304NotModified** [comment]
@aireq would it be possible to deliver a internal log (trace) level for those cases?

> I'm not very experienced with how timer threads and garbage collection works in .NET. Is there some way i can confirm this is the issue? I'm logging freezes over 60 seconds long. Does garbage collection really take this long?

I don't this could be the GC, but it depends how much you're writing (and which hardware)



> This is difficult to debug because the issue does not happen very often. Yesterday I logged 3345 events out of which 212 took more then 2 seconds to log. So only about 6%

2 seconds is way to much for async.

**Comment by aelij** [comment]
@304NotModified I think you meant to mention someone else :)

**Comment by 304NotModified** [comment]
oops sorry! @aelij

**Comment by aireq** [comment]
@304NotModified I've collected some debug level internal logs, but nothing looks out of the ordinary. Only a few warnings about unused targets. I'll increase the level to trace and see what I get. 

The Elasticsearch target also has a [`throwExceptions` parameter](https://github.com/ReactiveMarkets/NLog.Targets.ElasticSearch/wiki). Should I enable this as well? Will nlog swallow exceptions thrown by the target? I don't want to crash the application for the user while testing.

I'm certainly not logging millions of events. More like 500 or so events per user over the course of a workday.

I keep a single log file for each session the user is in the application and have `archiveOldFileOnStartup=true`. So it should only archive once when the user launches the application right? The slow down happens much later as they are working the software.

Yes that's the Elasticsearch target I'm using. There's [a comment in the source for 2.1.0](https://github.com/ReactiveMarkets/NLog.Targets.ElasticSearch/blob/2.1.0/src/NLog.Targets.ElasticSearch/ElasticSearchTarget.cs#L147) which explains [a bug](https://github.com/elastic/elasticsearch-net/issues/2052) that extra serialization and deserialization attempts to fix.

**Comment by aireq** [comment]
Actually, now that I think about it I'm not actually logging the events that are causing the application to freeze to Elasticsearch. 

My plug-in is subscribed to the ViewActivated, events of the native application's API. This fire when the user opens a new window, which I typically don't want to log. But I figured I'd keep the logging code in my plugin and filter out these events with the nlog config. This way I can re-enable logging of these events on a case by case basis later if needed.

The logger config below shows how I am filtering out the ViewActivated events.

```
    <logger enabled="true" name="*" minlevel="Info" writeTo="elastic_async" >
      <filters>
        <when condition="equals('${event-properties:item=Event}','ViewActivated')" action="Ignore"/>
      </filters>
    </logger>
```
I'm only sending Info level events to Elasticsearch, but I'm also writing debug level log files to the user's local computer. However, the debug logs include the ViewActivated events I'm filtering from the Elasticsearch target.

Here's my config for the debug file(s) target.

```
<target xsi:type="AsyncWrapper" name="debugFileAsync">
    <target name="debugFile" xsi:type="File"
              layout="${logFileLayout}"
              fileName="${specialfolder:folder=LocalApplicationData}/ActivityLog/Debug Logs/${shortdate} - ActivityLog Debug.txt"
              archiveFileName ="${specialfolder:folder=LocalApplicationData}/ActivityLog/Debug Logs/${shortdate} ({###}) - ActivityLog Debug.txt"
              keepFileOpen ="true"
              maxArchiveFiles ="100"
              archiveOldFileOnStartup="true"
              archiveNumbering="Sequence"
            />
</target>
```
Could using `$(specialfolder)` be causing a similar issue as using `$(windows-identity)`?

**Comment by snakefoot** [comment]
Tried to run your config in the profiler, and the "filters" are not performing very well.

I would recommend that you use a special Logger-Name for the "ViewActivated"-events and then in the top of the logging-rules add a new logging-rule matching that Logger-Name (as final), so they never reach the elastic_async-logging-rule.

Then you can remove the filters.

**Comment by 304NotModified** [comment]
yes indeed, the filters are running in the main thread. I think this could cause a 2 sec delay. 



> I keep a single log file for each session the user is in the application and have archiveOldFileOnStartup=true. So it should only archive once when the user launches the application right? The slow down happens much later as they are working the software.

I see also   maxArchiveFiles ="100"

**Comment by 304NotModified** [comment]
> I would recommend that you use a special Logger-Name for the "ViewActivated"-events and then in the top of the logging-rules add a new logging-rule matching that Logger-Name (as final), so they never reach the elastic_async-logging-rule.

That's indeed the best approach. Another posiblity is to use the [PostFilteringWrapper](https://github.com/NLog/NLog/wiki/PostFilteringWrapper-target) inside the AsyncWrapper

**Comment by aireq** [comment]
Got it. So the filters run on the main thread before they even get to the AsyncWrapper. So if the filters are slow this will block the main thread.

Although I'm logging freezes that are *much* more than 2 seconds.  For one user this morning I logged separate instances of the ViewActivated handler taking 112.35 sec, 27.68 sec, 24.12 sec, and 61.47 sec! I've enabled the nlog-internal log on this user's computer at a trace level, and am waiting for this to happen again.

Any idea why these filters are not performing very well?

I'll try filtering by logger name instead.

**Comment by snakefoot** [comment]
I have made a PR that will improve the filter performance (if accepted). But they are slow by nature as they do a lot of string-formatting and then performs a string-comparison. See #1779

**Comment by 304NotModified** [comment]
I think this one is solved?

**Comment by aireq** [comment]
I'm going to try snakefoot's suggestion of creating unique logger names for these events and filter them out with a final logger rule rather then a filter.

**Comment by 304NotModified** [comment]
👍

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, let us know!
