### ISSUE TITLE
NLog.Config.ConfigurationItemFactory exception

### ISSUE THREAD

**Issue by luminalpark** [NLog/NLog#1744]
Type: Bug

NLog version: 4.3.10
NLog.Web version: 4.2.1

Platform: .NET

Current NLog config:

`<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="false"
      internalLogLevel="Off" internalLogFile="c:\temp\nlog-internal.log">

  <variable name="myvar" value="myvalue"/>

  <targets>
    <target name="db"
        xsi:type="Database"
        connectionStringName="NLogConn"
        commandType="StoredProcedure"
        commandText="[dbo].[NLog_AddEntry_p]"
        >
      <parameter name="@machineName"    layout="${machinename}" />
      <parameter name="@siteName"       layout="${iis-site-name}" />
      <parameter name="@logged"         layout="${date}" />
      <parameter name="@level"          layout="${level}" />
      <parameter name="@username"       layout="${aspnet-user-identity}" />
      <parameter name="@message"        layout="${message}" />
      <parameter name="@logger"         layout="${logger}" />
      <parameter name="@properties"     layout="${all-event-properties:separator=|}" />
      <parameter name="@serverName"     layout="${aspnet-request:serverVariable=SERVER_NAME}" />
      <parameter name="@port"           layout="${aspnet-request:serverVariable=SERVER_PORT}" />
      <parameter name="@url"            layout="${aspnet-request:serverVariable=HTTP_URL}" />
      <parameter name="@https"          layout="${when:inner=1:when='${aspnet-request:serverVariable=HTTPS}' == 'on'}${when:inner=0:when='${aspnet-request:serverVariable=HTTPS}' != 'on'}" />
      <parameter name="@serverAddress"  layout="${aspnet-request:serverVariable=LOCAL_ADDR}" />
      <parameter name="@remoteAddress"  layout="${aspnet-request:serverVariable=REMOTE_ADDR}:${aspnet-request:serverVariable=REMOTE_PORT}" />
      <parameter name="@callSite"       layout="${callsite}" />
      <parameter name="@exception"      layout="${exception:tostring}" />
    </target>
  </targets>

  <rules>
    <logger name="*" minlevel="Trace" writeTo="db" />
  </rules>
</nlog>
`

- What is the current result? System.TypeInitializationException: The type initializer for 'NLog.Config.ConfigurationItemFactory' threw an exception. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'c:\webfiles\Siti\StagingIT\bin'

- What is the expected result? No exception

My ASP.NET application is hosted in IIS in a shared volume, BIN folder is located in an UNC path, Nlog is looking for the assembly in the local drive.

**Comment by 304NotModified** [comment]
Fixed? What was the fix?

**Comment by luminalpark** [comment]
Hi,

don't really know, I deployed once again the application and now it runs
ok..


*Carlo Cecco*----------------------

*Luminal Park S.r.l.*Via Abetone Brennero, 149
46025 Poggio Rusco (MN) ITALY
Tel. +39 (0) 386 51 209 - Fax +39 (0) 386 70 01 65
Mobile: +39 349 3528421
Email: carlo.cecco@luminalpark.com - Web: www.luminalpark.it

[image: Follow us on Facebook] <https://www.facebook.com/luminalpark.it>

Ai sensi della Legge 196/03 si precisa che le informazioni contenute in
questo messaggio sono riservate ed a uso esclusivo del destinatario.
Qualora il messaggio in parola Le fosse pervenuto per errore, la preghiamo
di eliminarlo senza copiarlo e di non inoltrarlo a terzi, dandocene
gentilmente comunicazione. Grazie.

This message, for the law 196/03, may contain confidential and/or
privileged information. If you are not the addressee or authorized to
receive this for the addressee, you must not use, copy, disclose or take
any action based on this message or any information herein. If you have
received this message in error, please advise the sender immediately by
reply e-mail and delete this message. Thank you for your cooperation.

2016-11-04 12:42 GMT+01:00 Julian Verdurmen <notifications@github.com>:
