### ISSUE TITLE
Remove unnecessary memory allocations

### ISSUE THREAD

**Issue by sungam3r** [NLog/NLog#1753]
**Type**: Feature request

**NLog version**: 4.3.11

**Platform**: any

**Current NLog config**: does not matter

Just try search through solution with keyword [0];

Among results you will find places with unnecessary memory allocations:
```
\src\NLog\Config\LoggingConfiguration.cs(110):   get { return new string[0]; }
\src\NLog\Internal\SortHelpers.cs(199):          return new TKey[0];
\src\NLog\Layouts\SimpleLayout.cs(123):          renderers = new LayoutRenderer[0];
```
Also in SortHelpers.cs you can see
```
return new TValue[] { };
```
which in fact equals to
```
return new TValue[0];
```

But somewhere there are cached one time allocated fields:
```
\src\NLog\Internal\FactoryHelper.cs(45):   private static Type[] emptyTypes = new Type[0];
\src\NLog\Internal\FactoryHelper.cs(46):   private static object[] emptyParams = new object[0];
```

In case of .NET 4.6 we can just use this:
https://msdn.microsoft.com/en-us/library/dn906179(v=vs.110).aspx

**Comment by 304NotModified** [comment]
Is the proposal to replace them with `null`?

**Comment by sungam3r** [comment]
Proposal is to replace it with similarly to
```
private static Type[] emptyTypes = new Type[0];
```
with concrete types (string, TKey etc).

Array.Empty<string> is just a short wrapper around such static field:
```
public abstract class Array : ICloneable, IList, ICollection, IEnumerable, IStructuralComparable, IStructuralEquatable
{
  ... 
  public static T[] Empty<T>()
  {
    return EmptyArray<T>.Value;
  }
  ...
}

internal static class EmptyArray<T>
{
  public static readonly T[] Value;
  static EmptyArray()
  {
    EmptyArray<T>.Value = new T[0];
  }
}
```

It will consume only one memory allocation per template argument type in AppDomain instead of every call.

**Comment by UgurAldanmaz** [comment]
It would be useful. Need to test performance difference.

**Comment by sungam3r** [comment]
Yes, it is just a small nice memory optimization.

**Comment by snakefoot** [comment]
Those locations will not be hit by the normal execution path,. But always nice with a cross-platform Array<T>.Empty() method that works on all .NET versions.

**Comment by snakefoot** [comment]
At good place for your optimized Array.Empty() would be here:

resultEvents = new AsyncLogEventInfo[count]; - AsyncRequestQueue-T.cs(140)

For normal operation, then is is called 200 times/sec. Constantly allocating empty arrays, when nothing to write.

**Comment by sungam3r** [comment]
Nice.
Also you can find constantly allocations in calls to string.Split() in MailTarget, ExceptionLayoutRenderer, AppDomainWrapper - Split(new[] {';'} ... etc.

**Comment by snakefoot** [comment]
I well let you hunt down those fixed-readonly-array, and create a PR for it.
