### ISSUE TITLE
Multi Instancing problem

### ISSUE THREAD

**Issue by TazarvEBanking** [NLog/NLog#1759]
Dear Friend,
I need two instance of Logger in my app with different configurations. I wrote bellow sample code but found there is a problem in multi instancing.

```
            var config1 = new LoggingConfiguration();
            var fileTarget1 = new FileTarget();
            config1.AddTarget("file", fileTarget1);
            fileTarget1.Layout = "${message}";
            fileTarget1.FileName = "1.txt";
            var rule1 = new LoggingRule("1", LogLevel.Trace, fileTarget1);
            config1.LoggingRules.Add(rule1);
            LogManager.Configuration = config1;   
            Logger Logger1 = LogManager.GetLogger("1");

            var config2 = new LoggingConfiguration();
            var fileTarget2 = new FileTarget();
            config2.AddTarget("file", fileTarget2);
            fileTarget2.Layout = "${message}";
            fileTarget2.FileName = "2.txt";
            var rule2 = new LoggingRule("2", LogLevel.Trace, fileTarget2);
            config2.LoggingRules.Add(rule2);
            LogManager.Configuration = config2;   
            Logger Logger2 = LogManager.GetLogger("2");

```
            Logger1.Info("1111111111111");
            Logger2.Info("2222222222222");
            Logger1.Info("1111111111111");

Result : only (second) file contains "222222" and first file is missed!!!!

**Type** :Question
**NLog version**: 4.3.11
**Platform**:  .Net 4.5 
**Current NLog config** : C# Code Config

- What is the current result? single 1.2.txt contains "2222222222"
- What is the expected result? 2 Files each contains related messages
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?yes (attached)[log.txt](https://github.com/NLog/NLog/files/585570/log.txt)

**Comment by snakefoot** [comment]
Think the clue is that only one LoggingConfiguration is allowed.

So when you do this, then the previous one is discarded:

LogManager.Configuration = config2;   

You should append the two loggers (with targets) to the same LoggingConfiguration, and then assign it to the LogManager.

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, let us know!
