### ISSUE TITLE
new var syntax in file name rendering does not work

### ISSUE THREAD

**Issue by nshanb** [NLog/NLog#1760]
Hi! Thanks for reporting this feature/bug/question! 

**Type** (choose one):

- Bug

**NLog version**: ( 4.2.11)

**Platform**: .Net 4.5

**Current NLog config** (xml or C#, if relevant)

```xml
<nlog>
  <variable name="xxx" value="1"/>
  <include file="test${var:xxx}.config"/>
</nlog>

```

In case of a BUG:

- What is the current result?
exception - file not found, ${var:xxx} is totally ignored
- What is the expected result?
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
- Please post full exception details (message, stacktrace, inner exceptions)
- Are there any work arrounds? yes
use old syntax

```xml
  <variable name="xxx" value="1"/>
  <include file="test${xxx}.config"/>
```

- Is there a version in which it did worked? 
- Can you help us by writing an unit test?

**Comment by 304NotModified** [comment]
Good one. Just checked the NLog code, which looks good, so we should check where it goods wrong.

There is an issue inside `XmlLoggingConfiguration`. Step 1 is to create an unit test first.

**Comment by nazim9214** [comment]
Is this a bug?
From release notes (http://nlog-project.org/2015/08/31/nlog-4-1-0-is-now-available.html)

Variables can be changed, deleted and created from the API
A default value can be configured for a variable, e.g. ${var:password:default=unknown}
The old variables can still be used and so this is completely backwards-compatible.
**You might wonder: why has the old method not been replaced? The answer is simple: the new method only works on Layout types and not on plain strings.**

**Comment by 304NotModified** [comment]
Checked this in-depth. 

This is indeed not a bug. Only the old method works and it's indeed not layoutable. We could make it layoutable, but:

- That will be difficult as reading the includes in early in the process
- You would expect the include would change if the variable was changed, that would make it more difficult.
