### ISSUE TITLE
<include> with wildcard

### ISSUE THREAD

**Issue by rbouny** [NLog/NLog#1764]
Hello

I developp a modular application with Prism.
Each module (plugin) could have its own logging targets and rules. 
I don't know modules at compile time.
it could be great to discover Nlog config files at runtime.
Something like this :

```xml
<nlog>
  <include file="${basedir}\*.nlog"/>
</nlog>

```

Is there already any solution ?
Thanks

**Comment by 304NotModified** [comment]
Interesting question.

Currently masks aren't support in the `<include>`, but i won't be that difficult to support it. (hint it should be in `XmlLoggingConfiguration.ParseIncludeElement`).

Another option would be to allow partial loading of the configuration, e.g. 

     LogManager.Configuration.LoadPartial("nlog1.config")


The current work around I would think of, building your own `<include>`s, do a  `string.Replace` and load it from `string` or write the new nlog.config (and  `LogManager.Configuration.Reload()`)

**Comment by rbouny** [comment]
Thank you for the work around. I will try this way

**Comment by 304NotModified** [comment]
Any luck on this?
