### ISSUE TITLE
AsyncException when writing to internallogger

### ISSUE THREAD

**Issue by sebastianslutzky** [NLog/NLog#1766]
Hi,

I have a custom target that writes to the internal logger. 
This works well if logging synchronously, but the normal use of the target in production is async="true". In this case, the call to internalLogger.Debug (or any other internalLogger method) throws an AsyncException and the entry is not logged (silently)

Is there any workaround to this? I need to have internalLogging to troubleshoot another logging issue, specific to my target.

Thanks,
Sebastian

**Comment by snakefoot** [comment]
Could you provide a callstack, and an exception message? Maybe even provide a reproducable case with a modified custom target that is disconnected from your production environmnet?

**Comment by 304NotModified** [comment]
got the same error when performance testing

![image](https://cloud.githubusercontent.com/assets/5808377/20636887/6434619e-b376-11e6-9f77-82bb06647522.png)


but not with internallogger

   at NLog.Common.AsyncHelpers.RunSynchronously(AsynchronousAction action) in X:\nlog\NLog-Performance-tests\NLog\src\NLog\Common\AsyncHelpers.cs:line 226

**Comment by snakefoot** [comment]
Should be fixed by #1927

**Comment by 304NotModified** [comment]
Thanks @snakefoot !
