### ISSUE TITLE
Customize email further

### ISSUE THREAD

**Issue by R-oberto** [NLog/NLog#1767]
Type: Question
NLog version: 4.2.3
Platform: .Net 4.5

I'm looking for a way to customize the email that is sent further than what appears to be provided. I'd like to be able to set the importance of the email to high and low. I would also like to be able to add custom headers. 

This property can add custom headers, but I don't think NLog supports any sort of delegate or callback that I can use so that I can manipulate the mailmessage just before sending.
https://msdn.microsoft.com/en-us/library/system.net.mail.mailmessage.headers(v=vs.110).aspx

Setting the Microsoft Outlook ConverstationID property would be one reason I would add a header to the email. This could help keep my mailbox better organized. I think if I set this header, I can get Outlook to show the emails as part of a conversation, instead of as separate conversations. If I set the ConversationID intelligently, I could have a conversation that represents all logs of a particular message from one code point.
https://msdn.microsoft.com/en-us/library/office/ff862787.aspx

Do I need to customize the code for this kind of thing? Is there a way to override the constructor of the mailmessage or anything like that?

**Comment by 304NotModified** [comment]
This isn't possible indeed (yet). 

Best work around is to copy-paste the [`MailTarget` class,](https://github.com/NLog/NLog/blob/master/src/NLog/Targets/MailTarget.cs) edit to your requirements, and register it (or place it in NLog.something.dll)

Maybe we should make `MailTarget.CreateMailMessage` `virtual and protected`? (instead of `private`)

**Comment by R-oberto** [comment]
Great, the NLog.something.dll solution is easy enough to maintain. I think I'll tweak it so that Fatal is high importance, Error is normal, and anything less is low importance. Thanks @304NotModified.

**Comment by 304NotModified** [comment]
OK, let me know if we should make the method virtual or something like that :)
