### ISSUE TITLE
DetectConsoleAvailable disables console logging in WPF application even in DEBUG

### ISSUE THREAD

**Issue by skyline75489** [NLog/NLog#1773]
**Type** :
- Question

**NLog version**: 4.3.10

Hi, I just upgrade from 4.3.6 to 4.3.10 in my WPF application and found that all the `ColoredConsoleTarget` log is not displayed any more. Turns out that the newly added console-detection feature turns off the console logging. Setting `DetectConsoleAvailable` to false can fix this. But still I'd love to know that is this expected? I mean I'm in DEBUG and clearly needs console logging.

**Comment by 304NotModified** [comment]
Hi,

this is a performance feature. We have tweaked the condition in 4.3.11. Could you test if that version is working? (without setting it `DetectConsoleAvailable` to `false`)

**Comment by skyline75489** [comment]
I've tried with 4.3.11 and had no luck. Without setting `DetectConsoleAvailable` to `false` I can not see any output in debug output window. I'd put some code here if you feel needed. It works perfectly with 4.3.6, though.

**Comment by skyline75489** [comment]
Come to think about it, I don't think DEBUG configuration actually matters. In RELEASE the console target should also work as expected, right?

**Comment by SuhovDE** [comment]
I have the similar problem with console application when it is started by Task Scheduler if task is configured to not display window (**Hidden** option on **General** tab of scheduled task configuration window)
It doesn't work with version 4.3.10 and 4.3.11
Changing **DetectConsoleAvailable** to **false** helps.

I start application using command file like:
`NLogTest.exe >> log.txt`

**Comment by 304NotModified** [comment]
Thanks for the feedback! Seems the check won't work well. 

Someone has an idea how to improve it?  See code
https://github.com/NLog/NLog/blob/90f037391fb383421162788a7f6f21eef0c698f8/src/NLog/Targets/ConsoleTargetHelper.cs#L48

Any idea if this it logs "Environment.UserInteractive = False" or "Console.OpenStandardInput = Null"?

**Comment by snakefoot** [comment]
When NLog is initialized, then it checks if a normal console window is available with input-/output-stream.

If the WPF-Application ensures a proper console window has been created before using NLog (Calling AllocConsole), then NLog will use the console window. Though I must admit it is very strange to use a native Console Window within a WPF-Application.

The special solution of piping the output from the NLog Console Target for file writing, that doesn't work when starting the console application using the Task Scheduler (or running it as non-interactive windows service). Then one could consider to give the log-filename as input parameter instead of using pipe.

Again I have no issue with changing the default value of DetectConsoleAvailable,.

**Comment by 304NotModified** [comment]
> Again I have no issue with changing the default value of DetectConsoleAvailable

Yes, I guess we should change it to `false` by default in 4.4

**Comment by skyline75489** [comment]
Thanks for the feedback. Glad to finally know what is going on with the new version. Then again, I wonder if there is any actually performance overhead when writing console output in WPF applications. I mean, when not attached to debugger, there is no console to write anyhow.

**Comment by snakefoot** [comment]
> any actually performance overhead when writing console output in WPF applications

First it spend time on formatting each LogEvent to a nice string for the Console-Window to write, and then it throws the work away. So yes there is some overhead.

**Comment by skyline75489** [comment]
Well in this case maybe it's better to disable console logging completely in RELEASE mode.

**Comment by 304NotModified** [comment]
Every target should be available when needed, so I'm not a fan of disabling targets on some modes (e.g. release).

**Comment by skyline75489** [comment]
I don't have issue with changing the default value of DetectConsoleAvailable, either. But why changing it back in ver 5.0? Am I missing anything?

**Comment by skyline75489** [comment]
Disabling targets on some mode is a bad move, I agree. Guess that's why the console-detection is introduced in the first place.

**Comment by 304NotModified** [comment]
> But why changing it back in ver 5.0? Am I missing anything?

I guess when we fixed the condition check in 5.0. We aren't going to change it back until is it's working all the cases :)

**Comment by reijerh** [comment]
Maybe I'm misunderstanding, but wouldn't it be more performant to keep `DetectConsoleAvailable=True` and have people add a `Debugger` target if they need logging to the debugger output window? (https://github.com/NLog/NLog/wiki/Debugger-target)

**Comment by snakefoot** [comment]
Because of compatibility, then it is the other way around (See the unique case where one perform file logging using the console output, when running within the Task Scheduler)

**Comment by techie55** [comment]
We are using NLog with Azure webjobs and realized that azure was not logging console messages written using NLog anymore. On digging further I discovered that DetectConsoleAvailable was the culprit. 
FYI, azure logs all messages which are written to the console, since this is how webjobs are run. Even though, we may not have a real console

**Comment by 304NotModified** [comment]
Which NLog version ? This should be Fixed already.

**Comment by techie55** [comment]
I was referring to the 4.3.10 version. Yes, I know this has been fixed in 4.4.1
