### ISSUE TITLE
Is there any way to include the achieve name format for today's file?

### ISSUE THREAD

**Issue by AnderssonPeter** [NLog/NLog#1774]
Is there any way to include the achieve name format for today's file?
The idea is to remove the need for a rename, i still want nlog to delete old files.
(I will be having tools that monitor the files and im unsure what happens if nlog tries to rename them in the middle of a read of the file).

```
 <target name="file" xsi:type="File" fileName="${logFile}"
            maxArchiveFiles="14" archiveEvery="Day" archiveNumbering="Date" archiveDateFormat="yyyy-MM-dd" encoding="UTF-8">
```

**Comment by 304NotModified** [comment]
I don't fully understand your question. Could you give an example? Thx!

**Comment by snakefoot** [comment]
Think the goal is to extend the fileName-layout with ${date:format=yyyy-MM-dd}, but still have the archive logic to remove old files.

**Comment by AnderssonPeter** [comment]
Ok ill explain it further.
Today the output is as follows:
```
Application.log <- Todays log file
Application.2016-11-21.log <- Yesterdays log file
Application.2016-11-20.log
...
```
I want today's logfile to have the same name standard as the archived files:
```
Application.2016-11-22.log <- Todays log file
Application.2016-11-21.log <- Yesterdays log file
Application.2016-11-20.log
```
There by removing the need to rename the file when it´s archived.

**Comment by 304NotModified** [comment]
Ah well, you could use indeed `${date:format=yyyy-MM-dd} ` in the filename, but when you have enabled remove logic, it should be in another directory. 

The different directory also applies if today's log is named "Application.log" IMO

**Comment by AnderssonPeter** [comment]
What do you mean with in another directory?
`Application.log` was just an example there are multiple applications logging to the same directory using nlog all with the same configuration except the log file name.

If i change the configuration to
```
 <target name="file" xsi:type="File" fileName="Application${date:format=yyyy-MM-dd}.log"
            maxArchiveFiles="14" archiveEvery="Day" archiveNumbering="Date" archiveDateFormat="yyyy-MM-dd" encoding="UTF-8">
```

Wouldn't that result in the following:
```
Application.2016-11-22.log <- Todays log file
Application.2016-11-21.2016-11-21.log <- Yesterdays log file
Application.2016-11-20.2016-11-20.log
...
```
?

**Comment by 304NotModified** [comment]
> What do you mean with in another directory?

`${basedir}\today.log`

and `${basedir}\archive\2016-11-21.log`

See https://github.com/NLog/NLog/issues/1681

**Comment by AnderssonPeter** [comment]
Im thoroughly confused how would that help with my problem?

**Comment by 304NotModified** [comment]
Sorry about the confusion. 

Your archive file and log files are in the same file directory? That will give issues when maxArchiveFiles has been set.

**Comment by AnderssonPeter** [comment]
Yes, but when does this issue happen i currently to have `maxArchiveFiles` set and i have don't issues? Do you mean when i append the date to the todays file?

**Comment by snakefoot** [comment]
PR #1993 will make it possible to perform archive cleanup within the logging-folder.
