### ISSUE TITLE
EventLog source needed otherwise exception stops program

### ISSUE THREAD

**Issue by R-oberto** [NLog/NLog#1777]
Type: Questions
NLog version: 4.2.3
Platform:  .Net 4.5 

This page( https://github.com/NLog/NLog/wiki/EventLog-target) mentions "When install/uninstalling, the event source is only created...". When does the install/uninstall happen? I don't understand what installation is being referred to.

Also, the target EventLog throws an exception if the source is not registered. This stops my program. Is the FallbackGroup config the way to log without stopping the program? If EventLog throws exception for any reason, I would want to log that fact to the other targets and disable it as a target. More generally, should I be logging in a try..catch for all logging?

One last thing, I aim to log thread-specific details like a CorrelationId. I see that the static variable is the recommended approach. How can I set the this custom property for the current thread so that when a log call is made, it has that value for this thread only? In Log4Net, I learned that there is log4net.GlobalContext.Properties and log4net.LogicalThreadContext.Properties. Does NLog have something similar?

**Comment by 304NotModified** [comment]
> This page( https://github.com/NLog/NLog/wiki/EventLog-target) mentions "When install/uninstalling, the event source is only created...". When does the install/uninstall happen? I don't understand what installation is being referred to.

You need to call them manually (and in the case of the eventlogtarget as admin):
`LogManager.Configuration.Install(new InstallationContext())` and `LogManager.Configuration.Uninstall(new InstallationContext())`



> Also, the target EventLog throws an exception if the source is not registered. This stops my program. Is the FallbackGroup config the way to log without stopping the program?

The fallbackgroup will fallback to another target in case of an exception.

> More generally, should I be logging in a try..catch for all logging?

That not needed, disable throwing errors. e.g. `<nlog ThrowExceptions="false">` or `LogManager.ThrowExceptions=false;`

What is needed is updating to NLog 4.3. Error handling of NLog itself is greatly improved in that version.

**Comment by 304NotModified** [comment]
> In Log4Net, I learned that there is log4net.GlobalContext.Properties and log4net.LogicalThreadContext.Properties. Does NLog have something similar?

Yes, the MDLC or MDC. See https://github.com/NLog/NLog/wiki/MDC-Layout-Renderer

**Comment by 304NotModified** [comment]
Updated the wiki: installing targets: https://github.com/NLog/NLog/wiki/Installing-targets

**Comment by R-oberto** [comment]
Ok. Thanks. That will all work great!
