### ISSUE TITLE
add Google Cloud Logging Target

### ISSUE THREAD

**Issue by ctaggart** [NLog/NLog#1794]
**Type** (choose one):
- Feature request

Google Cloud team has created a log4net appender. Many of our applications use NLog, and we would like to continue using it instead. We would like to target Google Cloud Logging for our apps that are hosted in Google Cloud and for a few on premise.

https://cloud.google.com/logging/
https://cloud.google.com/logging/docs/

https://www.nuget.org/packages/Google.Logging.Log4Net/
A getting started I made is [here](https://github.com/GoogleCloudPlatform/google-cloud-dotnet/issues/466#issuecomment-262877086). Their implementation is [here](https://github.com/GoogleCloudPlatform/google-cloud-dotnet/tree/master/apis/Google.Logging.V2/Google.Logging.Log4Net) with GoogleStackdriverAppender.cs, LogUploader.cs, & MemoryLogQueue.cs being the main files.

A new NLog targets just needs to do something similar using the same underlying library dependency of:
https://www.nuget.org/packages/Google.Logging.V2/

**Comment by 304NotModified** [comment]
Good idea!

If we guide you to create the target, could you code it? As far as I understand, we need a dependency to https://www.nuget.org/packages/Google.Logging.V2/?

**Comment by ctaggart** [comment]
@304NotModified, possibly. Yes, the new target would need to take a dependency on Google.Logging.V2, which is currently at 1.0.0-beta04. Do you have reusable code for queuing a batch of log statements and triggering them to be sent? I imagine that is pretty common.

**Comment by 304NotModified** [comment]
I think the mail target is a good example. Check the write methods. 

https://github.com/NLog/NLog/blob/master/src/NLog/Targets/MailTarget.cs

**Comment by adyshimony** [comment]
Any news on this?

**Comment by 304NotModified** [comment]
not by us. I think it's easy to add, but we don't have any experience/test environment for google logging.

**Comment by snakefoot** [comment]
Think inspiration can be found here:

https://github.com/manigandham/serilog-sinks-googlecloudlogging

The official log4net appender looks a little more convoluted:

https://github.com/GoogleCloudPlatform/google-cloud-dotnet/tree/master/apis/Google.Cloud.Logging.Log4Net

**Comment by snakefoot** [comment]
It is now available on nuget: https://www.nuget.org/packages/Google.Cloud.Logging.NLog/

**Comment by 304NotModified** [comment]
🎉  nice!
