### ISSUE TITLE
nested application issue: aspnetsession Layout renderer

### ISSUE THREAD

**Issue by yosz** [NLog/NLog#180]
I've got two applications in IIS. Application two runs "under" (nested) application one in IIS. Nlog is configured in application one (main application) and one appender is using ${aspnet-session:variable=UserLogin} layout renderer. Application two hosts web service with BasicAuthentication set.

When I access application two it crashes with an exception (IIS tries to load parent web.config from application one and crashes):

```
web.config 
----> NLog.NLogConfigurationException: Error when setting property 'FileName' on File Target[usertrace] 
----> System.ArgumentException: LayoutRenderer cannot be found: 'aspnet-session'
```

Workaround is simple - in application one's web.config nlog section should look like this

```xml
<location path="." inheritInChildApplication="false">
    <nlog ...> ..... </nlog>
</location>
```

But it worked in NLog 1 ;)

**Comment by 304NotModified** [comment]
I was thinking. Is this really a bug?


I don't think this is a problem if nlog is configured nlog.config (instead of web.config)

**Comment by 304NotModified** [comment]
this is probably not a bug. Feel free to reopen if you think otherwise
