### ISSUE TITLE
Installing NLog manually (or for combined C++/C# solution)

### ISSUE THREAD

**Issue by zotty** [NLog/NLog#1800]
I have a solution that contains both a C++ and a C# .NET Winforms project.  This seems to cause problems in installing through the NuGet manager (error below).  Is there a way I could install NLog manually?  I've tried referencing NLog.dll, and have added the files NLog.config, NLog.xsd, and although my program compiles and runs, no logfile is created (I'm using log.trace and log.debug)

**Type**: Question

**NLog version**: 4.2.3.11

**Platform**: .Net 4.5

**Current NLog config** (xml or C#, if relevant)

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <targets>
        <target name="logfile" xsi:type="File" fileName="log.txt" />
    </targets>

    <rules>
        <logger name="*" minlevel="Trace" writeTo="logfile" />
    </rules>
</nlog>
```

Install-Package NLog -Version 4.3.11
Attempting to gather dependency information for package 'NLog.4.3.11' with respect to project 'PicUSB_Host', targeting 'native,Version=v0.0'
Attempting to resolve dependencies for package 'NLog.4.3.11' with DependencyBehavior 'Lowest'
Resolving actions to install package 'NLog.4.3.11'
Resolved actions to install package 'NLog.4.3.11'
Install failed. Rolling back...
Package 'NLog.4.3.11' does not exist in project '****C++ Project Name ****'
Package 'NLog.4.3.11' does not exist in folder '.....\packages'
Install-Package : Could not install package 'NLog 4.3.11'. You are trying to install this package into a project that targets 'native,Version=v0.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
At line:1 char:1
+ Install-Package NLog -Version 4.3.11
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by 304NotModified** [comment]
Well we don't support the Native platform or C++

But if this could be easily solved, let me know. 

Is this also fixed with NETSTANDARD in the future?

**Comment by 304NotModified** [comment]
PS: you could check the internal log if it compiles. See https://github.com/NLog/NLog/wiki/Internal-logging

**Comment by snakefoot** [comment]
If you have a solution that contains WinForms-project that uses a C++/Native-project, then you can configure NuGet just to get NLog for the WinForms-project, then just change your C++/Native-project to load and use the NLog.dll manually (without using NuGet).

**Comment by 304NotModified** [comment]
Cool, which version of NLog.dll it should use? 

Current package (NLog 4.3.11)

![image](https://cloud.githubusercontent.com/assets/5808377/20767914/4a2099ac-b73c-11e6-894e-4228fcb5088d.png)

**Comment by snakefoot** [comment]
Using a managed dll from C++ project required CLI/Interop. Unless you experiment with building the managed DLL to have a COM-interface.

You will ofcourse use the NLog.dll that matches the .NET version of the Winforms-project.

**Comment by 304NotModified** [comment]
> Using a managed dll directly from C++ project required CLI/Interop. Unless you experiment with building the managed DLL to have a COM-interface.

NLog 2 was supporting C++ ("NLogC"), but that has been dropped. http://nlog-project.org/2013/12/14/nlog-3-0.html

**Comment by 304NotModified** [comment]
@zotty is this still an issue?

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, let us know!
