### ISSUE TITLE
Manually archive file target?

### ISSUE THREAD

**Issue by mbcrawfo** [NLog/NLog#1803]
**Type**: Question

**NLog version**: 4.3.7

**Platform**: .Net 4.5

**Current NLog config** (xml or C#, if relevant)

```xml
<target name="myJobLogfile" type="File"
              layout="${level} | ${date} | ${callsite:includeSourcePath=false:cleanNamesOfAnonymousDelegates=true} | ${message} ${exception:format=tostring}"
              fileName="${basedir}/logs/jobs/myJob.txt" maxArchiveFiles="30"
              archiveFileName="${basedir}/logs/myJob.{#}.txt" archiveNumbering="Date"
              archiveDateFormat="yyyyMMdd HHmm" archiveEvery="Hour" />

```

I have a set of jobs that run regularly in the background of an ASP.Net MVC application (using Hangfire).  Each job is set up with its own separate logger and file target, and I would like each job to write to a fresh log file every time it starts.  I don't think I can completely configure that in the config (though it would be awesome if I could), but I also have failed so far to find a way in code to say "perform an archive operation".  What's the best way to accomplish this goal?

**Comment by 304NotModified** [comment]
Currently there is no way to manually invoke the creation of archive files.


What you could do is creating a new log file with every restart, by using the MDLC (or GDC)

e.g.

    fileName="${basedir}/logs/jobs/myJob-run{mdlc:item=run_number}.txt"


and set on each start

    MappedDiagnosticsLogicalContext.Set("run_number", "something");

Another way is to add the start time in the filename: 

    fileName="${basedir}/logs/jobs/myJob-started-${date:cached=true}.txt"

**Comment by mbcrawfo** [comment]
Thanks.  I was hoping to have NLog manage the archiving, but c'est la vie.
