### ISSUE TITLE
Stuck Thread

### ISSUE THREAD

**Issue by efinovation** [NLog/NLog#1806]
I am working with MS on a support case having to do with a mysterious issue on a business application built with .NET 4.5 MVC WebApi 2.0. The issue being, about once every 3 months the app response times go from under 10 seconds (on average) to over 2 minutes and becomes so severe the only working recovery option seems to be recycling the app pool. As part of the case we are creating IIS dump files for this application when any request takes longer than 30 seconds. MS has found while analyzing these dump files several instances of stuck threads in NLog. MS and I are not entirely sure if NLog is the cause of our latency issue or something deeper is the issue. Either way we need to understand what is happening with these stuck threads. Also, this is my first time opening any type of case on any Git Hub repo, so sorry ahead of time if I botched any aspect of this.

I cannot attach the dump files they are compressed to about 320 MB (or ~100MB each). How should I get them to you?

- Question

NLog 3.2.0.0
NLog.Extended 3.2.0.0
NLog.Extensions 1.0.1.0
NLog.Web 1.0.8.0

There are no errors in the internal NLog log file.

Below is the current NLog.config. This particular version has a bunch of the ASP layout renderers turned off by replacing those tokens with ${logger}. So you may see that in several places. This was done because there was some question from MS about the various AspReqeust layout renderers that we were using. And to get them passed that I basically removed that problem/distraction.
```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      throwExceptions="true"
      internalLogFile="d:/logs/Apps/SalesScript/SalesScript-nlog.txt"
      internalLogLevel="Error">
  <extensions>  
    <add assembly="NLog.Extensions"/>
    <add assembly="NLog.Extended" />
    <add assembly="NLog.Web"/>
    <add assembly="Efinancial.Lib.Utilities"/>
  </extensions>  
  <!-- 
  See https://github.com/nlog/nlog/wiki/Configuration-file 
  for information on customizing logging rules and outputs.
   -->
  <targets>
    <target xsi:type="AsyncWrapper"
            name="CsvFile"
            queueLimit="10000"
            timeToSleepBetweenBatches="50"
            batchSize="100"
            overflowAction="Grow">
      <target name="CsvFile" 
      	      xsi:type="File"
              fileName="d:/logs/Apps/SalesScript/${shortdate}_${date:format=HH}_SalesScript.csv"
              concurrentWrites="true">
        <layout xsi:type="CsvLayout" >          
          <column name="MsgNumber" layout="${counter}" />
          <column name="Time" layout="${longdate}" />
          <column name="Level" layout="${uppercase:${level}}"/>
          <column name="Logger" layout="${logger}"/>
          <column name="Message" layout="${message}"/>
          <column name="StackTrace" layout="${stacktrace}"/>
          <column name="Exception" layout="${exception:maxInnerExceptionLevel=3:format=Message, StackTrace}"/>
          <column name="ContextId" layout="${activityid}" />
          <column name="RequestId" layout="${mdc:item=requestId}" />
          <column name="ClientIp" layout="${logger}" />
          <column name="RefContextId" layout="${event-context:item=refCntxtId"/>
          <column name="Request" layout="${logger}" />
          <column name="InteractionId" layout="${logger}" />
          <column name="User" layout="${logger}" />
          <column name="PolicyId" layout="${logger}" />
          <column name="MachineName" layout="${machinename}" />
        </layout>
      </target>
    </target>

    <target xsi:type="AsyncWrapper"
            name="LoggerDatabase"
            queueLimit="10000"
            timeToSleepBetweenBatches="50"
            batchSize="100"
            overflowAction="Grow">
      <target xsi:type="Database"
              name="LoggerDatabase"
              dbProvider="System.Data.SqlClient"
              keepConnection="false"
              connectionStringName="LoggerConnection"
              commandType="StoredProcedure"
              commandText="dbo.CreateLog ">
        <parameter name="@MsgNumber" layout="${counter}" />
        <parameter name="@Time" layout="${longdate}"/>
        <parameter name="@Level" layout="${uppercase:${level}}"/>
        <parameter name="@Logger" layout="${logger}"/>
        <parameter name="@Message" layout="${message}"/>
        <parameter name="@StackTrace" layout="${stacktrace}"/>
        <parameter name="@Exception" layout="${exception:maxInnerExceptionLevel=3:format=Message, StackTrace}"/>
        <parameter name="@ContextId" layout="${activityid}"/>
        <parameter name="@RefContextId" layout="${event-context:item=refCntxtId}"/>
        <parameter name="@RequestId" layout="${mdc:item=requestId}"/>
        <parameter name="@ClientIp" layout="${aspnet-request:serverVariable=remote_host}" />
        <parameter name="@CustomEntity" layout="${event-context:item=Entity}"/>
        <parameter name="@CustomId" layout="${aspnet-request:form=Interaction[InteractionId]}"/>
        <parameter name="@Detail" layout="${aspnet-request-summary}"/>
        <parameter name="@Application" layout="${literal:text=SalesScript}"/>
        <parameter name="@Host" layout="${machinename}"/>
      </target>
    </target>

    <target xsi:type="AsyncWrapper"
          name="ServiceCallLogFile"
          queueLimit="10000"
          timeToSleepBetweenBatches="50"
          batchSize="100"
          overflowAction="Grow">
      <target name="ServiceCallLogFile"
              xsi:type="File"
              fileName="c:/logs/Apps/SalesScript/${shortdate}_ServiceLog_SalesScript.csv"
              concurrentWrites="true">
        <layout xsi:type="CsvLayout" >          
          <column name="Time" layout="${longdate}" />
          <column name="ContextId" layout="${activityid}" />
          <column name="ServiceProvider" layout="${event-context:ServiceProvider}"/>
          <column name="Direction" layout="${event-context:Direction}" />
          <column name="Payload" layout="${message}"/>
          <column name="Application" layout="${literal:text=SalesScript}" />          
        </layout>
      </target>
    </target>

    <target xsi:type="AsyncWrapper"
          name="ServiceCallLogDB"
          queueLimit="10000"
          timeToSleepBetweenBatches="50"
          batchSize="100"
          overflowAction="Grow">
      <target xsi:type="Database"
              name="ServiceCallLogDB"
              dbProvider="System.Data.SqlClient"
              keepConnection="false"
              connectionStringName="LoggerConnection"
              commandType="StoredProcedure"
              commandText="dbo.CreateServiceCallLog ">
        <parameter name="@ContextId" layout="${activityid}"/>
        <parameter name="@ServiceProvider" layout="${event-context:ServiceProvider}"/>
        <parameter name="@Direction" layout="${event-context:Direction}"/>
        <parameter name="@Payload" layout="${message}"/>
        <parameter name="@ConsumingApplication" layout="${literal:text=SalesScript}"/>
      </target>
    </target>

    <target xsi:type="BufferingWrapper"
            name="EmailAlert"
            bufferSize="1">
      <target xsi:type="Mail"
              name="EmailAlert"
              encoding="UTF-8"
              enableSsl="false"
              smtpServer=""
              subject="SalesScript ${machinename}"
              addNewLines="true"
              layout="${longdate}${newline}Logger: ${logger}${newline}Level: ${uppercase:${level}}${newline}Message: ${message}${newline}ContextId: ${activityid}${newline}Id: ${event-context:item=Id}${newline}Stack: ${stacktrace}${newline}InteractionId:${aspnet-request:form=Interaction[InteractionId]}${newline}PolicyId:${aspnet-request:form=Interaction[PolicyId]}"
              to="toErrorEmailExample@test.com"
              from="fromErrorEmailExample@test.com"
              useSystemNetMailSettings="true" />
    </target>    
  </targets>
	<rules>  
    <logger name="Efinancial.Lib.Utilities.Logging.ServiceCallLogger.*"
            minlevel="Off"
            writeTo="ServiceCallLogFile" />
    <logger name="Efinancial.Lib.Utilities.Logging.ServiceCallLogger.*"
            minlevel="Off"            
            writeTo="ServiceCallLogDB"
            final="true">
    </logger>
    <!-- EntityLogger -->
    <logger name="Efinancial.Lib.Utilities.Logging.EntityLogger"
            minlevel="Off"
            writeTo="LoggerDatabase"
            final="true">
    </logger>
    <logger name="Efinancial.Telephony.SalesScript.Controllers.BreakGrantedController" level="Warn" writeTo="LoggerDatabase"></logger>
    <logger name="*" minlevel="Trace" writeTo="CsvFile"/>		
		<logger name="*" minlevel="Off" writeTo="LoggerDatabase"/>
		<logger name="*" minlevel="Error" writeTo="EmailAlert"/>
	</rules>
</nlog>
```
web config system.net settings
```xml
 <system.net>
    <mailSettings>
      <smtp deliveryMethod="SpecifiedPickupDirectory">
        <network host="localhost" port="25" />
        <specifiedPickupDirectory pickupDirectoryLocation="C:\inetpub\mailroot\pickup" />
      </smtp>
    </mailSettings>
  </system.net>
```

# MS case info:
For these three dump files the same stack is stuck for the entire duration (And these are 300MB each, need to know how to upload for this case).
w3wp__SalesScript__PID__6736__Date__11_07_2016__Time_11_55_32AM__166__iisfreb!FREB_LOG_FILE_MANAGER__WriteLogFile
w3wp__SalesScript__PID__6736__Date__11_07_2016__Time_11_55_41AM__932__iisfreb!FREB_LOG_FILE_MANAGER__WriteLogFile
w3wp__SalesScript__PID__6736__Date__11_07_2016__Time_11_55_50AM__746__iisfreb!FREB_LOG_FILE_MANAGER__WriteLogFile

MS highlighted the following portion of the stack trace:

```
0b 25b5dfd0 2182851e NLog!NLog.Internal.ObjectGraphScanner.ScanProperties[[System.__Canon, mscorlib]](System.Collections.Generic.List`1<System.__Canon>, System.Object, Int32, System.Collections.Generic.Dictionary`2<System.Object,Int32>)+0x57
0c 25b5e014 21828572 NLog!NLog.Internal.ObjectGraphScanner.ScanProperties[[System.__Canon, mscorlib]](System.Collections.Generic.List`1<System.__Canon>, System.Object, Int32, System.Collections.Generic.Dictionary`2<System.Object,Int32>)+0x266
0d 25b5e058 21828572 NLog!NLog.Internal.ObjectGraphScanner.ScanProperties[[System.__Canon, mscorlib]](System.Collections.Generic.List`1<System.__Canon>, System.Object, Int32, System.Collections.Generic.Dictionary`2<System.Object,Int32>)+0x2ba
0e 25b5e09c 21828572 NLog!NLog.Internal.ObjectGraphScanner.ScanProperties[[System.__Canon, mscorlib]](System.Collections.Generic.List`1<System.__Canon>, System.Object, Int32, System.Collections.Generic.Dictionary`2<System.Object,Int32>)+0x2ba
0f 25b5e0e0 21828288 NLog!NLog.Internal.ObjectGraphScanner.ScanProperties[[System.__Canon, mscorlib]](System.Collections.Generic.List`1<System.__Canon>, System.Object, Int32, System.Collections.Generic.Dictionary`2<System.Object,Int32>)+0x2ba
10 25b5e110 2182d6fb NLog!NLog.Internal.ObjectGraphScanner.FindReachableObjects[[System.__Canon, mscorlib]](System.Object[])+0xd0
11 25b5e128 2182d5fa NLog!NLog.Internal.TargetWithFilterChain.PrecalculateStackTraceUsage()+0x33
12 25b5e164 2182d23e NLog!NLog.LogFactory.GetTargetsByLevelForLogger(System.String, System.Collections.Generic.IList`1<NLog.Config.LoggingRule>, NLog.Internal.TargetWithFilterChain[], NLog.Internal.TargetWithFilterChain[])+0x1fa
13 25b5e198 21822b34 NLog!NLog.LogFactory.GetConfigurationForLogger(System.String, NLog.Config.LoggingConfiguration)+0x56
14 25b5e1dc 21822959 NLog!NLog.LogFactory.GetLogger(LoggerCacheKey)+0x1c4
15 25b5e20c 2182290d NLog!NLog.LogFactory.GetLogger(System.String)+0x39
```

**Comment by snakefoot** [comment]
Are you constantly creating new NLog Logger-objects ? Maybe even using a different Logger-Name every time?

There is an overhead every time you allocate a NLog Logger-object, as it has to check the configuration what Targets can be reached by the Logger.

**Comment by 304NotModified** [comment]
AFAIK FindReachableObjects is only called when the config has been changed. Have to check that.

**Comment by efinovation** [comment]
> Are you constantly creating new NLog Logger-objects ? Maybe even using a different Logger-Name every time?

Every class where we want logging we inherit from a base class that calls NLog.LogManager.GetLogger(GetType().FullName)) . We inherit from this base in most of our business layer and repo layer objects. And in some of the application layer, like in certain controllers and other application logic. Hopefully this answer your question. Let me know if you need more info.

> AFAIK FindReachableObjects is only called when the config has been changed. Have to check that.

I think the last changes we made to the NLog.config were about an hour before these stack traces

**Comment by snakefoot** [comment]
> we inherit from a base class that calls NLog.LogManager.GetLogger(GetType().FullName))

How many objects do you allocate per second, that inherit from this base class?

Maybe consider changing the logic into this, as the Logger is thread-safe:

class BaseClass
{
    virtual Logger ClassLogger { get; }
}

class BaseClassT<T>
{
      static Logger _logger = NLog.LogManager.GetLogger(typeof(T).FullName));
      override Logger ClassLogger { get { return _logger; } }
}

class SpecialClass : BaseClassT<SpecialClass>

**Comment by 304NotModified** [comment]
> AFAIK FindReachableObjects is only called when the config has been changed.

Checked it, FindReachableObjects  is only called after the first usage after a config change. 

> Maybe consider changing the logic into something like this, as the Logger is thread-safe:

That's indeed a big improvement (static loggers are recommend), but I don't think the isssue is there. 

> app response times go from under 10 seconds (on average) to over 2 minutes

If you are use logging, you could determine which operation takes 2 minutes? 

I could also advise to use 1 asyncTargetWrapper and include multiple targets in it. So instead of

```xml
 <target xsi:type="AsyncWrapper" ... >
      <target ..>
  </target>
 <target xsi:type="AsyncWrapper" ... >
      <target ..>
  </target>
 <target xsi:type="AsyncWrapper" ... >
      <target ..>
  </target>
```
Go for (when possible_

```xml
 <target xsi:type="AsyncWrapper" ... >
      <target ..>
      <target ..>
      <target ..>
  </target>
```

**Comment by 304NotModified** [comment]
It this still an issue?

**Comment by efinovation** [comment]
> If you are use logging, you could determine which operation takes 2 minutes?
Microsoft and my team have not been able to identify the cause, they (MS) noticed this same stuck thread throughout the 2 minutes and theorized this was the cause but it could also just be a symptom. We have also seen in other instances (but dont have the perfmon for this case) where IO on the server completely stops during this period which could be causing the NLog read issue.

> Is this still an issue?
Its hard to say if its still an issue or not since the frequency is once every couple of months. My plan is to make the AsyncWrapper changes and let that soak for a while and see what happens. If we still have the issue then make the base logger static and rinse and repeat.

**Comment by snakefoot** [comment]
Not sure how NLog handles this, but I can see that you have several targets with the same name:

name="CsvFile"
name="LoggerDatabase"
name="ServiceCallLogFile"
name="ServiceCallLogDB"
name="EmailAlert"

**Comment by efinovation** [comment]
> I could also advise to use 1 asyncTargetWrapper and include multiple targets in it. So instead of

I tried the 1 AsyncTargetWrapper to rule them all and got the following exception:
NLog.NLogConfigurationException: Wrapped target already defined.
` <targets>
    <target xsi:type="AsyncWrapper"
            name="IceCube"
            queueLimit="10000"
            timeToSleepBetweenBatches="50"
            batchSize="100"
            overflowAction="Grow">
      <target xsi:type="Database"
              name="LoggerDatabase"
              dbProvider="System.Data.SqlClient"
              keepConnection="false"
              connectionStringName="LoggerConnection"
              commandType="StoredProcedure"
              commandText="dbo.CreateLog ">       
        <parameter name="@Time" layout="${longdate}"/>
        <parameter name="@Level" layout="${uppercase:${level}}"/>
        <parameter name="@Logger" layout="${logger}"/>
        <parameter name="@Message" layout="${message}"/>
        <parameter name="@StackTrace" layout="${stacktrace}"/>
        <parameter name="@Exception" layout="${exception:maxInnerExceptionLevel=3:format=Message, StackTrace}"/>       
      </target>
      <target name="CsvFile"
      	      xsi:type="File"
              fileName="c:/Logs/Apps/SalesScript/${shortdate}_SalesScript.csv"
              concurrentWrites="true">
        <layout xsi:type="CsvLayout" >          
          <column name="Time" layout="${longdate}" />
          <column name="Level" layout="${uppercase:${level}}"/>
          <column name="Logger" layout="${logger}"/>
          <column name="Message" layout="${message}"/>
          <column name="StackTrace" layout="${stacktrace}"/>
          <column name="Exception" layout="${exception:maxInnerExceptionLevel=3:format=Message, StackTrace}"/>          
        </layout>
      </target>
    </target>   
  </targets>
	<rules>  
    <logger name="*" minlevel="Trace" writeTo="CsvFile"/>		
		<logger name="*" minlevel="Off" writeTo="LoggerDatabase"/>		
	</rules>`



> Not sure how NLog handles this, but I can see that you have several targets with the same name:

name="CsvFile"
name="LoggerDatabase"
name="ServiceCallLogFile"
name="ServiceCallLogDB"
name="EmailAlert"

Can you please clarify? I am confused on the name concern when all the above names are different. Thanks!

**Comment by snakefoot** [comment]
> NLog.NLogConfigurationException: Wrapped target already define

You can only have a single target inside the AsyncWrapper.

> Can you please clarify?

Try to use a text search on this web-page for the above names, then you will see multiple targets in the samed nlog.config matching the same name.

**Comment by snakefoot** [comment]
Also noticed that you have enabled this setting:

> throwExceptions="true"

This is only intended for unit-testing, as it can stop NLog completely or make the host-application crash with unhandled exception.

**Comment by snakefoot** [comment]
Actually I can see that @304NotModified has fixed a bug that matches this stack-trace. #1303

**Comment by efinovation** [comment]
Alright several light bulbs have gone off, thanks snakefoot.
On the topic of AsyncWrappers we will make the change as you described using the short hand notation.

On the topic of duplicated names you are right, I was thinking target wrappers were a different thing, but clearly they are another type of target. This also gets fixed by using the short hand notation.

Good catch on the ThrowExceptions we will also turn that off.

**Comment by snakefoot** [comment]
>  short hand notation

Just remember to read the documentation about how overflowAction=Discard works (It is different from your current overflowAction=Grow).

As an alternative you could just add the suffix "Wrapped" to all targets inside an AsyncWrapper. Ex. CsvFileWrapped.

**Comment by snakefoot** [comment]
If you continue to use NLog ver. 3.2.0.0, then you should really consider to implement the Logger as a static-object (As allocating the Logger really exercises this bug). Have updated my previous comment above with another example for how to implement a static-logger. Also updated by other previous comment with a different way to implement a default async-wrapper, where you can customize it.

**Comment by 304NotModified** [comment]
> Actually I can see that @304NotModified has fixed a bug that matches your stack-trace. #1303, #1310 and #1316. Guess it is time to upgrade from NLog 3.2.0.0 :)

Yes indeed, it should not be difficult to migrate to NLog, almost everything is still there (but then deprecated), see also http://nlog-project.org/2015/06/09/nlog-4-has-been-released.html

**Comment by efinovation** [comment]
> Actually I can see that @304NotModified has fixed a bug that matches your stack-trace. #1303, #1310 and #1316. Guess it is time to upgrade from NLog 3.2.0.0 :)

I agree! Upgrading NLog is pretty much at the bottom of our backlog currently but seems like we need to up the priority based on this discovery.

**Comment by 304NotModified** [comment]
> NLog 3.2.0
> Xharze released this on Dec 21, 2014 · 2099 commits to master since this release

A lot of changes since 3.2.0. Pretty sure NLog has improved a lot :)

**Comment by efinovation** [comment]
It seems like we can close this. Lots of suggesting we can try that were contributed. It will take some time to try them and see if we still have issue. I can open another ticket if something else is discovered. Thanks to all who help out!

**Comment by 304NotModified** [comment]
:+1:
