### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by ZhiweiGaby** [NLog/NLog#1808]
Hello. 
I can't make NLog work in my test project (winform).

Here is the config file:
```
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      internalLogLevel="Trace"
      internalLogFile="E:\travaille\Share\Server\WebStock\Log\log.txt">  
  <targets>     
    <target name="logfile" xsi:type="File" fileName="E:\travaille\Share\Server\WebStock\Log\logfile.txt"/>            
   <rules>
        <logger name="*" minlevel="Info" writeTo="logfile" />
    </rules>
  </targets>  
</nlog>
```

Code in C#
private static Logger logger = LogManager.GetCurrentClassLogger();

 private void button1_Click(object sender, EventArgs e)
        {
            logger.Log(LogLevel.Info, "test me");
        }

Result>
I do get  internal log file (log.txt), but i can't get logfile.txt

Sorry to create a issue, but i can't find the problem by myself:-(

Best regards
Zhiwei LIU

**Comment by 304NotModified** [comment]
Please post the internal log :)

**Comment by ZhiweiGaby** [comment]
I find finally. 
balise rules should be outside of targets. 
I was stupide.
