### ISSUE TITLE
Layoutable non-string values

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#1811]
Current approach:

render, parse.

e.g.

`Convert.ToInt64(this.MaxKilobytes.Render(logEvent), CultureInfo.InvariantCulture);`

This isn't optimal. 

Proposal, replace Layout with `Layout<int>` ~`IntLayout`,~ and let `render` do a parse.

related #1234 

update: We have now also an implicit conversion from `string` to `layout`. For the `int` case it should be also from `int` to `layout` (fixed values), hence we need `IntLayout` or something like that.

**Comment by snakefoot** [comment]
> That is possible, but then the property value is not evaluated runtime.

If the configuration-logic was able to set the correct properties at startup, then the configuration-logic should also be able to set the correct properties on reload (Without using dedicated Layout-properties). Would also require some logic regarding perform Reinitialize on a running system.

**Comment by 304NotModified** [comment]
What would be the type of the property then @snakefoot, `int`? I don't see how that would work :(

**Comment by snakefoot** [comment]
Not sure I understand. You have some logic already that can re-apply the configuration. The configuration-logic reads string-values and then parses it so it matches the property-type (string/int/enum or whatever)

Now this re-apply logic "just" need to recognize layout-format, and then render first to string, before again parsing it to the matching property-type.

**Comment by 304NotModified** [comment]
example

```
class MyCustomLayoutRender
{
    
    Layout MaxCount  {get;set;} //"int"
}

var l = new MyCustomLayoutRender();
l.MaxCount  = "${gdc:maxCount}";
```

Currently we have to do a int parse after render.

- If we change the property type to `int`, this won't work currently (e.g. GDC, we need "subscriptions" then)
- We could make dedicated `Layout` types, like `IntLayout`, to "hide" the parse and do some smarter conversions/caching.

**Comment by snakefoot** [comment]
If configuring stuff from the code, there I have much stronger eco-system than Layout-renderer can ever provide.

I was thinking the Layout-Property-Parsing-Logic made sense when using the XML-config, like most people are using:

```
<targets>
  <target xsi:type="EventLog" maximumKilobytes="${gdc:maxSize}" />
</targets>
```

**Comment by 304NotModified** [comment]
well there we're multiple request for changing variables on runtime.

I think also 90% of the cases are from XML config, but we can't drop the 10%

**Comment by snakefoot** [comment]
Anyway, just ignore my rant, but please make the Layout-properties like this:

```
struct LayoutProperty<T>
{
     public T Value;
     public Layout Laoyut;
}
```

Though the struct will be mutable, then access to Value will be cheap.

**Comment by 304NotModified** [comment]
> But by assigning Layout-strings directly to properties in .NET-code? Instead of just changing the NLog-XML-config or flipping the properties directly using .NET-code ?

    filename = "${basedir}/file1.txt" ? ;)


> struct LayoutProperty<T>

Well that doesn't work as I can't write a implicit conversion from `T` to ` LayoutProperty<T>` (e.g. `int` to `LayoutProperty<int>`). That's unfortunately, as we have to make a lot LayoutProperties

**Comment by snakefoot** [comment]
> filename = "${basedir}/file1.txt" ? ;)

That sounds just like:

> filename = LayoutParser<string>.Read("${basedir}/file1.txt");
