### ISSUE TITLE
Logging stops using archiving and async target

### ISSUE THREAD

**Issue by ChristianHoe** [NLog/NLog#1826]
Hi,

I tried to use archiving (DateAndSequence) in combination with async target and keepFileOpen.
Testing this feature locally with our database log worked fine and the archive files where created like expected (Database 20161205.1.log, Database 20161205.2.log ....).

Putting same configuration under stress running multiple WCF-Requests causing the logging to stop. Leaving a valid log file like Database ${522or5ae}.0.log and no further activity.

First I thought it could be something like #1029 but updating from 3.2.0 to 4.3.11 did not help. It looks like the logger dies silently the very moment the current file is archived (see internal log). 

The WCF Service is running on Windows Server 2008 and .Net-Framework 4.5.1.

My current work around is using the archiving on daily base only. but files with size of 1.5 GB and more are not easy to handle.

[nlog.config.txt](https://github.com/NLog/NLog/files/631357/nlog.config.txt)

~nlog-internal.log.txt~

**Comment by 304NotModified** [comment]
Please fill in the template, thanks!

**Comment by ChristianHoe** [comment]
**Type**
- Bug

**NLog version**: 4.3.11

**Platform**: .Net 4.5

**Current NLog config** see attached file

In case of a BUG:
- No logs are written after archiving the first log
- Logs should be written
- Internals-Log attached
- No Exception
- Not using DateAndSequence
- No
- No

**Comment by 304NotModified** [comment]
thx!

**Comment by 304NotModified** [comment]
[nlog-internal.log.txt](https://github.com/NLog/NLog/files/631714/nlog-internal.log.txt)

**Comment by ChristianHoe** [comment]
Can you please remove the smtp entry from the internal log also? Thx.

**Comment by 304NotModified** [comment]
yes done :)

**Comment by snakefoot** [comment]
@ChristianHoe  Could you try and add OpenFileCacheTimeout=10 to the file-target configuration? And see if the problem is "fixed".

**Comment by 304NotModified** [comment]
@ChristianHoe I'm adding more internal logging. Could you test it with a trace internal log soon?

**Comment by ChristianHoe** [comment]
Sorry, I am on vacation till begin of january. What is the best way to get the new tracing? Nuget?

**Comment by 304NotModified** [comment]
@ChristianHoe have a good vacation!



> What is the best way to get the new tracing? Nuget?

I mean the internal log as described here: https://github.com/NLog/NLog/wiki/Internal-logging

**Comment by snakefoot** [comment]
Maybe the question was how to get the build that includes this PR: #1872

**Comment by 304NotModified** [comment]
Ah,

1. go to https://github.com/NLog/NLog/pull/1872
2. go to details of the PR build: 
![image](https://cloud.githubusercontent.com/assets/5808377/21625727/5159755e-d20d-11e6-8d1f-13486f0413b9.png)
3. click on artifacts on the right:
![image](https://cloud.githubusercontent.com/assets/5808377/21625767/909443de-d20d-11e6-9c08-12a4f025853f.png)


4. Download and install (I use the local nuget storage for that)
![image](https://cloud.githubusercontent.com/assets/5808377/21625790/b77041ce-d20d-11e6-99ca-6dacb0223e44.png)

short-link for this case: https://ci.appveyor.com/api/buildjobs/6f8felbsc9agdfe5/artifacts/build%2Fbin%2Frelease%2FNuGetPackages%2FNLog.4.4.nupkg
