### ISSUE TITLE
Can support object dump？

### ISSUE THREAD

**Issue by FishThirteen** [NLog/NLog#1827]
**Type** (choose one):

- Feature request
Could support obj dump similar to serilog?

in case of a FEATURE REQUEST:
 - Why do we need it?
1.  We often need to dump object to logging file
2. Supporting object dump natively could improve the performance and reduce dependencies despite we can use the thirty part tools to dump object.

**Comment by 304NotModified** [comment]
I'm not sure, as I don't know what it do exactly ;)

So please give an example :)

**Comment by FishThirteen** [comment]
For example:
var position = new { Latitude = 25, Longitude = 134 };

logger.Info("the position: {0}", position);
Write the log: 
the position: { Latitude: 25, Logitude: 134 }

and support IList, IDictionary
var positions = new List<Position>() { new Position() { Latitude = 25, Longitude = 134 }, new Position() { Latitude = 10, Longitude = 20 } };
logger.Info("the positions: {0}", positions);
the position: [{Latitude: 25, Longitude: 134 },{Latitude: 10, Longitude: 20 }]

**Comment by 304NotModified** [comment]
thanks for the info!

We will add this in NLog 4.5, as part of the structural logging. See https://github.com/NLog/yamtp/issues/3

But this feature hasn't been written yet. Could you help us with that or help us performance test it?

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, let us know!
