### ISSUE TITLE
Callsite Without the Namespace

### ISSUE THREAD

**Issue by spottedmahn** [NLog/NLog#1832]
- Question
How can I log the callsite without the namespace?  I don't see an option here: https://github.com/NLog/NLog/wiki/Callsite-layout-renderer

**Example**

namespace SomeReallyCoolNamespace
{
       public class AwsomeClass{
                 public void DoIt(){}
       }
}

I want to see "AwesomeClass.DoIt" in my logging not "SomeReallyCoolNamespace.AwesomeClass.DoIt"

**NLog version**: 4.3.11

**Platform**:.Net 4.5

**Comment by 304NotModified** [comment]
This ins't possible right now. We use `method.DeclaringType.FullName;`.

We could make it optional. Any idea how we should name the option? 

Maybe `NameSpace` with default to `true`?

**Comment by ie-zero** [comment]
How about NamespaceIncluded = true?

**Comment by 304NotModified** [comment]
Yes that's even better!

**Comment by spottedmahn** [comment]
thanks!!

**Comment by 304NotModified** [comment]
OK, have opened a feature request ticket for it :) 

https://github.com/NLog/NLog/issues/1835

**Comment by 304NotModified** [comment]
This will be included in NLog 4.4!

**Comment by 304NotModified** [comment]
added to NLog 4.4 rc2: https://www.nuget.org/packages/NLog/4.4.0-rc2
