### ISSUE TITLE
Writing event without checking-bug

### ISSUE THREAD

**Issue by Grant-Liu** [NLog/NLog#1833]
In all places when the code writes log event, it should check if event is not null and length >0.
old code
 this.WrappedTarget.WriteAsyncLogEvent(logEvent);
new code.
if (logEvents != null && logEvents.Length > 0)

such as AsyncTargetWrapper.cs

**Comment by 304NotModified** [comment]
Hey!

Could you  give an example what you mean?

**Comment by snakefoot** [comment]
Think Grant-Liu wants the AsyncWrapper to check the length of the dequeued LogEvents-array, before calling the WrappedTarget.

**Comment by Grant-Liu** [comment]
This is correct.
It should check the lendth.

________________________________

**Comment by snakefoot** [comment]
Will be fixed together with #1853

**Comment by snakefoot** [comment]
@304NotModified Merged and can be closed.

**Comment by 304NotModified** [comment]
Thanks!
