### ISSUE TITLE
Unnecessary finalizer in NetworkSender class

### ISSUE THREAD

**Issue by plukawski** [NLog/NLog#1842]
**Type**: Bug
**NLog version**: 4.3.11
**Platform**: All

In NetworkSender base class there is an finalizer that does nothing. This is causing a lot of objects being placed on finalizer queue thus making the unnecessary waste of memory. Such objects are never collected in gen 0 (unless someone calls the dispose method explicitly which in this case removes the instance from finalizer queue). This also involves higher CPU utilization during GC collections.
In my opinion this finalizer from NLog.Internal.NetworkSenders.NetworkSender class should be removed - it does not add any value.

Current result - greater memory consumption and higher CPU during GC run because of many objects placed in finalizer queue when using network related targets.
Expected result - no NetworkSender related instances on finalizer queue when using network related targets.

**Comment by 304NotModified** [comment]
Good point!

**Comment by snakefoot** [comment]
Think it is okay to keep the finalizer, it will not be called if Dispose() was called.

Sadly enough this doesn't happen here:

NetworkSender.Close(AsyncContinuation continuation)

I guess one should change the Close-method to be non-virtual, and then call a virtual Dispose-method.

**Comment by 304NotModified** [comment]
@snakefoot but the finalizer doesn't do a thing? So removal is better?

**Comment by snakefoot** [comment]
Well the finalizer ensures Dispose is called, if reached unexpected code-path where people forget to call Dispose/Close.

**Comment by 304NotModified** [comment]
yes, but dispose is non virtual and doesn't do a thing when `false` is passed

```
        private void Dispose(bool disposing)
        {
            if (disposing)
            {
                this.Close(ex => { });
            }
        }

```

**Comment by snakefoot** [comment]
Not saying that the Dispose-pattern implemented by NetworkSender is perfect. This is how it can look:

```
        private bool disposedValue = false; // To detect redundant calls

        protected virtual void Dispose(bool disposing)
        {
            if (!disposedValue)
            {
                disposedValue = true;

                if (disposing)
                {
                    // TODO: dispose managed state (managed objects).
                }

                // TODO: free unmanaged resources (unmanaged objects) and override a finalizer below.
                // TODO: set large fields to null.
            }
        }

         ~NetworkSender()
        {
            Dispose(false);
        }

        // This code added to correctly implement the disposable pattern.
        public void Dispose()
        {
            Dispose(true);
            GC.SuppressFinalize(this);
        }
```

**Comment by 304NotModified** [comment]
valid point.

resources:

- https://msdn.microsoft.com/en-us/library/b1yfkh5e(v=vs.100).aspx
- https://msdn.microsoft.com/en-us/library/b1yfkh5e(v=vs.110).aspx

**Comment by snakefoot** [comment]
Yes the finalizer should be declared in the subclass that introduce the unmanaged resource. And fixing the Dispose-pattern will just introduce an unused code-path.
