### ISSUE TITLE
Possible big memory leak in DomainUnload event

### ISSUE THREAD

**Issue by plukawski** [NLog/NLog#1846]
**Type**: Bug
**NLog version**: 4.3.11
**Platform**: .Net 4.5 / .NET Core  and possible others when hosted on IIS

This is not outlined in MSDN documentation but at least in .NET 4.5 and .NET core platforms the domain unload event is always executed on finalizer thread (you can check this in coreclr source code available on GitHub - you will notice, that the domain unload event is being executed by **ProcessUnloadDomainEventOnFinalizeThread** native call used in **finalizerthread.cpp** file). Having this in mind the code placed in DomainUnload event must follow the same restrictions like code in regular class finalizer - for example it cannot ever try to block current thread and wait for something else to wake it up (like ManualResetEvent.WaitOne). Blocking the finalizer thread can lead to a very big and nasty memory leak, because many objects will never be collected by GC in such scenario.

I think that the **ManualResetEvent** instance should be removed from the body of **Dispose(bool)** method from **LogFactory** class, because in case of reloadTimer being not null the call to ManualResetEvent.WaitOne can freeze the thread on which the Dispose(bool) method is being executed. As you may noticed, the Dispose(bool) method of LogFacory class is being called from **LogManager.TurnOffLogging** static method, which is always executed from DomainUnload event. This can lead to a very nasty memory leak because there is a possibility, that the finalizer thread can be frozen when that event fires.

This bug affects only web applications hosted on IIS, because of the way the IIS server handles AppDomains. IIS restarts appdomains (not the whole worker process) when it detects a change in **web.config** file or in the **/bin** directory (for example after new deploy of web application). In such case the domainunload event is fired from appdomain being unloaded (and it executes on the finalizer thread, which is only one per w3wp.exe process) and then the new appdomain is being created. This is the moment when the problem described above can occur.

Current result: there is a possibility that the domain unload event can freeze the finalizer thread thus making a big memory leak in IIS hosted web applications
Expected result: code from domain unload event shall never try to block the thread it is executing on.

**Comment by snakefoot** [comment]
If waiting for the Time-thread is bad, then I think you will be surprised that NLog performs its Target-Flush operation in the AppDomain-Unload (Timeout 15 secs).

**Comment by 304NotModified** [comment]
IMO a wait is less dangerous than a lock?

**Comment by snakefoot** [comment]
Well actually the Wait was implemented badly, so when raced by the timer-thread, then the timer-thread could set the reloadTimer = null, so it could not be awaited by the disposing-thread.

**Comment by plukawski** [comment]
@snakefoot you are right, I didn't notice that there is a 500ms limit on  that wait in current version of code.
I started this issue because we had that big memory leak problem when using older version of Nlog (4.3.5) and to give you a hint that when writing the code in domain unload event you have to proceed with caution especially, when you are planning to block the executing thread, because that code will be executed on finalizer thread.

When analyzing most current code of Nlog I confirm, that this issue with memory leak should not occur thanks to the limit of miliseconds given in WaitOne call.

**Comment by snakefoot** [comment]
We could consider changing the LogManager-shutdown, so it doesn't set LogFactory.Configuration = null (Schedules threadpool-workitems for all targets to flush, and waits 15 secs).

Instead LogFactory could get a Close() method that performs a fast Flush and then Diposes().

Not sure I understand why, but there is a special internal WriteAsyncLogEvents(AsyncLogEventInfo[] logEventInfos, AsyncContinuation continuation). That delays the Flush() until all logEventInfos has been processed by the Target (Can get really messy if targets async=true and have a buffering-wrapper-target, as one has to wait for the buffering-timer-thread).

Instead I think the Flush should be made instant, instead of async (Requires the Timer-thread also uses the same lock while writing to this.WrappedTarget).

```
lock (this.RequestQueue)
{
   AsyncLogEventInfo[] logEventInfos = this.RequestQueue.DequeueBatch(-1);
   this.WrappedTarget.WriteAsyncLogEvents(logEventInfos);
   if (continuation != null)
      this.WrappedTarget.Flush(continuation);
}
```
