### ISSUE TITLE
Vary log level on several request depending on some context status

### ISSUE THREAD

**Issue by hbazan** [NLog/NLog#185]
Hi, I have an issue with logging levels. 
We need to vary log level for specific log entries, based on some conditions, leaving configuration as is for all other log entries.

Our first idea was inherit from NLog.Logger, aiming to override IsXXEnabled properties, but those properties are not virtual.

We've managed to solve the issue using Filters, but we needed to remove the MinLevel setting on the Logger config, like:

NLog.config

``` xml
<logger name="*" writeTo="async">
   <filters>
      <when Condition="MY_CONDITION" action="Log" />
      <when Condition="level &lt; LogLevel.Info" action="Ignore" />
   </filters>
</logger>
```

So we have two filter "Check" on every log entry, and most of the times MY_CONDITION wil be false. 
It's working, but our concern is we think that an override for IsXXEnabled would have a higher performance than our current solution. 

What do you think?

Do you recommend to change Logger properties to virtual so we can override it?
Is there a simpler way to achieve this?

Thanks...

**Comment by 304NotModified** [comment]
This is not planned for now
