### ISSUE TITLE
File target - keepFileOpen: file is not recreated if deleted manually.

### ISSUE THREAD

**Issue by thba** [NLog/NLog#1856]
**Type**: Bug
**NLog version**: 4.3.4
**Platform**: .Net 4.5

I have configured a file target:
`<target name="myFileTarget" xsi:type="File"
	fileName="${event-properties:item=myFileDir}\${event-properties:item=myFile}"
	layout="${message}"
	cleanupFileName="false"
	autoFlush="false"
	concurrentWrites="false"
	keepFileOpen="true">
</target>`

When I run my application the file gets created and logged into like expected. When my application is idle (no logs are created) and I delete the logfile and then the application starts to produce logs again, the file is not re-created, the logs go to nowhere and no exception or error occures.

I expect that the file is recreated when it does no longer exist. If I set keepFileOpen = "false" this is the case.

**Comment by 304NotModified** [comment]
Not sure if this a bug.

I think keepopen and deleting the file is incompatible

**Comment by snakefoot** [comment]
Would be an expensive operation to re-validate FileStream for every wirte-operation.

Windows allows the user to delete files, while another process has open filehandles to the file. Windows just cheats and hides the file from the user, and deletes the file correctly when all handles are closed.

**Comment by thba** [comment]
Well, I know nothing about NLog's "special technique" to keep the files open, but I wonder what happens internally if the file suddenly no longer exists. I can't even see some errors in ProcMon.

It has not to be, that NLog verifies the file stream with every write-operation, but it would be possible to implement a method to do so manually.

I have a long running application which has an idle mode, where no logs are written, and an active mode where logs are written. The user may delete the logs during an idle period. If he does, he will not have any logs for the next active period. If I had some method to call before my app enters the active mode, everything would be fine. Something to reset the logger completly, but I have not found anything which would help me so far.

**Comment by snakefoot** [comment]
Maybe you could try and use this special tool to close file-handles.

So the trick is:

1) Rename the file in the log-directory to have bak-file-extension
2) Close all file handle to the file in the log-directory (See https://technet.microsoft.com/en-us/sysinternals/bb896655)
3) Delete all file with bak-file-extension in the log-directory

This should make NLog react to the filehandle being broken, and then reopen the file automatically.

**Comment by 304NotModified** [comment]
@snakefoot would closing/re-initialing of the target help?

**Comment by snakefoot** [comment]
@304NotModified Maybe, but I'm guessing that the file-cleanup is an external tool, so I guess it would be easier if the external cleanup tool handled everything without needing special help from the application  (As the first post suggests).

**Comment by thba** [comment]
I understand, that the current behaviour is intended and makes sense for most cases. So this is more of a feature request that a bug report.

I request a feature, where I can reinitialize a file target configured with keepFileOpen = true, so that any invalid file handle is closed and a new one is opened. Checking when this invalid handle state occures must not necessarily be part of NLog. Just provide a means to reopen the file handle.

> would closing/re-initialing of the target help?
How can I do so?

**Comment by snakefoot** [comment]
Another solution that should also work, is to use OpenFileCacheTimeout=10

Then the FileTarget will automatically open/close the file every 10 secs. Causing it to detect that the file has been deleted.

**Comment by 304NotModified** [comment]
> Another solution that should also work, is to use OpenFileCacheTimeout=10

sound like a good solution to me 👍

**Comment by thba** [comment]
> Another solution that should also work, is to use OpenFileCacheTimeout=10

Sorry, but this is no good solution for me. That would mean, I can loose up to 10 seconds of logs. I use NLog for writing important data to file. It need to be high performance. Mulptiple threads are writing to the same target, each with its own dedicted file (I use event-variables in my fileName config). The only reason I use NLog for this task is its ready to use ability for file spliting based upon size (archiving).

The only reason I set keepFileOpen = true is for performance. I will try to set it to false again and set my target async="true". But last time I checked I got better performance with keepFileOpen = true.

**Comment by snakefoot** [comment]
> That would mean, I can loose up to 10 seconds of logs.

 OpenFileCacheTimeout=10 means that it will close and reopen the log file every 10 secs. Not sure how that is translated into loosing logevents.

**Comment by thba** [comment]
> OpenFileCacheTimeout=10 means that it will close and reopen the log file every 10 secs. Not sure how that is translated into loosing logevents.

Because before that 10 seconds the files could be already missing and logs could have been written (into nirwana). Of course I can shorten the 10 second intervall but then again I can completely resign from using keepFileOpen = true.

So there is no way of closing/re-initialing a NLog FileTarget from code and you are not planing on providing such a method?

**Comment by snakefoot** [comment]
> logs could have been written (into nirwana)

Not sure I understand you have an application that removes all log-files (also the logs written 20 secs ago), and then you worry about the 10 secs?

Sounds like you want to enable NLog-archive logic, so NLog automatically on day-change moves its active-log file into a sub-folder and continues. Then the log-cleanup task can just cleanup inside the sub-folder (leaving the log from yesterday, so you also have the log events from 20 secs ago)

**Comment by thba** [comment]
@snakefoot No, you do not understand correctly. For my app it is important to keep all logs, hence they are also archived. But sometimes the user may decide to manually (without my app) delete the current set of logs. Then I will have a problem. It is no big problem loosing 10 seconds, but it is not nice and this is the reason why I dislike your suggestion.

What is the deal about providing an API for closing/re-initialing a NLog FileTarget?

**Comment by snakefoot** [comment]
>  But sometimes the user may decide to manually (without my app) delete the current set of logs

Having an API for closing/reopening the log-files will not help you there

> What is the deal about providing an API for closing/re-initialing a NLog FileTarget?

If you assign a new configuration to LogManager.Configuration, then it will close the existing one, and start using the new one (close + reopen).

**Comment by thba** [comment]
> But sometimes the user may decide to manually (without my app) delete the current set of logs
>> Having an API for closing/reopening the log-files will not help you there

It will, since I can check without NLog if the file is there or not and calling an appropiate NLog API function to reinitialize the file target.

> If you assign a new configuration to LogManager.Configuration, then it will close the existing one, and start using the new one (close + reopen).

That sound like what I wanted. I will give it a try and reassign the same configuration.
