### ISSUE TITLE
[Feature Request] make *.svclog format support

### ISSUE THREAD

**Issue by EvgeniyGrishnov** [NLog/NLog#186]
I'd like to suggest making *.SVCLOG file target as File target extension.
It can be very usefull in cases of logging of complex SOA systems with non trivial interraction with each other (data flow map).

**Comment by Xharze** [comment]
This won't be included in NLog. If more people need this, we'll think about it again

**Comment by 304NotModified** [comment]
I think it's a great idea, but we definitely need more info. (examples, how we should write, cavecats etc)
