### ISSUE TITLE
FileTarget Archiving gets stuck

### ISSUE THREAD

**Issue by ivmreg** [NLog/NLog#1866]
**Type**:

- Bug

**NLog version**: 4.4.0

**Platform**: .Net 4.5

**Current NLog config** (xml or C#, if relevant)
```

	        var fileTarget = new FileTarget
	        {
	            FileName = Path.Combine(directoryPath, "${logger}_${date:format=yyyyMMdd}.txt"),
	            Layout = DefaultLayoutFormatter,
                NetworkWrites = false,
                KeepFileOpen = true,
                ConcurrentWrites = true,
	            Name = name,
                MaxArchiveFiles = 10,
                ArchiveAboveSize = 1024 * 20, //1024*1024*10 - we reduce the log size before archiving to 20KB to reach the problematic condition quicker, with log size of 10MB the problem reproduces as well
                ArchiveFileName = Path.Combine(directoryPath, "${logger}_{#}.txt"),
                ArchiveDateFormat = "yyyyMMdd.HHmmss",
                ArchiveNumbering = ArchiveNumberingMode.DateAndSequence
            };
            var fileWrapper = new BufferingTargetWrapper
            {
                WrappedTarget = fileTarget,
                Name = name,
                SlidingTimeout = true
            };

            LogManager.Configuration.AddTarget(name, fileWrapper);

            var logFileLoggingRule = new LoggingRule("*", minLevel, fileTarget);
	        LogManager.Configuration.LoggingRules.Add(logFileLoggingRule);

```

Bug description:
We have a "host" application that spins up multiple child "runner" applications.
The "host" application can write to it's own single "host" log.
Multiple "Runner" application can write to a single "runners" log as well as write some diagnostic information in "host" log.
Therefore, for both "runner" and "host" logs there are multiple writers.
The configuration above reflects that.

- What is the current result?

At some point during the runtime of the application when archiving of "host" log happens, it gets stuck on "host" application side (at least) with the following message:

```

2016-12-18 21:15:36.4364 Info Deleting old archive D:\Temp\Logs\HOST_20161218.211223.0.txt.
2016-12-18 21:15:36.4364 Warn Failed to archive file 'D:\Temp\Logs\HOST_20161218.txt'. Exception: System.UnauthorizedAccessException: Access to the path 'D:\Temp\Logs\HOST_20161218.211223.0.txt' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at System.IO.File.Delete(String path)
   at NLog.Targets.FileTarget.EnsureArchiveCount(List`1 oldArchiveFileNames)
   at NLog.Targets.FileTarget.ArchiveByDateAndSequence(String fileName, String pattern, LogEventInfo logEvent)
   at NLog.Targets.FileTarget.DoAutoArchive(String fileName, LogEventInfo eventInfo)
   at NLog.Targets.FileTarget.TryArchiveFile(String fileName, LogEventInfo ev, Int32 upcomingWriteSize)

```
If we look at system handles, we see the following picture:

```

ServiceManager.Host.exe (29528), File, D:\Temp\Logs\HOST_20161218.txt, 0x104c
ServiceManager.Runner.exe (4824), File, D:\Temp\Logs\HOST_20161218.211240.0.txt, 0xb0c
ServiceManager.Runner.exe (7404), File, D:\Temp\Logs\HOST_20161218.211520.0.txt, 0x8c4
ServiceManager.Runner.exe (8404), File, D:\Temp\Logs\HOST_20161218.211223.0.txt, 0x8ac
ServiceManager.Runner.exe (17008), File, D:\Temp\Logs\HOST_20161218.211456.0.txt, 0x87c
ServiceManager.Runner.exe (17812), File, D:\Temp\Logs\HOST_20161218.211432.0.txt, 0xaec
ServiceManager.Runner.exe (23244), File, D:\Temp\Logs\HOST_20161218.211456.0.txt, 0x8dc
ServiceManager.Runner.exe (26364), File, D:\Temp\Logs\HOST_20161218.211536.0.txt, 0x860
ServiceManager.Runner.exe (27284), File, D:\Temp\Logs\HOST_20161218.211552.0.txt, 0x884
ServiceManager.Runner.exe (27892), File, D:\Temp\Logs\HOST_20161218.211536.0.txt, 0x6bc
ServiceManager.Runner.exe (28220), File, D:\Temp\Logs\HOST_20161218.211520.0.txt, 0x884
ServiceManager.Runner.exe (29672), File, D:\Temp\Logs\HOST_20161218.211520.0.txt, 0x8b8
ServiceManager.Runner.exe (37296), File, D:\Temp\Logs\HOST_20161218.211456.0.txt, 0x8ac
ServiceManager.Runner.exe (37856), File, D:\Temp\Logs\HOST_20161218.211601.0.txt, 0x4f4
ServiceManager.Runner.exe (38412), File, D:\Temp\Logs\HOST_20161218.211552.0.txt, 0x8d4
ServiceManager.Runner.exe (40516), File, D:\Temp\Logs\HOST_20161218.txt, 0x8c8
ServiceManager.Runner.x86.exe (26160), File, D:\Temp\Logs\HOST_20161218.211601.0.txt, 0x98c

```
Where (8404) is process id. We see that "Runner" process with process id of "8404" has got a hold of the "host" log file and none of the processes can now archive it, if we observe this for longer we see that this process never closes this handle, so I expect that it is stuck.

If we attach a debugger to 8404 PID "Runner" process we see the following messages being generated over and over:
```

NLog: 2016-12-18 20:56:16.0584 Error Error has been raised. Exception: System.ObjectDisposedException: Cannot access a closed file.
   at System.IO.__Error.FileNotOpen()
   at System.IO.FileStream.Flush(Boolean flushToDisk)
   at System.IO.FileStream.get_SafeFileHandle()
   at NLog.Internal.Win32FileCharacteristicsHelper.GetFileCharacteristics(String fileName, FileStream fileStream)
   at NLog.Internal.FileAppenders.WindowsMultiProcessFileAppender.GetFileLength()
   at NLog.Internal.FileAppenders.FileAppenderCache.GetFileLength(String filePath, Boolean fallback)
   at NLog.Targets.FileTarget.GetArchiveFileNameBasedOnFileSize(String fileName, Int32 upcomingWriteSize)
   at NLog.Targets.FileTarget.GetArchiveFileName(String fileName, LogEventInfo ev, Int32 upcomingWriteSize)
   at NLog.Targets.FileTarget.TryArchiveFile(String fileName, LogEventInfo ev, Int32 upcomingWriteSize)
   at NLog.Targets.FileTarget.ProcessLogEvent(LogEventInfo logEvent, String fileName, Byte[] bytesToWrite)
   at NLog.Targets.Target.Write(AsyncLogEventInfo logEvent)
```

On some occasions when we attach to the Runner that has the problematic fild handle open - we see no exceptions as above.

- What is the expected result?

The archiving of files does not get stuck when there's multiple log writers.

- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?

Yes, it contains the exceptions reported.

- Please post full exception details (message, stacktrace, inner exceptions)

See above

- Are there any work arrounds? yes/no

Not to my knowledge

- Is there a version in which it did worked? 

Unknown

- Can you help us by writing an unit test?

At this point I have a repro case and can supply exception traces

**Comment by 304NotModified** [comment]
I've seen these errors on the unit tests in the past.

What is the final result? I think logging still works and archiving not? Is the archive file made when the program is started again?

**Comment by snakefoot** [comment]
I can see a possible issue with having keepFileOpen=true together with archiving. Since NLog doesn't close file handles automatically, only the process that does the archiving.

Could consider to enable autoclose-timer as soon one tries to use archiving together with keepFileOpen=true.

**Comment by 304NotModified** [comment]
Sounds as a good solution to me 👍

**Comment by ivmreg** [comment]
Hi,

Doublechecked on several other versions .. 4.3.11 and 5.0.0-beta03 - same behavior.

The behavior is as follows:
1. After the problem happens, the logging still continues, however archiving of "host" logs stops - apparently due to the possible deadlock between two processes handling the same file (just my guess).
If I look at the "Runner" process keeping the handle - I can see that there's a file handle stuck:
"File, D:\Temp\Logs\HOST_20161218.224301.0.txt, 0x89c"

However other logging still continues (Runner logs) as I can see handles for the "head" runner log gets opened and closed every now and then.

If I don't terminate the Runner process keeping the handle, the number of archived files grows.

If I terminate the Runner process that keeps the handle, the archiving rolls up successfully (up until the next instance of "stuck" handle).

2. If I terminate the "Host" process along with all child "Runner" processes and re-start the application again, the archive logs are rolled up successfully and logging continues successfully up until the next "stuck" moment.

**Comment by snakefoot** [comment]
@ivmreg Could you try and add OpenFileCacheTimeout=10 to the file-target configuration?

**Comment by ivmreg** [comment]
@snakefoot 

Yes, the problem is fixed after adding "OpenFileCacheTimeout=10".
The side effect of this (I guess negligible) is that the archived files are now of "uneven" length - I cannot confirm at this point if some events are missed. Just flagging it.

**Comment by 304NotModified** [comment]
Could you also try NLog 4.2.3? (Without OpenFileCacheTimeout)

I like to know of we introduced this bug in 4.3.x

**Comment by snakefoot** [comment]
@ivmreg What do you mean by "uneven" length? Do you have zero-length files?

**Comment by ivmreg** [comment]
@304NotModified 
For 4.2.3 with the configuration in the initial post I can't even get archiving to work.
The behavior is such that the "head" log reaches the "Archiving" size and stays like this forever (e.g. no new logging messages are added to the head log, no archive files are created).

**Comment by snakefoot** [comment]
> The behavior is such that the "head" log reaches the "Archiving" size and stays like this forever

Remember that archiving with KeepFileOpen=true, has been broken for a long time. See #1513

**Comment by ivmreg** [comment]
@snakefoot 

Let's say for this test we specify the archiving size to be "1024 * 20" bytes. The archive files I see created after adding the OpenFileCacheTimeout=10 option are as follows (in bytes):
ArchiveLog1: 20414 bytes
ArchiveLog2: 20507 bytes
ArchiveLog3: 19352
ArchiveLog4: 7198
ArchiveLog5: 223
ArchiveLog6: 6786

Note that although I specified the archiving to archive after 20KB, the archives are of uneven size.

I guess this size difference will be negligible in "normal" scenarios of archiving when files are archived in arrears of megabytes or gigabytes.

If I remove the OpenFileCacheTimeout=10 option, then the archive files are all created reasonably even, 20KB each, with very slight byte variations in size.

**Comment by ivmreg** [comment]
And thanks @snakefoot and @304NotModified for following this up! I was struggling with this problem for at least a day...
