### ISSUE TITLE
LogManager.GetCurrentClassLogger() failed on WP81 Silverlight apps [fix proposed]

### ISSUE THREAD

**Issue by yschkatula** [NLog/NLog#1875]
Hi! 

**Type**: Bug

**NLog version**: v4.0.30319

**Platform**: Windows Phone 8.1 Silverlight apps

**Current NLog config** (xml or C#, if relevant)

Today I tried to repeat steps from this tutorial but in terms of Windows Phone 8.1 http://nlog-project.org/2011/01/09/nlog-for-windows-phone-7.html

Latest sources have only Windows Phone 8.0 support (and auto-upgrade causes removal of some methods in "Logger1.cs" file so you can't compile without reverting that file back to depot version). And even after resolving that caveats, you to receive a runtime error while trying to create any logger instance.

Config file is the same as described in the tutorial:

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

  <targets>
    <target xsi:type="LogReceiverService" name="webService" endpointAddress="http://localhost:5000/LogReceiver.svc"/>
  </targets>

  <rules>
    <logger name="*" minlevel="Debug" writeTo="webService" />
  </rules>
</nlog>
```

Code usage is from the tutorial too:
private static NLog.Logger logger = NLog.LogManager.GetCurrentClassLogger();

- What is the current result?
Exception: System.MethodAccessException occurred
  HResult=-2146233072
  Message=Attempt by security transparent method 'NLog.LogFactory.get_Configuration()' to access security critical method 'System.Windows.Application.GetResourceStream(System.Uri)' failed.
  Source=NLog
  StackTrace:
       at NLog.LogFactory.get_Configuration()
  InnerException: 

- What is the expected result?
Normal logger creation

- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
Have no idea how to achieve this as apps crashes at early stage (static init)

- Please post full exception details (message, stacktrace, inner exceptions)
Additional information: Attempt by security transparent method 'NLog.LogFactory.get_Configuration()' to access security critical method 'System.Windows.Application.GetResourceStream(System.Uri)' failed.

- Are there any work arrounds? yes/no
You can amend the sources in two places:
1) XmlLoggingConfiguration.cs
===============
---  #if SILVERLIGHT
+++ #if SILVERLIGHT && !WINDOWS_PHONE
                newFileName = newFileName.Replace("\\", "/");
                if (Application.GetResourceStream(new Uri(newFileName, UriKind.Relative)) != null)
#else
                if (File.Exists(newFileName))
#endif
===============

 2) LogFactory.cs
===============
---  #if SILVERLIGHT
+++ #if SILVERLIGHT && !WINDOWS_PHONE
                            Uri configFileUri = new Uri(configFile, UriKind.Relative);
                            if (Application.GetResourceStream(configFileUri) != null)
                            {
                                LoadLoggingConfiguration(configFile);
                                break;
                            }
#else
                            if (File.Exists(configFile))
                            {
                                LoadLoggingConfiguration(configFile);
                                break;
                            }
#endif
===============

- Is there a version in which it did worked? 
Not found

- Can you help us by writing an unit test?
Not sure

**Comment by 304NotModified** [comment]
Thanks for the suggestion. We are looking at it :)
