### ISSUE TITLE
Nlog archive not working as expected

### ISSUE THREAD

**Issue by Bidou44** [NLog/NLog#1884]
**Type**:
Bug

**NLog version**:
4.4.1

**Platform**: 
.Net 4.6

**Current NLog config**
```
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <targets>
        <target name="File" xsi:type="File" fileName="\\server\xxx\${shortdate}.log" keepFileOpen="false" 
encoding="iso-8859-2" layout="${longdate}|${pad:padding=5:inner=${level:uppercase=true}}|${message} ${exception:format=tostring}" 
archiveFileName="archive.{month}{year}.zip" archiveEvery="Month" maxArchiveFiles="24" enableArchiveFileCompression="true" />
  </targets>
  <rules>
    <logger name="*" minlevel="Info" writeTo="File" />
  </rules>
</nlog>

```
- What is the current result?
The first of the month, nlog created a zip file called "archive.{month}{year}.1.zip" which was located where the program.exe was. The content of the archive was the last file of the previous month, in my case, "2016-12-31.log". This log file was removed from the log location configured in the fileName property of the target.

- What is the expected result?
The first of the month, nlog should create a zip file called (for january 2017) archive.jan2017.zip. This file should not be in the main folder (where the .exe is) but in the location I specifed in the fileName property of my target. Furthermore, it should contain the whole month (31 files in my case (december 2016)) and not just the last one. All files log of this month (december 2016) should then be deleted.

- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
No

- Please post full exception details (message, stacktrace, inner exceptions)
No exception

- Are there any work arrounds?
I don't think so. At least, I'm not aware of any.

- Is there a version in which it did worked? 
No, I already created a bug a few month ago, it was closed but apparently not fixed. See https://github.com/NLog/NLog/issues/1277

- Can you help us by writing an unit test?
No

**Comment by snakefoot** [comment]
There is currently no support in NLog for compressing multiple files into a single compressed-archive-file. So I guess it cannot be called a bug :)

**archiveEvery** just means that it will compare the file-timestamp with the current logevent-timestamp, and if the file is older than the archive-period, then an archive operation is triggered.

I guess you have to settle for creating a scheduled task to perform the compression into a single-zip-file. But you might want to increase **maxArchiveFiles** to cover a whole month.

**Comment by 304NotModified** [comment]
Thanks @snakefoot !
