### ISSUE TITLE
My rules are being ignored when a assembly namespace is specified

### ISSUE THREAD

**Issue by jcbremond** [NLog/NLog#1895]
**- Question/Bug ?**

**NLog version**:  4.4.1
**Platform**:  .Net 4.5 

**Current NLog config** (xml or C#, if relevant)

```xml
 <rules>
    <!--Skip Microsoft logs and so log only own logs-->
    <logger name="Microsoft.*" minlevel="Trace" writeTo="blackhole" final="true" />

    <!-- disabled rules for debug (namespace pb ) -->
    <logger name="*" minlevel="Warn" writeTo="asyncFile" enabled="false" />
    <logger name="*" minlevel="Debug" writeTo="asyncFile,elasticSearch" enabled="false"  />
    <logger name="*" minlevel="Info" maxlevel="Info" writeTo="consoleColor,elasticSearchCustom" enabled="false" />
```
      
     <!-- rules for log only for 
[NLog - Copie.config.txt](https://github.com/NLog/NLog/files/696233/NLog.-.Copie.config.txt)

specific assembly:

```
    <logger name="Test.Dummy.*" minlevel="Info" maxlevel="Info" writeTo="consoleColor" enabled="true" />
    
  </rules>
```

If you take a look at my rules:

```xml
  <logger name="Test.Dummy.*" minlevel="Info" maxlevel="Info" writeTo="consoleColor" enabled="true" />
```
 
i need log only for an specific assembly but i doesn't log if logger name is not "*" why ?
exemple : [ConsoleTestNlog.zip](https://github.com/NLog/NLog/files/696244/ConsoleTestNlog.zip)
 
Thank's in advance for your reply.
Jc.

**Comment by 304NotModified** [comment]
hey!

This is a common mistake. Could you try to log `${logger}` in the target to double check the loggername?

e.g.

```
    <target name="console" xsi:type="Console" message="${logger}: ${message}" />
```

**Comment by jcbremond** [comment]
When i add  "message="${logger}: ${message}" " in my target   an exception occurs in my demo app...

Visual Studio 2015 does not like this addition ...


![capturenlog1](https://cloud.githubusercontent.com/assets/15029740/21841911/a1e75400-d7e4-11e6-92b9-646bc2092a4d.JPG)

What to do ?

TIA.
Jc

ps : Sorry for my poor English :-)

**Comment by 304NotModified** [comment]
sorry meant `layout`
So:

```xml
<target name="console" xsi:type="Console" layout="${logger}: ${message}" />
```

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, let us know!
