### ISSUE TITLE
Support extention loading startup

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#1916]
When loading a NLog extention, start up like [PreApplicationStartMethod](https://msdn.microsoft.com/en-us/library/system.web.preapplicationstartmethodattribute(v=vs.110).aspx)

e.g. for making package NLog.Json-net and loading into the static var

**Comment by snakefoot** [comment]
Maybe resolved with #1917 ?

**Comment by 304NotModified** [comment]
Yes! Nice catch!
