### ISSUE TITLE
Grouping log messages in the WebService target

### ISSUE THREAD

**Issue by JonasAxelsson** [NLog/NLog#1928]
Hi,

I have a question related to grouping of log messages in the WebService target when using Nlog 4.2.3 in ASP.NET Core.

Is it possible to use the WebService target but in a less "chatty" way? Currently I'm able to call a WebAPI using Json HTTP posts, but each log message generates a separate HTTP call to the WebAPI, i'm worried that this is not a good solution when thinking of performance and scalability.

The mail target groups multiple log messages into one mail message, could same be achieved when using the WebService target?

Currently we are using a buffering wrapper around the webservice target, the current configuration makes the logging asynchronous and also buffered into groups of 100 log messages which are posted as JSON in separate HTTP calls after exceeding 100 log messages or after 60 seconds.

This doesn't actually group all log messages into one HTTP call to our WebAPI. So is this a good solution when thinking of performance and scalability?

```xml
    <!-- Write logs to webservice -->
    <target name="logMessageWebServiceBuffered" xsi:type="BufferingWrapper" slidingTimeout="true" bufferSize="100" flushTimeout="60000">
      <target xsi:type="WebService" url="http://localhost:5103/loggingapi/Log/LogMessage" protocol="JsonPost" encoding="UTF-8" includeBOM="false">
        <parameter name="Message"    layout="${message}" />
        <parameter name="DateTime"    layout="${event-properties:item=DateTime}" />
        <parameter name="SystemName" layout="${event-properties:item=SystemName}" />
        <parameter name="ApplicationName" layout="${event-properties:item=ApplicationName}" />
        <parameter name="JobName" layout="${event-properties:item=JobName}" />
        <parameter name="Status" layout="${event-properties:item=Status}" />
      </target>
    </target>
```

**Comment by 304NotModified** [comment]
> The mail target groups multiple log messages into one mail message, could same be achieved when using the WebService target?

The same as on the chat ;)

This is currently not supported in the webservice target. Grouping is also not-trivial for some protocols (e.g. query string and GET).

**Comment by JonasAxelsson** [comment]
Yes same as on the chat :-) I thought it would be good to let other people find this question in the future.

A HTTP POST containing a JSON object array with log events should work but I doesn't have big knowledge about NLOG yet so I need alot of time to just read into the NLog framework.

Do you have any input on if it's wise to use the WebService target for majority of all application logging in a distributed environment.

We have three network zones, DMZ1 contains web servers with logging web applications. DMZ2 contains web servers running WebAPI's, and LAN where all databases is hosted.

The goal is to log towards database tables using the WebAPI's in DMZ2.

**Comment by 304NotModified** [comment]
Could you make a feature request for this and describe how we should do this and which protocols?

Closing this one as answered
