### ISSUE TITLE
Filter by Build Configuration

### ISSUE THREAD

**Issue by Rui90** [NLog/NLog#1929]
**Question**:

**NLog version**: v4.4.1

**Platform**: .Net 4.5 
**Current NLog config**:

```xml
<target name="logfileDev" xsi:type="File" fileName="fileDev.txt"  layout="${date:format=yyyyMMddHHmmss} ${message}"/>
<target name="logfileProd" xsi:type="File" fileName="fileProd.txt" layout="${date:format=yyyyMMddHHmmss} ${message}" />

    <logger name="*" minlevel="Trace" writeTo="logfileDev">
      <filters>
        <when condition="equals('${buildConfiguration}','Release')" action="Ignore" />
      </filters>
    </logger>
    <logger name="*" minlevel="Info" writeTo="logfileProd">
      <filters>
        <when condition="equals('${buildConfiguration}','Debug')" action="Ignore" />
      </filters>
    </logger>
```
Hi, after all this information my question is very simple. I want to filter my application so when it is in dev mode (debug) it creates only the fileDev, and when it is in production (release mode) it creates only the fileProd. I added those two rules to the targets in question but it always creates both files, fileDev and fileProd and it always, logs to both of them, of course maintaining the different minLevel. But it is possible to create just only one for each environment?

**Comment by 304NotModified** [comment]
That's strange! Your config looks correct.

Could you check the internal log on trace level?

**Comment by 304NotModified** [comment]
PS another options would be 

`<target name="logfileProd" xsi:type="File" fileName="${buildConfiguration}.txt" layout="${date:format=yyyyMMddHHmmss} ${message}" />
`


edit: maybe it's an issue with `${buildConfiguration}`? Are you registering that one too late?

**Comment by Rui90** [comment]
@304NotModified  I'm not sure I know how to do that. "Could you check the internal log on trace level?"

**Comment by 304NotModified** [comment]
https://github.com/nlog/nlog/wiki/Internal-logging

**Comment by 304NotModified** [comment]
Is this still an issue?

**Comment by Menelion** [comment]
@Rui90, sorry, but what was your solution? I'd like to accomplish just the same thing: one file for debug, one for release. Thanks!
