### ISSUE TITLE
RichTextBox target not working under Mono/Linux

### ISSUE THREAD

**Issue by Zlika** [NLog/NLog#193]
Hi!

The RichTextBox target does not work with Mono under Linux. I use NLog 2.0.0.2002 (Mono build).
The error message is:
NLog.NlogConfigurationException: Exception occured when loading configuration from ***/Nlog.config
---> System.ArgumentException: Target cannot be found: 'RichTextBox'
  at NLog.Config.Factory 2[NLog.Targets.Target,NLog.Targets.TargetAttribute].CreateInstance(System.String name)
...

The same code is working ok on Windows with Visual Studio/.NET 4.0.

Is there any workaround for that?

Thank you.
Thomas

**Comment by Xharze** [comment]
After the Windows.Forms features have been moved to it own repository. Mono is officially not supported for these features.
