### ISSUE TITLE
AspNetBufferingWrapper not working

### ISSUE THREAD

**Issue by nonelse** [NLog/NLog#194]
Hi, I have an MVC3 project with NLog.2.0.0.2000 and NLog.Extended.2.0.0.2000.
I can't seem to use NLog.Extended 'AspNetBufferingWrapper'. 
I have added 'add name="NLog" type="NLog.Web.NLogHttpModule, NLog.Extended" /' to 'httpModules'.
I have an 'AsyncWrapper' wrapper-target with same sub-target as 'AspNetBufferingWrapper', and it works with no problem. Is there a problem with this module or am I missing something?
Best regards

**Comment by dyardyGIT** [comment]
Is this working? I have yet to have all my logs in one http request grouped together?
thx
