### ISSUE TITLE
Question - Getting error while trying to add attributes for FluentD NLog target

### ISSUE THREAD

**Issue by harikasundarapu** [NLog/NLog#1947]
Hi,

I want to add fields like Hostname, Logger, Level and so on in FluentD target same as like RabbitMQ target in Nlog.config. I tried adding fields, attributes and parameters but am getting error PARAMETER NOT SUPPORTED ON FLUENTD. Any suggestions? 

Thanks in Advance

**Comment by 304NotModified** [comment]
I'm not sure if you should ask your question here: https://github.com/fluent/NLog.Targets.Fluentd

But please share your config

**Comment by harikasundarapu** [comment]
Below is the customized target I tried to execute but getting above error. Am not sure If I could layout in this way.

<target name="name" xsi:type="Fluentd"
            host="hostname"
            tag="tagname"
            noDelay="true"
          sendBufferSize="8192"
          sendTimeout="2"
          lingerEnabled="false"
          lingerTime="2"
          layout="${message}"
          emitStackTraceWhenAvailable="true"
      includeAllProperties="true">
        <layout xsi:type="JsonLayout">
          <attribute name="Hostname" layout="${machinename}" />
          <attribute name="Logger" layout="${logger}" />
          <attribute name="Level" layout="${level}" />
          <attribute name="Message" layout="${message}" />
        </layout>
    </target>

**Comment by 304NotModified** [comment]
I think this is not needed:

```
        <layout xsi:type="JsonLayout">
          <attribute name="Hostname" layout="${machinename}" />
          <attribute name="Logger" layout="${logger}" />
          <attribute name="Level" layout="${level}" />
          <attribute name="Message" layout="${message}" />
        </layout>

```

**Comment by 304NotModified** [comment]
See also this example: https://github.com/fluent/NLog.Targets.Fluentd/blob/master/src/Demo/Program.cs

**Comment by harikasundarapu** [comment]
Then is there way that I can parse these fields in elastic search interface like Grafana or Kibana without explicitly mentioning in the target?

**Comment by 304NotModified** [comment]
ow maybe it should work, but without the `layout attribute` and move of `includeAllProperties`

so:


```xml
    <target name="name" xsi:type="Fluentd"
            host="host"
            tag="tagname"
            noDelay="true"
          sendBufferSize="8192"
          sendTimeout="2"
          lingerEnabled="false"
          lingerTime="2"
          emitStackTraceWhenAvailable="true"
      >
        <layout xsi:type="JsonLayout" includeAllProperties="true">
          <attribute name="Hostname" layout="${machinename}" />
          <attribute name="Logger" layout="${logger}" />
          <attribute name="Level" layout="${level}" />
          <attribute name="Message" layout="${message}" />
        </layout>
    </target>
```

could you test? Please send the full exception if not working (including title, stacktrace etc)

**Comment by harikasundarapu** [comment]
Yes it worked!!
Thank you so much!!

**Comment by 304NotModified** [comment]
👍 glad to hear!
