### ISSUE TITLE
Add aliases option for layout renderer

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#1948]
For consistency and backwardscompatiblity

e.g.

* ` [LayoutRenderer("activityid")]` -> ` [LayoutRenderer("activity-id", "activityid")]`
* ` [LayoutRenderer("logger")]` -> ` [LayoutRenderer("logger", "loggername")]`

**Comment by UgurAldanmaz** [comment]
Would we like to release this one with the next version?

**Comment by 304NotModified** [comment]
It would be nice to target 4.6 for this :)
