### ISSUE TITLE
Add ordinal option for ${level}

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#1949]
When writing to e.g. a database, it would be faster and better to send a level "number" (ordinal), so that we could do a greater than and safe some space. 

Level | Ordinal
----|-----
0 | Trace
1 | Debug
2 | Info
3 | Warn
4 | Error
5| Fatal
*6* | *Off*

**Comment by 304NotModified** [comment]
from varchar(5) -> tinyint  (4-5 chars)

6-8 bytes -> 1 byte

**Comment by snakefoot** [comment]
Can be closed. Part of NLog 4.4.6

**Comment by 304NotModified** [comment]
:) thanks!
