### ISSUE TITLE
Move to VS2017

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#1954]
- Move all SLN files (net45.sln, net40.sln, wp8.sln etc) to one VS2017 SLN
- remove all unneeded SLN and CSPROJ files.

No need to sync to conflicts on CSPROJ!

**Comment by vgotra** [comment]
Hi - I can help with this and also with moving to C#6/C#7 in free time

**Comment by gnagar-dev** [comment]
Hi- Is this already picked up, if not then I can start on it?

**Comment by 304NotModified** [comment]
AFAIK this isn't started yet.

I dunno if we could use the new csproj format. If we could, then I prefer that. (no need to sync project files then!)

**Comment by gnagar-dev** [comment]
@304NotModified  Thanks a lot for getting back to me, as I am totally new to open source and this is going to be my first request can you please guide me how to proceed to this as I can see there are multiple solution files for each .NET framework.

**Comment by stil** [comment]
Silverlight 4, Silverlight 5, WP 8.1 are not supported in VS2017. You need VS2015 to build them.

So I suppose we would need separate project files for VS2015 compatible and VS2017 compatible frameworks which sounds rather messy.

On the other hand, is there a need to keep support for WP8 and Silverlights?

**Comment by snakefoot** [comment]
@stil You just need to install the right SDKs, and AppVeyor has apparently done it right. Since the there is now a NuGet-package ready for NetStandard2.0 (together with all the other platforms):

https://github.com/NLog/NLog/pull/2263

**Comment by stil** [comment]
@snakefoot were you able to build NLog from VS2017? I tried installing SL4 and SL5 SDKs but they don't seem to work.

**Comment by snakefoot** [comment]
@stil Well I didn't want to ruin my beautiful computer with installing all kind of random stuff, so I just perform trial-on-error using AppVeyor-VS2017-Image.

**Comment by 304NotModified** [comment]
That's strange as dotnet is forwarding the calls to msbuild (see https://stackoverflow.com/a/43455110/201303)

 Maybe is the dotnet version older.

**Comment by snakefoot** [comment]
@304NotModified Msbuild and dotnet setup different targets-files before being launched. So even if dotnet launches msbuild, then it has probably setup a different (limited) build configuration environment.

**Comment by 304NotModified** [comment]
Good one.

**Comment by snakefoot** [comment]
Maybe move milestone to 4.5

**Comment by 304NotModified** [comment]
thx
