### ISSUE TITLE
NLog WebService target send to web api a dictionary 

### ISSUE THREAD

**Issue by yotamLP** [NLog/NLog#1958]
Type:
- Question

NLog version:  4.2.2

Platform: .Net 4.5 

Current NLog config:
```xml
<nlog xmlns='http://www.nlog-project.org/schemas/NLog.xsd' 
        xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' autoReload='true' internalLogFile='c:\logs\log.txt' internalLogLevel='Trace'>
  <targets async='true'>
    <target xsi:type='WebService' name='TrackingWs' url='http://localhost/Tracking/AddNewEvent'
            protocol='JsonPost' encoding='UTF-8' includeBOM='false'>
      <parameter name='NewEventData' layout='${event-properties:item=NewEventData}'/> 
      <parameter name='NewEventType' layout='${event-properties:item=NewEventType}'/>
      <parameter name='NewEventName' layout='${event-properties:item=NewEventName}'/>
    </target>
  </targets>
  <rules>
    <logger name='FunnelTracking' minlevel='Info' writeTo='TrackingWs'>
    </logger>
  </rules>
</nlog>
```

Hi I'm trying to send a dictionary "NewEventData"  to my web api. plus 2 more parameters which are string and int. the only thing my service returns is the string. now my question is why when I send from the client a json string of all this object it's working but when I try to send it through Nlog as a complex type it will not work?

I would really love some guidance and an example if possible.

Thanks,
Yotam.

**Comment by 304NotModified** [comment]
not tested, but should be something like this:

```
 <target xsi:type='WebService' name='TrackingWs' url='http://localhost/Tracking/AddNewEvent'
            protocol='JsonPost' encoding='UTF-8' includeBOM='false'>
    <parameter name='dictionary' layout='{ 
"newEventData": ${event-properties:item=NewEventData:jsonEncode=true}' ,
"NewEventType": ${event-properties:item=NewEventType:jsonEncode=true}' ,
"NewEventName": ${event-properties:item=NewEventName:jsonEncode=true}' }

/> 

    </target>
```

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, let us know!

**Comment by yotamLP** [comment]
The only thing I would like to have in this great feature is the ability to send integers and complex types. 
the way I did it to work is I sent all my complex data as JSON and then converted it back to my desired object. hope it will help someone in the future.
