### ISSUE TITLE
Provide access to the parsed template for structured log events

### ISSUE THREAD

**Issue by nblumhardt** [NLog/NLog#1962]
**Type** (choose one): Feature request
**NLog version**: 4.5-alpha01
**Platform**: .NET 4.5, others

When processing a structured log event, the underlying `Template` object is useful for a few reasons.

 * Targets that want to pretty-print output need to iterate over the individual template tokens, e.g. see https://github.com/serilog/serilog-sinks-literate and https://github.com/logary/logary/pull/155
 * Targets that capture the template itself for later offline rendering need to pre-render `Hole`s that have a `Format` associated with them, see: https://github.com/datalust/nlog-targets-seq/issues/2

It'd be nice not to have to parse the template twice in this situation, since it's already parsed in `LogEventInfo.CalcFormattedMessage()`.

A simple way to do this would be to add a lazily-initialized `Template` property to `LogEventInfo`.

To avoid extending the `Template`'s lifetime (potentially hurting GC performance), a `GetTemplate()` method might be a better option. This would internally parse the template, then call the equivalent of `CalcFormattedMessage()` passing the parsed `Template` as an argument, before returning it from `GetTemplate()` (no backing `_template` field would thus be needed).

**Comment by 304NotModified** [comment]
Will implement this soon :)

**Comment by 304NotModified** [comment]
Also in alpha 2!

GetMessageTemplate.

**Comment by nblumhardt** [comment]
Awesome :-) will update ASAP for this and #1963.

**Comment by nblumhardt** [comment]
@304NotModified just one slight issue- the method is cased `GetmessageTemplate()` - lowercase 'm'

**Comment by 304NotModified** [comment]
Oops gonna fix that. Was also thinking I should return an interface eventually.

**Comment by 304NotModified** [comment]
This is Fixed in alpha3
