### ISSUE TITLE
LogEventInfo.Properties can be accessed before proper initialization

### ISSUE THREAD

**Issue by nblumhardt** [NLog/NLog#1963]
**Type** (choose one): Bug
**NLog version**: 4.5-alpha01
**Platform**: .NET 4.5, others

The `Properties` collection isn't populated from a structured event's message template unless formatting has been triggered.

Repro:

```csharp
[Target("test")]
class TestTarget : Target
{
    protected override void Write(LogEventInfo logEvent)
    {
        Console.WriteLine("Before: " + logEvent.Properties.ContainsKey("A"));

        var unused = logEvent.FormattedMessage;

        Console.WriteLine("After: " + logEvent.Properties.ContainsKey("A"));
    }
}

var target = new TestTarget();
var logger = LogManager.GetCurrentClassLogger();
SimpleConfigurator.ConfigureForTargetLogging(target);
logger.Info("{A}", 1);
```

Expected output should be `true`, `true`, i.e. `Properties` has nothing to do with lazy formatting. Actual output:

```
Before: False
After: True
```

**Comment by 304NotModified** [comment]
ow yes had already fixed that one also :) 

But will add  the unit test! Thanks!

**Comment by 304NotModified** [comment]
In alpha2!
