### ISSUE TITLE
Non-ThreadAgnostic Layouts/Renderers Being Rendered On Wrong Thread?

### ISSUE THREAD

**Issue by TheXenocide** [NLog/NLog#1973]
**Type**: Bug?
**NLog version**: 4.4.1
**Platform**: .Net 4.5

As per discussion on #1136, I believe I've found a possible bug, though I'm not 100% sure what the expected behavior ought to be. I was having some difficulty with non-thread-agnostic layouts being rendered on the wrong thread where they no long have the correct CallContext data. In experimenting, some things appeared to be fixed at first, but it looks like the behavior is different depending on the root layout format? I've uploaded a LINQPad script I was using to Prototype this [here](http://s000.tinyupload.com/index.php?file_id=03569483137711773681) (if you don't have LINQPad, the file can be opened as plain text and the code is there, but I'd at least recommend giving LINQPad if you haven't). The script has two primary layout configurations, one of which is commented out. I've included output from both configurations with async turned on and off (all of this is changed simply by commenting/uncommenting existing lines). The test runs three separate tests for methods we have prototyped for contextual diagnostic data, each of which differs a little bit, but even in the most simple form using MDLC there is a pretty curious difference in the output between the CsvLayout and JsonLayout; JsonLayout appears to lose a fair bit of context, though not all of it in all cases. The last 2/3 columns/properties are all thread-contextual and I'm a bit confused why some configurations work as expected under async and some don't, even simultaneously.

As an additional sidenote, it appears that using the async wrapper costs quite a bit of performance, which is the opposite of what my expectation was. If this holds true for our main application we'll likely just use synchronous writes anyway, but I thought it was worth asking if something is broken or if I'm doing something wrong?

**Comment by 304NotModified** [comment]
I think this is the same issue

https://github.com/NLog/NLog/issues/254

I really like to fix this, but dunno how

**Comment by 304NotModified** [comment]
I will try to look at your tesr script soon

**Comment by TheXenocide** [comment]
Since some layouts work better than others I wonder if it isn't the object graph exploration is just missing something? I don't know well enough how that code works, but it almost feels like it's not making it to some property that contains a non-agnostic layout when it's searching to find objects without the attribute?

**Comment by 304NotModified** [comment]
Thanks for the LINQpad script. I have LINQPad (but never use it ;))

Unfortunately the testscript is too large for me. I don't have time to debug 750 lines. Is it possible to provide a smaller testcase, and preferred as unit tests? (PR with unit tests also nice)

**Comment by TheXenocide** [comment]
I'm a little backed up at work at the moment, but I will try to put something smaller and more fitting together for you when I get caught up.

**Comment by 304NotModified** [comment]
thanks!

**Comment by snakefoot** [comment]
NLog 4.4.2 includes the PR #1925 that improves the async-handling for JsonLayout.

**Comment by TheXenocide** [comment]
Ahhh, ok, first I'll try with an updated package (I thought I was on most recent) and see if the issues are already resolved.

**Comment by TheXenocide** [comment]
Yup, that's what it was. Sincerely sorry for wasting your time, I thought I was up-to-date. Thanks very much for the assistance.

**Comment by snakefoot** [comment]
@TheXenocide The bug has been there since the dawn of the JsonLayout, and has just been resolved 2 weeks ago. Glad you can also confirm it as fixed :)

**Comment by 304NotModified** [comment]
\o/

**Comment by 304NotModified** [comment]
Thanks @snakefoot !
