### ISSUE TITLE
JsonLayout - JsonAttribute how to assign value with normal text "${value}" instead of configuration syntax

### ISSUE THREAD

**Issue by KennethWKZ** [NLog/NLog#1975]
**Type** (choose one): 
- Bug

**NLog version**: 4.4.2

**Platform**: .Net 4.5 

**Current NLog config**: API

```
        var fileTarget1 = new FileTarget
            {
                Name ="FileTargetName",
                Layout = logObject,
                //so'on.....
            };

        logObject= new JsonLayout
        {
            Attributes =
            {
                new JsonAttribute("timestamp", DateTime.Now.ToString("O")),
                new JsonAttribute("htmltbody", "<tbody>${summaryTable.rowData}</tbody>")
            },
            RenderEmptyObject = false,
            SuppressSpaces = true
        };
```

BUG case:

- What is the current result?
NLog failed to assign JsonAttribute value with simple text "${simpletext}". Example of the JsonAttribute value: "{"html": "<html>Client ${client.name}</html>"}" 

- What is the expected result?
Expected NLog can assign value in JsonAttribute "<html>Client ${client.name}</html>" is normal text usage instead of automatic recognize as configuration syntax.  

- Are there any work arrounds? yes/no
No

- Is there a version in which it did worked? 
No

**Comment by 304NotModified** [comment]
> NLog failed to assign JsonAttribute value with simple text "${simpletext}". Example of the JsonAttribute value: "{"html": "Client ${client.name}"}"

Please show me how you doing this.

**Comment by KennethWKZ** [comment]
I using JsonLayout to customize my log.

`
var fileTarget1 = new FileTarget
            {
                Name ="FileTargetName",
                Layout = logObject,
                //so'on.....
            };
`

`
                    logObject= new JsonLayout
                    {
                        Attributes =
                        {
                            new JsonAttribute("timestamp", DateTime.Now.ToString("O")),
                            new JsonAttribute("htmltbody", "<tbody>${summaryTable.rowData}</tbody>")
                        },
                        RenderEmptyObject = false,
                        SuppressSpaces = true
                    };
`

Which mean "${summaryTable.rowData}" actually not a variable from NLog configuration syntax but it is my html tbody value from server side retrieve the value.

Anyway can make NLog ignore it because it is same syntax.

**Comment by 304NotModified** [comment]
You could escape it with the ${literal}, see https://github.com/NLog/NLog/wiki/Literal-Layout-Renderer

**Comment by 304NotModified** [comment]
That's we're you looking for, right?

**Comment by KennethWKZ** [comment]
Yes! I didn't know got Literal Layout Renderer! It was solved my problem! Thank You!

**Comment by KennethWKZ** [comment]
Sorry...once test with this value with JsonAttribute decode way. 
It will not work anymore and got this error message: LayoutRenderer cannot be found: 'test'.

Example of my JSON Serialized to string value:
`var value = "{\"Headers\": {\"logname\": \"Test\"},\"dollarSign\": \"${test}\"}"

new JsonAttribute("body", "${literal:text=" + value + "}", false)
`

**Comment by 304NotModified** [comment]
You need to escape only `${`

There's a helper for that in c#, `SimpleLayout.Escape(...)`

**Comment by KennethWKZ** [comment]
my problem solved. Thanks again!!

**Comment by 304NotModified** [comment]
👍
