### ISSUE TITLE
Accessing layout renderer values from within a target

### ISSUE THREAD

**Issue by ThomasArdal** [NLog/NLog#1979]
- Question

I was wondering if it is possible to access the values of generated layout renderers from within a target. Let's say I implement a target that want to ping a hostname every time someone logs anything. To do this, I would need to access the value of ${machinename} from within my target. I don't want to add ${machinename} as part of the layout which ends up in the log file (or whatever target I use).

**Comment by ThomasArdal** [comment]
Cross post of https://groups.google.com/forum/#!topic/nlog-users/HNQXAOUdZlc (which I think is no longer monitored?)

**Comment by 304NotModified** [comment]
what about this?

```c#
var option1 = new NLog.LayoutRenderers.MachineNameLayoutRenderer().Render(LogEventInfo.CreateNullEvent());

Layout option2_dynamic = "${machinename}";
var option2 = option2_dynamic.Render(LogEventInfo.CreateNullEvent());


```

> Cross post of https://groups.google.com/forum/#!topic/nlog-users/HNQXAOUdZlc (which I think is no longer monitored?)

closed years ago!

**Comment by 304NotModified** [comment]
https://groups.google.com/forum/#!topic/nlog-users/0rJX4Cc6r9g

**Comment by ThomasArdal** [comment]
Thanks! I'll try that tomorrow.

Maybe close the google group? 30 threads have been created after writing that message :smile:

**Comment by 304NotModified** [comment]
I'm not admin of the group. Kim also not AFAIK.

**Comment by ThomasArdal** [comment]
@304NotModified Both options worked like a charm. Thanks!

**Comment by 304NotModified** [comment]
cool :)
