### ISSUE TITLE
Potential null reference exception (EventLogInfo.LoggerName)

### ISSUE THREAD

**Issue by Evangelink** [NLog/NLog#1980]
Hi there,

Just to let you know you may have a null reference exception [here](https://github.com/NLog/NLog/blob/master/src/NLog/LogReceiverService/BaseLogReceiverForwardingService.cs#L123). If the first `ev.LoggerName` is an empty string then you will have a NPE. It might be something you don't expect and maybe by design you know the logger name will never be an empty string but I thought you might want to know. Maybe you could simply refactor the if with `logger == null || ev.LoggerName != lastLoggerName` so you are sure it won't crash.

Cheers,
Amaury

**Comment by 304NotModified** [comment]
thx for the info.

I see we assume (unsafe) that loggerName is never `null`, see e.g.

https://github.com/NLog/NLog/blob/27e03e6a328184fabcfd3da62d6ac4f13dfa1c41/src/NLog/LogEventInfo.cs#L191


We should check here for `null`: 
https://github.com/NLog/NLog/blob/e4ddeefdc0137178f144c6bf5b65b38053385461/src/NLog/LogEventInfo.cs#L179

Breaking change, So Nlog 5

**Comment by snakefoot** [comment]
Maybe resolved with #2916

**Comment by 304NotModified** [comment]
This seems to be fixed already. Thanks for reporting.
