### ISSUE TITLE
Unable to make jsonlayout work with code net461

### ISSUE THREAD

**Issue by sherry9872** [NLog/NLog#1981]
Please provide suggestion regarding this. I have not been able to find a similar scenario in any example.  simpe file logging is working with this approach.
How can I make this work. Please find below the code snippet

```c#
var config = new LoggingConfiguration();


            var fileTarget = new FileTarget();
            config.AddTarget("file", fileTarget);

            // Step 3. Set target properties 
            fileTarget.FileName = logStorageOptions.LogFileSettings.FileName();
           var jsonLayout = new JsonLayout
            {
                Attributes = {
                    new JsonAttribute("message", "${message}")
                }
            };
            fileTarget.Layout = jsonLayout 
            
            // Step 4. Define rules
            var rule2 = new LoggingRule("*", NLog.LogLevel.Trace, fileTarget);
            config.LoggingRules.Add(rule2);
           Logger logger = LogManager.GetLogger("Example");
          logger.info().message("Some data");
```

**Comment by 304NotModified** [comment]
please fill in the template

**Comment by sherry9872** [comment]
Hi! Thanks for reporting this feature/bug/question! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

For .NET Core users, please check the platform support: https://github.com/NLog/NLog/wiki/platform-support

**Type** (choose one):
- Question


**NLog version**: (e.g. 4.2.3)
<package id="NLog" version="4.4.2" targetFramework="net461" />
**Platform**:  .NET 4.6.1

**Current NLog config** (xml or C#, if relevant)

Not using config file. Creating the log programmitically. The below code works for basic file strorage
var config = new LoggingConfiguration();


            var fileTarget = new FileTarget();
            config.AddTarget("file", fileTarget);

            // Step 3. Set target properties 
            fileTarget.FileName = "${basedir}/demofile.txt";
            fileTarget.Layout ="${longdate}|${event-properties:item=EventId.Id}|${logger}|${uppercase:${level}}|${message} ${exception};
            
            // Step 4. Define rules
            var rule2 = new LoggingRule("*", NLog.LogLevel.Trace, fileTarget);
            config.LoggingRules.Add(rule2);

            // Step 5. Activate the configuration
            LogManager.Configuration = config;
            Logger logger = LogManager.GetLogger("Example");          
            logger.Info(logMessage);
In case of a BUG:

- What is the current result?
I want the logging done in json format programmitically
- What is the expected result?
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)? Yes. I have taken the reference from 'https://github.com/NLog/NLog/wiki/JsonLayout'
- Please post full exception details (message, stacktrace, inner exceptions)
- Are there any work arrounds? yes/no
- Is there a version in which it did worked? 
- Can you help us by writing an unit test?


in case of a FEATURE REQUEST:
 
 - Why do we need it?
 - An example of the XML config, if relevant.

**Comment by 304NotModified** [comment]
```
           var jsonLayout = new JsonLayout
            {
                Attributes = {
                    new JsonAttribute("message", "${message}")
                }
            };
            fileTarget.Layout = jsonLayout 

```

Should work as you first tried.

But i'm still missing information as  NLog version etc

**Comment by sherry9872** [comment]
Nlog version 4.4.2

**Comment by sherry9872** [comment]
I face no errors but it does not create the file..

**Comment by 304NotModified** [comment]
OK, will try to test it this week

**Comment by snakefoot** [comment]
@sherry9872 Do you remember to assign the NLog-config to the NLog-LogManager.Configuraion-property ?

And if you modify LoggingRules on the fly, do you remember to call NLog-LogManager.ReconfigExistingLoggers() ?

Have you read about the [NLog Configuration API](https://github.com/nlog/NLog/wiki/Configuration-API) ?

**Comment by 304NotModified** [comment]
works for me:

```c#
var jsonLayout = new JsonLayout
{
    Attributes = {
        new JsonAttribute("message", "${message}")
    }
};

var fileTarget = WrapFileTarget(new FileTarget
{
    FileName = "c:\\temp\\json-test.log",
    Layout = jsonLayout
});
var config = new LoggingConfiguration();
//add target and rule
config.AddRule(LogLevel.Trace, LogLevel.Fatal, fileTarget);
//at last asign
LogManager.Configuration = config;

//test
logger.Debug("aaa");
logger.Info("bbb");
logger.Warn("ccc");
```

![image](https://cloud.githubusercontent.com/assets/5808377/23530254/39da61b0-ffa1-11e6-8477-feb8ff5abe91.png)

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, let us know!
