### ISSUE TITLE
LifeStyle of Logger instance

### ISSUE THREAD

**Issue by Kahbazi** [NLog/NLog#1983]
Hi, I have a question about lifestyle of Logger class in a web application.

I add five different logger and write a wrapper class for them : 

```
    internal class CommonNLogResolver : ICommonLogger
    {
        private readonly NLog.Logger commonLog;
        private readonly NLog.Logger errorLog;
        private readonly NLog.Logger dataBaseLog;
        private readonly NLog.Logger logExceptionLogger;
        private readonly NLog.Logger clientLogger;

        public CommonNLoggerResolver()
        {
            commonLog = NLog.LogManager.GetLogger(Constants.CommonLog);
            errorLog = NLog.LogManager.GetLogger(Constants.ErrorLog);
            dataBaseLog = NLog.LogManager.GetLogger(Constants.DBLog);
            logExceptionLogger = NLog.LogManager.GetLogger(Constants.LogExceptionLog);
            clientLogger = NLog.LogManager.GetLogger(Constants.ReportLog);
        }
    }
```

I look at the LogFactory class and since it has a cache for logger I don't know what lifestyle is appropriate for my wrapper class.

so my question is should I register this class **singleton** , **transient** or **scope**?
also I'm using SimpleInjector for Dependency Injection.

ps : I'm using .Net 4.6 and Nlog 4.3.10

**Comment by 304NotModified** [comment]
This is more a DI question the NLog IMO. 

I don't use SimpleInjector, so I don't know what singleton , transient or scope are

**Comment by Kahbazi** [comment]
ok, let me ask my question another way.

which approach is better for using NLog?

1. Having a class which has all the Logger that application needs as some **static fields**.

```
 class CommonNLogResolver
    {
        public static NLog.Logger commonLog =NLog.LogManager.GetLogger(Constants.CommonLog);
        public static NLog.Logger errorLog =NLog.LogManager.GetLogger(Constants.ErrorLog);
        public static NLog.Logger dataBaseLog =NLog.LogManager.GetLogger(Constants.DBLog);
        public static NLog.Logger logExceptionLogger =NLog.LogManager.GetLogger(Constants.LogExceptionLog);
        public static NLog.Logger clientLogger =NLog.LogManager.GetLogger(Constants.ReportLog);
    }

```

in this case whenever I need to log something I don't need to instantiate `CommonNLogResolver` or `NLog.Logger`, I can use the static field which already has been instantiate.

2. Having a class which has all the Logger that application needs as some **non-static fields**.

 ```
class CommonNLogResolver
    {
        private readonly NLog.Logger commonLog;
        private readonly NLog.Logger errorLog;
        private readonly NLog.Logger dataBaseLog;
        private readonly NLog.Logger logExceptionLogger;
        private readonly NLog.Logger clientLogger;

        public CommonNLoggerResolver()
        {
            commonLog = NLog.LogManager.GetLogger(Constants.CommonLog);
            errorLog = NLog.LogManager.GetLogger(Constants.ErrorLog);
            dataBaseLog = NLog.LogManager.GetLogger(Constants.DBLog);
            logExceptionLogger = NLog.LogManager.GetLogger(Constants.LogExceptionLog);
            clientLogger = NLog.LogManager.GetLogger(Constants.ReportLog);
        }
    }

```

in this case whenever I need to log something I create a new instance of my class and in its constructor the loggers will be created and this actions will repeat for each time that application needs to log something.

**Comment by 304NotModified** [comment]
1. Static fields.  It's one of the recommendations to use static fields. See wiki. 

That's Singleton I guess?

You have the same question on stackoverflow isn't it? ;)

**Comment by Kahbazi** [comment]
yep :)

**Comment by 304NotModified** [comment]
Has your question being answered?

**Comment by Kahbazi** [comment]
yes, I'm using static property for Logger

**Comment by 304NotModified** [comment]
👍 ok thx
