### ISSUE TITLE
aspnet layout not work

### ISSUE THREAD

**Issue by Tony1952466760** [NLog/NLog#1989]
Hi! Thanks for reporting this feature/bug/question! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

For .NET Core users, please check the platform support: https://github.com/NLog/NLog/wiki/platform-support

**Type** (choose one):
- Question

**NLog version**: (e.g. 4.4.3)

**Platform**: .Net 4.5 

**Current NLog config** (xml or C#, if relevant)

I include NLog.dll NLog.Web.dll

```xml
<parameter name="@ContentType" layout="${aspnet-request:header=Content-Type}"></parameter>
```

But ContentType is empty. Why?

**Comment by 304NotModified** [comment]
probably you're missing something in your config or code. 

 Check https://github.com/NLog/NLog.web/wiki/Getting-started-with-ASP.NET-Core-(project.json) and especially step 2 and 3

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, let us know!
