### ISSUE TITLE
NLog email send hands whole application if no internet connection

### ISSUE THREAD

**Issue by PatrickRyder** [NLog/NLog#1990]
Hi! Thanks for reporting this feature/bug/question! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

For .NET Core users, please check the platform support: https://github.com/NLog/NLog/wiki/platform-support

Bug
NLog version: 4.4.3

.NET 4.5.2 Windows 10 WPF Application (target application failed on 64-bit Windows 10 Intel i7 machine)

[NLog.config.txt](https://github.com/NLog/NLog/files/798888/NLog.config.txt)

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="false"
      internalLogLevel="Off" internalLogFile="C:\Temp\NLogInternalLogFile.txt">

	<!--
		Optional - add some variables.
		https://github.com/nlog/NLog/wiki/Configuration-file#variables
		<variable name="myvar" value="myvalue"/>
	-->

	<!--
		See https://github.com/nlog/nlog/wiki/Configuration-file for information on customizing logging rules and
		outputs.
	-->

	<targets>

		<!--
			Add targets here...
			See https://github.com/nlog/NLog/wiki/Targets for possible targets.
			See https://github.com/nlog/NLog/wiki/Layout-Renderers for the possible layout renderers.
		-->

		<!--
			EXAMPLE: Write events to a file with the date in the filename.
			<target xsi:type="File" name="f" fileName="${basedir}/logs/${shortdate}.log"
				layout="${longdate} ${uppercase:${level}} ${message}" />
		-->
		<target
			name="DateTimeNamedLog"
			xsi:type="File"
			fileName=".\Logs\${longdate:cached=true}.txt"
			layout="${message}"
			archiveFileName=".\Logs\Archive\${shortdate}{#}.txt"
			archiveAboveSize="1048576"
			archiveEvery="Day"
			archiveNumbering="DateAndSequence"
			maxArchiveFiles="20">
		</target>

		<target
			name="MainLog"
			xsi:type="File"
			fileName=".\Logs\MainLog.txt"
			layout="${message}"/>

		<target
			name="EmailLog"
			xsi:type="Mail"
			layout="${message}"
			html="false"
			addNewLines="false"
			replaceNewlineWithBrTagInHtml="true"
			encoding="UTF-8"
			subject="DoddPMP Error!"
			to="patrickskelton@gmail.com"
			bcc=""
			cc=""
			from="log@doddeng.co.uk"
			body="${message}"
			smtpUserName="REMOVED FOR SECURITY"
			enableSsl="true"
			smtpPassword="REMOVED FOR SECURITY"
			smtpAuthentication="Basic"
			smtpServer="smtp.gmail.com"
			smtpPort="587">
		</target>

	</targets>

	<rules>

		<!-- Add logging rules here... -->

		<!--
			EXAMPLE: Write all events with minimal level of Debug (so Debug, Info, Warn, Error and Fatal, but not Trace)
			to "MyLog" <logger name="*" minlevel="Trace" writeTo="MyLog" />
		-->

		<logger name="*" minlevel="Trace" writeTo="MainLog"/>
		<logger name="*" minlevel="Trace" writeTo="DateTimeNamedLog"/>
		<!--<logger name="*" minlevel="Error" writeTo="EmailLog"/>-->

	</rules>

</nlog>

```

In case of a BUG:

What is the current result?
Entire application hangs, seemingly while trying to send the email specified by the target in the config file.

What is the expected result?
Normally, the email sends fine, with no error message or internal exception (though I did not have NLog set to produce internal exceptions).

Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
Sorry, no (please see note * below).

Please post full exception details (message, stacktrace, inner exceptions)
(please see note * below)

Are there any work arounds? yes/no
It is now functioning fine again but I want to guard against future occurrences.

Is there a version in which it did worked? 
(please see note * below)

Can you help us by writing an unit test?
(please see note  * below)

NOTE * : You will note from the config file that I am using Google's SMTP server to bounce NLog emails, so this issue may not arise if I had an internal email server.  I got this bug while my internet connection was broken.  It is now working again and so far I haven't managed to reproduce the bug.  I will continue to try, but I have limited time windows when I can disconnect the internet.  I will also enable the internal NLog logging, to see if I can find out what is happening.  If I find out anything further, I will update the bug.

**Comment by 304NotModified** [comment]
Hi,

You could do two things:

- lower the [timeout of the mailtarget](https://github.com/NLog/NLog/wiki/Mail-target). It's now 10 seconds. 
- send the mail async. See https://github.com/NLog/NLog/wiki/AsyncWrapper-target#async-attribute

Because your are sending synchronously, it will keep the (main) thread waiting for the timeout.,

**Comment by PatrickRyder** [comment]
It hangs seemingly indefinitely, much longer than the 10 seconds currently set, but maybe that is because it is running in the debugger.  The async option fixed it though.  Excellent!

I'd test more but I have limited options to cut the internet connection.

Thank you for your help.

- Patrick
