### ISSUE TITLE
Could not load file or assembly

### ISSUE THREAD

**Issue by BrenoMiyazaki** [NLog/NLog#1994]
**Type**
- Bug

**NLog version**:
- 4..4.3

**Platform**: .Net 4.6.2

**Current NLog config**
```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="false"
      internalLogLevel="Off" internalLogFile="c:\temp\nlog-internal.log">

  <variable name="myvar" value="myvalue"/>
  <targets>
    <target xsi:type="File" name="logFile" fileName="${basedir}/logs/WebAPI/${shortdate}.log" layout="${longdate} ${uppercase:${level}} ${logger} ${callsite} ${callsite-linenumber} ${message} ${exception} " />
  </targets>

  <rules>
    <logger name="*" minlevel="Trace" writeTo="logFile" />
  </rules>
</nlog>
```

I have a MVC system running perfectly fine in my developing environment but as soon as I publish the site into my remote server, it gives me this error:
_**Could not load file or assembly 'NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c' or one of its dependencies. The system cannot find the file specified.**_

I doubled check the presence of the DLLs in correspondent folders and I can't figure it out why I'm having this issue... I also did a thorough check on access and security permission on the project folders.

Any help would be much appreciated!

**Comment by 304NotModified** [comment]
could you check the properties of the nlog.dll? e.g.

![image](https://cloud.githubusercontent.com/assets/5808377/23369400/863ab466-fd11-11e6-8212-906e6748a8a1.png)

**Comment by BrenoMiyazaki** [comment]
Hi!

This is it:

![sem titulo](https://cloud.githubusercontent.com/assets/25386333/23369868/869777ac-fcf1-11e6-8ee5-3a9ab336128e.png)

**Comment by BrenoMiyazaki** [comment]
Any insights on this?

**Comment by 304NotModified** [comment]
Do you have a Assemblybinding in your config?

**Comment by BrenoMiyazaki** [comment]
Actually, not. 
I'm running with the mininum configuration setup as listed in the hub tutorial.

It is working flawlessly in my dev envinronment.

**Comment by 304NotModified** [comment]
Maybe dumb question but is net462 installed on your server?

**Comment by 304NotModified** [comment]
Is your Project build with anycpu?

**Comment by BrenoMiyazaki** [comment]
Not dumb at all lol, but it is installed.
This app was working without NLog previously.

I moved from log4net and it stopped working after it.

And yes, it is built with anycpu.

**Comment by 304NotModified** [comment]
Maybe this is helpful. 

https://msdn.microsoft.com/en-us/library/e74a18c4(v=vs.71).aspx

**Comment by BrenoMiyazaki** [comment]
Yep, but my remote doesn't have VS installed... 
And I'm afraid I can't install it either...

**Comment by 304NotModified** [comment]
Maybe its a good idea to setup a small test application and to test with that?

Also check your apppool settings.

**Comment by BrenoMiyazaki** [comment]
Hmmm it seems this is a never seen issue before right?

**Comment by 304NotModified** [comment]
I have experience with runtime binding issues, but not with NLog 4. We have also a fixed assembly version in NLog 4, so you don't need an Assembly binding in your config.

**Comment by BrenoMiyazaki** [comment]
That's what I thought... 
But I'm really clueless on this because it's the first time it happens with me...

**Comment by 304NotModified** [comment]
I you have a small example application, I could double check it.

**Comment by BrenoMiyazaki** [comment]
At the moment no... I'm gonna work on it, and attach it here a.s.a.p.

**Comment by 304NotModified** [comment]
Also double checked the assembly version and public key of NLog 4.4.3, it's correct

(attaching images fails on github now `Something went really wrong, and we can’t process that file.  Choose Files`)

**Comment by kezcwy** [comment]
I've just installed NLog 4.4.3 and getting the same error as well

**Comment by 304NotModified** [comment]
Which version was working?

**Comment by BrenoMiyazaki** [comment]
Just to making you know Julian,
I managed to make it work here...

Maybe it was a conjunction of re-uploading everything again, plus
re-installing .net 4.6.2, plus installing VS 2017...

It's running without any issues...
Em qui, 2 de mar de 2017 às 16:22, Julian Verdurmen <
notifications@github.com> escreveu:

**Comment by 304NotModified** [comment]
Glad to hear!

**Comment by BrenoMiyazaki** [comment]
Anyhow, it would be great if I did this step-by-step but haha

I was stuck with this for 4 days already!
Em qui, 2 de mar de 2017 às 17:23, Julian Verdurmen <
notifications@github.com> escreveu:

**Comment by Shiva799** [comment]
After fetching nlog.config file i get the values of target inside it to be 0 when in fact i have set 4 targets and 4 rules in nlog.config file. Basically it means that file is not being read. Why this might be happening i do not know. Has anyone faced this issue? Please tell me how can i resolve this issue.
Thanks,

**Comment by 304NotModified** [comment]
@Shiva799 stop spamming please

**Comment by Page-Not-Found** [comment]
@304NotModified Not trying spam here. But @kezcwy mentioned as not working, did that got resolved?
