### ISSUE TITLE
MappedDiagnosticsLogicalContext & NETStandard

### ISSUE THREAD

**Issue by johnkors** [NLog/NLog#2001]
**Type** (choose one):
- Question

**NLog version**: (e.g. 4.2.3)

**Platform**: .NET Core 

Hi,

What's the alternative to `MappedDiagnosticsLogicalContext` when it comes to the NETStandard versions?

**Comment by 304NotModified** [comment]
Currently none. We have to implement it, but missing the needed types. Will be fixed in netstandard 2 AFAIK

**Comment by johnkors** [comment]
Thx!

**Comment by snakefoot** [comment]
Resolved with #2025 (Will be included in next NLog 5.0 BETA)

**Comment by 304NotModified** [comment]
Yes indeed, beta 7
