### ISSUE TITLE
Double registration of NLog.Web.AspNetCore

### ISSUE THREAD

**Issue by grokky1** [NLog/NLog#2002]
**Type**: Question
**NLog version**: 5.0.0-beta05
**Platform**: .NET Core 

[The setup docs](http://github.com/NLog/NLog.Web/wiki/Getting-started-with-ASP.NET-Core-(project.json)#1-add-dependency-in-projectjson) say to do this:

    <extensions>
        <add assembly="NLog.Web.AspNetCore"/>
    </extensions>

[And this](http://github.com/NLog/NLog.Web/wiki/Getting-started-with-ASP.NET-Core-(project.json)#3-update-startupcs):

    app.AddNLogWeb();

However, `AddNLogWeb` is already in the `NLog.Web.AspNetCore` assembly. So are both steps required?

**Comment by 304NotModified** [comment]
Good one!

This was first needed, but it could be removed.

**Comment by 304NotModified** [comment]
Well both are now required, but we could make some changes in code that this isn't needed.

**Comment by 304NotModified** [comment]
This is fixed in NLog.Web.AspNetCore 4.5
