### ISSUE TITLE
Custom NLog target with async writing

### ISSUE THREAD

**Issue by grokky1** [NLog/NLog#2004]
**Type**: Question
**NLog version**: 5.0.0-beta05
**Platform**: .NET Core 

I want to write a [custom target](http://github.com/NLog/NLog/wiki/How%20to%20write%20a%20custom%20target) that logs to my database using Entity Framework Core.

In `NLog.Targets.Target` there is this:

    protected virtual void Write(LogEventInfo logEvent);

However my code is async, so I must do:

    protected override /*async Task*/void Write(LogEventInfo logEvent)   // problem is here
    {
        await WriteToEfContext(logEvent);               // problem is here
        // and so on...
    }

But there is no `Task WriteAsync` version of that method.

How do I write a custom target, with async support?

**Comment by snakefoot** [comment]
> How do I write a custom target, with async support?

I guess you override the following method, like this (Not tested with compiler):

```
private Task _previousTask;

protected override void Write(AsyncLogEventInfo logEvent)
{
    if (_previousTask == null)
        _previousTask = WriteTask(logEvent.LogEvent).ConfigureAwait(false).Start();
    else
        _previousTask.ContinueWith(WriteTask(logEvent.LogEvent));
    _previousTask.ContinueWith(prevTask => continuation(prevTask.Exception)).ConfigureAwait(false);
}

protected override void FlushAsync(AsyncContinuation asyncContinuation)
{
    if (_previousTask == null)
         asyncContinuation(null);
    else
        _previousTask.ContinueWith((prevTask) => asyncContinuation(null));
}

private Task WriteTask(LogEventInfo logEvent)
{
    // Create custom write Task
}

```

**Comment by grokky1** [comment]
@snakefoot Thanks, this looks really cool!

@304NotModified What do you think of it?

Maybe it's a good idea to wrap this behavior in a new method:

    protected virtual Task WriteAsync(LogEventInfo logEvent);

It's such a common use case.

**Comment by 304NotModified** [comment]
I think a new (abstract) base class (AsyncTarget) would be nice.

**Comment by grokky1** [comment]
@304NotModified Interesting... However, why would that be "better" than an async overload?

**Comment by 304NotModified** [comment]
Well then it's less clear which method to implement in each case. 

The targetWithLayout and others are only small additions to Target.

**Comment by 304NotModified** [comment]
Thanks @snakefoot. You could also copy it to here http://stackoverflow.com/questions/42605275/custom-nlog-target-with-async-writing

Will upvote it :)

**Comment by snakefoot** [comment]
@304NotModified Think I will have to do some testing first, my pseudo-code didn't pass the compiler test. The ContinueWith-logic had to be changed to call the WriteAsync using a delegate, and this required context-capture of the LogEvent-struct. This I didn't like, but now the logic has become complicated.

Now it has the following properties:
- Only uses a single Task to protect against out-of-order writing of LogEvents (And avoids using the entire thread pool).
- WriteAsync is called without holding Target-Lock-object to improve concurrency (loggers can schedule more LogEvents while the initial LogEvent call is being started).
- Having a requestQueue to make it easier to monitor pending requests.

Following features could probably be added:
- Support batching of multiple LogEvents in a single write operation.
- Support parallel writing of LogEvents using a limited number of concurrent Tasks.

```
    using System;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;
    using NLog.Common;

    public abstract class AsyncTarget : Target
    {
        private readonly CancellationTokenSource _cancelTokenSource = new CancellationTokenSource();
        private readonly Queue<AsyncLogEventInfo> _requestQueue = new Queue<AsyncLogEventInfo>(10000);
        private readonly Action _taskStartNext;
        private readonly Action<Task, object> _taskCompletion;
        private Task _previousTask;

        protected AsyncTarget()
        {
            _taskStartNext = TaskStartNext;
            _taskCompletion = TaskCompletion;
        }

        protected abstract Task WriteAsync(LogEventInfo logEvent, CancellationToken token);

        protected override void Write(AsyncLogEventInfo logEvent)
        {
            if (_cancelTokenSource.IsCancellationRequested)
            {
                logEvent.Continuation(null);
                return;
            }

            this.MergeEventProperties(logEvent.LogEvent);
            this.PrecalculateVolatileLayouts(logEvent.LogEvent);

            _requestQueue.Enqueue(logEvent);
            if (_previousTask == null)
            {
                _previousTask = Task.Factory.StartNew(_taskStartNext, _cancelTokenSource.Token, TaskCreationOptions.DenyChildAttach, TaskScheduler.Default);
            }
        }

        protected override void FlushAsync(AsyncContinuation asyncContinuation)
        {
            if (_previousTask == null)
            {
                InternalLogger.Debug("{0} Flushing Nothing", this.Name);
                asyncContinuation(null);
            }
            else
            {
                InternalLogger.Debug("{0} Flushing {1} items", this.Name, _requestQueue.Count + 1);
                _requestQueue.Enqueue(new AsyncLogEventInfo(null, asyncContinuation));
            }
        }

        protected override void CloseTarget()
        {
            _cancelTokenSource.Cancel();
            _cancelTokenSource.Dispose();
            _requestQueue.Clear();
            _previousTask = null;
            base.CloseTarget();
        }

        private void TaskStartNext()
        {
            AsyncLogEventInfo logEvent = default(AsyncLogEventInfo);
            do
            {
                lock (this.SyncRoot)
                {
                    if (_requestQueue.Count == 0)
                    {
                        _previousTask = null;
                        break;
                    }

                    logEvent = _requestQueue.Dequeue();
                }
            } while (!TaskCreation(logEvent));
        }

        private bool TaskCreation(AsyncLogEventInfo logEvent)
        {
            try
            {
                if (_cancelTokenSource.IsCancellationRequested)
                {
                    logEvent.Continuation(null);
                    return false;
                }

                if (logEvent.LogEvent == null)
                {
                    InternalLogger.Debug("{0} Flush Completed", this.Name);
                    logEvent.Continuation(null);
                    return false;
                }

                var newTask = WriteAsync(logEvent.LogEvent, _cancelTokenSource.Token);
                if (newTask == null)
                {
                    InternalLogger.Debug("{0} WriteAsync returned null", this.Name);
                }
                else
                {
                    lock (this.SyncRoot)
                    {
                        _previousTask = newTask;
                        _previousTask.ContinueWith(_taskCompletion, logEvent.Continuation, _cancelTokenSource.Token);
                        if (_previousTask.Status == TaskStatus.Created)
                            _previousTask.Start(TaskScheduler.Default);
                    }
                    return true;
                }
            }
            catch (Exception ex)
            {
                InternalLogger.Error(ex, "{0} WriteAsync failed on creation", this.Name);
            }
            return false;
        }

        private void TaskCompletion(Task completedTask, object continuation)
        {
            try
            {
                if (completedTask.IsCanceled)
                {
                    if (completedTask.Exception != null)
                        InternalLogger.Warn(completedTask.Exception, "{0} WriteAsync was cancelled", this.Name);
                    else
                        InternalLogger.Info("{0} WriteAsync was cancelled", this.Name);
                }
                else if (completedTask.Exception != null)
                {
                    InternalLogger.Warn(completedTask.Exception, "{0} WriteAsync failed on completion", this.Name);
                }
                ((AsyncContinuation)continuation)(completedTask.Exception);
            }
            finally
            {
                TaskStartNext();
            }
        }
    }
```

**Comment by grokky1** [comment]
I was just going to report it doesn't compile, then I see that post. Way way above my head! 😃

This is an excellent piece of code to include into the library itself.

I volunteer myself as a guinea pig for using it.

**Comment by snakefoot** [comment]
> You could also copy it to here

I have now also posted the code on stackoverflow. Maybe more eyes will reveal stuff, that my testing didn't show.

**Comment by snakefoot** [comment]
@grokky1 I have updated the AsyncTaskTarget to also have timeout monitoring (Default 150 secs). The updated code can be found in #2006

**Comment by grokky1** [comment]
@snakefoot That's really nice to have. I am playing around with it now in my dev branch, and I like it so far. I hope we can get it into an alpha release.

**Comment by 304NotModified** [comment]
@grokky1 do you have some experience to share about the AsyncTaskTarget?

**Comment by grokky1** [comment]
Yeah I was using it and it seems to work fine. I was using the target as part of .NET Core's built in container, as well as Autofac. The non-async version allowed me to use the logger as transient or per-request, which is what I needed, because my context is registered as per-request.

My team though decided to go another route, because the it's still not "in the wild" for long enough. But I'm still using it on some personal projects.

**Comment by snakefoot** [comment]
@grokky1 Any input for this wiki-page about AsyncTaskTarget: https://github.com/NLog/NLog/wiki/How-to-write-a-custom-async-target
