### ISSUE TITLE
Add Overloads That Support LogMessageGenerator with Exception

### ISSUE THREAD

**Issue by TheXenocide** [NLog/NLog#2014]
**Type**: Feature request

**NLog version**: 4.4.2

**Platform**: .Net 4.5

While working on our internal logging facade I noticed NLog doesn't support deferred message generation on method overloads that also support Exceptions. In many common scenarios I can see how Exceptions would be less likely to be filtered, but given support for logging exceptions as Verbose or Information it seems like it would still be relevant to allow message generation to happen after filtering rules are applied the same as any other message.

**Comment by TheXenocide** [comment]
I figured that would be the rationale, but there are known exceptions that can be handled but logged for diagnostic purposes as verbose/debug/etc. which are much less likely to be automatically redirected to the Event Log than warning/error/fatal. Our project is on a very tight timeline at the moment, so for now we're just invoking our delegate and passing the result along, but it would be nice in the long run so maybe I'll see if I'm able to come back to it later. Still, thought I'd bring it up while passing through. Thanks for everything you guys do :)

**Comment by 304NotModified** [comment]
Well forgot it, and I think it should be there for consistency :)

**Comment by c0shea** [comment]
Submitted PR #2051 for this feature

**Comment by TheXenocide** [comment]
Awesome, thanks guys! Out of curiosity, any idea when 4.4.6 will be hitting NuGet?

**Comment by 304NotModified** [comment]
closed by #2051

**Comment by 304NotModified** [comment]
This week :) 

If you need it earlier, I can push a beta

**Comment by TheXenocide** [comment]
We're really close to the end of our project so I think we'll wait for the stable build just to reduce likelihood of issues, but that's great, thanks a bunch!
