### ISSUE TITLE
target type WebService with protocol XmlPost with boolean parameter do not send valid xml values

### ISSUE THREAD

**Issue by VictorTerraGIS** [NLog/NLog#2016]
Hi!

Please someone change/fix into  [NLog/src/NLog/Targets/WebServiceTarget.cs](https://github.com/NLog/NLog/blob/master/src/NLog/Targets/WebServiceTarget.cs) file into the method WriteAllParametersToCurrenElement the next code snippet.

Original code (at time was copied)
```c#
            protected void WriteAllParametersToCurrenElement(XmlWriter currentXmlWriter, object[] parameterValues)
            {
                for (int i = 0; i < Target.Parameters.Count; i++)
                {
                    currentXmlWriter.WriteElementString(Target.Parameters[i].Name, Convert.ToString(parameterValues[i], CultureInfo.InvariantCulture));
                }
            }
```
with this one
```c#
            protected void WriteAllParametersToCurrenElement(XmlWriter currentXmlWriter, object[] parameterValues)
            {
                for (int i = 0; i < Target.Parameters.Count; i++)
                {
                    currentXmlWriter.WriteElementString(Target.Parameters[i].Name, System.Xml.XmlConvert(parameterValues[i]));
                }
            }
```
if is possible.

The issue is with values which are not string. I encounter a issue with **System.Boolean** type. Where the call `Convert.ToString(parameterValues[i], CultureInfo.InvariantCulture)` will return values 'True', 'False', when valid values for xml are 'true', 'false', '0', '1'. The issue comes (in my case) when http service receives the xml and try to revert back the boolean value from xml text value and throw an exception that is invalid boolean format ...

Regards,
Victor Scorpan

**Comment by snakefoot** [comment]
@VictorTerraGIS Have created a PR that should implement the "simple" fix #2017

**Comment by VictorTerraGIS** [comment]
Looks that case with boolean should be fixed by changes for fix #2017 , but I don't like how was solved the case with boolean int src/NLog/Targets/DefaultJsonSerializer.cs method 
```c# 
private static string JsonStringValue(object value, out TypeCode objTypeCode)
{
...
   switch (objTypeCode)
   {
       case TypeCode.Boolean:
             return (Boolean)value ? "true" : "false";   // boolean as lowercase
   }
...
}
```
since for Double and Single type used
```c#
return System.Xml.XmlConvert.ToString(singleValue);
```
and
```c#
return System.Xml.XmlConvert.ToString(doubleValue);
```

If for `HttpPostFormEncodedFormatter` class the changes from fix #2017 may be are Ok, then for `HttpPostXmlDocumentFormatter` I'm doubt that the changes are the most correct one even the case for boolean should be Ok. Here will appear for sure cases with datetime format.

From my point view instead of changes done for `HttpPostXmlDocumentFormatter` which are
```c#
currentXmlWriter.WriteElementString(Target.Parameters[i].Name, DefaultJsonSerializer.JsonStringValue(parameterValues[i]));
```
I will put my version with `System.Xml.XmlConvert`, because this kind of conversion already is used in NLog.
```c#
currentXmlWriter.WriteElementString(Target.Parameters[i].Name, System.Xml.XmlConvert(parameterValues[i]));
```

-
Victor Scorpan.

**Comment by snakefoot** [comment]
> @VictorTerraGIS I will put my version with System.Xml.XmlConvert, because this kind of conversion already is used in NLog.

I love your idea, and think it is very simple. Which is why I offered to create the PR. But then I discovered that we are missing System.Xml.XmlConvert.ToString(object).

I mixed your request into the refactoring of the Json-serializer, because I could see that it suffered from the exact same issues as the parameters for the http-request.

But you are right, that since I have added tests to show that boolean is working, then I should also add test for DateTime. I guess the official format for http-requests (and Json) is ISO 8601 ?

**Comment by VictorTerraGIS** [comment]
This issue is more referred to the serialization of C# types to xml, than the serialization to http and/or json. This is becase the `HttpPostXmlDocumentFormatter` add serialized xml data as POST data of http request. So, as I see this should be related more to xml, than to http.

I didn't create PR, because of my practice before PR I should check and test the requested changes. But for this I should to prepare development environment for building the changes. So, I thought that may be somebody who already have prepared environment will check this and will add my requested changes to the build.

> I guess the official format for http-requests (and Json) is ISO 8601 ?
- Not really ISO 8601. You should check this [XSD Date and Time Data Types](https://www.w3schools.com/xml/schema_dtypes_date.asp) if do you think to do convert yourself the date, datetime, time offset data to xml value.

**Comment by snakefoot** [comment]
@VictorTerraGIS Well lucky for me (and maybe you), then XmlConvert.ToString(DateTime) conforms to ISO 8601. Have now made an extra commit where the JsonStringValue-method, has become a wrapper around XmlConvert.ToString().

**Comment by 304NotModified** [comment]
great work @snakefoot !

Will release soon 4.4.5

**Comment by 304NotModified** [comment]
I released a beta first. Could you check with this release? https://www.nuget.org/packages/NLog/4.4.5-beta1 

Thx!
