### ISSUE TITLE
The target log contains  levels  which we don't want

### ISSUE THREAD

**Issue by yinanrong** [NLog/NLog#2026]
i want to filter  logs that start with  "Microsoft." and are below "Warn"，so  the rules  in my nlog.config  file is like this :

 <rules>

    <logger name="*" minlevel="Debug" writeTo="xxx" />

    <logger name="Microsoft.*" minlevel="Warn" writeTo="xxx" final="true" />

  </rules>

but  i found  it  doesn't work(i.e. ,all levels that start with "Microsoft." were  wroten)，i am not sure  where the problem is in，i wanna some help, thanks

**Comment by 304NotModified** [comment]
The order of the `<logger>` rules matter.

This is a good example:

```xml
  <rules>
    <!--All logs, including from Microsoft-->
    <logger name="*" minlevel="Trace" writeTo="allfile" />

    <!--Skip Microsoft logs and so log only own logs-->
    <logger name="Microsoft.*" minlevel="Trace" writeTo="blackhole" final="true" />
    <logger name="*" minlevel="Trace" writeTo="ownFile-web" />
  </rules>
```
See https://github.com/NLog/NLog.web/wiki/Getting-started-with-ASP.NET-Core-(project.json)

**Comment by yinanrong** [comment]
The order of us is the same as you give.This is our  config:

<?xml version="1.0" encoding="utf-8"?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      internalLogLevel="Warn"
      internalLogFile="app_data\internal-nlog.txt">
  <variable name="Application" value="Feiniubus-Payment"></variable>
  <targets async="true">
    <target name="Network_To_Logstash" xsi:type="Network" address="udp://xxx">
      <layout xsi:type="JsonLayout">
        <attribute name="Date" layout="${longdate}" />
        
        <attribute name="Level" layout="${level}" />
        <attribute name="Message" layout="${message}" />
        <attribute name="Exception" layout="${exception}" />
        <attribute name="Stacktrace" layout="${stacktrace}" />
        <attribute name="Application" layout="${Application}" />
        <attribute name="EventId" layout="${event-properties:item=EventId.Id}" />
        <attribute name="EventName" layout="${event-properties:item=EventId.Name}" />
      </layout>
    </target>
  </targets>
  <rules>
    
    <logger name="*" minlevel="Debug" writeTo="Network_To_Logstash" />
    
    <logger name="Microsoft.*" minlevel="Warn" writeTo="Network_To_Logstash" final="true" />
  </rules>
</nlog>

**Comment by 304NotModified** [comment]
No it isn't? Check the order of the logger rules.

**Comment by yinanrong** [comment]
ok,thank you very much.

**Comment by 304NotModified** [comment]
:+1:
