### ISSUE TITLE
${callsite} ${callsite-linenumber} renderers with wrong values

### ISSUE THREAD

**Issue by BrenoMiyazaki** [NLog/NLog#2027]
**Type** (choose one): Bug
**NLog version**: (e.g. 4.4.4)
**Platform**: .Net 4.6.2

**Current NLog config** (xml or C#, if relevant)
```xml
<variable name="directory" value="c:/logs/"/>
<targets>
    <target
      xsi:type="File"
      name="logFile"
      fileName="${directory}/${shortdate}.log"
      layout="${longdate} ${uppercase:${level}} ${logger}
              ${message} ${callsite} ${callsite-linenumber}
              ${exception:format=toString}" />
</targets>

<rules>
  <logger name="*" minlevel="Trace" writeTo="logfile" />
</rules>

```
Hi!
I have created a project for NLog to be used across my solution and this is the class:

```c#
namespace Project.Util.Log
{
    using System;
    using System.Runtime.CompilerServices;
    using NLog;

    public static class LogService
    {
        public static void Log<T> ( LogLevel level, string message = null, Exception exception = null, [CallerMemberName] string caller = null, [CallerLineNumber] int line = 0 ) where T : class
        {   
            if ( level.Equals ( LogLevel.Error ) )
                LogManager
                    .GetLogger ( typeof ( T ).Name )
                    .Error (
                        exception,
                        string.IsNullOrEmpty ( message ) ? exception?.Message : message,
                        typeof ( T ).FullName,
                        caller,
                        line );
            else
                LogManager
                    .GetLogger ( typeof ( T ).Name )
                    .Log (
                        level,
                        message,
                        typeof ( T ).FullName, 
                        caller, 
                        line );
        }
    }
}
```

When I call it from the other projects like this:
`Project.Measurement.YearMeasurent.Log<YearMeasurement> ( LogLevel.Error, exception.Message, exception );`

[CallerMemberName], [CallerLineNumber] are passing correct values (member1, line XX);

When it hits the LogManager.GetLogger.Error() the parameters still holds the passed values, but it saves "Log" as member name and the current line from this method...

I'm a bit confused on this because of the disparity and the unexpected beahavior...

Any help will be much appreciated!

Best regards!

**Comment by 304NotModified** [comment]
Hi!

Please explain what is expected here. 

If you call `.Error(..)`, the parameters are `.Error(Exception, formatstring, FormatParameter1, formatParameter2)` etc.

e.g.

```
               Logger.Error(
                         exception,
                        "I have an issue on type {0} from caller {1} at line {2}
                        typeof ( T ).FullName,
                        caller,
                        line)

```

**Comment by BrenoMiyazaki** [comment]
Oh Hi Julian, it's you again! Lol...

Let's go to the problem...

when I call
```
LogManager.GetLogger ( typeof ( T ).Name ).Error (
                        exception,
                        string.IsNullOrEmpty ( message ) ? exception?.Message : message,
                        typeof ( T ).FullName,
                        caller,
                        line );
```
The caller method is sending caller = "GetTotalFromLast24Hours" and line = 86; Until here, it's fine....

But as soon as I check the log file, instead of GetTotalFromLast24Hours and 86, I'm getting Log and 12;

Log is the name of the method which has the logging mechanism, as I mentioned in the first post.

I invoke the method like this:
`Project.Measurement.YearMeasurent.Log<YearMeasurement> ( LogLevel.Error, exception.Message, exception );`

Did you understand a bit?

**Comment by BrenoMiyazaki** [comment]
Julian, you posted a test Project here, but it seems you deleted it before I could try...

Would you mind posting it again?

Best regards!

**Comment by 304NotModified** [comment]
> Julian, you posted a test Project here, but it seems you deleted it before I could try...

Did I? I'm not aware of that. 

Anyway, the ` ${callsite}`  (same for `${callsite-linenumber}`) is logging the callsite of the your helper. You can't pass the callsite to the logger and use  ${callsite} for it. 

You could use event-properties to pass the other callsite, e.g.

```c#
Logger logger = LogManager.GetCurrentClassLogger();
LogEventInfo theEvent = new LogEventInfo(LogLevel.Debug, "", "Pass my custom value");
theEvent.Properties["mycaller"] = caller;
theEvent.Properties["mylineno"] = line;
Logger.Error(theEvent);
```

usage `${event-properties:mycaller}` (instead of `${callsite}` )
usage `${event-properties:mylineno}` (instead of `${callsite-linenumber}` )

**Comment by BrenoMiyazaki** [comment]
Strange... must be some sort of confusion I made in my Inbox...

Oh, I got it then... the added layer of code kind of messes up with the callsite properties...
I'm gonna try it with LogEventInfo...

Thanks again for tour time!

**Comment by 304NotModified** [comment]
👍 good luck!
