### ISSUE TITLE
which renderers can get the Solution Name of the project

### ISSUE THREAD

**Issue by oppoic** [NLog/NLog#2028]
Type:Question
NLog version: 4.4.4
Platform:.Net 4.5
Current NLog config:

```xml
<nlog>
  <targets>
    <target xsi:type="File" name="f2" fileName="D:\log\SolutionName\${shortdate}.log" layout="${uppercase:${level}} ${longdate} ${message}" />
  </targets>
  <rules>
    <logger name="*" minlevel="Debug" writeTo="f2" />
  </rules>
</nlog>

```
A very sample question:As the xml file above,now '**SolutionName**' is Fixed value,which Layout Render should i use to get the SolutionName of current project?
${callsite}? I don't know how to set the parameter of this Layout Render :(

**Comment by 304NotModified** [comment]
I don't think its possible. AFAIK we can't read the solution name in c#?

You could use the namespace or folder name, but it requires some lines of code.

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, let us know!
