### ISSUE TITLE
Sourcefilename and number

### ISSUE THREAD

**Issue by KlausWilly** [NLog/NLog#2044]
**Type** :Question
**NLog version** :4.4.5
**Platform**: .Net 4.0 4.5

Hello together;

Bug or problem ? i dont know

I try to send out into nlogviewer the message + Sourcecodefile and number
thats my konfig for this:
        <target name="Viewer" xsi:type="NLogViewer"
            address="udp4:127.0.0.1:4000"
            includeCallSite="true"
            includeSourceInfo="true"
            includeMdc="true"
            includeNdc="true"
            includeNLogData="true"            
            />            
   
everything works fine but i dont see the Sourcefilename and Linenumber
Thats send to my viewer:

```
<log4j:event` logger="Program" level="TRACE" timestamp="1490959857884" thread="1">
        <log4j:message>
                entering func 'get_Givestring' , Stackframe='22'
        </log4j:message>
        <log4j:locationInfo class="Program.con"
                            method="System.String get_Givestring(System.String)" 
                            file=""
                            line="0"/>
        <log4j:properties>
                <log4j:data name="log4japp" value="Test.exe(12148)"/>
                <log4j:data name="log4jmachinename" value="PC1"/>
        </log4j:properties>
</log4j:event>`
```
thanks for helping 

Klaus

**Comment by 304NotModified** [comment]
Have you enabled/deployed the pdb files? Seehttps://msdn.microsoft.com/en-us/library/ee416588(v=vs.85).aspx

**Comment by KlausWilly** [comment]
Hi Julian;

Thanks for reacting to my question.

Yes the pdb-Files are there.
i have tested it with some Textfiles and the info then was there.

This is they correpondig Layoutrenderer:
```
<target name="File" 
                xsi:type="File"
                fileName="${var:logDirectory}\${var:baseFilename}.log"
                layout="${longdate} | ${level:uppercase=true} | ${callsite:fileName=True} | ${message}"
                archiveFileName="${var:archivDirectory}\${var:baseFilename}_{######}.log"
                />

```
Then i see in the Logfile:
```
2017-04-03 08:59:59.2750 | INFO | xxxx.xxxx.Classname(X:\aaaa\bbbb\Filename.vb:410) | Messsagetext
```
that's ok. (i think)

But as mentioned befor: nothing happen when using target "Viewer NlogViewer"

thanks for helping

Klaus

**Comment by 304NotModified** [comment]
So it works with a file target but not with NLogViewer target?

Could you post the config?

**Comment by KlausWilly** [comment]
Sure, i can.

That's the problem. It works with File Target but not with Viewer
and Yes **includesourceinfo** is set.

```
<target name="Viewer" xsi:type="NLogViewer"
            address="udp4://${machinename}.Myname.com:4000"
            includeCallSite="true"
            includeSourceInfo="true"
            includeMdc="true"
            includeNdc="true"
            includeNLogData="true"            
            />            
```

thanks Klaus

**Comment by snakefoot** [comment]
Think it is because of this:

`public class SimpleLayout : Layout, IUsesStackTrace`

Which is different from this:

`public class Log4JXmlEventLayout : Layout`

I'm guessing the logic should be, that if the Layout depends on a renderer that implements IUsesStackTrace, then it should capture StackTrace. But apparently it is the other way around.

If you make a NLogViewer parameter that includes `${callsite:fileName=True}`, then I think everything will work in the NLogViewer-Target.

This is of course a bug :)

**Comment by 304NotModified** [comment]
Great work @snakefoot!

**Comment by KlausWilly** [comment]
Hi snakefoot;

Thanks for the Info.
your workaround works like expected.

best regards
Klaus

**Comment by 304NotModified** [comment]
Thanks for the feedback!
