### ISSUE TITLE
Enable / fix two FileTarget unit tests

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#2050]
Two unit tests are skipped with the reason "Should be fixed in NLog 4.5"

In FileTargetTests.cs:

- [ ] `HandleArchiveFilesMultipleContextMultipleTargetTest()`
- [ ] `HandleArchiveFilesMultipleContextSingleTargetTest_ascii()`

https://github.com/NLog/NLog/blob/bc25298ce61bcf79a701ac001b24e334488e20cf/tests/NLog.UnitTests/Targets/FileTargetTests.cs#L2823

**Comment by snakefoot** [comment]
Fixed with #1993

**Comment by 304NotModified** [comment]
ah thx!
