### ISSUE TITLE
Question:ConfigFile  Path

### ISSUE THREAD

**Issue by zuosc** [NLog/NLog#2054]
**Type** (choose one):
- Question

**NLog version**: "NLog.Extensions.Logging  Version="1.0.0-rtm-beta4" 

**Platform**:  NET Core 

Hi, I have  a question.   I must set the nlog config  file in folder 'config',and the config file name must 
 'nlog.config'.

so my code is  ` public static Logger logger = LogManager.GetCurrentClassLogger(path:"config/nlog.config");`

but it doesn't work.  

i know if it have a file 'NLog.config'  ,it works.

so  how i do it? 

thank you!

**Comment by 304NotModified** [comment]
You need to pass the path of the config to `env.ConfigureNLog`, 

e.g. in startup.cs"


```c#
public Startup(IHostingEnvironment env)
{
    env.ConfigureNLog("config/nlog.config");
}
```
See https://github.com/NLog/NLog.Web/wiki/Getting-started-with-ASP.NET-Core-(project.json)

**Comment by zuosc** [comment]
oh  sorry。  I forgot to say.  This program is a ClassLibrary.  do not have 'startup.cs'

**Comment by zuosc** [comment]
@304NotModified   Hello？

**Comment by 304NotModified** [comment]
You could also use:

```c#
LogManager.Configuration = new XmlLoggingConfiguration("c:/tempconfig/nlog.config");
```

**Comment by zuosc** [comment]
0.0  Thank you very much.  I have a try

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, let us know!
