### ISSUE TITLE
Failing layout output is missing in .Net core

### ISSUE THREAD

**Issue by AnthonySteele** [NLog/NLog#2057]
We have some code around Nlog which I am porting to .Net core.
I test a Layout failure scenario, and this seems to behave differently in .Net core.

I have a failing layout as follows for test:

```csharp
public class NullReferenceLayout : Layout
{
	protected override string GetFormattedMessage(LogEventInfo logEvent)
	{
		throw new NullReferenceException();
	}
}
```

And elsewhere

```csharp
 public class FlattenedJsonLayout : JsonLayout
 {
 ...
             string renderedValue;
            try
            {
                renderedValue = renderer.Render(source);
            }
            catch (Exception ex)
            {
                renderedValue = $"Render failed: {ex.GetType().Name} {ex.Message}";
            }

... 
 }
 
 
 var layout = new FlattenedJsonLayout();
layout.Attributes.Add(new JsonAttribute("fail1", new NullReferenceLayout()));
```

on Windows this produces json output:

`{"fail1":"Render failed: NullReferenceException", ... }`

but on netcore / linux this key-value pair is missing.

We use resilient layouts because some of our co-workers have custom code to log values derived from the current http request as layout properties in the `nlog.config` file. They also have a desire to log at startup when there is no current http request and failure ensures. I am trying to allow logging to work in this case, and also highlight what exactly the issue is, so that this custom logging code can be made resilient or otherwise fixed.

It's odd that something about either exceptions or layout rendering seems to work differently on .Net core.

-------

Hi! Thanks for reporting this feature/bug/question! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

**Type** (choose one):

- Bug

**NLog version**:  4.4.5 / 5.0.0-beta06

**Platform**:  .Net 4.5 /  .NET Core 

```

**Comment by 304NotModified** [comment]
Hi, did you checked the internal log for errors?

**Comment by AnthonySteele** [comment]
Can you get these internal logs from a build on travis, or do I need a linux machine to test on?
It is a `MemoryTarget` in the test, yes.

**Comment by 304NotModified** [comment]
CI logs are fine :)

**Comment by AnthonySteele** [comment]
I will investigate how to get travis to keep this information.

**Comment by 304NotModified** [comment]
I think `<nlog internalLogToConsole="true" ...>` should be enough?

**Comment by snakefoot** [comment]
If using xUnit2 then you will have fun trying to write to the console. You can look at the changes made in NLogTestBase.cs for how to activate the Xunit.Abstractions.ITestOutputHelper and then pipe the trace-output to this output-helper.

Then one can just enable the `InternalLogger.LogToTrace = true`

**Comment by 304NotModified** [comment]
Another option is to write to a file. Dunno if Travis has artifacts like appveyor

**Comment by AnthonySteele** [comment]
We're using Nunit 3.6.1 and the NUnitLite runner.

**Comment by AnthonySteele** [comment]
Ok, after getting the internal logs going, it turns out that `exception.MustBeRethrown()` is true in regular .Net and false in .Net core. 
https://github.com/NLog/NLog/blob/master/src/NLog/LayoutRenderers/LayoutRenderer.cs#L175

I can set `LogManager.ThrowExceptions = true` in the test code and the test pass in .Net core, butit's there in the config.  I think that this means that the `nlog.config` is getting read in regular .Net, but not in .Net core.

**Comment by 304NotModified** [comment]
> think that this means that the nlog.config is getting read in regular .Net, but not in .Net core.

That's possible as `${basedir}` wont work yet and a lot has been changed regarding the "root" dir. Could you share your config and C# NLog init code?

It this an asp.net core or console application?

**Comment by 304NotModified** [comment]
Do you need some help on this or can we close it?

**Comment by AnthonySteele** [comment]
We're good; thanks for the help. I look forward to trying `5.0.0-beta07`

**Comment by 304NotModified** [comment]
OK, that one went live yesterday :)
