### ISSUE TITLE
Fluent API Method not found: 'Void NLog.Fluent.LogBuilder.Write()'.

### ISSUE THREAD

**Issue by luiscaiano** [NLog/NLog#2059]
**Type** Bug

**NLog version**: (e.g. 4.4.5)

**Platform**: .Net 4.0 / .Net 4.5 

In case of a BUG:

- What is the current result?
  System.MissingMethodException: Method not found: 'Void NLog.Fluent.LogBuilder.Write()'.
- What is the expected result?
  success log write
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
  No
- Please post full exception details (message, stacktrace, inner exceptions)
  N/A
- Are there any work arrounds? yes/no
  No
- Is there a version in which it did worked? 
  No
- Can you help us by writing an unit test?
  Dont know, that would depend on mocking platform, since this is related to usage with multiple target builds.

- steps to replicate the issue: 
 Have a lib compiled against NLog 4.4.5 net40, using 

have inside code 
_logger.Info()
       .Message("This is a test fluent message '{0}'.", DateTime.Now.Ticks)
       .Property("Test", "InfoWrite")
       .Write();

then use said lib with application compiled against NLog 4.4.5 net45, 
when running method 'Void NLog.Fluent.LogBuilder.Write()'. is produced.

- I believe that this is because of the signature of the method in NLog 4.4.5 net45 was change by using optional arguments, making it not able to find appropriate overload method. 

i propose one of 2 alternatives
 - remove usage of optional arguments for discrete specification, in  net45 ( this will MOST likely work) , 
 - Add overload in net40 will all possible arguments ( would have to try it out )

**Comment by 304NotModified** [comment]
AFAIK there is not change in those methods? Adding a optional parameter isn't allowed. 

None of the files has been changed lately:

![image](https://cloud.githubusercontent.com/assets/5808377/25094604/40068abc-2398-11e7-8f1b-7551547aa745.png)

**Comment by luiscaiano** [comment]
- i am not saing that this is a issue resulting from 4.4.5, rather that i detected with 4.4.5, i do believe this goes back to initial implementation/ change with net4.5, 
- I am not stating to ADD optional parameter, but it is present in net4.5 build.

as you can check here

https://github.com/NLog/NLog/blob/v4.4.5/src/NLog/Fluent/LogBuilder.cs:292
```
#if NET4_5
        /// <summary>
        /// Writes the log event to the underlying logger.
        /// </summary>
        /// <param name="callerMemberName">The method or property name of the caller to the method. This is set at by the compiler.</param>
        /// <param name="callerFilePath">The full path of the source file that contains the caller. This is set at by the compiler.</param>
        /// <param name="callerLineNumber">The line number in the source file at which the method is called. This is set at by the compiler.</param>
        public void Write(
            [CallerMemberName]string callerMemberName = null,
            [CallerFilePath]string callerFilePath = null,
            [CallerLineNumber]int callerLineNumber = 0)
        {
            if (callerMemberName != null)
                Property("CallerMemberName", callerMemberName);
            if (callerFilePath != null)
                Property("CallerFilePath", callerFilePath);
            if (callerLineNumber != 0)
                Property("CallerLineNumber", callerLineNumber);

            _logger.Log(_logEvent);
        }
#else
        /// <summary>
        /// Writes the log event to the underlying logger.
        /// </summary>
        public void Write()
        {
            _logger.Log(_logEvent);
        }
#endif
```

**Comment by 304NotModified** [comment]
Ow do you mean the .NET 4 version isn't binary compatible with the .NET 4.5 version?

**Comment by luiscaiano** [comment]
i dont know, but would have to try if it works, but , what about adding to NET4 version ?
``` 
Write(string callerMemberName, string callerFilePath, int callerLineNumber){
     if (callerMemberName != null)
                Property("CallerMemberName", callerMemberName);
            if (callerFilePath != null)
                Property("CallerFilePath", callerFilePath);
            if (callerLineNumber != 0)
                Property("CallerLineNumber", callerLineNumber);

            _logger.Log(_logEvent);
}
```
would that work ?, keeping existing Write, but adding a new method that would probably be accepted in 4.5 since the signature is equivalent.

**Comment by 304NotModified** [comment]
Not really as you calling `write`  without arguments in the .NET 4 code, and that one isn't available in .NET 4.5

If we add the write without arguments to .NET 4.5, then the caller attributes wont work :(

**Comment by luiscaiano** [comment]
something like this ?! wouldn't it work ?

```
#if NET4_5
        /// <summary>
        /// Writes the log event to the underlying logger.
        /// </summary>
        /// <param name="callerMemberName">The method or property name of the caller to the method. This is set at by the compiler.</param>
        /// <param name="callerFilePath">The full path of the source file that contains the caller. This is set at by the compiler.</param>
        /// <param name="callerLineNumber">The line number in the source file at which the method is called. This is set at by the compiler.</param>
        public void Write(
            [CallerMemberName]string callerMemberName = null,
            [CallerFilePath]string callerFilePath = null,
            [CallerLineNumber]int callerLineNumber = 0)
        {
            if (callerMemberName != null)
                Property("CallerMemberName", callerMemberName);
            if (callerFilePath != null)
                Property("CallerFilePath", callerFilePath);
            if (callerLineNumber != 0)
                Property("CallerLineNumber", callerLineNumber);

            _logger.Log(_logEvent);
        }
#else
        /// <summary>
        /// Writes the log event to the underlying logger.
        /// </summary>
        public void Write()
        {
            _logger.Log(_logEvent);
        }
Write(string callerMemberName, string callerFilePath, int callerLineNumber){
     if (callerMemberName != null)
                Property("CallerMemberName", callerMemberName);
            if (callerFilePath != null)
                Property("CallerFilePath", callerFilePath);
            if (callerLineNumber != 0)
                Property("CallerLineNumber", callerLineNumber);

            _logger.Log(_logEvent);
}
#endif
```

**Comment by 304NotModified** [comment]
what method do you like to invoke in .NET 4? `Write()` or `   Write(string callerMemberName, string callerFilePath, int callerLineNumber)`?

The first one isn't compatible with ` public void Write(
            [CallerMemberName]string callerMemberName = null,
            [CallerFilePath]string callerFilePath = null,
            [CallerLineNumber]int callerLineNumber = 0)` (note: those caller arguments are added at compile time)

the second one would be strange to use?

**Comment by luiscaiano** [comment]
the `Write()` is to keep compatibility with prev versions and `Write(string callerMemberName, string callerFilePath, int callerLineNumber)` to give compatibility with 4.5

**Comment by 304NotModified** [comment]
That's clear, but IMO it doesn't work. 



> what method do you like to invoke in .NET 4? Write() or Write(string callerMemberName, string callerFilePath, int callerLineNumber)?
> 
> The first one isn't compatible with public void Write( [CallerMemberName]string callerMemberName = null, [CallerFilePath]string callerFilePath = null, [CallerLineNumber]int callerLineNumber = 0) (note: those caller arguments are added at compile time)
> 
> the second one would be strange to use?

**Comment by snakefoot** [comment]
I think it is weird that the Write() operation by default appends 3 properties without having asked for it. Would have expected it to be its own NET4_5 fluent-method. Like ex CallSite().

**Comment by 304NotModified** [comment]
Maybe, but it would be a breaking change. I'm more in favor to turn it off/on in the (global) config

**Comment by snakefoot** [comment]
> Maybe, but it would be a breaking change

Think any change to fix this issue will be a breaking change. Either for NET4_5 or NET4_0. Just wanted to point out it was weird to mix the callsite-capture together with the actual Write-method. The whole idea with fluent is to build up using small-simple-methods and not create one big do-it-all-method. I'm not using the Fluent-API so have no special need to fix this :)

**Comment by 304NotModified** [comment]
To be clear. The .NET versions aren't binary compatible. This is by design as we cannot use otherwise .NET 4.5 features etc. 

Thanks for reporting, but we can't fix the breaking change.
