### ISSUE TITLE
NullReferenceException in InitializeTargets

### ISSUE THREAD

**Issue by fadenmad** [NLog/NLog#2060]
Hi! Thanks for reporting this feature/bug/question! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

For .NET Core users, please check the platform support: https://github.com/NLog/NLog/wiki/platform-support

**Type** (choose one):  Question

**NLog version**: 4.4.6

**Platform**: .Net 4.0

**Current NLog config** (xml or C#, if relevant)

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="true"
      internalLogLevel="Trace"
      internalLogFile="c:\temp\nlog-internal.log"
      internalLogToConsole="true"
      >

  <!-- optional, add some variables
  https://github.com/nlog/NLog/wiki/Configuration-file#variables
  -->

  <!--
  See https://github.com/nlog/nlog/wiki/Configuration-file
  for information on customizing logging rules and outputs.
   -->
  <targets async="true">
    <target xsi:type="ColoredConsole" name="console" layout="[${date:format=yyyy.MM.dd HH:mm:ss}]: ${message}" useDefaultRowHighlightingRules="true" footer="Hello, World"/>
      <target xsi:type="File" name="debugFile" fileName="${basedir}/Logs/debug_log.log" deleteOldFileOnStartup="true" layout="[${date:format=yyyy.MM.dd HH:mm:ss}]: ${message}${newline}Exception Information:${exception:format=type,message}" keepFileOpen="true"/>
      <target xsi:type="File" name="traceFile" fileName="${basedir}/Logs/trace_log.log" deleteOldFileOnStartup="true" layout="[${date:format=yyyy.MM.dd HH:mm:ss}]: ${message}${newline}Exception Information:${exception:format=type,message,method,stacktrace}" keepFileOpen="true"/>
      <target xsi:type="File" name="infoFile" fileName="${basedir}/Logs/info_log.log" deleteOldFileOnStartup="true" layout="[${date:format=yyyy.MM.dd HH:mm:ss}]: ${message}" keepFileOpen="true"/>
      <target xsi:type="File" name="errorFile" fileName="${basedir}/Logs/error_log.log" deleteOldFileOnStartup="true"  layout="General Information${newline}${newline}MachineName: ${machinename}${newline}TimeStamp: ${longdate}${newline}AppDomain: ${appdomain}${newline}ThreadCulture: ${ThreadName:variable=CurrentCulture}${newline}ThreadUICulture: ${ThreadName:variable=CurrentUICulture}${newline}WindowsIdentity: ${windows-identity}${newline}LogMessage: ${message}${newline}Exception Information:${exception:format=type,message,method,stacktrace}" keepFileOpen="true"/>
    <target xsi:type="MethodCall" name ="method" className="Messenger.Log" methodName="LogMethod">
      <parameter name="message" layout="${message}" xsi:type="NLog.Targets.MethodCallParameter"/>
    </target>
  </targets>

  <rules>
    <!-- add your logging rules here -->

    <!--
    Write all events with minimal level of Debug (So Debug, Info, Warn, Error and Fatal, but not Trace)  to "f"
    <logger name="*" minlevel="Debug" writeTo="f" />
    -->
    <logger name="*" minlevel="Info" writeTo="console" final="false"/>
    <logger name="*" minlevel="Trace" writeTo="traceFile" maxlevel="Trace" final="false"/>
    <logger name="*" minlevel="Debug" writeTo="debugFile" maxlevel="Debug" final="false"/>
    <logger name="*" minlevel="Info" writeTo="infoFile" final="false"/>
    <logger name="*" minlevel="Error" writeTo="errorFile" final="false"/>
    <logger name="*" minlevel="Info" writeTo="method" final="false"/>
  </rules>
</nlog>

```

Hello. I catch error with MethodCall logger. I've got a trace message "No invoke because class/method was not found or set". It means that this.Method in MethodCall is null. But in debug i see that "ClassName" and "MethodName" is not null. And I haven't any other messages about this target ("Initialize MethodCallTarget, method '{0}' in class '{1}' not found - it should be static" or "Initialize MethodCallTarget, class '{0}' not found").

How can i solve this problem?

**Comment by 304NotModified** [comment]
Do you have a stracktrace of the exception? Any idea if this bug is new in 44..6?

**Comment by fadenmad** [comment]
I'm not sure that it is the bug, because I just begin work with NLog and, may be, I do something wrong.
The last code I wrote didn't cause the exception but skip this target with "No invoke because class/method was not found or set".
This is trace of internal logger:
[nlog-internal.txt](https://github.com/NLog/NLog/files/926543/nlog-internal.txt)

**Comment by snakefoot** [comment]
I see the following message in the internal-log:

> 2017-04-17 22:56:26.8591 Warn Initialize MethodCallTarget, class 'Messenger.Log' not found

Maybe also specify the assembly-name when specifying the className, as NLog needs help with external assemblies:

`Type.GetType("MyNamespace." + myClassName + ", MyAssemblyName");`

**Comment by fadenmad** [comment]
It helps. MethodCall works when class name as AssemlyQualifiedName and method is public and static.
Thanks for helping. Excuse for this stupid mistake.

**Comment by 304NotModified** [comment]
Well if the null ref exception is from our code, then it's still a bug ;)
