### ISSUE TITLE
How to get stack trace also with exceptions through email

### ISSUE THREAD

**Issue by aswinfrancis91** [NLog/NLog#2065]
Hi! Thanks for reporting this feature/bug/question! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

For .NET Core users, please check the platform support: https://github.com/NLog/NLog/wiki/platform-support

**Type** (choose one):
- Question

**NLog version**: 4.4.6

**Platform**: .Net 4.5

**Current NLog config** (xml or C#, if relevant)
```xml
<targets async="true">
    <target name="mail" xsi:type="Mail" html="true" replaceNewlineWithBrTagInHtml="true" smtpServer="-removed-" smtpAuthentication="None" body="${exception:innerFormat=Message,StackTrace}" to="-removed-" from="-removed-" subject="${event-properties:item=Task} for ${event-properties:item=ClientName} has FAILED on ${machinename}"/>
</targets>
<rules>
    <logger name="*" minlevel="Fatal" writeTo="mail"/>
</rules>
```
I have tried different values for body like `${message}, ${exception:format=toString},${exception:innerFormat=Message,StackTrace}"`  etc but in the mail all i get is exception message and parameter name for argumentnullexception. I want to show the stack trace too.
My C# code is as below:
```c#
catch (Exception ex) {
  LogEventInfo logEventInfo = new LogEventInfo(LogLevel.Fatal, logger.Name, null, "", null, ex);
  logEventInfo.Properties["ClientName"] = "Name";
  logEventInfo.Properties["Task"] ="Test";
  logger.Log(logEventInfo);
}
```
This is what i get now:
![image](https://cloud.githubusercontent.com/assets/1233653/25216597/ef0e7d9c-25c0-11e7-8e73-5691a68e622f.png)

And this how i would prefer:
![image](https://cloud.githubusercontent.com/assets/1233653/25216655/3089c984-25c1-11e7-863c-21e401e816ee.png)

**Comment by 304NotModified** [comment]
hi,

could you make your code readable? See https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by aswinfrancis91** [comment]
@304NotModified My bad. I have updated it.

**Comment by aswinfrancis91** [comment]
Any update?

**Comment by snakefoot** [comment]
@aswinfrancis91 Have to you tried to use this instead:

`body="${exception:format=tostring}"`

**Comment by aswinfrancis91** [comment]
Yes. I have tried that. Still I was not getting trace through mail. The same worked for file and console though.

⁣Sent from BlueMail ​

**Comment by 304NotModified** [comment]
That's really strange as it's the same code for rendering `${exception:format=tostring}`

**Comment by 304NotModified** [comment]
it's this a mail formatting issue? 

Could you please check the internal log and the email source? Thanks!

**Comment by aswinfrancis91** [comment]
Guess what. It worked. I removed 'body' option and instead gave layout and it worked fine.

,,,
<target name="mail" xsi:type="Mail" html="true" replaceNewlineWithBrTagInHtml="true" smtpServer="lvsprdmailgw.prd.gsi.local" smtpAuthentication="None" 
					layout="${message} ${exception:format=tostring}" to="afrancis@radial.com" from="${machinename}@radial.com" subject="${event-properties:item=Task} for ${event-properties:item=ClientName} has FAILED on ${machinename}"/>
,,,

**Comment by 304NotModified** [comment]
> The email doesnt seem to be coming all the time though. I have attached the internal log
> nlog.txt

I don't see any error? Is that correct?

**Comment by aswinfrancis91** [comment]
Correct. I also don't see any error.

**Comment by 304NotModified** [comment]
isn't it in your spambox?

**Comment by aswinfrancis91** [comment]
No it is not :(

**Comment by 304NotModified** [comment]
if you see `Sending mail to ` in your internal log (and no 'Error sending mail' after it), then i should be sent.

**Comment by 304NotModified** [comment]
Unfortunately, I don't think I can help you further if you don't have any errors.

**Comment by aswinfrancis91** [comment]
@304NotModified  can you tell me if the code i wrote inside the catch statement is right? It in the first post.

**Comment by 304NotModified** [comment]
yes, but the message is empty which is a bit strange. Would write something like this:

```C#
LogEventInfo logEventInfo = new LogEventInfo(LogLevel.Fatal, logger.Name, null, "Error occured in ... ", null, ex);
```

and then your body `body="${message}${exception:innerFormat=Message,StackTrace}"`

**Comment by aswinfrancis91** [comment]
@304NotModified  I made modifications as mentioned and mail came ones. Stopped working after that without me making any change after that. 
So basically I got two emails only during a fatal error. One in the morning, when I modified SMTP server to IP address and then now.

**Comment by aswinfrancis91** [comment]
``Send-MailMessage -SMTPServer "*server name*" -To "mail id" -From "mail id" -Subject "This is a test email" -Body "Hi, this is a test email sent via PowerShell to test the STMP relay server"``
This works perfectly fine in Powershell. So, I am guessing it's not SMPT server issue.

**Comment by 304NotModified** [comment]
That's strange. Would it be possible to setup a small test project? (as small as possible). Then I could try to reproduce it here. 

At my work we use the mailtarget for ages without any problem. So i'm not aware of any problem.

**Comment by 304NotModified** [comment]
> Stopped working after that without me making any change after that.

Stopped work means here: not recieving mail OR not seeing "Sending mail to {0} using {1}:{2} (ssl={3})" in the internal log? (debug level)

**Comment by aswinfrancis91** [comment]
@304NotModified 
This is what i get from the internal log for my project:
```
2017-05-09 10:12:41.1216 Debug Sending mail to ****@****.com using******:25 (ssl=False)
2017-05-09 10:12:41.1216 Trace   Subject: 'Order Status for **** has FAILED on *****'
2017-05-09 10:12:41.1216 Trace   From: '***@***com'
2017-05-09 10:12:43.8073 Info Shutting down logging...
```
This is what i got from my sample project i created. Attached here
```
2017-05-09 10:15:26.3336 Debug Sending mail to ****@****.com using ****:25 (ssl=False)
2017-05-09 10:15:26.3336 Trace   Subject: 'Cancel Status for ***** has FAILED on *****'
2017-05-09 10:15:26.3336 Trace   From: '****@****.com'
2017-05-09 10:15:27.8184 Info Logger has been shut down.
```
[ConsoleApplication3.zip](https://github.com/NLog/NLog/files/985590/ConsoleApplication3.zip)

**Comment by snakefoot** [comment]
Maybe because NLog MailTarget doesn't wait for SmtpClient.SendCompleted-event before shutting down?

Maybe the NLog MailTarget should also make use of this helper class (Just like WebServiceTarget)

`private readonly AsyncOperationCounter pendingManualFlushList = new AsyncOperationCounter();`

**Comment by aswinfrancis91** [comment]
@304NotModified  I think @snakefoot might be right. I have noticed that sometimes when I am debugging through the code and wait for some time inside my catch statement, I do get the mail. Right now I tested it, I didn't get any email but this is what I got in the log:
```
2017-05-09 10:49:31.7098 Debug Sending mail to ****@****.com using ****:25 (ssl=False)
2017-05-09 10:49:31.7098 Trace   Subject: 'Order Status for **** has FAILED on *****'
2017-05-09 10:49:31.7098 Trace    From: '***@***com'
2017-05-09 10:51:01.1135 Trace AsyncWrapper 'debugFile': writing 1 events (Timer)
2017-05-09 10:51:01.1135 Trace Opening C:/*******_2017-05-09.log with allowFileSharedWriting=False
2017-05-09 10:50:45.8751 Error Error sending mail. Exception: System.Net.Mail.SmtpException: The operation has timed out.
   at System.Net.Mail.SmtpClient.Send(MailMessage message)
   at NLog.Internal.MySmtpClient.NLog.Internal.ISmtpClient.Send(MailMessage )
   at NLog.Targets.MailTarget.ProcessSingleMailMessage(IList`1 events)
```

**Comment by 304NotModified** [comment]
> Maybe because NLog MailTarget doesn't wait for SmtpClient.SendCompleted-event before shutting down?
> 
> Maybe the NLog MailTarget should also make use of this helper class (Just like WebServiceTarget)

👍 👍 👍

**Comment by snakefoot** [comment]
@aswinfrancis91 Think I was little too quick on the gun. NLog MailTarget is fully synchronous. It is strange that your internal logger only has this content:

```
2017-05-09 10:15:26.3336 Debug Sending mail to ****@****.com using ****:25 (ssl=False)
2017-05-09 10:15:26.3336 Trace   Subject: 'Cancel Status for ***** has FAILED on *****'
2017-05-09 10:15:26.3336 Trace   From: '****@****.com'
2017-05-09 10:15:27.8184 Info Logger has been shut down.
```

Would have expected lines like these:

```
Shutting down logging...
Flushing all targets...
AsyncWrapper writing 1 events
Closing target AsyncWrapper
Closed target AsyncWrapper
```

NLog hooks into application-shutdown-event and tries to flush all targets, but only delays the shutdown for 1 sec. If the flush doesn't complete within this time-window, then it just continues the shutdown.

You can perform a manual NLog-flush before entering the application-shutdown-state, which will allow you to wait whatever time you need.

**Comment by aswinfrancis91** [comment]
@snakefoot can you guide me on how to do it? I really need this feature to be setup

**Comment by snakefoot** [comment]
@aswinfrancis91 You can add the following lines to your program, just before exiting:

```
static void Main(string[] args)
{
   ...
   Exception flushException;
   NLog.LogManager.Flush((ex) => flushException = ex, TimeSpan.FromMinutes(2));
   if (flushException != null)
   {
        // Flush failed, maybe with a timeout
   }
}
```

**Comment by aswinfrancis91** [comment]
@snakefoot. So if i am sending the error message as mail inside a catch statement(mentioend in the first post) you want me to write the above code there? Can you please explain how that would help fix the issue?

**Comment by snakefoot** [comment]
@aswinfrancis91 So now you have made sure that the application waits for the mail-target to complete sending mails before application-exit.

Now you just have to figure out why your application is not able to communicate with the specified SMTP-server (System.Net.Mail.SmtpException: The operation has timed out).

You could increase the mail-target-timeout from the default 10 sec to 90 secs:

```
<targets async="true">
    <target name="mail" xsi:type="Mail" timeout="90000" ... />
</targets>
```

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, let us know!

**Comment by aswinfrancis91** [comment]
Thank you @snakefoot  and @304NotModified . It still doesn't work in my system but from the test server, it is sending emails perfectly. It does go to spam though.
