### ISSUE TITLE
System.MissingMethodException: 'Method not found: 'Void NLog.Logger.Fatal(System.Exception, System.String)

### ISSUE THREAD

**Issue by bobheck** [NLog/NLog#2066]
Hi! Thanks for reporting this feature/bug/question! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

For .NET Core users, please check the platform support: https://github.com/NLog/NLog/wiki/platform-support

**Type** (choose one):

- Bug

**NLog version**: (e.g. 4.4.6)

**Platform**: .Net 4.5.2 

In case of a BUG:

- What is the current result?
logger.Fatal(Exception, string) throws this:
System.MissingMethodException: 'Method not found: 'Void NLog.Logger.Fatal(System.Exception, System.String)
- What is the expected result?  
no error
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
yes
- Please post full exception details (message, stacktrace, inner exceptions)
Method not found: 'Void NLog.Logger.Fatal(System.Exception, System.String)'. [Int32 Main(System.String[])] => [Void Run()] => [Void Parse(Sts.FileParser.QT.QtOut, Sts.Structure.Pole, Sts.Structure.Model)] 
2017-04-20 11:38:15.5488 ERROR [BackEnd.Program.Run(0)] Error parsing QT.OUT at line 92. [Int32 Main(System.String[])] => [Void Run()] 
2017-04-20 11:38:15.5488 ERROR [BackEnd.Program.Run(0)] System.Exception: Error at line 92 in QT.OUT

Method not found: 'Void NLog.Logger.Fatal(System.Exception, System.String)'.
   at Sts.FileParser.QT.QtParser.Parse(QtOut data, Pole pole, Model model)
   at BackEnd.Program.Run() [Int32 Main(System.String[])] => [Void Run()] 

- Are there any work arrounds?  no
- Is there a version in which it did worked?  4.3.5

**Comment by 304NotModified** [comment]
Thanks for reporting!

**Comment by snakefoot** [comment]
Think it is the other way around. That you have compiled against NLog 4.4.6, but still trying to run against NLog 4.3.5

**Comment by 304NotModified** [comment]
Ah yes its backwards compatible but not forward.

**Comment by 304NotModified** [comment]
@bobheck could you please check this?

**Comment by bobheck** [comment]
Thank you.  Yes the issue was the incorrect version.  I had several
projects in my solution, one external.  The external project had a later
version of NLog installed.   Sorry for the post, it was not a bug.  Thank
you for following up.

**Comment by 304NotModified** [comment]
OK thanks for the feedback!
