### ISSUE TITLE
Example for JsonLayout puts attributes in the wrong place

### ISSUE THREAD

**Issue by mrfrostfire** [NLog/NLog#2068]
**Type** (choose one):
- Bug

**NLog version**: (e.g. 4.2.3)
N/A

**Platform**: .Net 3.5 / .Net 4.0 / .Net 4.5 / Mono 4 / Silverlight 4 / Silverlight 5 / Xamarin Android / Xamarin iOs / .NET Core 
N/A

**Current NLog config** (xml or C#, if relevant)
N/A

In case of a BUG:

- What is the current result?
Example configuration throws internal exception while parsing the config
- What is the expected result?
It should parse fine
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
Yes, that's where I found the issue
- Please post full exception details (message, stacktrace, inner exceptions)
N/A
- Are there any work arrounds? yes/no
Yes
- Is there a version in which it did worked? 
N/A
- Can you help us by writing an unit test?
No, but I can give you the reason.
The Example in the documentation shows:
`<target name="jsonFile" xsi:type="File" fileName="${logFileNamePrefix}.json" includeAllProperties="Boolean" excludeProperties="Comma-separated list (string)">
      <layout xsi:type="JsonLayout">
              <attribute name="time" layout="${longdate}" />
              <attribute name="level" layout="${level:upperCase=true}"/>
              <attribute name="message" layout="${message}" />
       </layout>
</target>`

It should be changed to:
`<target name="jsonFile" xsi:type="File" fileName="${logFileNamePrefix}.json">
      <layout xsi:type="JsonLayout" includeAllProperties="Boolean" excludeProperties="Comma-separated list (string)">
              <attribute name="time" layout="${longdate}" />
              <attribute name="level" layout="${level:upperCase=true}"/>
              <attribute name="message" layout="${message}" />
       </layout>
</target>`

**Comment by snakefoot** [comment]
Thanks for the heads up, have updated the documentation.

**Comment by 304NotModified** [comment]
This was only a documentation issue, isn't it?

**Comment by snakefoot** [comment]
> This was only a documentation issue, isn't it?

Yes and it has been fixed.

**Comment by 304NotModified** [comment]
thanks!
