### ISSUE TITLE
Exception Log in Winforms Installer

### ISSUE THREAD

**Issue by SalmanKarim** [NLog/NLog#2072]
Hi! Thanks for reporting this question! 

- Question
Hi, I am developing a winforms application and for exception handling I have used NLog. While debugging I can see the log .txt file in bin->debug folder, but when I create the installer and install it on the Client machine, where I can find this exception log .txt file? Please help me out.

**NLog version**: (e.g. 4.2.3)

**Platform**:   .Net 4.5 

**Current NLog config** (xml or C#, if relevant)

<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" >

  <targets>
    <target name="logfile" xsi:type="File" fileName="POSExceptionsLog.txt" />
  </targets>

  <rules>
    <logger name="*" minlevel="Info" writeTo="logfile" />
  </rules>
</nlog>

**Comment by snakefoot** [comment]
Seldom one have permission to place log-files next to the binary files. This is the OperationSystem trying to protect you from malware injecting itself into installed applications.

Try modify your file-target to have a different filename. Example:
`
<target xsi:type="File" filename="${specialfolder:folder=CommonApplicationData}/log.txt" />`

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, let us know!
