### ISSUE TITLE
RichTextBoxTarget LayoutWithHeaderAndFooter support

### ISSUE THREAD

**Issue by shravan2x** [NLog/NLog#2073]
**Type** (choose one): Feature request

**NLog version**: 4.4.6 (NLog), 4.2.3 (NLog.Windows.Forms)

**Platform**: .Net 4.5

**Current NLog config** (xml or C#, if relevant)

```c#
LoggingConfiguration newConf = new LoggingConfiguration();

RichTextBoxTarget richTextBoxTarget = new RichTextBoxTarget();
richTextBoxTarget.TargetForm = this;
richTextBoxTarget.TargetRichTextBox = LogBox;
richTextBoxTarget.UseDefaultRowColoringRules = true;
richTextBoxTarget.SupportLinks = false;
newConf.AddTarget("richtextbox", richTextBoxTarget);

LayoutWithHeaderAndFooter fullLayout = new LayoutWithHeaderAndFooter();
fullLayout.Header = $"#Software: {Program.ProductName}\r\n#Version: {Program.VersionName}\r\n#StartTime: ${{date}}";
fullLayout.Layout =  @"[${date} ${logger}] ${level:uppercase=true}: ${message}";
richTextBoxTarget.Layout = fullLayout;

LoggingRule debugAllRule = new LoggingRule("*", LogLevel.Trace, richTextBoxTarget);
newConf.LoggingRules.Add(debugAllRule);

LogManager.Configuration = newConf;
```

I had a brief look at the `RichTextBoxTarget` and was unsure why `LayoutWithHeaderAndFooter` was not used there. I can imagine it behaving similar to a console and printing these. Is there a deeper reason behind this design decision that I have not thought of?

**Comment by 304NotModified** [comment]
I think it's difficult (in performance) to insert / replace the text in a RichTextBox?



@mikhail-barg any idea?

**Comment by shravan2x** [comment]
Yes, but in this case, I don't believe we'd be doing either. We will just be prepending some content in the beginning and appending at the end (Unless I'm confused as to what LayoutWithHeaderAndFooter does).

**Comment by 304NotModified** [comment]
Sorry for the delay,

the LayoutWithHeaderAndFooter layout write a header, multiple logevents, and when done the footer. e.g. a file. When the file is created the header, and when the file is closed, the footer.

If you need to append info before/after a logevent, you could just append them in the layout (and maybe using `${newline}'

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, let us know!
