### ISSUE TITLE
Stacktrace doesn't show file lines and file names

### ISSUE THREAD

**Issue by bruderalex** [NLog/NLog#2074]
**Type**: Bug

**NLog version**:   4.4.6

**Platform**: .Net 4.5

**Current NLog config**

```xml
<nlog>
  <targets>
    <target name="logfile" xsi:type="File" fileName="file.txt" layout="${stacktrace:format=raw}"/>
  </targets>
  <rules>
    <logger name="*" minlevel="Trace" writeTo="logfile" />
  </rules>
</nlog>

```
My current log with that configuration is:
_ExecuteAssembly at offset 127 in file:line:column <filename unknown>:0:0
nExecuteAssembly at offset 0 in file:line:column <filename unknown>:0:0
Main at offset 710 in file:line:column <filename unknown>:0:0_

I expect filelines and filenames to be in logfile.
I tried to do same thing with .NET diagnostic (something like _var frames = new StackTrace(true).GetFrames();_) and all filenames and filelines were showed correctly.

Project has full output debug info, all pdb-files are on their place.

I also tried to do that on NLog version 4.2.3 and received same result - no filelines and filenames.

**Comment by 304NotModified** [comment]
Hi,

we also use ` stackTrace = new StackTrace(StackTraceSkipMethods, stu == StackTraceUsage.WithSource);` 

Could you set up a small test project?

**Comment by bruderalex** [comment]
I made little test project. It's here - https://github.com/bruderalex/nlogstacktrace

If it will help, i tried to explore source code of NLog and find a problem in ObjectGraphScanner.cs on line 94. For ${stacktrace:format=raw} it returns object of StackTraceLayoutRenderer, which has IUsesStackTrace.StackTraceUsage value as "Without Source". I tried to set thar property manually to "With Source" and that helped, but i can't find what is wrong with my test project's code becasue of which that property always is "Without Source"

Thank you in advance for your answer

**Comment by 304NotModified** [comment]
Indeed! Good catch!

https://github.com/NLog/NLog/blob/master/src/NLog/LayoutRenderers/StackTraceLayoutRenderer.cs#L94

**Comment by 304NotModified** [comment]
As this could be a performance thing, I think we should make it configurable.

**Comment by bruderalex** [comment]
Thank you a lot! That would be great!)

With best regards, Alexander

**Comment by 304NotModified** [comment]
it's according to the docs I see, so doubting if #2075 is a bug fix or a feature.

See example: https://github.com/NLog/NLog/wiki/Stack-Trace-Layout-Renderer
