### ISSUE TITLE
Release 4.5 alpha 5

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#2077]
release 4.5 alpha 5

for https://github.com/NLog/NLog/issues/2062

rebase first

**Comment by 304NotModified** [comment]
see https://github.com/NLog/NLog/commits/structural-events-alpha5

**Comment by 304NotModified** [comment]
@snakefoot could you please help me with this? Had some problems merging the changes in the JsonSerializer.cs into NLog 4.5

**Comment by snakefoot** [comment]
@304NotModified You can look at the DefaultJsonSerializer.cs from #2107 (Includes a small change in XmlHelper.cs)

**Comment by snakefoot** [comment]
@304NotModified Resolved with the release of NLog 4.5 BETA

**Comment by 304NotModified** [comment]
thx!
