### ISSUE TITLE
${aspnet-mvc-action} not filled when log is called from an API Controller method.

### ISSUE THREAD

**Issue by Francois-La** [NLog/NLog#2082]
Hello,

I have a question or maybe a bug to report ?

I want to log ${aspnet-mvc-controller} and ${aspnet-mvc-Action} from my **Web API** methods.
Is this supposed to work ?

Everything works fine when I log from a method in a MVC Controller (System.Web.Mvc).  

But when I log from the Web API method **(ApiController, System.Web.Http)**, the "layout variables" related to apsnet are all empty.  Only my custom text  - set in Log.Trace("xxx") - makes his way to the log file... (my configuration is ok).

_Note: In a different but similar project (The default MS template for a new Web API Project, I have almost the same issue.  In this project, the ${aspnet-mvc-controller} is filled up, but not the action._

Everything (MVC controllers and API controllers) are all in the same project.  So it's all the same web.config, nlog.config, references, etc.

VS 2013, .Net 4.5, Nlog: 4.4.7, Nlog.Web: 4.4.0

Nothing special in the internal-log.  The result is the "same" for each log action.

<module`> entry is present in my web.config file.

My Layout definition:

<target name="TraceLogFile" xsi:type="File" fileName="WebApiTraces.log" layout="${longdate} [${aspnet-sessionid}] |${aspnet-mvc-controller}.${aspnet-mvc-action}| ${message}"/>

Good log entry (from a method in a MVC Controller):
2017-04-27 10:53:09.3973 26092/20 [5m1leip0e03esgxjpfqy4khx] |Home.About|  This is from HomeController.About

Bad log entry (From a method in a API Controller):
2017-04-27 10:43:16.5434 26092/38 [] |.|  This from the Get in Test APIController 

Both logger are declared/initialized the same way.

Any advice for me ?
 
Thanks

**Comment by Francois-La** [comment]
Got it.
It Seems to be related to the default route configuration.

For web api, action is not in the default route configuration (as opposed to MVC).

If {action} is part of it, then it's filled for Web API also.

In my case, I completely remove the default route configuration and instead, I'm using the route attribute over each of my controller and method  (not usual, I know...)...    

So it looks to be the problem.

**Comment by 304NotModified** [comment]
routes like this aren't working?

```c#
routes.MapRoute("DefaultPromo", "", new { controller = "Promo", action = "Index" });
```

**Comment by 304NotModified** [comment]
@Francois-La bump

**Comment by nzain** [comment]
@304NotModified such routes are not used in a RESTful web api (serving JSON, no HTML). The typical approach is to put `RouteAttribute` on you controller and action+subroute attributes on the methods within, e.g: `[HttpGet("{id}", Name = "GetTodo")]`

Take a look at recent asp.net core tutorials (where all the ${aspnet-*} properties are not working:
https://docs.microsoft.com/de-de/aspnet/core/tutorials/web-api-vsc

A few years ago, I've been working quite a lot with asp.net webapi (the routing stuff hasn't changed, since), but I'm really new to asp.net core - so I'm not sure why/where this happens (or does not happen).

**Comment by nzain** [comment]
There was a note about adding an IHttpContextAccesor service when some auth stuff is required:

```csharp
    public void ConfigureServices(IServiceCollection Services)
    {
        //call this in case you need aspnet-user-authtype/aspnet-user-identity
        services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();
    }
```
from https://github.com/NLog/NLog.Web/wiki/Getting-started-with-ASP.NET-Core-(csproj---vs2017)

I remember that the evil static HttpContext had _everything_... and I gave it a try. Now, the two layout properties I'm interested in

- ${aspnet-request-method}
- ${aspnet-request-url}

are populated.

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, let us know!

**Comment by jaydubal** [comment]
Even after adding `services.AddHttpContextAccessor();` The log file does not show ${aspnet-request-url} & ${aspnet-mvc-action} in asp.net core 2.0

**Comment by snakefoot** [comment]
@jaydubal Please create new issue where you use NLog.Asp NetCore ver 4.6.0 and include the output from NLog InternalLogger at Trace Level
