### ISSUE TITLE
Fixed bug to logging by day of week

### ISSUE THREAD

**Issue by RussianDragon** [NLog/NLog#2089]
Hi! 
We found bug in logging by day of week.
If you set option "archiveEvery" as any day of week, nlog will create new archive file every day.

Мы нашли ошибку в создании файлов логов-архивов, если установлено архивирование по дням недели. Файлы создаются каждый день, а не в определенные дни 

--------------------
next code сontains fix bug 

```
private static DateTime TruncateArchiveTime(DateTime input, FileArchivePeriod resolution)
        {
            switch (resolution)
            {
                case FileArchivePeriod.Year:
                    return new DateTime(input.Year, 1, 1, 0, 0, 0, 0, input.Kind);
                case FileArchivePeriod.Month:
                    return new DateTime(input.Year, input.Month, 1, 0, 0, 0, input.Kind);
                case FileArchivePeriod.Day:
                    return input.Date;
                case FileArchivePeriod.Hour:
                    return input.AddTicks(-(input.Ticks % TimeSpan.TicksPerHour));
                case FileArchivePeriod.Minute:
                    return input.AddTicks(-(input.Ticks % TimeSpan.TicksPerMinute));
                case FileArchivePeriod.Sunday:
                    return CalculateNextWeekday(input.Date, DayOfWeek.Sunday);
                case FileArchivePeriod.Monday:
                    return CalculateNextWeekday(input.Date, DayOfWeek.Monday);
                case FileArchivePeriod.Tuesday:
                    return CalculateNextWeekday(input.Date, DayOfWeek.Tuesday);
                case FileArchivePeriod.Wednesday:
                    return CalculateNextWeekday(input.Date, DayOfWeek.Wednesday);
                case FileArchivePeriod.Thursday:
                    return CalculateNextWeekday(input.Date, DayOfWeek.Thursday);
                case FileArchivePeriod.Friday:
                    return CalculateNextWeekday(input.Date, DayOfWeek.Friday);
                case FileArchivePeriod.Saturday:
                    return CalculateNextWeekday(input.Date, DayOfWeek.Saturday);
                default:
                    return input;   // Unknown time-resolution-truncate, leave unchanged
            }
        }
```

**Comment by 304NotModified** [comment]
Hi, please use the issue template

**Comment by RussianDragon** [comment]
We writing about of bug, and writing fix code.
What's not clear?

Мы написали об ошибке и написали как исправить.
Что тут непонятного?

**Comment by 304NotModified** [comment]
which NLog version? is this NLog 4.4.8? NLog 5 beta?

**Comment by RussianDragon** [comment]
It is master branch.
Commit 39541571eed7bbdbc8a27019f32a78e3a5ae6969 [3954157]

**Comment by snakefoot** [comment]
@RussianDragon Sounds like you are very close to make a unit-test and a github pull-request :). This will increase the chance of it making it into next NLog-release.

**Comment by RussianDragon** [comment]
I have not enough permissions to push my fix-branch...
![image](https://cloud.githubusercontent.com/assets/12259067/25716056/69b3e334-3106-11e7-81b5-dd93bb15d469.png)

**Comment by 304NotModified** [comment]
Steps:

Create a fork (the button)
Add it as remote (or clone and copy changes)
Push
Create PR in github

**Comment by RussianDragon** [comment]
@304NotModified Thank you!
I created new pull requests.

**Comment by 304NotModified** [comment]
You fixed it!
(in https://github.com/NLog/NLog/issues/2093) 

thanks!

**Comment by 304NotModified** [comment]
NLog 4.4.9 is in the deploy pipeline! Will be online in an hour!
