### ISSUE TITLE
Programmatically set async attribute

### ISSUE THREAD

**Issue by dvladimirovich** [NLog/NLog#2097]
HI! I'm currently programatically configure NLog configuration according to documentation. I decided to use async attribute on targets tag `<targets async="true">`. So, my question is how to set this value programmatically? And will it work asynchronously for all my targets without any further implementations?

**Comment by snakefoot** [comment]
When doing it programmatically, then it should be very easy to implement a generic method for adding targets, that automatically wraps them with the AsyncTargetWrapper.

**Comment by 304NotModified** [comment]
So currently, wrap your target in a asynctargetwrapper and write the logs to the wrapper.

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, let us know!

**Comment by dvladimirovich** [comment]
Yes, thank you!
