### ISSUE TITLE
Fixed markdown problem on File Target wiki page

### ISSUE THREAD

**Issue by Mykezero** [NLog/NLog#2099]
Hi, I've updated the [File Target](https://github.com/NLog/NLog/wiki/File-target/d2f42ed0fb622eb792595671e2f8087cd54015a4) wiki page to fix problem with its markdown. I've included the changes down below for further review. Also, I'm not 100% what the meaning of this phrasing is: 

> **Warning: combining this mode with _Archive Numbering Date_ is not supported. Archive files are not merged.    _ DateAndSequence_ do will work. **

What are we trying to convey about DateAndSequence here? 

---

### Archival Options
* **archiveAboveSize** - Size in bytes above which log files will be automatically archived. [Long](Layouts)  
Caution: Enabling this option can considerably slow down your file logging in multi-process scenarios. If only one process is going to be writing to the file, consider setting ConcurrentWrites to false for maximum performance. 
**Warning: combining this mode with _Archive Numbering Date_ is not supported. Archive files are not merged.    _ DateAndSequence_ do will work. **

### Archival Options
* **archiveAboveSize** - Size in bytes above which log files will be automatically archived. [Long](Layouts)  
Caution: Enabling this option can considerably slow down your file logging in multi-process scenarios. If only one process is going to be writing to the file, consider setting ConcurrentWrites to false for maximum performance. 
**Warning: combining this mode with _Archive Numbering Date_ is not supported. Archive files are not merged. _DateAndSequence_ will work**

**Comment by 304NotModified** [comment]
Thanks!

The markdown is a lot more picky then before.



> What are we trying to convey about DateAndSequence here?

archiveNumber=Date  + archiveAboveSize=...  won't work and is not supported

**Comment by 304NotModified** [comment]
Nothing to do here, so closing :)
