### ISSUE TITLE
NLog.Targets.LogReceiverWebServiceTarget needs custom binding

### ISSUE THREAD

**Issue by ghost** [NLog/NLog#21]
> receiveService.EndpointConfigurationName assumes that we have a clientconfig in our solution.
> 
> However, in SilverLight and PRISm, the config is not locally to our project within a solution. It is xap(ed) and having a basicHttpBinding section in the shell.xaml project, is really not a good solution.
> 
> So, I suggest that the LogReceiverWebServiceTarget supports a new method of type Binding so, we can create custom binding in code!

Moved from http://nlog.codeplex.com/workitem/6509

**Comment by MichelZ** [comment]
Maybe it makes sense to close some issues that are unlikely to be ever implemented? :)

**Comment by 304NotModified** [comment]
maybe, until now that's not the policy

**Comment by MichelZ** [comment]
ok. I just thought it may make it a little bit more manageable. 190 open issues has a bit of a bad vibe, but then again it's not really important :)

**Comment by 304NotModified** [comment]
No plans for this now
