### ISSUE TITLE
NLog.Windows.Forms "Form Form1 not found" error when trying log to form control.

### ISSUE THREAD

**Issue by bruceburge** [NLog/NLog#2104]
**Description**
I've have NLog working with text loggers, attempting to add textControl to log to, 
I have insured that the control is present and the name is correct.
I have insured that the form is present and named correctly also. 
No Errors are Exceptions are reported, and the "Form Form1 not found" message is logged as Info in internal Nlog log. 

Possibly related to https://github.com/NLog/NLog/issues/1166

**Type** (choose one):

- Bug

**NLog version**: (e.g. 4.4.9)

**Platform**:  .Net 4.5 

**Current NLog config** (xml or C#, if relevant)

```xml
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="true"
      internalLogLevel="Info" internalLogFile="c:\temp\nlog-internal.log">
  <targets>
<target xsi:type="FormControl" name="control" append="true" controlName="txtLog" formName="Form1" layout="${message}"/>
  </targets>
  <rules>
<logger name="*" minlevel="Trace" writeTo="control"/>
  </rules>
</nlog>

```

In case of a BUG:

- What is the current result?
no content written to textbox control
- What is the expected result?
content written to textbox control 
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)? Yes

> 2017-05-10 14:27:29.4771 Info Auto loading assembly file: C:\Users\bruce\documents\visual studio 2017\Projects\LDAA.ProsecutorsNotebook\LDAA.ProsecutorsNotebook.DesktopApp\bin\Debug\NLog.Windows.Forms.dll
> 2017-05-10 14:27:29.5011 Info NLog.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c. File version: 4.2.3.167. Product version: 4.2.3.
> 2017-05-10 14:27:29.5011 Info Auto loading assembly file: C:\Users\bruce\documents\visual studio 2017\Projects\LDAA.ProsecutorsNotebook\LDAA.ProsecutorsNotebook.DesktopApp\bin\Debug\NLog.Windows.Forms.dll succeeded!
> 2017-05-10 14:27:29.5381 Info Adding target File Target[errors]
> 2017-05-10 14:27:29.5381 Info Adding target FormControl Target[control]
> 2017-05-10 14:27:29.5471 Info Configured from an XML element in C:\Users\bruce\documents\visual studio 2017\Projects\LDAA.ProsecutorsNotebook\LDAA.ProsecutorsNotebook.DesktopApp\bin\Debug\NLog.config...
> 2017-05-10 14:27:29.5631 Info Found 25 configuration items
> 2017-05-10 14:27:29.5762 Info Configuration initialized.
> 2017-05-10 14:27:29.5762 Info NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c. File version: 4.4.5097. Product version: 4.4.9.
> 2017-05-10 14:27:29.6302 Info Form Form1 not found
> 2017-05-10 14:27:29.6402 Info Form Form1 not found
> 2017-05-10 14:27:31.9622 Info Shutting down logging...
>2017-05-10 14:27:31.9822 Info Logger has been shut down.
- Please post full exception details (message, stacktrace, inner exceptions)

- Are there any work arrounds? no
- Is there a version in which it did worked? Unsure
- Can you help us by writing an unit test? Maybe

**Comment by 304NotModified** [comment]
@mikhail-barg  any idea?

**Comment by mikhail-barg** [comment]
Looks a bit weird, but I haven't seen `FormControlTarget` before. 

@bruceburge just to be sure, you using the [`NLog.Windows.Forms`](https://github.com/NLog/NLog.Windows.Forms) package as well as regular `NLog`, right? I see that NLog has some example with `FormControl` which I've never seen before too, so maybe there's something wrong here.

Could you please try logging to [`RichTextBoxTarget`](https://github.com/NLog/NLog.Windows.Forms/wiki/RichTextBoxTarget) and see if you have the similar error? Please note that iot works only with RichTextBox controls.

**Comment by bruceburge** [comment]
I'm not sure what you mean, about FormControl vs FormControlTarget was that just a spacing issue, or are you saying those are two different things? 

I will try changing from a textbox to RichTextBox as I was unaware of that restriction, I'll update once I've done that.

**Comment by bruceburge** [comment]
switching to RichTextBox provided no difference. I have attached a internal trace level log.
[nlog-internal.log_reallyGitHubNotLogFiles.txt](https://github.com/NLog/NLog/files/999096/nlog-internal.log_reallyGitHubNotLogFiles.txt)





``

**Comment by bruceburge** [comment]
I've found the issue, though I'm unsure of the best solution. 

Granted this is an edge case (I'm lucky like that), 
if that forms properties have been changed in code (IE **this.ShowInTaskbar = false;**)  both of the conditions used to get the target form fail, until the form is interacted with by user or  **.Focus()** is called. 

(see bottom of post for code used to get target.)

To reproduce this problem use this 

`

      private void Form1_Load(object sender, EventArgs e)
        {
            logger.Debug("Form Loaded");
           //Logs
            logger.Debug($"1| Form count: {Application.OpenForms.Count}");
            logger.Debug($"1| Activeform: {Form.ActiveForm?.Name ?? "Null Activeform"}");
            this.ShowInTaskbar = false;
            this.ShowInTaskbar = true;
            //Fails to Log to control
            logger.Debug($"2| Form count: {Application.OpenForms.Count}");
            logger.Debug($"2| Activeform: {Form.ActiveForm?.Name ?? "Null Activeform"}");         
        }
`
Associated Text logger from the above code

> 2017-05-14 00:52:30.6538|DEBUG|DesktopApp.Form1|Form Loaded
> 2017-05-14 00:52:30.6598|DEBUG|DesktopApp.Form1|1|Form count: 1
> 2017-05-14 00:52:30.6598|DEBUG|DesktopApp.Form1|1|Activeform: Null Activeform
> 2017-05-14 00:52:30.7263|DEBUG|DesktopApp.Form1|2|Form count: 0
> 2017-05-14 00:52:30.7383|DEBUG|DesktopApp.Form1|2|Activeform: Null Activeform

This example logs correctly. 
`

      private void Form1_Load(object sender, EventArgs e)
        {
            logger.Debug("Form Loaded");
           //Logs
            logger.Debug($"1| Form count: {Application.OpenForms.Count}");
            logger.Debug($"1| Activeform: {Form.ActiveForm?.Name ?? "Null Activeform"}");
            this.ShowInTaskbar = false;
            this.ShowInTaskbar = true;
            this.Focus();
            //No Longer fails to Log to control
            logger.Debug($"2| Form count: {Application.OpenForms.Count}");
            logger.Debug($"2| Activeform: {Form.ActiveForm?.Name ?? "Null Activeform"}");         
        }
`
> 2017-05-14 01:13:42.4370|DEBUG|DesktopApp.Form1|Form Loaded
> 2017-05-14 01:13:42.4440|DEBUG|DesktopApp.Form1|1|Form count: 1
> 2017-05-14 01:13:42.4440|DEBUG|DesktopApp.Form1|1|Active form: Null Active Form
> 2017-05-14 01:13:42.5294|DEBUG|DesktopApp.Form1|2|Form count: 0
> 2017-05-14 01:13:42.5382|DEBUG|DesktopApp.Form1|2|Active form: Form1


**Odd still is calling this.Focus() anytime before changing another property of the form, does not seem to set the active form**

`

      private void Form1_Load(object sender, EventArgs e)
        {
            logger.Debug("Form Loaded");
           //Logs
            logger.Debug($"1| Form count: {Application.OpenForms.Count}");
            logger.Debug($"1| Activeform: {Form.ActiveForm?.Name ?? "Null Activeform"}");
            //this.ShowInTaskbar = false;
            //this.ShowInTaskbar = true;
            this.Focus();
            //No Longer fails to Log to control
            logger.Debug($"2| Form count: {Application.OpenForms.Count}");
            logger.Debug($"2| Activeform: {Form.ActiveForm?.Name ?? "Null Activeform"}");         
        }
`

> 2017-05-14 01:14:35.9864|DEBUG|DesktopApp.Form1|Form Loaded
> 2017-05-14 01:14:35.9864|DEBUG|DesktopApp.Form1|1|Form count: 1
> 2017-05-14 01:14:35.9864|DEBUG|DesktopApp.Form1|1|Active form: Null Active Form
> 2017-05-14 01:14:36.0045|DEBUG|DesktopApp.Form1|2|Form count: 1
> 2017-05-14 01:14:36.0045|DEBUG|DesktopApp.Form1|2|Active form: Null Active Form
 

**Code from FindControlAndSendTheMessage**
`

            if (Form.ActiveForm != null)
            {
                form = Form.ActiveForm;
            }

            if (Application.OpenForms[FormName] != null)
            {
                form = Application.OpenForms[FormName];
            }

            if (form == null)
            {
                InternalLogger.Info("Form {0} not found", FormName);
                return;
            }
`

[https://github.com/NLog/NLog.Windows.Forms/blob/670b20c1fa4ffd2e9b6897dfe775bd5bd9d6455e/NLog.Windows.Forms/FormControlTarget.cs#L85-L99](FormControlTarget.cs)

**Comment by mikhail-barg** [comment]
> I'm not sure what you mean, about FormControl vs FormControlTarget was that just a spacing issue, or are you saying those are two different things?

You are using `FormControlTarget`, I've asked you to try `RichTextBoxTarget` which is a different one: 
https://github.com/NLog/NLog.Windows.Forms

> I will try changing from a textbox to RichTextBox as I was unaware of that restriction, I'll update once I've done that.

This is a restriction for `RichTextBoxTarget` (which I asked you to try) not for `FormControlTarget` (which you are using)

**Comment by mikhail-barg** [comment]
So my question still stands, does the same problem happens with `RichTextBoxTarget`?

**Comment by bruceburge** [comment]
@mikhail-barg short answer is no, but with justification, I'd rather not use the richtextbox logger

This logger seems to require that LogManager.GetCurrentClassLogger(); is called after the constructor for the form has been called before it finds it. 

I'd also rather not have to explain why the logger is doing p/invoke to user32 and marshaling memory to accomplish the link conversions, and that someone changing the config file setting on the logger will open up that exposure.

The work around of having to focus on the form that has the control for logging, after adjusting the forms properties is a bit of a hack, but I think it comparision it is a better and simpler solution for my current needs than dealing with the two previously mentioned issues.

**Comment by mikhail-barg** [comment]
@bruceburge  I did not mean to use it in production, just to test, if the problem still stands with it. The `RichTextBoxTarget` use a bit more intelligent approach to finding forms AFAIK, so it would help to understand where the problem lies.

**Comment by bruceburge** [comment]
I did test it, it doesn't have the same issue, but I did find that unless the get class logger is called after the form you are calling it on has finished executing its constructor then it always pops up a new form. 

This is generally incosistant with other targets. 

Though in general I find the rich text target to be better written, it's pinvoke to user32 and marshalling of memory are hard to justify for converting links. 

These are the reasons we have decided not to use it. 

I think adding the code that attaches or creates the form/control from richtexttarget to the condition show above that causes formcontroltarget to fail would be a nice improvement. 

Thanks for time in trying to resolve this issue.

**Comment by mikhail-barg** [comment]
> but I did find that unless the get class logger is called after the form you are calling it on has finished executing its constructor then it always pops up a new form.

To overcome this please specify `allowAccessoryFormCreation=false` for the target, and also call `RichTextBoxTarget.ReInitializeAllTextboxes(form)` from the form's constructor.

> I think adding the code that attaches or creates the form/control from richtexttarget to the condition show above that causes formcontroltarget to fail would be a nice improvement.

Yes, we need to use same code for all targets that are looking for a control on form.

**Comment by mikhail-barg** [comment]
> it's pinvoke to user32 and marshalling of memory are hard to justify for converting links.
> These are the reasons we have decided not to use it.

If you don't need links, then just don't enable/use them )

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, let us know!
