### ISSUE TITLE
Adding LogEventInfo at Controller Action level for Asp.Net Core Application

### ISSUE THREAD

**Issue by yehonathan** [NLog/NLog#2106]
Hi, I have been able to hook nlog into an asp.net core application  as described [here](https://github.com/NLog/NLog.Web/wiki/Getting-started-with-ASP.NET-Core-(project.json))

Now i need to do add log event info properties like described [here](https://github.com/nlog/nlog/wiki/Event-Context-Layout-Renderer) but how do i do that in the action method. The issue is that  **Ilogger** does not accept LogEventInfo object. 

How do i pass this to the nloger through Ilogger interface? or otherwise?

**Comment by snakefoot** [comment]
You could try and inject the LogEventInfo object as a parameter that is not referenced by the Log-Text:

```
LogEventInfo theEvent = new LogEventInfo(LogLevel.Debug, "", "");
theEvent.Properties["MyValue"] = "My custom string";
_logger.LogInformation("Index page says hello", theEvent);
```

**Comment by yehonathan** [comment]
@snakefoot  It does not seem to do that. I am trying to create a custom layout 
`[LayoutRenderer("custom")]
    public class CustomLayoutRenderer : LayoutRenderer
    {
        protected override void Append(StringBuilder builder, LogEventInfo logEvent)
        {          
            builder.Append(logEvent.Properties["MyValue"]);
        }
    }`

But the logeventinfo object has null parameters when i debug. **theEvents** is not added to the parameters like you said.

**Comment by snakefoot** [comment]
@yehonathan I wrote:

> automatically merge the Properties from theEvent

This means that the properties you add to `theEvent` will be appended to the Properties-dictionary of the actual LogEventInfo.

Instead of checking the LogEventInfo.Parameters then you should look at LogEventInfo.Properties.

**Comment by snakefoot** [comment]
@yehonathan and @304NotModified I now see my mistake. I thought that NLog was able to handle the Microsoft-ILogger parameters, but it only handles the formatted message.

The following code is missing from NLogLogger.cs (NLog.Extensions):

```
public void Log<TState>(Microsoft.Extensions.Logging.LogLevel logLevel, EventId eventId, TState state, Exception exception, Func<TState, Exception, string> formatter)
{
      ...

      var eventInfo = LogEventInfo.Create(nLogLogLevel, _logger.Name, message);

      var formattedLogValues = state as IEnumerable<KeyValuePair<string, object>>;
      if (formattedLogValues != null)
      {
            foreach (var logValue in formattedLogValues)
            {
                  var logEvent = logValue.Value as NLog.LogEventInfo;
                  if (logEvent != null && logEvent.HasProperties)
                  {
                        foreach (var prop in logEventParameter.Properties)
                        {
                              eventInfo.Properties.Add(prop.Key, prop.Value);
                        }
                  }
            }
      }

      _logger.Log(eventInfo);
}
```

**Comment by 304NotModified** [comment]
> @yehonathan and @304NotModified I now see my mistake. I thought that NLog was able to handle the Microsoft-ILogger parameters, but it only handles the formatted message

I was also thinking it should work. But I think the `formatter` (https://github.com/NLog/NLog.Extensions.Logging/blob/master/src/NLog.Extensions.Logging/NLogLogger.cs#L30) is breaking it. 

> var formattedLogValues = state as IReadOnlyList<KeyValuePair<string, object>>;

I'm not keen on this. It's a breaking change and I think it's also influence performance. Also I doubting if we should use the code that's already in NLog (nlog.dll), e.g. by passing the logeventinfo to it. 

Another option is to create a new class (e.g. LogProperties), that will be captures here. 
(so `var formattedLogValues = state as LogProperties;`)
That is backwardscompatible.

**Comment by snakefoot** [comment]
@304NotModified Yes ofcourse that would be so much simpler:

```
public void Log<TState>(Microsoft.Extensions.Logging.LogLevel logLevel, EventId eventId, TState state, Exception exception, Func<TState, Exception, string> formatter)
{
    ...
    var eventInfo = state as NLog.LogEventInfo
    if (eventInfo == null)
    {
        if (formatter == null)
        {
            throw new ArgumentNullException(nameof(formatter));
        }

        var message = formatter(state, exception);
        eventInfo = LogEventInfo.Create(nLogLogLevel, _logger.Name, message);
        // Only allocate LogEventInfo-Properties-Dictionary if needed
        if (eventId.Id != 0 || eventId.Name != null)
        {
            // TODO Cache string.Concat() result, instead of always making string-allocations
            eventInfo.Properties["EventId" + _options.EventIdSeparator + "Id"] = eventId.Id;
            eventInfo.Properties["EventId" + _options.EventIdSeparator + "Name"] = eventId.Name;
            eventInfo.Properties["EventId"] = eventId;
        }
    }

   _logger.Log(eventInfo);
}
```

Then it is just a matter of making an extension method like this:

```
private static Func<NLog.LogEventInfo, Exception, string> _nlogFormatter = (l,e,m) => 
l.FormattedMessage;

public static void LogEvent([NotNull] this ILogger logger, LogLevel logLevel, NLog.LogEventInfo state)
{
    logger.Log(logLevel, 0, state, state.Exception, _nlogFormatter);
}
```

> also, isn't eventid=0 not a valid evenid?

I guess one could add a new option to NLogProviderOptions, whether it should attempt to hurt performance by capturing EventId = 0.

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, let us know!
