### ISSUE TITLE
All MDC/MDLC/NDC properties layout renderer

### ISSUE THREAD

**Issue by biiiipy** [NLog/NLog#2108]
**Type** (choose one):
- Feature request

**NLog version**: 4.5.0-alpha4

Can't figure out how to output all MDLC (or MDC/NDC) properties as json object.
It would be great if we could work with this in a similar way as all-event-properties renderer, although it seems that JsonLayout has specific implementation to do this and it's not applicable to other types of property collections like MDLC.

It's kind of possible with custom renderer:

```
LayoutRenderer.Register("all-mdlc-properties", (logEvent) =>
{
    var dict = new Dictionary<string, object>();
    foreach (var mdlcName in MappedDiagnosticsLogicalContext.GetNames())
    {
        dict.Add(mdlcName, MappedDiagnosticsLogicalContext.GetObject(mdlcName));
    }

    return NLog.Targets.DefaultJsonSerializer.Instance.SerializeObject(dict);
});
```

but then obviously the output is not a JSON object, but string containing JSON:
``{"ctx":"{\"b\":\"10\"}}"``
should be:
``{"ctx":{"b":"10"}}"``

**Comment by 304NotModified** [comment]
what's your nlog config here? 

I think you should print the "ctx" by `${all-mdlc-properties}`, or nest it inside a JsonLayout (and set encode=false)

**Comment by biiiipy** [comment]
Thanks for pointing it out, I totally forgot about the third parameter 😄
``jsonLayout.Attributes.Add(new JsonAttribute("ctx", @"${all-mdlc-properties}", false));``
So yes, combining this layout with my custom ``all-mdlc-properties`` renderer works.

And I'm looking forward for this being built-in with PR https://github.com/NLog/NLog/pull/2109
Cheers!

**Comment by 304NotModified** [comment]
OK great! Closing this now! #2109 will be there soon!

**Comment by biiiipy** [comment]
How can we use this in, for example, SimpleLayout? I kind of thought there should be a parameter for ``${mdlc}`` layout render and possibly a seperator character parameter.

**Comment by 304NotModified** [comment]
Please open a new issue. Closed issues are hard to monitor
