### ISSUE TITLE
WebServiceTarget writes encoding preamble (e.g. UTF BOMs)

### ISSUE THREAD

**Issue by fryburger** [NLog/NLog#212]
When using WebServiceTarget with Protocol HttpPost, default encoding is UTF-8. Internally the requests body is written by a StreamWriter, that always prepends some encoding mark bytes (e.g. FE FF for UTF-16). This unfortunately may result in odd behavior, when using standard serializers in receiving ASP.NET services, that ain't aware of such encoder preambles and sometimes deserialize models not completely or even wrong.

My current workaround is, after I configured NLog, parse through the 'AllTargets'-property for a WebServiceTarget and set the Encoding manually like this:

		private static void patchWebServiceTargetEncodingPreambleIssue()
		{
			LogManager.Configuration.AllTargets
				.OfType<global::NLog.Targets.WebServiceTarget>()
				.ToList()
				.ForEach(p => p.Encoding = new System.Text.UTF8Encoding(false));
		}

This creates a UTF-8 encoding for every WebServiceTarget, without written preamble.

Maybe it'd be possible to change that behavior of WebServiceTarget?

**Comment by 304NotModified** [comment]
Needs probably http://msdn.microsoft.com/en-us/library/s064f8w2.aspx

**Comment by 304NotModified** [comment]
3 reports of the same issue. Well this should be fixed in 4.0

**Comment by 304NotModified** [comment]
Note: there are multiple workarrounds:

- See Issue start post
- #250 has another workarround

#380 has a nice example
