### ISSUE TITLE
Feature request: allow format arguments to be lazily evaulated

### ISSUE THREAD

**Issue by Pzixel** [NLog/NLog#2139]
### Why do we need it

I think it's a quite common usecase when you want to log some large amount of data. But most of time, it's only required on `Trace` level or something. For example, assume we have level `WARNING` below:

`logger.Debug("ProceddId = {0} Data received from client = {1}", Process.GetCurrentProcess().Id, JsonConvert.SerializeObject(clientResponse);`
We have to call `GetCurrentProcess` and serialize a large object even when we don't actually writing to the log. Of course, client code may check `IsEnabled(level)` but it seems to be an abstraction leak. 

### Proposition

Add overloads that takes `Func<TArg>` instead of `TArg` and evaluates if and only if we are actually writing to the log. Such "write a lot of data, but only if verbose flag is enabled" seems to be quite often pattern.

**Comment by snakefoot** [comment]
Should be easy to make an extension method to ILogger that takes a Func<T1> as input parameter. This extension method will then check the LogLevel of the ILogger before invoking the Func-delegate.

```
    public static class Hello
    {
        public static void Debug<TArg0>(this ILogger logger, string message, Func<TArg0> arg0)
        {
            if (logger.IsDebugEnabled)
                logger.Log(LogLevel.Debug, message, arg0());
        }

        public static void Debug<TArg0, TArg1>(this ILogger logger, string message, Func<TArg0> arg0, Func<TArg1> arg1)
        {
            if (logger.IsDebugEnabled)
                logger.Log(LogLevel.Debug, message, arg0(), arg1());
        }

        // etc....
    }
```

**Comment by 304NotModified** [comment]
Isn't already there? (LogMessageGenerator parameter)

**Comment by Pzixel** [comment]
@304NotModified wonderful, I wasn't aware about it. So, it's fulfill requirements. This is why I open discussion before creating a pull request :)

However, what's about adding these shortcuts into `Logger.tt` file? I'm not sure because it seems that this `LogMessageGenerator` may have even higher performance comparing to `Lots of funcs`, it supports string interpolation out of the box and other significant pros.

So it's probably doesn't worth and this may be closed.

Stay in touch.

**Comment by c0shea** [comment]
As a simple one-liner for the `LogMessageGenerator`, you could use
logger.Debug(() => $"ProceddId = {Process.GetCurrentProcess().Id} Data received from client = {JsonConvert.SerializeObject(clientResponse)}");

**Comment by 304NotModified** [comment]
> However, what's about adding these shortcuts into Logger.tt file?

What's the benefit of that? And do you mean the `LogMessageGenerator ` or the `Func`?

I like to add the `Func` overloads if and only if it has some performance improvements above the LogMessageGenerator.
