### ISSUE TITLE
Change defaults of NLogViewer target

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#2147]
See https://github.com/NLog/NLog/issues/2145

Change defaults to
- `keepConnection="false" onConnectionOverflow="Block" maxConnections="100"`

**Comment by stil** [comment]
While it works indeed with 100 connections, I think the limit of connections is imposed by `log4view` implementation. So other logging software could have the limit much lower, for example 50 connections or even higher, at 999 connections. Operating system can have even 2^16 = 64K open TCP connections at the moment.

I'd suggest to set default `maxConnections` limit much lower, for example at 16.

**Comment by 304NotModified** [comment]
Good one. But don't you think this will be a too big change in defaults then?

**Comment by stil** [comment]
I don't think unlimited connections were good idea at any time. Also, are we changing defaults for both Network target and NLogViewer target or just NLogViewer?

**Comment by 304NotModified** [comment]
only NLogViewer target.

**Comment by 304NotModified** [comment]
so this is the proposal:
    
    keepConnection="false" onConnectionOverflow="Block" maxConnections="16"

I think this is suitable for the next minor release (4.5)
