### ISSUE TITLE
NLog 5 -> drop .NET Standard 1.x support 

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#2150]
Drop .NET standard 1.x support and move to .NET standard 2.0

related https://github.com/aspnet/Announcements/issues/249

**Comment by jahmai** [comment]
So there will be no stable release of NLog that supports netstandard 1.x? That's not great...

**Comment by 304NotModified** [comment]
No as the stacktrace/strackframe API isn't there in .NET Standard 1.x 

Is it difficult to move to  .NET Standard 2?

**Comment by jahmai** [comment]
It's an upstream dependency issue. We have customers who use our .net standard 1.3 libraries which is using NLog 4.4.0-betaV15. I clearly made a bad bet here as I assumed there would be a stable v4.x with .netstandard support soon after.

We don't use a lot of NLog's functions (like stack trace) because we have our own logging abstraction (NLog provides a bunch of useful targets and live configuration), so in reality we could probably just not use NLog if we want to stay on netstandard 1.3 - so I guess it is not critical for us.

**Comment by 304NotModified** [comment]
> It's an upstream dependency issue. We have customers who use our .net standard 1.3 libraries which is using NLog 4.4.0-betaV15. I clearly made a bad bet here as I assumed there would be a stable v4.x with .netstandard support soon after.

Of course NLog 4.4.0-betaV15 will keep working, but as you may have noticed, there isn't progress on the .NET standard + 4.x

It's also announced here: http://nlog-project.org/2016/10/30/nlog-roadmap-netcore-structural-logging.html

**Comment by jahmai** [comment]
Thanks for the link. Yes NLog 4.4.0-betaV15, but depending on it is marking our package as pre-release (since nuget won't allow stable packages to depend on pre-release ones). It was acceptable short term.

At any rate, I read the blog and saw the challenges and agree that it's not really viable to support NLog on netstandard 1.x. Pity.

**Comment by 304NotModified** [comment]
> it's not really viable to support NLog on netstandard 1.x. Pity.

Could not agree more! 

> but depending on it is marking our package as pre-release

That's not required, for example [NLog.Web.AspNetCore 4.4.0](
https://www.nuget.org/packages/NLog.Web.AspNetCore/4.4.0) is using NLog (>= 5.0.0-beta05) etc

**Comment by jahmai** [comment]
> That's not required, for example NLog.Web.AspNetCore 4.4.0 is using NLog (>= 5.0.0-beta05) etc

You're right! Seems they removed the restriction after our package was first shipped. Good news :)

**Comment by luigiberrettini** [comment]
I think I will try giving my support with #2152 so that it will be easier to migrate libs depending on NLog removing issues like #2253 and #2255 😉

**Comment by snakefoot** [comment]
I think it is a good idea to release NLog ver. 4.5 with support for NetStandard 2.0.

When splitting NLog up into smaller packages, then try and aim for NetStandard 1.3 where possible.

Have just converted the current NLog-master to NetStandard 2.0 (VS2017 15.3), and it required very few modifications, and currently only 9 tests are failing.

**Comment by 304NotModified** [comment]
:+1: good idea!

I had soms trouble upgrading to xunit 2, but maybe it's not needed

**Comment by luigiberrettini** [comment]
Maybe using xUnit.net 2.2+ you won't have any issue since it [supports .NET Standard 1.1+](https://xunit.github.io/)

**Comment by 304NotModified** [comment]
Converting NLog 4.4 to xunit 2 was already an issue in .net 4.5. Done tests suddenly are failing.

**Comment by 304NotModified** [comment]
Update, NLog 4.5 beta 1 has netstandard 2 support. 🎉

**Comment by 304NotModified** [comment]
https://twitter.com/NLogOfficial/status/909135834229755904

**Comment by snakefoot** [comment]
NLog 5.0 is the only one that will support Windows Store Apps (UWP). Until everyone has upgraded to the non-releases version of UWP with NetStandard 2.0 support.

**Comment by 304NotModified** [comment]
true, i won't gonna delete it, but also won't expect a RTM

**Comment by snakefoot** [comment]
#2341 adds support for NetStandard1.5 (UWP10/uap1.0 and NetStandard1.3 are still NLog 5 only).

**Comment by snakefoot** [comment]
Guess this can be closed, as NLog 5.0 is probably going to be the only one supporting UWP10, and NLog 4.5 is now supporting NetStandard1.5

**Comment by 304NotModified** [comment]
The current NLog 5 will be dropped and I will remove the pre-releases in NuGet in favor of NLog 4.5
