### ISSUE TITLE
log filter "action=log" behaving unexpectedly?

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#2151]
When filtering the logging with only one filter with "action=log", this is strange and useless as it won't discard other logevents  

e.g.
```
<logger name="*" writeTo="file">
   <filters>
    <when condition="length('${message}') > 100" action="Log" />
  </filters>
</logger>
``` 

Still *All* logevents will be logged.

Options:

- Or discard others by default when using `action=log` (but not with `action=neutral`?)
- or add an option, "discard-others"
- Or add action logOnly
- add option, default-action (currently _log_)

Related: https://github.com/NLog/NLog/issues/2125
See https://github.com/NLog/NLog/wiki/Filtering-log-messages

**Comment by MarekPokorny** [comment]
Another possibility without changing **logger**...
The configuration could look like this:
- add **filter** elelment
```xml
<logger name="*" writeTo="file">
    <filter condition="length('${exception}') > 0" />
</logger>
```
- or **fastfilter** element...
```xml
<logger name="*" writeTo="file">
    <fastfilter condition="length('${exception}') > 0" />
</logger>
```
The logic of this new **filter** (or **fastfilter**) should work same as when using FilteringWrapper
### Why to do it?
- solid and fast - write to output only when **one condition** is met (this condition can be difficult of course) 
- easy - **no need for actions** - Ignore, Log, Neutral ...
- intuitive - say what logs want to have, **not what logs want to ignore**

Old fitering logic inside **filters** could be without changes.

**Comment by snakefoot** [comment]
Another confused soul:

https://www.codeproject.com/Questions/1205689/How-do-I-filter-an-nlog-logger-to-contain-only-lin

**Comment by 304NotModified** [comment]
I think "default action" is the best option on `<filters>`

**Comment by MarekPokorny** [comment]
On what element will the "default action" be defined? How will it exactly work?

**Comment by 304NotModified** [comment]
Eg

```xml
<logger name="*" writeTo="file">
   <filters default-action="log">
    <when condition="length('${message}') > 100" action="Log" />
  </filters>
</logger>
```

**Comment by MarekPokorny** [comment]
It looks good...

**Comment by MarekPokorny** [comment]
It means when using this example, no log will be written?
```xml
<logger name="*" writeTo="file">
  <filters default-action="log">
  </filters>
</logger>
```

**Comment by snakefoot** [comment]
Maybe it should be called **`defaultFilter`**. Just like:

https://github.com/NLog/NLog/wiki/PostFilteringWrapper-target

**Comment by MarekPokorny** [comment]
It could work...

Marek Pokorný

________________________________
Od: Rolf Kristensen <notifications@github.com>
Odesláno: 16. září 2017 12:59:01
Komu: NLog/NLog
Kopie: Marek Pokorný; Comment
Předmět: Re: [NLog/NLog] log filter "action=log" behaving unexpectedly? (#2151)


Maybe it should be called defaultFilter. Just like:

https://github.com/NLog/NLog/wiki/PostFilteringWrapper-target

**Comment by 304NotModified** [comment]
> It means when using this example, no log will be written?
> 
> <logger name="*" writeTo="file">
>   <filters default-action="log">
>   </filters>
> </logger>

No, with that case, all of them will be logged.

You need this then (to log nothing)

```xml
<logger name="*" writeTo="file">
  <filters default-action="ignore">
  </filters>
</logger>
```
notice the `default-action="ignore"`

**Comment by MarekPokorny** [comment]
Thank you for your answer.
This solution can be used to solve my problem. Good.

**Comment by 304NotModified** [comment]
thanks for the feedback!

**Comment by MarekPokorny** [comment]
Thank you for your work on NLog! It is very powerfull logging system...

________________________________
Od: Julian Verdurmen <notifications@github.com>
Odesláno: 10. října 2017 0:17:56
Komu: NLog/NLog
Kopie: Marek Pokorný; Comment
Předmět: Re: [NLog/NLog] log filter "action=log" behaving unexpectedly? (#2151)


thanks for the feedback!

**Comment by 304NotModified** [comment]
FYI

it will be the attribute "defaultAction", as filter as an "action" and all attributes in the NLog Config are camelCase and not kebab-case
