### ISSUE TITLE
Support .NET Standard 2.0

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#2152]
Results of analysis on NLog 4.4.10

- 67 warnings for .Net standard 2.0 ( .Net standard 1.6 had 196)
- see also https://github.com/NLog/NLog/issues/2150

details:

![image](https://cloud.githubusercontent.com/assets/5808377/26757615/2b0856a0-48c2-11e7-94f3-8e02a453d26b.png)

**Comment by 304NotModified** [comment]
Zip of html (same results)

[ApiPortAnalysis-NLog-netstandard2.html.zip](https://github.com/NLog/NLog/files/1050015/ApiPortAnalysis-NLog-netstandard2.html.zip)

**Comment by 304NotModified** [comment]
http://www.michael-whelan.net/replacing-appdomain-in-dotnet-core/

**Comment by snakefoot** [comment]
Should include the following changes from CoreClr-branch:

**BaseFileAppender.cs:**

if (this.CreateFileParameters.EnableFileDelete <del>&& PlatformDetector.CurrentOS != RuntimeOS.Windows </del>)
{
   fileShare |= FileShare.Delete;
}

**ObjectGraphScanner.cs** (Everything)

**ThreadLocalStorageHelper.cs** (Everything)

**NativeMethods.cs** (Everything)

**Win32FileNativeMethods.cs** (Everything)

**StackTraceLayoutRenderer.cs** (Null-check in Append)

```
if (logEvent.StackTrace == null)
   return;
```

**AsyncHelpers.cs** (WaitForDispose)

**ConsoleTarget.cs** (WriteToOutput should also catch ArgumentOutOfRangeException)

**OutputDebugStringTarget.cs** (Everything)

**MappedDiagnosticsLogicalContext.cs** (Everything)

**InternalLoggerTests.cs** (Everything- Fixes xUnit2)

**ConfigApiTests.cs** (Inherit from NLogTestBase - Fixes xUnit2)

**XmlConfigTests.cs** (Everything- Fixes xUnit2)

**GlobalDiagnosticsContextTests.cs** (Inherit from NLogTestBase - Fixes xUnit2)

**MappedDiagnosticsContextTests.cs** (Inherit from NLogTestBase - Fixes xUnit2)

**MappedDiagnosticsLogicalContextTests.cs** (Inherit from NLogTestBase - Fixes xUnit2)

**NestedDiagnosticsContextTests.cs** (Inherit from NLogTestBase - Fixes xUnit2)

**LayoutHelpersTests.cs** (Inherit from NLogTestBase - Fixes xUnit2)

**MdlcLayoutRendererTests.cs** (Inherit from NLogTestBase - Fixes xUnit2)

**LogManagerTests.cs** (ThreadSafe_getCurrentClassLogger_test - And remove Unity-dependency)

**Comment by 304NotModified** [comment]
Sounds good!
