### ISSUE TITLE
No logging due to network problems?

### ISSUE THREAD

**Issue by AndersTornqvist** [NLog/NLog#2157]
Problem summary:
================
We are using nLog for logging to file located on the same server as the application is placed.

See attached file for nLog section we are using:

```xml
<nlog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <targets>
    <target name="jsonFile" xsi:type="File" 
                fileName="C:\temp\logs\${machinename}.json"             
                archiveFileName="C:\temp\logs\Archive\${shortdate}\{#}-${machinename}.log"
                                archiveEvery="Minute" 
                                archiveNumbering="Date" 
                                archiveDateFormat="yyyy-MM-dd_HH.mm"
                                createDirs="True" >
      <layout xsi:type="JsonLayout">
         ....
       </layout>
     </target> 
  </targets>
  <rules>
      <logger name="*" minlevel="Debug" writeTo="jsonFile" />
  </rules>
</nlog>
```

We have received reports that archive files is empty when a network connection problem occurs. The application always contact nLog for logging, whatever the result is.

When we recreate the error the log files and archive files are filled with information.

We cannot see that a network connection problem would stop nLog to log, as the file is placed on the same server as the application.

Any assistance or suggestion in this matter would be greatly appreciated?

**Comment by 304NotModified** [comment]
Please provide the version number  and internal log etc (from the template)

**Comment by AndersTornqvist** [comment]
NLog version is: 4.3.4
We do not have an internal log. It's not activated in production and we cannot recreate the problem in test or debug.

**Comment by 304NotModified** [comment]
That's strange as the FileTarget isn't using network connecties (only when logging over the network). 

Would recommend to enable the internal log in productie and post the error when it's a problem

**Comment by snakefoot** [comment]
@AndersTornqvist So both the active log-file (${machinename}.json) and the log-files in the archive-folder are empty, when the network-error occurs? Not a disk-full error?

**Comment by 304NotModified** [comment]
Would also recommended to update NLog.

**Comment by 304NotModified** [comment]
Is this still an issue? Please update and provide the required info, thanks!

**Comment by AndersTornqvist** [comment]
We are still searching and cannot recreate the problem. We have requested that internal logging is enabled but have not yet received any results.

**Comment by 304NotModified** [comment]
Let me know if this is again happening and please post the info. Thanks!
