### ISSUE TITLE
MDLC Value lost during ASP.NET Application_EndRequest processing

### ISSUE THREAD

**Issue by HowardHoffman** [NLog/NLog#2158]
Question (or Bug; am unsure)

Platform: ASP.Net .NET 4.6.1 and .NET 4.6.1 (console application) - occurs both on local environment, Windows 10, and Azure AppService.

NLog version:  4.3.9

We use multiple threads and `async` / `await` operators liberally in our code.  We use NLog's MDLC to emit correlation-ids so we can effectively reason over the logs.  It's mostly great - but there is an odd case that we are a bit stumped over.

We often lose the `correlation-id` value in the log statement written by our end-of-request code.

We have this block of code in Global.asax.cs:
```c#
protected void Application_BeginRequest(object sender, EventArgs e)
    {
        string correlationId = Guid.NewGuid().ToString("N");
        MappedDiagnosticsLogicalContext.Set(LoggingArgumentConstants.CorrelationIdKey, correlationId);
         logger.Trace($"In Application_BeginRequest for URL [{System.Web.HttpContext.Current?.Request?.Url?.ToString()}].");
         ...
    }
...
 protected void Application_EndRequest(object sender, EventArgs e)
    {
        logger.Trace($"Application_EndRequest for URL [{System.Web.HttpContext.Current?.Request?.Url?.ToString()}] by user [{System.Web.HttpContext.Current?.User?.Identity?.Name}]");
            //Remove stored correlation info
            MappedDiagnosticsLogicalContext.Remove(LoggingArgumentConstants.CorrelationIdKey);
    }
```

That reads to me like we should *always* have a value for `CorrelationIdKey` in the log -- but we often don't.  

This is related to https://github.com/NLog/NLog/issues/1714; more evidence of the root issue is a limitation where an NLog code change should to be considered (e.g. as opposed to documenting as a limitation).  Namely should we have NLog place MDLC into some container that tolerates both ASP.NET and non-ASP.NET scenarios.  The write up in https://github.com/NLog/NLog/issues/1714 links to blog posts that discuss more robust solutions.  The writeup by tpodolak.com describes a work-around.  We are about to try the work-around -- but I note that we have a libraries that need to run in both ASP.NET and console applications.

Because 1714 is currently closed I perhaps erred in providing comments to that issue.  I repeat those comments, verbatim, below:
****

There is a real issue in the MDLC functionality, when used in ASP.NET. This blob post (not by me or anyone in our organization; a colleague in our group found it) discusses w/ examples: https://tpodolak.com/blog/2016/07/05/nlog-tracking-flow-of-requests-using-mappeddiagnosticslogicalcontext/.

Our case is slightly different: we have code in Global.asax.cs Application_BeginRequest / Application_EndRequest that creates a correlationId and calls MappedDiagnosticsLogicalContext.Set("correlationIdKey", value); during Application_BeginRequest. Code in Application_EndRequest logs the "end of the request" as a marker. We call MappedDiagnosticsLogicalContext.Remove("correlationIdKey"); on the line immediately after the log statement. That log statement sometimes emits a value for "correlationIdKey" and sometimes does not. This pattern is reproducible.

**Comment by 304NotModified** [comment]
Not sure if we could solve this.

For ASP.NET you could also use `${aspnet-item}`.

```
HttpContext.Current.Items["myvariable"] = 123;

${aspnet-item:variable=myvariable} - produces "123"
```

See https://github.com/NLog/NLog/wiki/AspNetItem-layout-renderer

**Comment by snakefoot** [comment]
Sounds very similar to this:

http://piers7.blogspot.dk/2005/11/threadstatic-callcontext-and_02.html

Seems normal CallContext is not supported by the suspend / resume of requests in the IIS (Only HttpContext). 

From the mouth of the horse, then it says using aspnet-items:

https://www.hanselman.com/blog/ATaleOfTwoTechniquesTheThreadStaticAttributeAndSystemWebHttpContextCurrentItems.aspx

Curious if AsyncLocal is working better than CallContext (maybe create custom layout-renderer to test):

https://github.com/NLog/NLog/blob/coreCLR/src/NLog/MappedDiagnosticsLogicalContext.cs

**Comment by 304NotModified** [comment]
I think we cannot fix this, and so labeling as "known issue".

Recommend to use the `${aspnet-item}.`

**Comment by snakefoot** [comment]
Created #4643 with an idea to allow scope-properties to propagate back to the parent-task
