### ISSUE TITLE
NLog.confing indirect reference project

### ISSUE THREAD

**Issue by jirisykora83** [NLog/NLog#2161]
Type: Feature request

NLog version:  Any

Description:

When you have NLog in one project (project A). Then you have project B which reference project A and finally you have project C which reference project B (whatever console app or app which you actually run).

Then NLog.confing is not copy to output folder (even if you have right settings in visual studio "copy always").

Solution is add direct reference from project A to project C (maybe it is possible "hack" it via some post-build task but i don't try it).

Idea: Somebody with better English like me could add this to Troubleshooting in wiki (i think this is not to uncommon situation).

**Comment by 304NotModified** [comment]
Thanks, clear to me. 

We have to test this, a I think it should work.

@jirisykora83 What is the version of your Visual Studio?

**Comment by jirisykora83** [comment]
@304NotModified Last. Visual Studio 2017.

**Comment by 304NotModified** [comment]
we need to check this, adding this to 4.6

**Comment by snakefoot** [comment]
Maybe just remove the non-working NLog.config nuget-package. See also #3882
