### ISSUE TITLE
.NET Standard + .NET Framework = System.MissingMethodException: NLog.Logger NLog.LogManager.GetCurrentClassLogger(System.String)

### ISSUE THREAD

**Issue by stil** [NLog/NLog#2162]
> **Type** (choose one):

Bug

> **NLog version**: 

5.0.0-beta07

> **Platform**:

Mixed .NET 4.7 and .NET Standard

> What is the current result?

I have 2 projects, one is .NET 4.7 executable and second is .NET Standard 1.6 library with NLog installed.
In second library project, following call

```csharp
private readonly Logger Logger = LogManager.GetCurrentClassLogger();
```

crashes with an exception

```
System.MissingMethodException: NLog.Logger NLog.LogManager.GetCurrentClassLogger(System.String)
```

I think it's caused by method signature mismatch here: https://github.com/NLog/NLog/blob/coreCLR/src/NLog/LogFactory.cs#L450-L492

There are two method overloads that can be called without arguments

```csharp
Logger GetCurrentClassLogger([CallerFilePath] string path = ""); // .NET Standard
Logger GetCurrentClassLogger(); // .NET Framework
```

So if a solution has mixed targeting (for example .NET 4.7 + .NET Standard) it fails, because there is a collision.

**Comment by 304NotModified** [comment]
Unfortunately i'm aware of that. 

There isn't a quickfix I think.

We will fix this in 5.0 RTM, by targeting netstandard 2.0 and dropping netstandard 1.x support. See #2150

**Comment by 304NotModified** [comment]
Resolved in https://github.com/NLog/NLog/pull/2146

Will be released in NLog 5 beta 8. 

Thanks @snakefoot and @stil !!

**Comment by snakefoot** [comment]
@arunprasathv Please create a new issue, instead of commenting on old unrelated ones.
