### ISSUE TITLE
Suggestion: Add More logLevel

### ISSUE THREAD

**Issue by mhamri** [NLog/NLog#2169]
Hi, I am a usual Log4net user and thought it would be nice if you guys also add more log level in NLog

Alert 
All
Critical
Debug 
Emergency 
Error 
Fatal 
Fine / Success
Finer 
Finest 
Info 

Thanks for the awesome library

**Comment by snakefoot** [comment]
Similar to this issue #1762

**Comment by 304NotModified** [comment]
Closing as duplicate
