### ISSUE TITLE
archiving "Sequence" not moving last file if log fileName has date

### ISSUE THREAD

**Issue by ejamali0x** [NLog/NLog#2180]
I tried to use date in log file name but also required to archive the log file in different path with the sequence number based on the size but latest file of each day remain in the current path and they are not archiving to the archive path as the last file of the day, here is the details:

**NLog version**:  4.4.5
**Platform**: .Net 4.5 

<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="false"
      internalLogLevel="Debug" internalLogFile="C:\temp\nlog-internal.log">

  <variable name="myvar" value="myvalue"/>
  <targets>

    <target xsi:type="RepeatingWrapper" name="AsyncLog" repeatCount="1">    
      <target xsi:type="File" 
              name="LogFile"
              layout="${longdate}|${pad:padding=-5:inner=${level:uppercase=true}}|${logger}|${message}"
              fileName="D:\Logs\mylog-${date:yyyyMMdd}.log"
              concurrentWrites="false"
              keepFileOpen="true"
              openFileCacheTimeout="30"
              encoding="iso-8859-2"
              archiveFileName="D:\Archive\${date:yyyyMMdd}\mylog-${date:yyyyMMdd}.{###}.log"
              archiveAboveSize="500000000"
              archiveNumbering="Sequence"
              enableArchiveFileCompression="false" />
    </target>
  </targets>
  <rules>
    <logger name="*" minlevel="Debug" writeTo="AsyncLog"/>
  </rules>
</nlog>

The current result?
Current Log path "D:\Logs\" is including such file as following 
mylog-20170620.log
mylog-20170619.log
mylog-20170618.log
mylog-20170617.log
And Archiving path "D:\Archive\" including following folder and files:
D:\Archive\20170620\
   mylog-20170620-000.log
D:\Archive\20170619\
   mylog-20170619-001.log
   mylog-20170619-000.log
D:\Archive\20170618\
   mylog-20170618-002.log
   mylog-20170618-001.log
   mylog-20170618-000.log
D:\Archive\20170617\
   mylog-20170617-001.log
   mylog-20170617-000.log

The expected result?
The expectation is after changing date is creating new file in the current Log path "D:\Logs\" the latest file of previous day move to the relevant archive folder and get the sequence number accordingly such as this example, the current file should only keep today's latest file
mylog-20170620.log
And Archiving path "D:\Archive\" including following folder and files:
D:\Archive\20170620\
   mylog-20170617-000.log
D:\Archive\20170619\
   mylog-20170619-002.log
   mylog-20170619-001.log
   mylog-20170619-000.log
D:\Archive\20170618\
   mylog-20170618-003.log
   mylog-20170618-002.log
   mylog-20170618-001.log
   mylog-20170618-000.log
D:\Archive\20170617\
   mylog-20170617-002.log
   mylog-20170617-001.log
   mylog-20170617-000.log
Internal log has no exception

Is this scenario possible in the current NLog or did i missed some parameter to be configured?

**Comment by snakefoot** [comment]
If you want date and sequence, then you can try these parameters:

```
archiveNumbering="DateAndSequence"
archiveDateFormat="yyyyMMdd"
archiveFileName="D:\Archive\${date:yyyyMMdd}\mylog-{###}.log"
```

**Comment by ejamali0x** [comment]
Thank you @snakefoot,
Can combine archiveEvery="Day" to archiveAboveSize="500000000"?
Because the daily log size is huge and I need to limit it to manageable size such as 500MB

I tried to simulate the combination with smaller archiveAboveSize and changing date of the system manually, after changing the date the current log folder only keep one file as current date but the latest file of prev date will move to the folder of the current date with sequence 000 and 
D:\Logs
mylog-20170622-000.log

D:\Archive\20170622
**mylog-20170621-000.log** (must be in the D:\Archive\20170621 folder as mylog-20170621-003.log)
mylog-20170622-000.log
D:\Archive\20170621
mylog-20170621-000.log
mylog-20170621-001.log
mylog-20170621-002.log

**Comment by snakefoot** [comment]
> Can combine archiveEvery="Day" to archiveAboveSize="500000000"?

@ejamali0x Yes you can combine these. But I think the problem is having `${date:yyyyMMdd}` inside the `archiveFileName`. It will use the date of the new LogEvent, instead of the current log-file. I guess NLog cannot put the log-files into separate date-folders.

**Comment by ejamali0x** [comment]
@snakefoot Thank you for clarification

> But I think the problem is having ${date:yyyyMMdd} inside the 

You mean the sub-folder here:
archiveFileName="D:\Archive\${date:yyyyMMdd}\mylog-{###}.log"
if is the case i will try to arrange it in different way
Thank you, i will revert the feedback shortly

**Comment by ejamali0x** [comment]
@snakefoot I've already tried with removing `${date:yyyyMMdd}` from `archiveFileName` during automatic system date change and all the file from previous date will move to the archive path and only latest log file remain in log file path
here is the latest configuration for the reference
```
<target xsi:type="RepeatingWrapper" name="AsyncLog" repeatCount="1"> 
  <target xsi:type="File" 
          name="LogFile"
          layout="${longdate}|${pad:padding=-5:inner=${level:uppercase=true}}|${logger}|${message}"
          fileName="D:\Logs\mylog-${date:yyyyMMdd}.log"
          concurrentWrites="false"
          keepFileOpen="true"
          openFileCacheTimeout="30"
          encoding="iso-8859-2"
          archiveEvery="Day"
          archiveAboveSize="500000000"
          archiveNumbering="DateAndSequence"
          archiveDateFormat="yyyyMMdd"
          archiveFileName="D:\Archive\\mylog-{###}.log"
          enableArchiveFileCompression="false" />
</target>
```
Thank you for your help,
You can close this issue.
