### ISSUE TITLE
.NET Core LogManager.GetCurrentClassLogger(): ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by haidelber** [NLog/NLog#2181]
**Type**: Bug

**NLog version**: 5.0.0-beta8

**Platform**: .NET Core 2.0

**Current NLog config**: not relevant

One of my classes is instantiated via Autofac. This class has a member `public readonly Logger Logger = LogManager.GetCurrentClassLogger();`. Every time a new instance is created I get following Exception:

```
System.ArgumentOutOfRangeException: Length cannot be less than zero.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at NLog.Internal.StackFrameExt.GetClassFullName()
   at NLog.LogManager.GetCurrentClassLogger()
   at EvaluationFramework.Data.SeedData.Impl.SeedIdentity..ctor(EntityContext context, RoleManager`1 roleManager, UserManager`1 userManager) in *****\Data\SeedData\Impl\SeedIdentity.cs:line 11
   at lambda_method(Closure , Object[] )
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
```
The funny thing is as soon as I declare this member static the exception disappears.

After peeking into the code it seems to be a problem here: https://github.com/NLog/NLog/blob/v5.beta8/src/NLog/Internal/StackFrameExt.cs Line 106

If you need more data/details/code I'm happy to contribute.

Thanks,
Stefan

**Comment by 304NotModified** [comment]
Hey! Thanks for reporting!

**Comment by snakefoot** [comment]
@haidelber I'm guessing it is choking on this line:

`at lambda_method(Closure , Object[] )`

But I'm curious why it has skipped this line, since it works just fine:

`at EvaluationFramework.Data.SeedData.Impl.SeedIdentity..ctor(EntityContext context, RoleManager`1 roleManager, UserManager`1 userManager) in *****\Data\SeedData\Impl\SeedIdentity.cs:line 11`

Curious if something is different in the initial Environment.StackTrace on NETCore 2.0

**Comment by snakefoot** [comment]
Think something might have been changed here:

https://github.com/dotnet/coreclr/issues/6209

**Comment by snakefoot** [comment]
@haidelber Can you test if this custom NuGet-package (from #2182) fixes the exception and gives the right logger-name?

https://ci.appveyor.com/project/nlog/nlog/build/5.0.0-beta5485/artifacts

**Comment by haidelber** [comment]
@snakefoot Thanks, it works with this build.

**Comment by snakefoot** [comment]
@haidelber NLog 5.0 BETA09 is now available on NuGet:

https://www.nuget.org/packages/NLog/5.0.0-beta09

**Comment by 304NotModified** [comment]
Fixed in beta 9 thanks to @snakefoot!
