### ISSUE TITLE
No log file generated with code and config set up via Visual Studio for Mac

### ISSUE THREAD

**Issue by robertchong** [NLog/NLog#2184]
Hi,

I'm using Visual Studio for Mac. After getting NLog installed via NuGet and NLog.config configured, I can't get my code (see https://github.com/robertchong/NLogVS4MacDemo) to get log file generated. What am I missing?

**Type** (choose one): Question

**NLog version**: 4.4.11

**Platform**: Mono 5.0.1.1 

**Current NLog config** 
See https://github.com/robertchong/NLogVS4MacDemo/blob/master/NLog.config

**Comment by 304NotModified** [comment]
Is it a case sensitive file system?  Then is should be "nlog.config" (lower case)

Otherwise check the internal log.

**Comment by robertchong** [comment]
Yes it is. Renamed to nlog.config. Still no luck. I did specify internalLogFile="/tmp/nlog-internal.log" in nlog.config but there's no internal log in /tmp.

**Comment by snakefoot** [comment]
@robertchong Think you have to setup the InternalLogger by code, since the NLog.config is not used. Maybe include the NLog.config in your app.config:

https://gist.github.com/Chrisso/1703644

**Comment by robertchong** [comment]
I included App.config and no log. I then created a new [branch1](https://github.com/robertchong/NLogVS4MacDemo/tree/branch1) branch with the App.config, checked it out into my Visual Studio 2017 running on Windows 10, updated NLog.config by changing   internalLogFile to "C:\Temp\nlog-internal.log" and internalLogLevel to "Trace" but still can't see app.log or nlog-internal.log. What am I missing? I would appreciate if you can shed any light on this. Thanks.

**Comment by robertchong** [comment]
Update: I just ported the same code into my Visual Studio 2015 running on Windows 7 machine and it works fine. Without including the NLog.config to my App.config, I can see app.log as well as c:\temp\nlog-internal.log generated.

**Comment by robertchong** [comment]
Update: Using the same Visual Studio 2017, I recreated the NLog demo code from scratch. Without adding NLog.config to App.config, I can get app.log and nlog-internal.log generated. Looks like there are things needed to be sorted out on the VS4Mac side.

**Comment by 304NotModified** [comment]
Is this resolved or do we need to do something?

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, let us know!
