### ISSUE TITLE
NLog doesn't work with xUnit when 'netcoreapp1.1' is targeted.

### ISSUE THREAD

**Issue by stil** [NLog/NLog#2187]
> **Type** (choose one):
- Bug

> **NLog version**:

5.0.0-beta09 (previous beta releases are also affected)

> **Platform**:

.NET Core

> **To reproduce**:

Create following .csproj

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NLog" Version="5.0.0-beta09" />
    <PackageReference Include="xunit" Version="2.3.0-beta3-build3705" />
    <DotNetCliToolReference Include="dotnet-xunit" Version="2.3.0-beta3-build3705" />
  </ItemGroup>
  
</Project>
```

Add dummy test class

```csharp
using Xunit;

namespace MyFirstUnitTests
{
    public class Class1
    {
        [Fact]
        public void PassingTest()
        {
            Assert.Equal(4, Add(2, 2));
        }
        
        int Add(int x, int y)
        {
            return x + y;
        }
    }
}
```

Run with following commands:

```bash
dotnet restore
dotnet xunit
```

It fails with following error message

```
Running .NET Core tests for framework netcoreapp1.1...
Error: assembly specified in the dependencies manifest was not found -- package: system.diagnostics.tracesource', version: '4.0.0', path: 'runtimes/win/lib/netstandard1.3/System.Diagnostics.TraceSource.dll'
```

When you change target from `netcoreapp1.1` to, for example, `net47`, it works correctly.

```
Running desktop CLR tests for framework net47...
xUnit.net Console Runner (64-bit Desktop .NET 4.0.30319.42000)
  Discovering: CurlThin.Tests
  Discovered:  CurlThin.Tests
  Starting:    CurlThin.Tests
  Finished:    CurlThin.Tests
=== TEST EXECUTION SUMMARY ===
   CurlThin.Tests  Total: 1, Errors: 0, Failed: 0, Skipped: 0, Time: 0,206s
```

It seems like it's a compatibility issue between xunit and NLog, but I need your help on this. I'm not even sure how to debug this issue.

**Comment by 304NotModified** [comment]
`dotnet build` gives the same error?

**Comment by stil** [comment]
`dotnet build` succeeds, no errors are thrown.

**Comment by 304NotModified** [comment]
Thanks for checking.

Honestly I have no idea. I try to google something.

Could you please try adding `system.diagnostics.tracesource` to `<PackageReference `?

**Comment by stil** [comment]
I've already tried adding `System.Diagnostics.Tracesource` as `<PackageReference>` but it doesn't help. I also tried googling before posting this issue but I ended up with nothing.

**Comment by 304NotModified** [comment]
Related: https://github.com/dotnet/corefx/issues/3378

**Comment by 304NotModified** [comment]
Could you please try specifying the runtime in the csproj?

**Comment by stil** [comment]
I tried, it didn't help. I decided I'll do my tests with MS test driver. I changed my .csproj to following

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NLog" Version="5.0.0-beta09" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0" />
    <PackageReference Include="Microsoft.TestPlatform.TestHost" Version="15.0.0" />
    <PackageReference Include="xunit" Version="2.3.0-beta3-build3705" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.3.0-beta3-build3705" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CurlThin.Native\CurlThin.Native.csproj" />
    <ProjectReference Include="..\CurlThin\CurlThin.csproj" />
  </ItemGroup>
  
</Project>
```

I run my tests with
```
dotnet restore
dotnet test
```

It works, so I suppose xunit's `dotnet xunit` command is somehow broken.

Before we waste too many hours here, I suggest to close this issue, because it appears to be very hard to debug. I'll stick with `dotnet test` instead of `dotnet xunit`.

**Comment by 304NotModified** [comment]
Well maybe it would be nice to report it at xunit.

**Comment by stil** [comment]
There is very similiar issue reported on xunit repository 2 days ago https://github.com/xunit/xunit/issues/1336

**Comment by 304NotModified** [comment]
OK thanks, will close this one indeed.
