### ISSUE TITLE
Unstable test on Travis: BufferingTargetWrapperAsyncTest1

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#2206]
See https://travis-ci.org/NLog/NLog/builds/250136516

and 

https://travis-ci.org/NLog/NLog/builds/284469275

**Comment by snakefoot** [comment]
Could be solved by adding AsyncOperationCounter to the test-target MyAsyncTarget

**Comment by 304NotModified** [comment]
could you give me a hint how to use the `AsyncOperationCounter` (https://github.com/NLog/NLog/blob/master/src/NLog/Internal/AsyncOperationCounter.cs) here?

**Comment by snakefoot** [comment]
See MyAsyncTarget in AsyncTargetWrapperTests

**Comment by 304NotModified** [comment]
@snakefoot if you find some time in fixing this, then please. it's really delaying the merge of PRs and the release.
