### ISSUE TITLE
Exceptions in LoggingConfiguration.Install() getting swallowed

### ISSUE THREAD

**Issue by rbarillec** [NLog/NLog#2207]
**Type**: Bug / Question (if incorrect usage)

**NLog version**: 4.4.11 (from official NuGet repo)

**Platform**: .Net 4.5.1

**Current NLog config** (xml or C#, if relevant)

```xml
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      internalLogLevel="Debug" internalLogFile="nlog-internal.log">

  <targets>

    <!-- Log to console -->
    <target name="consoleTarget"
            xsi:type="Console"
            layout="[Console logger] ${logger} | ${message}"
    />

    <!-- And to SQLite database -->
    <target name="databaseTarget"
          xsi:type="Database"
          dbProvider="System.Data.SQLite.SQLiteConnection, System.Data.SQLite"
          connectionString="Data Source=logs.sqlite3;Version=3;"
          commandType="Text"
    >
      <commandText>
        INSERT INTO Logs(logger, message)
        VALUES(@logger, @message)
      </commandText>

      <parameter name="@logger" layout="${logger}"/>
      <parameter name="@message" layout="${message}" />

      <install-command commandType="Text" ignoreFailures="false">
        <text>
          DROP TABLE IF EXISTS Logs
        </text>
      </install-command>

      <install-command commandType="Text" ignoreFailures="false">
        <text>
          CREATE TABLE Logs(
          id integer primary key,
          logger text,
          message text
          )
        </text>
      </install-command>
    </target>

  </targets>

  <rules>
    <logger name="*" minlevel="Debug" writeTo="databaseTarget" />
    <logger name="*" minlevel="Debug" writeTo="consoleTarget" />
  </rules >
</nlog>
```

**Test program**:

I've reproduced the issue below. Namely, I have a read-only SQLite database file that NLog is trying to install and then log to. Both the `Configuration.Install()` and the `logger.Error()` trigger a "database is read-only" exception (as expected and seen in Visual Studio debugger), however the first exception never reaches my code (the second does, as expected). Note that the `ThrowConfigExceptions` and `ThrowExceptions` flags are set to `true`.

```csharp
class Program
{
    static void Main(string[] args)
    {
        LogManager.ThrowConfigExceptions = true;
        LogManager.ThrowExceptions = true;

        try
        {
            LogManager.Configuration.Install(new InstallationContext(Console.Out) { IgnoreFailures = false});
        }
        catch (Exception)
        {
            SwitchToBasicLogger();
        }

        try
        {
            var logger = LogManager.GetCurrentClassLogger();
            logger.Error("Logging something");
            logger.Warn("Logging something else");
        }
        catch (Exception)
        {
            Console.WriteLine("Logging failed");
        }
            
        Console.WriteLine("Test complete");
    }

    private static void SwitchToBasicLogger()
    {
        Console.WriteLine("Switching to basic logger.");
    }
}
```

- **Actual console output**

```

Installing 'Database Target[databaseTarget]'
attempt to write a readonly database
attempt to write a readonly database
Install of 'Database Target[databaseTarget]' failed: System.Data.SQLite.SQLiteException (0x80004005): attempt to write a readonly database
attempt to write a readonly database
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery()
   at NLog.Targets.DatabaseTarget.RunInstallCommands(InstallationContext installationContext, IEnumerable`1 commands)
   at NLog.Targets.DatabaseTarget.Install(InstallationContext installationContext)
   at NLog.Config.LoggingConfiguration.Install(InstallationContext installationContext).
Logging failed
Test complete
```

- **Expected output:** I'd expect the console output to show `Switching to basic logger` but it doesn't.

- **Why this is an issue:**
   - I have no way to tell whether NLog was successful in setting up the log database and can't therefore react to the failure, e.g. to switch to a dummy logger and let the user know that logging is currently disabled (or limited). The only way I could achieve that (I think?) would by to parse the internal log or the output of the `InstallationContext`, which would be quite fragile.
   - Every subsequent call to `logger.Error()` triggers the same exception again, which is expensive and unnecessary: we know this is going to fail.

- **Questions:**
   - Am I not using the exception flags correctly? None of them (`ThrowConfigExceptions`, `ThrowExceptions` and `InstallationContext.IgnoreFailures` seem to have any effect on the `LoggingConfiguration.Install()` call.
   - Looking at the source, it looks like there's blanket `catch` in [LoggingConfiguration.Install()](https://github.com/NLog/NLog/blob/master/src/NLog/Config/LoggingConfiguration.cs#L372)). Is there a reason for this and why doesn't this reflect the `ThrowConfigExceptions` or `ThrowExceptions` flags? 
   - What is, then, the recommended way to react to a target initialisation failure? 

- **Are there any work arrounds?**

As mentioned above, I guess one could parse the output of the `InstallationContext` for errors, but this would be prone to error. It might also be possible to set up a custom fallback target which in turn provides a way to react to the installation failure, but this feels a bit convoluted.

- **Is there a version in which it did work?**

Not sure, I have only recently switch to NLog.

- **Can you help us by writing an unit test?**

I'll see if I can turn my example above into one.

- **Why do we need it?**

So that in case of failure, we can turn off the logging, change the state of the application accordingly and notify users that logging is currently disabled. 

- **An example of the XML config, if relevant.**

I think installation of targets has to be done in code? My preference would be for standard exception handling:

```csharp
try { 
    LogManager.Configuration.Install(new InstallationContext()) 
}
catch { 
   /* Disable logging, switch to a different logger, notify the user, etc. */ 
}
```

**Comment by rbarillec** [comment]
Ok, I only just noticed the `throwException = false` in my config file (I used the default and hadn't spotted it). This seems to take precedence over `LogManager.ThrowExceptions = true`. If I remove the attribute or set it to `true`, then the `logger.Error()` **does** throw the exception and hits my `catch` block. That's the second part of my issue addressed.

The exception thrown inside `LoggingConfiguration.Install()` is still getting swallowed, though.

**Comment by rbarillec** [comment]
Initially, I had both `throwException = false` in the config file and `LogManager.ThrowExceptions = true` in the code. It looks like the config file takes precedence over the API route. I have removed the `throwException=false` from the config file and edited the issue above to remove the question about why exceptions weren't being thrown by the `logger.Error()` call (they now are as I'd expect).

The exception thrown inside `LoggingConfiguration.Install()` is still getting swallowed, though.

**Comment by 304NotModified** [comment]
I checked it, the errors are logged to the [`installationContext.LogOutput`](https://github.com/NLog/NLog/blob/6b41b3dae7410532e933b8b3261e5ef6d6642ff8/src/NLog/Config/InstallationContext.cs#L100). (and console)

See also [logging code](https://github.com/NLog/NLog/blob/6b41b3dae7410532e933b8b3261e5ef6d6642ff8/src/NLog/Config/InstallationContext.cs#L147)

Bit difficult/unlogical to use, maybe we should improve it.

**Comment by rbarillec** [comment]
@304NotModified Thanks for the quick reply and the links. I am aware that NLog captures exceptions internally, and that works fine. What I'm missing here is a way to tell - in my client code - if the installation was successful or not. I had (incorrectly) assumed that `ThrowExceptions=true` would mean exceptions thrown during the installation would propagate into my code (as they do with the logger). 

It might be worth updating the docs to explicitly mention that `LoggingConfiguration.Install()` will always catch exceptions (bar the 3 or 4 critical ones that it lets through), regardless of the `ThrowExceptions=true` flag?

Meanwhile, I'm trying to see if I can achieve what I want with a [`FallbackGroupTarget`](https://github.com/nlog/NLog/wiki/FallbackGroup-target) (if database target can't be installed, then fall back to a custom target which I can use to indicate that the installation has failed).

**Comment by 304NotModified** [comment]
Well you can read the property and throw the exception yourself? (Not ideal of course)

If you send a PR for the docs, that would be great!

**Comment by rbarillec** [comment]
I did consider it, but parsing the `LogOutput` would be really fragile. I don't know what NLog write to this log, this is really an implementation detail and it could change at any time.

I did get some way with the `FallbackGroupTarget`, in that if the log database can't install, logging then fails and falls back to a `NullTarget`. This is close to what I need. I think I might now be able to use a [`MethodCallTarget`](https://github.com/nlog/NLog/wiki/MethodCall-target) instead of a `NullTarget` and hopefully use that to trigger some client side logic when the logging fails.

I'll submit a PR for the docs. If I did write a patch that enables installation exceptions to propagate up (optional, disabled by default), would that be something you'd consider including? Or would that kind of functionality go against NLog's philosophy somehow?

**Comment by 304NotModified** [comment]
> I'll submit a PR for the docs. If I did write a patch that enables installation exceptions to propagate up (optional, disabled by default), would that be something you'd consider including?

If it's backwards-compatible, i would be happy to include it! E.g. make it optional and disable by default.

**Comment by rbarillec** [comment]
OK, I've opened a pull request for the change to the documentation here:

https://github.com/rbarillec/nlog-wiki/pull/1

Interestingly, GitHub wouldn't allow me to submit a change to your wiki repo directly, so I worked off a fork. Let me know if for any reason you can't access the pull request.

**Comment by 304NotModified** [comment]
Looks good!

Can't merge it :(  wiki and github is always s bit strange. We use a wiki-strategy for the wiki: just edit it as we can always revert it :)

**Comment by rbarillec** [comment]
OK, I'll update the wiki then. Feel free to edit further as you see fit! :)

**Comment by 304NotModified** [comment]
:+1:

**Comment by 304NotModified** [comment]
Looks good to me!

**Comment by 304NotModified** [comment]
fixed in https://github.com/NLog/NLog/pull/2214

Thanks again!
