### ISSUE TITLE
Apply [Target(...)] attribute globally

### ISSUE THREAD

**Issue by arc95** [NLog/NLog#2209]
**Type**:

- Question

**NLog version**: 4.4.11

**Platform**: .Net 4.5.2

**Current NLog config** (xml or C#, if relevant)

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="true"
      internalLogLevel="Trace" internalLogFile="c:\temp\nlog-internal.log">
  <targets>
    <target name="target1" xsi:type="Elmah" LogLevelAsType="false" />
    <target xsi:type="AsyncWrapper" name="asyncDatabase">
      <target xsi:type="Database" name="asyncDatabase"
              keepConnection="true" dbProvider="System.Data.SqlClient"
              connectionStringName="NLogDb"
              commandText="insert into dbo.Log (Application, Logged, Level, Message, Username, ServerName, Port, Url, Https, ServerAddress, RemoteAddress, Logger, CallSite, Exception) values (@Application, @Logged, @Level, @Message, @Username, @ServerName, @Port, @Url, @Https, @ServerAddress, @RemoteAddress, @Logger, @Callsite, @Exception);"
            >
        <parameter name="@application" layout="SomeApp" />
        <parameter name="@logged" layout="${date}" />
        <parameter name="@level" layout="${level}" />
        <parameter name="@message" layout="${message}" />
        <parameter name="@username" layout="${identity}" />
        <parameter name="@serverName" layout="${aspnet-request:serverVariable=SERVER_NAME}" />
        <parameter name="@port" layout="${aspnet-request:serverVariable=SERVER_PORT}" />
        <parameter name="@url" layout="${aspnet-request:serverVariable=HTTP_URL}" />
        <parameter name="@https" layout="${when:inner=1:when='${aspnet-request:serverVariable=HTTPS}' == 'on'}${when:inner=0:when='${aspnet-request:serverVariable=HTTPS}' != 'on'}" />
        <parameter name="@serverAddress" layout="${aspnet-request:serverVariable=LOCAL_ADDR}" />
        <parameter name="@remoteAddress" layout="${aspnet-request:serverVariable=REMOTE_ADDR}:${aspnet-request:serverVariable=REMOTE_PORT}" />

        <parameter name="@logger" layout="${logger}" />
        <parameter name="@callSite" layout="${callsite}" />
        <parameter name="@exception" layout="${exception:tostring}" />

        <dbProvider>sqlserver</dbProvider>
      </target>
    </target>
  </targets>
  <rules>
    <logger name="*" minlevel="Info" writeTo="target1" />
    <logger name="*" minlevel="Trace" writeTo="asyncDatabase" />
  </rules>
</nlog>
```

Hi. Is it possible to apply an NLog target attribute globally to all controllers in an ASP.NET MVC 5 application? For example, the `RegisterGlobalFilters()` method in `FilterConig` class allows attributes to be added globally:

```c#
public static void RegisterGlobalFilters(GlobalFilterCollection filters)
{
	filters.Add(new HandleErrorAttribute());
}
```
Can the above add a new [NLog.Elmah](https://github.com/NLog/NLog.Elmah) attribute globally? It's used by applying the `[Target("Elmah")]` to a controller class.

**Comment by UgurAldanmaz** [comment]
What do you want to do exactly by applying target attribute? Do you want to do something like AOP for logging abilities?

**Comment by arc95** [comment]
@UgurAldanmaz Here's what's going on: A colleague wrote a bunch of NLog logging calls throughout the MVC app. I'm implementing Elmah.MVC to catch all uncaught exceptions. I'd also like to put all the NLog records into Elmah going forward, so we have one place to see all logging information. In other words, automatically send all NLog logging to Elmah as well. 

I can achieve this using a base controller and applying the `[Target("Elmah")]` to it, then having all my controllers inherit from it. Was wondering if there's another way to do this. If not, it's not a big deal. Don't want you guys spending time trying to solve some edge case that most people won't need.

**Comment by 304NotModified** [comment]
I think you're confused, or at least I am ;)

The `TargetAttribute` is an attribute to add to a target, e.g. the filetarget, databasetarget. It's used to add the targets dynamically to NLog. You could also use it for a custom target.

The TargetAttribute is not used to route logging. That unhanded exceptions are logged, is a ELMAH trick AFAIK. 


> I can achieve this using a base controller and applying the [Target("Elmah")]

That's not true. This is marking your controller as custom target. As you don't registering your target, this won't do anything.

**Comment by arc95** [comment]
Thanks, @304NotModified. That helped clear up my confusion!
