### ISSUE TITLE
Request for compilation NLog in .NET Framework 4.5.1

### ISSUE THREAD

**Issue by Szymod** [NLog/NLog#2210]
**Type**: FEATURE REQUEST
**NLog version**: 4.2.0
**Platform**: .Net 4.5.1 

Hello,

We run into problem with logging to databese using NLog compiled in .NET 4.5 and Npgsql compiled in .NET 4.5.1.  Do you ever considered publishing on nuget NLog compiled in .NET 4.5.1? It would be much easier for us, because now we have to downgrading .NET version of Npgsql to 4.5 to make it work.

**Comment by 304NotModified** [comment]
Why is this needed? You could use 4.5 libraries in 4.5.1?

Currently there are no plans for a separate 4.5.2 or 4.6.* DLL as we don't need anything from those versions.

**Comment by Szymod** [comment]
Yes we can, and we're using 4.5 NLog libraries in our 4.5.1 project. But this is not a problem. The problem is that we also use Npgsql in 4.5.1 and we want NLog to use it to log errors in our database.  It's a pity that you don't plan publishing NLog in higher framework. Thank you for your answer.

**Comment by 304NotModified** [comment]
I don't get it. 

> The problem is that we also use Npgsql in 4.5.1 and we want NLog to use it to log errors in our database.

This is still possible?

If your project is 4.5.1, you could use NLog *and* Npgsql in 4.5.1?

**Comment by 304NotModified** [comment]
> It's a pity that you don't plan publishing NLog in higher framework.

it's not planned as it won't add things. You can use NLog in .NET 3.5+, including  4.5, 4.5.1, 4.5.2, 4.6.0 etc
