### ISSUE TITLE
AppSetting Layout Renderer

### ISSUE THREAD

**Issue by bennaniadnan** [NLog/NLog#2211]
**NLog Version**: 4.4.11
**target Framework**: .Net 4.5.1

**Hello**

I'm trying To log into database
    Everything goes well except for this parameter stays empty

```
<parameter name="@username" layout="${appsetting:name=userName}" />
```

**App.Config** --> 
```
</configuration>
        <appSettings>
		<add key="userName" value="user" />
	</appSettings>
	<connectionStrings>
		<add name="NLog" connectionString="Data Source=.\SQLEXPRESS;Initial Catalog=AuditTrace;Integrated Security=True" providerName="System.Data.SqlClient" />
	</connectionStrings>
</configuration>

```

## internal-nlog error is 
```
2017-07-12 18:31:16.7718 Error Parsing configuration from D:\TestNlog\BatchProcess\bin\Debug\NLog.config failed. Exception: NLog.NLogConfigurationException: Exception when parsing D:\TestNlog\BatchProcess\bin\Debug\NLog.config.  ---> NLog.NLogConfigurationException: Target file not found.
   at NLog.Config.XmlLoggingConfiguration.ParseLoggerElement(NLogXmlElement loggerElement, IList`1 rulesCollection)
   at NLog.Config.XmlLoggingConfiguration.ParseRulesElement(NLogXmlElement rulesElement, IList`1 rulesCollection)
   at NLog.Config.XmlLoggingConfiguration.ParseNLogElement(NLogXmlElement nlogElement, String filePath, Boolean autoReloadDefault)
   at NLog.Config.XmlLoggingConfiguration.ParseTopLevel(NLogXmlElement content, String filePath, Boolean autoReloadDefault)
   at NLog.Config.XmlLoggingConfiguration.Initialize(XmlReader reader, String fileName, Boolean ignoreErrors)
   --- End of inner exception stack trace ---
```

**Comment by 304NotModified** [comment]
The error says "Target file not found."?

**Comment by bennaniadnan** [comment]
NLog.NLogConfigurationException: Target file not found.
I think the Target here is the App.config

**Comment by 304NotModified** [comment]
Please post the full NLog config.

**Comment by bennaniadnan** [comment]
````
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="false"
      internalLogLevel="Error" internalLogFile="D:\nlog-internal.log">


	<targets>
		<target name="database" xsi:type="Database">

			<connectionStringName>NLog</connectionStringName>

		
			<commandText>
				insert into dbo.NLogDb (
				Logged, Level, Message,
				Username,
				Logger, CallSite, Exception, ExceptionType, InnerException, StackTrace
				) values (
				@Logged, @Level, @Message,
				@Username,
				@Logger, @Callsite, @Exception, @ExceptionType, @InnerException, @StackTrace
				);
			</commandText>

			<parameter name="@logged" layout="${date}" />
			<parameter name="@level" layout="${level}" />
			<parameter name="@message" layout="${message}" />

			<parameter name="@username" layout="${appsetting:name=userName}" />

			<parameter name="@logger" layout="${logger}" />
			<parameter name="@callSite" layout="${callsite}" />
			<parameter name="@exception" layout="${exception:tostring}" />
			<parameter name="@ExceptionType" layout="${exception:format=type}" />
			<parameter name="@InnerException"
			  layout="${exception:format=:innerFormat=ShortType,Message,Method:MaxInnerExceptionLevel=1:InnerExceptionSeparator=}" />
			<parameter name="@StackTrace" layout="${exception:format=StackTrace}" />

		</target>
		
	</targets>

	<rules>
		<logger name="databaseLogger" levels ="Error,Debug,Warn,Trace" writeTo="database" />
	</rules>
</nlog>`

**Comment by bennaniadnan** [comment]
**## InternalLogFile**

> 2017-07-13 14:40:29.8636 Error Error parsing layout appsetting will be ignored. Exception: System.ArgumentException: LayoutRenderer cannot be found: 'appsetting'
>    at NLog.Config.Factory`2.CreateInstance(String name)
>    at NLog.Layouts.LayoutParser.ParseLayoutRenderer(ConfigurationItemFactory configurationItemFactory, SimpleStringReader sr)
> 2017-07-13 14:40:29.9106 Error Parsing configuration from C:\Users\bennani\Desktop\ConsoleApplication1\ConsoleApplication1\bin\Debug\NLog.config failed. Exception: NLog.NLogConfigurationException: Exception when parsing C:\Users\bennani\Desktop\ConsoleApplication1\ConsoleApplication1\bin\Debug\NLog.config.  ---> NLog.NLogConfigurationException: Target file not found.
>    at NLog.Config.XmlLoggingConfiguration.ParseLoggerElement(NLogXmlElement loggerElement, IList`1 rulesCollection)
>    at NLog.Config.XmlLoggingConfiguration.ParseRulesElement(NLogXmlElement rulesElement, IList`1 rulesCollection)
>    at NLog.Config.XmlLoggingConfiguration.ParseNLogElement(NLogXmlElement nlogElement, String filePath, Boolean autoReloadDefault)
>    at NLog.Config.XmlLoggingConfiguration.ParseTopLevel(NLogXmlElement content, String filePath, Boolean autoReloadDefault)
>    at NLog.Config.XmlLoggingConfiguration.Initialize(XmlReader reader, String fileName, Boolean ignoreErrors)
>    --- End of inner exception stack trace ---

**Comment by 304NotModified** [comment]
Have you installed NLog.Extended? 

see 
![image](https://user-images.githubusercontent.com/5808377/28177224-67d01b3e-67fa-11e7-8d97-b046a71e3839.png)
https://github.com/NLog/NLog/wiki/Layout-Renderers

Just install the package, or drop the nuget.extended dll in your bin folder (hot patching works after config reload), no config needed

**Comment by bennaniadnan** [comment]
i installed the package it's working thank you

**Comment by 304NotModified** [comment]
:+1:
