### ISSUE TITLE
How to read Object in nlog Layouts

### ISSUE THREAD

**Issue by rams300** [NLog/NLog#2216]
I wanted to maintain some common class for logging related information like as below.
```c#
 public class LogObject
    {
        public string AppName { get; set; }
        public string StackTrace { get; set; }
        public string Message { get; set; }
        public string JobNumber { get; set; }
        public string TransactionType { get; set; }
    }
```

Adding entire log object in API, like as below.

     logMgr.Info<LogObject>(logObject);

now i need to print those information into log like as below.
```xml
 <layout xsi:type="SimpleLayout"
               text="AppName-- ${logObject.AppName}
                     Message-- ${logObject.Message}"
              >
      </layout>
```
But above layout render is not working, i am unable to read the object like logObject.Message.
i know other way is adding individual properties into variable and events, i am more looking addding entire object into log and reading in layout.

**Comment by snakefoot** [comment]
Maybe you can to do something like this:

`nLogger.Info("{0}", logObject);`

Then register a custom layoutrenderer for each LogObject-property:

```
NLog.LayoutRenderers.LayoutRenderer.Register("logObject-AppName", (logEvent) =>
{
    if (logEvent.Parameters?.Count == 1)
    {
        LogObject logObject = logEvent.Parameters[0] as LogObject;
        if (logObject != null)
              return logObject.AppName;
    }
    return string.Empty;
}
```

Then your layout can look like this:

```
 <layout xsi:type="SimpleLayout"
               text="AppName-- ${logObject-AppName}
                     Message-- ${logObject-Message}"
              >
 </layout>
```

**Comment by rams300** [comment]
Thanks Snakefoot for quick response and providing the solutions.
I am new to Nlog,  i  am looking for is there any possibility of accessing object members directly in Layout without writing custom code.

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, let us know!

**Comment by snakefoot** [comment]
NLog 4.6.3 introduces `objectpath=` as option, so you can specify `${event-properties:item=logObject:objectpath=AppName}`. See also #3329
