### ISSUE TITLE
Nlog PublicToken not present in AndroidMono dll 

### ISSUE THREAD

**Issue by samvdd** [NLog/NLog#2217]
Hi,

I just have a quick note on the NLog Nuget Package, The dll for MonoAndroid doesn't have it's PublicToken. This gives problems if you have packages that are depending on NLOG.
As you can see in the image "errornlog" we have 2 projects that include NLOG but one has a PublicToken and the other doesn't.
![errornlog](https://user-images.githubusercontent.com/29921940/28371568-a42ebb74-6c9d-11e7-85ff-6415d809f25d.png)

In the second project we get the error that we need to add a reference to Nlog but there is a reference to the one without the PublicToken. (see errornlog2)
![errornlog2](https://user-images.githubusercontent.com/29921940/28371751-18a80d66-6c9e-11e7-9186-91910d7e7bed.png)

This is also for the latest 4.4.11

**Comment by 304NotModified** [comment]
Could you help us in fixing this?

I had troubles enabling it

**Comment by 304NotModified** [comment]
fixed in 4.5!

![image](https://user-images.githubusercontent.com/5808377/31357369-b387e3d6-ad41-11e7-895c-c03d8ff5894d.png)

All platforms are now strong named.
