### ISSUE TITLE
Nlog release 5 RTM

### ISSUE THREAD

**Issue by Anamika1911** [NLog/NLog#2218]
Hi! Thanks for reporting this feature/bug/question! 
Type: Question
Platform: .net core
support for .net core is in beta version at the moment. When are you planning to do a release for it?

thanks,
Anamika Aggarwal
Please keep / fill in the relevant info from this template so that we can help you as best as possible.

For .NET Core users, please check the platform support: https://github.com/NLog/NLog/wiki/platform-support

**Type** (choose one):

- Bug
- Feature request
- Question

**NLog version**: (e.g. 4.2.3)

**Platform**: .Net 3.5 / .Net 4.0 / .Net 4.5 / Mono 4 / Silverlight 4 / Silverlight 5 / Xamarin Android / Xamarin iOs / .NET Core 

**Current NLog config** (xml or C#, if relevant)

```xml
<nlog>
  <targets>
  </targets>
  <rules>
  </rules>
</nlog>

```

In case of a BUG:

- What is the current result?
- What is the expected result?
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
- Please post full exception details (message, stacktrace, inner exceptions)
- Are there any work arrounds? yes/no
- Is there a version in which it did worked? 
- Can you help us by writing an unit test?

in case of a FEATURE REQUEST:
 
 - Why do we need it?
 - An example of the XML config, if relevant.

**Comment by 304NotModified** [comment]
The is no release date yet.

**Comment by Anamika1911** [comment]
Is beta version stable enough to use in production?

**Comment by snakefoot** [comment]
> Is beta version stable enough to use in production?

Yes, but make sure you don't depend on things not supported for NetStandard:

https://github.com/NLog/NLog/wiki/Platform-Support

**Comment by Anamika1911** [comment]
Thanks for quick reply Rolf.

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, let us know!
