### ISSUE TITLE
Feature Request: source code line number as first class Layout Renderer variable

### ISSUE THREAD

**Issue by beatgates** [NLog/NLog#222]
Escalate from my comment in #128. Please add a Layout Renderer ${srcline} to refer to the source code line where the logging takes place.

I believe this is a very basic and helpful function in logging and debuging that most log4x framework has. So it deserves a first class variable rather than unintuitive ${callsite:lineno}.

I've been using log4j, log4net for a long time but new to NLog. So please correct me if I missed out and this feature does exist. Thanks.

**Comment by 304NotModified** [comment]
PR merged
