### ISSUE TITLE
unoptimized stackTrace management: ${onexception:inner=${callsite}}

### ISSUE THREAD

**Issue by edi1980** [NLog/NLog#2225]
**Type** (choose one): BUG
**NLog version**: 4.4.11
**Platform**:  .Net 4.5 
**Current NLog config** (xml or C#, if relevant)
                Layout = @"${Level} ${message} ${onexception:inner=${callsite}}"

- What is the current result?
inner Render of "onexception" is "used" also if no exception is present, and it affect the logging performance

- What is the expected result?
I expect that innerRender of ${onexception} is used only when a exception is present.

- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
yes, but it did not give me any help (too less log also in Trace mode)

- Please post full exception details (message, stacktrace, inner exceptions)
no exception raised, the problem is affecting performance

- Are there any work arrounds?
no

- Is there a version in which it did worked? 
not tried previous versions

- I've already found the problem, because I've debug the Nlog sources:
the real problem it is not depending only by the ${onexception} wrapper 
but also by the ${callsite} set as innerLayout, and its "IUsesStackTrace" derivation

In LoggerImpl.cs, line 68 (internal static void Write...) 
there is a check to create/get/attach the stackTrace to the LogEvent if one of the targets needs to have it, if yes (and this is the case with the usage of ${callsite}) the stackTrace is retrieved, and this operation consume time.
The condition has to be adjusted, to take in account if the stackTrace is really needed.

The most fast way it is to move the logic to get the stackTrace inside the LogEvent.StackTrace:
in the get has to be checked if a new private Logevent._stackTrace is = null, if it is null, then GetStackTrace (at that time the stack is really needed) and if it is already != null, just return _stackTrace
in the set...nothing, it has to be not settable property.
It is required also additional change to get correctly the UserStackFrame: add property loggerType to LogEvent (needed to for the method FindCallingMethodOnStackTrace)

**Comment by 304NotModified** [comment]
> In LoggerImpl.cs, line 68 (internal static void Write...)
> there is a check to create/get/attach the stackTrace to the LogEvent if one of the targets needs to have it, if yes (and this is the case with the usage of ${callsite}) the stackTrace is retrieved, and this operation consume time.
> The condition has to be adjusted, to take in account if the stackTrace is really needed.
> 
> The most fast way it is to move the logic to get the stackTrace inside the LogEvent.StackTrace:
> in the get has to be checked if a new private Logevent._stackTrace is = null, if it is null, then GetStackTrace (at that time the stack is really needed) and if it is already != null, just return _stackTrace
> in the set...nothing, it has to be not settable property.
> It is required also additional change to get correctly the UserStackFrame: add property loggerType to LogEvent (needed to for the method FindCallingMethodOnStackTrace)

could you do a PR for this? That would be easier to review :)

**Comment by snakefoot** [comment]
The NLog layout logic allows one to make very convoluted expression, where `${callsite}` is only relevant on certain conditions.

Trying to optimize for all possible combinations (and future combinations) will increase code-complexity a lot.

Many times a simple work-around is to have different targets with individual Layout, and use the filtering-logic to redirect to the target with `${callsite}` when needed.

**Comment by 304NotModified** [comment]
I like the idea, but this will be hard indeed to implemented. (but it's possible without breaking changes).

If this could be done without a lot of code, a PR would be accepted.

**Comment by snakefoot** [comment]
Closing as inactive. But PullRequest is ofcourse welcome
