### ISSUE TITLE
Load order (precedence) of config files is broken

### ISSUE THREAD

**Issue by mvarblow** [NLog/NLog#223]
More specific config files, e.g. program-name.exe.nlog, should be used before using nlog.config.  Commit #66bbed5242dca83fa8f24a6f72118d53e51674cd seems to have broken the precedence order for config file locations that was in place in NLog 2.0.0.  GetCandidateFileNames seems to return the paths in reverse priority order.  LogFactory used to use the _last_ candidate file that existed.  It now takes the _first_ candidate that exists.  The LogFactory change (to break on the first file that exists) makes sense.  It will perform better.  However, GetCandidateFileNames must also be changed to reverse the order.

**Comment by williamb1024** [comment]
I'd like to deal with this issue, based on the code the current list of candidate files is (in order of precedence):

* BaseDirectory\NLog.config
* AppDomain.ConfigurationFile (with extension changed to ".nlog")
* AppDomain.ConfigurationFile (with ".vshost." removed and extension changed to ".nlog")
* NLog.config in all AppDomain.PrivateBinPath directories
* NLog.dll.nlog in same folder as nlog.dll

I believe the updated order should be (again in order of precedence):
* AppDomain.ConfigurationFile (with extension changed to ".nlog")
 * This makes "application.vshost.exe.nlog" override "application.exe.config" if running in Visual Studio (with the Visual Studio Hosting Process). This allows for a separate configuration for debugging (or really just running in Visual Studio)
* AppDomain.ConfigurationFile (with ".vshost." remove and extensions changed to ".nlog")
* BaseDirectory\NLog.config
* NLog.config in all AppDomain.PrivateBinPath directories
* NLog.dll.nlog in same folder as nlog.dll

If there is general agreement about the priority of the configuration files, I'll make the required changes and make a pull request.

**Comment by mvarblow** [comment]
Are you forgetting AppDomain.ConfigurationFile with .config extension?

**Comment by williamb1024** [comment]
@mvarblow Yes, I didn't include the standard app.config. Didn't think about it because it's coming from somewhere else in the code. I've updated the list.

**Comment by mvarblow** [comment]
Perfect.  That looks right to me.

**Comment by 304NotModified** [comment]
Thanks. We have to discuss with @Xharze what the optimal order should be.

(ps the use of numbered lists instead of bullets is IMO easier to read)

**Comment by 304NotModified** [comment]
And I have to admit, this is a breaking change, but I don't see the real benefit of changing this.

**Comment by williamb1024** [comment]
I agree with you about it being a breaking change and also about the lack of benefit, but it was marked as a bug, so I'd assumed it was considered something that should have worked in the original manner. 

Anyway, if the decision is to change it, I'll be happy to do the work.

My markdown is rudimentary at best.

**Comment by mvarblow** [comment]
There was a breaking change a few releases ago.  The list above almost matches the documentation.  The current behavior does not.  I would welcome a fix that simply restores the documented behavior - which we count on - so that we can take the latest version of NLog.

https://github.com/nlog/nlog/wiki/Configuration-file#configuration-file-locations

**Comment by williamb1024** [comment]
Well, considering that it's documented as working in a specified way, I think that's a pretty good reason to fix it and eventually the documentation.

**Comment by 304NotModified** [comment]
It has the preference to fix the code and not the documention.

**Comment by 304NotModified** [comment]
PR is submitted, will be merged in 5.0
