### ISSUE TITLE
Old archive files are not deleted when a variable is used in the path

### ISSUE THREAD

**Issue by mrflowo** [NLog/NLog#2235]
**Type**: Bug

**NLog version**: 4.4.11

**Platform**:  .Net 4.5 ( 4.5.2 )

**Current NLog config**

```C#
LogManager.Configuration.Variables["LogPath"] = @"D:\NLog\";
```

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="false"
      internalLogLevel="Trace" internalLogFile="c:\temp\internal.log">
  <targets>
    <target
      archiveFileName="${var:LogPath}\Logs\Archiv\Demo.{#}.log"
      archiveEvery="Minute"
      archiveNumbering="Date"
      archiveDateFormat="mm-ss"
      enableFileDelete="true"
      maxArchiveFiles="2"
      keepFileOpen="true"
      openFileCacheTimeout="30"
      concurrentWrites="true"
      openFileCacheSize="1"
      fileName="${var:LogPath}\Logs\Demo.log"
      layout="${longdate} | ${threadid} | ${threadname} | ${logger} | ${level:uppercase=true} | ${message}"
      name="file"
      xsi:type="File"/>
  </targets>
  <rules>
    <logger minlevel="Trace" name="*" writeTo="file"/>
  </rules>
</nlog>
```

**What is the current result?**

```
NLog
    Logs
        Demo.log
        Archiv
            Demo.22-59.log
            Demo.23-59.log
            Demo.24-59.log
            Demo.25-59.log
            Demo.26-59.log
            Demo.27-59.log
            Demo.28-59.log

Logs
    Archiv
```

As you can see, NLog creates 2 folders. The NLog folder corresponds to the configuration. The current log file "Demo.log" is located in the subfolder "Logs". Archived files can be found in the "Archiv" subfolder of the "Logs" subfolder.

The Logs folder contains only one folder archive.

In the internal log file is several times to find the following line:

```
2017-08-02 09:36:00.6654 Debug Watching path 'D:\Logs\Archiv' filter 'Demo.*.log' for changes.
2017-08-02 09:36:00.6654 Debug Watching path 'D:\NLog\Logs' filter 'Demo.log' for changes.
```
Old archived log files are not deleted from the NLog Archiv folder.

Additional files:
[Internal Log File](https://github.com/NLog/NLog/files/1193091/internal.log.txt)
[My C# Testcode](https://github.com/NLog/NLog/files/1193097/NLog.Test.zip)

**What is the expected result?**

I am not quite sure if I have made a mistake in the configuration or whether this is a bug.
In principle, I am concerned that the old log files are properly deleted.

**Please post full exception details (message, stacktrace, inner exceptions)**
No exception.

**Are there any work arrounds?**
I can't work out what the issue is.

**Is there a version in which it did worked?**
I haven't had it work correctly before.

**Can you help us by writing an unit test?**
No.

**Comment by 304NotModified** [comment]
@snakefoot any idea if this is solved in 4.5?

**Comment by snakefoot** [comment]
@304NotModified Yes NLog 4.5 is able to remove files from the Archiv-folder.

@mrflowo Think the problem is that you have specified `archiveNumbering="Date"` but you have chosen a date-format that cannot be parsed as a date `archiveDateFormat="mm-ss"`

**Comment by mrflowo** [comment]
@snakefoot I've already tested it with different format variants ("yyyy-MM-dd", "yyyy-MM-dd\THH-mm", ...). There was no difference.

**Comment by 304NotModified** [comment]
@snakefoot I think we have to add some internal logging in 4.5 so users could debug this their self. https://github.com/NLog/NLog/pull/1872 was meant for that. 

Maybe we could add some logging and I can create a new alpha release.

**Comment by snakefoot** [comment]
@304NotModified Pretty sure no one wants to put an alpha version of Nlog 4.5 into production. Or do you want to create an NLog 4.4-release ?

**Comment by 304NotModified** [comment]
Valid point. 

Doubting to include it into 4.4.12. I think the impact is really low?

**Comment by snakefoot** [comment]
@mrflowo Can see that you have enabled `autoReload="true"`, but using variables. Maybe you just need to add `keepVariablesOnReload="true"` ?

**Comment by mrflowo** [comment]
Thanks a lot @snakefoot! With the option works the delete now. However, he still looks in the wrong folder (or is it only logged incorrectly?) "D:\Logs\Archiv". The folder is still created as well.

**Comment by mrflowo** [comment]
After updating to version 4.4.12, the problem with the additionally created folders is solved now.

**Comment by 304NotModified** [comment]
It sounds highly unlikely that the change of 4.4.12 was fixing your issue. See https://github.com/NLog/NLog/releases/tag/v4.4.12
