### ISSUE TITLE
NLog.Web.Aspnetcore and NLog.Extended can not use together

### ISSUE THREAD

**Issue by YaoNiGu** [NLog/NLog#2236]
**Type** (choose one):

- Bug

**NLog version**: (e.g. 4.2.3)

**Platform**: .Net 4.6.2

**Current NLog config** (xml or C#, if relevant)

<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      internalLogLevel="Warn"
      internalLogFile="c:\temp\internal.txt">

  <extensions>
    <add assembly="NLog.Web.AspNetCore"/>
  </extensions>

  <targets>
   <target xsi:type="MSMQ"
         name="otherFile"
         useXmlEncoding="true"
         layout="${longdate}|${aspnet-User-Identity}|${aspnet-Request-IP}|${aspnet-Request-Host}|${aspnet-SessionId}|${guid}|ParentToken|${level}|${aspnet-Request-Url}|${aspnet-Request-QueryString}|${message}|${exception}"      
         queue=".\private$\logqueue" />    
    <target xsi:type="Null" name="blackhole" />
  </targets>

```

In case of a BUG:

I am currently using the asp.net core mvc environment, so i used the NLog.Web.Aspnetcore package and I read the system files and learned that to use MSMQ, I need to reference the package NLog.Extended, but it seems that there will be a version error The problem that caused the normal use, which was previously used in NLog.Web will not encounter the problem.
The following is an error message:

2017-08-02 16:45:43.1170 Error Error has been raised. Exception: System.IO.FileLoadException: 無法載入檔案或組件 'NLog.Extended, Version=5.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c' 或其相依性的其中之一。 找到的組件資訊清單定義與組件參考不符。 (發生例外狀況於 HRESULT: 0x80131040)
檔案名稱: 'NLog.Extended, Version=5.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c'
   於 System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type)
   於 System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName)
   於 System.RuntimeType.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark)
   於 System.Type.GetType(String typeName, Boolean throwOnError)
   於 NLog.Config.Factory`2.<>c__DisplayClass6_0.<RegisterNamedType>b__0()
   於 NLog.Config.Factory`2.TryGetDefinition(String itemName, Type& result)


How can i try to solve this problem?

**Comment by 304NotModified** [comment]
Please post your config. I think it should work with a `<extension>`

**Comment by snakefoot** [comment]
@YaoNiGu Try and upgrade to NLog 5 BETA09

**Comment by YaoNiGu** [comment]
@304NotModified 
This is my config.
Did I forget add thing?
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      internalLogLevel="Warn"
      internalLogFile="c:\temp\internal.txt">
  

  <extensions>
    <add assembly="NLog.Web.AspNetCore"/>

  </extensions>

  <targets>
    <target xsi:type="MSMQ"
            name="otherFile"
            useXmlEncoding="true"
            layout="${longdate}|${message}|${exception}"
            queue=".\private$\logqueue" /> 
  </targets>

**Comment by YaoNiGu** [comment]
@snakefoot I already used NLog 5 BETA09 , but it still not work

**Comment by YaoNiGu** [comment]
@304NotModified 
After I add `<add` assembly="NLog.Extended"/> in `<extensions>`, it works now!
But why should I have to add this assembly in extensions?
Before I use NLog.Web.AspNetCore, I was using NLog.Web. And I did not have to add this assembly in it.
What's the difference between theese two?
Thanks! I'm so appreciated!

**Comment by 304NotModified** [comment]
> After I add <add assembly="NLog.Extended"/> in <extensions>, it works now!

In .NET Core not all the dlls are in the same folder, hence NLog can't find them automatically. We still have to fix this.

**Comment by snakefoot** [comment]
@304NotModified Maybe there should be some forced auto-loading of some the "commonly known" DLLs ?

**Comment by 304NotModified** [comment]
Good idea. 

There is also an api to query the installed nuget packages AFAIK.
