### ISSUE TITLE
Capturing application termination & exit code in log

### ISSUE THREAD

**Issue by j-maly** [NLog/NLog#2239]
Hi, 
I'd like to log program termination, e.g., when main method finishes or when someone calls `Environment.Exit(10)`

I'd like to capture and write the exit code to log file too. 
I tried: 

```c#
        Logger logger; 
        static FloggerFactory()
        {
            logger = ...
            AppDomain.CurrentDomain.ProcessExit += CurrentDomainOnProcessExit;
        }

        private static void CurrentDomainOnProcessExit(object sender, EventArgs eventArgs)
        {
            logger.Fatal(" ==== Exiting ===== ");
            LogManager.Flush();
        }
```

Now the code is executed (I can put a breakpoint there and it is hit), but the line never appears in the log file. What am I doing wrong?

**Comment by 304NotModified** [comment]
Your code looks good, please capture the internal log and post it here (trace level)

**Comment by j-maly** [comment]
I added 
<nlog internalLogFile="c:\log.txt" internalLogLevel="Trace">
but after running my program, there is no file c:\log.txt
Not sure whether this means everything was ok and thus no file was created or there is something wrong with my config.

**Comment by 304NotModified** [comment]
That could be file system permissions? Please try to log into c:\temp

**Comment by j-maly** [comment]
Attached
[log.txt](https://github.com/NLog/NLog/files/1200554/log.txt)

**Comment by 304NotModified** [comment]
have you seen this warning?

```
2017-08-04 15:47:13.4166 Warn Exception in layout renderer: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: Process must exit before requested information can be determined.
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_ExitCode()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at NLog.LayoutRenderers.ProcessInfoLayoutRenderer.Append(StringBuilder builder, LogEventInfo logEvent)
   at NLog.LayoutRenderers.LayoutRenderer.Render(StringBuilder builder, LogEventInfo logEvent)
```

I think what you're trying won't work. 

Please post your nlog.config (inline)

**Comment by j-maly** [comment]
I think this error comes from ${processinfo:property=ExitCode} which I also tried, but it is skipped silently (and there is no exit code on the loglines). 
But I think it is not related to the fact that logger.Fatal(" ==== Exiting ===== "); doesn't make it to the file. 

Could it be something like the file handle is already closed when logger is called in CurrentDomainOnProcessExit method?


```
<nlog internalLogFile="c:\temp\log.txt" internalLogLevel="Trace" internalLogToConsole="true" internalLogToTrace="true">
	<variable name="logDirectory" value="C:\temp\LogFiles" />
	<variable name="filename" value="${processname}_${processid}.Nlog.log" />
	<variable name="filenameArchive" value="${processname}_${processid}.NLog_${date:format=yyyyMMdd_HHmmss:cashed=true}.log" />
	<variable name="flogLayout" value="${date:format=dd MMMM yyyy HH\:mm\:ss.fff}: ${level} : [${threadid}] : ${logger}: ${message} ${processinfo:property=ExitCode} ${processinfo:property=StartTime}" />
	<targets async="true">
		<target name="StandardLog" type="File" maxArchiveFiles="100" archiveNumbering="Sequence" archiveAboveSize="10485760" archiveFileName="${logDirectory}\${filenameArchive}" fileName="${logDirectory}\${filename}" layout="${flogLayout}" />
		<target name="ErrorLog" type="File" fileName="error.${logDirectory}\${filename}" layout="${flogLayout}" />
	</targets>
	<rules>
		<logger name="*" minlevel="Info" maxlevel="Fatal" writeTo="StandardLog" />
		<logger name="*" levels="Error,Fatal" writeTo="StandardLog,ErrorLog" />
	</rules>
</nlog>
```

**Comment by 304NotModified** [comment]
Have to check, but that could be the reason indeed. I see also closing the file handle in the internal log

**Comment by snakefoot** [comment]
@j-maly Pretty sure that you cannot capture the exit-code or your own running process  (Reason for the error: `Process must exit before requested information can be determined`).

About the missing `==== Exiting =====`. Have you made sure not to call any NLog-code (be aware of static NLog-Logger-objects), before you register your own delegate for ProcessExit ? (See also  #2219)

**Comment by j-maly** [comment]
This code calls Environment.Exit(2) and prints 
"Process exited: 2"
in the command line. 
So you can read and print the current exit code before the process terminates.  
About the second part - I'll try that next week. 
`
        static void Main(string[] args)
        {
            AppDomain.CurrentDomain.ProcessExit += CurrentDomain_ProcessExit;
            Environment.Exit(2);
        }

        private static void CurrentDomain_ProcessExit(object sender, EventArgs e)
        {
            System.Console.WriteLine("Process exited: " + Environment.ExitCode);
        }
`

**Comment by snakefoot** [comment]
@j-maly Excellent then instead of using processinfo, then just register a custom layout-renderer with Environment.ExitCode:

https://github.com/NLog/NLog/wiki/How-to-write-a-custom-layout-renderer

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, let us know!
