### ISSUE TITLE
Access to log - Error file is in use

### ISSUE THREAD

**Issue by ws7m** [NLog/NLog#2240]
**Type**: Question

**NLog version**: 4.4.9

**Platform**: .Net 4.0

Question:

Logging is working nicely.  We are using AsyncWrapper on our targets.  Our app is multi-threaded with a client and server.

When we encounter an error we would like to grab a copy of the logs, zip them, attach them to a notification we send out.   At times we get a "file is in use" error trying to make a zip of the log file probably because something else in another thread is causing a write.

Is there a way to get a copy of a log file "through" NLog which would avoid this?  Is there some other way to prevent NLog temporarily from writing to the log during the exact time we are trying to zip the file?  We have tried flushing NLog trying to get it to empty it's queue before writing but still see the error at times.

As an alternative is there a way to force NLog at the time we are trying to get a copy of the log to start a new log file so we can send the prior one?

Any help would be appreciated.

**Comment by ws7m** [comment]
Sorry I didn't know how to turn on the question label.

**Comment by snakefoot** [comment]
@ws7m Usually never have any issues with reading files that are currently being written to by NLog. But I'm also using `KeepFileOpen=true`.

Can you show us the NLog-config for the file-target?
Is the log-file place on a local-folder or network-share?
What operating system are you running?
What application are you using for compression?
Are you running any anti-virus software?
Are you running any tail-applications that monitors the log-file?
Does the error also occur when taking a raw copy of the log-file, and comprressing afterwards?

**Comment by ws7m** [comment]
Hi snakefoot,

I will post the config.
The nlog files are local C: drive
Windows 10
We are using gzip compression as part of the C# IO libraries
No AV software
No tail operations.  Once in a great while we will have BareTail pro looking at a file but we see the error without it.
Honestly we have not tried.  As we try to resolve the errors we are first looking at NLog, next we will try some changes to what we are doing.

The config:

<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="false"
      internalLogLevel="Off" internalLogFile="c:\PropelAutomation\InternalLogs\nlog-internal.log">

      

  

  
  <variable name="InternalLogOutputDir" value="c:\PropelAutomation\InternalLogs"/>

  
  <variable name="InternalLogFileName" value="${InternalLogOutputDir}/AutomationInternal-${machinename}-${shortdate}"/>


  <variable name="InternalLogPrefixFmt" value="${longdate:universalTime=false}|${counter}|${level}|"/>

  
  <variable name="InternalLogFmt" value="${InternalLogPrefixFmt}${message}"/>
  
  
  
  
  <variable name="SystemLogOutputDir" value="c:\PropelAutomation\SystemLogs"/>
  
  
  
  <variable name="SystemLogFileName" value="${SystemLogOutputDir}/AutomationSystem-${machinename}-${shortdate}"/>
  
  
  <variable name="SystemLogPrefixFmt" value="${longdate:universalTime=false}|"/>

  
  <variable name="SystemLogFmt" value="${SystemLogPrefixFmt}${message}"/>

  
  <targets>
    <default-wrapper xsi:type="AsyncWrapper" queueLimit="20000" overflowAction="Grow"/>
      <target name="SystemLogFile" xsi:type="File"
            fileName="${SystemLogFileName}.log"
            layout="${SystemLogFmt}"
            archiveEvery="None"/>
      <target name="InternalLogFile" xsi:type="File"
            fileName="${InternalLogFileName}.log"
            layout="${InternalLogFmt}"
            archiveEvery="Day"/>
  </targets>

  
  <rules>
    <logger name="InternalLogger" writeTo="InternalLogFile" />
    <logger name="SystemLogger" writeTo="SystemLogFile" />
  </rules>
  
</nlog>

**Comment by snakefoot** [comment]
Since you are using `KeepFileOpen="false"` (For some reason). Then you can just do the compression like this:

- Rename/Move file to new location (Maybe with a retry-loop)
- Sleep for 1 sec (Just to make sure everything has cooled down)
- Perform the compression

NLog will automatically create a new file on the next log-operation.

**Comment by ws7m** [comment]
Well I can certainly try keepfileopen=true.  That is easy.  I'll post back what result I have.

Thanks by the way for your attention!

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, let us know!
