### ISSUE TITLE
whenRepeated Filter - Status?

### ISSUE THREAD

**Issue by somnatic** [NLog/NLog#2246]
**Type** (choose one): Question

**NLog version**: 4.5+

**Platform**: .Net 4.5 

Hi

Your Wiki states that starting with 4.5 there should be a filter called WhenRepeated: https://github.com/NLog/NLog/wiki/WhenRepeated-Filter

I tried the Nuget packages for 4.5.n (all being in Alpha state) and for 5.0 (Beta) but it doesn't appear to be available. Has this filter been decommissioned?

**Comment by 304NotModified** [comment]
It will be in the beta of 4.5. I will try to create the beta this weekend.

**Comment by somnatic** [comment]
That's great to hear! Thank you.
