### ISSUE TITLE
Database targets not working with .NET Core

### ISSUE THREAD

**Issue by SonOfMa** [NLog/NLog#2247]
Hi.

Are database targets working with .NET Standard 1.3 yet? The platform support page https://github.com/NLog/NLog/wiki/platform-support says that only config files are not supported, so I've tried to create my own database targets in C# to no avail - no errors thrown, just nothing being logged. All the example code belows works just fine when compiled with .NET 4.6 but not with .NET Core 2.0. I get no exceptions or error messages from NLog so its hard to know what's happening at the moment here - it's just not logging anything. Database and table is already created (and same example code works with .NET 4.6 as mentioned) The first example uses Microsoft console extensions:

```using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using System;
using NLog.Extensions.Logging;
using System.IO;
using NLog;
using NLog.Config;
using NLog.Targets;

namespace NLogConsolePoC_1
{
    class Program
    {
        static ILoggerFactory loggerFactory;
        static ILogger<Program> logger;

        static void Main(string[] args)
        {
            var serviceProvider = new ServiceCollection()
                .AddLogging()  // Extension metode fra Microsoft.Extensions.Logging.Console
                .BuildServiceProvider();

            loggerFactory = serviceProvider.GetService<ILoggerFactory>();

            loggerFactory.AddNLog();    // Extension metode fra NLog.Extensions.Logging

            var dbLogTarget = new DatabaseTarget
            {
                Name = "example",
                DBProvider = "mssql",
                DBHost = "localhost",
                DBDatabase = "log",
                DBUserName = "user",
                DBPassword = "password",
                CommandText = "insert into LogTable(message) values(@message);"
            };

            dbLogTarget.Parameters.Add(new DatabaseParameterInfo
            {
                Name = "@message",
                Layout = "${message}"
            });

            var config = new LoggingConfiguration();
            config.AddTarget(dbLogTarget.Name, dbLogTarget);
            config.LoggingRules.Add(new LoggingRule("*", NLog.LogLevel.Debug, dbLogTarget));
            loggerFactory.ConfigureNLog(config);

            logger = serviceProvider.GetService<ILoggerFactory>()
                .CreateLogger<Program>();

            logger.LogInformation("info log message");
            logger.LogDebug("debug log message");
        }
    }
}
```

My second example uses simple configuration:

```
using NLog;
using NLog.Config;
using NLog.Targets;

namespace NLogConsolePoC_2
{
    class Program
    {
        static void Main(string[] args)
        {
            var dbLogTarget = new DatabaseTarget
            {
                Name = "example",
                DBProvider = "mssql",
                DBHost = "localhost",
                DBDatabase = "log",
                DBUserName = "user",
                DBPassword = "password",
                CommandText = "insert into LogTable(message) values(@message);"
            };

            dbLogTarget.Parameters.Add(new DatabaseParameterInfo
            {
                Name = "@message",
                Layout = "${message}"
            });

            SimpleConfigurator.ConfigureForTargetLogging(dbLogTarget, NLog.LogLevel.Info);

            Logger logger = LogManager.GetLogger("Example");
            logger.Info("log info");
            logger.Debug("log debug");
        }
    }
}
```
**Type** (choose one):

- Bug

**NLog version**: (e.g. 4.2.3)
NLog 5.0.0-beta09
NLog.Extension-Logging 1.0.0-rtm-beta5

**Platform**: 
.NET Core 2.0 (successfully tested with 4.6)

**Current NLog config** (xml or C#, if relevant)

Not relevant as NLog for .NET Standard 1.3 does not support .config files, see https://github.com/NLog/NLog/wiki/platform-support

In case of a BUG:

- What is the current result?
No logging in MSSQL database,

- What is the expected result?
Logging in database.

- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?

N/A 

- Please post full exception details (message, stacktrace, inner exceptions)

No errors

- Are there any work arrounds? yes/no

works with .NET 4.6, but not an option inn my case.

- Is there a version in which it did worked? 

.NET 4.6

- Can you help us by writing an unit test?

See examples provided above

**Comment by snakefoot** [comment]
To diagnose the problems with writing to database, then activate and check the NLog-InternalLogger. Maybe you need the following package-reference for the mssql-database:

`<PackageReference Include="System.Data.SqlClient" Version="4.3.1" />`

**Comment by SonOfMa** [comment]
Adding internal logging `InternalLogger.LogToConsole = true;` to NLog yielded no further errors. Adding a Nuget package reference fixed the error. Thank you.

**Comment by 304NotModified** [comment]
Thanks for the feedback!

Thanks @snakefoot !
