### ISSUE TITLE
Newline in exception formatt

### ISSUE THREAD

**Issue by rhegner** [NLog/NLog#2248]
**Type**:
Question

**NLog version**:
NLog.Web.AspNetCore: 4.4.1

**Platform**:
.NET Core 

**Current NLog config**:

```xml
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      internalLogLevel="Warn"
      internalLogFile="../Logs/internal-nlog.txt">

  <!-- define various log targets -->
  <targets>
    <!-- write logs to file -->
    <target xsi:type="File" name="allfile" fileName="../Logs/nlog-${shortdate}.log"
                layout="${longdate}|${event-properties:item=EventId.Id}|${logger}|${uppercase:${level}}|${message} ${exception:format=tostring,data:maxInnerExceptionLevel=10}" />

    <target xsi:type="ColoredConsole" name="console" />
  </targets>

  <rules>
    <logger name="*" minlevel="Debug" writeTo="console" />
    <logger name="*" minlevel="Info" writeTo="allfile" />
  </rules>
</nlog>

```

**Question**:
The above config works fine. However I'd like the data of the exception be separated with a newline from the rest. I noticed that a newline-renderer exists, so I tried this but it doesn't work:
`${exception:format=tostring,data:maxInnerExceptionLevel=10:separator=${newline}}`
So what is the correct way to configure a newline as the separator?

**Comment by 304NotModified** [comment]
Not sure why `${newline}` won't work,
this should work:

     ${exception:format=tostring,data:maxInnerExceptionLevel=10:separator=\r\n}

**Comment by rhegner** [comment]
Yes it does! Thank you for your quick response!

Now the only not so nice thing is that the separator is inserted unconditionally. So if no data is available I get an empty line in my log. IMO the separator should only be inserted for fields that exist. But I can live with the current behavior.

**Comment by 304NotModified** [comment]
> Now the only not so nice thing is that the separator is inserted unconditionally. So if no data is available I get an empty line in my log.

true, could you make a separate issue in Github for this? And if you could, please create an unit test
