### ISSUE TITLE
${exception} - separator=${newline} won't work

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#2249]
Bug:

```
${exception:format=tostring,data:maxInnerExceptionLevel=10:separator=${newline}} 
```

wont work

but this works:

```
${exception:format=tostring,data:maxInnerExceptionLevel=10:separator=\r\n}
```

See https://github.com/NLog/NLog/issues/2248

**Comment by jojosardez** [comment]
Hi 304,
I am able to replicate it. I believe I have fixed it locally. Can I commit it to my fork and raise a pull request?

**Comment by 304NotModified** [comment]
Yes that would be great! Please also include an unit test, thanks!

**Comment by jojosardez** [comment]
OK. I'll refine it first and will let you know once its ready.

**Comment by jojosardez** [comment]
Hi @304NotModified ,
The pull request is now ready: https://github.com/NLog/NLog/pull/2256
Thanks!

**Comment by 304NotModified** [comment]
Investigated this, this isn't a bug as the type of the parameter is `string` and not `Layout`

**Comment by xmedeko** [comment]
How to make platform compatible line separator? I.e. for Linux `separator=\n` and for Windows `separator=\r\n`?

**Comment by 304NotModified** [comment]
I think the only way is to fix this issue (it's a breaking change), or your program needs some code for it.

**Comment by snakefoot** [comment]
Discovered that there is different between:

- `<target type="file" filename="C:\NLog\Rocks" />`

And

- `${literal:inner=C:\NLog\Rocks}`

So when suddenly changing Exception.Separator from `string` to `Layout` then this will change meaning:

- `${exception:separatorr=\r\n}`

Instead of being Windows-newline, then it will translate into the actual string "\r\n". I kind of like that NLog 5.0 is still non-breaking in parsing of `NLog.config`.

**Comment by 304NotModified** [comment]
> where escapes are ignored

Isn't that we need an extra `\`? e.g 

   ${exception:format=message:maxInnerExceptionLevel=10:separator=\\t\\r\\n}

But of course, unfortunate for the breaking change.

**Comment by 304NotModified** [comment]
another trick is to decompose the `${newline}`  when parsing the file ;)

**Comment by snakefoot** [comment]
> another trick is to decompose the ${newline} when parsing the file ;)

Thinking the same, since all use-cases has been about using `${newline}`.

**Comment by snakefoot** [comment]
> but I think it should be now in LayoutParser, and that could have bigger side-effect

Yes close to impossible. `${newline}` as implicit nlog-config-variable would also give headaches.

**Comment by snakefoot** [comment]
Created #4538 that allows parsing of `${newline}` when non-layout.
