### ISSUE TITLE
Suggestion for the documentation

### ISSUE THREAD

**Issue by houdelou** [NLog/NLog#225]
I've been using NLog a lot recently but not since a long time (about 6 months). I use it almost daily at my job. I like it a lot. Simple and effective. I would like to share my experience and maybe the challenge I encountered.

First, I was always searching for a way to change the log file at runtime. Here is the solution I found and that could be added to Wiki/Examples.

using NLog.Targets;
FileTarget target = LogManager.Configuration.FindTargetByName(targetName) as FileTarget;
target.FileName = filename;

Secondly, it would be good if we could specify a different config file. I know it would be a challenge to implement this because the LogManager.GetCurrentlClassLogger is a static function and it has to know where the file is I think. Probably, we would need to call a init function before writing.

Third, for the file target, I did not find any way to create a log file for every execution and roll it. So I usually put a size or date criteria. Seems to be the same request as https://github.com/NLog/NLog/issues/213.

And last, in Wiki/Configuration File/Variable, I would find it interesting if you add a way to set variable from the code. I don't know how to do it either.

Thank you ! I don't have any expectations after this message. I mean, I know you receive probably a lot of issue. But I was interested sharing this with you because last time I did, you add it to the wiki and I was happy to contribute.

**Comment by 304NotModified** [comment]
@houdelou  I don't completely understand the above post, but please make a PR to https://github.com/NLog/NLog.github.io or just edit the wiki. Thanks!

Closing it now, because it's unclear where to continue. Feel free to re-open.
