### ISSUE TITLE
Logging Stops intermediately

### ISSUE THREAD

**Issue by Vatsi** [NLog/NLog#2258]
Hi! Thanks for reporting this feature/bug/question! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

For .NET Core users, please check the platform support: https://github.com/NLog/NLog/wiki/platform-support

**Type** (choose one):

- Bug
- Feature request
- Question

**NLog version**: (e.g. 4.2.3)

**Platform**: .Net 3.5 / .Net 4.0 / .Net 4.5 / Mono 4 / Silverlight 4 / Silverlight 5 / Xamarin Android / Xamarin iOs / .NET Core 

**Current NLog config** (xml or C#, if relevant)

```xml
<nlog>
  <targets>
  </targets>
  <rules>
  </rules>
</nlog>

```

In case of a BUG:

- What is the current result?

Currently, my NLog Section is as follows,

```xml
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <targets>
      <target xsi:type="RetryingWrapper" retryCount="3" retryDelayMilliseconds="2" name="retryingWrap">
        <target name="asyncWrapper" xsi:type="AsyncWrapper" queueLimit="5000" overflowAction="Grow">
          <target name="file" xsi:type="File"
                  layout="${message}"
                  fileName="${basedir}/../Log/LogFile.log"
                  archiveFileName="${basedir}/../Log/LogFile.{##}.log"
                  archiveAboveSize="25000"
                  archiveNumbering="Rolling"
                  concurrentWrites="true"
                  maxArchiveFiles="100"
                  keepFileOpen="true"
                  encoding="iso-8859-2"
                  enableFileDelete="false" />
        </target>
      </target>
    </targets>
    <!-- NLog will use rule to set this level to decide whether to log message provided or not. minlevel or level have one of these values: "Trace", "Debug", "Info", "Warn", "Error", "Fatal" -->
    <rules>
      <logger name="*" minlevel="Trace" writeTo="asyncWrapper" />
    </rules>
  </nlog>
```

After NLog reaches to maximum number of files it stops logging in middle.

One of the observations was that it was logging in files which have already been archived. Maybe because of that thread is holding off file and not allowing it to push forward.

NLog version used is 2.1 but we see same issue with 4.4 as well.

I need support for 2.1 only.

- What is the expected result?

It should not stop logging intermediately.

- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?

Nothing there.

- Please post full exception details (message, stacktrace, inner exceptions)
- Are there any work arrounds? yes/no

We tried setting enablefiledelete to true which kind of resolved it but I could see loss of logs as well.

I tried setting section as below.

 <nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <targets>
      <target name="NullWithoutFormat" type="Null" formatMessage="false" />
      <target name="NullWithSimpleFormat" type="Null" formatMessage="true" layout="${message}${onexception:${newline}${exception:format=tostring}}" />
      <target name="NullWithFullFormat" type="Null" formatMessage="true" layout="${longdate} [${threadid}] ${level:uppercase=true} ${logger} - ${message}${onexception:${newline}${exception:format=tostring}}" />
      <target name="File" type="File" fileName="logfile.txt" autoFlush="false" keepFileOpen="true" layout="${longdate} [${threadid}] ${level:uppercase=true} ${logger} - ${message}${onexception:${newline}${exception:format=tostring}}" />
      <target name="AsyncFile" type="AsyncWrapper" overflowAction="Block" queueLimit="1000000" batchSize="1000" timeToSleepBetweenBatches="0">
        <target name="File" type="File" fileName="logfile.txt" autoFlush="false" keepFileOpen="true" layout="${longdate} [${threadid}] ${level:uppercase=true} ${logger} - ${message}${onexception:${newline}${exception:format=tostring}}" />
      </target>
    </targets>
    <rules>
      <logger name="*" minlevel="Trace" writeTo="AsyncFile" />
    </rules>
  </nlog>

But it caused CPU hike.

- Is there a version in which it did work? 

Nop.

- Can you help us by writing a unit test?

Let me know which kind of testing you will need and I can work and provide it. For now, it looks pretty straightforward issue to me.

in case of a FEATURE REQUEST:
 
 - Why do we need it?
 - An example of the XML config, if relevant.

**Comment by 304NotModified** [comment]
Probably Its the issue that the file is in the same folder as the archived files. Please try with a different archive folder. Probably you need 4.4

This issue will be solved in 4.5

**Comment by Vatsi** [comment]
Hello, 

Thanks for the prompt response. I've been stuck for days now.

 We've created our own logging APIs using NLog and 2.1 is currently on the client-side. I can make changes only in the configuration section deploying newer version is little difficult. Will setting archive folder different from the same folder as log file resolve my issue for 2.1?

**Comment by 304NotModified** [comment]
> Will setting archive folder different from the same folder as log file resolve my issue for 2.1?

I think so, but not sure. If it won't work, please update. Unfortunately we cannot support every version of NLog.

**Comment by Vatsi** [comment]
I understand about support. I tested and it worked with combination of "openFileCacheTimeout" set to 15. I'm creating 100 files in rolling with 25MB size per file. Thanks for all the help.
