### ISSUE TITLE
Nlog unusable on Google Pixel devices due to failing to load extensions (present or not)

### ISSUE THREAD

**Issue by jpajak** [NLog/NLog#2260]
**Type** (choose one):  Bug
**NLog version**: 4.4.12 (happens on 5.0.0-beta09 as well)
**Platform**: . Xamarin Android 

- What is the current result?
  On all google Pixel devices we have (a Pixel and 3 Pixel XLs), NLog fails to load the configuration file, so no logging occurs. We have many other types of phones, and this ONLY occurs on those Pixel devices. 

This seems to happen at the point when extensions are attempted to be loaded. We are not using any extensions.

The line that searches for them fails with an exception: 

> System.UnauthorizedAccessException: Access to the path '/' is denied.

This happens on this line in `ConfigurationItemFactor.cs (line 378)`
```c#
var extensionDlls = Directory.GetFiles(assemblyLocation, "NLog*.dll")
		.Select(Path.GetFileName)
		.Where(x => !x.Equals("NLog.dll", StringComparison.OrdinalIgnoreCase))
		.Where(x => !x.Equals("NLog.UnitTests.dll", StringComparison.OrdinalIgnoreCase))
		.Where(x => !x.Equals("NLog.Extended.dll", StringComparison.OrdinalIgnoreCase))
		.Select(x => Path.Combine(assemblyLocation, x));
```

- What is the expected result?
  The config file should be loaded and NLog should be able to log as configured.

- Are there any work arrounds? yes/no
 I commented out that section searching for exceptions and NLog functions correctly for me again. This works since we aren't using any extensions, but the inability to search for them is a larger issue, seemingly with just Google Pixel devices.

**Comment by jpajak** [comment]
That would help with my issue, but does it make sense why this is happening only on Pixels. 

Also does that mean that extensions would just be unsupported on Pixels?

**Comment by 304NotModified** [comment]
I think the root cause is that the value of `assemblyLocation` is wrong. I think it's `/` on the pixel device. Is that something you could check with the internal log?

**Comment by jpajak** [comment]
That is the case, but it's the same on every phone I've tested. On all the phones, this is what I see:
		assemblyCodeBase	  =  {file:///NLog.dll}	
		assemblyCodeBase.LocalPath   = "/NLog.dll"	
		assemblyLocation   ="/"

But only on the Pixel devices does passing "/" into Directory.GetFiles throw an exception.

**Comment by snakefoot** [comment]
@jpajak If you configure the NLog-setting `throwExceptions=false` (or use `NLog.LogManager.ThrowExceptions = false;`)

Then it should only log a warning, and continue to load the NLog-configuration.

**Comment by 304NotModified** [comment]
I double checked the code. This is indeed a warning when `throwExceptions=false` (as @snakefoot)

That should be OK, we could lower the warning to debug, but I don't seen any benefit in that. 

Of course, don't use throwExceptions=true in production.
