### ISSUE TITLE
Logging to EventViewer. Description for event can not be found.

### ISSUE THREAD

**Issue by alexandrudanpop** [NLog/NLog#2275]
**Type** (choose one):
- Bug

**NLog version**:  4.4.2

**Platform**: .Net 4.6.1

**Current NLog config** (xml or C#, if relevant)

```xml
  <nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <targets>
      <target xsi:type="EventLog" name="eventlog" source="Application" layout="${message}${newline}${exception:format=ToString}" eventId="MyApp"/>  
    </targets>
    <rules>
      <logger name="*" minlevel="Error" writeTo="eventlog" />
    </rules>
  </nlog>

```

In case of a BUG:

- What is the current result?
![eventviewer_nlog](https://user-images.githubusercontent.com/15979292/30153751-47755844-93c0-11e7-843f-9083d6c65c98.PNG)

The description for Event ID 0 from source Application cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

**Errors: There has been a specific error in the application.**

the message resource is present but the message is not found in the string/message table

- What is the expected result?
Only Include: **Errors: There has been a specific error in the application.**

**Comment by snakefoot** [comment]
@alexandrudanpop That is how the Windows EventLog works. You first need to register/install your application-name to be an EventLog-Source. 

The `source` you have specified in your NLog-EventLog-target should specify your registered EventLog-source. Usually the EventLog-Source is created during application install:

https://msdn.microsoft.com/en-us/library/2awhba7a(v=vs.110).aspx
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/new-eventlog?view=powershell-5.1

Btw. using "Application" as EventLog-source is a bad choice, if you have a computer with more than one application.

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, let us know!
