### ISSUE TITLE
NLog stops working when .config updated with invalid XML. Does not recover.

### ISSUE THREAD

**Issue by alexandery** [NLog/NLog#2279]
**Type**:

- Bug

**NLog version**: 4.4.12

**Platform**: .Net 4.6.1 

I have XML based configuration. Upon startup a program logs correctly. There is code that updates NLog.config with new XML and it does something to this extend:

```c#
private void Configure(string xmlConfig){
	string nlogConfigFile = $"{AppDomain.CurrentDomain.BaseDirectory}NLog.config";
	File.WriteAllText(nlogConfigFile, xmlConfig);
	LogManager.Configuration = LogManager.Configuration.Reload();
	LogManager.ReconfigExistingLoggers();
}
```

As soon as broken XML is written into .config file, "Reload()" returns an empty configuration. Calling the same method with correct XML has no effect - "Reload()" never creates a properly created Configuration object. The only way to get LogManager working is to restart the application (next to impossible in my case).

I see that a similar bug was reported and fixed years ago, but it clearly is broken for me: https://github.com/NLog/NLog/issues/273 . Any help is appreciated.

**Comment by 304NotModified** [comment]
it's a bit difficult to reload, if the config is gone (nothing to reload).

A more robust approach would be:

```c#
LogManager.Configuration = new XmlLoggingConfiguration(nlogConfigFile);
```

**Comment by alexandery** [comment]
Well, nothing is gone, it's just that XML is invalid (a missing closing tag or something). What's the real problem here is that once XML is fixed - subsequent calls into "LogManager.Configuration.Reload()" do not return properly constructed configuration object. It always come back as empty with nothing in it. And this means that something internal is broken and not loading from a new, corrected XML.

P.S. I will look into the XmlLoggingConfiguration() but that is really a workaround, I believe.

Thank you.

**Comment by 304NotModified** [comment]
Thanks for the fix @MikeFH !

**Comment by MikeFH** [comment]
You're welcome.
