### ISSUE TITLE
Silverlight NLog.extmap.xml

### ISSUE THREAD

**Issue by apotapenko** [NLog/NLog#228]
Please add the file 'NLog.extmap.xml' in the NuGet package "NLog" (lib\sl30\NLog.extmap.xml, lib\sl4\NLog.extmap.xml, lib\sl5\NLog.extmap.xml)
![nlog extmap](https://f.cloud.github.com/assets/1414032/601730/91e02bc0-cc87-11e2-9019-552f08c30e5f.jpg)

**Comment by 304NotModified** [comment]
@Xharze do you think this old issue is still a valid question?

**Comment by Xharze** [comment]
@304NotModified I don't know what this file does, but I don't think it is a high priority issue either way.

**Comment by 304NotModified** [comment]
Something with caching, but no experience with Silverlight 

https://msdn.microsoft.com/en-us/library/dd833069%28VS.95%29.aspx

PS: I'm more a HTML5 dude ;)

**Comment by Xharze** [comment]
Let's close it as wontfix, if this feature is requested by multiple people, we'll think about it again

**Comment by 304NotModified** [comment]
Yes, we also need some more info for this request. So close is the best solution for now.
