### ISSUE TITLE
Microsoft Store auto-rejects UWP app submission due forbidden kernel32 imports at NLog

### ISSUE THREAD

**Issue by yschkatula** [NLog/NLog#2282]
**Type** (choose one):

- Bug

**NLog version**: (e.g. 4.2.3)
Latest commit cbecb43 on Dec 7 2015 

**Platform**: 
UWP 

In case of a BUG:

- What is the current result?
You can't pass Microsoft Store submission

- What is the expected result?
You can successfully pass Microsoft Store submission

- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
No

- Please post full exception details (message, stacktrace, inner exceptions)
There is no exception, just app submission rejected. Reason: attempt to import WinAPI functions that are not allowed for MS Store.  Could you just switch off the following two by conditional compilation?

public static extern Microsoft.Win32.SafeHandles.SafeFileHandle CreateFile
public static extern bool GetFileInformationByHandle

- Are there any work arrounds? yes/no
No

- Is there a version in which it did worked? 
No

- Can you help us by writing an unit test?
N/A

**Comment by snakefoot** [comment]
@yschkatula What version of NLog are you using? 

NLog 5.0 BETA07 doesn't include any native API-calls (See `#if !NETSTANDARD`)

https://github.com/NLog/NLog/blob/coreCLR/src/NLog/Internal/Win32FileNativeMethods.cs

**Comment by yschkatula** [comment]
@snakefoot, I'm on UWP branch. It's nice if there is any stable version of trunk that supports UWP apps (Windows 10, Windows 10 Phone)

**Comment by snakefoot** [comment]
The coreclr branch is very stable and can be used for production. Much better than the stale uwp branch.

Sent from my Samsung device


-------- Original message --------

**Comment by 304NotModified** [comment]
@snakefoot could we close this for NLog 4.5?

**Comment by snakefoot** [comment]
@304NotModified Yes can be closed as already working with NLog 5.0 (and now also working with NLog 4.5)

**Comment by yschkatula** [comment]
Sorry to disturb you, guys, but while trying to add NLog reference to a new & empty UWP project I receive "Unable to add a reference to project 'NLog'." (I'm on VS2017). Steps: sync with NLog 4.5 sources, add empty UWP project, then try to add a reference to NLog class library to this new project.

If I try to add a reference from NuGet, I see "Package NLog 4.4.12 is not compatible with uap10.0.10586 (UAP,Version=v10.0.10586) / win10-x86-aot."

5.0 beta11 Installs from NuGet just fine (and the only issue here I'm not allowed to use pre-release nugets by our internal policy).

So, after all, UWP seems not to be a first-class citizen at NLog world ;(

**Comment by 304NotModified** [comment]
You need nlog 4.5 rc. Almost in rtm.
