### ISSUE TITLE
System.ArgumentException: Target cannot be found: 'EventLog'

### ISSUE THREAD

**Issue by astavria4** [NLog/NLog#2287]
Hi! Thanks for reporting this feature/bug/question! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

For .NET Core users, please check the platform support: https://github.com/NLog/NLog/wiki/platform-support

**Type** (choose one):
- Question

**NLog version**: 4.4.1

**Platform**:  Asp.NetCore 2.0

**Current NLog config** (xml or C#, if relevant)
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      throwExceptions="true"
       internalLogFile="c:\temp\internal-nlog.txt">

  <targets async="true">
    

    <target xsi:type="EventLog"
            name="eventlog"
            source="CoreDemo"
            layout="${message}${newline}${exception:format=ToString}"/>
  </targets>
  <rules>
    
    <logger name="*" writeTo="eventlog" minlevel="Error" />
  </rules>
</nlog>

Question:

The above is my nlog.config file. I cannot write to the Event Log. 

2017-09-20 13:47:07.8519 Error Parsing configuration from C:\Users\stavrianidisa\source\repos\CoreDemo\CoreDemo\nlog.config failed. Exception: NLog.NLogConfigurationException: Exception when parsing C:\Users\stavrianidisa\source\repos\CoreDemo\CoreDemo\nlog.config.  ---> System.ArgumentException: Target cannot be found: 'EventLog'
   at NLog.Config.Factory`2.CreateInstance(String name)
   at NLog.Config.XmlLoggingConfiguration.ParseTargetsElement(NLogXmlElement targetsElement)
   at NLog.Config.XmlLoggingConfiguration.ParseNLogElement(NLogXmlElement nlogElement, String filePath, Boolean autoReloadDefault)
   at NLog.Config.XmlLoggingConfiguration.Initialize(XmlReader reader, String fileName, Boolean ignoreErrors)
   --- End of inner exception stack trace ---
2017-09-20 13:47:07.8915 Info Found 0 configuration items
2017-09-20 13:47:07.8915 Info Found 0 configuration items

The nlog.config file has Build Action set to None and Copy to Output Directory set to Copy always. 

I am also copying my whole startup.cs

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.DependencyInjection;
using Swashbuckle.AspNetCore.Swagger;
using Microsoft.Extensions.Logging;
using NLog.Extensions.Logging;
using NLog.Web;

namespace CoreDemo
{
    public class Startup
    {
        public Startup(IHostingEnvironment environment)
        {
            environment.ConfigureNLog("nlog.config");
        }

        public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc();
    
            // Register the Swagger generator, defining one or more Swagger documents
            services.AddSwaggerGen(c =>
            {
                c.SwaggerDoc("v1", new Info
                {
                    Title = "CoreDemo API",
                    Version = "v1",
                    Description ="Learning how to create an API",
                    TermsOfService = "None",
                });
            });
           
        }

        public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory logger)
        {
            logger.AddConsole();
            logger.AddNLog();

            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            // Enable middleware to serve generated Swagger as a JSON endpoint.
            app.UseSwagger();
            app.UseSwaggerUI(c =>
            {
                c.SwaggerEndpoint("/swagger/v1/swagger.json", "Demo API");
            });
            app.UseStatusCodePages();
            app.UseMvc();
        }
    }
}

What am I doing wrong here?

**Comment by astavria4** [comment]
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      throwExceptions="true"
       internalLogFile="c:\temp\internal-nlog.txt">


  <targets async="true">
    

    <target xsi:type="EventLog"
            name="eventlog"
            source="CoreDemo"
            layout="${message}${newline}${exception:format=ToString}"/>
  </targets>
  <rules>
    
    <logger name="*" writeTo="eventlog" minlevel="Error" />
  </rules>
</nlog>

**Comment by astavria4** [comment]
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      throwExceptions="true"
       internalLogFile="c:\temp\internal-nlog.txt">


  <targets async="true">
    

    <target xsi:type="EventLog"
            name="eventlog"
            source="CoreDemo"
            layout="${message}${newline}${exception:format=ToString}"/>
  </targets>
  <rules>
    
    <logger name="*" writeTo="eventlog" minlevel="Error" />
  </rules>
</nlog>

**Comment by snakefoot** [comment]
If you check the platform support, then EventLog is not working for NetStandard 1.3+:

https://github.com/NLog/NLog/wiki/Platform-Support

And I guess the reason is this:

dotnet/corefx#6913

**Comment by 304NotModified** [comment]
Please let us know if we should add a link somewhere else for the platform support docs.

Closing for now

**Comment by snakefoot** [comment]
This will be fixed with PR #2547
