### ISSUE TITLE
NullReferenceException on reconfiguring loggers

### ISSUE THREAD

**Issue by emmauss** [NLog/NLog#2289]
- Bug

**NLog version**: 4.4.12

**Platform**: Xamarin Android  

**Current NLog config** (xml or C#, if relevant)

```c#
NLog.Targets.FileTarget target = new NLog.Targets.FileTarget("log");
                string logfile = Core.App.Settings.Log + DateTime.Now.ToShortDateString().Replace("/", "-") + " - "
                    + DateTime.Now.ToShortTimeString().Replace(":", ".") + " - log.txt";
                target.FileName = logfile;
                target.FileNameKind = NLog.Targets.FilePathKind.Absolute;
                LogManager.Configuration.AddTarget(target);

                LogManager.Configuration.AddRuleForAllLevels(target);
                LogManager.ReconfigExistingLoggers();
```
i have confirmed that the log file can be created with logfile as name manually.nlog config is the default one.

In case of a BUG:

- What is the current result?
throws a System.NullReferenceException on re configuring loggers

- What is the expected result?
a file is created and logged into. 
- Please post full exception details (message, stacktrace, inner exceptions)
stacktrace
```c#
  at System.Reflection.MonoProperty.GetValue (System.Object obj, System.Object[] index) [0x00027] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
  at NLog.Internal.ObjectGraphScanner.ScanProperties[T] (System.Collections.Generic.List`1[T] result, System.Object o, System.Int32 level, System.Collections.Generic.HashSet`1[T] visitedObjects) [0x000d6] in <d020946c0b3847f696ca171f5ea7baf6>:0 
  at NLog.Internal.ObjectGraphScanner.ScanPropertiesList[T] (System.Collections.Generic.List`1[T] result, System.Collections.Generic.IEnumerable`1[T] elements, System.Int32 level, System.Collections.Generic.HashSet`1[T] visitedObjects) [0x00010] in <d020946c0b3847f696ca171f5ea7baf6>:0 
  at NLog.Internal.ObjectGraphScanner.ScanProperties[T] (System.Collections.Generic.List`1[T] result, System.Object o, System.Int32 level, System.Collections.Generic.HashSet`1[T] visitedObjects) [0x0014b] in <d020946c0b3847f696ca171f5ea7baf6>:0 
  at NLog.Internal.ObjectGraphScanner.FindReachableObjects[T] (System.Object[] rootObjects) [0x0002c] in <d020946c0b3847f696ca171f5ea7baf6>:0 
  at NLog.Config.LoggingConfiguration.ValidateConfig () [0x00090] in <d020946c0b3847f696ca171f5ea7baf6>:0 
  at NLog.Config.LoggingConfiguration.InitializeAll () [0x00000] in <d020946c0b3847f696ca171f5ea7baf6>:0 
  at NLog.LogFactory.ReconfigExistingLoggers () [0x00019] in <d020946c0b3847f696ca171f5ea7baf6>:0 
  at NLog.LogManager.ReconfigExistingLoggers () [0x00000] in <d020946c0b3847f696ca171f5ea7baf6>:0 
  at HappyPandaXDroid.MainActivity.OnCreate (Android.OS.Bundle bundle) [0x0011d] in C:\HPX\HPX\MainActivity.cs:79 
```

- Are there any work arrounds? 
skipping the exception leaves logging disable

**Comment by 304NotModified** [comment]
Thanks for reporting!

**Comment by snakefoot** [comment]
@emmauss Could you make a try catch of this exception and check these properties of LogManager.Configuration:

- LoggingRules
- ConfiguredNamedTargets

To see if any of their IList-collections contains a null-object. I'm guessing that one of the LoggingRules.Targets contains an item that has the value null (Can see there is no null check validation on LoggingRule-constructor).

**Comment by emmauss** [comment]
@snakefoot under ConfiguredNamedTargets -> the added file target -> Filename -> base = {SimpleLayout}->base={Layout) -> NonPublic members -> loggingConfiguration is null,

also in the same filetarget -> base = {targetwithlayoutheaderandfooter}, the header and footer are null.
also in that filetarget. archive name is null, but archiving is not enabled, so i dont use it.
loggingrule has it target pointing to the filetarget

**Comment by 304NotModified** [comment]
@emmauss could you help us in creating an unit test from your testcase?

**Comment by emmauss** [comment]
made some test using Xamarin.Android Unit Testing
```
 class LoggingTest
    {
        static Logger logger = LogManager.GetCurrentClassLogger();
        [Test]
        public void InitLogging()
        {
            try
            { var config = new LoggingConfiguration();
                    NLog.Targets.FileTarget target = new NLog.Targets.FileTarget("log");
                    string logfile = Android.OS.Environment.ExternalStorageDirectory.Path + "/HPX/"
                    + DateTime.Now.ToShortDateString().Replace("/", "-") + " - "
                        + DateTime.Now.ToShortTimeString().Replace(":", ".") + " - log.txt";
                    target.FileName = logfile;
                    target.FileNameKind = NLog.Targets.FilePathKind.Unknown;
                    //LogManager.Configuration = new XmlLoggingConfiguration("assets/NLog.config");
                    LogManager.Configuration.AddTarget(target);

                    LogManager.Configuration.AddRuleForAllLevels(target);

                
                LogManager.ReconfigExistingLoggers();
                Assert.True(true);
            }
            catch (System.Exception ex)
            {
                
                Assert.False(true);
            }
            
        }
    }
```
it failed. 
results
![screenshot_2017-09-22-17-50-07](https://user-images.githubusercontent.com/5307160/30757578-bd830fc2-9fbe-11e7-8fb7-7911952d8377.png)
![screenshot_2017-09-22-17-50-27](https://user-images.githubusercontent.com/5307160/30757579-bd86a3f8-9fbe-11e7-9f1a-7dd46743aafc.png)
![screenshot_2017-09-22-17-50-53](https://user-images.githubusercontent.com/5307160/30757580-bd98c5ec-9fbe-11e7-8b67-11fc7171a3f7.png)

**Comment by 304NotModified** [comment]
in ` LogManager.Configuration.AddTarget(target);`, `LogManager.Configuration` is `null`

**Comment by emmauss** [comment]
every time ii catch the exception, and check the obect, `LogManager.Configuration` was never null. otherwise i would not be able to analyze the members like in the 3rd comment.

**Comment by 304NotModified** [comment]
please remove the try-catch from the unit test. (and the `assert`s). If it throws an exception, we could cleary see the stacktrace

**Comment by 304NotModified** [comment]
maybe this is related: https://stackoverflow.com/questions/30312538/xml-serialization-fails-with-nullreferenceexception-on-simple-class

**Comment by emmauss** [comment]
removed the try catch. here is the result;
![screenshot_2017-09-22-19-08-58](https://user-images.githubusercontent.com/5307160/30760423-a06e503a-9fc9-11e7-87f6-ff977962d4e3.png)

**Comment by emmauss** [comment]
in the test case, creating a new `Logmanager.Configuration` passes the test. but doing the same fails in the app. and the exception thrown are different, with the test throwing it at `InternalInvoke`, and the app at `GetValue`( the exception in the issue description).

**Comment by 304NotModified** [comment]
Could you try narrowing down the test case? (less code)

I have double checked the code, every possible null value is checked.

**Comment by emmauss** [comment]
setting linking to none, cleaning and rebuilding the solution fixes it for the app. seems to be a xamarin thing. sorry and thanks for the help.

**Comment by 304NotModified** [comment]
OK, glad it has been resolved!
