### ISSUE TITLE
Can WhenRepeatedFilter prevent logging events until time period has passed?

### ISSUE THREAD

**Issue by Mykezero** [NLog/NLog#2295]
**Type**
Question

**NLog version**:
4.4.11

**Platform**: .NET 4.6

Hi, is it possible for the WhenRepeated filter to prevent logging the first log message?

I'd like to be able to log events only after they have been occurring for at least 30 minutes.

**Comment by 304NotModified** [comment]
I think your could use the bufferTargetWrapper for that: https://github.com/NLog/NLog/wiki/BufferingWrapper-target
