### ISSUE TITLE
Sonarqube analysis is broken

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#2299]
Broken after move to VS 2017

> Sonar: Running Sonar in preview mode for PR 
SonarQube Scanner for MSBuild 3.0.2
MSBuild.SonarQube.Runner.exe : The format of the analysis property sonar.github.pullRequest= is invalid
At C:\projects\nlog\run-sonar.ps1:33 char:9

See build log: https://ci.appveyor.com/project/nlog/nlog/build/4.5.0-beta6197

**Comment by snakefoot** [comment]
@304NotModified Resolved with  #2683
