### ISSUE TITLE
Make NLog  as Public between some projects

### ISSUE THREAD

**Issue by osmanrahimi** [NLog/NLog#2304]
Hi.
I have a solution that contains Some Projects Like `Class Library` , `ASP.NET WEb API`
now I want to set NLog's configuration as public in a project and in another Projects Just Call it to log .
is it possible ? Or I have to Install NLog in each project with` Nlog.config` .

**Comment by 304NotModified** [comment]
There are two options:

- Create the XML config in your starting project (MVC etc). Then it's also used in calls to your class library etc.
- Or create the config in C#, then you can easily share it between projects.

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, let us know!
