### ISSUE TITLE
Potential data race in the file TimeoutContinuation.cs

### ISSUE THREAD

**Issue by MSIC-HSR** [NLog/NLog#2306]
**Type**: Bug (potential data race)

**NLog version**:
latest master as of 4.10.2017 @ 14:50, latest commit is [86202f6  on Oct 4](https://github.com/NLog/NLog/blob/86202f6c32dd3b88abe5a037b7cd5d0c3e7e9c5e/src/NLog/Internal/TimeoutContinuation.cs)

**Platform**:
.Net 3.5 / .Net 4.0 / .Net 4.5 / Mono 4 / Silverlight 4 / Silverlight 5 / Xamarin Android / Xamarin iOs / .NET Core 
(any making use of `TimeoutContinuation`)

**Further details**:
Hello

As part of an evaluation with a new static checker of our research, we think we have probably identified a potential (not necessarily critical and maybe very seldom occurring) data race. (A data race is an unsynchronized concurrent read/write or write/write access on the same variable or array element that has undefined behavior in the programming language, thus possibly considered as a formal issue as instructions could be reordered/optimized.)

The potential data race may happen in [TimeoutContinuation.cs](https://github.com/NLog/NLog/tree/master/src/NLog/Internal/TimeoutContinuation.cs) on the lines [56](https://github.com/NLog/NLog/tree/master/src/NLog/Internal/TimeoutContinuation.cs#L56) and [98](https://github.com/NLog/NLog/tree/master/src/NLog/Internal/TimeoutContinuation.cs#L98):
```cs
public TimeoutContinuation(AsyncContinuation asyncContinuation, TimeSpan timeout)
{
    this.asyncContinuation = asyncContinuation;
    this.timeoutTimer = new Timer(this.TimerElapsed, null, timeout, TimeSpan.FromMilliseconds(-1)); // TASK (TIMER) START HERE (CONCURRENT),  WRITE ACCESS ON timeoutTimer
}
// ...
private void StopTimer()
{
    lock (this)
    {
        var currentTimer = this.timeoutTimer; // ACCESSES INVOLVED IN DATA RACE
        if (currentTimer != null)
        {
            this.timeoutTimer = null;
            currentTimer.WaitForDispose(TimeSpan.Zero);
        }
    }
}
```

While it is very unlikely, there is a small chance that the timeout is fired before assigning the timer instance to the `timeoutTimer` variable. A possible fix would be enclosing this assignment with a `lock` statement:
```cs
public TimeoutContinuation(AsyncContinuation asyncContinuation, TimeSpan timeout)
{
    this.asyncContinuation = asyncContinuation;
    lock(this)
    {
        this.timeoutTimer = new Timer(this.TimerElapsed, null, timeout, TimeSpan.FromMilliseconds(-1));
    }
}
```

Maybe the constellation is impossible or the issue is very minor or unlikely, we just wanted to hint it.

**Comment by 304NotModified** [comment]
hey thanks! 

I will think about this. Thanks!

**Comment by MSIC-HSR** [comment]
You're welcome.
We have noticed prior reporting, that the code inside the `StopTimer` method slightly changed after the initial detection (see [here](https://github.com/NLog/NLog/commit/f90a55e943c9b1457349225f7350d1cd6065010b#diff-ceb04884b210ef3d764a01ef8907d9d3)).
This change allows that simply declaring the `timeoutTimer` variable as `volatile` is sufficient, so there is no need for using the `lock` statement inside the constructor.

**Comment by snakefoot** [comment]
> @MSIC-HSR While it is very unlikely, there is a small chance that the timeout is fired before assigning the timer instance to the timeoutTimer variable.

Not sure I understand how the constructor and the StopTimer-method can have a race-condition (Very hard to have multiple threads in the same object-constructor. Requires effort to have other threads calling into object-StopTimer while initial thread is still inside the object-contructor). Think you need to fix your race-condition-checking-tool.

**Comment by 304NotModified** [comment]
It's only possible if its called from the parents constructor (not this case) or as static (also not this case)

I think this is even theoretical impossible?

**Comment by 304NotModified** [comment]
Or do you think `TimerElapsed` could ne called before the Timer constructor has been finished?

**Comment by MSIC-HSR** [comment]
In this particular case, you are creating a thread (aka Timer which creates a Task) inside the constructor which is immediately started.
Of course, it does not necessarily fire immediately because of how the timer works (the timeout argument).
By conservatively assuming that the timer task fires right after its construction, this leads to a thread which has access to the incompletely created `TimeoutContinuation` object (like you correctly assumed @304NotModified).
Thus, the `StopTimer` function may be invoked before the construction of `TimeoutContinuation` has finished.
At this time, `timeoutTimer` can be anything from simply being `null` to an incompletely constructed object (depending on the implementation of `Timer`).

**Comment by MSIC-HSR** [comment]
In case you want some more insight see the example code below (note that these examples use the conservative interpretation by setting the timeout to 0, aka immediate start). It consists of four different implementations.

The first one is broken because of the data race we have reported. The second one fixes the data race with the help of `volatile`, but the race condition remains: `timer` can be either `null` or the instance that is created within the constructor.

The last two fix both issues. The first one with the help of the `lock` statement, as it was initially suggested (the idea was to match the existing style/re-use the existing synchronization mechanisms). The latter is not as verbose as the one with the `lock` statement and might fit better your taste. It declares the `timer` variable as `volatile`. But instead of letting the  `Timer` constructor start the "Task" immediately, this is accomplished with the separate `Change` invocation. This way, the data race is prevented by the `volatile` modifier, and the race condition is prevented as it is ensured that the `timer` variable is referencing the created instance.

```cs
using System;
using System.Threading;

class Program {
  static void Main(string[] args) {
    ConstructTimer<TimerDemoBroken>();
    ConstructTimer<TimerDemoBrokenVolatile>();
    ConstructTimer<TimerDemoFixedLock>();
    ConstructTimer<TimerDemoFixedVolatile>();
  }

  private static void ConstructTimer<T>() where T : new() {
    Console.WriteLine($"testing {typeof(T)}");
    for(var i = 0; i < 1000000; ++i) {
      new T();
    }
  }
}

class TimerDemoBroken {
  private Timer timer;

  public TimerDemoBroken() {
    timer = new Timer(StopTimer, null, 0, -1);
  }

  private void StopTimer(object arg) {
    timer.Dispose();
  }
}

class TimerDemoBrokenVolatile {
  private volatile Timer timer;

  public TimerDemoBrokenVolatile() {
    timer = new Timer(StopTimer, null, 0, -1);
  }

  private void StopTimer(object arg) {
    timer.Dispose();
  }
}

class TimerDemoFixedLock {
  private Timer timer;

  public TimerDemoFixedLock() {
    lock(this) {
      timer = new Timer(StopTimer, null, 0, -1);
    }
  }

  private void StopTimer(object arg) {
    lock(this) {
      timer.Dispose();
    }
  }
}

class TimerDemoFixedVolatile {
  private volatile Timer timer;

  public TimerDemoFixedVolatile() {
    timer = new Timer(StopTimer);
    timer.Change(0, -1);
  }

  private void StopTimer(object arg) {
    timer.Dispose();
  }
}
```

**Comment by 304NotModified** [comment]
Thanks for reporting, but this issue is too theoretical and hence we won't gonna change it.
