### ISSUE TITLE
Tests: replace integration tests with unit tests (including mocking)

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#2322]
some tests are  unneeded unstable and slow. 

Many test cases could be replaced with a mocking variant. For integration tests, only a single test should be needed.

For mocking, NSubstitute has the preference

**Comment by noamyogev84** [comment]
Where are these tests? @304NotModified 
I can take this.

**Comment by 304NotModified** [comment]
Thanks!

Unfortunately the list of unstable tests is not up-to-date anymore. Also this is less a problem nowadays, so I gonna close this one for now :)
