### ISSUE TITLE
Add regex.is-match(...) between basic Condition Functions

### ISSUE THREAD

**Issue by MarekPokorny** [NLog/NLog#2324]
**Type**: Feature request
Add `regex.is-match(input, pattern, options)` between **basic** Condition Functions like `contains(s1, s2)`, `starts-with(s1, s2)` and others.
It would easily call this method:
```cs
public static bool Regex.IsMatch(string input, string pattern, RegexOptions options)
```
 - Why do we need it?
Regex searching is used **very often** and it should be in my opinion between **basic** Condition Functions.
- Workaround
You can write new condition function and mark the class with the attribute [ConditionMethod].

**Comment by 304NotModified** [comment]
Sounds good!

Maybe just call it `regex-match`?  Or maybe even `regex`?

**Comment by MarekPokorny** [comment]
`regex` looks better.

**Comment by 304NotModified** [comment]
Could you help us in creating this feature? I can point you in the right direction

**Comment by MarekPokorny** [comment]
Maybe later. I can't do it now.

________________________________
Od: Julian Verdurmen <notifications@github.com>
Odesláno: 10. října 2017 22:09:18
Komu: NLog/NLog
Kopie: Marek Pokorný; Author
Předmět: Re: [NLog/NLog] Add regex.is-match(...) between basic Condition Functions (#2324)


Could you help us in creating this feature? I can point you in the right direction

**Comment by MikeFH** [comment]
Is it OK if I take a look at this ?
Regarding the name, it is written in [ConditionMethods.cs](https://github.com/NLog/NLog/blob/7e3629b3dc365c209e163d8bf3f0c263f996b0b3/src/NLog/Conditions/ConditionMethods.cs#L42) that the other names were loosely inspired by XPath functions names so maybe [matches](https://www.w3.org/TR/xpath-functions/#func-matches) could be nice. What do you think ?

**Comment by 304NotModified** [comment]
@MikeFH yes please!



> XPath functions names so maybe matches could be nice.

Only matches, or regex-matches? Maybe also regex-contains is an option?

I like the term `regex` for visibility, also we already a [`contains`](https://github.com/NLog/NLog/wiki/When-filter#condition-functions)

**Comment by MarekPokorny** [comment]
@MikeFH It would be nice, if you can write it! Thank you.

Both `regex` and `regex-matches` look good.
