### ISSUE TITLE
NLog 4.5 changelog

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#2325]
Update changelog

**Comment by snakefoot** [comment]
List of important changes in NLog 4.5

**Features:**
Introduced NetStandard 2.0 #2263 + #2402
Introduced MessageTemplates #2262 + #2301 + #2208
Introduced NetStandard 1.5 #2341
Default file archive logic is now easier to use #1993
Improve archive stability during concurrent file access #1889
Introduced InstallationContext.ThrowExceptions #2214
WebServiceTarget can now batch multiple logevents into single request #2223
WebServiceTarget - Allow configuration of proxy address #2375
Json conversion also supports object properties #2179
event-properties layout-renderer can now render objects as json #2241
exception layout-renderer can now render objects as json #2357
${guid}, added GeneratedFromLogEvent #2226
TraceTarget RawWrite to always perform Trace.WriteLine independen of LogLevel #1968
Adding OverflowAction options to BufferingTargetWrapper #2276
WhenRepeatedFilter  #2123 + #2297
${callsite} added CleanNamesOfAsyncContinuations option #2292
${ndlctiming} allows timing of ndlc-scopes #2377
NLogViewerTarget - Enable override of the Logger-name #2390
${sequenceid} added #2411 

**BugFixes:**
FallbackGroup could lose log events #2265
Exception separator should only be inserted for available items #2250
${exception} - only include separator when items are available #2257
LogFactory - Fixes broken EventArgs for ConfigurationChanged #1897
Do not report wrapped targets as unused targets #2290
Added IIncludeContext, implemented missing properties #2117
Improve logging of callsite linenumber for async-methods #2386
NLogTraceListener - DisableFlush is enabled by default when AutoFlush=true #2407
NLogViewer - Better defaults for connection limits #2404

**Performance:**
StringBuilderPool - Improved Layout Render Performance #2262
Target - Precalculate Layout should ignore sub-layouts for complex layout (Ex Json) #2378

**Comment by 304NotModified** [comment]
Thank you very much!

**Comment by snakefoot** [comment]
Performance Comparison of NLog 4.4 and NLog 4.5. 

Most of the performance improvements disappears in the extra overhead of the new MessageTemplate-parser, but one can still see the reduced memory allocation. 

One can also get a glimpse of the extra overhead introduced by parsing the message-template, and capturing the message-properties (NLog45-MT). The memory allocation increases along with the CPU-time.

Still the differences is so small, so I don't think anyone will actually notice :smiley:

| Logger Name      | Messages   | Size | Args | Threads | Loggers |
|------------------|------------|------|------|---------|---------|
| PerfLogger       | 15.000.000 |   16 |    0 |       1 |       1 |


| Test Name  | Time (ms) | Msgs/sec  | GC2 | GC1 | GC0 | CPU (ms) | Alloc (MB) |
|------------|-----------|-----------|-----|-----|-----|----------|------------|
| NLog44    |     7.786 | 1.926.497 |   0 |  25 |  50 |   11.109 |    2.232,2 |
| NLog45    |     7.573 | 1.980.628 |   0 |  23 |  46 |   11.453 |    2.175,0 |
| NLog45-MT |     7.747 | 1.936.185 |   0 |  22 |  47 |   11.156 |    2.175,0 |


| Logger Name      | Messages   | Size | Args | Threads | Loggers |
|------------------|------------|------|------|---------|---------|
| PerfLogger       | 15.000.000 |  128 |    2 |       1 |       1 |

| Test Name  | Time (ms) | Msgs/sec  | GC2 | GC1 | GC0 | CPU (ms) | Alloc (MB) |
|------------|-----------|-----------|-----|-----|-----|----------|------------|
| NLog44    |    28.746 |   521.805 |   0 |  50 | 101 |   34.359 |    6.126,3 |
| NLog45    |    28.450 |   527.223 |   0 |  47 |  96 |   33.843 |    6.070,8 |
| NLog45-MT |    37.213 |   403.084 |   0 |  60 | 121 |   42.359 |    8.990,1 |


| Logger Name      | Messages   | Size | Args | Threads | Loggers |
|------------------|------------|------|------|---------|---------|
| PerfSyncLogger   | 10.000.000 |   16 |    0 |       1 |       1 |


| Test Name  | Time (ms) | Msgs/sec  | GC2 | GC1 | GC0 | CPU (ms) | Alloc (MB) |
|------------|-----------|-----------|-----|-----|-----|----------|------------|
| NLog44    |     7.234 | 1.382.270 |   0 |   0 | 150 |    7.312 |    1.487,8 |
| NLog45    |     8.364 | 1.195.480 |   0 |   0 | 139 |    8.421 |    1.449,7 |
| NLog45-MT |     8.438 | 1.185.092 |   0 |   0 | 144 |    8.453 |    1.449,7 |


| Logger Name      | Messages   | Size | Args | Threads | Loggers |
|------------------|------------|------|------|---------|---------|
| PerfSyncLogger   | 10.000.000 |  128 |    2 |       1 |       1 |


| Test Name  | Time (ms) | Msgs/sec  | GC2 | GC1 | GC0 | CPU (ms) | Alloc (MB) |
|------------|-----------|-----------|-----|-----|-----|----------|------------|
| NLog44    |    22.116 |   452.147 |   0 |   0 | 406 |   22.140 |    4.082,0 |
| NLog45    |    23.386 |   427.595 |   0 |   0 | 402 |   23.500 |    4.043,8 |
 NLog45-MT |    28.700 |   348.422 |   0 |   0 | 595 |   28.484 |    5.989,6 |


| Logger Name      | Messages   | Size | Args | Threads | Loggers |
|------------------|------------|------|------|---------|---------|
| Logger           | 10.000.000 |   16 |    0 |       1 |       1 |

| Test Name  | Time (ms) | Msgs/sec  | GC2 | GC1 | GC0 | CPU (ms) | Alloc (MB) |
|------------|-----------|-----------|-----|-----|-----|----------|------------|
| NLog44    |    21.000 |   476.172 |   0 |  30 |  61 |   35.312 |    4.999,3 |
| NLog45    |    19.571 |   510.951 |   0 |  29 |  58 |   33.875 |    4.503,4 |
| NLog45-MT |    19.825 |   504.410 |   0 |  28 |  57 |   33.968 |    4.503,5 |


| Logger Name      | Messages   | Size | Args | Threads | Loggers |
|------------------|------------|------|------|---------|---------|
| Logger           | 10.000.000 |  128 |    2 |       1 |       1 |

| Test Name  | Time (ms) | Msgs/sec  | GC2 | GC1 | GC0 | CPU (ms) | Alloc (MB) |
|------------|-----------|-----------|-----|-----|-----|----------|------------|
| NLog44    |    29.592 |   337.919 |   0 |  44 |  88 |   52.500 |    9.797,4 |
| NLog45    |    25.961 |   385.188 |   0 |  73 | 147 |   48.765 |    9.262,2 |
| NLog45-MT |    30.899 |   323.625 |   0 |  96 | 196 |   50.890 |   11.285,0 |


| Logger Name      | Messages   | Size | Args | Threads | Loggers |
|------------------|------------|------|------|---------|---------|
| Logger           | 10.000.000 |   64 |    2 |       2 |       1 |

| Test Name  | Time (ms) | Msgs/sec  | GC2 | GC1 | GC0 | CPU (ms) | Alloc (MB) |
|------------|-----------|-----------|-----|-----|-----|----------|------------|
| NLog44    |    25.592 |   390.740 |   0 |  38 |  77 |   68.156 |    7.366,7 |
| NLog45    |    23.116 |   432.583 |   0 |  56 | 121 |   65.546 |    6.832,7 |
| NLog45-MT |    28.219 |   354.364 |   0 |  82 | 169 |   71.109 |    8.848,4 |


| Logger Name      | Messages   | Size | Args | Threads | Loggers |
|------------------|------------|------|------|---------|---------|
| Logger           | 10.000.000 |   64 |    2 |       4 |       1 |

| Test Name  | Time (ms) | Msgs/sec  | GC2 | GC1 | GC0 | CPU (ms) | Alloc (MB) |
|------------|-----------|-----------|-----|-----|-----|----------|------------|
| NLog44    |    42.338 |   236.190 |   0 |  33 |  66 |  107.703 |    7.369,3 |
| NLog45    |    37.909 |   263.785 |   0 |  31 |  64 |  106.625 |    6.836,3 |
| NLog45-MT |    28.165 |   355.044 |   0 |  67 | 143 |  108.968 |    8.855,6 |


| Logger Name      | Messages   | Size | Args | Threads | Loggers |
|------------------|------------|------|------|---------|---------|
| Logger           | 10.000.000 |   64 |    2 |       8 |       1 |

| Test Name  | Time (ms) | Msgs/sec  | GC2 | GC1 | GC0 | CPU (ms) | Alloc (MB) |
|------------|-----------|-----------|-----|-----|-----|----------|------------|
| NLog44    |    61.379 |   162.921 |   0 |  30 |  61 |  199.218 |    7.377,2 |
| NLog45    |    60.469 |   165.373 |   0 |  29 |  58 |  199.406 |    6.844,9 |
| NLog45-MT |    57.638 |   173.493 |   0 |  37 |  77 |  195.390 |    8.863,4 |



| Logger Name      | Messages   | Size | Args | Threads | Loggers |
|------------------|------------|------|------|---------|---------|
| JsonLogger       | 10.000.000 |   16 |    0 |       1 |       1 |

| Test Name  | Time (ms) | Msgs/sec  | GC2 | GC1 | GC0 | CPU (ms) | Alloc (MB) |
|------------|-----------|-----------|-----|-----|-----|----------|------------|
| NLog44    |    36.198 |   276.254 |   0 |  96 | 193 |   38.812 |    8.358,5 |
| NLog45    |    32.963 |   303.364 |   0 |  28 |  59 |   35.343 |    3.054,9 |
| NLog45-MT |    32.374 |   308.883 |   0 |  31 |  65 |   34.984 |    3.054,9 |


| Logger Name      | Messages   | Size | Args | Threads | Loggers |
|------------------|------------|------|------|---------|---------|
| JsonLogger       | 10.000.000 |  128 |    2 |       1 |       1 |

| Test Name  | Time (ms) | Msgs/sec  | GC2 | GC1 | GC0 | CPU (ms) | Alloc (MB) |
|------------|-----------|-----------|-----|-----|-----|----------|------------|
| NLog44    |    56.170 |   178.028 |   0 | 137 | 275 |   58.921 |   19.577,8 |
| NLog45    |    56.329 |   177.527 |   0 |  57 | 114 |   60.187 |    8.131,8 |
| NLog45-MT |    66.294 |   150.842 |   0 |  70 | 141 |   70.406 |   10.311,3 |


| Logger Name      | Messages   | Size | Args | Threads | Loggers |
|------------------|------------|------|------|---------|---------|
| PerfArchiveLogger | 10.000.000 |   16 |    0 |       1 |       1 |

| Test Name  | Time (ms) | Msgs/sec  | GC2 | GC1 | GC0 | CPU (ms) | Alloc (MB) |
|------------|-----------|-----------|-----|-----|-----|----------|------------|
| NLog44    |    12.610 |   793.000 |   0 |   0 | 147 |   12.578 |    1.487,8 |
| NLog45    |    12.442 |   803.682 |   0 |   0 | 142 |   12.296 |    1.449,7 |
| NLog45-MT |    11.898 |   840.475 |   0 |   0 | 139 |   11.890 |    1.449,7 |


| Logger Name      | Messages   | Size | Args | Threads | Loggers |
|------------------|------------|------|------|---------|---------|
| SyncLogger       | 10.000.000 |   16 |    0 |       1 |       1 |

| Test Name  | Time (ms) | Msgs/sec  | GC2 | GC1 | GC0 | CPU (ms) | Alloc (MB) |
|------------|-----------|-----------|-----|-----|-----|----------|------------|
| NLog44    |    31.195 |   320.560 |   0 |   0 | 247 |   31.046 |    2.479,7 |
| NLog45    |    32.243 |   310.142 |   0 |   0 | 193 |   32.015 |    1.983,8 |
| NLog45-MT |    32.530 |   307.405 |   0 |   0 | 188 |   32.687 |    1.983,8 |


| Logger Name      | Messages   | Size | Args | Threads | Loggers |
|------------------|------------|------|------|---------|---------|
| SyncLogger       | 10.000.000 |  128 |    2 |       1 |       1 |

| Test Name  | Time (ms) | Msgs/sec  | GC2 | GC1 | GC0 | CPU (ms) | Alloc (MB) |
|------------|-----------|-----------|-----|-----|-----|----------|------------|
| NLog44    |    46.390 |   215.562 |   0 |   0 | 508 |   46.359 |    5.112,1 |
| NLog45    |    46.884 |   213.292 |   0 |   0 | 454 |   46.796 |    4.578,2 |
| NLog45-MT |    51.850 |   192.861 |   0 |   0 | 647 |   51.859 |    6.523,6 |


| Logger Name      | Messages   | Size | Args | Threads | Loggers |
|------------------|------------|------|------|---------|---------|
| SimpleLogger     | 10.000.000 |   16 |    0 |       1 |       1 |

| Test Name  | Time (ms) | Msgs/sec  | GC2 | GC1 | GC0 | CPU (ms) | Alloc (MB) |
|------------|-----------|-----------|-----|-----|-----|----------|------------|
| NLog44    |    27.320 |   366.023 |   0 |  25 |  51 |   29.796 |    2.482,3 |
| NLog45    |    26.506 |   377.269 |   0 |  19 |  40 |   28.609 |    1.986,5 |
| NLog45-MT |    26.603 |   375.892 |   0 |  19 |  39 |   29.171 |    1.986,6 |



| Logger Name      | Messages   | Size | Args | Threads | Loggers |
|------------------|------------|------|------|---------|---------|
| SimpleLogger     | 10.000.000 |  128 |    2 |       1 |       1 |

| Test Name  | Time (ms) | Msgs/sec  | GC2 | GC1 | GC0 | CPU (ms) | Alloc (MB) |
|------------|-----------|-----------|-----|-----|-----|----------|------------|
| NLog44    |    42.277 |   236.532 |   0 |  36 |  73 |   46.609 |    5.117,2 |
| NLog45    |    41.249 |   242.425 |   0 |  32 |  67 |   44.921 |    4.583,0 |
| NLog45-MT |    45.907 |   217.827 |   0 |  44 |  90 |   49.546 |    6.528,9 |


| Logger Name      | Messages   | Size | Args | Threads | Loggers |
|------------------|------------|------|------|---------|---------|
| SimpleLogger     | 10.000.000 |   64 |    2 |       2 |       1 |

| Test Name  | Time (ms) | Msgs/sec  | GC2 | GC1 | GC0 | CPU (ms) | Alloc (MB) |
|------------|-----------|-----------|-----|-----|-----|----------|------------|
| NLog44    |    36.006 |   277.729 |   0 |  29 |  58 |   42.187 |    3.897,0 |
| NLog45    |    35.924 |   278.363 |   0 |  23 |  49 |   42.234 |    3.362,8 |
| NLog45-MT |    41.687 |   239.879 |   0 |  37 |  76 |   47.500 |    5.309,4 |



| Logger Name      | Messages   | Size | Args | Threads | Loggers |
|------------------|------------|------|------|---------|---------|
| SimpleLogger     | 10.000.000 |   64 |    2 |       4 |       1 |

| Test Name  | Time (ms) | Msgs/sec  | GC2 | GC1 | GC0 | CPU (ms) | Alloc (MB) |
|------------|-----------|-----------|-----|-----|-----|----------|------------|
| NLog44    |    41.850 |   238.944 |   0 |  29 |  60 |   71.093 |    3.897,3 |
| NLog45    |    39.664 |   252.114 |   0 |  25 |  52 |   63.609 |    3.363,2 |
| NLog45-MT |    45.193 |   221.269 |   0 |  39 |  81 |   69.406 |    5.309,4 |


| Logger Name      | Messages   | Size | Args | Threads | Loggers |
|------------------|------------|------|------|---------|---------|
| SimpleLogger     | 10.000.000 |   64 |    2 |       8 |       1 |

| Test Name  | Time (ms) | Msgs/sec  | GC2 | GC1 | GC0 | CPU (ms) | Alloc (MB) |
|------------|-----------|-----------|-----|-----|-----|----------|------------|
| NLog44    |    60.767 |   164.560 |   0 |  29 |  59 |  149.046 |    3.899,7 |
| NLog45    |    62.119 |   160.980 |   0 |  24 |  50 |  157.203 |    3.365,2 |
| NLog45-MT |    67.887 |   147.303 |   0 |  39 |  79 |  158.531 |    5.311,7 |


| Logger Name      | Messages   | Size | Args | Threads | Loggers |
|------------------|------------|------|------|---------|---------|
| MultiLogger      | 10.000.000 |   16 |    0 |       1 |       1 |


| Test Name  | Time (ms) | Msgs/sec  | GC2 | GC1 | GC0 | CPU (ms) | Alloc (MB) |
|------------|-----------|-----------|-----|-----|-----|----------|------------|
| NLog44    |    19.500 |   512.806 |   1 |  59 | 147 |   25.265 |    4.841,5 |
| NLog45    |    20.070 |   498.244 |   0 |  55 | 138 |   29.859 |    4.355,4 |
| NLog45-MT |    20.265 |   493.437 |   3 | 105 | 263 |   31.390 |    4.358,8 |


| Logger Name      | Messages   | Size | Args | Threads | Loggers |
|------------------|------------|------|------|---------|---------|
| MultiLogger      | 10.000.000 |  128 |    2 |       1 |       1 |


| Test Name  | Time (ms) | Msgs/sec  | GC2 | GC1 | GC0 | CPU (ms) | Alloc (MB) |
|------------|-----------|-----------|-----|-----|-----|----------|------------|
| NLog44    |    32.587 |   306.870 |   5 | 118 | 530 |   81.093 |    9.679,5 |
| NLog45    |    37.747 |   264.916 |   3 | 117 | 738 |  110.015 |    9.165,9 |
| NLog45-MT |    43.756 |   228.538 |   4 | 116 | 1157 |  136.609 |   11.186,9 |

**Comment by 304NotModified** [comment]
looks good!

MT will be only a good option if you're really using structured logging, isn't?

**Comment by 304NotModified** [comment]
are the message count per thread? as more threads = slower?

**Comment by snakefoot** [comment]
> MT will be only a good option if you're really using structured logging, isn't?

Is the same configuration as NLog45-Auto. I have just changed the performance to to generate structured-logging test-message, so it starts to capture the message-properties.

**Comment by snakefoot** [comment]
> are the message count per thread? as more threads = slower? (comparing the 8 threads to the 4 and 2)

The message count is the same. Just more threads calling the logger-object concurrently. This gives an overhead when multiple threads are hitting the same target, thus slowing performance (waiting for the other threads to leave the target).

You can see the non-sync-tests performs better when going from 1 thread to 2 threads, but when reaching 4 threads then the target-monitor-lock starts to hurt. The monitor-lock is needed to protect the layoutrenderers as not all can handle multiple threads.

I guess one could consider replace the lock-queue on the async-wrapper with the concurrentqueue, when using NetStandard2.0. But all earlier version of ConcurrentQueue actually performs worse than lock-queue, and those versions also generate a lot of extra allocations.

**Comment by 304NotModified** [comment]
@snakefoot do you like to write a post on nlog.org for this? (http://nlog-project.org/archives/)

**Comment by snakefoot** [comment]
Think you are doing a great job already. And the MessageTemplate logic is your creation.


Sent from my Samsung device


-------- Original message --------

**Comment by 304NotModified** [comment]
See https://github.com/NLog/NLog/blob/master/CHANGELOG.md

@snakefoot 
thanks for keeping the import changes up-to-date!
