### ISSUE TITLE
Structured logging feedback

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#2332]
Structured logging has been re-introduced in NLog 4.5 beta 4. It works on all platforms, including .NET Standard 2. 

Please post feedback here!

(PS: We have to update our docs)

Thanks in advance!

**Comment by tylerohlsen** [comment]
Not supporting .Net Standard 1.x delays my consumption and evaluation of structured logging by many months.  *sigh*

**Comment by 304NotModified** [comment]
Unfortunately no. Supporting .NET Standard 1 is hard and therefor there is no RTM for .NET Standard 1 

Probably we will also drop .NET Standard 1 support soon. It's really delaying our development, feedback is low, has too many hacks  and tooling support is dramatic.  See https://github.com/NLog/NLog/issues/2150 and https://twitter.com/NLogOfficial/status/909135834229755904

**Comment by snakefoot** [comment]
> Will it be merged up to the 5.x branch and then supported by .Net Standard 1.x?

If this should be done, then it would probably be easier to create a new branch from main (ex coreclr2), and then cherry-pick the changes needed for NetStandard 1.3 and UWP.

**Comment by mika76** [comment]
Is there a note anywhere on how to enable this?

**Comment by snakefoot** [comment]
>  @mika76 Is there a note anywhere on how to enable this?

It is enabled by default, so it will automatically parse log-messages and capture property-names. These can be presented like one have always done with NLog-Properties.

**Comment by snakefoot** [comment]
> @tylerohlsen Not supporting .Net Standard 1.x delays my consumption and evaluation of structured logging

You can try this custom nuget-package build, that supports NetStandard1.5:

https://ci.appveyor.com/project/nlog/nlog/build/4.5.0-beta6403/artifacts

**Comment by 304NotModified** [comment]
I think this one could be closed :)
