### ISSUE TITLE
Merge NLog.Extended appsettings to NLog

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#2335]
deprecate NLog.Extended and move to NLog

Move MSMQ to separate package

**Comment by snakefoot** [comment]
Thought you wanted to split NLog into multiple packages. Think that XML-config + Json-config + Legacy-AppSettings + Json-AppSettings all should be seperate nuget-packages.

**Comment by 304NotModified** [comment]
yes, but the goals for splitting is:

- faster build/test time
- faster/more scoped development
- less dependencies in main package

That the current ${appsetting} is in the NLog.Extended, is a bit hard to explain. Especially because the client framework in unknown by many users.

**Comment by snakefoot** [comment]
Agree on the goals, so why put more into the NLog-core, especially when it is not supported by all platforms? Instead NLog.Extended could be split into two packages NLog.AppSettings.Renderer and NLog.Msmq.Target

**Comment by 304NotModified** [comment]
> Agree on the goals, so why put more into the NLog-core, especially when it is not supported by all platforms? I

Good point.

Because it's easier to use, the code for appsettings is small, fast test, and no new dependency is needed. But the latter i'm not sure in .NET Standard.

**Comment by snakefoot** [comment]
> The code for appsettings is small, fast test, and no new dependency is needed

Oh just wait for it having to load an external config-file, and maybe have to setup a file-watcher for the config-file if changes occurs. Many things happens in the night.

**Comment by snakefoot** [comment]
After lots of failures in creating a fully working NLog.AppConfig-package (See #2919), then I accept my defeat and have instead created #3053.

**Comment by snakefoot** [comment]
@304NotModified Now included in NLog 4.6 Release (And not Nlog 5.0)

**Comment by 304NotModified** [comment]
Thanks!
