### ISSUE TITLE
Structured logging in 4.5-beta4 feedback

### ISSUE THREAD

**Issue by nblumhardt** [NLog/NLog#2339]
**Type** (choose one):

- Feature request (essentially)

**NLog version**: 4.5-beta4

**Platform**: all

Hi! I've just updated _Seq.Targets.NLog_ to the new 4.5-beta04 🎉 

A few things seem to be missing or are unclear:

 - `MessageTemplateParameter.Format` is null in a case like `"The number is {0:000}"` - I would expect the format to be `"000"` in this case
 - In a positional template, there doesn't seem to be a way to get the position of a placeholder except by parsing the parameter's `Name`
 - By including `@` and `$` directives in `MessageTemplateParameter.Format`, it's ambiguous whether they constitute capture types or .NET format strings (like `$` for currency)

With my limited understanding of the feature at this point, it appears these could be resolved cleanly by:

 - Exposing `CaptureType` on `MessageTemplateParameter`, and _not_ duplicating the capture type in `Format`
 - Always using `Format` for the text-formatting information
 - Providing `int` or `int? Position` on `MessageTemplateParameter`, with a value provided when `IsPositional` is true

Can you please let me know if I'm on the right track, or misunderstanding how NLog should work, here?

Congratulations on shipping the new beta! :-)

**Comment by snakefoot** [comment]
Yes I have not given the MessageTemplateParameters so much love when IsPositional. Will try and improve this.

Did not think about $ being used as actual format-string. Thought I could use it as reserved word.

**Comment by nblumhardt** [comment]
Thanks for the reply. (I just found #2332 - I can close this and post over there, if you'd prefer - sorry about that!)

**Comment by 304NotModified** [comment]
> Thanks for the reply. (I just found #2332 - I can close this and post over there, if you'd prefer - sorry about that!)

NP! Thanks for the fast feedback!

**Comment by snakefoot** [comment]
> @nblumhardt or .NET format strings (like $ for currency)

I have looked at the format strings, and I can see one can use "C" to output as localized currency (Ex $), but I cannot see that one can use $ and @ in the format-string.

https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-numeric-format-strings

If we add the CaptureType to the MessageTemplateParameter, then must also be added as input parameter to the IValueSerializer. What do you think @304NotModified  ?

> Providing int or int? Position on MessageTemplateParameter, with a value provided when 

Should be easy to implement a method that quickly converts single-digit string-values into integer values.  Should I implement a new getter on MessageTemplateParameter, that does the conversion. What do you think @304NotModified  ?

**Comment by nblumhardt** [comment]
> I have looked at the format strings, and I can see one can use "C" to output as localized currency (Ex $), but I cannot see that one can use $ and @ in the format-string.

@snakefoot thanks for taking a look! I was just giving an arbitrary example; format strings in .NET are extensible, so it's possible for custom types to use `@` and `$` in their format strings, even if there aren't any readily-located cases of it in the BCL. Seems like it would be better to protect against this during the limited-distribution beta, rather than face a breaking change if/when a conflict is found in the wild.

**Comment by 304NotModified** [comment]
> If we add the CaptureType to the MessageTemplateParameter, then must also be added as input parameter to the IValueSerializer. What do you think @304NotModified ?

I think that's a bit odd, maybe multiple ValueSerializers?

**Comment by 304NotModified** [comment]
> @nblumhardt Have fixed the problem with the parsing of IsPositional-messages, now it performs the full parsing when requested. Just need to have #2340 approved and merged, and new BETA released.

new beta is in the build queue! Thanks @snakefoot !

**Comment by snakefoot** [comment]
> @nblumhardt Exposing CaptureType on MessageTemplateParameter, and not duplicating the capture type in Format

> Providing int or int? Position on MessageTemplateParameter, with a value provided when IsPositional is true

Both features are now implemented with #2348. Guess it is time for a new BETA :)

**Comment by 304NotModified** [comment]
yes! beta6 is the build queue.

@nblumhardt feel free to open a new issue if there is new feedback. :)

**Comment by 304NotModified** [comment]
it's on nuget: https://www.nuget.org/packages/NLog/4.5.0-beta06

**Comment by nblumhardt** [comment]
Thank you! I'll try it out later today 👍
