### ISSUE TITLE
Remove [StringFormatMethod] on loggers

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#2345]
Remove the StringFormatMethodAttribute as this gives warnings for structured logging

**Comment by snakefoot** [comment]
Maybe replace with a different attribute. Like MessageTemplateFormatMethodAttribute.

**Comment by 304NotModified** [comment]
see also https://github.com/Suchiman/SerilogAnalyzer/issues/15

**Comment by 304NotModified** [comment]
> Maybe replace with a different attribute. Like MessageTemplateFormatMethodAttribute. (That allows one use both positional-parameters and structured-parameters)
> 
> In case one wanted to make something like https://github.com/Suchiman/SerilogAnalyzer

I'm not sure how this works. Do we have to add attributes for this as you suggested? What should be in the attribute, or is it a "marker" attribute? thanks!

**Comment by snakefoot** [comment]
> I'm not sure how this works. What should be in the attribute, or is it a "marker" attribute? 

Yes it works as marker attribute. Just like the StringFormatMethod-attribute does. Signalling to a code-analyzer that extra validation can be performed (If it recognizes the attribute).
