### ISSUE TITLE
rename messageTemplateParser to parseMessageTemplate

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#2347]
rename `<nlog messageTemplateParser=true>` to 
`<nlog structuredLogging=true>` ?

**Comment by snakefoot** [comment]
Like messageTemplateParser since it matches the messageTemplates-namespace.

Also structuredLogging-support is always enabled even if not specifying structuredLogging=true (Ex. if getting help from Microsoft Extensions Logging).

**Comment by 304NotModified** [comment]
I showed the new feature here at work, and there a bit confused by the name of the setting.

**Comment by 304NotModified** [comment]
also, i don't know how the explain the auto.

**Comment by snakefoot** [comment]
> also, i don't know how to explain the auto.

null (auto) means that it attempts to parse and render as messagetemplate, but if it smells like IsPositional, then it quickly make fallback to string.format.

true means that it uses the messagetemplate-parser for parse and render no matter what.

false means that it always uses string.format no matter what.

**Comment by 304NotModified** [comment]
thanks!

**Comment by 304NotModified** [comment]
thinking to rename it to: parseMessageTemplate or parseMessageAsTemplate

What do you think @snakefoot ?

**Comment by snakefoot** [comment]
parseMessageTemplate is fine with me

**Comment by 304NotModified** [comment]
doubting if we need to keep this name in-sync

https://github.com/NLog/NLog.Extensions.Logging/blob/c3eb3ef3f99862735c27017fc7fa818744ea2648/test/LoggerTests.cs#L171

**Comment by snakefoot** [comment]
> doubting if we need to keep this name in-sync

Well the NLog-ParseMessageTemplate logic is not activated here, since a custom message formatter is use for Microsoft Extension Logging.
