### ISSUE TITLE
How to writes log messages to the MongoDB?

### ISSUE THREAD

**Issue by zhjunzh** [NLog/NLog#2350]
Hi, I wanted to use NLog to save log messages on the MongoDB, Is this support ?

**Comment by 304NotModified** [comment]
I think the database target could do that:

https://github.com/NLog/NLog/wiki/Database-Target

not sure what to take for dbProvider. It should be the full qualified name and dll

**Comment by 304NotModified** [comment]
there is also:

- https://github.com/Logrythmik/NLog.MongoDB
although not sure if it works: https://stackoverflow.com/questions/30594437/nlog-with-mongodb-connection-and-target

**Comment by snakefoot** [comment]
This seems newer:

https://github.com/loresoft/NLog.Mongo

Success story from someone:

https://stackoverflow.com/questions/38953210/storing-logs-in-a-mongo-database-using-nlog

**Comment by 304NotModified** [comment]
yes indeed, nuget link: https://www.nuget.org/packages/NLog.Mongo/

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, let us know!
