### ISSUE TITLE
Preferred way to write custom target which is sanitizing NLog message

### ISSUE THREAD

**Issue by ghost** [NLog/NLog#2352]
**Type**: Question

**NLog version**: 4.4.12

**Platform**: .Net 4.5

**Current NLog config**

```xml
<nlog>
  <targets>
    <default-wrapper xsi:type="AsyncWrapper">
      <wrapper-target xsi:type="SanitizingWrapper" />
    </default-wrapper>
    <target name="File" xsi:type="File" fileName="messages.log" encoding="UTF-8" layout="${message}" />
    <target name="Console" xsi:type="Console" layout="${message}" />
  </targets>
  <rules>
    <logger name="*" minlevel="Trace" writeTo="File"/>
    <logger name="*" minlevel="Trace" writeTo="Console" />
  </rules>
</nlog>

```

Hello,

I would like to write a custom wrapping target which is sanitizing NLog messages - what is the preferred way to modify AsyncLogEventInfo logEvent? I was thinking about following code:

```
protected override void Write(AsyncLogEventInfo logEvent)
{
    logEvent.LogEvent.Message = SanitizeMessage(logEvent.LogEvent.FormattedMessage);
    logEvent.LogEvent.Parameters = null;

    WrappedTarget.WriteAsyncLogEvent(logEvent);
}
```

but I'm not sure if this is a right way of doing it.

P.S. I don't want to do it via a custom layout as wrapping target is easier to configure once for all targets  (via the default-wrapper tag) and less error prone.

Thank you,
Best Regards,

**Comment by 304NotModified** [comment]
this approach looks good to me!

**Comment by AfterSanitizing** [comment]
Yeah, that seems to work, but I'm not sure about rewriting FormattedMessage to Message property and removing Parameters. Does FormattedMessage always contain the final message or does it depends on inner targets / layouts? What about exception logging (logger.Error(ex, "Message"))? What about performance (maybe creating a custom layout wrapper would be more reasonable - in that case a Message property is assigned only once)?

**Comment by 304NotModified** [comment]
> Does FormattedMessage always contain the final message or does it depends on inner targets / layouts?

It does contain the final version of `${message}`. The exception is logger by `${exception}`.

For a target wrapper this is the best approach, you need the formatted message and you can't set the formatted message (and so setting message is OK),

A better option is to create a layout renderer wrapper,  See for example: https://github.com/NLog/NLog/blob/master/src/NLog/LayoutRenderers/Wrappers/UppercaseLayoutRendererWrapper.cs

**Comment by AfterSanitizing** [comment]
Great, thank you!

**Comment by AfterSanitizing** [comment]
I've made some tests and wrapping layout is about 3 times slower than wrapping target (the same sanitizing method was used in both cases). Any idea why?

P.S. Input messages are rather big, 1MB and more.

**Comment by snakefoot** [comment]
> @AfterSanitizing wrapping layout is about 3 times slower than wrapping target 

Most performance issues can be solved by using a profiler, and then fix the places that are broken. You can consider to inherit from the WrapperLayoutRendererBuilderBase if you can do the tranformation inside the same StringBuilder (Maybe with some help from a local char-buffer).

**Comment by 304NotModified** [comment]
How are you sanitizing? Regex is slow of course.

**Comment by AfterSanitizing** [comment]
I'm not using Regex, instead I'm doing a loop trough the whole message and put valid chars / whole substrings into temporary StringBuilder. I'm not sure if I can use WrapperLayoutRendererBuilderBase, as I'm making an additional check to log level to run sanitization only on configured level.

Here is a fragment of my layout wrapper:

```
protected override void Append(StringBuilder stringBuilder, LogEventInfo logEvent)
{
	var inputMessage = RenderInner(logEvent);

	stringBuilder.Append(logEvent.Level <= _parsedMinLogLevel ? Transform(inputMessage) : inputMessage);
}

protected override string Transform(string inputText)
{
	return SanitizeMessage(inputText);
}
```

Maybe the performance difference comes from what you said - that LogEvent is reused between targets? The SanitizeMessage method is exactly the same in both target wrapper and layout wrapper.

Here is my nlog.config with all targets:

```
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      throwExceptions="true">

  <variable name="logDirectory" value="${basedir}/Logs/${shortdate}" />
  <variable name="logMessage" value="${level:uppercase=true} ${logger:uppercase=true} ${date} ${sanitizeMessage:inner=${message}}${onexception:${newline}${exception}" />

  <targets>
    <target name="FileAll" xsi:type="File" fileName="${logDirectory}/${shortdate}.log" layout="${logMessage}" encoding="UTF-8" />
    <target name="FileModule" xsi:type="File" fileName="${logDirectory}/${shortdate}_${logger}.log" layout="${logMessage}" encoding="UTF-8" />
    <target name="Console" xsi:type="Console" layout="${logMessage}" />
  </targets>

  <rules>
    <logger name="*" minlevel="Trace" writeTo="FileAll"/>
    <logger name="*" minlevel="Trace" writeTo="FileModule"/>
    <logger name="*" minlevel="Trace" writeTo="Console" />
  </rules>
</nlog>
```

**Comment by snakefoot** [comment]
@AfterSanitizing Have modified WrapperLayoutRendererBuilderBase to allow access to the LogEventInfo, so one can perform transformation based on LogEventInfo-details.

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, let us know!
