### ISSUE TITLE
Support for .NET Standard 1.4 / UWP

### ISSUE THREAD

**Issue by owlstack** [NLog/NLog#2370]
Is there support for .Net Standard 1.4 for NLog? Albeit I try to install it, nothing happens. 

**Type** (choose one):
- Question

**NLog version**: (e.g. 4.2.3)
Any version

**Platform**: .Net Standard 1.4

in case of a FEATURE REQUEST:
 
 - Why do we need it? Support for UWP app service

**Comment by snakefoot** [comment]
Only NLog 5.0 BETA supports UWP - https://www.nuget.org/packages/NLog/5.0.0-beta11

It is very stable and production ready.

**Comment by snakefoot** [comment]
Supporting UWP means not using System.Threading.Thread.

I guess when support is dropped for NET3_5 + SILVERLIGHT4, then we can consider changing to Tasks and remove all Thread-calls. But there are some Unity3D users that like the NET3_5 support.

But now that Windows Phone 10 is dead, then I think UWP will have a hard time, until something magically happens and Xamarin Forms merges together with UWP and becomes a GUI-platform for both Mac, Linux and Windows.

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, let us know!

**Comment by snakefoot** [comment]
@owlstack Seems your wish might become true. See also #2441 and #2440
