### ISSUE TITLE
Create SequenceId layout renderer

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#2373]
> at the moment the SequenceId is only available if Layout log4jxmlevent and includeNLogData=true. can we have the sequenceId also for other simple formats too?

See (issue 2): https://github.com/NLog/NLog/issues/107

**Comment by MikeFH** [comment]
Is someone working on this ? If not I can give it a try. 
At the moment the SequenceId is not persistent across restarts, is it needed ? If yes, does a mean to persist data across application restarts already exists ?
