### ISSUE TITLE
Issue starting application using NLog on some machines, seems Nlog config related

### ISSUE THREAD

**Issue by xxxsinx** [NLog/NLog#2376]
**Type** (choose one):
- Bug

**NLog version**: (e.g. 4.4.9)

**Platform**:  .Net 4.5

**Current NLog config** (xml or C#, if relevant)

<?xml version="1.0" encoding="utf-8" ?>

<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  
  <targets async="true">
    <target name="file" xsi:type="File" fileName="${basedir}/log.txt" />
    <target name="errorfile" xsi:type="File" fileName="${basedir}/errorlog.txt" layout="${longdate} ${message}${newline}${exception:format=type,message,method:maxInnerExceptionLevel=5:innerFormat=shortType,message,method}}${newline}${newline}"/>
  </targets>

  <rules>
    <logger name="*" minlevel="Trace" writeTo="file" />
    <logger name="*" minlevel="Error" writeTo="errorfile" />
    </rules>
</nlog>

- What is the current result?

We have several dozens of users using this app on their computer and 3-4 of them have this issue. Basically they start our application and absolutely nothing happens, no errors, nothing. When looking at Windows Event Viewer, we see it seems to be NLog related. We checked the config, checked for other configs on the machine(s), and we can't find anything obviously different from those 3-4 machines vs others. We have not been able to reproduce the issue on any of our development machines.

- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?

No, it seems that since the error is with the config file itself, adding anything to it would not get us anywhere

- Please post full exception details (message, stacktrace, inner exceptions)

Nom de l’application défaillante AideEstimation.exe, version : 1.0.2037.0, horodatage : 0x59ef4dbd | 10:44 AM
-- | --
Application : AideEstimation.exeVersion du Framework : v4.0.30319Description : le processus a été arrêté en raison d'une exception non gérée.Informations sur l'exception : System.Xml.XmlException   à System.Xml.XmlTextReaderImpl.Throw(System.Exception)   à System.Xml.XmlTextReaderImpl.ParseDocumentContent()   à System.Xml.XmlTextReaderImpl.Read()   à System.Xml.XmlTextReader.Read()   à System.Configuration.XmlUtil..ctor(System.IO.Stream, System.String, Boolean, System.Configuration.ConfigurationSchemaErrors)   à System.Configuration.BaseConfigurationRecord.InitConfigFromFile()Informations sur l'exception : System.Configuration.ConfigurationErrorsException   à System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean)   à System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(System.Configuration.ConfigurationSchemaErrors)   à System.Configuration.BaseConfigurationRecord.ThrowIfInitErrors()   à System.Configuration.ClientConfigurationSystem.OnConfigRemoved(System.Object, System.Configuration.Internal.InternalConfigEventArgs)Informations sur l'exception : System.Configuration.ConfigurationErrorsException   à System.Configuration.ClientConfigurationSystem.OnConfigRemoved(System.Object, System.Configuration.Internal.InternalConfigEventArgs)   à System.Configuration.Internal.InternalConfigRoot.OnConfigRemoved(System.Configuration.Internal.InternalConfigEventArgs)   à System.Configuration.Internal.InternalConfigRoot.RemoveConfigImpl(System.String, System.Configuration.BaseConfigurationRecord)   à System.Configuration.BaseConfigurationRecord.GetSectionRecursive(System.String, Boolean, Boolean, Boolean, Boolean, System.Object ByRef, System.Object ByRef)   à System.Configuration.BaseConfigurationRecord.GetSection(System.String)   à System.Configuration.ClientConfigurationSystem.System.Configuration.Internal.IInternalConfigSystem.GetSection(System.String)   à System.Configuration.ConfigurationManager.GetSecti | 10:44 AM
<?xml version="1.0" encoding="utf-8" ?><nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">    <targets async="true">    <target name="file" xsi:type="File" fileName="${basedir}/log.txt" />    <target name="errorfile" xsi:type="File" fileName="${basedir}/errorlog.txt" layout="${longdate} ${message}${newline}${exception:format=type,message,method:maxInnerExceptionLevel=5:innerFormat=shortType,message,method}}${newline}${newline}"/>  </targets>  <rules>    <logger name="*" minlevel="Trace" writeTo="file" />    <logger name="*" minlevel="Error" writeTo="errorfile" />    </rules></nlog>

- Are there any work arrounds?

Short of formatting the computer and starting anew we have not found any work around.

- Is there a version in which it did worked? 

We have dozens of other users who run the same exact code/config with no issues

- Can you help us by writing an unit test?

We cannot reproduce it on our own machine, so I guess we're out of luck on that one.

Any help would be appreciated!

Alex.

**Comment by snakefoot** [comment]
Don't think this is related to NLog (Cannot see any NLog in the stacktrace), but that the AppData folder of the application is broken:

https://www.google.dk/search?q=ClientConfigurationSystem+OnConfigRemoved

Maybe catch the exception, and make backup of the old configuration, and then reset the configuration:

https://stackoverflow.com/questions/2269489/c-sharp-user-settings-broken

**Comment by 304NotModified** [comment]
if it is NLog, there seems to something wrong with your XML. (System.Xml.XmlException)

please share your nlog config

**Comment by xxxsinx** [comment]
Alright, problem is solved following Snakefoot's guidance. Turns out the user.config file was empty. Sorry to have assumed it was NLOG, we've had a very similar issue with the NLOG config a while back and I wrongfully assumed this was the same issue. In fact, looking back at it I'm now guessing those cases we had before were probably empty NLOG configs in the appData folder perhaps. 

In any case, thanks for the help, this is now resolved.

**Comment by 304NotModified** [comment]
OK thanks for the feedback!

**Comment by xxxsinx** [comment]
Hello again,

Not sure if it's possible to re-open the issue, or if I should create a new one... But here goes, the NLOG issue I thought we were having when I initially create this issue has popped up again. The user.config doesn't seem to be the issue this time around and we can't figure what's going on. The NLOG config on the machine is valid and the same as all other machines we run this on (config is in the installation folder of the app).

This is the stack trace we get in the Event Viewer (NLOG part is at the end ---- getting a logger instance is the first thing the app does when it starts):

`Version du Framework : v4.0.30319
Description : le processus a été arrêté en raison d'une exception non gérée.
Informations sur l'exception : System.Xml.XmlException
   à System.Xml.XmlTextReaderImpl.Throw(System.Exception)
   à System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   à System.Xml.XmlTextReaderImpl.Read()
   à System.Xml.XmlTextReader.Read()
   à System.Configuration.XmlUtil..ctor(System.IO.Stream, System.String, Boolean, System.Configuration.ConfigurationSchemaErrors)
   à System.Configuration.BaseConfigurationRecord.InitConfigFromFile()

Informations sur l'exception : System.Configuration.ConfigurationErrorsException
   à System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean)
   à System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(System.Configuration.ConfigurationSchemaErrors)
   à System.Configuration.BaseConfigurationRecord.ThrowIfInitErrors()
   à System.Configuration.ClientConfigurationSystem.OnConfigRemoved(System.Object, System.Configuration.Internal.InternalConfigEventArgs)

Informations sur l'exception : System.Configuration.ConfigurationErrorsException
   à System.Configuration.ClientConfigurationSystem.OnConfigRemoved(System.Object, System.Configuration.Internal.InternalConfigEventArgs)
   à System.Configuration.Internal.InternalConfigRoot.OnConfigRemoved(System.Configuration.Internal.InternalConfigEventArgs)
   à System.Configuration.Internal.InternalConfigRoot.RemoveConfigImpl(System.String, System.Configuration.BaseConfigurationRecord)
   à System.Configuration.BaseConfigurationRecord.GetSectionRecursive(System.String, Boolean, Boolean, Boolean, Boolean, System.Object ByRef, System.Object ByRef)
   à System.Configuration.BaseConfigurationRecord.GetSection(System.String)
   à System.Configuration.ClientConfigurationSystem.System.Configuration.Internal.IInternalConfigSystem.GetSection(System.String)
   à System.Configuration.ConfigurationManager.GetSection(System.String)
  à NLog.Config.XmlLoggingConfiguration.get_AppConfig()
   à NLog.LogFactory.get_Configuration()
   à NLog.LogFactory.GetLogger(LoggerCacheKey)
   à NLog.LogFactory.GetLogger(System.String)
   à NLog.LogManager.GetLogger(System.String)
   à Gdtm.AideEstimation.Program.Main()
`

Any ideas how I can fix this?

**Comment by snakefoot** [comment]
Now it looks like NLog. What version of Nlog are you using? Have you tried upgrading to Nlog 4.4.12? Is nlog throwexceptions=false ? Can you copy paste the contents of the exe-app-config file ? Is it a valid XML file? Can you try and catch the exception and display the exception message?



Sent from my Samsung device


-------- Original message --------

**Comment by xxxsinx** [comment]
Looks like we're running Nlog 4.3.5... 

This is the only reference to NLOG I see in the app.config (I'd rather not post all of it as it contains lots of info I'd rather not put out publicly). Bottom line though is all users are using the same app.config... and this happens for a handful of players out of close to a hundred:

      <dependentAssembly>
        <assemblyIdentity name="NLog" publicKeyToken="5120e14c03d0593c" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.0.0" newVersion="4.0.0.0" />
      </dependentAssembly>

I'll experiment with nlog throwexceptions and trying to catch the exception and report back.

**Comment by snakefoot** [comment]
Will probably help to upgrade nlog. but then it will ignore any nlog config from app settings

See https://github.com/NLog/NLog/issues/1772



Sent from my Samsung device


-------- Original message --------

**Comment by 304NotModified** [comment]
as this is fixed in 4.4 and 'cause of inactivity, I will close this one.
