### ISSUE TITLE
Nlog and UWP (on 5.0.0 beta 11)

### ISSUE THREAD

**Issue by andyphilpotts** [NLog/NLog#2380]
After some effort I was able to configure a file writer, but I also want to be able to route logging to the debug window when running out of Visual Studio

If I try to configure a Debugger based target I get an exception as soon as I try to access the configuration, without the Debugger target, no exception...

{NLog.NLogConfigurationException: Exception when parsing c:\src\Funnel2\Funnel2\bin\x64\Debug\AppX\NLog.config.  ---> System.ArgumentException: Target cannot be found: 'Debugger'
   at NLog.Config.Factory`2.CreateInstance(String name)
   at NLog.Config.XmlLoggingConfiguration.ParseTargetsElement(NLogXmlElement targetsElement)
   at NLog.Config.XmlLoggingConfiguration.ParseNLogElement(NLogXmlElement nlogElement, String filePath, Boolean autoReloadDefault)
   at NLog.Config.XmlLoggingConfiguration.Initialize(XmlReader reader, String fileName, Boolean ignoreErrors)
   --- End of inner exception stack trace ---
   at NLog.Config.XmlLoggingConfiguration.Initialize(XmlReader reader, String fileName, Boolean ignoreErrors)
   at NLog.Config.XmlLoggingConfiguration..ctor(String fileName, Boolean ignoreErrors, LogFactory logFactory)
   at NLog.LogFactory.LoadLoggingConfiguration(String configFile)
   at NLog.LogFactory.get_Configuration()
   at Funnel2.App..ctor()
   at Funnel2.Program.<>c.<Main>b__0_0(ApplicationInitializationCallbackParams p)}
                        Target cannot be found: 'Debugger'

Here is how I initialize:

            NLog.LogManager.ThrowExceptions = true;

            var localFolder = Windows.Storage.ApplicationData.Current.LocalFolder;
            System.Diagnostics.Debug.WriteLine($"Local path={localFolder.Path}");

            NLog.LogManager.Configuration.Variables["logPath"] = localFolder.Path;

Here is my config

<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <targets>
    <target name="logfileTarget" xsi:type="File" fileName="${var:logPath}\funnel2.log" />
    <target name="debugTarget" xsi:type="Debugger" layout="${logger}::${message}"/>
  </targets>

  <rules>
    <logger name="*" minlevel="Debug" writeTo="logfileTarget" />
    <logger name="*" minlevel="Trace" writeTo="debugTarget" />
  </rules>
</nlog>

**Comment by andyphilpotts** [comment]
Seems the config did not get copied correctly, this is what it looks like

```
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <targets>
    <target name="logfileTarget" xsi:type="File" fileName="${var:logPath}\funnel2.log" />
    <target name="debugTarget" xsi:type="Debugger" layout="${logger}::${message}"/>
  </targets>

  <rules>
    <logger name="*" minlevel="Debug" writeTo="logfileTarget" />
    <logger name="*" minlevel="Trace" writeTo="debugTarget" />
  </rules>
</nlog>

```

**Comment by snakefoot** [comment]
Please look at the platform support, to see what works with NetStandard 1.3

https://github.com/NLog/NLog/wiki/Platform-Support

**Comment by andyphilpotts** [comment]
Thanks, I should have spotted that before, I suspect OutputDebugString will do what I need
