### ISSUE TITLE
Nlog ${callsite-linenumber} not working properly with async methods

### ISSUE THREAD

**Issue by issatayev** [NLog/NLog#2382]
I am using NLog v4.4.12.

I have an async method where I must log info with line numbers being included. The problem is that if I log anything before a call to async method, line lumber is always 0. However, if I log anything after a call to async method, line number always prints correctly.

    public class TestController : ApiController {
        private static HttpClient Client = new HttpClient(new HttpClientHandler { Proxy = null, UseProxy = false }){ Timeout = TimeSpan.FromSeconds(double.Parse(WebConfigurationManager.AppSettings["httpTimeout"])) };
        private static readonly Logger logger = LogManager.GetCurrentClassLogger();

        public async Task DoSomething(int clientId)
        {
            logger.Info($"Here, line number is always 0");

            try
            {
                var clientBooks = new List<string>();
                Client.DefaultRequestHeaders.Accept.Clear();
                Client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                using (var response = await Client.GetAsync(new Uri(WebConfigurationManager.AppSettings["cb"] + "books?clientId=" + clientId)))
                {
                    if (response.IsSuccessStatusCode)
                    {
                        clientBooks = await response.Content.ReadAsAsync<List<string>>();
                    }
                    else
                    {
                         throw new Exception($"Error getting books");
                    }
                }

                logger.Info($"Here, line number always prints correctly");

                // Here I have some other logic ...
            }
            catch (Exception ex)
            {
                logger.Error(ex);
            }

            logger.Info($"Here, line number always prints correctly");
        }
    }

My NLog configuration:

```
<nlog autoReload="true" xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <variable name="logDirectory" value="${basedir}/Logs/${shortdate}" />
    <variable name="format" value="${longdate}|${activityid}|${logger}|Line:${callsite-linenumber}|${level:uppercase=true}|${message}" />
    <targets>
      <target name="fileLogErrors" xsi:type="File" fileName="${logDirectory}/errors.txt" layout="${format}" encoding="utf-8" />
      <target name="fileLog" xsi:type="File" fileName="${logDirectory}/all.txt" layout="${format}" encoding="utf-8" />
    </targets>
    <rules>
      <logger name="*" minlevel="Warn" writeTo="fileLogErrors" />
      <logger name="*" minlevel="Info" writeTo="fileLog" />
    </rules>
 </nlog>
```

Here is the log that I have after running actual code (log format is ${stacktrace}|Line:${callsite-linenumber}):

```
AsyncTaskMethodBuilder.Start => <<UpdateAttributes>b__0>d.MoveNext => AttributesBaseController.UpdateEquationAccountsInfo|Line:0
ExecutionContext.RunInternal => MoveNextRunner.InvokeMoveNext => <UpdateEquationAccountsInfo>d__9.MoveNext|Line:457
```

**Comment by snakefoot** [comment]
Was able to reproduce the case:

![image](https://user-images.githubusercontent.com/11509660/32630309-833aff92-c59c-11e7-99eb-4a34ca052f7b.png)

NLog correctly detects the MoveNext() and skips it. But funny enough the line-number is valid on MoveNext and not on WriteMessages:

```
        private static async Task WriteMessages(Logger logger, int count)
        {
            logger.Info($"Here, line number is always 0");

            try
            {
                await Task.Delay(1000);

                logger.Info($"Here, line number always prints correctly");

                // Here I have some other logic ...
            }
            catch (Exception ex)
            {
                logger.Error(ex);
            }

            logger.Info($"Here, line number always prints correctly");
        }
```

**Comment by snakefoot** [comment]
I guess the correct solution is changing LogEventInfo.UserStackFrameNumber so it doesn't attempt to skip MoveNext, but let the layoutrenderer handle it instead.
