### ISSUE TITLE
Nlog to Event log with multiple event data

### ISSUE THREAD

**Issue by arifulhoque** [NLog/NLog#2391]
I have raised this question in Stackoverflow. So far no luck anybody answering. I am raising it here hoping that I might get some help. 

https://stackoverflow.com/questions/47302621/nlog-logging-to-event-log-with-multiple-event-data

**Comment by snakefoot** [comment]
Looks like you are not alone:

https://social.msdn.microsoft.com/Forums/en-US/22a091aa-a4cd-4c18-ba6d-fb7859578d60/c-windows-event-log-custom-data?forum=csharplanguage

This guy is able to use the new EventSouce (NET4.5+) from PowerShell:

https://blogs.technet.microsoft.com/kevinholman/2016/04/02/writing-events-with-parameters-using-powershell/
https://msdn.microsoft.com/en-us/library/system.diagnostics.tracing.eventsource(v=vs.110).aspx

And this guy has also found a way using the EventLog-object directly:

https://stackoverflow.com/questions/21448509/how-to-add-names-to-data-entries-in-event-viewer-eventdata-using-c-sharp

Maybe you can use this knowledge to create your own custom target, and then make a PR to this repository, when you have something that works:

https://github.com/NLog/NLog/wiki/How-to-write-a-custom-target

**Comment by arifulhoque** [comment]
@snakefoot Thanks for your comment. My question was if I can add multiple <Data> element using nlog. I know that I can use EventLog.WriteEntry which will add in individual <Data> entries. As I am using nlog to log to Event log, my questions was is there way nlog can do this?

**Comment by snakefoot** [comment]
@arifulhoque My answer would be to look at the documentation:

https://github.com/nlog/NLog/wiki/EventLog-target

And if nothing was found in the documentation, then look at the code and see if there is logic matching the above articles:

https://github.com/NLog/NLog/blob/master/src/NLog/Targets/EventLogTarget.cs

And if the code doesn't reveal the wanted feature, then please create a pull-request :)

**Comment by 304NotModified** [comment]
Has your question being answered?

**Comment by arifulhoque** [comment]
Yes. NLog current EventLog does not do what I need.

**Comment by 304NotModified** [comment]
OK, it's a bit unclear to me what we have to change in the eventlog to support this. If you think this is needed, please open a new github issue with the feature request (or just send a PR ;) - thx!
