### ISSUE TITLE
Any milestone for FormattableString?

### ISSUE THREAD

**Issue by Anapher** [NLog/NLog#2397]
**Type** (choose one):
- Feature request

**NLog version**: 5.0.0-beta11
**Platform**:  .NET Core 

Hey,
there's a new type in .Net called [FormattableString](https://msdn.microsoft.com/de-de/library/system.formattablestring(v=vs.110).aspx). With the [Interpolated Strings](https://docs.microsoft.com/en-gb/dotnet/csharp/language-reference/keywords/interpolated-strings), string.Format is now almost obsolete. The only relevant usage of string.Format was for me in NLog because of performance reasons when the message is not needed (yeah, technically I don't really use string.Format bymyself but I mean overloads like `Log(string message, params object[] args)`). With the new data type, it's now possible to don't immediately apply the format on the interpolated string but just give the format with the arguments to the method (like your overload with `params` does). IMO, it is far more comfortable to use Interpolated Strings and it would be nice if you would also support it in NLog.

Just a small code sample in case that you didn't get what FormattableString does:
```csharp
        public void Warn(FormattableString message)
        {
            if (IsWarnEnabled)
            {
                WriteToTargets(LogLevel.Warn, message.Format, message.GetArguments());
            }
        }

//and now, just call
Warn($"Hello NLog, you are {ComplimentGenerator.Generate()}.");
```

**Comment by 304NotModified** [comment]
We really like to support this,but we can't. The overload with the string argument takes precedence. :(

See #825

**Comment by Anapher** [comment]
Wow, I'm sorry for the duplicate, seems like i made a typo when searching for already existing issues...
I read the other issue and I get your problem, I think the best for me would be to write different-named extension methods (maybe something like `FInfo()`, etc...). Thank you.
