### ISSUE TITLE
Move WCF targets into seperate package for NetStandard2.0

### ISSUE THREAD

**Issue by snakefoot** [NLog/NLog#2400]
Instead of having extra dependencies for NetStandard2.0, then it could be nice if there was a dedicated WCF-nuget-package (Just like MailKit)

**Comment by 304NotModified** [comment]
true, the core of NLog 5 (or 6) should be as dependency free as possible

**Comment by snakefoot** [comment]
Think the core of NLog 4.5 NetStandard should be dependency free by default.

**Comment by 304NotModified** [comment]
aren't those breaking changes?
