### ISSUE TITLE
Add Support for Windows 8 Store Applications

### ISSUE THREAD

**Issue by ngbrown** [NLog/NLog#242]
This would be something similar to the Silverlight support, but with different networking code.

**Comment by 304NotModified** [comment]
Is this uap/uwp?

**Comment by ngbrown** [comment]
@304NotModified At the time, it was Windows 8/8.1.   Now, it would be Windows 8/8.1, and 10 (UAP) It should probably be a portable class library (with sections stubbed out as necessary) with per-platform builds to swap in what is needed for each platform.  See http://log.paulbetts.org/the-bait-and-switch-pcl-trick/

**Comment by 304NotModified** [comment]
Well we are moving to the netstandard 1.4 soon (when .NET CORE rc2 is released) and will try to move to netstandard 1.2 

See:
https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md#mapping-the-net-platform-standard-to-platforms

Any idea if that is good enough? 

PS: PCL will be replaced with netstandard  AFAIK

**Comment by snakefoot** [comment]
Seems NetStandard 1.2 is the last version to be supported by Windows 8.1:

https://docs.microsoft.com/en-us/dotnet/articles/standard/library

So NetStandard 1.3 or 1.4 cannot be used. Sadly enough FileStream arrives with NetStandard 1.3, so NetStandard 1.2 is not very interesting.

**Comment by 304NotModified** [comment]
I think wp8 is dead already.

**Comment by 304NotModified** [comment]
For the current perspective we will support .NET standard, and won't focus on Windows 8 any more
