### ISSUE TITLE
Why i'm getting frequent Nlog not found error ?

### ISSUE THREAD

**Issue by CodeGanesha** [NLog/NLog#2424]
I have an class library project name "Infrastructure", when I do restore nuget packages in visual studio I get error for Nlog only - not found, the details can be found on attached png file. I tried using different version of Nuget, but no luck. Thank you all.
![vs](https://user-images.githubusercontent.com/31499980/33260985-72290546-d389-11e7-8f02-336823acbfd5.png)

**Comment by 304NotModified** [comment]
Not sure which version you are trying to install, but there isn't a 2.0.0 of nlog. See versions on https://www.nuget.org/packages/NLog

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, let us know!

**Comment by CodeGanesha** [comment]
Didn't got rid of error. During restore nuget packages, I get error for
Nlog 2.0.0 frequently, although I tried latest versions too.

**Comment by 304NotModified** [comment]
What package and version are you trying to install?

I see common.logging.nlog in your screenshot?

We need more info to help you with this

**Comment by CodeGanesha** [comment]
Thank you sir, I got it solved. The problem was with nuget package manager.
I used the old version of nuget package manager and did clean restore and
got it solved. Thank you again for replying.

**Comment by 304NotModified** [comment]
Glad it has been resolved :+1:
