### ISSUE TITLE
Upload file target archives to cloud

### ISSUE THREAD

**Issue by adyshimony** [NLog/NLog#2426]
Hi,

Is it possible to know when a log is archived, so at that point I can upload it to the cloud?

We have a log that save 5 archives (maxArchiveFiles="5")
We want to to upload the log every time it's archived.

Thanks,

Ady.

**Comment by 304NotModified** [comment]
Unfortunately this isn't possible currently.

When we add an event on the filetarget, would that help in your case?

**Comment by adyshimony** [comment]
Sure, looks like simple event invoking.
I will update #1249

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, let us know!
