### ISSUE TITLE
New Method SetLevel(minLevel, maxLevel) on LoggingRule

### ISSUE THREAD

**Issue by stjephan** [NLog/NLog#2427]
**Type: Feature Request** 

**What needed:**
New Method SetLevel(LogLevel minLevel, Level maxLevel) on LoggingRule

**Why:**
At the moment there are only the following methodes availbale:

```
EnableLoggingForLevels(minLevel, maxLevel); 
EnableLoggingForLevel(level); 
DisableLoggingForLevel(level); 

```
As a result of that I first need to iterate over all levels and disable them, after that I can set the new required levels.

It's a "nice to have" but makes the using a bit simpler.

**Comment by 304NotModified** [comment]
fixed by @MikeFH , thanks!
