### ISSUE TITLE
Add structured logging docs

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#2432]
Add docs how to use and configure structured logging.

on nlog.-project.org or on the wiki. 

---

> snakefoot commented 12 minutes ago •  edited 
@304NotModified Can you give an example of what kind of docs you are looking for about structured logging, besides those written at https://messagetemplates.org/ ?

something like that but then on the wiki or nlog-project.org. Maybe also needed:

- [x] Why /  Pro and cons vs regular logging
- [x] Simple examples
- [x] Exceptional cases (e.g. mixing numeric and names, non-unique names)
- [x] Recommendations (maybe too opinion based?)
- [x] Default formating
- [x] How to tune formatting (e.g. `@user`, `$user`, `value:000`
- [x] The new settings in the (XML) config
- [x] `IJsonConverter` / `IValueSerializer`  -`ConfigurationItemFactory.JsonConverter ` / `ConfigurationItemFactory.ValueSerializer`

**Comment by 304NotModified** [comment]
> snakefoot commented 12 minutes ago •  edited 
@304NotModified Can you give an example of what kind of docs you are looking for about structured logging, besides those written at https://messagetemplates.org/ ?

something like that but then on the wiki or nlog-project.org. Maybe also needed:

- Exceptional cases (e.g. mixing numeric and names, non-unique names)
- pro and cons vs regular logging
- recommendations (maybe too opinion based?)
- Format of serialisation and how to tune it
- The new settings in the (XML) config

**Comment by snakefoot** [comment]
Have made an attempt here:

https://github.com/NLog/NLog/wiki/How-to-use-structured-logging

**Comment by 304NotModified** [comment]
cool! 

i've added syntax highlight

do you think the names of the holes should be camelCase? In Serilog/MessageTemplates those are PascalCase. Of course, everything is allowed, but examples are important

**Comment by snakefoot** [comment]
> do you think the names of the holes should be camelCase?

No opinion, not a JSON man (yet).

**Comment by 304NotModified** [comment]
good one, in javascript properties are camelCase for properties and methodes (in contrast to C#, where it's PascalCase)

**Comment by bruceliu2008** [comment]
If the target is database, Will the message template be stored? I didn't find something like messagetemplate column in the [database target](https://github.com/nlog/NLog/wiki/Database-target).

Thanks,

**Comment by snakefoot** [comment]
If you read the wiki for databasetarget, then you will know that input comes from the parameters.

You specify a Layout for a target-parameter, that captures the message template. ${message:raw=true}

See also the wiki for the message layout renderer



Sent from my Samsung device


-------- Original message --------

**Comment by bruceliu2008** [comment]
Thanks,
Is it possible to store both the message and template as two columns?

**Comment by snakefoot** [comment]
If you read the wiki for message layout renderer, then the formatted message is provided by ${message}


Sent from my Samsung device


-------- Original message --------

**Comment by 304NotModified** [comment]
@snakefoot I saw your edit. I Think i'm done editing.

**Comment by snakefoot** [comment]
@304NotModified Have updated the JSON.NET Example to reduce allocations.

**Comment by 304NotModified** [comment]
👍

**Comment by snakefoot** [comment]
@304NotModified Have you just performed a force push on the master-branch. Looks like all PRs are now in bad state.

**Comment by 304NotModified** [comment]
oops. Well I forgot I cannot change the release notes of a pushed package on nuget.org anymore. :(

So need to change it first, before updating the buildnumber

**Comment by 304NotModified** [comment]
I removed the last commit. 

> Looks like all PRs are now in bad state.

I don't see that?

**Comment by 304NotModified** [comment]
edit: fixed

**Comment by snakefoot** [comment]
> edit: fixed

Now the PRs looks good again.

**Comment by 304NotModified** [comment]
@snakefoot do you think that https://github.com/NLog/NLog/wiki/platform-support is up-to-date?

**Comment by snakefoot** [comment]
@304NotModified Yes I believe so.
