### ISSUE TITLE
NLog.Schema + NLog.Config for new csproj file format

### ISSUE THREAD

**Issue by luigiberrettini** [NLog/NLog#2434]
**Bug**

**NLog version**: 4.4.12

In case of a BUG:

- What is the current result?
XSD added to %USERPROFILE%\.nuget\packages

- What is the expected result?
XSD added to referencing project folder

- Are there any work arrounds? yes/no

- Is there a version in which it did worked? 
https://github.com/NuGet/Home/issues/4803

**Comment by 304NotModified** [comment]
hi!

Any idea how to fix this?

**Comment by 304NotModified** [comment]
this is also an issue for nlog.config I guess

**Comment by luigiberrettini** [comment]
A csproj to replace the schema nuspec can help if the xsd is packed into
the contentFiles folder.
I am working on the same issue forthe Syslog target and will let you know
as soon as I validate my solution.

**Comment by 304NotModified** [comment]
:+1: thanks!

**Comment by 304NotModified** [comment]
Would be great if I could add this for NLog 4.5 rc2 ;)

**Comment by luigiberrettini** [comment]
You should run `dotnet pack --no-build` in a folder with a `NLog.Schema.csproj` file like the following one:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net45;netstandard2.0</TargetFrameworks>

    <Product>NLog.Schema</Product>
    <Copyright>Copyright info</Copyright>

    <Company>Company info</Company>
    <Authors>Authors info</Authors>
    <PackageId>NLog.Schema</PackageId>
    <Title>NLog schema for Intellisense™</Title>
    <Description>Enables Intellisense™ for NLog settings in NLog.config</Description>
    <PackageTags>NLog Log Logging Intellisense xsd</PackageTags>
    <Version>0.1.0-alpha-01-commitHash</Version>
    <PackageLicenseUrl>https://github.com/NLog/NLog/blob/master/LICENSE</PackageLicenseUrl>
    <PackageProjectUrl>https://github.com/NLog/NLog</PackageProjectUrl>
    <PackageIconUrl>http://nlog-project.org/NConfig.png</PackageIconUrl>
    <RepositoryUrl>https://github.com/NLog/NLog</RepositoryUrl>
    <PackageReleaseNotes>https://github.com/NLog/NLog/releases/tag/v0.1.0-alpha-01-commitHash</PackageReleaseNotes>
    <RepositoryType>Git</RepositoryType>
  </PropertyGroup>

  <PropertyGroup>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <EnableDefaultItems>false</EnableDefaultItems>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="NLog.xsd" Pack="true" PackagePath="$(ContentTargetFolders)" />
  </ItemGroup>
</Project>
```

**Comment by 304NotModified** [comment]
FYI the current nuspec https://github.com/NLog/NLog/blob/master/src/NuGet/NLog.Schema/NLog.Schema.nuspec

**Comment by luigiberrettini** [comment]
You should migrate NuSpec tags to the csproj and then remove the NuSpec and only use the csproj with the dotnet CLI
