### ISSUE TITLE
nlog not logging on production environment, fine locally

### ISSUE THREAD

**Issue by piercy** [NLog/NLog#2435]
Hi, im having an issue with nlog not logging on our production servers but logging fine locally.  Originally i was logging to elastic, but ive since stripped that back and am just trying to log to a file.  I dont believe it to be permission based as the internal log file outputs fine to the same folder.

**Type** (choose one):

- Bug

**NLog version**:  4.4.12

**Platform**:  .Net 4.5 

**Current NLog config** (xml or C#, if relevant)

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd ..\..\NLog.xsd"
      autoReload="true"
      throwExceptions="true"
      internalLogLevel="Trace" internalLogFile="c:\gators\logs\nlog-creator-internal.log">

	<extensions>
		<add assembly="NLog.Targets.ElasticSearch"/>
		<add assembly="NLog.Web"/>
		<add assembly="GatorForms.Web"/>
		<add assembly="GatorForms.Common"/>
	</extensions>

	<variable name="branch" value="Test" />
	<variable name="application" value="GatorCreator" />
	
	<targets>
		<target name="logfile" xsi:type="File" fileName="c:\gators\logs\creator-output.txt" />
	</targets>

	<rules>
		<logger name="*" minlevel="Debug" writeTo="logfile" />
	</rules>
</nlog>
```

In case of a BUG:

- What is the current result?
I get internalLogFile traces but the actual log file doesnt get created at all.  This does work locally though.

- What is the expected result?
The log file be created.
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
Yes
- Please post full exception details (message, stacktrace, inner exceptions)
There are no exceptions.

I replaced some of our server paths with [removed] for security reasons
.
Internal log from the server (this doesnt log):
https://pastebin.com/pHeB5SUc

Internal log from the local (this does work):
https://pastebin.com/6QThExXf

note the couple of extra lines at the bottom which show it opening a file. These dont exist on the internal log of the server version.

- Are there any work arrounds? No
- Is there a version in which it did worked? No
- Can you help us by writing an unit test? No

**Comment by 304NotModified** [comment]
could you please try without the `<extensions>`?

Also, is this an asp.net application?

**Comment by piercy** [comment]
It's and MVC web api.

So, removing that didnt have an effect. However, the problem has now changed slightly, Since ive now travelled, i had to re log in again which actually triggered a different bit of logging than i was expecting.  So I am now getting logging lines back, i'm just expecting more than I am getting.

>2017-11-30 19:05:19.3736|INFO|GatorForms.Web.Controllers.EditorController|getformbydisplayid: lz

I suspect this has something to do with it being a different assembly. The assembly im not getting logging from is GatorForms.Common (specifically, GatorForms.Common.Services.AuditLog.AuditLogService which you can see in the internal logs).

This now leads me to believe it might be something to do with needing to reference the assembly in some way.  

Here is the internal log: https://pastebin.com/TAmkFZvf

As you can see its is now opening the file and logging, but im not seeing logging lines for the AuditLogService.  The interesting part  is every time i try trigger the audit service logging, i get the below lines logged in the internal log.  Im not sure if this is normal behavior or indicates some kind of problem?

`2017-11-30 19:12:19.2514 Debug Targets for GatorForms.Common.Services.AuditLog.AuditLogService by level:
2017-11-30 19:12:19.2514 Debug Trace =>
2017-11-30 19:12:19.2514 Debug Debug => logfile
2017-11-30 19:12:19.2514 Debug Info => logfile
2017-11-30 19:12:19.2514 Debug Warn => logfile
2017-11-30 19:12:19.2514 Debug Error => logfile
2017-11-30 19:12:19.2514 Debug Fatal => logfile`

Thanks,

**Comment by 304NotModified** [comment]
Is this still an issue?

**Comment by piercy** [comment]
yes this is still an issue, it seems i only get logging from the main project in the solution, the referenced assemblies (that also have logging) dont give any output.  I couldnt find anything in the docs to say that it needs to be referenced manually so not sure what to do for the moment.

**Comment by piercy** [comment]
Ok, i tried this again today. Took it all the way back to a small console app. Tested the scenario and it worked.  I then put those configs back into the main project and it all seems to be working now.

I'm honestly not sure what has changed between this configuration and previous. It seems mostly identical but it at least proves it was something config related and not something to do with nlog.

**Comment by piercy** [comment]
Example configs for anyone seeing this in the future.  I went a bit overboard in the end but heres what i ended up with.

**nlog.config**
`<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" autoReload="true">

	<variable name="application" value="Product1234" />
	<variable name="branch" value="Test" />

	<include file="${basedir}/App_Data/nlog-targets.config"/>

	<rules>
		<logger name="*" minlevel="Debug" writeTo="elastic" />
	</rules>
</nlog>`

**nlog-targets.config**
`<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

<targets>
	<target name="file" xsi:type="File"
			fileName="C:\Repositories\logs\SSO-output.log"
			layout="[${longdate}] [${uppercase:${level}}] [${logger}] ${message} ${exception:format=tostring}"
			concurrentWrites="false" keepFileOpen="false"/>
	<target name="console" xsi:type="ColoredConsole"
			layout="[${longdate}] [${uppercase:${level}}] [${logger:shortName=true}] ${message} ${exception:format=tostring}" />

	<target name="elastic" xsi:type="BufferingWrapper" flushTimeout="50">
		<target xsi:type="ElasticSearch"
				uri="xxxxx"
				index="app-${level}-${date:format=yyyy.MM.dd}"
				requireAuth="true"
				layout="${structuredlogging.json}"
				userName="xxx"
				password="xxx"
				documentType="application-nlog">
			<field name="Environment" layout="${branch}" />
			<field name="EventDateTime" layout="${date:s}" />
			<field name="EventLevel" layout="${level}" />
			<field name="UserName" layout="${identity:authType=false:isAuthenticated=false}" />
			<field name="AuthType" layout="${aspnet-user-authtype}" />
			<field name="MachineName" layout="${machinename}" />
			<field name="Logger" layout="${logger}" />
			<field name="Action" layout="${event-properties:item=Action}" />
			<field name="Account" layout="${event-properties:item=Account}" />
			<field name="ModifiedBy" layout="${event-properties:item=ModifiedBy}" />
			<field name="DateTime" layout="${event-properties:item=DateTime}" />
			<field name="IpAddress" layout="${event-properties:item=IpAddress}" />
			<field name="EventMessage" layout="${message}" />
			<field name="ErrorSource" layout="${exception-data:format=source}" />
			<field name="StackTrace" layout="${exception-data:format=stacktrace}" />
			<field name="ErrorMethod" layout="${exception-data:format=method}" />
			<field name="ErrorMessage" layout="${exception-data:format=message}" />
			<field name="InnerErrorMessage" layout="${exception-data:format=innerexceptionmessage}" />
			<field name="Application" layout="${application}" />
			<field name="CallSite" layout="${callsite}" />
			<field name="ThreadName" layout="${threadname}" />
			<field name="BaseDirectory" layout="${basedir}" />
			<field name="Varnish" layout="${aspnet-request:serverVariable=HTTP_X_VARNISH}"/>
			<field name="SessionId" layout="${aspnet-sessionid}"/>
			<field name="IISSiteName" layout="${iis-site-name}"/>
			<field name="URL" layout="${aspnet-request:serverVariable=URL}${aspnet-request:queryString}"/>
		</target>
	</target>

</targets>
</nlog>`

**Comment by 304NotModified** [comment]
Ok glad it has been solved!

**Comment by cuongnc5** [comment]
hi @piercy

Can you share your structuredlogging.json?
Thanks

**Comment by asad-naeem** [comment]
Hi,
Edit website permissions in IIS and under security tab give IIS_IUSRS group full privileges.
In Application, Pools find the pool your application is using and set some specific user.
