### ISSUE TITLE
Pad alignmentOnTruncation=left alings right

### ISSUE THREAD

**Issue by vankampenp** [NLog/NLog#2436]
QUESTIONS are preferred on StackOverflow. You could expect a faster response there (but do include all the info below). Use the tag "nlog" https://stackoverflow.com/questions/ask

**Type** BUG

**NLog version**: 4.5rc1

**Platform**: .NET Core 2.0 on NET Framework 4.6.1

**Current NLog config** (xml or C#, if relevant)
`|${pad:fixedLength=true:alignmentOnTruncation=left:padding=6:${uppercase:${level}}}|`

In case of a BUG:

- What is the current result?
`|  WARN|`
- What is the expected result?
`|WARN  |`
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
Yes, no error
- Are there any work arrounds? no
`:alignmentOnTruncation=right` gives the same result
- Is there a version in which it did worked? not tried before
- Can you help us by writing an unit test? no

**Comment by 304NotModified** [comment]
thanks for reporting!

**Comment by 304NotModified** [comment]
I checked the expected result. THe `alignmentOnTruncation` works only when truncating, see

https://github.com/NLog/NLog/blob/7e3629b3dc365c209e163d8bf3f0c263f996b0b3/tests/NLog.UnitTests/LayoutRenderers/Wrappers/PaddingTests.cs

and 

> alignmentOnTruncation - Indicates whether a value that has been truncated due to fixedLength=true is aligned to the left (characters removed from the right) or right (characters removed from the left). This is independent of the alignment applied when padding shorter strings out to padding characters. This property was introduced in NLog 4.0. Earlier versions always apply an alignment equivalent to alignmentOnTruncation=left. PaddingHorizontalAlignment Default: Left

https://github.com/NLog/NLog/wiki/Pad-Layout-Renderer

it means if we expect "war" or "arn" with 3 characters. The name `alignmentOnTruncation` isn't optimal ;)

to align with padding without truncation, use negative numbers

**Comment by vankampenp** [comment]
Ah, thanks, sorry to bother you with this.
