### ISSUE TITLE
docs for autoloading .net core / NLog 4.5

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#2438]
See https://github.com/NLog/NLog/issues/1091

**Comment by 304NotModified** [comment]
Update, NuGet packages will work:

- https://github.com/NLog/NLog/pull/2493

**Comment by snakefoot** [comment]
Yes it is only NetCoreApp1, that needs manually explicit help for loading assemblies coming from Nuget-packages.

**Comment by snakefoot** [comment]
NetStandard1.6 allows access to runtime assemblies:

`Microsoft.Extensions.DependencyModel.DependencyContext.Default.RuntimeLibraries`

But this doesn't help UWP10-Apps.

**Comment by 304NotModified** [comment]
nice!

**Comment by snakefoot** [comment]
Guess we should update the documentation about auto-loading assemblies has been disabled in NLog 5.0. See also #4232

**Comment by snakefoot** [comment]
Updated wiki about NLog 5.0 is not loading assemblies automatically:
- https://github.com/NLog/NLog/wiki/Configuration-file#extensions
- https://github.com/NLog/NLog/wiki/Register-your-custom-component
