### ISSUE TITLE
Merge UWP into NLog 4.5  - drop NLog 5

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#2440]
I think this is double.

Merge UWP target (UWP branch) to NLog 4.5

Then we could drop NLog 5 for now, as NLog 4.5 supports .NET Standard 1.5 (NLog 5 - .NET standard 1.3)

With loosing .NET Standard 1.3+1.4, we won't loose any platforms?

See https://blogs.msdn.microsoft.com/dotnet/2016/09/26/introducing-net-standard/

![image](https://user-images.githubusercontent.com/5808377/33509568-02ab3a86-d703-11e7-9c77-66f03f4600db.png)

**Comment by 304NotModified** [comment]
fixed by #2441

**Comment by mfeingol** [comment]
Hi.

> With loosing .NET Standard 1.3+1.4, we won't loose any platforms?

By losing .NET Standard 1.4, you've lost anyone using NLog in a .NET Standard assembly used by any UWP app targeting the Creator's Update and below. As that's my case, I'll be sticking to your 5.x pre-release versions until you can hopefully fix that.

Thanks!

**Comment by 304NotModified** [comment]
@mfeingol time to test a new rc with .net standard 1.3 support?

**Comment by mfeingol** [comment]
Absolutely!

**Comment by 304NotModified** [comment]
cool! Will release within a few days!

**Comment by 304NotModified** [comment]
@mfeingol rc7 is in the build/release queue. Will be published in a few hours

Would be great if you could confirm soon that this will fix your case :)

**Comment by 304NotModified** [comment]
Thanks for the feedback!
