### ISSUE TITLE
Internal Docs NLog 4.5  - platforms sl4,sl5, xamarin etc. are in build.ps1

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#2442]
and not in csproj

**Comment by snakefoot** [comment]
What docs are you missing ?

**Comment by 304NotModified** [comment]
I was a bit confused, so internal logs. Readme.md or https://github.com/NLog/NLog/blob/master/README-developers.md

Explaining that we support more than ` <TargetFrameworks>net45;net40-client;net35;netstandard1.5;netstandard2.0;netstandard1.4</TargetFrameworks>` and that is build by build.ps1
