### ISSUE TITLE
Nlog 4.5 - wp8/sl4/sl5/monoandroid/ xamarin

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#2443]
Imports are still there, but not in buildtargets

![image](https://user-images.githubusercontent.com/5808377/33517541-70a018d0-d786-11e7-96e1-581d67c30058.png)

**Comment by 304NotModified** [comment]
related #2442

**Comment by snakefoot** [comment]
What are you missing ? The build.ps1 is the one controlling what is being built.

**Comment by 304NotModified** [comment]
Thanks, was confused!
