### ISSUE TITLE
Add special folder for External Storage for Android

### ISSUE THREAD

**Issue by adyshimony** [NLog/NLog#2448]
- Feature request

Hi,

There are a lots of special folders, but none of them support writing to the external folder in android, where the user can see the logs by browsing the files.

I suggest rendering option - ExternalStorage.

Thanks,

Ady.

**Comment by snakefoot** [comment]
Easy work around is just to create your own custom layout-renderer:

https://github.com/NLog/NLog/wiki/How-to-write-a-custom-layout-renderer

**Comment by 304NotModified** [comment]
Is this a fixed string? Or where can we find the ExternalStorage exact pad (in C#)?

**Comment by snakefoot** [comment]
Instead of depending on ExternalStoragePath, then you could also consider embedding nlog.config as Xamarin resource:

https://github.com/nlog/NLog/wiki/Explicit-NLog-configuration-loading#loading-nlog-configuration-from-xamarin-resource

**Comment by 304NotModified** [comment]
Good one. And as there is no reaction on https://github.com/NLog/NLog/issues/2448#issuecomment-348908937, I'm gonna close this.

**Comment by snakefoot** [comment]
Maybe something like this:
```
LayoutRenderer.Register("ExternalStorage", (logEvent) => {
        if (Android.OS.Environment.IsExternalStorageEmulated)
        {
            return Android.OS.Environment.ExternalStorageDirectory.Path;
        }
        else
        {
            return Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments);
        });
```
Could probably also be assigned like this:

```c#
if (Android.OS.Environment.IsExternalStorageEmulated)
   NLog.GlobalDiagnosticsContext.Set("ExternalStorage", Android.OS.Environment.ExternalStorageDirectory.Path);

fileTarget.FileName = "${gdc:ExternalStorage:whenEmpty=${specialfolder:MyDocuments}}";
```
