### ISSUE TITLE
Why Nlog 5.0.0 in beta?

### ISSUE THREAD

**Issue by FenrisWolfAtMiddleEarth** [NLog/NLog#2457]
Thanks for a great log-library.
I am currently looking at migrating our entire system portfolio from Serilog to NLog. Mostly because we have had issues iwth Serilog, and I like the simplicity of NLog.
We will however need a .net Core library. I can see there is a 5.0.0 in beta-11. Is there any reason why it is still in beta?
I have tested use of the beta with our libraries, and it appears to be working. Are there any known concerns or issues with beta-11, which I should take in to consideration?
Thanks

**Comment by 304NotModified** [comment]
It's working, but I'm it's not good enough. 

But luckily there is nlog 4.5 which supports net standard, UWP and structured logging :)

Rc now, rtm expected in a few weeks!

**Comment by FenrisWolfAtMiddleEarth** [comment]
Ok. Thanks
