### ISSUE TITLE
PackageReference support broken

### ISSUE THREAD

**Issue by SixFive7** [NLog/NLog#2461]
Bug

NLog version: 4.4.12
Platform: .Net 4.6
Visual Studio: 15.5.1

When adding the NLog.Config nuget package using PackageReference in the project file instead of a Packages.config file the NLog.config example template file and is not placed in the project. Also missing is the NLog Schema file.
Adding the NLog.Config nuget package with the use of a packages.config work perfectly.

Steps to reproduce:
- Open VS.
- Go to Tools -> Options -> Nuget Package Manager.
- Set the "DEfault package management format to "PackageReference".
- Also set "Allow format selection on first package install".
- Create new VB.NET 4.6 WPF project.
- Add the NLog.Config package and let it resolve the nlog and schema dependencies.
- On the dialoge: "Choose Nuget Package Manager Format" choose either:
   -> A) Packages.config
   -> B) PackageReference in project file

Option A works perfectly.
Option B fails to place any schema or example config files. Also it seems to fail to install the NLog and NLog.Schema dependencies.

Is the nuget PackageReference method broken for the NLog nuget packages?

Kind regards

**Comment by 304NotModified** [comment]
I think this is https://github.com/NLog/NLog/issues/2434?

**Comment by 304NotModified** [comment]
Well guess so then

**Comment by SixFive7** [comment]
Sorry for the delay.
The problem with using the new nuget PackageReference is unrelated to #2434.

**Comment by 304NotModified** [comment]
What's the difference then? #2434. is for NLog.Schema en NLog.Config

**Comment by 304NotModified** [comment]
This is fixed in NLog 4.5.x. Since NLog 4.5.4 is works fully, see https://github.com/nlog/nlog/pull/2687

If not, please open a new issue

**Comment by shaggygi** [comment]
@304NotModified tried again, so created https://github.com/NLog/NLog/issues/2757
Let me know if you need more info and I'll try to provide.  Thx
