### ISSUE TITLE
Xamarin Android:  Target cannot be found: 'File'

### ISSUE THREAD

**Issue by pawlowskim** [NLog/NLog#2468]
**Type** (choose one): Bug
**NLog version**: 4.4.12
**Platform**: Xamarin Android
**Current NLog config** (xml or C#, if relevant)

```xml
<nlog
	xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	autoReload="true"
	throwExceptions="true"
	internalLogLevel="Debug"
	throwConfigExceptions="true"
	internalLogToConsole="true">
	<targets>
		<target
			name="file"
			xsi:type="File"
			layout="${longdate} ${logger} ${message}"
			fileName="${basedir}/logs/logfile.txt"
			keepFileOpen="false"
			encoding="iso-8859-2" />
	</targets>
	<rules>
		<logger
			name="*"
			minlevel="Debug"
			writeTo="file" />
	</rules>

```

In case of a BUG:

- What is the current result?
Loading config file throws error
- What is the expected result?
Loader should load config file successful
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
Yes.
- Please post full exception details (message, stacktrace, inner exceptions)
```
2017-12-18 10:29:56.1492 Debug ScanAssembly('NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null')
2017-12-18 10:29:56.2567 Debug Start auto loading, location: /storage/emulated/0/Android/data/io.netbulls.paymentterminalservice/files/.__override__
2017-12-18 10:29:56.2580 Debug Auto loading done
2017-12-18 10:29:56.2604 Error Parsing configuration from  failed. Exception: NLog.NLogConfigurationException: Exception when parsing .  ---> System.ArgumentException: Target cannot be found: 'File'
  at NLog.Config.Factory`2[TBaseType,TAttributeType].CreateInstance (System.String name) [0x00058] in <36883b57f6eb4c10a5bdcc5a97ab00da>:0 
  at NLog.Config.XmlLoggingConfiguration.ParseTargetsElement (NLog.Config.NLogXmlElement targetsElement) [0x00186] in <36883b57f6eb4c10a5bdcc5a97ab00da>:0 
  at NLog.Config.XmlLoggingConfiguration.ParseNLogElement (NLog.Config.NLogXmlElement nlogElement, System.String filePath, System.Boolean autoReloadDefault) [0x002c6] in <36883b57f6eb4c10a5bdcc5a97ab00da>:0 
  at NLog.Config.XmlLoggingConfiguration.ParseTopLevel (NLog.Config.NLogXmlElement content, System.String filePath, System.Boolean autoReloadDefault) [0x00057] in <36883b57f6eb4c10a5bdcc5a97ab00da>:0 
  at NLog.Config.XmlLoggingConfiguration.Initialize (System.Xml.XmlReader reader, System.String fileName, System.Boolean ignoreErrors) [0x0003d] in <36883b57f6eb4c10a5bdcc5a97ab00da>:0 
   --- End of inner exception stack trace ---
```
- Are there any work arrounds? yes/no
No
- Is there a version in which it did worked? 
Tried couple of version without any success.
- Can you help us by writing an unit test?
Probably no.

NLog suits my requirements perfectly but I cannot make it run. I spent couple of hours testing switching versions etc etc without any success. Support page says that FileTarget works on android. I was testing on Simulator Google Nexus 5 - 4.4.4 API 19 and Device HTC One M9.

I also have this in my application:
```
LogManager.ThrowExceptions = true;
LogManager.ThrowConfigExceptions = true;
LogManager.Configuration = new XmlLoggingConfiguration ("assets/NLog.config");
```

Tested also target type "Console" with the same result

**Comment by snakefoot** [comment]
Do not have much experience with NLog on Android, but it seems that the internal reflection of the builtin NLog-targets is failing (Could be nice if NLog did some more logging after `ScanAssembly` ...)

Without the internal type registration working, then all the exciting Layout-configuration is out of the window. So even if you instantiate the target manually, then the layout-configuration will not work.

Maybe the Mono-linker is optimizing all "unused" types away to make your app smaller. Maybe you need to configure it to ignore the NLog.dll when linking (Or if everything fails then disable "Link All Assemblies")

http://www.itworksonmymachine.net/2015/04/20/xamarin-tips-and-tricks-2-beware-of-linking-and-reflection/

https://developer.xamarin.com/guides/android/advanced_topics/linking/

**Comment by pawlowskim** [comment]
Thanks for response @snakefoot. Just tested every available linking option. It doesn't help :/

**Comment by snakefoot** [comment]
Have you checked the size of the NLog. dll after it has been deployed? What happens when trying in debug mode?



Sent from my Samsung device


-------- Original message --------

**Comment by pawlowskim** [comment]
Debug / Release same errors. Size is 585KB.

**Comment by snakefoot** [comment]
Do you get any types if doing Assembly GetTypes on the NLog assembly in your own code?


Sent from my Samsung device


-------- Original message --------

**Comment by pawlowskim** [comment]
I don't understand, could you explain it more?

**Comment by snakefoot** [comment]
Investigate the returned types from  Assembly.GetTypes() when using the Nlog-assembly



Sent from my Samsung device


-------- Original message --------

**Comment by pawlowskim** [comment]
```
NLog.Targets.DebugTarget
NLog.Targets.DefaultJsonSerializer
NLog.Targets.IJsonSerializer
NLog.Targets.JsonSerializeOptions
NLog.Targets.Target
NLog.Targets.Target+<>c
NLog.Targets.TargetAttribute
NLog.Targets.TargetWithLayout
NLog.Targets.Wrappers.AsyncRequestQueue
NLog.Targets.Wrappers.AsyncTargetWrapper
NLog.Targets.Wrappers.AsyncTargetWrapperOverflowAction
NLog.Targets.Wrappers.CompoundTargetBase
NLog.Targets.Wrappers.CompoundTargetBase+<>c
NLog.Targets.Wrappers.WrapperTargetBase
```

I'm not sure if this is what are you asking for :/ There isn't FileTarget nor ConsoleTarget I have tested. Moreover I found this (I'm not sure if it's related with the problem):

https://github.com/NLog/NLog/blob/master/src/NLog/Targets/FileTarget.cs

```
#if !SILVERLIGHT && !__ANDROID__ && !__IOS__ && !WINDOWS_UWP
// Unfortunately, Xamarin Android and Xamarin iOS don't support mutexes (see https://github.com/mono/mono/blob/3a9e18e5405b5772be88bfc45739d6a350560111/mcs/class/corlib/System.Threading/Mutex.cs#L167) so the BaseFileAppender class now throws an exception in the constructor.
#define SupportsMutex
#endif
```

**Comment by snakefoot** [comment]
Could you try and create an Nlog FileTarget and ConsoleTarget in your own code, and see if the Assembly linking then includes the types correctly?



Sent from my Samsung device


-------- Original message --------

**Comment by pawlowskim** [comment]
```
NLog.LogManager.ThrowExceptions = true;
NLog.LogManager.ThrowConfigExceptions = true;

NLog.Config.LoggingConfiguration cfg = new NLog.Config.LoggingConfiguration ();

FileTarget ft = new FileTarget ("f");
string path = System.Environment.GetFolderPath (System.Environment.SpecialFolder.Personal);
string filename = Path.Combine (path, "log");
ft.FileName = filename;
ft.FileNameKind = FilePathKind.Absolute;
ft.AutoFlush = true;
cfg.AddTarget ("f", ft);
cfg.AddRuleForAllLevels (ft);
NLog.LogManager.Configuration = cfg;
NLog.LogManager.ReconfigExistingLoggers ();

NLog.Logger logger = NLog.LogManager.GetCurrentClassLogger();
logger.Debug ("test");
logger.Warn ("test");
logger.Error ("test");
```

This fast test code allowed me to generate log in application folder. 

Thank you so much @snakefoot for help!

I assume that NLog is still bugged on Xamarin Android (loading from xml config didn't work).

**Comment by snakefoot** [comment]
If you can investigate how to make Assembly GetTypes work, then it would make the xml config work


Sent from my Samsung device


-------- Original message --------

**Comment by 304NotModified** [comment]
@pawlowskim could you please check NLog 4.5 RC?

**Comment by pawlowskim** [comment]
@304NotModified  From the moment I started to configure it manually in code, I was using 4.5.0-rc03. Reading config from XML doesn't work for me in 4.5-rc03 either.

**Comment by snakefoot** [comment]
Could you try and add the following to your Android project:

```
<PropertyGroup>
    <AndroidLinkSkip>NLog.dll</AndroidLinkSkip>
</PropertyGroup>
```

**Comment by pawlowskim** [comment]
@snakefoot I will check it next week and let you know.

**Comment by 304NotModified** [comment]
Polite Bump @pawlowskim

**Comment by 304NotModified** [comment]
Duplicate #1599

**Comment by pawlowskim** [comment]
Possible I have some bugs to resolved in my library that used NLog so I will let you know. Right now I don't have time to check this out.

**Comment by 304NotModified** [comment]
Closing as this is a duplicate

**Comment by snakefoot** [comment]
@pawlowskim If you know how to setup a local nuget-package-repository, then you are very welcome to try this pre-release build to see if it works as expected (without  using `--linkskip=NLog`):

https://ci.appveyor.com/project/nlog/nlog/builds/20883080/artifacts (Download `NLog.4.5.11.8779-PR3039.nupkg`)

**Comment by snakefoot** [comment]
@pawlowskim While waiting for NLog ver. 4.6, then you can also add this to your main-project:

```C#
[assembly: Preserve(typeof(NLog.Targets.FileTarget), AllMembers = true)]
```

This will force the AOT-linker to include code even if not referenced.
