### ISSUE TITLE
Next Version - NLog 6

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#2469]
As we have more than a year released pre-versions of NLog 5, and moved to NLog 4.5 in favor of NLog 5 (see #2445), the proposal is to skip NLog 5 and move to NLog 6 after NLog 4.x. This because many tutorials are written NLog 5 and that could be really confusing.

Old NLog 5 releases, almost 1 million downloads:

![image](https://user-images.githubusercontent.com/5808377/34183258-21833a9c-e51a-11e7-9faa-417443e5dee4.png)

Please you're opinion :) (@snakefoot)

**Comment by snakefoot** [comment]
Yes it is very confusing with having a NLog 5.0 that never becomes final.

The promise of NLog 5.0 was NetStandard with minimum amount of breaking inteface changes. This has now changed into NLog 4.5 with no breaking interface changes.

I understand the great news that NetStandard was possible without breaking interface changes (Which is signaled with ver. 4.5). But explaining to the entire world that NLog 5.0 is not the correct version to use for a whole year until NLog ver. 6.0 is released is not a rewarding job. You also identified that the NLog ver. 5 cannot be reused for doing breaking changes.

Maybe just bump the version to NLog 5.0 RTM, and mark all NLog 5.0 BETAS releases as obsolete? (Not sure how nuget works when requesting a non-existing pre-release, and a stable release is found).

I can see some NLog nuget packages continues to use NLog 2.0 as minimum version, and this is possible because there are very few breaking changes in the NLog-Target-interface, which I think is great. So people are navigating from NLog 2.0 to NLog 4.0 without thinking, so going to NLog 5.0 should not be a big deal.

P.S. Also hope that the NLog ver. 6.0 BETA stage will not be a year as well, since executing breaking changes and merging with main-branch is not gonna be fun for a long time (or error free).

**Comment by snakefoot** [comment]
Alternative then you need to be really quick and release NLog ver. 6.0 where everything has been sliced and diced to only include core-targets (MemoryTarget, AsyncTargetWrapper) and core-Layout (JsonLayout + SimpleLayout) and core-LayoutRenderers.

Everything else put into seperate NLog-packages (XmlConfig, exotic targets, exotic layouts). With the ability to easily register custom NLog-Config-Readers (LIke XmlConfig and soon to come JsonConfig).

**Comment by 304NotModified** [comment]
> Yes it is very confusing with having a NLog 5.0 that never becomes final (which is mentioned many places to be the version to use for NetStandard/NetCore).

true, but it was also wierd to rename to 5.0 when a RC of 4.5 was released. 







> Maybe just bump the version to NLog 5.0 RTM, and mark all NLog 5.0 BETAS releases as obsolete? (Not sure how nuget works when requesting a non-existing pre-release, and a stable release is found).

We can only unlist packages and so the betas are still restorable.  

I think it's too late for that, but what do you think about:

- The next version will be 5.0 
- The changes are that small that there aren't betas needed.
- We could then merge al the breaking changes PRs


> P.S. Also hope that the NLog ver. 6.0 BETA stage will not be a year as well, since executing breaking changes and merging with main-branch is not gonna be fun for a long time (or error free).

That's the last thing I would like ;)

**Comment by snakefoot** [comment]
> true, but it was also wierd to rename to 5.0 when a RC of 4.5 was released.

Think people have been using BETA and RC-versions because of need, not because they wanted to. Most people have been waiting for the RTM.

Going from NLog 4.4 RTM to NLog 5.0 RTM is not that weird.

**Comment by snakefoot** [comment]
We could also release NLog 5.0 with minimal breaking changes:

#1757 - AsyncTargetWrapper - Change default overflow action to blocking
#2069 - LayoutRenderer Initialize should swallow exceptions when configured

And all the NLog 5.0 TODOs in code fixed.

**Comment by snakefoot** [comment]
But it could be nice to remove the upper-version-nuget-restriction, since going forward it will only be an obstacle. And bumping the version would remove confusion around using an older NLog 5.0 BETA vs a newer NLog 4.5 RTM (Also for existing custom NLog-targets that requires NLog 5.0 or newer)

**Comment by sandersaares** [comment]
I can confirm that as a user of NLog who creates NetStandard targeting software, I really do not care if it says 4 or 5 or 6 - all I want is to use a a stable version with NetStandard support.

From the standpoint of someone reading tutorials on the web that say to use v5, I agree that it can be confusing to see 4.5 as the actual proper version to be used to gain netstandard support. Probably some v5 or v6 should be released to help out such users who might be confused by this. Whether you go to v5 or skip it and go straight to v6 makes no difference to me from a user's viewpoint.

**Comment by 304NotModified** [comment]
OK thanks,

FYI renaming 4.5 to 5 is out-of-scope. Unfortunately It's too late for that. So the discussion is if the next version should be 5 or 6

**Comment by snakefoot** [comment]
But you will remove the upper version cap from the nuget dependency for Nlog Extension Logging  and Nlog Web? Because that is going to bite users really hard



Sent from my Samsung device


-------- Original message --------

**Comment by 304NotModified** [comment]
> But you will remove the upper version cap from the nuget dependency for Nlog Extension Logging  and Nlog Web? Because that is going to bite users really hard

Do you mean remove the `<5`? Why is that needed?

**Comment by JustArchi** [comment]
My opinion probably doesn't matter that much as I'm not heavily involved in the project but I'd also vouch for NLog 6. I've just recently realized that NLog 5 was "rebranded" to NLog 4.5, so it makes sense to drop it for good and make people use either 4.5 or 6.0.

**Comment by snakefoot** [comment]
>Do you mean remove the <5? Why is that needed? Do you mean "now" or in the future?

I mean when NLog 4.5 RTM is out on the street.

I have have been bitten several times by dependency restrictions, so I only use them as last resort at the consuming application level. Logging libraries are usually at the bottom of the stack, and having dependency restriction at this level affects the entire stack.

**Comment by c0shea** [comment]
I don't know how the v5 betas compare to the 4.5 RC, but to me if the publicly-facing API doesn't have all that many changes then I'd say using v5 would be fine. However, if there are more than a couple small inconsistencies between the two, as a client I think it would be less confusing to jump to v6 to avoid any expectations of similarity. Though v5 isn't RTM, it's been in the beta stage for so long that I imagine many who needed the netstandard support have treated it as such.

**Comment by ppumkin** [comment]
It already really confusing which version works with which other version. Logging just used to work now I have all sorts of unnecessary problems and I have no idea what to use any more.

**Comment by snakefoot** [comment]
> @304NotModified I think it's too late for that, but what do you think about:
>
> - The next version will be 5.0
> - The changes are that small that there no betas are needed.
> - We could then merge al the breaking changes PRs

Like the idea of using NLog 5.0 for making minor breaking changes, that doesn't affect custom Targets or custom Layouts.

Then NLog 5.0 would be the last monolith build, and NLog 6.0 will be the one that breaks everything into small packages (NLog-core and everything else).

**Comment by 304NotModified** [comment]
> Like the idea of using NLog 5.0 for making minor breaking changes, that doesn't affect custom Targets or custom Layouts.
> 
> Then NLog 5.0 would be the last monolith build, and NLog 6.0 will be the one that breaks everything into small packages (NLog-core and everything else).

👍 OK that's the plan then :)

**Comment by 304NotModified** [comment]
@ppumkin is it clear now? If you experience problems, please create a new github issue, thx!

**Comment by 304NotModified** [comment]
will close this issue if I changed the milestones the current PRS to V5/V6

**Comment by sandersaares** [comment]
Is there any timeline for publishing a stable version of the current RC? I am most eager to get rid of the prelease tags on libraries that reference NLog 4.5 RC.

**Comment by 304NotModified** [comment]
Currently the main task is updating the docs and writing docs about structured logging. 

There is not ETA for that yet.

FYI There will be a rc4 soon with some small changes, see milestone

**Comment by snakefoot** [comment]
@304NotModified Can you give an example of what kind of docs you are looking for about structured logging, besides written at https://messagetemplates.org/ ?

**Comment by 304NotModified** [comment]
something like that but then on the wiki or nlog-project.org. Maybe also needed:

- Exceptional cases (e.g. mixing numeric and names, non-unique names)
- pro and cons vs regular logging
- Format of serialisation and how to tune it
- The new settings in the (XML) config

**Comment by 304NotModified** [comment]
Closing this one, in summary:

- we don't gonna rename 4.5 to 4
- there will be a NLog 5 version, and will have small breaking changes. No big features. 
- NLog 6 will break NLog into multiple packages.

**Comment by 304NotModified** [comment]
FYI up-to-date todo list for 4.5 is here: https://github.com/NLog/NLog/issues/2498
