### ISSUE TITLE
Json Serializer should sanitize custom dictionary keys

### ISSUE THREAD

**Issue by snakefoot** [NLog/NLog#2474]
Usually NLog should just do the garbage-in and garbage-out, and not worry about broken data.

But when logging exceptions, then it is not always possible to control the Exception-data, as they can come from an external source.

The Exception.Data collection can contain a dictionary, where the dictionary-keys doesn't match normal json-properties (containing "." or "-"). This can be seen with Microsoft SQL exceptions.

**Comment by 304NotModified** [comment]
Maybe "sanitize" or "escape" is a better word for this?

**Comment by snakefoot** [comment]
Example of unwanted keys being added to Exception.Data:

```
           exception.Data.Add("HelpLink.EvtSrc",      "MSSQLServer");
            exception.Data.Add("HelpLink.EvtID",       errorCollection[0].Number.ToString(CultureInfo.InvariantCulture));
            exception.Data.Add("HelpLink.BaseHelpUrl", "http://go.microsoft.com/fwlink");
            exception.Data.Add("HelpLink.LinkId",      "20476");
```

https://referencesource.microsoft.com/#System.Data/System/Data/SqlClient/SqlException.cs
