### ISSUE TITLE
GetCurrentClassLogger inside of a razor view returns logger name with ExecuteAsync

### ISSUE THREAD

**Issue by mariuszjamro** [NLog/NLog#2478]
**Type** (choose one):  Bug
**NLog version**: 5.0.0-beta09
**Platform**:  .Net 4.5 

If you try to get logger using `LogManager.GetCurrentClassLogger()` inside of a ASP.NET Core Razor view (`.cshtml` file) the generated logger name gets polluted with some async-related stuff. View like this:

    @using NLog;

    @{ 
        var logger = LogManager.GetCurrentClassLogger();
    }

    @logger.Name;

creates a logger named:

    AspNetCore._Areas_Foo_Views_Bar_Index_cshtml.<ExecuteAsync>d__13;

I believe the `.<ExecuteAsync>d__13` part should not be included in logger name using the same method as in  [`StackTraceUsageUtils.cs`](https://github.com/NLog/NLog/blob/fd6e91a2daed54570a8e89cc2575e0e11158343f/src/NLog/Internal/StackTraceUsageUtils.cs#L110). This way the result would be:

    AspNetCore._Areas_Foo_Views_Bar_Index_cshtml

**Comment by 304NotModified** [comment]
What the expected **class** name in a razor view?

**Comment by snakefoot** [comment]
> @304NotModified What the expected class name in a razor view?

Seems it should be **AspNetCore._Areas_Foo_Views_Bar_Index_cshtml** (as mentioned in the original post)

**Comment by snakefoot** [comment]
> @mariuszjamro Get logger using L`ogManager.GetCurrentClassLogger()` inside of a ASP.NET Core Razor view 

There is a huge overhead from calling `LogManager.GetCurrentClassLogger()`, so one usually creates the logger as a static variable. I recommend that you add the logger as a static variable in the "code-behind file for the view".

**Comment by mariuszjamro** [comment]
@snakefoot i know that this is easy to workaround (and i know logging in views is rather unusual in the first place). Nonetheless i just wanted you guys to know about that.

**Comment by 304NotModified** [comment]
Thanks @mariuszjamro for letting us know.

I don't like to change the current behavior because of the following reasons:

- There is no class in the view and so the class name is already unclear
- This will impact the performance of NLog core
- There is a work around - you could use getLogger("name")
- IMO creating a logger in a view is bad practice - views should be declarative.
