### ISSUE TITLE
Enable the counter sequence parameter to take layouts

### ISSUE THREAD

**Issue by lonevvolf** [NLog/NLog#248]
Enable the counter sequence parameter to take layouts, in order to split log counters by their variable information.  
For example:
${counter:sequence=${exception:format=shorttype}}

**Comment by 304NotModified** [comment]
Needs #427 for this.

**Comment by 304NotModified** [comment]
breaking change because using nested layout renderers before had a different result

**Comment by 304NotModified** [comment]
https://github.com/304NotModified/NLog/commit/5efe67a2fa58d7c2b369acc2dd589c1325f9fe66
