### ISSUE TITLE
NLog not respecting the actual app-config

### ISSUE THREAD

**Issue by Spiralis** [NLog/NLog#2482]
It may seem that NLog is perhaps not respecting the actual loaded app-config file. 

Changing app-config files in .Net is not made easy out of the box, but it [is possible](https://stackoverflow.com/a/6151688/95008). 

I believe that NLog should try to read its config-section using the real AppSettings API, which AFAICT also supports reloading. If it did then whatever .exe.config that the application is linked to should "just work", in regards to reading the NLog section from it.

**Comment by 304NotModified** [comment]
> AppSettings API, which AFAICT also supports reloading.

I don't think that's true. 

Any way, in this case a nlog.config is highly recommend

**Comment by Spiralis** [comment]
Hm. I think you are correct. I just checked our own codebase. We actually handle the file-watching and refresh on the app-config sections in our own code.

But, I still think NLog should use the correct log-file. So instead of relying on the "expected" .exe.config name it probably would be a better approach to use the actual config name.

**Comment by 304NotModified** [comment]
> But, I still think NLog should use the correct log-file. So instead of relying on the "expected" .exe.config name it probably would be a better approach to use the actual config name.

I'm sorry,  I don't think I fully understand this. What needs to be changed? Maybe you could fill in the template? (current and expected behavior)

**Comment by Spiralis** [comment]
I didn't fill in the template as I wasn't sure whether this was a bug or not. I'll try to give the issue a little bit of structure in this post:

*Description:*
A .Net application can have multiple instances running at the same time, but the default .Net behavior is that all of these will use the same `<appname.exe.config` file. However, that is really not always what you want. In our case each instance needs to have its own unique configuration and we also want the nlog config to differ as we want the logs for each instance to be written to different locations - and we also want to be able to i.e. change the logging for each instance separately for debugging purposes. Trying to debug and analyze one instance should not create extra logging for the other instances. Microsoft has not made a solution for this obvious, and I think what most people do is just to deploy the same binaries to multiple locations... Which makes everything use more space, upgrades have to be applied to each copy. All in all not a very nice solution, when you really just want the config-file to differ. But, it turns out that you *can* make the application use a different config file, like suggested [here](https://stackoverflow.com/a/6151688/95008). We use this method and it works out great for us. We check the commandline args in the application, looking for a `-config <file>` argument. When found we use the aforementioned code to make the application use that config-file instead. We then also want the NLog configurations to differ from instance to instance. But, NLog did not seem to check the actual config-file in use.

*Expected behavior:*
I was expecting NLog to read the *actual* `app.config`-file that the application was using.

*Actual behavior:*
It seems that NLog assumes the config file to be named `<appname>.exe.config` and for that file to reside next to the application binary executable. Which fails as that folder doesn't contain any config-files at all.

*Workaround:*
Instead we have to manually tell NLog to reload the configuration based on the *actual* config-file that the application uses. 

*Suggested solution:*
It is possible to find out which config file is *actually* in use, by using i.e this call:
```
AppDomain.CurrentDomain.GetData("APP_CONFIG_FILE").ToString()
```
Reading the docs about [config files](https://github.com/NLog/NLog/wiki/Configuration-file#configuration-file-locations), I think it would be a good strategy to have it look for the typical nlog config-files *also* in the folder where the *actual* config-file is located - and not only in the folder where the application bin-file is located. Then it would automatically work, for both embedded nlog sections in the app.config as well as for `NLog.config` files placed in the same folder as the actual config-file that is in use. 

I could assist with a PR, but I was not able to find out where this happens in the Nlog code. I only did a quick search to see if I could find out where this was performed though. If someone can help identify the existing app-config loading code then I'd be happy to help.

**Comment by 304NotModified** [comment]
> I could assist with a PR, but I was not able to find out where this happens in the Nlog code.

The code is here: https://github.com/NLog/NLog/blob/master/src/NLog/Config/ConfigSectionHandler.cs

but I don't know how to fix this in the current code.

**Comment by Spiralis** [comment]
AFAICT, replacing
```
return appDomain.SetupInformation.ConfigurationFile;
```
with
```
return AppDomain.CurrentDomain.GetData("APP_CONFIG_FILE").ToString();
``` 
in `AppDomainWrapper.cs` will not be a breaking change. 

For users that are using the default config file, the two above constructs will return exactly the same. 
For users that are using a different config-file, the first will point to the wrong config-file and the latter to the correct config-file.

@304NotModified , I believe that this is not something that should be optional. I think it is an improvement (or even to be considered a fix), to return the correct config-file for both types of use.

**Comment by 304NotModified** [comment]
are you sure it's compatible on all platforms?

**Comment by Spiralis** [comment]
If by all Platforms you mean .Net Standard 2.0, then according to [MS .Net Standard 2.0 API list](https://raw.githubusercontent.com/dotnet/standard/master/docs/versions/netstandard2.0_ref.md) it is. 

But, a test to verify this would not harm...

**Comment by Spiralis** [comment]
Better docs here: https://docs.microsoft.com/nb-no/dotnet/api/system.appdomain.getdata?view=netstandard-2.0#System_AppDomain_GetData_System_String_

**Comment by 304NotModified** [comment]
thanks!

But according to the docs, "APP_CONFIG_FILE" == AppDomainSetup.ConfigurationFile, so the same?


![image](https://user-images.githubusercontent.com/5808377/39887814-6d4562b4-5493-11e8-8038-5fdacabd4209.png)

**Comment by Spiralis** [comment]
It might be, yes. I have been thinking the same. The problem is probably that for the 95%+ use case the value is always the default (appname.exe.config).

**Comment by 304NotModified** [comment]
sure if there are the same, i'm doubting if replace `AppDomainSetup.ConfigurationFile` with `AppDomain.CurrentDomain.GetData("APP_CONFIG_FILE").` will fix anything. 

Anyway, I could make a nupkg package (AppVeyor feed), so you could test with it. Would that be possible for you to test then?

**Comment by Spiralis** [comment]
I do agree with you. It would be weird for these two approaches to deliver different results.

It is a while ago since I looked at this, but I think I might have an idea of what is happening. I think NLog is initialized **before** the .Net application config param is changed (typically early in app Main). NLog just doesn't know that the config-file has changed. 

In that respect the current behavior is probably ok. But, with a knowledge-based entry explaining that if you use a different config-file than default, then you need to rewire the NLog setup as soon as the config-file path has been changed in .Net.

Having said that, any other .Net functionality that depends on the config-file seem to work as expected.

**Comment by 304NotModified** [comment]
> It is a while ago since I looked at this, but I think I might have an idea of what is happening. I think NLog is initialized before the .Net application config param is changed (typically early in app Main). NLog just doesn't know that the config-file has changed.

I think also that's the case!

If you have an idea how to fix that for this case, let me know.

**Comment by Spiralis** [comment]
I will think about this and see what we are doing in our code - and see if I have any suggestions for improvements, if any.
