### ISSUE TITLE
Why does NLog wrap the filename in parentheses

### ISSUE THREAD

**Issue by zhulika** [NLog/NLog#2483]
I'm looking at changing over to use NLog and I want to get ${callsite} to give me the full path-name only. Why do you force it to include parentheses and a line number? If I wanted to have those, I could add them to the configuration myself.

Surely it is a mistake to add things that are not required and, even if you must do so, it is a worse mistake to prevent the user from removing them with the qualifiers?

**Comment by 304NotModified** [comment]
good question,

I think this is a bad design choice indeed. 

The best way is to add a new layout renderer, e.g.

    ${callsite-filename}

just like `${callsite-linenumber}`

Adding an option to the current ${callsite} will make it more complex, so that's not preferred by my.

What do you think?

**Comment by 304NotModified** [comment]
please let me know what you think, so we can move to a feature request. thx!

**Comment by 304NotModified** [comment]
We will fix this in the future: https://github.com/NLog/NLog/issues/2583

**Comment by zhulika** [comment]
Sorry for the lack of response. I got the notification of the closure but no notification of your previous comments. Your proposed solution would work fine for me, thank you.

**Comment by 304NotModified** [comment]
Ok thanks for the feedback!
