### ISSUE TITLE
NLog/.NET core fails with "Too many open files" after few days

### ISSUE THREAD

**Issue by MiloszKrajewski** [NLog/NLog#2484]
**Type**: Bug
**NLog version**: 4.5.0-rc03
**Platform**: .NET Core 

**Current NLog config** (xml or C#, if relevant)

```xml
var target = new FileTarget {
	Name = "file",
	Layout = Layout,
	ArchiveEvery = FileArchivePeriod.Day,
	MaxArchiveFiles = 7,
	FileName = Path.Combine(folder, productName + ".log"),
	ArchiveFileName = Path.Combine(folder, productName + ".bak")
};
config.AddTarget("file", target);
config.LoggingRules.Add(new LoggingRule("*", LogLevel.Trace, target));
```

In case of a BUG:

**What is the current result?**

Attempt to log ens with:

```
Error Failed write to file 'xyz.log'. Exception: System.IO.IOException: Too many open files
	at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
	at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
	at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
	at NLog.Internal.FileAppenders.BaseFileAppender.TryCreateFileStream(Boolean allowFileSharedWriting)
	at NLog.Internal.FileAppenders.BaseFileAppender.CreateFileStream(Boolean allowFileSharedWriting)
	at NLog.Internal.FileAppenders.RetryingMultiProcessFileAppender.Write(Byte[] bytes, Int32 offset, Int32 count)
	at NLog.Targets.FileTarget.WriteToFile(String fileName, ArraySegment`1 bytes, Boolean initializedNewFile)
```
It also seems like it actually crashes method which tried to log (not sure about that).

**What is the expected result?**

It should log without problems, and even in case of failure it should not crash the caller.

**Comment by snakefoot** [comment]
What platform are you using? If Windows could you try and use Process Explorer to see what the file handles are referring to?

https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer (To show handles: View -> Lower Pane View -> Handles)

**Comment by snakefoot** [comment]
Seems that you are running on Linux, so I guess Process Explorer will not help you.

What is the current limits for files concurrently open on the Linux box?

https://easyengine.io/tutorials/linux/increase-open-files-limit/ (See ulimit -Hn and -Sn)

After running the application for a day, can you then list the open file handles for the running process?

https://www.cyberciti.biz/faq/howto-linux-get-list-of-open-files/

The easy work-around so you will not get an error from NLog is just to add the following setting to your FileTarget: `KeepFileOpen = true,` (But I think something else is leaking).

**Comment by MiloszKrajewski** [comment]
Thanks,

It is in docker container so it is not as easy to check now what was the problem. 
It was a false alarm most likely. It seems that leak was somewhere else (for now my bet is: failed HTTP request was not closing socket). As it was causing a lot of logging at the same time it was looking like excessive logging is the problem.

Thanks for the `KeepFileOpen = true` tip.

**Comment by 304NotModified** [comment]
Thanks for the feedback!
