### ISSUE TITLE
Make IMessageTemplateParameters internal

### ISSUE THREAD

**Issue by snakefoot** [NLog/NLog#2489]
Change LogEventInfo.MessageTemplateParameters to return the actual MessageTemplateParameters (and make it public sealed).

This will lead to less breaking changes, in case someone starts to mock IMessageTemplateParameters, and we want to extend MessageTemplateParameters.

**Comment by 304NotModified** [comment]
> This will lead to less breaking changes,

I don't get this, could you please elaborate?

**Comment by 304NotModified** [comment]
Could you please give an example what we're trying to support? I don't see the benefit here. I still think the interface is better. Thx!

**Comment by snakefoot** [comment]
If needing a new special property like `IsPositional`, then new interface has to be created.

I guess one could also consider to move `IsPositional` to MessageTemplateParameter, and then change the interface to a simple IEnumerable<MessageTemplateParameter> without `Count` or stuff like that (Thus removing `IMessageTemplateParameters` completely)

**Comment by 304NotModified** [comment]
I will try to look at this in depth tomorrow. 

I think NLog 4.5 (rc4) should wait on this.

**Comment by 304NotModified** [comment]
> If needing a new special property like IsPositional, then new interface has to be created, along with new property on LogEventInfo.

Do you mean `IsPositional` on LogeventInfo and a new **class** for `IMessageTemplateParameters ` should be created?

**Comment by snakefoot** [comment]
> Do you mean IsPositional on LogeventInfo and a new class for IMessageTemplateParameters should be created?

No. IsPositional is a property on IMessageTemplateParameters. It is impossible to add any new properties to IMessageTemplateParameters. Instead one always has to create a new interface, and a new property on LogEventInfo returning this new interface.

**Comment by 304NotModified** [comment]
I think I understand it now,

as NLog we like to add something to `MessageTemplateParameters` / `IMessageTemplateParameters`. But the interface, it would be a breaking change.

Am I correct?

**Comment by snakefoot** [comment]
> Am I correct?

Yes

**Comment by 304NotModified** [comment]
thx! 

Maybe we should ditch the whole interface then?

**Comment by snakefoot** [comment]
> Maybe we should ditch the whole interface then?

That would also work.

**Comment by 304NotModified** [comment]
less is more :)

If you have time, please remove also the interface in #2490. Then I would merge it :)

**Comment by 304NotModified** [comment]
Added a commit :)
