### ISSUE TITLE
[Feature Request] Support for the RichTextBox target in an UserControl

### ISSUE THREAD

**Issue by FlorianWolters** [NLog/NLog#249]
The [RichTextBox target](https://github.com/nlog/NLog/wiki/RichTextBox-target) can be used to log text to a Rich Text Box control in an existing or new form. I have the requirement to log messages to a Rich Text Box control in an existing [UserControl](http://msdn.microsoft.com/system.windows.controls.usercontrol.aspx). I tried to configure the target for the User Control, but as I expected, that didn't work (a new form is created by NLog). Therefore I request to make that target work within a Rich Text Box inside an User Control.

I am currently developing an application-level add-in for Microsoft Word 2010 and I want to utilize NLog to write application event messages to a custom task pane. Since a custom task pane can only contain custom user controls, I can't use a form.

**Comment by Xharze** [comment]
Closed as this doesn't seem needed by other people. But please create new issue in the NLog/NLog.Windows.Forms repository if necessary.
