### ISSUE TITLE
Request for Schemas fixed for http://nlog-project.org/schemas/NLog.xsd

### ISSUE THREAD

**Issue by dindarkdevil** [NLog/NLog#2492]
When I see the `NLog.config` file on my project solution always got the message "Could not find schema information for the element"
and I try to solve it.

I founded something warning on my visual studio 2017 at line 821 of this schema file [NLog.xsd for all version .NET Framework](http://nlog-project.org/schemas/NLog.xsd)

Detail at line 821:
```
            <xs:documentation>
              Name of the connection string (as specified in <connectionStrings> configuration section.</xs:documentation>
```

Because found tag `<connectionStrings>` inside the `</xs:documentation>` tag,
Can you change it to

```
            <xs:documentation>
              Name of the connection string (as specified in "connectionStrings" configuration section.</xs:documentation>
```

instead or another way.. to solve.

P.S. sorry for my poor grammar, I'm Asian.

Best Regard,
DinDarkDevil

**Comment by 304NotModified** [comment]
is `&lt;connectionStrings&gt;` also OK? (xml encoded)

**Comment by 304NotModified** [comment]
this is from: https://github.com/NLog/NLog/blob/63a744565a4bfec682b8331a3227d4f88973b981/src/NLog/Targets/DatabaseTarget.cs#L151

**Comment by 304NotModified** [comment]
it its already XML encoded. Which tool is showing this error? VS2017?

**Comment by 304NotModified** [comment]
I think this is already resolved in 4.4.12

**Comment by dindarkdevil** [comment]
@304NotModified The problem has been solved.

Thank you.

**Comment by 304NotModified** [comment]
thx for the feedback!
