### ISSUE TITLE
Update all the docs for changed targets etc.

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#2499]

**Comment by snakefoot** [comment]
What changes and targets are you thinking about?

**Comment by 304NotModified** [comment]
we need to check these I guess:

https://github.com/NLog/NLog/pulls?utf8=%E2%9C%93&q=is%3Apr+label%3A%22needs+documentation+on+wiki%22+is%3Aclosed+-label%3A%22documentation+on+wiki+done%22+

**Comment by 304NotModified** [comment]
![image](https://user-images.githubusercontent.com/5808377/34921567-acf93a76-f984-11e7-9ead-b21d7ca347b7.png)

thank you very much @snakefoot !! 👍
