### ISSUE TITLE
Fluent logger should not inject callsite as properties

### ISSUE THREAD

**Issue by snakefoot** [NLog/NLog#2501]
This is for NLog 5.0 (new). 

Create a special setting that controls whether it should pollute the logevent-properties with its special callsite-properties (Default = false).

At the same time fix the interface problem when combining assemblies compiled with Net40 and Net45 that both makes use of the fluent-logger-interface. See also #2059

**Comment by 304NotModified** [comment]
👍

**Comment by snakefoot** [comment]
Maybe consider adding the setting with NLog 4.5, but changing the default value in NLog 5.0

**Comment by 304NotModified** [comment]
That's also a good idea, unfortunately i'm a bit behind with the PRs

**Comment by snakefoot** [comment]
Looked a little closer at LogBuilder, and it will require a cast to convert the ILogger to a Logger-object, and then ask the Logger-object whether the LoggerConfiguration has the new setting FluentLogBuilderWithCallSiteProperties enabled.

Think I will wait until NLog 5.0

**Comment by snakefoot** [comment]
Think I have found a solution. Going to move the adding of properties from LogBuilder into LoggerBase. Then LoggerBase can check its LoggerConfiguration.FluentLogBuilderWithCallSiteProperties, and if the LogEvent has been enriched with callsite (without using StackTrace) then it will inject properties automatically. Will fix this with #2527 (After #2554 has been merged)
