### ISSUE TITLE
Layout renderer for message template

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#2502]
I think we are still missing a layout renderer for the message template

e.g.

```c#
logger.Info("Logon by {userid} from {ip_address}", "Kenny", "127.0.0.1");
```

should print `Logon by {userid} from {ip_address}`

something like `${template}` or `${message-template}`

We need this for easily grouping of related messages

**Comment by snakefoot** [comment]
It is already there it is `${message:raw=true}`

**Comment by snakefoot** [comment]
Maybe rename it to `${message:template=true}`

**Comment by snakefoot** [comment]
Could also be nice with a layout renderer that generated this output:

`Logon by userid=Kenny from ip_address=127.0.0.1`

Right now the following can be done with `$(message:raw=true} $(all-event-properties:format=@)`

**Comment by 304NotModified** [comment]
You're right, raw is fine for now. Thx!
