### ISSUE TITLE
Change default Layout

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#2503]
include ${exception}

**Comment by snakefoot** [comment]
See also #1959

**Comment by snakefoot** [comment]
See also #2975 1292

**Comment by snakefoot** [comment]
My suggestion: `"${longdate}|${level:uppercase=true}|${logger}|${message:withException=true:exceptionSeparator=|}"`

**Comment by snakefoot** [comment]
I like the `exceptionSeparator=|` as it matches the seperator used in the current default layout:

${longdate}|${level:uppercase=true}|${logger}|${message}

**Comment by 304NotModified** [comment]
but then you have dynamic amount of `|`? brain-overload ;) 

I really really like consistency, but dynamic amount <> consistent

**Comment by snakefoot** [comment]
No matter what separator you choose then it will be "dynamic" as it will only be included when actually an exception.

**Comment by 304NotModified** [comment]
`${longdate}|${level:uppercase=true}|${logger}|${message:withException=true:exceptionSeparator=#}` -> is no dynamic `|`

**Comment by snakefoot** [comment]
@304NotModified How do you protect yourself from random `|` in mesage or exception? Not sure I understand your arguement. If needing strict formating then CsvLayout or JsonLayout is your guy.

**Comment by 304NotModified** [comment]
good one, although the likelihood of that is much lower

**Comment by 304NotModified** [comment]
duplicate of https://github.com/NLog/NLog/issues/1292
