### ISSUE TITLE
Auto reload on by default

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#2505]
for XML config

**Comment by snakefoot** [comment]
Not sure I like this feature enabled by default, but I think the default value for keepVariablesOnReload should be true.

**Comment by 304NotModified** [comment]
Please create a new issue for that, sounds like a good idea. 

And why not enabled by default?

**Comment by snakefoot** [comment]
> And why not enabled by default?

I think it would have too many side-effects, when reloading NLog-config while the application is running at full speed.

**Comment by snakefoot** [comment]
P.S. Looks like a duplicate of  #1114

**Comment by 304NotModified** [comment]
indeed, thanks!

**Comment by 304NotModified** [comment]
see https://github.com/NLog/NLog/issues/1114
