### ISSUE TITLE
Change Target.ToString

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#2508]
Currently

    File Target[file]

Maybe a bit more explicit:

    File Target (name=file)

**Comment by 304NotModified** [comment]
related https://github.com/NLog/NLog/issues/2506

**Comment by snakefoot** [comment]
Could be nice with some bonus logic, regarding wrappers. When using `async=true`, then the wrapped target will be called `<Name>_wrapped`.

When doing manual wrapping, then this auto-naming doesn't occur, so targets remain unnamed, as one usually do this:

```
   <target name="EventLogAsyncTarget" xsi:type="AsyncWrapper">
      <target xsi:type="RetryingWrapper">
        <target xsi:type="EventLog" source="${EventSource}" machineName="." />
      </target>
    </target>
```

This causes the internal-logging to become very vague for the final target.

Could also be nice that if the `TargetAttribute` has `IsWrapper=true` or `IsCompound=true`, then it will not get `Target` appended to the end. (Ex `AsyncWrapper(Name=Hello)` and `MailTarget(Name=Hello)`)
