### ISSUE TITLE
Archiving every day does not work when "change of day" happens during downtime

### ISSUE THREAD

**Issue by joecro88** [NLog/NLog#2523]
Hi!

I have noticed that when I want to archive the log file every day, and the program/service is not running during midnight, but is started back up the next day, NLog won't archive the log file from the previous day.
Tried combining this with the archiveOldFileOnStartup option, but it still won't do it.

We're using NLog 4.3.9. The .net framework target version is 4.6.

```xml
<target name="logfile" xsi:type="File" fileName="${basedir}/Log/TEST-${date:format=yyyy-MM-dd}-apicall.log"
                                archiveEvery="Day"
                                archiveFileName="${basedir}/Log/TEST-{#}-apicall-archive.zip"
                                archiveNumbering="DateAndSequence"
                                archiveDateFormat="yyyyMMdd"
                                enableArchiveFileCompression="true"
                                archiveOldFileOnStartup="true"

```

**Comment by 304NotModified** [comment]
We have changed a lot with archiving in NLog 4.4.x. Please try with 4.4.12, thanks!

**Comment by joecro88** [comment]
Thank you for the quick reply.

I'm not sure if I can get the project to use an updated version. Is there no way to achieve what I want with the version I'm using?
It is My first time using NLog, so if the version I'm using is too old and no longer supported, I understand, I just need a precise answer that I can pass along to the others.

**Comment by 304NotModified** [comment]
Well probably you need a fix and that fix is already made in 4.4

An upgrade should be easy, there aren't breaking changes.

**Comment by snakefoot** [comment]
@joecro88 You need to change your logging-setup, so the fileName remains static, no matter what the application runs.

`fileName="${basedir}/Log/TEST-apicall.log"`

NLog will currently only perform archive operation on the current filename. It will not attempt to archive any random filename.

**Comment by joecro88** [comment]
Thank you both for your help!
Will look in to the file name thing, and if that's not an option, then it's upgrade time.
