### ISSUE TITLE
Bug: Custom LayoutRenderer is rendering log events as empty string

### ISSUE THREAD

**Issue by GrosLalo** [NLog/NLog#2525]
Hi

I think this is a bug where `LayoutRenderer.Register()` fails to register a custom renderer. Please find below test code, screen shots and (`InternalLogger`) trace log to help understand the problem and issue at hand.

I have posted this problem on StackOverflow (Ref: [https://stackoverflow.com/questions/48341259/nlog-custom-layoutrenderer-is-rendering-log-events-as-empty-string](https://stackoverflow.com/questions/48341259/nlog-custom-layoutrenderer-is-rendering-log-events-as-empty-string). But, here is (same kind of) information that is required by the template of a new issue:

**The environment:**

- Visual Studio 2017
- Project's .NET runtime version is 4.6.2
- XUnit version 2.3.1
- **NLog version 4.4.12**
- Fluent Assertions 4.19.4

**The problem:**

From the sample code below which can be run to reproduce the problem, we have 2 custom `LayoutRenderer`:  `RendererOne` and `RendererTwo`. Those 2 are then used in tests `TestA` and `TestB` respectively. When i run the test one at a time in Visual Studio, I do not get any problem. However, if were to run them in one go example via XUnit's "Run All" button, I get failed assertions as illustrated in the attached image below:

<img width="755" alt="xunit_renderer_run_all_fails" src="https://user-images.githubusercontent.com/6862577/35157434-a5da6c9a-fd3c-11e7-922a-b3792f8e1f6b.PNG">

The actual test is in the code below but briefly, test `SomeTest()` in `TestB` is expecting certain strings in intended Target (with Name `TestB`). The latter appears to receive those log events in its `Write()` method passes them to the configured renderer, `RendererTwo` (see additional screenshot below for confirmation of correct Layout configuration of the respective Targets). However, the renderer returns empty strings (`""`) which are stored in the `Messages` collection.

At the point where the assertion fails, I have a break in my visual studio program. Here is a screenshot of the relevant Targets and what is in there:

<img width="248" alt="renderer_not_found" src="https://user-images.githubusercontent.com/6862577/35157432-a5b8ccac-fd3c-11e7-8c98-1f0c9a62d874.PNG">

You can see that the messages do end up in the other target (because both Targets have same log-level settings) but the one that is being targeted by the failing test-case has same number of messages but are empty. Find below the log captured by the internal logger. At line `2018-01-19 17:04:41.9833 Info Shutting down logging...`, is when I have resumed the running of the test-run. So all lines before that pertain to `RendererTwo`.

[nlog.debug.txt](https://github.com/NLog/NLog/files/1646982/nlog.debug.txt)

I have also tried the 'old way' of registering the Renderers but, i have same problem. I another test run, i have also captured the LayoutRenderers that are currently available. Here is a screenshot of that and you can see that even though the code registers 2 renderers, there is only 1 when the break due to a failed assertion occurs:

<img width="543" alt="xunit_renderer_run_all_fails_missing_renderer" src="https://user-images.githubusercontent.com/6862577/35158467-d69b94dc-fd3f-11e7-9bd0-a87acd7f1382.PNG">

**Code under test + test-cases:**

```
using FluentAssertions;
using NLog;
using NLog.Common;
using NLog.Config;
using NLog.LayoutRenderers;
using NLog.Layouts;
using NLog.Targets;
using System;
using System.Collections.Concurrent;
using System.IO;
using System.Text;
using Xunit;

namespace LoggingTests
{
    [Target("test-target")]
    class TestTarget : TargetWithLayout
    {
        public ConcurrentBag<string> Messages = new ConcurrentBag<string>();

        public TestTarget(string name,
                          Layout layout)
        {
            Name = name;
            Layout = layout;
        }

        protected override void Write(LogEventInfo logEvent)
        {
            Messages.Add(Layout.Render(logEvent));
        }
    }

    class Log
    {
        private string _target_name;

        public Log(Layout layout,
                   string target_name)
        {
            if (LogManager.Configuration == null)
            {
                LogManager.Configuration = new LoggingConfiguration();
                InternalLogger.LogFile = Path.Combine(Environment.CurrentDirectory,
                                                      "nlog.debug.txt");
                InternalLogger.LogLevel = LogLevel.Trace;
            }

            _target_name = target_name;
            if (LogManager.Configuration.FindTargetByName<TestTarget>(_target_name) == null)
            {
                // Create the target:
                TestTarget target = new TestTarget(_target_name,
                                                   layout);

                // Register the target:
                Target.Register<TestTarget>(_target_name);

                // Add the target to the configuration:
                LogManager.Configuration.AddTarget(_target_name,
                                                   target);

                // Add a logging rule pertaining to the above target:
                LogManager.Configuration.AddRule(LogLevel.Trace,
                                                 LogLevel.Fatal,
                                                 target);

                // Because configuration has been modified programatically, we have to reconfigure all loggers:
                LogManager.ReconfigExistingLoggers();
            }
        }

        public void AssertLogContains(string message)
        {
            TestTarget target = LogManager.Configuration
                                          .FindTargetByName<TestTarget>(_target_name);
            target.Messages.Should().Contain(message);
        }
    }

    class Loggable
    {
        private Logger _logger;

        public Loggable()
        {
            _logger = LogManager.GetCurrentClassLogger();
        }

        public void Error(string message)
        {
            _logger.Error(message);
        }

        public void Info(string message)
        {
            _logger.Info(message);
        }
    }

    [LayoutRenderer("renderer-one")]
    class RendererOne : LayoutRenderer
    {
        protected override void Append(StringBuilder builder,
                                       LogEventInfo logEvent)
        {
            builder.AppendFormat($"{GetType().Name} - {logEvent.Level.Name}: {logEvent.Message}");
        }
    }

    [LayoutRenderer("renderer-two")]
    class RendererTwo : LayoutRenderer
    {
        protected override void Append(StringBuilder builder,
                                       LogEventInfo logEvent)
        {
            builder.AppendFormat($"{GetType().Name} - {logEvent.Level.Name} -> {logEvent.Message}");
        }
    }

    public class TestA
    {
        private Log _log;

        public TestA()
        {
            LayoutRenderer.Register<RendererOne>("renderer-one");
            //ConfigurationItemFactory.Default
            //                        .LayoutRenderers
            //                        .RegisterDefinition("renderer-one", typeof(RendererOne));
            _log = new Log("${renderer-one}", GetType().Name);
        }

        [Fact]
        public void SomeTest()
        {
            Loggable l = new Loggable();
            l.Info("Test A - SomeTest");
            l.Error("Test A - SomeTest");
            _log.AssertLogContains("RendererOne - Info: Test A - SomeTest");
            _log.AssertLogContains("RendererOne - Error: Test A - SomeTest");
        }

        [Fact]
        public void AnotherTest()
        {
            Loggable l = new Loggable();
            l.Info("Test A - AnotherTest");
            l.Error("Test A - AnotherTest");
            _log.AssertLogContains("RendererOne - Info: Test A - AnotherTest");
            _log.AssertLogContains("RendererOne - Error: Test A - AnotherTest");
        }
    }
    public class TestB
    {
        private Log _log;

        public TestB()
        {
            LayoutRenderer.Register<RendererTwo>("renderer-two");
            //ConfigurationItemFactory.Default
            //            .LayoutRenderers
            //            .RegisterDefinition("renderer-two", typeof(RendererTwo));
            _log = new Log("${renderer-two}", GetType().Name);
        }

        [Fact]
        public void SomeTest()
        {
            Loggable l = new Loggable();
            l.Info("Test B - SomeTest");
            l.Error("Test B - SomeTest");
            _log.AssertLogContains("RendererTwo - Info -> Test B - SomeTest");
            _log.AssertLogContains("RendererTwo - Error -> Test B - SomeTest");
        }
    }
}
```

**Comment by snakefoot** [comment]
Cannot reproduce the bug you describe when just pasting into the NLog-Unit-Test classes. But the NLog -UnitTest-project also has the following line in `AssemblyInfo.cs`

`[assembly: Xunit.CollectionBehavior(DisableTestParallelization = true)]`

**Comment by GrosLalo** [comment]
Adding the above configuration helped with the issue. i'Il close it (and also on SO).

**Comment by 304NotModified** [comment]
Strange, it was one class so there was no parallelism enabled by xunit?

**Comment by GrosLalo** [comment]
I had also made sure that Parallelization button in the XUnit Runner in Visual Studio was not enabled.

**Comment by 304NotModified** [comment]
Sounds like a xunit bug then, anyway, thanks for the feedback!

**Comment by snakefoot** [comment]
@304NotModified Not sure i understand the one class thing, it is a one file with two classes:

public class TestA
public class TestB
