### ISSUE TITLE
Make MDC and MDLC Set method using friendly

### ISSUE THREAD

**Issue by MikeFH** [NLog/NLog#2526]
**Type** :
- Feature request
 
**Why do we need it?**
This would make the MDC and MDLC usage easier when the goal is to capture scoped data.
For example :
```csharp
public void DoSomethingWithProduct(Product p) {
	using (MappedDiagnosticContext.Set("productId", p.Id)) {
		//do something	
	}
}
```
This is already present in NDC and NDLC.

I'am not sure about the performance inpact such a feature would have but if the returned `IDisposable` is a struct, maybe it wouldn't impact current users too much.

**Comment by 304NotModified** [comment]
> I'am not sure about the performance inpact such a feature would have but if the returned IDisposable is a struct, maybe it wouldn't impact current users too much.

I don't think this will hurt performance


PR would be nice !

**Comment by 304NotModified** [comment]
:) fixed, thanks!

**Comment by MikeFH** [comment]
Thanks !

**Comment by MikeFH** [comment]
@304NotModified Should I add something in the doc regarding the new methods ?

**Comment by 304NotModified** [comment]
Thanks for the suggestion. Where would you like to add it?

It's anyway already in the API docs, but more exposure would be nice.

**Comment by MikeFH** [comment]
I thought of adding something along the lines of 
> The SetScoped method returns an IDisposable that removes the added item when disposed. It can be used in conjunction with the using statement to limit the scope during which the item will be present in the context.

with a simple code example in those pages
https://github.com/NLog/NLog/wiki/MDLC-Layout-Renderer
https://github.com/NLog/NLog/wiki/MDC-Layout-Renderer

But I totally forgot about the API docs so, I agree, the need is limited.

**Comment by 304NotModified** [comment]
Yeah would be nice to add to the mdc and mdlc pages! please do :+1:

**Comment by MikeFH** [comment]
Alright, done !

**Comment by 304NotModified** [comment]
thanks!!
