### ISSUE TITLE
Remove Logger-V1Compat and ILoggerBase-V1

### ISSUE THREAD

**Issue by snakefoot** [NLog/NLog#2528]
Remove the following files from the NLog-solution:

ILoggerBase-V1.cs
Logger-V1Compat.cs

For NLog ver. 5

**Comment by 304NotModified** [comment]
I think this will be too much breaking change. There is also not really a benefit in removing it IMO

**Comment by snakefoot** [comment]
> I think this will be too much breaking change. 

But all log-methods are covered by the generic-version in Logger.cs, cannot see how it will break anything. The methods was created for .NET11 without generics.

**Comment by 304NotModified** [comment]
Yes, only a binary breaking change. But then probably all libraries that are build on nlog < 5 need a new version. That's huge

**Comment by 304NotModified** [comment]
I think there isn't a real benefit here and so I think it's better to keep the interfaces.

**Comment by snakefoot** [comment]
I want to reuse the name ILoggerBase for my PR for improved callsite capture. I have recognised that removal of these interfaces must be delayed until NLOG 6.0. But I think it should be done. These logger interfaces are terrible


Sent from my Samsung device


-------- Original message --------

**Comment by 304NotModified** [comment]
> These logger interfaces are terrible

Could you elaborate on this? It should not a problem with adding new code? 

Do you agree that this will be a (binary) breaking change in the logging API?

**Comment by snakefoot** [comment]
They are overly complicated. Should just have two methods Log and IsLevelEnabled. Rest should be extension methods.Interfaces are for mocking. Again this change is for Nlog 6.0



Sent from my Samsung device


-------- Original message --------

**Comment by 304NotModified** [comment]
> Do you agree that this will be a (binary) breaking change in the logging API?

Sorry, I will prevent any breaking change to the logging API as far possible. 

AFAIK this is a binary breaking change, thus "wont fix"

**Comment by snakefoot** [comment]
Thought major versions (Like Nlog6) was for breaking changes. Not sure I  understand how you are going to break up Nlog without making breaking changes (Ex moving config using xml into separate nuget package)


Sent from my Samsung device


-------- Original message --------

**Comment by 304NotModified** [comment]
> Thought major versions (Like Nlog6) was for breaking changes

that's true, but lot of libraries are build on the logging API. So breaking changes, even with major versions, should be prevented if possible.  The logging API is now binary compatible with NLog 1. 

Breaking changes on targets VS logging API is different

So NLog 5 and 6 could make breaking changes, but not in the logging API and we try to limit to breaking changes if that's possible - there should be a good reason to make a breaking change.
