### ISSUE TITLE
Written Log file using Unicode (UTF-16) encoding cannot be opened in some editors such as Notepad++ and VSCode

### ISSUE THREAD

**Issue by bergmeister** [NLog/NLog#2531]
**Type**:

- Bug

**NLog version**:  `4.5.0-rc04` (latest)

**Platform**: `Net 4.6.1`

**Current NLog config** (xml or C#, if relevant)

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" throwExceptions="true">

  <targets>
    <target name="file" type="File" fileName="${basedir}/log.txt" encoding="Unicode"/>
  </targets>
  <rules>
    <logger name="*" minLevel="Trace" writeTo="file" />
  </rules>
</nlog>
```

In case of a BUG:

- What is the current result? The [file](https://github.com/bergmeister/NLog_Unicode_Issue/blob/master/log.txt) being produced by the example [here](https://github.com/bergmeister/NLog_Unicode_Issue) cannot be opened correctly in Notepad++ or VSCode:
![image](https://user-images.githubusercontent.com/9250262/35216963-66ff6cb0-ff61-11e7-8306-52bbc07b803d.png)

- What is the expected result? Notepad++ or VSCode have proven to be well written editors capable of handling many file encoding scenarios already. It is unlikely that it is an issue on their side. Something in the written log by NLog must cause that.
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)? - NA
- Please post full exception details (message, stacktrace, inner exceptions) - NA
- Are there any work arrounds? Using UTF-8 but this is not really a workaround if I want Unicode
- Is there a version in which it did worked? I am not aware of it.
- Can you help us by writing an unit test? I provided a minimal example solution [here](https://github.com/bergmeister/NLog_Unicode_Issue) where you can just press F5 to get the log file.

**Comment by 304NotModified** [comment]
Isn't "Unicode" UTF-16? Can image most of the programs could not handle that.

Could you check the HEX of the file and see if this a NLog issue or the text editor?

**Comment by 304NotModified** [comment]
I think you need a BOM, (see https://github.com/Microsoft/vscode/issues/22564)

use `writeBom` (NLog 4.5+)


```xml
 <target name="file" type="File" fileName="${basedir}/log.txt" encoding="Unicode" writeBom="true" />

```

**Comment by bergmeister** [comment]
@304NotModified Yes, Unicode is `UTF-16` as far as I know (I am not an expert in encoding).
Thanks for the tip with `writeBom="true"`, this makes it work in `Notepad++` and `VSCode` now. :-)
Shall I close the issue then (I am wondering if it is not better for NLog to default to `writeBom="true"` for Unicode encoding)?

**Comment by bergmeister** [comment]
@304NotModified Do you know when NLog 4.5 will go from pre-release to release state?

**Comment by 304NotModified** [comment]
I created a new issue ( #2533) for that. Enabling the BOM is a behavior change, hence would be good to enable this in NLog 5.

> @304NotModified Do you know when NLog 4.5 will go from pre-release to release state?

few weeks, mostly docs that needs an update, there will be a RC5 also
https://github.com/NLog/NLog/milestone/62

Used structured logging? Having any feedback?

**Comment by bergmeister** [comment]
Thanks.
No, I haven't used structured logging, the product that I work on uses only simple Trace based file logging. I only happened to be looking at its `NLog` configuration because we could not see special characters, such a Japanese/Greek symbols in the log when doing testing for different locals.
My (opinionated) feedback would be to not use `Encoding.Default` as a default but maybe something better like e.g. `UTF-8`.
https://blogs.msdn.microsoft.com/shawnste/2005/03/15/dont-use-encoding-default/

**Comment by 304NotModified** [comment]
Good idea, created also an issue for that.

Thanks for feedback, gonna close this one a new github issues have been made
