### ISSUE TITLE
Enable BOM  by-default for UTF16/32

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#2533]
Should we enable the BOM by default for UTF16/32?

If so, should we implement this as whitelist or blacklist (e.g. UTF and not UTF8 => BOM)

See https://github.com/NLog/NLog/issues/2531

**Comment by snakefoot** [comment]
I think that UTF8 (without BOM) is the default file-format.

But yes if using obscure encoding like UTF16 + 32 then it is a good idea to include BOM by default. Because it will always be obscure encoding for any log-readers.

**Comment by 304NotModified** [comment]
Do you think it should be a white or black list?

**Comment by 304NotModified** [comment]
Related https://github.com/NLog/NLog/issues/2536

PS utf16 isn't obscure in SQL server (e.g nvarchar and utf8 isn't supported until SQL server 2019)

**Comment by 304NotModified** [comment]
This should be a white list
