### ISSUE TITLE
Rename IValueSerializer.FormatObject / simplify IValueSerializer

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#2535]
I was trying to create my custom IValueSerializerer, and having trouble to understand what to do in every method. Related https://github.com/NLog/NLog/pull/2534

proposal: rename `FormatObject` to `PrettyPrintObject` . 

https://github.com/NLog/NLog/blob/84174bd5c3624bd8864d1b71a20cb7ae08bb841e/src/NLog/IValueSerializer.cs#L72

OR another option,

remove all the 3 methods, move to 1 method (renderProperty/renderHole or something like that), and pass the format (Stringify, Serialize etc),

@snakefoot your opinion please :)

**Comment by snakefoot** [comment]
The 3 different methods matches the 3 different CaptureTypes @ $

But yes CaptureType is now public, so it can just be a be parameter to a single method

Sent from my Samsung device


-------- Original message --------

**Comment by 304NotModified** [comment]
OK, single method is the best way then, as all of them have the same signature.
