### ISSUE TITLE
Remove TemplateParser, replace tests

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#2541]
The TemplateParser is only used for unit testing.

This class should be removed and tests should be altered

update: same for TemplateRenderer.Render(Template)

**Comment by snakefoot** [comment]
Then you could also consider removing `internal class Template`. I just left everything there, in case you had special plans for it.

**Comment by 304NotModified** [comment]
Unfortunately I do the reviews from Github itself, and then it's hard to see if something is still used. I assumed it was still used. 

No special plans, and if so, it should not be in master ;)

**Comment by 304NotModified** [comment]
maybe I was wrong here. Other clients need of course the Template (and TemplateParser), for their structured logging. (e.g. Seq) - isn't?

**Comment by snakefoot** [comment]
> maybe I was wrong here. Other clients need of course the Template (and TemplateParser), for their structured logging. (e.g. Seq) - isn't?

Think Seq just wants to to have the result of the parsing, not to perform the parsing once more.

**Comment by 304NotModified** [comment]
Could be helpful. Keeping it for now
