### ISSUE TITLE
ValueSerializer remove legacy mode 

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#2543]
Because we have already the `string.format`, we should consider removing the legacy mode in the `ValueSerializer`.

Also for this we need to detect mixed mode better, see #2532

**Comment by snakefoot** [comment]
TemplateRenderer.Render() will not call string.Format, when parseMessageTemplates=true, instead it will use the method:

`RenderHole(sb, hole, formatProvider, parameters[hole.Index], true);`

Where the last true-parameter signals legacy mode (or simulate string.Format-mode)

**Comment by 304NotModified** [comment]
true, but i'm doubting if that's really needed. We could do `if indexed` then always use `string.format`, we need also to change `TemplateRenderer.Render(Template)` then.

I'm a bit confused by all the modes and legacy modes, while we also use string.format. The goal in the past was to remove the string.format (and therefor the legacy mode), we moved from that idea, and now we have 2 legacy modes - not the best way for maintaining it.

**Comment by snakefoot** [comment]
- **parseMessageTemplate = null** - Means that it will support both modes, but not mixed.
- **parseMessageTemplate = false** - Means that it will also use string.Format
- **parseMessageTemplate = true** - Means it will attempt to treat numeric-templates almost like string.Format, and handle structured-templates.

**Comment by snakefoot** [comment]
> now we have 2 render methodes (lazy and Template type) - not the best way for maintaining it.

Well I have just left the `Template`-type in case you had special plans for it. Not using it anywhere, beside in unit test to show that I didn't break it.

**Comment by 304NotModified** [comment]
I think we should leave it now as is.
