### ISSUE TITLE
Consuming NLog 4.5 within .NET Standard 1.4 library (not UWP)

### ISSUE THREAD

**Issue by zulfahmi93** [NLog/NLog#2546]
**Type**: Question
**NLog version**: 4.5.0-rc04
**Platform**: .NET Standard 1.4 (not UWP)

I have a .NET Standard 1.4 library project and I plan to use NLog for logging within the library. From the nuget package, I noticed that the minimum supported .NET Standard version is 1.5. However, when I browse the GitHub project, I noticed that `netstandard1.3` target framework is defined inside the NLog.csproj file [here][1]. The nuget package can also be consumed by Windows Phone 8.0 project which has the lowest .NET Standard version of 1.0 but no .NET Standard 1.3 is defined. So my question is, is it possible to consume the package within my library as currently the package cannot be installed into the project.

### Error Log
```
error NU1202: Package NLog 4.5.0-rc04 is not compatible with netstandard1.4 (.NETStandard,Version=v1.4). Package NLog 4.5.0-rc04 supports:
error NU1202:   - monoandroid44 (MonoAndroid,Version=v4.4)
error NU1202:   - net35 (.NETFramework,Version=v3.5)
error NU1202:   - net40-client (.NETFramework,Version=v4.0,Profile=Client)
error NU1202:   - net45 (.NETFramework,Version=v4.5)
error NU1202:   - netstandard1.5 (.NETStandard,Version=v1.5)
error NU1202:   - netstandard2.0 (.NETStandard,Version=v2.0)
error NU1202:   - sl4 (Silverlight,Version=v4.0)
error NU1202:   - sl5 (Silverlight,Version=v5.0)
error NU1202:   - uap10.0 (UAP,Version=v10.0)
error NU1202:   - wp8 (WindowsPhone,Version=v8.0)
error NU1202:   - xamarinios10 (Xamarin.iOS,Version=v1.0)
```
  [1]: https://github.com/NLog/NLog/blob/4c0acefa3d394f768b46ac8ba0cb39a018565ce4/src/NLog/NLog.csproj#L6

**Comment by snakefoot** [comment]
@zulfahmi93 Only if your own NLog.dll from the source code.

Any reason why you have to use netstandard1.4 instead of netstandard1.5 ?

**Comment by zulfahmi93** [comment]
@snakefoot the library is used by many projects and some of them are targeting Windows 10 build 14393 which unfortunately can consume .NET Standard 1.4 library or lower. Thanks for your reply. Never mind, I will close this and just find any workaround.

**Comment by snakefoot** [comment]
@zulfahmi93 I think the best solution for you is to add a dependency to `Microsoft.Extensions.Logging.Abstractions` until LibLog is supporting NetCore.

When NLog ver. 6 comes (probably in two years if we follow the current major release-speed), then we can lower the requirements for the core package. But I don't think you want to wait for that.
