### ISSUE TITLE
 constructor protection level to internal for `MessageTemplateParameters` and `MessageTemplateParameter`

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#2552]
constructor protection level to internal for

- MessageTemplateParameters
- MessageTemplateParameter

see https://github.com/NLog/NLog/pull/2544

**Comment by B3nCr** [comment]
Is there anything more to this or could a new contributor just fork and make these changes?

**Comment by snakefoot** [comment]
@B3nCr This is partially resolved by #2544 (Fixes `MessageTemplateParameters`) . Not sure how important it is to hide the constructors on `MessageTemplateParameter`
