### ISSUE TITLE
A build problem in NLog.UnitTests project

### ISSUE THREAD

**Issue by a14907** [NLog/NLog#2562]
Type (choose one):
Bug
NLog version: (e.g. 4.5.0-rc04)

I just clone the Project from github.And then open it by vs2017.
When I build it, All the other project is OK,except this project NLog.UnitTests.
The output show:
**Package Microsoft.AspNet.WebApi.Core 5.2.3 is not compatible with net452 (.NETFramework,Version=v4.5.2). Package Microsoft.AspNet.WebApi.Core 5.2.3 does not support any target frameworks.**

**Comment by snakefoot** [comment]
Think you need to clear your local nuget-cache in VS2017:

Tools -> Options -> Nuget Package Manager -> "Clear All Nuget Cache(s)".

And then perform a  `dotnet restore` from the command prompt:

`Repos\NLog\src>dotnet restore`

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, please let us know!
