### ISSUE TITLE
Archive all files level log every day

### ISSUE THREAD

**Issue by pisvthanh** [NLog/NLog#2564]
Hi Guys!

I want to archive all files level log every day but It is only archive one file in list files level log
Please help me!

My config:

> <targets async="true">
    <target name="LogFile" xsi:type="File" keepFileOpen="true"
      layout="${longdate} ${uppercase:${level}} ${newline} ${message} ${newline}"
      fileName="${basedir}/../logs/App-test.${shortdate}.${level}.log"
      archiveFileName="${basedir}/../logs/archives/App-test.{#}.gz"
      archiveEvery="Day"
      archiveNumbering="Date"
      archiveDateFormat="yyyyMMdd"
      maxArchiveFiles="30"
      enableArchiveFileCompression="true" />
  </targets>

![image](https://user-images.githubusercontent.com/36264007/35970386-c07193a6-0cfc-11e8-87aa-20898b29d56b.png)

**Comment by 304NotModified** [comment]
Please fill in the template, so we could help you with your issue, thanks!

**Comment by pisvthanh** [comment]
`<?xml version="1.0" encoding="utf-8"?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" throwExceptions="true" internalLogFile="c:\nlog.txt" internalLogLevel="Debug">
  <extensions>
    <add assembly="NLog.Extended" />
  </extensions>

  <targets async="true">
    <target name="LogFile" xsi:type="File" keepFileOpen="true"
      layout="${longdate} ${uppercase:${level}} ${newline} ${message} ${newline}"
      fileName="${basedir}/../logs/App-test.${shortdate}.${level}.log"
      archiveFileName="${basedir}/../logs/archives/App-test.{#}.gz"
      archiveEvery="Day"
      archiveNumbering="Date"
      archiveDateFormat="yyyyMMdd"
      maxArchiveFiles="30"
      enableArchiveFileCompression="true" />
  </targets>

  <rules>
    <logger name="*" levels="info,warn,error,debug,trace" writeTo="LogFile" />
    <logger name="Name.Space" minlevel="Debug" maxlevel="Error" final="true" />
  </rules>
</nlog>`

**Comment by pisvthanh** [comment]
You mean fill full file Nlog.config ?
```xml
<?xml version="1.0" encoding="utf-8"?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" throwExceptions="true" internalLogFile="c:\nlog.txt" internalLogLevel="Debug">
  <extensions>
    <add assembly="NLog.Extended" />
  </extensions>

  <targets async="true">
    <target name="LogFile" xsi:type="File" keepFileOpen="true"
      layout="${longdate} ${uppercase:${level}} ${newline} ${message} ${newline}"
      fileName="${basedir}/../logs/App-test.${shortdate}.${level}.log"
      archiveFileName="${basedir}/../logs/archives/App-test.{#}.gz"
      archiveEvery="Day"
      archiveNumbering="Date"
      archiveDateFormat="yyyyMMdd"
      maxArchiveFiles="30"
      enableArchiveFileCompression="true" />
  </targets>

  <rules>
    <logger name="*" levels="info,warn,error,debug,trace" writeTo="LogFile" />
    <logger name="Name.Space" minlevel="Debug" maxlevel="Error" final="true" />
  </rules>
</nlog>
```

**Comment by 304NotModified** [comment]
https://github.com/NLog/NLog/issues/new

**Comment by snakefoot** [comment]
@pisvthanh The problem is the `{shortdate}` in `fileName=`

> fileName="${basedir}/../logs/App-test.${shortdate}.${level}.log"

This means it rolls automatically, so the archive/compression-logic gets confused.

**Comment by pisvthanh** [comment]
I will be implement differently
Thanks!

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, please let us know!
