### ISSUE TITLE
NLog AsyncWrapper not logging all messages to console

### ISSUE THREAD

**Issue by the-petrolhead** [NLog/NLog#2565]
Hi! 

I have a question about NLog configuration:

I'm trying to setup NLog with AsyncWrapper, for a .NET Web API. The issue is I'm getting unexpected number of log messages on Console.

The issue is seen when load testing the API. The messages are logged properly with a single request.
Can anyone help me why logs are being swallowed?

For starters, I'm trying to use the AsyncWrapper target with a nested Console target. Is anything wrong with NLog configuration?

**NLog**: v5.0.0-beta11

**Platform**: .Net Core 1.0 

**Current NLog config XML**

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      internalLogLevel="Warn"
      internalLogFile="c:\temp\internal.txt">

  <!-- Load the ASP.NET Core plugin -->
  <extensions>
    <add assembly="NLog.Web.AspNetCore"/>
  </extensions>

  <!-- the targets to write to -->
  <targets>
    <!-- write to the void aka just remove -->
    <target xsi:type="Null" name="blackhole" />
    <target xsi:type="AsyncWrapper" overflowAction="Grow" queueLimit="10000">
      <target name='JsonConsole' xsi:type="Console"  >
        <layout xsi:type="JsonLayout" includeAllProperties='true'>
          <attribute name="eventTime" layout="${date:universalTime=true:format=yyyy-MM-ddTHH\:mm\:ss.fff:culture=en-us}" />
          <attribute name="level" layout="${level:upperCase=true}"/>
          <attribute name="message" layout="${message}" />
          <attribute name="eventName" layout="${aspnet-mvc-action}" />
          <attribute name="className" layout="${aspnet-mvc-controller}" />
          <attribute name="method" layout="${aspnet-request-method}" />
          <attribute name="referer" layout="${aspnet-request-referrer}" />
          <attribute name="user-Agent" layout="${aspnet-request-useragent}" />
          <attribute name="exception" layout="${exception:format=message, Type, ShortType, ToString, Method, StackTrace,Data:maxInnerExceptionLevel=2 }" />
        </layout>
      </target>
    </target>
  </targets>

  <!-- rules to map from logger name to target -->
  <rules>
    <!--Skip Microsoft logs and so log only own logs-->
    <logger name="Microsoft.*" minlevel="Trace" writeTo="blackhole" final="true" />
    <logger name="*" minlevel="Trace" writeTo="JsonConsole" />
  </rules>
</nlog>

```

I tried to set this up using the tutorial [https://github.com/NLog/NLog.Web/wiki/Getting-started-with-ASP.NET-Core-(csproj---vs2017)]

Can anyone help?

**Comment by snakefoot** [comment]
One error is that your Async-target is unnamed, and you are logging directly to the console (`JsonConsole`). Not sure how that works.

**Comment by the-petrolhead** [comment]
@snakefoot 
Thanks for your reply.

I tried naming the AsyncWrapper and then using the same instead of JsonConsole.
It doesn't resolve the issue. Still getting unexpected number of log messages on console.

Anything else I can try?

**Comment by snakefoot** [comment]
Nlog ensures to protect the console from multithreaded access. But if other threads are using the console directly then it will not work

Have you tried to configure Nlog to use a file target instead of the console. Just to ensure the right number of lines are written to file. Remember to configure the overflow action on the async target wrapper to be block



Sent from my Samsung device


-------- Original message --------

**Comment by 304NotModified** [comment]
> Still getting unexpected number of log messages on console.

Is it clear which log messages are missing? E.g all trace and debug, every first messages, the last messages etc

**Comment by 304NotModified** [comment]
Also recommend to update to NLog 4.5 RC

see

![image](https://user-images.githubusercontent.com/5808377/36090268-033985fa-0fe0-11e8-8e91-e0891744c5d1.png)


https://github.com/NLog/NLog#getting-started

**Comment by the-petrolhead** [comment]
@snakefoot @304NotModified 
Thanks for your inputs.

Some details on my project structure:

**LibraryX** intializes NLog. It also provides a logger implementation(consumed using DI).
**APIProject** is the WebAPI project(has controller/models) which uses LibraryX using DI.

**The issue:** Messages from controller are not always logged. If I load test the API with 10 requests, I should get 10 log messages from the controller(on method entry). I'm just seeing 2 logs in the console.

**Latest update:**
The issue occurs when APIProject uses a '**Release**' build of LibraryX.
When I use the '**Debug**' build of LibraryX, I'm getting messages logged as expected.

I tried building the 'Release' version of LibraryX by turning off 'Code Optimizations'. This successfully logs messages as expected.

I'm wondering what could be the code optimizations the compiler is applying which effectively swallows the log messages from controller. I'm trying to reach the to the root cause here.

Any directions on this?

**Comment by 304NotModified** [comment]
Sorry of I missed this...

Is this also an issue when writing to a file?

**Comment by the-petrolhead** [comment]
@304NotModified 
Yes. I can see the issue when writing to a file.

**Comment by 304NotModified** [comment]
and without the ` <logger name="Microsoft.*" minlevel="Trace" writeTo="blackhole" final="true" />`?

**Comment by the-petrolhead** [comment]
@304NotModified 

Works as expected without `<logger name="Microsoft.*" minlevel="Trace" writeTo="blackhole" final="true" />`

So how is blackhole target causing issue?

**Comment by 304NotModified** [comment]
Well I think some messages are wrongly  under Microsoft logger. You could check that with ${logger}

**Comment by the-petrolhead** [comment]
@304NotModified 
Appreciate your help.

I checked the missing logs for logger name using ${logger} and they are non Microsoft logs. 

Also, 
I tried with logger filters and it did the trick.
Updated configuration as follows:

```xml
    <rules>
      <!--<logger name="Microsoft.*" minlevel="Trace" writeTo="blackhole" final="true" />-->
      <logger name="*" minlevel="Trace" writeTo="JsonConsole" >
        <filters>
          <when condition="starts-with('${logger}', 'Microsoft.')" action="Ignore" />
          <when condition="equals('${logger}','ApiProjectLogger')" action="Log" />
        </filters>
      </logger>
    </rules>
```

While current configuration serves as a workaround for me, I'd still want to know why a Null(blackhole) target couldn't produce logs as expected.

Can you direct me on that?

**Comment by snakefoot** [comment]
Can you attach a sample app that reproduces the issue?



Sent from my Samsung device


-------- Original message --------

**Comment by the-petrolhead** [comment]
@snakefoot 

Unfortunately I cannot. The app I'm working now contains many specifics.
Will try finding the root cause and post an update when done.

Thank you for your support.
