### ISSUE TITLE
JsonLayout missing event properties fields when using network target

### ISSUE THREAD

**Issue by adrianpetcu** [NLog/NLog#2569]
There seems to be an issue when logging only to the network target, with JsonLayout: the fields obtained from the event-properties are missing.

All the data is present when logging to a file target, or both file and network targets.

I created a sample here: https://github.com/adrianpetcu/nlog-networktarget-issue.

NLog version: 4.4.12
Platform: .Net 4.5

**Comment by 304NotModified** [comment]
you need includeAllProperties ? 

e.g.

```
   <layout xsi:type="JsonLayout" includeAllProperties="true"
```

See https://github.com/NLog/NLog/wiki/JsonLayout

**Comment by adrianpetcu** [comment]
Even with includeAllProperties="true", the two fields coming from the event properties are missing when using the network target alone.

I attached the internal log files for the two cases as txt (I stripped the date info, to ease the file diff)

[networkOnly.txt](https://github.com/NLog/NLog/files/1716093/networkOnly.txt)
[fileAndNetwork.txt](https://github.com/NLog/NLog/files/1716094/fileAndNetwork.txt)

**Comment by 304NotModified** [comment]
Could you update the nlog.config?


> Even with includeAllProperties="true", the two fields coming from the event properties are missing when using the network target alone.

it's working in the file target? The code for JSONlayout is independent of the target, so it sounds like a config issue

**Comment by adrianpetcu** [comment]
Changed nlog.config, see the attached files:

- file only target - all the fields are logged 
- network only target - logging works, but two fields are missing
- both file + network - all the fields are logged (file & network, too)


[NLog.fileOnlyConfig.txt](https://github.com/NLog/NLog/files/1716375/NLog.fileOnlyConfig.txt)
[NLog.networkOnlyConfig.txt](https://github.com/NLog/NLog/files/1716376/NLog.networkOnlyConfig.txt)
[NLog.bothTargetsConfig.txt](https://github.com/NLog/NLog/files/1716377/NLog.bothTargetsConfig.txt)

**Comment by 304NotModified** [comment]
that's strange! There is no logical reason for this. 

With the two fields, do you mean `${event-properties:item=dbResponseTime}` and `${event-properties:item=messagesSentTotal}`

I seems a bug, could you please fill in the template from https://github.com/NLog/NLog/issues/new?

**Comment by adrianpetcu** [comment]
Yes, ${event-properties:item=dbResponseTime} and ${event-properties:item=messagesSentTotal} are missing. I added https://github.com/NLog/NLog/issues/2573. Thanks!
