### ISSUE TITLE
Max numbers of day of archive file, not max archive file

### ISSUE THREAD

**Issue by PingPongSet** [NLog/NLog#2574]
Type:

Bug/New feature

NLog version:

4.4.11

Platform:

.Net 4.5

NLog config
```xml
<target name="asyncFile" xsi:type="AsyncWrapper" >
  <target xsi:type="File"
              fileName="c:/logs/${shortdate}.log"
              archiveFileName="c:/logs/archive/{#}.log"
          archiveAboveSize="1024"
          maxArchiveFiles="5"
          archiveEvery="Day"
          archiveDateFormat="yyyy-MM-dd"
          archiveNumbering="DateAndSequence">      
  </target>
</target>
```

I need to archive log file based on the numbers of days, not the numbers of log files. Below works, except when log file size exceeds 1024 bytes in a day. In that case, the archive log file might contain all five log files for today (5*1024), and all other log files from previous day are deleted as a result.

I don't want to increase the size of archiveAboveSize, which might affect the performance of my application.

Expected: 
Archive filename:  
```
2017-07-21.0.log
2017-07-22.0.log
2017-07-23.0.log
2017-07-24.0.log
2017-07-25.0.log
2017-07-25.1.log
2017-07-25.2.log
2017-07-25.3.log
2017-07-25.4.log
```

Actual: Archive filename: 
```
2017-07-25.0.log
2017-07-25.1.log
2017-07-25.2.log
2017-07-25.3.log
2017-07-25.4.log
```

**Comment by 304NotModified** [comment]
> maxArchiveFiles="5"

I would never expect more then 5 files. I think your expectation is wrong. 

I'm don't think that there is a bug here, only something we won't support currently

**Comment by 304NotModified** [comment]
Think also, so close as dupl of #311
