### ISSUE TITLE
error. Parameter name: userName Value cannot be null. 

### ISSUE THREAD

**Issue by vankampenp** [NLog/NLog#2577]
**Type** (choose one):

- Bug

**NLog version**:4.5.0-rc2

**Platform**: .NET Core  2.0

**Current NLog config** (xml or C#, if relevant)

```xml
<targets async="true">
    <!-- write logs to file -->
    <target xsi:type="File" name="allfile" fileName="logs\${machinename}-all-${shortdate}.log"
            layout="${longdate}|${aspnet-request-ip}|${aspnet-User-Identity}|${pad:padding=-5:${uppercase:${level}}}|${assembly-version}|${event-properties:item=EventId.Id}|${logger}|${aspnet-mvc-controller}|${callsite:className=True:includeNamespace=False:fileName=False:includeSourcePath=False:methodName=True}|${message} ${exception}" 
            maxArchiveFiles="2"
            archiveFileName="logs\archive\${machinename} -all.{#}.zip" 
            archiveNumbering="Date"
            archiveEvery="Day"
            archiveDateFormat="yyyyMMdd"
            enableArchiveFileCompression ="true"
    />
    <!-- another file log, only own logs. Uses some ASP.NET core renderers -->
    <target xsi:type="File" name="ownFile-trace" fileName="logs\${machinename}-trace-${shortdate}.log"            
            layout="${longdate}|${aspnet-request-ip}|${machinename} |${pad:padding=-5:${uppercase:${level}}}|${assembly-version}|${pad:padding=-3:${threadid}}|${aspnet-mvc-controller}|${callsite:className=True:includeNamespace=False:fileName=False:includeSourcePath=False:methodName=True}|${message} ${exception}" 
            maxArchiveFiles="14"
            archiveFileName="logs\archive\${aspnet-Request-Host}-trace.{#}.zip" 
            archiveNumbering="Date"
            archiveEvery="Saturday"
            archiveDateFormat="yyyyMMdd"
            enableArchiveFileCompression ="true"
            />
  
    <target xsi:type="File" name="ownFile-info" fileName="logs\${machinename}-info-${shortdate}.log"
            layout="${longdate}|${aspnet-request-ip}|${aspnet-User-Identity}|${pad:padding=-5:${uppercase:${level}}}|${assembly-version}|${aspnet-mvc-controller}|${callsite:className=True:includeNamespace=False:fileName=False:includeSourcePath=False:methodName=True}|${message} ${exception}"
            maxArchiveFiles="3000"
            archiveFileName="logs\archive\${machinename}-info.{#}.zip"
            archiveNumbering="Date"
            archiveEvery="Month"
            archiveDateFormat="yyyyMMdd"
            enableArchiveFileCompression ="true"
    />
    <target xsi:type="ColoredConsole"
            name="ColoredConsole"
            layout="${aspnet-User-Identity}|${event-properties:item=EventId.Id}|${uppercase:${level}}|${logger}|${message} ${exception}"
            header="${longdate}"
            footer="${longdate}"
            useDefaultRowHighlightingRules="True"
           
            detectConsoleAvailable="True">
    </target>
```

In case of a BUG:

- What is the current result?
I am getting a null error on username. At this point there is no logged in user name yet. 
```
2018-02-14 08:25:55.3743|<ipaddress>||INFO |7.6.3.0||Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker|Home|Logger.Log|Executed action DTOWEB.Areas.Online.Controllers.HomeController.Default (DTOWEB) in 487.8857ms 
2018-02-14 08:25:56.0004|<ipaddress>||ERROR|7.6.3.0||Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|Home|Logger.Log|An unhandled exception has occurred: Value cannot be null.
Parameter name: userName Value cannot be null.
Parameter name: userName
2018-02-14 08:25:56.0108|<ipaddress>||INFO |7.6.3.0||Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker|Base|Logger.Log|Executing action method DTOWEB.Controllers.BaseController.Index (DTOWEB) with arguments (, , , 0) - ModelState is Valid 

```
- What is the expected result?
I would expect the username part of the log to be empty, and not get an error from the logging system

This is not consistent on all requests, not sure when it happens and when not.

- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
Nothing logged there
- Please post full exception details (message, stacktrace, inner exceptions)
- Are there any work arrounds? no
- Is there a version in which it did worked?  unknown
- Can you help us by writing an unit test?
probably not

**Comment by 304NotModified** [comment]
What the version of the other NLog compontents?

**Comment by vankampenp** [comment]
I do not have any other NLog components. There is an internal log, with InternalLogLevel="Warn", which is now changed to Trace:

`<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       internalLogToConsoleError="true"
       internalLogLevel="Trace"
      internalLogFile="logs\internal-nlog.txt"
      throwExceptions="true">`

**Comment by vankampenp** [comment]
I don't think it is an Nlog exception, but an exception is caused in the middleware:
```
2018-02-15 08:23:06.0932|212.238.163.42||ERROR|7.6.3.0||Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|Home|Logger.Log|An unhandled exception has occurred: Value cannot be null.
Parameter name: userName Value cannot be null.
Parameter name: userName
```
No error is written to internal-nlog.txt

**Comment by 304NotModified** [comment]
> I don't think it is an Nlog exception, but an exception is caused in the middleware:

Agree, so we can't fix it? It's an issue in the middleware? 

Or am I missing something?

**Comment by vankampenp** [comment]
It appears to be a log error in the middleware. So my assumption is that Nlog sends the null value. But that could be wrong.

**Comment by 304NotModified** [comment]
ah that could be the case that we should prevent this

I guess it from `${aspnet-User-Identity}`, but not sure. Any way the source of `${aspnet-User-Identity}` is pretty easy: https://github.com/NLog/NLog.Web/blob/master/NLog.Web.AspNetCore/LayoutRenderers/AspNetUserIdentityLayoutRenderer.cs

Dunno how to prevent this.

**Comment by 304NotModified** [comment]
could you test if it's from ` `${aspnet-User-Identity}``?

**Comment by snakefoot** [comment]
@vankampenp Could you change all your `${exception}` into `${exception:format=tostring}` ? (Update your `nlog.config`)

Then you will get the stacktrace of the exception.

**Comment by 304NotModified** [comment]
Good one!

**Comment by vankampenp** [comment]
Will do the above, thanks

**Comment by vankampenp** [comment]
Thanks that worked! Embarrassing: it was me. _userManager.FindByNameAsync does not work when you search for null. Sorry guys

**Comment by 304NotModified** [comment]
Np, thanks for the feedback!
