### ISSUE TITLE
Allow to log ReflectedType instead of DeclaredType in $callsite when logging from base class

### ISSUE THREAD

**Issue by SylwesterZarebski** [NLog/NLog#2579]
**Type**: Feature request

**NLog version**: 4.4.11

**Platform**: .Net 4.5

**Current NLog config**: I'm using `${callsite:className=true:methodName=true}`

**Description**:  
I have base class which log some information, but currently $callsite logs DeclaredType and i need to log derived class (ReflectedType).

**Example**:
```
public abstract class A
{
    protected Logger Logger { get; } = null;
    public A()
    {
        Logger = LogManager.GetCurrentClassLogger();
    }
    public void BaseMethod()
    {
        Logger.Trace("Run BaseMethod()");
        ... some other code ...
    }
}
public sealed class B : A
{
    public void DerivedMethod()
    {
         BaseMethod();
    }
}
```

Log has `A:BaseMethod` and i need `B:BaseMethod`, because i have very many (about 20) derived classes and base class has all common code.
Above code is an example, current one is way more complicated with events etc.

**Comment by snakefoot** [comment]
@SylwesterZarebski Have you actually tested that this is possible?

Looking at the documentation then it doesn't seem possible:

> The method that is currently executing may be inherited from a base class, although it is called in a derived class. In this case, the ReflectedType property of the MethodBase object that is returned by GetMethod identifies the base class, **_not the derived class_**.

https://msdn.microsoft.com/en-us/library/system.diagnostics.stackframe.getmethod.aspx

**Comment by SylwesterZarebski** [comment]
I did test simple case using GetMethod("Method").ReflectedType and it works, i did not test with StackTrace. If it behave as written, i do not know how it should be resolved, maybe there is some other way to get this information?
Without this logging from base classes is way harder, every message has to contain extra GetType().

**Comment by snakefoot** [comment]
@SylwesterZarebski If you promise to use `LogManager.GetCurrentClassLogger()` in your classes, then I recommend you always use `${logger}` instead of `${callsite:className=true:methodName=true}`

Because the callsite-logic is super expensive right now, because the overhead of creating the StackTrace is huge. Trying to improve on this with #2527

**Comment by SylwesterZarebski** [comment]
Thanks, then i should have:
`${logger}.${callsite:className=false:methodName=true}`
instead of:
`${callsite:className=true:methodName=true}`
to get:
`<classtype>.<methodname>`
Correct?

**Comment by snakefoot** [comment]
Yes until someone creates PR, that adds support for ReflectedType in CallSite (if it is possible).

**Comment by SylwesterZarebski** [comment]
Using ${logger} do not give me satisfying results, it also give me base class instead of real class (as GetType()). Do You have any other ideas how to use class logging as in first code example?

**Comment by snakefoot** [comment]
>  Found it, this code makes me happy: 

Yes it looks very similar to this:

https://github.com/NLog/NLog/wiki/How-to-create-Logger-for-sub-classes

**Comment by SylwesterZarebski** [comment]
Thanks, i could not find that before.
Please, add some note to Tutorial with some more explanation of this behaviour, because i was sure, that GetCurrentClassLogger() means current = derived class like GetType() shows.

**Comment by snakefoot** [comment]
Closing since `ReflectedType` is not available when probing dotnet StackTrace.
