### ISSUE TITLE
Move WCF targets to NLog.WCF package

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#2582]
and move to NLog.WCF

See also https://github.com/NLog/NLog/issues/1955

**Comment by snakefoot** [comment]
Will also help Mono Apps, as they don't have to install `libmono-system-servicemodel4.0a-cil` make NLog work.

**Comment by snakefoot** [comment]
Will also help using NLog within SQL CLR projects.

**Comment by snakefoot** [comment]
Will also help Xamarin Apps as one doesn't have to pay for Xamarin business edition to use NLog. Because NLog will no longer reference System.ServiceModel.
