### ISSUE TITLE
Create ${callsite-filename}

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#2583]
Create ${callsite-filename} that only prints the filename and not the line number.

See https://github.com/NLog/NLog/issues/2483

**Comment by zhulika** [comment]
Also, please output the full path name and do not change the string in any way. Do not change "\" into "/", do not convert to a UNC path, and do not wrap it in any other punctuation. Simply print the string exactly as the operating system supplies it. If you really have to mangle the string, please add an option that allows me to suppress the mangling, and to report the filename exactly as the operating system expects it to be formatted.

I have automation scripts that need to parse the output.

**Comment by brunotag** [comment]
Hi :) I'd be keen to give it a shot if that's ok.

So the closest thing we have at the moment is 
```{callsite:className=False:methodName=False:fileName=True}```
which gives us
```(C:\Dev\NLog\src\TestApp\Program.cs:25)```

And instead we want a new, independent
```${callsite-filename}```
to get
```C:\Dev\NLog\src\TestApp\Program.cs``` 
or anyway the file name as it comes from the OS

is that right?

**Comment by 304NotModified** [comment]
> Hi :) I'd be keen to give it a shot if that's ok.

That would be great! 👍 

> is that right?

yes that's correct. While there is already a `${callsite}`, there is also a `${callsite-linenumber}`, so `${callsite-filename}` looks consistent to me. 

It will look a bit like https://github.com/NLog/NLog/blob/master/src/NLog/LayoutRenderers/CallSiteLineNumberLayoutRenderer.cs


One thing, maybe `${callsite-filepath}` is a better name? What do you think?

**Comment by zhulika** [comment]
My vote is for ```${callsite-filename}```, but I don't really mind either way. The key thing for me is that it should be possible to get hold of the full path-name exactly as returned by the operating system.

It might be worth considering options to return the full path, just the folder/directory, or the filename with extension or just the filename with no extension but, for me, those are nice-to-haves. I don't think that I would use them.

**Comment by 304NotModified** [comment]
OK `${callsite-filename}` then :)

**Comment by brunotag** [comment]
`${callsite-filename}`, with  `${callsite-filenameincludeSourcePath=Boolean}` true by default, which would be consistent with `${callsite}`

**Comment by brunotag** [comment]
https://github.com/NLog/NLog/pull/2591

**Comment by brunotag** [comment]
Wiki: https://github.com/NLog/NLog/wiki/Call-site-file-name-layout-renderer

**Comment by 304NotModified** [comment]
thanks @brunotag !

**Comment by brunotag** [comment]
no worries. It's done and released right? 
https://github.com/NLog/NLog/releases/tag/v4.5
Should we close the issue?

**Comment by 304NotModified** [comment]
yes it could be closed now, thanks!
