### ISSUE TITLE
Change JsonLayout.MaxRecursionLimit default value to 1

### ISSUE THREAD

**Issue by snakefoot** [NLog/NLog#2588]
NLog 5.0 should increase the MaxRecursionLimit to 1 (Thus enabling object reflection by default).

**Comment by 304NotModified** [comment]
And what about 10 for this?

**Comment by snakefoot** [comment]
Exception objects are dangerous. Can have object references  to the entire database. Maybe special protection for those?


BTW would prefer that the Data dictionary was not included by default for exception output. You talk about good default and I think Data can be unsafe. Also need protection from bad objects  in Data that throw exception on ToString.


Sent from my Sony Xperia


---- Julian Verdurmen wrote ----


And what about 10 for this?

**Comment by snakefoot** [comment]
About removing exception Data from default output. Then one could have an app that processes 500Kbyte json docs. If an error happens then it might add an reference to the JObject in Exception.Data suddenly NLog will dump the 500Kbyte into the log file.


Like one can optin for possible crazy output. But not that one needs to explicitly OptOut from getting possible crazy output.


Sent from my Sony Xperia


---- Julian Verdurmen wrote ----


And what about 10 for this?

**Comment by 304NotModified** [comment]
Maybe we should only print primitive types for data by default.

**Comment by 304NotModified** [comment]
Or Maybe even better, limit the results of data. E.g. max 250 chars (configurable)

**Comment by snakefoot** [comment]
That could be a good idea. This could also be applied for the JsonSerializer. It could be types that are IConvertible or IFormatable


Sent from my Sony Xperia


---- Julian Verdurmen wrote ----


Maybe we should only print primitive types for data by default.

**Comment by snakefoot** [comment]
You would still perform huge allocations first and then truncate afterwards.


Sent from my Sony Xperia


---- Julian Verdurmen wrote ----


Or Maybe even better, limit the results of data. E.g. max 250 chars (configurable)

**Comment by 304NotModified** [comment]
If that is for exception, I think it's less bad. If you log multiple exceptions in a short period, there is something else wrong ;)

**Comment by 304NotModified** [comment]
Anyway, about the "data". I recommend other not to do this:

```
try
{
    Foo();
}
catch (Exception exception)
{
    Logger.Warn(exception, "something with id {Id}", id);
    throw;
}

```

as this will lead to duplicate error logs, with different context. 

But this is better:

```c#
try
{
    Foo();
}
catch (Exception exception)
{
    exception.Data["Id"] = id;
    throw;
}

```
and so only log at the end (when we not (re)throw it)

**Comment by 304NotModified** [comment]
alternatively we could do something like this (but hard reference to NLog)

```c#
try
{
    Foo();
}
catch (Exception exception)
{
    exception.Data["Id"] = new NLogContextData(id);
    throw;
}

```

or 
```c#
try
{
    Foo();
}
catch (Exception exception)
{
    exception.Data["NLog:Id"] = id;
    throw;
}


```

**Comment by snakefoot** [comment]
Think you will be surprised how many exceptions you can get in an application running on 56 cpu-cores with 100 threads running at 95 pct which suddenly gets into a momentarily bad state. And the threads try again and again to get out of the bad state.


Sent from my Sony Xperia


---- Julian Verdurmen wrote ----


If that is for exception, I think it's less bad. If you log multiple exceptions in a short period, there is something else wrong ;)

**Comment by snakefoot** [comment]
I like your idea of only outputting primitive data by default (IConvertible + IFormatable)


But the whole issue could also be "solved" by having ToString as default. (Without Data)


Sent from my Sony Xperia


---- Julian Verdurmen wrote ----


alternatively we could do something like this (but hard reference to NLog)

try
{
    Foo();
}
catch (Exception exception)
{
    exception.Data["Id"] = new NLogContextData(id);
    throw;
}


or

try
{
    Foo();
}
catch (Exception exception)
{
    exception.Data["NLog:Id"] = id;
    throw;
}

**Comment by 304NotModified** [comment]
>  by having ToString as default. (Without Data)

Yes, I understand, but see https://github.com/NLog/NLog/issues/2588#issuecomment-500116491

**Comment by 304NotModified** [comment]
-> https://github.com/NLog/NLog/issues/3463

**Comment by snakefoot** [comment]
Yes people who know their own app and all its dependent libraries are not injecting funky stuff into Data-dictionary can then explicitly add it to their NLog-config. But very few apps can make this promise.


Sent from my Sony Xperia


---- Julian Verdurmen wrote ----


by having ToString as default. (Without Data)

Yes, I understand, but see #2588 (comment)<https://github.com/NLog/NLog/issues/2588#issuecomment-500116491>

**Comment by snakefoot** [comment]
Funny how you mention the serilog exception enricher. It is actually because of issues with out-of-memory caused by this enricher that I want NLog to avoid the same mistakes.


Sent from my Sony Xperia


---- Julian Verdurmen wrote ----


-> #3463<https://github.com/NLog/NLog/issues/3463>

**Comment by snakefoot** [comment]
After seeing that `ExceptionLayoutRenderer.AppendData` only appends the `ToString()`-output and not performs object-reflection of any kind, then I think all my worries are unwarranted.

Closing this issue as I think it is fine with having `Format=ToString,Data` as default.
