### ISSUE TITLE
Lost log statements target on application (AppDomain) close (when async writing)

### ISSUE THREAD

**Issue by eirikb** [NLog/NLog#259]
Since the WebService target is asynchronous messages are lost if the application close before log statements are sent.

Here is a basic example of our program and config:

Program.cs

``` C#
using NLog;

namespace ConsoleTest
{
    internal class Program
    {
        private static void Main()
        {
            var logger = LogManager.GetLogger("MyLog");
            logger.Info("Hello, world!");
            logger.Info("Hello, world again!");
        }
    }
}
```

nlog.config

``` XML
<?xml version="1.0" encoding="utf-8" ?>
<nlog>
  <targets>
      <target name="ws" xsi:type="WebService" namespace="http://tempuri.org" methodName="SaveLog" url="http://ourserver.com/">
        <parameter name="message" type="String" layout="${message}"/>
      </target>
  </targets>

  <rules>
    <logger name="MyLog" minlevel="Info" writeTo="ws" />
  </rules>
</nlog>
```

We have tried some different approaches so far, such as wrapping the target _ws_ in `AutoFlushWrapper` (writeTo that wrapper) and even calling `LogManager.Flush()` but this did not help.  
If we use `AsyncWrapper` we seem to be able to flush out one of the messages, but not all.

**Comment by 304NotModified** [comment]
@Xharze could you help me with this issue? do you fully understand the issue and is this solvable?

**Comment by 304NotModified** [comment]
I think we need [`currentAppDomain_DomainUnload` ](https://github.com/NLog/NLog/blob/1714e4277097b0abe95e4013dccf55909f0051b0/src/NLog/LogFactory.cs#L103) and flush all the targets

**Comment by 304NotModified** [comment]
Fixed by https://github.com/nlog/nlog/pull/1868
