### ISSUE TITLE
Logging to multiple targets in ASP.NET Core 2.0 in same controller

### ISSUE THREAD

**Issue by krishnan-unni** [NLog/NLog#2593]
**Type** : Question
**NLog version**: 4.5.0-rc2

Hi

I am using Nlog.Web.Aspnetcore in my asp.net core 2.0 web api. In my nlog.config I have the target defined like this:
```
<targets>
    <target name="file1" xsi:type="File" fileName="${logDirectory}/file1.log"/>
</targets>
```

I use the ILogger in my controller to get the logger and use it. The logging works fine. Now I add another target to the config.
```
<targets>
    <target name="file1" xsi:type="File" fileName="${logDirectory}/file1.log"/>
    <target name="file2" xsi:type="File" fileName="${logDirectory}/file2.log"/>
</targets>
```

I want to log separate data to these separate targets in the same controller. E.g. logger.LogWarn("Data") to file1.log and logger.LogWarn("AnotherData") to file2.log. How do I achieve this with NLog without breaking the Asp.Net Core's DI system. In other words How do I create\target logger to different Nlog targets to log different data.

**Comment by 304NotModified** [comment]
something like this:

```xml
 <rules>
        <logger name="*" minlevel="Trace" writeTo="file1" />
        <logger name="*" minlevel="Info" writeTo="file2" />
    </rules>
```

or 

```xml
 <rules>
        <logger name="*" minlevel="Trace" writeTo="file1, file2"/>
    </rules>
```

see https://github.com/NLog/NLog/wiki/Tutorial#configuration

**Comment by snakefoot** [comment]
Think @krishnan-unni wants logging from one app-location to hit `file1` and logging from another app-location to reach `file2` (Not all logging put into both files)

The fastest way to do this is using the name of the logger to route to the right file. See also:

https://github.com/NLog/NLog/wiki/Tutorial#logger-specific-routing

And:

https://github.com/NLog/NLog/wiki/Filtering-log-messages

**Comment by krishnan-unni** [comment]
Thank you for the quick response @304NotModified  and @snakefoot . My scenario is, I have added Nlog.Web.Aspnetcore nuget package to my solution and have configured it as per the startup tutorial for aspnet core app in NLog website. I have not done any wrapping or anything. In my controller I am using ILogger<HomeController> logger in the constructor. So the question is if I have only this one logger for the controller, how do I log different data to different target (as my original post) for the same log level (say, LogWarn). So it's like logger.LogWarn("Data1");  logger.LogWarn("Data2"); How do I tell logger to put these two logs in two different files. Let's say I am ok with creating different logger for the controller using ILoggerFactory, how do I tell those loggers to log to different files\targets?
Hope you understand my question. Is there any samples I can find regarding the context?

In case of Log4Net, for two appenders (targets), I can use the appender name to be create the logger and redirect data to different targets through each logger. Is it possible in NLog for ASP net core?

**Comment by snakefoot** [comment]
Yes NLog support filtering based on the Logger Name (as it has been repeated several times here, and also stated in the documentation provided for you). 

If you can use `ILoggerFactory` to create two loggers called `logger1` and `logger2`, then your nlog.config could look like this:

```
<targets>
    <target name="file1" xsi:type="File" fileName="${logDirectory}/file1.log"/>
    <target name="file2" xsi:type="File" fileName="${logDirectory}/file2.log"/>
</targets>
<rules>
    <logger name="logger1" minlevel="Trace" writeTo="file1" />
    <logger name="logger2" minlevel="Info" writeTo="file2" />
</rules>
```

Where `logger1` writes to `file1`, and `logger2` writes to `file2`

**Comment by krishnan-unni** [comment]
Understood now. Thank you so much. Really appreciate it guys

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, please let us know!

**Comment by krishnan-unni** [comment]
@304NotModified yes it is answer. That very much.
