### ISSUE TITLE
There is a System.IO.IOException when I use NLog for Log information

### ISSUE THREAD

**Issue by Billy-ZGJ** [NLog/NLog#2594]
- Question

**NLog version**: 4.3.6

**Platform**: .Net 4.5

**Current NLog config** (xml or C#, if relevant)

```xml
    <target xsi:type="File" name="f" fileName="${basedir}/logs/PollerLog.log"
                layout="${date:format=yyyy\-MM\-dd HH\:mm\:ss} ${uppercase:${level}}&#009;${message}"
                archiveAboveSize="500000000"
                archiveNumbering="DateAndSequence"
                maxArchiveFiles="100"
                enableArchiveFileCompression ="true"/>
    </targets>

```

Exception which is System.IO.IOException happened some time when file is compressed or process is restarted. 

2018-02-11 14:17:54 INFO	System crash, reason is System.IO.IOException: The file "E:\poller\logs\PollerLog.log" is in use by another process, so the process cannot access this file.
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.File.InternalDelete(String path, Boolean checkHost)
   在 NLog.Targets.FileTarget.DeleteAndWaitForFileDelete(String fileName)
   在 NLog.Targets.FileTarget.ArchiveByDateAndSequence(String fileName, String pattern, LogEventInfo logEvent)
   在 NLog.Targets.FileTarget.ProcessLogEvent(LogEventInfo logEvent, String fileName, Byte[] bytesToWrite)
   在 NLog.Targets.Target.Write(AsyncLogEventInfo logEvent)
   在 NLog.Targets.Target.WriteAsyncLogEvent(AsyncLogEventInfo logEvent)
   在 NLog.LoggerImpl.WriteToTargetWithFilterChain(TargetWithFilterChain targetListHead, LogEventInfo logEvent, AsyncContinuation onException)
   在 NLog.LoggerImpl.Write(Type loggerType, TargetWithFilterChain targets, LogEventInfo logEvent, LogFactory factory)
   在 NLog.Logger.Info(Exception exception, String message, Object[] args)
   在 System.Windows.Threading.Dispatcher.CatchException(Exception e)
   在 MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   在 System.Windows.Threading.DispatcherOperation.InvokeImpl()
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   在 System.Windows.Threading.DispatcherOperation.Invoke()
   在 System.Windows.Threading.Dispatcher.ProcessQueue()
   在 System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

 Above is the log when process is restarted. I suspect it was caused by file compression.

**Comment by snakefoot** [comment]
`enableArchiveFileCompression` is not implemented very well. Some patches has been made in newer version of NLog. I recommend you update to NLog 4.4.12 (Or perform the log-file compression using external tool)

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, please let us know!
