### ISSUE TITLE
NLog 4.4 cannot handle new ReadOnlySpan implicit operator on string

### ISSUE THREAD

**Issue by snakefoot** [NLog/NLog#2598]
Spun up a quick docker container as smoke test:

```
    root@8391e3c12c9c:/# mono --trace=exceptions /opt/NzbDrone/NzbDrone.exe
    [0x7f0e0fc97740:] EXCEPTION handling: System.ArgumentException: Object of type 'System.ReadOnlySpan`1[System.Char]' cannot be converted to type 'System.String'.
    [0x7f0e0fc97740:] EXCEPTION handling: NLog.NLogConfigurationException: Error when setting property 'Format' on Layout Renderer: ${exception}
```

Not sure what to make of it, but wild guess some newer dotnet core code in mono broke backward compat. Can't look into it further today, so yeah, you might want to downgrade to the 5.8 snapshot.

https://www.reddit.com/r/sonarr/comments/80g1e2/broken_after_upgrade_to_mono_510_stable/

Think this is causing the issue:

```c#
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator ReadOnlySpan<char>(string value) =>
value != null ? new ReadOnlySpan<char>(ref value.GetRawStringData(), value.Length) : default;
```

https://github.com/dotnet/coreclr/blob/9b0a9fd623c8448af4619acb30b0b469aa5dd6b2/src/mscorlib/src/System/String.cs#L701

Which `TryImplicitConversion` finds and then attempts to use. NLog 4.5 doesn't react to implicit conversions on System-types.

**Comment by snakefoot** [comment]
Adding the following lines to the top of `TryImplicitConversion` will fix the issue:

```c#
        private static bool TryImplicitConversion(Type resultType, string value, out object result)
        {
            try
            {
                if (Convert.GetTypeCode(resultType) != TypeCode.Object)
                {
                    result = null;
                    return false;
                }
```

**Comment by 304NotModified** [comment]
great work!

**Comment by 304NotModified** [comment]
NLog 4.5 -> #2599
NLog 4.4.14 -> #2600
