### ISSUE TITLE
NLog doesn't colorize VSCode Debug Console

### ISSUE THREAD

**Issue by LeonidasFettikus** [NLog/NLog#2623]
Hi guys, 

I am using VSCode to develop a .NetCore solution with NLog as my logging provider. I have set up everything according to the tutorial:

- Installed NuGet Package NLog.Config
- Added NLog.config file and modified console type to "ColoredConsole"
- Added NLog.config to project output with CopyToOutputDirectory set to true
- Add a static variable to my classes that gets a logger instance from LogManager
- Use logger.Warn("..."), logger.Error("...") and logger.Info("...") according to my needs

However, when I debug my app inside VSCode, the logs are written into the debug console without any colors. When I run into an unhandled exception, the debug console displays a message in a dark yellow/orange color so it should work or am I missing something here?

```
<?xml version="1.0" encoding="utf-8" ?>
<nlog 
    xmlns="http://www.nlog-project.org/schemas/NLog.xsd" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" throwConfigExceptions="true">
    <targets>
        <target name="logfile" xsi:type="File" fileName="logs.log" />
        <target name="logconsole" xsi:type="ColoredConsole" />
    </targets>
    <rules>
        <logger name="*" minlevel="Info" writeTo="logconsole" />
        <logger name="*" minlevel="Debug" writeTo="logfile" />
    </rules>
</nlog>
```

**Comment by snakefoot** [comment]
I guess if you enabled the terminal system i VsCode:

https://github.com/Microsoft/vscode/issues/243#issuecomment-311680959

And then "just" fixed up this PR for adding support for ANSI color codes in NLog (Read as creating new PR):

https://github.com/NLog/NLog/pull/1495

Then you would probably get colors in VsCode.

**Comment by snakefoot** [comment]
@LeonidasFettikus Could you try this pre-release of NLog (NLog.4.5.11.8741-PR3018.nupkg):

https://ci.appveyor.com/project/nlog/nlog/builds/20372413/artifacts

**Comment by 304NotModified** [comment]
yes please try, then we can merge it soon :)

**Comment by snakefoot** [comment]
@304NotModified This can be added to NLog 4.6 milestone with PR #3018

**Comment by 304NotModified** [comment]
🎉  thanks!

**Comment by 304NotModified** [comment]
FYI, NLog 4.6 RC is online which includes this feature (EnableAnsiOutput  option)
