### ISSUE TITLE
Support rendering structured message as json selectively

### ISSUE THREAD

**Issue by lunim** [NLog/NLog#2629]
**Type**:

- Feature request

**NLog version**: 4.5

**Platform**: .NET Core 
 
 - Why do we need it?
Currently, it seems that if you want to display a structured logging object as JSON, it must be done in all locations.  I would like to be able to render a friendly-output for the console, but have json in a log file.

For example, given the following:

```C#
public class TestObject
{
    public string A { get; set; }
    public int B { get; set; }

    public override string ToString()
    { return A; }
}

public static void Main(string[] args)
{
    var testObj = new TestObject
    {
       A = "Sample",
       B = 2
    };

    log.Info("Test: {obj}", testObj);
}
```
With the defined loggers:
```xml
<target xsi:type="File" name="logfile" layout="${message} | ${all-event-properties}" fileName="${basedir}/logs/logfile.txt" />

<target name="console" xsi:type="ColoredConsole" layout="${message}" />
```
Will display `Test: Sample` in the console, and write `Test: Sample | obj=Sample` to the file.

It would be nice to write the JSON output to the log file, the same output you get by prefixing the argument with an '@' symbol (For example: `Test: {"A":"Sample", "B":2}`), while maintaining the "pretty" output to the console.  The `all-event-properties` does not seem to output all of the arguments that the JSON renders.

**Comment by snakefoot** [comment]
Yes it should be possible to extend Format-property on ${all-event-properties} to support `@`. Which means to output all properties in Json format (Instead of special key/value-pair format)

PullRequests are welcomes.

**Comment by 304NotModified** [comment]
Why can't you use the JsonLayout?

**Comment by lunim** [comment]
@304NotModified JsonLayout also does not serialize the entire object, like the '@' symbol does.

Given the sample layout here: https://github.com/NLog/NLog/wiki/How-to-use-structured-logging using `includeAllProperties="true"`, and the same code as above, the log file contains:

`{ "time": "2018-03-27 08:40:59.4537", "level": "INFO", "message": "Test: Sample", "obj": "Sample" }`

It is not displaying the entire object.

**Comment by 304NotModified** [comment]
I think you need `MaxRecursionLimit` , see https://github.com/NLog/NLog/wiki/JsonLayout

**Comment by lunim** [comment]
@304NotModified Thanks, that helps me get at the info in a better way.  I looked around, but did not find a way to have `${all-event-properties}` serialize the result into json, like you can do with `${exception:format=@}`, is this possible?  I was looking to do this so I can have the event properties nested, instead of in-line.

Thanks!

**Comment by 304NotModified** [comment]
Could you give an example of the desired (json) output?

**Comment by snakefoot** [comment]
Would this work for you:

```xml
<layout type="JsonLayout">
          <attribute name="time" layout="${longdate}" >
          <attribute name="level" layout="${level}" >
          <attribute name="message" layout="${message}" >
          <attribute name="eventProperties" encode="false" >
            <layout type='JsonLayout' includeAllProperties="true"/>
          </attribute>
</layout>
```

**Comment by 304NotModified** [comment]
tested it, got this:

```json
{ "time": "2018-04-02 02:00:00.2349", "level": "Info", "message": "First: AlphaObject, Second: BetaObject", "eventProperties": { "alpha": {
  "A": "AlphaObject",
  "B": 2
}, "beta": {
  "A": "BetaObject",
  "B": 3
} } }

```

pretty printed:

```json
{
  "time": "2018-04-02 02:00:00.2349",
  "level": "Info",
  "message": "First: AlphaObject, Second: BetaObject",
  "eventProperties": {
    "alpha": {
      "A": "AlphaObject",
      "B": 2
    },
    "beta": {
      "A": "BetaObject",
      "B": 3
    }
  }
}
```

thanks @snakefoot !

**Comment by 304NotModified** [comment]
added here: https://github.com/NLog/NLog/wiki/JsonLayout#nested-json-with-structured-logging

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, please let us know!

**Comment by lunim** [comment]
@304NotModified Thanks, that produces what I was looking for!  I appreciate the help!
