### ISSUE TITLE
Declaration of Logger in base class leads to exception

### ISSUE THREAD

**Issue by adimkov** [NLog/NLog#263]
``` c#
abstract class BaseClass
{
    protected BaseClass()
    {
        Log = LogManager.GetLogger(GetType().FullName, GetType());
    }

    protected Logger Log {get; private set;}
}

class ExactClass : BaseClass
{
    //Some stuff.....
}
```

#### problem 1: ####
if derived class without parameterless constructor
```
NLog.NLogConfigurationException : Cannot access the constructor of type: ExactClass. Is the required permission granted?
   at NLog.Internal.FactoryHelper.CreateInstance(Type t)
   at NLog.LogFactory.GetLogger(LoggerCacheKey cacheKey)
   at NLog.LogFactory.GetLogger(String name, Type loggerType)
   at NLog.LogManager.GetLogger(String name, Type loggerType)
   ...
   ...
   ...
```
#### problem 2: ####
if derived class with  parameterless constructor
```
StackOverflowException throws.
```

**Comment by ie-zero** [comment]
Documentation https://github.com/NLog/NLog/wiki/Tutorial updated.

**Comment by 304NotModified** [comment]
Thanks @ie-zero

**Comment by 304NotModified** [comment]
I checked this case, as I was working on a related thing. And this has nothing to do a sub class.

The loggerType is the type we're returning. E.g.

```c#
public static Logger GetLogger("test", typeof(Logger2))
```

returns a `Logger2`. And therefor, it should inherited from Logger, and it's clear that it will not work in the contructor of `Logger2`.

So we have to update the wiki, but also create a better exception. Will create a new ticket for that.
