### ISSUE TITLE
NLog 4.5 does not seem to work for projects on ASP.NET Core 1.1 targeting full .NET FW 4.6.1

### ISSUE THREAD

**Issue by hiredgunhouse** [NLog/NLog#2636]
**Type**:
- Bug (possibly)

**NLog version**: 4.5

**Platform**: .Net 4.5

**Current NLog config** xml, but not relevant

In case of a BUG:

- What is the current result?
The app crashes
- What is the expected result?
The app does not crash and logs.
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
No
- Please post full exception details (message, stacktrace, inner exceptions)
When the app starts this is what is logged in "Output" window in VS:
'WebApplication1.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_32\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll'. Symbol loading disabled by Include/Exclude setting.
'WebApplication1.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'R:\nlog45issue\WebApplication1\bin\Debug\net461\WebApplication1.exe'. Symbols loaded.
'WebApplication1.exe' (CLR v4.0.30319: WebApplication1.exe): Loaded 'R:\nlog45issue\WebApplication1\bin\Debug\net461\Microsoft.AspNetCore.Hosting.dll'. Symbol loading disabled by Include/Exclude setting.
'WebApplication1.exe' (CLR v4.0.30319: WebApplication1.exe): Loaded 'R:\nlog45issue\WebApplication1\bin\Debug\net461\Microsoft.AspNetCore.Hosting.Abstractions.dll'. Symbol loading disabled by Include/Exclude setting.
'WebApplication1.exe' (CLR v4.0.30319: WebApplication1.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\netstandard\v4.0_2.0.0.0__cc7b13ffcd2ddd51\netstandard.dll'. Symbol loading disabled by Include/Exclude setting.
'WebApplication1.exe' (CLR v4.0.30319: WebApplication1.exe): Loaded 'R:\nlog45issue\WebApplication1\bin\Debug\net461\Microsoft.Extensions.DependencyInjection.Abstractions.dll'. Symbol loading disabled by Include/Exclude setting.
An unhandled exception of type 'System.TypeLoadException' occurred in Unknown Module.
Method 'ConfigureAppConfiguration' in type 'Microsoft.AspNetCore.Hosting.WebHostBuilder' from assembly 'Microsoft.AspNetCore.Hosting, Version=1.1.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' does not have an implementation.

- Are there any workarounds? not sure
- Is there a version in which it did work? NLog 5.0-beta09
- Can you help us by writing an unit test? maybe (IMHO this is more related to application dependencies and configuration)

I followed the instructions from the WIKI (https://github.com/NLog/NLog.Web/wiki/Getting-started-with-ASP.NET-Core-(csproj---vs2017))
As the title specifies, my project is ASP.NET Core 1.1 targetting full .NET FW (v 4.6.1).
Here is a repo with the problem reproduced using instructions from the WIKI:  https://github.com/hiredgunhouse/nlog45issue

**Comment by 304NotModified** [comment]
I think the problem is that `NLog.Web.AspNetCore ` is build on ASP.NET core 2 and not 1 for .NET 4.6.1 

see nuget:

![image](https://user-images.githubusercontent.com/5808377/38089103-922ec346-335e-11e8-9558-96490fbea3b8.png)

unfortunately we can't build 1 package with ASP.NET core 1  + ASP.NET core 2 support for the same platform.

**Comment by 304NotModified** [comment]
> Platform: .Net 4.5

Your config says 4.6

https://github.com/hiredgunhouse/nlog45issue/blob/master/WebApplication1/WebApplication1.csproj#L4

**Comment by hiredgunhouse** [comment]
I suspect that is exactly the problem that you use abstractions from .NET Core 2.0 basically meaning you do not support earlier versions but I'm not .NET Core expert.
If this is true, does that mean NLog is not an option for .NET Core 1.x projects? 
That's not what MS was promising to us with .NET Core :/
Regarding the reported platform, you bug template did not have 4.6 that's why I chose 4.5.

**Comment by 304NotModified** [comment]
> I suspect that is exactly the problem that you use abstractions from .NET Core 2.0 basically meaning you do not support earlier versions but I'm not .NET Core expert.

We do support ASP.NET Core 1, but only when using .NET Framework 4.5 or .NETStandard 1.5+

When you're using .NET Framework 4.6+ or .NETStandard 2+, we currently only support  ASP.NET Core 2

**Comment by hiredgunhouse** [comment]
Ok, thanks for clarification. I'm closing the issue.
PS. Maybe it would be good to update the WIKI page I linked to.

**Comment by 304NotModified** [comment]
I've updated the wiki pages with a warning.

See 

- https://github.com/NLog/NLog.Web/wiki
- https://github.com/NLog/NLog.Web/wiki/Getting-started-with-ASP.NET-Core-(csproj---vs2017)
- and https://github.com/NLog/NLog.Web/wiki/Getting-started-with-ASP.NET-Core-2

But it's not that strange requirement, if you check:


https://www.nuget.org/packages/Microsoft.Extensions.Logging/

- Microsoft.Extensions.Logging 1.x supports only .NETStandard 1.1
- Microsoft.Extensions.Logging 2.x supports only .NETStandard 2

and if you check:

https://docs.microsoft.com/en-us/dotnet/standard/net-standard

![image](https://user-images.githubusercontent.com/5808377/38100248-27102acc-337d-11e8-87fc-885bd4038296.png)

for .NET standard 2.0 you need .NET Core 2 or .NET standard 4.6.1


.NET 4.6 and  Microsoft.Extensions.Logging 1.x  is supported, but only with an older version of NLog.Web.AspNetCore
