### ISSUE TITLE
The internalLogFile does not resolve ${nlogdir}

### ISSUE THREAD

**Issue by Dschingis** [NLog/NLog#2646]
**Type**
- Bug

**NLog version**: 4.5.1
**Platform**: .Net 4.6.2
**Current NLog config**

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      throwExceptions="false"
      internalLogFile="${nlogdir}\..\Log\Test.exe.NLog.log" internalLogLevel="Debug" >

  <targets>
      <target xsi:type="File"
            fileName="${nlogdir}\..\Log\Test.exe.log"
            keepFileOpen="false"
			name="default"
      />
  </targets>
  <rules>
    <logger name="*" writeTo="default" minlevel="Debug" />
  </rules>
</nlog>
```

**Program**
```C#
LogManager.Configuration = new XmlLoggingConfiguration(@"..\..\nlogconfig.config");
var logger = NLog.LogManager.GetCurrentClassLogger();
logger.Error("Hello World");
```

In case of a BUG:

- What is the current result?
The internal log file writes to {Project}\bin\Debug\Log
The target file logs to {Project}\bin\Log

- What is the expected result?
The internal log file should write to {Project}\bin\Log

**Comment by 304NotModified** [comment]
The internalLogFile is just a string and not layout renderers are allowed in them.

**Comment by 304NotModified** [comment]
duplicate of https://github.com/NLog/NLog/issues/581

**Comment by Dschingis** [comment]
It seems I didn't google good enough. Thanks for the info.
