### ISSUE TITLE
Using ${callsite} returns invalid classname "Microsoft.Extensions.Logging.LoggerExtensions" when using HostBuilder for .NET Core 2.1 Application

### ISSUE THREAD

**Issue by agentschmitt** [NLog/NLog#2647]
I am using Generic HostBuilder from **Microsoft.Extensions.Hosting** (2.1.0 preview1-final) to startup my .NET Core Application. But then i get invalid callsite classnames in Nlog.

Blog Post: https://jmezach.github.io/2017/10/29/having-fun-with-the-.net-core-generic-host/
Sample: https://github.com/stevejgordon/GenericHostExample/tree/master/GenericHostExample

I know there is some documentation how to setup Nlog for .NET Core 2 Console Application.
https://github.com/NLog/NLog.Extensions.Logging/wiki/Getting-started-with-.NET-Core-2---Console-application
But with loggerFactory.AddNLog() it does just log nothing. So i tryed loggingBuilder.AddNlog() which worked.

 **Type** (choose one): Bug

- What is the current result?
2018-04-06 13:35:01.108 [1] INFO Microsoft.Extensions.Logging.LoggerExtensions.LogInformation - Task started

- What is the expected result?
2018-04-06 13:35:01.108 [1] INFO My.ConsoleApp.MyTask - Task started

- Are there any work arrounds? yes:

```c#
LogManager.AddHiddenAssembly(Assembly.Load(new AssemblyName("Microsoft.Extensions.Logging.Abstractions")));
```

I Have added this code to my application and then logging of classname works again, see code example below.

**Related Issue**:
It seems that .NET Core 2.1 Applications with IHostingBuilder initialization have the same problem as AspNet.Core.Web Projects had before. https://github.com/NLog/NLog.Web/issues/206

I looked a bit in the sourcecode: and it seems that ConfigureHiddenAssemblies is not done for .NET Core 2.0. https://github.com/NLog/NLog.Extensions.Logging/blob/master/src/NLog.Extensions.Logging/Extensions/ConfigureExtensions.cs

**NLog version**: (4.5.1)
**NLog Extensions.Logging**: (1.0.0)
**Microsoft.Extensions.Hosting** (2.1.0 preview1-final)

**Platform**: . .NET Core 2.1

**Current NLog config** (xml or C#, if relevant)

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      internalLogLevel="Warn"
      internalLogFile="..\..\logs\internal-NLog.txt">

  <variable name="formattedMessage" value="${message}${onexception:${newline}${exception:format=ToString}}" />
  <variable name="defaultLayout" value="${date:format=yyyy-MM-dd HH\:mm\:ss.fff} [${threadid}] ${level:uppercase=true} ${callsite} - ${formattedMessage}" />
  <variable name="logFolder" value="..\..\..\..\..\logs" />

  <targets async="true">
    <target xsi:type="File" name="rootFileTarget" fileName="${logFolder}\app-${shortdate}.log" layout="${defaultLayout}" keepFileOpen="true" />
  </targets>

  <rules>
    <logger name="*" minlevel="Debug" writeTo="rootFileTarget" />
  </rules>
</nlog>
```

```c#
using System.IO;
using System.Reflection;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using NLog;
using NLog.Extensions.Logging;

namespace My.ConsoleApp
{
    public class Program
    {
        static void Main(string[] args)
        {
            var logger = LogManager.LoadConfiguration("NLog.config").GetCurrentClassLogger();

            try
            {
                logger.Info("application started");
                BuildHost(args).RunConsoleAsync();
            }
            catch (Exception e)
            {
                logger.Fatal(e, "application crashed");
                throw;
            }
            finally
            {
                logger.Info("application exited");
                LogManager.Shutdown();
            }
        }

        private static IHostBuilder BuildHost(string[] args)
        {
            var hostBuilder = new HostBuilder()
                .UseDefaultEnviroment("Local")
                .ConfigureAppConfiguration((context, config) => ConfigureAppConfiguration(context, config, args))
                .ConfigureLogging(ConfigureLogging)
                .ConfigureServices(ConfigureServices);

            return hostBuilder;
        }

        private static void ConfigureServices(HostBuilderContext hostBuilderContext, IServiceCollection serviceCollection)
        {
            // services
            serviceCollection.AddSingleton<IHostedService, MyTask>();
        }

        private static void ConfigureLogging(HostBuilderContext context, ILoggingBuilder logging)
        {
            LogManager.AddHiddenAssembly(Assembly.Load(new AssemblyName("Microsoft.Extensions.Logging.Abstractions")));

            logging
                .AddConfiguration(context.Configuration.GetSection("Logging"))
                .AddNLog()
                .AddConsole();
        }

        private static void ConfigureAppConfiguration(HostBuilderContext context, IConfigurationBuilder config, string[] args)
        {
            config
                .SetBasePath(Directory.GetCurrentDirectory())
                .AddJsonFile("appsettings.json")
                .AddJsonFile($"appsettings.{context.HostingEnvironment.EnvironmentName}.json", optional: true)
                .AddCommandLine(args)
                .AddEnvironmentVariables();
        }
    }
}
```

**Comment by snakefoot** [comment]
Try and replace this line:

`var logger = LogManager.LoadConfiguration("NLog.config").GetCurrentClassLogger();`

With this line:

`var logger = NLog.Web.NLogBuilder.ConfigureNLog("nlog.config").GetCurrentClassLogger();`

**Comment by agentschmitt** [comment]
Should i use NLog.Web.NLogBuilder for .NET Core Console Applications too?
I thought this is only for ASP.NET Core Applications.

**Comment by snakefoot** [comment]
> Should i use NLog.Web.NLogBuilder for .NET Core 2 Console application too?

No you should not. Sorry about this. Was just confused by "My.**Web**.Api"

**Comment by 304NotModified** [comment]
Thanks for reporting. Fixed in https://github.com/NLog/NLog.Extensions.Logging/pull/210 / NLog.Extensions.Logging 1.0.1 - thanks @snakefoot
