### ISSUE TITLE
Improve documentation on MDLC, MDC, NDLC and NDC

### ISSUE THREAD

**Issue by furier** [NLog/NLog#2652]
Could the documentation possibly be included to explain what is the purpose of NDLC and NDC and maybe how it differs from MDLC and MDC? 

With NLog 4.5 structured logging MDLC seems to add metadata properties that are part of the structured data being logged but not part of the message rendered, correct? 

What does NDLC do then? append the pushed value to the rendered message or prepended, does it also support structured data, etc...?

**Comment by furier** [comment]
And what is the difference for mapped and nested? Like I described in my
question?
søn. 8. apr. 2018 kl. 01:18 skrev Rolf Kristensen <notifications@github.com

**Comment by snakefoot** [comment]
Mapped works like a dictionary where each scope can add new values

Nested works like a stack allowing one to rename the scope on each stack push. Used for BeginScope in Microsoft Extension Logging



Sent from my Samsung device


-------- Original message --------

**Comment by furier** [comment]
So nested works like described here? https://nblumhardt.com/2016/11/ilogger-beginscope/

**Comment by snakefoot** [comment]
Serilog have transformed BeginScope into something that works like a combination of MDLC and NDLC



Sent from my Samsung device


-------- Original message --------

**Comment by snakefoot** [comment]
Maybe this wiki-page covers your questions:

https://github.com/NLog/NLog/wiki/Gdc-layout-renderer

**Comment by 304NotModified** [comment]
I've added https://github.com/NLog/NLog/wiki/Contexts

Please your input and feel free to improve/edit the page

**Comment by snakefoot** [comment]
@304NotModified Have added more details to the page:

https://github.com/NLog/NLog/wiki/LogEvent-Context-Information

**Comment by 304NotModified** [comment]
Hi @snakefoot 

I see you did a complete rewrite and removed a lot I have written. Do you think it was unclear? e.g. this is now dropped

> 
> ## Advise
> 
> - When you need the context for all threads, use the [GDC](Gdc-Layout-Renderer). 
> - When you need the context for one thread, use the [MDC](MDC-Layout-Renderer). 
> - When you work with async, use the [MDLC](MDLC-Layout-Renderer).
> - When tracking scoped work, use [NDC](NDC-Layout-Renderer) or [NDLC](NDLC-Layout-Renderer)
> - If the context is different for every message, use [Structured logging](How-to-use-structured-logging) or the [Log event properties](EventProperties-Layout-Renderer)

IMO that's the question I get from others and was unclear to me when I started with Nlog.

Also do you think we have to ignore the MDC and NDC in favor of the MDLC and NDLC?

**Comment by snakefoot** [comment]
> IMO that's the question I get from others and was unclear to me when I started with Nlog.

I have now made a headline with example code for each of your advice lines. You are welcome to add more details for each headlines. Or make an index of the headlines.

>Also do you think we have to ignore the MDC and NDC in favor of the MDLC and NDLC?

Yes. Too confusing.

**Comment by 304NotModified** [comment]
> Yes. Too confusing

OK, but maybe we should add something about it, as currently users are using the MDC and NDC

**Comment by snakefoot** [comment]
Already done since it says `Replaces ${mdc}` and `Replaces ${ndc}`.

And have also updated:

https://github.com/NLog/NLog/wiki/NDC-Layout-Renderer
https://github.com/NLog/NLog/wiki/mdc-Layout-Renderer

**Comment by 304NotModified** [comment]
> And have also updated:
> 
> https://github.com/NLog/NLog/wiki/NDC-Layout-Renderer
> https://github.com/NLog/NLog/wiki/mdc-Layout-Renderer

👍

**Comment by 304NotModified** [comment]
@snakefoot I'm busy combining both documents,

but I'm search for an example: when should we use `NestedDiagnosticsLogicalContext.Push` over `MappedDiagnosticsLogicalContext.SetScoped`?

**Comment by snakefoot** [comment]
Ndlc should be used when wanting to output the entire scope-stack.


Sent from my Sony Xperia


---- Julian Verdurmen wrote ----


@snakefoot<https://github.com/snakefoot> I'm busy combining both documents,

but I'm search for an example: when should we use NestedDiagnosticsLogicalContext.Push over MappedDiagnosticsLogicalContext.SetScoped?

**Comment by 304NotModified** [comment]
So we need an example with 2 pushes I guess

**Comment by snakefoot** [comment]
Have updated these wiki-packages to better explain when they are useful:

- https://github.com/NLog/NLog/wiki/NDLC-Layout-Renderer 
- https://github.com/NLog/NLog/wiki/MDLC-Layout-Renderer

**Comment by 304NotModified** [comment]
Thanks!
