### ISSUE TITLE
internal log file and target file using different root path?

### ISSUE THREAD

**Issue by meanshe** [NLog/NLog#2656]
When I use nlog in asp.net core 2.0 (Debug Mode)， there is a bug seams 'internalLogFile' and target file using different root path. 

```xml
<nlog ... internalLogFile="App_Data\Logs\nlogInternal.log">
...
<target name="fileTarget" fileName="App_Data\Logs\nlog-all-${shortdate}.log" ... />
 ```

internal file:  [project_dir]\App_Data\Logs\nlogInternal.log
target file: [project_dir]\bin\Debug\netcoreapp2.0\App_Data\Logs\nlog-all-2018-03.log

**Comment by 304NotModified** [comment]
Hi,

Thanks for reporting this issue. This is indeed an issue, see https://github.com/NLog/NLog.Web/issues/201

**Comment by 304NotModified** [comment]
duplicate in favor of NLog/NLog.Web#201
