### ISSUE TITLE
Using NLog in SQL CLR project

### ISSUE THREAD

**Issue by christifi** [NLog/NLog#2657]
Hi! 
I have a question.

Using NLog  4.3.8 on Platform:  .Net 4.5 in library works fine.
Now I would register the assembly to SQL CLR and run into trouble cause the Nlog refers to System.ServiceModel.dll and this to microsoft.visualbasic.activities.compiler wich is not pure .NET assembly.

Getting this error registering the DLL in SQL Server 2012:
_Msg 6544, Level 16, State 1, Line 1
CREATE ASSEMBLY for assembly 'System.ServiceModel' failed because assembly 'microsoft.visualbasic.activities.compiler' is malformed or not a pure .NET assembly. 
Unverifiable PE Header/native stub.
Msg 10301, Level 16, State 1, Line 3
Assembly 'NLog' references assembly 'system.servicemodel, version=4.0.0.0, culture=neutral, publickeytoken=b77a5c561934e089.', which is not present in the current database. SQL Server attempted to locate and automatically load the referenced assembly from the same location where referring assembly came from, but that operation has failed (reason: 2(The system cannot find the file specified.)). Please load the referenced assembly into the current database and retry your request._

Is there a solution using Nlog in SQL CLR Projects?

Thanks for help

**Comment by snakefoot** [comment]
@christifi Think you are waiting for this issue to be resolved: #2582

While waiting then you could consider making a local build where you remove the parameter WCF_SUPPORTED from the csproj-file. I have created a PR that show how to do this: #2658

If you are lucky, then you can just use the nuget-package found here (Generated from that PR):

https://ci.appveyor.com/project/nlog/nlog/build/4.5.0-7469/artifacts

**Comment by christifi** [comment]
Thank you very much @304NotModified and @snakefoot this will help a lot.
