### ISSUE TITLE
Feature Request: Log4JXMLEvent Layout Render, include ALL User StackTrace on exception

### ISSUE THREAD

**Issue by delfuria** [NLog/NLog#266]
Hi,
i'm using this render for my log.

 <target name="xmlfile" xsi:type="File" fileName="${basedir}/_logs/LogEmiter.Nlog.xlog" keepFileOpen="true"
              archiveFileName="${basedir}/_logs/LogEmiter.Nlog.{#####}.xlog" archiveAboveSize="1000000"
              layout="${log4jxmlevent:includeSourceInfo=true:includeCallSite=true:includeMDC=true:appInfo=LogEmiter:includeNdc=true:includeNLogData=true}" />

But i would like to include all the stack trace when an exception is raised.

Actually the exception show only the last method that raise the exception in this way:

```xml
<log4j:event logger="th" level="ERROR" timestamp="1380657106586" thread="10">
  <log4j:messageError>doing something...</log4j:message>
  <log4j:NDC /> 
  <log4j:throwable>
    <![CDATA[System.ApplicationException: Errore dell'applicazione.
   in TestConsoleDelfo.Program.SubTestNlog(Logger log) in d:\TestConsoleDelfo\Program.cs:riga 814]]>
     </log4j:throwable>
  <log4j:locationInfo class="TestConsoleDelfo.Program" method="Void SubTestNlog(NLog.Logger)" file="d:\TestConsoleDelfo\Program.cs" line="818" />
  <nlog:eventSequenceNumber>
     307
   >/nlog:eventSequenceNumber>
   <nlog:locationInfo assembly="TestConsoleDelfo, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" />
   <nlog:properties />
   <log4j:properties>
     <log4j:data name="log4japp" value="LogEmiter" /> 
     <log4j:data name="log4jmachinename" value="DELFO" /> 
   </log4j:properties>
</log4j:event>
```

but the entire stack trace is longer than the SubTestNlog method as there's a main() method that call a TestNLog() method and at last the SubTestNlog method.

I had take a look at the source code and i think that the "problem" is on this line of code that belong to src\NLog\LayoutRenderers\Log4JXmlEventLayoutRenderer.cs

```c#
  System.Diagnostics.StackFrame frame = logEvent.UserStackFrame;
  if (frame != null)
  {
     //...
  }
```

In this if statement is used the variable frame that is initialized with the property UserStackFrame 
This property contains only the LAST stackframe the is the method who raised the exception.

I think that will be great to set a parameter for write all Users's StackTrace frames and not just the last User's StackFrame

What do you think ???
Thanks in advance
Stefano

**Comment by snakefoot** [comment]
Already now Log4JXmlEventLayoutRenderer the entire Exception.ToString():

https://github.com/NLog/NLog/blob/01018e0f1cd7884b6185d2aa4b3b6c6653dd185d/src/NLog/LayoutRenderers/Log4JXmlEventLayoutRenderer.cs#L292-L305

Not sure what is missing?
