### ISSUE TITLE
LayoutRenderer cannot be found: 'qpc'

### ISSUE THREAD

**Issue by GibbOne** [NLog/NLog#2667]
**Type**: Bug

**NLog version**: 4.5.3

**Platform**: Xamarin Android / .NET Core 

**Current NLog config**

```c#
LoggingConfiguration cfg = new LoggingConfiguration();
target = new FileTarget();
LogFolder = Path.GetTempPath();
target.ArchiveEvery = FileArchivePeriod.Day;
target.AutoFlush = true;
target.KeepFileOpen = true;
target.Header = "Proc: ${processname} Assy: ${assembly-version} Windows ID: ${windows-identity} Time: ${longdate:universalTime=true} UTC ${newline}";
target.Header += "************|********|*******|*************************************************************************************************${newline}";
target.Header += "    Time    |  Delta | Level |     Logger / Method / Message${newline}";
target.Header += "************|********|*******|*************************************************************************************************${newline}";
target.Layout = "${date:format=HH\\:mm\\:ss.fff} | ${qpc:difference=true:alignDecimalPoint=true} | ${pad:padding=5:inner=${level:uppercase=true}} | ${logger} | ${message}";
target.Footer = "${newline}*******************************************************************************************************************************${newline}";
target.ArchiveAboveSize = 10485760;
target.MaxArchiveFiles = 0;
cfg.AddTarget("file", target);
LogManager.Configuration = cfg;
```

- What is the current result?
I got an exception `System.ArgumentException: LayoutRenderer cannot be found: 'qpc'`
- What is the expected result?
From [wiki page](https://github.com/NLog/NLog/wiki/platform-support) QueryPerformanceCounter layout render should be supported also on Mono.

**Comment by 304NotModified** [comment]
> From wiki page QueryPerformanceCounter layout render should be supported also on Mono.

yes, but not for Xamarin Android ;)

I don't think this is possible in Xamari.

**Comment by GibbOne** [comment]
Yes performance counters are windows stuff. 

In fact my need is just a simple delta of time since previous log item as accurate as possible.

**Comment by 304NotModified** [comment]
I don't think NLog could solve that. Maybe you need a custom layout renderer?

**Comment by GibbOne** [comment]
Ok. Thx.

**Comment by springy76** [comment]
I just converted an app to netcore3 and noticed that `${qpc:precision=3:padding=7}` only renders many spaces. Why not just use a StopWatch which definitely is in netstandard and might use low-frequency depending on the platform instead of Windows-API stuff?

**Comment by snakefoot** [comment]
@springy76 Please create a new issue with your idea. If implementing something that depends on `StopWatch`, then it would probably be a good idea to call the layout-renderer something like `${stopwatch}`. You are very welcome to also create a pull-request that resolves your newly created issue.
