### ISSUE TITLE
Condition base email

### ISSUE THREAD

**Issue by parthakbari** [NLog/NLog#2668]
Hi,

I want to send email if there is exception. for that, I have write below setting in web.config file.

On CS side, I am creating event "EmailBody" and fill it when there is execution in CS code otherwise it's empty.

**Here, I am trying if "EmailBody" is empty then no need to send email so, used condition tag. mentiond above.**  

**How to check "${event-context:item=EmailBody}" is null?**

>  Web.Config

```xml
<target xsi:type="Mail" 
  name="Email" 
  html="true"
  addNewLines="false" 
  replaceNewlineWithBrTagInHtml="false" 
  subject="Error Log" 
  to="parth.akbari@xxxxx.com" 
  useSystemNetMailSettings="true"
  body="${event-context:item=EmailBody}" />
```

Below rules,
```xml
<rules>
        <logger name="*" minlevel="trace" writeTo="oracle" />
        <logger name="*" minlevel="trace" writeTo="file" />
        <logger name="*" minlevel="Debug" writeTo="Email">
        <filters>
               <when condition="length('${event-context:item=EmailBody}) > 0" action="Ignore" />
        </filters>
      </logger>
</rules>
```

> CS CODE

```c#
public static void ErrorLog(NLogData nLogData)
{
      LogEventInfo theEvent = new LogEventInfo(LogLevel.Error, NLogManager._logger.Name, nLogData.Message);
      SetLogEventInfo(theEvent, nLogData);
      _logger.Log(theEvent);
}
```

function "SetLogEventInfo" contain below line.

`theEvent.Properties["EmailBody"] = string.IsNullOrEmpty(nLogData.EmailBody) ? string.Empty : nLogData.EmailBody;`

Suggection most welcome, any other alternative way to send email via nlog with current setup.

Let me know if you require more information.

**Comment by 304NotModified** [comment]
shouldn't it be (`==0`)? 

```xml
<when condition="length('${event-context:item=EmailBody}) == 0" action="Ignore" />
```

?

Ps you could create multiline code blocks with a triple backtrick. I've edited (partly) your post

**Comment by parthakbari** [comment]
@304NotModified Thanks for quick replay.. let me check your suggection.

**Comment by parthakbari** [comment]
Sorry its's not working. I have attached my code. might be help us.

**Configration**
![Configuration](https://user-images.githubusercontent.com/3718529/38987687-4aec4580-43ee-11e8-9dd0-4abe20f9d0d7.JPG)

**EmailBody with html string** 
![emailbody](https://user-images.githubusercontent.com/3718529/38987710-619442b0-43ee-11e8-8e69-a1bb0391f154.JPG)

**No EmailBody**
![noemailbody](https://user-images.githubusercontent.com/3718529/38987727-6efe1020-43ee-11e8-86c6-9b202b4e5068.JPG)

**Comment by 304NotModified** [comment]
at least there is something wrong with the quotes (also in my answer)

update:

     <when condition="length(${event-context:item=EmailBody}) == 0" action="Ignore" />


also please check the internal log on trace level: https://github.com/NLog/NLog/wiki/Internal-logging

**Comment by 304NotModified** [comment]
see docs here https://github.com/NLog/NLog/wiki/Filtering-log-messages

I think it should be this: (quotes are required)

   <when condition="length('${event-context:item=EmailBody}') == 0" action="Ignore" />

**Comment by parthakbari** [comment]
@304NotModified Thanks it's working

**Comment by 304NotModified** [comment]
OK glad it has been resolved!
