### ISSUE TITLE
Logging line numbers is slow on .NET Core

### ISSUE THREAD

**Issue by martinmine** [NLog/NLog#2669]
**Type**: Bug
**NLog version**: 4.5.3 (latest)
**Platform**: .NET Core 

Logging line numbers in .NET Core takes an awful lot of time. This is because generating the call stacks takes a whole lot of time. The following program demonstrates this:

```CSharp
static void Main()
{
    var config = new NLog.Config.LoggingConfiguration();

    var logfile = new NLog.Targets.FileTarget
    { 
        FileName = "file.log",
        Name = "logfile",
        Layout = "${callsite-linenumber}",
        KeepFileOpen = true,
        ConcurrentWrites = false
    };
            
    config.LoggingRules.Add(new NLog.Config.LoggingRule("*", NLog.LogLevel.Trace, logfile));
            

    NLog.LogManager.Configuration = config;

    var logger = NLog.LogManager.GetCurrentClassLogger();
    var start = System.DateTime.Now;

    for (var i = 0; i < 5000; i++)
    {
        logger.Trace("Hello World");
    }

    var timeSpent = System.DateTime.Now - start;
    System.Console.WriteLine($"Spent time: {timeSpent.TotalMilliseconds} ms");
    System.Console.ReadKey();
}
```

Targeting .NET Core the program outputs: **5515.6167 ms**
On .NET 4.7.1 you get: 282.2698 ms

This is an issue in .NET Core and not in NLog. I am creating this issue for the record in case others are experiencing the same issue. I have filed a bug to Microsoft here: https://github.com/dotnet/coreclr/issues/17701

**Comment by snakefoot** [comment]
This will solve the issue: #2527

**Comment by 304NotModified** [comment]
@snakefoot any idea if we could fix this without breaking changes?

**Comment by 304NotModified** [comment]
See also https://github.com/Microsoft/dotnet/issues/529

**Comment by martinmine** [comment]
I'm gonna go ahead and close this as this is being fixed in .NET Core 2.1 RTM, for more information, see https://github.com/dotnet/coreclr/issues/17701
