### ISSUE TITLE
Need access to ID when inserting log to db

### ISSUE THREAD

**Issue by blubinsky** [NLog/NLog#2671]
No way of easily retrieving the id after inserting log to db.  It looks like I'd be able to hack something through by overriding DatabaseTarget, but I can't see a way to make it thread safe when accessed by the client component.

Given that the logging is abstracted and may be writing to console, file, db, etc it's understandable that the id isn't returned. That could easily be addressed by returning , for instance, a LogResult that could contain a file name, database id, etc.

As it stands, despite all the great features, we won't be able to use NLog. Our preference is generally to expose minimal error information to our endusers and present them simple messages containing a log id which can then be used by our support team if needed.

**Comment by snakefoot** [comment]
So why not generate a simple guid (Not full 128 bit), that you insert into the LogEventInfo.Properties. This guid can be displayed to the user and be written to the database as a string-parameter.

**Comment by blubinsky** [comment]
Thanks for the response, much appreciated. Something like the below works along the lines you suggested. But two things:

1. I'd prefer to be able to use the .Error method rather than constructing the LogEventInfo object, but I suppose I could write wrapper classes to simplify things for our devs. 
2. More importantly, I'd much rather display a simple ID rather than a guid to our users. They're bound to get things wrong when they report a guid to support.

Is there any way the DatabaseTarget class could be overridden to do this - without doing an extra database call to retrieve the id?

public class QuantumDatabaseTarget : DatabaseTarget
    {
        protected override void Write(LogEventInfo logEvent)
        {
            logEvent.Properties.Add("LogGuid", Guid.NewGuid());
            base.Write(logEvent);
        }
    }

... calling code
            catch (Exception error)
            {
                //logger.Error(error);
                var logInfo = new LogEventInfo() { Level = LogLevel.Error, Exception = error };
                logger.Log(logInfo);
                var logGuid = (Guid)logInfo.Properties["LogGuid"];                
            }

**Comment by snakefoot** [comment]
Think it would be a good idea to make it possible to override the execute command in databasetarget. Then a custom target can change the call to ExecuteScalar and use the return code.

But depending on the target being synchronous (not using async) and returning ID through LogEvent Properties sounds like a nice hack that should only be in your code. Must admit I cannot see the difference from creating the Guid before logging.

Creating the Guid upfront before logging will allow you to use context (Like UserId) to make Guid that includes CRC check. So one can validate the provided Guid actually comes from that specific UserId

Sent from my Samsung device


-------- Original message --------

**Comment by snakefoot** [comment]
Looks like a good change for the databasetarget. You are welcome to create a pull-request.

Regarding needing to use the database to make a simple Guid. Then I'm sure a good programmer can also make a simple Guid in code without needing to use Guid.NewGuid



Sent from my Samsung device


-------- Original message --------

**Comment by blubinsky** [comment]
Ok, thank you. I don't think I have permissions to create a branch though, or is there an existing one I should use?

**Comment by snakefoot** [comment]
You just make a fork and then make a pull-request to this project


Sent from my Samsung device


-------- Original message --------

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, please let us know!

**Comment by carlos0202** [comment]
> So why not generate a simple guid (Not full 128 bit), that you insert into the LogEventInfo.Properties before logging. This guid can be displayed to the user and be written to the database as a string-parameter.

Is there any example of this that we can check? 
Thanks in advance!

**Comment by snakefoot** [comment]
@carlos0202 You can see how to inject properties when logging:

https://github.com/NLog/NLog/wiki/EventProperties-Layout-Renderer

And just include the named-property in the database-parameter-layout:

https://github.com/NLog/NLog/wiki/Database-target
