### ISSUE TITLE
Use Nlog with Xamarin.IOS

### ISSUE THREAD

**Issue by ForkBug** [NLog/NLog#2674]
There is document about Xamarin.Android, https://github.com/NLog/NLog/wiki/Configuration-file#xamarin-assets

How about Xamarin.IOS? Where NLog will load NLog.config from?

**Comment by 304NotModified** [comment]
if you can't configure a name (i'm not a Xamarin iOs Expert), you should use a programmatic configuration (e.g. in c#)

**Comment by ForkBug** [comment]
Where NLog will load NLog.config from, the app bundle or Environment.SpecialFolder.Personal?

**Comment by snakefoot** [comment]
@ForkBug Maybe just perform explicit loading of the `nlog.config`, instead of relying on the automatic loading. Then you don't need to guess.

**Comment by 304NotModified** [comment]
> Where NLog will load NLog.config from, the app bundle or Environment.SpecialFolder.Personal?

I think only the "current dir" 

Anyway, you could check the paths NLog will try with

```xml
XmlLogging.ConfigurationGetCandidateConfigFilePaths().ToList()
```

Maybe that make things more clear.

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, please let us know!
