### ISSUE TITLE
Please add support for SSL encryption when using Network target.

### ISSUE THREAD

**Issue by schuettecarsten** [NLog/NLog#2677]
Please add support for SSL encryption when using Network target. This can be useful when sending log messages to external systems like logstash.

**Comment by snakefoot** [comment]
If you are lucky, then there will be a BETA-nuget-package you can do some testing with (if the build is good):

https://ci.appveyor.com/project/nlog/nlog/build/4.5.0-7573/artifacts

**Comment by 304NotModified** [comment]
@schuettecarsten any time to test the package? Thanks in advance!

**Comment by 304NotModified** [comment]
will move this after the next release, as we need a confirmation.

**Comment by schuettecarsten** [comment]
As I am not in the office at the moment, I will not be able to test this before May, 14th. But I will do and let you know asap.

**Comment by 304NotModified** [comment]
OK thanks!

**Comment by snakefoot** [comment]
@schuettecarsten Had some time to do some testing of SSL in the NetworkTarget using the pre-release nuget-package from the build-link?

**Comment by snakefoot** [comment]
@schuettecarsten Polite ping. Had time to validate anything?

**Comment by schuettecarsten** [comment]
Hi, I just downloaded the package and changed my config file from tcp://address to ssl://address. The connection is established and some bytes are sent, but then the connection is dropped. How does NLog handle self-signed certificates?

**Comment by snakefoot** [comment]
@schuettecarsten No support right now (since not mentioned), but I guess something logic can be added to `SslStream` using `RemoteCertificateValidationCallback`.

**Comment by 304NotModified** [comment]
> Could probably add an IgnoreSslErrors-property to the NetworkTarget (Default false)

PS: I like the name `GiveUpSecurityAndAcceptAnyTlsHostCertificate` (from [Winscp.net](https://winscp.net/eng/docs/library_sessionoptions))

**Comment by snakefoot** [comment]
Very long name for something where one just ignores ssl errors on SSL handshake:

https://jenkins.io/doc/pipeline/steps/http_request/ (IgnoreSslErrors)
https://msdn.microsoft.com/en-us/library/microsoft.hadoop.client.clientbase.ignoresslerrors.aspx (IgnoreSslErrors)
https://octopus.com/docs/api-and-integration/octo.exe-command-line/pushing-packages (IgnoreSslErrors)
https://seleniumhq.github.io/selenium/docs/api/dotnet/html/P_OpenQA_Selenium_PhantomJS_PhantomJSDriverService_IgnoreSslErrors.htm (IgnoreSslErrors)

**Comment by snakefoot** [comment]
@schuettecarsten Have created a new pre-release, with support for `IgnoreSslErrors`:

https://ci.appveyor.com/project/nlog/nlog/build/4.5.0-7917/artifacts

Also changed how to enable SSL (no longer part of the address), so now one have to explicit specify SslProtocols (Default=None):

`<target name="target1" type="network" address="tcp://127.0.0.1" sslProtocols="Default" ignoreSslErrors="true" />`

**Comment by snakefoot** [comment]
@schuettecarsten Had time to download the updated prerelease-package, and test if `ignoreSslErrors` helps ?

**Comment by snakefoot** [comment]
@schuettecarsten Another summer-holiday poke

**Comment by 304NotModified** [comment]
> Very long name for something where one just ignores ssl errors on SSL handshake:

about this. It's not just a warning. Man can argue that ssl with and error is useless. It's not safe. fake-security. 

I'm really against allowing SSL with errors. 

> How does NLog handle self-signed certificates?

Just install it on your system. That's the only safe solution

**Comment by 304NotModified** [comment]
fixed by #2678

**Comment by 304NotModified** [comment]
FYI, NLog 4.6 RC is online which includes this feature
