### ISSUE TITLE
NLog.config not copied to output directory

### ISSUE THREAD

**Issue by c0shea** [NLog/NLog#2686]
**Type** (choose one):

- Bug

**NLog version**: 4.5.3

**Platform**: .NET 4.5.1 (VS 2015)

**Current NLog config:**

```xml
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="false"
      internalLogLevel="Off" internalLogFile="c:\temp\nlog-internal.log">

  <targets async="true">
    <target name="file" xsi:type="File"
            layout="${longdate} ${level:uppercase=true:padding=-5} ${machine-name} ${callsite}  ${message}  ${exception:format=tostring}"
            fileName="${basedir}/Logs/today.log"
            archiveFileName="${basedir}/Logs/previous-{#}.log"
            archiveEvery="Day"
            archiveNumbering="Rolling"
            maxArchiveFiles="30"
            concurrentWrites="true"
            keepFileOpen="false"
            encoding="iso-8859-2" />
    <target name="console" xsi:type="ColoredConsole" layout="${longdate} ${level:uppercase=true:padding=-5} ${message}" />
  </targets>
  <rules>
    <logger name="*" minlevel="Trace" writeTo="file" />
    <logger name="*" minlevel="Info" writeTo="console" />
  </rules>
</nlog>

```

In case of a BUG:

- What is the current result?
I created a brand new .NET 4.5.1. console project and installed the NLog.Config package, which pulled in the NLog and NLog.Schema dependencies. The `NLog.Config` Copy to Output Directory is set to `Do not copy`. Since it's not defaulted to copy on build, NLog never logs anything because the config file isn't there at runtime.

- What is the expected result?
I would expect that Copy to Output Directory is set to `Copy always` like it used to be.

- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
This is a package install issue.

- Are there any workarounds? yes/no
Manually set the property to copy always.

- Is there a version in which it did work? 
I don't know the exact version, but it used to work correctly before 4.5 was released. If I upgrade the packages it's fine.

**Comment by 304NotModified** [comment]
are you using the [NLog.Config nuget package](https://www.nuget.org/packages/NLog.config)?

**Comment by c0shea** [comment]
I reproduced it with a brand new solution and project with a fresh install of NLog.Config.

I'm using VS Enterprise 2015 14.0.25431.01 Update 3 with NuGet 3.4.4.

[ConsoleApplication1.zip](https://github.com/NLog/NLog/files/1964230/ConsoleApplication1.zip)

**Comment by 304NotModified** [comment]
I could reproduce your issue with VS2017 (15.6.5), nuget 4.6.0 on your project

it does work on a new asp.net core website

![image](https://user-images.githubusercontent.com/5808377/39526235-79c0f83a-4e1e-11e8-8f42-7fa1dff0ed2d.png)

**Comment by 304NotModified** [comment]
the same issue is there for a new MVC 5 application (.net 4.5.2)

![image](https://user-images.githubusercontent.com/5808377/39526328-b960ac74-4e1e-11e8-9e86-9119e5feb021.png)

**Comment by 304NotModified** [comment]
funny, 4.4.13 does work on MVC 5:

![image](https://user-images.githubusercontent.com/5808377/39526371-d8f0cd44-4e1e-11e8-9272-11ba886c90d5.png)

**Comment by 304NotModified** [comment]
@c0shea could you test with NLog.Config 4.4.13?

**Comment by 304NotModified** [comment]
related: https://github.com/NuGet/Home/issues/6404, https://github.com/NuGet/Home/issues/4834

**Comment by 304NotModified** [comment]
reported here: https://github.com/NuGet/Home/issues/6894

**Comment by c0shea** [comment]
@304NotModified Thanks for all your efforts on this. I tried with VS 2015 using NLog.Config 4.4.13 and it works and sets it to Copy always.

![image](https://user-images.githubusercontent.com/17714002/39528092-2769ae9c-4df1-11e8-96fe-597a3dbc244c.png)

Using VS 2017 and NLog.Config 4.5.3 I was able to reproduce like you

![image](https://user-images.githubusercontent.com/17714002/39528267-a0f500d6-4df1-11e8-99ae-081393be9810.png)

**Comment by 304NotModified** [comment]
Thanks! I think I found the issue, install.ps1 was still needed.

PR: #2687

I hope it works in the build chain on appveyor.

**Comment by 304NotModified** [comment]
@c0shea you please confirm it's fixed with this package?

https://ci.appveyor.com/api/buildjobs/x6wdcg1i88vw140q/artifacts/artifacts%2FNLog.Config.4.5.3.nupkg

thanks in advance!

**Comment by c0shea** [comment]
@304NotModified Thanks Julian! It's fixed with that package. It set NLog.config to Copy if newer and I verified it did, in fact, copy the file to my bin directory on build.

**Comment by 304NotModified** [comment]
OK thanks for reporting, testing & confirming!, this will be included in NLog 4.5.4

**Comment by c0shea** [comment]
Sweet, thanks!

**Comment by snakefoot** [comment]
@c0shea NLog 4.5.4 has been released, that fixes the issue: https://www.nuget.org/packages/NLog/
