### ISSUE TITLE
Unstable test NLog.UnitTests.Targets.AsyncTaskTargetTest.AsyncTaskTarget_TestTimeout

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#2713]
https://ci.appveyor.com/project/nlog/nlog/build/4.5.0-7756

**Comment by snakefoot** [comment]
@304NotModified Have not seen this error for a long time. Maybe resolved with changes in #2909 and #2914

**Comment by 304NotModified** [comment]
Thanks! Closing this for now :)
