### ISSUE TITLE
Possible bug: DatabaseTarget's RunInstallCommands disregards SqlParameters

### ISSUE THREAD

**Issue by Jejuni** [NLog/NLog#2715]
Hey,

I tried running the following, simple code to be executed as an install command:

```c#
(...)
var config = new LoggingConfiguration();
var installDbCommand = new DatabaseCommandInfo
{
    Text = "INSERT INTO Application(Name) SELECT @app WHERE NOT EXISTS(SELECT 1 FROM Application WHERE Name = @app);"
};
            
var sqliteTarget = new DatabaseTarget("sqlite")
{
    DBProvider = "Microsoft.Data.Sqlite.SqliteConnection, Microsoft.Data.Sqlite, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60",
    ConnectionString = $"Data Source={sqlitePath}"
};
sqliteTarget.InstallDdlCommands.Add(installDbCommand);
installDbCommand.Parameters.Add(new DatabaseParameterInfo("@app", appName));

(...) Omitting actual working logging command for brevity (...)

config.AddRuleForAllLevels(sqliteTarget);
LogManager.Configuration = loggingConfig;
LogManager.Configuration.Install(new InstallationContext());
```

Internally, the Microsoft.Data.Sqlite Assembly would always throw an exception that the "@app" parameter needed to be definied.

I checked the source code for DatabaseTarget.cs and the the WriteEventToDatabase Method loops through all the available parameters, the RunInstallCommands method, however, does not. That would explain the the exception.
Since the DatabaseCommandInfo class has a Parameters Collection I assume I've encountered a bug.

**Comment by 304NotModified** [comment]
Hi! Thanks for reporting. 

Would it be possible to send a PR? (with unit test?)

**Comment by Jejuni** [comment]
Hey, no problem.
I'll get a PR and unit tests ready soon.
