### ISSUE TITLE
feat(Logical Context): The equivalent to log4net.ThreadLogicalContext

### ISSUE THREAD

**Issue by bfcamara** [NLog/NLog#272]
NLog has the GlobalDiagnosticsContext and the MappedDiagnosticsContext.

The MappedDiagnosticsContext stores the dictionary in the thread locall storage, which it does not flow in async points. For example, if I am using the async/await pattern in my web application, and I want to log  a specific property (being set in the begining of the request processing), in all my log statements, if I use the MaapedDiagnosticsContext, I will lose the property in logs as soon the request jump to another thread.

I've explained this problem in my blog: http://www.bfcamara.com/post/66886024762/nlog-how-to-include-custom-context-variables-in-all

Log4Net supports this scenario by using the  log4net.ThreadLogicalContext

In my current project, I've implemented this feature, but before doing a PR, I would like to have some opinions.

Basically I've used the CallContext (instead of thread local storage), which flows in async points.

```
public static class MappedDiagnosticsLogicalContext
{
    private const string LogicalContextDictKey = "NLog.MappedDiagnosticsLogicalContext";

    private static IDictionary<string, string> LogicalContextDict
    {
        get
        {
            var dict = CallContext.LogicalGetData(LogicalContextDictKey) as ConcurrentDictionary<string, string>;
            if (dict == null)
            {
                dict = new ConcurrentDictionary<string, string>();
                CallContext.LogicalSetData(LogicalContextDictKey, dict);
            }
            return dict;
        }
    }

    public static void Set(string item, string value)
    {
        LogicalContextDict[item] = value;
    }

    public static string Get(string item)
    {
        string s;

        if (!LogicalContextDict.TryGetValue(item, out s))
        {
            s = string.Empty;
        }

        return s;
    }
}
```

I also have a new Layout Render (mdlc - mapped diagnostics logical context)

```
/// <summary>
/// Mapped Diagnostic Logical Context item (based on CallContext).
/// </summary>
[LayoutRenderer("mdlc")]
public class MdlcLayoutRenderer : LayoutRenderer
{
    /// <summary>
    /// Gets or sets the name of the item.
    /// </summary>
    /// <docgen category='Rendering Options' order='10' />
    [RequiredParameter]
    [DefaultParameter]
    public string Item { get; set; }

    /// <summary>
    /// Renders the specified MDLC item and appends it to the specified <see cref="StringBuilder" />.
    /// </summary>
    /// <param name="builder">The <see cref="StringBuilder"/> to append the rendered data to.</param>
    /// <param name="logEvent">Logging event.</param>
    protected override void Append(StringBuilder builder, LogEventInfo logEvent)
    {
        string msg = MappedDiagnosticsLogicalContext.Get(this.Item);
        builder.Append(msg);
    }
}
```

What do you think?

**Comment by snakefoot** [comment]
NLog v4.1 introduced support for MappedDiagnosticsLogicalContext (MDLC). See also #833

NLog v5.0 merged MappedDiagnosticsLogicalContext (MDLC). + MappedDiagnosticsContext (MDC) into NLog ScopeContext.
