### ISSUE TITLE
Feature request: Add support to capture properties in fluent interface

### ISSUE THREAD

**Issue by katdti** [NLog/NLog#2720]
Background for this request:
 I am trying to log properties using nlog-targests-seq so they are searchable in seq.
 I know I can use @ to serialize objects in messages - but is seems not possible for user properties?

Pseudo c# code that works (I can e.g. search for x.status=0 i seq):
```c#
class MyClass { public int status { get; set; } };
var x = new MyClass();
log.Debug().Message("Write {@x}", x).Write();

```
Pseudo c# code not working (only x class name is serialized so I can not search for x.status=0):
```c#
class MyClass { public int status { get; set; }
var x= new MyClass();
log.Debug().Message("Write Hi").Property("x", x).Write();

```
Today I have to format every property into the message string - this does not seem like an optimal method for structured logging.

Suggestion is to add a capture option like this:
   `log.Debug().Message("Write Hi").Property("x", x, capture: true).Write();`

Regards

**Comment by 304NotModified** [comment]
Well you could use the JsonLayout to serialize property "x"? 

e.g. https://github.com/NLog/NLog/wiki/JsonLayout#nested-json-with-structured-logging

**Comment by katdti** [comment]
Correct. Serializing to file with json format works. But nlog-targests-seq does not support includeAllProperties. So the choice is to add includeAllProperties in nlog-targests-seq or NLog adds a capture option.

To quote @nblumhardt from nlog-targests-seq
> Although it might seem like capturing structure is a reasonable alternative default, it's not always clear-cut. E.g. Property("MessageType", message.GetType()) is a case where the value benefits enormously from being considered a string - serializing broad structures like Type, even to a limited depth, can generate tonnes of data very quickly.

> To handle this case, Serilog (upon which NLog's new structured logging support is based) accepts a Boolean to the equivalent of Property(),

**Comment by 304NotModified** [comment]
OK, have to think about this. It's a bit against the current structure in NLog

@snakefoot what do you think?

**Comment by snakefoot** [comment]
I think the Seq-target should provide support for configuring MaxRecursionLimit


Sent from my Samsung device


-------- Original message --------

**Comment by nblumhardt** [comment]
Just a slight clarification:

> But nlog-targests-seq does not support includeAllProperties

The Seq target [always includes all properties](https://github.com/datalust/nlog-targets-seq/blob/dev/src/NLog.Targets.Seq/CompactJsonLayout.cs#L45), or does this not always work?

Wouldn't doing this via `MaxRecursionLimit` turn something that's a per-value requirement into a global one?

E.g. that might make:

```csharp
log.Debug().Message("Write Hi").Property("User", x).Write();
```

record `"User"` one way, but then five minutes later won't the next requirement be to have:

```csharp
log.Debug().Message("Write Hi, again!").Property("MessageType", y).Write();
```

use the opposite strategy for `"MessageType"`?

It's not too much of a stretch to think that a user might want some properties structured (e.g. a DTO reflecting the username, id etc. of a user), and others not to be structured (e.g. a `Type` that represents the kind of message being processed)?

**Comment by snakefoot** [comment]
> use the opposite strategy for "MessageType"?

Then the user just have to add `ToString()`:

`log.Debug().Message("Write Hi, again!").Property("MessageType", y.ToString()).Write();`

**Comment by nblumhardt** [comment]
Hmm, that's a fair workaround if all your code is being used in one application, and you decide on which setting to use up-front; but, if you are writing code that's shared between many apps, or changing the default after-the-fact, the behavior changes could be rather unexpected.

I.e. if you start with:

```
log.Debug().Message("Write Hi, again!").Property("MessageType", y).Write();
```

and the non-serializing defaults, but later turn on serialization, then you're in for a rather surprising payload in `"MessageType"`, here. There are other scenarios where this becomes a footgun.

This is back to the same conundrum we originally had when discussing whether `{Foo}` in a message template should be serialized or not - there's really no logical, safe, predictable way to set this on a global level. We got explicit `@` capture types into 4.5 before it RTM'd to fix this - I think this case is the exact parallel for the `Property()` API.

**Comment by snakefoot** [comment]
Right now the default behavior in NLog is to perform full serialization of all Properties. I guess when the need arrives then we will provide a method to restrict this.

I implemented the message-template-restriction for you, so out-of-box-experience would be very similar to Serilog. But NLog-Properties have a different origin than Serilog Parameters, and never had any builtin restriction in how they were serialized.

**Comment by katdti** [comment]
It was not well formulated from my side.
Seq include all Properties but as ToString values in my tests - except for Dictionary!

With regard to 

`. Property("MessageType", message.GetType()) `

I think it should serialize the object - if the hacker wants to log the name he should write

`. Property("MessageType", message.GetType().FullName) `

Is the conclusion:
All targets including nlog-targets-seq should always serialize the Property value as object with properties and not as ToString.
?

**Comment by snakefoot** [comment]
> @katdti All targets including nlog-targets-seq should always serialize the Property value as object with properties and not as ToString ?

My conclusion is that if MaxRecursionLimit > 0, then it should serialize all properties, unless the mesage-template specifies tostring-only.

**Comment by snakefoot** [comment]
@304NotModified This can now be closed as https://github.com/datalust/nlog-targets-seq/pull/34 has been resolved

**Comment by 304NotModified** [comment]
OK Thanks!
