### ISSUE TITLE
Nlog 4.5 WhenRepeated with multiple targets in logger writeTo only writes to first target

### ISSUE THREAD

**Issue by melmears** [NLog/NLog#2722]

**Comment by melmears** [comment]
Type:  Bug  (I think)
NLog version: 4.5.4
Platform:  .Net 4.6.1
Current NLog config:

<nlog throwConfigExceptions="true"> 
  <variable name="logDirectory" value="C:/GhostConveyLogs"/>
<targets>
 <target name="eventlogError" type="EventLog"
      log="GhostConveyOnline" source="${event-properties:item=EventLogSource}" eventId="${event-properties:item=EventLogId}"
       layout="${message}${newline}${event-properties:item=ErrorReport}" maxMessageLength="32766" />
    <target name="databaseError" type="Database" connectionStringName="GhostConveyOnlineData">
      <commandText>
        INSERT INTO [dbo].[NET_Error] ([Callstack],[Computer],[ErrorReport],[ErrorTime],[Message],[ProductVersion],[SystemInfo],[User])
        VALUES (@Callstack, @Computer, @ErrorReport, @ErrorTime, @Message, @ProductVersion, @SystemInfo, @User)
      </commandText>
      <parameter name="@Callstack" layout="${exception:format=toString}" />
      <parameter name="@Computer" layout="${event-properties:item=Computer}" />
      <parameter name="@ErrorReport" layout="${event-properties:item=ErrorReport}"/>
      <parameter name="@ErrorTime" layout="${date:format=yyyy-MM-dd HH\:mm\:ss.fff}" />
      <parameter name="@Message" layout="${message}" />
      <parameter name="@ProductVersion" layout="${event-properties:item=ProductVersion}" />
      <parameter name="@SystemInfo" layout="" />
      <parameter name="@User" layout="${event-properties:item=User}" />
    </target>
 </targets>
<rules>
    <logger name="ErrorLog" minlevel="Error" writeTo="eventlogError,databaseError" >
      <filters>
        <whenRepeated layout="${exception:format=ToString:whenEmpty=${message}}"
         FilterCountMessageAppendFormat=" (Hits: {0})"
         timeoutSeconds="900" action="Ignore" />
      </filters>
    </logger>
    <logger name="ErrorLog" minlevel="Error" writeTo="fileError" />
</rules>
</nlog>


What is the current result?  only writes to the first target.  For exmample eventLog or if I change the order in the config, only to the database.  However, if I include both targets without the WhenRepeated -> then it writes to both.
What is the expected result? Should write to both the targets in writeTo
Did you checked the Internal log? Yes, no errors - just trace and debug lines
Please post full exception details (message, stacktrace, inner exceptions)
Are there any workarounds? no, even when I separate loggers, each with a filter - the second logger does not log correctly.
Is there a version in which it did work? not sure
Can you help us by writing an unit test?

**Comment by snakefoot** [comment]
@304NotModified Maybe you can fix the styling of the code-samples in the above comment?

**Comment by 304NotModified** [comment]
yes, done!

**Comment by snakefoot** [comment]
Yes that is not a very intuitive behavior. The reason is that the filter is checked for every target, and not just once for all targets.

This means for the first target, then the filter-check passes, but the for the second-target then the filter-check rejects because it seen as repeated log-event.

I'm not sure why we re-run the filtering-logic for every target in the in the target chain. Can you reveal a reaon for this @304NotModified ?

**Comment by snakefoot** [comment]
Have created #2726 to fix this.

**Comment by snakefoot** [comment]
@melmears NLog 4.5.5 has been released: https://www.nuget.org/packages/NLog/
