### ISSUE TITLE
archiveEvery does not include all archives since the last date

### ISSUE THREAD

**Issue by vankampenp** [NLog/NLog#2729]
**Type**  Bug

**NLog version**: 4.5.4

**Platform**: NET Core 

**Current NLog config** 

```xml
  <target xsi:type="File" name="ownFile-trace" fileName="logs\${machinename}-trace-${shortdate}.log"
            layout="${longdate}|${aspnet-request-ip}|${aspnet-User-Identity}|${pad:padding=-5:${uppercase:${level}}}|${assembly-version}|${pad:padding=-3:${threadid}}|${aspnet-mvc-controller}|${callsite:className=True:includeNamespace=False:fileName=False:includeSourcePath=False:methodName=True}|${message}|${exception}"
            maxArchiveFiles="14"
            archiveFileName="logs\archive\${machinename}-trace.{#}.zip"
            archiveNumbering="Date"
            archiveEvery="Saturday"
            archiveDateFormat="yyyyMMdd"
            enableArchiveFileCompression ="true"
            />

```

In case of a BUG:

- What is the current result?
On the first write on Satury, the log file from Friday is put in an archive file. It is also removed from the log directory
- What is the expected result?
Using archiveEvery="Saturday", I expected 7 log files to be moved to an archive file, that is, the files from the previous Saturday to Friday, not just one log file. I assume it has to do with having a date on the log file name. I would like to have a daily log file, rather than one big one, an combine these in one archive. Since the configuration target specifies that there is a date, it should be able to handle this case.
- Are there any workarounds? yes/no
no
- Is there a version in which it did work? 
no
- Can you help us by writing an unit test?
no

**Comment by snakefoot** [comment]
`archiveEvery="Saturday"`   means that you use the same file for the entire week, until saturday where you start on a new file.

There could certainly be made some improvements to the compression-part of the file-target. One is to remove the compression-logic from the the file-target. Instead have a file-target-wrapper, that monitors the file-target for archive-events. See also ideas here https://stackoverflow.com/questions/46569005/nlog-with-enablearchivefilecompression-doesnt-work

**Comment by vankampenp** [comment]
Thanks, I assume it is implemented that way, but it is not clear from the documentation, nor logical in my humble view. 
I think `archiveEvery="Saturday"` should me move all the file or files to an archive every Saturday. Perhaps there should be a filemask in the target to determine what files are moved to the archive.
archiveFileMask="logs\${machinename}-trace-*.log"
Meaning all files that comply with this mask will be added to the archive.

**Comment by snakefoot** [comment]
I think it was a mistake to put the compression-logic directly into the FileTarget directly. Instead it should be something that can be configured separately which receives archive-notification-events from the FileTarget.

You are very welcome to create a PullRequest (PR) to improve this area. So your ideas of logical behavior becomes true.

**Comment by 304NotModified** [comment]
I'm gonna close this one, as in my opinion this is solved.

For a feature request, please create a new issue, so it is more clear what to implement.
