### ISSUE TITLE
One log file per request

### ISSUE THREAD

**Issue by Nodios** [NLog/NLog#2730]
**Type** (choose one):

- Question

**NLog version**:  4.5.4

**Platform**: .NET Core 

**Current NLog config** (xml or C#, if relevant):

```xml
<nlog>
  <variable name="logDirectory" value="D:\logdir\${shortdate}" />
  <targets>
    <target xsi:type="File" name="mytarget" fileName="${logDirectory}\logfile.log" layout="${message}" />
  </targets>
</nlog>

```
Because of the specific business logic, I need to have **one log file per HTTP request**. I was changing 'mytarget's name programmatically like
```c#
var target = (FileTarget) LogManager.Configuration.FindTargetByName("mytarget");
var dir = LogManager.Configuration.Variables.FirstOrDefault(v => v.Key == "logDirectory");
target.FileName = $"{dir.Value.OriginalText}\\{uniqueRequestId}.log";

LogManager.ReconfigExistingLoggers();
```
but found out that the log will be written to the log file with the name that was last set. Someone on the StackOverflow mentioned using MDLC, is that the way to go for this specific scenario? 

If not, what are the recommendations?

**Comment by snakefoot** [comment]
If you just need to use the same Guid in both targets then you can do this:

```xml
<nlog>
  <variable name="logDirectory" value="D:\logdir\${shortdate}" />
  <targets>
    <target xsi:type="File" name="mytarget" fileName="${logDirectory}\${guid:generatedFromLogEvent=true}.log" layout="${message}" />
  </targets>
</nlog>
```

But yes an alternative approach is to setup MDLC before each LogEvent. See https://github.com/NLog/NLog/wiki/MDLC-Layout-Renderer

Yet another alternative approach is using the Fluent-interface and insert the Guid as EventProperty. See 
https://github.com/NLog/NLog/wiki/EventProperties-Layout-Renderer and https://github.com/NLog/NLog/wiki/Fluent-API

**Comment by 304NotModified** [comment]
another option is to set a guid in the http context itemss and use the ${aspnet-item:variable=myvariable} in the filename. 

see https://stackoverflow.com/a/50533462/201303.

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, please let us know!
