### ISSUE TITLE
Unable to extend WrapperTargetBase without converting IList<AsyncLogEventInfo> to AsyncLogEventInfo[]

### ISSUE THREAD

**Issue by joaorosado** [NLog/NLog#2738]
Hi

I'm trying to make a target wrapper but I don't see how I'm supposed to implement the Write(IList<AsyncLogEventInfo> logEvents) method without converting the IList to an array.

We are expected to override the Write method that takes a IList (since the array one is deprecated)
`protected override void Write(IList<AsyncLogEventInfo> logEvents) {
            WrappedTarget.WriteAsyncLogEvents(logEvents);
}`

But the WriteAsyncLogEvents that takes a IList is marked as internal forcing me to convert it to an array and call the WriteAsyncLogEvents(params AsyncLogEventInfo[] logEvents) method.

Is there a better way to do this or should this be a Bug/Feature Request?

**Type**:
- Question

**NLog version**: 4.5.4

**Platform**: .Net 4.5 

In case of a BUG:

- What is the current result?
Having to convert the IList<AsyncLogEventInfo> to AsyncLogEventInfo[] to be able to call the only public method on the Wrapped Target

- What is the expected result?
To be able to call the WriteAsyncLogEvents that is currently marked as internal.

- Are there any workarounds? yes
- Is there a version in which it did work? no

**Comment by snakefoot** [comment]
Not sure why you say the method is internal. It looks protected and virtual to me, and easy to override:

https://github.com/NLog/NLog/blob/ac99d37beaffb5738d4796c9f9b3fced66a7f62b/src/NLog/Targets/Target.cs#L626

The reason for deprecation of the array-version is to minimize memory-allocations, as it will allow to reuse the same payload for next batch.

**Comment by 304NotModified** [comment]
I think he means:

https://github.com/NLog/NLog/blob/29c5930c0acb8955955625f5b5f8b36b3794ab9f/src/NLog/Targets/Target.cs#L340

Good point.

**Comment by 304NotModified** [comment]
I think this is a valid design, as we also use it here:

https://github.com/NLog/NLog/blob/6cccc7b700ab6d94543d3de5229cd3081f35b3c5/src/NLog/Targets/Wrappers/ImpersonatingTargetWrapper.cs#L205-L211

So the method `WriteAsyncLogEvents(IList<AsyncLogEventInfo>)` should be protected

**Comment by 304NotModified** [comment]
@joaorosado good suggestion, we will fix this in 4.5.5!
