### ISSUE TITLE
UTC based archiving

### ISSUE THREAD

**Issue by adamralph** [NLog/NLog#274]
When using UTC universally (:wink:) including timestamps on log messages, it would make more sense if time based archiving could also be set to use UTC. E.g.:

```xml
<target
  archiveEvery="Day:universalTime=true" />
```

**Comment by 304NotModified** [comment]
@mattAtCSL PR Would be great.

**Comment by mattAtCSL** [comment]
Pull request #504.

**Comment by adamralph** [comment]
@mattAtCSL great!

**Comment by adamralph** [comment]
I've gotten completely lost in the various PR's which may or may not add this feature and have/have not been merged. I think if/when this feature is released the most important thing is that the wiki is updated so that it's clear how to switch on UTC based archiving.

**Comment by mattAtCSL** [comment]
If they go for the fix where the same date time source is used for archiving as the time stamps on log entries you'll not need another setting, using a UTC time type will mean the archiving period matches the log entry times.

**Comment by adamralph** [comment]
As long as the final solution is clearly communicated, I'll be happy :smile:

**Comment by 304NotModified** [comment]
I think the lasted PR (#512), should include this feature. Too bad the're a lot of failing unit tests with PR #512.
