### ISSUE TITLE
assembly-version returns "Could not find entry assembly" in ASP.NET logging

### ISSUE THREAD

**Issue by slolife** [NLog/NLog#275]
the `${assembly-version}` layout renderer returns "Could not find entry assembly" in ASP.NET. It seems that:

`var assembly = Assembly.GetEntryAssembly();`

Returns null in ASP.NET situations.

There is a StackOverflow question/answer that seems to have a solution:

http://stackoverflow.com/a/4803419/698

For myself, I've been able to make it work with:

`Assembly assembly = HttpContext.Current == null ? Assembly.GetEntryAssembly() : Assembly.GetExecutingAssembly();`

**Comment by 304NotModified** [comment]
So a possible solution is to use https://github.com/laazyj/ApplicationAssemblyUtility in the next version of NLog?

**Comment by drasive** [comment]
I am also having this issue, using NLog 4.0.1 on .NET 4.5.2

**Comment by 304NotModified** [comment]
Thanks for the up. Is not implemented yet. The proposed code isn't a solution for everything, but it's a improvement and probably fixes this case. 

We will look at this for the next  release

**Comment by mikhail-barg** [comment]
As for me, I'm having this issue when logging from a com-server DLL running from a Delphi application. I'm not sure which version I'd like to have in the log, but Assembly.GetEntryAssembly() should probably do.

**Comment by 304NotModified** [comment]
I see this code needs (obvious) system.web.

I think we should move this to nlog.web https://github.com/NLog/NLog.web, under another name?

**Comment by 304NotModified** [comment]
As we need system.web for this, we will implement this in NLog.Web

If everything works as expected, the layout renderer can be added with the same name to NLog.Web.  It should overwrite the one from core. (double check that).

Steps:
- [ ] Create a subclass of the current layout renderer in NLog.Web, same name, different namespace.
- [ ] Implement proposed codde
- [ ] Test with unit test in NLog.web

**Comment by 304NotModified** [comment]
Moved to https://github.com/NLog/NLog.Web/issues/46

**Comment by 304NotModified** [comment]
As a work around, since NLog 4.3.7 you can specificy the assembly name, e.g. `${assembly-version:NLogAutloadExtension}`. See https://github.com/NLog/NLog/wiki/AssemblyVersion-Layout-Renderer

**Comment by 304NotModified** [comment]
Fixed in NLog.Web.AspNetCore 4.4.0 +  NLog.Web 4.5.0
