### ISSUE TITLE
Readable formatted exception message

### ISSUE THREAD

**Issue by rijoshvk** [NLog/NLog#2759]
Type: Question
NLog version: 4.5.6
Platform: .Net 4.0 / .Net 4.5
Current NLog config
My application produces large exception messages traversing over several file paths sometimes producing over 110 kb of single error text data, The output though very informative is a clutter of string text, How can i format or beautify the exception message so that i can make it more readable to the user?
![nlog](https://user-images.githubusercontent.com/17570545/40915888-10d48e8a-6841-11e8-9554-89bb3fd868b8.png)

**Comment by 304NotModified** [comment]
I don't you should use `format=toString` in this case, but use multiple attributes for the exeption, e.g.

`${exception:format=message}` `${exception:format=data}` etc.

See https://github.com/NLog/NLog/wiki/Exception-Layout-Renderer

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, please let us know!
