### ISSUE TITLE
Custom Layout Renderer Lambda not updating value

### ISSUE THREAD

**Issue by Sebastriani** [NLog/NLog#2760]
**NLog version**: 4.5.6
**Platform**: .Net 4.5
**Current NLog config** (xml or C#, if relevant)

Hi, I'm trying to have in a helper class, a Custom Layout Renderer, by using a lambda, to log the string I pass to it like this:
```c#
        public static void LogUserAction(string login, string class, string message)
        {
            LayoutRenderer.Register("logged-user", (LogEvent) => login);
            LogManager.Configuration = LogManager.Configuration;
            Logger usrLogger = LogManager.GetLogger(class);
            usrLogger.Info(message);
        }
```
This is always outputing to "logged-user" the first value it's being passed to it and never the subsequent values.

Now, if instead of a string I pass DateTime.Now, the value get's updated.
Am I missing something? Is this behaviour by design?

Thanks

**Comment by Sebastriani** [comment]
Anyone?

**Comment by 304NotModified** [comment]
There is no NLog config here at all? Please check https://github.com/NLog/NLog/wiki/Tutorial#configure-nlog-targets-for-output

**Comment by Sebastriani** [comment]
I thought that sharing the the NLog config was irelevant... The problem is just the custom renderer, everything else is doing just fine, would this be enough info?

```xml
<attribute name="User" layout="${logged-user}" />
```

**Comment by 304NotModified** [comment]
Just to be sure.

I think the problem here is that the lambda is capturing the string value, and therefor I won't get updated.

e.g.

     LayoutRenderer.Register("logged-user", (LogEvent) => "hello"); //same value everytime

     LayoutRenderer.Register("logged-user", (LogEvent) => DateTime.Now); //different value everytime

**Comment by Sebastriani** [comment]
Sorry for my lack of knowledge, do you mean the lamda itself by means of the CLR captures de variable as a static value? Or somehting in NLog's code does?

I'll try passing as a parameter a simple class with a getter as container for the variable and see what happens, then I'll comment back.

**Comment by Sebastriani** [comment]
This got even weirder.
I did a wrapper class to contain a variable in a getter to pass that class as a parameter and see if that way the custom renderer updated the value, but NLog wasn't even writting the renderer. So I enabled NLog's debug with internalLogLevel="Debug" to try to see what was happening and by doing that... NLog started to output the renderer... Anyway, even passing a wrapper class as a parameter to get the value by a getter didn't work, NLog kept outputing the first value passed to the Lambada so, I added a getter method for the Lambda to get the value instead of a getter but, didn't work either.
So to wrap up:
- NLog is only outputing the custom renderer only if enabling internalLogLevel="Debug"
- If internalLogLevel="Debug", NLog is always outputing the first value passed to the lambda, no matter if you pass a variable, or get the value by a getter or by a method.
- But if you pass a date value even as a string it outputs the correct value

Here goes an example:

Config:

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="false"
      internalLogLevel="Debug" internalLogFile="C:\SEPA\Logs\nlog-internal.log">

  <targets>
    <target name="WrapperUsers" xsi:type="AsyncWrapper" queueLimit="5000" overflowAction="Discard">
      <target name="Users" xsi:type="File" createDirs="true" fileName="C:\MyExample\Logs\Users.log">
        <layout xsi:type="JsonLayout" includeAllProperties="false" renderEmptyObject="false">
          <attribute name="Date" layout="${longdate}" />
          <attribute name="User" layout="${logged-user}" />
          <attribute name="Event" layout="${message}" escapeUnicode="false" />
        </layout>
      </target>
    </target>
  <rules>
    <logger name="MyExample.*" minlevel="Debug" writeTo="Users" />
  </rules>
</nlog>
```
Example Code: Always outputs first passed value

```c#
namespace MyExample
{
    public class LoggerHelper
    {
        public class LoginWrapper
        {
            public string Login { get;  set; }
            public string GetLogin()
            {
                return Login;
            }
        }

        public static void LogUserAction(LoginWrapper loginWrapper, string class, string message)
        { 
            // this doesn't work
            LayoutRenderer.Register("logged-user", (LogEvent) => logginWrapper.Login);
            
            // and this doesn't work either
            LayoutRenderer.Register("logged-user", (LogEvent) => logginWrapper.GetLogin());
            
            // but this always renders the right value
            LayoutRenderer.Register("logged-user", (LogEvent) => DateTime.Now);
            
            // even if you do this, the rendered value is always right
            string variable = DateTime.Now.ToString()
            LayoutRenderer.Register("logged-user", (LogEvent) => variable);

            LogManager.Configuration = LogManager.Configuration;
            Logger logger = LogManager.GetLogger(class);
            logger.Info(message);
        }
    }
}
```
And I call the above just like:
```c#
var login = "AloginIGetSomewhereElse";
LoggerHelper.LogUserAction(new LoggerHelper.LoggerWrapper() { Login = login }, "Login Successfull", GetType().FullName);

I don't understand if this behaviour is by desing, if I'm doing something wrong or whether it's a bug

**Comment by snakefoot** [comment]
@Sebastriani It is extremely bad practice to update/assign the LogManager.Configuration multiple times (ex for every logevent).

Instead I would consider using the MDLC to inject whatever log-context-info you need:

https://github.com/NLog/NLog/wiki/MDLC-Layout-Renderer

**Comment by Sebastriani** [comment]
@snakefoot thanks, yes well I thought the same since it's expressed in the best practices here https://github.com/NLog/NLog/wiki/Tutorial#best-practices-for-logging but Julian told me this https://github.com/NLog/NLog/issues/2766#issuecomment-396080833

I thought I had thoroughly searched in the documentation but it seems I didn't. I hadn't see the EventProperties option, it looks promising for what I wanted.

I had seen ${var} but it's global and I needed per event info, it seems MDLC would also be global?

Anyway, I couldn't get the Custom Layout Renderer Labmda to output the value I pass to it but the first one.

Thanks

**Comment by 304NotModified** [comment]
> @Sebastriani It is extremely bad practice to update/assign the LogManager.Configuration multiple times (ex for every logevent).

agree on that. Missed that.

**Comment by Sebastriani** [comment]
ops sorry, I just realized snakefoot was talking about this
```c#
LogManager.Configuration = LogManager.Configuration;
```
and not about getting a logger each time....

**Comment by 304NotModified** [comment]
> I guess that a Custom Layout Rendered is not meant for what I wanted,

that's correct. I think this case could be closed.
