### ISSUE TITLE
Callsite cleanNamesOfAnonymousDelegates doesn't work when includeNamespace is set to false

### ISSUE THREAD

**Issue by Azatey** [NLog/NLog#2762]
Hi! Thanks for reporting this feature/bug/question! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

QUESTIONS are preferred on StackOverflow. You could expect a faster response there (but do include all the info below). Use the tag "nlog" https://stackoverflow.com/questions/ask

For .NET Core users, please check the platform support: https://github.com/NLog/NLog/wiki/platform-support

**NLog version**: 4.5.6

**Platform**: .Net 4.6.1

Currently when callsite layout renderer's ```includeNamespace``` parameter is set to **false** and ```cleanNamesOfAnonymousDelegates``` parameter is set to **true**, the outcome of callsite will be something like ```<>c```.
Below is a test that will fail.

```c#
[Fact]
public void When_NotIncludeNameSpace_Then_CleanAnonymousDelegateClassNameShouldReturnParentClassName()
{
	LogManager.Configuration = CreateConfigurationFromString(@"
		<nlog>
			<targets><target name='debug' type='Debug' layout='${callsite:ClassName=true:MethodName=false:IncludeNamespace=false:CleanNamesOfAnonymousDelegates=true}' /></targets>
			<rules>
				<logger name='*' levels='Fatal' writeTo='debug' />
			</rules>
		</nlog>");

	ILogger logger = LogManager.GetLogger("A");

	bool done = false;
	ThreadPool.QueueUserWorkItem(
		state =>
		{
			logger.Fatal("message");
			done = true;
		},
		null);

	while (done == false)
	{
		Thread.Sleep(10);
	}

	if (done == true)
	{
		AssertDebugLastMessage("debug", "CallSiteTests");
	}
}
```
My suggestion is to append additional logic to check if the class is nested and compiler generated, and if so, use its ```DeclaringType``` for naming.
Created PR for this: https://github.com/NLog/NLog/pull/2761

**Comment by 304NotModified** [comment]
Thanks for reporting and fixing!
