### ISSUE TITLE
New FileVersionInfoRenderer

### ISSUE THREAD

**Issue by alexangas** [NLog/NLog#2765]
**NLog version**: 4.5.6

**Platform**: Where FileVersionInfo API is available according to MS docs

 - Why do we need it?

We currently have AssemblyVersionLayoutRenderer (which I have added features to before). I would like to add a FileVersionInfoRenderer that exposes properties on FileVersionInfo. https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.fileversioninfo?view=netframework-4.7.1

Would there be any questions or objections to this?

**Comment by 304NotModified** [comment]
are you looking for `${assembly-version:type=file}`? See https://github.com/NLog/NLog/wiki/AssemblyVersion-Layout-Renderer

**Comment by alexangas** [comment]
I know of that renderer (actually added a minor feature to it!). They are actually different APIs that return subtly different data. However after further investigation, I don't really need this. Raising an issue in nlog/nlog.web instead. :smile:
