### ISSUE TITLE
loggerName in LogEventInfo.Create() does not fully override name set with LogManager

### ISSUE THREAD

**Issue by Sebastriani** [NLog/NLog#2766]
**NLog version**: 4.5.6
**Platform**: .Net 4.5
**Current NLog config** (xml or C#, if relevant)

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="false"
      internalLogLevel="Off" internalLogFile="C:\MyProject\Logs\nlog-internal.log">

  <targets>
    <target name="GeneralWrapper" xsi:type="AsyncWrapper" queueLimit="5000" overflowAction="Discard">
      <target name="General" xsi:type="File" createDirs="true" fileName="C:\MyProject\Logs\General${level}.log">
        <layout xsi:type="JsonLayout" includeAllProperties="false" renderEmptyObject="false">
          <attribute name="Logger" layout="${logger}" />
          <attribute name="Date" layout="${longdate}" />
          <attribute name="Exception" layout="${exception:format=toString,Data:maxInnerExceptionLevel=10}" escapeUnicode="false" />
          <attribute name="Event" layout="${message}" escapeUnicode="false" />
          <attribute name="Data" encode="false">
            <layout xsi:type="JsonLayout" includeAllProperties="true" renderEmptyObject="false" maxRecursionLimit="10" />
          </attribute>
        </layout>
      </target>
    </target>
    <target name="TasksWrapper" xsi:type="AsyncWrapper" queueLimit="5000" overflowAction="Discard">
      <target name="Tasks" xsi:type="File" createDirs="true" fileName="C:\MyProject\Logs\Tasks.log">
        <layout xsi:type="JsonLayout" includeAllProperties="false" renderEmptyObject="false">
          <attribute name="Logger" layout="${logger}" />
          <attribute name="Date" layout="${longdate}" />
          <attribute name="Event" layout="${message}" escapeUnicode="false" />
          <attribute name="Data" encode="false">
            <layout xsi:type="JsonLayout" includeAllProperties="true" renderEmptyObject="false" maxRecursionLimit="10" />
          </attribute>
        </layout>
      </target>
    </target>  
  </targets>

  <rules>
    <logger name="MyProject.Core*" minlevel="Debug" writeTo="General" />
    <logger name="Tasks" level="Debug" writeTo="Tasks" />
  </rules>
</nlog>
```

Here goes example code, it always writes to "General" logger:
```C#
namespace MyProject.Core.Helpers
{
    public class LoggerHelper
    {
        // It's the same with any of the following two, the logger name used for the rules config
        // it's not overriden by LogEventInfo.Create

        // This one
        private static Logger logger = LogManager.GetCurrentClassLogger();
        // Or this one...
        // private static Logger logger = LogManager.GetLogger("Whatever");

        public static void TasksLog(string message, object[] data)
        {
            var logEventInfo = LogEventInfo.Create(LogLevel.Info, "Tasks", CultureInfo.InvariantCulture, message, data);
            logger.Log(logEventInfo);
        }

        public static void GeneralInfoLog(string class, string method, string menssage, object[] data)
        {
            var logEventInfo = LogEventInfo.Create(LogLevel.Info, class + "." + method, CultureInfo.InvariantCulture, message, data);
            logger.Log(logEventInfo);
        }
    }
}

```

- What is the current result?
The config rules apply to the original name set by LogManager and everthing gets logged to target "General". 

- What is the expected result?
I expect the config rules to be applied to the logger name I set in LogEventInfo.Create and data to be logged accordingly to "General" or "Tasks". The layout renderer ${logger} works as I expected and renders the name from LogEventInfo and not the original name.

- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
2018-06-09 13:41:43.6939 Debug FileTarget(Name=General): Process file 'C:\MyProject\Logs\GeneralInfo.log' on startup
2018-06-09 13:41:43.6939 Debug Creating file appender: C:\MyProject\Logs\GeneralInfo.log

- Are there any workarounds? yes
I can get a logger from LogManager with the name I want, within each function call, but I intend to not to...

**Comment by 304NotModified** [comment]
I think the loggerImpl will overwrite the logger name. Have to check that. 

But IMO this is a pretty good option:

```
namespace MyProject.Core.Helpers
{
    public class LoggerHelper
    {
        // It's the same with any of the following two, the logger name used for the rules config
        // it's not overriden by LogEventInfo.Create

        // This one
        private static Logger logger = LogManager.GetCurrentClassLogger();
        // Or this one...
        // private static Logger logger = LogManager.GetLogger("Whatever");

        public static void TasksLog(string message, object[] data)
        {
            var logEventInfo = LogEventInfo.Create(LogLevel.Info, "Tasks", CultureInfo.InvariantCulture, message, data);
             LogManager.GetLogger("Tasks").Log(logEventInfo);
        }

        public static void GeneralInfoLog(string class, string method, string menssage, object[] data)
        {
            var logEventInfo = LogEventInfo.Create(LogLevel.Info, class + "." + method, CultureInfo.InvariantCulture, message, data);
            LogManager.GetLogger(class + "." + method).Log(logEventInfo);
        }
    }
}

```

**Comment by Sebastriani** [comment]
Yes, that's what I'm actually doing, but I would prefer not to do that because of NLog's best practices https://github.com/NLog/NLog/wiki/Tutorial#best-practices-for-logging

Specifically:
**1. Logger should be a static variable in each class**
Creating a new Logger has an overhead, as it has to acquire locks and allocate objects.

I don't know the impact that this overhead would have in the application if say, 100 loggers are being gotten at the same time, but if it's not so significant that code will do.

**Comment by 304NotModified** [comment]
> 1. Logger should be a static variable in each class
> Creating a new Logger has an overhead, as it has to acquire locks and allocate objects.

true, but the loggers are cached and the getlogger is faster than getCurrentClassLogger.

static is preferred, but it's currently not possible for you case. Anyway, I highly doubt if you see any performance difference..

**Comment by Sebastriani** [comment]
Ok, it'll work fine like that for me then, but anyway, if LogEventInfo.Create() should fully override the logger name, probably you should look at it, because believe me it doesn't override it for rule cheking but only fo the layout renderer ${logger}

Thanks!

**Comment by snakefoot** [comment]
> @Sebastriani  If LogEventInfo.Create() should fully override the logger name, probably you should look at it

It is not intended to override the logging rules of the used logger. It would introduce too much overhead. Maybe it would be more userfriendly that the logger always assigned its name to `LogEventInfo.Logger`, but it would be a breaking change and few are tinkering with the NLog internals.

**Comment by Sebastriani** [comment]
@snakefoot I solved it by doing this https://github.com/NLog/NLog/issues/2766#issuecomment-396003874

Thanks!

**Comment by 304NotModified** [comment]
> It would introduce too much overhead.

With that in mind, we will close this one. Thanks!

**Comment by snakefoot** [comment]
Created #2917 so the Logger assigns LogEventInfo.LoggerName if uninitialized (null).
