### ISSUE TITLE
NLog.Logger is not Serializable

### ISSUE THREAD

**Issue by doug144** [NLog/NLog#2770]
**NLog version 4.4.12**
**Platform**: Net 4.5 (but it should be relevant for all platforms)

It seems that [NLog.Logger](https://github.com/NLog/NLog/blob/master/src/NLog/Logger.cs) is not serializable. This prevents saving it in a field in a serializable class. We came accross the issue when building a PostSharp aspect, which is required to be serializable. This issue was opened in the past in [issue #1345](https://github.com/NLog/NLog/issues/1345), but was closed for inactivity.

Previously, we were using NLog through Common.Logging, and there it was not an issue. Is it possible to implement it here as well?

**Comment by 304NotModified** [comment]
Could you give some more info on what your doing?

**Comment by doug144** [comment]
I'm building a [PostSharp](https://www.postsharp.net/) aspect and it has an Nlog.Logger member. However, Postsharp requires all of the members to be serializable, but that class is not.

**Comment by 304NotModified** [comment]
I was more curious what kind of aspect :) 

Could you give an example? Thanks!

**Comment by doug144** [comment]
On second thought, it seems that it would not be reasonable to save the logger at compile time, since we are using the `LogManager.GetLogger` method, which is based on configuration. I will implement similarly to how we did [here](https://github.com/pub-comp/aspects/blob/master/Monitoring/LogAttribute.cs).

I am closing the issue. Thanks.
