### ISSUE TITLE
Writing custom target wrapper: changing LogEventInfo.Message does not reset _layoutCache

### ISSUE THREAD

**Issue by kvchernyaev** [NLog/NLog#2773]
I want to write custom target wrapper. My custom wrapper needs to change log message - it  accumulates count and appends it (https://github.com/NLog/NLog/pull/2751).

And i noticed - when wrapped target is **FileTarget** (or **MailTarget**) so text in file (or email) is unchanged. I see in **LogEventInfo** class that it uses **_layoutCache** for caching rendered layout (but i guess that **ConsoleTarget** does not use that cache?). 

I guess it is a bug - is'nt it?
What workaround can i use?

**Comment by snakefoot** [comment]
Targets or target wrappers should not modify logevents. Only loggers with their filters. You need an external cache that a custom layout renderer can perform lookup in.

**Comment by kvchernyaev** [comment]
@snakefoot Why you forbid to append some additional info to log message in custom wrapper?  I think it is not good for public library.
And other question - why FILTER modifies log message? It breaks SRP, doesnt it?

**Comment by kvchernyaev** [comment]
Oh. I can not even **set property** in custom wrapper! That property is not shown in layout for FileTarget (_${all-event-properties}_)

It is 100% bug.

**Comment by kvchernyaev** [comment]
Oh guys - i deleted code **PrecalculateVolatileLayouts(e.LogEvent);** in method _protected override void Write(AsyncLogEventInfo e)_ - i copy-pased it from other wrapper target. And it is now ok. 
Sorry guys. I think this theme can be closed.

**Comment by snakefoot** [comment]
If you apply the AsyncTargetWrapper around your target  (or use targets async="true") then you will see the "bug" again.

Nlog sends the same LogEvent-instance to all targets (performance). So if one target modifies the LogEvent then it affects all other targets


Sent from my Samsung device


-------- Original message --------

**Comment by 304NotModified** [comment]
> I think this theme can be closed.

Thanks for the feedback!
