### ISSUE TITLE
maxArchiveFiles inconsistent behavior

### ISSUE THREAD

**Issue by ittegrat** [NLog/NLog#2775]
**NLog version**: 4.5.6
**Platform**:  .Net 4.0

**Current NLog config** (xml or C#, if relevant)

```xml
<nlog>
  <targets>
    <target name="tracelog" xsi:type="File"
        fileName="trace.log"
        archiveNumbering="Rolling"
        archiveOldFileOnStartup="true"
        maxArchiveFiles="1"
    />
  </targets>
  <rules>
    <logger name="*" minlevel="Trace" writeTo="tracelog" />
  </rules>
</nlog>

```

I'm not sure if the following behavior is expected / known or not:
- when `maxArchiveFiles` is set to **0**, I get the current log file and **all** the archived versions (i.e. trace.log, plus trace.0.log, trace.1.log, trace.2.log ...)
- when `maxArchiveFiles` is set to **1**, I get the **current log file only** (i.e. trace.log)
- when `maxArchiveFiles` is set to **2**, I get the current log file and **two** archived versions (i.e. trace.log, plus trace.0.log and trace.1.log)

Is this related to #1479 ?

By the way, i'm in favor with the proposal:
0 => zero archives
-1 => unlimited archiving

**Comment by 304NotModified** [comment]
> Is this related to #1479 ?

yes, it's the same issue. 

Maybe we should add an new option, to fix this before NLog 5.

**Comment by 304NotModified** [comment]
close in favor of #1479

**Comment by DmitryFromDubna** [comment]
**NLog version:** 4.7.2
**Platform version**: .Net Core 3.1

Hello, I am not sure the fix proposed in #1479 is going to address this issue. At the moment there is no way to keep one day of archived logs - it is either 0, 2 or greater. This is a stopper for our upgrade to .Net Core, because NLog 4.0.0.0 where this worked well does not support .Net Core.

Is there a way to keep exactly one archived daily log file? Thank you!

**Comment by snakefoot** [comment]
@DmitryFromDubna Better that you create your own issue, and present your unique `NLog.config`, and present your requirements. Instead of making comments on old issues, that have been closed long time ago.

**Comment by snakefoot** [comment]
NLog v6 changed its FileTarget default to `MaxArchiveFiles = -1` and when specifying `MaxArchiveFiles = 0` it means archive-rolling without backup. See also #5673

Notice the legacy [NLog.Target.ConcurrentFile](https://www.nuget.org/packages/NLog.Targets.ConcurrentFile) is the original NLog v5 FileTarget with unchanged behavior.,
