### ISSUE TITLE
InternalLog Targets ?

### ISSUE THREAD

**Issue by ClementHuart** [NLog/NLog#2777]
Hi everyone,

I wrote a program that log into a database.

I know there are logs written in a internal logfile if the database connection failed.
I would like to write these logs into a different target like a RichTextBox.

I short i'd like to know if the entry in the database is a succes or not and write it in my windows form.

Is it possible ? How can i do that?

Thank you 
Clément Huart

**Comment by snakefoot** [comment]
@ClementHuart You can hook into the NLog Internal Logger and redirect where you like. I recommend that you do not redirect into NLog Loggers, as it willl cause havoc.

`InternalLogger.LogWriter = new StringWriter();`

https://github.com/NLog/NLog/wiki/Internal-Logging

**Comment by ClementHuart** [comment]
@snakefoot 
Sorry about the delay

I do not really understand. Could you show me a simple exemple of Logging the internallog into a richtextbox ?

Thanks in advance

**Comment by ClementHuart** [comment]
Okay, thanks for your help and courtesy.

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, please let us know!
