### ISSUE TITLE
Which version of Nlog dll is compatiable with .Net Core 2.1 Class library Project

### ISSUE THREAD

**Issue by RJWIN1** [NLog/NLog#2779]
Which version of Nlog dll is compatiable with .Net Core 2.1 Class library Project

**Comment by snakefoot** [comment]
NLog 4.5 supports NetStandard2, which can be used by NetCore2.1 applications/libraries.

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, please let us know!
