### ISSUE TITLE
MaxMessageLength with FileTarget

### ISSUE THREAD

**Issue by t0pd3v1c3** [NLog/NLog#2782]
Hello.

EventLogTarget have:
http://nlog-project.org/documentation/v4.5.0/html/P_NLog_Targets_EventLogTarget_MaxMessageLength.htm

But FileTarget does not have such a property.

We use PostSnarp with NLog. With long error messages it doesn't write them to the log, we have to truncate it. How can I adjust the maximum length?

**NLog version**: 4.5.6

**Platform**: .Net 4.5

**Current NLog config**
```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="false"
      internalLogLevel="Off"
      internalLogFile="" >

  <targets>
    <!-- 
      https://github.com/nlog/NLog/wiki/Targets
      https://github.com/nlog/NLog/wiki/Layout-Renderers
    -->

    <target xsi:type="File" name="file" keepFileOpen="true" concurrentWrites="false" fileName="${basedir}/logs/${shortdate}.log" layout="${longdate} - ${uppercase:${level}} - ${message}" />
  </targets>

  <rules>
    <logger name="*" minlevel="Debug" writeTo="file" />
  </rules>
</nlog>
```

**Comment by snakefoot** [comment]
This very cryptic logic will truncate the log-message to 80 chars:

`${trim-whitespace:inner=${message:padding=-80:fixedLength=true}}`

Could probably be nice to a have truncate-layoutrenderer-wrapper.

**Comment by 304NotModified** [comment]
> Could probably be nice to a have truncate-layoutrenderer-wrapper.

PS was working on that, but unfortunately is stagnant, see #2194

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, please let us know!

**Comment by snakefoot** [comment]
NLog 4.6.3 has been released, that allows you to do this:

`${message:truncate=80}`

See also https://www.nuget.org/packages/NLog
