### ISSUE TITLE
Need to make long operation in thread

### ISSUE THREAD

**Issue by VladDodon** [NLog/NLog#2784]
I'm using XmlSerializer because I need to get object in text view. It takes long time for a big objects. For my logic I can't spend this time. 

I tried to use method "**public void Info(LogMessageGenerator messageFunc);**" 
example: 

> Logger.Info(new LogMessageGenerator(() => { return GetXML(obj, _hideParams); }));

As i looked in source code Action GetXML(obj, _hideParams) executed in this thread.

> public void Info(LogMessageGenerator messageFunc)
> {
>  if (IsInfoEnabled)
>  {
>   if (messageFunc == null)
>   {
>    throw new ArgumentNullException(nameof(messageFunc));
>   }
> 
>   WriteToTargets(LogLevel.Info, null, messageFunc());
>  }
> }

what you can advise me to do? Thanks.

**Comment by snakefoot** [comment]
You can schedule the logging on another thread, without waiting for it to complete. The easy way is just to do a `Task.Run`

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, please let us know!
