### ISSUE TITLE
Move System.Configuration into NLog.AppSettings package

### ISSUE THREAD

**Issue by snakefoot** [NLog/NLog#2787]
Remove dependency from NLog-core (And avoid issues like this: #2754)

`<Reference Include="System.Configuration" />`

With the help from #2676 and #2786 then most of the System.Configuration usage will be removed.

Then it is a matter of removing the last remains from `InternalLogger` + `XmlLoggingConfiguration`. See also #2624 (Making autoload of NLog-config from appsettings a nuget-package behavior).

**Comment by snakefoot** [comment]
Opposite suggestion to #2335

**Comment by 304NotModified** [comment]
of course we could create NLog.AppSettings before creating NLog 5.0

**Comment by snakefoot** [comment]
After seeing that NetFramework will now enter maintenance mode, and NetCore will take over.

Then it doesn't make sense trying extract app.config-logic from NLog-core, as it will only be available for NetFramework (And not NetCore).

Closing this issue, and instead created #3053

**Comment by snakefoot** [comment]
@304NotModified Also not for NLog 5.0, but is now included in NLog 4.6

**Comment by 304NotModified** [comment]
updated :)
