### ISSUE TITLE
default-target-parameters Source="${logger}"

### ISSUE THREAD

**Issue by marcusorchard** [NLog/NLog#279]
In my implementation I have multiple targets where the only difference is the source. I'd like to point all my Loggers at one target with the source being =${logger}. When I do this now, in the EventLog it shows the string version "${logger} instead of the actual logger name.

**Comment by 304NotModified** [comment]
@marcusorchard do you have an example config?

**Comment by 304NotModified** [comment]
We need more info, closing this issue. Feel free to reopen when the requested info is provided.

**Comment by ilya-g** [comment]
@304NotModified, seems like it's the same issue as #508 
Here the `EventLog` target doesn't render value specified in its `Source` parameter.

**Comment by 304NotModified** [comment]
@ilya-g I think your are right!

**Comment by 304NotModified** [comment]
Mark this one a duplicate. Of course this issue was before #508, but I was unclear IMO
