### ISSUE TITLE
Wrong filetarget archive date, yes once again :(

### ISSUE THREAD

**Issue by kirsan31** [NLog/NLog#2790]
**NLog version**: 4.5.4 and 4.5.6 tested

**Platform**: .Net 4.7.2

**Current NLog config** (xml)

```xml
    <target xsi:type="File" name="f"            
            fileName="${basedir}/logs/log.txt"            
            encoding="utf-8"
            concurrentWrites ="false"
            keepFileOpen="true"
            openFileCacheTimeout="30"
            layout="${time} ${uppercase:${level}} [${logger:shortName=false}]: ${message} ${exception:format=tostring}" 
            maxArchiveFiles = "31"
            archiveFileName="${basedir}/logs/log.{#}.txt"
            archiveNumbering="Date"
            archiveEvery="Day"
            archiveDateFormat="yyyy-MM-dd"
            >
    </target>

```
Today is 2018-06-27.
![image](https://user-images.githubusercontent.com/17767561/41974311-4aa60026-7a20-11e8-9b4e-19ad020c8a61.png)

- What is the current result?
log.2018-06-2**7**.txt
- What is the expected result?
log.2018-06-2**6**.txt

- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?  

> 2018-06-27 15:23:29.2310 Debug FileTarget(Name=f): Process file '...\bin\Debug\/logs/log.txt' on startup
> 2018-06-27 15:23:29.2620 Trace FileTarget(Name=f): Archive attempt for file '...\bin\Debug\/logs/log.txt'
> 2018-06-27 15:23:29.2620 Debug FileTarget(Name=f): Do archive file: '...\bin\Debug\/logs/log.txt'
> 2018-06-27 15:23:29.2620 Trace FileTarget(Name=f): Archive pattern '...\bin\Debug\/logs/log.{#}.txt'
> 2018-06-27 15:23:29.2770 Trace FileTarget(Name=f): Calculating archive date. File-LastModifiedUtc: **06/27/2018 12:23:29**; Previous LogEvent-TimeStamp: 01/01/0001 00:00:00
> 2018-06-27 15:23:29.2770 Trace FileTarget(Name=f): Using last write time
> 2018-06-27 15:23:29.2770 Info FileTarget(Name=f): Archiving ...\bin\Debug\logs\log.txt to ...\bin\Debug\logs\log.2018-06-27.txt
> 2018-06-27 15:23:29.2770 Debug FileTarget(Name=f): Move file from '...\bin\Debug\logs\log.txt' to '...\bin\Debug\logs\log.2018-06-27.txt'

Dunno where it takes 06/27/2018 12:23:29.
So, I think #2736 didn't fully solved this :( It's 100% reproducible if you change all 3 date attribute to yesterday.

- Is there a version in which it did work? 
Yes, in 4.**4**

**Comment by snakefoot** [comment]
@kirsan31 Cannot reproduce your case, when changing File-Times. Think you need to create a unit test (or test application) where you startup with the following:

```
                File.SetCreationTime("c:/logs/log.txt", DateTime.UtcNow.AddDays(-1));
                File.SetLastWriteTime("c:/logs/log.txt", DateTime.UtcNow.AddDays(-1));
                File.SetLastAccessTimeUtc("c:/logs/log.txt", DateTime.UtcNow.AddDays(-1));
```

Are you using any special timesource. Ex. `<time type="AccurateUTC" />` ?

**Comment by kirsan31** [comment]
@snakefoot 

> Are you using any special timesource. Ex. <time type="AccurateUTC" /> ?  

No, not any special. I notice, that our app start creating strange logs after updating nlog from 4.4 to 4.5. After investigation,  I found this behavior. And was able to reproduce it with changing File-Dates (I change it with TC - Total Commander).  I will try it with File.SetxxxTime...

**Comment by snakefoot** [comment]
@kirsan31 Not sure I understood your problem. But writing something to an old file, will archive the file using LastWriteTime before actually writing. So if writing a newline to an existing old file, then it will first archive and then write newline.

**Comment by kirsan31** [comment]
@snakefoot yea. I need to write an empty line to the log when app starts, to achieve this I used additional filetarget:
```xml
    <target xsi:type="File" name="nl"
        fileName="${basedir}/logs/log.txt"
        encoding="utf-8"
        concurrentWrites ="false"
        layout = ""
            >
    </target>  
```

and it's have no archiving setup - my bad :( It's very old style, now I plan switch to LayoutWithHeaderAndFooter...

When I removed call to _nl_ all work well. But if file log.2018-06-26.txt already exist, there another problem -  after start we will see: 
log.2018-06-26.txt _- old log + appended text from log.txt_
log.2018-06-27.txt _- first line of new log_
log.txt _- other lines of new log_

and need to be:
log.2018-06-26.txt _- old log + appended text from log.txt_
log.txt _- new log_

I will open new issue with details tomorrow...

**Comment by snakefoot** [comment]
@kirsan31 Sounds strange that you can have multiple files to the same day, when only doing archive-operation daily. Having multiple targets to the same file?

**Comment by snakefoot** [comment]
@kirsan31 Think the reason why NLog 4 worked before was that it always used the cached LastWrite-Timestamp for archive.

But lots of issues with archive have been seen when holding the file-handle open and doing archive (Especially when ConcurrentWrites = true). Now NLog 4.5 closes all filehandles and looks at the LastWrite-timestamp.

**Comment by snakefoot** [comment]
@kirsan31 It is a bug. The problem are these lines:

https://github.com/NLog/NLog/blob/49fdd08e17370fcc5b4f22e701eae710abe4ba54/src/NLog/Targets/FileTarget.cs#L1302-L1303

This causes the log-file to keep its creation-time, which means it must be archived. But because the last-write-time becomes today (because of the logevent after the first archive), then the next archive-operation generates a filename for today, instead of yesterday.

**Comment by kirsan31** [comment]
@snakefoot  Yea got it. 
Do you need any more actions from my side?

**Comment by snakefoot** [comment]
> @kirsan31 Do you need any more actions from my side?

No I just need to figure how to fix it :)

**Comment by snakefoot** [comment]
@kirsan31 Have now added a bonus commit to #2776 that fixes the issue together with a unit-test that reproduces your case.
