### ISSUE TITLE
Log4JXmlEventLayoutRenderer adds exception details twice

### ISSUE THREAD

**Issue by hakro-repo** [NLog/NLog#2791]
NLog version: 4.5.6
Platform: All

The `Log4JXmlEventLayoutRenderer` adds two `throwable` elements which makes the resulting XML invalid because the ![log4j DTD](https://github.com/apache/log4j/blob/7be00eed88152dd011a619e8bae5a631235c3f4c/src/main/resources/org/apache/log4j/xml/log4j.dtd#L206) only allows it once. The call to ![xtw.WriteElementSafeString()](https://github.com/NLog/NLog/blob/49fdd08e17370fcc5b4f22e701eae710abe4ba54/src/NLog/LayoutRenderers/Log4JXmlEventLayoutRenderer.cs#L271) should be removed in favor of ![AppendException()](https://github.com/NLog/NLog/blob/49fdd08e17370fcc5b4f22e701eae710abe4ba54/src/NLog/LayoutRenderers/Log4JXmlEventLayoutRenderer.cs#L276) because the latter adds the exception details as CDATA which preserves line breaks and makes stack traces much more readable.

**Comment by snakefoot** [comment]
Sounds like this #2672, but with an extra option to render Exception inside CDATA.

**Comment by hakro-repo** [comment]
You're right, I overlooked the other issue.

**Comment by 304NotModified** [comment]
Fixed in #2672
