### ISSUE TITLE
NLog throws exceptions in Visual Studio 2017

### ISSUE THREAD

**Issue by hedzerjan** [NLog/NLog#2794]
Hello, somehow NLog throws System.Web.HttpException when I execute the following code:
```
            logger = LogManager.GetCurrentClassLogger()
            logger.Info("Start")
```
The exception is thrown at the logger.Info line. If I, at that point, use the immediate window to request the value of LogManager.ThrowExceptions, I get "False".

If I run the solution in Visual Studio 2013, I have no problem. I've tried removing NLog and adding the latest version to no avail. Does anyone have a clue what I'm doing wrong or where I should continue looking?

**Comment by 304NotModified** [comment]
Hi, please follow; https://github.com/NLog/NLog/wiki/Logging-troubleshooting

**Comment by snakefoot** [comment]
@hedzerjan Can you give the full stacktrace of the exception? NLog should not be throwing any exceptions when `LogManager.ThrowExceptions = false`

**Comment by hedzerjan** [comment]
@snakefoot Sorry for the long wait, deadlines on other stuff :( Anyway, below is the callstack when the exception occurs. And to be more specific, it's not an unhandled exception: I don't need to handle it and the application will run just fine. However, it is shown in the debug output: Exception thrown: 'System.Web.HttpException' in System.Web.dll
Request is not available in this context

I can just ignore the exception but it still boggles me that it shows up in the new Visual Studio, whereas it didn't  before.

Call stack:
 	System.Web.dll!System.Web.HttpContext.Request.get()	Unknown
 	System.Web.dll!System.Web.HttpContextWrapper.Request.get()	Unknown
 	NLog.Web.dll!NLog.Web.Internal.RequestAccessor.TryGetRequest(System.Web.HttpContextBase context)	Unknown
 	NLog.Web.dll!NLog.Web.LayoutRenderers.AspNetRequestValueLayoutRenderer.DoAppend(System.Text.StringBuilder builder, NLog.LogEventInfo logEvent)	Unknown
 	NLog.Web.dll!NLog.Web.LayoutRenderers.AspNetLayoutRendererBase.Append(System.Text.StringBuilder builder, NLog.LogEventInfo logEvent)	Unknown
 	NLog.dll!NLog.LayoutRenderers.LayoutRenderer.RenderAppendBuilder(NLog.LogEventInfo logEvent, System.Text.StringBuilder builder)	Unknown
 	NLog.dll!NLog.Layouts.SimpleLayout.RenderAllRenderers(NLog.LogEventInfo logEvent, System.Text.StringBuilder target)	Unknown
 	NLog.dll!NLog.Layouts.SimpleLayout.RenderFormattedMessage(NLog.LogEventInfo logEvent, System.Text.StringBuilder target)	Unknown
 	NLog.dll!NLog.Layouts.Layout.RenderAllocateBuilder(NLog.LogEventInfo logEvent, System.Text.StringBuilder reusableBuilder, bool cacheLayoutResult)	Unknown
 	NLog.dll!NLog.Layouts.SimpleLayout.GetFormattedMessage(NLog.LogEventInfo logEvent)	Unknown
 	NLog.dll!NLog.Targets.DatabaseTarget.WriteEventToDatabase(NLog.LogEventInfo logEvent)	Unknown
 	NLog.dll!NLog.Targets.DatabaseTarget.Write(NLog.LogEventInfo logEvent)	Unknown
 	NLog.dll!NLog.Targets.Target.Write(NLog.Common.AsyncLogEventInfo logEvent)	Unknown
 	NLog.dll!NLog.Targets.Target.WriteAsyncThreadSafe(NLog.Common.AsyncLogEventInfo logEvent)	Unknown
 	NLog.dll!NLog.Targets.Target.WriteAsyncLogEvent(NLog.Common.AsyncLogEventInfo logEvent)	Unknown
 	NLog.dll!NLog.LoggerImpl.WriteToTargetWithFilterChain(NLog.Internal.TargetWithFilterChain targetListHead, NLog.LogEventInfo logEvent, NLog.Common.AsyncContinuation onException)	Unknown
 	NLog.dll!NLog.LoggerImpl.Write(System.Type loggerType, NLog.Internal.TargetWithFilterChain targets, NLog.LogEventInfo logEvent, NLog.LogFactory factory)	Unknown
 	NLog.dll!NLog.Logger.WriteToTargets(NLog.LogLevel level, System.IFormatProvider formatProvider, string message)	Unknown
 	NLog.dll!NLog.Logger.Info(string message)	Unknown
	**SynCubes.TriasWeb.dll!SynCubes.TriasWeb.Global_asax.Application_Start**(Object sender, System.EventArgs e) Line 65	Basic
 	[Native to Managed Transition]	
 	[Managed to Native Transition]	
 	System.Web.dll!System.Web.HttpApplication.InvokeMethodWithAssert(System.Reflection.MethodInfo method, int paramCount, object eventSource, System.EventArgs eventArgs)	Unknown
 	System.Web.dll!System.Web.HttpApplication.ProcessSpecialRequest(System.Web.HttpContext context, System.Reflection.MethodInfo method, int paramCount, object eventSource, System.EventArgs eventArgs, System.Web.SessionState.HttpSessionState session)	Unknown
 	System.Web.dll!System.Web.HttpApplicationFactory.EnsureAppStartCalledForIntegratedMode(System.Web.HttpContext context, System.Web.HttpApplication app)	Unknown
 	System.Web.dll!System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(System.IntPtr appContext, System.Web.HttpContext context, System.Reflection.MethodInfo[] handlers)	Unknown
 	System.Web.dll!System.Web.HttpApplication.InitSpecial(System.Web.HttpApplicationState state, System.Reflection.MethodInfo[] handlers, System.IntPtr appContext, System.Web.HttpContext context)	Unknown
 	System.Web.dll!System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(System.IntPtr appContext, System.Web.HttpContext context)	Unknown
 	System.Web.dll!System.Web.Hosting.PipelineRuntime.InitializeApplication(System.IntPtr appContext)	Unknown
 	[AppDomain Transition]

**Comment by snakefoot** [comment]
That is expected when doing logging during startup (no active request) and logging to a target that has a Layout that attempts to log request values.

To avoid these exceptions then use a custom named logger during startup where the logging rule for this logger, points to a target where layout does NOT attempt log request values



Sent from my Samsung device


-------- Original message --------

**Comment by hedzerjan** [comment]
Allright, thank you very much

**Comment by 304NotModified** [comment]
I'm glad is has been resolved 👍
