### ISSUE TITLE
Timezone for archived filename

### ISSUE THREAD

**Issue by krzychu195** [NLog/NLog#2795]
Hi, I have a log file with dateformat filename in UTC timezone, when I roll it is changing its timezone to local so I assume that is not based on the active file name. How can I force to roll it with UTC timezone as well?

**Comment by 304NotModified** [comment]
I think this isn't possible (yet).

**Comment by snakefoot** [comment]
Maybe a workaround is to change the NLog time-source to utc (`AccurateUTC`), and then fix the output to use local time where needed:

https://github.com/nlog/nlog/wiki/Time-Source

http://caraulean.com/2016/timestamp-accuracy-and-resolution-in-nlog/

**Comment by 304NotModified** [comment]
Good one!

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, please let us know!
