### ISSUE TITLE
target type="webService" url="${jsonEndpointAddress}" failed

### ISSUE THREAD

**Issue by papygourbi** [NLog/NLog#2796]
Hello
apparently, it's not possible to use a variable for the url of the webService. 
in the nlog log file i have the error : system.invalidOperatioException: This operation is not supported for a relative URI at system.Uri.get_absoluteUri()
if i put directly the address in litteral it's work fine.
as we will have different server for different environment it's a problem.

this is my Nlog.config, the variable to use is ${NeuronLogEndpoint}

?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      throwExceptions="false" 
      throwConfigExceptions="false"
      internalLogToConsole="false"
      internalLogFile="d:\temp\nlog.txt" 
      InternalLogLevel="Trace">

  <variable name="baselocation" value="${environment:variable=NLogBaseLocation}" />
  <variable name="environment" value="${environment:variable=NLogEnvironment}" />
  <variable name="NeuronLogEndpoint" value="${environment:variable=NeuronLogEndpoint}" />
  <variable name="appName" value="BankServices" />
  <variable name="logDirectory" value="${baselocation}/${environment}/${appName}/${shortdate}" />
  
  <targets async="true">
    <target xsi:type="File"
            name="default"
            layout="${longdate} - ${level:uppercase=true}: ${message}${onexception:${newline}EXCEPTION\: ${exception:format=ToString}}"
            fileName="${logDirectory}/Debug.log"
            archiveFileName="${logDirectory}/Debug_${shortdate}.{##}.log"
            archiveNumbering="Sequence"
            archiveEvery="Day"
            maxArchiveFiles="30"
            keepFileOpen="false"
            />
    <target xsi:type="File"
            name="errorFile"
            layout="${longdate} - ${level:uppercase=true}: ${message}${onexception:${newline}EXCEPTION\: ${exception:format=ToString}}"
            fileName="${logDirectory}/Error.log"
            archiveFileName="${logDirectory}/Error_${shortdate}.{##}.log"
            archiveNumbering="Sequence"
            archiveEvery="Day"
            maxArchiveFiles="30"
            keepFileOpen="false"
            />
    
      <target xsi:type="EventLog"
            name="eventlog"
            source="${appName}"
            layout="${message}${newline}${exception:format=ToString}"
            />
    <target name="AsyncWrapper" type="AsyncWrapper">
      <target type="RetryingWrapper">
        <target name="FallbackGroup" type="FallbackGroup" returnToFirstOnSuccess="true">
          <target type="WebService" name="NeuronLog" url="http://localhost:8081/api/v1/monitor/log" encoding="UTF-8" protocol="JsonPost">
            <parameter name="logGuid"  type="System.string" layout="${guid}"/>
            <parameter name="businessKey"  type="System.string" layout="${appName}"/>
            <parameter name="logLevel"  type="System.string" layout="${level}"/>
            <parameter name="logMessage"  type="System.string" layout="${message:format=ToString}"/>
            <parameter name="logEventTime"  type="System.DateTime" layout="${date:format=yyyy-MM-ddTHH\:mm\:ss.fff}"/>
            <parameter name="callStack"  type="System.string" layout="${message}${onexception:${newline}EXCEPTION\: ${exception:format=ToString}"/>
            <parameter name="entityClassMethod"  type="System.string" layout="${callsite}"/>
            <parameter name="httpMethod"  type="System.string" layout=""/>
            <parameter name="httpHeader"  type="System.string" layout=""/>
            <parameter name="entityName"  type="System.string" layout=""/>
            <parameter name="entityUri"  type="System.string" layout=""/>
            <parameter name="entityParams"  type="System.string" layout=""/>
            <parameter name="userId"  type="System.string" layout="${windows-identity}"/>
            <parameter name="tag"  type="System.string" layout="${machinename}"/>
          </target>
          <target xsi:type="File"
           name="errorFile"
           layout="${longdate} - ${level:uppercase=true}: ${message}${onexception:${newline}EXCEPTION\: ${exception:format=ToString}}"
           fileName="${logDirectory}/Error.log"
           archiveFileName="${logDirectory}/Error_${shortdate}.{##}.log"
           archiveNumbering="Sequence"
           archiveEvery="Day"
           maxArchiveFiles="30"
           keepFileOpen="false"
         />
        </target>
      </target>
    </target>
  </targets>
  <rules>
    
    
    
    <logger name="*" writeTo="AsyncWrapper" minlevel="Warn" />
    
  </rules>
  
</nlog>

this is the full error:
2018-07-06 15:20:17.6097 Error Error has been raised. Exception: System.InvalidOperationException: This operation is not supported for a relative URI.
   at System.Uri.get_AbsoluteUri()
   at System.Net.WebRequest.Create(Uri requestUri, Boolean useUriBase)
   at System.Net.WebRequest.Create(Uri requestUri)
   at NLog.Targets.WebServiceTarget.DoInvoke(Object[] parameters, AsyncLogEventInfo logEvent)
   at NLog.Targets.MethodCallTargetBase.Write(AsyncLogEventInfo logEvent)
   at NLog.Targets.Target.Write(IList`1 logEvents)
   at NLog.Targets.Target.WriteAsyncThreadSafe(IList`1 logEvents)
   at NLog.Targets.Target.WriteAsyncLogEvents(IList`1 logEvents)
2018-07-06 15:20:17.6097 Error AsyncWrapper(Name=NeuronLog): Error in lazy writer timer procedure. Exception: System.InvalidOperationException: This operation is not supported for a relative URI.
   at System.Uri.get_AbsoluteUri()
   at System.Net.WebRequest.Create(Uri requestUri, Boolean useUriBase)
   at System.Net.WebRequest.Create(Uri requestUri)
   at NLog.Targets.WebServiceTarget.DoInvoke(Object[] parameters, AsyncLogEventInfo logEvent)
   at NLog.Targets.MethodCallTargetBase.Write(AsyncLogEventInfo logEvent)
   at NLog.Targets.Target.Write(IList`1 logEvents)
   at NLog.Targets.Target.WriteAsyncThreadSafe(IList`1 logEvents)
   at NLog.Targets.Target.WriteAsyncLogEvents(IList`1 logEvents)
   at NLog.Targets.Wrappers.AsyncTargetWrapper.WriteEventsInQueue(Int32 batchSize, String reason)
   at NLog.Targets.Wrappers.AsyncTargetWrapper.ProcessPendingEvents(Object state)

best regards

**Comment by 304NotModified** [comment]
Currently layout renderers aren't supported in the URL of the webservicetarget.

**Comment by Bjego** [comment]
We also need that feature. Thanks for adding it to the roadmap.

**Comment by Bjego** [comment]
@papygourbi @304NotModified  I had the same issue.
Here is a workaround until V 5.0 is ready: https://github.com/NLog/NLog/wiki/WebService-target---Workaround-for-url-variables

**Comment by snakefoot** [comment]
Created  #4291 to resolve this issue.
