### ISSUE TITLE
Add UseNLog() extension to IHostBuilder

### ISSUE THREAD

**Issue by bryan5989** [NLog/NLog#2798]
net core generic host builder could use some love. With this, you can save the trouble of implementing the same tired service collection extension pattern. Maybe I'm just weird for building .net core console apps. 

**NLog version**: latest

**Platform**: .NET Core 2

**Current NLog config** (xml or C#, if relevant)

```xml
<?xml version="1.0" encoding="utf-8"?>

<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      throwConfigExceptions="true"
      internalLogFile="internal-nlog.log">

  <variable name="DefaultLayout"
            value="TID:${threadid} ${longdate} ${level:upperCase=true} ${logger} ${message} ${onexception:(${stacktrace:topFrames=10}) ${exception:format=ToString}}" />

  <targets async="true">
    <target name="debuglogfile" xsi:type="File" fileName="debug.log" layout="${DefaultLayout}" />
    <target name="normallogfile" xsi:type="File" fileName="log.log" layout="${DefaultLayout}" />
    <target name="logconsole" xsi:type="Console" layout="${DefaultLayout}" />
  </targets>

  <rules>
    <logger name="*" minlevel="Trace" writeTo="logconsole" />
    <logger name="*" minlevel="Debug" writeTo="debuglogfile" />
    <logger name="*" minlevel="Info" writeTo="normallogfile" />
  </rules>
</nlog>

```

**Comment by bryan5989** [comment]
Use this:

```csharp
    public static class Extensions
    {
        public static IHostBuilder UseNLog(this IHostBuilder builder)
        {
            if (builder == null) throw new ArgumentNullException(nameof(builder));

            builder.ConfigureServices(services =>
            {
                ConfigurationItemFactory.Default.RegisterItemsFromAssembly(
                    typeof(Extensions).GetTypeInfo().Assembly);

                LogManager.AddHiddenAssembly(typeof(Extensions).GetTypeInfo().Assembly);

                services.AddSingleton(new LoggerFactory().AddNLog(new NLogProviderOptions
                {
                    CaptureMessageTemplates = true,
                    CaptureMessageProperties = true
                }));
            });

            return builder;
        }
    }
```

Example Program:
```csharp
    internal class Program
    {
        public static async Task Main(string[] args)
        {
            var logger = NLog.LogManager.LoadConfiguration("nlog.config").GetCurrentClassLogger();

            try
            {
                var host = new HostBuilder()
                    //.ConfigureHostConfiguration(configHost => { })
                    .ConfigureAppConfiguration((hostContext, configApp) =>
                    {
                        configApp.AddJsonFile("Appsettings.json", optional: true);
                        //configApp.AddEnvironmentVariables();

                        if (args != null)
                        {
                            //configApp.AddCommandLine(args);
                        }
                    })
                    //.ConfigureServices((hostContext, services) => { })
                    .ConfigureLogging((hostContext, configLogging) =>
                    {
                        configLogging.ClearProviders();
                        configLogging.SetMinimumLevel(Microsoft.Extensions.Logging.LogLevel.Trace);
                    })
                    .UseNLog()
                    .UseConsoleLifetime()
                    .Build();

                await host.RunAsync();
            }
            catch (Exception ex)
            {
                // Catch setup errors
                logger.Error(ex, "Main execution failed, Exception");
                throw;
            }
            finally
            {
                // Avoid segmentation fault in linux
                NLog.LogManager.Shutdown();
            }
        }
    }
```

**Comment by 304NotModified** [comment]
Good idea.
 It should be added to https://github.com/NLog/NLog.Extensions.Logging

We have to check if this is consistent with the other UseNLog (in usage)

**Comment by bryan5989** [comment]
Are you referring to the use of reflection to get the assembly name? I may
just omit that. I copy pasted from a similar snippet for an implementation
of UseXXX() I don't remember what it was for originally, I just know it
works in an app i'm working on. I don't mind that it calls AddNLog()
internally, the point is to not have to see the boiler plate code when
setting up a simple app with a default setup for nlog using DI. netcore
patterns seem to be all moving towards DI and somewhere I read that the
netcore team is trying to abstract away all the non-http functionality from
IWebHostBuilder. Basically we end up with a generic host builder that works
for both console and web apps, and eventually IHost will be the base class
of IWebHost.

I was inspired by how netcore team is taking all the cookie cutter DI setup
that's common to most programs and hiding it with helper methods.

I will have to look carefully at the dependencies. IHostBuilder is very
new, requires Microsoft.Extensions.Hosting 2.1.0 and
Microsoft.Extensions.Logging 2.1.0 minimum. (there is 2.1.1 available for
both ATM)

The Console Example will need/should retarget netcoreapp2.1

This may only be compatible with .NET Standard 2.X and .NET Framework 4.6.1

I'm not sure how to get it to work for anything older, so i plan to
surround this code with:

```csharp
#if NETSTANDARD2_0 || NET461
```

Suggestions welcome.
I should have this ready tomorrow evening, I think. I didn't realize how
much of a pain it would be because of the dependencies.

PS I may need to rework your !NETCORE1_0 directives a little, unless you
think i should just forget about Net framework...

**Comment by bryan5989** [comment]
I've got most of the kinks worked out, but .AddSingleton is giving me
problems. the .ConfigureServices delegate is not liking being an Action
with a parameter.

I didn't make my self-imposed deadline, but I am away tomorrow, will be
back Sunday.

**Comment by bryan5989** [comment]
PR submitted: [#231](https://github.com/NLog/NLog.Extensions.Logging/pull/231)

**Comment by 304NotModified** [comment]
Closing this in favor of https://github.com/NLog/NLog.Extensions.Logging/issues/230
