### ISSUE TITLE
Qestion: OutputDebugString for Xamarin.Android and iOS

### ISSUE THREAD

**Issue by WebDucer** [NLog/NLog#2799]
Hello.

Is there a reason, why the target `OutputDebugString` is not included in the Android / iOS version of NLog?

I use the current version 4.5.6 and use it in my Xamarin.Forms applications. The `Debug.Write` as a underlying implementation of `OutputDebugString` works on all platforms (UWP, Android, iOS) I use.

**Comment by snakefoot** [comment]
Created PR for you #2792

**Comment by WebDucer** [comment]
@snakefoot Thanks. Hope to see the changes in the next version.

**Comment by 304NotModified** [comment]
Will be there in 4.5.7!

**Comment by snakefoot** [comment]
@WebDucer NLog 4.5.7 is released: https://www.nuget.org/packages/NLog/4.5.7
