### ISSUE TITLE
Multiple configuration files each with their own <nlog></nlog> sections 

### ISSUE THREAD

**Issue by ChaitanyaKN** [NLog/NLog#2800]
**NLog version 4.5.6**

**Platform**: .Net 3.5 / .Net 4.0 / .Net 4.5 

**Current NLog config** (xml or C#, if relevant)

**Feature Request**

The feature : In applications that are deployed in multiple environments. Consider the case where I have a Local version, a testing version and a Production version. In these kinds of scenarios usually people use different Configuration files that merge together to form one final configuration in the compiled version. 

As an example, consider 2 different config files i have in each environment:
- Local Environment: app.config(common to all 3 envs), envspecific,config.
- Testing Environment: app.config, envspecific.Testing.config
- Production environment: app.config, envspecific.Production.config.

Whenever i choose a environment(usually done via varying post-build events to merge the required config files): both files are merged, their configuration sections overwritten by the latter config and a single config appears.

Now since Nlog is not a Microsoft product, it seems i can only use a single nlog configuration section(`<nlog></nlog>`). If in the local environment i use it in app.config: envspecific.config will not allow another nlog section to be added. 

One of the scenarios in which this feature would be helpful is:
I have 3 targets: 2 filetargets by name "Infofile" and "Warningfile" and a console output of name "con"
Say i want a console output in my Local and testing versions, but not in my production version, so i could define rules for loggers to connect to the filetargets in the app.config, but i create another rules section in envspecific,config and envspecific.Testing.config which contains the routing to "con". 

I'm not sure if microsoft allows 3rd party libraries to implement such a thing, but it would be a very helpful feature if it exists.
System.Diagnostics.Trace has such a feature that allows configuration overwriting:
This feature in system.diagnostics is what i was suggesting :: 

my app.config:   

```xml
  <system.diagnostics>
 <sources>
       <source name="DefaultSource" switchValue="Information">
         <listeners>
           <add name="File"/>
           <add name="ErrorFile"/>
           <add name="WarningFile"/>
         </listeners>
       </source>
  </sources>
 </system.diagnostics>
```

my envspecific.config:

```xml
 <system.diagnostics>
     <sources>
       <source name="DefaultSource" switchValue="Verbose">
         <listeners>
           <add name="Console"/>
           <add name="File"/>
           <add name="ErrorFile" />
           <add name="WarningFile" />
         </listeners>
        </source>
       </sources>
 </system.diagnostics>
```

The 2nd configuration section overrwrites the app.config's similarly labelled section. So now only the 2nd configuration exists.

**Comment by 304NotModified** [comment]
can't you use nlog.config files and `<include`?

**Comment by ChaitanyaKN** [comment]
That's pretty much what i was looking for. I guess i can do with it. Thank you. 
It might be pretty obvious in the link you gave [https://github.com/NLog/NLog/wiki/Configuration-file#include-files] but an example like the one you mentioned in the comment is of great help in the configuration file wiki page.

**Comment by 304NotModified** [comment]
agree, will try to add a good example

**Comment by 304NotModified** [comment]
See here

https://github.com/NLog/NLog/wiki/XML-config-include-Example

**Comment by 304NotModified** [comment]
I think `<include>` covers this, so no need for more complexity.
