### ISSUE TITLE
'NLog' already has a dependency defined for 'NETStandard.Library'.

### ISSUE THREAD

**Issue by tdemichele** [NLog/NLog#2802]
Hello,

My Build server breaks on build of my solution with nlog installed. I had it working on a different project with the same setup but it complains about the .netstandard.library.

These are the packages I have installed. Can you tell me if one of those has a dependency or if there's a redirect rule I should use?

 ```xml
 <package id="AuthorizeNet" version="1.9.5" targetFramework="net45" />
  <package id="Microsoft.AspNet.WebApi" version="5.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.WebApi.Client" version="5.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.WebApi.Core" version="5.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.WebApi.WebHost" version="5.2.3" targetFramework="net45" />
  <package id="Newtonsoft.Json" version="6.0.4" targetFramework="net45" />
  <package id="NLog" version="4.5.6" targetFramework="net45" />
  <package id="NLog.Config" version="4.5.6" targetFramework="net45" />
  <package id="NLog.Schema" version="4.5.6" targetFramework="net45" />
```

Thanks in advance for your help.

**Comment by 304NotModified** [comment]
What's the full error message?

**Comment by tdemichele** [comment]
build	12-Jul-2018 16:15:47	Successfully installed 'Microsoft.AspNet.WebApi.WebHost 5.2.3'.
build	12-Jul-2018 16:15:47	WARNING: 'NLog' already has a dependency defined for 'NETStandard.Library'.

build	12-Jul-2018 16:15:49	Successfully installed 'WebGrease 1.5.2'.
error	12-Jul-2018 16:15:49	'NLog' already has a dependency defined for 'NETStandard.Library'.

so those would two would be my primary suspects.

I'm thinking maybe if i update to newer versions of things they'll play nice together but haven't had time to try it. It feels like NLOG should be able to stand on it's own without worrying what the other dlls are pulling though.

**Comment by tdemichele** [comment]
I upgraded the newtonsoft package to the latest 11 and webgrease to the latest but the build still failed on the server but with a new message.

The 'Newtonsoft.Json 11.0.2' package requires NuGet client version '2.12' or above, but the current NuGet version is '2.8.60717.93'.
'NLog' already has a dependency defined for 'NETStandard.Library'.

This made sense the build server was the problem. It had an old nuget executable so packages that should play nice together were breaking.

After I upgraded the nuget client exe on the build server the errors went away and the build succeeded.

**Comment by 304NotModified** [comment]
Thanks for the feedback! Glad it has been resolved!

**Comment by McPhale** [comment]
I'm having the same issue at my dev box (we're stuck on Visual Studio 2010 for now. I know, I know. We need to upgrade, but corporate's just very very slow to move).

If anyone else is in the same boat, you can run "Install-Package Nlog -Version 4.4.13" at the package manager console to get the latest version of Nlog that will work with 2010's old version of nuget. Not great but it will do in a pinch.

**Comment by shahnawazm786** [comment]
Hello,
when i creating a new Project of NUnit in Visual Studio 2013, I am getting following error.
![image](https://user-images.githubusercontent.com/49604292/99024829-6df01880-258d-11eb-9ea9-70a07746f395.png)
If any one have idea please let me know.
Thanks

**Comment by shahnawazm786** [comment]
> Hello,
> when i creating a new Project of NUnit in Visual Studio 2013, I am getting following error.
> ![image](https://user-images.githubusercontent.com/49604292/99024829-6df01880-258d-11eb-9ea9-70a07746f395.png)
> If any one have idea please let me know.
> Thanks

It has been resolved
I update the Nuget package and then installed the NUnit 
Thanks

**Comment by shahnawazm786** [comment]
> Hello,
> when i creating a new Project of NUnit in Visual Studio 2013, I am getting following error.
> ![image](https://user-images.githubusercontent.com/49604292/99024829-6df01880-258d-11eb-9ea9-70a07746f395.png)
> If any one have idea please let me know.
> Thanks

I resolved my self after updating nuget package.
Thanks
