### ISSUE TITLE
NLog.Logger Summary tooltip is confusing/misleading

### ISSUE THREAD

**Issue by elvishfiend** [NLog/NLog#2803]
**NLog version**: 4.5.4, probably earlier

**Platform**: .Net 4.5 

**Current NLog config** N/A

- What is the current result?
Summary Tooltip reads: "Logging methods which only are executed when the DEBUG conditional compilation symbol is set."
(Summary tag from NLog/Logger-Conditional.cs)
![image](https://user-images.githubusercontent.com/1051830/42672556-0b281ccc-86aa-11e8-8647-ec0ed2d57c6e.png)

- What is the expected result?
Summary Tooltip reads: "Provides logging interface and utility functions."
(Summary tag from NLog/Logger.cs)

This caused some confusion, as it gives the impression that logging is also dependent on the DEBUG compilation symbol, and not just the configuration.

The cause of the problem is that when you've got multiple Summary tags on a partial class, the behavior of which summary tag is shown is non-deterministic.
See: https://stackoverflow.com/questions/5984557/xml-commenting-on-partial-classes-methods

**Comment by elvishfiend** [comment]
Potential fix for this is to replace the <summary> tags in Logger-Conditional.cs with <content> tags.
This still documents the partial class, but won't overwrite the Logger.cs <summary> tag.

http://stylecop.soyuz5.com/SA1601.html

**Comment by 304NotModified** [comment]
Good catch! 

Could you please create a PR? Thanks!

**Comment by 304NotModified** [comment]
Created PR: #2807
