### ISSUE TITLE
DOES NOT WORK: By not specifying writeTo= then it act like a blackhole

### ISSUE THREAD

**Issue by mdebeus** [NLog/NLog#2805]
**NLog version**: 4.5.6

**Platform**: .NET Core 2.1

**Current NLog config** (xml or C#, if relevant)

Internally configured with the following code:
```
var loggerFactory = serviceProvider.GetRequiredService<ILoggerFactory>();
loggerFactory.AddNLog(new NLogProviderOptions { CaptureMessageTemplates = true, CaptureMessageProperties = true });
NLog.LogManager.LoadConfiguration("nlog.config");
```

My nlog.config file:
```xml
<nlog>
   <variable name="logDirectory" value="${basedir}/../../Logs/${shortdate}"/>
  <targets>
    <target xsi:type="File" name="TempLog" fileName="c:/temp/app-temp.log"
            layout="${date}|${level:uppercase=true}|${logger}|${message} ${exception}|${all-event-properties}" />
    <target xsi:type="File" name="DebugLog" fileName="${logDirectory}/app-debug.log"
            layout="${date}|${level:uppercase=true}||${logger}|${message} ${exception}|${all-event-properties}" />
    <!-- write logs to Console -->
    <target xsi:type="ColoredConsole" name="ConsoleTarget"
            layout="${level:uppercase=true}|${message} ${exception}|${logger}|${all-event-properties}" />  </targets>
  <rules>
    <logger name="Microsoft.*" minlevel="Info" final="true" />
    <logger name="*" minlevel="Trace" writeTo="TempLog,DebugLog,ConsoleTarget" />
  </rules>
</nlog>
```
I also tried:
1. Adding a Null black hole target and writing Microsoft.* stuff to that
2. Specifying the rule 
`<logger name="Microsoft.*" minlevel="Info" writeTo="" final="true" />`
Both 1) and 2) are described in https://stackoverflow.com/questions/50447166/nlog-netcore-turn-off-microsoft-info-level-logging

- What is the current result? 
Answer: My log is populated with Debug level logging for everything within the Microsoft name space. 
- What is the expected result? 
Answer: Entries with the Microsoft name space should not be present in the logs.
Example of a log entry in my log: 
2018/07/13 16:55:56.341|DEBUG|Microsoft.AspNetCore.Hosting.Internal.WebHost|Hosting started |EventId_Id=4, EventId_Name=, EventId=4

- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)? 
Answer: Yes.
- Please post full exception details (message, stacktrace, inner exceptions)
Answer: No exceptions occurred.
- Are there any workarounds? yes/no 
Answer: Not that I am aware of.
- Is there a version in which it did work?
Answer: I haven't tried any other versions.
- Can you help us by writing an unit test?
Answer: Maybe in the future - I'm really a git noob (although I have been a developer for a very long time)

**Comment by snakefoot** [comment]
You are doing it wrong. You have created a blackhole for Info-Level and above. 

You should do it like this;

```
<logger name="Microsoft.*" maxLevel="Info" final="true" /><!--Skip non-critical Microsoft logging -->
```
