### ISSUE TITLE
When target of type is Network,how to setting index of elastic?

### ISSUE THREAD

**Issue by moyuanhui** [NLog/NLog#2811]
The config of source code:
![image](https://user-images.githubusercontent.com/18112282/43068258-89e7bc1c-8e9c-11e8-9421-ce0c45daf84d.png)
Error message:
![image](https://user-images.githubusercontent.com/18112282/43068288-9ede94ec-8e9c-11e8-85f2-ff1c3ed74781.png)
elk Kibana  Index:
![image](https://user-images.githubusercontent.com/18112282/43068415-e98b9bf2-8e9c-11e8-969b-c50d30dcc2a6.png)

**Comment by snakefoot** [comment]
Think you should take this to the support forum of LogStash for how to setup Index.

The NLog Network Target has no direct support for configuration of index (As you have discovered yourself).

**Comment by 304NotModified** [comment]
> Think you should take this to the support forum of LogStash for how to setup Index.

Agree on this. We won't maintain Kibina/Logstash.

**Comment by moyuanhui** [comment]
OK, I have solved it. Thank you very much

**Comment by snakefoot** [comment]
Maybe share the solution you found? It might help others :)


Sent from my Samsung device


-------- Original message --------

**Comment by sujivisva** [comment]
Hi @moyuanhui ,

Could you please share your solution for enabling index for Elastic Search. I am trying the same for Splunk index

**Comment by snakefoot** [comment]
@sujivisva Different solutions for Splunk:
- https://github.com/NLog/NLog/wiki/Webservice-Target-for-Splunk
- https://github.com/DarekDan/NLog.Targets.HTTP#sample-splunk-configuration
- https://github.com/AlanBarber/NLog.Targets.Splunk/

**Comment by sujivisva** [comment]
Thanks for your response.

I am trying to do this

<target xsi:type="Network"
         name="Splunk"
         address="tcp://<splunk-address>:<splunk-port>"
         newLine="true"
         layout="${level}|${logger}|${message}|{exception:format=tostring}">
</target>

But with UDP protocol. However am not able to view any logs in splunk.

The problem is, I have a custom index created in splunk, not a default one.

How can I mention the index part in NLog network target?


Regards
Sujith Visvanathan

**Comment by snakefoot** [comment]
@sujivisva This place is mostly issue about NLog, and not so much about communication-protocols with random external-systems like Splunk or Elastic. Maybe try Splunk-support forum?

**Comment by sujivisva** [comment]
Hi @snakefoot ,

Thanks.!

This particular topic is about what I am trying to do exactly. And @moyuanhui has mentioned that he has solved the problem. Thats why trying to get his solution.
