### ISSUE TITLE
Mark WrapperLayoutRendererBuilderBase as obsolete

### ISSUE THREAD

**Issue by snakefoot** [NLog/NLog#2818]
WrapperLayoutRendererBuilderBase should be marked as obsolete as it doesn't give the best optimization.

The following WrapperLayoutRenderer should be changed to inherit from `WrapperLayoutRendererBase`:

- Rot13LayoutRendererWrapper 
- UppercaseLayoutRendererWrapper
- FileSystemNormalizeLayoutRendererWrapper 
- ReplaceNewLinesLayoutRendererWrapper
- WhenLayoutRendererWrapper
- JsonEncodeLayoutRendererWrapper
- WhenEmptyLayoutRendererWrapper
- TrimWhiteSpaceLayoutRendererWrapper
- LowercaseLayoutRendererWrapper

See also #2817 and #2743 that changes the above WrapperLayoutRenderer to no longer depend on StringBuilderPool-features from `WrapperLayoutRendererBuilderBase`.

Thinking NLog 5.0

And then removal of WrapperLayoutRendererBuilderBase in NLog 6.0

**Comment by 304NotModified** [comment]
marking could be in a minor version according to semver, so 4.6 is also fine by me

**Comment by snakefoot** [comment]
Was thinking the following:

- NLog 4.5.8 - Stop using features from WrapperLayoutRendererBuilderBase 
- NLog 4.5.8 / 4.6 - Mark methods on WrapperLayoutRendererBuilderBase  as obsolete
- NLog 5.0 - Remove all inheritance from WrapperLayoutRendererBuilderBase and mark the entire class as obsolete
- NLog 6.0 - Remove WrapperLayoutRendererBuilderBase completely.

**Comment by 304NotModified** [comment]
good proposal

> Mark methods on WrapperLayoutRendererBuilderBase as obsolete. See #2817

4.6 for this one please.

**Comment by snakefoot** [comment]
> @304NotModified 4.6 for this one please.

Removed obsolete attributes from #2817 and instead created #2836

**Comment by 304NotModified** [comment]
implemented by# 2836
