### ISSUE TITLE
Unable to log using EventLog target .NET Core 2.1

### ISSUE THREAD

**Issue by gingjonesy** [NLog/NLog#2828]
I'm trying to get my console application to log to the database, file, console and eventviewer. However everytime i had the eventviewer code it throws an exception. I added the NLog.WindowsEventLog nuget package but it still isnt working. The errors can be seen below and the full config image is attached:

2018-08-01 Error parsing layout all-event-properties will be ignored. Exception: LayoutRenderer cannot be found: 'all-event-properties' at NLog.Config.Factory

2018-08-01 Error Parsing configuration from C:\Users\user20\TestLogging\TestLogging\nlog.config failed. Exception: Exception when parsing C:\Users\user20\TestLogging\TestLogging\nlog.config. ---> Target cannot be found: 'EventLog' at NLog.Config.Factory

![capture](https://user-images.githubusercontent.com/41999959/43524392-1b64aa64-9597-11e8-8d04-98770cfa2c68.PNG)

**Comment by snakefoot** [comment]
@user2661305 Try remove everything from your NLog.config except the `EventLog`-target and a single logging-rule. Instead trying to fly on first attempt. Then work from there like all developers do.

Have you checked that internal logger whether it recognizes and loads the NLog.WindowsEventLog-assembly?

P.S. Still see that you have not removed the newline from the `logfile`-target.

**Comment by gingjonesy** [comment]
Sorry I had removed the new line yesterday when trying to get this to work and made other tweaks, when they didnt work i undone my changes and reverted it back to the original code. Thats why you still see the newline.

I've striped down the config and made it only to be what you have said but it still fires up an error saying _Target cannot be found: 'EventLog'_. I'm quite new with this so not really sure how to check that, I added NLog.WindowsEventLog using the nuget package manager. Is there anything else i need to do to get the application to pick up the dll and get it to work? Or should it work once you install the nuget and add the <extension> reference to NLog.WindowsEventLog? 

Yea looking at the logs it says the following, then it fails on the next line. I'll attach my log.
- 2018-08-02 09:23:49.5709 Info Loading assembly: NLog.WindowsEventLog

Thanks
[console-example-internal.log](https://github.com/NLog/NLog/files/2252738/console-example-internal.log)

**Comment by 304NotModified** [comment]
strange, it does "Loading assembly: NLog.WindowsEventLog"

but also reports:  "Target cannot be found: 'EventLog'"

**Comment by gingjonesy** [comment]
Yea I've been so confused trying to get this to work. Does it work fine with console apps in .NET Core 2.1? Or do i need to add something else in the program code to start up or reference the NLog.WindowsEventLog assembly?

**Comment by mathiasbl** [comment]
I'm currently dealing with the same problem. FYI

**Comment by mathiasbl** [comment]
Rather than excluding the EventLogTarget by conditional debug statements, isn't it better to check at runtime if we're running on windows?

```c#
 if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
 {}
```

**Comment by 304NotModified** [comment]
> Rather than excluding the EventLogTarget by conditional debug statements, isn't it better to check at runtime if we're running on windows?

yes, we don;t have conditional debug statements for Windows?

**Comment by 304NotModified** [comment]
I think I see the problem, working on it

**Comment by 304NotModified** [comment]
If you like a pre-release, it could be downloaded here: https://ci.appveyor.com/project/nlog/nlog/build/4.5.0-8021/artifacts

**Comment by 304NotModified** [comment]
PS: I'm thinking to re-version it to 1.0, any opinion on it? 

The package is now update every NLog release (so also if there are no changes), but i'm not sure if that is  confusing.

**Comment by snakefoot** [comment]
@304NotModified Well nothing wrong with https://www.nuget.org/packages/NLog.WindowsEventLog/4.5.6 . It is just the NLog 4.5.7 that is not working.

**Comment by gingjonesy** [comment]
@snakefoot @304NotModified I tried changing my nuget package to use the 4.5.6 and it works now. I'll keep an eye out for when the new version is released to nuget.

**Comment by mathiasbl** [comment]
When is 4.5.8 expected to release?

**Comment by 304NotModified** [comment]
this weekend

@snakefoot , @gingjonesy thx for feedback!

**Comment by 304NotModified** [comment]
4.5.8 is now live!
