### ISSUE TITLE
Setting configuration programatically is very slow. 

### ISSUE THREAD

**Issue by JCTirado** [NLog/NLog#2829]
**NLog version**: 4.4.12

**Platform**: .Net 4.5

**Current NLog config** (xml or C#, if relevant)

XML

![image](https://user-images.githubusercontent.com/31074467/43538210-9dd1cac2-957e-11e8-8c3f-1f75d2f7dd2f.png)

C#

        public static void CreateLoggers(List<string> strMembers, List<string> strTaskOrUsers)
        {
            string strVersion = GetVersion();
            var configLog = LogManager.Configuration;
            bool bSetConfiguration = false;

            var targets = configLog.AllTargets.Where(t => t.GetType() == typeof(AwsTarget)).ToList();
            if (targets.Any())
            {
                foreach (string strMember in strMembers)
                {
                    foreach (string strTaskOrUser in strTaskOrUsers)
                    {
                        bool bConfigChanged;
                        string strRuleName = GetLogger(strMember, strTaskOrUser, strVersion, configLog, targets, out bConfigChanged);
                        if (bConfigChanged)
                        {
                            bSetConfiguration = true;
                        }
                    }
                }
            }

            if (bSetConfiguration)
            {
                LogManager.Configuration = configLog;
            }
        }

        private static string GetLogger(string strMember, string strTaskOrUser, string strVersion, LoggingConfiguration configLog, List<Target> targets, out bool bConfigChanged)
        {
            bConfigChanged = false;

            string strTargetName = string.IsNullOrEmpty(strMember) ? $"AWSTarget.{strTaskOrUser}" : $"AWSTarget.{strMember}.{strTaskOrUser}";
            string strRuleName = string.IsNullOrEmpty(strMember) ? $"AWSLogger.{strTaskOrUser}" : $"AWSLogger.{strMember}.{strTaskOrUser}";
            string strPreffix = string.IsNullOrEmpty(strMember) ? $"{strVersion}/{strTaskOrUser}" : $"{strVersion}/{strMember}/{strTaskOrUser}";

            foreach (AwsTarget target in targets)
            {
                var target2 = (PatientNowAwsTarget)configLog.FindTargetByName(strTargetName);
                if (target2 == null)
                {
                    target2 = new PatientNowAwsTarget
                    {
                        Name = strTargetName,
                        Layout = target.Layout,
                        LogGroup = target.LogGroup,
                        Region = target.Region,
                        LogStreamNamePreffix = strPreffix,
                    };

                    configLog.AddTarget(target2);

                    var loggingRules = configLog.LoggingRules.Where(r => r.Targets.Contains(target)).ToList();
                    foreach (var loggingRule in loggingRules)
                    {
                        var loggingRule2 = new LoggingRule(strRuleName, GetMinLogLevel(loggingRule), target2)
                        {
                            Final = false,
                        };

                        configLog.LoggingRules.Add(loggingRule2);
                    };

                    bConfigChanged = true;
                }

                break;
            }

            return strRuleName;
        }

- What is the current result?

I am adding programatically 275 new targets and LogManager.Configuration = configLog; is taking more than 1 minute which is too long.

- What is the expected result?

It needs to be faster

**Comment by JCTirado** [comment]
It seems that removing these lines from nlog.config solved the problem:

throwExceptions="true" internalLogFile="${basedir}/internallog.txt" internalLogLevel="Trace"

Now is setting the configuration in less than a second.

**Comment by 304NotModified** [comment]
Thanks for the feedback!
