### ISSUE TITLE
Port ImpersonatingTargetWrapper to .NET Core/Standard (new package)

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#2832]
Port ImpersonatingTargetWrapper to .NET Core / .NET Standard

Needed: https://www.nuget.org/packages/System.Security.Principal.Windows/

New package. NLog.Windows?

**Comment by snakefoot** [comment]
Maybe just add it to `NLog.WindowsIdentity`:

https://www.nuget.org/packages/NLog.WindowsIdentity

**Comment by 304NotModified** [comment]
and then rename it to NLog.Windows ? ;)

**Comment by snakefoot** [comment]
Impersonating using a WindowsIdentity sounds very much like it belongs to NLog.WindowsIdentity (Without renaming to NLog.Windows).

**Comment by snakefoot** [comment]
Resolved by  #4275
