### ISSUE TITLE
Fix NLog.WindowsIdentity

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#2837]
See https://github.com/NLog/NLog/pull/2834#issuecomment-410184760

related #2834

**Comment by 304NotModified** [comment]
@snakefoot what about nlog.wcf? I think the same, so unlisted them also

**Comment by snakefoot** [comment]
@304NotModified NLog.Wcf doesn't have the same issue. It is using WCF_SUPPORTED

**Comment by 304NotModified** [comment]
thanks!
