### ISSUE TITLE
LoggerName partially overriden when using LogEvent

### ISSUE THREAD

**Issue by carlosinit** [NLog/NLog#2841]
Dear Nlog team,

I found the following issue while using Nlog with .NET core. 

Hope I gave enough information, it is my first :)

**NLog version**:  Include="NLog" Version="4.5.3"

**Platform**: .NET Core 2

**Current NLog config** (xml or C#, if relevant)

- What is the current result?

> I instantiate my logger using:
> var logger = LogManager.GetLogger("XXX")
> I log events using 
> var logEvent = new LogEventInfo(LogLevel.Info, "YYY", "some message");
> logger.Log(logEvent);
> 
> In the output file I see YYY in the log line as ${logger} but the rules of my Nlog.config only refer to XXX:
> <logger name="XXX" minlevel="Debug" writeTo="startup" final="true" />

- What is the expected result?

> I was expecting the LogEvent loggerName property to override even for the rules the name of the logger. And therefore use the following rule:
> <logger name="YYY" minlevel="Debug" writeTo="startup" final="true" />

- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?

> Yes did not find any interesting input that I could leverage.

- Please post full exception details (message, stacktrace, inner exceptions)

> N.A.

- Are there any workarounds? 

> No

- Is there a version in which it did work? 

> Didn't try

- Can you help us by writing an unit test?

> Of course if you point me to the right direction. Never did before :)

**Comment by 304NotModified** [comment]
is this #2766?

**Comment by 304NotModified** [comment]
Unfortunately this is a known issue, because of performance reasons.

> It is not intended to override the logging rules of the used logger. It would introduce too much overhead. 

see https://github.com/NLog/NLog/issues/2766#issuecomment-398147079

**Comment by carlosinit** [comment]
Indeed you it is related and I understood the performance reasons, but wouldn't it make sense then not to allow this override of logger name in the LogEvent class?

I have the feeling it would be less confusing but I don't know if users of Nlog leverage that partial override in their code.

**Comment by 304NotModified** [comment]
> but wouldn't it make sense then not to allow this override of logger name in the LogEvent class then?

Yes, but that would be a breaking change in the most important API of NLog :(

**Comment by carlosinit** [comment]
Fair enough. At least I know now.

**Comment by snakefoot** [comment]
Created #2917 so the Logger assigns `LogEventInfo.LoggerName` if uninitialized (null).
