### ISSUE TITLE
NLog working in VS/IIS-Express but not in IIS 6 or 10

### ISSUE THREAD

**Issue by Omortis** [NLog/NLog#2842]
Hello,

NLog 4.5.8
Visual Studio 2017
C# Targeting 4.6.1

I am using NLog in a webapi. When running in Visual Studio (IIS Express) the output is seen in the output file as expected. When I run it in IIS6/Win7 or IIS10/Win10 I see nothing. No output, no exceptions, nothing in the Event Viewer.

My config:

```xml
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      throwExceptions="true"
>

  <targets async="true">
    <target
      name="logfile"
      xsi:type="File"
      layout="${date}|${level:uppercase=true}${message}"
      fileName="C:\inetpub\wwwroot\myapp\App_Data\webapi.log"
    />
  </targets>

  <rules>
    <logger name="*" minlevel="Trace" writeTo="logfile" />
  </rules>
</nlog>
```

I am calling NLog via a static class:

```c#
  static class Logger
  {
      public static void Write(string caller, string message)
      {
          var logTime = DateTime.Now.ToString();

          var openSep = "\r\n===========================> myapp <========================================\r\n";
          var msgSep = "---------------------------> Message <-----------------------------------------\r\n";
          var closeSep = "===============================================================================\r\n";
          var debugString = openSep
                            + "Caller  -->  " + caller + "\r\n"
                            + "---------->  " + logTime + "\r\n"
                            + msgSep
                            + message + "\r\n"
                            + closeSep;
          var logger = LogManager.GetCurrentClassLogger();
          logger.Trace(debugString);
      }
  }
```
I have used the internal logging feature in NLog in VS to get my config correct and it all works fine. No output at all in IIS. Nothing anywhere. Even a crash or an unhandled exception would be lovely. If I set (in NLog.config) `fileName` to some location I can't write to, still no exceptions and nothing in the Event Log.

Suggestions? What am I missing?

Thanks,

John

**Comment by 304NotModified** [comment]
Please check the internal log when using in IIS

**Comment by Omortis** [comment]
If by the internal log you are referring to

```c#
            InternalLogger.LogFile = @"C:\NLog.txt";
            InternalLogger.LogLevel = LogLevel.Trace;
```

I have tried that. Nothing. Zilch. Nada. And no exceptions thrown. I have used NLog's internal logging in VS quite a bit to set things up. I would expect some sort of exception writing to a file in the root directory (as above).

**Comment by 304NotModified** [comment]
Please try writing to C:\temp instead of C:\

OR 

```
// enable internal logging to a custom TextWriter
    InternalLogger.LogWriter = new StringWriter();

```

**Comment by 304NotModified** [comment]
update, easier, and maybe the best way:

enable exception throwing from code:

```c#
LogManager.ThrowExceptions = true;
LogManager.ThrowConfigExceptions = true;
```

**Comment by Omortis** [comment]
Fixed. It took an act of God (Corporate IT) to make my permissions adjustments stick in the target location. I will close this, but why does 

```
      throwExceptions="true"
```

seem to have no effect at all?

**Comment by Omortis** [comment]
@304NotModified we are working on a way to accumulate data from these services. I have set it to `c:\temp` for now - thanks for the suggestion, I am relatively new to running custom services on Windows.
