### ISSUE TITLE
Writing to the ApplicationData folder with NLog Configuration API

### ISSUE THREAD

**Issue by gnichs** [NLog/NLog#2843]
**Original StackOverflow question**: https://stackoverflow.com/questions/51750682/writing-to-the-applicationdata-folder-with-nlog-configuration-api

**NLog version**: 4.5.8
**Platform**: .Net 4.7.2
**Current NLog config** (xml or C#, if relevant)
```c#
// Step 1. Create configuration object 
var config = new LoggingConfiguration();

// Step 2. Create targets
var infoFileTarget = new FileTarget("infoFileTarget")
{
    //FileName = "${basedir}/Program/File.Info.log", // works
    //FileName = "C:/Users/<USERNAME>/AppData/Roaming/Program/File.Info.log", // works
    FileName = "${specialfolder:ApplicationData}/Program/File.Info.log", // does not work
    Layout = @"${longdate}|${level:uppercase=true}|${callsite}|${logger:shortName=true}: ${message}",
    KeepFileOpen = false,
    ArchiveFileName = "${specialfolder:ApplicationData}/Program/Info_${shortdate}.{##}.log",
    ArchiveNumbering = ArchiveNumberingMode.Sequence,
    ArchiveEvery = FileArchivePeriod.Day,
    MaxArchiveFiles = 30,
};
config.AddTarget(infoFileTarget);

var errorFileTarget = new FileTarget("errorFileTarget")
{
    //FileName = "${basedir}/Program/File.Error.log", // works
    //FileName = "C:/Users/<USERNAME>/AppData/Roaming/Program/File.Error.log", // works
    FileName = "${specialfolder:ApplicationData}/Program/File.Error.log", // does not work
    Layout = @"${longdate}|${level:uppercase=true}|${callsite}|${logger:shortName=true}${newline}Message: ${message}${onexception:${newline}Exception\: ${exception:format=ToString}}${newline}",
    KeepFileOpen = false,
    ArchiveFileName = "${specialfolder:ApplicationData}/Program/Error_${shortdate}.{##}.log",
    ArchiveNumbering = ArchiveNumberingMode.Sequence,
    ArchiveEvery = FileArchivePeriod.Day,
    MaxArchiveFiles = 30
};
config.AddTarget(errorFileTarget);

// Step 3. Define rules
config.AddRuleForOneLevel(LogLevel.Info, infoFileTarget);
config.AddRuleForOneLevel(LogLevel.Error, errorFileTarget);

// Step 4. Activate the configuration
LogManager.Configuration = config;
```

- What is the current result? NLog does not log to the ApplicationData folder.
- What is the expected result? NLog should log to the ApplicationData folder.
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)? Yes, but there were no exceptions. Near the end of the internal log, it does look like NLog is trying to open the log files from the wrong ApplicationData folder though. See attached [interal.log](https://github.com/NLog/NLog/files/2275136/interal.log).
- Are there any workarounds? Not that I know of.
- Is there a version in which it did work? Not that I know of.
- Can you help us by writing an unit test? Yes, see attached [NLogUnitTest.zip](https://github.com/NLog/NLog/files/2275172/NLogUnitTest.zip). See the ReadME.txt inside the solution for installation instructions and notes about the project.

**Comment by 304NotModified** [comment]
Hi,

We are using `Environment.GetFolderPath`: https://docs.microsoft.com/en-us/dotnet/api/system.environment.getfolderpath?view=netcore-2.1#System_Environment_GetFolderPath_System_Environment_SpecialFolder_

Could you please try it in your environment and check the result?

Thanks for the complete bug/issue report 👍

**Comment by 304NotModified** [comment]
also what you can do, instead of file, log the `Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData)` to the file (the Layout). I have the idea it's in the wrong user folder

**Comment by gnichs** [comment]
Thanks for the reply. 

I did some more digging and it turns out that my issue is actually occurring because `Environment.SpecialFolder.ApplicationData` refers to a different location when referenced by a Windows Service running under the LocalSystem account and not due to a bug in NLog. The workaround for me was to choose to log to the `Environment.SpecialFolder.CommonApplicationData` folder as that location does not change when referenced by a Windows Service.

I'll go ahead and close the bug.

**Comment by 304NotModified** [comment]
Thanks for the feedback!
