### ISSUE TITLE
NuGet Package : Add `repository` metadata. 

### ISSUE THREAD

**Issue by MaximRouiller** [NLog/NLog#2852]
Basically, we can now add a repository metadata on a nuspec file to allow the repository to be surfaced on NuGet. This allows you to have a `projectUrl` as well a repository URL now.

I've talked about it [on Twitter](https://twitter.com/MaximRouiller/status/1030468873945075712) but the most basic things to know is here:

[NuSpec Reference](https://docs.microsoft.com/en-us/nuget/reference/nuspec?WT.mc_id=social-github-marouill#repository)

Reference Implementation in Json .NET
![image](https://user-images.githubusercontent.com/209384/44277447-b1c20f00-a218-11e8-9406-4f1f05879d47.png)

**Comment by 304NotModified** [comment]
excellent idea, will be fixed in #2853

Thx!

**Comment by MaximRouiller** [comment]
My pleasure! 😄

**Comment by 304NotModified** [comment]
PS it was already in the nlog package, but not in nlog.config and nlog.schema

![image](https://user-images.githubusercontent.com/5808377/44282135-59136600-a25a-11e8-8733-c083a2d71673.png)
