### ISSUE TITLE
MessageTemplate renders boolean with lowercase

### ISSUE THREAD

**Issue by snakefoot** [NLog/NLog#2854]
The following message-template:

`logger.Info("{alpha:l}{bravo}{charlie}", "aaa", 75.5, false);`

Renders the following:

> aaa75.5false

But should render this (Uppercase boolean).

> aaa75.5False

At least this is how Serilog does it :)

**Comment by 304NotModified** [comment]
this is indented behavior.

lowercase booleans are more JSON/XML like, and PascalCase is a toString in .NET (which is a bad choice IMO).

**Comment by snakefoot** [comment]
Fine with me. Just wanted to point out that NLog renders differently than Serilog (Which seems to be the official standard from MessageTemplates.org)

**Comment by snakefoot** [comment]
I would have expected that writing this would cause it to use JSON-style:

`logger.Info("{alpha:l}{bravo}{@charlie}", "aaa", 75.5, false);`

**Comment by 304NotModified** [comment]
unlike Serilog, we choice to have the default rendering more JSON alike. 

Thanks for pointing out
