### ISSUE TITLE
Race condition with multiple targets to same file together with keepFileOpen="true" concurrentWrites="false"

### ISSUE THREAD

**Issue by martinmine** [NLog/NLog#2866]
**NLog version**: 4.5.8

**Platform**: .Net 4.5 (net471)

**Current NLog config**

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="true"
      internalLogLevel="Off" internalLogFile="c:\temp\nlog-internal.log">

  <variable name="logDirectory" value="C:\Temp"/>
  <targets>
    <target xsi:type="File" name="FooTarget" fileName="${logDirectory}\test.log"
            layout="${message}"
            keepFileOpen="true" concurrentWrites="false" />
    <target xsi:type="File" name="BarTarget" fileName="${logDirectory}\test.log"
            layout="${message}"
            keepFileOpen="true" concurrentWrites="false" />
  </targets>
  <rules>
    <logger name="FooNamespace.*" minlevel="Trace" writeTo="FooTarget" />
    <logger name="BarNamespace.*" minlevel="Trace" writeTo="BarTarget" />
  </rules>
</nlog>
```

Sample program to reproduce (run this multiple times):

```CSharp
using BarNamespace;
using FooNamespace;
using NLog;

namespace NLogTesting
{
    class Program
    {
        static void Main()
        {
            Foo.Log();
            Bar.Log();
        }
    }
}

namespace FooNamespace
{
    public class Foo
    {
        public static void Log()
        {
            LogManager.GetCurrentClassLogger().Info("Foo logs");
        }
    }
}

namespace BarNamespace
{
    public class Bar
    {
        public static void Log()
        {
            LogManager.GetCurrentClassLogger().Info("Bar logs");
        }
    }
}

```

It is expected that the test.log-file contains both "Bar logs" and "Foo logs", however in some cases only one of them are present. Some times the program will log both entries. There is also a chance the program will throw an System.IO.FileLoadException ('The process cannot access the file because it is being used by another process. (Exception from HRESULT: 0x80070020)).

I expect NLog to be able to have multiple targets towards the same file as I may have a different format on one target compared to another. This does only happen with the flags `keepFileOpen="true" concurrentWrites="false"`, which is [recommended to be set in order to avoid extensive IO for logging](https://github.com/NLog/NLog/wiki/Performance).

**Comment by 304NotModified** [comment]
you're telling NLog you're not doing concurrentWrites, but you are as you have 2 times keepopen.

anyway, 2 times keepopen for the same file is not supported.

**Comment by snakefoot** [comment]
When you configure `keepFileOpen="true" concurrentWrites="false"`, then you promise NLog that only one target on the whole machine will write to the log-file. NLog will then skip all synchronization mechanisms and open the file for exclusive access (best performance).

When you suddenly break this promise and open two targets to the same file. Then it will give unexpected behavior.

If you need two individual file-targets writing to the same file, then you need to activate synchronization. Which means you should use `keepFileOpen="true" concurrentWrites="true"` (Also very good performance)

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, please let us know!
