### ISSUE TITLE
.NET 4.6 build

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#2867]
Needed for #2857

**Comment by snakefoot** [comment]
> Needed for #2857

It is more a "nice to have" / "should have" than a "must have".

**Comment by snakefoot** [comment]
Instead of net46, then it could be net472 or net48. They add support for portable-pdb, that reduces size of pdb-file to 0.2 MB (Instead of 2.5 MB)

Would be great if there was a netframework version that included the optimizations for concurrentqueue, that have been added to NetStandard2.0

**Comment by 304NotModified** [comment]
> Would be great if there was a netframework version that included the optimizations for concurrentqueue, that have been added to NetStandard2.0

Any Idea if this has implemented recently?

**Comment by snakefoot** [comment]
> Any Idea if this has implemented recently?

Nope apparently too difficult. At least not included for net48
