### ISSUE TITLE
Move public classes from internal namespace

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#2870]
Some classes are public, but in the internal namespace

**Comment by snakefoot** [comment]
Guess it means duplicate classes. One obsolete as public, and new internal non-obsolete. Going to be confusing :)

**Comment by 304NotModified** [comment]
I don't think we need here obsolete attributes, as in general it's always not advised to use classes meant to be internal (so .Internal namespace or .Private etc).

**Comment by snakefoot** [comment]
Happy we are back to grey in grey and not black and white :)

**Comment by snakefoot** [comment]
Almost resolved by #4331 . Just need to figure out what to do about IAppDomain.

**Comment by snakefoot** [comment]
Have created  #4433 to mark `LogFactory.CurrentAppDomain` as obsolete

**Comment by snakefoot** [comment]
Closing issue as resolved by #4331. And now IAppDomain has become obsolete, and will be part of normal cleanup. See also #4433
