### ISSUE TITLE
Drop Silverlight and WinPhone8 support

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#2871]

**Comment by snakefoot** [comment]
Silvelight ver. 5 has end-of-life support until 10/12/2021:

https://support.microsoft.com/en-us/lifecycle/search/12905

Also the code cleanup will not be that impressive until Xamarin iOS and Xamarin Android start using NetStandard (Then the code cleanup will be real).

**Comment by 304NotModified** [comment]
> Silvelight ver. 5 has end-of-life support until 10/12/2021:
> 
> https://support.microsoft.com/en-us/lifecycle/search/12905
> 
> Windows Phone 8.1 has end-of-life support until July 1, 2023. But yes new WP8 Apps will not be accepted in Windows Store after 31 Oct. 2018

Thanks for the details!



> Don't hope NLog 5 is first in 3-5 years.

What do you mean with that?



> Also the code cleanup will not be that impressive until Xamarin iOS and Xamarin Android start using NetStandard (When those are also removed, then the code cleanup will be real).

True, but it also saves build time. For me the build time is too long (also because of the unstable tests).

**Comment by snakefoot** [comment]
It takes 10 secs to build and package. So I don't think you will see much improvement there



Sent from my Samsung device


-------- Original message --------

**Comment by snakefoot** [comment]
Starting to convince myself that we should remove Silverlight + Xamerin platforms with Nlog ver 5.0 (Maybe also remove ne40), and instead introduce net472 with NLog 5.0

**Comment by snakefoot** [comment]
Another reason to drop Xamarin, Silverlight, etc.:

#3703

But we should make sure to use ConcurrentWrites=false by default, since Mutex-usages is not welcome on those platforms. See also #3048 + #2742

**Comment by 304NotModified** [comment]
:+1:
