### ISSUE TITLE
Question: what is the difference between AsyncTaskTarget and AsyncWrapper Target?

### ISSUE THREAD

**Issue by Hussein-Dahir** [NLog/NLog#2872]
What is the difference between [AsyncTaskTarget ](http://nlog-project.org/documentation/v4.5.0/html/T_NLog_Targets_AsyncTaskTarget.htm) and [AsyncWrapper](https://github.com/nlog/NLog/wiki/AsyncWrapper-target)?

which is better?

I have seen that AsyncWrapper has more config options (like **queueLimit**, **overflowAction** & more) which is important for me (I don't want logs to get discarded, even if more than 10000 logs buffered, I am working on a website for some big company).

So, is that the only difference?

why then we even have something like AsyncTaskTarget?

Moreover, what happens if I combined both AsyncTaskTarget & AsyncWrapper with something like this:

`CustomTargetExtendingAsyncTaskTarget  customTarget = CustomTargetExtendingAsyncTaskTarget();
AsyncTargetWrapper asyncTargetWrapper = new AsyncTargetWrapper(customTarget, 100000, AsyncTargetWrapperOverflowAction.Grow);`

is this a bad idea?

**Comment by snakefoot** [comment]
`AsyncTaskTarget` is a base-class just like `TargetWithLayout` for creating your own custom Target. It makes it easier to make one chain of tasks with timeout-handling.

`AsyncWrapper` is a helper class for non-async targets that schedules the writing on a timer-thread.

**Comment by snakefoot** [comment]
Using `AsyncWrapper` around a target that inherits from `AsyncTaskTarget` doesn't make much sense, besides a adding some overhead.

**Comment by Hussein-Dahir** [comment]
@snakefoot

Thank you very much !

**Comment by Hussein-Dahir** [comment]
@snakefoot

I think your words should be added as documentation 😛, especially that AsyncTaskTarget doesn't have one in the wiki (which made me ask you about it).

Thanks

**Comment by 304NotModified** [comment]
> especially that AsyncTaskTarget doesn't have one in the wiki

FYI, there is: http://nlog-project.org/documentation/v4.5.0/html/T_NLog_Targets_AsyncTaskTarget.htm

**Comment by snakefoot** [comment]
@Hussein-Dahir Most users of NLog doesn't write their own targets. The Wiki is mostly helping people how to configure the ready-to-use NLog-components.

The AsyncTaskTarget is as the documentation says "**Abstract** Target with async Task support".

**Comment by Hussein-Dahir** [comment]
@snakefoot yes you are right, even I started using the ready-to-use DatabaseTarget at first.

But at some point later, I had to make custom one to use EF Core and use AsyncTaskTarget to support Async usage, which took some time from me to explore the API Docs & found out AsyncTaskTarget and how to use it, that's why I thought wiki docs can be useful :P

Anyway, this is really a great work, and NLog is an excellent logger that I really liked, keep going guys ;)

Thanks !

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, please let us know!

**Comment by snakefoot** [comment]
@Hussein-Dahir Any input for this wiki-page about AsyncTaskTarget: https://github.com/NLog/NLog/wiki/How-to-write-a-custom-async-target

**Comment by Hussein-Dahir** [comment]
@snakefoot your docs is good, thanks for adding them.

Anyway, change `WriteAsyncTask(LogEventInfo logEvent, LogEventInfo logEvent, CancellationToken token)` to `WriteAsyncTask(LogEventInfo logEvent, CancellationToken token)`, you repeated that by mistake.


You may add this info, I really found it useful:
> `AsyncTaskTarget` has an internal queue the grows to infinity (Initial capacity is 10000), so if the Tasks constantly performs timeout then at one point it will have eaten all memory. LogEvents are only lost if the Task completes in failure.

For `this.RenderLogEvent(this.Layout, logEvent)` and `this.GetAllProperties(logEvent)`, I never tried them, but I will soon.

Currently, I am using `string jsonData = Layout.Render(logEventInfo);`, alongside with a JSON Layout and JSON Parser (I think your method would spare me the JSON Parser, if it is rendering all layout-renderers).

Thanks,

**Comment by snakefoot** [comment]
> AsyncTaskTarget has an internal queue the grows to infinity (Initial capacity is 10000)

NLog 4.6 changes this behavior by introducing an `OverflowAction` that defaults to `Discard`. So it will not eat all memory by default.

**Comment by snakefoot** [comment]
>  you repeated that by mistake.

Thank you for spotting it. Have now been fixed.

**Comment by issafram** [comment]
@snakefoot @304NotModified @Hussein-Dahir 
So I'm currently creating a new target where logs should be sent to an API using HTTP.
I'm thinking that I would want to **Async** send those post requests.

Would it be recommended to inherit from `TargetWithContext` or the `AsyncTaskTarget`?
I'd appreciate a response as I'm a bit confused.

**Comment by snakefoot** [comment]
If you want to support batching in an async way then I suggest using AsyncTaskTarget

**Comment by issafram** [comment]
@snakefoot I've started to implement my target and AsyncTaskTarget has [many different methods](https://nlog-project.org/documentation/v4.5.0/html/T_NLog_Targets_AsyncTaskTarget.htm) that can be implemented.  I'm not sure which ones would be useful/required. 

Do you by chance know what should be used?  I know there is comments on the methods but it isn't quite clear to me.  Thanks for the help.

**Comment by 304NotModified** [comment]
Good questions, I think it's nice if we could improve the docs on this.

**Comment by snakefoot** [comment]
There is a guide. You are welcome to improve it:


https://github.com/NLog/NLog/wiki/How-to-write-a-custom-async-target


Sent from my Sony Xperia


---- Issa Fram wrote ----


@snakefoot<https://github.com/snakefoot> I've started to implement my target and AsyncTaskTarget has many different methods<https://nlog-project.org/documentation/v4.5.0/html/T_NLog_Targets_AsyncTaskTarget.htm> that can be implemented. I'm not sure which ones would be useful/required.

Do you by chance know what should be used? I know there is comments on the methods but it isn't quite clear to me. Thanks for the help.
