### ISSUE TITLE
Excuse me, Please help me change the layout renderer details of NLog.Appsetting.Standard

### ISSUE THREAD

**Issue by linmasaki** [NLog/NLog#2879]
Hello! I'm the NLog.Appsetting.Standard package's author, Thank you for listing my package on the [page](https://nlog-project.org/config/?tab=layout-renderers). But today I modified the package name for some reason, so please help me update the introduction:

 **${appsetting} - ${appsetting} for .NET Standard and appsettings.json config files NLog.Appsetting.Standard External**  to 
**${appsettings} - ${appsettings} for .NET Standard and appsettings.json config files NLog.Appsettings.Standard External** 

Then nuget's url would be [https://www.nuget.org/packages/NLog.Appsettings.Standard](https://www.nuget.org/packages/NLog.Appsettings.Standard), and project's url would be [https://github.com/linmasaki/NLog.Appsettings.Standard](https://github.com/linmasaki/NLog.Appsettings.Standard). I am sorry if this has caused you any inconvenience.

**Comment by 304NotModified** [comment]
Hi,

you can change it on this repo: https://github.com/NLog/NLog.github.io

see readme:

![image](https://user-images.githubusercontent.com/5808377/44782809-c42d3880-ab88-11e8-8d64-04cec9d40582.png)

So please send a PR for https://github.com/NLog/NLog.github.io/blob/master/config/layout-renderers.json, thanks!

**Comment by linmasaki** [comment]
Ok, thank you for your kind response. I will do it right now!

**Comment by 304NotModified** [comment]
fixed by https://github.com/NLog/NLog.github.io/pull/70
