### ISSUE TITLE
AsyncWrapper without name attribute won't work

### ISSUE THREAD

**Issue by tryhp3** [NLog/NLog#288]
My config file is:

![image](https://f.cloud.github.com/assets/4246990/1809135/cb821a92-6db2-11e3-8e5d-290f62832302.png)

above no work for PostgreSql (logs are not inserted into the database), but for File solution works. When I remove target AsyncWrapper then works for PgSql.

**Comment by 304NotModified** [comment]
@Xharze I was under the impression I understood this issue.

But I don't fully understand 
>I added name="" for all target node

Do you?

**Comment by 304NotModified** [comment]
Thanks @tryhp3 !

**Comment by 304NotModified** [comment]
invalid as we have not fixed this in this release (for the logs)

**Comment by 304NotModified** [comment]
Working in 4.0. removing milestone
