### ISSUE TITLE
LogEventInfo.LoggerName is not respected by rules for logger names

### ISSUE THREAD

**Issue by jackhorton** [NLog/NLog#2887]
**NLog version**: 4.5.9

**Platform**: .NET Core 2

**Current NLog config** (xml or C#, if relevant)

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      throwExceptions="true"
      throwConfigExceptions="true">
    <targets>
        <target xsi:type="Console" name="ConsoleTarget" layout="[${threadid}][${logger}][${date} ${level:uppercase=true}] ${message}" />
        <target xsi:type="Console" name="ConsoleJsonTarget">
            <layout type="JsonLayout">
                <attribute name="time" layout="${longdate}" />
                <attribute name="level" layout="${level}" />
                <attribute name="message" layout="${message}" />
                <attribute name="loggerName" layout="${logger}" />
                <attribute name="eventProperties" encode="false" >
                    <layout type='JsonLayout' includeAllProperties="true"  maxRecursionLimit="2"/>
                </attribute>
            </layout>
        </target>
    </targets>

    <rules>
        <logger name="*" writeTo="ConsoleTarget" />
        <logger name="ActionRecorder" writeTo="ConsoleJsonTarget" />
    </rules>
</nlog>
```

Code that I _think_ should trigger the ActionRecorder rule:
```C#
static Logger _logger = LogManager.GetCurrentClassLogger(); // Current class is like TestProject.TestClass, NOT ActionRecorder
…
_logger.Log(new LogEventInfo
{
    …
    LoggerName = "ActionRecorder"
}
```

- What is the current result? Name filters on logging rules only respect the name of logger object, not the name of a single logged message
- What is the expected result? I am new to NLog so perhaps this is an incorrect expectation, but since messages logged with `_logger.Log(LogEventInfo)` have `${logger} == LogEventInfo.LoggerName`, I expected that the logger name set in the message would also impact the rule.
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)? Yes -- it looks like rule resolution is done at logger initialization while ${logger} is done lazily?
- Please post full exception details (message, stacktrace, inner exceptions): N/A
- Are there any workarounds? yes: create a separate logger object for the logger name in question.
- Is there a version in which it did work? Unknown
- Can you help us by writing an unit test? Possibly? Depends on if this is even a real bug.

**Comment by 304NotModified** [comment]
is this #2841?

**Comment by jackhorton** [comment]
It is, my bad! Don't remember those coming up in my search for "rule name" before posting this.

Thanks for the quick response!

**Comment by snakefoot** [comment]
Created #2917 so the Logger assigns LogEventInfo.LoggerName if uninitialized (null).
