### ISSUE TITLE
EventLog target to support SuccessAudit and FailureAudit events

### ISSUE THREAD

**Issue by MNF** [NLog/NLog#289]
Currently EventLog target translates `logEvent.Level` into `EventLogEntryType.Error`,`.Warning` or `.Information`. 

It will be good to have new entryType configuration parameter that will allow to specify `SuccessAudit` and `FailureAudit` events
 (reference http://msdn.microsoft.com/en-us/library/system.diagnostics.eventlogentrytype(v=vs.110).aspx)

**Comment by 304NotModified** [comment]
@MNF I would like to look at this. Any ideas how to configure this feature?

**Comment by 304NotModified** [comment]
https://github.com/304NotModified/NLog/commit/d1bab0a9dca2cfafd7ac437f8940c64dd0d19cc1
