### ISSUE TITLE
Question: multiple applications logging to the same db table

### ISSUE THREAD

**Issue by SylvainNZ** [NLog/NLog#2894]
Hi there,

I have multiple multiple bits of my website generating logs with NLog:
a web application, a webhook receiver and a windows service.

Is it ok to make them point to the same database table ? 
They will login using the same windows account to SQL server.
I am affraid of failures in case they try to insert at the same time.

They don't produce a lot of logs so the performance is not an issue.

Thanks

**Comment by 304NotModified** [comment]
Yes that's possible. At my work we have +20 applicaties logging to the same table. 


It depends of course of you DB structure, indexes, DB system and applications, but you could consider to:


- async write
- and/or don't create to much indexes for insert performance

FYI, we have 350.000 logs in our production log DB (we clean it automatically) without any problems

**Comment by SylvainNZ** [comment]
Thanks for the reply that's useful !
I will go for this solution then.
