### ISSUE TITLE
Use Layout Render to compose Variable name

### ISSUE THREAD

**Issue by pedrofernandesfilho** [NLog/NLog#2898]
Hi! 

Is possible to use Layout Render (${level}) to compose a variable name used in target.layout?

**NLog version**: 4.5.9

**Platform**: .Net 4.7.2

**Current NLog config**

```xml
<nlog>
  <variable name="LayoutDefault" value="D - ${longdate} | ${message}"/>
  <variable name="LaytouInfo" value="${longdate} | ${message}"/>
  <variable name="LaytouWarn" value="${longdate} ${newline} ${message}"/>
  <targets>
  <target name="logFile" xsi:type ="File"
            archiveEvery="Day" maxArchiveFiles="15"
            fileName="Logs\${level}\log${level}-${shortdate}.txt"
            layout="${var:Layout${level}}" />
  </targets>
  <rules>
    <logger name="*" writeTo="logFile" />
  </rules>
</nlog>
```

 - Why do we need it?
practicality

**Comment by 304NotModified** [comment]
that won't work, but this will:

- nest multiple `${when}` (bit clumsy probably). See https://github.com/NLog/NLog/wiki/When-Layout-Renderer
- write a custom layout renderer, that writes renders the layouts default/info/warn: see https://github.com/NLog/NLog/wiki/How-to-write-a-custom-layout-renderer  
- write a custom layout renderer that reads the variables depending on the level.

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, please let us know!

**Comment by pedrofernandesfilho** [comment]
Sorry for the delay in answering.
You helped me. I used custom layout render.
Thank you!

**Comment by FixRM** [comment]
Hi @pedrofernandesfilho! How did you do this? I'm trying to solve similar issue: I need to map Elastic Seach index with ASP environment variable value:

C#
```
    [LayoutRenderer("elk-environment-index")]
    public class EnvironmentNameLayoutRender : LayoutRenderer
    {
        [DefaultParameter]
        [RequiredParameter]
        public string? AspNetEnvironmentName { get; set; }


        protected override void Append(StringBuilder builder, LogEventInfo logEvent)
        {
            var name = AspNetEnvironmentName switch 
            {
                "development" => "debug",
                "staging" => "test",
                "production" => "prod",
                _ => AspNetEnvironmentName
            };

            builder.Append(name);
        }
    }
```
My config:
XML
```
<variable name="asp_environment" value="${environment:variable=ASPNETCORE_ENVIRONMENT}" />
***
layout="my render: ${elk-environment-index:${asp_environment}}">
```
But I got the following output:
`my render: ${environment:variable=ASPNETCORE_ENVIRONMENT}`

**Comment by snakefoot** [comment]
@FixRM Instead of waking up old issues, then please create new issue (maybe with reference to old issue), or post your question at StackOverflow.com

**Comment by FixRM** [comment]
Thank you, @snakefoot. Done: https://stackoverflow.com/questions/79676566/custom-nlog-layout-render-with-support-of-inner-layout
