### ISSUE TITLE
nlog.dll.nlog is not correctly resolved if hosted on UNC path [regression bug]

### ISSUE THREAD

**Issue by Xharze** [NLog/NLog#29]
> `GetCandidateFileNames` returns AbsolutPath instead of LocalPath in Ln 671.

> That causes nlog.dll.nlog hosted on UNC path not to be resolved.

It retruns:

```
/Share/nlog.dll.nlog
```

instead of:

```
\\Server\Share\nlog.dll.nlog
```
Moved from http://nlog.codeplex.com/workitem/7043

**Comment by 304NotModified** [comment]
not sure where to fix this

**Comment by 304NotModified** [comment]
This seems to be solved before, but broken again in 4.0.1

See
https://github.com/NLog/NLog/commit/9032367cdf88d66a345d49c8f3fdcf00b820233e#commitcomment-11797254

and https://github.com/Mike120Git/NLog/pull/1

**Comment by 304NotModified** [comment]
Raising to must have as the solution is almost clear.

**Comment by 304NotModified** [comment]
needs unit tests, if possible

**Comment by 304NotModified** [comment]
PR merged
