### ISSUE TITLE
LogManager.GetCurrentClassLogger() returns logger with incorrect name when code is inlined

### ISSUE THREAD

**Issue by plabanauskis** [NLog/NLog#2900]
`LogManager.GetCurrentClassLogger()` uses `StackTraceUsageUtils.GetClassFullName()` which simply takes the class name 2 levels deep from the stack trace.

When the program is compiled using Release configuration, the JIT compiler might inline some code. This causes invalid class name to be received from the StackTrace.

**NLog version**: 4.5.9

**Platform**: .NET 4.7.1, .NET Core 2.1 (probably others, too)

**Current NLog config with code to reproduce the issue**

```csharp
using NLog;
using NLog.Config;
using NLog.Targets;
using System.Runtime.CompilerServices;

namespace ConsoleApp
{
    class Program
    {
        static void Main()
        {
            var config = new LoggingConfiguration();
            var consoleTarget = new ConsoleTarget("console");
            config.AddTarget(consoleTarget);
            config.AddRuleForOneLevel(LogLevel.Debug, consoleTarget);
            LogManager.Configuration = config;

            new Test();
        }
    }

    class Test
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Test()
        {
            var logger = LogManager.GetCurrentClassLogger();
            logger.Debug(logger.Name);
        }
    }
}

```

- What is the current result?
The logger output is as follows:
`2018-09-05 10:47:55.6422|DEBUG|ConsoleApp14.Program|ConsoleApp14.Program`

- What is the expected result?
`2018-09-05 10:47:55.6422|DEBUG|ConsoleApp14.Program|ConsoleApp14.Test`

- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
No.
- Are there any workarounds? yes/no
Yes. The expected output can be seen after changing `AggressiveInlining` with `NoInlining`.

- Is there a version in which it did work? 
The lowest version I checked with was 4.5.0. It didn't work either.

- Suggested solution
Remove `GetCurrentClassLogger` implementation entirely as it probably cannot work reliably with the way JIT works. Instead, passing in name manually or via generic is sufficient.

**Comment by snakefoot** [comment]
If you read the NLog wiki, that it tells you to avoid allocating Logger in method, instead as static property on the class:

https://github.com/NLog/NLog/wiki/Tutorial#best-practices-for-logging

Just because you have a hard time using `GetCurrentClassLogger`, then I don't think it should be removed.

**Comment by 304NotModified** [comment]
> the JIT compiler might inline some code

Therefor `[MethodImpl(MethodImplOptions.NoInlining)]` is in NLog's code.

To be clear, it goes wrong in your codebase without using `[MethodImp...]`?

**Comment by plabanauskis** [comment]
@snakefoot I agree as I haven't read that particular explanation. In that case, the documentation for the method could be expanded to explain how it should be used. Currently it says: 

> This is a slow-running method. Make sure you're not doing this in a loop.

@304NotModified I am aware of that, however I think consumers shouldn't tinker with JIT's settings unless it is necessary for their applications.

I am closing this as explanations have been very clear. Thank you.
