### ISSUE TITLE
Logger.Log(LogEventInfo logEvent) does not set LoggerName

### ISSUE THREAD

**Issue by clearwaterstream** [NLog/NLog#2916]
Hi,

Unlike Logger.Debug(), Logger.Info(), Logger.Error(), etc the Logger.Log(LogEventInfo logEvent) does not set the LoggerName property.

Since we are calling Log method of the Logger object, we know who the logger is.

Why not do this inside the code for the logger class:

```
if(string.IsNullOrEmpty(logEvent.LoggerName))
  logEvent.LoggerName = logger.Name;
```

This way Logger.Log would exhibit similar behavior to Logger.Info(), Logger.Error(), etc --- all of which set the logger name for you auto-magically.

I raised it as a bug b/c I think Logger.Log stands out like a black sheep from other log methods (LoggerName wise) and there is no need for it.

Thanks!!

**Comment by snakefoot** [comment]
That is a good idea. Have created #2916 (But only checks for null, so one can still create LogEventInfo with LoggerName = string.Empty)
