### ISSUE TITLE
PDB cannot be loaded from SymbolSource

### ISSUE THREAD

**Issue by emresebat** [NLog/NLog#2921]
Hi
As explained #236  I'm trying to load the pdb from http://srv.symbolsource.org/pdb/public but is seems to be down. 

Does nlog still use symbolsource?

**Comment by snakefoot** [comment]
Symbols nuget-packages are being created, and they should be pushed to SymbolServer.

But can see that PullRequest also attempts to publish to SymbolServer. This should probably be stopped.

But I guess @304NotModified performs the final publish to nuget. Not sure if this includes the symbols-package:

https://www.appveyor.com/docs/deployment/nuget/

There is also this command:

```dotnet nuget push [PACKAGE].nupkg```
> This command automatically pushes the primary package to nuget.org and the symbol package to the official Nuget symbols source: symbolsource.org.

https://geeklearning.io/how-to-debug-a-net-core-nuget-package/

**Comment by emresebat** [comment]
Hi

Thanks for the info, I see this is the default setup but it doesn't mean anything is symbolsource.org fails to load... So I have to wait for them to fix I think.

<img width="1017" alt="screenshot 2018-09-19 19 46 02" src="https://user-images.githubusercontent.com/2254943/45774071-571f3700-bc4c-11e8-8783-91f915d3be6a.png">

**Comment by snakefoot** [comment]
Think we could try and change NLog to have the following (Only works for netstandard + net471):

`<DebugType>embedded</DebugType>`

https://github.com/rgl/example-dotnet-source-link

This can then be combined with Microsoft.SourceLink.GitHub:

`<PackageReference Include="Microsoft.SourceLink.Vsts.Git" Version="1.0.0-beta-63127-02" PrivateAssets="All"/>`

**Comment by emresebat** [comment]
I think symbolsource.org is having a bad time, now the site is not even available. 

So it would be great to have an alternative.

**Comment by 304NotModified** [comment]
> You can see something here (Search for SourceLink in the page below):
> 
> https://blogs.msdn.microsoft.com/dotnet/2018/05/30/announcing-net-core-2-1/

:) nice!

**Comment by emresebat** [comment]
Hi

So it seems currently symbolsource is down, and we don't have an alternative way to debug NLog nuget package. 

I have 1 NullReference exception I see at my application startup and 1 KeyAlreadyExists exception with NLog.Targets.Gelf package which I'm trying to solve. The best way seems to go from the source code.

**Comment by snakefoot** [comment]
@emresebat One can usually get very far with the Exception.StackTrace. But yes this is something to improve upon. Maybe create a PullRequest?

**Comment by 304NotModified** [comment]
> Starting today, you can publish symbol packages to the NuGet.org symbol server. 

https://blog.nuget.org/20181116/Improved-debugging-experience-with-the-NuGet-org-symbol-server-and-snupkg.html

**Comment by snakefoot** [comment]
>  @304NotModified this is fixed by #3045, isn;t?

Yes if snupkg-packages are being uploaded to nuget.org.

**Comment by 304NotModified** [comment]
👍
