### ISSUE TITLE
No logs written from .net core console app

### ISSUE THREAD

**Issue by fschick** [NLog/NLog#2930]
Demo project here: [NLogTest](https://github.com/fschick/NLogTest)

**Very intresting detail**: As soon as the `internalLogLevel` is set to other than `None` e.g. `internalLogLevel="Trace"`, it's all workging without any noticeable error/warning/debug message.

**NLog version**: 4.5.10
**NLog.Extensions.Logging**: 1.3.0
**Platform**: .NET Core 2

**Current NLog config**
```<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" 
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
      autoReload="true" 
      throwExceptions="true" 
      internalLogFile="C:\NLog.internal.log" 
      internalLogLevel="None">
  <targets>
    <target name="logfile"
            xsi:type="File"
            fileName="${basedir}\NLogTest.log"
            layout="${date}|${level}|${message}|">
    </target>
  </targets>
  <rules>
    <logger name="*" minlevel="Trace" writeTo="logfile" />
  </rules>
</nlog>
```
**Current code**
```
private static void Main(string[] args)
{
    using (var services = CreateDiServiceProvider())
    {
        var logger = services.GetRequiredService<ILogger<Program>>();
        logger.LogCritical("Test");
    }

    LogManager.Shutdown();
}

private static ServiceProvider CreateDiServiceProvider()
{
    IServiceCollection services = new ServiceCollection();
    services.AddLogging(ConfigureLogging);
    return services.BuildServiceProvider();
}

private static void ConfigureLogging(ILoggingBuilder loggingBuilder)
{
    LogManager.LoadConfiguration("NLogTest.nlog");
    loggingBuilder.SetMinimumLevel(LogLevel.Trace);
    loggingBuilder.AddNLog(new NLogProviderOptions { CaptureMessageTemplates = true, CaptureMessageProperties = true });
}
```

- What is the current result: *No logs are written to log file*
- What is the expected result? *Logs should be written log file*
- Did you checked the Internal log: *yes*
- Please post full exception details: *no messages, no exceptions*
- Are there any workarounds? *yes, set `internalLogLevel` to other than `None`*
- Is there a version in which it did work? *no*
- Can you help us by writing an unit test? *unsure, test project provided*

As mentioned above, with the given configuration no logs are written. Demo project here: [NLogTest](https://github.com/fschick/NLogTest)

**Comment by 304NotModified** [comment]
> _set `internalLogLevel` to other than `None`_

"none" isn't a valid value for "internalLogLevel". I think you are looking for "off"

Using "none" will make your config invalid. But I have to agree that it should be more robust.

**Comment by 304NotModified** [comment]
checked this, in my case i get an exception (which is correct, because of ` throwExceptions="true" `) - aren't you?

**Comment by 304NotModified** [comment]
#2931 should fix this if there is an invalid value :)

**Comment by fschick** [comment]
Shame on me :-(. It works smoothly when set to `off`. Slightly difference between net core and nlog levels. BTW, I dont't get an exception, event with `throwExceptions="true"`.

**Comment by fschick** [comment]
`None` is the equilant to `Off` from net core, see https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.loglevel?view=aspnetcore-2.1. When working from net core, I'm personally using Microsoft.Extensions.Logging framework and take NLog as the final 'materializer'.
