### ISSUE TITLE
Could not load type for Oracle.ManagedDataAccess.Client for .Net 4.6 Class Library 

### ISSUE THREAD

**Issue by DougSloane** [NLog/NLog#2932]
Hi,

I'd really appreciate any comments on this. Nlog to Oracle seems to not work in a .Net Class Library

I'm trying to write a logging routine class library to incorporate in multiple .Net applications. I am having trouble logging to Oracle when using Nlog in a class library. It works when using winforms but  not a class library.

I create 2 very basic .Net applications - 1 a Class Library and 1 a WinForms application. 
I install Nlog (4.5.10) Nlog.Config (4.5.10) and Oracle ManagedDataAccess (18.3) via Nuget.
The only difference between the two applications is that for the class library I create another project with a form and a button (which calls my object library) and add a reference to my class library, I also copy nlog.config to the EXE path. The code in both applications is

```c#
private static Logger logger;
        public static void LogDB()
        {
            try
            {
                logger = NLog.LogManager.GetCurrentClassLogger();

                LogEventInfo logEvent = new LogEventInfo();
                logEvent.Level = LogLevel.Error;
                logEvent.Properties["Timestamp"] = DateTime.Now.ToString();
                logEvent.Properties["Application"] = "test";
                logEvent.Properties["UserID"] = "test";
                logEvent.Properties["MachineID"] = "test";
                logEvent.Properties["PrisonerID"] = "test";
                logEvent.Properties["Message"] = "test";
                logEvent.Properties["Sequence"] = "test";
                logEvent.Properties["CommandText"] = "test";
                logEvent.Properties["PrisIR1ID"] = "test";
                logEvent.Properties["Parameters"] = "test";
                logger.Log(logEvent);
            }
            catch (Exception ex)
            {

            }
        }
```
When I instantiate my logger using
```c#
logger = NLog.LogManager.GetCurrentClassLogger();
```
in the class library I get an error, in winforms application I don't. The error is 

Could not load type 'Oracle.ManagedDataAccess.Client' from assembly 'NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c'.

My Nlog.config is boilerplate apart from the target which is -

```xml
<nlog>
  <targets>
<target xsi:type="Database"
      name="DBOracle"
      dbProvider="Oracle.ManagedDataAccess.Client"
      connectionString="Data Source=IPS123.DEV;User ID=********;Password=********;Max Pool Size=3;"
      commandText="exec ********.LOGGING.SaveDBLog
                            @Timestamp, 
                            @Application, 
                            @UserID, 
                            @MachineID, 
                            @PrisonerID, 
                            @Message, 
                            @Sequence, 
                            @CommandText, 
                            @PrisIR1ID, 
                            @Parameters" >

      <parameter name="@Timestamp" layout="${date}"/>
      <parameter name="@Application" layout="${message}"/>
      <parameter name="@UserID" layout="${message}"/>
      <parameter name="@MachineID" layout="${message}"/>
      <parameter name="@PrisonerID" layout="${message}"/>
      <parameter name="@Message" layout="${message}"/>
      <parameter name="@Sequence" layout="${message}"/>
      <parameter name="@CommandText" layout="${message}"/>
      <parameter name="@PrisIR1ID" layout="${message}"/>
      <parameter name="@Parameters" layout="${message}"/>
    </target>
  </targets>
  <rules>
    <logger name="*" minlevel="Error" writeTo="DBOracle" />
  </rules>
</nlog>

```
Stack trace is

```
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName)
   at System.RuntimeType.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark)
   at System.Type.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase)
   at NLog.Targets.DatabaseTarget.SetConnectionType()
   at NLog.Targets.DatabaseTarget.InitializeTarget()
   at NLog.Targets.Target.Initialize(LoggingConfiguration configuration)
   at NLog.Targets.Target.NLog.Internal.ISupportsInitialize.Initialize(LoggingConfiguration configuration)
   at NLog.Config.LoggingConfiguration.InitializeAll()
   at NLog.LogFactory.ReconfigExistingLoggers()
   at NLog.LogFactory.get_Configuration()
   at NLog.LogFactory.GetLogger(LoggerCacheKey cacheKey)
   at NLog.LogFactory.GetLogger(String name)
   at NLog.LogManager.GetCurrentClassLogger()
   at t5.Class1.LogDB() in C:\development\tfs\IPS.Log\IPSLog\test5\T5Forms\t5\Class1.cs:line 17
```

I have also tried removing the dbprovider and changing it to 
```
dbProvider="Oracle.ManagedDataAccess.Client, Oracle.ManagedDataAccess, Version=4.122.18.3,Culture=neutral, PublicKeyToken=89b483f429c47342"
```

to no avail.

Thank You 

Doug

**Comment by snakefoot** [comment]
Have you tried this:

`dbProvider="Oracle.ManagedDataAccess.Client.OracleConnection, Oracle.ManagedDataAccess"`

Remember to add a package-reference to the Oracle-client (`Oracle.ManagedDataAccess.dll` must be in the deployment folder)

**Comment by snakefoot** [comment]
If you want to reference properties on the LogEventInfo, then you must do it like this:

`<parameter name="@Application" layout="${event-properties:Application}"/>`

Instead of injecting everything with LogEventInfo.Properties, then you can also make use of layoutrenderers. Ex:

`<parameter name="@MachineID" layout="${machinename}"/>`

**Comment by 304NotModified** [comment]
PS https://github.com/NLog/NLog/wiki/Database-target

tells "Oracle.DataAccess.Client"  for "dbProvider"

But I think that's a driver from another package (https://www.oracle.com/technetwork/database/windows/downloads/index-101290.html)

**Comment by 304NotModified** [comment]
> Instead of injecting everything with LogEventInfo.Properties,

see for all options: https://nlog-project.org/config/?tab=layout-renderers

**Comment by DougSloane** [comment]
> Have you tried this:
> 
> `dbProvider="Oracle.ManagedDataAccess.Client.OracleConnection, Oracle.ManagedDataAccess"`
> 
> Maybe have to add a package-reference to the Oracle-client?

Hi and thanks to you both for replying,

This has worked, thank you so much. I'm still curious however as to why this is required when instantiating the logger within a class library but not in a winforms application. Seems odd to me.

Thanks also for pointing out the issues with the layouts. I'm aware of these, we're currently just evaluating Nlog and this is very far from production. I just wanted to get the basic Oracle connectivity working.

Thanks again for your help with this

Doug

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, please let us know!
