### ISSUE TITLE
ExceptionLayoutRenderer generates invalid JSON for exceptions with Data collection with objects as keys

### ISSUE THREAD

**Issue by owerkop** [NLog/NLog#2936]
NLog version: 4.5.6

Layout with exception formatted as JSON:
```xml
<nlog>
    <targets>
        <target name='debug1' type='Debug' layout='${exception:format=@}' />
    </targets>
    <rules>
        <logger minlevel='Info' writeTo='debug1' />
    </rules>
</nlog>
```

Logging exception with Data property where the keys are objects:
```cs
class SomeType {
   public int SomeProperty { get; set; }
}

var someObject = new SomeType() { SomeProperty = 123 };
var ex = new Exception("msg");
ex.Data.Add(someObject, 1);
logger.Error(ex, "msg");
```

Generates invalid JSON in the logs:
```json
{"Message":"msg", "Data":{{_SomeProperty__123}:1}, 
```

It should be:
```json
{"Message":"msg", "Data":{"_SomeProperty__123":1}, 
```

This case is from production system.
`System.Activities.XamlIntegration.ActivityXamlServices.Compile` throw `System.InvalidOperationException` with Data property where the keys are objects.

**Comment by 304NotModified** [comment]
This could be fixed with https://github.com/NLog/NLog/pull/2865

Could you please check with the latest NLog version? (4.5.10) 

thanks!

**Comment by snakefoot** [comment]
@owerkop Thank you for reporting this bug. I have created #2937 to fix the issue in the NLog JSON Serializer

**Comment by snakefoot** [comment]
@owerkop NLog ver. 4.5.11 has been released that fixes the issue: https://www.nuget.org/packages/NLog/
