### ISSUE TITLE
Log file not being created

### ISSUE THREAD

**Issue by stesvis** [NLog/NLog#2938]
**NLog version**: 4.5.10

**Platform**: .Net 4.6.1

**Current NLog config**

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="false"
      internalLogLevel="Off" internalLogFile="c:\temp\nlog-internal.log">

  <!-- optional, add some variables
  https://github.com/nlog/NLog/wiki/Configuration-file#variables
  -->
  <variable name="myvar" value="myvalue" />

  <!--
  See https://github.com/nlog/nlog/wiki/Configuration-file
  for information on customizing logging rules and outputs.
   -->
  <targets>

    <!--
    add your targets here
    See https://github.com/nlog/NLog/wiki/Targets for possible targets.
    See https://github.com/nlog/NLog/wiki/Layout-Renderers for the possible layout renderers.
    -->

    <!-- local file target -->
    <target name="fileTarget"
            xsi:type="File"
            fileName="${basedir}\Logs\${shortdate}.log"
            layout="
-------------- ${level} (${longdate}) --------------${newline}
${newline}
Call Site: ${callsite}${newline}
Exception Type: ${exception:format=type}${newline}
Exception Message: ${exception:format=message}${newline}
Stack Trace: ${exception:format=stacktrace}${newline}
Additional Info: ${message}${newline}" />

    <!-- task file target -->
    <target name="taskTarget"
            xsi:type="File"
            fileName="${basedir}\Logs\Tasks.log"
            layout="
-------------- ${level} (${longdate}) --------------${newline}
${newline}
Call Site: ${callsite}${newline}
Message: ${message}${newline}" />

    <!--
    Write events to a file with the date in the filename.
    <target xsi:type="File" name="f" fileName="${basedir}/logs/${shortdate}.log"
            layout="${longdate} ${uppercase:${level}} ${message}" />
    -->
  </targets>

  <rules>
    <!-- add your logging rules here -->
    <!-- local file logger -->
    <logger minlevel="Trace" name="fileLogger" writeTo="fileTarget" />
    <logger minlevel="Trace" name="taskLogger" writeTo="taskTarget" />
    <!--
    Write all events with minimal level of Debug (So Debug, Info, Warn, Error and Fatal, but not Trace)  to "f"
    <logger name="*" minlevel="Debug" writeTo="f" />
    -->
  </rules>
</nlog>
```

- **What is the current result?** The log file is not being generated
- **What is the expected result?** The log file should be created in the "Logs" folder
- NLog.config is set with **BuildAction=Content** and **Copy to Output Directory=Copy always**

**Comment by snakefoot** [comment]
Start here: https://github.com/NLog/NLog/wiki/Logging-troubleshooting#internal-logging

**Comment by stesvis** [comment]
@snakefoot so I found another **Project A** where i used the same configuration and everything, and it works there. The only difference is that NLog.config has Build Action = ContentWithTargetPath.
If I set it to just Content, it stops working.

In this **Project B** where I am trying to implement it, I don't have ContentWithTargetPath as an option, and I don't know why.
However, NLog works if I move NLog.config to the project root (before I had it in its own sub-folder, but also in Project A it is in its own sub-folder).

**Comment by snakefoot** [comment]
The most important thing is to stop using "NLog.config"-nuget-package. It will only cause you misery.

Instead create the NLog.config manually, and ensure **Copy to Output Directory**=`Preserve Newest`

**Comment by stesvis** [comment]
Cool but the tutorial is receiving then?
https://github.com/NLog/NLog/wiki/Tutorial

**Comment by snakefoot** [comment]
Yes it was good advice with NLog 4.4. But it became broke with NLog 4.5 and NetCore. I guess the changes should be rolled back until someone knows how to fix it. But I'm not the one

Sent from my Sony Xperia


---- stesvis wrote ----


Cool but the tutorial is receiving then?
https://github.com/NLog/NLog/wiki/Tutorial

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, please let us know!
