### ISSUE TITLE
Extend NLog target extension type-name loading

### ISSUE THREAD

**Issue by snakefoot** [NLog/NLog#2944]
Right now on NetCore one must remember to add extension targets to the extensions-section. See also #1091

But actually many extension targets have very good names, so could consider registering a target like this:

https://www.nuget.org/packages/NLog.Targets.Seq

Target-alias: **Seq**
Target-Assembly: **NLog.Targets.Seq**

Then one could support this declare of type:

`<target xsi:type="NLog.Targets.Seq" serverUrl="http://localhost:5341" apiKey="" />`

And the config-loader would then do the following:

- Check if any targets registered as `NLog.Targets.Seq`
- Check if any targets registered as `Seq`
- Attempt to resolve assembly `NLog.Targets.Seq` (Unless already tried)
- Perform the two previous checks again

Then it would not be necessary to have `NLog.Targets.Seq` in the `extensions`-section.

It would then just be a matter of updating the guide-lines for naming packages with NLog Target Extensions.

One could also consider to add full typename-support: **SeqTarget, NLog.Targets.Seq**

**Comment by 304NotModified** [comment]
> It would then just be a matter of updating the guide-lines for naming packages with NLog Target Extensions.

Another option is to name the dll the same as the target?

**Comment by snakefoot** [comment]
> Another option is to name the dll the same as the target?

That is pretty much what many are doing. Just with a namespace to signal that it is for NLog/log4net/serilog etc. and also the 

I'm suggesting that we improve the NLog user experience. Of course one could require one to declare the target like this (Then the example code would work on new and old NLog):

```
[Target("NLog.Targets.Seq")]
public sealed class SeqTarget : Target
```

It is just a suggestion for making it easier to add/remove targets in config , without needing to remember updating extensions-section.

**Comment by 304NotModified** [comment]
anyway, great idea, would be very nice to add :)
