### ISSUE TITLE
Documentation error: ${configsetting} is tagged with wrong Nuget packages.

### ISSUE THREAD

**Issue by ArveSystad** [NLog/NLog#2947]
Hi!

Over on https://nlog-project.org/config/?tab=layout-renderers, the {configsetting} layout renderer is tagged with `NLog.Extensions.Logging` and `NLog.Web.AspNetCore`. However, after a little digging, I found the renderer in the `NLog.Extensions.Configuration` package (https://github.com/NLog/NLog.Extensions.Logging/blob/master/src/NLog.Extensions.Configuration/ConfigSettingLayoutRenderer.cs).

Couldn't find any way to make a PR for the documentation, so I post it here instead, hopefully saving some souls a few minutes of research in the future.

Arve

**Comment by snakefoot** [comment]
See also https://github.com/NLog/NLog.Extensions.Logging/issues/250 and https://github.com/NLog/NLog.Extensions.Logging/pull/248

**Comment by Valeriy1991** [comment]
@304NotModified see, please, this page - https://github.com/NLog/NLog/wiki/ConfigSetting-Layout-Renderer - I'm added info about package `NLog.Extensions.Configuration` for using the `configsetting` layout renderer in .NET Core 2.1 Console apps.

P.S. If I did something wrong, please tell me how to do it.
