### ISSUE TITLE
MDLC Allow pushing a list of properties

### ISSUE THREAD

**Issue by snakefoot** [NLog/NLog#2948]
Microsoft Extension Logging comes with BeginScope with 2-3 properties. See ActionLogScope  and HostingLogScope.

Instead of calling MappedDiagnosticsLogicalContext.SetScoped for each property, then it could be nice if one could deliver an `IList<KeyValuePair<string,object>>`

This would allow NLog to skip allocation of new Dictionary for every SetScoped-call (Along with skip allocation of Stack-collection in NLog.Extension.Logging)

**Comment by 304NotModified** [comment]
Sounds good to me! 👍
