### ISSUE TITLE
Mark RequiredParameterAttribute with MeansImplicitUseAttribute attribute

### ISSUE THREAD

**Issue by imanushin** [NLog/NLog#2952]
**NLog version**: 4.5.0

**Platform**: .Net 4.7.1

Current issue: ReSharper thinks that properties marked with [RequiredParameter](https://github.com/NLog/NLog/blob/master/src/NLog/Config/RequiredParameterAttribute.cs) are not used, which is completely wrong (see [documentation page](https://github.com/NLog/NLog/wiki/How-to-write-a-custom-target)).

What do I need: help ReSharper to understand, that property (e.g. marked with attribute [RequiredParameter](https://github.com/NLog/NLog/blob/master/src/NLog/Config/RequiredParameterAttribute.cs)) is used from reflection.

Two tasks:
* Update [ReSharper Annotations](https://github.com/NLog/NLog/blob/master/src/NLog/Annotations.cs) to get the latest supported attributes
* Mark [RequiredParameterAttribute](https://github.com/NLog/NLog/blob/master/src/NLog/Config/RequiredParameterAttribute.cs) with [MeansImplicitUseAttribute](https://www.jetbrains.com/help/resharper/Reference__Code_Annotation_Attributes.html#MeansImplicitUseAttribute)

**Comment by 304NotModified** [comment]
Yes, that would be great if you could do a PR for the two tasks 👼

**Comment by snakefoot** [comment]
Maybe also include [DefaultParameterAttribute](https://github.com/NLog/NLog/blob/master/src/NLog/Config/DefaultParameterAttribute.cs)

**Comment by imanushin** [comment]
Ok, will apply on these attributes first (will try on the next weekends). Then will try to find other attributes for improvement
