### ISSUE TITLE
Nlog sends email automatically on exception

### ISSUE THREAD

**Issue by panoj** [NLog/NLog#2953]
Hello Team,

This is a weird suitation, Nlog users usually contact you when Nlog does not send emails but I am contacting you because Nlog is sending emails.

I configured NLog using UseNLog(). I have nlog.config file. Thats it.  Nothing else is set to configure it.

Nlog.config file just have target set to email me.

I do not even inject Logger in any OData controller. 
It is a Asp.net Core project.

I am manually throwing exception from one of  my controller. And it sends me email.
I am not even calling Logger.LogError().

How is this happening?

**Comment by 304NotModified** [comment]
answered here: https://stackoverflow.com/questions/52709013/nlog-asp-net-core-sends-email-automatically-on-error-without-logging-it

also the same comments apply, 

> We could better answer your question if you share the error message (in the email) and the nlog.config

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, please let us know!
