### ISSUE TITLE
How to render the message template when using structuerd logging?

### ISSUE THREAD

**Issue by pardahlman** [NLog/NLog#2956]
Hello again,

I have another question regarding the structured logging with NLog. One of my log targets is Elasticsearch, which provides great flexibility to filter and search log entries based on property values. I want to include the message template (that is, the "raw" log entry without any values inserted into the "holes"). This way I can filter based in the message template and see all occurrences of this particular entry.

Any ideas on how to achieve this? Thanks!

**Comment by snakefoot** [comment]
If you read the wiki:

https://github.com/NLog/NLog/wiki/How-to-use-structured-logging

Then you can see that one can use the following in the NLog target:

`$(message:raw=true)`

**Comment by pardahlman** [comment]
Perfecto, I missed that. Thanks!

**Comment by pardahlman** [comment]
Hi, @snakefoot - not sure if this is on purpose or typos, but in order for the message template to be rendered, you need to use curly brackets: (`${message:raw=true}`) - this goes for all properties listed in [NLog Layout Support](https://github.com/NLog/NLog/wiki/How-to-use-structured-logging#nlog-layout-support)

**Comment by snakefoot** [comment]
Me making typos. Will fix my previous comment. Sorry

Sent from my Sony Xperia


---- Pär Dahlman wrote ----


Hi, @snakefoot<https://github.com/snakefoot> - not sure if this is on purpose or typos, but in order for the message template to be rendered, you need to use curly brackets: (${message:raw=true}) - this goes for all properties listed in NLog Layout Support<https://github.com/NLog/NLog/wiki/How-to-use-structured-logging#nlog-layout-support>
