### ISSUE TITLE
NLog gives exception for NLog.LogFactory TimeSpan overflowed because duration too long

### ISSUE THREAD

**Issue by Toxaris-NL** [NLog/NLog#2958]
After updating Mono to version 5.16.0.179 on  Raspbian 9 I can no longer start several programs utilizing NLog (specifically Sonarr and Jackett) running on Mono. The error is the same:

System.TypeInitializationException: The type initializer for 'NLog.LogManager' threw an exception. ---> System.TypeInitializationException: The type initializer for 'NLog.LogFactory' threw an exception. ---> System.OverflowException: TimeSpan overflowed because the duration is too long.
  at System.TimeSpan.Interval (System.Double value, System.Int32 scale) <0x74a03bb8 + 0x0010c> in <c3c5f4bb011a4af8b925b0d39ee12396>:0
  at System.TimeSpan.FromSeconds (System.Double value) <0x74a03e88 + 0x0001b> in <c3c5f4bb011a4af8b925b0d39ee12396>:0
  at NLog.LogFactory..cctor () [0x00000] in <94b2a4e8be134a208425f74d14f2331e>:0
   --- End of inner exception stack trace ---
  at (wrapper managed-to-native) System.Object.__icall_wrapper_mono_generic_class_init(intptr)
  at NLog.LogManager..cctor () [0x00000] in <94b2a4e8be134a208425f74d14f2331e>:0

I can of course also report this at the programs, but as they both use NLog and both have the same error, I thought it would be best reported here.

**Comment by snakefoot** [comment]
Duplicate of  #2957. See also https://github.com/mono/mono/issues/11095

**Comment by Toxaris-NL** [comment]
> Duplicate of #2957. See also [mono/mono#11095](https://github.com/mono/mono/issues/11095)

Ok, so it is a mono issue and not NLog. Then this one can be closed I think

**Comment by timmi-on-rails** [comment]
@Toxaris-NL Could you please remove mono packages completely and install them again. I am still guessing, but that worked for me :-/. Maybe there is something missing in the upgrade scripts.
Thank you!

**Comment by Toxaris-NL** [comment]
@timmi-on-rails  I actually removed the version with the issue and reinstalled the previous version to get my programs running again. I have blocked the upgrade for now. I will check tomorrow by reinstalling the latest version again.

**Comment by timmi-on-rails** [comment]
@Toxaris-NL That is exactly what I was doing. And then I wanted to reproduce the error and removed the old version and installed the new version again and I was unable to reproduce the error.
You should remove the old version and install the new one, instead of upgrading. (haven't tried upgrading again...)
