### ISSUE TITLE
How to parse timestamp property of log4jxmlevent renderer?

### ISSUE THREAD

**Issue by LeonidasFettikus** [NLog/NLog#2962]
Hi guys,

I use NLog for logging in one of my applications and wanted to provide logs to the user via the UI. I have built a log parser for this purpose that takes the log file and parses all the logs into C# objects that are then sent to the UI so the user can view them.

However, I am having a hard time getting the date parsing right. NLog logs with log4jxmlevent look like the following:

```xml
<log4j:event 
    logger="Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker" 
    level="INFO" 
    timestamp="1539939614029" 
    thread="6">
        <log4j:message>Executing action method Condato.IoT.Client.TinkerForge.Controllers.ApplicationController.GetLogs (Condato.IoT.Client.TinkerForge) - Validation state: Valid</log4j:message>
        <log4j:properties>
            <log4j:data name="log4japp" value="Condato.IoT.Client.TinkerForge(15096)" />
            <log4j:data name="log4jmachinename" value="DEVDOTNET" />
        </log4j:properties>
</log4j:event>
```

I then have created a simple class to hold a log:

```c#
public class Log
{
    public string Logger { get; set; }
    public string Level { get; set; }
    public DateTime Time { get; set; }
    public string Message { get; set; }
    public string LogSource { get; set; }
    public string LogSourceName { get; set; }
}
```

After that I simply iterate over my logs and parse each one from XML to C# objects. The relevant part here is parsing the timestamp property of each log.

`var time = new DateTime(long.Parse(rootReader["timestamp"])).ToUniversalTime();`

I assumed that the number in the timestamp property represents the ticks. So I just passed them into the Date() constructor. However, this is the output I get from parsing the timestamp property:

![image](https://user-images.githubusercontent.com/8888670/47215860-34935180-d3a3-11e8-9ea9-33d0421f806c.png)

So this seems not right as those logs were created yesterday. I have looked at the NLog documentation, but log4jxmlevent is very sparsely documented or I missed something.

**Comment by LeonidasFettikus** [comment]
After googling around a bit, I found this:

`DateTimeOffset.FromUnixTimeMilliseconds(long.Parse(rootReader["timestamp"].ToString())).DateTime;`

Which works perfectly. But I wouldn't have found out that this is Unix time, so thanks mate. 👍

**Comment by snakefoot** [comment]
@LeonidasFettikus So this issue can be closed as resolved?

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, please let us know!
