### ISSUE TITLE
nlog changes behaviour depending on logger priority

### ISSUE THREAD

**Issue by giannisgeros** [NLog/NLog#2965]
**NLog version: 4.5.10**

**Platform: .NET 4.0**

**StackOverflow link:** https://stackoverflow.com/questions/52819710/nlog-changes-behaviour-depending-on-logger-priority

I want to log a certain layout:

    Message: {the message}  
    Properties: {key}: {value} | {key}: {value} | ...

My main is:  

    static void Main(string[] args)
		{
			Loggers.TxtLogger.LogInfo();
			Loggers.TxtLogger.LogInfo("My custom message");
			Loggers.TxtLogger.LogInfo(new { id = 1, issue = "my custom issue" });

			Console.ReadKey();
		}

My Loggers class is:  

    public static class Loggers
	{
		public static ILogger TxtLogger { get; private set; }

		static Loggers()
		{
			TxtLogger = LogManager.GetLogger("TxtLogger");
		}

		public static void LogInfo(this ILogger @this, object message = null)
		{
			@this.Info()
				.Property("Property1Key", "Property1Value")
				.Property("Property2Key", "Property2value")
				.Message(message == null ? "" : "{@message}", message)
				.Write();

		}

		public static void LogError(this ILogger @this, Exception e, object message = null)
		{
			@this.Error()
			   .Exception(e)
			   .Property("Property1Key", "Property1Value")
			   .Property("Property2Key", "Property2value")
			   .Message(message == null ? "" : "{@message}", message)
			   .Write();
		}
	}

My NLog.config is:  

   

     <?xml version="1.0" encoding="utf-8" ?>
    <nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
          autoReload="true"
          throwExceptions="false"
          throwConfigExceptions="true"
          internalLogLevel="Off" internalLogFile="c:\temp\nlog-internal.log">
    
    	<variable name="logFile" value="./logs/${shortdate}/${logger}.log" />
    
    	<variable name="colon" value="${literal:text=\:}"/>
    	<variable name="quotationMark" value="${literal:text=&quot;}"/>
    	<variable name="messageIfNotEmpty" value="${when:when=length('${message}')>0:inner=Message${colon} ${message}${newline}}"/>
    	<variable name="properties" value="Properties${colon} ${all-event-properties:format=[key]\: [value]:separator= | }${newline}"/>
    
    	<variable name="layout2" value="${messageIfNotEmpty}${properties}"/>
    
    	<targets>
    		<target name="ConsoleLog" xsi:type="Console" layout="${layout2}"/>
    		<target name="TxtLog" xsi:type="File" fileName="${logFile}" layout="${layout2}"/>
    	</targets>
    
    	<rules>
    		<logger name="*" writeTo="ConsoleLog" final="true"/>
    		<logger name="*" writeTo="TxtLog" />
    	</rules>
    
    </nlog>

With this set i get the desired outcome:  

    Properties: Property1Key: Property1Value | Property2Key: Property2value  
        
    Message: "My custom message"  
    Properties: Property1Key: Property1Value | Property2Key: Property2value 
        
    Message: {"id":1, "issue":"my custom issue"}  
    Properties: Property1Key: Property1Value | Property2Key: Property2value 

But when I try to log it to a .txt file also (I remove the `_final="true"_` attribute from _ConsoleLog_ logger), I get this outcome:  

    Properties: Property1Key: Property1Value | Property2Key: Property2value
        
    Message: "My custom message"  
    Properties: message: My custom message | Property1Key: Property1Value | Property2Key: Property2value  
        
    Message: {"id":1, "issue":"my custom issue"}  
    Properties: message: { id = 1, issue = my custom issue } | Property1Key: Property1Value | Property2Key: Property2value  

Now there is a work around and that's if I change the `_object message = null_` parameter in the `_LogInfo_` method to `_string message_` and I use `_newtonsoft json serializer_` to serialize the object, but I want to use the NLog serializer.  
Any thoughts?

>UPDATE

At NLog.Config I changed:  
`<variable name="layout2" value="${messageIfNotEmpty}${properties}"/>`  
to  
`<variable name="layout2" value="${properties}${messageIfNotEmpty}"/>`  
(put the message variable after the properties variable)  
And:  
`<rules>
    <logger name="*" writeTo="ConsoleLog" final="true"/>
    <logger name="*" writeTo="TxtLog" />
</rules>`  
to  
`<rules>
    <logger name="*" writeTo="ConsoleLog"/>
    <logger name="*" writeTo="TxtLog" />
</rules>`  
(removed the `final=true` attribute)  

So now my Console outcome is:    

    Properties: Property1Key: Property1Value | Property2Key: Property2value

    Properties: Property1Key: Property1Value | Property2Key: Property2value
    Message: "My custom message"

    Properties: Property1Key: Property1Value | Property2Key: Property2value
    Message: {"id":1, "issue":"my custom issue"}  
which is the desired outcome(with message after properties),  
but at the txt file i get the outcome:  

    Properties: Property1Key: Property1Value | Property2Key: Property2value

    Properties: message: My custom message | Property1Key: Property1Value | Property2Key: Property2value
    Message: "My custom message"

    Properties: message: { id = 1, issue = my custom issue } | Property1Key: Property1Value | Property2Key: Property2value
    Message: {"id":1, "issue":"my custom issue"}  
which obviously is not the desired outcome.  

Now I change the NLog.Config once again:

    <rules>
		<logger name="*" writeTo="ConsoleLog"/>
		<logger name="*" writeTo="TxtLog" />
	</rules>  
to:  

    <rules>
        <logger name="*" writeTo="TxtLog" />
		<logger name="*" writeTo="ConsoleLog"/>
	</rules>  
(I put the `TxtLog` first)  
And now the outcomes are reveresed,  
Console: Not the desired outcome(message is printed twice)  
TXT: The desired outcome  
And last if I change:

    <variable name="layout2" value="${properties}${messageIfNotEmpty}"/>  
back to:

    <variable name="layout2" value="${messageIfNotEmpty}${properties}"/>  
(put the message variable before properties),  
I don't get the desired outcome whatever the logger order may be.

**Comment by snakefoot** [comment]
Created #2963 to resolve the issue in NLog Fluent LogBuilder

**Comment by 304NotModified** [comment]
Fixed by  #2963
