### ISSUE TITLE
The same relative file path (folder) for internal and file target write to different locations

### ISSUE THREAD

**Issue by schallm** [NLog/NLog#2966]
**NLog version**: 4.5.10

**Platform**:  .NET Core 2.1

**Current NLog config**:
Modified [example](https://github.com/NLog/NLog.Web/blob/master/examples/ASP.NET%20Core%202/Visual%20Studio%202017/ASP.NET%20Core%202%20-%20VS2017/NLog.config) to use relative paths for internal and file targets.
```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      throwConfigExceptions="true"
      internalLogLevel="info"
      internalLogFile="..\..\log\internal-nlog-AspNetCore2.txt">


	<!-- the targets to write to -->
	<targets>
		<!-- write logs to file  -->
		<target xsi:type="File" name="allfile" fileName="..\..\log\nlog-AspNetCore2-all-${shortdate}.log"
				layout="${longdate}|${event-properties:item=EventId_Id:whenEmpty=0}|${uppercase:${level}}|${logger}|${message} ${exception:format=tostring}" />

		<!-- another file log, only own logs. Uses some ASP.NET core renderers -->
		<target xsi:type="File" name="ownFile-web" fileName="..\..\log\nlog-AspNetCore2-own-${shortdate}.log"
				layout="${longdate}|${event-properties:item=EventId_Id:whenEmpty=0}|${uppercase:${level}}|${logger}|${message} ${exception:format=tostring}|url: ${aspnet-request-url}|action: ${aspnet-mvc-action}|${callsite}" />

	</targets>

	<!-- rules to map from logger name to target -->
	<rules>
		<!--All logs, including from Microsoft-->
		<logger name="*" minlevel="Trace" writeTo="allfile" />

		<!--Skip non-critical Microsoft logs and so log only own logs-->
		<logger name="Microsoft.*" maxlevel="Info" final="true" />
		<!-- BlackHole -->
		<logger name="*" minlevel="Trace" writeTo="ownFile-web" />
	</rules>
</nlog>
```

> Note the folder portion of the relative path for internal and file target begins with `..\..\log`

So a developer can have multiple checkouts (different branches) of the same code base without changing log paths, we like to use relative paths for logging.  Our structure looks like the following:

```
<checkout root>
  \log
    <would like log files here>
  \src
    ...
    \WebServices
      ...
      nlog.config
      Program.cs
      Startup.cs
      WebServices.csproj
  App.sln
```

Currently the internal log files are "correctly" written to `<checkout root>\log\internal-nlog-AspNetCore2.txt`.  However, the file target output files are written to `<checkout root >\src\WebServices\bin\log`.  The base used to calculate the relative paths must be different between internal and file target logging?  Internal seems to be based off project folder while file target seems to be based of project output folder?

**Comment by snakefoot** [comment]
Believe that the InternalLogger uses the Current-Directory as relative path.

And the FileTarget uses AppDomain.BaseDirectory as relative path.

You can try and change your FileTarget FileName to this:

`fileName="${currentdir:cached=true}\..\..\log\nlog-AspNetCore2-all-${shortdate}.log"`

Or this:

`fileName="${aspnet-appbasepath}\..\..\log\nlog-AspNetCore2-all-${shortdate}.log"`

Btw. remember to add this to your NLog.config if planning to use **${aspnet**-whatever} layout-renderers:

```
  <extensions>
    <add assembly="NLog.Web.AspNetCore"/>
  </extensions>
```

**Comment by schallm** [comment]
Confusing that they would use different bases.  I suppose it would be a breaking change at this point to have them the be the same. 

Both your suggestions work...  Going with `${aspnet-appbasepath}` for now. 

Thanks for your help!

**Comment by snakefoot** [comment]
The InternalLogger attempts to be a no-nonsense logger, that doesn't attempt to probe anything but just writes no matter what.

FileTarget has been changed by #1089.

For me NLog is pretty much fire and forget, so I keep InternalLogger disabled and just use `throwConfigExceptions=true`.

But no one is stopping you from making a PR to improve NLog.

**Comment by snakefoot** [comment]
@schallm You can also configure the InternalLogger at runtime. Can hook into InternalLogger.LogWriter and then redirect directly to the Windows EventLog (You should never redirect the output of the InternalLogger to a NLog Logger-object).
