### ISSUE TITLE
Is there an example for FileTarget using C# code

### ISSUE THREAD

**Issue by mattraffel** [NLog/NLog#2976]
I would like to create a FileTarget, not using a config file.  I would like to do so with C# code.   I cannot find an example that does not use a config file.  Can we please have a code example?

**Comment by snakefoot** [comment]
There is an easy code example in the wiki Tutorial:

https://github.com/NLog/NLog/wiki/Tutorial#configure-nlog-targets-for-output

**Comment by mattraffel** [comment]
Thank you
