### ISSUE TITLE
Formatting properties

### ISSUE THREAD

**Issue by ThomasArdal** [NLog/NLog#2995]
I have a question regarding the formatting of the log message. If I log the following:

```csharp
IList<string> list = new List<string>();
list.Add("A");
list.Add("B");
list.Add("C");
logManager.Fatal("List Properties {data}", list);
```

Using the default layout, I get a nicely formatted log message:

```
List Properties "A", "B", "C"
```

I'm storing all properties on each log message in a separate store. In my target, I iterate through the `Properties` property on `LogEventInfo` and store each property. My challenge here is that I store both they key and value as a string and simply call the `ToString`-method on each item. This result in the following being stored:

```
data = System.Collections.Generic.List`1[System.String]
```

In other places in my code, I'm using different layout renderers to generate a correct username, machine name, etc. But can I somehow use a generic renderer, similar to the one NLog uses for the log message? Would like to render all property values, without knowing what's inside each value really.

**Comment by 304NotModified** [comment]
I think you're looking for the default `IValueFormatter`. 

example:

```c#
 var valueFormatter = ConfigurationItemFactory.Default.ValueFormatter;
 var sb = new StringBuilder();
 valueFormatter.FormatValue(list, null, CaptureType.Normal, null, sb);
 var text = sb.ToString();
```

**Comment by 304NotModified** [comment]
yes 8 seconds earlier 😄

**Comment by snakefoot** [comment]
But mine has less overhead for non-collections :)

**Comment by 304NotModified** [comment]
Simple vs optimized example 👍

**Comment by ThomasArdal** [comment]
@304NotModified @snakefoot You guys rock. I can see how the second proposal will be good for a list, but I was chasing a solution working for everything really.

**Comment by snakefoot** [comment]
@ThomasArdal The second option will work for "everything". What do you feel that is missing?

**Comment by ThomasArdal** [comment]
Maybe I am missing something. Will it work for non-IEnumerable types?

**Comment by snakefoot** [comment]
> Maybe I am missing something. Will it work for non-IEnumerable types?

As you can read from the very simple code-snippet, then it will call ToString on non-IEnumerable types.

Are you looking for JSON serialization?

**Comment by ThomasArdal** [comment]
Nope, bit I guess NLog.Config.ConfigurationItemFactory.Default.ValueFormatter will handle enumerables and anything else already supported on the log message.

**Comment by snakefoot** [comment]
> ValueFormatter will handle enumerables and anything else already supported on the log message.

Yes ValueFormatter will handle everything. But to avoid always allocating a StringBuilder, then I have made it a special case for IEnumerable-only.

**Comment by snakefoot** [comment]
@ThomasArdal Guess the issue can be closed as Resolved?

**Comment by ThomasArdal** [comment]
Absolutely 👍
