### ISSUE TITLE
Environment layout in fileName attribute of Target tag affects performance

### ISSUE THREAD

**Issue by Havoc9792** [NLog/NLog#3001]
**NLog version**: 4.5.10

**Platform**: .Net 4.5 
```

	<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	  <targets>
	    <target name="file" xsi:type="AsyncWrapper" timeToSleepBetweenBatches="0" overflowAction="Block">
	      <target type="File" layout="${longdate} ${level:uppercase=true} ${logger} ${message} ${onexception:EXCEPTION OCCURRED\:${exception:format=ToString,StackTrace} ${newline}}" fileName="C:\temp\Service-${environment:username}-${machinename}-${processid}-${shortdate}.log" archiveFileName="C:\temp\log.${shortdate}.{#####}.txt" archiveAboveSize="10240000" archiveNumbering="Sequence" encoding="iso-8859-2"/>
	    </target>
	  </targets>
		<rules>
			<logger name="*" minlevel="Info" writeTo="file"/>
		</rules>
	</nlog>
```

I can observe in dotTrace that the ${environment:username} will degrade the performance because of calling EnvironmentLayoutRenderer.Append in WriteAsyncThreadSafe->Write->PrecalculateVolatileLayouts->PrecalculateBuilder->RenderAppendBuilder

But filename is quite static, I would have expected it to be cached somewhere, instead of rebuilding on every call.

Another question I have is why do we have to pre-calculate layouts in the main thread even there is no thread sensitive layout (eg thread id)?

**Comment by snakefoot** [comment]
If your Environment.UserName is static fo the entire application lifetime, then you can do this:

`fileName="C:\temp\Service-${environment:username:cached=true}`

You can also consider to store it in the NLog GDC at application startup:

`NLog.GlobalDiagnosticsContext.Set("Environment_UserName", Environment.UserName);`

Then you can use it like this:

`fileName="C:\temp\Service-${gdc:Environment_UserName}`

NLog ver. 4.6 (Not yet released) will skip precalculate for GDC. Giving you full optimization.

**Comment by 304NotModified** [comment]
you can also use ${cache} -> https://github.com/NLog/NLog/wiki/Cached-Layout-Renderer
