### ISSUE TITLE
does "Environment layout renderer" support "aspnet core"?

### ISSUE THREAD

**Issue by protossyk** [NLog/NLog#3005]
hi:
    has the feature "Environment layout renderer" supported asp.net core 2.1

NLog version: 4.5.8

    <PackageReference Include="NLog" Version="4.5.8" />
    <PackageReference Include="NLog.Extensions.Logging" Version="1.2.1" />
    <PackageReference Include="NLog.Web.AspNetCore" Version="4.6.0" />

my nlog config:

    <target xsi:type="File" name="allfile" fileName="${environment:LogPath}/nlog-all-${shortdate}.log"
            layout="${longdate}|${event-properties:item=EventId_Id}|${uppercase:${level}}|${logger}|${message} ${exception:format=tostring}" />

the "${environment:LogPath}" doesn't work.

**Comment by snakefoot** [comment]
It is supported on NetStandard. I would probably check the NLog InternalLogger to see if something is blocking it from working:

https://github.com/NLog/NLog/wiki/Internal-Logging

**Comment by protossyk** [comment]
> See also:
> 
> https://nlog-project.org/config/?tab=layout-renderers&search=env
> 
> ![image](https://user-images.githubusercontent.com/5808377/48230655-1b7f2e80-e3ac-11e8-93b4-fb4c012c543c.png)

thank you  for  reply.  I found the  mistake is caching the old error environment settings, it works now.
