### ISSUE TITLE
Nlog with a class Library

### ISSUE THREAD

**Issue by alimhabib** [NLog/NLog#3009]
I have a class library and configuration file in a separate place I want to use it so I do the following
```
LogManager.Configuration = new NLog.Config.XmlLoggingConfiguration(configurationFile , true);
LogManager.ReconfigExistingLoggers();
```

The configuration of NLog is part of a remote app.config looks like
```xml
<configuration>
    <!-- ... -->
    <configSections>
        <section name="nlog" type="NLog.Config.ConfigSectionHandler, NLog" />
    </configSections>
    <nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
        <targets>
            <!-- 
              Log in a separate thread, possibly queueing up to
              5000 messages. When the queue overflows, discard any
              extra messages
            -->
            <target name="file" xsi:type="AsyncWrapper" queueLimit="5000" overflowAction="Discard" 
                layout="${machinename} - ${level} - ${longdate} - ${callsite} - ${threadid} - ${message} ${exception:format=tostring}">
                <target xsi:type="File" fileName="C:\logs/${level}.txt" />
            </target>
        </targets>
        <rules>
            <logger name="*" minlevel="Debug" writeTo="file" />
        </rules>
    </nlog>
</configuration>
```
the configuration object LogManager.Configuration always has the default values , any idea how to fix this.

**Comment by 304NotModified** [comment]
Hi, 

please check https://github.com/NLog/NLog/wiki/Logging-troubleshooting

**Comment by snakefoot** [comment]
@alimhabib Guess this issue can be resolved? Since your question has been answered here:

https://stackoverflow.com/questions/53223915/nlog-with-a-class-library

**Comment by alimhabib** [comment]
> @alimhabib Guess this issue can be resolved? Since your question has been answered here:
> 
> https://stackoverflow.com/questions/53223915/nlog-with-a-class-library

yes it solved, thanks a lot all , how to close this

**Comment by snakefoot** [comment]
> yes it solved, thanks a lot all , how to close this

Usually there is a "Close Issue"-button at the bottom of the issue (Next to the green "Comment")

**Comment by 304NotModified** [comment]
![image](https://user-images.githubusercontent.com/5808377/48580378-54288600-e91f-11e8-8dea-bf9362dc76f9.png)
