### ISSUE TITLE
NLog in a .NET Core console app without DI?

### ISSUE THREAD

**Issue by jez9999** [NLog/NLog#3011]
I know Microsoft are trying to prescribe the use of DI everywhere in .NET Core but frankly I think it's overkill for a very simple console app.  I'm writing a simple console app WITHOUT DI and I have no wish to use DI for my logging.  Can I use NLog in a .NET Core console app without DI, and if not, could a NuGet package be developed to allow me to do so?

**Comment by snakefoot** [comment]
NLog works fine on NET Core without any use of DI.

But if wanting to capture logging from libraries that depends on Microsoft Extension Logging, then you need to register NLog as Logging Provider (Using NLog.Extension.Logging).

P.S. If running application using through the system **dotnet**-executable then AppDomain.BaseDirectory changes and affects the default file-location `${basedir}`.

**Comment by jez9999** [comment]
@snakefoot Could you point me to any documentation that shows me how to use NLog in .NET Core without DI?  Like which NuGet packages to install?  Because the docs say that `NLog.Config` is [not supported in .NET Core](https://github.com/NLog/NLog.Extensions.Logging/wiki/Getting-started-with-.NET-Core-2---Console-application) and that you use DI for logging in a [console application](https://github.com/NLog/NLog.Extensions.Logging/wiki/Getting-started-with-.NET-Core-2---Console-application).

**Comment by snakefoot** [comment]
I recommend that you just add reference to NLog-nuget-package: https://www.nuget.org/packages/NLog/

And then manually add a NLog.config file to your project (Copy Always) with content from tutorial: 

https://github.com/NLog/NLog/wiki/Tutorial#configure-nlog-targets-for-output

**Comment by jez9999** [comment]
OK you're right, I got it to work quite easily without DI.  I might submit a PR for the [.NET Core README](https://github.com/NLog/NLog.Extensions.Logging/blob/master/README.md) to note that you don't actually have to use DI to use NLog with .NET Core as I think it's rather misleading at the moment.

**Comment by snakefoot** [comment]
@jez9999 Thank you for the PR. Guess this issue can be resolved?
