### ISSUE TITLE
NLog shuts down logging on SIGTERM

### ISSUE THREAD

**Issue by jez9999** [NLog/NLog#3012]
I'm using NLog on a Linux-deployed .NET Core 2.1 application.  I've turned on NLog's internal trace logging to see what's going on:

`
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" throwConfigExceptions="true" throwExceptions="true" internalLogFile="nlog.txt" internalLogLevel="Trace" internalLogToConsole="true">...</nlog>`

What happens is that NLog starts fine and logs stuff, but when I use `pkill dotnet` to send a SIGTERM to the process, NLog immediately shuts down even before I have called `NLog.LogManager.Shutdown`:

```
2018-11-10 19:40:17.2991 Info Shutting down logging...
[...]
2018-11-10 19:40:17.3623 Trace Closing Layout Renderer: ${level}
2018-11-10 19:40:17.3667 Trace Closing Layout Renderer: ${literal}
2018-11-10 19:40:17.3667 Trace Closing Layout Renderer: ${logger}
2018-11-10 19:40:17.3667 Trace Closing Layout Renderer: ${literal}
2018-11-10 19:40:17.3667 Trace Closing Layout Renderer: ${message}
2018-11-10 19:40:17.3667 Debug Finished closing logging configuration.
2018-11-10 19:40:17.3667 Info Logger has been shut down.
```

This means that when my code later tries to log out a message just before it shuts down, nothing happens because the logger has been shut down.  How can I stop the logger shutting down on a SIGTERM and instead make it wait for me to call `NLog.LogManager.Shutdown`?

**Comment by jez9999** [comment]
Possibly this is causing the problem:

https://github.com/NLog/NLog/blob/86169b0a2cbb6eb0914bc528dadbaf04e404403a/src/NLog/LogFactory.cs#L1527

It shuts down the logger as soon as the process exits, even if my code is still running and wanting to use the logger.  What can I do here?

**Comment by snakefoot** [comment]
@jez9999 What event to you react to for handling the shutdown signal in your application?

When ProcessExit or DomainUnload happens, then it usually means one should leave the burning house as fast as possible (avoid segmentation faults). That is why NLog tries to shutdown everything ASAP.

If you are reacting to ProcessExit, then you can "just" hook your own event-handler before starting to use NLog-objects (Including initialization of any static NLog Logger objects). Then your event-handler will be called first.

**Comment by jez9999** [comment]
@snakefoot My application reacts to `CurrentDomain_ProcessExit`.  Hooking up my event before getting the current class logger did indeed seem to work, thank you.  Presumably NLog is still registering its shutdown event too, though?  I wonder whether that could lead to a race condition.  Seems to me it would be cleaner if you could just tell NLog not to register its own shutdown events, and rely solely on you calling `NLog.LogManager.Shutdown()`.

**Comment by snakefoot** [comment]
@jez9999 NLog 4.6.8 introduces this property (Can also be assigned from NLog.config):

`NLog.LogManager.AutoShutdown = false;`
