### ISSUE TITLE
DatabaseTarget not found for xamarin.forms

### ISSUE THREAD

**Issue by tp16190** [NLog/NLog#3016]
In my xamarin.forms project I have installed Nlog package for logging errors in database. I have to configure Nlog programmitically but I dont found database target for xamarin.forms. Please resolve this issue as soon as possible.

**Comment by snakefoot** [comment]
If you need help with programming, then I recommend StackOverflow. Don't know much about helping xamarin.forms-developers

**Comment by tp16190** [comment]
My question is that all other targets(console, file etc..) are working with xamarin.forms. I am saying that in your "NLog/src/NLog/Targets/DatabaseTarget.cs" file you are not allowed this file for xamarin development why?. So all other targets works fine with xamarin but not databasetarget.

**Comment by snakefoot** [comment]
I guess one thought that database was not needed on iOS (iPhone) or Android, as it requires extra dependencies on System.Data + System.Transaction. See also #2676

Have you tried to use NetStandard ? Ex. Xamarin.Forms 2.5.0.280555 with NetStandard 2.0.1 and NLog 4.5.11

**Comment by tp16190** [comment]
I am using Xamarin.Forms 3.3.0.967583 with NetStandard 2.0.3 and NLog 4.5.11. I am unable to use databasetarget because it does not found in library.

**Comment by snakefoot** [comment]
Check the file properties of the NLog..dll does it say NetStandard?

Sent from my Sony Xperia


---- tp16190 wrote ----


I am using Xamarin.Forms 3.3.0.967583 with NetStandard 2.0.3 and NLog 4.5.11. I am unable to use databasetarget because it does not found in library.

**Comment by tp16190** [comment]
Nlog is successfully installed in my xamarin android project with NetStandard 2.0.3. But I dont found databasetarget class. please check "NLog/src/NLog/Targets/DatabaseTarget.cs" because you are using "#if !SILVERLIGHT && !__IOS__ && !__ANDROID__" above the namespace. So I think this is the reason for not found databasetarget class.

**Comment by tp16190** [comment]
Have you implementated databasetarget class for xamarin application or not? Because all other targets works using programmatically. See below code that works in my xamarin android application.


 var config = new LoggingConfiguration();

            var consoleTarget = new ConsoleTarget();
            config.AddTarget("console", consoleTarget);

            var consoleRule = new LoggingRule("*", LogLevel.Trace, consoleTarget);
            config.LoggingRules.Add(consoleRule);

            var fileTarget = new FileTarget();
            string folder = Environment.GetFolderPath(Environment.SpecialFolder.Personal);
            fileTarget.FileName = Path.Combine(folder, "Log.txt");
            config.AddTarget("file", fileTarget);

            var fileRule = new LoggingRule("*", LogLevel.Warn, fileTarget);
            config.LoggingRules.Add(fileRule);

            LogManager.Configuration = config;

**Comment by snakefoot** [comment]
You are probably using Android build of NLog instead of the NetStandard build

Sent from my Sony Xperia


---- tp16190 wrote ----


Nlog is successfully installed in my xamarin android project with NetStandard 2.0.3. But I dont found databasetarget class. please check "NLog/src/NLog/Targets/DatabaseTarget.cs" because you are using "#if !SILVERLIGHT && !IOS && !ANDROID" above the namespace. So I think this is the reason for not found databasetarget class.

**Comment by 304NotModified** [comment]
@tp16190 please post the properties op NLog.dll:

e.g.


![image](https://user-images.githubusercontent.com/5808377/48429177-e8062080-e76c-11e8-82c4-7a006195c665.png)

**Comment by tp16190** [comment]
I am giving sample code that is worked in xamarin.android (or ios).

        var config = new LoggingConfiguration();

        var consoleTarget = new ConsoleTarget();
        config.AddTarget("console", consoleTarget);

        var consoleRule = new LoggingRule("*", LogLevel.Trace, consoleTarget);
        config.LoggingRules.Add(consoleRule);

        var fileTarget = new FileTarget();
        string folder = Environment.GetFolderPath(Environment.SpecialFolder.Personal);
        fileTarget.FileName = Path.Combine(folder, "Log.txt");
        config.AddTarget("file", fileTarget);

        var fileRule = new LoggingRule("*", LogLevel.Warn, fileTarget);
        config.LoggingRules.Add(fileRule);

        LogManager.Configuration = config; 



Now If I am using below code that is not worked in xamarin.android (or ios)


            var config = new LoggingConfiguration();

            var databaseTarget = new DatabaseTarget();
            config.AddTarget("database", databaseTarget);


it give this error
The type or namespace name 'DatabaseTarget' could not be found (are you missing a using directive or an assembly reference?)

So error clearly say that NLog latest version not support databasetarget.

**Comment by 304NotModified** [comment]
> So error clearly say that NLog latest version not support databasetarget.

It's supported in .NET standard and Xamarin should use the .NET standard NLog.dll for this. 

We know it's not supported in the NLog for Xamarin and I'm not sure if we could even support this in that platform.

**Comment by 304NotModified** [comment]
could be helpful: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/internals/net-standard

**Comment by 304NotModified** [comment]
or maybe just replace the NLog.dll  in your bin folder:

unzip https://www.nuget.org/api/v2/package/NLog/4.5.11, get NLog.dll from netstandard2.0 folder

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, please let us know!

**Comment by snakefoot** [comment]
NLog 5.0 will extract the DatabaseTarget into its own nuget-package.
