### ISSUE TITLE
databaseTarget ConnectionString Programmatically Fails on Windows Server 2016

### ISSUE THREAD

**Issue by excelthoughts** [NLog/NLog#3020]
Hi

I am setting databaseTarget.ConnectionString like this in a C# Library called by both WebAPI and Windows services. 
This is how I use it for Windows services.

```
        static void Main()
        {
            //Windows service. Logging setup
            Task.Factory.StartNew(() => Log.Initialise());
        }

    public static async Task Initialise()
    {
      LoggingConfiguration config = LogManager.Configuration;
      DatabaseTarget dbTarget = (DatabaseTarget) config.FindTargetByName("database");
      string connectionString = await Log.GetLoggingConnectionString();
      databaseTarget.ConnectionString = connectionString;
      LogManager.ReconfigExistingLoggers();
}

```
It works 99% of the time, but today, one of the Windows Services was installed on Windows Server 2016, and I get the error (only in the InternalLog file and Windows event log) that the ConnectionString has not been initialized, and the Service crashes.

I have seen this before somewhere else but can't recall whether it was just with WebAPI services or another Windows service.

It works fine when the same Windows service is installed on Windows Server 2012. Is there some update that I need to allow this? Win Server 2016 has .NET 4.7 and 2012 is 4.6.1. 
Am I setting  databaseTarget.ConnectionString correctly?

Should  be doing this instead rather than setting the databaseTarget.ConnectionString directly?
`LogManager.Configuration.Variables["logConnectionString"] =  await GetLoggingConnectionString();`

**Comment by snakefoot** [comment]
Don't know how your database-target is configured in your NLog.config or what Nlog-version you are using (Why didn't you just fill out the issue-template?)

But I would use the GDC for global variables:

`ConnectionString="${gdc:item=logConnectionString}"`

And then assign the GDC when possible:

```
var logConnectionString = await Log.GetLoggingConnectionString();
GlobalDiagnosticsContext.Set("logConnectionString", logConnectionString);
```

Remember not to use `throwexceptions="true"` in the production environment. It is only for NLog unit-testing and last resort troubleshooting.

**Comment by excelthoughts** [comment]
Sorry I was not aware of the issue template.
NLog version 4.4.12

```
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd" autoReload="true" throwExceptions="false" internalLogLevel="Off" internalLogFile="c:\temp\nlog-internal.log">

    <targets>
      <target name="asyncDatabase" xsi:type="AsyncWrapper">
        <!--target named 'database',connectionString and commandText need to be present at a minimum-->
        <target name="database" xsi:type="Database" dbProvider="System.Data.SqlClient" connectionString="" commandText="">
        </target>
      </target>
    </targets>
    <rules>
      <!--write all logs to asyncDatabase-->
      <logger name="*" minlevel="Trace" writeTo="asyncDatabase" />
    </rules>
  </nlog>
```

I have read elsewhere (SO?) of people having issues with the GDC not working for them.

**Comment by snakefoot** [comment]
> I have read elsewhere (SO?) of people having issues with the GDC not working for them.

Not aware of any issues with GDC. Please provide links if you have any.

**Comment by snakefoot** [comment]
Btw. only dbProvider and commandText are required parameters for database-target (Not connectionString).

So your original code should work just fine:

`databaseTarget.ConnectionString = connectionString;`

Do you have an exception-stacktrace from the incident?

**Comment by excelthoughts** [comment]
[nlog-internal.log](https://github.com/NLog/NLog/files/2597405/nlog-internal.log)

The only exception was shown in EventViewer was a generic System.Exception

Faulting application name: HAMBS.TransferRequest.FileMonitor.exe, version: 1.0.0.0, time stamp: 0x5bcfbcc7
Faulting module name: KERNELBASE.dll, version: 10.0.14393.2189, time stamp: 0x5abda7d6
Exception code: 0xe0434352
Fault offset: 0x000daa12
Faulting process id: 0x1654
Faulting application start time: 0x01d47fb640e4fb57
Faulting application path: C:\HAMBS\TransferRequestFileMonitorService\HAMBS.TransferRequest.FileMonitor.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: bb579604-e677-44c8-9248-630de89e1220
Faulting package full name: 
Faulting package-relative application ID:

**Comment by snakefoot** [comment]
@excelthoughts Could you setup this:

https://docs.microsoft.com/en-us/dotnet/api/system.appdomain.unhandledexception?view=netframework-4.7.2

And write the exception tostring somewhere?

**Comment by snakefoot** [comment]
But still your application crashes with unhandled exception? 

Don't think NLog is the issue as it eats all exceptions unless using throwExceptions="true" (Which you should never use)

If you want to remove the error in the NLog Internal Logger, then probably have to remove `async` from `Initialise()`.

**Comment by snakefoot** [comment]
If your application crashes, then you can try and configure Windows to create a local minidump:

https://docs.microsoft.com/en-us/windows/desktop/wer/collecting-user-mode-dumps

Then you can load the minidump in Visual Studio and see the reason.

**Comment by excelthoughts** [comment]
Turned out to be firewall and blocked ports not returning the ConectionString from the remote server. Thanks for all your help.

**Comment by 304NotModified** [comment]
I'm glad is has been resolved 👍
