### ISSUE TITLE
Machine name greater than 15 characters truncated

### ISSUE THREAD

**Issue by amitsaha** [NLog/NLog#3024]
Hi, looking at how the current `machineName` is derived [code](https://github.com/NLog/NLog/blob/3a2f1214700464e969e92384ea80dcaffec49b4e/src/NLog/Internal/EnvironmentHelper.cs#L64), I see it reads the `ComputerName` environment variable which as per this [article](https://blogs.msdn.microsoft.com/brada/2005/08/11/environment-machinename-truncates-after-the-first-15-characters/) is by default limited to 15 characters. This is a problem for AWS instance IDs for example or any custom hostname that exceeds 15 characters.

**NLog version**: (e.g. 4.4.13)

`master`

**Platform**: 

.NET Framework/Windows

**Current NLog config** (xml or C#, if relevant)

NA

- What is the current result?

Machine name logged as: `I-03FB71646161E` .

- What is the expected result?

I was expecting the machine name should be the same as hostname (in my case, AWS instance ID
`i-03fb71646161e8626`)

- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?

Yes

- Please post full exception details (message, stacktrace, inner exceptions)

NA

- Are there any workarounds? yes/no

Not sure

- Is there a version in which it did work? 

No.

- Can you help us by writing an unit test?

Perhaps, if guided.

**Comment by amitsaha** [comment]
Thanks, @snakefoot - will give it a shot. If I get some guidance, I could try creating a PR as well.

**Comment by 304NotModified** [comment]
> Thanks, @snakefoot - will give it a shot. If I get some guidance, I could try creating a PR as well.

See https://github.com/NLog/NLog/wiki/How-to-write-a-custom-layout-renderer

**Comment by 304NotModified** [comment]
Need any help on this @amitsaha ?

**Comment by amitsaha** [comment]
hi @304NotModified - Plan to take a look at this in the next week.

**Comment by 304NotModified** [comment]
👍

**Comment by amitsaha** [comment]
@snakefoot @304NotModified done. please take a look. I went ahead and implemented a new layout renderer, since it probably makes more sense IMO.

**Comment by 304NotModified** [comment]
Fixed by #3071. Thanks!
