### ISSUE TITLE
Question:  GetLogger

### ISSUE THREAD

**Issue by mkantz84** [NLog/NLog#3034]
Hi,
I'm asking GetLogger for a specific target name (loggerName).
I'm getting back the full logger with all the targets, and then it writes to all my targets.
Am i doing something wrong?
What is the right way to get a specific target and to write only for that target?
here is my method:

```c#
public static void Info(string msg, Int64 brandId = 0, Int64 moduleId = 0, Int64 streamId = 0, string loggerName = "")

        {
            if (!string.IsNullOrEmpty(loggerName))
            {
                LogEventInfo theEvent = new LogEventInfo(LogLevel.Info, loggerName, msg);
                theEvent.Properties["brandId"] = brandId;
                theEvent.Properties["moduleId"] = moduleId;
                theEvent.Properties["streamId"] = streamId;

                log = NLog.LogManager.GetLogger(loggerName);    //asking for a specific target
                log.Log(theEvent);  //writes to all targets :(
            }
        } 
```

**Comment by snakefoot** [comment]
You might want to read about logging rules:

https://github.com/NLog/NLog/wiki/Tutorial#configure-nlog-targets-for-output
https://github.com/NLog/NLog/wiki/Configuration-file#rules

**Comment by mkantz84** [comment]
I am building the logger programmatically.
My problem is that all the targets are in 1 logger.
Is there a way to make more than 1 logger programmatically?
That way i could set specific targets to specific loggers and reach them easily.

**Comment by snakefoot** [comment]
@mkantz84 You have not shown any code about building target and logging-rules programmatically.

Have you read the tutorial: https://github.com/NLog/NLog/wiki/Tutorial#configure-nlog-targets-for-output

**Comment by snakefoot** [comment]
@mkantz84 And when you write to a logger what targets don't you want to write to? (Btw. can see you never register the fileTarget in the LoggingRules)

I can only recommend that you read more about how logging rules works. Ex this line will match all logger independent of name (LoggerName Wildcard = `"*"`):

> var rule = new LoggingRule("*", LogLevel.Info, databaseTarget);

**Comment by mkantz84** [comment]
OK.
Thank you very much!

**Comment by mkantz84** [comment]
@snakefoot You really helped me.
My problem was that i didn't understand the correlation between logging rules and loggers.
After i read the documentation properly it was very clear what do do.
Thanks very much!
