### ISSUE TITLE
I want to truncate message layout renderer after 30 characters in database logging.Any suggestion?

### ISSUE THREAD

**Issue by xaagarwal** [NLog/NLog#3040]
Hi! Thanks for reporting this feature/bug/question! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

QUESTIONS are preferred on StackOverflow. You could expect a faster response there (but do include all the info below). Use the tag "nlog" https://stackoverflow.com/questions/ask

For .NET Core users, please check the platform support: https://github.com/NLog/NLog/wiki/platform-support

**NLog version**: (e.g. 4.2.3)

**Platform**: .Net 3.5 / .Net 4.0 / .Net 4.5 / Mono 4 / Silverlight 4 / Silverlight 5 / Xamarin Android / Xamarin iOs / .NET Core 1 / .NET Core 2

**Current NLog config** (xml or C#, if relevant)

```xml
<nlog>
  <targets>
  </targets>
  <rules>
  </rules>
</nlog>

```

 - Why do we need it?
 - An example of the XML config, if relevant.

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, please let us know!

**Comment by snakefoot** [comment]
NLog 4.6.3 has been released, that allows you to do this:

`${message:truncate=30}`

See also https://www.nuget.org/packages/NLog

**Comment by Hellaren** [comment]
Is there any way I can add ellipsis at the end when message got truncated?
Similar to:
> Some pretty long messa...

**Comment by 304NotModified** [comment]
Please open a new issue, or even better, ask on StackOverflow
