### ISSUE TITLE
AutoClosingTimerCallBack threads causing app suspension

### ISSUE THREAD

**Issue by alexo00** [NLog/NLog#3046]
Nlog version: 4.5.11
.Net Framework  7.7.2
On our production environment yesterday we experienced unresponsiveness. Looking at the memory dump we noticed an unusual amount of nlog functions in threads which appear to be locking our system.

Can someone please assist us in determining what went wrong or what could have done wrong.
We currently log out only errors to a file and a database table.

![image](https://user-images.githubusercontent.com/46009236/50251948-87d45f80-0439-11e9-9f77-3f673919b35d.png)

Nlog Config: (removed tables names)

`<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="false"
      internalLogLevel="Off" internalLogFile="c:\temp\nlog-internal.log">

  
  <variable name="NlogConnectionString" value="tmp"/>
  
  
  <targets>
    <target xsi:type="File" name="logfile" fileName=""
            layout="${longdate}|Thread:${pad:padding=3:inner=${threadid}}|${pad:padding=5:inner=${level:uppercase=true}}|${all-event-properties:format=\[[key]\: [value]\]:separator=} ${message}"
            archiveAboveSize="30000000"
            archiveNumbering="Sequence"
            concurrentWrites="true"
            keepFileOpen="true"
            openFileCacheTimeout="10"/>

    
    <target  xsi:type="Database" name="db" connectionString="${var:NlogConnectionString}">

      <commandText>
        INSERT INTO SCHEMA.TABLE (Column1, Column2, Column3, Column4, Column5, Column6, Column7, Column8, Column9)
        VALUES(@VALUE1, @VALUE2, @VALUE3, nullif(@VALUE4,''),  @msg, nullif(@VALUE5,''), nullif(@VALUE6,''), nullif(@VALUE7,''), nullif(@VALUE8,'') );
      </commandText>
      <parameter name="@logdate" layout="${longdate}" />
      <parameter name="@msg" layout="${message}" />
      <parameter name="@level1" layout="${level}" />
      <parameter name="@PARAM" layout="${event-properties:item=PARAM}"/>
      <parameter name="@PARAM" layout="${event-properties:item=PARAM}" />
      <parameter name="@PARAM" layout="${event-properties:item=PARAM}" />
      <parameter name="@PARAM" layout="${event-properties:item=PARAM}" />
      <parameter name="@PARAM" layout="${threadid}" />
      <parameter name="@PARAM" layout="${event-properties:item=PARAM}" />

    </target>

    

    
  </targets>

  <rules>
    
    
    <logger name="*" minlevel="Error" writeTo="logfile" />
    <logger name="*" minlevel="Error" writeTo="db" />
  </rules>
</nlog>
`

**Comment by snakefoot** [comment]
Looks like you are using File-Targets from the screenshot, but those are not in your NLog.config?

Looks like you are initializing an NLog-target from the screenshot. Are you using NLog autoreload=true? Or are you perform explicit reload of NLog-config ? Or are you dynamically adding new NLog targets to the NLog-config? Or is the screenshot from the application hanging at startup?

**Comment by alexo00** [comment]
@snakefoot  Thank you for your response.

Sorry it must have got cropped while pasting (please find it below).
Yes we are using autoreload = true in the config.
We do the following dynamically:
1- adding the connection string to the database
2- Specifying the log file name
We then call LogManager.ReconfigExistingLoggers(); , the rest is controlled through the config.

The screen shot is from a memory dump analysed after the app was suspended and inactive. 
The app had been online for 5 days prior to the event, it wasn't on start up. 

<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="false"
      internalLogLevel="Off" internalLogFile="c:\temp\nlog-internal.log">

  
  <variable name="NlogConnectionString" value="tmp"/>
  
  
  <targets>
    <target xsi:type="File" name="logfile" fileName=""
            layout="${longdate}|Thread:${pad:padding=3:inner=${threadid}}|${pad:padding=5:inner=${level:uppercase=true}}|${all-event-properties:format=\[[key]\: [value]\]:separator=} ${message}"
            archiveAboveSize="30000000"
            archiveNumbering="Sequence"
            concurrentWrites="true"
            keepFileOpen="true"
            openFileCacheTimeout="10"/>

    
    <target  xsi:type="Database" name="db" connectionString="${var:NlogConnectionString}">

      <commandText>
        INSERT INTO SCHEMA.TABLE (Column1, Column2, Column3, Column4, Column5, Column6, Column7, Column8, Column9)
        VALUES(@VALUE1, @VALUE2, @VALUE3, nullif(@VALUE4,''),  @msg, nullif(@VALUE5,''), nullif(@VALUE6,''), nullif(@VALUE7,''), nullif(@VALUE8,'') );
      </commandText>
      <parameter name="@logdate" layout="${longdate}" />
      <parameter name="@msg" layout="${message}" />
      <parameter name="@level1" layout="${level}" />
      <parameter name="@PARAM" layout="${event-properties:item=PARAM}"/>
      <parameter name="@PARAM" layout="${event-properties:item=PARAM}" />
      <parameter name="@PARAM" layout="${event-properties:item=PARAM}" />
      <parameter name="@PARAM" layout="${event-properties:item=PARAM}" />
      <parameter name="@PARAM" layout="${threadid}" />
      <parameter name="@PARAM" layout="${event-properties:item=PARAM}" />

    </target>

    

    
  </targets>

  <rules>
    
    
    <logger name="*" minlevel="Error" writeTo="logfile" />
    <logger name="*" minlevel="Error" writeTo="db" />
  </rules>
</nlog>

**Comment by snakefoot** [comment]
Are you writing to a network path using the FileTarget ? (Filename is blank in the attached Nlog.config)

Not sure I understand the meaning of suspended/inactive. Do you mean deadlocked/frozen ?

**Comment by alexo00** [comment]
The file is written to the directory where our app is hosted , so not over the network (its configurable therefore we have made it dynamic , but in this instance its the same directory where the app which contains nlog is hosted) .
I mean locked not accepting connections due to it being suspended.

**Comment by snakefoot** [comment]
I guess you have to navigate through all the threads, and find the one that is holding the FileTarget.SyncRoot-lock but is stuck on something else (Ignore all other threads that are waiting for FileTarget.SyncRoot).

**Comment by alexo00** [comment]
Thanks very much @snakefoot  for your response I really appreciate your time.
I am currently looking into the above.

May I ask what would be best practice if I wanted to change the log location on the fly based on company for example (different folders).  Its all shared code , but would having a nlog configuration be the best practice here or a shared instance (what we currently have and we are changing the filename dynamically)

**Comment by snakefoot** [comment]
If the same running instance of the application is used by different companies at the same time, then I would probably use a scope-name-variable (See `${mdlc}`) or a logger-name-variable (See `${logger}`) in the FileTarget.FileName that matches company.

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, please let us know!
