### ISSUE TITLE
NLog Targets page

### ISSUE THREAD

**Issue by Mirimon** [NLog/NLog#3052]
Hello,

Logify, our application monitoring service, supports NLog. How our plugin can be included to your Targets page (https://nlog-project.org/config/?tab=targets)?

Information on our NLog plugin can be found here: https://logify.devexpress.com/Alert/Documentation/Send/IntegrationWithLogSystems/Net/NLog.

Source code is available here: https://github.com/DevExpress/Logify.Alert.Clients/tree/develop/dotnet/Logify.Alert.NLog.

I look forward to your reply.

Best Regards,
Alex
logify.devexpress.com

**Comment by snakefoot** [comment]
Just create pull-request here:

https://github.com/NLog/NLog.github.io/pulls

Updating this file:

https://github.com/NLog/NLog.github.io/blob/master/config/targets.json

Adding the new target with the following `"category": "Integrations (Cloud)"` and `"external": true,` (See others for inspiration)

If you want to be really helpful then please also update the following targets to have `"category": "Integrations (Cloud)"` :

- Gibraltar.Agent.NLog4
- AWS.Logger.NLog
- NLog.Extensions.AzureStorage
- Google.Cloud.Logging.NLog

**Comment by Mirimon** [comment]
Thank you. Created. Category of the Gibraltar.Agent.NLog4, AWS.Logger.NLog, NLog.Extensions.AzureStorage, Google.Cloud.Logging.NLog targets is also updated.

**Comment by 304NotModified** [comment]
👍 merged https://github.com/NLog/NLog.github.io/pull/79 for this :)
