### ISSUE TITLE
NLog.Schema not installed when adding NLog.Config

### ISSUE THREAD

**Issue by taori** [NLog/NLog#3054]
**Reproduction steps:**

Get netcore 3.0 preview sdk

- dotnet new wpf -n SomeProject
- open project
- add NLog
- add NLog.Config

While NLog.Config does reference NLog.Schema it does not end up getting referenced - Manually adding the package does work however.

**Comment by 304NotModified** [comment]
Thanks for reporting and writing explicit the steps 👍 

I think this is #2823, isn't?

**Comment by taori** [comment]
@304NotModified thanks for reply - yep. very much does look like it might be related to #2823

**Comment by 304NotModified** [comment]
OK thanks, closing this as duplicate. Thanks for reporting!
