### ISSUE TITLE
NLog don't create directories for logs

### ISSUE THREAD

**Issue by AlexeiScherbakov** [NLog/NLog#3066]
**NLog version**: 4.5.11

**Platform**: .NET Core 3

**Current NLog config** (xml or C#, if relevant)

```
var config = new LoggingConfiguration();
			// all warnings
			{
				FileTarget warningTarget = new FileTarget()
				{
					FileName = "logs\\warnings.log",
					CreateDirs = true,
				};
				var rule = new LoggingRule("*", LogLevel.Warn, warningTarget);
				config.LoggingRules.Add(rule);
			}
			// all other debug
			{
				FileTarget debugLastStartupTarget = new FileTarget
				{
					ArchiveNumbering = ArchiveNumberingMode.DateAndSequence,
					ArchiveOldFileOnStartup = true,
					FileName = "logs\\All\\debug.log",
					CreateDirs=true,
				};
				var rule = new LoggingRule("*", LogLevel.Debug, debugLastStartupTarget);
				config.LoggingRules.Add(rule);
			}


			LogManager.Configuration = config;
```

- What is the current result? At application start, directories "logs" & "logs\All" are not exists. When app starts - it throw exception System.IO.DirectoryNotFoundException: 'Could not find a part of the path 'd:\Projects\Project1\src\ConsoleTest\bin\Debug\netcoreapp3.0\logs\All\debug.log'.'

- What is the expected result? All directories for log files must be created by NLog internally
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)? No
- Please post full exception details (message, stacktrace, inner exceptions) - System.IO.DirectoryNotFoundException: 'Could not find a part of the path 'd:\Projects\Project1\src\ConsoleTest\bin\Debug\netcoreapp3.0\logs\All\debug.log'.' after write Info in Logger class. 
- Are there any workarounds? yes - manually create directories
- Is there a version in which it did work? Under standard .NET Framework all is ok
- Can you help us by writing an unit test?

**Comment by 304NotModified** [comment]
Yes indeed, this is by design (performance reasons) - https://github.com/NLog/NLog/issues/2822#issuecomment-410061904

@snakefoot maybe we shouldn't log this internal exception in the internal log? It's by design, so not really an exception.

**Comment by snakefoot** [comment]
@304NotModified Just like with #2822 then I think that the exception is detected by running the code  inside Visual Studio Debugger.

If wanting to make special handling of this, then one should perform a directory-exist-check for the very first LogEventInfo for a FileTarget (Skipping this check for all the following).

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, please let us know!
