### ISSUE TITLE
Many 1kb log files generated when change system date for FileTarget

### ISSUE THREAD

**Issue by tanguohao** [NLog/NLog#307]
1. Config the Nlog to daily archive and target is a FileTarget
2. While the system is running and many processes will write log to NLog, CHANGE THE SYSTEM DATE.
3. You will see there are a lot of 1KB log files.

Detailed description in the forum:
https://groups.google.com/forum/#!topic/nlog-users/-V4b0z4QQTc

**Comment by ilya-g** [comment]
> `if (long.Parse(ts) < long.Parse(ts2))`

Date format string may be MMDDYYYY for example, or contain some non-digit characters, so parsing it to long and then comparing the resulting values may fail or give the incorrect result.

**Comment by 304NotModified** [comment]
We know the date format, so we can parse to datetime?

**Comment by ilya-g** [comment]
Not sure if we can parse back date formatted with any possible date format, but with DateTime.TryParseExact and a reasonable fallback behavior this solution can be given a chance.

**Comment by 304NotModified** [comment]
It would be nice if someone could retest this with NLog 4.3 (RC)

**Comment by 304NotModified** [comment]
We think this is a non-issue. Don't change your time of your machine. So closing this.

Please let us know if some disagrees
