### ISSUE TITLE
NLog badly includes Jetbrains resharper attributes

### ISSUE THREAD

**Issue by abrevinci** [NLog/NLog#3070]
**NLog version**: 4.5.10
**Platform**: .NET Core 2

- What is the current result?
When trying to use the UsedImplicitly and PublicAPI attributes in a project I get resharper errors pointing out that these are internal. They worked fine until I tried to add NLog to the project and sure enough, NLog has its own version of these that are internal since #292 (this was fixed in a way to allow it to compile at all). But why the heck does NLog embed these? I couldn't believe my eyes. Please reference the jetbrains.annotations package like everyone else. 
- What is the expected result?
NLog should not interfere at all in any way with the Jetbrains annotations package.
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
Not relevant
- Please post full exception details (message, stacktrace, inner exceptions)
Not relevant
- Are there any workarounds? yes/no
It compiles but I can't get rid of the resharper errors/squiggly lines. A suggested workaround here https://stackoverflow.com/questions/24047368/why-does-nlog-dll-contain-a-jetbrains-annotations-namespace is not possible in this net core project.
- Is there a version in which it did work? 
Not sure
- Can you help us by writing an unit test?
Not applicable

**Comment by snakefoot** [comment]
Sounds like a bug in Resharper, since NLog is a third-party framework and uses recommended internal class approach.

See "third-party frameworks" here: https://blog.jetbrains.com/dotnet/2015/08/12/how-to-use-jetbrains-annotations-to-improve-resharper-inspections/

Have you tried to contacting Resharper people instead?

**Comment by ericnewton76** [comment]
And frankly its nice that NLog doesnt include direct references to Jetbrains assemblies... 

Oy vey, to have to drag those around too... LOL!

**Comment by 304NotModified** [comment]
See also "Embedding declarations of code annotations in your source code" https://www.jetbrains.com/help/resharper/Code_Analysis__Annotations_in_Source_Code.html

**Comment by 304NotModified** [comment]
Closing as this is an external issue
