### ISSUE TITLE
Nlog.Config (4.5.11) missing richtextbox in XSD

### ISSUE THREAD

**Issue by neilw1** [NLog/NLog#3086]
Hello,
Regarding the Nlog.Config nuget package (not Nlog, but nlog.config), you have not kept the XSD in this package in sync with the current version:

When you install this package to get a starter config, it also brings down the XSD that the project then uses.

However, if you try and add a RichTextBox (target xsi:type="RichTextBox") you get an XSD error on the page saying the type does not exist, because it is using this XSD to parse the file, which does not have RichTextBox defined as a type.

Delete the XSD and everything works.

**Comment by 304NotModified** [comment]
Only the targets of the core package (NLog nuget package) are in the XSD. 



> you get an XSD error on the page saying the type does not exist

You can ignore that error. NLog will still work.

**Comment by neilw1** [comment]
So richtextbox is not in the core package? How are you supposed to know? All I did was download NLog from nuget, I didn't have to get any other packages for rich text box support...

**Comment by 304NotModified** [comment]
> So richtextbox is not in the core package

No it's not in the NLog package, but in NLog.Windows.Forms, see also https://nlog-project.org/config/?tab=targets&search=richtextbox

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, please let us know!
