### ISSUE TITLE
RichTextBox target stops all logging targets from working

### ISSUE THREAD

**Issue by neilw1** [NLog/NLog#3087]
Hello,
When I add the richtextbox as below (there are no parse errors in VS, and it's a copy from the website) I get no logging at all, either to the text box, console or file. If I remove the richtextbox entry, everything work as normal.

Any idea what is going wrong? the name of the form and text box is valid, but even if wrong I wouldn't expect all the other loggers to fail because one target failed.

I am creating my logger in the form class as follows:
        private static Logger logger = LogManager.GetLogger("XXXX");

      <?xml version="1.0" encoding="utf-8" ?>
      <nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
        <variable name="dateFormat" value="${date:format=yyyy-MM-dd HH\:mm\:ss}"/>
        <targets>
          <target name="logfile" xsi:type="File" fileName="MissingUPRN.log"
                  layout="${dateFormat} ${level}: ${message} ${exception:format=ToString,StackTrace}" />
          <target name="console" xsi:type="Console"
                  layout="${dateFormat} ${level}: ${message}" />
          <target xsi:type="RichTextBox"
                    name="textbox"
                    layout="${longdate}|${level:uppercase=true}|${logger}|${message}"
                    autoScroll="True"
                    maxLines="100"
                    controlName="richTextBox1"
                    formName="MainApplication"
                  />
        </targets>
    
        <rules>
          <logger name="*" minlevel="Trace" writeTo="logfile" />
          <logger name="*" minlevel="Trace" writeTo="console" />
          <logger name="*" minlevel="Trace" writeTo="textbox" />
        </rules>
      </nlog>

**Comment by 304NotModified** [comment]
Hi, please check [troubleshooting guide](https://github.com/NLog/NLog/wiki/Logging-troubleshooting). If this is still an issue, please post the full internal log (trace level)

**Comment by neilw1** [comment]
Ok, so when I searched google for adding text box support, I got to the relevant pages, but there wasn't anything telling me I needed a separate package, nlog.windows.forms :)

So, I've downloaded that and it still fails, so I'll see about tracng as you suggested.

However, if it is a simple case of a missing package, surely it would be better to continue working for the targets specified and ignoring the one failing, not aborting all of Nlog without any meaningful error...

**Comment by 304NotModified** [comment]
> surely it would be better to continue working for the targets specified and ignoring the one failing

I'm pretty sure it's doing that?



> telling me I needed a separate package, nlog.windows.forms :)

That' kind of info is also available here: https://nlog-project.org/config/

**Comment by neilw1** [comment]
Well, the problem, is I didn't download the windows form package as I got myself to the page via google and found everything I thought I needed - my mistake. However, that caused the logger to not output anything to my console or file with the 'richtextbox' target.

So, my only problem is it seems to not find my 'MainApplication'.

thanks anyway.
