### ISSUE TITLE
[Question] : How to Ignore a property?

### ISSUE THREAD

**Issue by HesamKashefi** [NLog/NLog#3099]
Hi, 
When using structured logging like : 
`_logger.Log('Data: {@data}', data);`
This logs every property of data with extremely high depth, so I want to ignore a property from being serialized by attribute or something or limit the Max Depth of logger.
I tried [JsonIgnore] and [IgnoreDataMember] and excludeProperties on Target but they didn't work.

**Comment by snakefoot** [comment]
Sounds like a good idea to support `IgnoreDataMember`-attribute for properties. PR are welcome.

You can inject your own `IJsonConverter` at `https://github.com/NLog/NLog/wiki/How-to-use-structured-logging#i-like-to-use-jsonnet-for-creating-json` and do special handling for your special object:

See also: https://github.com/NLog/NLog/wiki/How-to-use-structured-logging#i-like-to-use-jsonnet-for-creating-json

**Comment by 304NotModified** [comment]
Another quick option is to:

-  Write the ToString on your type and do a data.ToString()
- Convert the instance before logging

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, please let us know!

**Comment by jordanhammond** [comment]
What about doing this when using DI such as Autofac?

**Comment by snakefoot** [comment]
NLog 5.0 will make it easier to override the IJsonConverter by hooking up a dependency-injection-container. See also:  #3666

NLog 4.7 will includes #3610 that will allow one to transform objects into anonymous-objects with only the wanted properties.
