### ISSUE TITLE
File target: Date based file archiving + max file size

### ISSUE THREAD

**Issue by Kaarel** [NLog/NLog#310]
The following configuration creates archives based on date (and time) but only keeps the last 1KB of the specified date.
```xml
<target xsi:type="File"
      archiveFileName="${logDir}\example.{#}.log"
      archiveNumbering="Date"
      archiveEvery="Minute"
      archiveDateFormat="yyyy-MM-ddTHH-mm"
      archiveAboveSize="1024" />
```
So example.2014-02-10T12-01.log would only contain the last 1KB of logs. Any earlier log entries for that minute will be lost.

What I'm looking for is something similar to log4net Composite behaviour (http://logging.apache.org/log4net/release/sdk/log4net.Appender.RollingFileAppender.RollingMode.html). That is I need the current date based archive file naming but I need to set maximum file size per archive file. This is useful when an issue causes unexpectedly large amounts of log data creating huge, gigabyte size log files. Smaller files would be much easier to work with, especially when accessing them over a network share.

So either the above should produce multiple archive files per minute (example.2014-02-10T12-01.1.log, example.2014-02-10T12-01.2.log etc) while honoring the maxArchiveFiles attribute or the desired behaviour should be achieved with an new attribute **maxArchiveSize** which could be more explicit.

**Comment by 304NotModified** [comment]
The pull request has been merged. Thus I assume the issue has been fixed. If not, then just re-open the issue.
(https://github.com/NLog/NLog/pull/449)
