### ISSUE TITLE
Integration instructions for a .NET Core 2.2 App

### ISSUE THREAD

**Issue by siliconplains44** [NLog/NLog#3102]
Does anyone out there have step by step instructions on how to properly integrate NLog with a .net Core 2.2 web api?  I was looking through existing docs and they appear to have a different code format from what is gened up in Visual Studio 2019 2.2 web apis.

**Comment by snakefoot** [comment]
Please give code-example from Program.cs. One is no longer building host-environment, so `UseNLog()` is impossible?

Btw. I think you will reach a larger audience on stackoverflow with your question.

**Comment by siliconplains44** [comment]
Here is my Program.cs.  

public class Program
    {
        public static void Main(string[] args)
        {
            // NLog: setup the logger first to catch all errors
            var logger = NLog.Web.NLogBuilder.ConfigureNLog("nlog.config").GetCurrentClassLogger();
            try
            {                
                logger.Debug("init main");                
            }
            catch (Exception ex)
            {
                //NLog: catch setup errors
                logger.Error(ex, "Stopped program because of exception");
                throw;
            }
            finally
            {
                // Ensure to flush and stop internal timers/threads before application-exit (Avoid segmentation fault on Linux)
                NLog.LogManager.Shutdown();
            }

            CreateWebHostBuilder(args).Build().Run();
        }

        public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>();
    }

**Comment by snakefoot** [comment]
This part:
```c#
public static IWebHostBuilder CreateWebHostBuilder(string[] args)
    =>  WebHost.CreateDefaultBuilder(args)
        .UseStartup<Startup>();
```
Should changed into this part:
```c#
public static IWebHostBuilder CreateWebHostBuilder(string[] args)
    =>  WebHost.CreateDefaultBuilder(args)
        .UseStartup<Startup>()
        .UseNLog();   /// Remember to have using NLog.Web;
```
Just like it is written here: https://github.com/NLog/NLog.Web/wiki/Getting-started-with-ASP.NET-Core-2#4-update-programcs

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, please let us know!
