### ISSUE TITLE
[Question] Nested Replace

### ISSUE THREAD

**Issue by lickou** [NLog/NLog#3108]
Hello,
I was wondering if it's possible to do nested replace like this
`<variable name="test" value="${replace:searchFor=]:replaceWith=|]:regex=true:inner=${replace:searchFor=[:replaceWith=|[:regex=true:inner=${message}}}" />`
or any other way to achieve this? The goal is to replace certain characters
Thanks

**Comment by 304NotModified** [comment]
Yes, that should work!

**Comment by lickou** [comment]
but it didn't :(
this is how I'm using the variable in target:
`<target name="console" xsi:type="Console" layout="${test}" />`
but the variable is empty

**Comment by lickou** [comment]
when I remove the nested code it worked, am I doing something wrong with the nested part?

**Comment by 304NotModified** [comment]
Could you please try without using a variable?

**Comment by 304NotModified** [comment]
is this really a regex? `[` isn't a regex value? I think for both regex should be `false`

**Comment by lickou** [comment]
The regex value was the problem, setting it to false solved it!!
Thanks a lot!

**Comment by 304NotModified** [comment]
I'm glad is has been resolved 👍
