### ISSUE TITLE
File target: maxArchiveAge

### ISSUE THREAD

**Issue by Kaarel** [NLog/NLog#311]
I'd like to propose **maxArchiveAge** (or similar) attribute to File target. The idea is I want to keep the last x days worth of archives. I would expect this to work with **maxArchiveFiles**, whichever is hit first. If one is not specified, only the other should be used.

The syntax should default to days but for convenience might accept "3d" (for days), "1w" (for weeks), "8h" (for hours) etc.

**Comment by luigiberrettini** [comment]
This is somewhat related to issue #150 and it will be really useful also when using NLog with **daemons/services.**

It would be great if we could also **issue the deletion/archival programmatically** e.g. at each scheduled execution in a daemon/service using Quartz scheduler or simply at each loop iteration.

I achieved something similar to this behavior, but I think it's only a workaround:
https://github.com/luigiberrettini/NLogArchivingForDaemons

**Comment by 304NotModified** [comment]
I think it would be nice to extend NLog so quartz can be hooked easily on it.

**Comment by luigiberrettini** [comment]
My solution breaks when running tests (I think because of some parallel execution).
I ended up changing file name and manually deleting old files on each run.

**Comment by snakefoot** [comment]
Resolved with  #3714
