### ISSUE TITLE
Update SHFB docs

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#3115]
Update https://nlog-project.org/documentation/

for NLog 4.6

**Comment by ozjekaporlis** [comment]
i want to help with this issue. Can you guide me?

**Comment by 304NotModified** [comment]
hi!

Thanks for the help!

The https://github.com/NLog/NLog/blob/dev/src/Docs/NLog.shfbproj should be run (maybe tweak some bit), with all updated dlls (also need maybe some more dlls). 

Then we need a PR to https://github.com/NLog/NLog.github.io/tree/master/documentation

Any experience with SHFB?

**Comment by ozjekaporlis** [comment]
I'm wrote you gitter.im

**Comment by 304NotModified** [comment]
updated here: https://nlog-project.org/documentation/v4.6.0/

Still need to change the index.html (https://nlog-project.org/documentation)
