### ISSUE TITLE
NLog 4.6+ enhancements 

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#3122]
**[snakefoot](/snakefoot)** commented:
>  Would like to have these fixed before the final NLog 4.6:

- [x] NetworkTarget improvement by stealing KeepAlive-config from SysLog-Target. (4.6 rc2 - #3124)
- [ ] DatabaseTarget with AllowDbNull-property for parameter
- [ ] XmlDocLayout as HeaderFooter-Layout that inserts `<?xml>` with attributes.
- [ ] Service Fabric Shared Process support by reducing the number of static variables
  - [ ] Allowing multiple concurrent `${configsetting}`-lookups
  - [ ] Allowing multiple factory CreateInstance-overrides with different dependency injection-sources.

**Comment by 304NotModified** [comment]
@snakefoot sounds good, although I will release NLog 4.6 RTM ASAP when the docs are ready.

I think all of them could be also 4.6.1?

**Comment by snakefoot** [comment]
Would really like to have the Service Fabric Shared Process improvements included in the NLog 4.6 release.

**Comment by 304NotModified** [comment]
> * DatabaseTarget with AllowDbNull-property for parameter

What would this one do?

**Comment by snakefoot** [comment]
> What would this one do? (error checking? conversion?)

There is a "hole" in the logic for DbType-Value-onversion. Should empty-string become the default value or should empty-string become DbNull ? (Maybe a setting could help there)

**Comment by 304NotModified** [comment]
There is a dbnull layout renderer for that ;)

(But maybe bit more clumsy to configure and lesser performance in combination with a conditional)

**Comment by snakefoot** [comment]
> There is a dbnull layout renderer for that ;)

If the Layout is more complex that a single LayoutRenderer then it always become string-output (RawValue) stops working.

You cannot do this: `${event-properties=hello:whenEmpty:${db-null}}`

**Comment by 304NotModified** [comment]
The whenEmpty could handle this? (Well not now, but ok)

**Comment by snakefoot** [comment]
Yes whenEmpty could try to to support IRawValue-interface, but then need to signal that it fails incase that fallback-Layout does not support IRawValue-interface.

**Comment by 304NotModified** [comment]
Maybe we should move to the "try pattern" then?

**Comment by snakefoot** [comment]
@304NotModified Think these are things that not going to happen soon:

-  `DatabaseTarget with AllowDbNull-property for parameter` was my thinking one could do something like `DataColumn.AllowDBNull` but it will not be supported by many DbProviders.
-  `XmlDocLayout as HeaderFooter-Layout that inserts <?xml> with attributes.` - Discovered XmlColumn works fine without this one and one can work-around using a compound-layout. Maybe an up-for-graps task ?
- `Service Fabric Shared Process support by reducing the number of static variables` - This has now been post-poned for NLog 5.0

**Comment by 304NotModified** [comment]
> * `DatabaseTarget with AllowDbNull-property for parameter` was my thinking one could do something like `DataColumn.AllowDBNull` but it will not be supported by many DbProviders.

I think it's nice, but haven't seen much requests for it

> * `XmlDocLayout as HeaderFooter-Layout that inserts <?xml> with attributes.` - Discovered XmlColumn works fine without this one and one can work-around using a compound-layout. Maybe an up-for-graps task ?

Good idea!

> * `Service Fabric Shared Process support by reducing the number of static variables` - This has now been post-poned for NLog 5.0

Yes, I think it would be great to have, but designing this good is some work

I also like to split this issue in others and close it.

**Comment by snakefoot** [comment]
Created feature issue #3126 and created pull-request #3616 to resolve this.

Will defer xml-header/footer-layout until someone comes looking for it.
