### ISSUE TITLE
tests NLogDotDllDotNLogTest fails with The process cannot access the file 'NLog.dll' because it is being used by another process.

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#3123]
NLog.UnitTests.ConfigFileLocatorTests.NLogDotDllDotNLogTest [FAIL]
      System.IO.IOException : The process cannot access the file 'NLog.dll' because it is being used by another process.
:

see https://ci.appveyor.com/project/nlog/nlog/builds/22420526

**Comment by snakefoot** [comment]
Working build:

> Successfully installed 'OpenCover 4.6.519' to C:\projects\nlog

Non-working build:

> Successfully installed 'OpenCover 4.7.922' to C:\projects\nlog

Guess we should use the old version until NLog 4.6 is done to avoid more noise.

Will be resolved with #3132
