### ISSUE TITLE
readthedocs?

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#3125]
(@snakefoot)

I was experimenting with readthedocs for NLog (see first example https://docs.nlog-project.org/)

Why? Because the docs in wiki are difficult to search and to structure, also the layout is not that good (too small for code examples IMO)

Pro readthedocs

- Search!
- Really quick build times after push (<1 min)
- generation of TOC
- possible to style (inject css in possible)
- custom domain, including SSL
- works better on mobile compared to Github wiki
- "edit on github" link is nice
- versioning of docs

Cons

- No wiki anymore 
- We need to move to restructuredtext (RST) for TOC and other advanced features (but there is a converter)
- Syntax of RST is much complexer compared to MarkDown (IMO)
- Conversion and rendering of Markdown is incomplete (e.g. tables, headings syntax, internal link syntax), so we have to check every file (203 files)
- Not sure if we could like all documents (e.g. all targets) in one page dynamically (but I could write a tool for that)
- Not fully integrated into website (https://nlog-project.org)
- No WYSIWYG
- How to setup a redirect? (for old links on Google etc)

Other options are: GitHub pages (https://www.mkdocs.org/), custom page online (e.g. Wordpress),  https://www.siteleaf.com/

@snakefoot please your opinion

**Comment by snakefoot** [comment]
I find that quality of documentation comes from the people writing it, and seldom from the platform for hosting the documentation. Of course if the platform is completely impossible to use (No editor, No history, etc) then it might be a stopper.

Regarding search then I guess most people google or use stackoverflow, and will ignore any local search engines.

I find the Github-wiki okay. So it has be some very good arguments to change, as there will be a lot of broken links

**Comment by 304NotModified** [comment]
This is also nice, https://dotnet.github.io/docfx/ :)

**Comment by 304NotModified** [comment]
I think it would be nice if there was one clear "getting started" (with all the variants, asp.net core, non-core etc). Now it's on different places.
