### ISSUE TITLE
Improve Service Fabric Shared Host Support

### ISSUE THREAD

**Issue by snakefoot** [NLog/NLog#3126]
NLog have several static-property-points that makes it easy to use for standard console-/monolith-applications.

If needing to have more advanced setup, then the goto-location is the LogFactory. But if using dependency injection then one will run into the wall `ConfigurationItemFactory.Default`.

I think ConfigurationItemFactory should be a member on LogFactory. And the `ConfigurationItemFactory.Default` should just be the `LogManager.LogFactory.ItemFactory`-instance.

I also think that ConfigurationItemFactory has become polluted as its factory role have been expanded into something different (JsonConverter + ValueFormatter + PropertyTypeConverter)

**Comment by 304NotModified** [comment]
> I also think that ConfigurationItemFactory has become polluted as its factory role have been expanded into something different 

Agree, we need a DI container/interface

**Comment by snakefoot** [comment]
Try to have two LogFactory-setups running side-by-side but with different override of `ConfigurationItemFactory.Default.CreateInstance`

**Comment by 304NotModified** [comment]
I think we could remove these dependencies:

![image](https://user-images.githubusercontent.com/5808377/52920445-9f7e7600-330c-11e9-879c-475cff9a8152.png)

**Comment by snakefoot** [comment]
> I think we could remove these dependencies:

Those are not dependencies. It just the AppDomain-interface. It is fine with me. Only one AppDomain.

**Comment by snakefoot** [comment]
Actually my suggestion is to inject the LogFactory into the `ConfigurationItemFactory`-instance. So I want to make it even more dependent.

Then create a new "proper" class for holding  JsonConverter + ValueFormatter + PropertyTypeConverter that also lives on LogFactory, and then `ConfigurationItemFactory` instance can just forward.

**Comment by snakefoot** [comment]
But I'm curious about the cost of creating ConfigurationItemFactory-instance, and whether all the default assembly scanning within the AppDomain should only be done once. Even if creating multiple LogFactory-instances.

**Comment by 304NotModified** [comment]
> But I'm curious about the cost of creating ConfigurationItemFactory-instance,

Currently expensive I'm afraid.

**Comment by 304NotModified** [comment]
> Try to have two LogFactory-setups running side-by-side but with different override of `ConfigurationItemFactory.Default.CreateInstance`

Can't you inject a factory in between?

**Comment by snakefoot** [comment]
> Can't you inject a factory in between?

How would you recognize which LogFactory is loading a configuration?

**Comment by 304NotModified** [comment]
not I guess. Difficult case without a code example ;)

**Comment by snakefoot** [comment]
Imagine two LogFactory-instances that tries this stunt: https://github.com/NLog/NLog.Web/issues/248#issuecomment-399579074

**Comment by snakefoot** [comment]
Created PR #3128 as first step to improve shared-process-support with dependency-injection.

**Comment by 304NotModified** [comment]
created a more abstract issue -> https://github.com/NLog/NLog/issues/3362

**Comment by snakefoot** [comment]
Resolved by #3675
