### ISSUE TITLE
NLog not writing in development environment

### ISSUE THREAD

**Issue by zinduyaar** [NLog/NLog#3130]
I have been trying to implement NLog in an Asp.Net Core Web Api app. This is my nlog.config:

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      internalLogLevel="Trace"
      internalLogFile=".\logs\internal-nlog.txt">

  <extensions>
    <add assembly="NLog.Web.AspNetCore"/>
  </extensions>

  <targets>
    <target xsi:type="File" name="allfile" fileName="${basedir}\logs\nlog-all-${shortdate}.log"
            layout="${longdate}|${event-properties:item=EventId_Id}|${uppercase:${level}}|${logger}|${message} ${exception:format=tostring}" />
  </targets>

  <rules>
    <logger name="*" minlevel="Trace" writeTo="allfile" />
  </rules>
</nlog>
```

The code works fine for local host, it creates and write logs to it, but, it does not work in development environment, though it is able to create a log file in development environment but it does not write anything to it.

I have already tested for permissions by creating a text file in the same folder in development environment.

Any ideas what could be the problem here?

**Comment by 304NotModified** [comment]
Hi, please check [troubleshooting guide](https://github.com/NLog/NLog/wiki/Logging-troubleshooting). If this is still an issue, please post the full internal log (trace level)

**Comment by zinduyaar** [comment]
Are you talking of internal log created by NLog? 
It does not write anything to even that internal log file.

And, I think I have already tried almost all things from troubleshooting guide

Thanks

**Comment by snakefoot** [comment]
Try and specify an absolute working path for `internalLogFile=` and if still no output, then it is because you have an issue with deployment of `nlog.config`.

You can also try and activate the InternalLogging at runtime, before creating the first NLog-Logger (Be aware of static Logger-objects). See https://github.com/NLog/NLog/wiki/Internal-Logging

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, please let us know!
