### ISSUE TITLE
IRawValue - support for renderers that *could* have layouts

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#3139]

**Comment by Page-Not-Found** [comment]
@304NotModified - After about 2 years, I am ready to support nlog again. Is this up for grabs?

**Comment by 304NotModified** [comment]
Hey! Cool!

I think this is a hard one start with, but you could give it a try. :)

**Comment by Page-Not-Found** [comment]
Could you add a little more detail?

**Comment by 304NotModified** [comment]
We like to get this working:

https://github.com/NLog/NLog/pull/3140/files#diff-b8f49ba5c2431083e904f0e421818acb

So one of the results of the ${when} is a Irawvalue layout, and the other isn't (of course both or none should also work).

I think this should work also in more renderers, but ${when} is an example.

related changes (after the test of #3140?) #3165, #3144, #2973
