### ISSUE TITLE
How to: Does NLog work with Async code with MVC 5 in any specific case?

### ISSUE THREAD

**Issue by ttaylor29** [NLog/NLog#3149]
I am doing some research on what is the best way to log errors in our MVC 5 application.

We have a lot of async code. Is there a good way to use NLog to log errors on different threads? I know in WPF, we have to add a try/catch at the highest level. Is there a way to maybe add an attribute for async code error handling?

**Comment by 304NotModified** [comment]
It isn't a problem to log in different threads. B

But do notice that some information isn't available in all threads, e.g. the httpContext

**Comment by snakefoot** [comment]
@ttaylor29 Not sure what you are looking for. Maybe something like Fody ?

But maybe this pseudo code might make the error-logging easier for you:

```c#
public static class TaskExtensions
{
    static Logger TaskLogger = LogManager.GetCurrentClassLogger();

    public static Task LogOnFaulted(this Task task, [System.Runtime.CompilerServices.CallerFilePath] string contextInfo = "")
    {
            return task.ContinueWith((t,state) => TaskLogger.Error(t.Exception, state), contextInfo, TaskContinuationOptions.OnlyOnFaulted);
    }

    public static Task LogContinueWith(this Task task, [System.Runtime.CompilerServices.CallerFilePath] string contextInfo = "")
    {
            return task.ContinueWith((t,state) => if (t.Exception != null) TaskLogger.Error(t.Exception, state), contextInfo);
    }
}
```

Then you can probably do something like this:

```c#
var task = await mytask.LogOnFaulted();
```

NLog works very well in an async and multi-threaded environment. NLog takes great care in capturing the state of parameters provided to the log-write operations when needed. NLog Layout logic makes it very easy to capture context in the async operations (allowing one to track threadid, correlationids, etc.)

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, please let us know!

**Comment by ttaylor29** [comment]
Yes, this should help. Thank you.
