### ISSUE TITLE
Show Exception Type in serialized ExceptionLayoutRenderer

### ISSUE THREAD

**Issue by sharonrk** [NLog/NLog#3151]
When using the serialize formatter for exceptions, we don't get to see the exception type, which makes it a challenge to use. I know I can add the type formatter as well but then it won't be part of the json and won't be shown for inner exceptions. I could also add an inner exception formatter but the serializer will still serialize the inner exceptions so it ends up with a lot of bloat. 
I would like to see Type added as a fake property of all exceptions in the json. 

**NLog version**: 4.5.11

**Platform**: .Net 4.5

**Current NLog config** (xml or C#, if relevant)

```c
private const string Layout ="${message}${onexception:${newline}${exception:format=@}";
```

**Comment by snakefoot** [comment]
You can try and upgrade to NLog 4.6-rc1 as it will include this PR: #2989

https://www.nuget.org/packages/NLog/4.6.0-rc1

**Comment by sharonrk** [comment]
Thank you!
