### ISSUE TITLE
Sending Error Emails in Nlog? .net Core 2.1

### ISSUE THREAD

**Issue by chobo2** [NLog/NLog#3152]
Hi

I am a bit confused, I am not sure if since I can am using asp.net core if I can send out emails when an error occurs?

I found this: https://github.com/nlog/NLog/wiki/Mail-target

but it says: Supported in .NET, .NET Standard 2.x and Mono  but no mention of .net Core?

I am also using sendGrid so not sure if this would cause problems or not?

**Comment by 304NotModified** [comment]
.net core implements .net standard, so yes it supports .net core. See 
https://docs.microsoft.com/en-us/dotnet/standard/net-standard

>  am also using sendGrid so not sure if this would cause problems or not?

Maybe check this first: https://github.com/nlog/nlog/wiki/Logging-troubleshooting

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, please let us know!
