### ISSUE TITLE
How to omit escaping "/" in Nlog.Web.AspNetCore

### ISSUE THREAD

**Issue by aspdev** [NLog/NLog#3153]
I'm using Nlog.Web.AspNetCore 4.8 to log to a file. In the Nlog.config I've configured the layout as JsonLayout. The problem is that the final outcome contains a backslash to escape the "/" present in the original error message. 

Here is my JsonLayout configuration:

`<target xsi:type="File" name="ownFile-web" fileName="${logDirectory}/logs.txt" >
  <layout type='JsonLayout' includeAllProperties="true"  maxRecursionLimit="20" >
    <attribute name="time" layout="${longdate}" />
    <attribute name="level" layout="${level}" />
    <attribute name="logger" layout="${logger}" />
    <attribute name="message" layout="${message}" />
  </layout >
</target>`

Here is the outcome:

`{ "time": "2019-03-01 13:03:27.6581", "level": "Error", "logger": "Scheduler.Api.Startup", "message": "A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 26 - Error Locating Server\/Instance Specified)", "url": "http:\/\/localhost\/scheduler" }
`

As you can see, the Nlog log.Error(string errorMessage) escapes the "/" character in  the "Server\/Instance Specified" part of the error message as well as in the url generated by the ${aspnet-request-url} tag. I would rather the outcome look like this:

`{ "time": "2019-03-01 13:03:27.6581", "level": "Error", "logger": "Scheduler.Api.Startup", "message": "A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 26 - Error Locating Server/Instance Specified)", "url": "http://localhost/scheduler" }`

Is there a way to configure Nlog to omit escaping certain characters unless explicitly told so?

**Comment by 304NotModified** [comment]
Encode=false? See https://github.com/NLog/NLog/wiki/JsonLayout

I think this is a bug?

**Comment by aspdev** [comment]
Thank you Julian. I didn't notice that while reading the docs. Actually, I'm using the Nlog the first time.

**Comment by 304NotModified** [comment]
No problem, glad it helped!
