### ISSUE TITLE
Getting Emails When I should not.

### ISSUE THREAD

**Issue by chobo2** [NLog/NLog#3154]
Hi

I am trying to setup email sending but when I run my code I am geting like 144 emails even though I expect 1

For instance I getting an email with this in(I pulled it from my log that I am saving)

2019-03-01 10:25:21.5693|2|INFO|Microsoft.AspNetCore.Hosting.Internal.WebHost|Request finished in 9538.3354ms 200 application/json; charset=utf-8 

I have this

```
    <target name="email" xsi:type="Mail"
         smtpServer="smtp.sendgrid.net"
         smtpPort="587"
         smtpAuthentication="Basic"
         smtpUserName="apikey"
         smtpPassword="dfa,addjkdajkfajdf715471571575715757157"
         enableSsl="true"
         from="me@test.com"
         to="me@test.com"
          />

    <logger name="*" minlevel="Error" writeTo="email" />

```

So I should just be seeing emails from error level or higher

My other rules

```
  <!--All logs, including from Microsoft-->
    <logger name="*" minlevel="Trace" writeTo="allfile" />
    <logger name="*" minlevel="Error" writeTo="email" />

    <!--Skip non-critical Microsoft logs and so log only own logs-->
    <logger name="Microsoft.*" maxLevel="Info" final="true" />
    <!-- BlackHole without writeTo -->
    <logger name="*" minlevel="Trace" writeTo="ownFile-web" />

```

Also is there away to specify more fine grained if an email is sent? I see you can do by like namspace but is it possible to put it on the debug line it self?

  logger.LogError("Test email"); // can I say this is the only line that will send an email?

**Comment by 304NotModified** [comment]
See you sure you're editing the correct NLog.config? (E.g is there on in the bin folder?). Please check the internal log.

**Comment by chobo2** [comment]
@304NotModified 

Ok, I will check that out. How about controlling which Error Logs will get an email send out? Is that possible?

**Comment by 304NotModified** [comment]
I think you're looking for: https://github.com/NLog/NLog/wiki/Filtering-log-messages

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, please let us know!
