### ISSUE TITLE
Configuration in applicationname.exe.nlog files do not load

### ISSUE THREAD

**Issue by john-cullen** [NLog/NLog#3156]
**NLog version**: 4.5.11
**Platform**:  .NET Core 2
**Current NLog config** (xml or C#, if relevant)

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      throwExceptions="true" throwConfigExceptions="true">

  <targets>
    <target name="file" xsi:type="File"
            layout="${longdate} ${level} ${logger}: ${message} ${exception:format=ToString}"
            fileName="LogFiles/${shortdate}_LogFile.txt" keepFileOpen="true" encoding="utf-8"/>

    <target name="console" xsi:type="ColoredConsole"
            layout="${longdate} ${logger} ${level}: ${message} ${exception:format=ToString}"
            detectConsoleAvailable="true" />

  <rules>
    <logger name="*" minlevel="Debug" writeTo="file,console,viewer" />
  </rules>
</nlog>
```

According to https://github.com/nlog/nlog/wiki/Configuration-file it should be possible to have a configuration in a file called `program.exe.nlog` where `program.exe` is the executable for my program.

When the config file is in the `applicationname.exe.nlog` file, it does not work as expected.

Create a console application with the following `Program.cs`

```csharp
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");

            foreach (var target in LogManager.Configuration.AllTargets)
                Console.WriteLine("Target: {0}", target.Name);
        }
    }
```

Publish the program with `dotnet publish -c Release -r win-x64` and run the executable. The program crashes with `Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.`.

Rename the file to `nlog.config` and it works as expected.

**Comment by 304NotModified** [comment]
Do you have a stack trace for the exception?

**Comment by john-cullen** [comment]
No, it throws on the configuration property access in the foreach so a stack trace is not useful.

**Comment by 304NotModified** [comment]
What about a try-catch and a logger.Error? ;)

Or on visual studio when debugging: https://stackoverflow.com/a/116934/201303

Thanks in advance!

**Comment by snakefoot** [comment]
@304NotModified This line throws, because no config is found (LogManager.Configuration = null)

> `foreach (var target in LogManager.Configuration.AllTargets)`

**Comment by snakefoot** [comment]
@john-cullen Think the problem is because of NetCore, and the current file-probe-logic for finding application.exe.nlog uses NetFramework app.config as guide.

https://github.com/NLog/NLog/blob/b974a19e453de90d76f98513db8a1d52a3245f95/src/NLog/Config/LoggingConfigurationFileLoader.cs#L239-L243

There is no app.config on NetCore so the lookup of application.exe.nlog is skipped.

**Comment by snakefoot** [comment]
Probably need a champion to investigate:

- dotnet using dll
- dotnet using exe
- dotnet native
- aspnetcore
- aspnetcore hosted on iis
- service fabric
- etc.

And come up with a probe-method that works okay for the different runtime modes (and not tries to load dotnet.exe.nlog or iis.exe.nlog)

**Comment by snakefoot** [comment]
There is a shortage of champions right now so I guess a workaround would be to add the extra lookup path manually for your app:

Maybe like this:
```c#
var candidatePaths = NLog.LogManager.LogFactory.GetCandidateConfigFilePaths().ToList();
candidatePaths.Insert(0, Process.GetCurrentProcess().MainModule.FileName + ".nlog");
NLog.LogManager.LogFactory.SetCandidateConfigFilePaths(candidatePaths);
```

Remember to perform the above initialization code before creating any NLog Logger-object (including static ones).

**Comment by snakefoot** [comment]
@john-cullen Could you try this pre-release build of NLog:

https://ci.appveyor.com/project/nlog/nlog/builds/23613568/artifacts (See `NLog.4.6.2.9556-PR3261.nupkg`)

It should load the `exe.nlog`-file correctly.

**Comment by snakefoot** [comment]
@john-cullen NLog 4.6.3 has been released:

https://www.nuget.org/packages/NLog
