### ISSUE TITLE
Colon within innerExceptionSeparator

### ISSUE THREAD

**Issue by brinko99** [NLog/NLog#3158]
It's a small detail but I've been unable to find a way to get a colon to show within the inner exception separator. I've tried `\:`, `{literal:text=\:}` and even `&#x3A;`. None of these will produce a colon in the output.

What I'm really looking for is the following:

`innerExceptionSeparator=&#xD;&#xA;Inner Exception&#x3A;&#xD;&#xA;`

I'm happy to forgo the colon here, but I am curious...

**Comment by 304NotModified** [comment]
I am afraid this is a limitation in the current parser, related: https://github.com/NLog/NLog/issues/2844

**Comment by 304NotModified** [comment]
Not sure how to solve this.

**Comment by brinko99** [comment]
Thanks...

Shortly after posting, it occurred to me to look for a Unicode Colon alternative. The "Fullwidth Colon", `&#xFF1A;` works well for this need.
