### ISSUE TITLE
Sentry target

### ISSUE THREAD

**Issue by UgurAldanmaz** [NLog/NLog#3172]
It would be nice to have a target for Sentry. Sentry is an open source error tracking software. For detail: https://sentry.io/

I would like to implement it. Please let me know whether we want it or not.

**Comment by 304NotModified** [comment]
What about

https://nlog-project.org/config/?tab=targets&search=Sentry

?

**Comment by UgurAldanmaz** [comment]
It's my bad. I have forgot to look at the configuration page. I've searched issues and pull requests but couldn't find anything about Sentry. It looks fine, but we may consider developing it officially or we can close this issue.

**Comment by snakefoot** [comment]
@UgurAldanmaz Maybe this issue could be of interest:

https://github.com/getsentry/sentry-dotnet/issues/167

They are looking for someone to make a PR for an official Sentry-target.

**Comment by 304NotModified** [comment]
So wontfix for this repo 👼

**Comment by 304NotModified** [comment]
Closing this as there is nothing to do for us
