### ISSUE TITLE
Unstable test LogBuilder_Structured_Logging_Test 

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#3174]
See https://ci.appveyor.com/project/nlog/nlog/builds/23084197

**Comment by 304NotModified** [comment]
@snakefoot any idea on this? The test and code looks good to me...

**Comment by snakefoot** [comment]
Have also looked at the code, and cannot see why it fails.

**Comment by 304NotModified** [comment]
maybe the static LogEventInfo.DefaultMessageFormatter (parallel tests?)

**Comment by snakefoot** [comment]
Strange if the NLog Message Formatter could not handle parallel execution.

**Comment by 304NotModified** [comment]
ConfigurationItemFactory.Default.ParseMessageTemplates will be set by other tests, e.g. SingleTargetMessageFormatOptimizationTest 

and also indirect by LoadConfig in LoggingConfigurationParser.

Could that be the issue?
