### ISSUE TITLE
Change defaultaction of filter to ignore

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#3177]
Currently "neutral"

Fixes this case:

```xml
  <filters>
    <when condition=""starts-with(message, 't')"" action='Log' />
  </filters>
```

everything is just logged!

**Comment by 304NotModified** [comment]
note: it should be neutral if no filters are configured.

but what about 

```xml
  <logger name='*' level='Warn' writeTo='d1'>
                        <filters>
                      
                        </filters>
                    </logger>

```

? are the logs now ignored or logged ?

**Comment by 304NotModified** [comment]
@snakefoot as I see how many test I have changed (see https://github.com/NLog/NLog/pull/3359), i'm a bit doubting of this change. What do you think?

**Comment by snakefoot** [comment]
Never used filters much myself. Maybe the default-action should be the opposite of the action specified for the when-condition?

Or would that be too confusing?

**Comment by 304NotModified** [comment]
I had that also in my mind - but think that's too confusing.

**Comment by 304NotModified** [comment]
I think this is the best choice and so merge it. Luckily it's easy to revert with `<filters defaultAction="log">`
