### ISSUE TITLE
Handle invalid nlog.config / XML better

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#3178]
> When the xml-parser fails to parse the input stream, then NLog should scan the configuration-blob-stream for these strings (without trying to parse as xml):

> throwConfigExceptions="true"
> throwExceptions="true"

this needs probably a regex. Search should be case insensitive and sinqle quote and spaces should also work.

Unit tests are needed for this, TTD recommended

**Comment by ajitpeter** [comment]
Can I have a look at this issue?

**Comment by 304NotModified** [comment]
Yes, that would be great :+1:

**Comment by ajitpeter** [comment]
@304NotModified is there any time(future releases) by which this fix has to go in as I was unable to spend much time on it yet.

**Comment by 304NotModified** [comment]
Not really, is a nice enhancement but not critical

**Comment by 304NotModified** [comment]
WIP here -> #3521

**Comment by snakefoot** [comment]
@304NotModified Guess this has been resolved with NLog 4.6.7 ?

**Comment by 304NotModified** [comment]
Yes indeed! Thanks!

Fixed by https://github.com/NLog/NLog/pull/3562
