### ISSUE TITLE
Going from log4net to NLOG

### ISSUE THREAD

**Issue by MC01DA** [NLog/NLog#3179]
Hello,

As the title says, I'm going from log4net to NLOG. 

Everything configured successfully but got problems with pattern layout. 

log4net pattern layout 
```xaml
%8level| %8timestamp| %5.5thread| %10.20logger{1}| %message%newline
 ```

How do I write this pattern layout in nlog? 
Currently Getting problems with empty spaces and also cannot find timestamp pattern.

**Comment by snakefoot** [comment]
The simple conversion would be this:

> ${level}|${longdate}|${threadid}|${logger}|${message}${exception}

If you want the padding:

> ${level:padding=5}| ${time:invariant=true}| ${threadid:padding=6}| ${logger}| ${message}${exception}

**Comment by 304NotModified** [comment]
Recommended to read:

- https://github.com/NLog/NLog/wiki/Tutorial#layouts-and-layoutrenderers

And (searchable) list of all options: https://nlog-project.org/config/?tab=layout-renderers

**Comment by MC01DA** [comment]
Thank you
