### ISSUE TITLE
event-properties:item always empty

### ISSUE THREAD

**Issue by Exerlol** [NLog/NLog#3182]
Hello, first of all thanks for a great framework. 
I'm using NLog v4.5.11 with Asp.net Mvc and trying to save a log into db table, here is my NLog config:

   ```xml
 <target name="database" 
            type="Database"
            connectionStringName="Test">
      <commandText>
        INSERT INTO ExceptionLog
        (Message, StackTrace, InnerException, ExtraInfo,  Date ) VALUES
        (@Message, @StackTrace, @InnerException, @ExtraInfo, @Date);
      </commandText>

      <parameter name="@Message" layout="${exception:format=message}" />
      <parameter name="@StackTrace" layout="${exception:format=stacktrace}" />
      <parameter name="@InnerException" layout="${exception:format=type,message,method:maxInnerExceptionLevel=5:innerFormat=shortType,message,method}" />
      <parameter name="@ExtraInfo" layout="${event-properties:item=extraInfo}" />
      <parameter name="@Date" layout="${date}" />

      <dbProvider>System.Data.SqlClient</dbProvider>
    </target>

    <logger name="Test.Namespace.DatabaseLogger" minlevel="Debug" writeTo="database" final="true" />
```
This is how I call it inside my DatabaseLogger:

```
public void Error(string message, Exception exception)
{
       Logger.Error(exception, "{extraInfo}", "This is some test extra info");
}
```

However, this just inserts an empty string into ExtraInfo column (because property was not found). All other columns are set right. Am I doing something wrong? Any ideas how to fix this?

**Comment by snakefoot** [comment]
Could you make a simple Test App where the following NLog-config also fails:

```xml
<nlog>
<targets>
<target type="console" name="db" layout="${event-properties:item=extraInfo} - ${message}" />
</targets>
<rules>
<logger name="Test.Namespace.DatabaseLogger" minlevel="Debug" writeTo="db" final="true" />
</rules>
</nlog>
```

And then attach the solution to this issue?

**Comment by 304NotModified** [comment]
Maybe it's also a good idea to double check if the value is also empty when writing to the filetarget

**Comment by Exerlol** [comment]
First of all thanks for reply's guys. @304NotModified  I'll be able to do some checks tomorrow morning, what i managed to do so far is follow @snakefoot suggestion and created Test App, however I cant reproduce bug that I'm experiencing with real app... Sample app works without issue... I must be missing something... I'll also introduce some internalLog's to see if that helps...

**Comment by snakefoot** [comment]
@Exerlol Minor detail unrelated to event-properties. You might want to include:

`<parameter name="@Type" layout="${exception:format=type}" />`

**Comment by Exerlol** [comment]
@snakefoot yeah, what I've posted is just a "simplified sample", we are logging much more in real app... Anyways, I feel so dumb, we have quite a few projects inside solution and after some hair pulling I've noticed that class library is referencing latest version of NLog, but web project was using old one, once updated everything started working like a charm... Sorry for all the fuzz, you can close this question, note for others that come across same issue - check your NLog version since event-properties are NLog 4.5+ feature...hope it helps someone. Thanks to both of you guys!

**Comment by 304NotModified** [comment]
I'm glad is has been resolved 👍
