### ISSUE TITLE
AsyncTaskTarget does not batch rows after first iteration

### ISSUE THREAD

**Issue by mmurrell** [NLog/NLog#3185]
I'm trying to write a custom async target for NLog that pushes logs to Azure, and ran into an unexpected scenario. Basically this: when the async task that I am invoking is slow (in this example 1.5s), after the first batch, all remaining log entries are sent in single batches.  

This is reproducable with various values for TaskDelayMilliseconds, and various app delays. I would expect one "Write" operation every "TaskDelayMilliseconds" except in cases of exceptions / retry. I suspect this may be a bug in the AsyncTaskTarget, but I'd like a community review before I submit it. Any thoughts? Thanks in advance.

After further tracing, I suspect that this could be based on the dual role of `TaskStartNext` in that it cleans up '_previousTask', from TaskCompletion, and also works to empty the queue.  I hesitate to recommend changes because I'm not familiar enough with async, or the patterns here, but perhaps the `TaskCompletion` should kick off a new timer if the queue is not empty.

StackOverflow link:
https://stackoverflow.com/questions/55228585/nlog-asynctasktarget-does-not-batch-rows-after-first-iteration?noredirect=1#comment97196350_55228585

This is reproducible against 4.6.0-rc3, and I am running on .Net Framework, 4.7.2

```xml
<nlog internalLogLevel="Debug" internalLogToConsole="true">
    <extensions>
      <add assembly="ConsoleApp1"/>
    </extensions>

    <targets>
      <target type="console" name="console"/>
      <target type="AsyncTestTarget" name="test" />
    </targets>

    <rules>
      <logger name="*" minlevel="Trace" writeTo="console" />
      <logger name="*" minlevel="Trace" writeTo="test" />
    </rules>
</nlog>
```

Sample Consumer:
```
class Program
{
    static ILogger logger = LogManager.GetCurrentClassLogger();
    static void Main(string[] args)
    {

        for (var i = 0; i < 5000; i++)
        {
            logger.Info(i.ToString());
            System.Threading.Thread.Sleep(TimeSpan.FromMilliseconds(100));
        }

        logger.Info("Done");

        LogManager.Flush(TimeSpan.FromSeconds(15));
    }
}
```

Sample (buggy) Target:
```
[Target("AsyncTestTarget")]
public class AsyncTestTarget : AsyncTaskTarget
{
    protected override void InitializeTarget()
    {
        base.InitializeTarget();

        BatchSize = 10000;
        TaskDelayMilliseconds = 3000;
    }


    protected override Task WriteAsyncTask(LogEventInfo logEvent, CancellationToken cancellationToken)
    {
        InternalLogger.Info($"NLog.Extensions.AsyncTestTarget.WriteAsyncTask()");
        return WriteAsyncTask(new List<LogEventInfo> {logEvent}, cancellationToken);
    }

    protected override Task WriteAsyncTask(IList<LogEventInfo> logEvents, CancellationToken cancellationToken)
    {
        InternalLogger.Info($"NLog.Extensions.AsyncTestTarget.WriteAsyncTask(List) : {logEvents.Count}");
        if (!logEvents.Any())
            return Task.CompletedTask;
        // If this line is commented, the rows are batched as expected.  If this line is left as-is, then after the first batch, records are sent one at a time.
        System.Threading.Thread.Sleep(TimeSpan.FromMilliseconds(1500));

        return Task.CompletedTask;
    }
}
```

Current Result:
Records are batched initially, but seem to immediately transition to a sequential (non-batched) WriteAsyncTask implementation.  See the screenshot below.
![Broken Result](https://i.stack.imgur.com/w3EqC.png)

Expected Result:
Records are batched consistently.  See the screenshot with the delay removed.
![Expected Result](https://i.stack.imgur.com/zxNRM.png)

**Comment by snakefoot** [comment]
Thank you for reporting this. The problem is indeed caused by the slow creation of tasks (Sleeping 1500 msec)

The AsyncTaskTarget is very careful with not starting more than one Task. This gives the following pattern:

1) Logger writes to an empty queue and schedules timer while holding lock
2) Logger continues to write without any issues.
3) Timer calls TaskStartNext() and empties queue and then tries to schedule task (blocks while holding lock)
4) Logger writes again to an empty queue and schedules timer but needs to wait for lock
5) TaskStartNext schedules task and releases locks
6) Task completes right away and schedules TaskStartNext()
7) Task calls TaskStartNext() and empties queue and then tries to schedule task (blocks while holding lock)
8) Goto 4

I did not anticipate that one would do a blocking operation inside the async-method. Expected one to return a task right away that would then complete after a long time.

Workaround would be to change this:

> System.Threading.Thread.Sleep(TimeSpan.FromMilliseconds(1500));

Into this:

> await Task.Delay(TimeSpan.FromMilliseconds(1500));

But I have now created #3187 to better support this unsupported scenario.

**Comment by mmurrell** [comment]
Thanks for the prompt reply and refactor.  Admittedly the "bug" was my failure to understand the intention of the async method.  That being said, I'm still struggling a bit with a correct implementation.  

For example this code (when compiled against #3187) runs correctly.
```
        protected override Task WriteAsyncTask(IList<LogEventInfo> logEvents, CancellationToken cancellationToken)
        {
            var max = logEvents.Select(x => x.SequenceID).Max();
            var min = logEvents.Select(x => x.SequenceID).Min();
            InternalLogger.Info($"NLog.Extensions.AzureTableStorage.WriteAsyncTask(List) sequence {min} to {max}");

            if (!logEvents.Any())
                return Task.CompletedTask;

            var task = Task.Run(async () =>
            {

                InternalLogger.Info($"*** ENTERING THREAD - Writing sequence {min} to {max}");
                await Task.Delay(1500);
                InternalLogger.Info($"*** LEAVING THREAD - Writing sequence {min} to {max}");
            });

            InternalLogger.Info($"EXITING NLog.Extensions.AzureTableStorage.WriteAsyncTask(List)sequence {min} to {max}");

            return task;
        }
```
Screenshot:
![image](https://user-images.githubusercontent.com/673839/54655500-8d712e00-4a98-11e9-980f-1daede18fe79.png)

However, when running with my desired target implementation, I'm still getting unexpected results:
```
        protected override Task WriteAsyncTask(IList<LogEventInfo> logEvents, CancellationToken cancellationToken)
        {
            var max = logEvents.Select(x => x.SequenceID).Max();
            var min = logEvents.Select(x => x.SequenceID).Min();
            InternalLogger.Info($"NLog.Extensions.AzureTableStorage.WriteAsyncTask(List) sequence {min} to {max}");

            if (!logEvents.Any())
                return Task.CompletedTask;

            var task = Task.Run(async () =>
            {

                InternalLogger.Info($"*** ENTERING THREAD - Writing sequence {min} to {max}");

                if (currentLogBlob.Name != GetBlobFileName())
                    currentLogBlob = CreateLocalBlob();

                var body = string.Join(Environment.NewLine, logEvents.Select(x => Layout.Render(x))) + Environment.NewLine;
                using (var memoryStream = new System.IO.MemoryStream(Encoding.UTF8.GetBytes(body)))
                {
                    await currentLogBlob.AppendBlockAsync(memoryStream, null, null, _options, null, cancellationToken);
                }

                InternalLogger.Info($"*** LEAVING THREAD - Writing sequence {min} to {max}");
            });

            InternalLogger.Info($"EXITING NLog.Extensions.AzureTableStorage.WriteAsyncTask(List)sequence {min} to {max}");

            return task;
        }
```
Screenshot of unexpected behavior.  
![image](https://user-images.githubusercontent.com/673839/54655577-d628e700-4a98-11e9-8eeb-b2a3324f31b2.png)

Is this my still incomplete async understanding, or is there something deeper going on here?  Thanks again for your assistance.

**Comment by snakefoot** [comment]
@mmurrell Think you have to explain to me what is wrong/unexpected with the output in the last console window.

**Comment by snakefoot** [comment]
@mmurrell Is it because `TaskDelayMilliseconds` is only used when timer triggered?

**Comment by snakefoot** [comment]
@mmurrell Created  #3189 with better respect for `TaskDelayMilliseconds`

**Comment by mmurrell** [comment]
@snakefoot - Thanks for your quick response and fixes.  I've pulled #3189 and it seems to address the issue.  It looks in all load conditions I was able to test, the target batching did not degrade.

**Comment by snakefoot** [comment]
@mmurrell Because of timing of your feedback, then you have to wait for NLog 4.6.1

**Comment by 304NotModified** [comment]
Unfortunately 4.6 was already tagged and in the release pipeline. Anyway, you could use the PR nuget package. 

Also I think it won't take long when NLog 4.6.1 will be released (maybe next week, depends on the feedback)

**Comment by mmurrell** [comment]
Understood guys.  Thanks for your help!  You are really appreciated.

**Comment by snakefoot** [comment]
@mmurrell  NLog 4.6.1 has been released: https://www.nuget.org/packages/NLog/4.6.1
