### ISSUE TITLE
PerfCounterTarget only allows to Increment a counter

### ISSUE THREAD

**Issue by vladimirlapacek** [NLog/NLog#319]
The AverageTimer32 performance counter and similar others require the Increment method to be called with a specific value. This is currently not possible, which makes these counters unusable in NLog

**Comment by 304NotModified** [comment]
Is there some code examples related to this problem/feature request/

**Comment by 304NotModified** [comment]
Related #525

**Comment by 304NotModified** [comment]
Summary 

- https://github.com/NLog/NLog/wiki/PerfCounter-target

Need for countervalue property. (Currently  1?)

**Comment by 304NotModified** [comment]
PR merged, so this is fixed :) 

Thanks @bhaeussermann 

This will be released in 4.2
