### ISSUE TITLE
.Net Core usage with api endpoint.

### ISSUE THREAD

**Issue by cRUSHER-HLG** [NLog/NLog#3192]
Hello guys,

I want to ask if i can use this lib under .net core and how can i send reports to lets say an api endpoint?

Good Regards,
cRUSHER

**Comment by snakefoot** [comment]
Yes NLog supports NetStandard so it can be used with NetCore.

API endpoint can be a lot of things. Api-webservice or Api-library-method or ....

But you can write your own custom target:

https://github.com/NLog/NLog/wiki/How-to-write-a-custom-target

Or you can just use the method call target to call your custom code (See "Configure call of lambda at runtime"):

https://github.com/NLog/NLog/wiki/MethodCall-target#configure-call-of-lambda-at-runtime

**Comment by cRUSHER-HLG** [comment]
So i need to make my own custom target which transports then the data to the database?

**Comment by lobster2012-user** [comment]
@cRUSHER-HLG 
Is it suitable for you?
https://github.com/nlog/NLog/wiki/Database-target

If necessary, you can wrap in asynchronous sending. I did not use it myself, I can not say anything about sending a portion of several messages at once.

**Comment by 304NotModified** [comment]
FYI all targets are listed here: https://nlog-project.org/config/

**Comment by cRUSHER-HLG** [comment]
Currently i test it with graylog 3.

**Comment by lobster2012-user** [comment]
@cRUSHER-HLG 
https://marketplace.graylog.org/addons?tag=Nlog
I see open source projects.
What is your question?

**Comment by snakefoot** [comment]
@cRUSHER-HLG No idea what endpoint of GrayLog 3 you are using but recall GrayLog likes GELF:

```xml
<?xml version="1.0" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" >
  <extensions>
    <add assembly="NLog.Layouts.GelfLayout" />
  </extensions>
  
  <targets async="true">
	<target xsi:type="Network" name="GelfHttp" address="http://localhost:12201/gelf" layout="${gelf:facility=MyFacility}" />
  </targets>

  <rules>
    <logger name="*" minlevel="Debug" writeTo="GelfHttp" />
  </rules>
</nlog>
```

See also https://github.com/farzadpanahi/NLog.GelfLayout and remember to install this nuget: https://www.nuget.org/packages/NLog.GelfLayout/

**Comment by cRUSHER-HLG** [comment]
I want to add my application logs to graylogs

**Comment by snakefoot** [comment]
@cRUSHER-HLG Guess you should read the manual then, or ask on StackOverflow.

This place is for reporting bugs and feature-request for the NLog-core project alone. 

It is not meant as a consultancy service for how to setup logging collection services (Like GrayLog, ElasticSearch) or for diagnosing environment issues.

**Comment by cRUSHER-HLG** [comment]
@snakefoot 
If you think that such a theme is better to discuss on StackOverflow, then do it for you. For me i use the communication way of github. Its not a core-service but its a part of it.

**Comment by lobster2012-user** [comment]
@cRUSHER-HLG 
Thank you for your message, smiled. The advice above is sensible. People who are ready to help you with your question will help on stackoverflow, and there are much more such people

**Comment by cRUSHER-HLG** [comment]
I have some questions:
1. I made a test program in .net core (not asp.net core) and used the GelfUdpSender. I send 25k request to the graylog server and the graphs says that it receives more then 1 million requests. The 25k request is for each request a pause of 10ms. But more then 30 - 60 minutes later the in/out messages are still between 1k - 5k and dont goes down. Can someone explain me how 

2. When i use the way with the NLog.config it dont works. Can someone provide me maybe a way in which he has installed it on his own?

**Comment by 304NotModified** [comment]
Hi @cRUSHER-HLG 

It's OK for me to ask questions here for me, but there are some things to know:

- On stackoverflow there is a much broader community. 
- The GELF and Graylog components are 3rd party. This team won't maintain them and also I personally never used graylog.

So it's hard to help you here with these questions.

I would recommend to:

- Ask it on stackoverflow, OR,
- Ask it on github of the graylog/gelf components.

Closing this for now.

**Comment by 304NotModified** [comment]
FYI,

This package seems active and so also maybe for Graylog **3**

https://github.com/dustinchilson/NLog.Targets.GraylogHttp

**Comment by cRUSHER-HLG** [comment]
@304NotModified Thanks for your answer. 
I using Nlog.Gelf to send reports by udp to the graylog server. How can i configurate Nlog to log every exception that occurs? I dont mean only try/catch and then send the exception. I want to catch all exceptions :D

**Comment by 304NotModified** [comment]
This could be helpful: https://stackoverflow.com/questions/219594/net-whats-the-best-way-to-implement-a-catch-all-exceptions-handler
