### ISSUE TITLE
SimpleStringReader.CurrentState

### ISSUE THREAD

**Issue by lobster2012-user** [NLog/NLog#3194]
```csharp

string CurrentState
        {
            get
            {
                var current = (char)Peek();
                var done = Substring(0, Position - 1);

```

Why not
```csharp

var done = Substring(0, Position);

```
?

```csharp
   var todo = ((Position > _text.Length) ? Text.Substring(Position + 1) : "");
```
why not

```csharp
   var todo = ((Position < _text.Length) ? Text.Substring(Position ) : "");
```
?

**Comment by snakefoot** [comment]
Yes that looks like a bug. Very well spotted.

**Comment by snakefoot** [comment]
Yes that looks like a bug. Very well spotted. PullRequests are welcome :)

**Comment by lobster2012-user** [comment]
OK. One question.
Should `todo` include the current character, that is, the next one to read? I think not.

**Comment by snakefoot** [comment]
Think @304NotModified knows more about this code than I do :)

**Comment by 304NotModified** [comment]
I need to check that. Has been some time this code has been altered.

**Comment by 304NotModified** [comment]
> Should `todo` include the current character, that is, the next one to read? I think not.

I think also not :)
