### ISSUE TITLE
MdlcLayoutRenderer not marked with ThreadAgnostic

### ISSUE THREAD

**Issue by SergiyBondarInvisible** [NLog/NLog#3197]
Hi! 
Any reason this class is not marked with ThreadAgnostic?
The Mapped Diagnostic Logical Context is async but without attribute ThreadAgnostic for class MdlcLayoutRenderer used as sync - as I understood.
Similar problem was here - https://github.com/NLog/NLog/issues/893

**Comment by snakefoot** [comment]
The idea with ThreadAgnostic is that the output will be the same independent of what thread is logging.

The AsyncLocal is not the same for all threads. Just like ThreadId is not the same for all threads.

This means `MdlcLayoutRenderer` has to capture the AsyncLocal-state when trying to defer the actually log-writing to an async Timer-thread. Because the Timer-thread always sees an empty AsyncLocal-state.

Guess the work done with #1956 is not enough.

**Comment by 304NotModified** [comment]
> Guess the work done with #1956 is not enough.

Please let me know what to add, or PR ;)

**Comment by SergiyBondarInvisible** [comment]
Few words about my problem - when my web app have started to response with delay about few minutes, I created dump from w3wp.exe and found that very huge scope of threads delayed on NLog.dll!NLog.Targets.Target.PrecalculateVolatileLayouts. So I have started to investigate and found that all layouts used attribute ThreadAgnostic, but MdlcLayoutRenderer not used it. In method PrecalculateVolatileLayouts if not all layouts with atribute ThreadAgnostic then used logic with lock - so we have bottleneck.

**Comment by snakefoot** [comment]
Can you paste your Layout config?


NLog should not hold locks as long the layoutrenderers are marked as threadsafe.


Threadsafe was introduced with NLog 4.5.3 and NLog.Web.AspNetCore 4.7.1



Sent from my Sony Xperia


---- Sergiy Bondar2 wrote ----


Few words about my problem - when my web app have started to response with delay about few minutes, I created dump from w3wp.exe and found that very huge scope of threads delayed on NLog.dll!NLog.Targets.Target.PrecalculateVolatileLayouts. So I have started to investigate and found that all layouts used attribute ThreadAgnostic, but MdlcLayoutRenderer not used it. In method PrecalculateVolatileLayouts if not all layouts with atribute ThreadAgnostic then used logic with lock - so we have bottleneck.

**Comment by SergiyBondarInvisible** [comment]
I used NLog 4.5.11

<target xsi:type="File"
            name="File"
            fileName="${gdc:item=LogsPath}/WebApi.log" encoding="utf-8"
            layout="${longdate:universalTime=true} [M:${machinename}] [AD:${appdomain:format=short}] [Op:${mdlc:item=ApiOpId:whenEmpty=NA}] ${uppercase:${level:padding=-5}} [${logger:shortName=true}] ${message} ${onexception:EXCEPTION OCCURRED\:${newline}${exception:format=tostring}${newline}    }" />

**Comment by snakefoot** [comment]
You only have a single target and layout?


Sent from my Sony Xperia


---- Sergiy Bondar2 wrote ----


I used NLog 4.5.11

**Comment by SergiyBondarInvisible** [comment]
I updated my comment - one global target with async="true" and other inside and one layout.

**Comment by snakefoot** [comment]
Believe the problem is `${gdc}` it was not marked as ThreadAgnostic until NLog 4.6.

The `${gdc}` uses a global lock. I guess we should fix that with a ConcurrentDictionary.

**Comment by snakefoot** [comment]
Created #3201 for improving concurrency for `${gdc}`

**Comment by snakefoot** [comment]
@SergiyBondarInvisible Would it be possible you could confirm that the "lock" occurs in GDC?

As you can see here then NLog 4.5.11 allows multiple threads to precalculate without waiting on a lock:

https://github.com/NLog/NLog/blob/5d14e5669a860bde7b8f6d7765dea99cbd6dbc0f/src/NLog/Targets/Target.cs#L205-L220

**Comment by snakefoot** [comment]
@SergiyBondarInvisible Also NLog 4.6 will improve concurrency when using `<targets async='true'>` because NLog 4.6 makes use of ConcurrentQueue on NetCore2.

**Comment by SergiyBondarInvisible** [comment]
I double checked and found that on the env(it was not updated for some reasons) where was problem we used nuget package with custom layout and it was included to nlog.config. It was without any attributes. So it was a main problem of bottleneck. It is my confuse, sorry guys. I think you can close this issue. Thanks!

**Comment by snakefoot** [comment]
So you were running an old version of NLog? Or were you running with different layout config?


Sent from my Sony Xperia


---- Sergiy Bondar2 wrote ----


I double checked and found that on the env(it was not updated for some reasons) where was problem we used nuget package with custom layout and it was included to nlog.config. It was without any attributes. So it was a main problem of bottleneck. It is my confuse, sorry guys. I think you can close this issue. Thanks!

**Comment by SergiyBondarInvisible** [comment]
version was NLog 4.5.11 and  layout config was different.

**Comment by snakefoot** [comment]
If you feel the issue is resolved for you, then just close it


Sent from my Sony Xperia


---- Sergiy Bondar2 wrote ----


version was NLog 4.5.11 and layout config was different.

**Comment by SergiyBondarInvisible** [comment]
Ok, thanks

**Comment by 304NotModified** [comment]
I'm glad is has been resolved 👍
