### ISSUE TITLE
The 'onndlc' check just like the 'onexception'

### ISSUE THREAD

**Issue by watsonsong** [NLog/NLog#3250]
NLog version: 4.6.0
Platform: .NET Core 2 / .NET Core 3

I want to output a pretty look log to console target and show the ndlc with it.
If I just write the ndlc into the layout:
```
${logger:shortName=true}|${ndlc}|${message}
```
When the ndlc does not existed, there will be two '||'appear, this may good for file log that can easy split each log into columns, but it just make the console output look ugly.

Is there any way to check whether the ndlc existed just like the 'onexception' layout worked?

**Comment by snakefoot** [comment]
Would this give the wanted output:

`${when:when='${ndlc:topframes=1}' == '':inner=:else=${ndlc}|}`

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, please let us know!
