### ISSUE TITLE
Does target types no longer support dot (.)?

### ISSUE THREAD

**Issue by ThomasArdal** [NLog/NLog#3252]
I currently have a target looking like this:

```csharp
[Target("elmah.io")]
public class ElmahIoTarget : TargetWithLayout
```

This worked pre 4.6 when referencing the target using the type `elmah.io`. After upgrading to 4.6, the dot no longer seems allowed in the target name:

```
Target cannot be found: 'io'
```

I've tried removing the dot from both the target and the config which works in 4.6.

Is dots no longer allowed in target types or is there another way to get it to work? Removing the dot from the target type would break all existing config out there :smile:

**Comment by snakefoot** [comment]
Believe it is my fault. Should be fixed with #3199 (NLog 4.6.1)

**Comment by ThomasArdal** [comment]
No worries. When is 4.6.1 scheduled for release?

**Comment by 304NotModified** [comment]
this week

**Comment by 304NotModified** [comment]
closed by #3199

**Comment by 304NotModified** [comment]
4.6.1 is now in the deployment queue :)

**Comment by 304NotModified** [comment]
It's released! :tada: https://www.nuget.org/packages/NLog/4.6.1

**Comment by ThomasArdal** [comment]
Thank you for the rapid response and quick turnaround. You guys rock as always!
