### ISSUE TITLE
Layout render doesn't reset body stream possition

### ISSUE THREAD

**Issue by floatas** [NLog/NLog#3273]
**NLog version**: ( 4.6.1)
**NLog extensions.logging**: (1.4.0)
**NLog web aspnetcore**: (4.8.1)

**Platform**:  .NET Core 2

        public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseNLog()
                .UseStartup<Startup>();

I'm trying to log request body, body is written to log successfully, however body is null for controller action.

- What is the current result?
unable to seek in request body. Layout renderer reads body, prints it to logs and doesn't reset position.
- What is the expected result?
Stream position is reset where it was before layout formater.
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
No errors
- Are there any workarounds?
Configuring nlog manually, but can't find documentation for this. Even if layout renderer is added to collections, it's still not invoked. Would be nice to get some instructions how to config manually.
- Is there a version in which it did work? 
don't know

In order to make request body seekable I should invoke `Request.EnableRewind();`, but nlog is added too high in configuration and there doesn't seem to be room left to invoke `Request.EnableRewind();`. Is there a workaround ?

Same issue with HttpContextAccessor.HttpContext.User.Identity.IsAuthenticated. In layout renderer this property is false, because it hasn't been filled yet.

Is there a way to register NLog in startup class ? I think it would solve my issues.

**Comment by 304NotModified** [comment]
Hi!

Please elaborate "Configuring nlog manually". What's that?

Please share your config. And Where are you doing the logger call?

**Comment by floatas** [comment]
Ignore please, looks eveything is working as expected.
