### ISSUE TITLE
Travis: No output has been received in the last 10m0s

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#3281]
I've seen this multiple times last weeks :(

> No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated

https://travis-ci.org/NLog/NLog/builds/513631215?utm_source=github_status&utm_medium=notification

**Comment by 304NotModified** [comment]
Again two times, same PR

- https://travis-ci.org/NLog/NLog/builds/515957514?utm_source=github_status&utm_medium=notification
- https://travis-ci.org/NLog/NLog/builds/515957605?utm_source=github_status&utm_medium=notification

**Comment by snakefoot** [comment]
Maybe it started with this build:

https://travis-ci.org/NLog/NLog/builds/502259924

#3124 - NetworkTarget - Added support for KeepAliveTimeSeconds

**Comment by snakefoot** [comment]
Could try and disable the test for NetCore on Travis, and see if the problem disappear

**Comment by 304NotModified** [comment]
assume fixed by #3282. Will reopen if not :)

**Comment by 304NotModified** [comment]
Unfortunately still an issue ☹️

https://travis-ci.org/NLog/NLog/builds/518142389?utm_source=github_status&utm_medium=notification

**Comment by 304NotModified** [comment]
Looks also stable :tada:
