### ISSUE TITLE
NlogConfig file could not be read properly

### ISSUE THREAD

**Issue by Shiva799** [NLog/NLog#3283]
After fetching nlog.config file i get the values of target inside it to be 0 when in fact i have set 4 targets and 4 rules in nlog.config file. Basically the nlog.config file is not being read. Why this might be happening i do not know. Has anyone faced this issue? Please tell me how can i resolve this issue. Also Nlog 4.6.1 is installed in my proj
Thanks,

**Comment by 304NotModified** [comment]
Please add some more info. We can't help you now.
