### ISSUE TITLE
Unstable test AsyncTaskTarget_TestThrottleOnTaskDelay 

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#3292]
See https://ci.appveyor.com/project/nlog/nlog/builds/23659118

> Failed   NLog.UnitTests.Targets.AsyncTaskTargetTest.AsyncTaskTarget_TestThrottleOnTaskDelay
Error Message:
 18 LogEvents are too few after 4 writes
Expected: True
Actual:   False
Stack Trace:

**Comment by snakefoot** [comment]
Looks all AsyncTaskTarget tests are failing because no timers are triggering. Very weird. Created #3294

**Comment by 304NotModified** [comment]
https://ci.appveyor.com/project/nlog/nlog/builds/23732577

**Comment by snakefoot** [comment]
Happy to see only one AsyncTaskTarget are failing, instead all of them. Guess more loving and care is needed

**Comment by snakefoot** [comment]
Created #3299

**Comment by 304NotModified** [comment]
Looks stable now :) thanks!
