### ISSUE TITLE
Log files are not created

### ISSUE THREAD

**Issue by prkishan** [NLog/NLog#3300]
I have installed the NLog package on Visual Studio Extension (VSIX) project and tried to generate logs with below configuration in config file,, but the log files are not creating. There are no internal exceptions or error messages too. Please let me know if this framework works with VS Extensions.

<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <targets>
        <target name="logfile" xsi:type="File" fileName="file.txt" />
    </targets>
    <rules>
        <logger name="*" minlevel="Info" writeTo="logconsole" />
    </rules>
</nlog>

NLog config and XML files are in the same location as NLog.dll file. I tried with basedir variable and also tried with an absolute path but it didn't work.

**Comment by prkishan** [comment]
For some reason configurations are not read from NLog.config file, evethough config file is in the same location as NLog.dll. I'm setting the configurations through API.

**Comment by snakefoot** [comment]
If you read the documentation about use of config files:

https://github.com/NLog/NLog/wiki/Configuration-file#configuration-file-locations

Then you will see that it look for `NLog.dll.nlog`:

- `NLog.dll.nlog`  in a directory where NLog.dll is located
