### ISSUE TITLE
NLog.NLogConfigurationException: Error when setting property 'Uppercase' on Layout Renderer: ${uppercase}

### ISSUE THREAD

**Issue by majumajid** [NLog/NLog#3308]
I tried to implement the NLog using this reference link (https://martynnw.wordpress.com/2016/10/16/logging-with-nlog-in-xamarin-forms/) and github(https://github.com/Martynnw/AndroidDemos/tree/master/LoggingDemo)

This error is encountering on this line 
**var config = new LoggingConfiguration();  //THIS LINE GENERATING ERROR**

```c#
 [assembly: Dependency(typeof(NLogManager))]
namespace LoggingDemo.Droid
{
    public class NLogManager : ILogManager
    {
        public NLogManager()
        {
             var config = new LoggingConfiguration();   
            var consoleTarget = new ConsoleTarget();
            config.AddTarget("console", consoleTarget);

            var consoleRule = new LoggingRule("*", LogLevel.Trace, consoleTarget);
            config.LoggingRules.Add(consoleRule);

            var fileTarget = new FileTarget();
            string folder = Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments);
            fileTarget.FileName = Path.Combine(folder, "Log.txt");
            config.AddTarget("file", fileTarget);

            var fileRule = new LoggingRule("*", LogLevel.Warn, fileTarget);
            config.LoggingRules.Add(fileRule);

            LogManager.Configuration = config;
        }

        public ILogger GetLog([System.Runtime.CompilerServices.CallerFilePath] string callerFilePath = "")
        {
            string fileName = callerFilePath;

            if (fileName.Contains("/"))
            {
                fileName = fileName.Substring(fileName.LastIndexOf("/", StringComparison.CurrentCultureIgnoreCase) + 1);
            }

            var logger = LogManager.GetLogger(fileName);
            return new NLogLogger(logger);
        }
    }
}
```

ERROR :

```
{NLog.NLogConfigurationException: Error when setting property 'Uppercase' on Layout Renderer: ${uppercase}
---> System.MissingMethodException: string[] string.Split(char,System.StringSplitOptions)
 at NLog.Internal.PropertyHelper.SetPropertyFromString (System.Object obj, System.String propertyName, System.String value,
 NLog.Config.ConfigurationItemFactory configurationItemFactory) [0x000b1] in <b575d0eed9dd4c07998e108d5c7bb2ad>:0
  --- End of inner exception stack trace ---
 at NLog.Internal.PropertyHelper.SetPropertyFromString (System.Object obj, System.String propertyName, System.String value,
 NLog.Config.ConfigurationItemFactory configurationItemFactory) [0x00163] in <b575d0eed9dd4c07998e108d5c7bb2ad>:0
 at NLog.Layouts.LayoutParser.ParseLayoutRenderer (NLog.Config.ConfigurationItemFactory configurationItemFactory,
 NLog.Internal.SimpleStringReader stringReader) [0x00145] in <b575d0eed9dd4c07998e108d5c7bb2ad>:0
 at NLog.Layouts.LayoutParser.CompileLayout (NLog.Config.ConfigurationItemFactory configurationItemFactory,
 NLog.Internal.SimpleStringReader sr, System.Boolean isNested, System.String& text) [0x0007b] in <b575d0eed9dd4c07998e108d5c7bb2ad>:0
 at NLog.Layouts.SimpleLayout.set_Text (System.String value) [0x00024] in <b575d0eed9dd4c07998e108d5c7bb2ad>:0
 at NLog.Layouts.SimpleLayout..ctor (System.String txt, NLog.Config.ConfigurationItemFactory configurationItemFactory) [0x0000d] in <b575d0eed9dd4c07998e108d5c7bb2ad>:0
 at NLog.Layouts.Layout.FromString (System.String layoutText, NLog.Config.ConfigurationItemFactory configurationItemFactory) [0x00000] in <b575d0eed9dd4c07998e108d5c7bb2ad>:0
 at NLog.Layouts.Layout.FromString (System.String layoutText) [0x00006] in <b575d0eed9dd4c07998e108d5c7bb2ad>:0
 at NLog.Layouts.Layout.op_Implicit (System.String text) [0x00000] in <b575d0eed9dd4c07998e108d5c7bb2ad>:0
 at NLog.Targets.TargetWithLayout..ctor () [0x00006] in <b575d0eed9dd4c07998e108d5c7bb2ad>:0
 at NLog.Targets.TargetWithLayoutHeaderAndFooter..ctor () [0x00000] in <b575d0eed9dd4c07998e108d5c7bb2ad>:0
 at NLog.Targets.ConsoleTarget..ctor () [0x00000] in <b575d0eed9dd4c07998e108d5c7bb2ad>:0
 at LogTest.Droid.NLogHelper.NLogManager..ctor () [0x0000f] in AppName\NLogManager.cs:23 }

 

 ```

**NLog version**:   4.6.2 

**Platform**:   Xamarin Android / Xamarin iOs /

**Comment by majumajid** [comment]
Kindly request you guys to help for fixing this

**Comment by 304NotModified** [comment]
Hi,

Could you check if you're using the .net standard dll or the xamarin version of NLog? (Properties of NLog.dll)

**Comment by 304NotModified** [comment]
PS the relevant error is here

    System.MissingMethodException: string[] string.Split(char,System.StringSplitOptions)

**Comment by majumajid** [comment]
> Hi,
> 
> Could you please check if you're using the .net standard dll or the xamarin version of NLog? (Properties of NLog.dll)

Well , i started project using .NET Standard ( Code sharing strategy)
![14-04-2019-07-11-15](https://user-images.githubusercontent.com/17178054/56094994-53554980-5ee9-11e9-8a12-40102e33088b.png)

**Comment by majumajid** [comment]
> PS the relevant error is here
> 
> ```
> System.MissingMethodException: string[] string.Split(char,System.StringSplitOptions)
> ```
> Related: https://developercommunity.visualstudio.com/content/problem/329057/xamarin-ios-build-got-systemmissingmethodexception.html

Well i am using window 10 and project in Xamarin.Forms and this error received on implementation of Android , the given link related with iOs

**Comment by snakefoot** [comment]
@majumajid I'm also guessing you are building with incompatible platform versions of Mono/NetCore/etc.

This is ofcourse a bug in the Xamarin-build-tools. It should not allow you to create and build an invalid project-setup.

**Comment by majumajid** [comment]
@snakefoot  i have installed this 
https://www.nuget.org/packages/NLog/4.6.2/, Well, its mentioned that it compatible  with Xamarin

**Comment by majumajid** [comment]
also this have github source , could you please check 
https://github.com/Martynnw/AndroidDemos/tree/master/LoggingDemo

![image](https://user-images.githubusercontent.com/17178054/56097851-a7bcf100-5f0a-11e9-9711-daf279804614.png)

**Comment by snakefoot** [comment]
What version of NetStandard have you chosen for your projects? Remember to choose NetStandard1.3 (or higher). Think it defaults to NetStandard1.1

**Comment by majumajid** [comment]
its seems higher than 1.3 
![image](https://user-images.githubusercontent.com/17178054/56098137-67f80880-5f0e-11e9-8380-69a73d21343b.png)

**Comment by snakefoot** [comment]
@majumajid Know very little about Xamarin. Think you should take your question to a Xamarin support forum about why your current setup throws `System.MissingMethodException` for this method:

> string[] string.Split(char,System.StringSplitOptions)

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/744

The funny thing is that NLog doesn't reference string.Split-method in `SetPropertyFromString`. Are you using latest version of Visual Studio?

**Comment by 304NotModified** [comment]
@snakefoot I think it's is used indirect for comma separated lists etc

**Comment by 304NotModified** [comment]
@majumajid 

I think you're mixin versions, e.g I see

    <HintPath>..\packages\NLog.4.3.10\lib\MonoAndroid10\NLog.dll</HintPath>

(Don't checked in depth, am I'm on mobile). 

See also:
https://stackoverflow.com/a/55650444/201303

**Comment by majumajid** [comment]
> 
> 
> > **NLog version**: 4.6.2
> > **Platform**: Xamarin Android / Xamarin iOs /
> 
> @majumajid
> 
> I think you're mixin NLog versions, e.g I see (in LoggingDemo.Droid.csproj)
> 
> ```
> <HintPath>..\packages\NLog.4.3.10\lib\MonoAndroid10\NLog.dll</HintPath>
> ```
> 
> (Don't checked in depth, am I'm on mobile).
> 
> See also:
> https://stackoverflow.com/a/55650444/201303

Well, I will check about this. 
I have created issue in xamarin : https://github.com/xamarin/Xamarin.Forms/issues/5916

**Comment by majumajid** [comment]
> 
> 
> > **NLog version**: 4.6.2
> > **Platform**: Xamarin Android / Xamarin iOs /
> 
> @majumajid
> 
> I think you're mixin NLog versions, e.g I see (in LoggingDemo.Droid.csproj)
> 
> ```
> <HintPath>..\packages\NLog.4.3.10\lib\MonoAndroid10\NLog.dll</HintPath>
> ```
> 
> (Don't checked in depth, am I'm on mobile).
> 
> See also:
> https://stackoverflow.com/a/55650444/201303

well, i am not mixing NLog version, i have tried to test after downloading this (LoggingDemo) project (its have NLog.4.3.10) and its also showing same error, and i have implemented in my new  project with NLog 4.6.2. 
So, Both version have same issue ,i have tried similar code in in console application and its working fine and writing log in text file.

**Comment by majumajid** [comment]
any one can help me to fix it ??

**Comment by 304NotModified** [comment]
Could you please create a demo application (as small a possible please), then we could check easier. (please do use the latest NLog version)

**Comment by majumajid** [comment]
Here i attached output log when  i am running

```
Resolved pending breakpoint at 'NLogManager.cs:38,1' to void LogTest.Droid.NLogHelper.NLogManager..ctor () [0x0009d].
Resolved pending breakpoint at 'NLogManager.cs:41,1' to void LogTest.Droid.NLogHelper.NLogManager..ctor () [0x000a8].
Resolved pending breakpoint at 'NLogManager.cs:40,1' to void LogTest.Droid.NLogHelper.NLogManager..ctor () [0x000a0].
Resolved pending breakpoint at 'NLogManager.cs:36,1' to void LogTest.Droid.NLogHelper.NLogManager..ctor () [0x00093].
Resolved pending breakpoint at 'NLogManager.cs:25,1' to void LogTest.Droid.NLogHelper.NLogManager..ctor () [0x00022].
Resolved pending breakpoint at 'NLogManager.cs:20,1' to void LogTest.Droid.NLogHelper.NLogManager..ctor () [0x00009].
04-17 23:49:16.603 D/Mono    (13752): Assembly Ref addref NLog[0xaadb1ac0] -> System[0xa3378c20]: 4
04-17 23:49:16.700 D/Mono    (13752): Assembly Ref addref NLog[0xaadb1ac0] -> System.Core[0xa33778a0]: 7
04-17 23:49:16.740 D/Mono    (13752): Image addref System.Xml[0x899b2a20] -> System.Xml.dll[0x899fa500]: 2
04-17 23:49:16.740 D/Mono    (13752): Prepared to set up assembly 'System.Xml' (System.Xml.dll)
04-17 23:49:16.740 D/Mono    (13752): Assembly System.Xml[0x899b2a20] added to domain RootDomain, ref_count=1
04-17 23:49:16.741 D/Mono    (13752): AOT: image 'System.Xml.dll.so' not found: dlopen failed: library "/data/app/com.companyname.LogTest-qMvmWJVb8qrvAy2NmxRd1A==/lib/x86/libaot-System.Xml.dll.so" not found
04-17 23:49:16.742 D/Mono    (13752): AOT: image '/Users/builder/jenkins/workspace/xamarin-android-d15-8/xamarin-android/external/mono/sdks/out/android-x86-release/lib/mono/aot-cache/x86/System.Xml.dll.so' not found: dlopen failed: library "/data/app/com.companyname.LogTest-qMvmWJVb8qrvAy2NmxRd1A==/lib/x86/libaot-System.Xml.dll.so" not found
04-17 23:49:16.743 D/Mono    (13752): Config attempting to parse: 'System.Xml.dll.config'.
04-17 23:49:16.743 D/Mono    (13752): Config attempting to parse: '/Users/builder/jenkins/workspace/xamarin-android-d15-8/xamarin-android/external/mono/sdks/out/android-x86-release/etc/mono/assemblies/System.Xml/System.Xml.config'.
04-17 23:49:16.743 D/Mono    (13752): Assembly Ref addref NLog[0xaadb1ac0] -> System.Xml[0x899b2a20]: 2
04-17 23:49:16.744 D/Mono    (13752): Assembly Ref addref System.Xml[0x899b2a20] -> mscorlib[0xaadb1040]: 46
Loaded assembly: System.Xml.dll [External]
04-17 23:49:17.160 D/Mono    (13752): Assembly Ref addref System.Core[0xa33778a0] -> System[0xa3378c20]: 5
04-17 23:49:37.066 I/mono-stdout(13752): NLog.NLogConfigurationException: Error when setting property 'Uppercase' on Layout Renderer: ${uppercase} ---> System.MissingMethodException: string[] string.Split(char,System.StringSplitOptions)
NLog.NLogConfigurationException: Error when setting property 'Uppercase' on Layout Renderer: ${uppercase} ---> System.MissingMethodException: string[] string.Split(char,System.StringSplitOptions)
04-17 23:49:37.081 I/mono-stdout(13752):   at NLog.Internal.PropertyHelper.SetPropertyFromString (System.Object obj, System.String propertyName, System.String value, NLog.Config.ConfigurationItemFactory configurationItemFactory) [0x000b1] in <b575d0eed9dd4c07998e108d5c7bb2ad>:0 
  at NLog.Internal.PropertyHelper.SetPropertyFromString (System.Object obj, System.String propertyName, System.String value, NLog.Config.ConfigurationItemFactory configurationItemFactory) [0x000b1] in <b575d0eed9dd4c07998e108d5c7bb2ad>:0 
   --- End of inner exception stack trace ---
  at NLog.Internal.PropertyHelper.SetPropertyFromString (System.Object obj, System.String propertyName, System.String value, NLog.Config.ConfigurationItemFactory configurationItemFactory) [0x00163] in <b575d0eed9dd4c07998e108d5c7bb2ad>:0 04-17 23:49:37.081 I/mono-stdout(13752):    --- End of inner exception stack trace ---

04-17 23:49:37.082 I/mono-stdout(13752):   at NLog.Internal.PropertyHelper.SetPropertyFromString (System.Object obj, System.String propertyName, System.String value, NLog.Config.ConfigurationItemFactory configurationItemFactory) [0x00163] in <b575d0eed9dd4c07998e108d5c7bb2ad>:0   at NLog.Layouts.LayoutParser.ParseLayoutRenderer (NLog.Config.ConfigurationItemFactory configurationItemFactory, NLog.Internal.SimpleStringReader stringReader) [0x00145] in <b575d0eed9dd4c07998e108d5c7bb2ad>:0 
  at NLog.Layouts.LayoutParser.CompileLayout (NLog.Config.ConfigurationItemFactory configurationItemFactory, NLog.Internal.SimpleStringReader sr, System.Boolean isNested, System.String& text) [0x0007b] in <b575d0eed9dd4c07998e108d5c7bb2ad>:0 
  at NLog.Layouts.SimpleLayout.set_Text (System.String value) [0x00024] in <b575d0eed9dd4c07998e108d5c7bb2ad>:0 

04-17 23:49:37.083 I/mono-stdout(13752):   at NLog.Layouts.LayoutParser.ParseLayoutRenderer (NLog.Config.ConfigurationItemFactory configurationItemFactory, NLog.Internal.SimpleStringReader stringReader) [0x00145] in <b575d0eed9dd4c07998e108d5c7bb2ad>:0   at NLog.Layouts.SimpleLayout..ctor (System.String txt, NLog.Config.ConfigurationItemFactory configurationItemFactory) [0x0000d] in <b575d0eed9dd4c07998e108d5c7bb2ad>:0 
  at NLog.Layouts.Layout.FromString (System.String layoutText, NLog.Config.ConfigurationItemFactory configurationItemFactory) [0x00000] in <b575d0eed9dd4c07998e108d5c7bb2ad>:0 
04-17 23:49:37.083 I/mono-stdout(13752):   at NLog.Layouts.LayoutParser.CompileLayout (NLog.Config.ConfigurationItemFactory configurationItemFactory, NLog.Internal.SimpleStringReader sr, System.Boolean isNested, System.String& text) [0x0007b] in <b575d0eed9dd4c07998e108d5c7bb2ad>:0 

04-17 23:49:37.084 I/mono-stdout(13752):   at NLog.Layouts.SimpleLayout.set_Text (System.String value) [0x00024] in <b575d0eed9dd4c07998e108d5c7bb2ad>:0 
  at NLog.Layouts.Layout.FromString (System.String layoutText) [0x00006] in <b575d0eed9dd4c07998e108d5c7bb2ad>:0 04-17 23:49:37.085 I/mono-stdout(13752):   at NLog.Layouts.SimpleLayout..ctor (System.String txt, NLog.Config.ConfigurationItemFactory configurationItemFactory) [0x0000d] in <b575d0eed9dd4c07998e108d5c7bb2ad>:0 

04-17 23:49:37.085 I/mono-stdout(13752):   at NLog.Layouts.Layout.FromString (System.String layoutText, NLog.Config.ConfigurationItemFactory configurationItemFactory) [0x00000] in <b575d0eed9dd4c07998e108d5c7bb2ad>:0 
  at NLog.Layouts.Layout.op_Implicit (System.String text) [0x00000] in <b575d0eed9dd4c07998e108d5c7bb2ad>:0 
  at NLog.Targets.TargetWithLayout..ctor () [0x00006] in <b575d0eed9dd4c07998e108d5c7bb2ad>:0 
  at NLog.Targets.TargetWithLayoutHeaderAndFooter..ctor () [0x00000] in <b575d0eed9dd4c07998e108d5c7bb2ad>:0 
  at NLog.Targets.ConsoleTarget..ctor () [0x00000] in <b575d0eed9dd4c07998e108d5c7bb2ad>:0 
  at LogTest.Droid.NLogHelper.NLogManager..ctor () [0x0000f] in D:\Office\Projects\LogTestApp\LogTest\LogTest\LogTest.Android\NLogHelper\NLogManager.cs:22 04-17 23:49:37.086 I/mono-stdout(13752):   at NLog.Layouts.Layout.FromString (System.String layoutText) [0x00006] in <b575d0eed9dd4c07998e108d5c7bb2ad>:0 

04-17 23:49:37.087 I/mono-stdout(13752):   at NLog.Layouts.Layout.op_Implicit (System.String text) [0x00000] in <b575d0eed9dd4c07998e108d5c7bb2ad>:0 
04-17 23:49:37.088 I/mono-stdout(13752):   at NLog.Targets.TargetWithLayout..ctor () [0x00006] in <b575d0eed9dd4c07998e108d5c7bb2ad>:0 
04-17 23:49:37.088 I/mono-stdout(13752):   at NLog.Targets.TargetWithLayoutHeaderAndFooter..ctor () [0x00000] in <b575d0eed9dd4c07998e108d5c7bb2ad>:0 
04-17 23:49:37.089 I/mono-stdout(13752):   at NLog.Targets.ConsoleTarget..ctor () [0x00000] in <b575d0eed9dd4c07998e108d5c7bb2ad>:0 
04-17 23:49:37.089 I/mono-stdout(13752):   at LogTest.Droid.NLogHelper.NLogManager..ctor () [0x0000f] in D:\Office\Projects\LogTestApp\LogTest\LogTest\LogTest.Android\NLogHelper\NLogManager.cs:22 
```

**Comment by majumajid** [comment]
Well, above log is when i didnt installed nlog.config. 
default, error is getting on this line :   var config = new LoggingConfiguration();   
            when i installed NLog.Config from the nuget, 
then error is getting from this line : var consoleTarget = new ConsoleTarget();
otherline

**Comment by majumajid** [comment]
Kindly advise

**Comment by majumajid** [comment]
i am using .net standard 2.0.3

**Comment by majumajid** [comment]
When installed nlog.config from nuget and 

error : 


04-18 00:35:59.350 I/mono-stdout(16209): NLog.NLogConfigurationException: Error when setting property 'Uppercase' on Layout Renderer: ${uppercase} ---> System.MissingMethodException: string[] string.Split(char,System.StringSplitOptions)
NLog.NLogConfigurationException: Error when setting property 'Uppercase' on Layout Renderer: ${uppercase} ---> System.MissingMethodException: string[] string.Split(char,System.StringSplitOptions)
  at NLog.Internal.PropertyHelper.SetPropertyFromString (System.Object obj, System.String propertyName, System.String value, NLog.Config.ConfigurationItemFactory configurationItemFactory) [0x000b1] in <b575d0eed9dd4c07998e108d5c7bb2ad>:0 04-18 00:35:59.370 I/mono-stdout(16209):   at NLog.Internal.PropertyHelper.SetPropertyFromString (System.Object obj, System.String propertyName, System.String value, NLog.Config.ConfigurationItemFactory configurationItemFactory) [0x000b1] in <b575d0eed9dd4c07998e108d5c7bb2ad>:0 

04-18 00:35:59.371 I/mono-stdout(16209):    --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
  at NLog.Internal.PropertyHelper.SetPropertyFromString (System.Object obj, System.String propertyName, System.String value, NLog.Config.ConfigurationItemFactory configurationItemFactory) [0x00163] in <b575d0eed9dd4c07998e108d5c7bb2ad>:0 
  at NLog.Layouts.LayoutParser.ParseLayoutRenderer (NLog.Config.ConfigurationItemFactory configurationItemFactory, NLog.Internal.SimpleStringReader stringReader) [0x00145] in <b575d0eed9dd4c07998e108d5c7bb2ad>:0 
  at NLog.Layouts.LayoutParser.CompileLayout (NLog.Config.ConfigurationItemFactory configurationItemFactory, NLog.Internal.SimpleStringReader sr, System.Boolean isNested, System.String& text) [0x0007b] in <b575d0eed9dd4c07998e108d5c7bb2ad>:0 
  at NLog.Layouts.SimpleLayout.set_Text (System.String value) [0x00024] in <b575d0eed9dd4c07998e108d5c7bb2ad>:0 
04-18 00:35:59.372 I/mono-stdout(16209):   at NLog.Internal.PropertyHelper.SetPropertyFromString (System.Object obj, System.String propertyName, System.String value, NLog.Config.ConfigurationItemFactory configurationItemFactory) [0x00163] in <b575d0eed9dd4c07998e108d5c7bb2ad>:0 
  at NLog.Layouts.SimpleLayout..ctor (System.String txt, NLog.Config.ConfigurationItemFactory configurationItemFactory) [0x0000d] in <b575d0eed9dd4c07998e108d5c7bb2ad>:0 
  at NLog.Layouts.Layout.FromString (System.String layoutText, NLog.Config.ConfigurationItemFactory configurationItemFactory) [0x00000] in <b575d0eed9dd4c07998e108d5c7bb2ad>:0 
  at NLog.Layouts.Layout.FromString (System.String layoutText) [0x00006] in <b575d0eed9dd4c07998e108d5c7bb2ad>:0 
  at NLog.Layouts.Layout.op_Implicit (System.String text) [0x00000] in <b575d0eed9dd4c07998e108d5c7bb2ad>:0 
  at NLog.Targets.TargetWithLayout..ctor () [0x00006] in <b575d0eed9dd4c07998e108d5c7bb2ad>:0 
  at NLog.Targets.TargetWithLayoutHeaderAndFooter..ctor () [0x00000] in <b575d0eed9dd4c07998e108d5c7bb2ad>:0 
  at NLog.Targets.ConsoleTarget..ctor () [0x00000] in <b575d0eed9dd4c07998e108d5c7bb2ad>:0 
04-18 00:35:59.374 I/mono-stdout(16209):   at NLog.Layouts.LayoutParser.ParseLayoutRenderer (NLog.Config.ConfigurationItemFactory configurationItemFactory, NLog.Internal.SimpleStringReader stringReader) [0x00145] in <b575d0eed9dd4c07998e108d5c7bb2ad>:0   at LogTest.Droid.NLogHelper.NLogManager..ctor () [0x0000f] in D:\Office\Projects\LogTestApp\LogTest\LogTest\LogTest.Android\NLogHelper\NLogManager.cs:22 

04-18 00:35:59.375 I/mono-stdout(16209):   at NLog.Layouts.LayoutParser.CompileLayout (NLog.Config.ConfigurationItemFactory configurationItemFactory, NLog.Internal.SimpleStringReader sr, System.Boolean isNested, System.String& text) [0x0007b] in <b575d0eed9dd4c07998e108d5c7bb2ad>:0 
04-18 00:35:59.375 I/mono-stdout(16209):   at NLog.Layouts.SimpleLayout.set_Text (System.String value) [0x00024] in <b575d0eed9dd4c07998e108d5c7bb2ad>:0 
04-18 00:35:59.376 I/mono-stdout(16209):   at NLog.Layouts.SimpleLayout..ctor (System.String txt, NLog.Config.ConfigurationItemFactory configurationItemFactory) [0x0000d] in <b575d0eed9dd4c07998e108d5c7bb2ad>:0 
04-18 00:35:59.376 I/mono-stdout(16209):   at NLog.Layouts.Layout.FromString (System.String layoutText, NLog.Config.ConfigurationItemFactory configurationItemFactory) [0x00000] in <b575d0eed9dd4c07998e108d5c7bb2ad>:0 
04-18 00:35:59.377 I/mono-stdout(16209):   at NLog.Layouts.Layout.FromString (System.String layoutText) [0x00006] in <b575d0eed9dd4c07998e108d5c7bb2ad>:0 
04-18 00:35:59.377 I/mono-stdout(16209):   at NLog.Layouts.Layout.op_Implicit (System.String text) [0x00000] in <b575d0eed9dd4c07998e108d5c7bb2ad>:0 
04-18 00:35:59.377 I/mono-stdout(16209):   at NLog.Targets.TargetWithLayout..ctor () [0x00006] in <b575d0eed9dd4c07998e108d5c7bb2ad>:0 
04-18 00:35:59.378 I/mono-stdout(16209):   at NLog.Targets.TargetWithLayoutHeaderAndFooter..ctor () [0x00000] in <b575d0eed9dd4c07998e108d5c7bb2ad>:0 
04-18 00:35:59.378 I/mono-stdout(16209):   at NLog.Targets.ConsoleTarget..ctor () [0x00000] in <b575d0eed9dd4c07998e108d5c7bb2ad>:0 
04-18 00:35:59.380 I/mono-stdout(16209):   at LogTest.Droid.NLogHelper.NLogManager..ctor () [0x0000f] in D:\Office\Projects\LogTestApp\LogTest\LogTest\LogTest.Android\NLogHelper\NLogManager.cs:22

**Comment by 304NotModified** [comment]
I will try to run your demo this week. Have to install Android SDK first :)

**Comment by 304NotModified** [comment]
Anyway,

NLog crashes as string[] string.Split(char,System.StringSplitOptions) crashes. (It's a system function!) It's a bit strange why what happens. 

Depending on the configuration, you still get this on another line, but bottom line, you can't run NLog with those crashing string[] string.Split(char,System.StringSplitOptions)

**Comment by 304NotModified** [comment]
Have you tried updating the Android SDK?

**Comment by majumajid** [comment]
> 
> 
> I will try to run your demo this week. Have to install Android SDK first :)

i have already installed android sdk as best of my knowledge.

**Comment by majumajid** [comment]
> 
> 
> Have you tried updating the Android SDK?

i wish to update because ,when i am running this project, i am getting this warning
```

Starting runtime checks
Starting emulator Android_Accelerated_x86_Oreo ...
1>------ Build started: Project: LogTest.Android, Configuration: Debug Any CPU ------
C:\Program Files (x86)\Android\android-sdk\emulator\emulator.EXE -partition-size 512 -no-boot-anim -avd Android_Accelerated_x86_Oreo -prop monodroid.avdname=Android_Accelerated_x86_Oreo
HAX is working and emulator runs in fast virt mode.
Your emulator is out of date, please update by launching Android Studio:
 - Start Android Studio
 - Select menu "Tools > Android > SDK Manager"
 - Click "SDK Tools" tab
 - Check "Android Emulator" checkbox
 - Click "OK"
```

**Comment by majumajid** [comment]
kindly advise

**Comment by 304NotModified** [comment]
@majumajid see https://github.com/xamarin/Xamarin.Forms/issues/4462

Update VS2017 to 15.9.2?

**Comment by majumajid** [comment]
@304NotModified  i wll update VS2017 to 15.9.11 , i will check working of this and let you know.

**Comment by majumajid** [comment]
i have updated VS2017 to 15.9.11 , issue fixed by updating VS2017.
Thank you so much for your great support

**Comment by 304NotModified** [comment]
I'm glad is has been resolved 👍
