### ISSUE TITLE
empty object in log when trying to output value from logged order object.

### ISSUE THREAD

**Issue by themythhimself** [NLog/NLog#3314]
Hi All,
I'm trying to output just the order id but all I get is a empty object in the log. I've created this simple console app just from the samples in the documentation which has the same issue as my larger app. I'd expect to see an object like

Edit:
Using NLOG 4.6.2

```json
{
OrderId : 1
}
```

but all i get is and empty json object

```json
{   }
```

here is my simple console app with the problem.

```C#
var logger = NLog.LogManager.GetCurrentClassLogger();
            var input = "";
            while(input != "x")
            {
                var order = new Order
                {
                    OrderId = 2,
                    Status = "Processing"
                };

                logger.Info("Test {value1}", order); // object Result:  Test MyProgram.Program+Order
                logger.Info("Test {@value1}", order); // object Result:  Test {"OrderId":2, "Status":"Processing"}
                logger.Info("Test {value1}", new { OrderId = 2, Status = "Processing" }); // anomynous object. Result: Test { OrderId = 2, Status = Processing }
                logger.Info("Test {@value1}", new { OrderId = 2, Status = "Processing" }); // anomynous object. Result:Test {"OrderId":2, "Status":"Processing"}

                input = Console.ReadLine();
            }

            Console.ReadLine();
```

Nlog.config file
```xml
    <target xsi:type="File" name="perf" fileName="PERFDATA-${shortdate}.log">
      <layout xsi:type="JsonLayout">
        <attribute name="orderid" layout="${event-properties:orderid}" />
      </layout>
    </target>
  </targets>

  <rules>
    <!-- add your logging rules here -->

    <!--
    Write all events with minimal level of Debug (So Debug, Info, Warn, Error and Fatal, but not Trace)  to "f"-->
    <logger name="*" minlevel="Debug" writeTo="perf" />
```

Any help appreciated

**Comment by themythhimself** [comment]
After some playing i figured I might have the wrong idea how this works?

For example do I need to log the properties into the message itself

```C#
logger.Info("Order Id: {orderid}", order.OrderId);
```

vs

```C#
logger.info("Order {@object}",order);
```

So that in my layout I can get the value order id.

```xml
<attribute name="message" layout="${event-properties:orderid}" />
```

**Comment by snakefoot** [comment]
I guess one could create a special layout renderer that was able to handle dot-lookup. Like this:

`logger.info("Order {myorder}",order);`

It could make use of the internal NLog ObjectReflectionCache. To extract a single dottet-property from an item in `LogEventInfo.Properties`.

`${object-properties:myorder.OrderId}`

PR are always welcome.

**Comment by 304NotModified** [comment]
For the object properties, this code could be copied: https://github.com/NLog/NLog.Web/blob/master/NLog.Web.AspNetCore/Internal/PropertyReader.cs

**Comment by themythhimself** [comment]
@snakefoot Thanks for your reply. Yes something like you described sounds like how I was thinking it worked. I'll have a go at making my own layout renderer and log PR if it works out :-)

@304NotModified This looks like a nice starting point for getting something working.

**Comment by snakefoot** [comment]
@themythhimself NLog 4.6.3 has been released with a new option:

`${event-properties:myOrder:objectpath=OrderId}`

See also https://github.com/NLog/NLog/wiki/EventProperties-Layout-Renderer
