### ISSUE TITLE
Nlog archiving

### ISSUE THREAD

**Issue by Shiva799** [NLog/NLog#3315]
Hi,
this is my nlog file setting

      <target name="file" xsi:type="File"
            layout="${longdate} | ${level:uppercase=true} | ${message} ${newline}
            ${event-properties:item=prop}"
    		archiveAboveSize="4096"
            keepFileOpen="true"
            encoding="utf-8" />

and code behind

    string filename = "file.log";
    var fileTarget = (FileTarget)config.FindTargetByName("file");
    fileTarget.FileName = Path.Combine(folder, filename);
    fileTarget.ArchiveFileName = "file.{##}.log";

What im getting:
Only one log file which later keeps on increasing in size as i use my app
what im expecting is: 
create the new log as per said name and number
Am i making a mistake? Help me out here thanks

**Comment by 304NotModified** [comment]
archiveAboveSize=4096, is 4KB size for a file. How big is the current file now?

please note, if you are using autoreload=true in the XML, then you need to re-apply the code changes after each reload

**Comment by Shiva799** [comment]
Thank you
its working the problem was wrong path file

**Comment by 304NotModified** [comment]
I'm glad is has been resolved 👍
