### ISSUE TITLE
XML namespaces are not supported

### ISSUE THREAD

**Issue by michael-ww** [NLog/NLog#3319]
Hi! Thanks for reporting this feature/bug/question! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

QUESTIONS are preferred on StackOverflow. You could expect a faster response there (but do include all the info below). Use the tag "nlog" https://stackoverflow.com/questions/ask

For .NET Core users, please check the platform support: https://github.com/NLog/NLog/wiki/platform-support

**NLog version：1.4.0

**Platform**: .NET Core 2.2

**Current NLog config** (nlog.config)

<?xml version="1.0" encoding="utf-8" ?>

<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xsi:schemaLocation="NLog NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true">

  
  <targets>
    
    <target xsi:type="File" name="fileTarget" fileName="c:\temp\console-example.log"
            layout="${date}|${level:uppercase=true}|${message} ${exception:format=tostring}|${logger}|${all-event-properties}" />
    <target xsi:type="Console" name="consoleTarget"
            layout="${date}|${level:uppercase=true}|${message} ${exception:format=tostring}|${logger}|${all-event-properties}" />
  </targets>

  
  <rules>
    <logger name="*" minlevel="Trace" writeTo="fileTarget,consoleTarget" />
  </rules>
</nlog>

- What is the current result?  ### **_XML namespaces are not supported_**
- What is the expected result?
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
- Please post full exception details (message, stacktrace, inner exceptions)
- Are there any workarounds? yes/no
- Is there a version in which it did work? 
- Can you help us by writing an unit test?

ConfigureAppConfiguration((hostBuilderContext, configurationBuilder) =>
            {
                configurationBuilder.AddXmlFile("nlog.config", optional: true, reloadOnChange: true);

            }).ConfigureServices((hostBuilderContext, serviceCollection) =>
            {

            }).ConfigureLogging((hostBuilderContext, loggingBuidler) =>
            {
                loggingBuidler.ClearProviders();
                loggingBuidler.AddProvider(new NLogLoggerProvider());
            });

**Comment by 304NotModified** [comment]
Got this working after all?

**Comment by michael-ww** [comment]
when i comment this line of code  "configurationBuilder.AddXmlFile("nlog.config", optional: true, reloadOnChange: true);", and just set "copy always", then it works well.
But the nlog.config still can't pass compiler verification.

**Comment by Sm1le291** [comment]
Hi! Why this bud was closed? It's still easy to reproduce, just get default App..config and pass to ConfigurationBuilder like below and you will get an exception

**Comment by snakefoot** [comment]
@Sm1le291 Please create [new issue](https://github.com/NLog/NLog/issues/new/choose) and fill out the issue-template with YOUR details. Please also explain in the new issue what you are trying to accomplish by calling `AddXmlFile(@"App.config");`.
