### ISSUE TITLE
support for CorrelationManager.ActivityId

### ISSUE THREAD

**Issue by tugberkugurlu** [NLog/NLog#332]
related to this question: http://stackoverflow.com/questions/23313627/how-can-i-log-the-correlationmanager-activityid-with-nlog

**Comment by 304NotModified** [comment]
This feature is present at the [NLog-Contrib hub](https://github.com/NLog/NLog-Contrib/blob/master/NLog.Contrib/LayoutRenderers/TraceActivityIdLayoutRenderer.cs).

So closing the out.
