### ISSUE TITLE
How to implement custom target?

### ISSUE THREAD

**Issue by ErcinDedeoglu** [NLog/NLog#3327]
I would like to implement custom target to NLog.
I want to put a web api log storage, and want to handle each log write request by sending web api request to remote restful service.

I tried to implement ITraceWriter but no luck (it's not coming to my breakpoint)

Could you provide an exit point please?

**Comment by 304NotModified** [comment]
Hi,

Are here: https://github.com/nlog/nlog/wiki/How-to-write-a-custom-target

**Comment by ErcinDedeoglu** [comment]
Awesome, thank you!
