### ISSUE TITLE
NLog reference to Standard .Net project

### ISSUE THREAD

**Issue by Tiago-OP** [NLog/NLog#3330]
Hello,

Im using a Standard project to create my NLog class/references, as I have projects using .Net Core and .Net Framework on the same solution.

When referencing that common standard project, for the Nlog classes, on .Net Core Projects it works fine, on .net framework project I got the following error:

System.IO.FileNotFoundException: 'Could not load file or assembly 'NLog, Version=4.0.0.0, Culture=neutral, 

To fix this, I must install the NLog nugget package on each of the projects.

**Comment by snakefoot** [comment]
It is not an NLog-issue but just an issue with Visual Studio and integration of .NetFramework- and .NetCore-projects.

Think the solution is to add the following to you .NetFramework-project:

`<RestoreProjectStyle>PackageReference</RestoreProjectStyle>`

See also: https://www.hanselman.com/blog/ReferencingNETStandardAssembliesFromBothNETCoreAndNETFramework.aspx

Remember to use .NetFramework 4.7.2 (or newer) for optimal experience.

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, please let us know!
