### ISSUE TITLE
Time Source perfomance speed

### ISSUE THREAD

**Issue by Encamy** [NLog/NLog#3331]
Hi!
There are some perfomance benchmarks on [Time Source wiki page](https://github.com/NLog/NLog/wiki/Time-Source). It's clear that AccurateLocal is slower than other time sources. So I've decided to run test using [BenchmarkDotNet](https://github.com/dotnet/BenchmarkDotNet).

NLog was forked from `dev` branch, commit: 3c16e69ae0bd6e33d16d1580882dce354c02d51c

Here is my results:
``` ini

BenchmarkDotNet=v0.11.5, OS=Windows 10.0.17763.437 (1809/October2018Update/Redstone5)
Intel Core i5-3570 CPU 3.40GHz (Ivy Bridge), 1 CPU, 4 logical and 4 physical cores
  [Host]     : .NET Framework 4.7.2 (CLR 4.0.30319.42000), 32bit LegacyJIT-v4.7.3324.0
  DefaultJob : .NET Framework 4.7.2 (CLR 4.0.30319.42000), 32bit LegacyJIT-v4.7.3324.0


```
|        Method |     Mean |    Error |   StdDev |   Median |      Min |      Max |
|-------------- |---------:|---------:|---------:|---------:|---------:|---------:|
|     FastLocal | 175.2 us | 7.286 us | 21.48 us | 165.6 us | 150.2 us | 234.2 us |
|       FastUtc | 175.5 us | 6.740 us | 19.77 us | 165.7 us | 153.7 us | 231.0 us |
| AccurateLocal | 174.9 us | 6.226 us | 18.36 us | 168.3 us | 154.1 us | 226.3 us |
|   AccurateUtc | 177.6 us | 6.036 us | 17.70 us | 172.6 us | 155.4 us | 229.0 us |

Test results shows that perfomance of all time sources are equal
Is perfomace tests on wiki page outdated or my result are incorrect?

Here is test code that i've used:
```C#
    [MinColumn, MaxColumn, MeanColumn, MedianColumn]
    public class TestLogSpeed
    {
        NLog.Logger m_logger = null;
        NLog.LoggingConfiguration m_config = null;
        private bool firstCallFastLocal = true;

        [GlobalSetup]
        public void Setup()
        {
           m_config = new LoggingConfiguration();
            var target = new FileTarget("target1")
            {
                FileName = "${basedir}/file.txt",
                Layout = @"${date:format=HH\:mm\:ss} ${level} ${message} ${exception}"
            };
            m_config.AddTarget(target);
            m_config.AddRuleForAllLevels(target);

            LogManager.Configuration = m_config;

            m_logger = NLog.LogManager.GetCurrentClassLogger();
        }

        public void TestFastLocal()
        {
            if (firstCallFastLocal == true)
            {
                firstCallFastLocal = false;
                TimeSource.Current = new FastLocalTimeSource();
            }

            m_logger.Info("Hello World");
        }

        [Benchmark]
        public void FastLocal() => TestFastLocal();
    }

    class Program
    {
        static void Main(string[] args)
        {
            var summary = BenchmarkRunner.Run<TestLogSpeed>();
        }
    }
```
(Other methods looks the same, so I do not paste them here)

I'm use BenchmarkDotNet for the first so I can do something wrong

**Comment by snakefoot** [comment]
Others have comes to the same conclusion to you, that their performance is much the same:

https://caraulean.com/2016/timestamp-accuracy-and-resolution-in-nlog/

**Comment by Encamy** [comment]
@snakefoot but 784 ns and 7 ns is a huge difference, so I can't agree that perfomance is the same

**Comment by snakefoot** [comment]
@Encamy Could also be that newer versions of NetFramework have made improvements to `DateTime.Now`

**Comment by Encamy** [comment]
After performing the test only for TimeSource (without writing to the file), it became clear that, as before, AccurateLocal is slower than AccurateUtc. I will prepare a PR that which will improve performance a bit.
