### ISSUE TITLE
NLog tutorial should define where configuration file must go in project directory.

### ISSUE THREAD

**Issue by kgilmer** [NLog/NLog#3334]
**NLog version**: N/A

**Platform**: .N/A

 - Why do we need it? So people can onboard more easily.
 - An example of the XML config, if relevant. N/A

The tutorial page mentions that a configuration file must be added for NLog to work, but doesn't explicitly say where the file should go, nor are there any obvious links to an example repo that would show a new user this information.  Text in question on page https://github.com/nlog/nlog/wiki/Tutorial:

```
NLog can be configured using XML by adding a NLog.config file to your application project (File Properties: Copy Always). This is a simple example of the content for NLog.config
```

**Comment by snakefoot** [comment]
It says:

> See also [Configuration File](https://github.com/nlog/nlog/wiki/Configuration-file#configuration-file-locations)

But will try and add the extra detail to the tutorial-page

**Comment by snakefoot** [comment]
Have now updated the tutorial with the following sentence:

> NLog will automatically load the NLog.config by [searching multiple file location](https://github.com/nlog/nlog/wiki/Configuration-file#configuration-file-locations)

Anyway the Wiki is open editing, so you can improve all you want.

**Comment by 304NotModified** [comment]
thanks @snakefoot !
