### ISSUE TITLE
Don't write with multiple threads to multiple files?

### ISSUE THREAD

**Issue by snakefoot** [NLog/NLog#3349]
Curious about this statement:

> Don't write with multiple threads to multiple files.

From https://github.com/NLog/NLog/wiki/performance

Is that from the old days with spinning harddisks, with performance hit when doing seeks? Or is it when one reuses(abuses) the same NLog FileTarget instance for writing to multiple appenders?

NLog has no issue with writing to multiple file-targets from multiple threads.

**Comment by 304NotModified** [comment]
I think thats for the (short) locks on the file. 

PS it's before my time.

**Comment by snakefoot** [comment]
> I think thats for the (short) locks on the file.

But having two threads that writes to two separate filetargets will not be affected more locking than usual.

It should rather say that if multiple threads are writing to the same filetarget, then it can be a good idea to use AsyncTarget-Wrapper.

**Comment by 304NotModified** [comment]
I'm thinking of this comment:

```
/// <summary>
    /// Multi-process and multi-host file appender which attempts
    /// to get exclusive write access and retries if it's not available.
    /// </summary>
    [SecuritySafeCritical]
    internal class RetryingMultiProcessFileAppender : BaseMutexFileAppender
```

**Comment by snakefoot** [comment]
Still having two threads that writes to two separate filetargets will not be affected more locking than usual.

**Comment by 304NotModified** [comment]
> Curious about this statement:
> 
> > Don't write with multiple threads to multiple files.

I think it should be "Don't write with multiple threads to the same file"

**Comment by 304NotModified** [comment]
Funny, me to blame. But I think I got it from another document

![image](https://user-images.githubusercontent.com/5808377/56991288-8e1cda00-6b97-11e9-8300-9261963e14ac.png)

**Comment by snakefoot** [comment]
Well now I have updated the advice to "Don't write with multiple threads to the same file" .

**Comment by 304NotModified** [comment]
👍 👍
