### ISSUE TITLE
Add internallogger event(s)

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#3350]
Easier to subscribe than  ` InternalLogger.LogWriter`

**Comment by snakefoot** [comment]
Would make sense to have a delegate. Maybe with these parameters:

`Logger(Type contextType, string contextInfo, LogLevel level, string message, object[] parameters)`

- `Type contextType` would be Target.GetType().
- `string contextInfo` could be `File(Name=myfile)`

This would allow one to setup a listener for the DatabaseTarget, by filtering on the `contextType`.

**Comment by snakefoot** [comment]
Resolved with #3796
