### ISSUE TITLE
Add require loaded config

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#3351]
Add helper for checking if the config is loaded and otherwise crash

for some applications where logging is critical.

**Comment by snakefoot** [comment]
Different than:

```c#
if (LogManager.Configuration == null)
    throw new Exception("Missing config");
```

**Comment by 304NotModified** [comment]
It's in some comparisons with other logging frameworks (as downside)

And yes, it won't be much more difficult than those code lines. We could also add that to the wiki.

**Comment by snakefoot** [comment]
You can now do this:

```c#
LogManager.Setup().LoadConfigurationFromFile(optional: false);
```

**Comment by 304NotModified** [comment]
Great!
