### ISSUE TITLE
Better DI support

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#3362]
Support DI providers. Difficult as logging is configured before the DI in our aspnet core example

**Comment by 304NotModified** [comment]
@snakefoot I think it's important to fix this, but I think we have to think of a design before implementing. I'm doubting to close https://github.com/NLog/NLog/pull/3128 for now, or do you think that's rude?

**Comment by 304NotModified** [comment]
What needs to be supported in this case:

1. Inject non NLog interfaces and classes into layout renderers and targets, e.g.
    

     ```c#

     class MyTarget{
             MyTarget(IMyTargetService service) { ...}

     }
2. Resolve NLog targets, layoutrs and layout renderers?
3. Resolve a custom target etc by DI (no need for "register"?)
3. 
3. Work correctly with NLog.Extensions.Logging, fix the issue that in the in main the injectables aren't ready (as configureService is later on)

- Currently when reading the XML config, the targets are "newed". Maybe that's too soon?

**Comment by snakefoot** [comment]
I would settle for having a ServiceProvider that one can register/lookup services.

Trying to do funky stuff like normal DependencyInjection frameworks are doing like scanning all types in all assemblies, and trying and perform fluffy-matching of constructur-parameters are out scope. Along with assigning special lifetime-traits to objects (singletons/disposable/etc.) is also out-of-scope.

**Comment by snakefoot** [comment]
> do you think that's rude?

You can do what you want. I just wanted a generic ServiceProvider than all these static properties. But I also wanted it to be very simple. People can then hook it up to more advanced DI-containers if neeeded.

**Comment by 304NotModified** [comment]
> People can then hook it up to more advanced DI-containers if needed.

>. People can then hook it up to more advanced DI-containers if needed.

Yes, that's the goal. 

FYI tried that with the current version (and some new code as extensions) for asp.net core 2 with MS DI, but failed. Got it working to create a new instance, but Write(LogEventInfo logEvent) was never called :(  (need to investigate that)

**Comment by 304NotModified** [comment]
Proposal:

```c#
interface IResolver{

    object Resolve(Type t);
}
```

Looks like: https://docs.microsoft.com/en-us/dotnet/api/system.iserviceprovider.getservice?view=netframework-4.8

**Comment by 304NotModified** [comment]
basic impl idea:

```c#
internal class DefaultResolver : IResolver, IRegisterDependecies{

Register<TInterface, TImplement>();
Register(Type from, Type to);

Resolve(Type t) {
 // Activator, check arguments
}

}
```

usage idea
```c#
DefaultResolver .Register<IJsonConverter, DefaultJsonSerializer>(); 
DefaultResolver .Register<FileTarget, FileTarget>();  //maybe?
```

**Comment by 304NotModified** [comment]
Adding resolve helper idea:

```c#
public static class ResolverExtensions{

    public static IJsonConverter GetJsonConverter(IResolver resolver);
    public static  IValueFormatter GetValueFormatter(IResolver resolver);


}

**Comment by 304NotModified** [comment]
I think we need this before splitting the packages, as we have hard references

**Comment by snakefoot** [comment]
So if we rename ServiceRepository to IServiceResolver in my suggested PR for resolving this, then we are home safe?


Sent from my Sony Xperia


---- Julian Verdurmen wrote ----


I think we need this before splitting the packages, as we have hard references

**Comment by snakefoot** [comment]
Know I'm responding to different issue. But could be nice to have NLog Extension Logging ver 1 5 1<tel:1%205%201> released. And updated Asp Netcore 4 8 3<tel:4%208%203> updated to use that version. Think the bug fix for async blocking is important.


Sent from my Sony Xperia


---- Julian Verdurmen wrote ----


I think we need this before splitting the packages, as we have hard references

**Comment by 304NotModified** [comment]
@snakefoot OK will work on it!

**Comment by 304NotModified** [comment]
@snakefoot all live :)

**Comment by 304NotModified** [comment]
> So if we rename ServiceRepository to IServiceResolver in my suggested PR for resolving this, then we are home safe?

Not really, https://github.com/NLog/NLog/pull/3128 is using service locator pattern, not sure if we should keep it like that. 

e.g.


```C#
 public class GdcLayoutRenderer {
     private IValueFormatter ValueFormatter => _valueFormatter ?? (_valueFormatter = LoggingConfiguration.GetServiceRepository ().ValueFormatter);
```
would be better to:

```c#
 public class GdcLayoutRenderer {

     public GdcLayoutRenderer(IValueFormatter valueFormatter){

         _valueFormatter = valueFormatter;
     }
```

**Comment by 304NotModified** [comment]
But have the downsides, that adding a dependency will be a breaking change

**Comment by snakefoot** [comment]
Think you are overenginering but if you like that then go ahead. Remember NLog is a log library


Sent from my Sony Xperia


---- Julian Verdurmen wrote ----


So if we rename ServiceRepository to IServiceResolver in my suggested PR for resolving this, then we are home safe?

Not really, #3128<https://github.com/NLog/NLog/pull/3128> is using service locator pattern, not sure if we should keep it like that.

e.g.

 public class GdcLayoutRenderer {
     private IValueFormatter ValueFormatter => _valueFormatter ?? (_valueFormatter = LoggingConfiguration.GetServiceRepository ().ValueFormatter);

would be better to:

 public class GdcLayoutRenderer {

     public GdcLayoutRenderer(IValueFormatter valueFormatter){

         _valueFormatter = valueFormatter;
     }

**Comment by 304NotModified** [comment]
> Think you are overenginering but if you like that then go ahead. Remember NLog is a log library
> […](#)

I did a lot with DI last 1-2 years, I'm getting used to constructor injection

**Comment by snakefoot** [comment]
Well usually you want lazy initialization and not at construction-time. So the lookup of the interface implementation should be as late as possible.


Sent from my Sony Xperia


---- Julian Verdurmen wrote ----


Think you are overenginering but if you like that then go ahead. Remember NLog is a log library
…

I did a lot with DI last 1-2 years, I'm getting used to constructor injection

**Comment by wehadfun** [comment]
> ... Remember NLog is a log library

Out of curiosity what does "Remember NLog is a log library" mean?

**Comment by snakefoot** [comment]
> @wehadfun  Out of curiosity what does "Remember NLog is a log library" mean?

Means NLog should focus on being good at logging, and not try to [include everything but the kitchen sink](https://idioms.thefreedictionary.com/everything+but+the+kitchen+sink).

**Comment by snakefoot** [comment]
Created  #3616 as new attempt to introduce dependency injection in NLog.

**Comment by 304NotModified** [comment]
replaced with https://github.com/NLog/NLog/issues/3675. So we have a simple todo list
