### ISSUE TITLE
Remove old examples, add new

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#3374]
Remove the old stuff (everything?) from the examples dir

**Comment by snakefoot** [comment]
Created #4685 to remove Silverlight and WindowsPhone Apps

**Comment by snakefoot** [comment]
When https://github.com/NLog/NLog.Windows.Forms/pull/95 has been merged, then all Winforms-samples can be removed.

**Comment by 304NotModified** [comment]
no steps plan anymore here
