### ISSUE TITLE
MessageTemplateParameters.IsValidTemplate is behaving funky

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#3375]
got some interesting results with `MessageTemplateParameters.IsValidTemplate`:

![image](https://user-images.githubusercontent.com/5808377/55676396-fcda8080-58d4-11e9-9651-3136b146e581.png)

With an empty list as `object[] parameters` , is always says `IsValidTemplate=true` - independent of the message-template. 

See also unit test here: https://github.com/NLog/NLog/pull/3286

**Comment by nishantgupta204** [comment]
I was looking at the issue. I was wondering why below test case should be passed. The parameter count should be 1.

IsValidTemplateTest(input:{A} {A}, parameterCount: 2, expected :True)

**Comment by 304NotModified** [comment]
Currently it does make the values distinct (performance reasons)

**Comment by snakefoot** [comment]
I don't see any of the reported issues as a bugs:
- NLog have never parsed the message template when not provided any parameters.
- NLog simulates Microsoft Extension Logging, that also sees "{A} {A}" as two individual parameters
   - One might consider that `IsValidTemplate` should become false, but there will be a performance hit to do this checking that will hurt all just to save a few.
- NLog also captures the format specifier, so the following "{0} {0,-18]" should also return two individual parameters with different Format.

**Comment by 304NotModified** [comment]
Then we need to fix the tests only ;)

**Comment by snakefoot** [comment]
Have fixed two of the failing tests in PR #3541 (The one without parameters have been commented out)

**Comment by snakefoot** [comment]
@304NotModified Guess this has been resolved with NLog 4.6.7 ?

**Comment by 304NotModified** [comment]
Thanks!
