### ISSUE TITLE
VS2017 NuGet GUI NLog.Config does not install dependency packages (NLog, NLog.Schema)

### ISSUE THREAD

**Issue by GreatFireWall** [NLog/NLog#3379]
Document description incorrect or nuget package bug ?

![image](https://user-images.githubusercontent.com/4510984/57371756-364d2700-71c6-11e9-8b30-40c37350a4ba.png)

And I never see `NLog.config` add in my project.

**NLog version**: 4.6.3

**Platform**: .Net 4.6.2

**NuGet Console Version**: 4.9.3.5777

**Current NLog config**: No automatic installation

![image](https://user-images.githubusercontent.com/4510984/57371721-14ec3b00-71c6-11e9-9451-a15c322b06e0.png)

**Comment by 304NotModified** [comment]
Unfortunately you need to create the config file yourself. You can find it here: https://github.com/NLog/NLog/blob/dev/src/NuGet/NLog.Config/content/NLog.config

The xsd can be found online: https://nlog-project.org/schemas/NLog.xsd

**Comment by 304NotModified** [comment]
Unfortunately you need to create the config file yourself. You can find it here: https://github.com/NLog/NLog/blob/dev/src/NuGet/NLog.Config/content/NLog.config

The xsd can be found online: https://nlog-project.org/schemas/NLog.xsd

**Comment by GreatFireWall** [comment]
OK, thanks, I will try it.

**Comment by snakefoot** [comment]
@GreatFireWall Think the phrase "this will also install NLog" requires some knowledge about nuget.

Nuget will only show the direct package (This case NLog.config) as installed, but it will behind your back install **ALL** packages that the direct package is depending on. (This case NLog + NLog.Schema).

**Comment by GreatFireWall** [comment]
@304NotModified I had try use `openFileFlushTimeout` attribute, but get warning it's no declaration.

It seems not define in `https://nlog-project.org/schemas/NLog.xsd`

**Comment by 304NotModified** [comment]
> @304NotModified I had try use `openFileFlushTimeout` attribute, but get warning it's no declaration.
> 
> It seems not define in `https://nlog-project.org/schemas/NLog.xsd`

I've updated the XSD online. It's unfortunately not in your build/release script

**Comment by GreatFireWall** [comment]
OK, work well, thank you :)
