### ISSUE TITLE
Update XSD on github.io in build script

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#3383]
manual or release script to update https://github.com/NLog/NLog.github.io/blob/master/schemas/NLog.xsd

**Comment by 304NotModified** [comment]
mabye artifact also on appVeyor?

**Comment by yyjdelete** [comment]
Seems `defaultAction` in `<filters/>` is missing from the xsd file, is this the right issue?
https://github.com/NLog/NLog/wiki/Filtering-log-messages

**Comment by 304NotModified** [comment]
Hi! 

That's another issue. Most of the things in the xsd are generated, but I guess it isn't for defaultAction then. https://github.com/NLog/NLog/blob/dev/tools/MakeNLogXSD/TemplateXSD.xml needs to be updated

**Comment by 304NotModified** [comment]
@yyjdelete created #3396 for your issue.
