### ISSUE TITLE
`defaultAction` in `<filters/>` is missing from the xsd file

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#3396]
Seems `defaultAction` in `<filters/>` is missing from the xsd file, is this the right issue?
https://github.com/NLog/NLog/wiki/Filtering-log-messages

_Originally posted by @yyjdelete in https://github.com/NLog/NLog/issues/3383#issuecomment-491506383_

**Comment by 304NotModified** [comment]
@yyjdelete created 

any change to test https://ci.appveyor.com/api/buildjobs/6b9cgwifk7hif545/artifacts/artifacts%2FNLog.Schema.4.6.3.nupkg

?

**Comment by yyjdelete** [comment]
@304NotModified It works for me.

**Comment by 304NotModified** [comment]
Thanks!

Fixed by https://github.com/NLog/NLog/pull/3392
