### ISSUE TITLE
Can not find MessageBox target

### ISSUE THREAD

**Issue by aisen0921** [NLog/NLog#3397]
I created a new winform project (C# .NET 4.6.2),
and install NLog、NLog.config、NLog.Windows.Form、NLog.Schema from NuGet.

When I used target type  MessageBox ,
it appear invalid  type.

What have I lost setting?

**Comment by 304NotModified** [comment]
Hi, where do you see the error? If it's in the xsd, it's a warning and you could ignore that without problems. If it isn't in the xsd, please provide a stacktrace.

**Comment by aisen0921** [comment]
It's works fine now.
Thanks for help!
