### ISSUE TITLE
Make Log events Serializable

### ISSUE THREAD

**Issue by ghost** [NLog/NLog#34]
> in Log4net, the remoting appender sends a log event to the server. This is the kind of behavior I'm looking for in nlog. I could write my own target, but unless the log events are serializable, there's no way to send them up to the server.
> 
> (by the way, I'd go ahead and use Log4net and create my own appender, but there are no fallback mechanisms supported in Log4net yet as there is in NLog - good job on that.)

Moved from http://nlog.codeplex.com/workitem/2323

**Comment by snakefoot** [comment]
@304NotModified Now we have CsvLayout + JsonLayout + log4jxmlevent + XmlLayout. Think there are all the options you need to serialize NLog LogEvents in whatever format you need.

**Comment by 304NotModified** [comment]
Is `ISerializable ` Deprecated ? it's in .NET Standard 2?

**Comment by snakefoot** [comment]
> @304NotModified  Is ISerializable Deprecated ? it's in .NET Standard 2?

I was talking about "Remoting"

**Comment by 304NotModified** [comment]
true,

You will also need `ISerializable` for external cache and MSMQ afaik, but all of them aren't common to store logevents.

**Comment by 304NotModified** [comment]
This is not planned
