### ISSUE TITLE
Question: Saving text to varchar(max) column

### ISSUE THREAD

**Issue by Miguel-ezh** [NLog/NLog#3402]
I have a "Database" target that is using an stored procedure to log some information into a table:

``` xml
<target name="MessageLogger" xsi:type="Database" connectionString="ConnectionString"
            commandText="exec MessageLog_Log @TransactionId, @MessageType, @Direction, @NetworkId, @Url, @Message" dbProvider="mssql">
  <parameter name="@TransactionId" layout="${mdc:TransactionId}" xsi:type="NLog.Targets.DatabaseParameterInfo"/>
  <parameter name="@MessageType" layout="${event-context:item=MessageType}" xsi:type="NLog.Targets.DatabaseParameterInfo"/>
  <parameter name="@Direction" layout="${event-context:item=Direction}" xsi:type="NLog.Targets.DatabaseParameterInfo"/>
  <parameter name="@NetworkId" layout="${event-context:item=NetworkId}" xsi:type="NLog.Targets.DatabaseParameterInfo"/>
  <parameter name="@Url" layout="${event-context:item=Url}" xsi:type="NLog.Targets.DatabaseParameterInfo"/>
  <parameter name="@Message" layout="${event-context:item=Message}" xsi:type="NLog.Targets.DatabaseParameterInfo"/>
</target>
```

Both the stored procedure and table are using a VARCHAR(MAX) for the parameter 'Message', sometimes the value for 'Message' is a little bigger(around 100,000 characters) but when is stored the string is truncated(around 43,000 characters)

My questions are:
1.- Does NLog truncate strings for Database parameters? 
2.- Is there is any way to specify the actual type of the parameter?

**Comment by 304NotModified** [comment]
1. Nope
2.  Set the dbtype on the parameter, see https://github.com/NLog/NLog/wiki/Database-target

**Comment by 304NotModified** [comment]
This could be the problem: https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/configure-the-max-text-repl-size-server-configuration-option?view=sql-server-2017

See also https://stackoverflow.com/questions/40850221/log4net-limiting-to-about-43000-characters#40850242

**Comment by snakefoot** [comment]
@Miguel-ezh Have you tried to set the size property for the VARCHAR(MAX) column to `"-1"` ?

**Comment by Miguel-ezh** [comment]
Thanks, for the quick response.

@304NotModified yes, I think is the replication. I have had this problem before.... 

@snakefoot I will do more test, thanks for the help
