### ISSUE TITLE
Remove obsolete dependency Microsoft.Extensions.PlatformAbstractions

### ISSUE THREAD

**Issue by snakefoot** [NLog/NLog#3407]
It is only being used for netstandard1.3 (UWP1 etc.) for writing Application Assembly-version.

But it seems that it might get a bad treatment in the future.

See also: https://github.com/dotnet/corefx/issues/35068 + https://github.com/dotnet/corefx/issues/35068

Also curious how to handle NetCore1 being unsupported this year. Should one remove NetCore1 support from NLog?

**Comment by 304NotModified** [comment]
> Also curious how to handle NetCore1 being unsupported this year. Should one remove NetCore1 support from NLog?

Good question. 

Dunno how Xamarin etc are on .NET Standard 2 yet.

**Comment by 304NotModified** [comment]
> Also curious how to handle NetCore1 being unsupported this year. Should one remove NetCore1 support from NLog?

I think it's wise to remove .NET COre 1 support if it's officially unsupported.

**Comment by snakefoot** [comment]
I guess there is a difference between NetCore1 (platform) and netstandard1 (api) other platforms than NetCore1 might like the support of Netstandard1. Maybe wait one year after NetCore1 end-of-life to consider removing netstandard1 support


Sent from my Sony Xperia


---- Julian Verdurmen wrote ----


Also curious how to handle NetCore1 being unsupported this year. Should one remove NetCore1 support from NLog?

I think it's wise to remove .NET COre 1 support if it's officially unsupported.

**Comment by 304NotModified** [comment]
Good one! If .net standard 1 isn't deprecated, then it's another story indeed

**Comment by snakefoot** [comment]
Now the nuget-package have become obsolete, so guess a good time to remove it:

https://www.nuget.org/packages/Microsoft.Extensions.PlatformAbstractions/

**Comment by 304NotModified** [comment]
isn't .NET standard 1 also obsolete? 

So IMO remove .NET Standard 1 support = fix this issue

**Comment by snakefoot** [comment]
NetStandard1.X defines an API, and it is not obsolete. It is forever just like NET35

Sent from my Galaxy



-------- Original message --------
From: Julian Verdurmen ***@***.***>
Date: 12/08/2022 11:39 (GMT+01:00)
To: NLog/NLog ***@***.***>
Cc: Rolf Kristensen ***@***.***>, Author ***@***.***>
Subject: Re: [NLog/NLog] Remove dependency on Microsoft.Extensions.PlatformAbstractions (#3407)


isn't .NET standard 1 also obsolete?

So IMO remove .NET Standard 1 support = fix this issue
