### ISSUE TITLE
BufferingTargetWrapper should supress the timer while waiting the lock

### ISSUE THREAD

**Issue by rusanu** [NLog/NLog#3410]
We noticed a situation when the `BufferingTargetWrapper` timer was leading to thread pool starvation because actual flushing was slower than the timer interval. Hundreds of threads are blocked in this stack:

```
        Child SP               IP Call Site
000000ebef0be938 00007ff94e7c6654 [GCFrame: 000000ebef0be938] 
000000ebef0beb50 00007ff94e7c6654 [GCFrame: 000000ebef0beb50] 
000000ebef0beb88 00007ff94e7c6654 [HelperMethodFrame: 000000ebef0beb88] System.Threading.Monitor.Enter(System.Object)
000000ebef0bec80 00007ff8e5f34553 NLog.Targets.Wrappers.BufferingTargetWrapper.FlushCallback(System.Object)
000000ebef0bece0 00007ff93e935ab3 System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
000000ebef0bedb0 00007ff93e935944 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
000000ebef0bede0 00007ff93e96b0ba System.Threading.TimerQueueTimer.CallCallback()
000000ebef0bee40 00007ff93e96aeb7 System.Threading.TimerQueueTimer.Fire()
000000ebef0beeb0 00007ff93e925b05 System.Threading.TimerQueue.FireNextTimers()
000000ebef0bf328 00007ff941636da3 [DebuggerU2MCatchHandlerFrame: 000000ebef0bf328] 
000000ebef0bf4b8 00007ff941636da3 [ContextTransitionFrame: 000000ebef0bf4b8] 
000000ebef0bf6e8 00007ff941636da3 [DebuggerU2MCatchHandlerFrame: 000000ebef0bf6e8] 
```

The target can be slow due to transient conditions. Is not feasible to increase the flush timer in config as to cover such transient conditions. It would be better if the [`FlushCallback`](https://github.com/jkowalski/NLog/blob/master/src/NLog/Targets/Wrappers/BufferingTargetWrapper.cs#L188) is either suppressing the timer (change to infinite) and restore it at exit, or have a state flag indicating that another flush timer thread is already waiting and exit immediately.

**Comment by snakefoot** [comment]
@rusanu Think the work-around until a fix is made is to configure `SlidingTimeout="False"`

**Comment by snakefoot** [comment]
Created PR #3412

**Comment by snakefoot** [comment]
@304NotModified Guess you can add this issue to 4.6.4

**Comment by 304NotModified** [comment]
Thanks!

**Comment by snakefoot** [comment]
@rusanu NLog 4.6.4 has been released: https://www.nuget.org/packages/NLog/4.6.4

Please tell if it resolves your issue with timer-threads building up.
