### ISSUE TITLE
NLog\NLog.config installing

### ISSUE THREAD

**Issue by nvchernov** [NLog/NLog#3418]
Hi, I had situation when I install nlog and nlog.cofing form nuget for project A. 

Then I configured NLog.config file. 
Then I installed NLog from nuget (without nlog.config) for project B.

Logging was not working for project B until I install nlog.cofing from nuget for project B.
It's not user-friendly acting (I mean not user-friendly - it's when i waste time to understand install problem), I think config metadata should be installed just when I install nlog from nuget.

Thanks!

**Comment by 304NotModified** [comment]
Is project B a class library or another type?

**Comment by nvchernov** [comment]
@304NotModified, yes, project B is class library

**Comment by 304NotModified** [comment]
Then there should be something else wrong. There is no need to install the NLog.config package on class library, only the NLog package. 

Im doing that for years without problems

**Comment by 304NotModified** [comment]
If you have an small example solution, I could check it

**Comment by nvchernov** [comment]
@304NotModified, ok i'll try to reproduce and make instructions (I need few days)

**Comment by nvchernov** [comment]
@304NotModified, hi, i tried to reproduce this problem and I cant. I got this problem in very large project, may be it was install problem, may be I forgot something.

Anyway thanks for your answers, next time first thing I'll make is reproduce bug in test proj

**Comment by 304NotModified** [comment]
I think it could be an issue with locked files and nuget, so reinstall of NLog would helped. 

Anyway, let me know if the issue is back
