### ISSUE TITLE
Use separator in stacktrace layout renderer even when format is raw

### ISSUE THREAD

**Issue by SuperCorks** [NLog/NLog#3419]
**NLog version**:  4.6.3

**Platform**:  Xamarin Android / Xamarin iOS

I don't know if it's been coded like that by design, but when the `${stacktrace}` layout renderer is in `format=Raw`, the `separator` property isn't used. You can clearly see that in the source code:

https://github.com/NLog/NLog/blob/dev/src/NLog/LayoutRenderers/StackTraceLayoutRenderer.cs#L127

This feature request is to enable the `separator` property even when `format=Raw`.

Thanks

**Comment by 304NotModified** [comment]
Good one! I think the separator option is added later. 

I propose to change this in 5.0 (next non-patch release)

**Comment by 304NotModified** [comment]
Is the default of " => " maybe wierd in combination with raw?
