### ISSUE TITLE
Decide what to do with <logger> and <rule>

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#3420]
Introduced in https://github.com/NLog/NLog/pull/2891

**Comment by snakefoot** [comment]
Right now one can do this (Works very well with `nlog.config`)

```xml
<rules>
   <logger name="*" rulename="hello" />
</rules>
```

And one can also do this (Works very well with `appsettings.json`)

```xml
<rules>
   <rule logger="*" name="hello" />
</rules>
```

```json
 "rules": [
      {
        "logger": "*",
        "name": "hello"
      }
 ]
```

Is some change required here?

**Comment by 304NotModified** [comment]
Guess not 🙂
