### ISSUE TITLE
Feature: list contextProperties of Logger

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#3422]
Make _contextProperties public on the Logger object.

Discussion: read-only or mutable?

asked here: https://stackoverflow.com/questions/56278360/nlog-list-property-values

**Comment by snakefoot** [comment]
> Discussion: read-only or mutable?

I vote for readonly using `IReadOnlyDictionary` (Only have the property on platforms where interface is supported).

**Comment by 304NotModified** [comment]
I checked the code. I think IDictionary is flexible enough. If we need to know changes in the dictionary, we could implement this.

**Comment by snakefoot** [comment]
Doesn't make sense. You can modify using the IDictionary-interface. It is way too flexible. You will get `Collection was modified`-exceptions

**Comment by 304NotModified** [comment]
Do we need also a clone then? (I think so)

**Comment by snakefoot** [comment]
> Do we need also a clone then? (I think so)

Would be very confusing to get a mutable dictionary returned, and your changes doesn't have any effect.

I continue to vote for `IReadOnlyDictionary`

**Comment by 304NotModified** [comment]
That's clear ;)

But besides IReadOnlyDictionary we need a clone then. Otherwise your could cast it back. Unfortunately, you could always change and object living in the dictionary

**Comment by snakefoot** [comment]
Trying to protect yourself from a developer is hard work, and seldom gives any bonus.

Developer can also do reflection and access the dictionary that way.

The goal is to provide an easy to understand interface.

**Comment by 304NotModified** [comment]
fixed by #3430
