### ISSUE TITLE
Context classes (gdc, mdc etc), make key case-insensitive

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#3425]
Proposal

Makes things easier.

It could be also an option, but a bit tricky with the statics

**Comment by snakefoot** [comment]
Think it makes sense to be case-insensitive. Could also consider doing it for LogEventInfo.Propertiers.

Maybe with some special sugar for LogEventInfo.Properties, when the message-template contains the same property-name with different casing (Ex. add suffix `_1`)

**Comment by 304NotModified** [comment]
Good ideas!

**Comment by snakefoot** [comment]
#4366 resolved this for GDC
#4124 resolved this for MDC / MDLC (Replaced by ScopeContext)
#816 resolved this for NLog Config Variables.

**Comment by snakefoot** [comment]
The effort required to fix this for NLog LogEventInfo.Properties is more than I want to bite.

And it would also divert from the behavior found in other logging-frameworks,

**Comment by snakefoot** [comment]
Guess this should be resolved with NLog 5.0, but create new issue for NLog 6.0 to fix LogEventInfo.Properties ?

**Comment by snakefoot** [comment]
Created #4507 and closing this for NLog 5.0
