### ISSUE TITLE
${callsite} and related, ignore by namespace

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#3426]
Currently we could ignore by assembly,

but a much easier to understand feature would be to ignore by namespace. Also helpful to fix bugs like:  https://github.com/NLog/NLog/issues/3421

**Comment by 304NotModified** [comment]
This should be ignored by default then

```
Microsoft.*
System.*
```

**Comment by snakefoot** [comment]
Duplicate of #1145 ?

**Comment by 304NotModified** [comment]
Yes indeed
