### ISSUE TITLE
Unable to write to NLog in kubernetes containers

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#3446]
@ram62836 wrote:

```xml
<targets>
    <target xsi:type="File" name="ApplicationLog" fileName="/logs/application-${date:format=yyyyMMdd}.log"
            layout="${longdate} ${message} ${exception:format=tostring}" archiveEvery="Day" maxArchiveFiles="14" concurrentWrites="true" keepFileOpen="false" />
    <target xsi:type="File" name="RequestLog" fileName="/logs/requests-${date:format=yyyyMMdd}.log"
            layout="${message}" archiveEvery="Day" maxArchiveFiles="14" concurrentWrites="true" keepFileOpen="false" />
</targets>
<rules>
    <logger name="*" minlevel="Trace" writeTo="ApplicationLog" final="true" />
    <logger name="RequestLogger" minlevel="Trace" writeTo="RequestLog" final="true" />
</rules>
```

Above is my nlog config, this creates log file in the linux container mounted path. Im using kubernetes persistent volume.
As soon as it starts writing application hangs.

**Comment by 304NotModified** [comment]
@ram62836 is this still an issue?

Please don't use the wiki as issue reporting, it's not monitored and we found this by luck

**Comment by 304NotModified** [comment]
We need more info. One of the possibles issues:

- NLog config is read before start of the main() and nlog.config is missing or corrupt. See https://stackoverflow.com/q/34994470/201303

**Comment by ram62836** [comment]
What extra information should i add?

**Comment by 304NotModified** [comment]
Please fill in this template: https://github.com/NLog/NLog/issues/new?template=bug_report.md

**Comment by 304NotModified** [comment]
Please also check https://github.com/nlog/nlog/wiki/Logging-troubleshooting

**Comment by snakefoot** [comment]
@ram62836 Consider using absolute file path should be used that matches the mounted volumes configured. Kubernetes write permissions should of course be given. 

Good idea to upgrade to latest NLog and check the internal logging (maybe redirect to console if that is working)

**Comment by swathicv** [comment]
@ram62836 : did above mentioned issue is resolved? we are facing same issue

**Comment by ram62836** [comment]
The issue in our case is not Nlog, we are hosting our app in kubernetes and
using persistent volume (NFS) to write logs.
The issues seems to be at dotnet runtime, which was unable to read]write
files onto NFS volume in kubernetes.
