### ISSUE TITLE
Rules -> logging -> minlevel can not read the config from appsettings

### ISSUE THREAD

**Issue by LiuSikChung** [NLog/NLog#3447]
NLog version: 4.6.4

Platform: .Net Framework 4.6.1
```xml
  <nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <extensions>
      <add assembly="NLog.Extended" />
    </extensions>
    
    <variable name="logLevel" value="level &gt;= LogLevel.Info" />
    <variable name="AppLogLevel" value="${appsetting:LogLevel}" />
    <variable name="logFolder" value="${appsetting:LogRoot}\${environment:variable=USERNAME}\${machinename}" />
    <variable name="logFileNameRoot" value="${appsetting:ApplicationName}" />
    
    <targets async="true">
      <default-target-parameters xsi:type="File" createDirs="true" keepFileOpen="false" layout="${time}${literal:text=\t}${message}" />
      <target xsi:type="File" name="dataFile" fileName="${logFolder}\${logFileNameRoot}-data.log" archiveFileName="${var:logFolder}/archive/${var:logFileNameRoot}/${shortdate}.{##}.log" archiveNumbering="Sequence" archiveEvery="Day" maxArchiveFiles="2">
        <layout xsi:type="CSVLayout" delimiter="Tab">
          <column name="date" layout="${longdate}" />
          <column name="level" layout="${level}" />
          <column name="logger" layout="${logger}" />
          <column name="thread" layout="[${threadid}]" />
          <column name="message" layout="${message}" />
          <column name="callsite" layout="${callsite}" />
          <column name="exception" layout="${exception:format=tostring}" />
        </layout>
      </target>
    </targets>
    <rules>
      <logger name="dataLog" minlevel="${AppLogLevel}" writeTo="dataFile" final="true" />
      <logger name="*" minlevel="Info" writeTo="logfile" />
    </rules>
  </nlog>
```
- What is the current result?
Can not write log files.
```xml
  <appSettings>
    <add key="ApplicationName" value="Test" />
    <add key="LogRoot" value="c:\tmp\project"/>  
    <add key="LogLevel" value="debug"/>
  </appSettings>
```
For the rest in the appsettings nlog can get it without any problems, but for the log level,
seems rules -> logger can not load the appsettings, it is giving me
System.ArgumentException: 'Unknown log level: ${appsetting:LogLevel}'

- What is the expected result?
rules -> logger should get the appsetting.loglevel and write the log file

- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
No, I think the excption above is clear

- Please post full exception details (message, stacktrace, inner exceptions)
System.ArgumentException: 'Unknown log level: ${appsetting:LogLevel}'

- Are there any workarounds? yes/no
If I want to load the setting from appsetting.config file. No

- Is there a version in which it did work? 
No

- Can you help us by writing an unit test?

**Comment by 304NotModified** [comment]
Hi,

for performance reaons, you can't use layout renderers in level attributes

See https://github.com/NLog/NLog/wiki/Configuration-file#variables-for-level-attributes

> It's not possible to use layout-renderers in the level attributes (level, minlevel etc), but since NLog 4.6 you can use variables.

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, please let us know!

**Comment by snakefoot** [comment]
NLog 4.6.7 makes it possible to have semi dynamic routing rules with Layout-support:

https://github.com/nlog/NLog/wiki/Filtering-log-messages#semi-dynamic-routing-rules
