### ISSUE TITLE
Documentation on AppSettingLayoutRenderer2

### ISSUE THREAD

**Issue by ThomasArdal** [NLog/NLog#3451]
I found the recently added layout renderer `AppSettingLayoutRenderer2`. I'm wondering if I could use this in my NLog target as part of the configuration.

My target currently supports configuration like this:

```xml
<targets>
  <target
    name="elmahio"
    xsi:type="elmahio:elmah.io"
    apiKey="some-value-here"
    logId="some-other-value-here" />
</targets>
```

Using the appSetting layout renderer, I would like to be able to do something like this (for .NET Framework):

```xml
<appSettings>
  <add key="firstKey" value="some-value-here" />
  <add key="secondKey" value="some-other-value-here" />
</appSettings>
...
<targets>
  <target
    name="elmahio"
    xsi:type="elmahio:elmah.io"
    apiKey="${appsetting:item=firstKey}"
    logId="${appsetting:item=secondKey}" />
</targets>
```

I know that I will probably need to utilize the layout renderer in my property setters for `ApiKey` and `LogId`, but when doing this:

```csharp
var rend = new AppSettingLayoutRenderer2();
rend.Render(...);
```

the renderer expects a `LogEventInfo` object which I don't have at this point in time.

**Comment by 304NotModified** [comment]
I think you're looking for `LogEventInfo.CreateNullEvent()` ?

**Comment by ThomasArdal** [comment]
You are absolutely right. Thanks!
