### ISSUE TITLE
Is there support for AWS Cloudwatch logging?

### ISSUE THREAD

**Issue by Jhordan92** [NLog/NLog#3452]
After a while using the Cloudwatch integration on NLogs, I started to notice that it creates a delay in service comunication, and it also appeared this exception Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown awssdk.core
Can someone point me in the right direction about this subjects?

**Comment by 304NotModified** [comment]
I think you mean the "Amazon CloudWatch" package? (url: https://nlog-project.org/config/?tab=targets&search=aws)



1. click on the badge
    ![image](https://user-images.githubusercontent.com/5808377/59064692-30249600-88ab-11e9-90e2-e7b4fc06dcb6.png)

2. on Nuget go to source repository

    ![image](https://user-images.githubusercontent.com/5808377/59064752-50545500-88ab-11e9-9884-e0ec22021423.png)


3. The repo: https://github.com/aws/aws-logging-dotnet

It's an external package, so please try to get support there :)

**Comment by 304NotModified** [comment]
I think this is https://github.com/aws/aws-logging-dotnet/issues/56

**Comment by 304NotModified** [comment]
Have you tried the latest version of https://www.nuget.org/packages/AWS.Logger.NLog? I think you need 1.3.1+

**Comment by Jhordan92** [comment]
Hi, thanks for the quick reply.
![image](https://user-images.githubusercontent.com/38331222/59066147-f7b59580-8873-11e9-9968-9c5d6ae94caf.png)
Those are the packages used, of wich there's no recent released, although, there are updates on their dependencies

**Comment by 304NotModified** [comment]
that this repo: https://github.com/Onalytica/CloudWatchLogsTarget (found on https://www.nuget.org/packages/nlog.targets.cloudwatchlogs). Also external ;)

**Comment by 304NotModified** [comment]
I think you should move to  https://www.nuget.org/packages/AWS.Logger.NLog, but dunno of the configs / features are the same. AWS.Logger.NLog is more active and more popular.

**Comment by Jhordan92** [comment]
Well, thanks for the help. I'll go check out those options.

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, please let us know!
