### ISSUE TITLE
NLog XSD schema broken

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#3472]
Warning		Type 'http://www.nlog-project.org/schemas/NLog.xsd:Filter' is not declared, or is not a simple type.	

![image](https://user-images.githubusercontent.com/5808377/59306143-efa68d00-8c9b-11e9-9e4b-00b7763300c3.png)

Seems to be broken with NLog 4.6.4 (4.6.3 is OK)

broken with https://github.com/NLog/NLog.github.io/commit/febd452f7716025e589d02672ae3b9c75cf0ec0e

**Comment by 304NotModified** [comment]
https://github.com/NLog/NLog/pull/3409 or https://github.com/NLog/NLog/pull/3392

**Comment by 304NotModified** [comment]
This is not from the template (NLog/tools/MakeNLogXSD/TemplateXSD.xml)

**Comment by 304NotModified** [comment]
filter isn't an attribute, but not sure why it generated like that

**Comment by 304NotModified** [comment]
```xml
  <xs:attribute name="filter" type="Filter">
          <xs:annotation>
            <xs:documentation>Filter. Log events who evaluates to  will be discarded</xs:documentation>
          </xs:annotation>
        </xs:attribute>
```

needs to be removed, as we have already the child element: 
```
          <xs:element name="filter" minOccurs="0" maxOccurs="1" type="Filter" />
```

**Comment by 304NotModified** [comment]
found another issue -> https://github.com/NLog/NLog/issues/3473

**Comment by 304NotModified** [comment]
quick fixed online by https://github.com/NLog/NLog.github.io/commit/8bdcd926b4c37554a43584e2176528213a10eb83#diff-7a71422add18a6aa259cdf7abd0887d1

**Comment by 304NotModified** [comment]
tools/MakeNLogXSD/XsdFileGenerator.cs of dfd3845e8c5ea989e8a1a9d0106e68c569277ba7 could be the issue

**Comment by 304NotModified** [comment]
`[NLogConfigurationIgnorePropertyAttribute]` could be a solution, but not sure what side effects that has(used in ObjectGraphScanner

**Comment by snakefoot** [comment]
> tools/MakeNLogXSD/XsdFileGenerator.cs of dfd3845 could be the issue

Not super skilled with  MakeNLogXSD. But have maybe this will improve the output: #3474
