### ISSUE TITLE
XSD, validation of wrappers

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#3481]
XSD allows this, but it is nonsense?

```xml
<target xsi:type="FilteringWrapper" name="default" >
  <target xsi:type="Console"  />
  <target xsi:type="File"  />
</target>
```

related https://github.com/NLog/NLog/issues/3473

**Comment by 304NotModified** [comment]
If someone is good with XSD, help would be great!

**Comment by VHellin** [comment]
Hi, 
Can you describe the non-sense ? Do you want your wrapper to contain only 1 target ? Is this applicable only for the FilteringWrapper ? Or do you want this for all kinds of wrappers extending WrapperTargetBase ?

**Comment by snakefoot** [comment]
@VHellin Thanks for the heads up about the Wiki. Have now update it.

The `WrapperTargetBase` only supports a single wrapped-target. So it is non-sense to declare two targets.

**Comment by 304NotModified** [comment]
The specs of this issue are really not good, so gonna close this for now. I don't think this is easy to fix, as this should be valid with the XSD:


```xml
  <target xsi:type="FallbackGroup" name="String" returnToFirstOnSuccess="Boolean">
    <target xsi:type="wrappedTargetType" ... />
    <target xsi:type="wrappedTargetType" ... />
    ...
    <target xsi:type="wrappedTargetType" ... />
  </target>
```
