### ISSUE TITLE
NLog XSD still broken

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#3485]
> Type 'http://www.nlog-project.org/schemas/NLog.xsd:Layout' is not declared, or is not a simple type.

full XSD from 739b86233ca1d621332413d374a39479f10bbd40:

![image](https://user-images.githubusercontent.com/5808377/59471550-a7be6c00-8e3b-11e9-97cd-04daca7945ab.png)

[nlog 4.6.5-rc1.xsd.txt](https://github.com/NLog/NLog/files/3288331/nlog.4.6.5-rc1.xsd.txt)
[NLog 4.6.3.xsd.txt](https://github.com/NLog/NLog/files/3288332/NLog.4.6.3.xsd.txt)

**Comment by snakefoot** [comment]
Looks like it is there:
```
  <xs:complexType name="Layout">
    <xs:choice minOccurs="0" maxOccurs="unbounded" />
  </xs:complexType>
```
But the attribute should use `SimpleLayoutAttribute`

**Comment by 304NotModified** [comment]
Indeed, made a comparison between 4.6.5-rc and 4.6.3:

![image](https://user-images.githubusercontent.com/5808377/59471712-34692a00-8e3c-11e9-9679-4208b15d3768.png)

**Comment by snakefoot** [comment]
Found the bug:

```c#
        private static XElement GetAttributeElement(XElement propertyElement)
        {
            var result = new XElement(xsd + "attribute",
                new XAttribute("name", (string)propertyElement.Attribute("camelName")));

            var propertyType = (string)propertyElement.Attribute("type");
            if (propertyType == "Collection")
            {
                return null;
            }

            if (propertyType == "Enum")
            {
                string enumType = (string)propertyElement.Attribute("enumType");

                result.Add(new XAttribute("type", enumType));
            }
            else 
            {
                string xsdType = GetXsdType(propertyType, false);   // must be true
                if (xsdType == null)
                    return null;

                result.Add(new XAttribute("type", xsdType));
            }
```

**Comment by snakefoot** [comment]
Created #3486

**Comment by 304NotModified** [comment]
> Created #3486 (Sorry about this)

NP! Thanks for helping out!
