### ISSUE TITLE
Question: Pass message format arguments ad dictionary

### ISSUE THREAD

**Issue by petrnymsa** [NLog/NLog#3489]
I've tried but failed, so i hope i will get answer here. Probably i am lacking some knowledge about this. 

The log message can be structured, e.g 
```
Client {name} with id {id} connected
``` 
I can pass arguments to log method to fulfill name and id parameters.
```
Log("Client {name} with id {id} connected", "kevin", 1234)
```
This works, but i would like to pass dictionary<string, object> just like that
```
var args = new Dictionary<string,object> {
 {"id" , 1334},
 {"name", "kevin"},
};
Log("Client {name} with id {id} connected", args)
// output Client kevin with 1234 connected"
```

For now i have something like this, due to i need some additional properties.
```
var properties = PrepareProperties(message.SomeId, message.TrackingId, message.Data);

 logger.Log(level)
                .Message(message.Message, ??? What pass here ???)
                .Properties(properties)
                .Write();
```
Is this even possible?

**Comment by 304NotModified** [comment]
Currently this isn't supported. What you could do is destructing the dictionary (prefix with @, see https://github.com/NLog/NLog/wiki/How-to-use-structured-logging#formatting-of-the-message) , but that will give other results.

**Comment by snakefoot** [comment]
Not sure what interface you are looking, but you can do the following:

- Create extension method for NLog.Fluent.LogBuilder that takes a message and a Dictionary. Then just loop through the dictionary and access LogBuilder.LogEventInfo.Properties and add ditionary-values.

- Create an extension method for the NLog-Logger that takes a message and a Dictionary, Then just create a LogEventInfo-object, fill LogEventInfo.Properties and pass to the NLog-logger-object.

- Create wrapper around the NLog-Logger-object. Then you can implement all the special logic you want.

But maybe I'm misunderstanding what you want to do.

**Comment by petrnymsa** [comment]
> Currently this isn't supported.
> 
> You could pass the dictionary as argument and that will print all keys and values (see https://github.com/NLog/NLog/wiki/How-to-use-structured-logging#formatting-of-the-message) , but I think that isn't what you're looking for

Thank you for response. However this will not help. I just want to format message with arguments without needing to pass args by right order.

**Comment by petrnymsa** [comment]
I've just create helper method which will prepare message and then send it to nlog. Closing issue.

**Comment by 304NotModified** [comment]
Please share your helper for others, thanks :)

**Comment by petrnymsa** [comment]
@304NotModified  Sorry, of course. No magic here. For now, we know that message logs will not have many parameters -- just iterate over values and replace them. Not so nice, not so efficient but it just works. 

```C#
 foreach ((string key, var value) in data)
  {
          message = message.Replace($"{{{key}}}", value.ToString(), StringComparison.InvariantCultureIgnoreCase);
 }

return message;
```

**Comment by snakefoot** [comment]
If you want to keep the raw message-template and let NLog extract properties:

```c#
if (logger.IsEnabled(logLevel))
{
  var parameters = new object[dictionary.Count];
  var newLogEvent = LogEventInfo.Create(logLevel, logger.Name, exception, null, message, parameters);
  var messageTemplate = newLogEvent.MessageTemplateParameters;
  for (int i = 0; i < messageTemplate.Count; ++i)
  {
       var messageParameter = messageTemplate[i];
       if (dictionary.TryGetValue(messageParameter.Name, out parameterValue))
          parameters[i] = parameterValue;
  }
  newLogEvent.Parameters = parameters;  // Recapture property-values  
  logger.Log(newLogEvent);
}
```

There is no handling if the message-template contains parameter-placeholders that is not provided by the dictionary (will just log the raw message-template without any parameter values).
