### ISSUE TITLE
Performance measurements

### ISSUE THREAD

**Issue by imanushin** [NLog/NLog#3490]
Hi Team!

I wrote short article regarding NLog (and log4net) performance (with benchmark comparison, etc.).

What do you think, is it reasonable to add article link into the NLog documentation?

Target text: https://medium.com/@imanushin/net-logging-performance-comparison-20c83aa84333

**Comment by 304NotModified** [comment]
Hi!

Yes I think that's a good idea, bit more sure where exactly. 

PS: please be sure to use the lastest NLog version (can't find the versions for now in your article, on mobile), and please add them to the article :). Almost every NLog version has a performance improvement :smile:

PS 2.  Benchmark with Serilog would also be nice ;) 
This is done in the past although many benchmarks won't use equal configs between libraries (and so big unfair difference). If you have any questions about performance for your article, please let us know!

**Comment by snakefoot** [comment]
> @imanushin Cases with `KeepFileOpen=true` mean that for each logging event NLog opens file (e.g. creates file system handle), then it writes data to disk

Sounds like you mean  `KeepFileOpen=false`

**Comment by snakefoot** [comment]
> @imanushin As you can see, wrapper configuration allows logger to keep a lot of logging lines in the memory. 

Instead of configuring `BatchSize = 4096` and `FullBatchSizeWriteLimit = 128`, then I guess you are looking for for `queueLimit=10000`.

`BatchSize = 4096` means it will write in batches for 4096 LogEvents at a time. Writing in very large batches actually hurts performances. On my SSD then the "sweet spot" is BatchSize=500 for file-target. (Default is 200 which work well for Nlog-targets that uses network)

`FullBatchSizeWriteLimit = 128` means it will perform a single "throttle" (Default 1 ms) after having written 128 full batches of `BatchSize = 4096` (Default is 5 which work well for NLog-targets that uses network).

**Comment by snakefoot** [comment]
> @imanushin Logger construction Results.

The test-case for `CreateNLogTypeOfLogger` does not compare to `CreateLog4NetLogger`
- `CreateNLogTypeOfLogger` - Captures current callstack and extracts LoggerName and then create a logger of the type provided. If the type provided does not inherit from NLog Logger-object then it logs error and fallback to creating a standard NLog Logger.
- `CreateLog4NetLogger` - FullName is extracted from Type provided, and then create a logger with that name.

The valid NLog test should be this:

```c#
[Benchmark]
public object CreateNLogTypeOfLogger()
{
    return new[]
    {
        NLog.LogManager.GetLogger(typeof(BaseTest).FullName), // x16 times
    };
} 
```
And why the extra creation of array ? (Think `return new[]` should be removed from both benchmark tests).

**Comment by snakefoot** [comment]
@imanushin Regarding benchmarks then there is huge difference between:
- net472 - 32 bit
- net472 - 64 bit
- netcore22

There is also a huge difference between using GcServer or not. See my own tests [here](https://github.com/percentor/LoggingPerformance/issues/1#issuecomment-476013097)

**Comment by snakefoot** [comment]
> @imanushin ConcurrentWrites option orders system to gain and release Mutex, 

NLog with net472 running on Windows will actually perform "atomic" writes without using Mutex. Instead it will use `FileSystemRights.AppendData | FileSystemRights.Synchronize`. It provides atomic file-writes across processes. It is similar to log4net `log4net.Appender.FileAppender+MinimalLock`

**Comment by imanushin** [comment]
@snakefoot , @304NotModified ,

Thank you for feedback! I fixed typo with ```KeepFileOpen=true```.

I used NLog version 2.6.3 (please see [project here](https://github.com/imanushin/nlog-log4net-performance-comparison/blob/master/Performance.Comparison/Comparison.Runner/Comparison.Runner.csproj#L14)). I added them to article.

Regarding to ```Create*Logger``` - unfortunately, these tests are not fully correct (as I noticed in article, will highlight this again a bit later). The main reason: I could not do honest black-box checking of this method, because looks like both libraries store something in the internal dictionaries. So many calls are followed with Out Of Memory error. I just tried to show, that difference between new logger creation and single line writing is not dramatic. Also x16 times and array creation were added just to have ability to run all benchmark from the single suite.

I agree with queue limit and batch sizes, I'll re-run tests with that parameters.

I used Win x64, because it is faster version of executable, which can have both libraries in the single memory. This is honest (from my point of view), because the same application operates with the both libraries. I think I'll prepare NLog vs SeriLog comparison with also .Net Core/.Net Framework differences.

And I'll fix article part, which describes Mutex operations.

**Comment by snakefoot** [comment]
> I used NLog version 2.6.3

I guess you mean NLog version 4.6.3 :)

**Comment by imanushin** [comment]
@snakefoot , yes, you are right.

**Comment by imanushin** [comment]
Added page: https://github.com/NLog/NLog/wiki/External-articles
And added page mention in the end of the FAQ: https://github.com/NLog/NLog/wiki/faq

Could you please review there (and please rollback if I'm doing wrong)?

**Comment by snakefoot** [comment]
Please use this page, instead of creating new:


https://github.com/nlog/NLog/wiki/Web-resources


Thanks


Sent from my Sony Xperia


---- Igor Manushin wrote ----


Added page: https://github.com/NLog/NLog/wiki/External-articles
And added page mention in the end of the FAQ: https://github.com/NLog/NLog/wiki/faq

Could you please review there (and please rollback if I'm doing wrong)?

**Comment by imanushin** [comment]
@snakefoot, done: I removed the new page, rolled back FAQ and updated the [Web-resources](https://github.com/nlog/NLog/wiki/Web-resources).

**Comment by 304NotModified** [comment]
OK thanks, I assume this could be closed now :)

**Comment by snakefoot** [comment]
@imanushin Could still be nice if you could fix this part of the article code:

```c#
[Benchmark]
public object CreateLog4NetLogger()
{
    return new []
    {
        LogManager.GetLogger(typeof(BaseTest)), // x16 times
    };
}

[Benchmark]
public object CreateNLogTypeOfLogger()
{
    return new[]
    {
        NLog.LogManager.GetCurrentClassLogger(typeof(BaseTest)), // x16 times
    };
}

[Benchmark]
public object CreateNLogDynamicLogger()
{
    return new[]
    {
        NLog.LogManager.GetCurrentClassLogger(), // x16 times
    };
}
```

Removing the `return new[]`, then you could get rid of the problem with:

> I failed to create reproducible benchmark which does not lead to an “Out Of Memory” issue

**Comment by imanushin** [comment]
@snakefoot , yes, will remove and return to the thread.
