### ISSUE TITLE
LoggingConfiguration.AddRule with name for DeleteRule

### ISSUE THREAD

**Issue by Freddyvdh** [NLog/NLog#3491]
Hi,

I just switch NLog from 4.4 to 4.6 and want to implement a console and file logger, which log levels can be changed during runtime. I'm using the programmactily approach and I'm wondering how to add a rule to the LoggingConfiguration with a name, to be able to remove the rule by LoggingConfiguration.RemoveRuleByName().

With LoggingConfiguration.AddRule() doesn't have a parameter for the name. 
I tried to create a new LoggingRule to set a name, but then I can't set the levels and target and a LoggingRule can not be given as paramter in AddRule.

How can I modify or remove a rule?

**Comment by 304NotModified** [comment]
You need for this LoggingConfiguration.Rules. The addrule() is a simple helper with limited options.

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, please let us know!
