### ISSUE TITLE
can NLog config target filename unique?

### ISSUE THREAD

**Issue by Yang09701194** [NLog/NLog#3496]
Is there way to log with unique file name by setting in `NLog.config` (not using code to config)?

For an exagerrated example, if there are 100000 same `exe process` with same NLog.config execute at the same time, how to make each `exe process` log with its unique log file? 

Is it can be Logged as `{Random Unique Guid}`.log or something else?

**NLog version**: 4.0
**Platform**:  .Net 4.5 
**Current NLog config** 
```xml
<nlog>
  <targets>
    <target name="Info" xsi:type="File" fileName="D:\Log\${How to Unique?}.log"  encoding="utf-8"  />
</nlog>
```

**Comment by 304NotModified** [comment]
Hi,

You could use ${guid} in the file name.  See https://github.com/NLog/NLog/wiki/Guid-Layout-Renderer

**Comment by Yang09701194** [comment]
@304NotModified  Thank you, I test `${Guid}` works, and option list page is great.

for me this issue is solved and I don't mind it to be closed! :thumbsup:

**Comment by Yang09701194** [comment]
@304NotModified  Thank you, I test `${guid}` works, and the option list is great!
