### ISSUE TITLE
How to long a big CSV string?

### ISSUE THREAD

**Issue by otherdave** [NLog/NLog#3503]
Hi!

My application currently writes some debugging data to a .csv file manually. It's a header and then a row of data every N seconds. I'd like to move this to NLog and not do it myself.

However, I'm not sure how to create this in the NLog ecosystem.

My current file may look like this:

Header: Time, Sensor1, Sensor2, Sensor3
Row1: <timestamp>,100, 200, 300
Row2: <timestamp>, 105, 190, 333

and so on. In case it matters, there are currently 51 columns. I believe things like the CSV layout are a good start because I could configure it to log something like "<timestamp>,<message>" but what I really need is some way to define the <message> and the columns so that I get a header that includes Sensor1, Sensor2 and Sensor3. Can this be done with existing options & Layouts/formatters? Or do I need to write custom implementations for some things?

Apologies if this is the wrong place to ask this question! I couldn't find a more suitable way to get this question to the team.

**Comment by 304NotModified** [comment]
Hi!

Please check this example: https://github.com/NLog/NLog/wiki/CsvLayout#example

**Comment by otherdave** [comment]
Hey, @304NotModified , thanks for the reply!

I saw that example but I wasn't sure if it was the best for my use case. Would I need to do something like:

```csharp
mLogger.Info("{sensor1},{sensor2},{sensor3}");
```

And then have the layout set up like this:

```xml
<target xsi:type="File" fileName="${csvPath}">
    <layout xsi:type="CsvLayout" delimiter="Tab" withHeader="false">
        <column name="time" layout="${longdate}" />
         <column name="message" layout="${message}" />
    </layout>
</target>
```

Is that all there is to it? If so, how do I get the headers for my message (for example "Time, Sensor 1, Sensor 2, Sensor 3") into the file? Hardcode the header in the XML somehow?

**Comment by 304NotModified** [comment]
I think you're looking for:

```
 <layout xsi:type="CsvLayout" delimiter="Comma" withHeader="true">
    <column name="time" layout="${longdate}" quoting="None" />
    <column name="Sensor 1" layout="${event-properties:sensor1}"/>
    <column name="Sensor 2" layout="${event-properties:sensor2}"/>
    <column name="Sensor 3" layout="${event-properties:sensor3}"/>
</layout>
```

The name of the `<column>` is the header name

with this logger call:
```c#
logger.Info("{sensor1},{sensor2},{sensor3}", sensorValue1, sensorValue2, sensorValue3);
```

**Comment by otherdave** [comment]
Oh man, that's perfect, thanks! I'm sorry I didn't make the connection between the CSV layout and the Structured Logging support. Thanks!
