### ISSUE TITLE
XmlLoggingConfiguration should have a constructor from stream

### ISSUE THREAD

**Issue by dmitrynovik** [NLog/NLog#3504]
Every constructor of `XmlLoggingConfiguration` requires passing a path to a file on disk. In other words, it only supports initialization from file.

However, the configuration might be obtained from other sources (e.g. central document database, or any other data store). 

The easiest way to abstract from files and to support any configuration source would be having a constructor `XmlLoggingConfiguration( Stream stream)` OR `XmlLoggingConfiguration( XmlReader r )`

**Comment by snakefoot** [comment]
@304NotModified Resolved with #3514 and included in milestone 4.6.6 ?

**Comment by 304NotModified** [comment]
yes indeed, thanks!

4.6.6 is now live! https://www.nuget.org/packages/NLog
