### ISSUE TITLE
aspnet-request-form:Exclude unable to get exclude values stored in variable

### ISSUE THREAD

**Issue by pratishthap** [NLog/NLog#3509]
I am trying to use aspnet-request-form and want to exclude certain form properties. Since the exclude properties are common in other targets I decided to use variable which will have the value of excluded form properties .But it doesn't work.
Without variable substitution the Exclude does work.
I Have something like this 
```xml
<column name="aspnetrequestform" layout="${aspnet-request-form:OutputFormat=JSON:${exclude1}}"/>
``` 
and 

```xml
 <variable name="exclude1" value="${Exclude=Password}"/>

```

**Comment by 304NotModified** [comment]
Hi,

You can't use the `exclude` key in a variable. This will work:

```xml
<column name="aspnetrequestform" layout="${aspnet-request-form:OutputFormat=JSON:exclude=${exclude1}}"/>
``` 
and 

```xml
 <variable name="exclude1" value="Password"/>
```

nb: ${var:exclude1} won't work as the exclude property isn't layoutable

**Comment by pratishthap** [comment]
<column name="aspnetrequestform" layout="${aspnet-request-form:OutputFormat=JSON:exclude=${exclude1}}"/>
and
<variable name="exclude1" value="Input.Password"/>

But the log does not exclude Input.Password. It only works when I use
 <column name="aspnetrequestform" layout="${aspnet-request-form:OutputFormat=JSON:Exclude=Input.Password}"/>

**Comment by 304NotModified** [comment]
please use backticks. (```` ```` ````) See the message I edited

**Comment by pratishthap** [comment]
Unable to see your edited post..Can you post it again..Thanks

**Comment by pratishthap** [comment]
WHere do I use backticks?

**Comment by pratishthap** [comment]
OK..i edited my post to include backticks.Can you have a look at it?

**Comment by 304NotModified** [comment]
https://github.com/NLog/NLog/issues/3509#issuecomment-510175459 -> this should work.

Could you please check the ordering? Is `<variable>` before the ` <column `? Otherwise, please post the full (striped) config

**Comment by 304NotModified** [comment]
Please also check the [internal log](https://github.com/NLog/NLog/wiki/Internal-logging)

**Comment by pratishthap** [comment]
```xml

 <targets>
    
     <variable name="exclude1" value="Input.Password,__RequestVerificationToken"/>

    <target xsi:type="File" name="RequestResponseAuditingMiddlewareLogger" fileName="r.development.txt"  archiveFileName="abc.txt"
     archiveEvery="Tuesday" enableArchiveFileCompression="true">
      <layout xsi:type="CsvLayout"  delimiter="Comma" withHeader="true">
        <column name="time" layout="${longdate}" />
        <column name="level" layout="${level:upperCase=true}"/>
        <column name="logger" layout="${logger}" />
        <column name="message" layout="${message}" />
        <!--<column name="callsite" layout="${callsite:includeSourcePath=true}" />
        <column name="stacktrace" layout="${stacktrace:topFrames=10}" />
        <column name="exception" layout="${exception:format=ToString}"/>
        <column name="property1" layout="${event-properties:property1}"/>-->
        <column name="aspnetrequestmethod" layout="${aspnet-request-method}"/>
        <column name="aspnetrequestip" layout="${aspnet-request-ip}"/>
        <column name="aspnetrequestform" layout="${aspnet-request-form:OutputFormat=JSON:Exclude=${exclude1}}"/>
        <column name="aspnetrequestpostedbody" layout="${aspnet-request-posted-body}"/>
        <column name="aspnetwebrootpath" layout="${aspnet-webrootpath}"/>
        <column name="iissitename" layout="${iis-site-name}"/>
      </layout>
    </target>

<targets/>

```

**Comment by pratishthap** [comment]
under internal log I see:
2019-07-10 15:34:00.6561 Debug Setting 'CsvColumn.name' to 'aspnetrequestform'
2019-07-10 15:34:00.6561 Debug Setting 'CsvColumn.layout' to '${aspnet-request-form:OutputFormat=JSON:Exclude=${exclude1}}'

so {exclude1} is not getting replaced with the actual values

**Comment by 304NotModified** [comment]
That's very strange. I have to check that. 

We are doing a simple replace when reading the config, see https://github.com/NLog/NLog/blob/3ea14315c563ee6ca06d9516166077a344e848f6/src/NLog/Config/LoggingConfiguration.cs#L821-L853

**Comment by pratishthap** [comment]
I found the issue..Its not working with "NLog" Version="4.6.4" and "NLog.Web.AspNetCore" Version="4.8.2" .
As soon as i upgraded versions to "NLog" Version="4.6.5" and "NLog.Web.AspNetCore" Version="4.8.4",
it worked.

**Comment by 304NotModified** [comment]
I'm glad is has been resolved 👍
