### ISSUE TITLE
Circular Logging

### ISSUE THREAD

**Issue by Alby1987** [NLog/NLog#3525]
Nlog doesn't have an option for circular logging after [max number of rows]/[max file size] is reached.

For example, if I have set 3 maximum rows, I should have

1. Log 1
2. Log 2

Call (.log("Log 3")

1. Log 1
2. Log 2
3. Log 3

Call (.log("Log 4")

1. Log 2
2. Log 3
3. Log 4

Call (.log("Log 5")

1. Log 3
2. Log 4
3. Log 5

I hope this is a feature that can be useful for other people, and not too complex to develop.

**Comment by 304NotModified** [comment]
Hi!

You mean logging to file for this?

Unfortunately  removing content from a file is slow and difficult with threads. 

What you could do instead:

- Use rolling files or,
- create partitioned files, e.g one per day.

**Comment by Alby1987** [comment]
> Hi!
> 
> You mean logging to file for this?
> 
> Unfortunately removing content from a file is slow and difficult with threads.
> 
> What you could do instead:
> 
> * Use rolling files or,
> * create partitioned files, e.g one per day.

Hi there!

I tried to use the archive option to make maximum one file and use the archive on maximum size. Alas, this is not our client wants, but honestly I didn't think removing lines would be such a concern cause of the multithread model. Thanks for your reply!

**Comment by snakefoot** [comment]
Lets say we have this state, and want to create new file:

    Log 1
    Log 2
    Log 3

Then I guess one could do this:

1. Delete Log 3
2. Rename Log 2 -> Log 3
3. Rename Log 1 -> Log 2
3. Create Log 1

Which sounds very much like rolling-files:

https://github.com/nlog/NLog/wiki/FileTarget-Archive-Examples#archive-numbering-examples

Source code here:

https://github.com/NLog/NLog/blob/eb8e93cac3ca36093f2de1f6ba4e57b05053ba51/src/NLog/Targets/FileArchiveModes/FileArchiveModeRolling.cs#L124-L140

**Comment by snakefoot** [comment]
Closing as inactive
