### ISSUE TITLE
Throwing error after upgrading Nlog.Extended from 2.0 to 4.6 

### ISSUE THREAD

**Issue by avinash84r** [NLog/NLog#3529]
My MVC 5 application running on .net framework 4.6 and previously it has Nlog.Extended 2.0. 
and it was running smoothly. Now, I want to update the Nlog.extended version with the latest version 4.6.6. While upgrading it upto 3.2.1  it is working fine, but when I upgrade it to 4 and above version, it is throwing runtime error "Could not load type 'NLog.Web.NLogHttpModule' from assembly 'NLog.Extended'. ". Please fellow attached error screen shot.
Please help me to fixed this error.
 
![error1](https://user-images.githubusercontent.com/42776267/61943149-7c8d7780-afb8-11e9-8c23-3ffb0c36fc03.PNG)

**Comment by snakefoot** [comment]
NLogHttpModule now lives In NLog.Web<http://NLog.Web>. You should recompile your code to get the type from NLog.Web.dll<http://NLog.Web.dll>


NLog.Extended<http://NLog.Extended> is no longer needed with NLog 4.6.6<tel:4.6.6> unless using Msmq-target.


Sent from my Sony Xperia


---- welcome[bot] wrote ----


Hi! Thanks for opening your first issue here! Please make sure to follow the issue template - so we could help you better!

**Comment by avinash84r** [comment]
Thanks It working now..
