### ISSUE TITLE
Layout Renderer in V4.6.6

### ISSUE THREAD

**Issue by Rajkumar28269** [NLog/NLog#3535]
I need some references to know more about layout rendering. Can anyone suggest where can I start?

**Comment by 304NotModified** [comment]
Using the default renderers or write a custom one?

**Comment by Rajkumar28269** [comment]
Writing custom

**Comment by 304NotModified** [comment]
See here :)

https://github.com/NLog/NLog/wiki/Extending-NLog

And especially

https://github.com/NLog/NLog/wiki/How-to-write-a-custom-layout-renderer

**Comment by Rajkumar28269** [comment]
Can you give some full examples how these are implemented.

**Comment by 304NotModified** [comment]
https://github.com/NLog/NLog/wiki/How-to-write-a-custom-layout-renderer has full examples? What are you missing?

**Comment by 304NotModified** [comment]
Maybe looking for this?

https://github.com/NLog/NLog/wiki/LogEvent-Context-Information#logevent-properties

In the layout renderer you will have the LogEventInfo

**Comment by Rajkumar28269** [comment]
Thank you. Now I got it.
