### ISSUE TITLE
Nlog does not create Root element in xml file document while writting logs for different log level in same file

### ISSUE THREAD

**Issue by BinayKushwaha** [NLog/NLog#3537]
Nlog writes log successfully for different log levels, but is does not create Root element in same file for different log levels. Due to this Invalid Xml Format issues is encountered. I think i have missed something in Nlog.Config or somewhere. Please help me with this.

This is the output which i am getting for different log levels without Root Element:

    <logevent time="2019-08-07 10:44:08.7467" level="DEBUG"> 
         <Message>System.Exception: test debug</Message><Exception>test 
          debug</Exception>
     </logevent>
    <logevent time="2019-08-07 10:44:08.8426" level="WARN"> 
           <Message>Serious 
            error</Message><Exception>Object reference not set to an instance 
            of an object.</Exception>
         </logevent>
   
    Nlog.Config

       <target name="xmlFile" xsi:type="File" 
              fileName="${basedir}\log\Xmartlog.${shortdate}.xml" 
              archiveFileName="${basedir}\log\log.${shortdate}.xml"
              maxArchiveFiles="4"
              archiveAboveSize="10240"
             archiveEvery="Day"
             encoding="utf-8"  >
         <layout xsi:type="XmlLayout" includeAllProperties="false">
             <attribute  name="time" layout="${longdate}" />
             <attribute name="level" layout="${level:upperCase=true}"/>
           <element name="Message" 
             value="${message:exceptionSeparator=String}"/>
          <element name="Exception" value="${exception:format=message}" />
        </layout>
      </target> 

    Expected output:
      There should be output like this:
      <Log>
       ----logs should be here----
     </Log>

**Comment by BinayKushwaha** [comment]
thanks for your kind response. i am able to write log successfully but it is not able create log in XML format:
Result:
<logevent>--logs-- </logeevnt>

  Expected Output:
   <RootElement>
     <logevent>--logs-- </logeevnt>
     <logevent>--logs-- </logeevnt>
  </RootElement>

**Comment by 304NotModified** [comment]
Hi,

This is maybe not clear documented, but this is correct. 

When writing to a file, it will be appended. If we constantly have to remove the end-root-element (or insert content instead if append) , that would be difficult with performance and multithreading. 

I would recommend to add the root element as first step before processing the file.

**Comment by BinayKushwaha** [comment]
solved issue by adding header and footer attributes in target tag
  <target name="xmlFile" xsi:type="File" fileName="${basedir}\log\Xmartlog.${shortdate}.xml" archiveFileName="${basedir}\log\log.${shortdate}.xml" keepFileOpen="false" archiveAboveSize="1240" archiveNumbering="Sequence" header="&lt;?xml-stylesheet type='text/xsl' href='XmartLogViewer.xsl'?&gt; &lt;nlog&gt;" footer="&lt;/nlog&gt;" concurrentWrites="true" createDirs="true" autoFlush="true" encoding="utf-8"  >

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, please let us know!

**Comment by snakefoot** [comment]
Rewrite of Footer-Layout (xml-root-tag) on file-append discussed here: https://github.com/NLog/NLog/issues/1658#issuecomment-604589881

**Comment by snakefoot** [comment]
One could use NLog Header/Footer-feature on the NLog FileTarget:
```xml
header="&lt;nlog&gt;" footer="&lt;/nlog&gt;"
```

See also: https://github.com/solo-developer/NLog.TagEnder (Adding root-element for the log-file, before opening it)
