### ISSUE TITLE
NLog in Azure Function - not working when resolved with DI 

### ISSUE THREAD

**Issue by andronachev** [NLog/NLog#3538]
Hi,

I've been struggling for a while now, to use NLog in an Azure function. I got to the point where: 

1. I have a Startup class in my function where I configure and register NLog to the ServiceCollection, through the loggingBuilder , using an ElasticSearch target

2. The ILogger instance that is passed to the RUN method of the function works (i.e. I see my logs in Elastic Search)

3. Further in my function I resolve a custom application service using the IServiceProvider , in the application service I have an ILogger<T> as a dependency. This is also resolved fine, and among the _loggers property I can see an instance of NLogger. But when calling the logger.LogError method, nothing happens, no exception, and I don't see anything in ElasticSearch 

My Startup.cs: 

```
public class Startup : FunctionsStartup
    {
        public Startup()
        {
            // LogManager.Configuration = new XmlLoggingConfiguration("NLog.config");
            // NLogBuilder.ConfigureNLog(LogManager.Configuration);
            LoggingConfiguration config = new LoggingConfiguration();
            LogManager.ThrowExceptions = true;
            var elasticTarget = new ElasticSearchTarget()
            {
                Uri = "----the url -----",
                IncludeAllProperties = true,
                Fields = new List<Field>()
                {
                    new Field()
                    {
                        Name = "host",
                        Layout = "${aspnet-request-host}"
                    },
                    new Field()
                    {
                        Name = "machine",
                        Layout = "${machinename}"
                    },
                    new Field()
                    {
                        Name = "activityid",
                        Layout = "${aspnet-TraceIdentifier}"
                    }
                }
            };

            var bufferedElasticTarget = new BufferingTargetWrapper("ElasticSearch", elasticTarget)
            {
                FlushTimeout = 10000
            };

            config.AddTarget(bufferedElasticTarget);

            var nlogElasitcSearchRule = new LoggingRule("*", NLog.LogLevel.Debug, elasticTarget);
            config.LoggingRules.Add(nlogElasitcSearchRule);

            NLogBuilder.ConfigureNLog(config);
            LogManager.Configuration = config;
        }

        public override void Configure(IFunctionsHostBuilder builder)
        {
            try
            {
                var config = builder.Services.BuildServiceProvider().GetRequiredService(typeof(IConfiguration)) as IConfiguration;
                var originationConfiguration = new OriginationConfiguration();
                config.GetSection("OriginationConfigs").Bind(originationConfiguration);
                builder.Services.AddOriginationServices(originationConfiguration);

                builder.Services.AddLogging((loggingBuilder) => { loggingBuilder.AddNLog(); });
            }
            catch (Exception ex)
            {
                var abc = ex;
            }
        }
    }
```

My function: 

```
 [FunctionName(nameof(PingHttpTrigger))]
        public IActionResult PingHttpTrigger(
            [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "ping")] HttpRequest req, ILogger log)
        {
            try
            {
                throw new Exception("cocomarla_exceptie");
            }
            catch (Exception ex)
            {
                // this logging works, no problem
                log.LogError(ex, "error test");
            }

            CustomerRegisteredEvent customerRegistered = new CustomerRegisteredEvent()
            {
                AggregateId = Guid.NewGuid(),
                EventId = Guid.NewGuid(),
                Customer = new Context.Entities.Customer()
            };

            var customerEventHandler = _serviceProvider.GetRequiredService<IEventHandler<CustomerRegisteredEvent>>() as IEventHandler<CustomerRegisteredEvent>;

            customerEventHandler.Handle(customerRegistered);

            return new OkObjectResult(new { timestamp = DateTime.UtcNow });
        }
```

And the CustomerEventHandler class: 

```
 public class CustomerEventHandler : IEventHandler<CustomerRegisteredEvent>,
                                        IEventHandler<CustomerUpdatedEvent>
    {
        private ICustomerService customerService;
        private ILogger<CustomerEventHandler> logger;

        public CustomerEventHandler(ICustomerService customerService, ILogger<CustomerEventHandler> logger)
        {
            this.customerService = customerService;
            this.logger = logger;
        }

        public void Handle(CustomerRegisteredEvent @event)
        {
            try
            {
                throw new Exception("cocomarla_exceptie");
            }
            catch (Exception ex)
            {
                // this doesn't work, no log anywhere
                logger.LogError(ex, "error test");
            }

            // customerService.CreateCustomerProjection(@event.Customer);
        }

        public void Handle(CustomerUpdatedEvent @event)
        {
            customerService.UpdateCustomerProjection(@event.Customer);
        }
    }
```

I think there must be a conflict somewhere, because the Azure Function's pipeline must be slightly different than the ASP.NET pipeline, so probably something doesn't add up in the ServiceCollection... not sure. 

Thoughts ? Any help would be greatly appreciated. 

Thanks,
Vlad

**Comment by andronachev** [comment]
Update: after enabling the internal logging, I saw that NLog was missing the serviceProvider (the internal log stated: " Debug Missing serviceProvider, so no HttpContext" . 

I did a couple of searches on this and it seems that the serviceProvider was not properly registered with NLog. 

In an ASP.NET Core web app, this is fixed by registering NLog using the UseNLog() method on the IWebHostBuilder, but this is not available in Azure Functions, so I am using  loggingBuilder.AddNLog();

Turns out, you can pass the following Options object to AddNLog: 


```
new NLogAspNetCoreOptions
                                            {
                                                RegisterHttpContextAccessor = true,
                                                IgnoreEmptyEventId = true,
                                                IncludeScopes = true
                                            }
```

And then the issue is fixed. 

I'm thinking to leave this issue open, for some feedback from the authors... otherwise it can be closed. 

Thanks

**Comment by snakefoot** [comment]
@andronachev I'm curious about `BufferingTargetWrapper` with `FlushTimeout = 10000`.

Thought that Azure Functions had "sudden shutdown" so if there was no flush included, then it would just stop and anything in-memory and not sent would be discarded.

But maybe the Logging-Providers are shutdown nicely? (NLog Logging Provider flushes on shutdown)

**Comment by andronachev** [comment]
this fix that i've mentioned above suddenly stopped working, a few days ago, I have no idea why ... and the InternalLogger of nLog does not write anything to the console anymore (set InternalLogger.LogToConsole = true... and nothing. Debugging now..

**Comment by snakefoot** [comment]
@andronachev No logging at all. Or just no output generated by `${aspnet-request-host}` (and friends) ?

**Comment by andronachev** [comment]
@snakefoot  logging only works in the PingHttpTrigger (using the ILogger injected by the framework), but when I have an ILogger < T > injected by me, that one doesn't work at all, although while debugging I see the nlog logger in the list of loggers, with the correct configuration. 

Also, last time I had this issue, the InternalLogger was writting errors in the console (" Debug Missing serviceProvider, so no HttpContext") , that's why I've added the NLogAspNetCoreOptions to the AddNLog method. Now, even if I remove the options, the internal logger does not write any errors

**Comment by snakefoot** [comment]
And you have the magic code to register `FunctionsStartup`:

`[assembly: FunctionsStartup(typeof(MyNamespace.Startup))]`

See also: https://docs.microsoft.com/bs-latn-ba/azure/azure-functions/functions-dotnet-dependency-injection

**Comment by snakefoot** [comment]
NLog lives under the shadow of Microsoft Extension Logging, that performs filtering on the LogLevels configured in `host.json`:

Maybe try this:
```json
{
  "version": "2.0",
  "logging": {
    "logLevel": {
      "MyCompany.SolutionName": "Information"
    }
  }
}
```

**Comment by andronachev** [comment]
@snakefoot   yes, I have had the [assembly:] before. But your latest comment works, adding the logging node to the host.json file fixed the logging... but I din't understand why, it wasn't there before, either (last week when I commented that my logging works, I didn't have the logging node in host.json.

**Comment by snakefoot** [comment]
Instead of using `host.json` then you could also do this:


```c#
public override void Configure(IFunctionsHostBuilder builder)
{
    builder.Services.AddLogging(loggingBuilder =>
    {
        loggingBuilder.ClearProviders();
        loggingBuilder.SetMinimumLevel(LogLevel.Trace);
        loggingBuilder.AddNLog();
    });
}
```

**Comment by snakefoot** [comment]
>  @andronachev adding the logging node to the host.json file fixed the logging... but I don't understand why,

Cannot answer your question. Never created an Azure function. Just reading the manual

**Comment by snakefoot** [comment]
@andronachev Curious about you being able to provide `NLogAspNetCoreOptions` to AddNLog.

Can you copy-paste the code you have implemented to provide `NLogAspNetCoreOptions` ?

**Comment by andronachev** [comment]
@snakefoot  NLogAspNetCoreOptions is in the NLog.Web.AspNetCore, Version=4.0.0.0 nuget package

**Comment by snakefoot** [comment]
> @andronachev NLogAspNetCoreOptions is in the NLog.Web.AspNetCor

Yes, but curious how you are able to register it correctly, so `${aspnet-traceidentifier}` works. 

So can you copy-paste the code you have implemented to make it work. Since the registration of ServiceLocator (required for `${aspnet-}`) needs some special magic, that I don't see in your original post. And the special magic will not happen if just using AddNLog with NLogAspNetCoreOptions

**Comment by andronachev** [comment]
> > @andronachev NLogAspNetCoreOptions is in the NLog.Web.AspNetCor
> 
> Yes, but curious how you are able to register it correctly, so `${aspnet-traceidentifier}` works.
> 
> So can you copy-paste the code you have implemented to make it work? Since the registration of ServiceLocator (required for `${aspnet-}`) needs some special magic, that I don't see in your original post. And the special magic will not happen if just using AddNLog with NLogAspNetCoreOptions

That's all the code that I have, in the original post plus I added the logging node in the host.jsom file. I don't understand what other "special magic" you are referring to :)

**Comment by snakefoot** [comment]
Something like this:

```c#
builder.Services.AddLogging((loggingBuilder) => { loggingBuilder.AddNLog(); });
builder.Services.Build().SetupNLogServiceLocator();
```

But my mind cannot phantom how this will work in Azure Function. Looks like request-body (and other details) are received like this inside the Azure Functions:

```c#
var requestHost = req.Host;
var requestParameters = req.GetQueryParameterDictionary();
string requestBody = await new StreamReader(req.Body).ReadToEndAsync();
```

Things correlationid/traceidentifier/activityid logic must be implemented manually, as this currently not provided out-of-the-box.

**Comment by 304NotModified** [comment]
Has your question being answered?

**Comment by andronachev** [comment]
@304NotModified  I got it working by adding the logging node in the hosts.json config, allthough it's not yet clear to me why that works, it's probably related to the logging in .net core and not the nlog provider. The issue can be closed from my point of view

**Comment by 304NotModified** [comment]
OK thanks!
