### ISSUE TITLE
Need to have fileName and archiveFileName as date

### ISSUE THREAD

**Issue by rbouny** [NLog/NLog#354]
When there is date in filename, on next date, a new file is created.
But the archive is not created. And the max archive file is not respected.

there is an example at Minute scale.

<target xsi:type="File" name="file" fileName="Logs/${date:format=yyyy-MM-dd-HH}.txt" 
            layout="${longdate} ${message}"
            archiveEvery="Minute"
            archiveFileName="Logs/Archives/log.{#}.txt"
            archiveNumbering="Date"
            archiveDateFormat="yyyy-MM-dd-HH-mm"
            maxArchiveFiles="2"
            keepFileOpen="false"
            encoding="iso-8859-2"/>

The bug is also present with
 archiveNumbering="Rolling"

**Comment by askdong** [comment]
I also need this feature: Need to have fileName and archiveFileName as date

**Comment by snakefoot** [comment]
@askdong Please create new issue, instead of piggy-backing on this one. NLog 4.5 supports maxArchiveFiles. And NLog 4.7 supports maxArchiveDays.

See also https://github.com/NLog/NLog/issues/3807#issuecomment-587661413
