### ISSUE TITLE
Custom target with async attribute get incorrect timestamp and order of logs

### ISSUE THREAD

**Issue by Kirya522** [NLog/NLog#3542]
**NLog version**: 4.6.5

**Platform**: WebApi 2.1 .net47 

**Current NLog config**

```xml
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <targets async="true">
      <target name="graylogt" xsi:type="GraylogHttp" facility="WebApi" graylogServer="http://graylog" graylogPort="12201">
        <parameter name="current_user" layout="${aspnet-user-identity}" />
        <parameter name="exception_type" layout="${exception:Type}" />
        <parameter name="request" layout="${aspnet-request-method} ${aspnet-request-url}" />
        <parameter name="site" layout="${iis-site-name} ${aspnet-appbasepath}" />
        <parameter name="request_body" layout="${onexception:${aspnet-request-posted-body}:when=level>=LogLevel.Error}" />
      </target>
    </targets>
    <rules>
     <logger name="*" minlevel="debug" writeTo="graylogt" />
    </rules>
  </nlog>

```
Hi, I use a https://github.com/dustinchilson/NLog.Targets.GraylogHttp for graylog.
In order to don't block the thread for logging I use an async attribute. But logs have incorrect timestamps and order(compare to sync mode). I can't use "sync" logs, because every log operation takes 0.2 sec.
- What is the current result? 

> Incorrect order and timestamp of logs

- What is the expected result? 

> Correct order and timestamps

**Comment by 304NotModified** [comment]
Hi, 

Could you please test this with a logfile (file target)? Is there the same issue?

**Comment by Kirya522** [comment]
I have tested file target before all the same, except in sync mode file is much faster than that target

**Comment by 304NotModified** [comment]
Please share your logger calls because wrong timestamp sounds unlikely

**Comment by snakefoot** [comment]
@Kirya522 I think `GraylogHttp` is not guaranteed to send http-requests in-order. It only promises to throttle when http-exceptions occurs.

Could you try using [NLog.GelfLayout ver. 0.4](https://www.nuget.org/packages/NLog.GelfLayout) and try this instead:

```xml
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <extensions>
    <add assembly="NLog.Web.AspNetCore" />
    <add assembly="NLog.Layouts.GelfLayout" />
  </extensions>
  <targets async="true">
      <target name="graylogt" xsi:type="network" address="http://graylog:12201">
        <layout xsi:type="GelfLayout" facility="WebApi">
          <field name="current_user" layout="${aspnet-user-identity}" />
          <field name="exception_type" layout="${exception:Type}" />
          <field name="request" layout="${aspnet-request-method} ${aspnet-request-url}" />
          <field name="site" layout="${iis-site-name} ${aspnet-appbasepath}" />
          <field name="request_body" layout="${onexception:${aspnet-request-posted-body}:when=level>=LogLevel.Error}" />
        </layout>
      </target>
    </targets>
    <rules>
     <logger name="*" minlevel="debug" writeTo="graylogt" />
    </rules>
  </nlog>
```

Instead of using `address="http://` then you could consider using `address="tcp://` together with `lineEnding="Null"`.

**Comment by 304NotModified** [comment]
> I think `GraylogHttp` is not guaranteed to send http-requests in-order

I think in-order is also not important, because every log item has a timestamp. And i'm pretty sure that timestamp is correct in NLog, so maybe not correct processed by the gelf target?

**Comment by snakefoot** [comment]
> I think in-order is also not important, because every log item has a timestamp

One can easily generate multiple logevents with the same timestamp, especially if not using [AccurateUTC](https://github.com/NLog/NLog/wiki/Time-Source) (And it is still possible even if doing so).

**Comment by 304NotModified** [comment]
Good one. We have also `${sequenceid}`, but that's then also a work around?

**Comment by Kirya522** [comment]
But this thing happens in file too, so target doesn't make sense. I am trying to get an example, it will be as soon as possible

**Comment by snakefoot** [comment]
If you can make an example of logevents being reordered when writing to file. Then I will be happy to look at it.


But maybe the issue is the locations you are doing logging in the ASP..NET where the order of logging operations is not predictable.


Know very little about ASP.NET<http://ASP.NET>


Sent from my Sony Xperia


---- Kirill Grischuk wrote ----


But this thing happens in file too, so target doesn't make sense. I am trying to get an example, it will be as soon as possible

**Comment by Kirya522** [comment]
my web-config now:

> two targets: one in async and one in sync

```xml
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <variable name="logDirectory" value="c:/logs/MyApp" />
    <targets async="true">
      <target name="performance" xsi:type="File" fileName="${logDirectory}/performance/performance.log" 
layout="${longdate} 
[${tmdlc:OperationId}] 
${level:uppercase=true:padding=-5} 
${tmdlc:Request} 
${tmdlc:RequestBody} 
${tmdlc:Logins:whenEmpty=${gdc:Logins}} 
${message}" 
archiveFileName="${logDirectory}/performance/archive/performance.${shortdate}.log" maxArchiveFiles="31" 
archiveNumbering="Rolling" 
archiveEvery="Day" />
      </target>
    </targets>
    <targets>
      <target name="logfile" xsi:type="File" fileName="${logDirectory}/info/info.log" />
    </targets>
    <rules>
      <logger name="performance" minlevel="Trace" writeTo="performance" />
      <logger name="*" minlevel="Info" writeTo="logfile" />
    </rules>
  </nlog>

```
tmldc - my renderer in no auth mode(nlog.web analog)

logger usage :
```c#
NLog.LogManager.GetLogger("performance").Info("foo");
Thread.Sleep(3);
NLog.LogManager.GetLogger("performance").Info("bar");
```
but actually in logs i get next thing: same time for both logs, and if i make the sleep more than 3 ms (up to 10 ms or higher in tests) time is the same async logs:

```log
2019-08-13 18:14:57.1634 [7b-4all] INFO  POST http://localhost/MyApp/Api/SomeApi {"op":23353,"vp":2579} sc\protopopenko foo
2019-08-13 18:14:57.1634 [7b-4all] INFO  POST http://localhost/MyApp/Api/SomeApi {"op":23353,"vp":2579} sc\protopopenko bar
```

And sync logs:
```log
2019-08-13 18:14:57.1634|INFO|performance|foo
2019-08-13 18:14:57.1634|INFO|performance|bar
```
**Timestamps are the same** but sometimes logs come in incorrect order this is very strange

**Comment by 304NotModified** [comment]
> the sleep more than 3 ms

FYI, the default Accuracy is 16ms. I would recommend to use AccurateUTC, see https://github.com/NLog/NLog/wiki/Time-Source

**Comment by Kirya522** [comment]
I will check it, thx

**Comment by snakefoot** [comment]
> @Kirya522  Timestamps are the same **but sometimes logs come in incorrect order** this is very strange

If you can provide a reproducible case where logevents are coming in correct order in the file-target (async or sync), then please tell.

**Comment by Kirya522** [comment]
> Instead of using `address="http://` then you could consider using `address="tcp://` together with `lineEnding="Null"`.
I have tried tcp, but http sender only works in this target, I managed to create new tcp input but nothing changed

**Comment by snakefoot** [comment]
Look at first comment about using NLog network target with GelfLayout.


I know GrayLogHttp does not support TCP


Sent from my Sony Xperia


---- Kirill Grischuk wrote ----


Instead of using address="http:// then you could consider using address="tcp:// together with lineEnding="Null".
I have tried tcp, but http sender only works in this target, I managed to create new tcp input but nothing changed

**Comment by Kirya522** [comment]
@snakefoot You didn't understand, now i am using network target with NLog.GelfLayout ver. 0.4, but tcp doesn't work

**Comment by snakefoot** [comment]
Have you setup your Graylog instance to use TCP? Are you using the right port? Have you checked NLog InternalLogger?


Does network target with http work?


Sent from my Sony Xperia


---- Kirill Grischuk wrote ----


@snakefoot<https://github.com/snakefoot> You didn't understand, now i am using network target with NLog.GelfLayout ver. 0.4, but tcp doesn't work

**Comment by Kirya522** [comment]
I added new TCP GELF input with new port(input is running). Http target works properly. Also I didn't forget to change protocol and port in web.config.

**Comment by snakefoot** [comment]
Guess you have to check the NLog InternalLogger to investigate TCP. Sadly enough the NLog Network Target can also send out-of-order when using HTTP. See also #3546


Sent from my Sony Xperia


---- Kirill Grischuk wrote ----


I added new TCP GELF input with new port(input is running). Http target works properly. Also I didn't forget to change protocol and port in web.config.

**Comment by Kirya522** [comment]
My graylog config
![image](https://user-images.githubusercontent.com/33904040/63518515-a334c480-c50a-11e9-9c25-b4bd7fe1d554.png)
internal logging return this
`Error NetworkTarget(Name=graylogt_wrapped): Error when sending. Exception :System.IO.IOException:
Error: ConnectionRefused`

**Comment by snakefoot** [comment]
Are you able to make a telnet connection to the port number on Graylog? (or use some other tool that can verify that firewall or other is not blocking)


Never used Graylog myself. So I'm a poor help in that area.


Sent from my Sony Xperia


---- Kirill Grischuk wrote ----


My graylog config
[image]<https://user-images.githubusercontent.com/33904040/63518515-a334c480-c50a-11e9-9c25-b4bd7fe1d554.png>
internal logging return this
Error NetworkTarget(Name=graylogt_wrapped): Error when sending. Exception :System.IO.IOException: Error: ConnectionRefused

**Comment by Kirya522** [comment]
Yeah change port to 12221, i think firewall on server. But now i am missing messages I have tried using different line endings from (none to crlf) and changed in graylog string endings, but i get only 1 message

**Comment by snakefoot** [comment]
So TCP is now working. But you only get one log message over to Graylog? And you have disabled Http on Graylog (or moved it to different port than TCP uses)


Again not a super hero when it comes to diagnosing Graylog connection issues. Maybe  another forum is better?


Sent from my Sony Xperia


---- Kirill Grischuk wrote ----


Yeah change port to 12221, i think firewall on server. But now i am missing messages I have tried using different line endings from (none to crlf) and changed in graylog string endings, but i get only 1 message

**Comment by Kirya522** [comment]
Thx, U really helped me, but i disabled http target. And have only 1 msg from tcp)

**Comment by snakefoot** [comment]
Can only advice you to find someone that knows more about using TCP on Graylog. And can analyze why communication fails.


Sent from my Sony Xperia


---- Kirill Grischuk wrote ----


Thx, U really helped me, but i disabled http target. And have only 1 msg from tcp)

**Comment by snakefoot** [comment]
Could you try the setting: keepConnection="False" on the NLog Network Target?


If it works then it is not the most optimal solution, but it will send in order.


Sent from my Sony Xperia


---- Kirill Grischuk wrote ----


Thx, U really helped me, but i disabled http target. And have only 1 msg from tcp)

**Comment by Kirya522** [comment]
Well, this thing works, but with many logs it can create multiple connections, so i will continue to look around

**Comment by snakefoot** [comment]
What happens if you configure `keepConnection="True"` and `lineEnding="Null"` ?

**Comment by Kirya522** [comment]
Oh i am stupid haven't seen that line ending doesn't work without `newLine ="true"` and now it works allright, thx u really helped me

**Comment by Kirya522** [comment]
This problem can be closed because the main problem is that custom target doesn't have queue at all, so as a result races in http create problems

**Comment by snakefoot** [comment]
Happy the problem has been resolved. Could you post your final nlog-config for others to witness?

**Comment by Kirya522** [comment]
So my final nlog-config is
```xml
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <time type="AccurateUTC" />
    <extensions>
      <add assembly="NLog.Web" />
      <add assembly="NLog.Layouts.GelfLayout" />
    </extensions>
    <targets async="true">
      <target name="graylogt" xsi:type="network" address="tcp://graylog:12200" newLine ="true" lineEnding="Null" >
        <layout xsi:type="GelfLayout" facility="WebApi">
          <parameter  name="current_user" layout="${aspnet-user-identity}" />
          <field name="exception_type" layout="${exception:Type}" />
          <field name="request" layout="${aspnet-request-method} ${aspnet-request-url}" />
          <field name="site" layout="${iis-site-name} ${aspnet-appbasepath}" />
          <field name="request_body" layout="${onexception:${aspnet-request-posted-body}:when=level>=LogLevel.Error}" />
        </layout>
      </target>
    </targets>
    <rules>
        <logger name="*" minlevel="debug" writeTo="graylogt" />
    </rules>
  </nlog>
```

and here is my graylog input
![image](https://user-images.githubusercontent.com/33904040/63569383-8b088800-c592-11e9-808b-04e5f335bdf5.png)

**Comment by Kirya522** [comment]
Well i have tried this thing in prod and out of order happens again, graylog sorts default by timestamp, logs with the same time stamps sorts with ti,e of coming and the order isn't right. I have used sequenceId to show it.

![image](https://user-images.githubusercontent.com/33904040/63572843-4d5d2c80-c59d-11e9-9ec4-5b4d0902ad76.png)

**Comment by Kirya522** [comment]
Sorry it's gaylog bugs it sorts everything not by time of coming but by message so the easiest solution is to add sequenceId in message before everything, but now i am looking to change graylog web interface to graphana

**Comment by snakefoot** [comment]
Sounds like this whole adventure was triggered by "graylog web interface" then.

But I'm very happy that you "volunteered" to test "NLog.Layouts.GelfLayout" with NLog Network-Target.

Will make an update to the documentation with your updated NLog.config example. So others can use graylog with minimum of friction.

Maybe I could make a small "fix" to "NLog.Layouts.GelfLayout" so the timestamp tries to be unique. And only when sending more than 10000 msgs/sec then it it will be out-of-order.

**Comment by Kirya522** [comment]
Well in grafana interface logs is out of order too so I think that graylog save logs out of order with same timestamp and order of logs become unpredictable, logs sort not by time of coming from old to new and not by string compare of messages. For example I sent logs with the same timestamp, but different messages, the first is 36 and the second is 37, and "second" comes first, that's very strange, I sent this message through graylog api via postman.

**Comment by snakefoot** [comment]
Again if you are not sending 10000 msg/sec then I think it can be fixed in the "NLog.Layouts.GelfLayout" to ensure "unique" timestamps.

**Comment by Kirya522** [comment]
Well, waiting for update)

**Comment by snakefoot** [comment]
Created PR https://github.com/farzadpanahi/NLog.GelfLayout/pull/14 for you. Introduces a new setting `FixDuplicateTimestamp`.

**Comment by snakefoot** [comment]
NLog ver. 4.6.7 changes the Network Target so Http-requests are sent in-order by using a queue (Just like for TCP). See also #3546
