### ISSUE TITLE
NLog 4.6.6: questions

### ISSUE THREAD

**Issue by Rajkumar28269** [NLog/NLog#3543]
Hi! 

I have a solution with web application project and class library projects. One of class library project has logging functionality that is written inbuilt and we are trying to remediate inbuilt logging to NLog. Now the question is where should I have the configuration files installed for this solution.

Do I need to place the configuration in web application? or should I have to have the configuration in class library?

Also I want to install NLog.Extended.dll as well. Where should I have the extended assembly install?

Please confirm?

**Comment by 304NotModified** [comment]
> ow the question is where should I have the configuration files installed for this solution.

If you're using the nlog.config, in the entry points (web application in this case, please note you could reuse by loading (party) configs from other paths)

Or if you creating config from code, you could leave it where you like (web application or class library project)



> Also I want to install NLog.Extended.dll as well.

Are you using Nuget? Then just install the package. When using .NET Core, also use `<extensions>`.

(the nlog.extended.dll will be place in the same folder as nlog.dll)

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, please let us know!
