### ISSUE TITLE
Network Target with Http can become out-of-order

### ISSUE THREAD

**Issue by snakefoot** [NLog/NLog#3544]
- What is the current result? Network with TCP will ensure delivery in-order. Network with HTTP will allow multiple concurrent HTTP-requests out-of-order (to the same address).
- What is the expected result? Just like TCP is inorder, then HTTP should also be in-order
- Are there any workarounds? no
- Is there a version in which it did work? no
- Can you help us by writing an unit test?

I guess the same issue can occur with WebServer-Target

**Comment by snakefoot** [comment]
Could also be interesting to include an extra error-handling strategy. Right now TCP will drop all pending network-requests if the TCP-socket becomes bad (eventhough it has the power to attempt reinit the socket).

Maybe TCP  + HTTP should have some extra strategies:
- Discard entire queue on exception (current default)
- Sleep on exception, that increases on each error until good (new)
- Retry on exception (new)

**Comment by 304NotModified** [comment]
> * Are there any workarounds? no

Work around should be, disable concurrent request?

**Comment by snakefoot** [comment]
> Work around should be, disable concurrent request?

There is no option to "disable concurrent request". One could use blocking mode in the http-sender, but then the promise of network target being fully async is no longer true.

I would change the http-sender to inherit from a base-class that is shared by the tcp-sender and http-sender. This base-network-sender class would then have the queue-logic.

**Comment by 304NotModified** [comment]
> I would change the http-sender to inherit from a base-class that is shared by the tcp-sender and http-sender.

That I understand it correctly, a new base class for TcpNetworkSender and HttpNetworkSender that inherits from NetworkSender?

**Comment by snakefoot** [comment]
Yes. I think that would work


Sent from my Sony Xperia


---- Julian Verdurmen wrote ----


I would change the http-sender to inherit from a base-class that is shared by the tcp-sender and http-sender.

That I understand it correctly, a new base class for TcpNetworkSender and HttpNetworkSender that inherits from NetworkSender?

**Comment by 304NotModified** [comment]
Sounds nice. Added a new base class in between is also not a breaking change AFAIK

**Comment by snakefoot** [comment]
Created PR  #3546

**Comment by 304NotModified** [comment]
fixed by #3544
