### ISSUE TITLE
Question: NLog Configuration for SQLCipher Database

### ISSUE THREAD

**Issue by dmtomczyk** [NLog/NLog#3551]
Hello, got a question regarding NLog compatibility with SQLCipher. My question is expanded upon by the information I have entered below. Any assistance would be appreciated, and thanks in advance!

The current NLog version: **(NLog 4.6.6)**

**The current config (file content or API calls):**
```
<?xml version="1.0" encoding="utf-8" ?>

<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      internalLogLovel="Debug"
      internalLogFile="file.txt"
      internalLogToConsole="true"
      internalLogIncludeTimestamp="true">

  <targets>

    <!-- DATABASE LOGGER-->
    <target name="DBLog"
            xsi:type="Database"
            dbProvider="Microsoft.Data.SQLite.SQLiteConnection, Microsoft.Data.SQLite"
            keepConnection="false"
            connectionString="Data Source=redacted\redacted.db"
            dbPassword="redacted"
            commandText="INSERT INTO Logs (Message) VALUES ('Test');">
    </target>

  </targets>

  <rules>
    <logger name="*" minlevel="Debug" writeTo="DBLog" />
  </rules>

</nlog>
```

**If relevant: the current result**
```
2019-08-15 11:46:15.4789 Info Message Template Auto Format enabled

2019-08-15 11:46:15.5587 Info Adding target DatabaseTarget(Name=DBLog)

2019-08-15 11:46:15.6265 Info Found 38 configuration items

2019-08-15 11:46:15.7622 Info Configuration initialized.

2019-08-15 11:46:15.7751 Info NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c. File version: 4.6.6.10303. Product version: 4.6.6.

2019-08-15 11:47:04.6315 Error DatabaseTarget(Name=DBLog): Error when writing to database. Exception: Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 26: 'file is not a database'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.<PrepareAndEnumerateStatements>d__62.MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at NLog.Targets.DatabaseTarget.WriteEventToDatabase(LogEventInfo logEvent, String connectionString)
   at NLog.Targets.DatabaseTarget.Write(LogEventInfo logEvent)
```

**If relevant: the expected result**
- I am receiving a "file is not a database error" that is leading me to believe either the encryption on the db is causing the error, or my config is incorrect.
- I expect the config file to be correctly setup in order to work with this SQLCipher (SQLite encrypted) database. **Should** NLog work with [SQLCipher](https://github.com/sqlcipher/sqlcipher) as it does with SQLite? Or is my assumption wrong that NLog should work with this DB Type, so I should continue to use the custom logger I built using our ORM?

**Comment by snakefoot** [comment]
If you are able to communicate with your SQLCipher database using `Microsoft.Data.SQLite.SQLiteConnection`-object where ConnectionString has been assigned to `"Data Source=redacted\redacted.db"`, then NLog should also be able to do it.

But I think the problem is that `dbPassword="redacted"` has to be injected in special way:

https://www.zetetic.net/sqlcipher/sqlcipher-for-dotnet/ (Must execute command `$"PRAGMA key = '{password}';"`)
https://www.zetetic.net/sqlcipher/sqlcipher-ado/ (Must call SQLiteConnection.SetPassword)

There is currently no support for executing bonus commands when opening database-connection in DatabaseTarget. Either create PR to allow the DatabaseTarget to execute DbCommands after connection-open. Or create your own custom SqlCipherDatabaseTarget that inherits from DatabaseTarget.

**Comment by dmtomczyk** [comment]
@snakefoot Thanks for the reply! I believe you are entirely accurate. Would you have any suggestions as to the route to take when implementing the change to DatabaseTarget?

**Comment by snakefoot** [comment]
> Would you have any suggestions as to the route to take when implementing the change to DatabaseTarget?

Well I'm just a guy that likes to read the manual when things are not working. I know nothing about SqlCipher.

I think it is wise that you do some experiments with `Microsoft.Data.SQLite.SQLiteConnection`, and see if you can make a code-example where you are able to write to the database.

Based on the working code-example, then one can consider how to implement this in NLog DatabaseTarget.

Have you tried just doing this (Injecting the PRAGMA key in the `commandText`):

```xml
    <!-- DATABASE LOGGER-->
    <target name="DBLog"
            xsi:type="Database"
            dbProvider="Microsoft.Data.SQLite.SQLiteConnection, Microsoft.Data.SQLite"
            keepConnection="false"
            connectionString="Data Source=redacted\redacted.db"
            commandText="PRAGMA key = 'redacted';INSERT INTO Logs (Message) VALUES ('Test');">
    </target>
```

**Comment by dmtomczyk** [comment]
> Have you tried just doing this (Injecting the PRAGMA key in the commandText):

Yeah, it works! I am able to log to the table this way.

However, as you mentioned, I'm not sure how good of a solution that will end up being.
Though I suppose there will have to be some juggling around of the key regardless.

I guess the problem now is to look into the Cost-Benefits of using NLog while injecting the key in this manner, using the solution I have already implemented with EFCore, or making the PR and look into making those changes.

**Comment by dmtomczyk** [comment]
As far as the context of this question is concerned, I would say it has been answered, so I will go ahead and close this issue. 

I appreciate the assistance @snakefoot

**Comment by snakefoot** [comment]
As long you have the setting `keepConnection="false"` then it doesn't make much difference whether you setup the password on connection-open-attempt or setup password on execution-command-attempt.

**Comment by dmtomczyk** [comment]
Agreed.

Ultimately I believe we will be keeping the connection open, but for now this will do!

Thanks again!
