### ISSUE TITLE
NLog with docker-compose.yml

### ISSUE THREAD

**Issue by kushmishra21** [NLog/NLog#3553]
Hi,

Any suggestions on how could we attach the NLog.config to a docker-compose.yml file so that it generates a “NLog_Internal.txt” on the host machine and we can see all the application logs in that file?

I have already tried creating an ASP.NET Core application with “NLog.config” and having only “NLog.Web.AspNetCore” package but still doesn’t work.

Thanks,
Kush Mishra

**Comment by snakefoot** [comment]
If you need help setting up docker image to allow file-writing then you should probably find a forum about docker-images (Or try StackOverflow.com)

**Comment by 304NotModified** [comment]
Is this a NLog or a docker question?

**Comment by kushmishra21** [comment]
Hi,

I have managed to use NLog with docker-compose.yml however, the problem is how could we extract these logs in a local directory or use a cloud to see what logs are actually generated.

My NLog.config looks like the following:

<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      throwConfigExceptions="true"
      internalLogLevel="Trace"
      internalLogToConsole="true">

  <variable name="dockerlogDirectory" value="/data/logs/app"/>

  <targets>
    <target xsi:type="File" name="ownFile" fileName="${dockerlogDirectory}/MyCustomLog-${shortdate}.log"
            layout="${longdate}|${logger}|${uppercase:${level}}|${threadid}:${threadname}|${message} ${exception}" />
    <target xsi:type="Console" name="console" />
    <target xsi:type="Null" name="blackhole" />
  </targets>

  <rules>
    <logger name="*" minlevel="Trace" writeTo="console" />
    <logger name="Microsoft.*" minlevel="Trace" writeTo="blackhole" final="true" />
    <logger name="*" minlevel="Info" writeTo="ownFile" />
  </rules>

</nlog>

**Comment by kushmishra21** [comment]
`<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      throwConfigExceptions="true"
      internalLogLevel="Trace"
      internalLogToConsole="true">

  <variable name="dockerlogDirectory" value="/data/logs/app"/>

  <targets>
    <target xsi:type="File" name="ownFile" fileName="${dockerlogDirectory}/MyCustomLog-${shortdate}.log"
            layout="${longdate}|${logger}|${uppercase:${level}}|${threadid}:${threadname}|${message} ${exception}" />
    <target xsi:type="Console" name="console" />
    <target xsi:type="Null" name="blackhole" />
  </targets>

  <rules>
    <logger name="*" minlevel="Trace" writeTo="console" />
    <logger name="Microsoft.*" minlevel="Trace" writeTo="blackhole" final="true" />
    <logger name="*" minlevel="Info" writeTo="ownFile" />
  </rules>

</nlog>`

**Comment by snakefoot** [comment]
@kushmishra21 To make log-files available outside the docker-image, then one usually mount an external folder into the docker-image.

By logging to the mounted-external-folder, then one can access the log-files even when the docker-image is not running.

**Comment by kushmishra21** [comment]
@snakefoot Thanks for the reponse however, I am not sure how could I implement your suggestion because my application runs inside a Linux Docker container and I want to extract these logs and at the end, I should be able to see those logs.
My docker-compose.yml looks like the following:

version: '3.4'

networks:
  myapp-network:
    driver: bridge

services:
  myapp:
    image: myapp:latest
    depends_on:
      - "postgres_image"
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "5000:80"
    volumes:
      - myapp_logsvolume: /data/logs/app
    environment:
      ISDOCKER: ${ISDOCKER}
    networks:
      - myapp-network    
      
  postgres_image:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres_datavolume:/var/lib/postgresql/data
      - postgres_backupvolume:/backups
    environment:
      POSTGRES_USER: ${POSTGRESUSER}
      POSTGRES_PASSWORD: ${POSTGRESPWD}
      POSTGRES_DB: ${POSTGRESDB}
    networks:
      - myapp-network

volumes:
  myapp_logsvolume:
  postgres_datavolume:
  postgres_backupvolume:

**Comment by snakefoot** [comment]
Maybe something like this:

https://stackoverflow.com/questions/54374724/docker-container-save-logs-on-the-host-directory
