### ISSUE TITLE
ILogger and Logger have different APIs. Any reason why?

### ISSUE THREAD

**Issue by wehadfun** [NLog/NLog#3559]
The following methods are in Logger but not ILogger:
* ConditionalDebug
* ConditionalTrace
* WithProperty

Any reason why these were left off of ILogger?

**Comment by 304NotModified** [comment]
Most importatn, adding them to ILogger would be a breaking change. 

Maybe an extension on ILogger would be nice - if possible

**Comment by snakefoot** [comment]
If I had my will then ILogger would look like this:

```c#
interface ILogger
{
   bool IsEnabled(LogLevel level);

   void Log(Type wrapperType, LogEventInfo logEvent);

   void Log(LogLevel level, Exception exception, message, params object[] args);

   void Log(LogLevel level, string message, params object[] args);
}
```

And everything else would be extension-methods to ILogger. Right now NLog pays the price of virtual function call for all logging-methods. Stupid performance penalty.

Also everyone that wants to mock NLog-ILogger has to mock a crazy amount of methods. Stupid boilerplate code.

**Comment by 304NotModified** [comment]
> If I had my will then ILogger would look like this:

True, expect the ILogger interface is older than extensions methods.

One option is to create a new base interface, which is tried already I guess (ILoggerBase)

Maybe even LogEventInfo  should not belong to the interface, as LogEventInfo  has a many dependencies and it's an interface.

**Comment by snakefoot** [comment]
The LogEventInfo is needed for one to create the more exciting extension methods along with callsite handling when wrapping ILogger.


Sent from my Sony Xperia


---- Julian Verdurmen wrote ----


If I had my will then ILogger would look like this:

True, expect the ILogger interface is older than extensions methods.

One option is to create a new base interface, which is tried already I guess (ILoggerBase)

Maybe even LogEventInfo should not belong to the interface, as LogEventInfo has a many dependencies and it's an interface.

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, please let us know!
