### ISSUE TITLE
Question : Why not having a single Logger ?

### ISSUE THREAD

**Issue by NaolShow** [NLog/NLog#3564]
Hello everyone !

I just have a little question.
Why not just using a single static Logger in a class and use it everywhere ?
And then just having in the target a layout that has ${callsite} ?

Thanks for the answer!

**Comment by snakefoot** [comment]
- `${callsite}` is expensive as it requires StackTrace capture for each LogEvent
- Logger-Name is faster for LogLevel-filtering and routing to individual targets.

**Comment by NaolShow** [comment]
Oh, Ok thanks :) !
