### ISSUE TITLE
Nlog nuget package .nuspec contains wrong Version

### ISSUE THREAD

**Issue by gplutov** [NLog/NLog#3572]
Nlog nuget package .nuspec contains wrong Version

Current result: Added Nlog nuget reference to my project of version 4.6.6.
Nlog version added is 4.0.0

    <Reference Include="NLog, Version=**4.0.0.0**, Culture=neutral, PublicKeyToken=5120e14c03d0593c, processorArchitecture=MSIL">
      <HintPath>..\..\..\..\..\bin\packages\NLog.4.6.6\lib\net45\NLog.dll</HintPath>
    </Reference>

Expected result:

    <Reference Include="NLog, Version=**4.6.6.0**, Culture=neutral, PublicKeyToken=5120e14c03d0593c, processorArchitecture=MSIL">
      <HintPath>..\..\..\..\..\bin\packages\NLog.4.6.6\lib\net45\NLog.dll</HintPath>
    </Reference>

**Comment by snakefoot** [comment]
Assembly version is stuck at 4.0.0 because of strong-name-support.

NLog supports semver, and promise not to break any API-interfaces when upgrading to newer version (Unless major-version-change. Ex. 4.0 to 5.0)

**Comment by gplutov** [comment]
Hi, Thanks for the quick replay.

How can i overcome this scenario:
There is one project which has nuget reference of 4.0.0(which is actually 4.6.6) and in addition it has dll reference which requires nlog 4.4.5
msbuild automatically adds assembly binding:

         <dependentAssembly>
           <assemblyIdentity name="NLog" publicKeyToken="5120e14c03d0593c" culture="neutral" />
           <bindingRedirect oldVersion="0.0.0.0-4.4.5098.0" newVersion="4.4.5098.0" />
         </dependentAssembly>

and getting assembly not found exception because the actual nlog which exists is 4.0.0(4.6.6).

msbuild adds this redirect because it identify that 4.4.5098.0 is higher than 4.0.0

**Comment by snakefoot** [comment]
Sounds strange with the binding-redirect. It is for fixing strong-name version changes. And all of them has strong-version 4.0.0.

Have many solutions with projects using different NLog-versions, and have not experienced that binding-redirects are added.

What happens if you just remove the binding-redirect?

**Comment by 304NotModified** [comment]
If you aren't mixing NLog 4.x with a version before 4.0, then you don't need the bindingRedirect. So just remove it :)

**Comment by 304NotModified** [comment]
Please note that assembly version, file version and nuget version are different things and those don't need to be aligned. See also #2939 and #1765

**Comment by gplutov** [comment]
If i am removing it so it fails beacuase my dll reference which requires 4.4.5 fail to load the assembly.
The only thing that solved this is to add this strange biding redirect:
      <dependentAssembly>
        <assemblyIdentity name="NLog" publicKeyToken="5120e14c03d0593c" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.4.5098.0" newVersion="4.0.0.0" />
      </dependentAssembly>

**Comment by gplutov** [comment]
<dependentAssembly>
        <assemblyIdentity name="NLog" publicKeyToken="5120e14c03d0593c" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.4.5098.0" newVersion="4.0.0.0" />
      </dependentAssembly>

**Comment by 304NotModified** [comment]
Where is 4.4.5098.0 is coming from ? I checked al lot of 4.4 version, and all of them are correct. 

![image](https://user-images.githubusercontent.com/5808377/64076508-091d0b00-ccc6-11e9-88f7-8116616d9aee.png)


![image](https://user-images.githubusercontent.com/5808377/64076492-e5f25b80-ccc5-11e9-84a6-0874c0b1a483.png)

![image](https://user-images.githubusercontent.com/5808377/64076496-f276b400-ccc5-11e9-9b36-29af4993d8d3.png)

![image](https://user-images.githubusercontent.com/5808377/64076502-fe627600-ccc5-11e9-88b8-00cddce6603b.png)


![image](https://user-images.githubusercontent.com/5808377/64076478-b4799000-ccc5-11e9-8a37-60749035c122.png)

![image](https://user-images.githubusercontent.com/5808377/64076481-b7748080-ccc5-11e9-9af4-e65acbdec7a2.png)

![image](https://user-images.githubusercontent.com/5808377/64076482-ba6f7100-ccc5-11e9-935e-acc8ea6e7d66.png)

**Comment by gplutov** [comment]
Sorry maybe I was not clear. I will be more specific:

I have project which has nuget package reference to NLog 4.6.6 and in addition it has dll reference to Microsoft.Practices.Unity.dll, While Microsoft.Practices.Unity.dll require NLog 4.4.5098.0

When I build this project it automatically adds this:

     <dependentAssembly>
       <assemblyIdentity name="NLog" publicKeyToken="5120e14c03d0593c" culture="neutral" />
       <bindingRedirect oldVersion="0.0.0.0-4.4.5098.0" newVersion="4.4.5098.0" />
     </dependentAssembly>

When Execute it, it fails because Microsoft.Practices.Unity.dll need 4.4.5098.0 but it got 4.0.0(Which is actually 4.6.6)

If i remove the binding redirect it fails because of the same reason.

When I this it works: (not so logical binding redirect)

      <dependentAssembly>
        <assemblyIdentity name="NLog" publicKeyToken="5120e14c03d0593c" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.4.5098.0" newVersion="4.0.0.0" />
      </dependentAssembly>

If NuGet NLog was 4.6.6 version and not 4.0.0 so msbuild would know how to handle this situation and would add this which is logical binding redirect:

      <dependentAssembly>
        <assemblyIdentity name="NLog" publicKeyToken="5120e14c03d0593c" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.6.6.0" newVersion="4.6.6.0" />
      </dependentAssembly>

**Comment by 304NotModified** [comment]
> While Microsoft.Practices.Unity.dll require NLog 4.4.5098.0

I'm confused here. There is no NLog 4.4.5098.0?

> but it got 4.0.0(Which is actually 4.6.6)

It's both 4.0.0.0 and 4.6.6 ;) Assembly version 4.0.0.0 and Product/Information Version 4.6.6 and Nuget version 4.6.6.  See also https://stackoverflow.com/questions/64602/what-are-differences-between-assemblyversion-assemblyfileversion-and-assemblyin

**Comment by gplutov** [comment]
4.4.5098.0 is the file version 4.4.1 is the product version:

![image](https://user-images.githubusercontent.com/39349672/64077165-3bceff80-ccd6-11e9-9fb2-b4cf5c342a31.png)

**Comment by 304NotModified** [comment]
Now I;m even more confused. Nuget version 4.4.10 has file version 4.4.5361. 

![image](https://user-images.githubusercontent.com/5808377/64077277-15599600-cccf-11e9-8f83-e0ef164137ba.png)


Is your NLog 4.4.10 not from nuget?

Also, the bindingRedirect redirect uses  **assembly** version. Not file versions. 

![image](https://user-images.githubusercontent.com/5808377/64077290-2f937400-cccf-11e9-9f1a-6c698edce04d.png)

See https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/runtime/bindingredirect-element

Last but not least:

> The CLR does not care about nor examine the AssemblyFileVersion.

https://stackoverflow.com/a/802038/201303

**Comment by snakefoot** [comment]
Also surprised that your version of Microsoft Unity IOC-Container (Microsoft.Practices.Unity.dll) has a hard dependency on NLog. Pretty sure Microsoft have not released libraries with dependency on NLog. And at the same time a version of NLog that is not on nuget :)

Think this issue is a wild goose chase over the edge. Hope you find your wings and get back on track :)

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, please let us know!
