### ISSUE TITLE
Programmatically adding a target to a base configuration loaded from a file 

### ISSUE THREAD

**Issue by kaixiong** [NLog/NLog#3576]
Hi,

I have an application that is set up to log to a file via app.config. The version of NLog in use is 4.6.6.

Depending on the operational mode, either as a service or a commandline tool, I want the app to additionally print log messages to the console. To achieve this, I tried to add a console target programmatically to the existing, loaded configuration:

```
        private static void AddConsoleLogTarget()
        {
            var consoleTarget = new ColoredConsoleTarget("console")
            {
                Layout = @"${longdate} ${level:uppercase=true:padding=-5} ${message:withException=True}"
            };

            var configuration = LogManager.Configuration;
            configuration.AddTarget(consoleTarget);
            configuration.AddRuleForAllLevels("console");
        }
```

This did not work. I've also tried calling ReconfigExistingLoggers() afterward to no avail. Is this use case supported?

**Comment by snakefoot** [comment]
Have you tried this instead:

```c#
            var configuration = LogManager.Configuration;
            configuration.AddRuleForAllLevels(consoleTarget);
            configuration.ReconfigureExistingLoggers(); // Magic method
```

**Comment by kaixiong** [comment]
It turned out to be a configuration problem where I had set the 'final' flag for the main logging rule. I solved the problem by looking up the rule and adding the target directly to it:

```
LogManager.Configuration.FindRuleByName("Main").Targets.Add(consoleTarget);
LogManager.ReconfigExistingLoggers();
```

On a side note, setting LogManager.Configuration instead of calling ReconfigExistingLoggers() works as well.
