### ISSUE TITLE
Does OrdinalIgnoreCase works with (hash)Set if configured from nlog.config?

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#3591]
from https://github.com/NLog/NLog.Web/pull/472

does the OrdinalIgnoreCase work when Exclude is set from nlog.config?

```
public class MyTarget {
    public ISet<string> Exclude { get; set; } = new HashSet<string>(new[] { "AUTH", "SESS_ID" }, StringComparer.OrdinalIgnoreCase);
}
```

If a new (hash)set is created, we lose the `OrdinalIgnoreCase`. So we should not create a new set if it isn't needed.

**Comment by snakefoot** [comment]
The test failed when I tried. See also #3593

**Comment by 304NotModified** [comment]
fixed by https://github.com/NLog/NLog/pull/3593
