### ISSUE TITLE
Wrong values logged when using MDLC with TPL Dataflow

### ISSUE THREAD

**Issue by Azatey** [NLog/NLog#3592]
When using TPL Dataflow (I'm not blaming it) probably due to high concurrency usage NLog starts messing up the logged mdlc values inside scope.

**NLog version**: 4.6.7

**TPL Dataflow package**: System.Threading.Tasks.Dataflow, version 4.9.0

**Platform**: .Net 4.7.2

**Current NLog config** (xml or C#, if relevant)

```xml
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      throwConfigExceptions="true"
      throwExceptions="true"
      internalLogFile="logs\internal.log"
      internalLogLevel="Trace">
  <variable name="FileLayout"
            value="${longdate} | ${threadid} | ${level} | ${mdlc:item=context-data} | ${message}" />

  <targets async="true">
    <default-target-parameters type="File" layout="${FileLayout}" keepFileOpen="true" concurrentWrites="false" />
    <target name="Main" type="File" fileName="logs\application.log" />
  </targets>

  <targets>
    <target name="ConsoleLogger" type="ColoredConsole" layout="${FileLayout}" detectConsoleAvailable="true" />
  </targets>

  <rules>
    <logger name="*" minlevel="Trace" writeTo="Main, ConsoleLogger" />
  </rules>
</nlog>
```
**Sample C# code:**
```c#
internal class Input : TaskCompletionSource<string>
    {
        public int Value { get; }

        public Input(int value)
        {
            Value = value;
        }
    }

    class Program
    {
        private static readonly ILogger Logger = LogManager.GetCurrentClassLogger();

        static async Task Main(string[] args)
        {
            var mesh = CreateMesh();

            var computeTasks = Enumerable.Range(1, 3)
                .Select(async i =>
                {
                    using (MappedDiagnosticsLogicalContext.SetScoped("context-data", i))
                    {
                        Logger.Info($"Started processing within context {i}");
                        
                        var input = new Input(i);
                        await mesh.SendAsync(input);
                        var result = await input.Task;

                        Logger.Info($"Finished processing within context {i}");
                    }
                });

            await Task.WhenAll(computeTasks);

            Console.ReadLine();
        }

        private static ITargetBlock<Input> CreateMesh()
        {
            var options = new ExecutionDataflowBlockOptions
            {
                MaxDegreeOfParallelism = DataflowBlockOptions.Unbounded,
                EnsureOrdered = false
            };

            var incrementer = new TransformBlock<Input, (long, Input)>(input =>
            {
                Logger.Info($"Inside incrementer - context: {{{input.Value}}}...");
                return (input.Value + 1, input);
            }, options);

            var toStringConverter = new TransformBlock<(long number, Input input), (string, Input)>(tuple =>
            {
                var (number, input) = tuple;
                Logger.Info($"Inside hashedStringMaker - context: {{{input.Value}}}...");
                
                return ($">>{number}<<", input);
            }, options);

            var resultProvider = new ActionBlock<(string hash, Input input)>(tuple =>
            {
                var (hash, input) = tuple;
                Logger.Info($"Inside resultProvider - context: {{{input.Value}}}...");
                input.TrySetResult(hash);
            });

            var linkOptions = new DataflowLinkOptions {PropagateCompletion = true};

            incrementer.LinkTo(toStringConverter, linkOptions);
            toStringConverter.LinkTo(resultProvider, linkOptions);

            return DataflowBlock.Encapsulate(incrementer, toStringConverter);
        }
    }
```
- What is the current result?

|${longdate}|${threadid}|${level}|${mdlc:item=context-data}|${message}|
|---|---|---|---|---|
|2019-09-20 15:48:06.2936 | 1 | Info | 1 | Started processing within context 1        |
|2019-09-20 15:48:06.3916 | 1 | Info | 2 | Started processing within context 2        |
|2019-09-20 15:48:06.3986 | 5 | Info | 1 | Inside incrementer - context: {1}...       |
|2019-09-20 15:48:06.3986 | 1 | Info | 3 | Started processing within context 3        |
|2019-09-20 15:48:06.4126 | 6 | Info | 2 | Inside incrementer - context: {2}...       |
|2019-09-20 15:48:06.4426 | 6 | Info | 2 | Inside incrementer - context: {3}...       |
|2019-09-20 15:48:06.4586 | 7 | Info | 1 | Inside hashedStringMaker - context: {1}... |
|2019-09-20 15:48:06.4586 | 6 | Info | 2 | Inside hashedStringMaker - context: {2}... |
|2019-09-20 15:48:06.4586 | 7 | Info | 1 | Inside hashedStringMaker - context: {3}... |
|2019-09-20 15:48:06.4936 | 6 | Info | 1 | Inside resultProvider - context: {1}...    |
|2019-09-20 15:48:06.5126 | 6 | Info | 1 | Finished processing within context 1       |
|2019-09-20 15:48:06.5126 | 6 | Info | 1 | Inside resultProvider - context: {2}...    |
|2019-09-20 15:48:06.5126 | 6 | Info | 2 | Finished processing within context 2       |
|2019-09-20 15:48:06.5126 | 6 | Info | 1 | Inside resultProvider - context: {3}...    |
|2019-09-20 15:48:06.5126 | 6 | Info | 3 | Finished processing within context 3       |

- What is the expected result?

|${longdate}|${threadid}|${level}|${mdlc:item=context-data}|${message}|
|---|---|---|---|---|
|2019-09-20 15:48:06.2936 | 1 | Info | 1 | Started processing within context 1        |
|2019-09-20 15:48:06.3916 | 1 | Info | 2 | Started processing within context 2        |
|2019-09-20 15:48:06.3986 | 5 | Info | 1 | Inside incrementer - context: {1}...       |
|2019-09-20 15:48:06.3986 | 1 | Info | 3 | Started processing within context 3        |
|2019-09-20 15:48:06.4126 | 6 | Info | 2 | Inside incrementer - context: {2}...       |
|2019-09-20 15:48:06.4426 | 6 | Info | ~~2~~3 | Inside incrementer - context: {3}...       |
|2019-09-20 15:48:06.4586 | 7 | Info | 1 | Inside hashedStringMaker - context: {1}... |
|2019-09-20 15:48:06.4586 | 6 | Info | 2 | Inside hashedStringMaker - context: {2}... |
|2019-09-20 15:48:06.4586 | 7 | Info | ~~1~~3 | Inside hashedStringMaker - context: {3}... |
|2019-09-20 15:48:06.4936 | 6 | Info | 1 | Inside resultProvider - context: {1}...    |
|2019-09-20 15:48:06.5126 | 6 | Info | 1 | Finished processing within context 1       |
|2019-09-20 15:48:06.5126 | 6 | Info | ~~1~~2 | Inside resultProvider - context: {2}...    |
|2019-09-20 15:48:06.5126 | 6 | Info | 2 | Finished processing within context 2       |
|2019-09-20 15:48:06.5126 | 6 | Info | ~~1~~3 | Inside resultProvider - context: {3}...    |
|2019-09-20 15:48:06.5126 | 6 | Info | 3 | Finished processing within context 3       |

- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?

Yes, nothing helpful

**Comment by snakefoot** [comment]
Could you try and run this on the targetplatform `netcoreapp2.1`  ? (MDLC will use `AsyncLocal` on NetCore)

**Comment by snakefoot** [comment]
I can see these are good:

Started processing within context 1 - MDLC = 1
Started processing within context 2 - MDLC = 2
Started processing within context 3 - MDLC = 3

Finished processing within context 1- MDLC = 1
Finished processing within context 2 - MDLC = 2
Finished processing within context 3 - MDLC = 3

So I guess some kind of thread-optimization happens inside (skipping cloning of execution context):

`await mesh.SendAsync(input);`

NLog makes use of CallContext on net45 (and net472), so I guess you need to investigate if there pitfalls when combining TPL with CallContext.

**Comment by Azatey** [comment]
> I can see these are good:
> 
> Started processing within context 1 - MDLC = 1
> Started processing within context 2 - MDLC = 2
> Started processing within context 3 - MDLC = 3
> 
> Finished processing within context 1- MDLC = 1
> Finished processing within context 2 - MDLC = 2
> Finished processing within context 3 - MDLC = 3
> 
> So I guess some kind of thread-optimization (skipping cloning of execution context) happens inside:
> 
> `await mesh.SendAsync(input);`
> 
> NLog makes use of CallContext on net45 (and net472), so I guess you need to investigate if there are pitfalls when combining TPL with CallContext.

Yeah, tested TPL Dataflow in multiple ways and with other logging frameworks as well. Even tried pure AsyncLocal. Seems to be that TPL Dataflow somehow optimizes away the tasks and messes up ExecutionContext.
