### ISSUE TITLE
Should Factory.CreateInstance ignore NLog.Web errors?

### ISSUE THREAD

**Issue by ThomasArdal** [NLog/NLog#3595]
In my target I have a layout looking like this:

```csharp
public Layout HostnameLayout { get; set; } = "${event-properties:hostname:whenEmpty=${aspnet-request-host:whenEmpty=${machinename}}}";
```

Basically, I want to try and render a hostname by looking at various properties. If the user specify a structured variable named `hostname`, I will use that. If not, I look for an `aspnet-request-host`. If not there I try to pull the `machinename`.

The main challenge here is that the `CreateInstance` method of the `Factory` class, throws an exception if someone adds my target to their code but not add the `NLog.Web` package. I want to allow people running without the `NLog.Web` package, but I don't want the config causing an exception.

Is there some way to avoid this or should it maybe be allowed to reference layout renderers that may or may not be there?

**Comment by snakefoot** [comment]
If you want a soft dependency on NLog.Web and NLog.Web.AspNetCore. Then I guess you need to assign the layout on InitializeTarget instead of in constructor, and have some fallback mechanism if the wanted layoutrenderer is not yet available.

**Comment by ThomasArdal** [comment]
That would definitely work. Any way of "checking" a layout without trying to set the value and catch an `ArgumentException`?

```csharp
private void TrySetLayout(Action<Layout> layout, string value, string fallback)
{
    try
    {
        layout(value);
    }
    catch (ArgumentException)
    {
        layout(fallback);
    }
}
```

**Comment by snakefoot** [comment]
Can you give the exception-callstack, when you assign a text-string to a Layout that contains an unknown layout-renderer ?

Would actually think NLog would ignore unknown layout-renderers. Since that is the behavior when loading from Nlog.config-file.

**Comment by ThomasArdal** [comment]
```
LayoutRenderer cannot be found: 'aspnet-response-statuscode'. Is NLog.Web not included?
```

**Comment by ThomasArdal** [comment]
> Would actually think NLog would ignore unknown layout-renderers.

I think that would be a better solution overall.

**Comment by snakefoot** [comment]
> I think that would be a better solution overall.

Think the ignore-behavior only happens when throwExceptions=false and throwConfigExceptions=false.

Must admit I kind of like that throwConfigExceptions makes NLog complain about typos and other errors.

**Comment by ThomasArdal** [comment]
Didn't know about `throwConfigExceptions=false`. I had it in the sample code. Must have been a copy-paste from somewhere. It now makes total sense to me and I agree. If users set this to `true`, NLog should indeed complain.

**Comment by ThomasArdal** [comment]
This issue should probably just be closed then. I'll keep my `TrySetLayout`-method to support people who want to set `throwConfigExceptions` to `true` and not include the `NLog.AspNet` package.

**Comment by 304NotModified** [comment]
> This issue should probably just be closed then

👍
