### ISSUE TITLE
Failure in. net core 3.0

### ISSUE THREAD

**Issue by cxyzjnet** [NLog/NLog#3607]
When I upgraded my framework from 2.2 to 3.0, I found that all my logs (including the console) were gone, but when I switched back to the branch of 2.2, it was normal. When I commented out UseNLog (), the console logs returned to normal.

**Comment by snakefoot** [comment]
Does it work with NLog.Web.AspNetCore ver. 4.8.4 ?

**Comment by cxyzjnet** [comment]
<PackageReference Include="NLog" Version="4.6.7" />
    <PackageReference Include="NLog.Extensions.Logging" Version="1.5.4" />
    <PackageReference Include="NLog.Web.AspNetCore" Version="4.8.5" />

**Comment by snakefoot** [comment]
So du did you try with NLog.Web.AspNetCore ver 4.8.4? (Together with NLog.Extension.Logging ver 1.5.3)?


Sent from my Sony Xperia


---- cxyzjnet wrote ----


<PackageReference Include="NLog" Version="4.6.7" /> <PackageReference Include="NLog.Extensions.Logging" Version="1.5.4" /> <PackageReference Include="NLog.Web.AspNetCore" Version="4.8.5" />

**Comment by cxyzjnet** [comment]
OK, does the new version have BUG?

**Comment by snakefoot** [comment]
That is what I'm trying to figure out. Did it work better with NLog.Web.AspNetCore ver 4.8.4?


Sent from my Sony Xperia


---- cxyzjnet wrote ----


OK, does the new version have BUG?

**Comment by cxyzjnet** [comment]
Yes, the version returned to normal after downgrading.

**Comment by snakefoot** [comment]
Created PR https://github.com/NLog/NLog.Web/pull/485 to fix this change in behavior.
