### ISSUE TITLE
Incorrect path format with multiple NLog configs

### ISSUE THREAD

**Issue by Spamm3r** [NLog/NLog#3612]
So` basically in my project I have a lot of sub-projects which has to have NLog implemented. I tried to have two configs. One when sub-project is run seperately and second one for all projects. I tried to make this happen using AutoReload=true and attacking NLog.config with include file. Loggins works with multiple projects but I am getting NLog exception with incorrect path format.
This is my NLog (second NLog looks the same but without AutoReload, include and extension.

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      throwExceptions="true"
      internalLogFile="C:/LogError/ASILogError.txt"
      internalLogLevel="Warn"
      AutoReload="True">
  <include file="${basedir}\NLog.config"/>
  <extensions>
    <add assembly="Aktualizator" />
  </extensions>
  <targets>
    <target xsi:type="File" name ="CSV" fileName="C:/LogError/ASAktualizatorLogError.csv" encoding="ISO-8859-2">
      <layout xsi:type="LayoutWithHeaderAndFooter" >
        <header xsi:type="SimpleLayout" text= "Date; Time; Level; Message; Exception; Callsite; Stacktrace; inEx ; "/>
        <layout xsi:type="CsvLayout" delimiter="Semicolon">
          <column name="date" layout="${shortdate}" />
          <column name="time" layout="${date:format=HH\:mm\:ss}" />
          <column name="level" layout="${level}" />
          <column name="message" layout="${message}" />
          <column name="exception" layout="${exception:format=tostring:maxInnerExceptionLevel=10:exceptionDataSeparator= #}" />
          <column name="callsite" layout="${callsite:fileName=True:className=True:methodName=True}"/>
          <column name="stacktrace" layout="${stacktrace:format=Raw:topFrames=10}" />
          <column name="innerException" layout="${exception:format=type,message,method:maxInnerExceptionLevel=5:innerFormat=shortType,message,method}" />
        </layout>
      </layout>
    </target>
    <target xsi:type="Console" name="Console">
      <layout xsi:type="CsvLayout" withHeader="false" quoting="All">
        <column layout="################################################################################${newline}" />
        <column name="date" layout="${shortdate}${newline}" />
        <column name="time" layout="${date:format=HH\:mm\:ss}${newline}" />
        <column name="level" layout="${level}${newline}" />
        <column name="exceptionInner" layout="${exception:format=toString,Data:maxInnerExceptionLevel=10}${newline}" />
        <column name="innerException" layout="${exception:innerformat=tostring:maxInnerExceptionLevel=10}${newline}" />
        <column name="stracktrace" layout="${stacktrace:format=DetailedFlat:topFrames=5}${callsite}${callsite-linenumber}${newline}"/>
        <column layout="################################################################################" />
      </layout>
    </target>
  </targets>
  <rules>
    <logger name="*" minlevel="Warn" writeTo="CSV" />
    <logger name="*" minlevel="Info" writeTo="Console">
    </logger>
  </rules>
</nlog>
```

**Comment by 304NotModified** [comment]
Hi, please edit the question and fill in all the question. Please add the full error with stack Trace (visible in internal log)

**Comment by snakefoot** [comment]
@Spamm3r  The problem is probably this line:

```xml
<include file="${basedir}\NLog.config"/>
```

There is currently no support for layout-renderers in the file-attribute. I guess one could make a PR, that borrows the logic from internalLogFile. Feel free to make a PR.

**Comment by Spamm3r** [comment]
So basically in my project right now I have two sub-projects. One is main app and second one is updater. Updater will be in directory with main app and NLog config for main app (without AutoReload and include parameter).  And I am getting these errors.

[ASILogError.txt](https://github.com/NLog/NLog/files/3691643/ASILogError.txt)
[NLogError.txt](https://github.com/NLog/NLog/files/3691644/NLogError.txt)

And when I try to run Updater without these parameters I am still getting exception. 
[ASILogError.txt](https://github.com/NLog/NLog/files/3691656/ASILogError.txt)

In both cases apps are working fine

**Comment by snakefoot** [comment]
Can only see one error and it has been resolved here: https://github.com/NLog/NLog/pull/3258

Does the error also occur with NLog ver. 4.6.7 ?

**Comment by Spamm3r** [comment]
On Tuesday I will update NLog and see if problem is resolved.
