### ISSUE TITLE
Improve Documentation for WhenRepeatedFilter

### ISSUE THREAD

**Issue by da3dsoul** [NLog/NLog#3615]
**NLog version**: 4.6.7

**Platform**: .net 4.7

**Current NLog config**

```xml
<targets>
      <target name="file" xsi:type="File" fileName="${basedir}/logs/${shortdate}.txt" layout="[${shortdate} ${date:format=HH\:mm\:ss\:fff}] ${level}|${stacktrace} ${message}" />
      <target name="console" xsi:type="ColoredConsole" layout="${date:format=HH\:mm\:ss}| --- ${message}" />
    </targets>
    <rules>
      <logger name="*" minlevel="Info" writeTo="file" />
      <logger name="*" minlevel="Trace" writeTo="console" />
    </rules>
```
```C#
            var target = (FileTarget) LogManager.Configuration?.FindTargetByName("file");
            if (target != null)
            {
                target.FileName = ServerSettings.ApplicationPath + "/logs/${shortdate}.log";
                var rule = LogManager.Configuration?.LoggingRules.FirstOrDefault(a => a.Targets.Contains(target));
                rule?.Filters.Add(
                new WhenRepeatedFilter
                {
                    Layout = "Layout", TimeoutSeconds = 10,
                    FilterCountMessageAppendFormat = "--------------- The previous message occurred {0} times ---------------",
                    Action = FilterResult.Ignore
                });
                LogManager.ReconfigExistingLoggers();
            }
            Enumerable.Range(0, 10).ForEach(a => logger.Info("This is a test to make sure that repeated log entries are grouped"));
```

Okay, I included the requested info, but this is less about NLog, and more about the Wiki.
As you can see, I've been working on adding a `WhenRepeatedFilter` to group messages. 

The documentation for the `Layout` property is non-existent on the page. It should at least be linked to wherever the documentation for what a `Layout` is is kept. It should also say what it does in this context, and why it is required, since it does say that it *is* required.

After playing around, I got a handle on `Action`, but the documentation could be better. In the context of the `WhenRepeatedFilter`, I gathered that `FilterResult.Ignore` is likely the most common use case. `IgnoreFinal` and `LogFinal` are still a mystery. It could be that I don't comprehend Final, as I have only used NLog for server systems, which are designed to very infrequently shut down. I would expect that you wouldn't want something to only trigger once in the lifecycle of the program, unless the filters have the ability to do fancy logic trees. Do they? I don't see it mentioned anywhere, if so.

Then there's `FilterCountMessageAppendFormat`. I can't find any useful info on this anywhere. StackOverflow yields a staggering 1 result, and the question only has the variable in a code snippet. What is it? How do you use it? Why do you use it?
I'm a smart cookie, so if needed, I dig through code and spend hours playing around with stuff...but I shouldn't need to.

The amount of prerequisite knowledge I needed to even find `WhenRepeatedFilter` was also far too high. The wiki needs to link around, not just show a long list of things that exist and expect that you know what to look for.

Thank you.

**Comment by snakefoot** [comment]
The wiki is open for editing:

https://github.com/NLog/NLog/wiki/WhenRepeated-Filter

Not sure I understand your example, since you can configure the whenRepeated-filter directly in xml:

```xml
<targets>
      <target name="file" xsi:type="File" fileName=${gdc:item=ApplicationPath:whenempty=${basedir}}/logs/${shortdate}.txt" layout="[${shortdate} ${date:format=HH\:mm\:ss\:fff}] ${level}|${stacktrace} ${message}" />
      <target name="console" xsi:type="ColoredConsole" layout="${date:format=HH\:mm\:ss}| --- ${message}" />
</targets>
<rules>
      <logger name="*" minlevel="Info" writeTo="file">
            <whenRepeated layout="${message}" timeoutSeconds="10" action="Ignore">
                   <FilterCountMessageAppendFormat>--------------- The previous message occurred {0} times ---------------</FilterCountMessageAppendFormat>
            </whenRepeated>
      </logger>
      <logger name="*" minlevel="Trace" writeTo="console" />
</rules>
```

Then you can configure GDC-ApplicationPath like this:

```c#
NLog.GlobalDiagnosticsContext.Set("ApplicationPath", ServerSettings.ApplicationPath);
```

**Comment by da3dsoul** [comment]
Yeah...my example doesn't work. I don't know if your snippet will yet. I'll try it.
Sure I'd be happy to help improve any project that I am familiar enough with to help. The issue is that the number of hours to get familiar with something that should be close to a one-liner is too high in the current state.
I don't know how they work. The final result is intended to look like
```
Blah blah message that is spammed from a repeat error in a loop
------- The previous message occurred 812 times ------
```

**Comment by snakefoot** [comment]
> Yeah...my example doesn't work. I don't know if your snippet will yet. I'll try it.

I have just merged your example with the wiki-page documentation. Didn't do anything magically.

**Comment by da3dsoul** [comment]
I see. Thanks for your help. If I sounded rude, that's more out of sleep deprivation and frustration. I apologize.

Finding a way to intelligently not log a repeated error is difficult in this case, as the iterable is thousands of commands to execute in a queue, they may not all be the same type, and hopefully the errors are in the single digits. There are situations where many occur and just spam the same messages for literal megabytes of useless log.

As you say, given effort and time, there is another solution on our end, but I'd prefer to spend it on actually fixing the errors, rather than making the log smaller.

This seemed like it should be simple do through NLog, as it's so robust. I'm frustrated that something that seems simple is giving me a headache.

This also seemed like something that people would try to do often, but it must not be.

**Comment by snakefoot** [comment]
NLog is opensource and made in people sparetime. Trying anticipate all future usecases and needs can be a daunting task.

Usually it is the other way around. People ask for how to do something specific (here as an issue or stackoverflow), and then code/documentation is adapted to match those needs when possible.

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, please let us know!
