### ISSUE TITLE
What version ...

### ISSUE THREAD

**Issue by MichaelLiss** [NLog/NLog#3617]
What version of NLOG do I need to get to run on .NET 4.6 ?

**Comment by MichaelLiss** [comment]
I think my question is pretty straight forward:
What version of NLOG do I need to get to run it on .NET 4.6 ?

**Comment by snakefoot** [comment]
Think you can use any version from NLog ver. 1.0 and forward. Ofcourse the [latest version](https://www.nuget.org/packages/NLog) is the best version :)

But I guess you are holding back information, that makes you think NLog will not work with NET4.6
