### ISSUE TITLE
Logs location overwritten by code still logging happening at config location.

### ISSUE THREAD

**Issue by nikhilagrawaldotnet** [NLog/NLog#3624]
NLog version - 4.4.3

Platform - .Net 4.5.2

Current NLog config - 

```xml
<nlog autoReload="true" xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <variable name="layout" value="${longdate}|${level:uppercase=true}|${threadid}|${logger}|${message}" />
  <variable name="logLocation" value="logs" />
  <targets async="true">
    <target name="debugger" xsi:type="Debugger" layout="${layout}" />
    <target name="console" xsi:type="Console" layout="${layout}" />
    <target name="logfile" 
            xsi:type="File" 
            fileName="${logLocation}\${processname}.log" 
            archiveFileName="${logLocation}\\${processname}.{###}.log" 
            archiveEvery="Day" 
            archiveAboveSize="2048000" 
            archiveNumbering="Rolling" 
            maxArchiveFiles="10" 
            concurrentWrites="false" 
            keepFileOpen="false" 
            layout="${layout}" />
  </targets>
  <rules>
    <logger name="*" minlevel="Info" writeTo="logfile" />
    <logger name="*" minlevel="Debug" writeTo="debugger" />
    <logger name="*" minlevel="Info" writeTo="console" />
  </rules>
</nlog>
```

Code to override location
```C#
LogManager.ReconfigExistingLoggers();
var target = (FileTarget)LogManager.Configuration.FindTargetByName<AsyncTargetWrapper>("logfile").WrappedTarget;
target.FileName = $@"..\..\..\..\logs\Foobar.log";
```

- What is the current result?
When application/service starts it writes to overwritten location, but sometimes (not sure of scenario - _maybe_ rollover) it start writing to config location.

- What is the expected result?
Logs should always be written to overwritten location.

- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
No

- Please post full exception details (message, stacktrace, inner exceptions)
No Exception

- Are there any workarounds? yes/no
Restart service/application.

- Is there a version in which it did work? 
No idea. This is the version we started with and sticking to.

- Can you help us by writing an unit test?
Unit tests won't help as it is an intermittent scenario.

**Comment by nikhilagrawaldotnet** [comment]
Openedon on SO - https://stackoverflow.com/questions/58365910/logs-location-overwritten-by-code-still-logging-happening-at-config-location

**Comment by 304NotModified** [comment]
answered on SO :)

**Comment by nikhilagrawaldotnet** [comment]
Thanks @304NotModified :)
