### ISSUE TITLE
Suppport for database logging in Xamarin.Forms

### ISSUE THREAD

**Issue by mooola** [NLog/NLog#3626]
I'd like to see support for database logging (sqlite in my case) in Xamarin.Forms.

Is it on the roadmap?

**Comment by 304NotModified** [comment]
Could you use. Net standard libraries in xamarin forms nowadays?

**Comment by mooola** [comment]
Not at the present time

**Comment by 304NotModified** [comment]
> Xamarin.Forms 2.4 allows Xamarin.Forms applications to target .NET Standard 2.0 by replacing the PCL with a .NET Standard 2.0 library. 

https://docs.microsoft.com/en-us/xamarin/xamarin-forms/internals/net-standard

Or am I missing something?

**Comment by mooola** [comment]
We currently use a Shared project, and are in the later stages of a release.  I don't think switching to netstandard would go over as much as I'd like to.

Can you tell me how I can get to the data from a custom layout renderer in a custom target?  I don't see it in LogEventInfo.  Is there some other way to get at that data?  TIA

**Comment by 304NotModified** [comment]
> Can you tell me how I can get to the data from a custom layout renderer in a custom target? I don't see it in LogEventInfo.

you could do in the custom target:


```c#
Layout layout = "${myCustomLayoutRenderer}";
var value = layout.Render(logEvent);

```

or

```c#
var renderer = new MyCustomLayoutRenderer();
var value = renderer.Render(logEvent);

```

**Comment by 304NotModified** [comment]
Example here:

https://github.com/304NotModified/NLog.Xamarin.DatabaseTarget

Not tested. Feel free to send a PR when there's a mistake!

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, please let us know!
