### ISSUE TITLE
Class name output as lambda_method in release mode

### ISSUE THREAD

**Issue by kmjones77** [NLog/NLog#3630]
**NLog version**: v4.6.7

**Platform**: .NET Core 2.2

**Current NLog config** (xml or C#, if relevant)
```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <targets>
    <target
        name="file-all"
        xsi:type="File"
        fileName="${basedir}/App_Data/Logs/all.txt"
        archiveFileName="${basedir}/App_Data/Logs/archives/all.{#}.txt"
        archiveEvery="Day"
        archiveNumbering="Rolling"
        maxArchiveFiles="120"
        layout="${date:format=yyyy-MM-dd HH\:mm\:ss}|${level:uppercase=true}|${logger}|${message}|${exception:format=tostring}"
        />
    <target
        name="file-debug"
        xsi:type="File"
        fileName="${basedir}/App_Data/Logs/debug.txt"
        archiveFileName="${basedir}/App_Data/Logs/archives/debug.{#}.txt"
        archiveEvery="Day"
        archiveNumbering="Rolling"
        maxArchiveFiles="120"
        layout="${date:format=yyyy-MM-dd HH\:mm\:ss}|${level:uppercase=true}|${logger}|${message}|${exception:format=tostring}"
        />
    <target
        name="file-errors"
        xsi:type="File"
        fileName="${basedir}/App_Data/Logs/errors.txt"
        archiveFileName="${basedir}/App_Data/Logs/archives/errors.{#}.txt"
        archiveEvery="Day"
        archiveNumbering="Rolling"
        maxArchiveFiles="120"
        layout="${date:format=yyyy-MM-dd HH\:mm\:ss}|${level:uppercase=true}|${logger}|${message}|${exception:format=tostring}"
        />
  </targets>
  <rules>
    <logger name="*" writeTo="file-all"/>

    <!--Skip non-critical Microsoft logs and so log only own logs-->
    <logger name="Microsoft.*" maxLevel="Info" final="true" />
    <logger name="*" writeTo="file-debug"/>
    <logger name="*" minlevel="Error" writeTo="file-errors"/>
  </rules>
</nlog>

```

- What is the current result?
I have a Controller class with a logger that outputs the class name fine in debug mode but in release mode the class name is outputted as lamba_method

- What is the expected result?
Class name should be output in release mode as normal

**Comment by snakefoot** [comment]
Thank you for showing the NLog.config. Could you also show an example of how/where you call `LogManager.GetCurrentClassLogger()` ?

It is recommended that you just have Logger as static readonly variable on the class.

**Comment by kmjones77** [comment]
The logger is declared like this. This is how I always use the logger. The only interesting thing in this class is that it has a base class that also has a logger instance, I dont know why this would affect it.

`private readonly NLog.ILogger _logx = NLog.LogManager.GetCurrentClassLogger();`

And then used like this:

`_logx.Debug("Some information here");`

**Comment by snakefoot** [comment]
Think you have to provide a small example project that reproduces the issue. Either as link to github-project or attached zip-file to this issue.


Sent from my Sony Xperia


---- Ken Jones wrote ----


The logger is declared like this. This is how I always use the logger. The only interesting thing in this class is that it has a base class that also has a logger instance, I dont know why this would affect it.

private readonly NLog.ILogger _logx = NLog.LogManager.GetCurrentClassLogger();

And then used like this:

_logx.Debug("Some information here");

**Comment by snakefoot** [comment]
@jlechem NLog ver. 4.6.8 has been released:

https://www.nuget.org/packages/NLog

Has some improvements to its GetCurrentClassLogger-lookup-logic

**Comment by snakefoot** [comment]
@kmjones77 NLog ver. 4.6.8 has been released:

https://www.nuget.org/packages/NLog

Has some improvements to its GetCurrentClassLogger-lookup-logic

**Comment by kmjones77** [comment]
OK thanks @snakefoot I'll check it out

**Comment by dawncold** [comment]
`static` works for me, but I don't know why, if anyone knows, please tell me, thanks!

**Comment by snakefoot** [comment]
Please create new issue instead of waking old issues that are closed. But happy everything is working for you.


Sent from my Sony Xperia


---- Zhen Tian wrote ----


static works for me, but I don't know why, if anyone knows, please tell me, thanks!
