### ISSUE TITLE
Getting stacktrace prefixed with <no type>.lambda_method

### ISSUE THREAD

**Issue by ernavjotsingh2** [NLog/NLog#364]
Hi,

I am using Nlog file target and layout is as follows-
  
<target name="file" xsi:type="File" fileName="C:\RxArchive\Log_${shortdate}.txt"
             layout="${windows-identity}  ||||  ${longdate:universalTime=true} ||||  ${level}  ||||  ${stacktrace} ||||  ${message}" />

When the i run my website locally, stacktrace works just fine but when I deploy my website on server and run website then each of the stacktrace is prefixed by 
"\<no type>.lambda_method" . 

for example-
NT AUTHORITY\SYSTEM  ||||  2014-06-13 05:20:56.2777 ||||  Info  ||||  \<no type>.lambda_method => ReportsController.ViewReports => Log.Info ||||  User has logged into the EPCS Reporting application.

Anyone have seen problem before.
Which setting am I missing here ? 

Thanks,
Navjot

**Comment by 304NotModified** [comment]
@ernavjotsingh2 if this is still a problem, please submit the requested info and re-open this issue.
