### ISSUE TITLE
${callsite} on async methods contains extraneous data

### ISSUE THREAD

**Issue by jlechem** [NLog/NLog#3643]
Hi! Thanks for reporting this feature/bug/question! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

QUESTIONS are preferred on StackOverflow. You could expect a faster response there (but do include all the info below). Use the tag "nlog" https://stackoverflow.com/questions/ask

For .NET Core users, please check the platform support: https://github.com/NLog/NLog/wiki/platform-support

**NLog version**: 4.6.7

**Platform**: .Net 4.7.2 and 4.8

**Current NLog config** (xml or C#, if relevant)

```     <nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <targets>
      <target name="logFile" xsi:type="File" fileName="logs/ivrrelaylog${date:format=yyyyMMdd_HHmm}.txt" layout="{&quot;AppID&quot;: &quot;${appsetting:item=appId:default=appId}&quot;, &quot;type&quot;: &quot;Application&quot;, &quot;action&quot;: &quot; ${callsite:cleanNamesOfAnonymousDelegates=true}&quot;, &quot;level&quot;: &quot;${uppercase:${level}}&quot;, &quot;environment&quot;: &quot;${appsetting:item=environment:default=Test}&quot;, &quot;sourceIP&quot;: &quot;${aspnet-request-ip}&quot;, &quot;timestamp&quot;: &quot;${date:format=yyyy-MM-ddTHH\:mm\:ss.fff}&quot;, &quot;message&quot;: &quot;${message}&quot;, &quot;application-name&quot;: &quot;IVR Relay Service&quot;}, Trace = ${stacktrace}" />
    </targets>
    <rules>
      <logger name="*" writeTo="logFile" />
    </rules>
  </nlog>
```

- What is the current result?
{"AppID": "APP01142", "type": "Application", "action": " IvrRelayService.Controllers.CpasController+<CpasSelect>d__3.MoveNext", "level": "INFO", "environment": "Localhost", "sourceIP": "::1", "timestamp": "2019-10-23T13:46:59.664", "message": "Leaving method CpasServiceCall().", "application-name": "IVR Relay Service"}, Trace = ExecutionContext.Run => ExecutionContext.RunInternal => <CpasSelect>d__3.MoveNext

Specifically the ${callsite:cleanNamesOfAnonymousDelegates=true} result
 IvrRelayService.Controllers.CpasController+<CpasSelect>d__3.MoveNext

I am injecting the logger into an asp.net controller using Autofac so I have an Interface of ILogger that gets set to a variable. The method call for the above log is this:

Logger.Info("Leaving method CpasServiceCall().");

- What is the expected result?
 IvrRelayService.Controllers.CpasController.CpasSelect

In a non async method if I call

Logger.Info("Leaving method BuildEncodedGetUrl().");

I get 

{"AppID": "APP01142", "type": "Application", "action": " IvrRelayService.Controllers.CpasController.BuildEncodedGetUrl", "level": "INFO", "environment": "Localhost", "sourceIP": "::1", "timestamp": "2019-10-23T13:46:57.855", "message": "Leaving method BuildEncodedGetUrl().", "application-name": "IVR Relay Service"}, Trace = AsyncTaskMethodBuilder`1.Start => <MakeCpasServiceCall>d__5.MoveNext => CpasController.BuildEncodedGetUrl

- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
No

- Please post full exception details (message, stacktrace, inner exceptions)
Trace = ExecutionContext.Run => ExecutionContext.RunInternal => d__3.MoveNext

From the ${stacktrace} where the oddness is happening

- Are there any workarounds? yes/no No
- Is there a version in which it did work? I am unaware
- Can you help us by writing an unit test?

**Comment by jlechem** [comment]
Originally posted here:

https://github.com/NLog/NLog/issues/1805

**Comment by snakefoot** [comment]
Could you show a layout-example where you are actually using `${callsite}` ?

What happens if you use `${callsite:cleanNamesOfAnonymousDelegates=true}` ? (Make sure the updated nlog.config is deployed when testin)

Could you provide a code-example showing where logger fails to capture callsite?

What happens if you downgrade from net48 to net472 ?

**Comment by jlechem** [comment]
Oh yeah I forgot I changed the layout due to the extraneous data, 

  <nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <targets>
      <target name="logFile" xsi:type="File" fileName="logs/ivrrelaylog${date:format=yyyyMMdd_HHmm}.txt" layout="{&quot;AppID&quot;: &quot;${appsetting:item=appId:default=appId}&quot;, &quot;type&quot;: &quot;Application&quot;, &quot;action&quot;: &quot;${callsite}&quot;, &quot;level&quot;: &quot;${uppercase:${level}}&quot;, &quot;environment&quot;: &quot;${appsetting:item=environment:default=Test}&quot;, &quot;sourceIP&quot;: &quot;${aspnet-request-ip}&quot;, &quot;timestamp&quot;: &quot;${date:format=yyyy-MM-ddTHH\:mm\:ss.fff}&quot;, &quot;message&quot;: &quot;${message}&quot;, &quot;application-name&quot;: &quot;IVR Relay Service&quot;}" />
    </targets>
    <rules>
      <logger name="*" writeTo="logFile" />
    </rules>


@snakefoot  Adding that attribute didn't do anything when I tried it.

**Comment by 304NotModified** [comment]
I'm curious to the results of ${stacktrace}. Could you please capture and paste that?

**Comment by jlechem** [comment]
Downgrading the .net version didn't change anything

...
{"AppID": "APP01142", "type": "Application", "action": "IvrRelayService.Controllers.CpasController+<CpasSelect>d__3.MoveNext", "level": "INFO", "environment": "Localhost", "sourceIP": "::1", "timestamp": "2019-10-23T11:41:03.974", "message": "Leaving method CpasServiceCall().", "application-name": "IVR Relay Service"} - Trace ExecutionContext.Run => ExecutionContext.RunInternal => <CpasSelect>d__3.MoveNext
...

...
  <nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <targets>
      <target name="logFile" xsi:type="File" fileName="logs/ivrrelaylog${date:format=yyyyMMdd_HHmm}.txt" layout="{&quot;AppID&quot;: &quot;${appsetting:item=appId:default=appId}&quot;, &quot;type&quot;: &quot;Application&quot;, &quot;action&quot;: &quot;${callsite}&quot;, &quot;level&quot;: &quot;${uppercase:${level}}&quot;, &quot;environment&quot;: &quot;${appsetting:item=environment:default=Test}&quot;, &quot;sourceIP&quot;: &quot;${aspnet-request-ip}&quot;, &quot;timestamp&quot;: &quot;${date:format=yyyy-MM-ddTHH\:mm\:ss.fff}&quot;, &quot;message&quot;: &quot;${message}&quot;, &quot;application-name&quot;: &quot;IVR Relay Service&quot;} - Trace ${stacktrace}"/>
    </targets>
    <rules>
      <logger name="*" writeTo="logFile"/>
    </rules>
  </nlog>
...

**Comment by snakefoot** [comment]
I know all our questions are really annoying But if you want help, then you need to help, or even better write an unit-test that shows the error.

> Could you provide a code-example showing where logger fails to capture callsite?

> I'm curious to the results of `${stacktrace}`. Could you please capture and paste that?

**Comment by jlechem** [comment]
I upgraded the original post with the stack trace and logger call, please note.

**Comment by snakefoot** [comment]
So the `${callsite}`:

`"action": "IvrRelayService.Controllers.CpasController+<CpasSelect>d__3.MoveNext"`

Comes from this `${stacktrace}`:

`- Trace ExecutionContext.Run => ExecutionContext.RunInternal => <CpasSelect>d__3.MoveNext`

Can you show the code-context that generated the above callstack? The code calling:

`logger.Info("Leaving method CpasServiceCall().");`

Any reason why you insist on not using `${callsite=cleanNamesOfAnonymousDelegates=true}` in your examples ?

**Comment by jlechem** [comment]
Cleaned up the original post so they are all related.

**Comment by snakefoot** [comment]
Not sure I understand. Your code-example for how to reproduce. There is only a single line, which is the one I guessed. It is not enough need more context around the logging-operation.

Btw. what happens if you do this: `${callsite:cleanNamesOfAnonymousDelegates=true:cleanNamesOfAnonymousDelegates=true}`

**Comment by jlechem** [comment]
I have tried both and the result is always the same. What more context do you need on the logging? 

I make any call in an asnyc method and get this formatted result

Logger.Info("Leaving method CpasServiceCall().");

{"AppID": "APP01142", "type": "Application", "action": " IvrRelayService.Controllers.CpasController+d__3.MoveNext", "level": "INFO", "environment": "Localhost", "sourceIP": "::1", "timestamp": "2019-10-23T13:46:59.664", "message": "Leaving method CpasServiceCall().", "application-name": "IVR Relay Service"}, Trace = ExecutionContext.Run => ExecutionContext.RunInternal => d__3.MoveNext

I do the same thing in a non async method and I get this:

Logger.Info("Leaving method BuildEncodedGetUrl().");

{"AppID": "APP01142", "type": "Application", "action": " IvrRelayService.Controllers.CpasController.BuildEncodedGetUrl", "level": "INFO", "environment": "Localhost", "sourceIP": "::1", "timestamp": "2019-10-23T13:46:57.855", "message": "Leaving method BuildEncodedGetUrl().", "application-name": "IVR Relay Service"}, Trace = AsyncTaskMethodBuilder`1.Start => d__5.MoveNext => CpasController.BuildEncodedGetUrl

**Comment by snakefoot** [comment]
Starting to become a long journey. But a code example showing context is usually more than one line. So I was guessing to see some code that included names like `CpasController`, `BuildEncodedGetUrl`, etc.

**Comment by 304NotModified** [comment]
We like to fix this, but I think (indeed) we could use a repo case (zip, github repo or unit test). @Jeinhaus could you please help us with that?

**Comment by snakefoot** [comment]
@jlechem NLog ver. 4.6.8 has been released:

https://www.nuget.org/packages/NLog

Has some improvements to its CallSite-lookup-logic
