### ISSUE TITLE
New features added without incrementing minor version number

### ISSUE THREAD

**Issue by HolisticDeveloper** [NLog/NLog#3645]
**NLog version**: 4.6.2

**Platform**: .NET Core 2

**Current NLog config**: N/A

I have NLog 4.6.2 in a project, and NuGet tells me there is a newer version available. While checking the [CHANGELOG](https://github.com/NLog/NLog/blob/master/CHANGELOG.md), I see that all the 4.6.x patch releases since then also include new features and improvements. Shouldn't the minor version be incremented for these, and not the patch? The current pattern makes it more challenging to assess the risk of updating.

I have read in a few other issues that the team takes SemVer very seriously so this has left me a bit puzzled.

**Comment by 304NotModified** [comment]
hey! You're right that updating the minor version would be better.

Currently we also do small features in patch releases. Those are features with a really small impact on current code.
Note: I think we're doing that from version 4 (2015).

Unfortunately I think this is a result of open source contributions. Pull requests are submitted unplanned and so we get most of the time a feature change before a bugfix.  So to keep things we are not removing the feature before doing a patch release.

I have to think if we need to change it. If we would do that, then that will having the following consequences:

- We will do a lot more minor releases
- We will delay small features because of patch releases which only contains bugfixes.

**Comment by snakefoot** [comment]
Must admit I like the goal of not having PullRequest resting for a very long time. So when community offers a new feature, then they should not be punished to constantly handling merge-issues while waiting for the next minor-version.

Also don't think the NLog-team is a large enough to maintain multiple release-branches and dev-branches. Already enough confusion by maintaining a dev-branch and master-branch.

To me the semver for minor-version is mostly about:
- Not making existing classes as obsolete and generate build-versions.
- Not removing existing classes and generate build-errors
- Not changing existing interfaces and generate runtime-errors / build-errors.
- Not changing existing methods and generate runtime-errors / build-errors.

So I prefer that we stay away from bumping minor-version unless marking things obsolete, or introducing major features with new interface or new building blocks.

**Comment by HolisticDeveloper** [comment]
A good discussion! It's a nice "problem" to have such an active community making PRs!

SemVer clearly states:
> Minor version Y (x.Y.z | x > 0) MUST be incremented if new, backwards compatible functionality is introduced to the public API.

I think not getting any "real" patch versions wouldn't really make it any different than the current process -- as mentioned there have been very few fix-only releases. But bumping the minor version would be more reflective of the state of the project and provides more clarity.

 I understand, however, that your current overhead for releasing minor version updates may not make that practical.

**Comment by 304NotModified** [comment]
> SemVer clearly states:
> 
> > Minor version Y (x.Y.z | x > 0) MUST be incremented if new, backwards compatible functionality is introduced to the public API.

Yes, I saw it. 

I'm thinking to remove the semver badge and update the text. 

For NLog 5, I think creating more minor versions is feasible. But we NLog 4 we keep the process now as is.

**Comment by HolisticDeveloper** [comment]
Obviously it's up to the NLog team on how to proceed. But for now at least I have more clarity on the current practice, which is what I was initially looking for. Feel free to close this issue unless you want to use it to track some action item.
