### ISSUE TITLE
bug in archiveFileName when skipping days 

### ISSUE THREAD

**Issue by rbouny** [NLog/NLog#367]
I am using 'archiveNumbering=Date',
with 'archiveFileName="{#}.txt"'

I used my soft on 11/06.
I do not use it on 12/06
I use it again today, 13/06.

the archive file name is "2014-06-12" whereas I would like to have "2014-06-11"

**Comment by ilya-g** [comment]
@Xharze, @cvanbergen According to issues #580 and #646, and the first comment in this issue, people do expect acrhived log file to have the same date in the filename as the date of events logged in that file.

**Comment by 304NotModified** [comment]
@ilya-g I think that's also the most logical

**Comment by 304NotModified** [comment]
I think it should be configurable.  Would be nice if we could do that in 4.0

**Comment by 304NotModified** [comment]
same issue: https://github.com/NLog/NLog/issues/720
