### ISSUE TITLE
Skip auto-loading and auto-scanning of external assemblies by default

### ISSUE THREAD

**Issue by snakefoot** [NLog/NLog#3674]
This for NLog 5.0

Auto-loading works extremely bad on NetCore (the future) and the auto-loading gives a performance hit and probably also a security-issue (loading rogue assemblies). When used in Azure functions, then any reduction in startup time is extremely important.

Maybe extract the auto-loading logic into its own assembly. So one has to explicit call it upfront to activate it (If still want it on old platforms)

**Comment by 304NotModified** [comment]
@snakefoot could you assign milestones and add labels?

**Comment by 304NotModified** [comment]
> Maybe extract the auto-loading logic into its own assembly. So one has to explicit call it upfront to activate it (If still want it on old platforms)

Does this mean, in a separate package?

**Comment by snakefoot** [comment]
> Does this mean, in a separate package?

Just me dreaming of NLog-core without knowledge about files/assemblies etc. But I think the obvious path is to add a method in NLog 4.7 to skip/enable assembly-autoloading. And then make it default in NLog 5.0 to skip assembly-autoloading.

**Comment by snakefoot** [comment]
Example of someone using NLog as attack vector for code-injection:

https://github.com/sailro/EscapeFromTarkov-Trainer/blob/master/README.md

**Comment by 304NotModified** [comment]
Ok let's do this. Maybe totally remove auto loading, it doesn't work well for net core anyway.

**Comment by snakefoot** [comment]
@304NotModified You have already decided with #3798 :)

**Comment by 304NotModified** [comment]
Ow then is this a duplicate? ;)

**Comment by snakefoot** [comment]
Think it could be a good idea to remove the autoloading completely. Maybe together with implementing #2944 (Skipping the need to update `<extensions>` to make use of a custom target).

**Comment by 304NotModified** [comment]
I'm doubting if #2944 hasnt the same attack issue.

**Comment by snakefoot** [comment]
> I'm doubting if #2944 hasnt the same attack issue.

Anyone that can modify the NLog.config and update `<extensions>` has the ability to force NLog to load an assembly. 

Which is why I also write that the posted approach is very naive, and they could have done it without modifying NLog.config at all.

Are you suggesting to remove all support for loading NLog-extensions along with all 3rd-party targets?
