### ISSUE TITLE
Support DI and DI containers 

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#3675]
todo list

- [X] Register types with custom creator - https://github.com/NLog/NLog/pull/3616
- [X] Resolve NLog targets, layouts and layout renderers - yes it resolved all classes.
- [ ] Register all NLog targets, layouts and layout renderers ? For external libs
- [ ] Register types with interface, without static
- [x] Constructor injection - #3672
- [x] Easy resolve without Constructor injection - #3666
- [X] Support createIntance old style and make obsolete
- [ ] Obsolete ConfigurationItemCreator
- [ ] Optimize static registers (no lambda)
- [ ] Optimize  constructors precompile / cache
- [ ] Optimize  constructors precalculate  / find upfront
- [ ] Test / make package with another library (MS DI? - Not Unity!)
- [ ] Work correctly with NLog.Extensions.Logging, fix the issue that in the in main the injectables aren't ready (as configureService is later on)
- [ ] resolve nested statics dependencies lazy with storage (when using nested static resolves)

replaces https://github.com/NLog/NLog/issues/3362

working branch: https://github.com/NLog/NLog/tree/DI-Resolving

**Comment by 304NotModified** [comment]
@snakefoot you're working on 'Optimize constructors - cache and precalculate on register', isn't?

**Comment by snakefoot** [comment]
Working on injecting IValueFormatter into the LogEventInfo.MessageFormatter

**Comment by snakefoot** [comment]
Oops pushed directly to "DI-Resolving" without creating a pull-request first.

**Comment by snakefoot** [comment]
Please review this commit:

https://github.com/NLog/NLog/commit/05fec46a02ab7feaec753a7ce5cd93cd2cb6a88e

**Comment by snakefoot** [comment]
We should mark ConfigurationItemFactory.Default as obsolete in NLog 4.7 and introduce extension-methods to perform all config.

**Comment by 304NotModified** [comment]
working on performance/cache. Not sure if I finish it today.

**Comment by 304NotModified** [comment]
> Oops pushed directly to "DI-Resolving" without creating a pull-request first.

I prefer next time a git reset :angel:

**Comment by snakefoot** [comment]
This static property should be marked as obsolete:

> ConfigurationItemFactory.Default

Beside the obvious usages for static registration methods, then there are missing cleanup in #3831:

- SimpleLayout - Parsing layout should happen through extension-method on LogFactory (that uses LogFactory ServiceRepository)
  - Remove the setter on the Text-property
  - Remove member-variable `ConfigurationItemFactory _configurationItemFactory`
  - Layout.FromString should follow the same route.
  - How to handle conversion-operator from string to SimpleLayout? (Can use layout-renders that wants to resolve service).
- ConditionParser - Parsing condition methods should happen through extension-method on LogFactory (that uses LogFactory ServiceRepository)
- PerformanceCounterTarget has an Instance-property that must be changed into a standard Layout.
- EnvironmentLayoutRenderer has GetSimpleLayout()-method that needs to be updated.

**Comment by 304NotModified** [comment]
Fixed by https://github.com/NLog/NLog/pull/3831
