### ISSUE TITLE
ColoredConsole target not colored in Visual Studio 2019/Asp.Net Core 3

### ISSUE THREAD

**Issue by Land3r** [NLog/NLog#3682]
While settings up Nlog for a new asp.net core 3 project, i tried to use the ColoredConsole target but couldn't get any coloring working in Visual Studio Community 2019.

Has anyone ever got it working ?

**NLog version**: 4.6.8
**NLog.Web.AspNetCore version**: 4.9.0

**Platform**: Asp.NET Core 3 on Windows 10, using Visual studio 2019 Community edition and IISExpress as a webserver

**Current NLog config** (xml or C#, if relevant)

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      throwExceptions="true"
      internalLogLevel="Info"
      internalLogFile="c:\temp\internal-nlog.txt">

  <!-- enable asp.net core layout renderers -->
  <extensions>
    <add assembly="NLog.Web.AspNetCore"/>
  </extensions>

  <!-- the targets to write to -->
  <targets>
    <target xsi:type="ColoredConsole"
          name="Console"
          layout="${longdate}|${level:uppercase=true}|${logger}|${message}"
          useDefaultRowHighlightingRules="true"
          enableAnsiOutput="false"
          DetectOutputRedirected="false"/>
  </targets>

  <!-- rules to map from logger name to target -->
  <rules>
    <logger name="*" minlevel="Trace" writeTo="Console" />
  </rules>
</nlog>

```

- What is the current result?
In the Output > [Name of the project] - ASP.Net Core Web Server window, the ColoredConsole target should write logs doesn't use coloring.
![image](https://user-images.githubusercontent.com/22073877/68908322-34eb5100-074b-11ea-9569-5c5bb60e259d.png)

- What is the expected result?
In the Output > [Name of the project] - ASP.Net Core Web Server window, the ColoredConsole target should write logs with colors.

- Please post full exception details (message, stacktrace, inner exceptions)
My log code in a WebAPI controller : 
![image](https://user-images.githubusercontent.com/22073877/68908134-9fe85800-074a-11ea-985f-39326997a71d.png)

- Are there any workarounds? **YES**
This bug occurs only in the Output window of visual studio.
By Default on windows, IISExpress is selected as the default engine for running asp.net core project : 
![image](https://user-images.githubusercontent.com/22073877/68908420-84318180-074b-11ea-9cbc-1ca0044cc9d1.png)
If you change target and switch it the the project name (i.e 
![image](https://user-images.githubusercontent.com/22073877/68908451-9d3a3280-074b-11ea-9f77-f602b4d39225.png)), a new terminal window is spawned and the program output is redirected to that terminal.
Result is 
![image](https://user-images.githubusercontent.com/22073877/68908569-091c9b00-074c-11ea-8a03-f7d9da1941f4.png) and coloring is applied.

Has anyone got it working in the Output window of Visual Studio ?

**Comment by snakefoot** [comment]
Think the Visual Studio "Output Window" is not a real console window. It just displays the console output from the application.

Try changing the NLog console-Layout to begin with (Putting `${level}` first, and remember the colon):
- "Error: " - for errors
- "Warning: " - for warnings:

https://stackoverflow.com/a/54004318/193178

**Comment by 304NotModified** [comment]
@snakefoot maybe we could add an option to prefix those levels,

e.g.

visualStudioOutputColors=true.

or do you think that's to specific? Doubt here.

**Comment by snakefoot** [comment]
If you know how to implement that logic, then please. You need to navigate into the Visual Studio Application and find the output-window-handle and then modify the window-canvas.

Like I said Visual Studio doesn't have a console-window. It just pipes the output into a normal window with its own rules.

**Comment by 304NotModified** [comment]
Added, feel free to edit:

https://github.com/NLog/NLog/wiki/ColoredConsole-target#visual-studio-output-window

**Comment by snakefoot** [comment]
@Land3r Have your question been answered?

**Comment by Land3r** [comment]
Yes, i also think that this didn't require any additional source code, an appendix in the wiki is all that is required :)

I ended up using a regular console with the VsColorOutpu Visual studio extension.

Thanks a lot
