### ISSUE TITLE
maxarchivefiles at runtime???

### ISSUE THREAD

**Issue by AlexisChung** [NLog/NLog#3696]
Hi! i set maxarchivefiles for one day, and it works when i execute application every time.
but if i didn't shutdown application and the next day the old Log file still exist.
so is there any way that i can delete old Log file at runtime???

**NLog version**: (e.g. 4.6.8)
**Platform**:  .Net 4.0

**Current NLog config** 
```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true">

  <targets async="true">
    <target name="TraceTarget" xsi:type="File"
            layout="${level:uppercase=true:padding=-5} ${date:format=yyyy\-MM\-dd\ HH\:mm\:ss\.fff} - ${message}"
            fileName="${basedir}/Log/${date:yyyyMMdd}_Trace.txt"
            maxarchivefiles="1"
            />
  </targets>

  <rules>
    <logger ruleName="Trace" name="Trace" minlevel="Debug" writeTo="TraceTarget" />
  </rules>
</nlog>
```
- What is the current result?
   i set maxarchivefiles for one day,and the next day the old Log file still exist.
- What is the expected result?
  I would expect delete old Log file at runtime.
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
  Yes
- Please post full exception details (message, stacktrace, inner exceptions)
  None
- Are there any workarounds?
  No
- Is there a version in which it did work? 
  Don't think so
- Can you help us by writing an unit test?
  Sorry, I don't know how to writing an unit test

**Comment by 304NotModified** [comment]
Hi, Please fill in the template.

**Comment by snakefoot** [comment]
Maybe try adding `archiveOldFileOnStartup="true"`. See also:

https://github.com/NLog/NLog/wiki/File-target

**Comment by AlexisChung** [comment]
> Maybe try adding `archiveOldFileOnStartup="true"`. See also:
> 
> https://github.com/NLog/NLog/wiki/File-target

i did try that, but it's not working either.

**Comment by snakefoot** [comment]
Could you add the internal-log-ouput on debug-level where `archiveOldFileOnStartup="true"` is configured, and it fails to cleanup the log-file from last run?
