### ISSUE TITLE
Only store 2 days nearest log

### ISSUE THREAD

**Issue by dtnguyen1316** [NLog/NLog#3697]
![nlog](https://user-images.githubusercontent.com/32295626/69217791-fec22d00-0ba1-11ea-80cc-a2a77ed86cb8.PNG)

This is my config to .Net Project.
The log only stored 2 days nearest.
Example in 2 days : 11/18/2019 and 11/19/2019, 2 log  files will be created and stored. But in 11/20/2019 when I do somthing , The log file of  11/18/2019 will be replaced by log file of  11/20/2019.

Can you find to me what wrong in my config, I also used maxArchiveFiles="10" but it not working.
I looking forward to receive your response.
Thanks a lot.

**Comment by 304NotModified** [comment]
Hi, Please fill in the template.
