### ISSUE TITLE
When is flush needed

### ISSUE THREAD

**Issue by wehadfun** [NLog/NLog#3716]
Can I get a code example that shows something not working and flushing fixing it?

I am trying to get an example of when and why flushing is needed

**Comment by snakefoot** [comment]
You can read about flushing here:

https://github.com/NLog/NLog/wiki/Tutorial#5-remember-to-flush

If you are using AsyncWrapper / async="true" / network-target / webservice-target then you should always flush.

If using file-target / console-target then it is not always so important.
