### ISSUE TITLE
UseNLog vs AddNLog and asp.net core layout renderers

### ISSUE THREAD

**Issue by wehadfun** [NLog/NLog#3717]
1. When should UseNLog be used vs AddNLog
2. When I use AddNLog some of the ASP.net core layout renderers do not work for example ${aspnet-request-url}

**Comment by wehadfun** [comment]
Does this mean that they will work the same in a new version

https://github.com/NLog/NLog.Web/issues/499

**Comment by snakefoot** [comment]
I have tried to fix so both AddNLog and UseNLog from NLog.Web.AspNetCore will make `${aspnet-request-url}` work.

If using AddNLog from NLog.Extension.Logging then layoutrenderers from NLog.Web.AspNetCore-package will not work.

**Comment by 304NotModified** [comment]
To make things more clear:

- AddNLog is for ASP.NET Core 1, build for ` Configure(IApplicationBuilder app, ...)`
- UseNLog is the new pattern for ASP.NET Core 2 and 3, build for `IWebHostBuilder`
