### ISSUE TITLE
Structured logging and numeric parameters

### ISSUE THREAD

**Issue by TimmVonPuttkamer** [NLog/NLog#3727]
I am using the JsonLayout to log messages to the console and I want to output the raw message as well as all parameters separately, I turned on includeAllProperties for this.

If I have a call like
```
logger.Info("test {name}, {password}", "some value", "some password");
```

The output is as expected:
```
... "message":"test \"some value\", \"some password\"","raw_message":"test {name}, {password}","properties":{ "name": "some value", "password": "some password" } ...
```

However, if I have a call like
```
logger.Info("test {0}, {1}", "some value", "some password");
```
the output is currently (notice that properties are empty)
```
"message":"test some value, some password","raw_message":"test {0}, {1}","properties":{  }}
```

I would have expected that the properties field contains the numeric/unnamed properties that are referenced in the raw message. 
Is this behavior as designed? Is there another configuration option I have missed?

**Comment by snakefoot** [comment]
There is no currently no features for adding positional parameters (`{0}`, `{1}`, etc.) to the output.

Any reason why you want to do this, and not just write `${message}` and `${message:raw=true}` ? (Not like it is easy search and filter using `{0}`, `{1}`, etc.) 

Think `NLog.StructuredLogging.Json` has the ability to include the positional parameters (See `StructuredLoggingLayoutRenderer` aka `structuredlogging.json`):

https://github.com/justeat/NLog.StructuredLogging.Json

Of course PullRequest are welcome if you want to introduce a new option like `IncludeAllParameters`. But will probably a smart behavior so when combined with `IncludeAllProperties` then it will only output when no named properties are found. Guess the option-name should reflect this behavior, so maybe  `IncludeIndexParameters` or `IncludePositionalParameters` is a better description.

**Comment by 304NotModified** [comment]
FYI:

> Templates that use numeric property names like {0} and {1} exclusively imply that arguments to the template are captured by numeric index

from: https://messagetemplates.org/

**Comment by snakefoot** [comment]
Closing this question as answered. Please re-open if not
