### ISSUE TITLE
Did not work in Net Core3.1 PublishSingleFile mode

### ISSUE THREAD

**Issue by vl00** [NLog/NLog#3738]
It work well using 'dotnet publish'. But I publish using 'dotnet publish /p:PublishSingleFile=true', I found it has no logs.

**Comment by 304NotModified** [comment]
See https://github.com/NLog/NLog/issues/3517

ergo: use `${basedir:fixtempdir=true}` and NLog 4.6.8+

**Comment by vl00** [comment]
thank's for 304NotModified
I change the path in the nlog.config and it work .

**Comment by 304NotModified** [comment]
great! :)

**Comment by longskikondi** [comment]
@304NotModified  
hi, I get this issue as well 
and my Nlog 4.6.8 :
```
<target xsi:type="File" name="f1" fileName="${basedir:fixtempdir=true}/../logs/Normal/${shortdate}.txt"
           layout="${longdate} ${newline} ${uppercase:${level}} ${message} ${newline}" />
```

but it is not work in linux service

**Comment by snakefoot** [comment]
@longskikondi Please create new issue and fill out the template: https://github.com/NLog/NLog/issues/new/choose

Think the most important part is to provide the output from the InternalLogger. You need to provide the details of where Microsoft have decided to handle unzipping of single-file-publish-app on Linux (On Windows they used the temporary directory. Maybe another hack is used on Linux).

Please investigate yourself and if you find the issue, and can see NLog could better handle single-file-publish-app on Linux, then please create a pull-request.
