### ISSUE TITLE
Archived file size exceeds the specified size, archiveAboveSize

### ISSUE THREAD

**Issue by PingPongSet** [NLog/NLog#3756]
I have the setting below:

 ```
<target name="asyncFile" xsi:type="AsyncWrapper" queueLimit="10000" overflowAction="Block">
      <target xsi:type="File"
                fileName="/storage/sdcard0/com.my.app/Logs/${shortdate}.log"
                archiveFileName="/storage/sdcard0/com.my.app/Logs/archived.{#}.log"
                maxArchiveFiles="5"
                archiveDateFormat="yyyy-MM-dd"
                archiveAboveSize="1048576"
                archiveEvery="Day"
                archiveNumbering="DateAndSequence"
                concurrentWrites="true"
                keepFileOpen="false">
        <layout xsi:type="JsonLayout" includeAllProperties="true" excludeProperties="Comma-separated list (string)">
          <attribute name="time" layout="${longdate}" />
          <attribute name="level" layout="${level:upperCase=true}"/>
          <attribute name="message" layout="${message}" />
          <attribute name="exception" layout="${exception}" />
          <attribute name="threadid" layout="${threadid}" />
        </layout>
      </target>
    </target>

```
Expected behaviours:
No more than 5 archived files are generated, and each has a maximum size of 1MB.
```
archived.1.log
archived.2.log
archived.3.log
archived.4.log
archived.5.log
```

Actual behaviours:
One archived file has more 40 MB

Any idea?

**Comment by tholesen** [comment]
I have experienced this too and it's a major issue. I'm using version 4.5.8 on .net 4.6 and have planned to upgrade as an attempt to fix it.
@PingPongSet Which version are you running?

**Comment by PingPongSet** [comment]
Please see this, it might fix it.

**Comment by snakefoot** [comment]
See also: https://stackoverflow.com/a/59658486/193178

**Comment by snakefoot** [comment]
See also: #3661 (Issue on Xamarin Android Platform)

**Comment by PingPongSet** [comment]
> 
> 
> I have experienced this too and it's a major issue. I'm using version 4.5.8 with .net 4.6 on Windows Server 2016 and have planned to upgrade as an attempt to fix it.
> @PingPongSet Which version are you running?

Please see below, it might work.
https://stackoverflow.com/questions/59655035/archived-file-size-exceeds-the-specified-size-archiveabovesize-with-nlog/59658486#59658486

**Comment by snakefoot** [comment]
Closing this question as resolved. Please mark the Stackoverflow-question as answered.
