### ISSUE TITLE
MessageBox Target fails if message written while splashscreen active

### ISSUE THREAD

**Issue by EvilMav** [NLog/NLog#376]
In a WPF project: (.NET 4.0, NLog 3.0.0)

- Set an Image in project as a Splash-Screen
- Provide a messageBox target
- Log a message while in App constructor

MessageBox blinks and then disappears together with the Splash-Screen without giving the user a chance to read the message. App hangs, MainWindow never opens.

**Comment by 304NotModified** [comment]
Feel free to reopen when we have more info.
