### ISSUE TITLE
oooo，from version4.6.7 to 4.6.8 ，print log will be very slow！！！！

### ISSUE THREAD

**Issue by jol5** [NLog/NLog#3760]
in order to print server ip，i try to upgrade version from 4.6.7 to 4.6.8. however i found console logger output to be very slow；
so，i can only roll back...

**Comment by snakefoot** [comment]
Can you give an example of your `Nlog.config` ?

Make sure to use `${local-ip:cachedSeconds=60}` or else it is going to be very slow.

**Comment by jol5** [comment]
> Can you give an example of your `Nlog.config` ? (Fill out the [template](https://github.com/NLog/NLog/issues/new?template=bug_report.md))
> 
> Make sure to use `${local-ip:cachedSeconds=60}` or else it is going to be very slow.

on yeah! thanks! i lost it: ${local-ip:cachedSeconds=60}

**Comment by snakefoot** [comment]
Updated the wiki for you:

https://github.com/NLog/NLog/wiki/Local-IP-Address-Layout-Renderer
