### ISSUE TITLE
Include configfiles method missing in code behind

### ISSUE THREAD

**Issue by dojo90** [NLog/NLog#3768]
I have a `nlog.config` file with the following entry:

```xml
<include file="${basedir}/ActiveConfig/NLog/*.config"/>
```

But I want to solve this via code behind and have not found a method to do so.

```csharp
LogManager.LoadConfiguration()
``` 
is overwriting my existing configuration.

Did I miss something?

**Comment by snakefoot** [comment]
See also: https://stackoverflow.com/questions/59843896/how-to-include-nlog-config-files-in-code-behind

**Comment by 304NotModified** [comment]
answered at https://stackoverflow.com/questions/59843896/how-to-include-nlog-config-files-in-code-behind

I assume your question has been answered, if not, please let us know!

**Comment by dojo90** [comment]
**Please reopen the issue.**

The answer to SO is unfortunately not correct, otherwise I would have accepted it already.

**First solution:**
If I load all files in a `MemoyStream` I lose the reload function (in the sub files) which I urgently need.

**Second solution:**
`XmlLoggingConfiguration` needs a filename for the "main" config file in the default constructor. This does not exist, only the sub files.

---

I have `n` `fooLibraries` and each of it got an own `Config/NLog/FooLibrary.config` file included. This file is auto generated during the `ci build`.
The tactical background. By default, all warnings/infos/errors are displayed. If we want to take a closer look at a specific namespace of one of our modules, we just have to uncomment the corresponding line.

Sample:

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true">
  <rules>
    <!--Sentinel-->
    <!--<logger name="Haprotec.Opc"            writeTo="sentinel" minlevel="Trace" maxlevel="Debug"/>-->
    <!--<logger name="Haprotec.Opc.Extensions" writeTo="sentinel" minlevel="Trace" maxlevel="Debug"/>-->
    <!--<logger name="Haprotec.Opc.Sessions"   writeTo="sentinel" minlevel="Trace" maxlevel="Debug"/>-->
    <!--<logger name="Haprotec.Opc.Ua"         writeTo="sentinel" minlevel="Trace" maxlevel="Debug"/>-->
    <!--<logger name="Haprotec.Opc.Udt"        writeTo="sentinel" minlevel="Trace" maxlevel="Debug"/>-->

    <!--File-->
    <!--<logger name="Haprotec.Opc"            writeTo="file" minlevel="Trace" maxlevel="Debug"/>-->
    <!--<logger name="Haprotec.Opc.Extensions" writeTo="file" minlevel="Trace" maxlevel="Debug"/>-->
    <!--<logger name="Haprotec.Opc.Sessions"   writeTo="file" minlevel="Trace" maxlevel="Debug"/>-->
    <!--<logger name="Haprotec.Opc.Ua"         writeTo="file" minlevel="Trace" maxlevel="Debug"/>-->
    <!--<logger name="Haprotec.Opc.Udt"        writeTo="file" minlevel="Trace" maxlevel="Debug"/>-->

    <!--Cache-->
    <!--<logger name="Haprotec.Opc"            writeTo="cache" minlevel="Trace" maxlevel="Debug"/>-->
    <!--<logger name="Haprotec.Opc.Extensions" writeTo="cache" minlevel="Trace" maxlevel="Debug"/>-->
    <!--<logger name="Haprotec.Opc.Sessions"   writeTo="cache" minlevel="Trace" maxlevel="Debug"/>-->
    <!--<logger name="Haprotec.Opc.Ua"         writeTo="cache" minlevel="Trace" maxlevel="Debug"/>-->
    <!--<logger name="Haprotec.Opc.Udt"        writeTo="cache" minlevel="Trace" maxlevel="Debug"/>-->
  </rules>
</nlog>
```

By default we have a `nlog.config` with the following entry (and `targets` and `loggingRules`):
```xml
<include file="${basedir}/ActiveConfig/NLog/*.config"/>
```

Sometimes this file does not exist, but only the sub files. Our `Targets` and `LoggingRules` are created in code. **In this case I would now need the possibility to add the files in code behind.**

**Comment by 304NotModified** [comment]
Reopend, but I guess we could continue here: https://github.com/NLog/NLog/issues/3799 ;)

**Comment by 304NotModified** [comment]
> Sometimes this file does not exist,

I don't get this. If it don't exist, how should be fine the "sub files"?

**Comment by 304NotModified** [comment]
anyway, what about this?

```c#
var config =  XmlLoggingConfiguration.CreateFromXmlString("<include file='${basedir}/ActiveConfig/NLog/*.config' />");
LogManager.Configuration = config;

```

**Comment by dojo90** [comment]
> 
> 
> > Sometimes this file does not exist,
> 
> I don't get this. If it don't exist, how should be fine the "sub files"?

We are developing many apps. For this circumstance we have a logic to setup `NLog` by code behind (convience targets and rules) without defining a `nlog.config`. This is also extremely useful for `unit tests`. The subfiles are added by dependency libraries automatically. If we deploy the application to our customer, we have a `nlog.config` and don't need the "code behind logic" anymore.

> 
> 
> anyway, what about this?
> 
> ```cs
> var config =  XmlLoggingConfiguration.CreateFromXmlString("<include file='${basedir}/ActiveConfig/NLog/*.config' />");
> LogManager.Configuration = config;
> ```
That would be great! Sadly this method is not available on `netstandart2.0`/`netstandart2.1`. I'm currently experimenting to include an empty xml file (with the include call) as resource in the library and then load it. But if we could add the above method to `netstandart`, this would be much more elegant.

**Comment by 304NotModified** [comment]
It's available for net standard. Please update NLog.

**Comment by 304NotModified** [comment]
See https://github.com/NLog/NLog/blob/v4.6.8/src/NLog/Config/XmlLoggingConfiguration.cs#L215

**Comment by dojo90** [comment]
That was my fault! Of course the method is there, I just forgot to update! 🤦‍♂️

So it seems to work as expected except for this bug: https://github.com/NLog/NLog/issues/3803
