### ISSUE TITLE
<include file> rules are ignored 

### ISSUE THREAD

**Issue by lobster2012-user** [NLog/NLog#3775]
Hi!
When other files are included, rules are ignored in them. Is this done on purpose?

**Comment by snakefoot** [comment]
Bug reports are so much easier with a reproachable example. Is this done on purpose? :)

**Comment by lobster2012-user** [comment]
@snakefoot 
Thank you for answer. 
Before my message, it was impossible to configure correctly, I received a message - target skipping. Now it worked out.

**Comment by snakefoot** [comment]
You are very welcome to make a PR to improve the error messages for future users.
