### ISSUE TITLE
Replace System.Data.SqlClient dependency with Microsoft.Data.SqlClient

### ISSUE THREAD

**Issue by MartinStrbak** [NLog/NLog#3776]
See also https://devblogs.microsoft.com/dotnet/introducing-the-new-microsoftdatasqlclient/ - System.Data.SqlClient will not implement any new features, so Microsoft.Data.SqlClient should be used instead (current version is 1.1.0, version 2.0.0 is in preview)

**Comment by snakefoot** [comment]
NLog doesn't depend on SqlClient. But you are welcome to create a PullRequest to update any obsolete nuget-dependencies for the unit-test-project (for the platforms where the new nuget-dependency is supported).

**Comment by MartinStrbak** [comment]
Switching System.Data.SqlClient to new Microsoft.Data.SqlClient has one significant drawback - supported platforms for Microsoft.Data.SqlClient are .NET Framework 4.6+, .NET Core 2.1+ and .NET Standard 2.0+, so backward compatibility with older platforms will be lost for sqlserver data provider. 

Maybe the solution should be to create either separate DBProvider name for Microsoft.Data.SqlClient, or use some of the existing DBProvider names mapped to System.Data.SqlClient in
https://github.com/NLog/NLog/blob/dev/src/NLog/Targets/DatabaseTarget.cs , method SetConnectionType().

Is it feasible solution?

**Comment by snakefoot** [comment]
@MartinStrbak The special alias support for the "DBProvider"-property should be considered legacy. Instead one should always specify the full TypeName. See also: 

https://github.com/NLog/NLog/wiki/Database-target#dbprovider-examples

**Comment by MartinStrbak** [comment]
Thank you, I missed that information.

**Comment by 304NotModified** [comment]
So in summary:

Install package: https://www.nuget.org/packages/Microsoft.Data.SqlClient/

and use in the database target:

    dbProvider="Microsoft.Data.SqlClient.SqlConnection, Microsoft.Data.SqlClient"
