### ISSUE TITLE
MappedDiagnosticsLogicalContext doesn't work with ActionFilterAttribute

### ISSUE THREAD

**Issue by Boenne** [NLog/NLog#3782]
NLog version: 4.6.8
NLog.Web version: 4.9.0

.NET Framework 4.7.2

NLog config:
```c#
public class Logger : ILogger
    {
        private readonly NLog.Logger _logger;

        public Logger()
        {
            var config = new LoggingConfiguration();
            var databaseTarget = new DatabaseTarget
            {
                ConnectionStringName = "SclCentralConnection",
                CommandText =
                    @"insert into dbo.Logs (IpAddress, Logged, Level, Message, AppId, Exception, Payload) values 
                    (@IpAddress, @Logged, @Level, @Message, @AppId, @Exception, @Payload);"
            };

            databaseTarget.Parameters.Add(new DatabaseParameterInfo("@IpAddress", "${mdlc:item=IpAddress}"));
            databaseTarget.Parameters.Add(new DatabaseParameterInfo("@Logged", "${date}"));
            databaseTarget.Parameters.Add(new DatabaseParameterInfo("@Level", "${level}"));
            databaseTarget.Parameters.Add(new DatabaseParameterInfo("@Message", "${message}"));
            databaseTarget.Parameters.Add(new DatabaseParameterInfo("@AppId", "${event-properties:AppId}"));
            databaseTarget.Parameters.Add(new DatabaseParameterInfo("@Exception", "${exception:format=tostring,Data}"));
            databaseTarget.Parameters.Add(new DatabaseParameterInfo("@Payload", "${event-properties:Payload}"));
            config.AddTarget("database", databaseTarget);

            var logEverythingToDatabaseRule = new LoggingRule("*", LogLevel.Info, databaseTarget);
            config.LoggingRules.Add(logEverythingToDatabaseRule);

            LogManager.Configuration = config;

            _logger = LogManager.GetLogger("Default");
        }

        public void Information(string message)
        {
            Log(LogLevel.Info, message);
        }

        public static void SetIpAddress(string ipAddress)
        {
            MappedDiagnosticsLogicalContext.Set("IpAddress", ipAddress);
        }

        private void Log(LogLevel level, string message, Exception exception = null, object payload = null)
        {
            var logEvent = new LogEventInfo(level, _logger.Name, null, message, null, exception);

            _logger.Log(typeof(Logger), logEvent);
        }
    }
````

I've just started using MappedDiagnosticsLogicalContext in my Web.API where I would like to log the IP address of every caller, and to simplify my controllers I decided to create an ActionFilterAttribute to call MappedDiagnosticsLogicalContext.Set().
That way I don't have to call it in every single endpoint/method.
However that doesn't work. It looks like the logical context of the attribute is not the same as the logical context of the endpoint.

I've created a small test class to showcase this:

```c#
public class ValuesController : ApiController
    {
        private readonly ILogger _logger;

        public ValuesController(ILogger logger)
        {
            _logger = logger;
        }

        // Works as expected
        public async Task<IEnumerable<string>> Get()
        {
            Logger.SetIpAddress("localhost");
            _logger.Information("1");
            return new[] {"value1", "value2"};
        }

        // mdlc:item=IpAddress has no value in this case
        [LogHttpRequest]
        public async Task<IEnumerable<string>> Get1()
        {
            _logger.Information("1");
            return new[] {"value1", "value2"};
        }
    }
```

ActionFilterAttribute:

```c#
public class LogHttpRequestAttribute : ActionFilterAttribute
    {
        public override async Task OnActionExecutingAsync(HttpActionContext actionContext,
            CancellationToken cancellationToken)
        {
            Logger.SetIpAddress("localhost");
        }
    }
```

Is this something that can be solved, or is it necessary to call MappedDiagnosticsLogicalContext.Set() in the beginning of every endpoint of my API?

**Comment by snakefoot** [comment]
Not an expert in async Tasks, but this looks like expected behavior:

Task1 - Calls async-method that schedules and awaits Task2.
Task2 - Updates NLog MDLC and completes
Task1 - Resumes operation and does not see Task2 changes to NLog MDLC.

This is fully intentional, and follows the rules of the Task-Execution-Context. It only propagates to spawned child Tasks (Task2 can see NLog MLDC values from Task1). This also ensures that different Tasks will not step on each other toes by trying to update the same NLog MDLC-collection.

See also: https://github.com/NLog/NLog/issues/3301#issuecomment-483367975

**Comment by Boenne** [comment]
Thanks for the answer. I'll just have to MappedDiagnosticsLogicalContext.Set() in every method.

**Comment by snakefoot** [comment]
Where do you extract the ip-address from? The HttpContext or somewhere else?


Sent from my Sony Xperia


---- Nicolaj Enøe Simonsen wrote ----


Thanks for the answer. I'll just have to MappedDiagnosticsLogicalContext.Set() in every method.

**Comment by Boenne** [comment]
Yes I get the ip address from the HttpContext. But I found out that I can just use the non-async version of OnActionExecutingAsync. Then the logical context is the same for the attribute and the endpoint

**Comment by 304NotModified** [comment]
Not sure if this is already mentioned, but some related info:

- you could render the IP without MDC, e.g. `${aspnet-request-ip}` and `${local-ip} ` -  see https://nlog-project.org/config/?tab=layout-renderers&search=ip
- You could create a custom layout renderer in one line and that one could read the HttpContext, see https://github.com/NLog/NLog/wiki/How-to-write-a-custom-layout-renderer
