### ISSUE TITLE
Getting Stacktrace as "<no type>.CallSite.Target" when logging is done in Catch in MVC controller class.

### ISSUE THREAD

**Issue by ernavjotsingh2** [NLog/NLog#379]
Hi,

I am getting "<no type>.CallSite.Target" as stacktrace while logging in a Catch statement. I am calling a service to authenticate the user and when the authentication failed then Service throw exception like ProxyException was caught. When I try to NLog it from Catch in Controller, then I didn't get proper Stacktrace. I get

Layout
"${gdc:UserName}  ||||  ${date:universalTime=true} ||||  ${level}  ||||  ${stacktrace} ||||  ${message}" />

NoUser  ||||  06/26/2014 11:29:15 ||||  Error  ||||  <no type>.CallSite.Target => Log.Error => NLogLogger.Error ||||  Identification/Authorization failed: Please verify user account or contact administrator.

Then I tried DetailedFlat format of Stacktrace. I get

NoUser  ||||  06/26/2014 11:27:27 ||||  Error  ||||  [Void CallSite.Target(System.Runtime.CompilerServices.Closure, System.Runtime.CompilerServices.CallSite, Mdrx.CommonComponents.EPCS.RxArchive.Logging.ILogger, System.Object, System.Exception)] => [Void Error(System.String, System.Exception)] => [Void Error(System.String, System.Exception)] ||||  Identification/Authorization failed: Please verify user account or contact administrator.

Then I used Raw format of Stacktrace, I get

NoUser  ||||  06/26/2014 11:53:35 ||||  Error  ||||  CallSite.Target at offset 354 in file:line:column <filename unknown>:0:0
Error at offset 66 in file:line:column <filename unknown>:0:0
Error at offset 66 in file:line:column <filename unknown>:0:0
 ||||  Identification/Authorization failed: Please verify user account or contact administrator.

The whole scenario is working if the authentication is successful and I Log in try only but when its done in Catch after the exception occurs, the stacktrace it is lost.

Thanks,
Navjot

**Comment by 304NotModified** [comment]
@ernavjotsingh2  if this is still a problem, please submit the requested info and re-open this issue.
