### ISSUE TITLE
Update System.Data.SqlClient to Microsoft.Data.SqlClient

### ISSUE THREAD

**Issue by unionthugface** [NLog/NLog#3792]
**NLog version**: next

**Platform**: .Net Framework 4.6+ / .Net Core 2.1+ / .Net Standard 2.0+

- Why do we need it?

I recently had to add System.Data.SqlClient to my .Net Core 3.1 project to get NLog to work; it wouldn't work without it.  All new feature development is happening on Microsoft.Data.SqlClient [per this Microsoft statement](https://devblogs.microsoft.com/dotnet/introducing-the-new-microsoftdatasqlclient/), including performance and security enhancements.  It would be cool to use that instead.

> We have no intention of dropping support for System.Data.SqlClient any time soon. It will remain as-is and we will fix important bugs and security issues as they arise. If you have a typical application that doesn’t use any of the newest SQL features, then you will still be well served by a stable and reliable System.Data.SqlClient for many years.
> 
> However, Microsoft.Data.SqlClient will be the only place we will be implementing new features going forward. We would encourage you to evaluate your needs and options and choose the right time for you to migrate your application or library from System.Data.SqlClient to Microsoft.Data.SqlClient.

**Comment by 304NotModified** [comment]
This is a duplicate of https://github.com/NLog/NLog/issues/3776?

**Comment by 304NotModified** [comment]
So in summary:

Install package: https://www.nuget.org/packages/Microsoft.Data.SqlClient/

and use in the database target:

    dbProvider="Microsoft.Data.SqlClient.SqlConnection, Microsoft.Data.SqlClient"

**Comment by 304NotModified** [comment]
If updated https://github.com/NLog/NLog/wiki/Database-target to make it a bit more clear in the start :)
