### ISSUE TITLE
Allow loading extensions in the API

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#3799]
proposal:

```
LogManager.LoadExtension(Assembly)
```

Needed because of this: https://github.com/NLog/NLog/issues/3798

**Comment by snakefoot** [comment]
Think we should stay with the existing logic:

`LogManager.Setup().SetupExtensions(s => s.AutoLoadAssemblies(true));`

`LogManager.Setup().SetupExtensions(s => s.RegisterAssembly(Assembly));`

See also our long discussion here #3686. Or are you thinking of something else?

**Comment by 304NotModified** [comment]
ow yes indeed, LogManager.Setup().SetupExtensions(s => s.RegisterAssembly(Assembly)); is it
