### ISSUE TITLE
Old days log files are not archived and removed from Logs folder

### ISSUE THREAD

**Issue by mukeshlakum11** [NLog/NLog#3807]
**Issue (Question)**
**NLog version**: 4.5.10
**Platform: .Net** 4.5

**Current NLog config** (xml)

```xml
<targets>
<default-wrapper xsi:type="AsyncWrapper" timeToSleepBetweenBatches="0" overflowAction="Block" />
<target xsi:type="File" name="debug" fileName="${basedir}/logs/${shortdate}_Data_Debug.log" layout="${longdate} | ${message}" archiveFileName="${basedir}/LogArchive/${shortdate}_Data_Debug.zip" archiveEvery="Day" maxArchiveFiles="31" enableArchiveFileCompression="true" archiveOldFileOnStartup="true"/>
<target xsi:type="File" name="Error" fileName="${basedir}/logs/${shortdate}_Data_Error.log" layout="${longdate} | ${message}" archiveFileName="${basedir}/LogArchive/${shortdate}_Data_Error.zip" archiveEvery="Day" maxArchiveFiles="31" enableArchiveFileCompression="true" archiveOldFileOnStartup="true"/>
</targets>

<rules>
<logger name="*" level="Debug" writeTo="debug" enabled ="true" />
<logger name="*" level="Error" writeTo="Error" enabled ="true" />
</rules>
```

**Current result:** Nlog call on alternate day (as when required some times in a week) to generate a log file. so, previous day log files are not archived (as shown in below image)
![image](https://user-images.githubusercontent.com/61041994/74510193-42220280-4f29-11ea-9f31-c3b3b08c19c7.png)

**Expected result:** Old days file should archived and deleted from current folder.

**Are there any work arrounds?**
I can't work out what the issue is.

**Is there a version in which it did worked?**
I haven't had it work correctly before.

**Can you help us by writing an unit test?**
No.

**Comment by snakefoot** [comment]
Cleanup happens when you have more than `maxArchiveFiles="31`. The screenshot only shows 6 files.

**Comment by snakefoot** [comment]
Btw. you should remove `archiveEvery="Day"` since the dynamic fileName-Layout will automatically roll.

Btw. `enableArchiveFileCompression="true"` will not work well when having having dynamic fileName-Layout (Will probably only trigger at startup because of `archiveOldFileOnStartup="true"`)

**Comment by mukeshlakum11** [comment]
- 
`<target xsi:type="File" name="debug" fileName="${basedir}/logs/${shortdate}_Data_Debug.log" layout="${longdate} | ${message}" archiveFileName="${basedir}/LogArchive/${shortdate}_Data_Debug.zip" archiveEvery="Day" maxArchiveFiles="31" enableArchiveFileCompression="true"/>` 
Above NLOG setting is working in another application where log is continuously generated on some time interval. please find below image (Log file folder & Archived file folder).
![image](https://user-images.githubusercontent.com/61041994/74706291-87517780-523c-11ea-94d4-54d83d9d176b.png)

![image](https://user-images.githubusercontent.com/61041994/74706152-36418380-523c-11ea-9c75-49cc95bd7eef.png)

- in some application log is written as when functionality triggered, in that case daily log file not generated. for that we tried _archiveOldFileOnStartup="true"_ but it also not work. 

Please suggest if any other option / missing in above NLOG config settings.

**Comment by snakefoot** [comment]
I can only repeat what I have already said. Most of the features you have enabled and complaining about does not work very well with dynamic FileName-Layout (See `${shortdate}`).

The "magic" solution is to use a static FileName-Layout (Without `${shortdate}`). Like this:

```xml
<target xsi:type="File" 
 name="debug"
 fileName="${basedir}/logs/Data_Debug.log"
 layout="${longdate} | ${message}"
 archiveFileName="${basedir}/LogArchive/{#}_Data_Debug.zip"
 archiveEvery="Day" 
 maxArchiveFiles="31" 
 enableArchiveFileCompression="true"/>
```

NLog has two archive modes:
- FileName with dynamic-Layout has these archive features:
   - archiveAboveSize
   - maxArchiveFiles (Feature was fixed with NLog 4.5, before it would delete all files)
- FileName with static-Layout has these archive features:
   -  archiveAboveSize - Can move old files when reaching a certain size
   -  archiveEvery - Can move old files on specified interval
   -  archiveFileName - Can move old files into other folder
   -  enableArchiveFileCompression - Can compress old files
   -  maxArchiveFiles - Can delete old files

**Comment by mukeshlakum11** [comment]
team,
thanks for the support, your suggested configuration is working but our requirement is to add date in file name to see log on which date generated(even though we move those file to another location). do you plan to take support for dynamic FileName-Layout (See ${shortdate}) in coming future.

**Comment by snakefoot** [comment]
@mukeshlakum11 Have not seen any pull-requests on the horizon

**Comment by snakefoot** [comment]
Btw have you tried to configure ArchiveNumbering=DateAndSequence on the FileTarget? This will ensure the archived files will be stamped


Sent from my Sony Xperia


---- mukeshlakum11 wrote ----


team,
thanks for the support, your suggested configuration is working but our requirement is to add date in file name to see log on which date generated(even though we move those file to another location). do you plan to take support for dynamic FileName-Layout (See ${shortdate}) in coming future.

**Comment by mukeshlakum11** [comment]
Dear team,
thanks for the valuable support, we checked with given configuration.
