### ISSUE TITLE
Feature: OnNewLogFile Method Hook / Event Handler

### ISSUE THREAD

**Issue by Brondahl** [NLog/NLog#3814]
See this StackOverflow question:

https://stackoverflow.com/questions/60335551/nlog-onnewlogfile-handler

On the assumption that it doesn't *currently* exist, would you be open to adding such a config option?

**NLog version**: vNext?

**Platform**: N/A

**Current NLog config**: N/A?

 - Why do we need it?
So that (if desired) you can ensure that All log files contain relevant contextual information. Aiding in debugging production issues.

 - An example of the XML config, if relevant.
IDK.
Possibly something very similar to the [MethodCall target](https://github.com/NLog/NLog/wiki/MethodCall-target) functionality?

**Comment by Brondahl** [comment]
Supposing you were on board with the concept, would you welcome a PR for this, from a new contributor?

**Comment by 304NotModified** [comment]
I doubting if this really suitable for NLog Core. Another option is to make the File target extensible enough to handle this. 

> Possibly something very similar to the MethodCall target functionality?

I think c# events are a better way for this

**Comment by 304NotModified** [comment]
related #1249

**Comment by snakefoot** [comment]
Sounds like you are really looking for the **Header**-Layout on the FileTarget.

```xml
    <target name="logfile" xsi:type="File">
             <header>--- ${assembly-version} started on ${longdate} ---</header>
    </target>
```
See also https://github.com/NLog/NLog/wiki/File-target

**Comment by Brondahl** [comment]
🤣 Yes. Yes, it does indeed.
Internet points are available, if you want to post that on the SO question.

**Comment by snakefoot** [comment]
Some combine it with `archiveOldFileOnStartup` because the **Header** is only printed when file is created. See also #2119

**Comment by 304NotModified** [comment]
Closing this as the header layout is fine here and no upvotes
