### ISSUE TITLE
Write logs to Azure Share

### ISSUE THREAD

**Issue by WuMianRen** [NLog/NLog#3836]
=

**NLog version**: (4.9.0) (net core project)

**Platform**: .NET Core 2.2

**Current NLog config** (xml or C#, if relevant)

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      internalLogLevel="info"   
      internalLogFile="\\k8sdiag634.file.core.chinacloudapi.cn\share\AIService\log\internal-nlog.log">

  <!-- the targets to write to -->
  <targets>
    <!-- write logs to file  -->
    <target xsi:type="File" name="allfile" fileName="\\k8sdiag634.file.core.chinacloudapi.cn\share\AIService\log\nlog-all-${shortdate}.log"
            layout="${longdate}|${event-properties:item=EventId.Id}|${uppercase:${level}}|${logger}|${message} ${exception}" />

    <!-- another file log, only own logs. Uses some ASP.NET core renderers -->
    <target xsi:type="File" name="ownFile-web" fileName="\\k8sdiag634.file.core.chinacloudapi.cn\share\AIService\log\nlog-own-${shortdate}.log"
            layout="${longdate}|${event-properties:item=EventId.Id}|${uppercase:${level}}|${logger}|${message} ${exception}|url: ${aspnet-request-url}|action: ${aspnet-mvc-action}" />
    

    <!-- write to the void aka just remove -->
    <target xsi:type="Null" name="blackhole" />
  </targets>

  <!-- rules to map from logger name to target -->
  <rules>
    <!--All logs, including from Microsoft-->
    <logger name="*" minlevel="Trace" writeTo="allfile" />

    <!--Skip Microsoft logs and so log only own logs-->
    <logger name="Microsoft.*" minlevel="Trace" writeTo="blackhole" final="true" />
    <logger name="*" minlevel="Trace" writeTo="ownFile-web" />
  </rules>
</nlog>

```

- What is the current result?
   Unable to write to shared NAS （aliyun can write and also NAS shared storage）
- What is the expected result?
  How to write？？？
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
  yes   ExMessage: Could not create directory Z:\share\AIService\log or  path to the configuration file above

**Comment by WuMianRen** [comment]
2020-03-10 14:45:57.1339 Error FileTarget(Name=allfile): Failed write to file 'Z:\test\nlog-all-2020-03-10.log'. Exception: NLog.NLogRuntimeException: Could not create directory Z:\test
   at NLog.Internal.FileAppenders.BaseFileAppender.CreateFileStream(Boolean allowFileSharedWriting)
   at NLog.Internal.FileAppenders.RetryingMultiProcessFileAppender.Write(Byte[] bytes, Int32 offset, Int32 count)
   at NLog.Targets.FileTarget.WriteToFile(String fileName, ArraySegment`1 bytes, Boolean initializedNewFile)

this stack

**Comment by snakefoot** [comment]
Well the FilePath resolves into this filename:

> Z:\test\nlog-all-2020-03-10.log

And the path `Z:\test` does not exists, and NLog receives an exception when automatically trying to create the directory. Guess you application does not have enough rights.

Have you considered just using [Azure BlobStorage](https://www.nuget.org/packages/NLog.Extensions.AzureBlobStorage/) ?

**Comment by WuMianRen** [comment]
I don't want to write the blob but I write to 'k8sdiag634.file.core.chinacloudapi.cn' nas file storage
Before aliyun (also a cloud service vendor) it was writable
Then I wrote a simple example program. I tried to write the directory and file to 'Z: \ test \ 1.txt' so that it can be written.
I checked the nlog source code's writing path and file code as I wrote, but nlog did not create the path and write to the log
Make me confused

**Comment by WuMianRen** [comment]
If I want to write to any file system in Azure, such as Blog or File Share or Table, do I need to add the AzureBlobStorage package?

**Comment by WuMianRen** [comment]
```
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      internalLogLevel="info"
      internalLogFile="\\1436f49388-pvv34.cn-beijing.nas.aliyuncs.com\myshare\logs\AI_JD\internal-nlog.log">

  <!-- the targets to write to -->
  <targets>
    <!-- write logs to file  -->
    <target xsi:type="File" name="allfile" fileName="\\1436f49388-pvv34.cn-beijing.nas.aliyuncs.com\myshare\logs\AI_JD\logs\nlog-all-${shortdate}.log"
            layout="${longdate}|${event-properties:item=EventId.Id}|${uppercase:${level}}|${logger}|${message} ${exception}" />

    <!-- another file log, only own logs. Uses some ASP.NET core renderers -->
    <target xsi:type="File" name="ownFile-web" fileName="\\1436f49388-pvv34.cn-beijing.nas.aliyuncs.com\myshare\logs\AI_JD\logs\nlog-own-${shortdate}.log"
            layout="${longdate}|${event-properties:item=EventId.Id}|${uppercase:${level}}|${logger}|${message} ${exception}|url: ${aspnet-request-url}|action: ${aspnet-mvc-action}" />

    <!-- write to the void aka just remove -->
    <target xsi:type="Null" name="blackhole" />
  </targets>
```


This is a NAS server that successfully writes logs, but it is for the aliyu platform

**Comment by snakefoot** [comment]
So NLog is working is one environment, but not in another environment.

Sounds like an environment issue, or invalid configuration for that environment.

Sounds like you should contact the people that are responsible for providing support for this environment, and ask those experts for help about your issue.

**Comment by WuMianRen** [comment]
goog
