### ISSUE TITLE
Loosing contact with server results in application becoming unhealthy

### ISSUE THREAD

**Issue by angelalaweai** [NLog/NLog#3838]
Hi,

I am trying to use nlog.net to log errors and user activity.  When we put it up on our elasctic beanstalk and take down the database connection it uses to log the application begins to slow down to a turtle pace an AWS beanstalk reports the application is unhealthy.  When, we go through and bring the database back up for the nlog the application becomes healthy and starts working fine.

A side note is that nlog own internal logging is not turned on meaning I did not set any attributes for the internal logging.

My questions are if nothing is set for internal logging will it still attempt to log?  If so is there a way to shut that off? would that be causing this issue of the server crashing when it can't hit the database? Are there other reasons why nlog would cause the crashing of the application when it can't hit the server database?  Keep in mind the logging database server is separate from the application database server.

Any help would be greatly appreciated!

Angela

**Comment by snakefoot** [comment]
NLog performs all logging synchronously by default. To cater for simple targets like console and file.

When using remote targets like a database instance, then logging operations will suddenly be caught in network traffic. This will give a huge performance hit, especially when the remote instance is unavailable.

The normal solution is to use `<targets async="true">` or wrap using `AsyncWrapper`. This has the side-effect that when remote instance is unavailable, then logevents will be discarded.

**Comment by snakefoot** [comment]
Has your issue been resolved?
