### ISSUE TITLE
How to use the new Layout.FromString method

### ISSUE THREAD

**Issue by ThomasArdal** [NLog/NLog#3844]
I cannot seem to get the new `FromString` method on `Layout` working. I have the following code that works:

```csharp
LogManager.ThrowConfigExceptions = true;
Layout myLayout;
try
{
    myLayout = "${aspnet-request-host:whenEmpty=${machinename}}";
}
catch
{
    myLayout = "${machinename}";
}
```

After upgrading to NLog 4.7.0-rc1 and the following code:

```csharp
Layout myLayout;
try
{
    myLayout = Layout.FromString("${aspnet-request-host:whenEmpty=${machinename}}", true);
}
catch
{
    myLayout = "${machinename}";
}
```

The debugger no longer breaks and I don't get anything logged.

Am I doing something wrong here?

**Comment by snakefoot** [comment]
Strange. The NLog unit-test fails very nicely with an exception about unknown type `aspnet-request-host`.

See also SimpleLayout_FromString_ThrowConfigExceptions. Where I have just change it to:

```c#
      [Fact]
        void SimpleLayout_FromString_ThrowConfigExceptions()
        {
            using (new NoThrowNLogExceptions())
            {
                Assert.Throws<NLogConfigurationException>(() => Layout.FromString("${aspnet-request-host:whenEmpty=${machinename}}", true));
            }
        }
```

And it throws as expected.

**Comment by ThomasArdal** [comment]
My bad. I had updated the `NLog` package in the Target project but not in my console app 🤦🏻‍♂️

**Comment by snakefoot** [comment]
Guess the issue can be resolved. 

But strange that your build didn't fail. It is usually very happy about complaining when doing nuget-reference-downgrade.

**Comment by ThomasArdal** [comment]
The issue can be resolved yes 👍

I cannot explain why the code failed on runtime. But it's pretty easy to reproduce by downgrading `NLog` to 4.6 in the console app of https://github.com/elmahio/elmah.io.nlog. I think it's a problem with the compiler (as you mention) and not an issue with NLog.

**Comment by snakefoot** [comment]
Pushing the button for ya :)
