### ISSUE TITLE
Writing to file

### ISSUE THREAD

**Issue by fancky2019** [NLog/NLog#3845]
```C#
        private static readonly NLog.Logger nLog = NLog.LogManager.GetCurrentClassLogger();
      
        static void Main(string[] args)
        {
            for (int i = 0; i < 1000000; i++)
            {
                nLog.Info($"{i}-info");
            }
            Console.WriteLine("completed!");
            Console.ReadLine();
        }
```

I find it does not write 1000000 lines to file. Can you explain why? Thanks.

**Comment by snakefoot** [comment]
When you create a new issue, then there is template you should fill out:

https://github.com/NLog/NLog/issues/new/choose

You seemed to have missed that. Please do the necessary (Ex. show the contents of NLog.config or how you configure NLog).

**Comment by snakefoot** [comment]
Found your Nlog.config file:

https://github.com/fancky2019/DotNetDemos/blob/5803dd5afe6b2420a50818143f0feeab039184dd/Demos/NLog.config

You have enabled `<targets async="true" >`. This activates a background writer thread, where you need flush before application exit. See also https://github.com/NLog/NLog/wiki/Tutorial#5-remember-to-flush

**Comment by 304NotModified** [comment]
Also check https://github.com/NLog/NLog/wiki/AsyncWrapper-target#async-attribute-will-discard-by-default

> The async attribute is a shorthand for:

     xsi:type="AsyncWrapper overflowAction="Discard" queueLimit="10000" batchSize="200" timeToSleepBetweenBatches="1"

>So if you write a lot of messages (more then 10000) in a short time, it's possible that messages will be lost. This is intended behavior as keeping all the messages or waiting for all the messages to be written, could have impact on the performance of your program.
> 
> If you need all the log messages, then use AsyncWrapper with the wanted overflowAction, instead of the async attribute.

**Comment by fancky2019** [comment]
> Also check https://github.com/NLog/NLog/wiki/AsyncWrapper-target#async-attribute-will-discard-by-default
> 
> > The async attribute is a shorthand for:
> 
> ```
>  xsi:type="AsyncWrapper overflowAction="Discard" queueLimit="10000" batchSize="200" timeToSleepBetweenBatches="1"
> ```
> 
> > So if you write a lot of messages (more then 10000) in a short time, it's possible that messages will be lost. This is intended behavior as keeping all the messages or waiting for all the messages to be written, could have impact on the performance of your program.
> > If you need all the log messages, then use AsyncWrapper with the wanted overflowAction, instead of the async attribute.
