### ISSUE TITLE
[question] asp.net core + nlog fluent api

### ISSUE THREAD

**Issue by krzSobin** [NLog/NLog#3847]
Hello,
I didn't find it in documentation so asking here.

I have asp.net core api where I configured nlog (using documentation https://github.com/NLog/NLog/wiki/Getting-started-with-ASP.NET-Core-2)

I would like to use fluent api https://github.com/NLog/NLog/wiki/Fluent-API. Is there any option to use fluent api with `ILogger<T>` interface? I know I can use `NLog.LogManager.GetCurrentClassLogger()` instead of injected `ILogger<T>` but maybe there is another option?

**Comment by snakefoot** [comment]
The NLog.Fluent-extension methods are for NLog own Logger-object. 

You are welcome to create your improved extension methods for Microsoft ILogger-object.

Maybe can be some inspiration: https://github.com/NLog/NLog.Extensions.Logging/wiki/NLog-properties-with-Microsoft-Extension-Logging

**Comment by snakefoot** [comment]
@krzSobin Does it answer your question?
