### ISSUE TITLE
Can nlog support ElasticSearch  account and password mode?

### ISSUE THREAD

**Issue by zhan520g** [NLog/NLog#3852]
Hi! Thanks for reporting this feature/bug/question! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

QUESTIONS are preferred on StackOverflow. You could expect a faster response there (but do include all the info below). Use the tag "nlog" https://stackoverflow.com/questions/ask

For .NET Core users, please check the platform support: https://github.com/NLog/NLog/wiki/platform-support

**NLog version**: (e.g. 4.2.3)

**Platform**: .Net 3.5 / .Net 4.0 / .Net 4.5 / Mono 4 / Silverlight 4 / Silverlight 5 / Xamarin Android / Xamarin iOs / .NET Core 1 / .NET Core 2

**Current NLog config** (xml or C#, if relevant)

```xml
<nlog>
  <targets>
  </targets>
  <rules>
  </rules>
</nlog>

```

 - Why do we need it?
 - An example of the XML config, if relevant.

**Comment by snakefoot** [comment]
This is for support issues regarding the core of NLog.

Maybe better if you post the question to the GitHub repository for the ElasticSearch-target? 

Or if using File-beat (or similar upload service) then contact their support-help?

**Comment by chucklu** [comment]
The correct report new issue, https://github.com/markmcdowell/NLog.Targets.ElasticSearch
