### ISSUE TITLE
Internal log caused Windows Defender scan application every start up.

### ISSUE THREAD

**Issue by ky4mail** [NLog/NLog#3854]
Hello,
NLog.config with  
`internalLogLevel="Trace" internalLogFile="c:\temp\nlog-internal.log" `
caused Windows 10 Defender scans application every time its run.

If  `internalLogLevel` set to `"Off"` no visible delay then.

**Comment by snakefoot** [comment]
Sounds annoying, but not sure how the NLog-project should fix the behavior of Windows Defender.

What if you change the file-location to some other place? (Ex. `%AppData%` or `%Temp%`)

**Comment by ky4mail** [comment]
Not sure if than needs to be fixed. I just described Windows Defender behavior.
Maybe some will find this useful.

**Comment by snakefoot** [comment]
Excellent. Closing the issue since it cannot be fixed.
