### ISSUE TITLE
Can archives delete folders

### ISSUE THREAD

**Issue by JHeLiu** [NLog/NLog#3859]
Archive can delete folders, the directory created is
` ${basedir}/Log/${date:format= yyyy-mm-dd}/${level}. Log,`
Can I delete its directory?

**Comment by snakefoot** [comment]
No the NLog archive cleanup is only able to cleanup files, not folders.

Also the NLog archive cleanup has no ability to scan multiple sub-folders based on wildcard.

**Comment by snakefoot** [comment]
Does it answer your question?

**Comment by JHeLiu** [comment]
Ok, thank you. Now I use the file, The problem can be closed
