### ISSUE TITLE
The interface cannot be notified using custome target,

### ISSUE THREAD

**Issue by H3317** [NLog/NLog#3863]
NLog version: 4.7
Platform: .Net 4.7.2

I want to display the log on the interface,
However, after using the custome target, after the variable value changes, the interface cannot be notified, and PropertyChanged is empty.

    public class LogPageViewModel: Target, INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;
        protected virtual void OnPropertyChanged([CallerMemberName] string propertyName = null)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }
        private string mesaage;
        public string Message
        {
            get
            {
                return mesaage;
            }
            set
            {
                if (mesaage != null && mesaage.Equals(value)) return;
                mesaage = value;
                OnPropertyChanged();
            }
        }

        protected override void Write(LogEventInfo logEvent)
        {
            SetMessage(logEvent);
        }

        private void SetMessage(LogEventInfo logEvent)
        {
            string logMessage = logEvent.Message;
            Message = logMessage;
        }
    }

**Comment by snakefoot** [comment]
I'm guessing you have some faulty logic in the registration of your custom target `LogPageViewModel`.

Most likely the NLog config is replaced, and thus your custom-target is closed.

Try and override the method CloseTarget in you custom target, and place a breakpoint.
