### ISSUE TITLE
Is archiving configuration possible with xml format in nlog.config file?

### ISSUE THREAD

**Issue by priyanksurani** [NLog/NLog#3864]
Hello Team,

I was facing issue regarding archiving file in nlog.config file with xml format.

Is there any way to handle archiving file in nlog.config with xml format?

Here is nlog.config file : 

<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true">

    <target xsi:type="RetryingWrapper" retryCount="3" retryDelayMilliseconds="2" name="retryingWrap">
      <target name="asyncWrapper" xsi:type="AsyncWrapper" queueLimit="5000" overflowAction="Grow">
        <target name="xmlFile" xsi:type="File" fileName="c:\temp\Demo.log" >
          <layout xsi:type="XmlLayout" includeAllProperties="false" elementName='LogData'>
            <attribute name="xmlns:xsi" layout="http://www.w3.org/2001/XMLSchema-instance" />
            <attribute name="xmlns" layout="http://www.nlog-project.org/schemas/NLog.xsd"/>
            <element name="MachineName" value="${machinename}" />
            <element name="TypeName" value="${logger} />
          </layout>
        </target>
      </target>
    </target>
  </targets>

  <rules>
    <logger name="Microsoft.*" maxLevel="Info" final="true"  />
    <logger name="*" minlevel="Trace" writeTo="xmlFile" />
  </rules>

</nlog>

------------------------------------------------------------------------------------

If I want to add archiving configuration in nlog.file. is it possible?

Thanks you.

**Comment by snakefoot** [comment]
Have you tried to use the example shown in the Wiki:

https://github.com/NLog/NLog/wiki/File-target#archive-old-log-files

You can do this:

```xml
<target xsi:type="RetryingWrapper" retryCount="3" retryDelayMilliseconds="2" name="retryingWrap">
  <target name="asyncWrapper" xsi:type="AsyncWrapper" queueLimit="5000" overflowAction="Grow">
    <target name="xmlFile" xsi:type="File"
            fileName="c:\temp\Demo-${shortdate}.log"
            maxArchiveFiles="4"
            archiveAboveSize="10240" />
      <layout xsi:type="XmlLayout" includeAllProperties="false" elementName='LogData'>
        <attribute name="xmlns:xsi" layout="http://www.w3.org/2001/XMLSchema-instance" />
        <attribute name="xmlns" layout="http://www.nlog-project.org/schemas/NLog.xsd"/>
        <element name="MachineName" value="${machinename}" />
        <element name="TypeName" value="${logger} />
      </layout>
    </target>
  </target>
</target>
```

**Comment by priyanksurani** [comment]
Ok, Thank you for tour suggestions.

Thanks
