### ISSUE TITLE
Adopt NLog.FSharp - F# support

### ISSUE THREAD

**Issue by sircuri** [NLog/NLog#3865]
I have been using NLog in several F# projects and would like to use it in F# .NET Core application as well. Unfortunately the owner of this project https://github.com/Ravadre/NLog.FSharp is no longer working on it and is also not responding to requests to transfer the GitHub project to somebody else.

Is it possible that NLog adopts/ incorporates F# support into its main branch? 

Thank you for your consideration.

**Comment by 304NotModified** [comment]
Hi! Could you please tell me why the helper is needed? Unfortunately the project is missing unit tests.

**Comment by sircuri** [comment]
It is simply a convenience wrapper around NLog.
I know it lacks any unit test and is poorly maintained.
But thank you. I think I'll just close this one and include NLog directly into my F# projects without this wrapper package.

**Comment by snakefoot** [comment]
@sircuri I think if you made a fork of the repository and setup continous-integration-build with unit-testing, then it could be forked again and become part of [NLog-repository-list](https://github.com/NLog).
