### ISSUE TITLE
No log file is generated when Blue Prism's code stage invoked the class library

### ISSUE THREAD

**Issue by jtnguyen2000** [NLog/NLog#3869]
Hi! Thanks for reporting this feature/bug/question! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

QUESTIONS are preferred on StackOverflow. You could expect a faster response there (but do include all the info below). Use the tag "nlog" https://stackoverflow.com/questions/ask

For .NET Core users, please check the platform support: https://github.com/NLog/NLog/wiki/platform-support

**NLog version**: (e.g. 4.7)

**Platform**: .Net 4.5

**Current NLog config** (xml or C#, if relevant)

```xml
<nlog internalLogLevel="Trace" internalLogFile="c:\temp\nlog-internal.log">
  <targets>
<target xsi:type="File" name="f" fileName="C:\Users\abcd\Downloads\logs-${shortdate}.log"
           layout="${longdate} ${uppercase:${level}} ${message}" />
  </targets>
  <rules>
<logger name="*" minlevel="Trace" writeTo="f" />
  </rules>
</nlog>

```

- What is the current result? the class returns the results but no log file at the specify location
- What is the expected result? log file at the specify location
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)? yes and nothing there
- Please post full exception details (message, stacktrace, inner exceptions)
- Are there any workarounds? no
- Is there a version in which it did work? no
- Can you help us by writing an unit test? if you let me know what I need to do

**Comment by 304NotModified** [comment]
Please fill in the template, thanks!

**Comment by snakefoot** [comment]
The classic mistake is not having enabled "Copy to Output Directory" for your `NLog.config`:

https://github.com/NLog/NLog/wiki/Logging-troubleshooting

Can you check your application-bin-folder to see if `NLog.config` next to the application-exe?

**Comment by jtnguyen2000** [comment]
I've set it to "always copy" already and NLog.config is in the same folder as the exe.

**Comment by 304NotModified** [comment]
Please enable the internal log and paste it here.

**Comment by snakefoot** [comment]
@jtnguyen2000 You can enable the InternalLogger from code (since it fails to load NLog.config):

```
// set internal log level
NLog.Common.InternalLogger.LogLevel = LogLevel.Trace;

// enable internal logging to a file
NLog.Common.InternalLogger.LogFile = "c:\\log.txt";
```

Make sure to activate [InternalLogger](https://github.com/NLog/NLog/wiki/Internal-Logging) before calling `NLog.LogManager.GetCurrentClassLogger() `or `NLog.LogManager.GetLogger()`

Problem could also be that you don't have permissions to for file-writing, so maybe consider using the console.

**Comment by jtnguyen2000** [comment]
Here is my class....to see if I coded above correct.  If yes, it doesn't write any log files.  Thank you very much for your help!!  I ran the blue prism under the admin account so I'm sure that I've the permission to write the file.

using NLog;
using System;
using System.Data;

namespace ClassLibrary1
{
    public class Example
    {
        // set internal log level
        private static readonly Logger Logger = LogManager.GetCurrentClassLogger();

        public void FilenameParse(string filename)
        {
            // set internal log level
            NLog.Common.InternalLogger.LogLevel = LogLevel.Trace;

            // enable internal logging to a file
            NLog.Common.InternalLogger.LogFile = @"c:\temp\nlog-internal.log";
            Logger.Info("FilenameParse Success!!");
        }
    }
}

**Comment by snakefoot** [comment]
Yes you are on the right track. Now after you have configured the Internallogger. Then you can call GetCurrentClassLogger() and the Internallogger will output what is going on.


Sent from my Sony Xperia


---- jtnguyen2000 wrote ----


Here is my class....to see if I coded above correct. If yes, it doesn't write any log files. Thank you very much for your help!! I ran the blue prism under the admin account so I'm sure that I've the permission to write the file.

using NLog;
using System;
using System.Data;

namespace ClassLibrary1
{
public class Example
{
// set internal log level
private static readonly Logger Logger = LogManager.GetCurrentClassLogger();

    public void FilenameParse(string filename)
    {
        // set internal log level
        NLog.Common.InternalLogger.LogLevel = LogLevel.Trace;

        // enable internal logging to a file
        NLog.Common.InternalLogger.LogFile = @"c:\temp\nlog-internal.log";
        Logger.Info("FilenameParse Success!!");
    }
}


}

**Comment by snakefoot** [comment]
Like this:

```c#
using NLog;
using System;
using System.Data;

namespace ClassLibrary1
{
    public class Example
    {
        // Uncomment static Logger-objects as I said before, or else you will not see output in InternalLogger
        // private static readonly Logger Logger = LogManager.GetCurrentClassLogger();

        public void FilenameParse(string filename)
        {
            // set internal log level
            NLog.Common.InternalLogger.LogLevel = LogLevel.Trace;

            // enable internal logging to a file
            NLog.Common.InternalLogger.LogFile = @"c:\temp\nlog-internal.log";

            // Initialize the Logger after having enabled the InternalLogger
            LogManager.GetCurrentClassLogger().Info("FilenameParse Success!!");
        }
    }
}
```

**Comment by jtnguyen2000** [comment]
I'm sorry to report, still nothing once I executed the method above.

**Comment by snakefoot** [comment]
@jtnguyen2000 I'm guessing the location you have injected this code is not in Program.cs, but some random location that is executed long after the application initialized everything.

You need to understand that the InternalLogger will only give you output if it is enabled as the first thing in the application. Before anything else.

**Comment by snakefoot** [comment]
@jtnguyen2000 Congrats. If you had enabled InternalLogger earlier, then you would probably also have the startup. 

Have you checked where this file is coming from:

`C:\ProgramData\Blue Prism Limited\Blue Prism\Automate.NLog.config`

Seems like your application is loading NLog.config from this file.

**Comment by jtnguyen2000** [comment]
I've attached the Automate.NLog.config for your to review but the log file is not generated at all.

[Automate.NLog.zip](https://github.com/NLog/NLog/files/4411976/Automate.NLog.zip)

**Comment by snakefoot** [comment]
@jtnguyen2000 You should read the tutorial about using NLog and NLog-LoggingRules:

https://github.com/NLog/NLog/wiki/Tutorial

The `<rules>` controls/filters what LogEvents are written to the different targets.
