### ISSUE TITLE
XML log append

### ISSUE THREAD

**Issue by ammaade** [NLog/NLog#3870]
Hello

Could you tell me how to append in a XML log file?
I would like to add a new element attached to the root node element.

Thanks

**Comment by 304NotModified** [comment]
If you mean, 

mylogfile.txt

```
<root>
   LOGS WRITTEN HERE
</root>
```
Then you cant, as we can only append to a file, not insert.

Example that work, see here: https://github.com/NLog/NLog/wiki/XmlLayout

**Comment by snakefoot** [comment]
Duplicate of  #3537

**Comment by snakefoot** [comment]
Rewrite of Footer-Layout on file-append discussed here: https://github.com/NLog/NLog/issues/1658#issuecomment-604589881
