### ISSUE TITLE
DatabaseTarget  - VERACODE SQL Injection flaw

### ISSUE THREAD

**Issue by CharlesWang1** [NLog/NLog#3872]
I can provide more detail report

**Comment by snakefoot** [comment]
Thank you for showing interest in the NLog project. Since OpenSource project then please just provide the flaw you have found, since flaws should be shown.

**Comment by CharlesWang1** [comment]
![image](https://user-images.githubusercontent.com/13029475/78120740-0b526e00-743d-11ea-8a4c-3b5f9a497ab1.png)
![image](https://user-images.githubusercontent.com/13029475/78120766-13aaa900-743d-11ea-89bb-89ba2fe809b9.png)

**Comment by snakefoot** [comment]
Not sure I understand the whole idea with DatabaseTarget is to execute dynamically constructed SQL queries.

**Comment by 304NotModified** [comment]
As you can see in the code, the db command is created with parameters.

https://github.com/NLog/NLog/blob/dev/src/NLog/Targets/DatabaseTarget.cs#L787-L808

Of course, some one could use a layout renderer in the query and so could create SQL that's injectable. That is not something we could prevent as we are a framework and not the user.

So IMO there is nothing to do here.

**Comment by snakefoot** [comment]
@CharlesWang1 Have your question been answered?

**Comment by snakefoot** [comment]
I guess with NLog 5.0 then the DatabaseTarget will be extracted from the code NLog.dll so the warning will disappear. See also #2676

**Comment by snakefoot** [comment]
Maybe check if your VERACODE-tool supports ignoring specific errors/warnings for the NLog.dll-assembly (As config-exclude-file or parameter)

**Comment by 304NotModified** [comment]
This is just a false positive. Closing this.

**Comment by syedmdanish** [comment]
Do we have any expected Release Date for NLog 5.0?

**Comment by snakefoot** [comment]
> Do we have any expected Release Date for NLog 5.0?

Not in my book. NLog is a project developed in spare time. We still have some open issues:

https://github.com/NLog/NLog/milestone/61

**Comment by RickC10** [comment]
I download source and made the needed adjustments. Its good to know the projects will be split in 5.0.  This will remove the need to modify NLog.dll. proj if we are not using DB functionality.
