### ISSUE TITLE
Move older log from Archive folder to some other location instead of deletion

### ISSUE THREAD

**Issue by ashishgmishra** [NLog/NLog#3873]
Hi! 

Once Archive limit is reached, instead of deleting old files, I want to copy the older log file to another location on network. So that we have less older logs at location configured in "archiveFileName" and much older logs somewhere on archive server.
 Is there a way that we can achieve it through nlog.config file.
We are crating more than 2 GB data in a week so want to keep older logs (more than 3 month old which we do not open/read frequently) on archive server.

**NLog version**: 4.5.11

**Platform**: .Net 4.5 

**Current NLog config** 
```
<target name="file" xsi:type="Iit.AsyncWrapper">
      <target type="File"
            archiveAboveSize="10000000"
            archiveEvery="Day"
            maxArchiveFiles="200"
            archiveNumbering="Rolling"
            archiveFileName = "${logDirectory}/archive/log.{#####}.txt"
            fileName="${logDirectory}/log.txt"
            layout="${longdate}|${level}|${processid}|${threadid}|${message}"
            concurrentWrites="false"
            keepFileOpen="true"
            encoding="iso-8859-2" />
    </target>
```

 - We need to have older logs(4-5 month old) some where on my archive sever but few logs on configured archive path in archiveFileName

**Comment by ashishgmishra** [comment]
In another way- Is it possible to get a notification when file target deletes the oldest archive file and any event can be added to the delete event? In that way same can be achieved.

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, please let us know!
