### ISSUE TITLE
VERACODE - nLog Scan Issues - SQL Injection and Untrusted Initialization

### ISSUE THREAD

**Issue by syedmdanish** [NLog/NLog#3874]
We have been using VERACODE for scanning our .NET Core application and have been using nLog as logging framework. For logging to the database, we have been using the Stored procedure specified in nlog.config to insert the record in the log table.VERACODE team did some upgrades in their release 2 months back for more rigorous code checks after which the scans of the application started showing 2 HIGH errors associated with nLog.dll as below:

![image](https://user-images.githubusercontent.com/63002267/78152843-00590700-7458-11ea-9dc4-78a62890fec6.png)

![image](https://user-images.githubusercontent.com/63002267/78152890-11097d00-7458-11ea-8959-e77c93479473.png)

The nLog version we have using is 4.6.8 but we also tried with the latest version 4.7.0 and continue to receive the same Issue while scanning the application.
Any help would be appreciated in suggesting approaches to get us solving above Issues.

**Comment by snakefoot** [comment]
Hi ya. Guess there is special aprils foolsday offering on VERACODE today.

Looks like a duplicate of #3872 . Once again the whole idea with DatabaseTarget is to execute dynamic SQL.

**Comment by snakefoot** [comment]
I guess with NLog 5.0 then the DatabaseTarget will be extracted from the code NLog.dll so the warning will disappear. See also #2676

**Comment by snakefoot** [comment]
Maybe check if your VERACODE-tool supports ignoring specific errors/warnings for the NLog.dll-assembly (As config-exclude-file or parameter)

**Comment by 304NotModified** [comment]
Duplicate of https://github.com/NLog/NLog/issues/3872

**Comment by syedmdanish** [comment]
The issue #3872 mentions the SQL Injection flaw that we have raised but we do have additional Issue related to Untrusted Initialization for nLog.dll as provided in the screenshot which is not covered in that ticket:
![image](https://user-images.githubusercontent.com/63002267/78218029-bebd7000-74da-11ea-8cdf-07fdd8da5676.png)

Any help regarding this Issue would be appreciated.

**Comment by snakefoot** [comment]
My eyes are and your image is very blurry. Can only see something with OpenConnection (Sounds like database target again) . Can you provide a better screenshot or explain the issue yourself?


Sent from my Sony Xperia


---- syedmdanish wrote ----


The issue #3872<https://github.com/NLog/NLog/issues/3872> mentions the SQL Injection flaw that we have raised but we do have additional Issue related to Untrusted Initialization for nLog.dll as provided in the screenshot which is not covered in that ticket:
[image]<https://user-images.githubusercontent.com/63002267/78218029-bebd7000-74da-11ea-8cdf-07fdd8da5676.png>

Any help regarding this Issue would be appreciated.

**Comment by 304NotModified** [comment]
This is about openconnection and the same applies as for #3872.

The connectionstring is rendered from a layoutable value. This could be potential be vulnerable for injection, when the user doesn't validate things well.  This is beyond our control and so we can't change it. We are the library / framework. The user is the only one how knows what should be in the connectionstring.

**Comment by snakefoot** [comment]
NLog 5.0 will extract the DatabaseTarget into its own nuget-package.
