### ISSUE TITLE
Remove nuget-package NLog.config for NLog 5.0

### ISSUE THREAD

**Issue by snakefoot** [NLog/NLog#3882]
People are slowly moving to csproj-format with `<packagereference>`, and are constantly reminded not to put this knife in their eye:

https://www.nuget.org/packages/NLog.config

The advice on the nuget-package description is not-to-use. The advice on nlog-install-guide is not-to-use.

Instead of giving everyone a bad experience, and unwanted side-effects coming as a surprise, then I think the nuget-package should be deprecated. And stop releasing new versions of it.

The best thing would ofcourse be to correct all existing NLog-install-guides in the world, so they will not mention this now broken nuget-package.

**Comment by 304NotModified** [comment]
Yes this is needed. Would be nice to (easy) set up a configuration another way.
