### ISSUE TITLE
[SOLVED] NO logs on MONO / Debian

### ISSUE THREAD

**Issue by massimob64** [NLog/NLog#3885]
Hello everyone,

I developed my webservice with VS 2019 on Windows 10 / Windows 2016, and NLog works very well.
Brought on Linux - Debian + Mono it does not write any log line in any way, even internally, below the configuration file.
Is there any compatibility problem?
Thanks for your suggestions / indications.

![nlog](https://user-images.githubusercontent.com/63377596/78843359-e0e74e80-7a02-11ea-880c-e5827075e18a.PNG)

**Comment by massimob64** [comment]
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="true"
      internalLogToConsole="true"
      internalLogLevel="Debug" internalLogFile="/var/log/nlog-internal.log">

  
  <variable name="myvar" value="myvalue"/>

  

  <targets async="true">
    <target name="f" xsi:type="File" fileName="/var/log/${shortdate}.log"
            layout="${time} ${uppercase:${level}} ${message}" />
  </targets>


  <rules>
    <logger name="*" minlevel="Debug" writeTo="f" />
  </rules>
</nlog>

**Comment by massimob64** [comment]
..............................
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="true"
      internalLogToConsole="true"
      internalLogLevel="Debug" internalLogFile="/var/log/nlog-internal.log">

  
  <variable name="myvar" value="myvalue"/>

  

  <targets async="true">
    <target name="f" xsi:type="File" fileName="/var/log/${shortdate}.log"
            layout="${time} ${uppercase:${level}} ${message}" />
  </targets>


  <rules>
    <logger name="*" minlevel="Debug" writeTo="f" />
  </rules>
</nlog>
........

**Comment by 304NotModified** [comment]
Hi, please check [troubleshooting guide](https://github.com/NLog/NLog/wiki/Logging-troubleshooting). If this is still an issue, please post the full internal log (trace level)

**Comment by massimob64** [comment]
I used this statement in the nlog.config and internal log found that the correct authentication for writing to the folder was missing.

<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="false"
      throwConfigExceptions="true"
      internalLogToConsole="true"
      internalLogLevel="Debug" 
      internalLogFile="/var/log/nlog-internal.log">
