### ISSUE TITLE
Escaping }  doesnt work quite right

### ISSUE THREAD

**Issue by BillDinger** [NLog/NLog#3886]
**NLog version**: 4.7.0

**Platform**:  .Net 4.5 /

**Current NLog config** (xml or C#, if relevant)

```
<nlog internalLogLevel="Debug" internalLogFile="C:\temp\NLog.Internal.txt" internalLogToConsole="true" throwConfigExceptions="true" xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <variable name="maskedMessage" value="${replace:inner=${message}:searchFor=(((\\d{3\}-\\d{2\}-\\d{4\})|(\\s\\d{9\}\\s))|((\\s\\d{3\}\\s)|(\\W\\d{3\}\\W))|((\\s\\d{15,19\}\\s)|(\\W\\d{15,19\}\\W)))+:replaceWith=***MASKED***:regex=true}" />
    <variable name="GostLayout" value="${maskedMessage}" />
    <targets>
      <target name="file" 
layout="${GostLayout}" 
fileName="${basedir}/logs/Indenrollgp.${shortdate}.txt" 
maxArchiveFiles="90" 
archiveAboveSize="102400" 
maxArchiveDays="14" xsi:type="File"
 keepFileOpen="True" 
openFileCacheTimeout="30" />
    </targets>
    <rules>
      <logger name="*" minlevel="Debug" writeTo="file" />
    </rules>
  </nlog>

```

- What is the current result?
```
2020-04-08 20:19:42.3055 Debug Setting 'ReplaceLayoutRendererWrapper.searchFor' to '(((\d{3}-\d{2}-d{4})|(sd{9}s))|((sd{3}s)|(Wd{3}W))|((sd{15,19}s)|(Wd{15,19}W)))
```

- What is the expected result?
`(((\d{3}-\d{2}-\d{4})|(\s\d{9}\s))|((\s\d{3}\s)|(\W\d{3}\W))|((\s\d{15,19}\s)|(\W\d{15,19}\W)))+`

According to the [content escape rules](https://github.com/NLog/NLog/wiki/Configuration-file#content-escaping) we should only need to escape the `}` inside the regex. When we do this though the `searchFor` gets set to `(((d{3}-d{2}-d{4})|(sd{9}s))|((sd{3}s)|(Wd{3}W))|((sd{15,19}s)|(Wd{15,19}W)))+` so I attempted adding `\` to try and escape backslashes and that gets the result above. What it should output is the regex above. What it actually captures is in the log above.

- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
Yes

- Please post full exception details (message, stacktrace, inner exceptions)
no exception, just parsing the configuration.

- Are there any workarounds? 
I haven't tried this in fluent code yet, will do and report back. Its _possible_ this is a config file only issue.

- Is there a version in which it did work? 
No

- Can you help us by writing an unit test?
Yep!

**Comment by snakefoot** [comment]
I can only say it works on my machine. When using your NLog-config-example, then I get the following output:

```
2020-04-09 12:02:00.9625 Debug Setting 'ReplaceLayoutRendererWrapper.searchFor' to '(((\d{3}-\d{2}-\d{4})|(\s\d{9}\s))|((\s\d{3}\s)|(\W\d{3}\W))|((\s\d{15,19}\s)|(\W\d{15,19}\W)))+'
2020-04-09 12:02:00.9738 Debug Setting 'ReplaceLayoutRendererWrapper.searchFor' to '(((\d{3}-\d{2}-\d{4})|(\s\d{9}\s))|((\s\d{3}\s)|(\W\d{3}\W))|((\s\d{15,19}\s)|(\W\d{15,19}\W)))+'
2020-04-09 12:02:01.0017 Debug Setting 'ReplaceLayoutRendererWrapper.searchFor' to '(((\d{3}-\d{2}-\d{4})|(\s\d{9}\s))|((\s\d{3}\s)|(\W\d{3}\W))|((\s\d{15,19}\s)|(\W\d{15,19}\W)))+'
```

This the NLog-config that I copy/pasted from you:

```xml
<nlog internalLogLevel="Debug" internalLogFile="C:\temp\NLog.Internal.txt" internalLogToConsole="true" throwConfigExceptions="true" xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <variable name="maskedMessage" value="${replace:inner=${message}:searchFor=(((\\d{3\}-\\d{2\}-\\d{4\})|(\\s\\d{9\}\\s))|((\\s\\d{3\}\\s)|(\\W\\d{3\}\\W))|((\\s\\d{15,19\}\\s)|(\\W\\d{15,19\}\\W)))+:replaceWith=***MASKED***:regex=true}" />
  <variable name="GostLayout" value="${maskedMessage}" />
  <targets>
    <target name="file"
layout="${GostLayout}"
fileName="${basedir}/logs/Indenrollgp.${shortdate}.txt"
maxArchiveFiles="90"
archiveAboveSize="102400"
maxArchiveDays="14" xsi:type="File"
 keepFileOpen="True"
openFileCacheTimeout="30" />
  </targets>
  <rules>
    <logger name="*" minlevel="Debug" writeTo="file" />
  </rules>
</nlog>
```

**Comment by BillDinger** [comment]
@snakefoot tahnk you for double checking me and for uncovering the root cause - there was a hidden character in the source that didnt get moved over here to github when I copy pasted hence why it worked for you (and why it worked for me when I copy & pasted it back).

Going to take this opportunity though to submit a PR to update the replace documentation to let folks know with Regex to pay attention to the scaping rules and the fact you have to escape both `}` and `\` which are both pretty common in regex. Appreciate the help!

**Comment by snakefoot** [comment]
@BillDinger Happy to hear you found the missing puzzle piece. You are also welcome to update the wiki-page:

https://github.com/nlog/NLog/wiki/Replace-Layout-Renderer

**Comment by BillDinger** [comment]
@snakefoot  https://github.com/NLog/NLog/wiki/Replace-Layout-Renderer done! Thanks so much for the help!
