### ISSUE TITLE
Target for azure file system (file shares)

### ISSUE THREAD

**Issue by lucianaparaschivei** [NLog/NLog#3887]
Hello!
I have created a custom target for microsoft azure file system and want to make it publicly available so everyone can use it. I checked and the current available targets for azure do not include support for azure file system (file shares).
Can it be added to the custom targets available here: [Targets](https://nlog-project.org/config/?tab=targets)  

Here is my repo and nuget link: [Github](https://github.com/lucianaparaschivei/NLog.Extensions.AzureFileSystem)

What do you think?

**Comment by 304NotModified** [comment]
Sounds good! You could add your target here: https://github.com/NLog/NLog.github.io/blob/master/config/targets.json
