### ISSUE TITLE
UWP impossible to use file based Targets

### ISSUE THREAD

**Issue by msavazzi** [NLog/NLog#3893]
**NLog version**: Nuget Package 4.70

**Platform**: UWP

**Current NLog config** 
```<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="true"
      internalLogLevel="Debug" internalLogFile="c:\temp\nlog-internal.log">

  <!-- optional, add some variables
  https://github.com/nlog/NLog/wiki/Configuration-file#variables
  -->
  <variable name="myvar" value="myvalue"/>

  <!--
  See https://github.com/nlog/nlog/wiki/Configuration-file
  for information on customizing logging rules and outputs.
   -->
  <targets>

    <!--
    add your targets here
    See https://github.com/nlog/NLog/wiki/Targets for possible targets.
    See https://github.com/nlog/NLog/wiki/Layout-Renderers for the possible layout renderers.
    -->

    <target name="console" 
            xsi:type="Console"  
            layout="${longdate} ${callsite} ${level} ${message}"/>
    
    <!--
    Write events to a file with the date in the filename.
    <target xsi:type="File" name="f" fileName="${basedir}/logs/${shortdate}.log"
            layout="${longdate} ${uppercase:${level}} ${message}" />
    <target name="logfile" xsi:type="File"
        layout="${longdate} ${logger} ${message}${exception:format=ToString}"
        fileName="${var:LogPath}/logfile.txt"
        keepFileOpen="true"
        encoding="utf-8" />

    <target name="csvlog" xsi:type="File" fileName="${var:LogPath}/logfile.csv">
      <layout xsi:type="CsvLayout" delimiter="Tab" withHeader="false">
        <column name="time" layout="${longdate}" quoting="Nothing" />
        <column name="level" layout="${level:upperCase=true}" quoting="Nothing"/>
        <column name="message" layout="${message}" quoting="All" />
        <column name="exception" layout="${exception:format=ToString}" quoting="All"/>
      </layout>
    </target>
    -->
    <target name="log4view" xsi:type="NLogViewer" address="tcp://127.0.0.1:878"
                 KeepConnection="false" OnConnectionOverflow="Block" MaxConnections="5" />
  </targets>

  <rules>
    <!-- add your logging rules here -->
    <logger name="*" minlevel="Debug" writeTo="console" />
    <logger name="*" minlevel="Debug" writeTo="log4view" />

    <!--
    <logger name="*" minlevel="Debug" writeTo="logfile" />
    <logger name="*" minlevel="Debug" writeTo="csvlog" />
    Write all events with minimal level of Debug (So Debug, Info, Warn, Error and Fatal, but not Trace)  to "f"
    <logger name="*" minlevel="Debug" writeTo="f" />
    -->
  </rules>
</nlog>
```

- What is the current result? 
If I activate the file based loggers I get an error:

> System.UnauthorizedAccessException: 'Access to the path 'Global\NLog-FileFileLock-c:_users_massimo_appdata_local_packages_b8d9ddbf-3205-467c-af1b-462d24801107_zajsc8zqgb60r_localstate_logfile.txt' is denied.'

It does not change if I put it in the Roaming folder, in a direct folder. I've even tried to add:

`  xmlns:rescap="http://schemas.microsoft.com/appx/manifest/foundation/windows10/restrictedcapabilities"
    <rescap:Capability Name="broadFileSystemAccess" />
`

With no success. Note is NOT a good idea to do so as the checks from the Marketplace are much stronger if that Capability is requested. It would not be wise for "just" logging purposes.

- What is the expected result?
To have the files correctly genrated
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
Is not able to create them too :( as is not able to write to files
- Please post full exception details (message, stacktrace, inner exceptions)

- Are there any workarounds? yes/no
NO
- Is there a version in which it did work? 
not that I'm aware of
- Can you help us by writing an unit test?
Is very simple:
1) open visual studio 2019
2) create new project
3) select project time UWP, language C# 
4) Select Windows Template Studio
5) add what you like :) and create project
6) NuGet manager - add NLog
7) create Nlog configuration, enable NLog exceptions
8) add a log line in the App initialize:
`            Windows.Storage.StorageFolder storageFolder = Windows.Storage.ApplicationData.Current.LocalFolder;
NLog.LogManager.Configuration.Variables["LogPath"] = storageFolder.Path;
            Logger.Info("Initializer");
`
as per examples.
9) run

**Comment by snakefoot** [comment]
This error:

`System.UnauthorizedAccessException: 'Access to the path 'Global\NLog-FileFileLock-c:_users_massimo_appdata_local_packages_b8d9ddbf-3205-467c-af1b-462d24801107_zajsc8zqgb60r_localstate_logfile.txt' is denied.`

Is because you are using ConcurrentWrites=true (the default value).  You need to explicitly specify `keepFileOpen="true"  concurrentWrites="false"`:

```xml
    <target xsi:type="File" name="f" fileName="${basedir}/logs/${shortdate}.log"
            keepFileOpen="true" concurrentWrites="false"
            layout="${longdate} ${uppercase:${level}} ${message}" />

    <target name="logfile" xsi:type="File"
        layout="${longdate} ${logger} ${message}${exception:format=ToString}"
        fileName="${var:LogPath}/logfile.txt"
        keepFileOpen="true" concurrentWrites="false"
        encoding="utf-8" />

    <target name="csvlog" xsi:type="File" fileName="${var:LogPath}/logfile.csv" keepFileOpen="true"  concurrentWrites="false">
      <layout xsi:type="CsvLayout" delimiter="Tab" withHeader="false">
        <column name="time" layout="${longdate}" quoting="Nothing" />
        <column name="level" layout="${level:upperCase=true}" quoting="Nothing"/>
        <column name="message" layout="${message}" quoting="All" />
        <column name="exception" layout="${exception:format=ToString}" quoting="All"/>
      </layout>
    </target>
```

I'm trying to convince people that `concurrentWrites="false"` is a better default-value for all platforms.  And it should be changed with NLog 5.0 But it is still work-in-progress. See also: #3048

**Comment by msavazzi** [comment]
with that it works

**Comment by snakefoot** [comment]
I guess you can make use of the layoutrenderer `${specialfolder}`. See also: https://github.com/NLog/NLog/wiki/File-target#filename-directory

The configuration of file-permissions for UWP-applications from App-Store is not something NLog can do much about.

- https://docs.microsoft.com/en-us/windows/uwp/files/file-access-permissions#application-data-locations
- https://docs.microsoft.com/en-us/windows/uwp/files/file-access-permissions#accessing-additional-locations

Maybe you can give a hint of what error you are getting. It is hard to guess what walls you are banging your head into. But I think you will have better luck with UWP-file-permissions questions on StackOverflow than here.

**Comment by hooligan495** [comment]
I've been doing some research on this and if my UWP Application has declared BroadFileSystemAccess Windows should let me be able to create files outside the sandbox.  BUT my application has to use the Windows.STorage APIs.   In my UWP app I turned on BroadfileSystemAccess and tried to set the location in My NLOG config to point to C:\Temp.   I get an Unauthorized access exception.  And doing some debugging I see that the first place this happens is when NLog calls to File.IO.FileInfo in teh BaseFileAppender.   So it seems this class is not using the Windows STorage APIs when used in a UWP application.  The File.IO apis are only allowed IN the sandbox of UWP (applicationLocation).   The reason for this is that the StorageAPI allows the owner of the computer to override an app's broadfilesystem access policy.   The File.IO APIs don't use the Windows policies around this.  

So.  
I'd be interested in trying to make this work/explore building a PR.  where we use the Windows StorageAPIs do you have pointers within the NLog knowledge sphere of the best way to approach this?  Should I look at inserting more Compile time checks?  or maybe make a BaseUWPFileAppender type of thing?   

Thanks

**Comment by snakefoot** [comment]
@hooligan495 See also #4136
