### ISSUE TITLE
${aspnet-request-posted-body} not returning data

### ISSUE THREAD

**Issue by husseinshaib1** [NLog/NLog#3906]
hi I am trying to use Http target to send the log to an API.
```
<target name='HTTP'
		type='HTTP'
		URL='https://localhost:44331/api/companies/logs'
		Method='POST'
		BatchSize='100000'
        MaxQueueSize='2147483647'
        IgnoreSslErrors='true'
        FlushBeforeShutdown='true'
        ContentType='application/json'
        Accept='application/json'
        DefaultConnectionLimit='2'
        Expect100Continue='false'
        UseNagleAlgorithm='true'
        ConnectTimeout='30000' 
        InMemoryCompression='true'>
			<layout type='JsonLayout'>
				<attribute name='sourcetype' layout='_json' />
				<attribute name='host' layout='${machinename}' />
				<attribute name='requestbody' layout='${aspnet-request-posted-body}' />
				<attribute name='event' encode='false'>
					<layout type='JsonLayout'>
						<attribute name='level' layout='${level:upperCase=true}' />
						<attribute name='source' layout='${logger}' />
						<attribute name='thread' layout='${threadid}' />
						<attribute name='message' layout='${message}' />
						<attribute name='utc' layout='${date:universalTime=true:format=yyyy-MM-dd HH\:mm\:ss.fff}' /></layout>
				</attribute>
			</layout>
		</target>
requestbody param is always empty. any thing I am missing?

**Comment by 304NotModified** [comment]
Please tell is at least:

```
> Hi! Thanks for reporting this feature/bug/question! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

QUESTIONS are preferred on StackOverflow. You could expect a faster response there (but do include all the info below). Use the tag "nlog" https://stackoverflow.com/questions/ask

For .NET Core users, please check the platform support: https://github.com/NLog/NLog/wiki/platform-support

**NLog version**: (e.g. 4.4.13)

**Platform**: .Net 3.5 / .Net 4.0 / .Net 4.5 / Mono 4 / Silverlight 4 / Silverlight 5 / Xamarin Android / Xamarin iOs / .NET Core 1 / .NET Core 2 / .NET Core 3
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
```

**Comment by 304NotModified** [comment]
Asp.net or asp.net core? If asp.net core, which version?

**Comment by husseinshaib1** [comment]
hi , I am using
 NLog 4.7.0
 Nlog.Target.Http 1.0.1
Nlog.web.AspNet.Core 4.9.1
internal logging first was indicating : Warn Exception in 'NLog.Web.LayoutRenderers.AspNetRequestPostedBody.Append()' Exception: System.InvalidOperationException: Synchronous operations are disallowed. Call ReadAsync or set AllowSynchronousIO to true instead.
After googling I found that I must add 
 services.Configure<IISServerOptions>(options =>
 {
     options.AllowSynchronousIO = true;
  });
to the startup file. this is ll I got from internal logging of NLog.
After fixing this error no more errors occured but still same issue

**Comment by 304NotModified** [comment]
I also was typing at SO already. I will close this one in favor of https://stackoverflow.com/questions/61306722/aspnet-request-posted-body-not-returning-data

Please check there is the answer has what you need

**Comment by snakefoot** [comment]
Thanks to @bakgerman now NLog.Web.AspNetCore v5.1 re-introduces [${aspnet-request-posted-body}](https://github.com/NLog/NLog/wiki/AspNet-Request-posted-body-layout-renderer) with help from middleware:
```c#
app.UseMiddleware<NLog.Web.NLogRequestPostedBodyMiddleware>();
```
It is no longer necessary to explicit call `context.Request.EnableBuffering();` as it is handled by the middleware.
