### ISSUE TITLE
How to stop multiple rows in logging error

### ISSUE THREAD

**Issue by Vishnu-Datta** [NLog/NLog#3907]
Hello Team,

I'm new to NLog. I'm working on v4.7 to implement logging through file target. Based on various levels provided, I had noticed below while logging

1. For "Debug" level, for each message, only one line of text is added to file
2. For "Info" level, for each message, two lines of text is added to file
3. For "Error" level, for each message, three lines of text is added to file

I think, irrespective of level, the text added to log file should be single line., for this I added attribute concurrentWrites="false" for file target. But this didn't worked.

Is this a bug ? or should I need to add something?

Thanks in advance

**Comment by 304NotModified** [comment]
Yes it's probably a bug in your `<rules>` ;)

Please note, all the  `<rules>`  are used for top to bottom. If one match, it still goes on to the next (unless you say so it should not)

**Comment by Vishnu-Datta** [comment]
Hi @304NotModified 

Per you suggestion "_Please note, all the <rules> are used for top to bottom. If one match, it still goes on to the next_", I kept only those rules which I wanted, and it worked as expected.

So does this mean, we can't continue to use more than one level of rule at a time?
And if used, multiple lines are logged ?

**Comment by 304NotModified** [comment]
> So does this mean, we can't continue to use more than one level of rule at a time?
> And if used, multiple lines are logged ?

Sure you can, but please share your config, current and expected result. It's a bit of guessing now
