### ISSUE TITLE
NLog Hangs & pushes gigabytes of data into logfile

### ISSUE THREAD

**Issue by GerwinFleurop** [NLog/NLog#3911]
Heey,

We're using NLOG for an application of ours, that logs a lot of data,

From time to time we randomly find a very big log file (anyway where from a gigabyte, to multiple)
Where there's just 1 line where it says the exact date / time, and the rest is just the same data over & over again, but seemingly from multiple different pages?

Does this sound familair, has anyone seen this strange behaviour before?

It looks like NLog just kinda gets stuck, we don't log anything in looks so it's a really interesting problem.

**Comment by snakefoot** [comment]
Sound a little like this bug #3345
