### ISSUE TITLE
How to encrypt a profile  and make Output log encryption

### ISSUE THREAD

**Issue by gitlsl** [NLog/NLog#3916]
````
   <logger name="*"   writeTo="file" />
    <logger name="*"   writeTo="console" />
````
 
The clear text configuration file will be manually modified to the log level, so we want to encrypt the configuration file
At the same time, can the log be encrypted when outputting?

I found a circle that didn't seen any relevant examples, how do you think of this opinion?thanks

**Comment by 304NotModified** [comment]
> The clear text configuration file will be manually modified to the log level, so we want to encrypt the configuration file

You could configure NLog in the web.config and encrypt it: https://docs.microsoft.com/en-us/previous-versions/aspnet/dtkwfdky%28v%3dvs.100%29



> At the same time, can the log be encrypted when outputting?

There isn't a support for it, but you could make a custom target wrapper or layout wrapper: https://github.com/nlog/nlog/wiki/Extending-NLog

**Comment by gitlsl** [comment]
@304NotModified   

> You could configure NLog in the web.config and encrypt it

it only support when use web,config ,  how about   console . winform,wpf
If we can pass   `config string` to init   by  code   can be very useful

**Comment by 304NotModified** [comment]
Yes, or app.config

https://stackoverflow.com/questions/3349551/encrypting-app-config-file

**Comment by 304NotModified** [comment]
Anyway, Maybe using a config from code is better, as from runtime it's never encrypted anyway.

**Comment by snakefoot** [comment]
@gitlsl Sounds like a great idea for an NLog-extension-package. Please share when you having something working.
