### ISSUE TITLE
ColoreConsoleTarget throws exception when colorizing words when no word row highlighting rules set

### ISSUE THREAD

**Issue by mariusin79** [NLog/NLog#3917]
```c#
private void WriteToOutputWithColor(LogEventInfo logEvent, string message)

// this will enable word highlighting if \n, event without word highlighting rules: 
bool wordHighlighting = !ReferenceEquals(colorMessage, message) || message?.IndexOf('\n') >= 0;

WriteToOutputWithPrinter:

ColorizeEscapeSequences(_consolePrinter, consoleWriter, colorMessage, oldForegroundColor, oldBackgroundColor, rowForegroundColor, rowBackgroundColor);

var foreground = (ConsoleOutputColor)(c2 - 'A');
consolePrinter.ChangeForegroundColor(consoleWriter, currentForegroundColor);
```

```
stacktrace:

The ConsoleColor enum value was not defined on that enum. Please use a defined color from the enum.
   at System.ConsolePal.ConsoleColorToColorAttribute(ConsoleColor color, Boolean isBackground)
   at System.ConsolePal.set_ForegroundColor(ConsoleColor value)
   at NLog.Targets.ColoredConsoleSystemPrinter.ChangeForegroundColor(TextWriter consoleWriter, Nullable`1 foregroundColor)
   at NLog.Targets.ColoredConsoleTarget.ColorizeEscapeSequences(IColoredConsolePrinter consolePrinter, TextWriter consoleWriter, String message, Nullable`1 defaultForegroundColor, Nullable`1 defaultBackgroundColor, Nullable`1 rowForegroundColor, Nullable`1 rowBackgroundColor)
   at NLog.Targets.ColoredConsoleTarget.WriteToOutputWithPrinter(TextWriter consoleStream, String colorMessage, Nullable`1 newForegroundColor, Nullable`1 newBackgroundColor, Boolean wordHighlighting)
   at NLog.Targets.ColoredConsoleTarget.WriteToOutputWithColor(LogEventInfo logEvent, String message)
   at NLog.Targets.ColoredConsoleTarget.WriteToOutput(LogEventInfo logEvent, String message)
   at NLog.Targets.Target.Write(AsyncLogEventInfo logEvent)
   at NLog.Targets.Target.WriteAsyncThreadSafe(AsyncLogEventInfo logEvent)
   at NLog.Targets.Target.WriteAsyncLogEvent(AsyncLogEventInfo logEvent)
   at NLog.LoggerImpl.WriteToTargetWithFilterChain(Target target, FilterResult result, LogEventInfo logEvent, AsyncContinuation onException)
   at NLog.LoggerImpl.Write(Type loggerType, TargetWithFilterChain targetsForLevel, LogEventInfo logEvent, LogFactory factory)
```

**Comment by snakefoot** [comment]
Thank you for reporting this. Possible you could paste your NLog.config-file into the issue? And maybe a small code-example that triggers this exception? It would really help a lot.

**Comment by mariusin79** [comment]
<?xml version="1.0" encoding="utf-8"?>

<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="true"
      internalLogLevel="Off" internalLogFile="c:\dibs\nlog-internal.log">

  <include file="logsettings.config" />
  <targets>
    <default-wrapper xsi:type="AsyncWrapper" queueLimit="10000" overflowAction="Discard"
                     timeToSleepBetweenBatches="20" fullBatchSizeWriteLimit="5" batchSize="200"
                     optimizeBufferReuse="true" />

    <target name="fileIfApplicable" xsi:type="FilteringWrapper"
            condition="'${environment:DOTNET_RUNNING_IN_CONTAINER}' != 'true'">
      <target name="file"
              xsi:type="File"
              fileName="${configsetting:name=LogFolder}\${appName}.${date:format=yyyyMMddHH}.json.log"
              maxArchiveFiles="72"
              encoding="utf-8">
        <layout xsi:type="FastJsonLayoutToUseIfAllLogEventPropertiesAreImmutable" includeAllProperties="true">
          <attribute name="timestamp" layout="${date:format=yyyy-MM-dd HH\:mm\:ss.ffff K}" />
          <attribute name="logLevel" layout="${level:upperCase=true}" />
          <attribute name="subsystem" layout="${subsystem}" />
          <attribute name="application" layout="${appName}" />
          <attribute name="applicationVersion" layout="${appVersion}" />
          <attribute name="applicationLongVersion" layout="${appLongVersion}" />
          <attribute name="machineName" layout="${machinename}" />
          <attribute name="logMessage" layout="${message}" />
          <attribute name="exception" layout="${exception:format=tostring:maxinnerexceptionlevel=10}" />
        </layout>
      </target>
    </target>

    <target name="consoleIfApplicable" xsi:type="FilteringWrapper"
            condition="'${environment:DOTNET_RUNNING_IN_CONTAINER}' == 'true'">
      <target name="console"
              xsi:type="ColoredConsole"
              detectConsoleAvailable="true"
              layout="${date:format=yyyy-MM-dd HH\:mm\:ss.ffff K} | ${level:upperCase=true} | ${message} | ${exception:format=tostring:maxinnerexceptionlevel=10}">
      </target>
    </target>

    <target name="consoleIfApplicableBug" xsi:type="FilteringWrapper"
            condition="'${environment:DOTNET_RUNNING_IN_CONTAINER}' == 'true'">
        <target name="stdConsole"
                xsi:type="Console"
                detectConsoleAvailable="true"
                layout="${date:format=yyyy-MM-dd HH\:mm\:ss.ffff K} | ${level:upperCase=true} | ${message} | ${exception:format=tostring:maxinnerexceptionlevel=10}">
        </target>
    </target>
  </targets>
  <rules>
    <logger name="Services.Steps.Api.*" final="true" maxLevel="Debug" writeTo="consoleIfApplicable, consoleIfApplicableBug" />
  </rules>
</nlog>

**Comment by snakefoot** [comment]
Thank you. Have created PR #3918 to fix this.

Btw. you should consider changing this:

`condition="'${environment:DOTNET_RUNNING_IN_CONTAINER}' == 'true'"`

Into this (Adding `cached=true`):

`condition="'${environment:DOTNET_RUNNING_IN_CONTAINER:cached=true}' == 'true'"`

**Comment by snakefoot** [comment]
@mariusin79 It would be a great help if you could test this pre-release nuget-package to see if it resolves your issue:

https://ci.appveyor.com/project/nlog/nlog/builds/32386722/artifacts

Just download `NLog.4.7.0.11601-PR3918.nupkg` and put in a local nuget-repository-folder, then you can try it out.

**Comment by mariusin79** [comment]
thank you I will test it tomorrow

**Comment by snakefoot** [comment]
Any update on the test results?


---- Marius Ingjer wrote ----


thank you I will test it tomorrow

**Comment by mariusin79** [comment]
I will have to test on monday

**Comment by mariusin79** [comment]
I am not currently able to reproduce the original bug, I don't have the exact string which caused the issue, its a base64 encoded hash which takes a time factor into consideration. I will notify if I am able to reproduce this later.

**Comment by mariusin79** [comment]
Tested: was finally able to reproduce a string which caused error, downloaded and installed the prerelease package, bug was gone.

**Comment by snakefoot** [comment]
@mariusin79 NLog 4.7.1 has now been released.
