### ISSUE TITLE
Customize serialization on one logger?

### ISSUE THREAD

**Issue by snowjim** [NLog/NLog#3922]
Hi,

I got solution with several clients and services that uses NLog to log info objects and exceptions, now this needs to extended to all communication as well.

A communication NLogger have been added to not effect the general one. The new logger will in default mode only log timestamp, duration, operation, client and service.  In runtime we need to be able to include all parameters and how depth the serialization should go. Everything on a parameter object needs to be saved, even object fields and default getters(Most prameter objects have DataContract attributes).

All this needs to be logged to file in a structured JSON format so it could be sent to ElasticSearch.

Code so far 

Info buildup.
```
public void LogCommunication(string operation, TimeSpan duration, List<object> args)
        {

            var parameters = new List<Object>();

            var strcuteredMesage = "TimeStamp {TimeStamp}";
            parameters.Add(DateTime.Now.ToString("yyyy/MM/dd H:mm:ss:fff"));

            strcuteredMesage += ", Duration {Duration}";
            parameters.Add(duration.ToString());

            strcuteredMesage += ", Operation {Operation}";
            parameters.Add(operation);

            strcuteredMesage += ", PersonId {PersonId}";
            parameters.Add(SharedContext.GetMyUserContext().CurrentPersonId.ToString());

            strcuteredMesage += ", Servername {Servername}";
            parameters.Add(Environment.MachineName);

            strcuteredMesage += ", ClientMachineName {ClientMachineName}";
            parameters.Add(SharedContext.GetMyUserContext().ClientMachineName);

            if(args != null)
                foreach(var obj in args)
                {
                    var typeName = $"{args.GetType().Namespace.Split('.').Last()}.{args.GetType().Name}";
                    strcuteredMesage += ", " + typeName + " {@" + typeName + "}";
                    parameters.Add(obj);
                }
            _log.LogCommunication(strcuteredMesage, parameters.ToArray());
        }
```
NLog Config 

```
<target xsi:type="File" name="communicationTarget" fileName="${basedir}/logs/${shortdate}.log">
      <layout xsi:type="JsonLayout" includeAllProperties="true" maxRecursionLimit="10">
      </layout>
    </target>

<logger name="CommunicationLogger" minlevel="Info" writeto="communicationTarget"></logger>
```
The problem with this solution is that not all fields is serialized, to solve this I have tried several solutions : 

1. RegisterObjectTransformation like this 
```
LogManager.Setup().SetupSerialization(s =>
                   s.RegisterObjectTransformation<Orbit.ServiceContracts.GetEntityViewResponse>(obj => Newtonsoft.Json.Linq.JToken.FromObject(obj)));
```
There is however not just 1 class but 500-1000 classes that need to be added.

2. Add a custom ValueFormatter like this : 

`NLog.Config.ConfigurationItemFactory.Default.ValueFormatter = new NLogValueFormatter();`

```
public class NLogValueFormatter : IValueFormatter
    {
        public bool FormatValue(object value, string format, CaptureType captureType, IFormatProvider formatProvider, StringBuilder builder)
        {

            if (value.GetType() == typeof(LogData))
                return false;
            
            builder.Append(format);

            try
            {

                var myTarget = LogManager.Configuration.FindTargetByName("communicationTarget");
                myTarget = ((myTarget as NLog.Targets.Wrappers.WrapperTargetBase)?.WrappedTarget) ?? myTarget;
                var jsonLayout = (myTarget as NLog.Targets.TargetWithLayout)?.Layout as NLog.Layouts.JsonLayout;

                if (jsonLayout?.MaxRecursionLimit > 0)
                {
                    var jsonSettings = new JsonSerializerSettings() { MaxDepth = jsonLayout?.MaxRecursionLimit };
                    using (var stringWriter = new StringWriter())
                    {
                        using (var jsonWriter = new JsonTextWriterMaxDepth(stringWriter, jsonSettings))
                            JsonSerializer.Create(jsonSettings).Serialize(jsonWriter, value);
                        builder.Append(stringWriter.ToString());
                    }
                }
                else
                    value = null;
            }
            catch(Exception ex)
            {
                builder.Append($"Failed to serlize {value.GetType()} : {ex.ToString()}");
            }
            return true;
        }

    }
```
 This solution have been working best but the problem with it is that the generall logger will be affected and im not sure that its correct to read the MAXDepth manually from the config file in runtime.

So how should this be solved with NLog?

Regards

**Comment by snakefoot** [comment]
Have been thinking about you here. #3920

Again one of the core-principles in NLog is that the Logger should not care about the configured targets, and how targets decides to serialize the objects.

Right now you are telling the Logger (via formatter) how to do the serialization, because you have discovered that NLog-Targets (via JsonLayout) fails to handle field-members on your many objects.

Instead of implementing this formatter-hack, then I would prefer a solution where it is possible for you to configure the NLog-target (via JsonLayout) whether to serialize the whole object (using custom JsonSerializer that recognizes field-members) or just call object-ToString.

**Comment by snowjim** [comment]
I have done custom targets before, maybe I could write a custom target that do the JSON serialization to file? Could I read the MaxRecursionLimit from a custom target? Would that be a better way to handle this? Or is data already serlized at this stage?

**Comment by snakefoot** [comment]
If you click the link I posted, then you can see how to inject your own custom JsonSerializer. My idea was that NLog JsonLayout could be changed so it would not call the custom JsonSerializer when MaxRecursionLimit=0.

The ability to configure MaxRecursionLimit is a little over-engineered. There should probably only be the values MaxRecursionLimit=0 and MaxRecursionLimit=10.

So my thought was you didn't try to "read" MaxRecursionLimit from the JsonLayout. But instead had the translation. If MaxRecursionLimit=0 then the custom JsonSerializer is not called. If custom JsonSerializer is called then it should by default use MaxRecursionLimit=10.

When dealing with customizing output, then one should only consider writing a custom Layout, not to rewrite a custom Target. The custom Target is intended if wanting to redirect output to a whole new destination.

**Comment by snowjim** [comment]
Im not really following you, do you mean that with a custom JSON serializer I will be able to decide if I should serialize or not and on what level? How do I get the MaxRecurson level within this serializer? The example in the link do a regular json serializer without code to specify the deep or if it should be done at all?

**Comment by snakefoot** [comment]
You are completely correct that one cannot "see" the configured "MaxRecursionLimit" when using a custom JSON serializer.

I'm saying that JsonLayout should be changed to only call custom JSON serializer, when MaxRecursionLimit > 0.

And that the custom JSON serializer should by default expect that MaxRecursionLimit=10 when it is being called.

**Comment by snowjim** [comment]
So you suggest changes to the nLog source? What would be the solution for me in the meanwhile?

**Comment by snakefoot** [comment]
It would be nice if you could confirm if my suggestion would solve your issue. If not then it doesn't make sense to spend time on it.


One workaround would be to enumerate all types in your assemblies at runtime and for all types that has the datacontract class attribute  then call RegisterObjectTransformation and use JToken.FromObject




Sent from my Sony Xperia


---- snowjim wrote ----


So you suggest changes to the nLog source? What would be the solution for me in the meanwhile?

**Comment by snowjim** [comment]
So what you suggest is that the custom Json serializer will only be triggered if the MaxRecursionLimit is bigger den 0. But it will not use the MaxRecursionLimit value to determine how depth the serialization should go in objects?

If the entire object is logged without respect to depth then there will be way to much data logged to file. Some of our objects is REALLY big. 

Enumerate all types feels like a hack? And you get not as much control. 

At this point the IValueFormatter sounds like a better solution even if its not best practice.

Regards

**Comment by snakefoot** [comment]
Yes when custom Json Serialize is called then it will know that it should use a hard-coded default of MaxRecursionLevel=10 (And not serialize the entire world)


But it sounds like you don't like this solution. So I guess the only option that would work for you. Would be that one could specify that NLog JsonSerializer included fields.


Sent from my Sony Xperia


---- snowjim wrote ----


So what you suggest is that the custom Json serializer will only be triggered if the MaxRecursionLimit is bigger den 0. But it will not use the MaxRecursionLimit value to determine how depth the serialization should go in objects?

If the entire object is logged without respect to depth then there will be way to much data logged to file. Some of our objects is REALLY big.

Enumerate all types feels like a hack? And you get not as much control.

At this point the IValueFormatter sounds like a better solution even if its not best practice.

Regards

**Comment by snowjim** [comment]
We need to be able to set the rescursionlevel, this to keep the dataflow at a good level.

But as nLog works today, what is the best solution for this?

**Comment by snakefoot** [comment]
> We need to be able to set the rescursionlevel, this to keep the dataflow at a good level.

Happy that you like the ability to configure `MaxRecursionLimit`. Right now it is not possible for a custom JsonSerializer to tell what limit has been configured in the NLog JsonLayout.

If you have suggestions for how to improve the default NLog JsonSerializer or improve the integration with custom JsonSerializer, then please create a PR. Since my suggestions are not able to hit the nail.

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, please let us know!
