### ISSUE TITLE
.Net Core - config.addxmlfile xml namespaces are not supported. line 2, position 9.

### ISSUE THREAD

**Issue by bagalsamadhan** [NLog/NLog#3926]
**NLog version**: (e.g. 4.4.13)

**Platform**: .Net 3.5 / .Net 4.0 / .Net 4.5  .NET Core 2.1

**Current NLog config** (xml or C#, if relevant)
Getting error at line 'config.AddXmlFile("ValueStore.xml", optional: false, reloadOnChange: true);'
Error : config.addxmlfile xml namespaces are not supported. line 2, position 9.

```xml
<?xml version="1.0" encoding="iso-8859-1" standalone="no" ?>
<schema xmlns="http://www.w3.org/2000/10/XMLSchema" targetNamespace="http://forrad/20010817">
<simpleType name="MARKT" title="MARKT-TEST">
    <restriction base="string">
      <enumeration desc="" value=""/>
      <enumeration desc="No" value="N"/>
      <enumeration desc="Yes" value="J"/>
    </restriction>
  </simpleType>
</schema>
```

- What is the current result?config.addxmlfile xml namespaces are not supported. line 2, position 9
- What is the expected result? It should work
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
- Please post full exception details (message, stacktrace, inner exceptions)
- Are there any workarounds? yes - I tried to convert xml into json and it works. but when trying to read a file from Iconfiguration it tooks 2 minutes which is not expected.  
- Is there a version in which it did work? 
- Can you help us by writing an unit test?

**Comment by 304NotModified** [comment]
Hi,

What is the posted XML? That's not a nlog config xml?

Please read https://github.com/nlog/nlog/wiki/Configuration-file

Please edit your post and fill in the template. Otherwise we need to close this one.
