### ISSUE TITLE
New SonarQube issues

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#3931]
updated rules I guess

![image](https://user-images.githubusercontent.com/5808377/80530475-59ee1c00-8999-11ea-95d8-9b469828b2ab.png)

https://sonarcloud.io/project/issues?branch=dev&id=nlog2&resolved=false&types=BUG

**Comment by snakefoot** [comment]
Now zero bugs in the master-branch:

https://sonarcloud.io/dashboard/?id=nlog2&branch=master

**Comment by 304NotModified** [comment]
thanks!!
