### ISSUE TITLE
Unable to save aspnet-sessionid using NLog in .net framework application

### ISSUE THREAD

**Issue by Shilpakopparad** [NLog/NLog#3951]
`<target xsi:type="File"name="LogFileAppender"fileName="C:\Users\acer\Downloads\test1.txt"
        layout="${longdate} ${aspnet-sessionid} - ${message} "/>`

It is saving (as per layout) in target fileName like

2020-05-07 11:16:56.4047 - Global.asax.cs:Application_Start(): Application initializing, starting cache load

Unable to save aspnet-sesionid using NLog.

**Comment by snakefoot** [comment]
You have injected your own Session-Item-value called `"SessionID"`. You can extract such custom values like this:

`${aspnet-session:SessionID} `

See also: https://docs.microsoft.com/en-us/dotnet/api/system.web.httpsessionstatebase.item

**Comment by Shilpakopparad** [comment]
Hi sir,


I tried with below layout rendereder also , but still it's null
 ${aspnet-sessionid} .

Thanks,
Shilpa

**Comment by snakefoot** [comment]
It is ${aspnet-session:SessionID


Sent from my Sony Xperia


---- Shilpakopparad wrote ----


Hi sir,


I tried with below layout rendereder also , but still it's null
${aspnet-sessionid} .

Thanks,
Shilpa

**Comment by Shilpakopparad** [comment]
How to use below layout renderer in .net framework.
(https://github.com/NLog/NLog/wiki/AspNetSessionId-layout-renderer).

I tried with ${aspnet-session:SessionID} layout renderer , still its value is null.

**Comment by snakefoot** [comment]
Then I give up. I tried to decipher what value Log4net returned for you, but I guess I failed.

Guess you are condemned to use the debugger, and look at the output from the [InternalLogger](https://github.com/NLog/NLog/wiki/Internal-Logging) to figure out what value your application uses for SessionID.

**Comment by 304NotModified** [comment]
Please fill in the template. We are missing a lot of information.
