### ISSUE TITLE
Why does update nlog via nuget update web.config when nlog.config is installed?

### ISSUE THREAD

**Issue by philipcj** [NLog/NLog#3955]
Why does update nlog via nuget update web.config when I already have the nlog.config nuget package installed? I wasted two hours looking for this again today having not updated Nlog for a few months.

I end up with a web.config with empty values, which disables the settings in nlog.config, i.e. no error reporting on my project.

**Comment by 304NotModified** [comment]
Please elaborate on "update nlog via nuget update web.config". What steps do you mean?

**Comment by 304NotModified** [comment]
Please fill in the template with at least: steps, current result and expected result

**Comment by snakefoot** [comment]
Sound like you are a victim of an issue similar to this:

https://github.com/microsoft/ApplicationInsights-dotnet/issues/1449

Where the Nuget-package tries to be "smart" but ends up with destroying everything. Have same issue with NLog.config nuget-packag: #2608

But please update your original post with the original-config, and the steps you took to destroy it.

**Comment by philipcj** [comment]
> Please elaborate on "update nlog via nuget update web.config". What steps do you mean?

So I have a ASP.NET MVC web project that includes the following nuget packages:
NLog, NLog.config, NLog.schema.

From time to time NLog is updated, so I go into my project and update the nuget packages to the latest versions. Every time I have done this, it adds an empty <nlog> section to the web.config, which NLog prefers to use rather than nlog.config. So effectively nlog wasn't working for a couple of hours on my dev box while I worked out what had happened. Effectively no targets etc etc even though my nlog.config file was intact.

Many thanks for the quick reply BTW. I'm trying to help as well by helping make NLog better in my own small way.

**Comment by philipcj** [comment]
> Sound like you are a victim of an issue similar to this:
> 
> [microsoft/ApplicationInsights-dotnet#1449](https://github.com/microsoft/ApplicationInsights-dotnet/issues/1449)
> 
> Where the Nuget-package tries to be "smart" but ends up with destroying everything. Have same issue with NLog.config nuget-packag: #2608
> 
> But please update your original post with the original-config, and the steps you took to destroy it.

I'm not sure. I am using the Elmah.Io package as well with NLog but everything is good and works perfectly, provided I delete any empty configuration from web.config after upgrading the version of NLog.

**Comment by philipcj** [comment]
> Hi! Thanks for opening your first issue here! Please make sure to follow the issue template - so we could help you better!

Apologies this is my first issue, for some reason I didn't get the template when I posted this. Maybe because I wasn't logged in to begin with I don't know. Thanks again.

**Comment by 304NotModified** [comment]
Has your question being answered?
