### ISSUE TITLE
Thread safe variables/event properties

### ISSUE THREAD

**Issue by catmanjan** [NLog/NLog#3959]
**NLog version**: 4.7

**Platform**: .Net 4.5

Like many people on the net I am using ```LogManager.Configuration.Variables``` to log some common information in each line of a webservice log.

However, I have noticed that it is not thread safe, and it is possible for a thread to overwrite a previous threads variables before the previous thread is finished logging.

I have looked into EventProperties, but there is a warning that ```SetProperty``` is similarly not thread safe. It would be good to have the ability to easily set some variables/properties at the start of the request such that those variables can be accessed by all loggers in that thread for the rest of that request's lifetime.

**Comment by catmanjan** [comment]
Actually, looks like https://github.com/NLog/NLog/wiki/MDLC-Layout-Renderer

Is exactly what I am after, this definitely needs to be publicized better - I would argue that all ```LogManager.Configuration.Variables``` should operate like MDLC

**Comment by 304NotModified** [comment]
Please note that logger.WithProperty is also thread safe. I would recommend to use that over the mdlc, if suitable/possible
