### ISSUE TITLE
NLog - File Rotation - Sequence Issue

### ISSUE THREAD

**Issue by mohitscjain** [NLog/NLog#3961]
**NLog version**: (e.g. 4.7.0)
**Platform**:  .Net 4.5
**Current NLog config** (xml or C#, if relevant)
Issue details at : https://stackoverflow.com/questions/61784672/nlog-file-rotation-sequence-issue

```xml
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <variable name="logDir" value="C:\logs">
    <targets>
        <target name="logFile" xsi:type="File" fileName="${logDir}\API_${machinename}.json"
        archiveFileName="${logDir}\{#}_API_${machinename}.json" archiveNumbering="Date"
        archiveDateFormat="yyyy-MM-dd" archiveEvery="Day">
            <layout xsi:type="JsonLayout" includeAllProperties="true">
                <attribute name="time" layout="${date:format=yyyy-MM-ddTHH\:mm\:ss.fffzzz}"/>
                <attribute name="level" layout="${level:upperCase=true}"/>
                <attribute name="message" layout="${message}"/>
                <attribute name="exception" layout="${exception:format=@}"/>
            </layout>
        </target>
    </targets>
    <rules>
        <logger name="*" minlevel="Debug" writeTo="logFile" />
    </rules>
 </nlog>
```
I am using Nlog for logs and rotating file on daily basis with fixed file name. Archive file name is appended with date. 
Log files are read and processed further by another system to move to Splunk. I am having issues in moving these logs to Splunk as log file generated by NLog gets truncated every time it is rotated.

Here I am looking for-
1. confirmation if this is known issue that - on rotation main/active file gets truncated
2. is there any fix or alternate configuration which can avoid this

It works fine with other log framework like log4net/logback. If that's case, I may need to switch to other framework.

For me desired sequence of log file rotation is:
```
1. Open file - abc.txt 
2. add log line 1, log line 2.. log line n. 
3. 12.00 AM - file rotation - Rename file abc.txt => 2020-05-13 abc.txt 
4. create new file - abc.txt 
5. add log line a1, log line a2.. log line an.
```

Here are some stats. I enabled internal log and here is finding. At 15:24:25.3012 archiving happens. In my log file I see 1st log statement at 15:24:25.146 and rest all statements are from and after 15:24:25.320. So sequence comes out to be like this - 1st log line written > then archiving happened > and then rest lines written. 

This is confusing. I just want to understand how it is working and want to know if there is a fix for this or not. Else I will move to other logging framework. Kindly help.

- What is the current result?
Log files getting truncated on rotation

- What is the expected result?
New log file should be created with same name after every rotation. Existing file should get archive/renamed first, then new file should be created with same name.

- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
Yes. Stats added above.

- Please post full exception details (message, stacktrace, inner exceptions)
https://stackoverflow.com/questions/61784672/nlog-file-rotation-sequence-issue

- Are there any workarounds? yes/no
No, I am looking for the same.

- Is there a version in which it did work? 
I tested on 4.7.0

- Can you help us by writing an unit test?
Config is attached. Agent reads sequentially and if finds that file is truncated then it doesn't reads. But if file is rotated then it completes archived file first and then start with newly generated rotated file.

**Comment by 304NotModified** [comment]
Hi, I am missing the internal log? Please post it here.

**Comment by snakefoot** [comment]
@mohitscjain If you want help with your problem, then you need to provide the raw output from InternalLogger. And not your own interpreted version of the output:

> Here are some stats. I enabled internal log and here is finding. At 15:24:25.3012 archiving happens. In my log file I see 1st log statement at 15:24:25.146 and rest all statements are from and after 15:24:25.320. So sequence comes out to be like this - 1st log line written > then archiving happened > and then rest lines written.

**Comment by mohitscjain** [comment]
Sorry to say but per policy, I cannot take file out and upload here. 
But I am still facing issue. It can be reproducible by using above configuration. At rotation, per my investigation, instead of new file generation, existing file is getting truncated.
Looking forward for help.

**Comment by 304NotModified** [comment]
Just paste the content inline.

**Comment by snakefoot** [comment]
This is my output using your config:

```
2020-05-17 21:25:28.0872 Debug FileTarget(Name=logFile): Process file 'C:\Temp\API_RUMSTATION.json' on startup
2020-05-18 00:00:00.1855 Debug FileAppender Closing Invalidate - C:\Temp\API_RUMSTATION.json
2020-05-18 00:00:00.1855 Debug FileTarget(Name=logFile): Do archive file: 'C:\Temp\API_RUMSTATION.json'
2020-05-18 00:00:00.2199 Info FileTarget(Name=logFile): Archiving C:\Temp\API_RUMSTATION.json to C:\Temp\2020-05-17_API_RUMSTATION.json
2020-05-18 00:00:00.2286 Debug FileTarget(Name=logFile): Move file from 'C:\Temp\API_RUMSTATION.json' to 'C:\Temp\2020-05-17_API_RUMSTATION.json'
2020-05-18 00:00:00.2286 Debug FileTarget(Name=logFile): Process file 'C:\Temp\API_RUMSTATION.json' on startup
2020-05-18 00:00:00.2452 Debug Creating file appender: C:\Temp\API_RUMSTATION.json
```
Everything looks great. No truncate just move file, and creating new file. Maybe the tool you are using for upload is breaking the archive logic. Anyway everything looks great. Please prove otherwise.

**Comment by mohitscjain** [comment]
Thanks for getting back. Yes, its working for you.

I noticed another thing, I see another log line today like below. Not sure if it can tell something what's happening in my case -
2020-05-17 00:00:25.6520 Info FileTarget(Name=logFile) : Archive mutex not available : log_file_path
2020-05-17 00:00:25.6830 Info FileTarget(Name=logFile) : Archiving active_file to archive_file

Thanks again for looking into this.

**Comment by snakefoot** [comment]
This line is some noise that have now been removed with NLog 4.7.1:

`2020-05-17 00:00:25.6520 Info FileTarget(Name=logFile) : Archive mutex not available : log_file_path`

It is merely telling that it is not using global-mutex while doing archive operation, and that is okay,.

**Comment by 304NotModified** [comment]
I'm gonna close this until there is the requested info / demo.
