### ISSUE TITLE
LogBuilder.Write with custom/compiler generated code locations not implemented on iOS and Android

### ISSUE THREAD

**Issue by build-gms-online** [NLog/NLog#3971]
Using the fluent interface to write log messages, calling Write(string,string,int) function that allows the compiler to insert file, member and line information (or to hand over custom locations generated by a wrapper implementation (our use case). The wrapper is implemented in a .net standard 2.0 library.

NLog version: 4.6.8 (latest stable)
Platform: Xamarin Android / Xamarin iOs (using .net standard 2.0 library)
Current NLog config: (not relevant)

- What is the current result?
Build works fine
iOS / Android app crashes with 'MethodNotImplemented' exception.
UWP runs fine

- What is the expected result?
All platforms accept the location information given in the Write(...) method

- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
No. I checked the iOS and Android libraries and tehre is only an implementation of Write() (without parameters), but not Write(string,string,int). This is only present in the .Net Standard library

- Please post full exception details (message, stacktrace, inner exceptions)
No stacktrace within NLog. MethodNotImplemented exception when calling the Write method.

- Are there any workarounds? 
yes and not really, using the StackTrace method to generate the caller location details. But this is a) much slower than using the compiler generated information and b) gives meaningless information of the method name and file information is stripped in release builds.

- Is there a version in which it did work? 
No known

- Can you help us by writing an unit test?
Not really testable, it's a platform specific build binding / DLL incompatibility issue

**Comment by mzimdars-gms-online-de** [comment]
Hi, posted with the wrong user ;-) This is my real one

**Comment by snakefoot** [comment]
Guess your problem is resolved with NLog 5, where Xamarin-builds are replaced by NetStandard-builds.

**Comment by snakefoot** [comment]
Resolved by  #3978
