### ISSUE TITLE
Log through multiple threads

### ISSUE THREAD

**Issue by JZechy** [NLog/NLog#3976]
Hello,

I have application set up with a Dependency Injection (MS), so I'm using custom main class `Application`, where I am injecting a instance of NLog with `ILogger<Application>`. In this class I'm also creating an instance of my Socket Server, where I have events like `OnAccept`, when connection with client is accepted. The accepting of connection is in another Thread, where is OnAccept invoked.

And my problem is, that when is OnAccept invoked, the logger doesn't log anything in here. The event is really invoked (checked through debugger, and even used `Console.WriteLine()`). I assume it has to do something with another thread invoking the log method, I foudn something about AsyncWrapper or async attribute on config file for targets, but nothing is working.

How can I achieve to log in this event method?

My config file:

```xml
<?xml version="1.0" encoding="utf-8"?>

<!-- XSD manual extracted from package NLog.Schema: https://www.nuget.org/packages/NLog.Schema-->
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xsi:schemaLocation="NLog NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true">

    <targets async="true">
        <target xsi:type="Console" name="Console"
                layout="${date}|${level:uppercase=true}|${message} ${exception}|${logger}|${all-event-properties}" />
    </targets>

    <rules>
        <logger name="*" minlevel="Trace" writeTo="Console" />
    </rules>
</nlog>
```

**Comment by snakefoot** [comment]
I'm using NLog every day for logging in many threads without any issues, so I'm guessing you are holding it wrong :)

There is an official issue template with a lot of question. Can you update your question with the answers to these questions (NLog versions etc.)

https://github.com/NLog/NLog/issues/new?template=bug_report.md

I'm just guessing here but if you using Microsoft HostBuilder for setting up dependency-injection and logging, then please share the code of how you do this. If using some other dependency-injection-framework, then please tell what kind and again show the code for how you configure it.

If you are using Microsoft ILogger from NetCore. Then be aware that you also need to configure the [Microsoft ILogger LogLevel Filters](https://github.com/NLog/NLog.Web/wiki/Missing-trace%5Cdebug-logs-in-ASP.NET-Core-3%3F). If you are not using Microsoft-ILogger from NetCore, then tell what kind of ILogger-interface you are using.

**Comment by JZechy** [comment]
@snakefoot Well, I'm guessing that too, I'm doing something wrong 😄 

So to update:
- NLog version: 4.7.2 (+ NLog.Extensions.Logging 1.6.3)
- Platform: .netcore 3.1
- Using Microsoft.Exntesions.DependencyInjection 3.1.4

I'm not using HostBuilder, I have .netcoreapp3.1 console app build from scratch, NLog to DI is registered as follow:

```C#
 var serviceCollection = new ServiceCollection();
 serviceCollection.AddLogging(builder =>
 {
    builder.ClearProviders();
    builder.SetMinimumLevel(LogLevel.Trace);
    builder.AddNLog($"{ConfigBasePath}/{NlogConfig}");
});
```
Where NLog config file is created as mentioned in my first post.

Also tried configure the LogLevel filters, but no outcome here. The used `ILogger<>` interface is from `Microsoft.Extensions.Logging`.

I hope that's all, you asked for, if you need something more, just tell, and thanks for your help!

**Comment by snakefoot** [comment]
Looks very close to the vanilla example here:

https://github.com/NLog/NLog.Extensions.Logging/blob/master/examples/NetCore2/ConsoleExample/Program.cs

Are you creating multiple dependency-injection-containers and having them running side-by-side in the same application?

Possible you could share / attach the example project that reproduces the issue?

**Comment by JZechy** [comment]
Yup, something like this was even on the wiki for the netcore console app.

I'm creating scopes per connected client, so there are running container side by side.

**Comment by snakefoot** [comment]
When running multiple dependency-injection-containers at the same time, then you must decide if you want a single shared NLog LogFactory or multiple isolated NLog LogFactory

- If single shared NLog LogFactory, then you must stop loading new NLog.config for every creation of dependency-injection-container.

- If multiple isolated NLog LogFactory, then you must allocate a new NLog LogFactory for each dependency-injection-container. Like [this example](https://github.com/NLog/NLog.Extensions.Logging/issues/406#issuecomment-599786612).

**Comment by JZechy** [comment]
@snakefoot And how can I stop/prevent loading for every creation of DI container?

**Comment by snakefoot** [comment]
You just call AddNLog() without providing a config file. And instead assign/load config using the static global NLog.LogManager as first thing before creating any dependency containers


Sent from my Sony Xperia


---- JZechy wrote ----


@snakefoot<https://github.com/snakefoot> And how can I stop/prevent loading for every creation of DI container?

**Comment by JZechy** [comment]
Ah, nice. Any way thanks for help!
