### ISSUE TITLE
Proposal: Drop support .NET 4.0 (and add 4.6)

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#3979]
From https://docs.microsoft.com/en-us/lifecycle/faq/dotnet-framework

> .NET Framework 4: .NET Framework 4 did not ship in any operating system. Support for the .NET Framework 4 on Windows Server 2003 SP2 ended on July 14, 2015, and support on all other operating systems ended on January 12, 2016.

**Comment by 304NotModified** [comment]
related #3817

**Comment by snakefoot** [comment]
Along with also dropping Silverlight and Xamarin-builds

**Comment by snakefoot** [comment]
When removing .Net4 and adding .Net46, then I think we should remove the custom NLog defines NET3_5 + NET4_5 + NET4_6 and instead use the default ones NET35 + NET45 + NET46

Also the defines should changed from opt-in:
```c#
#if NET45 || NET46
// blah blah
#endif
```
To opt-out:
```c#
#if !NET35
// blah blah
#endif
```
