### ISSUE TITLE
Maybe NLog should use the same AssemblyLoadContext it loaded instead of the default one for netcore?

### ISSUE THREAD

**Issue by yyjdelete** [NLog/NLog#3981]
**NLog version**: 4.7.2

**Platform**: .NET Core 3.1

Maybe related to #3674

I use `NLog` and `NLog.Extensions.Logging` in an assembly, and load all of them into an new AssemblyLoadContext in another assembly as an plugin.

And then I found that when load and used NLog in an non-default AssemblyLoadContext, instead of use the current AssemblyLoadContext, it will load(or leak) another new instance of itself and all exts in default AssemblyLoadContext.

https://github.com/NLog/NLog/blob/86fba05e272a07d508b32475957b9310f607061d/src/NLog/Internal/AssemblyHelpers.cs#L80
Maybe `AssemblyLoadContext.GetLoadContext(typeof(AssemblyHelpers).Assembly)` should be used instead of `AssemblyLoadContext.Default` or [Assembly.LoadFrom](https://github.com/dotnet/runtime/blob/v5.0.0-preview.4.20251.6/src/libraries/System.Private.CoreLib/src/System/Reflection/Assembly.cs#L335)(which also call `AssemblyLoadContext.Default`) for netcore.

- What is the current result?
NLog load assemblies in the default AssemblyLoadContext.

- What is the expected result?
NLog load assemblies in the same AssemblyLoadContext itself loaded.

- Are there any workarounds? 
use `LogManager.Setup().SetupExtensions(seb => seb.AutoLoadAssemblies(false));` to disable auto load, always use hardcode `SetupExtensionsBuilderExtensions.RegisterAssembly(this ISetupExtensionsBuilder, Assembly)` instead of the string version, not use `extensions` in `NLog.config`

**Comment by snakefoot** [comment]
Think it is a good idea that NLog loads assemblies into the same AssemblyLoadContext as the NLog-assembly when running on NetCore/NetStandard-platform.

PR are welcome

**Comment by 304NotModified** [comment]
PR would be nice indeed! :)

**Comment by yyjdelete** [comment]
Unfortunately, maybe it's not possible to do that in netstandard platform, and needed to add an new targetFramework netcoreapp2.1(or any other verion) to NLog to use `AssemblyLoadContext` directly or use some reflect to try to load and use `AssemblyLoadContext` in ns2.0.

Since `System.Runtime.Loader` is not a part of any version of released netstandard, and in fact can not run on other platform except netcore.[(Not include in ns2.1)](https://github.com/dotnet/standard/blob/master/docs/planning/netstandard-2.1/README.md#decisions)

There is an `System.Runtime.Loader` on [NuGet](https://www.nuget.org/packages/System.Runtime.Loader/), but in fact it still can't run on other platforms(https://github.com/dotnet/runtime/issues/22732#issuecomment-415838808)

**Comment by snakefoot** [comment]
@yyjdelete Maybe open NLog to take an interface for handling assembly-loading Then create a nuget-package that can provide a `LogFactory.Setup()`-extension-method that adds support for `AssemblyLoadContext`.

**Comment by snakefoot** [comment]
Alternative just wait for NetCore5, and then add that as direct target-platform. Then `AssemblyLoadContext` should be available.

**Comment by snakefoot** [comment]
Created pull-request #4246 for resolving this.

**Comment by snakefoot** [comment]
@yyjdelete If you have the time, then please verify that #4246 will resolve your issue.

**Comment by yyjdelete** [comment]
@snakefoot 
I already forget what's the old reproduce code for me, and why I think extensions in NLog.config not works.

Tested 4.7.2 and the test version with the below code, `dotnet build && dotnet run --project Loader`
https://github.com/yyjdelete/NLog_Test_3981
It always get `Post(Default):0` when disable autoload(the default value in the new test version), and always `Post(Default):4` when enable it, change `RegisterAssemblyLoader` seems not actually affect the result.

And did you mean `NLog.LogManager.LogFactory.Setup().SetupExtensions(...` or `var lf = new NLog.LogFactory();lf.Setup().SetupExtensions(...` in example code of #4246?

**Comment by snakefoot** [comment]
You can disable autoload of assemblies doing this (Introduced with NLog 4.7):

```c#
NLog.LogManager.LogFactory.Setup().SetupExtensions(ext => AutoLoadAssemblies(false));
```

If you use the [pre-release-build](https://ci.appveyor.com/project/nlog/nlog/builds/37305930/artifacts) from #4246 and use it from a local-nuget-folder. Then you can override the assembly-loading-logic:

```c#
NLog.LogFactory().Setup().SetupExtensions(ext => ext.RegisterAssemblyLoader(asmName => {
   var assemblyName = new AssemblyName() { Name = asmName };
   var assemblyContext = AssemblyLoadContext.GetLoadContext(typeof(NLog.LogFactory).Assembly);
   return assemblyContext.LoadFromAssemblyName(assemblyName);
}));
```

But maybe this is not necessary for your plugin-logic to work?

**Comment by yyjdelete** [comment]
Yes, it's not necessary for me. (Disabling autoloading assemblies is enough)

**Comment by snakefoot** [comment]
Thank you for the confirmation. Will close the PullRequest  #4246
