### ISSUE TITLE
LayoutParser should throw ThrowConfigExceptions on unknown properties

### ISSUE THREAD

**Issue by snakefoot** [NLog/NLog#3996]
Change so it throws `NLogConfigurationException` when `ThrowConfigExceptions = true`

https://github.com/NLog/NLog/blob/733ce6e65045fd93de8bad6f9c5c67639e2d0978/src/NLog/Layouts/LayoutParser.cs#L384-L385

https://github.com/NLog/NLog/blob/733ce6e65045fd93de8bad6f9c5c67639e2d0978/src/NLog/Layouts/LayoutParser.cs#L436

https://github.com/NLog/NLog/blob/733ce6e65045fd93de8bad6f9c5c67639e2d0978/src/NLog/Layouts/LayoutParser.cs#L455-L456

**Comment by njqdev** [comment]
I couldn't figure out how to include the entire layout-string but I'll create a PR anyway.
