### ISSUE TITLE
[question] Misleading method name ConditionalTrace

### ISSUE THREAD

**Issue by DietmarH** [NLog/NLog#4003]
Regarding to issue #408 the methods ConditionalDebug and ConditionalTrace were introduced.

The source is here:
https://github.com/NLog/NLog/blob/86fba05e272a07d508b32475957b9310f607061d/src/NLog/Logger-Conditional.cs#L761 and following lines.

I'm wondering that ConditionalTrace generates a log entry even if the constant `TRACE` is not defined.
That happens because these ConditionalTrace methods are attributed with `[Conditional("DEBUG")]`.
Is this the intension of these methods?

My thoughts / excpectations were:
- the in Visual Studio predefined constants `DEBUG` and `TRACE` are used
- ConditionalDebug methods are compiled only if `DEBUG` is defined, what is done . 
- ConditionalTrace methods are compiled only if `TRACE` is defined, what is not done . These methods are attributed with `[Conditional("DEBUG")]` too.
- Shouldn't the ConditionalTrace methods are attributed with `[Conditional("TRACE")]`?

**Comment by 304NotModified** [comment]
Well the Trace refers to LogLevel Trace. But have to agree, it's could be confusing.

**Comment by DietmarH** [comment]
I would change the Attributes to [Conditional("TRACE")], because I would expect that a ConditionalTrace is only activated if the TRACE constant is set. But never mind. It's good to know annyway.
