### ISSUE TITLE
Close NLog logger file manually

### ISSUE THREAD

**Issue by sishik1** [NLog/NLog#4004]
I'd like to know if there is a way to manually close the log file. Suppose, I have the following `<target>` section:

`<target xsi:type="File" name="ownFile" header="Machine name: ${machinename}${newline}"         fileName="${mdc:logFolder}\${date:format=yyyyMMdd}\task_${activityid}.txt" layout="${date}|${activityid}|${level:uppercase=true}|${message} ${exception}|${logger}|${all-event-properties}"
            footer="${newline}Finished at: ${date}"/>-->`

`<logger name="*" minlevel="Debug" writeTo="ownFile" />`

The above creates log file at runtime when I set the mdc:logFolder variable and the `Trace.CorrelationManager.ActivityId` inside my code. The problem I have is that I could lots of log files created since the mdc:logFolder and Trace.CorrelationManager.ActivityId is set per thread. When thread is done, I want the NLog to just close the file and not track it anymore, which will also output my footer value correctly. Is there a way to do this?

I also posted same question on StackOverflow: https://stackoverflow.com/questions/62206095/nlog-filename-per-thread

Thanks in advance

**Comment by snakefoot** [comment]
Instead of using to Footer-Layout for this situation. Then I would probably just have the thread write a final LogEvent that signals that it has completed.

**Comment by sishik1** [comment]
Yes. That's should work for me. Thanks!
