### ISSUE TITLE
LoggerCache can grow infinitely

### ISSUE THREAD

**Issue by Sympatron** [NLog/NLog#4007]
Currently the LoggerCache uses `Dictionary<LoggerCacheKey, WeakReference>` internally. This means that the keys can never be garbage collected even if the loggers are collected.

In our application we generated unique logger names per instance of a class and while this is perhaps not an intended usage scenario I think it shouldn't cause the logging library to blow up the RAM usage over time.

Sadly `ConditionalWeakTable<LoggerCacheKey, Logger>` cannot be used in this case because it does not use overridden methods. One way to solve it though, would be to provide a `LogManager.PurgeLoggerCache()` method that removes all entries with empty WeakReferences. That way only users who use this kind of scenario are impacted and can solve it themselves.

**Comment by snakefoot** [comment]
Alternative to `LogManager.PurgeLoggerCache()` could be adding a new edition of `ReconfigureExistingLoggers` that takes a boolean a parameter to perform purge obsolete Logger-entries.

**Comment by ChrisTorng** [comment]
My ASP.NET 7.0 site has memory leak problem. This image shows the `WeakReference` "Path To Root" tab:

<img width="702" alt="image" src="https://github.com/NLog/NLog/assets/1582284/9d151701-15a3-4496-8d9b-f50fa9373b7b">

For the most "Count" `NLog.Internal.TargetWithFilterChain`, the "Path To Root" tab:

<img width="434" alt="image" src="https://github.com/NLog/NLog/assets/1582284/68d73915-ce7f-49f6-8336-0d924f478333">

I have dynamic loggerName with timestamp on it. I'm using [JsnLog](https://jsnlog.com/) to log browser side log to server. And use loggerName field to pass browser side timestamp to server side. Use [JavascriptLogging.OnLogging](https://jsnlog.com/Documentation/JavascriptLogging/OnLogging) to parse the loggerName to get the timestamp. Is this dynamic loggerName usage is not good for NLog?

I don't know whether this is the same problem to this issue. If it's the same issue, then: Is `LogFactory.ReconfigExistingLoggers(true)`/`LogManager.ReconfigExistingLoggers(true)` safe to call at any time? When should I call this to release useless log entries?

**Comment by snakefoot** [comment]
Looks like you are using Microsoft.Extensions.logging, so it is not just NLog-Logger, but also Microsoft-ILogger-instances.

Calling `LogManager.ReconfigExistingLoggers(true)` will not help since WeakReference are kept alive by Microsoft-ILogger-instnace.

It is not recommended to use Logger-Name to capture the TimeStamp. Instead consider adding additional context as LogEvent-Properties. See also: https://github.com/NLog/NLog.Extensions.Logging/wiki/NLog-properties-with-Microsoft-Extension-Logging

**Comment by ChrisTorng** [comment]
I don't know dynamic `loggerName` is not a good approach. Until the leak problem hits me, and analyzing the memory dump with a web search found this thread. And I still don't understand the reason why a dynamic `loggerName` can't be released. I found a way to get client-side timestamp from JSNLog `loggingEventArgs.LogRequest.UtcDate` (reference to [OnLogging Event](https://jsnlog.com/Documentation/JavascriptLogging/OnLogging)). That helps to make `loggerName` to a rather small set, hope this can fix the memory leak problem, and eliminate the extra timestamp passing in `loggerName`. Thanks for your help.

**Comment by snakefoot** [comment]
The [Logger](https://github.com/NLog/NLog/wiki/Logger-Layout-Renderer)-name is intended to show the source of the LogEvent. Often the Logger-name is the class-type-name where the Logger was used. Example NLog has the method `NLog.LogManager.GetCurrentClassLogger()` that resolves Logger-name from the class-type in call-stack. Same can also seen with Microsoft `ILogger<T>` where generic `<T>` is the class-type.

The Logger-name is often used for filtering / redirection, where NLog Logging-Rules are optimized for doing matching based on the Logger-name. This can also be seen with Microsoft Logging Filtering.

There is an overhead in creating a Logger. Besides the allocation of the Logger-object, then it also has resolve the configured output-targets for the Logger. Having a cache of all Logger-objects reducing allocation, but also makes it easy refresh active Logger-objects when the NLog Configuration changes and should refresh active Loggers with their expected output-targets.

**Comment by ChrisTorng** [comment]
For the server-side, I use static `GetCurrentClassLogger` instance for any class. But for `JSNLog`, I guess the server-side create new `Logger` for every log cause of the string `loggerName`. (Reference to [Getting started with JavaScript logging](https://jsnlog.com/Documentation/GetStartedLogging): JL(**"function1.logger1"**).warn("log message");)
But for real experiment, it should have reused the same `Logger` for a fix set of `loggerName`. Thanks for your explanation.
