### ISSUE TITLE
There is no way to define the RuleName when using AddRule(... , string ruleName = null) programmatically

### ISSUE THREAD

**Issue by gitjsdr26** [NLog/NLog#4015]
Hi all,

I'm trying to set a `RuleName` programmatically using the `AddRule(...)` methods.
`RuleName ` is public, but there is no  AddRule(...) taking into account this parameter.
Creating a `LoggingRule rule` is not possible because `AddLoggingRulesThreadSafe` is private.

Indeed, if someone wants to change the rule range from <LogLevel.Info, LogLevel.Fatal> to <LogLevel.Trace, LogLevel.Fatal> at runtime (which is my case), it's not possible apart from doing it by rules indexes why is not a good idea on my opinion.

Regards

**Comment by 304NotModified** [comment]
Hi,

Instead of this:

```c#
var config = new LoggingConfiguration();
var target = new FileTarget("t1");

config.AddRule(LogLevel.Info, LogLevel.Error, target, "MyNamespace.*");
```

Create a new instance of `LoggingRule` and add to `config.LoggingRules`, for example:

```c#
var config = new LoggingConfiguration();
var target = new FileTarget("t1");

var loggingRule = new LoggingRule("name1");
loggingRule.EnableLoggingForLevels(LogLevel.Info, LogLevel.Error);
loggingRule.Targets.Add(target);
loggingRule.LoggerNamePattern = "MyNamespace.*";

config.LoggingRules.Add(loggingRule);
```
