### ISSUE TITLE
Question about the order of stacktrace frames outputted by StackTraceLayoutRenderer

### ISSUE THREAD

**Issue by AlanLiu90** [NLog/NLog#4016]
The order of stacktrace frames outputted by StackTraceLayoutRenderer is different from the stacktrace of System.Exception（Reverse order）. I think the order from System.Exception is more natural. Why does NLog choose the reverse order?

**Comment by snakefoot** [comment]
@AlanLiu90 You are welcome to create a pull-request that reverses the printing.

**Comment by AlanLiu90** [comment]
I created a pull request: https://github.com/NLog/NLog/pull/4018
