### ISSUE TITLE
Zip Archive created under Linux is missing file permissions

### ISSUE THREAD

**Issue by marcwittke** [NLog/NLog#4022]
**NLog version**: 4.5.11

**Platform**: .NET Core 3

**Current NLog config** (xml or C#, if relevant)

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true" internalLogFile="logs/nlog.log"
      internalLogLevel="Warn">

  <targets async="true">
    <target name="rollingLogFile" xsi:type="File" layout="${level:uppercase=true:padding=-5} ${mdlc:item=app-Activity:padding=5} ${mdlc:item=app-Identity:padding=5} ${date} ${time} ${logger} ${message} ${exception}"
            keepFileOpen="true"
            concurrentWrites="false"
            fileName="logs/Application.log"
            archiveFileName="logs/Application.{#}.zip"
            archiveAboveSize="10240000"
            archiveNumbering="Rolling"
            maxArchiveFiles="20"
            enableArchiveFileCompression="true" />
    
  </targets>

  <rules>
    <logger name="*" minlevel="Debug" writeTo="rollingLogFile" />
  </rules>

</nlog>
```

Running the application on linux, everything seems to work. Opening a archived log file shows a problem: the files are archived with permission 0000 - no one can read them. The Linux unzippers do respect these permission masks (unlike windows tools) which results in a file that no one can read and a sudo operation is required to fix the file permissions before opening the file.

I recently stumbled upon the same problem and I think I know how to fix it. Unfortunately I don't have a windows machine at hand to compile the complete code, therefore the proposed fix via comment:

.net core now exposes the `ExternalAttributes` property of `ZipArchiveEntry` that allows you to set permissions, like this (664):

```csharp
entry.ExternalAttributes = entry.ExternalAttributes | (Convert.ToInt32("664", 8) << 16);
```

note that the string is an octal representation of the permission bit mask, therefore the convert to base 8. The line should probably embedded in some compiler-if checking for netstandard.

**Comment by snakefoot** [comment]
The preferred goal is to refactor and extract the zip-compression logic out of FileTarget into its own nuget-package. See #2732 (Maybe with help from  #1249).

The NLog FileTarget is already a gnarly old class, that have taken on many warts (options). And doing a lot more than just write to a file :)

But thank you for the great input. When a champion arrives that is ready to take on the task, then this option would be great to include.

**Comment by snakefoot** [comment]
Closing as not top-priority. Ofcouse pull-request are most welcome. See also https://github.com/NLog/NLog/issues/3711#issuecomment-559604944
