### ISSUE TITLE
How to Writes NLog message in Local When NAS Path or Network Path is slow or Not accessible

### ISSUE THREAD

**Issue by GaneshkNlog** [NLog/NLog#4024]
Hi,

I am using Nlog 4.0 Version from C# Console and Web Applications, It writes the Text Log in NAS Path and works as Expected.

If there is any issue in connecting the NAS or Network issue, It hangs... either not responding or not updating the Logs

Is there any way to change the Path dynamically if there is any issue in NAS Path access or Network issue.

It should give preference to NAS Path which is configured in Nlog config file.
If there is any issue, it should write the Logs in Local Machine (Secondary Path updated in Config File or Pragmatically change the path in Code to handle this situation) without hanging the Application

Please advise
Thanks
~Ganesh

**Comment by 304NotModified** [comment]
I think you're looking for https://github.com/NLog/NLog/wiki/FallbackGroup-target

**Comment by snakefoot** [comment]
When writing to a network share that is not available, then it is the operating system that gives the blocking behavior. It can block for over 2 minutes.

The blocking behavior will not disappear by using FallbackGroup-target. Instead I suggest making use of `<targets async="true">` that activates the https://github.com/nlog/NLog/wiki/AsyncWrapper-target

It will not be easy to add fallback-logic when a file-write-operation has taken longer than 5 seconds. Instead I would probably setup 2 file-targets (both wrapped using `AsyncWrapper`)
- FileTarget1 that writes to the NAS without automatic cleanup
- FileTarget2 that writes to local folder but with archiving and MaxArchiveFiles=5

**Comment by snakefoot** [comment]
Does it resolve your issue?
