### ISSUE TITLE
Where could I get NLog.dll

### ISSUE THREAD

**Issue by zhoujiazhi222** [NLog/NLog#4029]
i am macos ， how can I build the source code to get Nlog.dll for unity3d

**Comment by 304NotModified** [comment]
To build the code your self, just clone the source or download a source code of a release (e.g. https://github.com/NLog/NLog/releases/tag/v4.7.2)

For getting the build dlls, install the package by nuget or download by hand: https://www.nuget.org/packages/nlog/

**Comment by snakefoot** [comment]
Newer version of Unity3d supports NetStandard/NetCore just fine. 

If using older version of Unity3d then you should use the NET3_5 build but without WCF_SUPPORTED.

**Comment by zhoujiazhi222** [comment]
@304NotModified 
I download it , But his file format is **nupkg** , not **dll** , where can I download the dll
<img width="318" alt="Screen Shot 2020-06-27 at 10 34 15 AM" src="https://user-images.githubusercontent.com/20750357/85912782-c4202180-b861-11ea-97b6-fbb09513cdd8.png">
<img width="326" alt="Screen Shot 2020-06-27 at 10 31 40 AM" src="https://user-images.githubusercontent.com/20750357/85912741-74d9f100-b861-11ea-9b58-9f147cfc6910.png">

**Comment by zhoujiazhi222** [comment]
@snakefoot 
I using unity2019 LTS , I don't want to build the source code, I only need the **dll**

**Comment by snakefoot** [comment]
nupkg files are just zip files. Rename the file to have zip extension and then open it.


Why not just use nuget package in Unity instead of file extract?



Sent from my Sony Xperia


---- JiaZhi Zhou wrote ----


@snakefoot<https://github.com/snakefoot>
I am using unity2019 LTS , I don't want to build the source code, I only need the dll

**Comment by zhoujiazhi222** [comment]
@snakefoot 
Thank you very much , I using nugetforunity to download NLog ， it looks like works fine on my computer
And I have another question : Do I need to upload this directory Assets/Packages/Nlog.4.7.2 to my remote git repo?
