### ISSUE TITLE
An ability to bypass InternalLogger initialization

### ISSUE THREAD

**Issue by estrizhok** [NLog/NLog#4032]
**NLog version**: 4.7.2
**Platform**: .Net 3.5 / .Net 4.5

Setting up logging from a non-default AppDomain add a noticable time overhead, mainly due to initialization of InternalLogger. 
For a short-lived application, that has typical execution time of about 2 seconds, this represents 10-15%.

```
15.53%   ConfigurationItemFactory..ctor  •  348 ms  •  NLog.Config.ConfigurationItemFactory..ctor(params Assembly[])
  15.04%   RegisterItemsFromAssembly  •  336 ms  •  NLog.Config.ConfigurationItemFactory.RegisterItemsFromAssembly(Assembly, String)
    11.86%   [Native code]  •  265 ms
      11.86%   InternalLogger..cctor  •  265 ms  •  NLog.Common.InternalLogger..cctor
        11.86%   Reset  •  265 ms  •  NLog.Common.InternalLogger.Reset
          11.46%   GetSetting  •  256 ms  •  NLog.Common.InternalLogger.GetSetting(String, String, T)
            11.46%   GetSettingString  •  256 ms  •  NLog.Common.InternalLogger.GetSettingString(String, String)
              ►11.46%   GetAppSettings  •  256 ms  •  NLog.Common.InternalLogger.GetAppSettings(String)
    ►2.32%   SafeGetTypes  •  52 ms  •  NLog.Internal.ReflectionHelpers.SafeGetTypes(Assembly)
    ►0.45%   ScanTypes  •  10 ms  •  NLog.Config.MethodFactory.ScanTypes(Type[], String)
    ►0.40%   PreloadAssembly  •  9 ms  •  NLog.Config.ConfigurationItemFactory.PreloadAssembly(Type[])
```

**Comment by snakefoot** [comment]
Never heard of anyone using the ability to configure the `InternalLogger` from `app.config`, besides embedding the entire `NLog.config` as section inside `app.config`.

Of course a breaking change, but could be included in the coming NLog ver. 5. You are welcome to create a pull-request for the NLog-project

**Comment by estrizhok** [comment]
Not sure I understood correctly. 

I am not configuring in the internal logging in any way. I am just configuring the logger itself from a non-default appDomain, and run into a problem that:
a) ConfigurationManager subsystem has got to re-initialize even if there was not specific app.config set for it (and it, therefore, inherited the one from the default appDomain);
b) NLog is the only one reading into app.config settings because of InternalLogger initialization.

Also I don't see why such a change would necessarily be breaking. It is an addition to the existing API that would allow to switch initialization of the InternalLogger settings from the app.config off, isn't it?

**Comment by snakefoot** [comment]
I like things to be simple and predictable, and when `GetAppSettings` gives a hard penalty then it doesn't belong.

Lets say 99.9 pct of people doesn't make use of configuring InternalLogger using appsettings in app.config.
Lets say 10 pct of people are hurt by the overhead from the automatic call to `GetAppSettings`.

Then I think it is easier for 0.1 pct of people to explicitly configure  `InternalLogger`, instead of 10 pct of people having to explicit configure `InternalLogger` to avoid the penalty.

Anyway since you are one creating the PR then you can decide what is best. As long the solution is elegant and easy to understand (Usually removing code is quite easy)

**Comment by snakefoot** [comment]
Have it disabled by default, but introduce an ISetupBuilder-extension-method for LogFactory.Setup() to enable it (Does nothing on NetCore).

**Comment by noamyogev84** [comment]
@snakefoot looking into it.
