### ISSUE TITLE
Performance: Targets inheriting from NLog.Targets.TargetWithLayout can compile layout excessively

### ISSUE THREAD

**Issue by estrizhok** [NLog/NLog#4033]
**NLog version**: 4.7.2
**Platform**: .Net 3.5 / .Net 4.5 / .NET Core 2

If one sets up the `Layout` property on a target inheriting from `NLog.Targets.TargetWithLayout`, `LayoutParser.CompileLayout` will be invoked at least twice: once for the default value set inside the constructor of `NLog.Targets.TargetWithLayout`, and the second time for the value set by the user.

Expected behavior: 
Only compile layout once and only for the value which is going to be used.

P.S. I understand it is pretty minor, but if that is not too much effort...

**Comment by snakefoot** [comment]
> I understand it is pretty minor, but if that is not too much effort...

You are welcome to create a PullRequest for the NLog-project, and show your ideas.

**Comment by snakefoot** [comment]
Closing as inactive.
