### ISSUE TITLE
Suggestion, the default date time format should include the timezone info

### ISSUE THREAD

**Issue by chucklu** [NLog/NLog#4034]
**NLog version**: (4.7.2)

**Platform**:  .Net 4.5

 - Why do we need it?  

Did you ever think about this? For me, when I do the troubleshooting with a client, and the server timezone is not the same as my region. I need to confirmed the timezone info with client first if the log file did not contains the timezone info.

Although I can configure the layout of target to record the timezone info, but I believe it would be better to record timezone info as default behavior. I do not want to manually configure the date time format just because it lack of timezone info.
Why don't you record timezone info by default? What kind of concern you are worrying about? maybe to save disk  space?
No offense.

**Comment by snakefoot** [comment]
In my world then I prefer just using UTC everywhere and ensure timestamps received from external clients are converted to UTC before logging:

```xml
<nlog>
    <time type="AccurateUTC" />
</nlog>
```

See also: https://github.com/NLog/NLog/wiki/Time-Source

Think there are usually two types of users:
- Those running simple console-applications will choose local-time (the default)
- Those running cloud-service application will explicitly choose utc-time (explicit configured)

Think you belong to the 3rd type of users and is a minority, so I don't think it will become the new default. Anyway my 5 cents.

**Comment by chucklu** [comment]
The problem with UTC time is, we need convert it twice in mind when we communicate with client.
For example, my local timezone is UTC+8 and the timezone of client is UTC-5. When I get the log file, I have to convert the UTC time to my local time first, such as check how many hours ago, the log was recorded. And then when I communicate with client, I had to covert the time to the timezone of client again.
Most time I prefer the server time set as the same timezone as the client region. And I only need covert the time once to my local time.

**Comment by chucklu** [comment]
@snakefoot  Here is another log component which record the timezone along with the date time by default.
 https://github.com/serilog/serilog-sinks-rollingfile/blob/dev/src/Serilog.Sinks.RollingFile/RollingFileLoggerConfigurationExtensions.cs#L33

**Comment by snakefoot** [comment]
NLog makes it extremely easy to change the `Layout` for the NLog targets. Any reason why you cannot do that?

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <variable name="mydate" value="${date:format=yyyy-MM-dd HH:mm:ss.fff zzz}" />
    <variable name="mylayout" value="${mydate} ${level} ${logger} ${message} ${exception:format=tostring}" />

    <targets>
        <target name="logfile" xsi:type="File" fileName="file.txt" layout="${mylayout}" />
        <target name="logconsole" xsi:type="Console" layout="${mylayout}" />
    </targets>

    <rules>
        <logger name="*" minlevel="Info" writeTo="logconsole" />
        <logger name="*" minlevel="Debug" writeTo="logfile" />
    </rules>
</nlog>
```

**Comment by chucklu** [comment]
@snakefoot  Yes, I can adjust the layout. I already know how to do it. 
My point is it should be the default behavior.
Thanks.

**Comment by snakefoot** [comment]
@chucklu Not everyone is using NLog at multiple geographic locations. If you had your wish, then suddenly 1000 people will be asking. Why NLog is printing unnecessary information in their console? And how can it be removed?

**Comment by chucklu** [comment]
@snakefoot  ok, I also find the project used utc time without tiemzone.
https://github.com/serilog/serilog/blob/dev/src/Serilog/Debugging/SelfLog.cs#L100
