### ISSUE TITLE
Can't keep one day of archived logs

### ISSUE THREAD

**Issue by DmitryFromDubna** [NLog/NLog#4035]
**NLog version**: (e.g. 4.4.13)
**Platform**: .NET Core 3

**Current NLog config** (xml or C#, if relevant)

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <targets>
		<target xsi:type="File" name="f" fileName="file.log" autoFlush="true" keepFileOpen="true" concurrentWrites="true" archiveFileName="file-{#}.log" archiveNumbering="Date" archiveDateFormat="yyyy-MM-ddThh-mm-ss" maxArchiveFiles="1" archiveEvery="Day">
			<layout xsi:type="JsonLayout">
				<attribute name="time" layout="${date:universalTime=false:format=yyyy-MM-ddTHH\:mm\:ss.fffZ}"/>
			</layout>
		</target>
	</targets>
	
    <rules>
		<logger name="*" minlevel="Info" writeTo="f" />
    </rules>
</nlog>
```

Current result: no archive files are kept
Expected result: one archive file is kept

Worked well in v4.0.0.0

This is very similar to [#2775](https://github.com/NLog/NLog/issues/2775) which is closed as a dup of  #1479, but the latter is still open and it is not clear whether its fix will actually address the issue.

Please note, this blocks our project from migration to .Net Core; will likely block others as well.

**Comment by DmitryFromDubna** [comment]
Attaching internal log that corresponds to the following manual test:
 - Set maxArchiveFiles="2"
 - Start the application, wait for some logging, stop. Log file is created, OK.
 - Change the date to +1 day
 - Start the application, wait for some logging, stop. One archive file is created, OK
 - Change the date to +1 day
 - Start the application, wait for some logging, stop. Second archive file is created, OK
 - Set maxArchiveFiles="1"
 - Change the date to +1 day
 - Start the application, wait for some logging, stop. All archive files are deleted, NOT OK

[nlog-internal.txt](https://github.com/NLog/NLog/files/4869679/nlog-internal.txt)

**Comment by snakefoot** [comment]
Have you tried dusing the new option MaxArchiveDays=1 on FileTarget introduced with NLog 4.7:

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <targets>
		<target xsi:type="File" name="f" fileName="file.log" autoFlush="true" keepFileOpen="true" concurrentWrites="true" archiveFileName="file-{#}.log" archiveNumbering="Date" archiveDateFormat="yyyy-MM-ddThh-mm-ss" maxArchiveDays="1" archiveEvery="Day">
			<layout xsi:type="JsonLayout">
				<attribute name="time" layout="${date:universalTime=false:format=yyyy-MM-ddTHH\:mm\:ss.fffZ}"/>
			</layout>
		</target>
	</targets>
	
    <rules>
		<logger name="*" minlevel="Info" writeTo="f" />
    </rules>
</nlog>
```

See also: https://github.com/NLog/NLog/wiki/File-target

**Comment by DmitryFromDubna** [comment]
Works well, thank you! I think this issue can be closed.

**Comment by kirsan31** [comment]
Guys, I spent about 1 hour to figure out why maxArchiveFiles="1" won't working.
It's not normal, that:
with `maxArchiveFiles = 1`, I will get the current log file only (i.e. NO archive files) :confused:
and with `maxArchiveFiles = 2`, I will get 2 archive files. - correct.

This is really a bug, and if you interpret it like a _feature_, there must be a big warning about it in the docs, and described workaround with `maxArchiveDays`...
Thanks.
cc @304NotModified @snakefoot

**Comment by snakefoot** [comment]
@kirsan31 You are very welcome to create a more logical implementation of maxArchiveFiles for NLog 5.0 (dev-branch) with a pull-request.

Maybe read the comments for #2775 and #1479 before doing the implementation.
