### ISSUE TITLE
Rolling file problem(maybe called as archive file)  and file being used by another process

### ISSUE THREAD

**Issue by chucklu** [NLog/NLog#4037]
**NLog version**: (4.7.2)

**Platform**: .Net 4.6.1

**Current NLog config** (xml or C#, if relevant)

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog autoReload="true" throwConfigExceptions="true" xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

  <targets async="true">
    <target name="logfileInfo" xsi:type="File" fileName="log\Info_${date:format=yyyyMMdd}.log" layout="${date:format=yyyy-MM-dd HH\:mm\:ss.fff zzz}|${level:uppercase=true}|${threadid}|${logger}|${message}" archiveAboveSize="3072" KeepFileOpen="True" ConcurrentWrites="true"/>
    <target name="logfileError" xsi:type="File" fileName="log\Error_${date:format=yyyyMMdd}.log" layout="${date:format=yyyy-MM-dd HH\:mm\:ss.fff zzz}|${level:uppercase=true}|${threadid}|${logger}|${message}" archiveAboveSize="3072" KeepFileOpen="True" ConcurrentWrites="true"/>
    <target name="logconsole" xsi:type="Console" />
  </targets>

  <rules>
    <logger name="*" minlevel="Info" writeTo="logconsole" />
    <logger name="*" minlevel="Trace" maxlevel="Warn" writeTo="logfileInfo" />
    <logger name="*" minlevel="Error" maxlevel="Fatal" writeTo="logfileError" />
  </rules>
</nlog>
```

- What is the current result?
I have inspected the InternalLogger.LogMessageReceived and record exception into event log of Windows.
```
exception1: The process cannot access the file 'Info_20200707.3.log' because it is being used by another process.
exception2: Could not find file 'Info_20200707.log'.
```
By the way the file size is only used for test intent.

- What is the expected result?
I am not sure what's the correct behavior when rolling file with multi processes. Is it supposed to encounter such exception when rolling file with multi processes.

- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
The exception was captured from InternalLogger.LogMessageReceived .

- Please post full exception details (message, stacktrace, inner exceptions)
```
date time, 14:06:21
File Target[logfileInfo_wrapped]: Error has been raised.
,System.IO.IOException: The process cannot access the file 'Info_20200707.3.log' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at NLog.Targets.FileTarget.ArchiveFileAppendExisting(String fileName, String archiveFileName)
   at NLog.Targets.FileTarget.DoAutoArchive(String fileName, LogEventInfo eventInfo, DateTime previousLogEventTimestamp, Boolean initializedNewFile)
   at NLog.Targets.FileTarget.TryArchiveFileAfterCloseFileAppender(String fileName, String archiveFile, LogEventInfo ev, Int32 upcomingWriteSize, DateTime previousLogEventTimestamp, Boolean initializedNewFile)

date time, 14:06:22
File Target[logfileInfo_wrapped]: Error has been raised.
,System.IO.FileNotFoundException: Could not find file 'Info_20200707.log'.
File name: 'Info_20200707.log'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at NLog.Targets.FileTarget.ArchiveFileAppendExisting(String fileName, String archiveFileName)
   at NLog.Targets.FileTarget.DoAutoArchive(String fileName, LogEventInfo eventInfo, DateTime previousLogEventTimestamp, Boolean initializedNewFile)
   at NLog.Targets.FileTarget.TryArchiveFileAfterCloseFileAppender(String fileName, String archiveFile, LogEventInfo ev, Int32 upcomingWriteSize, DateTime previousLogEventTimestamp, Boolean initializedNewFile)
```

- Are there any workarounds? yes/no
no

- Is there a version in which it did work? 
no

- Can you help us by writing an unit test?
Maybe I can provide a repository with a console application write log and another console loop invoke the first console.

**Comment by snakefoot** [comment]
Think you have to provide the full output from `internalLogFile="...."` with `internalLogLevel="Trace"`. So one can see the operations that results in these exceptions.

It is strange that the archive mutex is not preventing the different processes from making changes to the same file.

**Comment by chucklu** [comment]
@snakefoot  I have created a git repository to reproduce this problem. https://github.com/ChuckTest/NLogTest
You can build the solution first, then go to fodler NLogTest\bin\Debug, and run ConsoleApp1.exe. The ConsoleApp1.exe will start 100 processes which will write log to the same file with rolling file by size.
You can check exception through the event log under "Applications and Services Logs"\NLog .
![image](https://user-images.githubusercontent.com/3004057/86882967-b1d89a00-c123-11ea-8da8-d09082841924.png)

Currently I set the InternalLogger.LogLevel to NLog.LogLevel.Error
https://github.com/ChuckTest/NLogTest/blob/master/NLogTest/Program.cs#L16

**Comment by snakefoot** [comment]
Does not sound optimal with 100 processes writing to the same file. Sadly enough my computer only has 4 cores.


Sent from my Sony Xperia


---- Chuck Lu wrote ----


@snakefoot<https://github.com/snakefoot> I have created a git repository to reproduce this problem. https://github.com/ChuckTest/NLogTest
You can build the solution first, then go to fodler NLogTest\bin\Debug, and run ConsoleApp1.exe. The ConsoleApp1.exe will start 100 processes which will write log to the same file with rolling file by size.
You can check exception through the event log under "Applications and Services Logs"\NLog .
[image]<https://user-images.githubusercontent.com/3004057/86882967-b1d89a00-c123-11ea-8da8-d09082841924.png>

Currently I set the InternalLogger.LogLevel to NLog.LogLevel.Error
https://github.com/ChuckTest/NLogTest/blob/master/NLogTest/Program.cs#L16

**Comment by chucklu** [comment]
My laptop has only 4 cores and 8 logical processors.
What's  the maximum number of Processes can NLog support to write log to same file with rolling?

**Comment by snakefoot** [comment]
No idea where the sweet spot is. Probably very dependent on your CPU-hardware, Disk-System and operating system. But having 100 processes fighting to use the same global mutex is not good. Usually a criticalsection works ok with 4 threads, and works bad with 8 threads (Independent of CPU cores available) . Since a mutex is slower than a criticalsection, then I guess 8 processes sharing the same file is close to a maximum (merely a random guess)


Sent from my Sony Xperia


---- Chuck Lu wrote ----


My laptop has only 4 cores and 8 logical processors.
What's the maximum number of Processes can NLog support to write log to same file with rolling?

**Comment by chucklu** [comment]
I have did another test with elasticsearch with the previous repository, and if you would like to test, you can check with https://github.com/ChuckTest/NLogTest/commit/97785bb7ee911f3a077b2313a9ce837ae35956e4 .
Thanks for your explanation,  I will try to use elastic search to avoid multi processes locking problem.

**Comment by snakefoot** [comment]
Depending on how critical the logging output is, then you continue write to file (just include ${processid} in fileName, so you get a file for each process, and use Jsonlayout) Then use LogStash or Filebeat to upload the files in the background


Sent from my Sony Xperia


---- Chuck Lu wrote ----


I have did another test with elasticsearch with the previous repository, and if you would like to test, you can check with ChuckTest/NLogTest@97785bb<https://github.com/ChuckTest/NLogTest/commit/97785bb7ee911f3a077b2313a9ce837ae35956e4> .
Thanks for your explanation, I will try to use elastic search to avoid multi processes locking problem.
