### ISSUE TITLE
Newline delimited JSON / Streamed JSON support

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#4049]
Idea: maybe make it easier to setup Newline delimited JSON and recommend this in the docs.

Mabye somethine like ` <layout xsi:type="JsonLayout"  newline-delimited=true ..>` or  ` <layout xsi:type="JsonLayout" delimiter="${newline}>`

(This would create trailing delimiters.  )

See: 
https://github.com/ndjson/ndjson-spec

**Comment by snakefoot** [comment]
When using the JsonLayout with FileTarget or NetworkTarget, then it automatically generates newline-delimited-JSON. What is missing?

**Comment by 304NotModified** [comment]
I think you right, expect maybe this:

> The JSON texts MUST NOT contain newlines or carriage returns.

from https://github.com/ndjson/ndjson-spec

And mostly, it's a docs thing.

**Comment by snakefoot** [comment]
> The JSON texts MUST NOT contain newlines or carriage returns.

NLog already escapes newlines and carriage returns:

https://github.com/NLog/NLog/blob/d84a0c021402958713156da0887772939f185976/src/NLog/Targets/DefaultJsonSerializer.cs#L670-L681

**Comment by snakefoot** [comment]
Closing as resolved, since both FileTarget and NetworkTarget supports adding newline after each JSON-document. Alternative one can use CompoundLayout if some NLog target is missing newline-support.
