### ISSUE TITLE
Veracode SQL Injection Scan Flaw: void ExecuteDbCommandWithParameters(LogEventInfo, System.Data.IDBConnection,IDBTransation)

### ISSUE THREAD

**Issue by RickC10** [NLog/NLog#4051]
Hi,  I received a SQL Injection vulnerability issue from a Veracode scan I ran on an application I'm using NLog.dll.  Version 4.7.2. 
We don't need the ability to log to DB. Can I pull the source and remove the execute DB Command method from the version?

Flaw was communicated on this method:
ExecuteDBCommandWithParameters(LogEventInfo,System.Data.IDBConnection,System.Data.IDBTransaction)

**Comment by snakefoot** [comment]
@RickC10 You are welcome to compile your own version of NLog without DatabaseTarget. The DatabaseTarget will only execute the sql-commands that has been specified in the NLog.config so it is not a real vulnerability.

NLog 5.0 will extract WCF, Network, Mail and Database-targets into separate nuget-packages, so it will "remove" the sql injection vulnerability from the NLog.dll

**Comment by 304NotModified** [comment]
See https://github.com/NLog/NLog/issues/3872#issuecomment-607281512

**Comment by 304NotModified** [comment]
Closed by https://github.com/NLog/NLog/issues/3872#issuecomment-662632166

**Comment by 304NotModified** [comment]
Any way, https://sca.analysiscenter.veracode.com/vulnerability-database/libraries/nlog/csharp/nuget/lid-1496871/summary

155
Versions
since 7 Jan 2011

Latest has vulnerabilities? No

155
Safe Versions
