### ISSUE TITLE
System.ArgumentOutOfRangeException when logging a message with unused parameters

### ISSUE THREAD

**Issue by Oberndorfer** [NLog/NLog#4052]
I am running NLog Version 4.6.6, .NET Framework 4.7.1 on VS2017.
When logging a message which exceeds `short.MaxValue` characters might result in an `ArgumentOutOfRangeException`.
Try this:
```c#
public static void Bumm()
{
	string char32 = "ABCDEFÖ8901234567890123456789012";
	string a = "";
	for (int i = 0; i < 1023 * 1; i++)
	{
		a += char32;
	}
	var myLogger = NLog.LogManager.GetLogger("myLogger");
	LogEventInfo theEvent = new LogEventInfo(
		LogLevel.Debug, "muh", CultureInfo.InvariantCulture, a, new object[] { 42 });
	myLogger.Log(theEvent);  // OK (length < short.MaxValue)
	a += char32;
	theEvent = new LogEventInfo(
		LogLevel.Debug, "muh", CultureInfo.InvariantCulture, a, new object[] { 42 });
	myLogger.Log(theEvent); // Exception length = short.MaxValue + 1
}
```
The reason is an overflow when converting an `int32` (returned by `SkipUntil`) to an int16 (`Literal.Skip`) in the `TemplateEnumerator.ParseTextPart`.

What is the preferred way of fixing this?

- Change the `Literal.Skip` from `short` to `int`
- Ensure that no overflow happens when assigning the Skip Property (more or less: `(short)Math.Min(short.MaxValue, SkipUntil(...)`)
It depends on what the intention was when defining the `Skip` as a short in the firstplace.
If I read the history correct, the Skip and Print both have been `ushort` in the first place. Someone has changed `Print` to an `int32` but the sense of changing the position from `ushort` to `short` I do not get.

@snakefoot @304NotModified do you have any concerns when changing the type of `Skip` to an `int32`?

**Comment by snakefoot** [comment]
Think it is a great idea to change `Literal.Skip` to be an `int`.

**Comment by snakefoot** [comment]
Created PR #4053

**Comment by snakefoot** [comment]
Pre-release nuget-package is now available (Download NLog.4.7.2.11960-PR4053.nupkg and place in local-path nuget-repository):

https://ci.appveyor.com/project/nlog/nlog/builds/34238992/artifacts

**Comment by Oberndorfer** [comment]
Thank you for fixing this super fast!
Do I have to close this issue myself or is this done automatically with the next release?

**Comment by snakefoot** [comment]
> Do I have to close this issue myself or is this done automatically with the next release?

When the PR is merged, then it will resolve the issue.
