### ISSUE TITLE
Merge NestedDiagnosticsLogicalContext and MappedDiagnosticsLogicalContext into one

### ISSUE THREAD

**Issue by snakefoot** [NLog/NLog#4056]
Right now there are two async-scope-managers in NLog:

- MappedDiagnosticsLogicalContext
- NestedDiagnosticsLogicalContext 

Both operates like an async-stack, so one can push and pop state on the thread-execution-context.

Thinking that one could implement an unified stack that can contain both scope-values and scope-properties.

This would also make the NLog-implementation of MEL-BeginScope faster, since it will only update a single state instead of updating both NDLC-state and MDLC-state. Could also consider doing lazy evaluation/parsing of scope-properties (extracted from scope-value), so it is only done when actually needing to write LogEvent.

Maybe call the class `ThreadExecutionScopeContext` and the layout renderer `${scopecontext}` that matches `ILog.PushScopeContext`.

**Comment by 304NotModified** [comment]
Maybe we could combine this with #886  and #3425

**Comment by snakefoot** [comment]
Trying to make an implementation of this, but have now been bitten many ways by legacy CallContext.

Think legacy CallContext should continue to use `Dictionary<string,object>` and should probably change to `LinkedList<T>` for NDLC (more allocation but better compatibility). And stop using `ObjectHandleSerializer` since it is only a partial solution: #3817 (`Unable to find assembly 'NLog'`).

The optimization of merging MDLC and NDLC is only possible for AsyncLocal, which I guess is okay since NetCore / Net5 is the future. "Just" need to make an implementation that is somewhat elegant since CallContext lives on a little longer.

**Comment by snakefoot** [comment]
Made a performance test with NetCoreApp3.1:

This is the NLog-config:

```c#
            var jsonLayout = new NLog.Layouts.JsonLayout() { IncludeAllProperties = true, IncludeMdlc = true, SuppressSpaces = true };
            jsonLayout.Attributes.Add(new NLog.Layouts.JsonAttribute("@t", "\"${date:format=o:universaltime=true}\"") { Encode = false });
            jsonLayout.Attributes.Add(new NLog.Layouts.JsonAttribute("@mt", "${message:raw=true}"));
            jsonLayout.Attributes.Add(new NLog.Layouts.JsonAttribute("SourceContext", "${logger}"));
            jsonLayout.Attributes.Add(new NLog.Layouts.JsonAttribute("Scope", "${ndlc}"));

            var fileTarget = new NLog.Targets.FileTarget
            {
                Name = "FileTarget",
                FileName = @"C:\Temp\MicrosoftPerformance\NLog.txt",
                Layout = jsonLayout,
                KeepFileOpen = true,
                ConcurrentWrites = false,
                AutoFlush = false,
                OpenFileFlushTimeout = 1,
            };
```

This SingleScope in Microsoft-Extension-Logging:

```c#
            var newGuid = Guid.NewGuid();
            var loggerTemplate = LoggerMessage.Define(LogLevel.Information, default(EventId), messageTemplate);
            var beginScopeTemplate = LoggerMessage.DefineScope<Guid>("RequestId={id}");
            var logMethod = (messageFormat, messageArgs) =>
            {
                using (beginScopeTemplate(logger, newGuid))
                    loggerTemplate(logger, null);
            };
```

This DoubleScope in Microsoft-Extension-Logging:

```c#
            var newGuid = Guid.NewGuid();
            var loggerTemplate = LoggerMessage.Define(LogLevel.Information, default(EventId), messageTemplate);
            var beginScopeTemplate1 = LoggerMessage.DefineScope<Guid>("RequestId={id}");
            var beginScopeTemplate2 = LoggerMessage.DefineScope<string>("RequestMethod={method}");
            Action<string, object[]> logMethod = (messageFormat, messageArgs) =>
            {
                using (beginScopeTemplate1(logger, newGuid))
                {
                    using (beginScopeTemplate2(logger, nameof(logMethod)))
                        loggerTemplate(logger, null);
                }
            };
```

This is the performance if 1 log-message is written for each request:

| Test Name        | Messages   | Size | Args | Threads |
|------------------|------------|------|------|---------|
| SingleScope - 1 LogMessage |  1.000.000 |  128 |    0 |       1 |

| Test Name        | Time (ms) | Msgs/sec  | GC2 | GC1 | GC0 | CPU (ms) | Alloc (MB) |
|------------------|-----------|-----------|-----|-----|-----|----------|------------|
| NLog PR            |     6.036 |   165.647 |   0 |   0 |  62 |    5.750 |      854,5 |
| NLog Master            |     6.335 |   157.835 |   0 |   0 |  98 |    6.140 |    1.342,8 |
| Serilog CompactJson |     9.915 |   100.847 |   0 |   0 | 232 |    9.156 |    3.189,1 |


| Test Name        | Messages   | Size | Args | Threads |
|------------------|------------|------|------|---------|
| DoubleScope - 1 LogMessage |  1.000.000 |  128 |    0 |       1 |

| Test Name        | Time (ms) | Msgs/sec  | GC2 | GC1 | GC0 | CPU (ms) | Alloc (MB) |
|------------------|-----------|-----------|-----|-----|-----|----------|------------|
| NLog             |     7.566 |   132.160 |   1 |   1 | 107 |    7.218 |    1.464,9 |
| NLog Master            |     9.142 |   109.379 |   0 |   0 | 177 |    8.609 |    2.426,2 |
| Serilog CompactJson |    13.145 |    76.072 |   0 |   0 | 303 |   12.000 |    4.180,9 |

Lets say you only perform logging of slow and failed requests, this means most of the requests will never perform logging. This shows the performance of handling only successful events (Changed from `LogLevel.Information` to `LogLevel.Trace`)

| Test Name        | Messages   | Size | Args | Threads |
|------------------|------------|------|------|---------|
| SingleScope - 0 LogMessage |  10.000.000 |  128 |    0 |       1 |

| Test Name        | Time (ms) | Msgs/sec  | GC2 | GC1 | GC0 | CPU (ms) | Alloc (MB) |
|------------------|-----------|-----------|-----|-----|-----|----------|------------|
| NLog PR             |     2.970 | 3.366.267 |   0 |   0 | 186 |    3.125 |    2.594,0 |
| NLog Master       |     8.405 | 1.189.645 |   0 |   0 | 492 |    8.734 |    6.866,5 |
| Serilog CompactJson  |     3.866 | 2.586.210 |   0 |   0 | 315 |    4.046 |    4.425,0 |


| Test Name        | Messages   | Size | Args | Threads |
|------------------|------------|------|------|---------|
| DoubleScope - 0 LogMessage |  10.000.000 |  128 |    0 |       1 |

| Test Name        | Time (ms) | Msgs/sec  | GC2 | GC1 | GC0 | CPU (ms) | Alloc (MB) |
|------------------|-----------|-----------|-----|-----|-----|----------|------------|
| NLog PR          |     6.026 | 1.659.339 |   0 |   0 | 393 |    6.156 |    5.493,2 |
| NLog Master         |    20.144 |   496.415 |   0 |   0 | 1187 |   20.796 |   16.479,5 |
| Serilog CompactJson |     6.394 | 1.563.847 |   0 |   0 | 498 |    6.609 |    6.942,7 |

One might be curious why allocation increases when writing 0 log-messages, but it is because it is performing 10 Million iterations, instead of 1 million.
