### ISSUE TITLE
how can i add nlog in iserviceCollection(net core di)

### ISSUE THREAD

**Issue by quliting** [NLog/NLog#4059]
i use asp.net mvc core to do my work.i want to use di to reslove nlog.but i don't know how to do!
now .i use this code to get nlog .
_logger = LogManager.GetCurrentClassLogger();
and it works.but this is not my mean,i want use di ....
please.

**Comment by quliting** [comment]
i see in asp.net 3.0 example you use logger<Controller> .this is net core default log

**Comment by quliting** [comment]
ok sir

**Comment by quliting** [comment]
where is the template

**Comment by 304NotModified** [comment]
Please check https://github.com/NLog/NLog/wiki/Getting-started-with-ASP.NET-Core-3 or  https://github.com/NLog/NLog/wiki/Getting-started-with-.NET-Core-2---Console-application

**Comment by quliting** [comment]
it is  Microsoft.Extensions.Logging;not the nlog.i want to use nlog someFunction.

**Comment by 304NotModified** [comment]
Hi! Please explain better what you need. This sounds like a XY problem. 

Your question is now missing a lot of details. Also please fill in the template (you removed that one when creating this issue)

**Comment by quliting** [comment]
ok.i new issue with template.tks a lot
