### ISSUE TITLE
aspnet-traceidentifier not Producing the expected value.

### ISSUE THREAD

**Issue by klepeis** [NLog/NLog#4060]
Hi! Thanks for reporting this feature/bug/question! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

QUESTIONS are preferred on StackOverflow. You could expect a faster response there (but do include all the info below). Use the tag "nlog" https://stackoverflow.com/questions/ask

For .NET Core users, please check the platform support: https://github.com/NLog/NLog/wiki/platform-support

**NLog version**: 4.7.2
**NLog.Web.AspNetCore**: 4.9.2

**Platform**: .NET Core 3

**Current NLog config** (xml or C#, if relevant)

I just included the relevant portion of the NLog config.

```xml
<nlog>
  <targets>
     <target xsi:type="File" name="allFile" filename="c:\temp\nlog-all-${shortdate}.log" layout="${aspnet-TraceIdentifier}|${message}" />
  </targets>
  <rules>
  </rules>
</nlog>

```

```cscharp

public void Test(HttpContext context)
{
   // GetCorrelationId looks for a Guid in a header if one is not present a new guid is created.
   string correlationId = GetCorrelationId();
   // Store CorrelationId as TraceIdentifier
   context.TraceIdentifier = correlationId;

   logger.LogInformation($"CorrelationId is {correlationId}");
}

```

- What is the current result?  The current result is something along the lines of "b02f4cb8-4n816dc9307b716|CorrelationId is a99de049-1fe7-4b27-93fd-24d50bd9b231"
- What is the expected result? The expected result should be "a99de049-1fe7-4b27-93fd-24d50bd9b231|CorrelationId is a99de049-1fe7-4b27-93fd-24d50bd9b231"  Anywhere in my .Net Code when I access HttpContext.TraceIdentifier I am getting the correct value.  When when I use to layout render I am not getting the value that I set the TraceIdentifier too.
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)? I did, no errors.
- Please post full exception details (message, stacktrace, inner exceptions) No exceptions.
- Are there any workarounds? yes/no  Not that I have found.
- Is there a version in which it did work? Unsure.
- Can you help us by writing an unit test? I have provided a sample program. You can review the log and hopefully let me know what I am missing.
[NLogTest.zip](https://github.com/NLog/NLog/files/4991661/NLogTest.zip)

UPDATE:

I was able to get what I needed by creating a simple custom LayoutRendered that extended AspNetLayoutRendererBase and simply returned the Context.TraceIdentifier.  Still curious what value aspnet-traceidentifier is returning.

**Comment by 304NotModified** [comment]
I think you need ignoreActivityId=false in your case. 

So `${aspnet-traceidentifier:ignoreActivityId=false}`


For full details, see code: https://github.com/NLog/NLog.Web/blob/master/src/Shared/LayoutRenderers/AspNetTraceIdentifierLayoutRenderer.cs

We need to update the docs (https://github.com/NLog/NLog/wiki/AspNetTraceIdentifier-Layout-Renderer) I see

**Comment by klepeis** [comment]
Awesome!
${aspnet-traceidentifier:ignoreActivityId=true} did the trick for me.

Thanks so much!

**Comment by 304NotModified** [comment]
thanks for the feedback. The docs has been updated also :)
