### ISSUE TITLE
ConditionParseException: Unexpected token

### ISSUE THREAD

**Issue by MaciejKnera** [NLog/NLog#4063]
Hi,
I'm trying to adjust logging level in run-time based on user input but I'm missing something and get ConditionParseException. Here are few lines of code which I'm working with:

LogLevel logLevel = LogLevel.FromString(sortedLevels[0]);
                        
filter.Condition = $"level <= {logLevel}";
filter.Action = FilterResult.Log;

sortedLevels is a List<string> which contains levels given by user, they are validated and converted to form like: "Debug", "Info" etc.

What's interesting such code works fine:

filter.Condition = "level <= LogLevel.Warn"; 
filter.Action = FilterResult.Log;

I don't understand what exactly is wrong with my approach. At the beggining I had problem with converting string to Nlog.LogLevel but it's done correctly with method LogLevel.FromString()

Exact error message: "NLog.Conditions.ConditionParseException: 'Unexpected token: Debug'" - it happens when user inputs for example debug level.

Is there any possibility to make it work that way?

**Comment by MaciejKnera** [comment]
Hey, 
I've finally made it. If anyone will need to set filter dynamically from the code you can do that like that:

var filter = new ConditionBasedFilter();
filter.Condition = $"level == LogLevel.{variableName}";  
// == can be replaced with any other relational operations, of course
//you can add other conditions which are vaiable in when statements.
filter.Action = FilterResult.Log;

It was quite difficult to guess the syntax, hope it will save somebodys time :)

**Comment by snakefoot** [comment]
If you feel the existing example of the syntax is not enough, then the wiki is free to update:

https://github.com/NLog/NLog/wiki/when-Filter#examples

If you prefer to skip the string-parsing logic, then you can also make use of the `WhenMethodFilter`:

https://github.com/NLog/NLog/wiki/Filtering-log-messages#fully-dynamic-filtering
