### ISSUE TITLE
Advertisement: Blipboard, a new logging viewer

### ISSUE THREAD

**Issue by jtheisen** [NLog/NLog#4074]
Hi logging folks,

I made [Blipboard](https://blipboard.io/), a cloud service that can be used as a logging target and displays the logging events on a logarithmic time scale (just see the background of the linked page and you'll understand).

It's brand new, no customers yet, and I'll ask here at NLog first because that's what I use myself.

I would greatly appreciate any feedback.

It's a commercial offering but you can try it without a license.

(As an issue, you can basically just close it. I would just like to have one or two people tell me what they think.)

**Comment by snakefoot** [comment]
Funny that `https://blipboard.io/details` (Documentation) gives `500 Internal Server Error`

**Comment by jtheisen** [comment]
How embarassing. Fixed.

There's not dedicated target yet, just an example configuration on the previously broken [doc page](https://blipboard.io/details) using the NetworkTarget.

**Comment by 304NotModified** [comment]
As there isn't really an action for us here, I'm gonna close this one.
