### ISSUE TITLE
Database target: SUpport connectionStringName on .NET Core

### ISSUE THREAD

**Issue by leonardder** [NLog/NLog#4075]
**NLog version**: 4.7.3
**Platform**: .NET Core 3

The [Database target wiki page](https://github.com/nlog/NLog/wiki/Database-target) says about connectionStringName:

> Not supported on NetCore as app.config has been replaced with appsettings.json

While this is true, connection strings are stored in the ConnectionStrings dictionary:
```json
{
  "ConnectionStrings": {
    "SomeName": "Data Source=.;Initial Catalog=SomeDB;Persist Security Info=True;Integrated Security=true;"
  }
}
```

Wouldn't it be possible to support this by retrieving them from the configuration?

**Comment by 304NotModified** [comment]
Yes, you need now: https://github.com/NLog/NLog/wiki/ConfigSetting-Layout-Renderer

**Comment by snakefoot** [comment]
@leonardder Does it answer your question? so the issue can be resolved/closed

**Comment by leonardder** [comment]
Yes, that's certainly a solution for me. However, may be the docs about connectionStringName should point at this alternative to get a connection string by name?

**Comment by snakefoot** [comment]
Good idea. The Wiki is open for editing


Sent from my Sony Xperia


---- Leonard de Ruijter wrote ----


Yes, that's certainly a solution for me. However, may be the docs about connectionStringName should point at this alternative to get a connection string by name?

**Comment by leonardder** [comment]
Done.

**Comment by 304NotModified** [comment]
Thanks!!
