### ISSUE TITLE
Provide DEBUG-Conditional trace and debug methods

### ISSUE THREAD

**Issue by roji** [NLog/NLog#408]
A while ago I submitted PR #286, which was to add [Conditional("DEBUG")] on the Trace overloads. The rationale was for extremely latency- or CPU-sensitive applications, the NLog logic that checks whether TRACE is enabled is sometimes too expensive and should not be compiled into release builds. That PR was (understandably) rejected because not all users are latency-sensitive and it's a pretty big change for people already using trace.

Here's a better alternative... What about adding ConditionalTrace() and ConditionalDebug() versions on Logger, with [CONDITIONAL("DEBUG")] on them? This wouldn't break backwards-compatibility in any way, while providing this feature to latency-sensitive users. We currently have this implemented internally as extension methods to Logger, if you think this is a good idea I'll submit a PR to integrate this logic into Logger.

**Comment by 304NotModified** [comment]
:+1: for this idea

**Comment by 304NotModified** [comment]
I like to implement this feature. But I have no idea how to use this with the Fluent API, which has my preference. [See Fluent API introduction](http://nlog-project.org/2015/01/20/have-you-seen-our-new-fluent-interface.html)

For example:  I think this won't boost the performance much.
```
  logger.Info()
    .Property("id", 123)
    .Property("category", "test")
    .WriteConditional(); \\conditional, but previous lines evaluated in RELEASE
```
And I think this won't work/compile??
```
   logger.InfoConditional() \\conditional
    .Property("id", 123) 
    .Property("category", "test")
    .Write();
```

Has someone an idea how to combine the `[Conditional]` attributes with the fluent API?

**Comment by 304NotModified** [comment]
I'm looking at this feature request now. I will skip the fluent interface for now.

But the code has some interesting comments: 
`the following code has been automatically generated by a PERL script`
(see screenshot)

![image](https://cloud.githubusercontent.com/assets/5808377/6255464/633a43c6-b7b0-11e4-8c04-e6460a09784b.png)

@Xharze what should I do with this? I was thinking to create the "conditional" variants with a T4 template. But do I break then a PERL script?

**Comment by Xharze** [comment]
The Perl script is no longer used, as the file no longer is auto generated.

**Comment by 304NotModified** [comment]
Thanks @Xharze

**Comment by 304NotModified** [comment]
PR ready

**Comment by 304NotModified** [comment]
new PR #616
