### ISSUE TITLE
Windows Server 2008 R2 - NLog 4.7.1. Not able to add to GAC

### ISSUE THREAD

**Issue by RickC10** [NLog/NLog#4080]
Please need help asap.

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

For .NET Core users, please check the platform support: https://github.com/NLog/NLog/wiki/platform-support

**NLog version**: 4.7.1

**Platform**: .I've pulled down your NLog code and compiled the code and signed it form my company.  I have several test server running our project utilizing compiled 4.7.1 version of our compiled NLog.dll.  I've compiled NLog with Visual Studio 2019.  I did not change anything in your project. 

I noticed on functioning server NLog.dll exists on both c:\windows\Assembly and c:\windows\Microsoft .net\assembly.  

Where does NLog need to exist for application to run in a prod setting?  This is for a Windows Form application .Net 4.6.
Can I possibly remove the signing of the DLL so that I'm dealing with GAC issue and only deal with having DLL in Bin folder.

**Current NLog config** 
  ```xml
  <targets>
    <target xsi:type="File" name="GeneralInfo" fileName="${basedir}/Inventory.log">
      <layout xsi:type="JsonLayout" includeAllProperties="true">
        <attribute name="ApplicationName" layout="${ApplicationName}" />
        <attribute name="Logger" layout="${logger}" />
        <attribute name="UserIdentity" layout="${windows-identity}" />
        <attribute name="CorrelationID" layout="${activityid}" />
        <attribute name="CallSite" layout="${callsite}" />
        <attribute name="LineNumber" layout="${callsite-linenumber}" />
        <attribute name="LogDateTime" layout="${longdate}" />
        <attribute name="LogLevel" layout="${level:upperCase=true}"/>
        <attribute name="Message" layout="${message}" />
      </layout>
    </target>
  </targets>

  <rules>
    <logger name="General" writeTo="GeneralInfo"/>
  </rules>
</nlog>

```

- What is the current result?  Windows application not running as NLog is called at load form of initial screen. 
- What is the expected result?  Windows application runs as expected without error. 

- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
- Please post full exception details (message, stacktrace, inner exceptions)
- Are there any workarounds? No
- Is there a version in which it did work? Not sure
- Can you help us by writing an unit test?

**Comment by snakefoot** [comment]
So you have compiled and signed the NLog-assembly yourself, and now you ask why your custom build doesn't work?

What happens if you try and register the official NLog-assembly in the GAC? (Extracted from the [nuget-package](https://www.nuget.org/packages/NLog))

Btw. it is recommended not to use the GAC, since it generates all kinds of conflicts.

**Comment by RickC10** [comment]
The IT admin can copy NLog.dll into C:\windows\Micorosft .Net\assembly. To the root of this folder. However, he cant copy to C:\windows\assembly. 
Currently the application crashes at start up.  My assumption is that windows application can't find NLog.dll.

**Comment by RickC10** [comment]
If we dont use the GAC does that mean I need to remove the signing of the NLog.dll?  Do I also need to remove the NLog dll from GAC -  C:\windows\Micorosft .Net\assembly ??

**Comment by 304NotModified** [comment]
> Can I possibly remove the signing of the DLL so that I'm dealing with GAC issue and only deal with having DLL in Bin folder

There is no requirement to have NLog in the gac. You could add it to your bin folder. If you need to sign the NLog.dll is dependent of the rest of your code. PS: the NLog.dll is signed by nlog in the nuget package.

**Comment by snakefoot** [comment]
> If we dont use the GAC does that mean I need to remove the signing of the NLog.dll?

You don't have to remove the signing of the NLog.dll to use it without placing it in the GAC. 

The important part is to deploy the same NLog.dll in the bin-folder, that was used when compiling/building the application.

**Comment by RickC10** [comment]
I've removed all traces of NLog from the GAC.  I've pulled down a fresh nlog.dll 4.7.1 from nuget.  I ran the the application from a different server hitting the same  bits and it runs successfully. When I run it on a specific server, it fails.

**Comment by RickC10** [comment]
is there a way to trouble shoot this issue. I will summarize once more.  Bits run fine a server A.  On server B, the bits dont run. I was under the impression it was something incorrect in the GAC.   We removed nlog from the GAC.  Application does not run. Looks to be breaking on nlog reference.  Im making on the assumption. 
Another note.. I removed Nlog from the application and the application runs fine.

**Comment by 304NotModified** [comment]
Please check the [internal log](https://github.com/NLog/NLog/wiki/Internal-logging)

**Comment by RickC10** [comment]
I've modified internalLogLevel="Fatal". The internal log file is not being created.

**Comment by RickC10** [comment]
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="false"
      internalLogLevel="Fatal" internalLogFile="c:\temp\nlog-internal.log">
  <variable name="ApplicationName" value="Inventory"/>
  


  
  <targets>
    <target xsi:type="File" name="GeneralInfo" fileName="${basedir}/Inventory.log">
      <layout xsi:type="JsonLayout" includeAllProperties="true">
        <attribute name="ApplicationName" layout="${ApplicationName}" />
        <attribute name="Logger" layout="${logger}" />
        <attribute name="UserIdentity" layout="${windows-identity}" />
        <attribute name="CorrelationID" layout="${activityid}" />
        <attribute name="CallSite" layout="${callsite}" />
        <attribute name="LineNumber" layout="${callsite-linenumber}" />
        <attribute name="LogDateTime" layout="${longdate}" />
        <attribute name="LogLevel" layout="${level:upperCase=true}"/>
        <attribute name="Message" layout="${message}" />
      </layout>
    </target>
  </targets>

  <rules>
    <logger name="General" writeTo="GeneralInfo"/>
  </rules>
</nlog>

**Comment by RickC10** [comment]
`<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="false"
      internalLogLevel="Fatal" internalLogFile="c:\temp\nlog-internal.log">
  <variable name="ApplicationName" value="Inventory"/>
  


  
  <targets>
    <target xsi:type="File" name="GeneralInfo" fileName="${basedir}/Inventory.log">
      <layout xsi:type="JsonLayout" includeAllProperties="true">
        <attribute name="ApplicationName" layout="${ApplicationName}" />
        <attribute name="Logger" layout="${logger}" />
        <attribute name="UserIdentity" layout="${windows-identity}" />
        <attribute name="CorrelationID" layout="${activityid}" />
        <attribute name="CallSite" layout="${callsite}" />
        <attribute name="LineNumber" layout="${callsite-linenumber}" />
        <attribute name="LogDateTime" layout="${longdate}" />
        <attribute name="LogLevel" layout="${level:upperCase=true}"/>
        <attribute name="Message" layout="${message}" />
      </layout>
    </target>
  </targets>

  <rules>
    <logger name="General" writeTo="GeneralInfo"/>
  </rules>
</nlog>
`


<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="false"
      internalLogLevel="Fatal" internalLogFile="c:\temp\nlog-internal.log">
  <variable name="ApplicationName" value="Inventory"/>
  


  
  <targets>
    <target xsi:type="File" name="GeneralInfo" fileName="${basedir}/Inventory.log">
      <layout xsi:type="JsonLayout" includeAllProperties="true">
        <attribute name="ApplicationName" layout="${ApplicationName}" />
        <attribute name="Logger" layout="${logger}" />
        <attribute name="UserIdentity" layout="${windows-identity}" />
        <attribute name="CorrelationID" layout="${activityid}" />
        <attribute name="CallSite" layout="${callsite}" />
        <attribute name="LineNumber" layout="${callsite-linenumber}" />
        <attribute name="LogDateTime" layout="${longdate}" />
        <attribute name="LogLevel" layout="${level:upperCase=true}"/>
        <attribute name="Message" layout="${message}" />
      </layout>
    </target>
  </targets>

  <rules>
    <logger name="General" writeTo="GeneralInfo"/>
  </rules>
</nlog>

**Comment by RickC10** [comment]
Trying to copy in config file but editor is not allowing.

**Comment by snakefoot** [comment]
@RickC10 Have you tried using this tool to see why the application cannot load:

https://github.com/awaescher/Fusion?WT.mc_id=-blog-scottha

**Comment by 304NotModified** [comment]
> I've modified internalLogLevel="Fatal". The internal log file is not being created.


Please use level trace.

**Comment by RickC10** [comment]
@snakefoot I tied but Fusion utilizes DevExpress which are not available via nuget.

**Comment by snakefoot** [comment]
@RickC10 Not sure I understand. Just download https://github.com/awaescher/Fusion/releases/download/v1.3/Fusion++.1.3.zip and have it running while trying to launch the broken application.

**Comment by RickC10** [comment]
I believe I found the issue.  The target server where the application was not working. The target server did not have .Net Core runtime installed caused the NLog to fail.  I utilized the .Net 4.5 version of NLog and application worked on this specific server.

**Comment by snakefoot** [comment]
>  I utilized the .Net 4.5 version of NLog and application worked

Sounds like an excellent choice to use .NetFramework-assemblies for a .NetFramework-application.
