### ISSUE TITLE
Document and Example Project are not same

### ISSUE THREAD

**Issue by emreerkoca** [NLog/NLog#4085]
Hi, I tried to implement this to my project but document and examples are not same. The document contains this:

**Program.cs**
` var logger = NLog.Web.NLogBuilder.ConfigureNLog("nlog.config").GetCurrentClassLogger();`

and example project (for .Net Core 3) contains this:

**Program.cs**
`var logger = LogManager.Setup()
                                   .LoadConfigurationFromAppSettings()
                                   .GetCurrentClassLogger();`

Probably, you already know this situation and you might be bored when you read this issue but I think document and examples should be the same. :)

**Comment by snakefoot** [comment]
@emreerkoca Yes you are correct. It is just recently that `LogManager.Setup()` was made available with NLog.Web.AspNetCore ver. 4.9.3

- `LogManager.Setup()` extensions allows you to easily load appsettings.json (and make use of config-settings) before having created/started the NetCore Hosting Environment.
   - Improvement of `NLogBuilder.ConfigureNLog` that failed to support [${configsetting}](https://github.com/NLog/NLog/wiki/ConfigSetting-Layout-Renderer) without extra magic spells.

I have been poking several people about the new API being available (To people that complained about `NLogBuilder.ConfigureNLog`), so we could get some feedback, before saying this is now the new default in the Wiki.

I guess everyone perished in the Corona Waves or have gone on summer-vacation. But got one approval [here](https://stackoverflow.com/a/63345868/193178) :)

**Comment by emreerkoca** [comment]
@snakefoot I see this situation and thank you. I used this and it's working well. :) 

`var logger = NLog.Web.NLogBuilder.ConfigureNLog("nlog.config").GetCurrentClassLogger();`

**Comment by snakefoot** [comment]
Hehe funny and tragic at the same time. Happy weekend :)


Sent from my Sony Xperia


---- Emre Erkoca wrote ----


@snakefoot<https://github.com/snakefoot> I see this situation and thank you. I used this and it's working well. :)

var logger = NLog.Web.NLogBuilder.ConfigureNLog("nlog.config").GetCurrentClassLogger();

**Comment by emreerkoca** [comment]
@snakefoot You're right :) Thank you and have a nice weekend too :)

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, please let us know!

**Comment by emreerkoca** [comment]
> I assume your question has been answered, if not, please let us know!

Excuse me! I forgot to close the issue. Thank you!
