### ISSUE TITLE
LogEventInfo Constructor / Create methods with LoggerName-parameter should be obsolete

### ISSUE THREAD

**Issue by snakefoot** [NLog/NLog#4086]
NLog-users find it confusing that the Logger-Name specified with the LogEventInfo is not used for filtering.

The NLog-engine automatically assigns the correct Logger-Name to the LogEventInfo if not assigned. See also #2917

It doesn't make sense to have this confusion, and need to provide a parameter that is assigned automatically.

**Comment by Semirk0** [comment]
Can I have a look at this one?

**Comment by snakefoot** [comment]
I think it is a good idea, but maybe @304NotModified has a different opinion?


Sent from my Sony Xperia


---- Semirk0 wrote ----


Can I have a look at this one?

**Comment by 304NotModified** [comment]
Isn't it better that the logger name is used if provided? So no obsolete, but just use it. 

I think it's also confusing anyway

**Comment by snakefoot** [comment]
> Isn't it better that the logger name is used if provided? So no obsolete, but just use it.

One should not provide Logger-name since it will not be used as expected. But ofcourse one can always assign the Logger-property if wanted. But it will not work as expected (Just like it will not work as expected when using constructor-parameter):

```c#
var logEvent = new LogEventInfo();
logEvent.LogLevel = LogLevel.Info;
logEvent.Messsage = "Hello World";
logEvent.Logger = "Crazy";  // Will not be used for filtering
logger.Log(logEvent);
```

This is why I think the LoggerName should be removed as constructor-parameter and Create-parameter, since it confuses and often will not give the expected behavior. NLog-users that are doing obscure things with LogEventInfo.Logger-property can still assign it manually if needed.

> I think it's also confusing anyway

So you agree that we should obsolete interfaces that doesn't make sense, and causes confusion?

**Comment by 304NotModified** [comment]
> since it will not be used as expected.

Yes and maybe we should fix that? e.g. only set the .Logger property if it isn't set by someone before? That sounds like a more clean solution and saves another obsolete.

**Comment by snakefoot** [comment]
Then I prefer to leave the broken API alone, than introducing complex code and performance overhead. Better to just close this issue then.


Sent from my Sony Xperia


---- Julian Verdurmen wrote ----


since it will not be used as expected.

Yes and maybe we should fix that? e.g. only set the .Logger property if it isn't set by someone before? That sounds like a more clean solution and saves another obsolete.

**Comment by snakefoot** [comment]
Created #4131 as compromise to obsoleting the loggerName-parameter.
