### ISSUE TITLE
Can we use nLog for .Net C++ and QT qml?

### ISSUE THREAD

**Issue by ryakkali-BR** [NLog/NLog#4089]
Hi!

If you have a question that the logging isn't working, check the [troubleshooting guide](https://github.com/nlog/nlog/wiki/Logging-troubleshooting) first before posting.
Almost every case is solveble with the internal log

Are you searching for a layout or layout renderer? You could find them [here](https://nlog-project.org/config/)

Stackoverflow is recommend for questions. You could expect a faster response there (but do include all the info below) and the search is better.

For the stackoverfolow the following is recommend:

- Use the tag "nlog"
- Include versions of NLog/NLog.AspNetCore etc.
- Include the platform (.NET 4.5, ASP.NET Core 3 etc)
- Include the current config (xml or code)
- Explain current result
- Explain desired result
- Please post full exception details (message, stacktrace, inner exceptions) in case of an error

**Comment by ryakkali-BR** [comment]
Hi

This is Ramesh, I am working for Bio-Rad Laboratories in Hercules, CA.
I am investigating to evaluate a log tool for our new product.
We are using C++ with QT and qml.

Please let me know if the nLog logger supports our product.
If yes, please let me know some pointers to evaluate.

Thanks
Ramesh
________________________________

**Comment by 304NotModified** [comment]
Only .net is supported.
