### ISSUE TITLE
NLog.Web.AspNetCore layout renders are not working when configuring from code

### ISSUE THREAD

**Issue by markkerins** [NLog/NLog#4090]
Hi there,
I think this is a bug :) 
 **context** 
I'm trying to introduce a repeatable logging pattern in our organisation.  I've managed to get things working with the NLog.Config file. now I'm trying to migrate to an appsettings.json file

first cab off the rank is .net Core 3.1 
when I use the NLog  file approach I'm getting headers through the renderer ${aspnet-request-headers} 
when I use the appsettings.json approach  that value is missing  :( 
here is the nlog.config that works 

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" autoReload="true" internalLogLevel="info" 
      internalLogFile="d:\home\LogFiles\startupLog.txt">
  <extensions>

    <add assembly="NLog.Targets.Splunk" />
  </extensions>
  <!-- the targets to write to -->
  <targets async="true" >
    <!-- write to file -->
    <target xsi:type="File" name="traceData" fileName="d:\home\LogFiles\traceLogs\trace-${date:format=yyyy-MM-dd HH}.log"
            layout="${longdate}|${event-properties:item=EventId_Id}|${uppercase:${level}}|${logger}|${message} ${exception:format=tostring}"
            archiveEvery="Hour"
            maxArchiveFiles="24"

            
    />
    <!-- another file log. Uses some ASP.NET core renderers -->
    <target xsi:type="File" name="debug" fileName="d:\home\LogFiles\Nlog\Startup-debug-${date:format=yyyy-MM-dd HH-mm}.log"
           layout= "${longdate}|${level}|${logger}|${message}|${all-event-properties}|{exception:format=tostring}|${aspnet-request-headers}"
            archiveEvery="Minute"
            maxArchiveFiles="24"

            
    />
    <target name="Splunk"
            xsi:type="SplunkHttpEventCollector"
            serverUrl="https://asplunkhec.endpoint"
            token="we dont need to know this :) "
            channel="we dont need to know this :)"
            retriesOnError="0"
            layout="${message} ${exception:format=tostring}"
            IgnoreSslErrors="true">
      <contextproperty name="host" layout="${machinename}" />
      <contextproperty name="threadid" layout="${threadid}" />
      <contextproperty name="logger" layout="${logger}" />
      <contextproperty name="forwarded-client-ip" layout="${aspnet-request-ip:CheckForwardedForHeader=true}"></contextproperty>
      <contextproperty name="client-ip" layout="${aspnet-request-ip:CheckForwardedForHeader=false}"></contextproperty>
      <contextproperty name="headers" layout="${aspnet-request-headers}"></contextproperty>
      <contextproperty name="site" layout="${iis-site-name}"></contextproperty>
      <contextproperty name="Url" layout="${aspnet-request-url} "></contextproperty>
      <contextproperty name="framework" layout="Environment.Version.ToString()"></contextproperty>
    </target>

  </targets>
  <!-- rules to map from logger name to target -->
  <rules>
    <logger name="*" minlevel="Trace" writeTo="traceData" />
    <!--Skip non-critical Microsoft logs and so log only own logs-->
    <logger name="Microsoft.*" maxLevel="Info" final="true" />
    <logger name="*" minlevel="Debug" maxLevel="Debug" writeTo="debug" />
    <logger name="*" minlevel="Information" writeTo="Splunk" />
  </rules>
</nlog>
```

and here is the  
appsettings file 

```json
 "NLog": {
    "internalLogLevel": "Info",
    "internalLogFile": "d:\\home\\LogFiles\\Nlog\\internal-nlog.txt",
    "extensions": {
      "NLog.Web.AspNetCore": {
        "assembly": "NLog.Web.AspNetCore"
      }
    },
    "targets": {
      "allfile": {
        "type": "File",
        "fileName": "d:\\home\\LogFiles\\Nlog\\nlog-all-${shortdate}.log",
        "layout": "${longdate}|${event-properties:item=EventId_Id}|${uppercase:${level}}|${logger}|${message} ${exception:format=tostring}"
      },
      "ownFile-web": {
        "type": "File",
        "fileName": "d:\\home\\LogFiles\\Nlog\\nlog-own-${shortdate}.log",
        "layout": "${longdate}|${event-properties:item=EventId_Id}|${aspnet-request-headers}|${uppercase:${level}}|${logger}|${message} ${exception:format=tostring}|url: ${aspnet-request-url}|action: ${aspnet-mvc-action}"
      }
    },
    "rules": [
      {
        "logger": "*",
        "minLevel": "Trace",
        "maxLevel" : "Trace", 
        "writeTo": "allfile"
      },
      {
        "logger": "Microsoft.*",
        "maxLevel": "Info",
        "final": "true"
      },
      {
        "logger": "*",
        "minLevel": "Trace",
        "writeTo": "ownFile-web"
      }
    ]
  }
```
and here is how I'm wiring it up in code 
```csharp
 public void ConfigureServices(IServiceCollection services)
        {

            var section = Configuration.GetSection("NLog");
            var logconfiguration = new NLogLoggingConfiguration(section);
            var splunkTarget = new SplunkHttpEventCollector
            {
                IgnoreSslErrors = true,
                Token ="we dont need to know this :) ",
                ServerUrl = new Uri("https://asplunkhec.endpoint"),
                Layout = "${message} ${exception:format=tostring}",
                Name = "Splunk",
                ContextProperties =
                {
                    new TargetPropertyWithContext("host","${machinename}"),
                    new TargetPropertyWithContext("threadid","${threadid}"),
                    new TargetPropertyWithContext("logger","Nlog"),
                    new TargetPropertyWithContext("loggedfrom","${logger}"),
                    new TargetPropertyWithContext("headers","${aspnet-request-headers}"),
                    new TargetPropertyWithContext("Url","${aspnet-request-url}"),     
                    new TargetPropertyWithContext("Framework", Environment.Version.ToString()),
                }

            };


           logconfiguration.AddRule(NLog.LogLevel.Debug, NLog.LogLevel.Fatal, splunkTarget, "*");
            services.AddRazorPages();
            services.AddLogging(loggingBuilder =>
            {
                loggingBuilder.ClearProviders();
                loggingBuilder.AddNLog(logconfiguration);
                //loggingBuilder.AddNLog("NLog.config"); this works 
            });

        }
```

and here are my Nuget packages 
![image](https://user-images.githubusercontent.com/12518717/90471196-a3918b00-e171-11ea-9948-515f97bab49d.png)
Thanks 
Mark

**Comment by snakefoot** [comment]
Try this instead:

```c#
public void ConfigureServices(IServiceCollection services)
{
   NLog.LogManager.Setup()
      .RegisterNLogWeb(services)
      .LoadConfigurationFromSection(Configuration, "NLog")
      .LoadConfiguration(builder => {
        // TODO Move logic into own method                   
        var splunkTarget = new SplunkHttpEventCollector
        {
           IgnoreSslErrors = true,
           Token ="we dont need to know this :) ",
           ServerUrl = new Uri("https://asplunkhec.endpoint"),
           Layout = "${message} ${exception:format=tostring}",
           Name = "Splunk",
           ContextProperties =
           {
              new TargetPropertyWithContext("host","${machinename}"),
              new TargetPropertyWithContext("threadid","${threadid}"),
              new TargetPropertyWithContext("logger","Nlog"),
              new TargetPropertyWithContext("loggedfrom","${logger}"),
              new TargetPropertyWithContext("headers","${aspnet-request-headers}"),
              new TargetPropertyWithContext("Url","${aspnet-request-url}"),     
              new TargetPropertyWithContext("Framework", Environment.Version.ToString()),
           }
        };
        builder.Configuration.AddRule(NLog.LogLevel.Debug, NLog.LogLevel.Fatal, splunkTarget, "*");
     });
}
```

P.S. Stop using `NLog.config`-nuget-package it will only bring you pain. Stop using `NLog.AppSettings.Standard` and instead use [${configsetting}](https://github.com/NLog/NLog/wiki/ConfigSetting-Layout-Renderer)-LayoutRenderer.

**Comment by snakefoot** [comment]
@markkerins Any reason why you don't configure the `splunkTarget` in the `appsettings.json` ?

```json
 "NLog": {
    "throwConfigExceptions": true,
    "internalLogLevel": "Info",
    "internalLogFile": "d:\\home\\LogFiles\\Nlog\\internal-nlog.txt",
    "extensions": [
      { "assembly": "NLog.Extensions.Logging" },
      { "assembly": "NLog.Web.AspNetCore" },
      { "assembly": "NLog.Targets.Splunk" }
    ],
    "targets": {
      "allfile": {
        "type": "File",
        "fileName": "d:\\home\\LogFiles\\Nlog\\nlog-all-${shortdate}.log",
      },
      "ownFile-web": {
        "type": "File",
        "fileName": "d:\\home\\LogFiles\\Nlog\\nlog-own-${shortdate}.log",
      },
      "splunk": {
        "type": "SplunkHttpEventCollector",
        "serverUrl": "https://asplunkhec.endpoint",
        "token": "we dont need to know this :)",
        "channel": "we dont need to know this :)",
        "retriesOnError": 0,
        "layout": "${message} ${exception:format=tostring}",
        "IgnoreSslErrors": true,
        "contextproperties": [
            {
              "name": "host",
              "layout": "${machinename}"
            },
            {
              "name": "threadid",
              "layout": "${threadid}"
            },
            {
              "name": "logger",
              "layout": "${logger}"
            },
            {
              "name": "message",
              "layout": "${message:raw=true}"
            }
          ]
      }
    },
    "rules": [
      {
        "logger": "*",
        "minLevel": "Trace",
        "maxLevel" : "Trace", 
        "writeTo": "allfile"
      },
      {
        "logger": "Microsoft.*",
        "maxLevel": "Info",
        "final": "true"
      },
      {
        "logger": "*",
        "minLevel": "Trace",
        "writeTo": "ownFile-web"
      },
      {
        "logger": "*",
        "minLevel": "Info",
        "writeTo": "splunk"
      }
    ]
  }
```

**Comment by markkerins** [comment]
Hi Rolf,

Thanks for your reply 

I had a few reasons for hand rolling it (rightly or wrongly :) ) 
1.  I want to store the token in Keyvault, (you've given me a pointer into how I can do that)
2. the really nice thing with NLog is multiple targets.  I can see advantages for certain applications to be able to extend the base logging to address application specific logging. I dont want these applications to be able to replace the core logging  with their own application specific logging
3. finally I want to be able to pass the .net core version /.net framework version to splunk  (Environment.Version.ToString()) . again you've pointed me in a direction that might achieve that through configuration

Thanks again
Mark

**Comment by markkerins** [comment]
Hey @snakefoot ,
I got your suggested alternative working, thanks.
however the issue I have is still the same.
using an  nlog.config (traditional xml config) 
and adding a contextproperty for the http headers 
`  <contextproperty name="headers" layout="${aspnet-request-headers}"></contextproperty>`
I get all the headers coming through to Splunk
using  the suggested appsettings implementation  and  add the property as
`  new TargetPropertyWithContext("headers", "${aspnet-request-headers}"),`
the property name comes through but its value is not populated 
as you can see the same is true for the url  which is using the renderer ${aspnet-request-url}
![image](https://user-images.githubusercontent.com/12518717/90620261-53482500-e266-11ea-996e-2a0a1d048c39.png)
thanks 
Mark

**Comment by snakefoot** [comment]
Guess you have to enable the NLog InternalLogger as suggested above. And then check the output for issues.


Sent from my Sony Xperia


---- markkerins wrote ----


Hey @snakefoot<https://github.com/snakefoot> ,
I got your suggested alternative working, thanks.
however the issue I have is still the same.
using an nlog.config (traditional xml config)
and adding a contextproperty for the http headers
<contextproperty name="headers" layout="${aspnet-request-headers}"></contextproperty>
I get all the headers coming through to Splunk
using the suggested appsettings implementation and add the property as
new TargetPropertyWithContext("headers", "${aspnet-request-headers}"),
the property name comes through but its value is not populated
as you can see the same is true for the url which is using the renderer ${aspnet-request-url}
[image]<https://user-images.githubusercontent.com/12518717/90620261-53482500-e266-11ea-996e-2a0a1d048c39.png>
thanks
Mark

**Comment by markkerins** [comment]
I thought I had that enabled 
`{

  "NLog": {
    "internalLogLevel": "Info",
    "internalLogFile": "d:\\home\\LogFiles\\Nlog\\internal-nlog_settings.txt",

    "extensions": {
      "NLog.Web.AspNetCore": {
        "assembly": "NLog.Web.AspNetCore"
      }
    },
    "targets": {
      "allfile": {
        "type": "File",
        "fileName": "d:\\home\\LogFiles\\Nlog\\settings-nlog-all-${shortdate}.log",
        "layout": "${longdate}|${event-properties:item=EventId_Id}|${uppercase:${level}}|${logger}|${message} ${exception:format=tostring}"
      },
      "ownFile-web": {
        "type": "File",
        "fileName": "d:\\home\\LogFiles\\Nlog\\settings-nlog-own-${shortdate}.log",
        "layout": "${longdate}|${event-properties:item=EventId_Id}|${aspnet-request-headers}|${uppercase:${level}}|${logger}|${message} ${exception:format=tostring}|url: ${aspnet-request-url}|action: ${aspnet-mvc-action}"
      }
    },
    "rules": [
      {
        "logger": "*",
        "minLevel": "Trace",
        "maxLevel" : "Trace", 
        "writeTo": "allfile"
      },
      {
        "logger": "Microsoft.*",
        "maxLevel": "Info",
        "final": "true"
      },
      {
        "logger": "*",
        "minLevel": "Trace",
        "writeTo": "ownFile-web"
      }
    ]
  },
  "AllowedHosts": "*"
}
`

here is what is logged to the internal logger file 
2020-08-19 10:03:31.7784 Info Message Template Auto Format enabled
2020-08-19 10:03:31.9595 Info Loading assembly: NLog.Web.AspNetCore
2020-08-19 10:03:32.1600 Info Adding target FileTarget(Name=allfile)
2020-08-19 10:03:32.1897 Info Adding target FileTarget(Name=ownFile-web)
2020-08-19 10:03:32.2735 Info Validating config: TargetNames=allfile, ownFile-web, ConfigItems=47
2020-08-19 10:03:32.3395 Info Validating config: TargetNames=allfile, ownFile-web, Splunk, ConfigItems=75

**Comment by snakefoot** [comment]
Can you lower internalLogLevel to Debug (Instead of Info) and try again?


Sent from my Sony Xperia


---- markkerins wrote ----


I thought I had that enabled
`{

"NLog": {
"internalLogLevel": "Info",
"internalLogFile": "d:\home\LogFiles\Nlog\internal-nlog_settings.txt",

"extensions": {
  "NLog.Web.AspNetCore": {
    "assembly": "NLog.Web.AspNetCore"
  }
},
"targets": {
  "allfile": {
    "type": "File",
    "fileName": "d:\\home\\LogFiles\\Nlog\\settings-nlog-all-${shortdate}.log",
    "layout": "${longdate}|${event-properties:item=EventId_Id}|${uppercase:${level}}|${logger}|${message} ${exception:format=tostring}"
  },
  "ownFile-web": {
    "type": "File",
    "fileName": "d:\\home\\LogFiles\\Nlog\\settings-nlog-own-${shortdate}.log",
    "layout": "${longdate}|${event-properties:item=EventId_Id}|${aspnet-request-headers}|${uppercase:${level}}|${logger}|${message} ${exception:format=tostring}|url: ${aspnet-request-url}|action: ${aspnet-mvc-action}"
  }
},
"rules": [
  {
    "logger": "*",
    "minLevel": "Trace",
    "maxLevel" : "Trace",
    "writeTo": "allfile"
  },
  {
    "logger": "Microsoft.*",
    "maxLevel": "Info",
    "final": "true"
  },
  {
    "logger": "*",
    "minLevel": "Trace",
    "writeTo": "ownFile-web"
  }
]


},
"AllowedHosts": "*"
}
`

here is what is logged to the internal logger file
2020-08-19 10:03:31.7784 Info Message Template Auto Format enabled
2020-08-19 10:03:31.9595 Info Loading assembly: NLog.Web.AspNetCore
2020-08-19 10:03:32.1600 Info Adding target FileTarget(Name=allfile)
2020-08-19 10:03:32.1897 Info Adding target FileTarget(Name=ownFile-web)
2020-08-19 10:03:32.2735 Info Validating config: TargetNames=allfile, ownFile-web, ConfigItems=47
2020-08-19 10:03:32.3395 Info Validating config: TargetNames=allfile, ownFile-web, Splunk, ConfigItems=75

**Comment by markkerins** [comment]
hi @snakefoot 

:D I was wondering why you were on the interlogger path.
after I changed the  level to debug, it all made sense


2020-08-19 19:45:47.3977 Debug Missing serviceProvider, so no HttpContext
2020-08-19 19:45:47.3977 Debug Missing serviceProvider, so no HttpContext
2020-08-19 19:45:47.4095 Debug Missing serviceProvider, so no HttpContext
2020-08-19 19:45:47.4220 Debug Missing serviceProvider, so no HttpContext
2020-08-19 19:45:47.4220 Debug Missing serviceProvider, so no HttpContext
2020-08-19 19:45:47.4378 Debug Missing serviceProvider, so no HttpContext
2020-08-19 19:45:47.4576 Debug Missing serviceProvider, so no HttpContext
2020-08-19 19:45:47.4710 Debug Missing serviceProvider, so no HttpContext
2020-08-19 19:45:47.4710 Debug Missing serviceProvider, so no HttpContext
2020-08-19 19:45:47.4876 Debug Missing serviceProvider, so no HttpContext
2020-08-19 19:45:47.7177 Debug Missing serviceProvider, so no HttpContext
2020-08-19 19:45:47.7177 Debug Missing serviceProvider, so no HttpContext
2020-08-19 19:45:47.7177 Debug Missing serviceProvider, so no HttpContext
2020-08-19 19:45:47.7362 Debug Missing serviceProvider, so no HttpContext
2020-08-19 19:45:47.7362 Debug Missing serviceProvider, so no HttpContext
2020-08-19 19:45:47.7362 Debug Missing serviceProvider, so no HttpContext
2020-08-19 19:45:47.7529 Debug Missing serviceProvider, so no HttpContext
2020-08-19 19:45:47.7529 Debug Missing serviceProvider, so no HttpContext
2020-08-19 19:45:47.7811 Debug Missing serviceProvider, so no HttpContext
2020-08-19 19:45:47.7811 Debug Missing serviceProvider, so no HttpContext
2020-08-19 19:45:47.7811 Debug Missing serviceProvider, so no HttpContext
2020-08-19 19:45:47.7955 Debug Missing serviceProvider, so no HttpContext
2020-08-19 19:45:47.7955 Debug Missing serviceProvider, so no HttpContext
2020-08-19 19:45:47.7955 Debug Missing serviceProvider, so no HttpContext
2020-08-19 19:45:47.8135 Debug Missing serviceProvider, so no HttpContext
2020-08-19 19:45:47.8135 Debug Missing serviceProvider, so no HttpContext
2020-08-19 19:45:47.8288 Debug Missing serviceProvider, so no HttpContext
2020-08-19 19:45:47.8288 Debug Missing serviceProvider, so no HttpContext
2020-08-19 19:45:47.8288 Debug Missing serviceProvider, so no HttpContext
2020-08-19 19:45:47.8453 Debug Missing serviceProvider, so no HttpContext

thanks 
Mark

**Comment by snakefoot** [comment]
Never developed any AspNetCore-applications, so just writing code without compiling or testing. But you are right `IServiceCollection` cannot directly convert to `IServiceProvider`.

Guess you need to add this after `NLog.LogManager.Setup()`

```c#
    services.AddLogging(builder =>
    {
        builder.ClearProviders();
        builder.AddNLog();
    });
```

Have updated my original https://github.com/NLog/NLog/issues/4090#issuecomment-675675942

**Comment by markkerins** [comment]
:)  
I did have that in the code 
`   public void ConfigureServices(IServiceCollection services)
        {
          
             LogManager.Setup()
                .RegisterNLogWeb(Configuration).LoadConfigurationFromSection(Configuration, "NLog")
                .LoadConfiguration(builder =>
                {
                    var splunkTarget = new SplunkHttpEventCollector
                    {
                        IgnoreSslErrors = true,
                        Token = "******",
                        ServerUrl = new Uri("****"),
                        Layout = "${message} ${exception:format=tostring}",
                        Name = "Splunk",
                        ContextProperties =
                        {
                            new TargetPropertyWithContext("host", "${machinename}"),
                            new TargetPropertyWithContext("threadid", "${threadid}"),
                            new TargetPropertyWithContext("logger", "Nlog"),
                            new TargetPropertyWithContext("loggedfrom", "${logger}"),
                            new TargetPropertyWithContext("headers", "${aspnet-request-headers}"),
                            new TargetPropertyWithContext("Url", "${aspnet-request-url}"),
                            new TargetPropertyWithContext("Framework", Environment.Version.ToString()),
                        }

                    };
                    builder.Configuration.AddRule(NLog.LogLevel.Debug, NLog.LogLevel.Fatal, splunkTarget, "*");
                });
             services.AddRazorPages();
            services.AddLogging(loggingBuilder =>
            {
                loggingBuilder.ClearProviders();
                loggingBuilder.AddNLog(Configuration);
                //loggingBuilder.AddNLog("NLog.config"); this works 
            });
 


        }`

**Comment by snakefoot** [comment]
Ahh maybe you are using namespace `NLog.Extension.Logging` and not `NLog.Web`

**Comment by snakefoot** [comment]
@markkerins Think I have fixed the call to `AddNLog` so it actually compiles. When including `using NLog.Web`.

**Comment by markkerins** [comment]
:D  I was struggling with it too . 
I managed to get it working using your line  
loggingBuilder.AddNlog(provider=>null) ;  
however ..
the method LoadConfigurationFromSection has a dependency on NLog.Extensions.Logging :( 
what I ended up doing was creating an extension method for IServiceCollection  and isolated it in its own class 
`using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using NLog.Web;
namespace core.webapp
{
    public static class helperAddNlog
    {

        public static void AddLogger( this IServiceCollection services )
        {
            services.AddLogging(loggingBuilder =>
            {
                loggingBuilder.ClearProviders();
                loggingBuilder.AddNLog(provider => null);


            });
        }

         
    }
}
`

**Comment by snakefoot** [comment]
Yes not very elegant work-around. This should be improved.

**Comment by markkerins** [comment]
@snakefoot  thanks heaps for your help on this. I really appreciate it.

**Comment by 304NotModified** [comment]
> IServiceCollection and not of type IServiceProvider

PS:
- IServiceCollection  is write only (registrations)
- You could build a IServiceProvider With [.BuildServiceProvider()](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.servicecollectioncontainerbuilderextensions.buildserviceprovider?view=dotnet-plat-ext-3.1)
- IServiceProvider  is read-only (only resolving)

**Comment by snakefoot** [comment]
[NLog.Web.AspNetCore ver. 4.10](https://www.nuget.org/packages/NLog.Web.AspNetCore/) has been released that includes https://github.com/NLog/NLog.Web/pull/602

So you can now use `AddNLogWeb` like this:

```c#
using NLog.Web

            services.AddLogging(loggingBuilder =>
            {
                loggingBuilder.ClearProviders();
                loggingBuilder.AddNLogWeb(provider => null); // Use the one from NLog.Web to fix Missing serviceProvider, so no HttpContext
            });
```
