### ISSUE TITLE
MaxArchiveFiles not working

### ISSUE THREAD

**Issue by ddisys** [NLog/NLog#4098]
Hi!

We are using NLog 4.5.8 with a .NET 4.6 windows application. 
This is how the setting is set through code. for LogLevl Info.
The Archive does happen every day. But the MaxArchiveFiles feature does not seem to work. I see more than 5 files in the Log Arcive folder. What am I doing wrong?

![image](https://user-images.githubusercontent.com/17656065/91178358-04115280-e6b3-11ea-8818-ae1b77df7860.png)

Thanks
Sowmya

**Comment by 304NotModified** [comment]
Please upgrade NLog. There have been many changes with archiving the last 2 years

maybe also the setting maxArchiveDays  is good to use, see https://github.com/NLog/NLog/wiki/File-target

**Comment by ddisys** [comment]
OK Thanks. I upgraded to 4.7. But still the above  settings does not seem to delete the files older then 5 days. Is it the Dateformat?

**Comment by snakefoot** [comment]
@ddisys Can you activate the NLog InternalLogger at Debug-Level, then one can investigate what happens when it performs archive on day-roll ? https://github.com/NLog/NLog/wiki/Internal-Logging
