### ISSUE TITLE
Line number is always 0 in log file

### ISSUE THREAD

**Issue by liaoliaoda** [NLog/NLog#4100]
Hi!

I am using NLog 4.7.0 in .Net Standard 2.0 and the startup project is a .NET Framework 4.6.1 console windows application.

The console windows application references the standard project.

NLog print results are as follows:
2020-08-28 16:20:55.8411 | Error | SDK.Device.Transport.Connection.OnClientDisconnected:0 - Message1
2020-08-28 16:22:55.8411 | Error | SDK.Device.Transport.Connection.OnClientDisconnected:0 - Message2

As you can see, the line number of code is always 0.

NLog.config content is as below:

```xml
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="false"
      internalLogLevel="Off" internalLogFile="c:\temp\nlog-internal.log">

  <variable name="myvar" value="myvalue"/>

  <targets>
    
    <target name="file_log"
      xsi:type="File"
      maxArchiveFiles="30"
      fileName="${basedir}/logs/log${shortdate}.txt"
      layout="${longdate} | ${level:uppercase=false} | ${callsite:fileName}:${callsite-linenumber} - ${message} ${onexception:${exception:format=tostring} ${newline} ${stacktrace} ${newline}" />
  </targets>

  <rules>
    <logger name="*" minlevel="Trace" writeTo="file_log" />
  </rules>
</nlog>
```

If the startup project of .NET Framework 4.6.1 console windows application is replaced by .NET Core 2.2 console windows application, the printing result is normal.

If the ClassLibrary of .Net Standard 2.0 is replaced by ClassLibrary of .NET Framework 4.6.1, the printing result is also normal.

Thanks very much for helping to look at this problem.

**Comment by 304NotModified** [comment]
Have you seen this comment?

> If symbol symbol information is not available, then it will only output source-code line-number 0. Symbol information from PDB files must be deployed with the application to retrieve and output source-code line-number. For applications compiled in release mode, then inlining can occur and cause "unexpected" line-numbers.

From: 
https://github.com/NLog/NLog/wiki/Callsite-line-number-layout-renderer

**Comment by snakefoot** [comment]
Also notice that only Net472 (or newer) is able to handle PDB-files compiled for NetStandard. Net461 cannot parse the new PDB-file-format.

**Comment by liaoliaoda** [comment]
> Have you seen this comment?
> 
> > If symbol symbol information is not available, then it will only output source-code line-number 0. Symbol information from PDB files must be deployed with the application to retrieve and output source-code line-number. For applications compiled in release mode, then inlining can occur and cause "unexpected" line-numbers.
> 
> From:
> https://github.com/NLog/NLog/wiki/Callsite-line-number-layout-renderer

ok, thank you for response. By the way,  how to deployed Symbol information from PDB files with the application to retrieve and output source-code line-number?

**Comment by snakefoot** [comment]
>  @liaoliaoda By the way, how do you deploy Symbol information (PDB files) and the application together to retrieve and output source-code line-number?

Sounds like a question for stackoverflow.
