### ISSUE TITLE
NLog.Schema does not support enabled attribute for logger rules

### ISSUE THREAD

**Issue by DavidMartinOnGitHub** [NLog/NLog#4101]
Using NLog.Schema 4.7.4 from NuGet package on .Net Framework 4.6.1

Visual Studio Project has NLog, NLog.Config and NLog.Schema installed from NuGet package.

Visual Studio does not recognize the **enabled** attribute in a **logger rule**. The enabled attribute is legal and functional. Visual Studio renders the rule with a squiggly underline and a hover-over message that states that "the enabled attribute is not declared".

The schema at   http://www.nlog-project.org/schemas/NLog.xsd has the enabled attribute declared but the NLog.xsd that gets included in the Visual Studio project does not. It would appear that Visual Studio is using the local file for intellisense.

When I update the local NLog.xsd to include the following :

```
    <xs:attribute name="enabled" type="xs:boolean" default="true">
        <xs:annotation>
            <xs:documentation>Enable this rule. Note: disabled rules aren't available from the API.</xs:documentation>
            </xs:annotation>
        </xs:attribute>

```

between the 'final' and 'ruleName' blocks that Visual Studio shows the appropriate documentation message.

**Comment by snakefoot** [comment]
Strange since `enabled` should be part of official schema:

https://github.com/NLog/NLog/blob/56ff6f45a2257fac8ca48a44dac2082e0a24b8d1/tools/MakeNLogXSD/TemplateXSD.xml#L177

And when looking in the XSD-file in the [nuget-package](https://www.nuget.org/packages/NLog.Schema), then it says this:

```xml
    <xs:attribute name="final" type="xs:boolean" default="false">
      <xs:annotation>
        <xs:documentation>Ignore further rules if this one matches.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="enabled" type="xs:boolean" default="true">
      <xs:annotation>
        <xs:documentation>Enable this rule. Note: disabled rules aren't available from the API.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="ruleName" type="xs:string" use="optional">
      <xs:annotation>
        <xs:documentation>Rule identifier to allow rule lookup with Configuration.FindRuleByName and Configuration.RemoveRuleByName.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
```
