### ISSUE TITLE
Date layout renderer not properly formatting custom date format with escaped M

### ISSUE THREAD

**Issue by TBSenseo** [NLog/NLog#4108]
Hello NLog development team,

I am trying to use a custom date format for the file name of a programmatically initialized FileTarget. As file name string I am trying to use "${processdir}/logs/verbose${date:format=\\\\Yyyyy\\\\MMM\\\\Ddd}.log" and would like to get a file name like "\<executable directory\>/logs/verboseY2020**M09**D04.log", but when I use it I get a file created in "\<executable directory\>/logs/verboseY2020**Sep**D04.log". When I try this formatting string with the DateTime.ToString function, "DateTime.Now.ToString("\\\\Yyyyy\\\\MMM\\\\Ddd")", within the QuickWatch window when debugging, then this evaluates correctly. Such it contradicts, what is described in [Date Layout Renderer](https://github.com/NLog/NLog/wiki/Date-Layout-Renderer) documentation.

I am using this in a Visual C# Forms project in Visual Studio 2019 with .NET Framework 4.7.2 and the NLog library 4.7.4 from NuGet.

Best regards,
TBSenseo

**Comment by snakefoot** [comment]
Made a small test with NLog 4.7.4 with the following layout:

`layout="${date:format=\\Yyyyy-\\MMM-\\Ddd}"`

And it generate the same output as:

`DateTime.Now.ToString("\\Yyyyy-\\MMM-\\Ddd")`

Can you attach a small sample-project to the issue that demonstrates the issue you are seeing?

**Comment by snakefoot** [comment]
I have been able to reproduce it when doing this:

```c#
NLog.Layouts.Layout layout = "${date:format=\\Yyyyy-\\MMM-\\Ddd}";
var ei = new LogEventInfo(LogLevel.Info, "logger", "msg");
Assert.Equal(ei.TimeStamp.ToString("\\Yyyyy-\\MMM-\\Ddd"), layout.Render(ei));
```

**Comment by TBSenseo** [comment]
[NLogIssueExample.zip](https://github.com/NLog/NLog/files/5183918/NLogIssueExample.zip) is the example. The application is reading the actual file name pattern with the date format string from the application settings file and then initialize NLog programmatically when the MainForm is initialized. When then button is clicked, the event handler logs a test message. NLog as reaction creates a log file, e. g. "bin\Debug\logs\verboseY2020SepD07.log" or "bin\Release\logs\verboseY2020SepD07.log" instead of the expected "verboseY2020M09D07.log" file in these directories. As double check, I update some labels with a fixed date format string and another one where the date format portion is programmatically determined without NLog and then formatted using the regular DateTime.Now.ToString(<format string>) function.

**Comment by TBSenseo** [comment]
@snakefoot, I now tried your variant with the minus symbols removed: "${date:format=\\\\Yyyyy\\\\MMM\\\\Ddd}". It works now as expected. I did not know that it needs double escape characters.
But, the Date Layout Renderer also does not say this. They use the example `${date:format=yyyy-MM-dd HH\:mm\:ss.fff}` and such only use simple escape characters. I will now think about if I add code such that I can specify the path with single escaped letters in the application settings file and the code will duplicate them before giving the path to NLog.
Should we update the Date Layout Renderer page for this example?

**Comment by snakefoot** [comment]
When doing this from code:

`NLog.Layouts.Layout layout = "${date:format=\\Yyyyy-\\MMM-\\Ddd}"`

Then you become victim of the dotnet-compiler-string-escape-logic. The solution is either to do this:

`NLog.Layouts.Layout layout = "${date:format=\\\\Yyyyy-\\\\MMM-\\\\Ddd}";`

Or disable the dotnet-compiler-string-escape-logic using `@`:

`NLog.Layouts.Layout layout = @"${date:format=\\Yyyyy-\\MMM-\\Ddd}";`

The example in the Wiki is for doing configuration using `NLog.config`-xmlfile, where you do not become victim of dotnet-compiler-string-escape-logic. I guess one could update the Wiki about being aware the dotnet-compiler-string-escape-logic, and that it can be a good idea to use `@`.

**Comment by TBSenseo** [comment]
I am still unsure why quadruple slashes need to be used. The escapes in the string are converted each in pairs to slashes. This is very common in programming languages and I am used to that, e. g. in Python you can write '\\\\' or r'\\' to get the same result. But what I do not yet understand is why NLop needs a string with double escaped letters. There seems to be a stage within NLop that converts the double slashes to single slashes before passing the string to DateTime.ToString in function DateLayoutRenderer.GetStringValue (see src/NLog/LayoutRenderers/DateTime/DateLayoutRenderer.cs of the NLog code base). I do not have the bare code checked out and such cannot trace what is done to the string passed to FileTarget.FileName (see src/NLog/Targets/FileTarget.cs).

**Comment by snakefoot** [comment]
The escaping shown in the wiki, shows how to escape `:` that has special meaning for NLog-LayoutRenderer-parser to handle Property-values (Notice property-value `:format` starts with `:`).

Because `\` has special meaning for the NLog-LayoutRenderer-parser, then it needs a bonus-escape. So it has to be `\\`.

**Comment by snakefoot** [comment]
Have now updated the wiki: https://github.com/NLog/NLog/wiki/Date-Layout-Renderer

**Comment by TBSenseo** [comment]
Thanks. I now dared to modify the page after you modified it and added more in depth on the result.
