### ISSUE TITLE
Nlog threwexception=false wcf traget issue

### ISSUE THREAD

**Issue by Grant-Liu** [NLog/NLog#411]
We found a issue and we think you should know about it.
We are using 2.1.0.0 which build for .Nnet 3.5
.
If the target is async of wcf service,you config the threwexception=false then it start to sending constanctly empty event entry to wcf server.
It made our server cpu to >90%.

We also need to add checker on all place before write to target.
if (logEventInfos != null && logEventInfos.Length > 0)

I have fixed it in the code.
Please update your release also.

**Comment by 304NotModified** [comment]
@Grant-Liu if this is still a problem, please submit the requested info and re-open this issue.
