### ISSUE TITLE
How to output NLog log to Rider's console

### ISSUE THREAD

**Issue by ZhouJiaZhi** [NLog/NLog#4112]
I use Rider as the editor of Unity. How do I redirect the log output from Nlog to Rider's console?

**Comment by snakefoot** [comment]
Rider seems to have support for displaying [Unity Console](https://docs.unity3d.com/Manual/Console.html):

https://blog.jetbrains.com/dotnet/2018/04/10/view-unity-console-logs-directly-rider-2018-1/

You can write to Unity Console using [UnityEngine.Debug](https://docs.unity3d.com/Manual/class-Debug.html):

You can make [you own NLog-target](https://github.com/NLog/NLog/wiki/How-to-write-a-custom-target) like this:

```c#
    [Target("UnityConsole")] 
    public class UnityConsoleTarget : TargetWithLayout
    { 
        protected override void Write(LogEventInfo logEvent)
        {
              string logMessage = RenderLogEvent(this.Layout, logEvent);
              if (logEvent.LogLevel <= LogLevel.Info)
                  UnityEngine.Debug.Log(message);
              else if (logEvent.LogLevel == LogLevel.Warn)
                  UnityEngine.Debug.LogWarning(message);
              else
                  UnityEngine.Debug.LogError(message);
        }

        protected override void CloseTarget()
        {
            _dispatcher = null;
        }
    }
```

And you can [configure the target](https://github.com/nlog/nlog/wiki/Tutorial) together with Unity-Bootstrap:

```c#
using System.IO;
using UnityEngine;

public static class Bootstrap
{
    [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.BeforeSceneLoad)]
    private static void ConfigureLogging()
    {
       var config = new NLog.Config.LoggingConfiguration();

       // Targets where to log to: File and Console
       var unityConsole = new UnityConsoleTarget() { Name = "Unity" };
            
       // Rules for mapping loggers to targets            
       config.AddRule(LogLevel.Info, LogLevel.Fatal, unityConsole);
            
       // Apply config           
       NLog.LogManager.Configuration = config;

       // Generate output
       NLog.LogManager.GetCurrentClassLogger().Info("Hello World");
    }
}
```

**Comment by ZhouJiaZhi** [comment]
@snakefoot 
Thank you very much. Your plan is complete and effective. The log can indeed be output to the Rider console, but I encountered a problem. If I switch the unity scene, the rider will automatically clear the console log. I don’t want him to clear mine log, is there any solution for this？

**Comment by snakefoot** [comment]
> @ZhouJiaZhi If I switch the unity scene, the rider will automatically clear the console log. I don’t want him to clear mine log, is there any solution for this？

I have never used Rider or Unity3D. This place is primary for NLog-specific issues/questions. Maybe try the support-forum for Rider  / Unity3d or try StackOverflow

**Comment by ZhouJiaZhi** [comment]
@snakefoot 
OK, Thank you

**Comment by tussock** [comment]
I am not using Unity, but have the same problem. NLog does now show in the console or Debug Output window of Rider.
I'm using Rider 2023.2.1, running on Mac M2 (it's the arm version of rider).
I've got the following nlog targets:

```
    <target name="debuglog" xsi:type="File" 
                fileName="debuglog${processid}.txt" 
                layout="${processid}|${threadid}|${time}|${level}|${callsite}|${message}" />
    <target name="console" xsi:type="Console" detectConsoleAvailable="false" 
                layout="${processid}|${threadid}|${time}|${level}|${callsite}|${message}" />
    <target name="nw" xsi:type="Network" newLine="true" lineEnding="LF" address="tcp://127.0.0.1:5061"
                layout="${processid}|${threadid}|${time}|${level}|${callsite}|${message}" />
    <!-- The next line is for outputting to the debugger in rider -->
    <target name="debugger" xsi:type="OutputDebugString" layout="${logger}::${message}"/>

```
(The last one I saw in a comment elsewhere, but its only for VS).

Is there something else I can do?
Thx.

**Comment by snakefoot** [comment]
Again this is for questions about NLog. You will probably get better response asking at Rider-Support-Forum or StackOverflow:

The Rider Debug-output window can be found here:

- **Show/hide:** `View` | `Tool Windows` | `Debug` (or shorcut-key `ALT` + `5`)
- **Configure:** `Settings/Preferences` | `Build, Execution, Deployment` | `Debugger`

In the `Debug`-window then you can choose to see:

- `Console`-output - From `Console.WriteLine` - https://github.com/NLog/NLog/wiki/Console-target
- `Debug`-output - From `Debug.WriteLine` - https://github.com/NLog/NLog/wiki/DebugSystem-target

See more: https://www.jetbrains.com/help/rider/Debug_Tool_Window.html
