### ISSUE TITLE
Database Target - Format="Json" for parameter

### ISSUE THREAD

**Issue by unionthugface** [NLog/NLog#4116]
**NLog version**: 4.7.4

**Platform**: .NET Core 3

**Current NLog config**: xml

```xml
<nlog>
  <targets>
    <target name="database">
      <parameter name="@properties" layout="${all-event-properties}" format="json" />
    </target>
  </targets>
</nlog>

```

 - Why do we need it?

Right now `all-event-properties` comes through as

```property1=property1, property2=property2, property3=property3```

It would be convenient for it to come through as

```json
{
  "property1": "property1",
  "property2": "property2",
  "property3": "property3"
}
```

**Comment by snakefoot** [comment]
You can do this:

```xml
    <target name="database" type="database">
        <parameter name="@properties">
            <layout type="JsonLayout" includeAllProperties="true" maxRecursionLimit="1" escapeForwardSlash="false" />
        </parameter>
    </target>

```
See also: https://github.com/nlog/nlog/wiki/JsonLayout

See also: https://stackoverflow.com/questions/63888758/nlog-database-parameter-net-core-all-event-properties-in-json

**Comment by unionthugface** [comment]
Works great.  Thank you!
