### ISSUE TITLE
The background thread logs three times at a time

### ISSUE THREAD

**Issue by luchong0813** [NLog/NLog#4117]
### Code:
```
heartBeatThread = new Thread(new ThreadStart(HeartBeatWork))
                        {
                            IsBackground = true,
                        };
                        heartBeatThread.Start();


private void HeartBeatWork()
        {
            while (true)
            {
                Logger.Info("Hello");
                Thread.Sleep(200);
            }
        }
```
### Nlog.Config:
![20200917171231](https://user-images.githubusercontent.com/46243214/93450898-158ff800-f909-11ea-9dde-bf0f35703d62.png)

### Output:
![20200917170648](https://user-images.githubusercontent.com/46243214/93450899-16288e80-f909-11ea-8cea-af3216f24084.png)

###### I don't know what is the root cause of this problem. I hope to get your help. Thank you

**Comment by snakefoot** [comment]
When making a LogEvent, then it will be matched against ALL rules specified, as explained in the tutorial:

https://github.com/NLog/NLog/wiki/Tutorial#configure-nlog-targets-for-output

Today you have provided the following rules:

```xml
<logger name="*" minLevel="Debug" writeTo="file" /><! -- Matches all LogLevels from Debug and up -->
<logger name="*" minLevel="Info" writeTo="file" />  ! -- Matches all LogLevels from Info and up -->
<logger name="*" minLevel="Error" writeTo="file" />  
<logger name="*" minLevel="Trace" writeTo="file" /> <! -- Matches all LogLevels from Trace and up -->
```

When creating the following LogEvent:

`Logger.Info("Hello");`

Then Info-LogEvent will match 3 rules: `minLevel="Debug" ` + `minLevel="Info" ` + `minLevel="Trace"`.

Maybe you should just do this:

```xml
<logger name="*" minLevel="Trace" writeTo="file" /> <! -- Matches all LogLevels from Trace and up -->
<logger name="*" minLevel="Trace" writeTo="viewer" /> <! -- Matches all LogLevels from Trace and up -->
```

**Comment by snakefoot** [comment]
@ luchong0813 Did it answer your question?

**Comment by snakefoot** [comment]
@luchong0813 Did it answer your question?
