### ISSUE TITLE
Having a wrapper / decorator function on every log message

### ISSUE THREAD

**Issue by pro-panda** [NLog/NLog#4118]
I want every log message to pass through my own custom function before being logged, which takes in a message, and returns a modified version.
I don't want to call the log function from a custom class because that messes with my callerinfo details.

I'm looking for a wrapper option. Is there something like that?(I couldn't find one in the Wiki and Docs)

**Comment by snakefoot** [comment]
Normally one would just create a custom layoutrenderer (And use that in NLog.config):

https://github.com/NLog/NLog/wiki/How-to-write-a-custom-layout-renderer

Alternative you can override the default [MessageFormatter](https://nlog-project.org/documentation/v4.5.0/html/P_NLog_LogEventInfo_MessageFormatter.htm)  when creating a LogEventInfo:

```c#
var logevent = new LogEventInfo(LogLevel.Info, null, null, "Hello {0}", new [] { "world"}, exception);
logevent.MessageFormatter = MyCustomMethod;
logger.Log(logevent);
```

**Comment by pro-panda** [comment]
Thanks. I'm registering this at the start of my code flow,
```
LayoutRenderer.Register("formatted-message", (logevent) => myMethod(logEvent.FormattedMessage));
```
and trying to use `${formatted-message}`, but I get the error `ArgumentException: LayoutRenderer cannot be found: 'formatted-message'`

**Comment by snakefoot** [comment]
Yes registration of custom layout-renderer AFTER having loaded `NLog.config` is not working. Guess you are waiting for #3557.

Either ensure that no NLog `Logger`-objects are created (that automatically loads `NLog.config`), before having performed registration of custom layoutrenderer.

Alternative reload the `NLog.config` after having performed the registration:

```c#
NLog.LogManager.Setup()
   .SetupExtensions(s => s.RegisterLayoutRenderer("myMessage", (logevent) => myMethod(logEvent.FormattedMessage)))
   .LoadConfigurationFromFile(optional: false);
```

**Comment by pro-panda** [comment]
> Either ensure that no NLog Logger-objects are created (that automatically loads NLog.config), before having performed registration of custom layoutrenderer.

Thanks, I had missed this.

For anyone else to refer, adding this before any reference to `NLog.config` allows you to add a wrapper over your message
```
LayoutRenderer.Register("myMessage", (logevent) => myMethod(logEvent.FormattedMessage));
```
