### ISSUE TITLE
“nlog” NLog(4.7.4) Is Logger and LogManager thread safe?

### ISSUE THREAD

**Issue by AmberSQQ** [NLog/NLog#4119]
“nlog” NLog(4.7.4) Is Logger and LogManager thread safe?

**Comment by 304NotModified** [comment]
To quote [my answer on Stackoverflow](https://stackoverflow.com/a/54406989/201303):


> - Creating a logger is thread-safe
> - Writing log messages is thread-safe
> - Usage of the context classes and renderers are (GDC, MDC etc) thread-safe
> - Adding new targets + rules at runtime is thread-safe (When using `LoggingConfiguration.AddRule` + `ReconfigExistingLoggers`)
> - Performing Reload of LoggingConfiguration will cause LogEvents from active loggers to be dropped until reload has completed.
> - Changing values of existing rules and targets at run-time **isn't** thread-safe! 
> 
> You should avoid changing the values of existing items at runtime. Instead one should use the [context renderers](https://nlog-project.org/config/?tab=layout-renderers&search=context) (`${event-properties}`, `${GDC}`, `${MDLC}`, etc.)

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, please let us know!

**Comment by AmberSQQ** [comment]
Thank you !

**Comment by AmberSQQ** [comment]
> I assume your question has been answered, if not, please let us know!

Thank you!
