### ISSUE TITLE
My application crashes on start when AsyncWrapper is used on WindowsXP virtual - box

### ISSUE THREAD

**Issue by waldimen** [NLog/NLog#413]
My application crashes on start when AsyncWrapper is used in nlog.config. 
I have following entry in nlog.config

` <target name="file" xsi:type="AsyncWrapper" queueLimit="5000" overflowAction="Grow">
      <target name="SerialPortFile" xsi:type="file"
          layout="${longdate} ${logger} ${threadid} ${message}"
          fileName="${basedir}/logs/SerialPort/SerialPort.log"
          archiveEvery="Day"
          maxArchiveFiles="5"
          keepFileOpen="true"  />
    </target>`

It is windows forms application, and it crash only when I run it on Windows XP SP2 running inside Virtual Box

The error in EventLog:
`Faulting application someapp.exe, version 1.0.5348.40697, stamp 53f8fb55, faulting module mscorwks.dll, version 2.0.50727.3643, stamp 50405371, debug? 0, fault address 0x002ee87c.`

It is windows forms (.NET 3.5) application, and it crashes only when it is run on Windows XP SP2 running inside Oracle Virtual Box. 

I updated nlog from 2.1 to 3.0 and the problem still exists. Any advice how to fix that ? Can it be a bug in nlog ?

Thanks,

**Comment by 304NotModified** [comment]
@waldimen if this is still an issue, please submit the requested info and re-open this issue.
