### ISSUE TITLE
NLog does not honor the BroadFileSystemAccess capability in UWP applications 

### ISSUE THREAD

**Issue by hooligan495** [NLog/NLog#4136]
I've been doing some research on this and if my UWP Application has declared BroadFileSystemAccess Windows should let me be able to create files outside the sandbox. BUT my application has to use the Windows.STorage APIs to create those files. In my UWP app I turned on BroadfileSystemAccess and tried to set the location in My NLOG config to point to C:\Temp. I get an Unauthorized access exception. And doing some debugging I see that the first place this happens is when NLog calls to File.IO.FileInfo in teh BaseFileAppender. So it seems this class is not using the Windows STorage APIs when used in a UWP application. The File.IO apis are only allowed IN the sandbox of UWP (applicationLocation). The reason for this is that the StorageAPI allows the owner of the computer to override an app's broadfilesystem access policy (which makes sense). The File.IO APIs don't use the Windows policies around this.

In my talks with Microsoft UWP is not going away.  Evolving yes... but I expect some of these core security things they've done will hang around.  I think it would be good to figure out how to get this to work.  If you have any pointers of a good approach I don't mind trying to make it work as I have time.   Having done some googling other UWP application developers have bumped into this limitation as well (but they didn't diagnose it down to the API limitation. 

I think the solution is to allow the basicFileAppender (or a derived variant?) to use the Windows.Storage Apis when you are a UWP application.
 If you have any pointers on a "best way to implement a solution"  I'd be happy to see if we can take a whack at a fix.

I'm not actually sure this is really a bug vs a new feature for NLog so I will beg forgiveness If I opened the wrong kind of ticket 
:)

**NLog version**: 4.7

**Platform**:  UWP  (I'm not sure this is considered a platform but I'm not sure if Silverlight 5 covers this)

**Current NLog config** (xml or C#, if relevant)

```xml
<nlog>
  <variable name="logDirectory" value="c:/Temp"/>
  
  <targets>
    <target name="GeneralLog" xsi:type="File" fileName="${var:logDirectory}/GeneralLog.txt"
            archiveFileName="${var:logDirectory}/Generalog.{#}.txt"
            archiveEvery="Day"
            archiveNumbering="Rolling"
            maxArchiveFiles="30"
            KeepFileOpen="true"
            concurrentWrites="false"
            layout="${longdate}|${level:uppercase=true}|${threadid}|${message}${exception:format=ToString}"/>
<targets>
</nlog>
```

- What is the current result?
UnauthorizedAccessException
- What is the expected result?
That the logfile gets created in the C:/Temp directory
- Are there any workarounds? no
- Is there a version in which it did work? 
no
- Can you help us by writing an unit test?
maybe

**Comment by snakefoot** [comment]
Sounds like you have already peeked at the source-code for the NLog FileTarget. You will probably have noticed that both BaseFileAppender-class and FileTarget-class makes heavy use of `System.Io`-methods.

My advice would be to create a new file-target that only supports dynamic-archive-mode, and without file-rename/file-move-logic.

This new file-appender should have a filesystem-interface that supports the following methods:
- Create Stream (Returned stream-object will close on dispose).
- List current files in folder (Used to recognize next filename):
   - CurrentFile.20201017.log
   - CurrentFile.20201017.1.log
   - CurrentFile.20201017.2.log
- Delete file using filename (Used to removed old files).

Then you can implement this filesystem-interface using both Windows.Storage-API and System.Io-API.

**Comment by snakefoot** [comment]
Closing as inactive.

**Comment by hooligan495** [comment]
Hello,   So I'm starting on this work now(it's now bubbled up to the right priority in our backlog :P).  A few questions:  You mentioned "advice would be to create a new file-target..." then in the next sentence mentioned "this new file-appender"  As I come back to this and am trying to recreate my understanding of what you recommend,  Teh File-System Interface makes sense, but are you recommending I make a new FileTarget type (say ArchiveFileTarget) and a new FileAppender type that can use the proper implememtation of the interface (Based on platform)?

Thanks!

**Comment by snakefoot** [comment]
I'm guessing this is your goal:

- Extend the NLog FileTarget so it can write to files using Windows Storage API

There some hurdles to reach this goal:

- The NLog-nuget-package cannot take dependency on the Windows Storage API, so it will have to a new project.
- The NLog FileTarget is not sealed, but has a very limited number of methods override.

If you want to implement this by extending the NLog FileTarget, then you could add a new virtual like this one:

```c#
virtual Stream OpenFileStream(string filename)
{
}
```

But for this to succeed then you must rewrite the FileAppenderCache, so it becomes a FileStreamCache. Instead of having FileAppenderFactory-method then it should a FileStreamFactory-method. Anyway that is my idea, maybe you will get a better idea with your own investigations. See also https://github.com/NLog/NLog/issues/4244#issuecomment-772325018

**Comment by hooligan495** [comment]
Thank you sir. 
I'm trying to wrap my head around all this and very much appreciate your guidance so far!

**Comment by hooligan495** [comment]
"The NLog-nuget-package cannot take dependency on the Windows Storage API, so it will have to a new project."
Do you know of an example where someone has done something like this (adding a new project) for Nlog?

**Comment by snakefoot** [comment]
There are several [Custom NLog Targets](https://nlog-project.org/config/?tab=targets) that depends on NLog but write to their own favorite location.

But your story is a little different, as you want to extend the existing NLog FileTarget. And it needs some refactoring before being ready for that kind of exercise.

**Comment by hooligan495** [comment]
Thanks!  I just found the Targets too.  The picture is coming clearer for me and again thanks for bearing with me with silly questions

**Comment by snakefoot** [comment]
Yes my suggestion requires a rewrite of the FileAppenders, so they become a simple Stream-object. And the FileAppenderCache becomes a dictionary of key-filename to stream-object (One might want to create a tiny-wrapper around the stream-object for any bonus-metadata).

Again this is just my idea. I have not checked all the dark corners of the FileTarget to see if this abstraction will work. There are a lot places where FileTarget suddenly creates FileInfo-objects or other crazy stuff. But most of this crazy stuff is related to archive logic. So maybe have something like this:

- FileStreamTarget (with fileappender-cache) -> FileTarget (with archive magic)

And then see if one could invent a IFileSystem-interface to support file-cleanup and other archive-stuff.

**Comment by hooligan495** [comment]
I guess I don't pick the easy tasks for my first foray into NLOG :)

**Comment by snakefoot** [comment]
Yes it might be simpler to create a simple target that just can handle a single filename. Something like this:

```c#
[Target("UwpFile")]
public UwpFileTarget : TargetWithLayout
{
       public Layout FileName { get; set; }

       public Encoding Encoding { get; set; } = System.Text.Encoding.UTF8;

       private string _currentFileName:
       private Stream _currentFileStream;

        protected override void Write(LogEventInfo logEvent) 
        { 
            string fileContent = RenderLogEvent(this.Layout, logEvent);
            string fileName = RenderLogEvent(this.FileName , logEvent);

            var fileStream = GetFileStream(fileName);
            fileStream.Write(Encoding.GetBytes(fileContent));
            fileStream.Write(Encoding.GetBytes(Environment.NewLine));
            fileStream.Flush();
        }

        protected override void CloseTarget()
        {
             _currentFileName = null;
             _currentFileStream?.Dispose();
        }

        Stream GetFileStream(string fileName)
        {
             var fileStream = _currentFileStream;
             if (_currentFileName != _fileName)
             {
                _currentFileStream?.Dispose();
                fileStream  = _currentFileStream = null;   // TODO Create FileStream
             }
             return fileStream;
        }
}
```

Then you can play around with NLog Target-Logic and see what is absolute minimum for UWP-file-writing to work.

**Comment by hooligan495** [comment]
Thanks!  
I'm moving forward (albeit slowly).   As I look at this... I want to be able to do the rotating archive files.  Does that mean I have to dive deep into the Appender implementations?

**Comment by snakefoot** [comment]
Believe the archive logic happens here:

https://github.com/NLog/NLog/blob/90c46772d2a5ddcd74bbdbec9642688df22735f7/src/NLog/Targets/FileTarget.cs#L1695

That calls into here:

https://github.com/NLog/NLog/blob/90c46772d2a5ddcd74bbdbec9642688df22735f7/src/NLog/Targets/FileTarget.cs#L1834

That checks the `_fileAppenderCache.`:

https://github.com/NLog/NLog/blob/90c46772d2a5ddcd74bbdbec9642688df22735f7/src/NLog/Targets/FileTarget.cs#L1993
https://github.com/NLog/NLog/blob/90c46772d2a5ddcd74bbdbec9642688df22735f7/src/NLog/Targets/FileTarget.cs#L1885

**Comment by hooligan495** [comment]
Thanks!  I've a slightly different question now :(   I've written a UwpTarget and what I'm trying to do is get to unit testing it.  I'm not what you'd call expert level at creating nuget packages..   I've creat3ed the UwpTarget in a separate proj.   It turns out that in order to actually run the unit tests correctly... I need to launch from a UWP application.. so I've created that as a separate Unit test project... but I'm having all hell trying to get the framework support to match up... 

my first attempt here got me to run a unit test.  But it fails (expectedly) because we are not running in a UWP app that has the BroadfileSystemAccess flag tweaked.  So when I try to run my target unit test. it fails to create the file.    (which is not surprising)

https://github.com/hooligan495/NLog/compare/dev...hooligan495:UwpFileTarget?expand=1


This leads me on a merry path now where I am trying to add an actual UWP application into the unit tests (per what I've read and experienced in the past).  But my attempt to define the UwpFile target project is not being easily referenced from the App based test project (you will see that I have 2 test projects Uwp.AppTests and UwpTests).  When I do get the AppTest to reference the NLog.UWP project I created I can't make it refer to the NLog or NLogUnit tests.   

https://github.com/hooligan495/NLog/compare/UwpFileTarget...hooligan495:UnitTestAttempt?expand=1


If you have any thoughts or ideas I'd be forever grateful.  In the meantime I'll keep banging away. 
Some googling has led me to an SDK extension but i'm not sure this is the right approach tbh.

**Comment by snakefoot** [comment]
I guess you are aware that your changes cannot be committed into the NLog-repository.

Right now there is an army of nuget-packages in the NLog-project, but they will be moved into their own repositories when NLog 5.0 is released.

I'm not an expert on UWP-Testing. I would guess that one did testing against interface-mocks and never really wrote to any real file. The current unittests for NLog FileTarget does not follow "modern" standards, and should not be used an example to follow.

**Comment by hooligan495** [comment]
that's fine if I'd have to be separate.  But what's melting my mind right now is ... how should I be thinking about this.  If I create a separate dll/library, and it needs to use the Windows.STorage APIs (Which is a WinRT API)... how does one think about it?  I have an existing application (UWP) that references NLog today... I'm guessing that it references it as a .net standard 2.0 library.  Does that mean I create this new "target" project as it's own superset of NLog?  (I'm not sure if the other example targets are plugins?  or are they a complete release in their own right (which depend on Nlog?). or would I have to take a different direction (sorry for so many questions and again thanks for all your help so far).

**Comment by snakefoot** [comment]
NLog is generic support both NetStandard1.3 and NetStandard2.0, and should work fine with any UWP-applications.

If you create new project that targets Uap10 (or some specific UWP-Runtime), then it should have no issue to depend on the generic NLog-package.

**Comment by hooligan495** [comment]
Not sure I'm asking this the correct way but.. I have a dll I've created (it's a UWP DLL ) I put my UwpFileTarget into it...and this project has a reference to the NLog nuget package... How do I make it so that the LogManager would know how to map a config type of "UwpFile" to the UwpFileTarget class and have it get instantiated at initialization time?

**Comment by snakefoot** [comment]
Yes NLog has several ways to [register your custom component](https://github.com/NLog/NLog/wiki/Register-your-custom-component).

I guess you can do this, where you change the alias "File" to point at your new custom target:

```c#
NLog.LogManager.Setup().SetupExtensions(s =>
   s.RegisterTarget<UwpFileTarget>("File")
);
```

**Comment by hooligan495** [comment]
Thanks!  Right after I posted I stumbled upon the extensions... in a sample of "elasticsearch"   Glad that you can confirm.. and wow thanks for the quick turnaround

**Comment by snakefoot** [comment]
You are very welcome to post a link to your repository, that contains your final UwpFileTarget. 

But I think it will be best if it is an empty repository and not a fork of the NLog-repository.

Please update your [UwpFileTarget](https://github.com/hooligan495/NLog/blob/UwpFileTarget/src/NLog.Uwp/Target/UwpFileTarget.cs) to include the latest changes from my [pseudo code example](https://github.com/NLog/NLog/issues/4136#issuecomment-791542408) (Ex. assign `_currentFileName` in `GetFileStream`)

**Comment by hooligan495** [comment]
yep I ended up creatinga clean repository... I'll create and push what I have.. I still have a lot of work I'll be doing to complete things (And simplify) but I have the basic logging working in unit tests at least.

**Comment by hooligan495** [comment]
https://github.com/hooligan495/Nlog.UwpTarget

That's the repo.  All comments/suggestions/guidance/criticisms welcome

**Comment by snakefoot** [comment]
@hooligan495 Great start. Please include the latest changes from my [updated pseudo code example](https://github.com/NLog/NLog/issues/4136#issuecomment-791542408) (Ex. assign `_currentFileName` in `GetFileStream`, and retry file-open on error)

**Comment by hooligan495** [comment]
Will do that right now thanks!

**Comment by hooligan495** [comment]
I have basic file writing working.  I'm now starting to look into the archiving.  In adding some of the archiving properties to my class I am looking at the NLog implementation and it is using things that are internal to Nlog.  E.g. FilePathLayout ... in this approach that type isn't available to me unless I copy it out of Nlog (ick?) or do something else (seems annoying not to be able to leverage some of the best practice already in Nlog) like write my own version.  I am seeing why you were saying earlier that this implementation is a bit 'special' ...

**Comment by snakefoot** [comment]
Yes the NLog FileTarget is a huge beast, and it requires a careful hand to open it up, and make it easier to extend.

Not sure what parts of the archive-functionality you are looking for. But I would probably focus on never moving files, so the "rolling" of files happens through the FileName-Layout. Ex. `App-${shortdate}.log`

**Comment by hooligan495** [comment]
`           
            archiveFileName="${var:logDirectory}/Generalog.{#}.txt"
            archiveEvery="Day"
            archiveNumbering="Rolling"
            maxArchiveFiles="30"
`

That's what I was looking to do.     I agree .. I don't have the knowledge of this beast to be the careful hand.  ugh ... I've been looking through the code just to see what's happening.

**Comment by hooligan495** [comment]
oh.. are you saying to simplify?   and find the ${shortdate} in the actual file name.  interesting... so my check on log event would be to just see if the day changed and if so open a new file?    Thanks!

**Comment by snakefoot** [comment]
It will happen automatically without needing to change anything.


Sent from my Sony Xperia


---- Jay McGaffigan wrote ----


oh.. are you saying to simplify? and find the ${shortdate} in the actual file name. interesting... so my check on log event would be to just see if the day changed and if so open a new file? Thanks!

**Comment by hooligan495** [comment]
Sweetness!!! you've thought of everything!  Thanks

**Comment by snakefoot** [comment]
If you want to implement `maxArchiveFiles="30"` then I suggest something simple like adding a new property `public Layout CleanupArchiveFileNames`. Where the user can specify a standard file-wildcard. Ex. `App-*.log`.

Then as part of creating/opening new file-stream, then if `maxArchiveFiles > 0` then get directory listing based on `var fileListWildcard = RenderLogEvent(CleanupArchiveFileNames, logEvent)`.
