### ISSUE TITLE
Counter layout renderer

### ISSUE THREAD

**Issue by ypelissier** [NLog/NLog#4139]
Hello,
I have an application running h24 and I want to have some log shortable by date and I would like to add a counter because a lot of time, I had the same date (format HH:mm:ss,fffffff).
My question is what's happen after the counter was set to Int.Max ?

Thanks a lot for your answer.

**Comment by snakefoot** [comment]
Believe it will start using negative numbers. I guess you can quickly test this by doing this:

`${counter:Increment=1000000000}`

Then by logging a few times it should show what happens. You are welcome to create a pull-request to change from `int` to `long`. See also https://github.com/NLog/NLog/wiki/Counter-layout-renderer

**Comment by snakefoot** [comment]
Closing as inactive.
