### ISSUE TITLE
AutoFlush property on FileTarget not always working

### ISSUE THREAD

**Issue by richol** [NLog/NLog#414]
AutoFlush does not work for all configuration options on FileTarget. Depending on which BaseFileAppender the configuration makes the FileTarget use, data written may not be flushed even if the AutoFlush property is set to true.

**Comment by 304NotModified** [comment]
related, but not the smae #294

**Comment by Xharze** [comment]
This was fixed in the 3.2 release, but a merge error made it necessary to fix in 4.0. Also the reason this issue weren't closed for version 3.2 were a missing reference between PR and issue. The PR fixing this is #414 and #707
