### ISSUE TITLE
Application crash in FileStream Finalize on program end

### ISSUE THREAD

**Issue by zmcx16** [NLog/NLog#4140]
Hi, 

I found if I use async and disable autoFlush in NLog config, the application sometime will crash on the program end (the application will crash on the last line: return exit code), this application doesn't read / write any file in code logic exception NLog. 

I am not actually sure the application crash is windows bug or NLog, do you have any idea on this problem? thanks. 

**NLog version**: 4.6.7

**Platform**: .Net 4.5 (.Net framework 4.6.1)

**Current NLog config** (xml or C#, if relevant)

```xml
<nlog>
  <!-- 
  See http://nlog-project.org/wiki/Configuration_file 
  for information on customizing logging rules and outputs.
   -->
  <targets async='true'>
	<!-- add your targets here -->
	<target name='file' type='File'
		  layout='${longdate} ${level:uppercase=true} [${threadid}] ${logger} - ${message} ${onexception:${newline}${exception:format=tostring}}'
		  fileName='debug.log'
		  archiveFileName='Logs/debug.log.{#}.zip'
		  archiveNumbering='Date'
		  archiveDateFormat ='yyyy_MM_dd_HH_mm_ss'
		  archiveAboveSize='100000000'
		  enableArchiveFileCompression='true'
		  maxArchiveFiles='50'
		  concurrentWrites='false'
		  keepFileOpen='true'
		  openFileCacheTimeout='30'
		  autoFlush='false'
		  openFileFlushTimeout='1'
		  encoding='UTF-8' />
  </targets>

  <rules>
	<!-- add your logging rules here -->
	<logger name='*' minlevel='Debug' writeTo='file' />
  </rules>
</nlog>

```

- What is the current result?
Sometime the application will crash on the program end, the test application can run task completed and write log before return exit code, but the program can' terminate normally and cause crash, the crash function is related on System.IO.FileStream, but this application doesn't read / write any file in code logic exception NLog.

- What is the expected result?
No crash on the program end.

- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)? 
yes

- Please post full exception details (message, stacktrace, inner exceptions)
the windows event log as follow:

.NET routime:
Application: XXX.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.IOException
   at System.IO.FileStream.VerifyOSHandlePosition()
   at System.IO.FileStream.WriteCore(Byte[], Int32, Int32)
   at System.IO.FileStream.FlushWrite(Boolean)
   at System.IO.FileStream.Dispose(Boolean)
   at System.IO.FileStream.Finalize()

Application Error:
Faulting application name: XXX.exe, version: 3.5.0.3664, time stamp: 0x5f8d0599
Faulting module name: KERNELBASE.dll, version: 10.0.14393.3383, time stamp: 0x5ddcb9ff
Exception code: 0xe0434352
Fault offset: 0x000dc232
Faulting process id: 0xd14
Faulting application start time: 0x01d6a6da98fa483c
Faulting application path: C:\Program Files (x86)\OOO\XXX.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: f4a25c63-3be2-4072-871c-44e593adf521
Faulting package full name: 
Faulting package-relative application ID: 

- Are there any workarounds? 
yes

I turn off async and buffer config, the application can work fine, but the performance is bad, the work config as follow:

<nlog>
  
  <targets>
	
	<target name='file' type='File'
		  layout='${longdate} ${level:uppercase=true} [${threadid}] ${logger} - ${message} ${onexception:${newline}${exception:format=tostring}}'
		  fileName='debug.log'
		  archiveFileName='Logs/debug.log.{#}.zip'
		  archiveNumbering='Date'
		  archiveDateFormat ='yyyy_MM_dd_HH_mm_ss'
		  archiveAboveSize='100000000'
		  enableArchiveFileCompression='true'
		  maxArchiveFiles='50'
		  concurrentWrites='false'
		  keepFileOpen='false'
		  encoding='UTF-8' />
  </targets>

  <rules>
	
	<logger name='*' minlevel='Debug' writeTo='file' />
  </rules>

- Is there a version in which it did work? 
I can't found an reproduce steps on this case, it is rarely happen and only occur on some machine.

- Can you help us by writing an unit test?
yes, but I can't reproduce the crash problem on my machine. This problem only occur on some machine

**Comment by snakefoot** [comment]
Do you call this method before application-exit:

`NLog.LogManager.Shutdown();`

See also: https://github.com/NLog/NLog/wiki/Tutorial#5-remember-to-flush

Maybe try and enable the [NLog InternalLogger ](https://github.com/NLog/NLog/wiki/Internal-Logging)for your application, and capture the output from a crashed application for investigation.

**Comment by zmcx16** [comment]
Hi snakefoot,

I didn't add NLog.LogManager.Shutdown() before application exit, and I found this problem can reproduce on Azure VM, the Azure VM disk write speed is slower than physical disk, I think the problem is like you mention, the .NET applications shutdown is limited causes NLog can't finish flush work.

I will add NLog.LogManager.Shutdown() before application exit and keep monitoring it. I will update if I have any findings. Thank you.

**Comment by snakefoot** [comment]
Closing the issue as resolved, until proven otherwise.
