### ISSUE TITLE
prevent aspnet-request-post-body to log some properties

### ISSUE THREAD

**Issue by heizel184** [NLog/NLog#4145]
hey everyone 
I am using {aspnet-request-post-body} attribute in nlog.config to log request body. I want to make annotation in c# like jsonignore so that Nlog attribute {aspnet-request-post-body} does not include those properties in log file?
any solution for that I have search a lot but could not find the best one that meets my requirements

**Comment by snakefoot** [comment]
Can you show your current `NLog.config` ?

Can you show the output generated by NLog ?

Can you show the expected output ?

Have you tried to do simple regex-replacing ? https://github.com/NLog/NLog/wiki/Replace-Layout-Renderer

**Comment by HinaSheikh** [comment]
Hey sorry for being late 
Here is the Nlog.config file

  <extensions>
    <add assembly="NLog.Web.AspNetCore"/>
  </extensions>
  <targets>
    <target xsi:type="File" name="logs" fileName="D:/Api_${longdate}.log"
            layout="==> 
                        ${when:when=('${aspnet-request-method}' != 'GET')   > 0 :inner=${newline} 
                    Request-Body\: ${aspnet-request-posted-body}}
                        Logger name: ${logger} " />
  </targets>

Output of File :

==>                        
Request-Body: {
 User: "abc",
Passoword : "123",
Key : "fggh12"
}  
Logger name : User

and the output that is expected is 
==>                        
Request-Body: {
 User: "abc",
Passoword : "****",
Key : "***"
}  
Logger name : User



Actually there can be multiple sensitive fields in json request so,if i  will use  Replace-Layout-Renderer for each sensitive info then nlog.cofig size will become large also. Is there is any other way other than Replace-Layout-Renderer.Can i change the data of  ${aspnet-request-posted-body} before logging into the file.

**Comment by snakefoot** [comment]
> Is there is any other way other than Replace-Layout-Renderer?

Not that I know of.

> Can i change the data of `${aspnet-request-posted-body}` before logging into the file?

Transformation of the output is usually handled by implementing `WrapperLayoutRendererBase`. 

But you can always implement your own custom layoutrenderer, that has a property `public Layout Inner { get; set; }`:

```c#
[LayoutRenderer("hello-world")]
public class HelloWorldLayoutRenderer : LayoutRenderer
{
    public Layout Inner { get; set; }

    protected override void Append(StringBuilder builder, LogEventInfo logEvent)
    {
        var result = Inner?.Render(logEvent);
        if (!string.IsNullOrEmpty(result))
        {
            // Perform any transformations
            builder.Append(result);
        }
    }
}
```

Then you can use it like this: `${hello-world:inner=${aspnet-request-post-body}}`

See also: https://github.com/NLog/NLog/wiki/How-to-write-a-custom-layout-renderer#example

**Comment by HinaSheikh** [comment]
so @snakefoot  I can mask password in append functin of this class ? can you please tell how can I acces my password in it ?

**Comment by snakefoot** [comment]
> can you please tell how can I acces my password in it ?

I'm sorry, but you have to carry the torch from here yourself. Coding-monkeys for free are hard to come by.

**Comment by heizel184** [comment]
> > Is there is any other way other than Replace-Layout-Renderer?
> 
> Not that I know of.
> 
> > Can i change the data of `${aspnet-request-posted-body}` before logging into the file?
> 
> Transformation of the output is usually handled by implementing `WrapperLayoutRendererBase`.
> 
> But you can always implement your own custom layoutrenderer, that has a property `public Layout Inner { get; set; }`:
> 
> ```cs
> [LayoutRenderer("hello-world")]
> public class HelloWorldLayoutRenderer : LayoutRenderer
> {
>     public Layout Inner { get; set; }
> 
>     protected override void Append(StringBuilder builder, LogEventInfo logEvent)
>     {
>         var result = Inner?.Render(logEvent);
>         if (!string.IsNullOrEmpty(result))
>         {
>             // Perform any transformations
>             builder.Append(result);
>         }
>     }
> }
> ```
> 
> Then you can use it like this: `${hello-world:inner=${aspnet-request-post-body}}`
> 
> See also: https://github.com/NLog/NLog/wiki/How-to-write-a-custom-layout-renderer#example

I am using ${hello-world:inner=${aspnet-request-post-body}}in nlog.config but this line does nothing.I added a breakpoint in hello world class but control not goes there .Do i need to add something in startup file before using this custom renderer.
I have added this line on my startup file 
ConfigurationItemFactory.Default.LayoutRenderers
                            .RegisterDefinition("HelloWorldLayoutRenderer", typeof(HelloWorldLayoutRenderer));

**Comment by heizel184** [comment]
Hey everyone I have implemented the above solution but 
inner.Render(logEvent); is returning an empty string in all cases .Curently when I debug inner contain '${aspnet-request-post-body}' as a string not the json data of request body so I am unable to get the request body value. 
anybody know what's the reason of this behaviour

**Comment by snakefoot** [comment]
@heizel184 Can you show the contents of your entire NLog.config together with how you initialize NLog with registration of your custom layout-renderer?

Have you checked the output of the [NLog InternalLogger](https://github.com/NLog/NLog/wiki/Internal-Logging) ?

**Comment by heizel184** [comment]
Here is the Nlog.config
 <extensions>
    <add assembly="NLog.Web.AspNetCore"/>
  </extensions>
  <targets>
    <target xsi:type="File" name="logs" fileName="D:/Api_${longdate}.log"
            layout="==> 
                        ${when:when=('${aspnet-request-method}' != 'GET')   > 0 :inner=${newline} 
                    Request-Body\: ${aspnet-request-posted-body}}
                        Logger name: ${logger} " />
  </targets>

Custom Layout 
 [LayoutRenderer("TransformLayoutRenderer")]
    public class TransformLayoutRenderer : LayoutRenderer
    {
        public Layout Inner { get; set; }

        protected override void Append(StringBuilder builder, LogEventInfo logEvent)
        {
            var result = Inner?.Render(logEvent);
            if (!string.IsNullOrEmpty(result))
            {
                // Perform any transformations
                builder.Append(result);
            }
        }

    }

Registeration in app_start 
 ConfigurationItemFactory.Default.LayoutRenderers
                          .RegisterDefinition("TransformLayoutRenderer", typeof(TransformLayoutRenderer));

after some search I have found

**Comment by snakefoot** [comment]
Cannot see `${TransformLayoutRenderer:Inner=${aspnet-request-posted-body}}` in your NLog.config

**Comment by heizel184** [comment]
> Cannot see `${TransformLayoutRenderer:Inner=${aspnet-request-posted-body}}` in your NLog.config
> 
> Have you checked the output of the [NLog InternalLogger](https://github.com/NLog/NLog/wiki/Internal-Logging) ?

sorry that was copy mistake 
yes i have checked internet-log file now and this was the error .

 Error Error parsing layout aspnet-request-post-body will be ignored. Exception: System.ArgumentException: LayoutRenderer cannot be found: 'aspnet-request-post-body'. Is NLog.Web not included?

**Comment by snakefoot** [comment]
When reading the docs then it should be `posted-body`. You are doing this:

- ${Transform:inner=${aspnet-request-post-body}

It should be this:

- ${TransformLayoutRenderer:Inner=${aspnet-request-posted-body}}

See also: https://github.com/NLog/NLog/wiki/AspNet-Request-posted-body-layout-renderer

**Comment by heizel184** [comment]
Thanks @snakefoot it solved now

**Comment by snakefoot** [comment]
Thanks to @bakgerman now NLog.Web.AspNetCore v5.1 re-introduces [${aspnet-request-posted-body}](https://github.com/NLog/NLog/wiki/AspNet-Request-posted-body-layout-renderer) with help from middleware:
```c#
app.UseMiddleware<NLog.Web.NLogRequestPostedBodyMiddleware>();
```
It is no longer necessary to explicit call `context.Request.EnableBuffering();` as it is handled by the middleware.
