### ISSUE TITLE
File archive to Network Drive fails with DirectoryNotFoundException

### ISSUE THREAD

**Issue by mbsijblackwell** [NLog/NLog#4146]
Nlog archiving won't write to a Network drive.  Works fine logging back to the c drive.  Z drive here is mapped to a network drive.  I have also tried the UNC path.

```xml
  <variable name="myvar" value="myvalue"/>
  <variable name="company" value="${event-properties:item=companyid}" /> 
  <variable name="process" value="images\" />
  <variable name="logpath" value="Z:\Logs\mrssend\archive" />

    <target xsi:type="File" name="logfileinfo" 
            fileName="${basedir}\logs\mrssend\${company}\nlog-info.log" 
            archiveFileName="${logpath}\${company}\${process}\nlog-info-${shortdate}.log"
            layout="${date} Content: ${message}"
            maxArchiveFiles="30" 
            archiveEvery="day"/>
```

```
2020-10-22 20:33:37.7021 Warn FileTarget(Name=logfileinfo): Failed to archive file 'c:\Program Files\RePros\MRSSendServiceImages\logs\mrssend\21702\nlog-info.log'. Exception: System.IO.DirectoryNotFoundException: Could not find a part of the path 'Z:\Logs\mrssend\archive\21702\images'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at NLog.Targets.FileTarget.ArchiveFile(String fileName, String archiveFileName)
   at NLog.Targets.FileTarget.DoAutoArchive(String fileName, LogEventInfo eventInfo, DateTime previousLogEventTimestamp, Boolean initializedNewFile)
   at NLog.Targets.FileTarget.ArchiveFileAfterCloseFileAppender(String archiveFile, LogEventInfo ev, Int32 upcomingWriteSize, DateTime previousLogEventTimestamp)
```

**Comment by mbsijblackwell** [comment]
My variable settings got dropped in the post.

  <variable name="myvar" value="myvalue"/>
  <variable name="company" value="${event-properties:item=companyid}" /> 
  <variable name="process" value="images\" />
  <variable name="logpath" value="C:\Logs\mrssend\archive" />

**Comment by mbsijblackwell** [comment]
<variable name="myvar" value="myvalue"/>
  
<variable name="company" value="${event-properties:item=companyid}" /> 
  
<variable name="process" value="images\" />
  
<variable name="logpath" value="Z:\Logs\mrssend\archive" />

**Comment by mbsijblackwell** [comment]
For some reason I can't paste in the variable settings

**Comment by mbsijblackwell** [comment]
"  <variable name="myvar" value="myvalue"/>
  <variable name="company" value="${event-properties:item=companyid}" /> 
  <variable name="process" value="images\" />
  <variable name="logpath" value="C:\Logs\mrssend\archive" />"

**Comment by mbsijblackwell** [comment]
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="false"
      internalLogLevel="Info" internalLogFile="${basedir}\logs\mrssend\nlog-internal.log">

  
  <variable name="myvar" value="myvalue"/>
  <variable name="company" value="${event-properties:item=companyid}" /> 
  <variable name="process" value="images\" />
  <variable name="logpath" value="C:\Logs\mrssend\archive" />

**Comment by mbsijblackwell** [comment]
Variables:

<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="false"
      internalLogLevel="Info" internalLogFile="${basedir}\logs\mrssend\nlog-internal.log">

  
  <variable name="myvar" value="myvalue"/>
  <variable name="company" value="${event-properties:item=companyid}" /> 
  <variable name="process" value="images\" />
  <variable name="logpath" value="C:\Logs\mrssend\archive" />

**Comment by mbsijblackwell** [comment]
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="false"
      internalLogLevel="Info" internalLogFile="${basedir}\logs\mrssend\nlog-internal.log">

  
  <variable name="myvar" value="myvalue"/>
  <variable name="company" value="${event-properties:item=companyid}" /> 
  <variable name="process" value="images\" />
  <variable name="logpath" value="C:\Logs\mrssend\archive" />
 
  
  <targets>

    

    

    
    
    
    

    <target xsi:type="File" name="logfileinfo" 
            fileName="${basedir}\logs\mrssend\${company}\nlog-info.log" 
            archiveFileName="${logpath}\${company}\${process}\nlog-info-${shortdate}.log"
            layout="${date} Content: ${message}"
            maxArchiveFiles="30" 
            archiveEvery="Minute"/>
    <target xsi:type="File" name="logfiletrace" 
            fileName="${basedir}\logs\mrssend\${company}\nlog-trace.log" 
            archiveFileName="${logpath}\${company}\${process}\nlog-trace-${shortdate}.log"
            layout="${date} Content: ${message}"
            maxArchiveFiles="30"
            archiveEvery="Minute"/>
    <target xsi:type="File" name="logfilefatal" 
            fileName="${basedir}\logs\mrssend\${company}\nlog-fatal.log" 
            archiveFileName="${logpath}\${company}\${process}\nlog-fatal-${shortdate}.log"
            layout="${date} Content: ${message}"
            maxArchiveFiles="30"
            archiveEvery="Minute"/>

    <target xsi:type="EventLog"
            name="eventLog"
            machineName="."
            source="MRS Send Service2"
            log="MRSSend2" 
            layout="${message}${newline}${exception:format=ToString}"/>

	
    
	

    <target xsi:type="EventLog"
            name="eventLog"
            machineName="."
            source="MRS Send Service2"
            log="MRSSend2"
            layout="${message}${newline}${exception:format=ToString}"/>
    
  </targets>

  <rules>
    

    

    
    

    <logger name="*" level="Info" writeTo="logfileinfo" />
    <logger name="*" level="Trace" writeTo="logfiletrace" />
    <logger name="*" level="Fatal" writeTo="logfilefatal" />
    <logger name="*" minlevel="Fatal" writeTo="eventLog" />
    
  </rules>
</nlog>

**Comment by snakefoot** [comment]
```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="false"
      internalLogLevel="Info" internalLogFile="${basedir}\logs\mrssend\nlog-internal.log">

  <!-- optional, add some variables
  https://github.com/nlog/NLog/wiki/Configuration-file#variables
  -->
  <variable name="myvar" value="myvalue"/>
  <variable name="company" value="${event-properties:item=companyid}" /> 
  <variable name="process" value="images\" />
  <variable name="logpath" value="C:\Logs\mrssend\archive" />
 
  <!--
  See https://github.com/nlog/nlog/wiki/Configuration-file
  for information on customizing logging rules and outputs.
   -->
  <targets>

    <!--
    add your targets here
    See https://github.com/nlog/NLog/wiki/Targets for possible targets.
    See https://github.com/nlog/NLog/wiki/Layout-Renderers for the possible layout renderers.
    -->

    <!--
    Write events to a file with the date in the filename.
    <target xsi:type="File" name="f" fileName="${basedir}/logs/${shortdate}.log"
            layout="${longdate} ${uppercase:${level}} ${message}" />
    -->

    <!-- local file target -->
    <!--<target name="fileTarget"
              xsi:type="File"
              fileName="D:\temp\example.log"
              layout="
              ${level} (${longdate}) ${newline}
              ${newline}
              Call Site: ${callsite}${newline}
              Exception Type: ${exception:format=Type}${newline}
              Exception Message: ${exception:format=Message}${newline}
              Stack Trace: ${exception:format=StackTrace}${newline}
              Additional Info: ${message}${newline}" />-->
    <!--<target name="fileTarget" xsi:type="File"
            layout="${longdate} ${logger} ${message}${exception:format=ToString}"
            fileName="d:/temp/logfile.txt"
            keepFileOpen="true"
            encoding="utf-8" />-->
    <!--fileName="${basedir}/logs/logfile.txt"-->

    <target xsi:type="File" name="logfileinfo" 
            fileName="${basedir}\logs\mrssend\${company}\nlog-info.log" 
            archiveFileName="${logpath}\${company}\${process}\nlog-info-${shortdate}.log"
            layout="${date} Content: ${message}"
            maxArchiveFiles="30" 
            archiveEvery="Minute"/>
    <target xsi:type="File" name="logfiletrace" 
            fileName="${basedir}\logs\mrssend\${company}\nlog-trace.log" 
            archiveFileName="${logpath}\${company}\${process}\nlog-trace-${shortdate}.log"
            layout="${date} Content: ${message}"
            maxArchiveFiles="30"
            archiveEvery="Minute"/>
    <target xsi:type="File" name="logfilefatal" 
            fileName="${basedir}\logs\mrssend\${company}\nlog-fatal.log" 
            archiveFileName="${logpath}\${company}\${process}\nlog-fatal-${shortdate}.log"
            layout="${date} Content: ${message}"
            maxArchiveFiles="30"
            archiveEvery="Minute"/>

    <target xsi:type="EventLog"
            name="eventLog"
            machineName="."
            source="MRS Send Service2"
            log="MRSSend2" 
            layout="${message}${newline}${exception:format=ToString}"/>

	<!-- <target xsi:type="File" name="logfileinfo" fileName="f:\logs\mrssend\nlog-${shortdate}_info.log" /> -->
    <!-- <target xsi:type="File" name="logfile" fileName="f:\logs\mrssend\nlog-${shortdate}.log" /> -->
	<!-- <target xsi:type="File" name="logfilefatal" fileName="f:\logs\mrssend\nlog-${shortdate}_fatal.log" /> -->

    <target xsi:type="EventLog"
            name="eventLog"
            machineName="."
            source="MRS Send Service2"
            log="MRSSend2"
            layout="${message}${newline}${exception:format=ToString}"/>
    
  </targets>

  <rules>
    <!-- add your logging rules here -->

    <!--
    Write all events with minimal level of Debug (So Debug, Info, Warn, Error and Fatal, but not Trace)  to "f"
    <logger name="*" minlevel="Debug" writeTo="f" />
    -->

    <!-- local file logger -->
    <!--<logger level="Info" name="fileLogger" writeTo="fileTarget"/>-->

    <logger name="*" level="Info" writeTo="logfileinfo" />
    <logger name="*" level="Trace" writeTo="logfiletrace" />
    <logger name="*" level="Fatal" writeTo="logfilefatal" />
    <logger name="*" minlevel="Fatal" writeTo="eventLog" />
    
  </rules>
</nlog>
```

**Comment by mbsijblackwell** [comment]
I have not posted here before, so not sure how you dropped that.  The C drive setting in this config works, it is when I change the logpath variable to the Z drive that it doesn't work.

**Comment by mbsijblackwell** [comment]
Ah triple quotes.

**Comment by mbsijblackwell** [comment]
''' <variable name="myvar" value="myvalue"/>
  <variable name="company" value="${event-properties:item=companyid}" /> 
  <variable name="process" value="images\" />
  <variable name="logpath" value="C:\Logs\mrssend\archive" />'''

**Comment by mbsijblackwell** [comment]
""" <variable name="myvar" value="myvalue"/>
  <variable name="company" value="${event-properties:item=companyid}" /> 
  <variable name="process" value="images\" />
  <variable name="logpath" value="C:\Logs\mrssend\archive" />"""

**Comment by snakefoot** [comment]
You need to use the right quotes. Again just use the `<>` in the editor, after having selected the blob of xml.

**Comment by mbsijblackwell** [comment]
` <variable name="myvar" value="myvalue"/>
  <variable name="company" value="${event-properties:item=companyid}" /> 
  <variable name="process" value="images\" />
  <variable name="logpath" value="C:\Logs\mrssend\archive" />`

**Comment by mbsijblackwell** [comment]
Finally got it thanks

**Comment by snakefoot** [comment]
You can edit  your own post with variables (that I have just updated) to see how to do the triple-quote-thingy.

**Comment by mbsijblackwell** [comment]
`  <variable name="myvar" value="myvalue"/>
  <variable name="company" value="${event-properties:item=companyid}" /> 
  <variable name="process" value="images\" />
  <variable name="logpath" value="C:\Logs\mrssend\archive" /> `

**Comment by mbsijblackwell** [comment]
```  <variable name="myvar" value="myvalue"/>
  <variable name="company" value="${event-properties:item=companyid}" /> 
  <variable name="process" value="images\" />
  <variable name="logpath" value="C:\Logs\mrssend\archive" /> ```

**Comment by mbsijblackwell** [comment]
```
  <variable name="myvar" value="myvalue"/>
  <variable name="company" value="${event-properties:item=companyid}" /> 
  <variable name="process" value="images\" />
  <variable name="logpath" value="C:\Logs\mrssend\archive" />
```

**Comment by mbsijblackwell** [comment]
Got it

**Comment by mbsijblackwell** [comment]
Now I just need some help with my issue, now that I know how to post to Github

**Comment by mbsijblackwell** [comment]
Thank you @snakefoot

**Comment by snakefoot** [comment]
I actually think it is a bug, or maybe just a missing feature.

NLog FileTarget automatically creates folders when writing to file, but it seems this logic is not available when doing file-archive, where moving file to other folder.

**Comment by mbsijblackwell** [comment]
@snakefoot  It works fine to the C drive though......

**Comment by mbsijblackwell** [comment]
I have services running on 5 servers.  Each have their own logging for the day.  Then trying to consolidate to a network drive for archive.

**Comment by snakefoot** [comment]
@mbsijblackwell Does it work when archive to local-folder that doesn't exist ? Ex:
```xml
<variable name="logpath" value="C:\Logs\mrssend\archive\hello\world\" />
```

**Comment by mbsijblackwell** [comment]
Yes it did.  It created the base folder on it's own and then for each company id.  I have over 4000 companies that it created folders for as well.

**Comment by mbsijblackwell** [comment]
![image](https://user-images.githubusercontent.com/48565589/96931058-b5055500-148a-11eb-81e2-483865b81a57.png)

**Comment by mbsijblackwell** [comment]
That is the archive when writing to the c drive

**Comment by snakefoot** [comment]
What happens if you do this a application start:

```xml
var logpath = NLog.LogManager.Configuration?.Variables["logpath"];
if (!string.IsNullOrEmpty(logpath) && !Directory.Exists(logpath))
          Directory.CreateDirectory(logpath);
```

How do you expect file-permissions should work on the network-share?

**Comment by mbsijblackwell** [comment]
I understand your thought, but why does it work on the C Drive?

**Comment by snakefoot** [comment]
> I understand your thought, but why does it work on the C Drive?

No idea. Maybe ask Microsoft how [System.IO.File.Move()](https://docs.microsoft.com/en-us/dotnet/api/system.io.file.move) is implemented.

Right now I'm only trying to probe your system to figure out what is possible or not. Maybe you don't have permissions, and `DirectoryNotFoundException` is just a vague description of that issue. Again you are the owner of the environment not me.

**Comment by mbsijblackwell** [comment]
Hmmm, I have checked all the permissions.  Administrator is running the service, so it has all rights.

**Comment by snakefoot** [comment]
So it works when you perform `System.IO.Directory.CreateDirectory(logpath);` manually before logging and archiving ?

**Comment by mbsijblackwell** [comment]
Ok, that does not work.  I will take this back to my IT on that drive config.  It is servers in an AWS host and a shared drive in that environment.  Something is not letting create that path.  Even though I can do it as a user.  I can create the folders in command prompt or via Windows Explorer.  If you will allow, please hold this open for now.

**Comment by mbsijblackwell** [comment]
Closing issue.  Didn't really find a solution to the issue with the AWS shared drive.  Changed some of my logging to a db logging to reduce the demand on the file based logging.  So, worked around the issue.  I will be using the archiving to the c drive to manage the file logging still enabled and the auto delete feature to keep it managed.

**Comment by snakefoot** [comment]
Now that the issue with directory creation has been investigated, then there is also a small issue with your use of `archiveFileName=`:
```xml
    <target xsi:type="File" name="logfileinfo" 
            fileName="${basedir}\logs\mrssend\${company}\nlog-info.log" 
            archiveFileName="${logpath}\${company}\${process}\nlog-info-${shortdate}.log"
            layout="${date} Content: ${message}"
            maxArchiveFiles="30" 
            archiveEvery="day"/>
```

You should do this instead for the archive cleanup to work as intended (Notice `{#}`):

```xml
    <target xsi:type="File" name="logfileinfo" 
            fileName="${basedir}\logs\mrssend\${company}\nlog-info.log" 
            archiveFileName="${logpath}\${company}\${process}\nlog-info-{#}.log"
            layout="${date} Content: ${message}"
            maxArchiveFiles="30" 
            archiveEvery="day"/>
```

See also: https://github.com/NLog/NLog/wiki/FileTarget-Archive-Examples#date (You don't have to specify `archiveDateFormat=` as it will be deduced automatically from value of `archiveEvery=`).
