### ISSUE TITLE
Sequential file generation in Nlog

### ISSUE THREAD

**Issue by heizel184** [NLog/NLog#4147]
Hi!
I am trying to create a new log file on each application startup, and previous file should be archived. The problem I am facing is that I want log filename to be generated with a sequence no that should always increment by 1 on each application restart. For example, the first log file should be named as: Api_shortdate_000 On restart, a new file should be created with name Api_shortdate_001.log

similarly On each subsequent restart, the counter should increase.

I dont want use custom-layout-rendrerer for this problem is there is any other way?

**Comment by snakefoot** [comment]
See also: https://stackoverflow.com/questions/64426859/how-to-create-log-file-in-nlog-with-a-sequence-no-include-in-filename-on-each-ap

**Comment by heizel184** [comment]
Hey I used ArchiveOldFileOnStartup in my nlog.config and set the file name in target as 
            
<target xsi:type="File" name="logs" fileName="D:/Api_${shortdate}_{###}.log >
this is filling the half of the requirement 
=》archive the old file on startup and also add a sequence no at the end 
Api_10102020_000  ______first generated file 
Api_10102020_001 _________second generated file 
Api_10102020_### ____ current file 
But for the current file it adds ### at the end of the file 
Api_10102020_###

I want to append a new sequence no at the end of the current file instead  ###
any solution available in nlog 
I don't want to use custom layout

**Comment by snakefoot** [comment]
> I dont want use custom-layout-rendrerer for this problem is there is any other way?

Not that I know of, but you are welcome to dive into the source-code of NLog FileTarget
