### ISSUE TITLE
Support for date descending logs

### ISSUE THREAD

**Issue by ajtruckle** [NLog/NLog#4154]
Hi

Other logging tools that I use for C# (SimpleLogger) create the log files in a sub folder and are written on a date by date basis. Each log file for that date are always maintained in date descending order which makes sense as the most recent issues are at the top.

Since the concept uses a folder with log files based on individual dates the data files are never too large.

Can't we have a similar approach for Nlog so I can also do the same with my VB.Net project logging?

**Comment by snakefoot** [comment]
See also: https://stackoverflow.com/questions/64648122/displaying-nlog-in-date-descending-order

**Comment by ajtruckle** [comment]
Thanks for linking to my SO question.

**Comment by snakefoot** [comment]
Closing as stackoverflow-question has been resolved.
