### ISSUE TITLE
How get a specific exception data item in layout rendering

### ISSUE THREAD

**Issue by Eugene-Lytvynov** [NLog/NLog#4155]
Hi!

I need save specific data item from exception layout rendering. As i understand - now we can save only whole collection of data items with separator. But i need to get an access for specific element by name.

reason: we use specific field in db for future reports. I need access to this item in data of exception structure

Best regard, Eugene

**Comment by snakefoot** [comment]
It could have neat if one could do this:

`${exception:object-path=Data.MyKey}`

But the Data-Dictionary on the Exception-object is a special `IDictionary`, and does not act like an expando-object.

The `ExceptionLayoutRenderer` is very focused about its `Format`-property, and trying to mix this with doing explicit lookup in Data-Dictionary will probably give more pain than benifit.

My suggestion is creating a new layoutrenderer called `ExceptionDataLayoutRenderer` with property `string Item` andf property `string Format`. Pull-Requests are welcome.

**Comment by ErickJeffries** [comment]
@snakefoot, I think I see where you're going, I'll take a crack at it. This one will be my first PR on this project so please let me know if I missed something.

**Comment by snakefoot** [comment]
Closed by #4226
