### ISSUE TITLE
Wiki Page - Special Folder Layout Renderer Typo/Error

### ISSUE THREAD

**Issue by joeburdick** [NLog/NLog#4157]
https://github.com/NLog/NLog/wiki/Special-Folder-Layout-Renderer

"LocalApplicationData - Application data for all users (Good when running as Windows Service)"

should read:

"CommonApplicationData - Application data for all users (Good when running as Windows Service)"

**Comment by joeburdick** [comment]
Just realized I could edit this myself

**Comment by 304NotModified** [comment]
@joeburdick thanks for fixing!
