### ISSUE TITLE
Creating blank\empty file

### ISSUE THREAD

**Issue by FilipNemec** [NLog/NLog#4160]
Hi,
I need to create the log file (*.txt) after NLog.LogFactory.GetLogger(string name) method is called. I wouldn't like to write an unnecessary log for the file to be created.
Is it currently possible to force creation of the file after creating the logger?

Thanks in advance for your answer.

**Comment by snakefoot** [comment]
Think the only way to create the log-file upfront is to write something to the logger. Ex. `logger.Info("App Started");`
