### ISSUE TITLE
No programmatic support for rule "enabled "attribute

### ISSUE THREAD

**Issue by IanKemp** [NLog/NLog#4167]
As per the description of #4101, this package does not surface the `enabled` attribute on rules via the `LoggingRule` class. This attribute is defined in the official XSD at https://nlog-project.org/schemas/NLog.xsd:

```xml
<xs:attribute name="enabled" type="xs:boolean" default="true">
  <xs:annotation>
    <xs:documentation>Enable this rule. Note: disabled rules aren't available from the API.</xs:documentation>
  </xs:annotation>
</xs:attribute>
```

It appears that the comment "disabled rules aren't available from the API" is correct, as calling `LogManager.Configuration.FindRuleByName("myDisabledRuleName")` returns `null`. **Why is this**?

The current way this is setup means I cannot define a rule as disabled in my configuration file, then load and tweak it at runtime, and finally enable it.

**NLog version**: 4.7.5

**Platform**: .NET Core 3

**Current NLog config**

(using https://github.com/NLog/NLog.Extensions.Logging to define logging config in `appsettings.json`)

```json
    "NLog": {
        "targets": {
            "ErrorFileTarget": {
                "type": "File",
                "layout": "${longdate} | [${threadid}] | ${callsite} | ${message}",
                "fileName": "${basedir}/Logs/${date:format=yyyyMMdd_HH00}.log"
            },
            "logFileTarget": {
                "type": "File",
                "layout": "${longdate} | [${threadid}] | ${callsite} | ${message}",
                "fileName": "/Logs/${date:format=yyyyMMdd_HH00}.log"
            }
        },
        "rules": [
            {
                "ruleName": "ErrorFileRule",
                "minLevel": "Error",
                "maxLevel": "Fatal",
                "writeTo": "ErrorFileTarget"
            },
            {
                "ruleName": "logFileRule",
                "minLevel": "Trace",
                "maxLevel": "Fatal",
                "writeTo": "logFileTarget",
                "enabled": false
            }
        ]
    }
```

- What is the current result? N/A
- What is the expected result? N/A
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)? N/A
- Please post full exception details (message, stacktrace, inner exceptions) N/A
- Are there any workarounds? No
- Is there a version in which it did work? N/A
- Can you help us by writing an unit test? N/A

**Comment by IanKemp** [comment]
Did a bit of digging and found https://github.com/NLog/NLog/blob/dev/src/NLog/Config/LoggingConfigurationParser.cs#L636 when parsing rules:

```cs
            if (!enabled)
            {
                InternalLogger.Debug("Logging rule {0} with filter `{1}` is disabled", ruleName, namePattern);
                return null;
            }
```

Why not still add the rule, but as `enabled = false`? What harm would it cause?

**Comment by snakefoot** [comment]
`enabled` came first, and allowed one to use NLog-Config-Variables to control the `enabled`-flag for all relevant LoggingRules.

`ruleName` was [introduced](https://github.com/NLog/NLog/pull/2891) much later, to make it easier to lookup and adjust an existing logging-rule. So the use-case of performing lookup of disabled logging-rules never existed until then.

> Why not still add the rule, but as enabled = false? What harm would that cause?

Could the same not be implemented like this:

```json
            {
                "logger": "*",
                "ruleName": "logFileRule",
                "level": "Off",
                "writeTo": "logFileTarget",
            }
```

Alternative you can dynamically control the level-filter: https://github.com/NLog/NLog/wiki/Filtering-log-messages#semi-dynamic-routing-rules

**Comment by IanKemp** [comment]
> So the use-case of performing lookup of disabled logging-rules never existed until then.

Fair enough, but I have that use-case now, so is there any good reason **not** to support it?

> Could the same not be implemented like this:

Yes, in that it has the same practical effect.
No, in that it has a different semantic meaning:
* `level: Off` means I still want the rule to be evaluated and executed, it will just do nothing if it is hit
* `enabled: false` means I want the rule to be ignored entirely, i.e. it will exists but not be evaluated or executed at all

**Comment by snakefoot** [comment]
> No, in that it has a different semantic meaning:

Well that is exactly how NLog works right now. `Enabled = false` means it is thrown away and never evaluated again (ignored entirely). `level: Off` means that it sticks around, and can be adjusted to actually redirect logevents to configured target(s).

Anyway breaking change to suddenly having disabled logging-rules dangling. You are welcome to create a pull-request for NLog 5, and if it source-code is elegant and it is not hurting performance to have 1000 dangling logging-rules, then it will probably be accepted.

**Comment by IanKemp** [comment]
> Anyway breaking change to suddenly having disabled logging-rules dangling. You are welcome to create a pull-request for NLog 5, and if it source-code is elegant and it is not hurting performance to have 1000 dangling logging-rules, then it will probably be accepted.

Thank you, that's the kind of feedback I was hoping for. Would you be open to adding a top-level configuration option to control the behaviour around disabled rules? Something like a boolean called `loadDisabledRules`:

* If not present or set to `false` (default), NLog functions as currently: rules marked as `enabled: false` are effectively ignored at runtime.
* If present and set to `true`, NLog will load all rules, even those marked as `enabled: false`, but disabled rules won't be evaluated.

The `Enabled` boolean property can then be added to `LoggingRule` and will behave as follows:

* If `loadDisabledRules` is not present or set to `false`, attempting to get/set `LoggingRule.Enabled` will throw an `InvalidOperationException` informing the caller that what they're doing will have no effect.
* If `loadDisabledRules` is present and set to `true`, get/set of `LoggingRule.Enabled` will work as expected.

The implementation of `LoggingRule.Enabled` behaviour is up for debate. I'm not sure how NLog works internally, but my guess would be that it effectively uses a single `IEnumerable<LoggingRule>` which is iterated when evaluating rules. The simplest (but not necessarily most performant) change is therefore to alter that iteration to skip rules that have `Enabled = false` via a simple `if` or predicate. Alternatively we could have two lists, one for the enabled and the other for the disabled rules, and only iterate the former when evaluating rules - that however makes things more difficult in the case that we want to iterate all rules, e.g. `FindRuleByName`.

As all of the above is new, current code using NLog will continue to function as normal, without the potential penalty of many disabled rules. Anyone who wants the ability to manipulate disabled rules, and/or enable or disable rules at runtime, needs to opt-in to this new functionality via setting `loadDisabledRules: true`. `LoggingRule.Enabled` similarly does not yet exist and current code will not break if that property is added.

**Comment by snakefoot** [comment]
> option to control the behaviour around disabled rules? Something like a boolean called loadDisabledRules:

Sounds a little convolutted. Just make sure that performance is good. Prefer to have good default behavior without special options. Special options leads to frozen code (code only executed once a year) and fear of change.

**Comment by snakefoot** [comment]
Closing as inactive

**Comment by ericnewton76** [comment]
Man this bites me today... I have a rule for a console logger that by nlog.config is enabled=false but added some code tied to pressing L key to gradually increase the console logging from "enabled=false" -> loglevel.info -> loglevel.debug -> "enabled=false"

Was disappointed to find out the rule is never added to configuration for manipulating via code.

I will look and see if the pull request was ever started.

**Comment by snakefoot** [comment]
Instead of using `enabled="false"` then one could just use  `minLevel="Off"`. 

See also: https://github.com/NLog/NLog/wiki/Filtering-log-messages#semi-dynamic-routing-rules

See also: #4948
