### ISSUE TITLE
API proposal: add LoggingRule.AllNamePattern field

### ISSUE THREAD

**Issue by IanKemp** [NLog/NLog#4168]
When it comes to logger name patterns, the majority of people will likely want everything, which is expressed as the pattern "*". However this does not seem to be explicitly documented anywhere, except as a hardcoded default argument to some methods. It also means that users have to manually type this constant value when defining "all" rules.

In order to simplify usage, I propose adding a simple field to `LoggingRule` encapsulating this specific pattern:

```cs
public class LoggingRule
{
    public const string AllNamePattern = "*";
}
```

All methods that currently use hardcoded `*` (e.g. `LoggingConfiguration.AddRule` overloads) will then be changed to refer to this field instead.

**Comment by snakefoot** [comment]
Maybe include the word "Logger" in the name of the constant (Ex. `AllLoggerNamesPattern` or `AllLoggersWildcard`).

Have no oppinion about adding an official const-value for this. Think I have been using ´NLog.config` too long :)

**Comment by snakefoot** [comment]
Closing as incative.
