### ISSUE TITLE
API proposal: improve addition of named logging rules

### ISSUE THREAD

**Issue by IanKemp** [NLog/NLog#4169]
For legacy reasons, the first parameter to most constructors of `LoggingRule` is `string loggerNamePattern`. With the relatively recent introduction of named rules, I envision that many people will be more interested in defining rules in this manner - unfortunately the current API doesn't support this very well.

The simplest way to accomplish this would be to add new overload constructors to `LoggingRule` that take `string ruleName` as an additional parameter:

* `public LoggingRule(string loggerNamePattern, Target target, string ruleName)`
* `public LoggingRule(string loggerNamePattern, LogLevel minLevel, Target target, string ruleName)`
* `public LoggingRule(string loggerNamePattern, LogLevel minLevel, LogLevel maxLevel, Target target, string ruleName)`

For me, this is inconvenient and clumsy because most of the time I don't care about the `loggerNamePattern` argument - I want it set to `*`. We can additionally/instead add a subclass to encapsulate this:

```cs
public class NamedLoggingRule : LoggingRule
{
    public NamedLoggingRule(string ruleName, Target target)
        : base("*", target)
    {
        RuleName = ruleName;
    }

    ... other constructors as well...
}
```

(Assuming #4168 is approved and implemented, we would use `LoggingRule.AllNamePattern` instead of the hardcoded `"*"` string here.)

Going forward then, every time you explicitly want a named rule, you use `NamedLoggingRule`. If you want the current behaviour, you use `LoggingRule`.

The `AddRule` methods on `LoggingConfiguration` should also receive additional overloads that take `ruleName`. Because the argument ordering on these is a little better, we can simply add `ruleName` as a first parameter:

```cs
void AddRule(string ruleName, LogLevel minLevel, LogLevel maxLevel, string targetName, string loggerNamePattern = "*")
void AddRule(string ruleName, LogLevel minLevel, LogLevel maxLevel, Target target, string loggerNamePattern = "*")
void AddRuleForOneLevel(string ruleName, LogLevel level, string targetName, string loggerNamePattern = "*")
void AddRuleForOneLevel(string ruleName, LogLevel level, Target target, string loggerNamePattern = "*")
void AddRuleForOneLevel(string ruleName, LogLevel level, Target target, string loggerNamePattern, bool final)
void AddRuleForAllLevels(string ruleName, string targetName, string loggerNamePattern = "*")
void AddRuleForAllLevels(string ruleName, Target target, string loggerNamePattern = "*")
void AddRuleForAllLevels(string ruleName, Target target, string loggerNamePattern, bool final)
```

(Again, should #4168 happen, `"*"` will instead refer to `LoggingRule.AllNamePattern`.)

**Comment by snakefoot** [comment]
There is already #4128 that will automatically use logger="*" unless specified something else.

I would like to move towards improving `NLog.LogManager.Setup()`-extension-methods. If you have input for improving the suggested API even further, then please tell.

**Comment by snakefoot** [comment]
Closing as inactive
