### ISSUE TITLE
Rolling to static archive files

### ISSUE THREAD

**Issue by PatriQ94** [NLog/NLog#4170]
Hello!

So my company has requirements as follows: Have 1 _static_ log file and 2 _static_ archive log files. The reason for this is so we manually create these files and give manually write permissions to IIS to be able to write into these files (can't give write permissions to entire Logs folder). I've achieved something similar with this configuration

```xml
<targets>
    <target 
      name="allfile" 
      xsi:type="File"
      layout="${longdate}|${level:uppercase=true}|${logger}|${message}"
      filename="Logs/log.txt"
      archiveFileName="Logs/log.{#}.txt" 
      archiveAboveSize="1000000" 
      archiveNumbering="Rolling" 
      concurrentWrites="True" 
      maxArchiveFiles="2"
      keepFileOpen="True"
      enableFileDelete="False">
    </target>
  </targets>
```
which results in constant 3 files:
log.txt
log.0.txt
log.1.txt

The only issue with this is that the archive files, they keep getting _re-created_ when reaching max size, instead of just content being compied over. And since NLog tries to recreate these archive files, it can't because the Logs folder doesn't and cant have write permissions. Any suggestions how to make these archive files be static at all costs?

**Comment by snakefoot** [comment]
When using maxArchiveFiles, then NLog will always delete and create new.

I guess one could make a small fix to NLog, so when using static archive-filename. Ex `archiveFileName="Logs/log.1.txt"`, then NLog will truncate the archive-filename when larger than `ArchiveAboveSize`. This would allow you to have 2 files (active and archived) that are never deleted.

**Comment by PatriQ94** [comment]
> When using maxArchiveFiles, then NLog will always delete and create new.
I guess one could make a small fix to NLog, so when using static archive-filename. Ex archiveFileName="Logs/log.1.txt", then NLog will truncate the archive-filename when larger than ArchiveAboveSize. This would allow you to have 2 static files (active and archived) that are never deleted.

I see, understandable. So basically there's no way to achieve this with the current version of Nlog without changing its source code?

**Comment by snakefoot** [comment]
Not as far as I know. But it is a small change, so with a little effort it could be included with next NLog release.


Sent from my Sony Xperia


---- PatriQ94 wrote ----


When using maxArchiveFiles, then NLog will always delete and create new.
I guess one could make a small fix to NLog, so when using static archive-filename. Ex archiveFileName="Logs/log.1.txt", then NLog will truncate the archive-filename when larger than ArchiveAboveSize. This would allow you to have 2 static files (active and archived) that are never deleted.

I see, understandable. So basically there's no way to achieve this with the current version of Nlog without changing its source code?

**Comment by snakefoot** [comment]
But notice that the suggested change will only give you: Log.txt and Log.1.txt (You will not get Log.2.txt)


Sent from my Sony Xperia


---- PatriQ94 wrote ----


When using maxArchiveFiles, then NLog will always delete and create new.
I guess one could make a small fix to NLog, so when using static archive-filename. Ex archiveFileName="Logs/log.1.txt", then NLog will truncate the archive-filename when larger than ArchiveAboveSize. This would allow you to have 2 static files (active and archived) that are never deleted.

I see, understandable. So basically there's no way to achieve this with the current version of Nlog without changing its source code?

**Comment by PatriQ94** [comment]
>But notice that the suggested change will only give you: Log.txt and Log.1.txt (You will not get Log.2.txt)

I see. What about something like this for example: ``archiveFileName="Logs/log.1.txt,Logs/log.2.txt,Logs/log.3.txt"``
Where one could list fixed files for archiving and then the roller would just be constantly rolling over them? Just thinking out loud.

**Comment by snakefoot** [comment]
That would not be a small change. But if my suggested change does not forfil your needs, then you are welcome to create a pull request, where MaxArchiveFiles=2 and EnableFileDelete=false is working as you want. But such pull request will probably be merged to dev, and wait for NLog 5 release (unless you find an elegant and simple solution)


Sent from my Sony Xperia


---- PatriQ94 wrote ----


But notice that the suggested change will only give you: Log.txt and Log.1.txt (You will not get Log.2.txt)

I see. What about something like this for example: archiveFileName="Logs/log.1.txt,Logs/log.2.txt,Logs/log.3.txt"
Where one could list fixed files for archiving and then the roller would just be constantly rolling over them? Just thinking out loud.

**Comment by PatriQ94** [comment]
Hey, just wanted to give you an update. At the end my superiors decided to write custom logger solution but in case anyone is reading this sometime later, I definitely agree with @snakefoot suggestion to just give write permissions to the entire Logs folder and avoid the mess we're having (mostly due to management).
