### ISSUE TITLE
Old files are not getting deleted on Windows server

### ISSUE THREAD

**Issue by ymetelkin** [NLog/NLog#4174]
Deleting of old files does not work on our production server but works on my development machine. 
NLog version 4.7.5
NET Framework 4.7.2
Server: AWS EC2 Windows
Configuration:
```xml
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <targets>
      <target name="logfile" xsi:type="File" fileName="${basedir}/logs/${shortdate}.log" maxArchiveDays="1" maxArchiveFiles="1" encoding="utf-8" keepFileOpen="true"/>
    </targets>
    <rules>
      <logger name="*" level="Info" writeTo="logfile" />
    </rules>
  </nlog>

```

**Comment by 304NotModified** [comment]
That sounds a permission error. 
Please enable and check the [internal log](https://github.com/NLog/NLog/wiki/Internal-logging)

**Comment by ymetelkin** [comment]
The internal log is attached. 
[nlog-internal.txt](https://github.com/NLog/NLog/files/5574388/nlog-internal.txt)

**Comment by snakefoot** [comment]
What happens if you enable `archiveOldFileOnStartup="true"` ? See also: https://github.com/nlog/NLog/wiki/File-target

**Comment by snakefoot** [comment]
Looks like your NLog.config shown in intial topic is not matching the output from `nlog-internal.txt`

`2020-11-20 15:10:47.0603 Debug FileTarget(Name=logfile): Preparing for new file 'C:\AP\SearchAPI\/logs/current.log'`

According to `nlog-internal.txt` then you have configured it like this:

`FileName="${basedir}/logs/current.log"`
`ArchiveFileName="${basedir}/logs/${shortdate}.log"`

It is not supported to use `${shortdate}` for `ArchiveFileName`. See also https://github.com/NLog/NLog/issues/3807#issuecomment-587661413 and https://github.com/NLog/NLog/issues/4105#issuecomment-685952654
