### ISSUE TITLE
Probable I/O race condition detected while copying memory. The I/O package is not thread safe by default.

### ISSUE THREAD

**Issue by RamBhat** [NLog/NLog#4175]
Hi! Thanks for reporting this bug! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

We are using NLOG version 4.7.2 and greater with .net framework 4.6.

Seems to occur at undeterminate points at diff points in application. we are using rest api to log messages for info, debug and error. 

can you let me know if tis error is fixed

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      throwExceptions="false">

  <variable name="appName" value="YourAppName" />

  <targets async="true">
    <target xsi:type="File"
            name="xyz_info"
            layout="${longdate} - ${level:uppercase=true}: ${message}${onexception:${newline}EXCEPTION\: ${exception:format=ToString}}"
          
  fileName="d:\\xyz_info.log"
    keepFileOpen="false"
    archiveFileName="e:\\\nlog_arch\\xyz_info_arch_${shortdate}.{##}.log"
    archiveNumbering="Sequence"
    archiveEvery="Day"
    maxArchiveFiles="50000"
    />
	<target xsi:type="File"
            name="cashwaste_error"
            layout="${longdate} - ${level:uppercase=true}: ${message}${onexception:${newline}EXCEPTION\: ${exception:format=ToString}}"
          
  fileName="d:\\xyz_error.log"
    keepFileOpen="false"
    archiveFileName="e:\\nlog_arch\\xyz_error_arch_${shortdate}.{##}.log"
    archiveNumbering="Sequence"
    archiveEvery="Day"
    maxArchiveFiles="50000"
    />
	<target xsi:type="File"
            name="cashwaste_debug"
            layout="${longdate} - ${level:uppercase=true}: ${message}${onexception:${newline}EXCEPTION\: ${exception:format=ToString}}"
          
  fileName="E:\\xyz_debug.log"
    keepFileOpen="false"
    archiveFileName="E:\\xyz_debug_arch_${shortdate}.{##}.log"
    archiveNumbering="Sequence"
    archiveEvery="Day"
    maxArchiveFiles="50000"
    />
  </targets>
  <rules>
    <logger name="*" writeTo="xyz_info" minlevel="Info" />
    <logger name="*" writeTo="xyz_error" minlevel="Error" />
    <logger name="*" writeTo="xyz_debug" minlevel="Debug" />
  </rules>
</nlog>
```

actual exception

```
2020-1-6 17:02:02.0849 - ERROR: Controller : API ERROR : Probable I/O race condition detected while copying memory. The I/O package is not thread safe by default. In multithreaded applications, a stream must be accessed in a thread-safe way, such as a thread-safe wrapper returned by TextReader's or TextWriter's Synchronized methods. This also applies to classes like StreamWriter and StreamReader.
    at xyz.Services.CW.create(Cw cwd, String username) in c:\abc\CreateCw.cs:line 594
   at xyz.abc.Controllers.v1.CWController.<Post>d__2.MoveNext() in C:\cw\Controllers\v1\Cw.cs:line 220 tranId = fae0d427753a4745bba2b0ad5477d283

2020-1-6 17:02:02.0849 - ERROR: Controller : API ERROR : Probable I/O race condition detected while copying memory. The I/O package is not thread safe by default. In multithreaded applications, a stream must be accessed in a thread-safe way, such as a thread-safe wrapper returned by TextReader's or TextWriter's Synchronized methods. This also applies to classes like StreamWriter and StreamReader.
    at xyz.abc.Controllers.v1.cwcontroller.<Post>d__2.MoveNext() in C:\cw\v1\cw.cs:line 231 tranId = fae0d427753a4745bba2b0ad5477d283
```

line where it is called:

initiated

```c#
 public class Log
        {

        public static void Error(string message)
        {
            string tranId = HttpContext.Current.Items["TRANID"] as string;
            var logger = NLog.LogManager.GetCurrentClassLogger();
            logger.Error(message + " tranId = " + tranId);
        }
        public static void Info(string message)
        {
            string tranId = HttpContext.Current.Items["TRANID"] as string;
            var logger = NLog.LogManager.GetCurrentClassLogger();
            logger.Info(message + " tranId = " + tranId);
        }
        public static void Debug(string message)
        {
            string tranId = HttpContext.Current.Items["TRANID"] as string;
            var logger = NLog.LogManager.GetCurrentClassLogger();
            logger.Debug(message + " tranId = " + tranId);
        }
    }
```

```c#
 Log.Info("Contr:Data sent for ");`
```

info provided on how the method is called.Like i said before it ocurrs at indefinite times and not at any specific time. This is just one of the illustration:

 public class Log
        {

        public static void Error(string message)
        {
            string tranId = HttpContext.Current.Items["TRANID"] as string;
            var logger = NLog.LogManager.GetCurrentClassLogger();
            logger.Error(message + " tranId = " + tranId);
        }
        public static void Info(string message)
        {
            string tranId = HttpContext.Current.Items["TRANID"] as string;
            var logger = NLog.LogManager.GetCurrentClassLogger();
            logger.Info(message + " tranId = " + tranId);
        }
        public static void Debug(string message)
        {
            string tranId = HttpContext.Current.Items["TRANID"] as string;
            var logger = NLog.LogManager.GetCurrentClassLogger();
            logger.Debug(message + " tranId = " + tranId);
        }
    }
 Log.Info("Contr:Data sent for ");`

**Comment by snakefoot** [comment]
@RamBhat Can you include the entire Exception-StackTrace? Then it would be easier to see, if there an actual issue in NLog.

**Comment by RamBhat** [comment]
> @RamBhat Can you include the entire Exception-StackTrace? Then it would be easier to see, if there an actual issue in NLog.

2020-1-6 17:02:02.0849 - ERROR: Controller : API ERROR : Probable I/O race condition detected while copying memory. The I/O package is not thread safe by default. In multithreaded applications, a stream must be accessed in a thread-safe way, such as a thread-safe wrapper returned by TextReader's or TextWriter's Synchronized methods. This also applies to classes like StreamWriter and StreamReader.
    at xyz.Services.CW.create(Cw cwd, String username) in c:\abc\CreateCw.cs:line 594
   at xyz.abc.Controllers.v1.CWController.<Post>d__2.MoveNext() in C:\cw\Controllers\v1\Cw.cs:line 220 tranId = fae0d427753a4745bba2b0ad5477d283
2020-1-6 17:02:02.0849 - ERROR: Controller : API ERROR : Probable I/O race condition detected while copying memory. The I/O package is not thread safe by default. In multithreaded applications, a stream must be accessed in a thread-safe way, such as a thread-safe wrapper returned by TextReader's or TextWriter's Synchronized methods. This also applies to classes like StreamWriter and StreamReader.
    at xyz.abc.Controllers.v1.cwcontroller.<Post>d__2.MoveNext() in C:\cw\v1\cw.cs:line 231 tranId = fae0d427753a4745bba2b0ad5477d283

**Comment by snakefoot** [comment]
Cannot see any NLog-source-code in those stacktraces.

What happens at `c:\abc\CreateCw.cs:line 594` ? What happens at `C:\cw\v1\cw.cs:line 231` ?

**Comment by RamBhat** [comment]
> Cannot see any NLog-source-code in those stacktraces.
> 
> What happens at `c:\abc\CreateCw.cs:line 594` ? What happens at `C:\cw\v1\cw.cs:line 231` ?

added in the original comment

**Comment by RamBhat** [comment]
Like i said it ocurrs within the application at different instances, the code snippet is just one of the places where we found from logs

info provided on how the method is called.Like i said before it ocurrs at indefinite times and not at any specific time. This is just one of the illustration:

 public class Log
        {

        public static void Error(string message)
        {
            string tranId = HttpContext.Current.Items["TRANID"] as string;
            var logger = NLog.LogManager.GetCurrentClassLogger();
            logger.Error(message + " tranId = " + tranId);
        }
        public static void Info(string message)
        {
            string tranId = HttpContext.Current.Items["TRANID"] as string;
            var logger = NLog.LogManager.GetCurrentClassLogger();
            logger.Info(message + " tranId = " + tranId);
        }
        public static void Debug(string message)
        {
            string tranId = HttpContext.Current.Items["TRANID"] as string;
            var logger = NLog.LogManager.GetCurrentClassLogger();
            logger.Debug(message + " tranId = " + tranId);
        }
    }

this line is in cw.cs file
 Log.Info("Contr:Data sent for ");`

**Comment by snakefoot** [comment]
@RamBhat Since there is no callstack that suggest NLog is the issue, then I will leave this issue alone. Maybe others can find the clue.

**Comment by 304NotModified** [comment]
NLog isn't in the stacktrace, so this doesn't seem the issue from NLog.
