### ISSUE TITLE
${aspnet-request-ip} not working - .NET Core Web Api

### ISSUE THREAD

**Issue by ivan5co** [NLog/NLog#4177]
I created .NET Core web api project (.NET Core 3.1), and trying to setup to get client ip address, but unsuccessfully. 

I have installed Nlog.Web.ASPNetCore 4.9.3, also added to nlog.config
```

<extensions>
    <add assembly="NLog.Web.AspNetCore"/>
  </extensions>
```

but constantly receive null for ip address.

**Comment by snakefoot** [comment]
Have you checked NLog InternalLogger at Debug-Level: https://github.com/NLog/NLog/wiki/Internal-Logging
