### ISSUE TITLE
 ${aspnet-request-posted-body} not logging

### ISSUE THREAD

**Issue by heizel184** [NLog/NLog#4179]
Hey 
 i am using ${aspnet-request-posted-body} in my log file to log requeswt body 
 here is nlog.config 

```xml
 <target xsi: type="File" name="allfile" fileName="c:\Logs\Api_.log"
            layout="==>[${event-properties:item=traceLevel}: User=${aspnet-user-identity}; ]
                        ${when:when=('${event-properties:item=traceLevel}' == 'Verbose' and '${aspnet-request-method}' != 'GET')   > 0 and length('${mdlc:item=RequestId}') > 0:inner=${newline}Request-Body\: ${aspnet-request-posted-body}}
                        ${newline}Logger name: ${logger} 
                        ${newline}" />
```

But ${aspnet-request-posted-body} is returning an empty string also {mdlc:item=RequestId} not working 
I have added configuration in startup.cs but still not working 
```c#
 app.Use(async (context, next) =>
            {
                context.Request.EnableBuffering();
                await next?.Invoke();
            });
```

**Comment by snakefoot** [comment]
Would probably start with something simple like this:

    <target xsi:type="File" name="allfile" fileName="c:\Logs\Api_.log"
                layout="RequestId=${mdlc:item=RequestId} RequestBody=${aspnet-request-posted-body}" />

And then enable the NLog InternalLogger at Debug-Level and look for clues:

- https://github.com/NLog/NLog/wiki/Internal-Logging
- https://github.com/NLog/NLog/wiki/Logging-troubleshooting

Besides calling `EnableBuffering()` then you also need to correctly register NLog as LoggingProvider with the method `UseNLog()`. See also https://github.com/NLog/NLog/wiki/Getting-started-with-ASP.NET-Core-3

What is the output from the NLog InternalLogger ?

**Comment by heizel184** [comment]
I have checked the above mentioned requirements for Nlog .All seems good. Nlog is also logging messages but only the request body requestId and user name is not printing in file 
current nlog.config is 
<target xsi:type="File" name="allfile" fileName="c:\Logs\Api_.log"
            layout="   message = ${message} RequestId=${mdlc:item=RequestId} RequestBody=${aspnet-request-posted-body}" />

Here is the output of internal log 
2020-11-22 00:00:25.7911 Info Message Template Auto Format enabled
2020-11-22 00:00:25.7973 Info Loading assembly: NLog.Web.AspNetCore
2020-11-22 00:00:25.8858 Info Adding target FileTarget(Name=allfile)
2020-11-22 00:00:25.9203 Info Validating config: TargetNames=allfile, ConfigItems=156, FilePath=nlog.config

**Comment by snakefoot** [comment]
@heizel184  Please "enable the NLog InternalLogger at **Debug**-Level"

**Comment by heizel184** [comment]
@snakefoot i found this error.

2020-11-22 01:52:25.2290 Debug Error => allfile
2020-11-22 01:52:25.2290 Debug Fatal => allfile
2020-11-22 01:52:26.3909 Debug Missing serviceProvider, so no HttpContext
2020-11-22 01:52:26.4100 Debug Missing serviceProvider, so no HttpContext
2020-11-22 01:52:26.4100 Debug Missing serviceProvider, so no HttpContext
2020-11-22 01:52:26.4100 Debug Missing serviceProvider, so no HttpContext

**Comment by snakefoot** [comment]
@heizel184 Please ensure "to correctly register NLog as LoggingProvider with the method `UseNLog()`." See also https://github.com/NLog/NLog/wiki/Getting-started-with-ASP.NET-Core-3

**Comment by snakefoot** [comment]
Guess the issue has been resolved: https://stackoverflow.com/questions/64935427/mdlcitem-requestid-and-aspnet-request-posted-body-not-returning-data/64942515#64942515 ?

**Comment by snakefoot** [comment]
Thanks to @bakgerman now NLog.Web.AspNetCore v5.1 re-introduces [${aspnet-request-posted-body}](https://github.com/NLog/NLog/wiki/AspNet-Request-posted-body-layout-renderer) with help from middleware:
```c#
app.UseMiddleware<NLog.Web.NLogRequestPostedBodyMiddleware>();
```
It is no longer necessary to explicit call `context.Request.EnableBuffering();` as it is handled by the middleware.
