### ISSUE TITLE
Issue of Mail sending with Send Grid 

### ISSUE THREAD

**Issue by kodithuwa** [NLog/NLog#4183]
Hi,
I have setup config as below for sendgrid, but it is not sending error notifications  to the target email.
Please let me know anything wrong in this configuration

```xml
<target name="errorMail" xsi:type="Mail"
            smtpServer="smtp.sendgrid.net"
            smtpPort="587"
            smtpAuthentication="Basic"
            smtpUserName="api_key_name"
            smtpPassword="api_key"
            enableSsl="false"
            subject="Message from NLog on ${machinename} "
            body="${longdate}|${event-properties:item=EventId.Id}|${logger}|${uppercase:${level}}|  ${message} ${exception}|url: ${aspnet-request-url}|action: ${aspnet-mvc-action}"
            from="xxx@xxxx.com"
            to="Application Errors - PERCS &lt;133a3c91.xxx.com@apac.teams.ms&gt;"
          />
```

- NLog Version=4.6.7
- NLog.MailKit Version=3.0.2
- NLog.Web.AspNetCore Version=4.8.4 

- **Platform**: ..NET Core 2.2 

Thank You
CK

**Comment by snakefoot** [comment]
Have you checked the NLog InternalLogger for warnings / errors: https://github.com/NLog/NLog/wiki/Internal-Logging ?

Did you [remember to flush](https://github.com/NLog/NLog/wiki/Tutorial#5-remember-to-flush) ?

**Comment by LauriHautala** [comment]
Hi! Smpt user name should be just "apikey", not the name of your API key. At least this was working for me.

`<target name="errorMail" xsi:type="Mail"
            smtpServer="smtp.sendgrid.net"
            smtpPort="587"
            smtpAuthentication="Basic"
            smtpUserName="apikey"
            smtpPassword="your_api_key"
            enableSsl="false"
            subject="Message from NLog on ${machinename} "
            body="${longdate}|${event-properties:item=EventId.Id}|${logger}|${uppercase:${level}}|  ${message} ${exception}|url: ${aspnet-request-url}|action: ${aspnet-mvc-action}"
            from="xxx@xxxx.com"
            to="Application Errors - PERCS &lt;133a3c91.xxx.com@apac.teams.ms&gt;"
          />`
