### ISSUE TITLE
final = "true" in rules didn't stopped the matching

### ISSUE THREAD

**Issue by shaojun** [NLog/NLog#4186]
**NLog version**: 4.7.5
**NLog.Extensions.Logging version**: 1.6.5
**Microsoft.Extensions.Logging version**: 3.1.5
**Platform**: .NET Core 3

**Current NLog config** (xml or C#, if relevant)

```xml
<nlog>
  <targets>
    <target name="dynamicPrivateFile" xsi:type="File" enableArchiveFileCompression="true" maxArchiveFiles="20" archiveAboveSize="50000000" archiveNumbering="Sequence"
            fileName="log\\${replace:searchFor=DynamicPrivate_:replaceWith=:inner=${logger}}_${date:format=yyyyMMdd}.log"
            layout="${date:format=HH\:mm\:ss.fff} [${threadid}:${level:uppercase=true}]${message} ${exception}"/>
  </targets>
  <rules>
    <logger name="DynamicPrivate_FdcServer" minlevel="Debug" writeTo="dynamicPrivateFile" final="true" />
    <logger name="DynamicPrivate_*" minlevel="Trace" writeTo="dynamicPrivateFile" final="true" />
  </rules>
</nlog>

```

used as DI into `IServiceProvider` with code: 
```
services.AddLogging(loggingBuilder =>
{
        // configure Logging with NLog
        loggingBuilder.ClearProviders();
        loggingBuilder.SetMinimumLevel(Microsoft.Extensions.Logging.LogLevel.Trace);
        var fa = loggingBuilder.AddNLog();
});
// must have below 2 lines
NLog.LogManager.Configuration = new NLog.Config.XmlLoggingConfiguration("nlog.config");
NLog.LogManager.LoadConfiguration("nlog.config");
```

app code:
```
var loggerFactory = services.GetRequiredService<ILoggerFactory>();
fdcLogger = loggerFactory.CreateLogger("DynamicPrivate_FdcServer");
//I assume the below line should hit the first rule and then stopped for more matching, thus 'DynamicPrivate_*' should NOT hit.
fdcLogger.LogTrace("Should not see trace");
```

- What is the current result?
the `Should not see trace` log had been writen to file.
and debug in VS can see:

![image](https://user-images.githubusercontent.com/3241829/100843357-3225e000-34b5-11eb-8c09-ade82308de59.png)

- What is the expected result?
the `Trace Level` log should not be writen to file,
the `IsTraceEnabled` should be `false`.
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
yes, no obvious errors.

**Comment by snakefoot** [comment]
I cannot reproduce the issue:

![image](https://user-images.githubusercontent.com/11509660/100908504-db77d080-34cb-11eb-9d32-b81fb6630d9d.png)

I used the following code (Had to change from `fdcLogger.Trace` to `fdcLogger.LogTrace` because of ILogger):

```c#
                var servicesProvider = BuildDi(config);
                using (servicesProvider as IDisposable)
                {
                    NLog.LogManager.Configuration = new NLog.Config.XmlLoggingConfiguration("nlog.config");
                    NLog.LogManager.LoadConfiguration("nlog.config");

                    var loggerFactory = servicesProvider.GetRequiredService<ILoggerFactory>();
                    var fdcLogger = loggerFactory.CreateLogger("DynamicPrivate_FdcServer");
                    fdcLogger.LogTrace("Should not see trace");
                }
```

Please create pull-request for https://github.com/NLog/NLog.Extensions.Logging/tree/master/examples/NetCore2/ConsoleExample with updates to reproduce the error (Or attach simple project that show the issue).

**Comment by shaojun** [comment]
@snakefoot 
I re-edit the `2nd rule` for a mistake in original sample posting, please help to take a look.
thanks.

**Comment by shaojun** [comment]
@snakefoot After a bit more thinking, I think this may the expected behavior in NLog rule's design, it go through all rules and stopped only it matches (and it has property `final=true`), in this case, the first rule has `minlevel` set to `Debug`, so it didn't match with `LogTrace`, and last rule will be matched.
My purpose here to using `wildcard rule` is to avoid too many `targets` defined by each module developers(our app is like a plug-in host, could be extend by developers with plug-in modules), I suppose developers using Logger with `loggerFactory.CreateLogger("DynamicPrivate_onePlugInModuleName")` in their module, without define dedicated `rule`, it'll use the default rule of `DynamicPrivate_*` which has a lowerest `minlevel` of 'Trace', if they choose not to logging so much, then define their own `rule`, like the `DynamicPrivate_FdcServer` with `minlevel` set to higher.
So what I want is the rules matching stopped at the dedicated rule whatever `minlevel` satisfied.
