### ISSUE TITLE
aspnet-user-identity is empty

### ISSUE THREAD

**Issue by jdream9728** [NLog/NLog#4187]
Hi,
      my system is use NET5 , in the system can get identity, but nlog use【 aspnet-user-identity】get value  is empty,  is  Net5 not support this?

**Comment by snakefoot** [comment]
Please enable NLog InternalLogger at debug-level and check for clues: https://github.com/NLog/NLog/wiki/Internal-Logging

Please update your question with the contents of `NLog.config`.

Please update your question with the startup-logic configuring Host-environment and NLog.

**Comment by jdream9728** [comment]
Thanks，
           I  use other way to do it ;
           but  now ，i  have a new question :
           does nlog have a way to write  many  table to database at the same time?

**Comment by snakefoot** [comment]
> does nlog have a way to write many table to database at the same time?

Please create new issue for new question, and remember close the this one with the solution you found.
