### ISSUE TITLE
Question: Is there an example of Configure-from-code in dotnet core?

### ISSUE THREAD

**Issue by kylelaverty** [NLog/NLog#4188]
Hello,

I currently have a fully setup NLog configuration using code for dotnet framework. We are looking to port our application into dotnet core and I have realized that there does not seem to be any documentation around doing code based configuration in dotnet core. I guess I have two related questions, did I miss the documentation somewhere? If not, does anyone have a sample I can look at on how to do this?

**References**
- [dotnet Framework Configure from Code](https://github.com/NLog/NLog/wiki/Configure-from-code)
- [dotnet Core 2 Console](https://github.com/NLog/NLog/wiki/Getting-started-with-.NET-Core-2---Console-application)

**Comment by snakefoot** [comment]
Examples like these:

https://github.com/NLog/NLog.Extensions.Logging/tree/master/examples/NetCore2

**Comment by kylelaverty** [comment]
@snakefoot, I have seen those samples but since all the objects that the MEL-LoggingProvider uses are different I was not sure how to set the configuration on them. Here is a sample of what I am doing for the framework version of nlog.

```csharp
// Set the root log configuration, this is used to log things about the log system.
InternalLogger.LogFile = $@"{nLogPath}\{applicationName}.NLOG.nlog";
InternalLogger.LogLevel = LogLevel.Info;

var config = new LoggingConfiguration();

var target = new FileTarget
{
     ArchiveAboveSize = ARCHIVE_LOG_FILE_ABOVE_SIZE,
     ArchiveEvery = FileArchivePeriod.Day,
     MaxArchiveFiles = DELETE_LOG_FILE_AFTER_THIS_AMOUNT,
     ConcurrentWrites = false,
     Name = "error",
     FileName = $@"{path}/{applicationName}.error.nlog",
     Layout = "${longdate}|${level}|${logger}|${message}|${exception:format=tostring}",
};

config.AddTarget(name, target);
var rule = new LoggingRule("*", target);
rule.EnableLoggingForLevel(LogLevel.Error);
rule.EnableLoggingForLevel(LogLevel.Fatal);
config.LoggingRules.Add(rule);

var consoleTarget = new ColoredConsoleTarget
{
    Name = "console",
    Layout = BASIC_LAYOUT,
};
config.AddTarget(consoleTarget.Name, consoleTarget);
var consoleRule = new LoggingRule("*", LogLevel.Info, consoleTarget);
config.LoggingRules.Add(consoleRule);

LogManager.Configuration = config;
```

Would I just do the same thing and then register the logger with DI?

**Comment by snakefoot** [comment]
> Would I just do the same thing and then register the logger with DI?

Yes it is a 2 stage setup;
- First stage is where you setup NLog-targets (as your example above).
- Second stage is adding NLog as MEL-LoggingProvider using extension-methods `UseNLog()` or `AddNLog()`

**Comment by snakefoot** [comment]
@kylelaverty Btw. since you have experience with configuring NLog-config from code, then you are very welcome to checkout #4128. It provides a more fluent API for setting up NLog-config from code. Any feedback is welcome.

**Comment by kylelaverty** [comment]
@snakefoot I will take a look and comment in that linked PR if I have any questions/comments. Just for anyone looking at this later, this question has stemmed from trying to hook NLog into EF core's logging system so I can see what sql is actually being generated. Here is a sample from the Microsoft docs:
```csharp
public static readonly LoggerFactory MyLoggerFactory
    = new LoggerFactory(new[] {new ConsoleLoggerProvider((_, __) => true, true)});

protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    => optionsBuilder
        .UseLoggerFactory(MyLoggerFactory)
        .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=EFLogging;ConnectRetryCount=0");
```
The idea would be to use the NLogLoggerProvider instead of the ConsoleLoggerProvider from the sample above.

**Comment by snakefoot** [comment]
I guess you can decide if you want to do it like this:

- EF UseLoggerFactory
   - Microsoft MEL-LoggerFactory
      -  AddNLog LoggerProvier from NLog.Extensions.Logging

Or do this:

- EF UseLoggerFactory
      - [NLogLoggerFactory](https://github.com/NLog/NLog.Extensions.Logging/blob/master/src/NLog.Extensions.Logging/Logging/NLogLoggerFactory.cs)  from NLog.Extensions.Logging

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, please let us know!
