### ISSUE TITLE
Nlog 4.76 not working on linux docker with .net core 2.1

### ISSUE THREAD

**Issue by MrXFP** [NLog/NLog#4194]
I use nlog 4.76. It can run in my local windows environment and write logs. But when I publish to linux docker, it doesn't work? Can anyone help?

net core 2.1

**Current NLog config** (xml or C#, if relevant)

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" throwExceptions="true">

  <targets xsi:type="AsyncWrapper">

    <target name="log_file" xsi:type="File"
    fileName="${basedir}/Logs/${shortdate}/${level:uppercase=false:padding=-5}.txt"
    layout="${longdate} | ${message} ${onexception:${exception:format=tostring} ${newline} ${stacktrace} ${newline}" />

    <target name="debugger" xsi:type="Debugger"
    layout="NLog: ${date:format=HH\:mm\:ss} | ${message}" />
    <target name="console" xsi:type="ColoredConsole" layout="${longdate} ${message} ${exception:format=tostring}"></target>
   


  <rules>
    <logger name="*" level="Info" writeTo="log_file" />
    <logger name="*" levels="Error" writeTo="log_file" />
    <logger name="*" levels="Debug" writeTo="log_file" />
    <!--<logger name="*" level="Debug" writeTo="debugger" />-->
    <!--<logger name="*" level="Fatal" writeTo="console" />-->
    <logger name="*" level="Fatal" writeTo="log_file" />
    <!--<logger name="*" level="Warn" writeTo="infoMail" />-->
    <logger name="*" level="Warn" writeTo="log_file" />
  </rules>
</nlog>

```

**Comment by MrXFP** [comment]
This problem has troubled me for many days. Please help.

**Comment by 304NotModified** [comment]
Please check the [internal log](https://github.com/NLog/NLog/wiki/Internal-logging)

**Comment by snakefoot** [comment]
The usual reason for NLog not producing output is because it cannot find the NLog.config:

- Ensure `nlog.config` exists in the deployment-folder
- Ensure `nlog.config` is ALL lowercase.
- Ensure you are NOT using the nuget-package [NLog.config](https://www.nuget.org/packages/NLog.Config/) (It is a trap).

See also: https://github.com/NLog/NLog/wiki/Logging-troubleshooting

**Comment by MrXFP** [comment]
> The usual reason for NLog not producing output is because it cannot find the NLog.config:
> 
> * Ensure `nlog.config` exists in the deployment-folder
> * Ensure filename of `nlog.config` is ALL lowercase (Because Linux is case-sensitive)
> * Ensure you are NOT using the nuget-package [NLog.config](https://www.nuget.org/packages/NLog.Config/) (It is a trap).
> * Ensure that the application has permissions to write into the log-directory (Enable NLog InternalLogger to diagnose)
> 
> See also: https://github.com/NLog/NLog/wiki/Logging-troubleshooting

Hi ,  

-Ensure nlog.config exists in the deployment-folder
yes. Its exists .
-Ensure filename of nlog.config is ALL lowercase (Because Linux is case-sensitive)
yes. name is NLog.config
-Ensure you are NOT using the nuget-package NLog.config (It is a trap).
how to ensure this?
-Ensure that the application has permissions to write into the log-directory (Enable NLog InternalLogger to diagnose)
yes. chmod -R 777 Logs.

**Comment by snakefoot** [comment]
- > Ensure you are NOT using the nuget-package NLog.config (It is a trap).

   - > how to ensure this?

You check your csproj-dependencies and check there is no packagereferences to the [NLog.config](https://www.nuget.org/packages/NLog.Config/)-nuget-package.

- >   Ensure that the application has permissions to write into the log-directory 

   - > yes. chmod -R 777 Logs.

Guess you have to enable the NLog InternalLogger, by inserting these lines at the start of your application:

```c#
NLog.Common.InternalLogger.LogLevel = LogLevel.Debug;
NLog.Common.InternalLogger.LogToConsole = true;
NLog.Common.InternalLogger.LogFile = "/home/nlog-internal.txt";
```

**Comment by snakefoot** [comment]
Btw I see some bugs in your NLog.config:

- > `<targets xsi:type="AsyncWrapper">`

    - It should be  `<targets async="true">` and you are missing a `</targets>`-end-tag

**Comment by MrXFP** [comment]
> * > Ensure you are NOT using the nuget-package NLog.config (It is a trap).
>   
>   
>   
>   * > how to ensure this?
> 
> You check your csproj-dependencies and check there is no packagereferences to the [NLog.config](https://www.nuget.org/packages/NLog.Config/)-nuget-package.
> 
> * > Ensure that the application has permissions to write into the log-directory
>   
>   
>   
>   * > yes. chmod -R 777 Logs.
> 
> Guess you have to enable the [NLog InternalLogger](https://github.com/NLog/NLog/wiki/Internal-logging), by inserting these lines at the start of your application:
> 
> ```cs
> NLog.Common.InternalLogger.LogLevel = LogLevel.Debug;
> NLog.Common.InternalLogger.LogToConsole = true;
> NLog.Common.InternalLogger.LogFile = "/home/nlog-internal.txt";
> ```
Thanks for your reply

I have tried InternalLogger. But it still nothing in nlog-internal.txt. Its also working well on windows.

**Comment by MrXFP** [comment]
> > * > Ensure you are NOT using the nuget-package NLog.config (It is a trap).
> >   
> >   
> >   
> >   * > how to ensure this?
> > 
> > You check your csproj-dependencies and check there is no packagereferences to the [NLog.config](https://www.nuget.org/packages/NLog.Config/)-nuget-package.
> > 
> > * > Ensure that the application has permissions to write into the log-directory
> >   
> >   
> >   
> >   * > yes. chmod -R 777 Logs.
> > 
> > Guess you have to enable the [NLog InternalLogger](https://github.com/NLog/NLog/wiki/Internal-logging), by inserting these lines at the start of your application:
> > ```cs
> > NLog.Common.InternalLogger.LogLevel = LogLevel.Debug;
> > NLog.Common.InternalLogger.LogToConsole = true;
> > NLog.Common.InternalLogger.LogFile = "/home/nlog-internal.txt";
> > ```
> 
> Thanks for your reply
> 
> I have tried InternalLogger. But it still nothing in nlog-internal.txt. Its also working well on windows.

Hi ， I tried write to console 'xxx'. It seemed ok.

> 2020-12-08 13:09:49.1614 Debug Loading config from /app/NLog.config
> 2020-12-08 13:09:49.1705 Info Configuring from an XML element in /app/NLog.config...
> 2020-12-08 13:09:49.1918 Debug ScanAssembly('NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c')
> 2020-12-08 13:09:49.2223 Debug Found assembly location directory: '/app' (NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c)
> 2020-12-08 13:09:49.2238 Debug Search for auto loading files in location: /app
> 2020-12-08 13:09:49.2247 Debug Found assembly location directory: '/app' (SHX.AdminWeb, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null)
> 2020-12-08 13:09:49.2247 Debug Auto loading based on AppDomain-BaseDirectory found location: /app
> 2020-12-08 13:09:49.2247 Debug Start auto loading, location: /app
> 2020-12-08 13:09:49.2286 Debug Auto loading done
> 2020-12-08 13:09:49.2292 Info Message Template Auto Format enabled
> 2020-12-08 13:09:49.2598 Debug Setting 'NLog.LayoutRenderers.Wrappers.UppercaseLayoutRendererWrapper.uppercase' to 'true'
> 2020-12-08 13:09:49.2703 Debug Setting 'NLog.Targets.FileTarget.name' to 'log_file'
> 2020-12-08 13:09:49.2703 Debug Setting 'NLog.Targets.FileTarget.fileName' to '${basedir}/Logs/${shortdate}/${level:uppercase=false:padding=-5}.txt'
> 2020-12-08 13:09:49.2737 Debug Setting 'NLog.LayoutRenderers.Wrappers.UppercaseLayoutRendererWrapper.uppercase' to 'false'
> 2020-12-08 13:09:49.2737 Debug Setting 'NLog.LayoutRenderers.Wrappers.PaddingLayoutRendererWrapper.padding' to '-5'
> 2020-12-08 13:09:49.2755 Debug Setting 'NLog.Targets.FileTarget.layout' to '${longdate} | ${message} ${onexception:${exception:format=tostring} ${newline} ${stacktrace} ${newline}'
> 2020-12-08 13:09:49.2755 Debug Setting 'NLog.LayoutRenderers.Wrappers.OnExceptionLayoutRendererWrapper.Inner' to '${exception:format=tostring} ${newline} ${stacktrace} ${newline}'
> 2020-12-08 13:09:49.2895 Debug Setting 'NLog.LayoutRenderers.ExceptionLayoutRenderer.format' to 'tostring'
> 2020-12-08 13:09:49.2912 Info Adding target FileTarget(Name=log_file)
> 2020-12-08 13:09:49.2924 Debug Registered target log_file: NLog.Targets.FileTarget
> 2020-12-08 13:09:49.2924 Debug Setting 'NLog.LayoutRenderers.Wrappers.UppercaseLayoutRendererWrapper.uppercase' to 'true'
> 2020-12-08 13:09:49.2924 Debug Setting 'NLog.Targets.DebuggerTarget.name' to 'debugger'
> 2020-12-08 13:09:49.2924 Debug Setting 'NLog.Targets.DebuggerTarget.layout' to 'NLog: ${date:format=HH\:mm\:ss} | ${message}'
> 2020-12-08 13:09:49.2943 Debug Setting 'NLog.LayoutRenderers.DateLayoutRenderer.format' to 'HH:mm:ss'
> 2020-12-08 13:09:49.2943 Info Adding target DebuggerTarget(Name=debugger)
> 2020-12-08 13:09:49.2943 Debug Registered target debugger: NLog.Targets.DebuggerTarget
> 2020-12-08 13:09:49.2951 Debug Setting 'NLog.LayoutRenderers.Wrappers.UppercaseLayoutRendererWrapper.uppercase' to 'true'
> 2020-12-08 13:09:49.3046 Debug Setting 'NLog.Targets.ColoredConsoleTarget.name' to 'console'
> 2020-12-08 13:09:49.3046 Debug Setting 'NLog.Targets.ColoredConsoleTarget.layout' to '${longdate} ${message} ${exception:format=tostring}'
> 2020-12-08 13:09:49.3046 Debug Setting 'NLog.LayoutRenderers.ExceptionLayoutRenderer.format' to 'tostring'
> 2020-12-08 13:09:49.3046 Info Adding target ColoredConsoleTarget(Name=console)
> 2020-12-08 13:09:49.3046 Debug Registered target console: NLog.Targets.ColoredConsoleTarget
> 2020-12-08 13:09:49.3055 Debug Setting 'NLog.LayoutRenderers.Wrappers.UppercaseLayoutRendererWrapper.uppercase' to 'true'
> 2020-12-08 13:09:49.3064 Debug Setting 'NLog.Targets.MailTarget.name' to 'infoMail'
> 2020-12-08 13:09:49.3064 Debug Setting 'NLog.Targets.MailTarget.smtpServer' to 'smtp.163.com'
> 2020-12-08 13:09:49.3064 Debug Setting 'NLog.Targets.MailTarget.smtpPort' to '25'
> 2020-12-08 13:09:49.3064 Debug Setting 'NLog.Targets.MailTarget.smtpAuthentication' to 'Basic'
> 2020-12-08 13:09:49.3079 Debug Setting 'NLog.Targets.MailTarget.smtpUserName' to 'deno@163.com'
> 2020-12-08 13:09:49.3079 Debug Setting 'NLog.Targets.MailTarget.smtpPassword' to 'demo'
> 2020-12-08 13:09:49.3082 Debug Setting 'NLog.Targets.MailTarget.enableSsl' to 'true'
> 2020-12-08 13:09:49.3082 Debug Setting 'NLog.Targets.MailTarget.addNewLines' to 'true'
> 2020-12-08 13:09:49.3082 Debug Setting 'NLog.Targets.MailTarget.from' to 'demo@163.com'
> 2020-12-08 13:09:49.3082 Debug Setting 'NLog.Targets.MailTarget.to' to 'demo@qq.com'
> 2020-12-08 13:09:49.3082 Debug Setting 'NLog.Targets.MailTarget.subject' to 'Project Exception Mail'
> 2020-12-08 13:09:49.3082 Debug Setting 'NLog.Targets.MailTarget.header' to '*********************'
> 2020-12-08 13:09:49.3082 Debug Setting 'NLog.Targets.MailTarget.body' to '${longdate} | ${message} '
> 2020-12-08 13:09:49.3092 Debug Setting 'NLog.Targets.MailTarget.footer' to '*********************'
> 2020-12-08 13:09:49.3092 Info Adding target MailTarget(Name=infoMail)
> 2020-12-08 13:09:49.3092 Debug Registered target infoMail: NLog.Targets.MailTarget
> 2020-12-08 13:09:49.3286 Debug --- NLog configuration dump ---
> 2020-12-08 13:09:49.3286 Debug Targets:
> 2020-12-08 13:09:49.3298 Debug File Target[log_file]
> 2020-12-08 13:09:49.3298 Debug Debugger Target[debugger]
> 2020-12-08 13:09:49.3298 Debug ColoredConsole Target[console]
> 2020-12-08 13:09:49.3298 Debug Mail Target[infoMail]
> 2020-12-08 13:09:49.3298 Debug Rules:
> 2020-12-08 13:09:49.3320 Debug logNamePattern: (:All) levels: [ Info ] appendTo: [ console ]
> 2020-12-08 13:09:49.3320 Debug logNamePattern: (:All) levels: [ Error ] appendTo: [ log_file ]
> 2020-12-08 13:09:49.3321 Debug logNamePattern: (:All) levels: [ Debug ] appendTo: [ log_file ]
> 2020-12-08 13:09:49.3321 Debug logNamePattern: (:All) levels: [ Fatal ] appendTo: [ log_file ]
> 2020-12-08 13:09:49.3321 Debug logNamePattern: (:All) levels: [ Warn ] appendTo: [ log_file ]
> 2020-12-08 13:09:49.3321 Debug --- End of NLog configuration dump ---
> 2020-12-08 13:09:49.3341 Info LogManager.ThrowExceptions = true can crash the application! Use only for unit-testing and last resort troubleshooting.
> 2020-12-08 13:09:49.3403 Info Validating config: TargetNames=console, log_file, ConfigItems=62, FilePath=/app/NLog.config
> 2020-12-08 13:09:49.3435 Debug Unused target checking is started... Rule Count: 5, Target Count: 4
> 2020-12-08 13:09:49.3506 Warn Unused target detected. Add a rule for this target to the configuration. TargetName: debugger
> 2020-12-08 13:09:49.3506 Warn Unused target detected. Add a rule for this target to the configuration. TargetName: infoMail
> 2020-12-08 13:09:49.3506 Debug Unused target checking is completed. Total Rule Count: 5, Total Target Count: 4, Unused Target Count: 2
> 2020-12-08 13:09:49.3618 Debug Debugger(Name=debugger): System.Diagnostics.Debugger.IsLogging()==false. Output has been disabled.
> 2020-12-08 13:09:49.3662 Info Configuration initialized.
> 2020-12-08 13:09:49.3831 Info NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c. File version: 4.7.5.12092. Product version: 4.7.5+ed343d5690d9c97a96fcff430e240e2d7c31a8d7. GlobalAssemblyCache: False
> 2020-12-08 13:09:49.3863 Debug Targets for SHX.AdminWeb.Controllers.HomeController by level:
> 2020-12-08 13:09:49.3863 Debug Trace =>
> 2020-12-08 13:09:49.3863 Debug Debug => log_file
> 2020-12-08 13:09:49.3863 Debug Info => console
> 2020-12-08 13:09:49.3863 Debug Warn => log_file
> 2020-12-08 13:09:49.3863 Debug Error => log_file
> 2020-12-08 13:09:49.3863 Debug Fatal => log_file
> 2020-12-08 13:09:49.3901 xxx 

-

**Comment by snakefoot** [comment]
Can see this configuration:

```
2020-12-08 13:09:49.3863 Debug Trace =>
2020-12-08 13:09:49.3863 Debug Debug => log_file
2020-12-08 13:09:49.3863 Debug Info => console
2020-12-08 13:09:49.3863 Debug Warn => log_file
2020-12-08 13:09:49.3863 Debug Error => log_file
2020-12-08 13:09:49.3863 Debug Fatal => log_file
```

What loglevel are you using when calling the NLog Logger? (Notice that Info-events are only written to "console" and not "log_file")

No idea if using MEL-ILogger or the the raw NLog Logger. But if using MEL-ILogger, then you must also be aware of the  loglevel-filtering configured in appsetting.json (along with appsettings.production.json). See also https://github.com/NLog/NLog.Web/wiki/Missing-trace%5Cdebug-logs-in-ASP.NET-Core-3%3F
