### ISSUE TITLE
Is AppSetting Layout Renderer working for archiving options?

### ISSUE THREAD

**Issue by AgilityCIS-Carlosb** [NLog/NLog#4195]
Hi,
I have the below config for NLog v4.7.5.

```xml
<appSettings>
    <add key="NLogMaxLogFileSize" value="5000"/>
    <add key="NLogMaxArchiveDays" value="30"/>
</appSettings>
```

```xml
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <extensions>
        <add assembly="Microsoft.ApplicationInsights.NLogTarget" />
    </extensions>
    <targets>
      <target name="file" 
              xsi:type="File" 
              fileName="${basedir}/App_Data/logs/${date:format=yyyy-MM-dd}/${level}.log" 
              layout="${newline}${longdate}|${uppercase:${level}}|${logger}|${message}|${exception:format=tostring}"
              archiveFileName="${basedir}/App_Data/logs/${date:format=yyyy-MM-dd}/${level}_{#}.log"
              archiveNumbering="Sequence"
              archiveAboveSize="${appsetting:item=NLogMaxLogFileSize}"
              maxArchiveDays="${appsetting:item=NLogMaxArchiveDays}" />
      <target name="debugger" 
              xsi:type="Debugger" 
              layout="${newline}${logger}::${message}::${exception:format=tostring}" />
    </targets>
    <rules>
      <logger name="*" minlevel="Trace" writeTo="file" />
      <logger name="*" minlevel="Trace" writeTo="debugger" />
    </rules>
  </nlog>
```

Which is not working. The appsetting layout renderer format comes from https://github.com/NLog/NLog/wiki/AppSetting-Layout-Renderer
However if I change the values for `archiveAboveSize` and `maxArchiveDays` to a number NLog starts logging correctly.

Does every option allow the use of Layout renderers? 

Thanks

**Comment by 304NotModified** [comment]
As you see on https://github.com/NLog/NLog/wiki/File-target#configuration-syntax,

archiveAboveSize and maxArchiveDays aren't of type Layout. So layouts cant be used. 

You could still use:

- const variables, like `${myvar}`, as those will be applied when evaluating the config. You can't change the runtime. See  https://github.com/NLog/NLog/wiki/Configuration-file#variables
- change the settings in code, see https://github.com/NLog/NLog/wiki/Configure-from-code

**Comment by AgilityCIS-Carlosb** [comment]
@304NotModified Thanks for pointing me into the right direction, I finally went with configuring it from code. 
Cheers
