### ISSUE TITLE
Environment Variables on Configuration

### ISSUE THREAD

**Issue by MartinSGill** [NLog/NLog#4199]
I was expecting the following snippet to work, but I get an exception saying that the "port" is not of the required value. In this case I'm using the syslog extension.

Is this expected behaviour or a possible bug in nlog, or a bug in syslog extension?

```xml
      <messageSend>
        <protocol>TCP</protocol>
        <tcp>
          <server>${PaperServer}</server>
          <port>${PaperPort}</port>
          <tls>
            <enabled>true</enabled>
          </tls>
        </tcp>
      </messageSend>
```

When variables are defined as:

```xml
  <variable name="PaperServer" value="localhost"/>
  <variable name="PaperPort" value="514"/>
```

The config snippet above appears to work correctly,

Yet when defined as:

```xml
  <variable name="PaperServer" value="${environment:PAPER_HOST:default=localhost}"/>
  <variable name="PaperPort" value="${environment:PAPER_PORT:default=514}"/>
```

I get an exception:

```
 NLog.NLogConfigurationException: Error when setting property 'Port' on TcpConfig
```

**Comment by snakefoot** [comment]
Yes the NLog-Configuration-Parser is doing some magic, when using `${PaperServer}.`

This magic not activated when using `${environment:PAPER_PORT:default=514}` or `${var:PaperServer}`. It requires that the NLog-Target property is of type `NLog.Layout` (instead of `int` or `string`).

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, please let us know!
