### ISSUE TITLE
Concurrent Access in File Target fails

### ISSUE THREAD

**Issue by Xharze** [NLog/NLog#42]
<p>Reported in the forum at post: http://nlog-project.org/forum.html#nabble-tc1685753|a1685753</p>
<p>&nbsp;</p>
<p>I am attempting to use NLog in a multiple app domain process.</p>
<p>&nbsp;</p>
<p>The log file has the following target</p>
<p>&nbsp;</p>
<p>----------------------------------------------</p>
<p> &lt;target name=&quot;DefaultLogFile&quot;</p>
<p>&nbsp;</p>
<p> concurrentWriteAttemptDelay=&quot;1&quot;</p>
<p> concurrentWrites=&quot;true&quot;</p>
<p> concurrentWriteAttempts = &quot;10&quot;</p>
<p>&nbsp;</p>
<p> keepFileOpen=&quot;false&quot;</p>
<p> autoFlush=&quot;false&quot;</p>
<p>&nbsp;</p>
<p> deleteOldFileOnStartup=&quot;true&quot;</p>
<p>&nbsp;</p>
<p> xsi:type=&quot;File&quot;</p>
<p> layout=&quot;${level:uppercase=true} ${message}&quot; </p>
<p> fileName=&quot;${basedir}/Log.log&quot;</p>
<p> /&gt;</p>
<p>-----------------------------------------------</p>
<p>&nbsp;</p>
<p>The nlog internal trace file produces the following exception.</p>
<p>&nbsp;</p>
<p>-----------------------------------------------</p>
<p>2008-06-02 11:34:05.7497 Error Target exception: System.IO.FileLoadException: The process cannot access the file because it is being used by another process. (Exception from HRESULT: 0x80070020)</p>
<p> at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)</p>
<p> at NLog.Internal.FileAppenders.BaseFileAppender.WindowsCreateFile(String fileName, Boolean allowConcurrentWrite)</p>
<p> at NLog.Internal.FileAppenders.BaseFileAppender.TryCreateFileStream(Boolean allowConcurrentWrite)</p>
<p> at NLog.Internal.FileAppenders.BaseFileAppender.CreateFileStream(Boolean allowConcurrentWrite)</p>
<p> at NLog.Internal.FileAppenders.RetryingMultiProcessFileAppender.Write(Byte[] bytes)</p>
<p> at NLog.Targets.FileTarget.WriteToFile(String fileName, Byte[] bytes, Boolean justData)</p>
<p> at NLog.Targets.FileTarget.Write(LogEventInfo logEvent)</p>
<p> at NLog.LoggerImpl.Write(Type loggerType, TargetWithFilterChain targets, LogEventInfo logEvent, LogFactory factory)</p>
<p>----------------------------------------------------------</p>
<p>&nbsp;</p>
<p>The following line in RetryingMultiProcessFileAppender.Write(byte[] bytes) is suspect</p>
<p>&nbsp;</p>
<p> using (FileStream fileStream = CreateFileStream(false))</p>
<p>&nbsp;</p>
<p>If the above value is true rather than false then no exceptions occur in the internal trace file.</p>
<p>&nbsp;</p>
<p>The false value means that in the BaseFileAppender.WindowsCreateFile() method it will end up opening the file without the FILE_SHARE_WRITE share value set. Thus it cannot succeed with other open attempts.</p>
<p>&nbsp;</p>
<p>So the question would be is the something in the above target that is inappropriate for current access? Nothing that I have tried alters that Retrying class is in use.</p>

Comments:
deleteOldFileOnStartup options

Reported in the forum at post: http://nlog-project.org/forum.html#nabble-tc1686002|a1686002

Hi

It seems that deleteOldFileOnStartup somehow make logger to erase fist few lines from the file including for example header.

This is a config file

<target name="fileFormOverwrite" xsi:type="File" fileName="${logDirectory}/${processname}.log"
layout="${genericLayout}"
deleteOldFileOnStartup="true"
concurrentWrites="false"
header="+++++++++++++"/>

As long as deleteOldFileOnStartup is true, the +++++++++++++ never appears in the log file (along with some of the program info which is logged by Main().

Here are examples of log file

deleteOldFileOnStartup="false"

+++++++++++++
22/10/2008 11:32:48| INFO| 10|--------------------------------------------- 
22/10/2008 11:32:48| INFO| 10|RB: App starts 
22/10/2008 11:32:48| INFO| 10|--------------------------------------------- 
22/10/2008 11:32:50| INFO| 10|RB: DropDownList: executing prSelect 
22/10/2008 11:32:51| INFO| 10|RB: DropDownList: executing prProcessView_Select
...

deleteOldFileOnStartup="true"

22/10/2008 11:34:08| INFO| 10|RB: DropDownList: executing prSelect 
22/10/2008 11:34:08| INFO| 10|RB: DropDownList: executing prProcessView_Select 
....

Cheers, Igor

NLogBugTroll wrote Oct 6 2009 at 10:02 PM

Testing indicates that the following option is what impacts this.

deleteOldFileOnStartup="true"

Although conceptually easy to understand why this causes a problem it means that functionality is lost particularly when it is AppDomains rather than actual different processes in use

**Comment by 304NotModified** [comment]
@Xharze as multi process writing is not supported (see #100) - this issue can also be 'nonfix'd? (and closed)?

**Comment by snakefoot** [comment]
Resolved by #1771
