### ISSUE TITLE
Archive existing log file on application start up

### ISSUE THREAD

**Issue by contento** [NLog/NLog#420]
I've been using deleteOldFileOnStartup="true", especially in Debug mode, to avoid long files. 
The issue with this approach is that I lose the previous log, which could contain valuable information.

I believe we'd require some parameters like:

      archiveEvery="Run|Start|Execution"  
      archiveNumbering="Date"
      archiveFormat="yyyyMMddHHmmss"
      archiveFileName="${logFolder}/archive/${logFilename}.{#}.log"

See: http://stackoverflow.com/questions/25411489/nlog-1-log-per-application-run-and-archive-old-logs

**Comment by 304NotModified** [comment]
archiveOldFileOnStartup had been added to NLog 4.0, this this one can be closed
