### ISSUE TITLE
.WithProperty() only logs structure of anonymous types 

### ISSUE THREAD

**Issue by maciekmw** [NLog/NLog#4200]
Hello,

I'm using nlog 4.7.6

.WithProperty() only logs structure of anonymous types, for example:
```
var d1 = new { Name = "foo", Surname = "Bar" };
_logger.WithProperty("test", d1).Info("anonymous test");

var d2 = new TestClass { Name = "foo", Surname = "Bar" };
_logger.WithProperty("test", d2).Info("TestClass test");
```

that results in:
```
2020-12-10 13:29:40.5961 Info -> MWAM.FinOps.MWControlPanel.DataCollector.Program -> anonymous test -> test={ Name = foo, Surname = Bar } |
2020-12-10 13:29:40.9028 Info -> MWAM.FinOps.MWControlPanel.DataCollector.Program -> TestClass test -> test=MWAM.FinOps.MWControlPanel.DataCollector.Program+TestClass |
```

and my config is:
```
<target xsi:type="File" name="logfile" fileName="C:\logs\nlog.log" layout="${longdate} ${level} -> ${logger} -> ${message} -> ${all-event-properties} |${exception:format=tostring}" />
```

as you can see, anonymous object is correctly logged considering whole structure but the actuall class only has the type name logged.

can anyone explain why is this and how to work around it?

thanks

**Comment by snakefoot** [comment]
`${all-event-properties}` will call `object.ToString()` and if you override the ToString-method on your TestClass then it will do the expected.

Maybe `${all-event-properties}` could be extended to support the option `Format=@`. Pull-requests are welcome

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, please let us know!
