### ISSUE TITLE
Value set using MappedDiagnosticsLogicalContext is getting cleared and not getting logged

### ISSUE THREAD

**Issue by myschandru** [NLog/NLog#4204]
Hi! Thanks for reporting this bug! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

For .NET Core users, please check the platform support: https://github.com/NLog/NLog/wiki/platform-support

**NLog version**: (e.g. 4.4.13)

**Platform**:  .NET Core 3.1

**Current NLog config** (xml or C#, if relevant)

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      internalLogLevel="Trace"
      internalLogFile="Logs/internallog.txt">
	<targets>
		<target name="logfile" xsi:type="File"
				fileName="Logs/${shortdate}_logfile.txt" archiveAboveSize="5000000"
				layout="${longdate} ${level:uppercase=true} ${mdlc:item=UserName} ${message}"/>
	</targets>
	<rules>
		<logger name="*" minlevel="Debug" writeTo="logfile" />
	</rules>
</nlog>

```

In ASP.Core 3.1 AuthorizationHandler, once user is authorized, I am setting the user name using MappedDiagnosticsLogicalContext like below:

    MappedDiagnosticsLogicalContext.Set("UserName", userName);

And expecting UserName be available in all log messages, however UserName is getting only logged in the AuthorizationHandler but not in any other log messages logged in subsequent code.

- What is the expected result?
UserName has to be logged along with all the log messages which will be in several asynchronous threads after setting MappedDiagnosticsLogicalContext for the given request.

- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)? yes. it doesn't give any details about the issue.
- Please post full exception details (message, stacktrace, inner exceptions)
- Are there any workarounds? no
- Is there a version in which it did work? no
- Can you help us by writing an unit test? no

**Comment by snakefoot** [comment]
If you can make a unit-test that reproduces the case, then I will be happy to look at it.

**Comment by 304NotModified** [comment]
Hi, 

I guess there is another thread involved. 

But as this is in asp.net core handler, I would recommend to use `${aspnet-item}`


example:

```
httpContext.Items["myvariable"] = 123;
```

config: 
```
${aspnet-item:variable=myvariable} - produces "123"
```

**Comment by myschandru** [comment]
I used httpContext and it worked for me. Thank you for the response.
