### ISSUE TITLE
NLog local vs GAC - how to force NLog to pick local version instead of going to GAC?

### ISSUE THREAD

**Issue by muditt-humanforce** [NLog/NLog#4208]
Hi,

I have a question around how to force NLog reference to pick from local folder instead of GAC.

We used NLog 4.7.4 from nuget, in our product that gets deployed to customers' servers. With this upgrade we found it was giving an error - NLog.SetProperty() method not found. On further troubleshooting we found that NLog 4.3.x (or below) was available on the server's GAC and our website was picking that dll from GAC instead of picking from local folder. As GAC's NLog.dll was an old version, it complained about method not available.

My question - how can we force our solution to pick NLog from local folder instead of going to GAC? We already tried mentioning dependentAssembly/bindingRedirect in web.config to this version, but then it complained about not able to match assembly manifest.

I did double check that NLog reference property "specific version" was selected as true, but still it was trying to execute with old version and hence breaking at runtime.

Thanks
Mudit

**Comment by snakefoot** [comment]
No sadly enough the GAC will always win, when using strong-version assembly and .NetFramework (instead of .NetCore).

Workaround could be to unregister NLog from the GAC at deployment. But it might break another application on the machine depending on NLog being in the GAC.

**Comment by snakefoot** [comment]
Another work-around is to use ILMerge to merge the NLog-assembly into your application.

**Comment by 304NotModified** [comment]
> Yet another work-around is to compile your own version of NLog without strong-naming

Yes, that's a good one. But you could still use other external nuget packages?

**Comment by 304NotModified** [comment]
See also https://stackoverflow.com/questions/1606867/how-to-prevent-a-net-application-from-loading-referencing-an-assembly-from-the

**Comment by 304NotModified** [comment]
Maybe reassign the strong name afterwards (of the dll, no compile needed) could work. See http://www.geekzilla.co.uk/ViewCE64BEF3-51A6-4F1C-90C9-6A76B015C9FB.htm

**Comment by 304NotModified** [comment]
Lady but not least, NLog takes semver serious, so it's also possible to update the NLog version in the GAC.

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, please let us know!
