### ISSUE TITLE
.NET Core ILogger rules don't work for anything under "Microsoft.*"

### ISSUE THREAD

**Issue by Kaelum** [NLog/NLog#4215]
**NLog version**: All versions, using the latest from NuGet (4.7.6)

**Platform**: .NET Core 3

**Current NLog config** (xml or C#, if relevant)

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog
	xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	autoReload="true"
	throwExceptions="true"
	internalLogFile="./logs/NLog-internal.log"
	internalLogLevel="Trace"
>
	<targets>
		<target
			name="logfile"
			xsi:type="File"
			fileName="./logs/[snip].WebApi.log"
			layout="${longdate:universalTime=false} ${pad:padding=4:inner=${threadid}} [${pad:padding=-5:inner=${level:uppercase=true}}] ${callsite}:line ${callsite-linenumber}${when:when='${message}' != '':inner=\: ${message}}${newline:when='${exception}' != ''}${exception:format=toString,Data:exceptionDataSeparator=\r\n}"
			archiveNumbering="DateAndSequence"
			archiveEvery="Day"
			archiveAboveSize="10485760"
			archiveDateFormat="yyyy-MM-dd"
			maxArchiveFiles="93"
			keepFileOpen="true"
		/>

		<target
			name="logconsole"
			xsi:type="ColoredConsole"
			layout="${message:when='${message}' != ''}${newline:when='${exception}' != ''}${exception:format=toString,Data:exceptionDataSeparator=\r\n}"
		/>

		<target
			name="logcontainer"
			xsi:type="ColoredConsole"
			layout="${longdate:universalTime=false} ${pad:padding=4:inner=${threadid}} [${pad:padding=-5:inner=${level:uppercase=true}}] ${callsite}:line ${callsite-linenumber}${when:when='${message}' != '':inner=\: ${message}}${newline:when='${exception}' != ''}${exception:format=toString,Data:exceptionDataSeparator=\r\n}"
		/>
	</targets>

	<rules>
		<logger name="Microsoft.AspNetCore.Hosting.GenericWebHostService.*" minLevel="Info" writeTo="logconsole,logfile" final="true" />
		<logger name="Microsoft.AspNetCore.Server.Kestrel.Core.Internal.*" minLevel="Info" writeTo="logconsole,logfile" final="true" />
		<logger name="Microsoft.Extensions.Hosting.Internal.ConsoleLifetime.*" minLevel="Info" writeTo="logconsole,logfile" final="true" />
		<logger name="[snip].WebApi.Program*" minLevel="Debug" writeTo="logconsole,logfile" final="true" />
		<logger name="[snip].WebApi.*" minLevel="Info" writeTo="logconsole,logfile" final="true" />
		<logger name="[snip].Services.*" minLevel="Debug" writeTo="logconsole,logfile" final="true" />
		<logger name="*" minLevel="Warn" writeTo="logconsole,logfile" final="true" />
	</rules>
</nlog>
```

Only the `<rules>` that do not begin with "Microsoft" work.  While debugging, I can see that all of the rules are loaded correctly, but none of the rules that begin with "Microsoft" are functional.  The "\*" rule ends up be the controlling factor for all "Microsoft.*" logging.  I haven't been able to find anything discussing this behavior, so I am assuming that it is a bug.

Additionally, when I turned on the InternalLogFile (as above), the file is not created.

**Comment by 304NotModified** [comment]
Please check https://github.com/NLog/NLog.Web/wiki/Missing-trace%5Cdebug-logs-in-ASP.NET-Core-3%3F

**Comment by 304NotModified** [comment]
For the internal logger, the base directory could be different AFAIK - and so also the write permissions. Please check with an absolute path.

**Comment by Kaelum** [comment]
I have the recommended overrides to set everything to "Trace" in the "Logging" settings, but I'll check to see if that is broken in .NET Core after the holidays.  I'll look into the what you are saying about the folder, but I am 99.999% certain that what you are saying is impossible in our application, unless NLog is completely ignoring the CurrentDirectory, and choosing folders on its own.

**Comment by 304NotModified** [comment]
I'm doubting about my internal logger path statement (can't find the issue). But please do test with an absolute path.

**Comment by Kaelum** [comment]
@304NotModified Ok, I found that NLog is using the project folder as the current folder when the application is executed from Visual Studio 2019, when it should be using the build folder (under bin).  I've just come back from vacation, so I haven't had time to look at what Microsoft is doing internally, but I do know that all of my settings are correct, as I could see them when running the application in DEBUG mode.
