### ISSUE TITLE
Why does the filtering rules only match logger name and not active method?

### ISSUE THREAD

**Issue by Kaelum** [NLog/NLog#4231]
NLog is logging items to the log file when the configuration explicitly states that it should only log to the console.

**NLog version**: 4.7.6

**Platform**: .NET Core 3.1

**Current NLog config**:

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog
	xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	autoReload="true"
	throwExceptions="true"
	internalLogFile="logs/NLog-internal.log"
	internalLogLevel="Trace"
>
	<targets>
		<target
			name="logfile"
			xsi:type="File"
			fileName="logs/NLogTest.P${processid}.log"
			layout="${longdate:universalTime=false} ${pad:padding=4:inner=${threadid}} [${pad:padding=-5:inner=${level:uppercase=true}}] ${callsite}:line ${callsite-linenumber}${when:when='${message}' != '':inner=\: ${message}}${newline:when='${exception}' != ''}${exception:format=toString,Data:exceptionDataSeparator=\r\n}"
			archiveNumbering="DateAndSequence"
			archiveEvery="Day"
			archiveAboveSize="10485760"
			archiveDateFormat="yyyy-MM-dd"
			maxArchiveFiles="93"
			keepFileOpen="true"
		/>

		<target
			name="logconsole"
			xsi:type="ColoredConsole"
			layout="${message:when='${message}' != ''}${newline:when='${exception}' != ''}${exception:format=toString,Data:exceptionDataSeparator=\r\n}"
		/>

		<target
			name="logcontainer"
			xsi:type="ColoredConsole"
			layout="${longdate:universalTime=false} ${pad:padding=4:inner=${threadid}} [${pad:padding=-5:inner=${level:uppercase=true}}] ${callsite}:line ${callsite-linenumber}${when:when='${message}' != '':inner=\: ${message}}${newline:when='${exception}' != ''}${exception:format=toString,Data:exceptionDataSeparator=\r\n}"
		/>
	</targets>

	<rules>
		<logger name="NLogTest.Program.Main" minLevel="Debug" writeTo="logconsole" final="true" />
		<logger name="NLogTest.Program*" minLevel="Debug" writeTo="logconsole,logfile" final="true" />
		<logger name="NLogTest.*" minLevel="Info" writeTo="logconsole,logfile" final="true" />
		<logger name="*" minLevel="Warn" writeTo="logconsole,logfile" final="true" />
	</rules>
</nlog>
```

- What is the current result?
Everything is logged to the log file.

- What is the expected result?
Nothing in the Main() method should be logged to the log file.

Here is a test application that demonstrates the issue: [NLogTest.zip](https://github.com/NLog/NLog/files/5778910/NLogTest.zip)

**Comment by snakefoot** [comment]
You can look at the Logger-object to see what the rules has configured. The Logger is named `"NLogTest.Program"`

This matches these rules:

```xml
		<logger name="NLogTest.Program*" minLevel="Debug" writeTo="logconsole,logfile" final="true" />
		<logger name="NLogTest.*" minLevel="Info" writeTo="logconsole,logfile" final="true" />
		<logger name="*" minLevel="Warn" writeTo="logconsole,logfile" final="true" />
```

Where it says all logging with `minLevel="Debug"` should be written to `logfile`. What do you expect?

**Comment by Kaelum** [comment]
@snakefoot that is not correct.  Every single rule has `final="true"`, thus the first match should end any further matching.

**Comment by snakefoot** [comment]
And it matches the first rule, which dictates minLevel=Debug should writeTo logfile


Sent from my Sony Xperia


---- William Bosacker wrote ----


@snakefoot<https://github.com/snakefoot> that is not correct. Every single rule has final="true", thus the first match should end any further matching.

**Comment by Kaelum** [comment]
@snakefoot the first rule is:

```xml
<logger name="NLogTest.Program.Main" minLevel="Debug" writeTo="logconsole" final="true" />
```

**Comment by snakefoot** [comment]
Think you are hoping GetCurrentClassLogger will include the method-name (Main) . But the Logger-name only includes the class-name so only "NLogTest.Program"


Sent from my Sony Xperia


---- William Bosacker wrote ----


@snakefoot<https://github.com/snakefoot> that is not correct. Every single rule has final="true", thus the first match should end any further matching.

**Comment by Kaelum** [comment]
That is not defined in the [Configuration file / Rules](https://github.com/nlog/nlog/wiki/Configuration-file#rules) documentation, and `${callsite}` clearly includes the method name.

**Comment by snakefoot** [comment]
Callsite and Logger-Name are two different things


Logger-Name provides super fast filtering using rules.


Callsite allows capture of stacktrace for the logevent but introduces a huge performance hit.


You are only using Callsite in the layout for logging output formatting.


It is recommended to use the Logger name for filtering. So maybe just have the Main-method in the Program-class and create another class for the other logic?


Sent from my Sony Xperia


---- William Bosacker wrote ----


That is not defined in the Configuration file / Rules<https://github.com/nlog/nlog/wiki/Configuration-file#rules> documentation, and ${callsite} clearly includes the method name.

**Comment by Kaelum** [comment]
Again, this is not defined in the [Configuration file / Rules](https://github.com/nlog/nlog/wiki/Configuration-file#rules) documentation.  If the documentation is wrong, then it needs to be updated.  Until then, NLog is not working as documented.

**Comment by snakefoot** [comment]
Please you show me the paragraph that says Callsite has special meaning in logging rule filtering? I only see it talks about using  Logger-Name


Sent from my Sony Xperia


---- William Bosacker wrote ----


Again, this is not defined in the Configuration file / Rules<https://github.com/nlog/nlog/wiki/Configuration-file#rules> documentation. If the documentation is wrong, then it needs to be updated. Until then, NLog is not working as documented.

**Comment by Kaelum** [comment]
@snakefoot you are asking the wrong question.  Show me where it states that the method name is not part of the filter pattern.

**Comment by snakefoot** [comment]
Think it would be a bad approach to list all types of details that are NOT included in the name-pattern for the **logger=** -parameter. And just focus on the fact that **logger=** matches the logger-name and nothing else.

You are welcome to update the wiki and emphasis that **logger=** only matches logger-name.

**Comment by Kaelum** [comment]
Where is `logger-name` defined?  There should be a clear list of exactly what we are matching against.  I have read through all of the documentation, which is scattered all over the place, and what can be found is overly ambiguous.  Developers need to know exactly what we're working with.  Asking us to guess, means that the documentation is not serving its purpose.

Every single aspect of the configuration file should branch from a single page, and go into every minute detail, but pages are scattered everywhere and the detail is severely lacking.  You would think that the configuration documentation would branch off of [Configuration file](https://github.com/nlog/nlog/wiki/Configuration-file), but it doesn't.  And what can be found is incomplete.

I'm not trying to be rude or anything, but I can guarantee you that everyone who tries to this documentation is overly frustrated.

**Comment by snakefoot** [comment]
I guess I have been using NLog for too long. But I find it logical that `<logger name="blah blah">` means "matching any logger with name blah blah".

Again you are more than welcome to improve the Wiki and reduce frustation, since it is community project so every helping hand is welcome.

You can also just present paragraphs that are confusing to read, and then we can try together to improve them.

**Comment by Kaelum** [comment]
That is a perfect example of what I am saying.  What does `"matching any logger with name blah blah"` mean?  Nowhere in the documentation is this defined.  The only possible way for anyone to find this information, would be for them to spend weeks looking at the source code.

In all honesty, I'm considering moving on and using log4net at this point.  I know this is a community project, but if the documentation is incomplete, then the product is incomplete, and we're not allowed to use unfinished/beta software.

**Comment by snakefoot** [comment]
Think you have been cheated by the "magic" in `LogManager.GetCurrentClassLogger()`.

The pure way to create a Logger-object is to called `LogManager.GetLogger("blah blah")`, and the  input-name becomes the name of the Logger. The name of the Logger is then used to dicover what target to writeTo.

Looks like NLog and log4net is similar in the [logger-name filtering](https://stackoverflow.com/a/2024103/193178). Just have different syntax.

**Comment by Kaelum** [comment]
I had been using `GetLogger()` for years.  However, that doesn't explain what we are pattern matching in `<logger name="<matching pattern>" />`.  There is nothing that explicitly states what is being matched.  You can't assume that we know what is in your head, as we don't.  What are we matching to?  If its ONLY the namespace.class, why is that not in the documentation?

Anywho, I've wasted too much time on this, and even with your current explanations, some things are not being logged (i.e. anything starting with Microsoft) if the minLevel of the matching pattern is lower than the "*" log level.

**Comment by snakefoot** [comment]
>  (i.e. anything starting with Microsoft) if the minLevel of the matching pattern is lower than the "*" log level.

That is probably caused by the Microsoft Extension Logging (MEL) filtering configuration in `appsettings.json` that has first priority See also https://github.com/NLog/NLog.Web/wiki/Missing-trace%5Cdebug-logs-in-ASP.NET-Core-3%3F

There have been thoughts about changing NLog integration with MEL, so NLog injects its own MEL-LoggerFactory and replace the Microsoft-Loggerfactory. Because users gets confused by having 2 log-filtering-systems. See also https://github.com/NLog/NLog.Web/issues/235

**Comment by Kaelum** [comment]
Ok, I think I've figured out the issue, which appears to be confirmed by what you said above.

1. The pattern that we are matching with `<logger name="pattern">` has absolutely nothing to do with the namespace or the class name, correct?  It is matching the `log-name` in `LogManager.GetLogger("log-name")`, correct?
2. `LogManager.GetCurrentClassLogger()` is simply passing `<namespace>.<class>` as the `log-name`, correct?
3. This whole `<namespace>.<class>` thing is a convention, and it has absolutely nothing at all to do with the actual logging location, correct?

If so, then that other thread is absolutely correct.  Using, the `ILoggingBuilder.AddNlog()` extension is a very bad idea, as it conflicts with the Microsoft ILogger system at a fundamental level.

**Comment by snakefoot** [comment]
> The pattern that we are matching with <logger name="pattern"> has absolutely nothing to do with the namespace or the class name, correct?

Not directly unless the Logger-object has been created using `LogManager.GetCurrentClassLogger()` where the name will become "NameSpace.ClassName".

> It is matching the log-name in LogManager.GetLogger("log-name"), correct?

Yes ` <logger name="pattern">` will match against the input-name when calling `LogManager.GetLogger`

> LogManager.GetCurrentClassLogger() is simply passing <namespace>.<class> as the log-name, correct?

Yes `LogManager.GetCurrentClassLogger()` generates a logger-name based the context. Ex. "NameSpace.ClassName".

> This whole <namespace>.<class> thing is a convention, and it has absolutely nothing at all to do with the actual logging location, correct?

Yes one usually crerates a single Logger-object for a single class, and when using this Logger-object the name will not change based on class-method the Logger is used.

Have tried to update the [Rules](https://github.com/nlog/nlog/wiki/Configuration-file#rules)-section to be more clear about this. Any input for improving this further is welcome.

**Comment by Kaelum** [comment]
Well, my last post is a good start.  It has the basics that everyone needs to know.  I would also make sure that this information is somehow explicitly linked to the `NLog.Extensions.Logging` assembly, as that would quell a lot of anguish.  At the very least, there should be link in the Intellisense tool-tip to this information, and link to the source code for this extension as well, for those who need to write their own.

Thank you for clearing that up, as we now need to have some discussions of whether or not we should go back to log4net.  The only reason that we switched was because of `ILoggingBuilder.AddNlog()` extension, and the appearance that the filtering was performed on the actual location in code.  log4net gave us a lot of flexibility in other ways, and seemed to have better performance.

At least you have a good starting point for the documentation now, as those are the major points that are missing.  When I have the time to get back to this, I need to see what I have available to me from the Microsoft ILogger, as I'll need to create a system that is similar to what I was originally describing.  We've already created a custom IHost system, so ILogger should be next.

**Comment by snakefoot** [comment]
>  Using, the ILoggingBuilder.AddNlog() extension is a very bad idea, as it conflicts with the Microsoft ILogger system at a fundamental level

You can inject the `NLogLoggerFactory` like this for `IWebHostBuilder`:

```c#
        public static IWebHostBuilder UseNLogFactory(this IWebHostBuilder builder)
        {
            if (builder == null) throw new ArgumentNullException(nameof(builder));
            if (configureLogger == null) throw new ArgumentNullException(nameof(configureLogger));

            builder.ConfigureServices((context, collection) =>
            {
                collection.AddSingleton<ILoggerFactory>(services =>
                {
                    return new NLog.Extensions.Logging.NLogLoggerFactory();
                });
            });
            return builder;
        }
```

Or like this for IHostBuilder:

```c#
        public static IHostBuilder UseNLogFactory(
            this IHostBuilder builder, 
            ILogger logger = null, 
            bool dispose = false,
            LoggerProviderCollection providers = null)
        {
            if (builder == null) throw new ArgumentNullException(nameof(builder));

            builder.ConfigureServices((context, collection) =>
            {
                collection.AddSingleton<ILoggerFactory>(services =>
                {
                    return new NLog.Extensions.Logging.NLogLoggerFactory();
                });
            });

            return builder;
        }
```

Guess some extra boilerplate-logic is needed for hooking up `${configsetting} `and `${aspnet-renderers}`

**Comment by snakefoot** [comment]
Think people that use log4net on AspNetCore uses this nuget-package: https://www.nuget.org/packages/Microsoft.Extensions.Logging.Log4Net.AspNetCore/

Curious about your performance issues. NLog is usually 50 pct. faster than log4net with less allocation. But I guess if you are using default configuration for NLog FileTarget then it will be slow. Using `keepFileOpen="true" and concurrentWrites="false"` will fix that. See also https://github.com/NLog/NLog/wiki/Performance
