### ISSUE TITLE
After publication by the customer in IIS does not write logs

### ISSUE THREAD

**Issue by Amangeldi** [NLog/NLog#4239]
Hi! Thanks for reporting this bug! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

For .NET Core users, please check the platform support: https://github.com/NLog/NLog/wiki/platform-support

**NLog version**: 4.7.5

**Platform**: net5.0 /Blazor Server

**Current NLog config** (xml or C#, if relevant)

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="false"
      internalLogLevel="Off" internalLogFile="c:\temp\nlog-internal.log">

  <!-- optional, add some variables
  https://github.com/nlog/NLog/wiki/Configuration-file#variables
  -->
  <variable name="myvar" value="myvalue"/>

  <!--
  See https://github.com/nlog/nlog/wiki/Configuration-file
  for information on customizing logging rules and outputs.
   -->
  <targets>

    <!--
    add your targets here
    See https://github.com/nlog/NLog/wiki/Targets for possible targets.
    See https://github.com/nlog/NLog/wiki/Layout-Renderers for the possible layout renderers.
    -->

    <target xsi:type="File" name="f" fileName="${basedir}/logs/${shortdate}.log"
            layout="${longdate} ${uppercase:${level}} ${message}" />
  </targets>

  <rules>
    <!-- add your logging rules here -->

    <logger name="*" minlevel="Debug" writeTo="f" />
  </rules>
</nlog>

```

- What is the current result?
- After publishing the solution in my VS in IIS, the "logs" directory with the log file is created. But I cannot achieve the same result in the customer's VS.
CopyToOutputDirectory: Always
IIS_IUSRS permissions: full control
- Can you help us by writing an unit test?
- no

**Comment by snakefoot** [comment]
Sounds like NLog is working, and it is an environment issues. Think StackOverflow is a better place for diagnosing environment-issue.

You can try and enable the internal-logger from from code, and redirect the output to a location that is now to known:

- https://github.com/NLog/NLog/wiki/Internal-Logging#enabling-internal-logging-programmatically
- https://github.com/NLog/NLog/wiki/Logging-troubleshooting
