### ISSUE TITLE
${date} throws an error "not a valid month"

### ISSUE THREAD

**Issue by shilpaka** [NLog/NLog#424]
I have set up NLog to log to the Oracle database. Below is the configuration:

 target name="database" xsi:type="Database" keepConnection="true" useTransactions="true"
                  dbProvider="System.Data.OracleClient"
                      connectionString="Data Source=test;User ID=test;password=test;">
            commandText>BEGIN VIAONE_EXPRESS.PKG_EXPRESS_SCREENS.NLOG_P(:in_machine_name,:in_process_name,:in_process_id,:in_win32thread_id,:in_session_id,:in_request_id,:in_severity,:in_timestamp,:in_duration,:in_category,:in_identifier,:in_message); END;/commandText>
            parameter name="in_machine_name" layout="${machinename}"/>
            parameter name="in_process_name" layout="${processname}" />
            parameter name="in_process_id" layout="${processId}"/>
            parameter name="in_win32thread_id" layout="${threadId}" />
            parameter name="in_session_id" layout="${sessionId}" />
            parameter name="in_request_id" layout="${requestId}"/>
            parameter name="in_severity" layout="${level:uppercase=true}"/>
            parameter name="in_timestamp" layout="${date}"/>
            parameter name="in_duration" layout="${duration}"/>
            parameter name="in_category" layout="${category}"/>
            parameter name="in_identifier" layout="${identifier}"/>
            parameter name="in_message" layout="${message:exceptionSeparator=String:withException=true}"/> 
          /target>

I am passing ${date} in the "in_timestamp" parameter. My table Log has date as a datatype for column timestamp. When I try to run my app, I get a not a valid month exception.

Below is what the exception says:

System.Data.OracleClient.OracleException: ORA-01843: not a valid month
ORA-06512: at line 1

**Comment by 304NotModified** [comment]
I assume that this question is answered. If not, then just re-open the issue.
