### ISSUE TITLE
JsonLayout generates invalid Json if one of the attributes is longer than 512KB and mdlc or properties are used

### ISSUE THREAD

**Issue by oleglck** [NLog/NLog#4241]
Hi!

**NLog version**: 
4.7.6

**Platform**: .Net 4.8

**Current NLog config** (xml or C#, if relevant)

```xml
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    autoReload="true"
    throwConfigExceptions="true"
    internalLogFile="NLogInternal.log"
    internalLogLevel="Debug">

    <targets >
        <target name="jsonFile"
                xsi:type="File"
                fileName="log.txt">
            <layout xsi:type="JsonLayout" includeMdlc="true" includeAllProperties="true">
                <attribute name="time" layout="${longdate}" />
                <attribute name="message" layout="${message}" />
             </layout>
        </target>
    </targets>

    <rules>
        <logger name="*" minlevel="Info" writeTo="jsonFile" />
    </rules>
</nlog>
```

- What is the current result?
 log record with invalid Json
- What is the expected result?
 log record with valid Json
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
 Yes, but didn't find a reason 
- Please post full exception details (message, stacktrace, inner exceptions)
 N\A
- Are there any workarounds? yes/no
 no
- Is there a version in which it did work? 
 N\A
- Can you help us by writing an unit test?
No, but attached application in which the bug is reproduced:
[NLogJsonLayoutTest.zip](https://github.com/NLog/NLog/files/5818671/NLogJsonLayoutTest.zip)
Run app, 
check log.txt, 
the first log entry is invalid Json due to the mdlc property value and log property value not being serialized
```
..., "MdlcTestProperty": , "TestProperty":  }
```
the second log record is valid Json
```
..., "MdlcTestProperty": "33f333b4-39a8-42bc-b638-25a8796624d6", "TestProperty": "919c0583-1967-44bf-b3de-431d46dc967f" }
```
Some information found by debugging:
See JsonLayout.RenderJsonFormattedMessage method
```
 if (this.IncludeMdc)
      {
        foreach (string name in (IEnumerable<string>) MappedDiagnosticsContext.GetNames())
        {
          if (!string.IsNullOrEmpty(name))
          {
            object propertyValue = MappedDiagnosticsContext.GetObject(name);
            this.AppendJsonPropertyValue(name, propertyValue, (string) null, (IFormatProvider) null, CaptureType.Unknown, sb, sb.Length == length1);
```
sb.Length is greater than 512Kb if one of the attributes is longer than 512KB

AppendJsonPropertyValue > JsonConverter.SerializeObject>DefaultJsonSerializer.SerializeObjectWithReflection>
```
private bool SerializeObjectWithReflection(object value, StringBuilder destination, JsonSerializeOptions options, ref SingleItemOptimizedHashSet<object> objectsInPath, int depth)
        {
            int originalLength = destination.Length;
            if (originalLength > MaxJsonLength)
            {
                return false;
            }
```
value is not serialized because originalLength > MaxJsonLength(512kb) is true

**Comment by snakefoot** [comment]
Yes it is bad that it creates invalid Json, and it should be fixed. Would fallback to `null` work for you:

`..., "MdlcTestProperty": null, "TestProperty": null  }`

**Comment by snakefoot** [comment]
Created pull-request #4245 so JsonLayout recognizes when object-serialization failed, and unwinds to avoid invalid Json.

Have also fixed so the MaxJsonLength will not affect simple objects like Guid.

**Comment by snakefoot** [comment]
Closed by #4245

**Comment by oleglck** [comment]
Thanks for the fix.

But do I understand correctly that the limitation in DefaultJsonSerializer.SerializeObjectWithReflection on MaxJsonLength remains?
that is, if the total length of the stringbuilder exceeds MaxJsonLength (this can happen if the length of the attribute is more than 512kb or attibute plus mdlc llength> 512kb, etc.), then all mdlc complex object properties or logevent properties will not be serialized?
guid was made for example,
ours mdlc or logevent properties can contain complex objects

maybe remove this restriction MaxJsonLength
or make it customizable?

**Comment by snakefoot** [comment]
> But do I understand correctly that the limitation in DefaultJsonSerializer.SerializeObjectWithReflection on MaxJsonLength remains?

Yes `const int MaxJsonLength = 512 * 1024` still remains.

> maybe remove this restriction MaxJsonLength? or make it customizable?

The restriction was made to ensure serialization will not run wild in an uncontrolled object-tree. Usually a log-message is 100-1024 characters long. You are welcome to create a pull-request to make it configurable. Alternative you can [provide your own JsonConverter](https://github.com/NLog/NLog/wiki/How-to-use-structured-logging#i-like-to-use-jsonnet-for-creating-json).
