### ISSUE TITLE
Add support for controlling FilePermissions in FileTarget

### ISSUE THREAD

**Issue by habakuk007** [NLog/NLog#4243]
As told by  @JoasE in #627 (see [his comment](https://github.com/NLog/NLog/issues/627#issuecomment-627205584)):
----
I am using NLog in an WPF application.
Logfiles for any user were stored in `ProgramData/Company/App/Logs/LogFile.log.` This caused AccessViolationException's when 2 different users use the application.

I solved this problem by creating a separate log folder for each user using the application in the nlog.config: `fileName="${specialfolder:folder=CommonApplicationData}/App/Logs/${windows-identity:domain=False}/LogFile.Log"`

After this I still experienced issues when the user runs the application in elevated permission. Their windows identity stays the same, but the files created can only be edited by an admin. So the next time the user starts the application without elevation, the user couldn't archive/write to the files.

However, I would still propose a fix for this to be implemented. This could come in the form of a new File target attribute which will make sure any files created by NLog are accessible to all users.
Example:

    <target xsi:type="File"
            filePermissions="allUsers | currentUser" />
----
I opened a new issue as the original one is closed.

**Comment by snakefoot** [comment]
For this new duplicate issue, then the [reply ](https://github.com/NLog/NLog/issues/627#issuecomment-627545410) remains the same.

Pull-requests are ofcourse welcome that will implement the solution suggested in the reply (or something more elegant).
