### ISSUE TITLE
Should targets added manually after configuration loaded already be initialized ?

### ISSUE THREAD

**Issue by GggXp** [NLog/NLog#4254]
Hi!
I have a config file in my case and i want to add a target manually after this config file loaded but this target is invalid and never initialized. 
Should targets added manually after configuration loaded already be initialized ?

**Comment by snakefoot** [comment]
After having added the new target and configured the Logging-Rules, then execute this method:

`LogManager.ReconfigureExistingLoggers()`

It will update all Logger-objects to apply the updated Logging-Rules, and also initialize newly added Targets.

**Comment by GggXp** [comment]
But I have no logger at all, this method name is a little confusing.

**Comment by GggXp** [comment]
> After having added the new target and configured the Logging-Rules, then execute this method:
> 
> `LogManager.ReconfigureExistingLoggers()`
> 
> It will update all Logger-objects to apply the updated Logging-Rules, and also initialize newly added Targets.

But I have no logger at all, this method name is a little confusing.

**Comment by snakefoot** [comment]
@GggXp If you don't have any Logger-objects or ILogger-objects, then I guess you don't need any targets (or any NLog configuration for that matter).

Again trust me. After having updated Logging-Rules and added NLog-Targets, then call this method:

`NLog.LogManager.ReconfigureExistingLoggers();`

**Comment by snakefoot** [comment]
Alternative you can make use of the fluent-API:

```c#
NLog.LogManager.Setup().LoadConfiguration(builder => {
    // Do your magic here, and NLog will make sure apply the changes (without needing to call ReconfigureExistingLoggers)
});
```

**Comment by GggXp** [comment]
> @GggXp If you don't have any Logger-objects or ILogger-objects, then I guess you don't need any targets (or any NLog configuration for that matter).
> 
> Again trust me. After having updated Logging-Rules and added NLog-Targets, then call this method:
> 
> `NLog.LogManager.ReconfigureExistingLoggers();`

I do believe you and it works. but what i mean is the method named NLog.LogManager.ReconfigureExistingLoggers() looks like reconfiguring existing loggers although I have no logger at that time.The name dose not match its behavior.
Thank you so much and sorry for my poor english language and expression.

**Comment by snakefoot** [comment]
Yes method `ReconfigureExistingLoggers` does a lot of things, but its main-objective is to do a fast-refresh of the LoggingConfiguration and update all existing Logger-objects apply any updates to the Logging-Rules.

You are welcome to use the [fluent-API](https://github.com/NLog/NLog/issues/4254#issuecomment-763565466) and then you don't have to look at the confusing method name.

**Comment by snakefoot** [comment]
Closing as resolved
