### ISSUE TITLE
NLogTraceListener results in TypeLoadException with Xamarin.iOS and Xamarin.Android

### ISSUE THREAD

**Issue by omghb** [NLog/NLog#4267]
**NLog version**: 4.7.7
**Xamarin Forms**: 4.7.0.1351

During initialization I get the following exception on iOS and on Android:

`System.TypeLoadException
  Message=Could not resolve type with token 01000059 from typeref (expected class 'NLog.NLogTraceListener' in assembly 'NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c')`

Before this exception occurs some other NLog types could be loaded without an error.

**Comment by snakefoot** [comment]
Looks like NLogTraceListener is not currently available on Xamarin Android + iOS platform:

https://github.com/NLog/NLog/blob/master/src/NLog/NLogTraceListener.cs

Believe this will be fixed with NLog 5.0 where Android and iOS specific builds will be removed, so it will use NetStandard instead.

**Comment by snakefoot** [comment]
Guess this issue was resolved by #3978
