### ISSUE TITLE
Evaluating nested substitutions

### ISSUE THREAD

**Issue by MgSam** [NLog/NLog#427]
I think NLog is improperly evaluating nested substitutions in the config file. 

Specifically, I'm trying to pass a variable to a custom layout. See the following snippet:

```xml
layout="${my.CustomLayout:Context=${test}}"
```
where `test` is defined as:

```xml
<variable name="test" value="${date}"/>
```

CusomLayout is a custom layout renderer. Rather than pass the contents of `test` into the `Context`; `Context` is receiving the string "${date" (yes, missing the closing bracket). I've tried all manner of esacpes but nothing seems to fix this problem.

Is this a bug or am I missing the solution?

**Comment by 304NotModified** [comment]
@Xharze any ideas on this issue? I need this for #485

**Comment by Xharze** [comment]
I haven't taken a look at it yet, but I'll let you know as soon as I looked
at it

**Comment by Xharze** [comment]
Have you tried escaping the last bracket with with a backslash? Like this:

```xml
<variable name="test" value="${date\}"/>
```

It should work
