### ISSUE TITLE
A way to write log files sequentially using Nlog

### ISSUE THREAD

**Issue by Melnikov37** [NLog/NLog#4281]
I have a question about setting up NLog. As part of our project, we want to create and write log files in this format:
- logname_2021_01_21_18_34_42.log (archive file 32Mb)
- logname_2021_01_22_11_54_21.log (current file 3Mb)

Next iteration:
- logname_2021_01_21_18_34_42.log (archive file 32Mb)
- logname_2021_01_22_11_54_21.log (archive file 32Mb)
- logname_2021_01_25_01_26_34.log (current file 7Mb)
- etc.

When the main file is full (for example up to 32 MB), a new file is created with the current date and time, and the old file is archived.

Is this implementation possible within NLog?

**NLog version:** 4.6.5
**Platform:** .Net 4.7.2

**Comment by snakefoot** [comment]
I guess you can do this:

```xml
<target type="file" name="logfile"
             filename="logname.log"
             archiveFileName="logname_{#}.log"
             archiveDateFormat="yyyy_MM_dd_HH_mm_ss"
             archiveEvery="DateAndSequence"
             archiveAboveSize="32000000" />
```

That will give the following output:

- logname_2021_01_21_18_34_42.log (archive file 32Mb)
- logname_2021_01_22_11_54_21.log (archive file 32Mb)
- logname.log (current file 7Mb)

But I do recognize that it doesn't match your desire. NLog have the ability to cache the initial FileName so it sticks throughout the lifetime of the application, but there is no option to re-init the cached FileName after archive-operation.

I usually do this, where it just create a new file every hour, and if there are a lot of activity with the same hour, then a sequence-no is added automatically:

```xml
<target type="file" name="logfile"
             filename="logname_${date:format=yyyy_MM_dd_HH}.log"
             archiveAboveSize="32000000" />
```

**Comment by Melnikov37** [comment]
Thanks for your help.
