### ISSUE TITLE
filter content form log

### ISSUE THREAD

**Issue by yedajiang44** [NLog/NLog#4283]
Please move [issues/473](https://github.com/NLog/NLog.Extensions.Logging/issues/473)

Very anxious, thanks!!!

**Comment by snakefoot** [comment]
Here is a simple (and advanced example) of how to setup NLog with appsettings.json:

https://github.com/NLog/NLog.Extensions.Logging/wiki/NLog-configuration-with-appsettings.json

**Comment by snakefoot** [comment]
Closing as duplicate
