### ISSUE TITLE
Data driven test cases: Integrate NLog with xunit into same logging / testing framework...

### ISSUE THREAD

**Issue by tapika** [NLog/NLog#4286]
See brief proposal in here:

https://github.com/xunit/xunit/discussions/2248

 - Why do we need it?
 
See brief description - pros / cons on that web page.

I guess this could be require major effort to make it happen.

Can you first list what kind of advantages and problems you see based on this approach ?

**Comment by snakefoot** [comment]
Not sure what changes you are proposing. But NLog has the ability [disable/suspend](https://nlog-project.org/documentation/v4.7.0/html/M_NLog_LogManager_DisableLogging.htm) to logging globally:

```c#
using (NLog.LogManager.DisableLogging())
{
    // Do something crazy
}
```

**Comment by tapika** [comment]
Basically my idea to provide to application mechanism to be able to log (to file) and after that to perform verification using same log as produced before. Somehow verified execution flow.

Previously in xunit you would use `Assert.Equal(x, 5)` - but now application developer would use some sort `logger.Debug($"{x}");`.

For first execution round - logger would log x value of 5, and store it in some log file.

For second execution round logger would not save "5" anymore, it would read previously recoded log file and compare that "5" matches "5". If not equal - logger will raise next exception, which in a turn would fail the test.

**Comment by snakefoot** [comment]
That approach sounds like most of the unit-testing in NLog, which also make sense they are tests for a logging-framework.

Though I find this approach less appealing in other application-scenario. Unit-testing verification based on logging output sounds fragile and a door for obfuscation. But I guess in a black-box scenario where it is hard to probe the inner-state, then it might make sense.

You are ofcourse very welcome to implement your own unit-test-extensions to setup NLog and assert that the expected output has been generated.

**Comment by tapika** [comment]
I'll probably will later on. Was just curious whether you accept this as an idea.

I'm also not sure about xunit versus NLog coupling - who depends on who, and where to reflect changes in first place.

Maybe some sort of API interface is needed from NLog, which in a turn needs to be integrated into xunit, which in a turn needs to be able to call NLog to manipulate log activation / deactivation.

If you have some rough ideas of what should be dependent an on what, let me know.

**Comment by snakefoot** [comment]
I'm guessing the logic for setting up NLog and doing comparison of output-content should be possible without being tied to a specific unit-test-framework.

Then any syntax sugar needed to integrate well with xUnit (or some other test-framework) can be added afterwards.

**Comment by snakefoot** [comment]
Closing as the work required here is not in the NLog-core-project but some extension library
