### ISSUE TITLE
JsonLayout excludeProperties does not work with includeMdlc

### ISSUE THREAD

**Issue by yosefca** [NLog/NLog#4287]
Hi,

When I'm using mdlc with a layout and trying to exclude this property from being added twice - It does not work and the
 excludeProperties of the eventProperties is not working.

for example:
 {
"name": "using-mdlc"
"layout": "${mdlc:hi:dusty=true}"
},
{
"name": eventProperties"
"layout": { "excludeProperties": dusty }
}

I will still see the property twice - one with the layout and another one without it.

example:
![image](https://user-images.githubusercontent.com/49646279/107207696-4c29f480-6a09-11eb-9eae-1728e30691a5.png)

**Comment by snakefoot** [comment]
Please provide the entire configuration instead of a tiny fraction. Hard to guess when no context.

**Comment by yosefca** [comment]
"NLog": {
		"throwConfigExceptions": true,
		"targets": {
			"syslog": {
				"type": "Syslog",
				"layout": {
					"type": "CompoundLayout",
					"layouts": [
						{
							"type": "JsonLayout",
							"Attributes": [
								{
									"name": "traceId",
									"layout": "${aspnet-TraceIdentifier}"
								},
								{
									"name": "user",
									"layout": "${aspnet-user-identity}"
								},
								{
									"name": "useragent",
									"layout": "${aspnet-request-useragent}"
								},
								{
									"name": "logger",
									"layout": "${logger}"
								},
								{
									"name": "message",
									"layout": "${message}"
								},
								{
									"name": "exception",
									"layout": "${exception:format=Message,ShortType,StackTrace:maxInnerExceptionLevel=5:innerFormat=Message,ShortType,StackTrace}"
								},
								{
									"name": "using-mdlc",
									"layout": "${mdlc:hi:dusty=true}"
								},
								{
									"name": "eventProperties",
									"encode": false,
									"layout": {
										"type": "JsonLayout",
										"maxRecursionLimit": 3,
										"includeAllProperties": true,
										"excludeProperties": "dusty",
										"includeMdlc": true
									}
								}
							]
						},
						{
							"type": "SimpleLayout",
							"text": "${newline}"
						}
					]
				},
				"messageCreation": {
					"facility": "local1",
					"rfc": "Rfc5424",
					"rfc5424": {
						"hostname": {
							"type": "SimpleLayout",
							"text": "${machinename}"
						},
						"appName": {
							"type": "SimpleLayout",
							"text": "${iis-site-name}"
						},
						"procId": {
							"type": "SimpleLayout",
							"text": "${processid}"
						},
						"msgId": {
							"type": "SimpleLayout",
							"text": "${threadid}"
						},
						"disableBom": true
					}
				},
				"messageSend": {
					"protocol": "tcp",
					"tcp": {
						"server": "localhost",
						"port": "5000"
					}
				}
			},
			"logconsole": {
				"type": "Console",
				"layout": {
					"type": "JsonLayout",
					"Attributes": [
						{
							"name": "traceId",
							"layout": "${aspnet-TraceIdentifier}"
						},
						{
							"name": "user",
							"layout": "${aspnet-user-identity}"
						},
						{
							"name": "useragent",
							"layout": "${aspnet-request-useragent}"
						},
						{
							"name": "timestamp",
							"layout": "${date:format=o}"
						},
						{
							"name": "level",
							"layout": "${level}"
						},
						{
							"name": "logger",
							"layout": "${logger}"
						},
						{
							"name": "message",
							"layout": "${message}"
						},
						{
							"name": "using-mdlc",
							"layout": "${mdlc:hi:dusty=true}"
						},
						{
							"name": "eventProperties",
							"encode": false,
							"layout": {
								"type": "JsonLayout",
								"maxRecursionLimit": 3,
								"includeAllProperties": true,
								"excludeProperties": "dusty",
								"includeMdlc": true
							}
						}
					]
				}
			}
		},
		"rules": [
			{
				"logger": "*",
				"minLevel": "Info",
				"maxLevel": "Error",
				"writeTo": "logconsole"
			},
			{
				"logger": "*",
				"minLevel": "Debug",
				"writeTo": "syslog"
			}
		]
	}

**Comment by snakefoot** [comment]
This looks very special. Can you explain what you expect it should do:

- `${mdlc:hi:dusty=true}`

Usually one does this:

- `${mdlc:item=dusty}`

One have to be careful when using the `:` inside NLog-Layout, since it has special meaning (means start of new property).

**Comment by snakefoot** [comment]
Notice also that `excludeProperties` currently only applies to LogEventInfo.Properties:

```json
"layout": {
	"type": "JsonLayout",
	"maxRecursionLimit": 3,
	"includeAllProperties": true,
	"excludeProperties": "dusty",
	"includeMdlc": true
}
```

So it will not exclude dusty from the properties retrieved from "includeMdlc". Which could be nice, but not yet implemented.

**Comment by yosefca** [comment]
I will add some information about the class im using in order to apply the layout:
`public class MaskedWrapper : WrapperLayoutRendererBase
{
	public bool Dusty {get; set;} = false;
	
	protected override string Transform(string text)
	{
		if (!Dusty) return text;
		
		if (string.IsNullOrEmpty(text)) return null;
		
		return "~!~!~!" + text + "!~!~!~";
	}
}`

In addition, this is how we added our value into the properties:
`using (logger.BeginScope(new [] { new KeyValuePair<string,object> ("hi", "whatsup")}))
{
	logger.LogInformation("some text")
}`

My question is - how we can add properties without including them in the string being logged as the message.

**Comment by snakefoot** [comment]
>  how we can add properties without including them in the string being logged as the message.

It is possible to add extra LogEvent properties by logging a custom LogState. See also [NLog properties with Microsoft Extension Logging](https://github.com/NLog/NLog.Extensions.Logging/wiki/NLog-properties-with-Microsoft-Extension-Logging#logtstate-simple)

You can also try this nuget-package: https://www.nuget.org/packages/XeonApps.Extensions.Logging.WithProperty/

**Comment by snakefoot** [comment]
Has your question been answered?
