### ISSUE TITLE
Configuration Tranformation Guide Missing

### ISSUE THREAD

**Issue by ollie10** [NLog/NLog#4288]
Hello everyone, I'm wondering why there is no page explaining how to generate a configuration transformation of the  **Nlog.config**

I'll explain the use case and I somehow made it work but I would like to know the proper way to do this:

I'm on a **.Net (core) 5.0 Web App with Visual Studio 2019**. Until today I used the **Web.config** only to transform the **Nlog section**, but I decided to get rid of the Web.config because it is not needed anymore, especially when you publish to a Linux Target the **Web.config** is not generated, neither taken into consideration.

So far it's years that the configuration of a .net core application it's done via **AppSettings.json** which is loaded / transformed at runtime but still no clear (or poor) documentation on how to configure Nlog with Appsettings. All the documentation keep referring it to the **Nlog.config**, event the latest 5.0, which in case of **Visual Studio** it's not transformed out of the box like the Web.config, so my question is how to transform the **Nlog.config** at build or publish time, it seems there is not a clear guideline to do it so and you need to run tools like **SlowCheetah** or Post Publish actions that are far to be optimal.

Besides that it seems that Nlog it's one of the last libraries using .config files as configuration source, on Microsoft website everything refers to json files since long time...

Any documentation about this? Many thanks

**Comment by snakefoot** [comment]
StackOverflow is probably a good place to start:

https://stackoverflow.com/questions/22438204/config-transformation-on-nlog-does-not-work
https://stackoverflow.com/questions/11633382/xml-file-transforms-using-one-click-publish-but-not-web-deploy
https://stackoverflow.com/questions/46443700/transform-a-file-other-than-web-config-replace-element

Also notice that you have NLog.config include other NLog.config so you can have a default NLog.config that is included by environment-specific NLog.config (That includes additional modifications).

You can also use GDC in the application to setup environment specific-values that can be referenced in the NLog.config

**Comment by ollie10** [comment]
Hello @snakefoot I have already red the first article before posting this question and they solve it or putting the Nlog configuration in the Web.config or using Slowcheeta. The second it's of 8 years ago, I don't even know if .Net Core was available 8 years ago so I suppose it won't apply, third link same story, outdated.

The last solution of publishing various profiles in the Nlog.config means that I will need to publish settings for Test and Production environment together even if I'm publishing to Development environment... it doesn't seem a real solution... for sure not a secure one

I have already tried with <TransformOnBuild>true</TransformOnBuild> and putting the proper namespaces in the file, nothing works on Visual Studio 2019. So I suppose there isn't a clear way to do it so and I will need to stick to Slowcheeta or change logging library, it seems a little strange because [Serilog](https://github.com/serilog/serilog-settings-configuration) perhaps supports it out of the box...

**Comment by snakefoot** [comment]
Yes that is the problem free open-source projects. They only improve when someone needs a feature bad enough.


Sent from my Sony Xperia


---- Vincenzo Pucarelli wrote ----


Hello @snakefoot<https://github.com/snakefoot> I have already red the first article before posting this question and they solve it or putting the Nlog configuration in the Web.config or using Slowcheeta. The second it's of 8 years ago, I don't even know if .Net Core was available 8 years ago so I suppose it won't apply, third link same story, outdated.

The last solution of publishing various profiles in the Nlog.config means that I will need to publish settings for Test and Production environment together even if I'm publishing to Development environment... it doesn't seem a real solution... for sure not a secure one

I have already tried with true and putting the proper namespaces in the file, nothing works on Visual Studio 2019. So I suppose there isn't a clear way to do it so and I will need to stick to Slowcheeta or change logging library, it seems a little strange because Serilog<https://github.com/serilog/serilog-settings-configuration> perhaps supports it out of the box...

**Comment by snakefoot** [comment]
Anyway please come back if you find the secret sauce that make everything work. When using NetCore then Microsoft is selling the appsettings.json that also include override logic:

See also: https://github.com/NLog/NLog.Extensions.Logging/wiki/NLog-configuration-with-appsettings.json#environment-specific-configuration

**Comment by ollie10** [comment]
Cool, this seems to be the solution, don't know why I didn't find it before, it should be linked directly in the main Nlog Wiki Page, it's pretty important to configure new applications, many thanks

**Comment by snakefoot** [comment]
@ollie10 Having NLog-config in the appsetting.json is still pretty "new", so have not gained that much traction.

**Comment by ollie10** [comment]
I will be an "early adopter" so! Cheers! Besides that you can even have an nlog.json file and keep separated appsettings and other components, If I will have problems integrating it I'll come back, my main concern is that extensions will work with that too, I think so, I'm using Syslog which is pretty straightforward to configure, let's see if it works as expected

**Comment by snakefoot** [comment]
Please tell if you bump into something annoying, then we might be able to make the road less bumpy for future users. Also notice that all Wiki-pages are open, so you are welcome to improve the place that are lacking.

**Comment by ollie10** [comment]
@snakefoot well I would say that this could be the first stopper... the packages [is not available](https://www.nuget.org/packages/NLog.Extension.Logging) in nuget (anymore?)

**Comment by snakefoot** [comment]
https://www.nuget.org/packages/NLog.Extensions.Logging


Sent from my Sony Xperia


---- Vincenzo Pucarelli wrote ----


@snakefoot<https://github.com/snakefoot> well I would say that this could be the first stopper... the packages is not available<https://www.nuget.org/packages/NLog.Extension.Logging> in nuget (anymore?)

**Comment by ollie10** [comment]
Ok thanks, in the github page it's written wrongly **NLog.Extension.Logging** without plural **Extensions**, I will give it a try

**Comment by snakefoot** [comment]
@ollie10 Thank you for noticing and updating the wiki. I have added some more examples of how to load NLog-config from appsettings.json
