### ISSUE TITLE
Programmatically invoke archive routine for FileTarget

### ISSUE THREAD

**Issue by cain05** [NLog/NLog#4289]
NLog version: 4.6.5

Platform: .Net 4.7

Why do we need it?

In our application we have some UI in place to display X number of log entries from the current log file.  In our old product that did not use NLog, we gave the user the ability to clear the current log file and the option to save it somewhere else.  While we could do this manually as we have before, it would be nice if we could ask the FileTarget to archive it immediately, rather than wait for the archiving conditions to be reached.  This way the log file would end up with the rest of the archives and follow the same naming convention.

**Comment by snakefoot** [comment]
NLog has a fire and forget behavior, where the following events can trickle down to the actual file-target:
- Initializing file target
- Writing logevent to file target
- Flushing file target
- Closing file target.

But none of those events matches your case, and it would not be trivial to stage a situation where the next logevent would trigger a file-archive-operation. I guess one could add an extra override of `CleanupInitializedFiles()` where one specifies that archive operation should be performed on any open files. But that requires the file in question has been initialized by the filetarget already, and not an "old" file from previous application-run.

**Comment by snakefoot** [comment]
Has your question been answered?

**Comment by cain05** [comment]
Thank you for the response.  I can look into playing around with `CleanupInitializedFiles()`.  To be honest, I haven't really dove into the code too much, so I'm not familiar with how it all works.  Is there a possibility that this feature could be added, or am I looking at having to implement something myself?

**Comment by snakefoot** [comment]
@cain05 I'm focusing my energy on preparing for NLog 5.0, so I'm not planning to make any changes in FileTarget.

**Comment by cain05** [comment]
Ok that's, fine.  It's not something that needs to be addressed immediately, I was just wondering if it was a possibility or not.

**Comment by snakefoot** [comment]
If a volunteer shows up that knows your application, and how it integrates with NLog, and can guess how to fulfil the expectations from your users, then I guess it is a possibility.
