### ISSUE TITLE
FindTargetByName fails with unable to cast type when using async=true

### ISSUE THREAD

**Issue by Gitas-eld** [NLog/NLog#4290]
Hi!

If you have a question that the logging isn't working, check the [troubleshooting guide](https://github.com/nlog/nlog/wiki/Logging-troubleshooting) first before posting.
Almost every case is solveble with the internal log

Are you searching for a layout or layout renderer? You could find them [here](https://nlog-project.org/config/)

Stackoverflow is recommend for questions. You could expect a faster response there (but do include all the info below) and the search is better.

For the stackoverfolow the following is recommend:

- Use the tag "nlog"
- Include versions of NLog/NLog.AspNetCore etc.
- Include the platform (.NET 4.5, ASP.NET Core 3 etc)
- Include the current config (xml or code)
- Explain current result
- Explain desired result
- Please post full exception details (message, stacktrace, inner exceptions) in case of an error

**Comment by snakefoot** [comment]
You have nicely skipped all the requirements from the issue-template, and provided a random error-message.

Please include your NLog.config if you expect to get any help.

**Comment by Gitas-eld** [comment]
This is Nlog.config:
<?xml version="1.0" encoding="utf-8" ?>
<nlog autoReload="true"
      globalThreshold="Debug"
      xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <targets >
    <target xsi:type="Database"
               name="LogDB"
               dbProvider="sqlserver"
               commandText="INSERT INTO [Log_Entries] ([CallSite], [Date], [Exception], [Level], [Logger], [MachineName], [Message], [StackTrace], [Thread], [Username]) VALUES (@CallSite, @Date, @Exception, @Level, @Logger, @MachineName, @Message, @StackTrace, @Thread, @Username);">
      <parameter name="@CallSite" layout="${callsite:filename=true}" />
      <parameter name="@Date" layout="${longdate}" />
      <parameter name="@Exception" layout="${exception}" />
      <parameter name="@Level" layout="${level}" />
      <parameter name="@Logger" layout="${logger}" />
      <parameter name="@MachineName" layout="${machinename}" />
      <parameter name="@Message" layout="${message}" />
      <parameter name="@StackTrace" layout="${stacktrace}" />
      <parameter name="@Thread" layout="${threadid}" />
      <parameter name="@Username" layout="${windows-identity:domain=true}" />
    </target>
  </targets>
  <rules>
    <logger name="LogData"  minlevel="Debug"  writeTo="LogDB" />
  </rules>
</nlog>

This is My Code:
static ErrorLog()
        {
            NLog.GlobalDiagnosticsContext.Set(LOGPATH, AppDomain.CurrentDomain.BaseDirectory);
            var config = LogManager.Configuration;
            var dbTarget = (DatabaseTarget)config.FindTargetByName("LogDB");
            dbTarget.ConnectionString = ApplicationDbContext.GetConnectionString;
            LogManager.ReconfigExistingLoggers();
        }

This line throw the exception:
var dbTarget = (DatabaseTarget)config.FindTargetByName("LogDB");

I would appreciate your help

**Comment by Gitas-eld** [comment]
For some reason the config was deleted,
Nlog.config:
nlog autoReload="true"
      globalThreshold="Debug"
      xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  targets 
    target xsi:type="Database"
               name="LogDB"
               dbProvider="sqlserver"
               commandText="INSERT INTO [Log_Entries] ([CallSite], [Date], [Exception], [Level], [Logger], [MachineName], [Message], [StackTrace], [Thread], [Username]) VALUES (@CallSite, @Date, @Exception, @Level, @Logger, @MachineName, @Message, @StackTrace, @Thread, @Username);"
      <parameter name="@CallSite" layout="${callsite:filename=true}" 
      <parameter name="@Date" layout="${longdate}" 
      <parameter name="@Exception" layout="${exception}" 
      <parameter name="@Level" layout="${level}" 
      <parameter name="@Logger" layout="${logger}" 
      <parameter name="@MachineName" layout="${machinename}" 
      <parameter name="@Message" layout="${message}" 
      <parameter name="@StackTrace" layout="${stacktrace}" 
      <parameter name="@Thread" layout="${threadid}" />
      <parameter name="@Username" layout="${windows-identity:domain=true}" 
    /target
  /targets
  rules
    logger name="LogData"  minlevel="Debug"  writeTo="LogDB" 
  /rules
/nlog

**Comment by snakefoot** [comment]
When using `<targets async="true">` then it actually becomes:

```xml
<targets>
    <target type="AsyncWrapper" name="LogDB">
                <target type="Database" name="LogDB_wrapped">
                </target>
    </target>
</targets>
```

You can do this as a workarounde:

```c#
           foreach (var dbTarget in config.AllTargets.OfType<DatabaseTarget>())
                dbTarget.ConnectionString = ApplicationDbContext.GetConnectionString;
           LogManager.ReconfigExistingLoggers();
```

Planning to improve NLog 5.0 a little so one can do this:

```c#
            var dbTarget = config.FindTargetByName<DatabaseTarget>("LogDB"); 
            dbTarget.ConnectionString = ApplicationDbContext.GetConnectionString;
```

**Comment by Gitas-eld** [comment]
Thank you very much, working properly
