### ISSUE TITLE
Simple SkipHelperFunction Attribute for excluding logging helper functions from ${callsite}

### ISSUE THREAD

**Issue by maazl** [NLog/NLog#4293]
**NLog version**: 4.0
(The recent master code is still affected.)

**Platform**: .Net 4.5
(probably not platform dependent)

**Current NLog config**
```xml
<nlog>
    <targets>
      <target name="file" xsi:type="File" fileName="${basedir}\App_Data\logs\Log${shortdate}.log" keepFileOpen="true">
        <layout xsi:type="CsvLayout" delimiter="Tab" withHeader="false">
          <column name="time" layout="${longdate}" quoting="Nothing"/>
          <column name="level" layout="${level:upperCase=true}" quoting="Nothing"/>
          <column name="callsite" layout="${callsite}" quoting="Nothing"/>
          <column name="message" layout="${message}" quoting="All"/>
        </layout>
      </target>
    </targets>
    <rules>
      <logger name="*" minlevel="Debug" writeTo="file"/>
    </rules>
</nlog>
```
Only the `${callsite}` is relevant for this feature.

## Why do we need it?

When writing **custom logging helper function** for logging, they **usually should be excluded from callstite determination**. This is currently only possible by using a distinct class and passing the wrapperType explicitly. But this is complicated, even more if the local helper method is not static. 

Example for static helper method *with work around*:
```cs
    public class WorkManager
    {
        private static readonly Logger Logger = LogManager.GetCurrentClassLogger();

        public SomeMethod(OrmWorkItem item)
        {
            LogHelper.ConditionalTrace(item, "My message");
        }

        // ...

        private static class LogHelper
        {
            // The helper function
            [Conditional("DEBUG")]
            public static void ConditionalTrace(OrmWorkItem item, string message)
            {
                if (Logger.IsTraceEnabled)
                    Logger.Log(typeof(Log), LogEventInfo.Create(LogLevel.Trace, Logger.Name,
                        $"{message} '{item.Name?.Translate()}' {item.Oid}, inst {item.InstanceGuid}, state {EnumWorkItemState.GetValue(item.State)?.Text}, class {item.ItemClass}, modified {item.Modified}"));
            }
        }
```

## Intended solution
```cs
    public class WorkManager
    {
        private readonly Logger Logger = LogManager.GetCurrentClassLogger();

        public SomeMethod(OrmWorkItem item)
        {
            ConditionalTraceHelper(item, "My message");
        }

        // ...

        // The helper function
        [Conditional("DEBUG")]
        [SkipHelperFunction]
        private void ConditionalTraceHelper(OrmWorkItem item, string message)
        {
            Logger.Trace($"{message} '{item.Name?.Translate()}' {item.Oid}, inst {item.InstanceGuid}, state {EnumWorkItemState.GetValue(item.State)?.Text}, class {item.ItemClass}, modified {item.Modified}");
        }
```

The **`SkipHelperFunctionAttribute`** should do the magic. It should **exclude this stack frame from callsite determination**.

This simplifies coding of helper methods significantly. First of all the convinient overloads for Error/Warning/Info etc. can be used. Furthermore it does also work if the custom helper function needs access to non-static members of the current class without passing the parent instance explicitly.

## Possible implementation

AFAIK this cannot be implemented by custom code. For this to work **the internal method `FindCallingMethodOnStackTrace` needs to be modified** to skip stack frames with this attribute. The method was in class `LoggerImpl` previously. Now it is in class `CallSiteInformation`.

I am not really familiar with the NLog code but probably something like
```cs
        if (stackFrame.GetMethod().IsDefined(typeof(SkipHelperFunctionAttribute), false)
            continue;
```
should do the job. I am unsure whether it should be placed before or after `if (IsLoggerType`.

**Comment by snakefoot** [comment]
Right now there are two approaches for handling Logger-wrappes and callsite-scanning:
- Inject the type of the logger-wrapper as input for NLog
- Register the assembly of the logger-wrapper so NLog will ignore all methods from the assembly.. See `LogManager.AddHiddenAssembly(yourAssembly)`.

Already now the stacktrace and callsite-scanning is very expensive. Not sure adding more wood to this fire would be any help.

**Comment by snakefoot** [comment]
Closing this as wont-fix as the suggested idea will give a performance overhead from everyone not making use of `[SkipHelperFunction]`. 

But you are welcome to open a new issue, with any new ideas for making it easier to create logger-wrappers with callsite-support.

**Comment by maazl** [comment]
The problem can be solved by a **custom layout renderer** as work-around. The solution is quite fast due to a cache. Unfortunately this will not prevent the standard, uncached callsite determination from running although the information is not needed.

And, of course, the dozens of options of the standard callsite renderer are not covered by this simple example. And the assembly filter is an opt-in filter here, because this better fits our needs. But this can be easily fixed, also with a cache. The primary benefit is a smaller ExludeRule cache.

But at least it proofs that **an implementation is possible without any significant runtime overhead**. In fact with the cache it might be even faster.
And tagging methods, classes and assemblies is _much more convenient_ than dealing with the logger class when passing any individual event.

Example:
```cs
[LayoutRenderer("BAcallsite")]
public class NLogBACallsiteLayoutRenderer : LayoutRenderer, IUsesStackTrace
{
    private readonly Dictionary<MemberInfo, bool> ExcludeRule = new Dictionary<MemberInfo, bool>();
    private readonly Dictionary<Assembly, bool> AssemblyRule = new Dictionary<Assembly, bool>();

    public StackTraceUsage StackTraceUsage => StackTraceUsage.WithoutSource;

    protected override void Append(StringBuilder builder, LogEventInfo logEvent)
    {
        StackTrace stack = logEvent.StackTrace;
        StackFrame frame;
        MethodBase method;
        Type type;

        lock (this)
            for (int i = 2; i < stack.FrameCount; ++i)
            {
                frame = stack.GetFrame(i);

                method = frame.GetMethod();
                type = method.DeclaringType;
                if (type == null)
                    continue;

                if (!AssemblyRule.TryGetValue(type.Assembly, out bool ret))
                    AssemblyRule.Add(type.Assembly, ret = type.Assembly.IsDefined(typeof(AssemblyFrameworkAttribute)));
                if (!ret)
                    continue;

                if (!ExcludeRule.TryGetValue(type, out ret))
                    ExcludeRule.Add(type, ret = !type.IsDefined(typeof(NLogIgnoreInBACallsiteAttribute)));
                if (!ret)
                    continue;

                if (!ExcludeRule.TryGetValue(method, out ret))
                    ExcludeRule.Add(method, ret = !method.IsDefined(typeof(NLogIgnoreInBACallsiteAttribute)));
                if (ret)
                    goto match; // continue outside lock
            }

        builder.Append("<unknown>");
        return;

    match:
        builder.Append(type.FullName).Append('.').Append(method.Name);
    }
}

[AttributeUsage(AttributeTargets.Class | AttributeTargets.Method)]
public class NLogIgnoreInBACallsiteAttribute : Attribute
{ }
```

**Comment by snakefoot** [comment]
@maazl My understanding was that you wanted to optimize performance by only doing capture of callsite when necessary.

But it just sounds like you want to exclude your own custom logger-wapper in the callsite-scan. I have already provided two solutions of how to do this in my previous comment: https://github.com/NLog/NLog/issues/4293#issuecomment-777024363

**Comment by maazl** [comment]
@snakefoot Indeed, the basic intent is to exclude some helper functions.
Unfortunately excluding assemblies or entire classes does not fit for the case when an abstract base class provides _protected_ helper functions for its descendants. If I exclude the class this will apply the all sub classes as well, so effectively everything is excluded.
The only way to come around this is to move the helper functions into a nested class and pass this type as log helper class. In this case additional overhead is required to access instance members of the base class to enrich context information (that's the primary purpose of the helper functions). And, of course, the syntax to call the helper functions is no longer compatible. It needs to be prefixed with `LogHeplerInstance.` or something similar. In our case this is a breaking change of a public extension API.

**Comment by maazl** [comment]
@snakefoot Indeed, the basic intent is to exclude some helper functions.
Unfortunately excluding assemblies or entire classes does not fit for the case when an abstract base class provides _protected_ helper functions for its descendants. If I exclude the class this will apply the all sub classes as well, so effectively everything is excluded.
The only way to come around this is to move the helper functions into a nested class and pass this type as log helper class. In this case additional overhead is required to access instance members of the base class to enrich context information (that's the primary purpose of the helper functions). And, of course, the syntax to call the helper functions is no longer compatible. It needs to be prefixed with `LogHeplerInstance.` or something similar. In our case this is a breaking change of a public extension API.

**Comment by snakefoot** [comment]
#5313 Adds support for excluding a single class-type when resolving CallSite, instead of having to exclude an entire assembly.
