### ISSUE TITLE
Retry timing logic in AsyncTaskTarget does not work as expected

### ISSUE THREAD

**Issue by aled** [NLog/NLog#4310]
**NLog version**: ;discovered in 4.7.5, but also present on dev branch

**Platform**: discovered on .NET framework 4.7.2, but likely affects all platforms

**Current NLog config**: paraphrased:

```xml
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" internalLogLevel="error" internalLogFile="nlog-internal.log">
    <extensions>
      <add assembly="MyCustomDll.dll"
    </extensions>
  <targets>
    <target xsi:type="MyCustomTarget" retryDelayMilliseconds ="500" retryCount="10"
  </targets>
  <rules>
    ...
  </rules>
</nlog>
```

The relevent parts of the custom target are as follows

```
protected override async Task WriteAsyncTask(IList<LogEventInfo> logEvents, CancellationToken cancellationToken)
{
    throw new Exception();
}
```

- What is the current result? Upon writing a log, `WriteAsyncTask` is called at times 0ms, 500ms, 1500ms, 2500ms, 3500ms, etc
- What is the expected result? Upon writing a log, `WriteAsyncTask` is called at times 0ms, 500ms, 1000ms, 2000ms, 4000ms, etc
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)? Yes, it confirms these timings.
- Please post full exception details (message, stacktrace, inner exceptions) N/A
- Are there any workarounds? no
- Is there a version in which it did work? no
- Can you help us by writing an unit test? yes

I'm happy to fix this and raise a PR if accepted as a valid bug.

**Comment by snakefoot** [comment]
@aled You are welcome to create a pull-request if you have found something that diverts from the expected.
