### ISSUE TITLE
How to add AppInsights taget as an additional target

### ISSUE THREAD

**Issue by madhusameena** [NLog/NLog#4319]
Hi!

I using dotnet core console application with NLog.
I have console and file targets already, I want to integrate the Appinsights target in Nlog.config
I tried some links but Cannot see the log in AppInsights

my tagets
```xml
<variable name="format" value="[${date:format=dd-MM-yyyy HH\:mm\:ss.fff K}] [${level:uppercase=true}] [Thread Id: ${threadid}] [${message} ${exception}]" />
<variable name="logsDir" value="${basedir}Logs" />
<target xsi:type="File" name="file"
		        fileName="${logsDir}/Test.log"
		        archiveFileName="${logsDir}/Test.Archive.{#}.log"
		        archiveAboveSize="20971520"
		        archiveNumbering="Date"
		        archiveDateFormat="dd-MM-yyyy_HH.mm.ss.fff"
		        archiveOldFileOnStartup="false"
		        concurrentWrites="true"
		        keepFileOpen="false"
		        layout="${var:format}" />
		<target xsi:type="Console" name="console"
		        layout="${var:format}" />
```

How Can I add appinsights target here But I want to send AppInsights Key from application (programmatically )

**Comment by 304NotModified** [comment]
See here

https://github.com/microsoft/ApplicationInsights-dotnet-logging#nlog

Please follow these instructions.

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, please let us know!

**Comment by madhusameena** [comment]
> 
> 
> See here
> 
> https://github.com/microsoft/ApplicationInsights-dotnet-logging#nlog
> 
> Please follow these instructions.

Hi @304NotModified  Thank you for the response.
with key value in config it is working fine
but I wanted to give the key from outside
with the given example it is not working fine.

`TelemetryConfiguration.Active.InstrumentationKey = "Your_Resource_Key";` - This is Deprecated So I used 
https://github.com/microsoft/ApplicationInsights-dotnet/issues/1152 This way 

I also followed 
```
ApplicationInsightsTarget appInsightsTarget = LogManager.Configuration.FindTargetByName<ApplicationInsightsTarget>(APP_INSIGHTS_TARGET);
appInsightsTarget.InstrumentationKey = appInsightsKey;
LogManager.ReconfigExistingLoggers();
```


But still it is not taking the value.
Any clue from your side ?

**Comment by madhusameena** [comment]
HI @304NotModified @snakefoot  I followed this approach
https://github.com/microsoft/ApplicationInsights-dotnet/issues/1688

I set Environment variable for the process with the given key and value

and now it is working fine.
Do you see this is a better approach or any suggestions from your side ?

**Comment by snakefoot** [comment]
The `${environment}`-layout is just one option. There are [many ways available](https://nlog-project.org/config/?tab=layout-renderers) for reading settings. Ex:

- [${gdc}](https://github.com/NLog/NLog/wiki/Gdc-Layout-Renderer) - Allows you to assign variable from code, that is loaded by NLog Target (just make sure to assign the variable before loading NLog.config)
- [${configsetting}](https://github.com/NLog/NLog/wiki/ConfigSetting-Layout-Renderer) - Reading from appsetting.json on NetCore
- [${appsetting}](https://github.com/NLog/NLog/wiki/AppSetting-Layout-Renderer) - Reading from app.config on NetFramework.

**Comment by madhusameena** [comment]
Thank you @snakefoot for the information.
