### ISSUE TITLE
When writing to a log file while it is moved to another location, data is lost

### ISSUE THREAD

**Issue by lufi1982** [NLog/NLog#433]
We use nlog component in our application. Logs are created and every hour moved to Archive folder.  Sometimes there is a problem when application is writing too many records to a log file during the time when it is moved to a Archive folder, that a 1KB file containing only one row is created in Archive folder and all logged information is lost. This can be annoying when trying to diagnostic a problem.

Is there any solution to such problem?

**Comment by 304NotModified** [comment]
Please update to a recent version of NLog and re-open this issue if the problem still persists. Thanks
