### ISSUE TITLE
Micro-optimization of null-check with VS2019 

### ISSUE THREAD

**Issue by snakefoot** [NLog/NLog#4335]
Instead of doing this:

`if (layout == null)`

Then it is now faster to do this:

`if (layout is null)`

**Comment by 304NotModified** [comment]
how is this faster? Why isn't that fixed by the compiler? I expect the same IL

**Comment by snakefoot** [comment]
>  The behavior is the same when no overloaded equality operator `operator==` is found

The IL code for `foo is null` uses the ceq instruction to perform a direct reference comparison:

```
IL_0003:  ldloc.0     // foo
IL_0004:  ldnull      
IL_0005:  ceq
```

The IL code for `foo == null` uses a call to the overloaded operator:

```
IL_0016:  ldloc.0     // foo
IL_0017:  ldnull      
IL_0018:  call        UserQuery+Foo.op_Equality
```

**Comment by NammoPillai** [comment]
@snakefoot So, basically throughout the code, we need to replace == null check with is null right.
Can you please assign this to me, I'd like to try this out.

**Comment by snakefoot** [comment]
@NammoPillai Well it seems now that the optimization if mostly relevant for classes/structs that has their own comparison-operators.

But to avoid having to "think" every time then it is better to always apply `is null`. But I would like to have NLog 5.0 RC1 released before making solution-wide refactoring to reduce merge pain with master (But that is just my personal preference).

**Comment by NammoPillai** [comment]
@snakefoot Sure, lets wait until the Nlog 5.0 RC1 is released.
