### ISSUE TITLE
Possible deadlock in AsyncWrapper with Console-Target

### ISSUE THREAD

**Issue by meareindel** [NLog/NLog#4338]
Hi,

We're running into some (same as in #3621) issue with NLog 4.7.6 on a NET 5.0.

We have the following NLog.config:

```
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns:sl="http://www.nlog-project.org/schemas/NLog.Targets.Syslog.xsd"
      autoReload="true"
      throwConfigExceptions="true"
      throwExceptions="false"
      internalLogLevel="Info"
      internalLogToConsole="true">

    <!-- enable asp.net core layout renderers -->
    <extensions>
        <add assembly="NLog.Web.AspNetCore"/>
    </extensions>

    <!-- the targets to write to -->
    <targets>
        <target name="default-async" xsi:type="AsyncWrapper" overflowAction="Block" queueLimit="50000">
            <target xsi:type="Console" name="default" WriteBuffer="true"
                    layout="[${longdate} ${event-properties:item=EventId_Id} ${uppercase:${level}}] ${message} [${mdlc:RequestGuid}] ${logger} ${exception:format=tostring}" />
        </target>
        <target name="own-web-async" xsi:type="AsyncWrapper" overflowAction="Block" queueLimit="50000">
            <target xsi:type="Console" name="own-web" WriteBuffer="true"
                    layout="[${longdate} ${event-properties:item=EventId_Id} ${uppercase:${level}}] ${message} ${aspnet-mvc-action} ${aspnet-request-url} [${mdlc:RequestGuid}] ${logger} ${exception:format=tostring}" />
        </target>
    </targets>

    <!-- rules to map from logger name to target -->
    <rules>
        <logger name="Microsoft.*" writeTo="own-web-async" final="true">
            <filters defaultAction='Log'>
                <when condition="contains('${aspnet-request-url}', '/health/')" action="Ignore" />
                <when condition="ends-with('${aspnet-request-url}', '/metrics')" action="Ignore" />
            </filters>            
        </logger>
        <logger name="*" writeTo="default-async" />
    </rules>
</nlog>
```

Under heavy load (about 10k rps, where single request itself makes many writes) we get a "deadlock" with the following stacktrace:

```
Monitor.Wait() at C:\Users\User\AppData\Roaming\JetBrains\Rider2020.3\resharper-host\SourcesCache\3BB42FD3-8BD8-407B-9667-FBF8CE1367E9\199\Monitor.cs:line 177
Monitor.Wait() at C:\Users\User\AppData\Roaming\JetBrains\Rider2020.3\resharper-host\SourcesCache\3BB42FD3-8BD8-407B-9667-FBF8CE1367E9\199\Monitor.cs:line 197
ConcurrentRequestQueue.WaitForBelowRequestLimit() at C:\Users\User\AppData\Roaming\JetBrains\Rider2020.3\resharper-host\SourcesCache\BC58F7AA-B054-4B56-909C-6485BD28CE06\52\ConcurrentRequestQueue.cs:line 139
ConcurrentRequestQueue.Enqueue() at C:\Users\User\AppData\Roaming\JetBrains\Rider2020.3\resharper-host\SourcesCache\BC58F7AA-B054-4B56-909C-6485BD28CE06\52\ConcurrentRequestQueue.cs:line 106
AsyncTargetWrapper.Write() at C:\Users\User\AppData\Roaming\JetBrains\Rider2020.3\resharper-host\SourcesCache\BC58F7AA-B054-4B56-909C-6485BD28CE06\4E\AsyncTargetWrapper.cs:line 433
AsyncTargetWrapper.WriteAsyncThreadSafe()
Target.WriteAsyncLogEvent()
LoggerImpl.WriteToTargetWithFilterChain()
LoggerImpl.Write()
Logger.WriteToTargets()
Logger.Log()
NLogLogger.Log<Microsoft.Extensions.Logging.LoggerMessage.LogValues<string, string>>()
Logger.<Log>g__LoggerLog|12_0<Microsoft.Extensions.Logging.LoggerMessage.LogValues<string, string>>()
Logger.Log<Microsoft.Extensions.Logging.LoggerMessage.LogValues<string, string>>()
LoggerMessage.<>c__DisplayClass9_0<string, string>.<Define>g__Log|0()
LoggerMessage.<>c__DisplayClass9_0<string, string>.<Define>b__1()
...
```

So no more output in console nor any new request get processed. But I call it a "deadlock" because when I change internalLogLevel to "Debug" then every second a line or few lines get appeared in console:

```
...
[2021-03-01 12:34:55.1975 1 INFO] Request starting HTTP/1.1 POST https://localhost:44302/api/dictionaries/GetDictionariesByRequests application/x-msgpack -  https://localhost/api/dictionaries/GetDictionariesByRequests [] Microsoft.AspNetCore.Hosting.Diagnos
tics
2021-03-01 12:34:56.1904 Debug Async queue is full
2021-03-01 12:34:56.1904 Debug Yielding because the overflow action is Block...
2021-03-01 12:34:56.2039 Debug Blocking because the overflow action is Block...
[2021-03-01 12:34:56.1904 1 INFO] Request starting HTTP/1.1 POST https://localhost:44302/api/dictionaries/GetDictionariesByRequests application/x-msgpack -  https://localhost/api/dictionaries/GetDictionariesByRequests [] Microsoft.AspNetCore.Hosting.Diagnos
tics
2021-03-01 12:34:57.1872 Debug Async queue is full
2021-03-01 12:34:57.1872 Debug Yielding because the overflow action is Block...
2021-03-01 12:34:57.1998 Debug Blocking because the overflow action is Block...
[2021-03-01 12:34:57.1872 1 INFO] Request starting HTTP/1.1 POST https://localhost:44302/api/dictionaries/GetDictionariesByRequests application/x-msgpack -  https://localhost/api/dictionaries/GetDictionariesByRequests [] Microsoft.AspNetCore.Hosting.Diagnos
tics
2021-03-01 12:34:58.1977 Debug Async queue is full
2021-03-01 12:34:58.1977 Debug Yielding because the overflow action is Block...
2021-03-01 12:34:58.2114 Debug Blocking because the overflow action is Block...
...
```

So it is not an issue perhaps but rather some logging overhead and/or misconfigured something. On the other hand when internal log is disabled, there are exactly zero logging output, so it may be considered as a bug.

Anyway it would be nice if the queue limit hit does not block each next write, but the content of queue got processed instead unless it hit 90% of limit or so.

**Comment by snakefoot** [comment]
So it is stuck forever, or does it just take time for the queue with 50.000 items to be emptied?

What happens if you reduce the queue by setting `queueLimit="5000"` ?

**Comment by snakefoot** [comment]
Strange that it changes to a mode where it only writes a single-console-line every 1 second. The `WriteBuffer="true"` should cause it to write many console-lines in a single batch.

**Comment by meareindel** [comment]
> So is it stuck forever, or does it just take time for the queue with 50.000 items to be emptied?
> 
> What happens if you reduce the queue by setting `queueLimit="5000"` ?

It get stuck "forever" almost every time. "Forever" means I've waited for several minutes before terminate it. One time it started writing one line every 0.5-1s.

It seems that with queueLimit="5000" it get stuck faster :) with 50000 it has a period when it writes a pack of lines every second or half, and sometimes even survives one or several 10k requests pack. With 5000 it get stuck very soon from 10k requests start.

I think it is need to be said that I have that issue only locally so far while debugging. I use Rider that has some own console perhaps, not that windows-standard (and I use windows 10, by the way). So it could be no NLog issue at all. 

Will try to make a unit test later.

**Comment by snakefoot** [comment]
How many threads are running, and how many threads are stuck, when this situation occurs?

**Comment by meareindel** [comment]
164 overall threads when I paused debugger first time, 130 of them are stuck. Then (when unpaused) it grows by 1 stuck thread about every 0.5 second - seems like thread pool is starving.

**Comment by snakefoot** [comment]
I guess if you only have 8 cores, and 150 threads are very aggressive around lock-monitors (or spinlocks), then suddenly no threads will be working because CPU is exhausted. Sadly enough I have not figured out how to make a `overflowAction="Block"`-mode that is lock-free and congestion-free.

**Comment by meareindel** [comment]
6 cores with a hyperthreading.

There are no expicit parallel working, just a lot of incoming requests that get processed with more or less one Task at all.

So the solution is to limit somehow overall running tasks count (eg limit incoming requests) or limit the logging output. Thanks!
