### ISSUE TITLE
RichTextBox target autoScroll sometimes crashes

### ISSUE THREAD

**Issue by mikhail-barg** [NLog/NLog#434]
I'm getting this problem when hiding/showing form with the RichTextBox and logging to it simultaneously:
```
Fatal exception System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
   at System.Windows.Forms.UnsafeNativeMethods.ITextRange.ScrollIntoView(Int32 value)
   at System.Windows.Forms.TextBoxBase.ScrollToCaret()
   at NLog.Targets.RichTextBoxTarget.SendTheMessageToRichTextBox(String logMessage, RichTextBoxRowColoringRule rule)
```
After this exception, form does not exist anymore, while the process itself runs.

Any workarounds?

**Comment by 304NotModified** [comment]
We can not fix this without more information. S o closing for now.

**Comment by mikhail-barg** [comment]
Sorry for not answering, but I failed to make a reproducible sample. So it wasprobably failure of my code somehow.

**Comment by 304NotModified** [comment]
NP!  Thanks for the feedback!
