### ISSUE TITLE
Could not load NLog assembly when missing project reference

### ISSUE THREAD

**Issue by arjitkapoor8888** [NLog/NLog#4341]
Hi! Thanks for reporting this bug! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

For .NET Core users, please check the platform support: https://github.com/NLog/NLog/wiki/platform-support

**NLog version**: 4.7.8

**Platform**: .NET Core 3

**Current NLog config** (xml or C#, if relevant)

```xml
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <variable name="LogFilePath" value="C:\Users\kapoarj\Documents\Log"/>
    <targets>
      <target name="LogFileTarget" xsi:type="File" fileName="${LogFilePath}\${logger}\${shortdate}.log" layout="${longdate}|${uppercase:${level}}|${message}" archiveFileName="${LogFilePath}\${logger}\Archive\${shortdate}_{####}.log" maxArchiveFiles="20" archiveAboveSize="100000"/>
    </targets>
    <rules>
      <logger name="Mail" levels="Info,Error,Debug,Trace" writeTo="LogFileTarget"/>
      <logger name="SnowClosure" levels="Info,Error,Debug,Trace" writeTo="LogFileTarget"/>
      <logger name="ZARProcessing" levels="Info,Error,Debug,Trace" writeTo="LogFileTarget"/>
      <logger name="SnowAssignment" levels="Info,Error,Debug,Trace" writeTo="LogFileTarget" />
    </rules>
  </nlog>

```

- What is the current result?
- Getting 'Could not load file or assembly 'NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c'. The system cannot find the file specified.' exception
-
- What is the expected result?
- Log the error
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
- yes
- Please post full exception details (message, stacktrace, inner exceptions)
Message:- 'Could not load file or assembly 'NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c'. The system cannot find the file specified.'

Stacktrace:-    at WPT_Logger.Log.Error(String message, String logger)
   at App1.Program.Main(String[] args) in C:\Users\kapoarj\source\repos\.Net_Core_Applications\App1\Program.cs:line 23

- Are there any workarounds? yes/no
- Is there a version in which it did work? 
-No
- Can you help us by writing an unit test?

[.Net_Core_Applications.zip](https://github.com/NLog/NLog/files/6088769/default.Net_Core_Applications.zip)

**Comment by snakefoot** [comment]
Think you have created the monster of frankenstein.  Right now you have done the following
- Created 2 different solutions where each has their own project
- The App1-project references the output dll directly from the WPT_Logger-project

Instead you should do the following:
- Have one solution that includes both projects
- Add a project references from App1 to WPT_Logger-project. Then all transitive-dependencies in WPT_Logger-project will flow automatically to App1 (Will include NLog).

**Comment by arjitkapoor8888** [comment]
Hi,

Thanks for your help. We have created one solution and inside that create two projects but still getting same error.
[WPT_Automation.zip](https://github.com/NLog/NLog/files/6094543/WPT_Automation.zip)

**Comment by snakefoot** [comment]
Yes you have now completed step 1. Now you just need to complete the two other steps:
- Remove assembly-reference and instead [add project reference](https://www.meziantou.net/visual-studio-tips-and-tricks-add-project-reference-using-drag-drop.htm) from `WPT_AutomationConsolidatedReportScheduler.csproj` to `WPT_Logger.csproj`. Then all transitive-dependencies in WPT_Logger-project will flow automatically to App1 (Will include NLog).
- Extract NLog-configuration from app.config and move it into NLog.config-file in the App1-project.

**Comment by arjitkapoor8888** [comment]
Hi,

We have added the NLog.Config file but that is in read only mode and not able to edit the same. 
[WPT_Automation.zip](https://github.com/NLog/NLog/files/6096511/WPT_Automation.zip)

**Comment by snakefoot** [comment]
Yes the [NLog.config](https://www.nuget.org/packages/NLog.Config/)-nuget-package is a trap and it should never be used. It will be marked obsolete with NLog ver. 5.

Pretty sure I never mentioned anything about installing that nuget-package. I just asked you to add a NLog.config-file to your project, and move the configuration from app.config into that NLog.config-file.

So remove the [NLog.config](https://www.nuget.org/packages/NLog.Config/)-nuget-package, and just create a new file named NLog.config.

Also you have still not changed from direct assembly-reference to a correct project-reference.

**Comment by arjitkapoor8888** [comment]
Hi Kristensen,

Thanks for your help. Issue was resolved now. We have add Nlog.config file and also add project as a reference. 
Can we use the same approach for .Net Framework project also.

**Comment by snakefoot** [comment]
If you continue to use the new project-format, and use `<packagereference>` then it will just work.

If you are using the old project-format for .NetFramework-project then you [need to add this](https://www.hanselman.com/blog/referencing-net-standard-assemblies-from-both-net-core-and-net-framework) for it to "just" work:

`<RestoreProjectStyle>PackageReference</RestoreProjectStyle>`
