### ISSUE TITLE
Consider using PhysicalFileProvider to detect config changes

### ISSUE THREAD

**Issue by meareindel** [NLog/NLog#4348]
Hi!

Current implementation of NLog.config changes detection relies on FileSystemWatcher. There are two issues in dotnet/runtime (https://github.com/dotnet/runtime/issues/25078. https://github.com/dotnet/runtime/issues/36091) that blocks using symlinks for NLog.config with changes detection. We've run into the very same issue - kubernetes configmaps.

There are a PhysicalFileProvider that could detect file changes and - with some manual path correction and when DOTNET_USE_POLLING_FILE_WATCHER is set - could also detect non-symlink file changes in a symlink-directory. So if NLog would use PhysicalFileProvider instead of FileSystemWatcher then at least the workaround proposed in (https://github.com/dotnet/runtime/issues/36091) will work.

**Comment by snakefoot** [comment]
You are welcome to create an extension project that ensure stable reload of NLog.config-files when using `autoReload="true"`.

Alternative you could consider have place [NLog-configuration in appsettings.json](https://github.com/NLog/NLog.Extensions.Logging/wiki/NLog-configuration-with-appsettings.json), where it will rely on Microsoft-Extension-Configuration to perform file-monitoring and reload.

**Comment by meareindel** [comment]
Thanks, will take a look!

**Comment by akovac35** [comment]
> Thanks, will take a look!

Hi. Have you been able to find an approach which works?
