### ISSUE TITLE
LogLevel seems too heavy for its function

### ISSUE THREAD

**Issue by maxima120** [NLog/NLog#4370]
I am sure there is a very good consideration for having LogLevel as it is.. But I feel whatever it is - it must be tramped by performance considerations. Passing class ref in high performance / high throughput systems thousands times per sec should be less efficient than just copying an int to a stack,, Prove me wrong please :)

**Comment by snakefoot** [comment]
Yes it would make more sense to have LogLevel as enum-value. Not sure about the reason for having it as a class.
- Maybe because enum-ToString() is expensive, unless using a helper function.
- Maybe because it should be possible to create own custom LogLevel-objects.

Anyway it would be a breaking change to change it from class to enum. See also #1269

**Comment by maxima120** [comment]
I am not following you notes in the bullet list.. enum to string is only good if you can have custom log level but(!) LogLevel is sealed class so you cant have it customized (unless i am missing something).. also if anyone asks me - I'd prefer not having custom log levels anyway if that means faster logging.. after all practical considerations are as important in this life as theoretical ones.. imo

**Comment by snakefoot** [comment]
@maxima120 Don't think I wrote anywhere in my reply that your suggestion was a bad idea. I just tried to use my imagination to think of reasons  why the choice made to use a class instead of an enum-value.

**Comment by snakefoot** [comment]
It actually started as an enum, but then changed to a class here:

https://github.com/NLog/NLog/commit/663c7df82dc49ded74f0999bfe2d1f4d7a959e66#diff-c6bb1d04c63afe2e41fcdb55c5560bc46eab63f5b03e180fb55e219cbbdbad78

Then later to fix code-analysis warnings, then it was change to be sealed class. But I guess if one changed the constructor to public, then one could create custom LogLevel-values without inheritance. Anyway just my imagination.

**Comment by snakefoot** [comment]
Closing as no apparent performance issue, but could be a candidate for the major refactoring in NLog 6.0
