### ISSUE TITLE
How to log exceptions in to wcf using Nlog

### ISSUE THREAD

**Issue by ssramvinay** [NLog/NLog#438]
Please note that i am trying to save the logs in to wcf service.I am having the below items with me

1.consoleapplication which will have simple exception
2.a wcf service

1.I need the Nlog.config file sample/code to configure the wcf & the wcf service.cs code(how to get the logs in wcf?],need wcf web.config too
2.After i am going to try to insert in to DB via wcf.

Please help as i am searching the answer for the past 2 days & i am unable to get it.Please help asap.
There is a link available but only very few..Also let me know where will logs are stored if i store it on WCF :)

**Comment by 304NotModified** [comment]
I assume that this question is answered. If not, then just re-open the issue.
