### ISSUE TITLE
Microsoft messages still show when I inject NLogLoggerFactory

### ISSUE THREAD

**Issue by TsakiDev** [NLog/NLog#4388]
Hi,

I too see Microsoft logging when I inject `NLogLoggerFactory` similar to #3731.

In the appsettings.json I have:
```json
{
...
        "rules": [
            {
                "logger": "*",
                "minLevels": "Trace",
                "writeTo": "consolelogger"
            },
            {
                "logger": "Microsoft.*",
                "maxLevel": "None", //Also tried Info, Error, etc.
                "final": true
            }
        ]
    },
    "Logging": {
        "IncludeScopes": false,
        "LogLevel": {
            "Default": "None",
            "Microsoft": "None",
            "Microsoft.Hosting.Lifetime": "None",
            "Microsoft.AspNetCore": "None"
        }
    }
}
```

Program.cs:
```cs
public static class Program
    {
        public static void Main(string[] args)
        {
            CreateHostBuilder(args).Build().Run();
        }

        private static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureLogging(logging =>
                {
                    logging.ClearProviders();
                    logging.SetMinimumLevel(LogLevel.Trace);
                })
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                })
                .UseNLog();
    }
```

Startup.cs:
```cs
        public void ConfigureServices(IServiceCollection services)
        {
            NLogBuilder.ConfigureNLog(new NLogLoggingConfiguration(_configuration.GetSection("NLog")));
            services.AddSingleton<ILoggerFactory, NLogLoggerFactory>();
        }
```

- Framework: .Net 5
- NLog: v4.7.9
- NLog.Extensions.Logging: v1.7.2
- NLog.Web.AspNetCore: v4.12.0

**Comment by snakefoot** [comment]
When replacing the Microsoft LoggerFactory with `NLogLoggerFactory`, then it means any configuration of Microsoft LoggerFactory is completely ignored:

```json
    "Logging": {
        "IncludeScopes": false,
        "LogLevel": {
            "Default": "None",
            "Microsoft": "None",
            "Microsoft.Hosting.Lifetime": "None",
            "Microsoft.AspNetCore": "None"
        }
    }
```

The `NLogLoggerFactory` only relies on the NLog-LoggingConfiguration, so you can do this:

```json
    "nlog": {
        "rules": [
            {
                "logger": "Microsoft*",
                "maxLevels": "Warn",
                "final": true
            },
            {
                "logger": "*",
                "minLevels": "Trace",
                "writeTo": "consolelogger"
            }
        ]
    },
```

Notice the rules are evaluated from the top, and if a rules matches and it has `"final": true` then it will capture the output and prevent it from reaching any following rules. See also https://github.com/NLog/NLog/wiki/Configuration-file#rules

Btw. the `NLogProviderOptions` now has a new option `ReplaceLoggerFactory` that allows you to do this:

```
        private static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                })
                .UseNLog(new NLogAspNetCoreOptions() { ReplaceLoggerFactory = true });
```

**Comment by TsakiDev** [comment]
@snakefoot So the `ReplaceLoggerFactory` option does renders this line `services.AddSingleton<ILoggerFactory, NLogLoggerFactory>();` unnecessary?

**Comment by snakefoot** [comment]
Yes using ReplaceLoggerFactory will overwrite the existing in the ServiceProvider


Sent from my Sony Xperia


---- Tsakiridis Ilias wrote ----


@snakefoot<https://github.com/snakefoot> So the ReplaceLoggerFactory option does renders this line services.AddSingleton<ILoggerFactory, NLogLoggerFactory>(); unnecessary?

**Comment by snakefoot** [comment]
Regarding logging rules. Then you seem to ignore my advice about logging rules are evaluated from the top. Notice there is a difference in the order of the rules suggested by me, and those you are repeating to use.


Sent from my Sony Xperia


---- Tsakiridis Ilias wrote ----


@snakefoot<https://github.com/snakefoot> So the ReplaceLoggerFactory option does renders this line services.AddSingleton<http://services.AddSingleton><ILoggerFactory, NLogLoggerFactory>(); unnecessary?

**Comment by TsakiDev** [comment]
@snakefoot 

Ok, I changed the configuration and now I don't get any logging.
```
"rules": [
            {
                "logger": "Microsoft*",
                "maxLevels": "Warn",
                "final": true
            },
            {
                "logger": "*",
                "minLevels": "Trace",
                "writeTo": "consolelogger"
            }
        ]
```

**Comment by snakefoot** [comment]
Are you doing any logging, besides the default logging from Microsoft Framework? Maybe you can attach the solution that reproduces the issue?


Sent from my Sony Xperia


---- Tsakiridis Ilias wrote ----


@snakefoot<https://github.com/snakefoot>

Ok, I changed the configuration and now I don't get any logging.

"rules": [
            {
                "logger": "Microsoft*",
                "maxLevels": "Warn",
                "final": true
            },
            {
                "logger": "*",
                "minLevels": "Trace",
                "writeTo": "consolelogger"
            }
        ]

**Comment by TsakiDev** [comment]
Sure. I have set the Microsoft log max level to Trace so it should print all of the logs, but it only prints the ones produced in the controller.
[WebApplication2.zip](https://github.com/NLog/NLog/files/6254477/WebApplication2.zip)

**Comment by snakefoot** [comment]
> but it only prints the ones produced in the controller.

That is different from "now I don't get any logging."

Think the problem is that you are using `"minLevels": "Trace"` an `"maxLevels": "Warn",`, but the right keyword is `minLevel` and `maxLevel` (without `s`). Like this

```json
"rules": [
            {
                "logger": "Microsoft*",
                "maxLevel": "Warn",
                "final": true
            },
            {
                "logger": "*",
                "minLevel": "Trace",
                "writeTo": "consolelogger"
            }
        ]
```

**Comment by TsakiDev** [comment]
Ok that did it!
Thank you very much for your time.

**Comment by TsakiDev** [comment]
But it is worth mentioning that now that I have set it to Trace levels I don't see Trace logging.
The problem is clearer when I set maxLevel to Info and don't get any info. But when I set it to Debug I get Info messages.
Shouldn't the maxLevel mean that it is also included?

**Comment by snakefoot** [comment]
If you want everything (including Trace-level), then I guess you should just remove the logging-rule from the NLog-config.

If you have ideas for improving the configuration of NLog-logging-rules (preferable without breaking existing behavior), then you are welcome to create a pull-request and show your idea.

**Comment by TsakiDev** [comment]
@snakefoot 

> If you want everything (including Trace-level), then I guess you should just remove the logging-rule from the NLog-config.

Ok but how can I, for example, allow `Microsoft.EntityFrameworkCore.*` and exclude everything else from the `Microsoft.*` namespace?

**Comment by snakefoot** [comment]
I usually put exceptions to the top like this:

```json
"rules": [
            {
                "logger": "Microsoft.EntityFrameworkCore.*",
                "minLevel": "Trace",
                "writeTo": "consolelogger",
                "final": true
            },
            {
                "logger": "Microsoft*",
                "maxLevel": "Warn",
                "final": true
            },
            {
                "logger": "*",
                "minLevel": "Trace",
                "writeTo": "consolelogger"
            }
        ]
```

**Comment by snakefoot** [comment]
NLog 5.0 makes it possible to use `finalMinLevel`:

```json
"rules": [
            {
                "logger": "Microsoft*",
                "finalMinLevel": "Warn"
            },
            {
                "logger": "Microsoft.Hosting.Lifetime",
                "finalMinLevel": "Info"
            },
            {
                "logger": "Microsoft.EntityFrameworkCore*",
                "finalMinLevel": "Trace"
            },
            {
                "logger": "*",
                "minLevel": "Trace",
                "writeTo": "consolelogger"
            }
        ]
```
