### ISSUE TITLE
Example for more complex console .NET Core 2 Console application

### ISSUE THREAD

**Issue by DuelingCats** [NLog/NLog#4397]
Sorry if this is being posted in the wrong place. If it is, please point me in the right direction.

I looked at the tutorial to add nlog for a [.NET Core 2 console application](https://github.com/NLog/NLog/wiki/Getting-started-with-.NET-Core-2---Console-application). The example given is for a simple console application that doesn't have various class files or much complexity. I was wanting to know how to handle a situation where multiple files are involved. I assume the code I have pasted below is not the way it should be used. I didn't see a more complex example involving multiple files, so I wanted to know what the correct way is. It just seems like there would be a lot of boilerplate code at first glance so I assume I am doing it wrong.

The most likely bad way of doing it...

```
public class MyClass
{
    private IConfigurationRoot config { get; set; }
    public MyClass()
    {
        config = new ConfigurationBuilder()
        .SetBasePath(System.IO.Directory.GetCurrentDirectory())
        .AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
        .Build();
    }

    public void DoWork()
    {
        var servicesProvider = Program.BuildDi(config);
        using (servicesProvider as IDisposable)
        {
            var runner = servicesProvider.GetRequiredService<Runner>();

            //Do some work here.
            runner.DoAction("Finished doing some work.");
        }
    }

    public void DoSomeOtherWork()
    {
        var servicesProvider = Program.BuildDi(config);
        using (servicesProvider as IDisposable)
        {
            var runner = servicesProvider.GetRequiredService<Runner>();

            //Do some other work here.
            runner.DoAction("Finished doing some other work.");
        }
    }

    public void DoEvenMoreWork()
    {
        var servicesProvider = Program.BuildDi(config);
        using (servicesProvider as IDisposable)
        {
            var runner = servicesProvider.GetRequiredService<Runner>();

            //Do even more work here.
            runner.DoAction("Finished doing even more work.");
        }
    }
}
```

**Comment by snakefoot** [comment]
@DuelingCats It is fully intentionaly that the NLog NetCore Console Application is super-simple, since all focus is about adding NLog as Microsoft Extension Logging Provider with dependency injection (`AddNLog`) 

Looks like you are not used to dependency injection. If you just want to make a simple NetCore Console Application that uses NLog, then just [read the tuturial for creating NLog.config](https://github.com/NLog/NLog/wiki/Tutorial) and do this:

```c#
namespace ConsoleExample
{
    internal static class Program
    {
        private static void Main()
        {
             NLog.LogManger.GetCurrentClassLogger().Info("Hello World");
             System.Console.ReadLine();
             return 0;
        }
   }
}
```

NLog works fine on NetCore without Microsoft Extension Logging and Microsoft Dependency Injection.

**Comment by snakefoot** [comment]
If you want help with how to write a console-application, then I think StackOverflow is a better place for questions.

**Comment by snakefoot** [comment]
Closing due to lack of input
