### ISSUE TITLE
escapeForwardSlash="false" is not applied for properties when includeAllProperties="true"

### ISSUE THREAD

**Issue by lekrus** [NLog/NLog#4402]
**NLog version**: 4.7.7.-4.7.9.
**Platform**: .Net 4.7 
**Current NLog config** 

```xml
	<layout xsi:type="JsonLayout" escapeForwardSlash="false">
		<attribute name="level" layout="${level:upperCase=true}"/>
		<attribute name="mpath" layout="${event-properties:mpath}"/>
	        <attribute name="props" encode="false" escapeForwardSlash="false">
			<layout xsi:type='JsonLayout' includeAllProperties="true" escapeForwardSlash="false"  />
		</attribute>		
	</layout>
```
- What is the current result?
mpath property is passed explicitly via Dictionary and it contains forward slash

mpath property in "props" nested layout has values with "/" escaped
mpath property defined explicitly via attribute properly doesn't have "/" escaped

```json
 { 
  "level" : "DEBUG", "mpath": "/api/test.ashx" }, 
  "props": { "module": "test", "mpath": "\/api\/test.ashx" } 
}
```

**Comment by snakefoot** [comment]
Created  #4403 to resolve this missing feature.

**Comment by snakefoot** [comment]
Resolved by #4403

**Comment by snakefoot** [comment]
[NLog v4.7.10](https://www.nuget.org/packages/NLog/4.7.10) has been released.

**Comment by lekrus** [comment]
thanks a lot for the quick update and NuGet release!
