### ISSUE TITLE
Consider removing out of support TFMs

### ISSUE THREAD

**Issue by ViktorHofer** [NLog/NLog#4408]
NLog supports a huge set of frameworks and some of those are already out-of-support. Most libraries already target .NET Standard 2.0 or a supported platform that support .NET Standard 2.0 like:

- .NET Core 2.0 and above
- .NET Framework 4.6.1 and above
- UAP10.0.16299

I would suggest to consider dropping support for anything older than .NET Standard 2.0 and .NET Framework < 4.6.1 in favor of a broader API set and a simplified dependency graph. Other open source repositories are dropping support for older targets as well, i.e. xunit v3.

**Comment by snakefoot** [comment]
NLog 5.0 will support the following frameworks:
- Net35
- Net45
- Net46
- NetStandard13
- NetStandard15
- NetStandard20

See also #4274

**Comment by ViktorHofer** [comment]
Got it, thanks.
