### ISSUE TITLE
Let FileTarget compress archived files as they "age"

### ISSUE THREAD

**Issue by jps1** [NLog/NLog#4409]
Being able to archive files is great, and being able to compress archived files is also handy.  However right now, I have to decide between:
1. having the convenience of being able to just grep through the archived files but only saving the archive for a short time
2. having the convenience of being able to just grep through the archived files and using a ton of disk-space
3. compressing the archive, but then every time I want to search for something, I have to unzip files, etc.

Since most of the time, when I'm searching for something, it will be relatively recent, it would be nice to be able to archive files uncompressed, but then once I hit some limit, compress the _oldest_ files (i.e. the ones that would be kicked out of the archive).

So perhaps I might set `maxArchiveFiles` to 10 and a new property, `maxCompressedFiles` to 100.  That way I can keep much more of the logs (retain the ability to search further back), while still usually retaining the convenience of uncompressed logs, all while not requiring a ton more disk-space.

**Comment by snakefoot** [comment]
You are welcome to create a Pull-Request. See also https://github.com/NLog/NLog/issues/3711#issuecomment-559604944

**Comment by snakefoot** [comment]
Closing issue, since not top-priority. But pull-request are ofcouse welcome.
