### ISSUE TITLE
Not clear instrucción Getting started with ASP.NET Core 5

### ISSUE THREAD

**Issue by EliseoPlunker** [NLog/NLog#4411]
The 4 point should be like:
4. Configure appsettings.json / appsettings.Development.json

The Logging configuration specified in appsettings.json overrides any call to SetMinimumLevel. So either remove "Default": or adjust it correctly to your needs.

```
{
  "Logging": {
    "IncludeScopes": false,
    "LogLevel": {
      "Default": "Trace",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information",
      "your-work-space.*":Trace,   //<---IMPORTANT add this line with the work space of your app
    }
  },
  "AllowedHosts": "*"
}
```

see Aliemre's answer in [this SO](https://stackoverflow.com/questions/65436315/nlog-doesnt-log-in-asp-net-core-controller/65438288#65438288)

**Comment by snakefoot** [comment]
You are free to edit the wiki if you have some improvements:

https://github.com/NLog/NLog/wiki/Getting-started-with-ASP.NET-Core-5#4-configure-appsettingsjson--appsettingsdevelopmentjson

Also notice that if you configure RemoveLoggerFactoryFilter=true, then you can completely ignore `appsetting.json` (Will be default with NLog 5.0). See also: https://github.com/NLog/NLog.Extensions.Logging/pull/482

**Comment by snakefoot** [comment]
Closing due to lack of input
