### ISSUE TITLE
NLog - possibility to log only caller source path + line number when available (similar to callsite)

### ISSUE THREAD

**Issue by tapika** [NLog/NLog#4412]
At the moment it's possible to use
`${callsite-filename:includeSourcePath=True}` to get source code path of the one who executed log function (or above based on skip frame), and also it's possible to log line number using `${callsite-linenumber}`.

In theory it's possible to log to output window line like this:

`c:\....myproject\mysource.cs(25): message`

to make this line double clickable in Visual studio output window.

In theory we can use layout like we want, so like this:

`${callsite-filename:includeSourcePath=True}(${callsite-linenumber}): ${message}`

When NLog will work the way I want it to.

However - there is still an issue if caller cannot be determine for some reason, which most probably will render in format:

`(0): message` 
or 
`(): message` depending on how NLog will work in this case.

That's is more or less ok - but you get extra garbage in log.

Also what I've briefly checked NLog - it does creates `new StackTrace` for each call stack resolution - however - 
using `new StackFrame` is generally cheaper than `new StackTrace`, see following link:

https://stackoverflow.com/a/18837390/2338477

So I would propose following - create new `LayoutRenderer` which would be used only for `OutputDebugStringTarget` NLog target, maybe `$(vs_caller)${message}` `$(vs_caller:skipFrame=2)${message}`, which would result in empty string if source code path or line number cannot be resolved, or formatted according as Visual studio requires this, like `<source code path>(<line>): `
(I think extra space at the end is required by visual studio itself).

Benefits:
- Can backtrack from where log entry came from from output window just by double clicking it.
- Faster call stack resolving (Use `new StackFrame` instead `new StackTrace`)
- Less programming on client side related to this functionality.

**Comment by tapika** [comment]
I think path / line resolving needs to be somehow embedded into logging function.

        public void ...logging_function...(...)
        {
            string file = null;
            int line = 0;
            
            if (isVsCallerInfoEnabled)
            { 
                var frame = new StackFrame(1, true);
                file = frame.GetFileName();
                line = frame.GetFileLineNumber();
            }

           if( file != null && line != 0 ) ... do render it ...

1 - maybe could be dynamic parameter. (E.g. to query upper function path / line number).

I've checked also that mono works slightly differently than VS - I think it's ok, as long as developer can hit more or less close to where logging was performed. +- 1 line difference does not matter.

**Comment by tapika** [comment]
Hmm...  Apparently using `OutputDebugString` requires native debug checkbox to be enabled:

https://stackoverflow.com/a/3040362/2338477

`Debug.WriteLine` works out of box, and apprently is already available in `DebugSystemTarget` , but that in a turn is not yet released in nuget package (I have tried 4.7.9).

**Comment by snakefoot** [comment]
I like the idea of being able to jump directly to source-code, by clicking logging-statement in Visual Studio Output-Window.

The NLog CallSite logic uses the StackTrace-object, because it is scanning for the most likely method-info. The skipFrame-option does not always work correctly, especially when async/await-calling-conventions.

But NLog ver. 5 extends the callsite-logic to support [Caller-Member-Attributes](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/attributes/caller-information), that are much faster / better than using `StackFrame` or `StackTrace`. One just needs to call [LogEventInfo.SetCallerInfo](https://nlog-project.org/documentation/v4.7.0/html/M_NLog_LogEventInfo_SetCallerInfo.htm) with the captured input-values.

But it is not "easy" to extend the existing logging-methods to apply Caller-Member-Attributes, so right now NLog ver. 5 only includes `ForLogEvent()`. But I guess NLog v5 could include some extra ILogger-extension-methods, that provides high-performance callsite-capture:

```
TraceCaller(string message, ... caller-member-attributes);
DebugCaller(string message, ... caller-member-attributes);
InfoCaller(string message, ... caller-member-attributes);
WarnCaller(string message, ... caller-member-attributes);
ErrorCaller(string message, ... caller-member-attributes);
FatalCaller(string message, ... caller-member-attributes);
```

**Comment by snakefoot** [comment]
Right now you are purposing two ideas:
- Create layout-renderer that works out of the box with visualstudio-output-window
- Optimizing CallSite capture using StackFrame. Where I think Caller-Member-Attributes are better.

You are welcome to create pull-requests for both, but please keep them separate.

**Comment by tapika** [comment]
Please note that `[CallerFilePath]` provides full source code path only if `Deterministic` option is not enabled.

If you reconfigure project like this:

```
  <PropertyGroup>
    <Deterministic>true</Deterministic>
    <PathMap>$(SolutionDir)=./</PathMap>
  </PropertyGroup>
```

`[CallerFilePath]` will get relative paths with that option enabled.

Suspect same is applicable to `StackTrace / StackFrame` classes.

Visual studio output window will require full file path, so this could be written down as known limitation.

**Comment by snakefoot** [comment]
Have updated https://github.com/NLog/NLog/wiki/Callsite-layout-renderer about relative paths when using `Deterministic`-build-option

**Comment by snakefoot** [comment]
Closing issue, since more about observations.
