### ISSUE TITLE
How to Log only when need (reading config file)

### ISSUE THREAD

**Issue by rspadim** [NLog/NLog#4413]
Hello!

I have a source code like this:
```
if(shouldLogBigMessages)
   Log.Debug("a very long message");
```
I want know if i could populate the shouldLogBigMessages boolean variable from nlog.config file, the idea is if a Logger is being used (probably only with debug) i start to call a function that create a big "dump", and only do this if the config file tell me to do it (avoiding creating a big string without use)

thanks!

**Comment by snakefoot** [comment]
I usually do this:

```c#
private readonly NLog.Logger Logger = NLog.LogManager.GetCurrentClassLogger();
private readonly NLog.Logger BigLogger = NLog.LogManager.GetLogger("BigLogger");

Logger.Debug("Sending Payload");
if (BigLogger.IsDebugEnabled)
{
    var bigPayload = BuildBigPayload();
    BigLogger.Debug(bigPayload);
}
```

Then make explicit logging rule for `logger="BigLogger"`.

**Comment by rspadim** [comment]
interesting, the isdebugenabled is something that nlog parse the xml and know that some logger is using it, right? there's any manual about it? just to check if documentation covers this

thanks!

**Comment by snakefoot** [comment]
Yes the NLog Logger-Name is used to find matching Logging-Rules. See also: https://github.com/NLog/NLog/wiki/Configuration-file#logger-name-filter

**Comment by snakefoot** [comment]
Closing question as resolved.
