### ISSUE TITLE
Microsoft Extension Logging ILogger decorator

### ISSUE THREAD

**Issue by timmvonputtkamer** [NLog/NLog#4417]
Hello, I have the following situation in an ASP.NET Core application: I would like to implement a custom logger (implementing the ILogger interface from Microsoft.Extensions.Logging) whose implementation leverages the logger from NLog (i.e. I want some kind of decorator).

So the reason behind this is that I want to perform some data transformations on the log data before sending it to NLog.

Do you have some suggestion on how I could proceed? At first I considered implementing a custom ILoggerProvider that relies on an NLogLoggerProvider instance being injected in the constructor in order to get my hands on an NLog logger when ILoggerProvider.CreateLogger is called, so I could wrap this logger in my own custom logger class. However with "UseNLog" the NLogLoggerProvider is only registered as an ILoggerProvider in the dependency injection.

**Comment by snakefoot** [comment]
I think you should go in one of these directions:

- Create your own `NLogLoggerProvider` and perform whatever parsing you need, before redirecting to NLog Logger.
- Create your own `NLogLoggerFactory` that can create your own custom Microsoft ILogger-objects where you can perform whatever parsing you need before redirecting to NLog Logger.

See also: https://github.com/NLog/NLog.Extensions.Logging

**Comment by timmvonputtkamer** [comment]
Thank you for your suggestion!
