### ISSUE TITLE
Text cut off when using When layout renderer combined with a colon

### ISSUE THREAD

**Issue by tino1986** [NLog/NLog#444]
In a File target, for example, I'm using a **When** layout renderer like this (simplified example):

    layout="${when:when=1 == 1:inner=Test: Hello}"

I would expect the result to be **Test: Hello**. However, only **Hello** is logged, without **Test:**.

I've already figured out that it has something to do with the colon, and I've tried solving the issue using several methods:

 - Escaping it with \
 - Wrapping it in a Literal layout renderer
 - Replacing it with its ASCII code &#58;
 - Putting it in a separate variable

But none of them seem to work.

**Comment by ie-zero** [comment]
Wiki page (https://github.com/NLog/NLog/wiki/When-Layout-Renderer) updated with the workaround until this issue is resolved.

**Comment by 304NotModified** [comment]
Changing the too short before a release isn't a good idea, so moving to 4.1

**Comment by 304NotModified** [comment]
Also unit test #914 with this case.
