### ISSUE TITLE
NLog WebService target creates too many connections

### ISSUE THREAD

**Issue by isabr85** [NLog/NLog#4447]
NLog version: 4.7.6
Platform: .Net Core 3.1

I have a .NET Core 3.1 service which make use of NLog. Here is my NLog.config code:

```xml
<?xml version="1.0" ?>
<nlog autoReload="true"
      xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <targets>
    <target name="AsyncInformation" xsi:type="AsyncWrapper">
      <target type="WebService"
                  name="ws"
                  url="https://log-api.com/log/v1"
                  protocol="JsonPost">
        <parameter name="">
          <layout xsi:type="newrelic-jsonlayout">
            <attribute name="time" layout="${date}" />
            <attribute name="level" layout="${level:upperCase=true}"/>
            <attribute name="message" layout="${message}" />
            <attribute name="host" layout="${machinename}" />
            <attribute name="ActivityId" layout="${activityId}" />
            <attribute name="processId" layout="${processId}" />
            <attribute name="threadid" layout="${threadid}" />
            <attribute name="event-properties" >
              <layout type="JsonLayout" includeAllProperties="true" maxRecursionLimit="0" escapeForwardSlash="true" />
            </attribute>
            <attribute name="exception" layout="${exception}" />
            <attribute name="traceId" layout="${var:traceId}" />
          </layout>
        </parameter>
        <header name="X-License-Key" layout="${environment:LICENSE_KEY}"/>
      </target>
    </target>
  </targets>
  <rules>
    <logger name="*" minlevel="Information" maxlevel="Error" writeTo="AsyncInformation"/>
  </rules>
</nlog>
```

My service is hosted in Azure and I can see that code is running and I can see also the logs arrive into in my API. Service performance been hit and the CPU usage is very high (most of the time 100%), I have noticed that our open connections have been increased from 700 to 2,000 (which is the maximum amount of allowed connections) which I believe is the source of the performance issue.

I tried to get into NLog source code and noticed that WebService target (which I use) is using HttpWebRequest which I believe is the reason for these huge amount of connections that being opened because the connection is not persistence. I wonder if there is an option use the WebService target but with reusing the connections by keeping the connections alive?

Or there is an option to use HttpClient instead of HttpWebRequest in the WebService target?

Any help would be great.

**Comment by snakefoot** [comment]
See also: https://stackoverflow.com/q/67803384/193178

**Comment by snakefoot** [comment]
Closing this as an "external" issue in NetCoreApp31, that has been fixed with Net50. See also: https://github.com/dotnet/corefx/pull/41462

Alternative you could try out https://github.com/DarekDan/NLog.Targets.HTTP
