### ISSUE TITLE
Compatibility of Nlog between .Netcore 3.1 and .Net framework4.6.2

### ISSUE THREAD

**Issue by chakrapanibeemanaboinaTR** [NLog/NLog#4450]
Hi 

I have class library which is developed in .net core 3.1  where a particular class(named TokenProducer) has a dependency on Ilogger.

This class library (as nuget package) is used in another project which is developed on .net framework 4.6.2. Now i need to inject ilogger dependency to the class TokenProducer mentioned above.

i am able to do it as follows
![image](https://user-images.githubusercontent.com/59600674/120749968-2037ff00-c523-11eb-83df-56b1444440e1.png)

**but how to configure nlog.config section from current project(which is on .Net framwork 4.6.2) to NLogLoggerProvider.?**

please suggest on how to resolve this issue

**Comment by snakefoot** [comment]
`NLogLoggerProvider` will automatically attempt to load the `NLog.config` file if available. Make sure to have configured "Copy if newer".

Notice that the `LoggerFactory` includes a default-loglevel-filter, that you might want to disable and instead depend on the `NLog.config`. You can configure the `LoggerFactory` like this:

```c#
_loggerFactory = LoggerFactory.Create(builder => builder.SetMinimumLevel(Microsoft.Extensions.Logging.LogLevel.Trace).AddNLog()));
_logger = _loggerFactory.CreateLogger<TokenProducer>();
```

**Comment by snakefoot** [comment]
Closed due to inactivity
