### ISSUE TITLE
Missing Trace/Debug Logs Created By Hangfire

### ISSUE THREAD

**Issue by fairking** [NLog/NLog#4451]
Having Asp.Net.Core 3.1 app among with Hangfire background jobs all nlog logs (Trace/Debug/Error) seem to appear in .log file when the code is executed in the main process (eg. http request in controllers).
But when Hangfire is executing a method in separate process (same instance) the only Errors are logged. No Trace or Debug logs. Comparing the Log Factories, all Targets and Rules are the same. Would be nice to debug somehow the logging process and find what is preventing the nlog from writing Trace and Debug messages:
For example I am looking for something like this (if someone knows if it's possible):
```
Logger.OnLog += onLog;

public void onLog(object sender, EventArgs e)
{
   // Check why the log is not passing rules and targets.
}
```

Please find some screenshots at the end of the message.

**NLog version**: 4.7.10

**NLog.Web.AspNetCore**: 4.12.0

**Platform**: .NET Core 3

**Current NLog config** (xml or C#, if relevant)

```c#
// File (https://github.com/NLog/NLog/wiki/File-target)
            {
                var fileMinLevel = LogLevel.FromString(settings.Logging.File);
                if (fileMinLevel != LogLevel.Off)
                {
                    var fileTarget = new NLog.Targets.FileTarget("file")
                    {
                        FileName = Path.Combine(settings.Logging.FileDirectory, "${var:instance_name}_${var:version_number}", "nlog-${shortdate}.log"),
                        KeepFileOpen = true,
                        ConcurrentWrites = true,
                        MaxArchiveFiles = 30,
                        EnableFileDelete = true,
                        Encoding = Encoding.UTF8,
                        Layout = "${date:format=yyyy-MM-dd HH\\:mm\\:ss}|${level:uppercase=true}|${logger:shortName=True}|${exception:format=Type}|${aspnet-user-identity}|${message}${newline}${exception:format=ToString}",
                    };
                    cfg.AddRule(fileMinLevel, LogLevel.Fatal, fileTarget);
                }
            }

            NLog.LogManager.KeepVariablesOnReload = true;

            NLog.LogManager.ThrowConfigExceptions = true;
```

- What is the current result?
Missing Trace/Debug logs

- What is the expected result?
Should be included into the file/console

- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
Yes. There is no any helpful information except of the one bellow:
```
2021-06-04 14:26:52.9389 Debug Trace => console file
2021-06-04 14:26:52.9389 Debug Debug => console file
2021-06-04 14:26:52.9389 Debug Info => console file
2021-06-04 14:26:52.9389 Debug Warn => console file
2021-06-04 14:26:52.9389 Debug Error => console file
2021-06-04 14:26:52.9389 Debug Fatal => console file
```

- Please post full exception details (message, stacktrace, inner exceptions)
No exception thrown by any code.

- Are there any workarounds? yes/no
Not known

- Is there a version in which it did work? 
Not known

- Can you help us by writing an unit test?
I don't know what is the problem, so I cannot write a test without knowing what is the issue.

Few useful screenshots:

LogFactory
![image](https://user-images.githubusercontent.com/13495631/120811976-79645a80-c544-11eb-8265-521eb7faeeef.png)

appsettings.json
![image](https://user-images.githubusercontent.com/13495631/120812066-913bde80-c544-11eb-95c9-e490ae88d807.png)

Console:
![image](https://user-images.githubusercontent.com/13495631/120812262-bcbec900-c544-11eb-92a7-0113c92026a2.png)

Appreciate any help.

**Comment by snakefoot** [comment]
Maybe relevant:

https://github.com/NLog/NLog.Web/wiki/Missing-trace%5Cdebug-logs-in-ASP.NET-Core-3%3F

**Comment by fairking** [comment]
@snakefoot 

I tried it but it didn't help. Is there any way to debug the logging process? Some Events?

**Comment by snakefoot** [comment]
Notice that you modify/update the NLog-LoggingConfiguration at runtime like this:

```
cfg.AddRule(fileMinLevel, LogLevel.Fatal, fileTarget);
```

Then make sure to call this method to "commit" your changes to the NLog-LoggingConfiguration:

```
NLog.LogManager.ReconfigExistingLoggers();
```

**Comment by fairking** [comment]
> Then make sure to call this method to complete the update, and "commit" your changes to the NLog-LoggingConfiguration:
> 
> ```
> NLog.LogManager.ReconfigExistingLoggers();
> ```

Tried but it makes not difference.

**Comment by snakefoot** [comment]
Since NLog it working just fine, then I guess you should go to the Hangfire-support-forum instead, or stackoverflow.

**Comment by fairking** [comment]
> Since NLog it working just fine, then I guess you should go to the Hangfire-support-forum instead, or stackoverflow.

I think it is not Hangfire issue related but rather Microsoft.

Could it be an issue? It says MinLevel: Information
![image](https://user-images.githubusercontent.com/13495631/120902624-45b72c80-c639-11eb-8d53-4fdabd3f5fad.png)

**Comment by snakefoot** [comment]
> I think it is not Hangfire issue related but rather Microsoft.

By default Microsoft-LoggerFactory uses LogLevel.Infomation, if you create the LoggerFactory manually then you can do this:
```
var loggerFactory = LoggerFactory.Create(builder => builder.SetMinimumLevel(Microsoft.Extensions.Logging.LogLevel.Trace).AddNLog()));
```

Again I recommend finding someone that knows about Hangfire and how it works with Microsoft-LoggerFactory.

**Comment by fairking** [comment]
The issue has been solved by changing the following line of code:
Before:
```
public IServiceCollection ConfigureWebServices(IServiceCollection services)
{
    services.AddLogging((logBuilder) => logBuilder.AddNLog());
}

public IServiceCollection ConfigureHangfireServices(IServiceCollection services)
{
    services.AddLogging((logBuilder) => logBuilder.AddNLog());
}
```

After:
```
public IServiceCollection ConfigureWebServices(IServiceCollection services)
{
    services.AddLogging((logBuilder) => logBuilder.AddNLog());
}

public IServiceCollection ConfigureHangfireServices(IServiceCollection services)
{
    services.AddLogging((logBuilder) =>
            {
                logBuilder.AddConfiguration(_cfg.GetSection("Logging")); // Where _cfg is IConfiguration
                logBuilder.AddNLog();
            });
}
```
