### ISSUE TITLE
SpecialFolder directory creation fails

### ISSUE THREAD

**Issue by ancoroc** [NLog/NLog#4460]
Using the file target and the specialfolder option with a subfolder, NLog fails to create the subfolder and a DirectoryNotFoundException is raised. The archive option works fine with the same directory.

**NLog version**: 4.7.9

**Platform**: .Net 4.7.2

**Current NLog config** 

Below, the configuration:
```xml
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="false"
      internalLogLevel="Debug" internalLogFile="${basedir}/Logs/nlog-internal.log">

  <targets>
    <target name="logfile" xsi:type="File"
          layout="${longdate}|${level}|${logger}|${message} ${exception:format=tostring:maxInnerExceptionLevel=5}"
          fileName="${specialfolder:folder=LocalApplicationData:dir=mySubfolder}/${processname}_log.txt"
          archiveEvery="Day"
          archiveFileName="${specialfolder:folder=LocalApplicationData:dir=mySubfolder}/Logs-Archive/${processname}_log_{#}.txt"
          archiveAboveSize="1"
          archiveDateFormat="yyyy-MM-dd"
          replaceFileContentsOnEachWrite="false"
          deleteOldFileOnStartup="false"
          archiveNumbering="DateAndSequence"
          maxArchiveDays="90" />
  </targets>

  <rules>
    <logger name="*" minlevel="Debug" writeTo="logfile" />
  </rules>
</nlog>

```
The directory mySubfolder does not exist. 

- What is the current result?
DirectoryNotFoundException when trying to log to the file target. If I create the folder manually, it works.
The archive directory will be created, even if it does not exist. Seems inconsistent to me since both are expected to behave the same way.

- What is the expected result?
The directory mySubfolder does not exist and therefore is expected to be created automatically. In the same manner as the archive option.

- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
Yes. It gives no hint on any errors.

- Please post full exception details (message, stacktrace, inner exceptions)
Exception thrown: 'System.IO.DirectoryNotFoundException' in mscorlib.dll
A part of the path "C:\Users\myusername\AppData\Local\mySubfolder\myApplicationName_log.txt" could not be found.

- Are there any workarounds? yes/no
Unknown.

- Is there a version in which it did work? 
Obviously https://github.com/NLog/NLog/issues/94 notes it works if no additional path is added after the ${specialfolder} option. 

- Can you help us by writing an unit test?
No

**Comment by snakefoot** [comment]
Cannot reproduce the issue. Tried using your example `NLog.config` at it creates the `mySubfolder` without any issues.

Notice that a `DirectoryNotFoundException` might be thrown, but the exception is handled by NLog, and causes NLog to explicitly create the directory.

Please attach the output from the [NLog InternalLogger](https://github.com/NLog/NLog/wiki/Internal-Logging)

**Comment by ancoroc** [comment]
You are right, I run it in Visual Studio. Ok, I didn't really tried to continue after the exception... Works like charm. Thanks for the clarification.
