### ISSUE TITLE
Make it so there's colors in the text so it doesn't look so bad

### ISSUE THREAD

**Issue by MarcelskyXD** [NLog/NLog#4466]
**NLog version**: 4.7.10

**Platform**: .NET 5

**Current NLog config**: XML

```xml
    <?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <targets>
        <target name="logconsole" xsi:type="Console" />
    </targets>

    <rules>
        <logger name="*" minlevel="Debug" writeTo="logconsole" />
    </rules>
</nlog>
```

**Comment by snakefoot** [comment]
You can take a look at the colored-console:

https://github.com/NLog/NLog/wiki/ColoredConsole-target

Here is an example of how to configure it to be similar to Microsoft Console Logger:

https://github.com/NLog/NLog.Extensions.Logging/wiki/NLog-Console-and-AddConsole

**Comment by snakefoot** [comment]
Have the colored-console solved your issue?
