### ISSUE TITLE
Conditional configuration sections

### ISSUE THREAD

**Issue by jakenuts** [NLog/NLog#4467]
**NLog version**: 4.6
**Platform**: .Net 4.5

 - Why do we need it?

To define an environment specific configurations I can move common elements to include files, but as the order of Variables -> Targets -> Rules is fixed, and the least likely to change is Targets (in the middle), I need to have a two additional files or a nearly complete config file for each environment. With conditional sections, you could define all your Variables, Targets & Rules in a single file which would adapt to the environment (or whatever the conditions are). 

```xml
<nlog>  
    <!-- Default -->
    <variable name="AppId" value="dv-dev" />

    <!-- Environment Override -->
    <section when="${gdc:item=ENV}='Production'">
        <variable name="AppId" value="dv-live" />
    </section>

    <!-- Common across environments -->
    <targets> 
        <target name="MyTarget" xsi:type="MyTarget" layout="...${var:AppId}"/>
    </targets>
    
    <rules>
        <logger name="*" minLevel="Debug" writeTo="MyTarget"/>
    </rules>

    <section when="${gdc:item=ENV}='Production'">
        <rules>
            <logger name="*" minLevel="Info" writeTo="MyTarget"/>
        </rules>
    </section>
</nlog>
```

**Comment by snakefoot** [comment]
Maybe you can make use of include-files:

https://github.com/nlog/NLog/wiki/Configuration-file#include-files

```xml
<nlog>  
    <variable name="AppId" value="dv-dev" />

    <include file="nlog-${gdc:item=ENV}.config" ignoreErrors="true" />

    <targets> 
        <target name="MyTarget" xsi:type="MyTarget" layout="...${var:AppId}"/>
    </targets>
    
    <rules>
        <logger name="*" minLevel="Debug" writeTo="MyTarget"/>
    </rules>
</nlog>
```

Then have the the `NLog-Production.config`:

```xml
<nlog>  
    <variable name="AppId" value="dv-live" />
    
    <rules>
        <logger name="*" minLevel="Info" writeTo="MyTarget"/>
    </rules>
 </nlog>

**Comment by snakefoot** [comment]
Have include-files been able to solve your issue ?

**Comment by jakenuts** [comment]
Thanks, include files are definitely helpful and the ability to parameterized the path is definitely cool, it still would necessitate two additional .config files for each environment (due to the ordering). It might be cool to expand the <include/> tag so it supports a where condition and if you remove the file="" attribute it just includes it's own content inline. 

<include file="my-external-file.config/>

<include when="(condition)">
    <rules>
        <logger name="*" ..>
    </rules>
</include>

Anyhoo, just a thought, it can definitely be achieved with the setup you mentioned so my focus on a single file might not be worth the effort.

**Comment by jakenuts** [comment]
Woot, the appsettings.json route definitely works. 

Using the configs & method below you can configure the default variables/targets/rules then override just variables/rules in production.

```
SetupLogging("development");   
-> TARGET #1 DEFAULT_VALUE Hello there!

SetupLogging("production");
-> TARGET #2 PRODUCTION_VALUE Hello there!
```

```
private static void SetupLogging(string environment)
{
    var config = new ConfigurationBuilder()
        .SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
        .AddJsonFile("nlog.json", optional: false, reloadOnChange: true)
        .AddJsonFile($"nlog.{environment}.json", optional: true)
        .AddEnvironmentVariables().Build();

    var logger = LogManager.Setup()
        .LoadConfigurationFromSection(config)
        .GetCurrentClassLogger();

    logger.Debug("Hello there!");
}
```

nlog.json (the defaults) 

```
{
  "NLog": {
    "autoReload": true,
    "throwConfigExceptions": true,
    "variables": {
      "var_myvar": "DEFAULT_VALUE"
    },
    "targets": {
      "log-trace": {
        "type": "Trace",
        "layout": "TARGET #1 ${var_myvar} ${message}"
      },
      "log-trace2": {
        "type": "Trace",
        "layout": "TARGET #2 ${var_myvar} ${message}"
      }
    },
    "rules": [
      {
        "logger": "*",
        "minLevel": "Trace",
        "writeTo": "log-trace"
      }
    ]
  }
}
```

nlog.production.json
```
{
  "NLog": {
    "variables": {
      "var_myvar": "PRODUCTION_VALUE"
    },
    "rules": [
      {
        "logger": "*",
        "minLevel": "Trace",
        "writeTo": "log-trace2"
      }
    ]
  }
}
```

**Comment by snakefoot** [comment]
Yes when loading NLog-config using Microsoft Extension Configuration, then it is possible to make use of the built-in configuration-override-feature:

https://github.com/NLog/NLog.Extensions.Logging/wiki/NLog-configuration-with-appsettings.json#environment-specific-configuration

Just have to pay attention to case-sensitivity when doing overrides.
