### ISSUE TITLE
NLog Support for Arabic characters

### ISSUE THREAD

**Issue by sonisp** [NLog/NLog#4472]
Hi!

I am using Nlog, Nlog.config & Nlog.schema all ver  4.7.10 running on platform .NET 4.5.2 on a WebAPI Project.

I have it up and running fine But I find that the "Text" that I log sometimes need to be ARABIC text. When I check the Logs, I find these Arabic Text shown as **???**. I believe this is related to Unicode UTF-8. How do I set this for Nlog logs.

Attaching a sample log for reference.
[2021-06-20.log](https://github.com/NLog/NLog/files/6698701/2021-06-20.log)
 

Thanks.
Regards,

**Comment by snakefoot** [comment]
Please include the contents of your `NLog.config`-file.

**Comment by sonisp** [comment]
Hi 
Please find attached the NLog.config.  I have just renamed the file extension from **.log** to **.txt**
[NLog.txt](https://github.com/NLog/NLog/files/6699365/NLog.txt)


Rgds,

**Comment by snakefoot** [comment]
Have you tried specifying the `Encoding` for the [NLog FileTarget](https://github.com/nlog/NLog/wiki/File-target) ?
```xml
    <target xsi:type="File" name="MyAppLoggerTarget" fileName="${basedir}/logs/${shortdate}.log"
           encoding="UTF-8"
           layout="${longdate} ${uppercase:${level}} ${message}" />
```

**Comment by sonisp** [comment]
Hi,
No I hadnt, Thanks for the suggestion. with the encoding attribute it works like a charm. Ty.
