### ISSUE TITLE
Capturing stderr in log file

### ISSUE THREAD

**Issue by luisrr1590** [NLog/NLog#4486]
I'm capturing video stream in my C# code with FFPMPEG.....it is imperative for me to capture FFPMPEG error in my log....however acording to all FFMPEG documentation errors are sended to the console via stderr. 

Needless to say I'm using NLog as my logger.

Since my app is meant to run as a service there is no visible console so I need to capture stderr in my log file, however I can not find the right way of doing it using NLog.

Is there a way of capturing stderr with NLog and a file target??

Thank you

**Comment by snakefoot** [comment]
I guess you can redirect the console-output to a NLog-Logger like this:

```c#
class NLogTextWriter : TextWriter
{
        private readonly NLog.Logger _logger;
        private readonly NLog.LogLevel _logLevel;

        public NLogTextWriter(NLog.Logger logger, NLog.LogLevel logLevel)
        {
            _logger = logger;
            _logLevel = logLevel;
        }

        public override void Write(string value)
        {
             _logger.Log(_logLevel, value);
        }

        public override void WriteLine(string value)
        {
            _logger.Log(_logLevel, value);
        }
}

var orgOutWriter = System.Console.Out;
var orgErrorWriter = System.Console.Error;
try
{
       System.Console.SetOut(new NLogTextWriter(NLog.LogManager.GetLogger("StdOut"), NLog.LogLevel.Info));
       System.Console.SetError(new NLogTextWriter(NLog.LogManager.GetLogger("StdErr"), NLog.LogLevel.Error));

       // Perform magic operation with FFPMPEG
}
finally
{
      System.Console.Out.SetOut(orgOutWriter);
      System.Console.Out.SetError(orgErrorWriter);
}
```

One could probably also just use a [StringWriter](https://docs.microsoft.com/en-us/dotnet/api/system.io.stringwriter) instead of `NLogTextWriter`, and then perform ToString when all done.

**Comment by luisrr1590** [comment]
Thanks for the response....I actually tested your code and it works fine....sending Console.Error.WriteLine does in fact goes through the logger.....however FFMPEG errors are still not getting captured (even though they appear on the console)...but I'm thinking it may be a different problem.

**Comment by snakefoot** [comment]
Guess you could launch FFMPEG in a child-process and then [capture the child-process console-output](https://stackoverflow.com/questions/3642147/redirect-the-output-stdout-stderr-of-a-child-process-to-the-output-window-in/3642517).

Else you can play around with PInvoke of [SetStdHandle](https://stackoverflow.com/questions/57369761/setstdhandle-could-not-redirect-stdout-and-stderr-in-native-dlls-to-files-in-c-s). But don't have much experience with this.
