### ISSUE TITLE
Multiple logfactory instances, is it performance safe?

### ISSUE THREAD

**Issue by raviraj-bhalerao** [NLog/NLog#4490]
Hi!

I am using NLog with .netcore31 web api hosted in IIS10.

[We are following a design](https://www.strathweb.com/2017/04/running-multiple-independent-asp-net-core-pipelines-side-by-side-in-the-same-application/) that allows running parallel and independent pipelines within an application for each application area/branch. 

I would like to configure individual nlog.config files for each of the independent pipeline so that each of them has its own logging configuration and logging filters/targets etc.

I am using following code to configure separate nlog.config for each branch - 

//sample Code - for each branch/pipeline

```c#
    var webHostBuilder = WebHost.CreateDefaultBuilder()
        .ConfigureLogging((hostingContext, logging) =>
        {
            logging.AddNLog(serviceProvider => new LogFactory(nLogConfigFilePathForBranch))
        })
```

I have 18 such branches configured in the application.
I have not used UseNLog() method anywhere in the code.

Under load (200 concurrent requests) the response time of the application is very low and application is stalled for first 4-5 mins and then responds at very slow speed. There is one "Select" query on single view (select 1 record from roughly 500 records) in the functionality.

I also see an error in NLog internal log - "Warn Flush completed with errors Exception: System.TimeoutException: Timeout when flushing all targets, after waiting 15 seconds."

I am using following Nuget pckgs - 

```xml
    <PackageReference Include="NLog" Version="4.7.4" />
    <PackageReference Include="NLog.Web.AspNetCore" Version="4.9.3" />
    <PackageReference Include="NLog.WindowsEventLog" Version="4.7.4" />
```

NLog.Config typically looks like - 

```xml
    <?xml version="1.0" encoding="utf-8" ?>
    <nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" autoReload="true" internalLogLevel="off" internalLogFile="admin.internalLog.txt">
      <extensions>
        <add assembly="NLog.Web.AspNetCore" />
        <add assembly="NLog.WindowsEventLog" />
        <add assembly="Sirius.Api.Platform.Common" />
      </extensions>
      <!-- the targets to write to -->
      <targets>
        <target xsi:type="EventLog" name="apiEventlog" source="Api.Travel" layout="${api-traceidentifier}|${api-userid}|${logger}|${message} ${exception:format=tostring}" Log="Application" machinename="."/>
        <!-- write to file -->
        <target xsi:type="File" name="Api.Travel" fileName="Logs\Api.Travel\${shortdate}.log" keepFileOpen="true" openFileCacheTimeout="120"
            layout="${longdate}|${api-traceidentifier}|${uppercase:${level}}|${api-userid}|${logger}|${message} ${exception:format=tostring}" />
      </targets>
      <!-- rules to map from logger name to target -->
      <rules>
        <logger name="*" minlevel="Info" writeTo="Api.Travel" />
        <!--Skip non-critical Microsoft logs and so log only own logs-->
        <logger name="Microsoft.*" maxLevel="Info"  writeTo="Api.Travel" />
        <logger name="*" minlevel="Warn" writeTo="apiEventlog" />
      </rules>
    </nlog>
```

api-traceidentifier and api-userid are layout renderer as follows - 

```c#
    [LayoutRenderer("api-traceidentifier")]
    [ThreadSafe]
    internal class ApiUserLogin_RequestTokenLayoutRenderer : AspNetLayoutRendererBase
    {
        protected override void Append(StringBuilder builder, LogEventInfo logEvent)
        {
            var httpContext = HttpContextAccessor?.HttpContext;
            if (httpContext == null)
            {
                Guid traceId = System.Diagnostics.Trace.CorrelationManager.ActivityId;
                var identifier = Convert.ToBase64String(traceId.ToByteArray()).Replace("=", "").Replace("+", "-").Replace("/", "_");
                builder.Append(identifier);
            }
            else
            {
                base.Append(builder, logEvent);
            }
        }
        protected override void DoAppend(StringBuilder builder, LogEventInfo logEvent)
        {
            var httpContext = HttpContextAccessor.HttpContext;
            builder.Append(LookupTraceIdentifier(httpContext));
        }
        private string LookupTraceIdentifier(HttpContext httpContext)
        {
            var traceId = Guid.Empty;
            if (Guid.TryParse(httpContext.TraceIdentifier, out traceId))
            {
                return Convert.ToBase64String(traceId.ToByteArray()).Replace("=", "").Replace("+", "-").Replace("/", "_");
            }
            return httpContext.TraceIdentifier;
        }

    }
```

I would like to know if this approach is good, that its performance safe. If not, will pls be able to suggest any different approach please.

**Comment by snakefoot** [comment]
Good job on activating the NLog InternalLogger. The warning about flush-timout is strange, since you should not explictly call `Flush()` so check your source code. Also make sure that you are not constantly assigning new NLog-Configuration. Maybe turn-off `autoreload="true"` to see if something triggers automatic reload.

And to answer your question. There is no problem with having 18 isolated LogFactory-instances.

See also: https://stackoverflow.com/questions/68326235/multiple-logfactory-instances-is-it-performance-safe

**Comment by snakefoot** [comment]
Maybe change this method:

```c#
                Guid traceId = System.Diagnostics.Trace.CorrelationManager.ActivityId;
                var identifier = Convert.ToBase64String(traceId.ToByteArray()).Replace("=", "").Replace("+", "-").Replace("/", "_");
                builder.Append(identifier);
```

So it becomes:


```c#
                Guid traceId = System.Diagnostics.Trace.CorrelationManager.ActivityId;
                if (traceId == Guid.Empty)
                {
                      builder.Append("0000_0000_0000_0000");
                }
                else
                {
                       var identifier = Convert.ToBase64String(traceId.ToByteArray()).Replace("=", "").Replace("+", "-").Replace("/", "_");
                       builder.Append(identifier);
                }
```

Curious why you have this `Convert.ToBase64String` encoding.

**Comment by snakefoot** [comment]
Also make sure that each "branch" uses their own unique FileName-path when using NLog FileTarget (Ex. `fileName="Logs\Api.Travel\${shortdate}.log"` should not be used by all "branches").

**Comment by snakefoot** [comment]
Also change your logging rules so instead of this:

```xml
     <rules>
        <logger name="*" minlevel="Info" writeTo="Api.Travel" />
        <!--Skip non-critical Microsoft logs and so log only own logs-->
        <logger name="Microsoft.*" maxLevel="Info"  writeTo="Api.Travel" />
        <logger name="*" minlevel="Warn" writeTo="apiEventlog" />
      </rules>
```

Then it becomes this:

```xml
     <rules>
        <!--Skip non-critical Microsoft logs and so log only own logs-->
        <logger name="Microsoft.*" maxLevel="Info"  writeTo="Api.Travel" />
        <logger name="*" minlevel="Info" writeTo="Api.Travel" />
        <logger name="*" minlevel="Warn" writeTo="apiEventlog" />
      </rules>
```

**Comment by snakefoot** [comment]
You also have `${api-userid}` maybe update your initial-post with the source-code for that also?

**Comment by snakefoot** [comment]
> Response time of the application is very low and application is stalled for first 4-5 mins and then responds at very slow speed

This is usually a symptom of heavy garbage collection, or that you are constantly reloading NLog-configuration. Both issues that you have to solve in your own source-code.

**Comment by raviraj-bhalerao** [comment]
>>Curious why you have this Convert.ToBase64String encoding. 
Its to trace the logs easily, searching GUID (multiple words separated with -) needs more mouse clicks/keyboard strokes than that for a single string with one word.

Been back from recovery, so late replies.

Thank you so much for you time to reply my question. Will take a look at the suggestions by you.
