### ISSUE TITLE
MappedDiagnosticsLogicalContext.SetScoped is not stackable

### ISSUE THREAD

**Issue by khmylov** [NLog/NLog#4493]
**NLog version**: 4.7.10

**Platform**: .NET Core 5

`MappedDiagnosticsLogicalContext.SetScoped` doesn't provide stack-like behavior, i.e. calling `IDisposable.Dispose()` on the returned value completely removes the value from the logical context, destroying the value from the outer scope.

Example code snippet:
```csharp
using (NLog.MappedDiagnosticsLogicalContext.SetScoped("X", 1)) {
	Console.WriteLine("1. Value = " + NLog.MappedDiagnosticsLogicalContext.Get("X"));
	using (NLog.MappedDiagnosticsLogicalContext.SetScoped("X", 2)) {
		Console.WriteLine("2. Value = " + NLog.MappedDiagnosticsLogicalContext.Get("X"));
	}
	Console.WriteLine("3. Value = " + NLog.MappedDiagnosticsLogicalContext.Get("X"));
}
```

- What is the current result?
```
1. Value = 1
2. Value = 2
3. Value = 
```

- What is the expected result?
```
1. Value = 1
2. Value = 2
3. Value = 1
```

- Are there any workarounds? I can spin up my own stackable AsyncLocal storage decoupled from NLog's contexts and use it instead, but would be great to have the desired behavior in the core library.
- Is there a version in which it did work? No, looking at the code, seems that's the intended original behavior.

I'm not sure whether it's a bug or a deliberate design decision. I guess for majority of the use-cases the current behavior is fine, but it can lead to some obscure bugs in the large codebases. For example, you may have several components adding context info with too generic names like `messageID`. *Silently discarding* values from the outer scope on disposal of the inner scope is an easy way to spend a huge amount of time looking at the "incorrect" logs.

If you think it makes sense to fix it and make contexts "stackable", I could try to make a pull request.

**Comment by snakefoot** [comment]
@khmylov You are not the first to discover this misleading behavior. See also #3820

I have tried to resolve this with #4124, that will be included in NLog 5.0

**Comment by khmylov** [comment]
@snakefoot Great to know, thanks! Looking at the code though, I see that it clones a dictionary each time you push a new set of key-value pairs. Wouldn't it be more CPU and memory efficient to use a single mutable dictionary of stacks/linked lists instead?

**Comment by snakefoot** [comment]
You are very welcome to improve the code. My focus has been to optimize the AsyncLocal-state-handling (Net46 + NetCore). When using the Remoting-Execution-state then one should only store data-types that are native to NetFramework (System-namespace)  and are serializable.

On 13 Jul 2021 22:59, Andrew Khmylov ***@***.***> wrote:

@snakefoot<https://github.com/snakefoot> Great to know, thanks! Looking at the code though, I see that it clones a dictionary each time you push a new set of key-value pairs. Wouldn't it be more CPU and memory efficient to use a single mutable dictionary of stacks/linked lists instead?
