### ISSUE TITLE
Getting EF Core to use DbLoggerCategory  with NLogLoggerProvider

### ISSUE THREAD

**Issue by ddemland** [NLog/NLog#4494]
I am trying to log information from Entity Framework Core and we use NLog for all our logging. I want to have information from EF logged using NLog. What I have found so far (and it works) is to define a static LoggerFacctory:

`public static readonly LoggerFactory m_myLoggerFactory = new LoggerFactory(new[] { new NLogLoggerProvider()});`

I then load the NLog LogManager with the NLog configuration file:

`NLog.LogManager.LoadConfiguration("nlog.config");`

I then set the DbContextOptionsBuilder to use the logger factory:

```c#
options = new DbContextOptionsBuilder<PublixInventoryContext>()
         .UseLoggerFactory(m_myLoggerFactory)
         .UseSqlServer(connectionStr,
              x => x.MigrationsAssembly("PublixInventory.DataAccess"))
         .Options
```
The issue is that this logs all information from EF. In many cases this is too much information and I have a hard time finding what I am looking for in the logs. What I would like to do is allow the message level to be set to a DbLoggerCategory level. For example:

```C#
public static readonly Microsoft.Extensions.Logging.ILoggerFactory _myLoggerFactory =
        new LoggerFactory(new[] { new
         Microsoft.Extensions.Logging.Console.ConsoleLoggerProvider((category, level) =>
              level >= LogLevel.Trace
         , false, false)
});
```
The problem is I do not see away to set EF to this log level when I am using the NLogLoggerProvider. How do I set EF to the DbLoggerCategory level I wish to use for EF logging?

Thank You,

David Demland

**Comment by snakefoot** [comment]
Yes the `NLogLoggerProvider´ contains no filtering, but expects the filtering to happen through the [NLog-LoggingRules](https://github.com/NLog/NLog/wiki/Configuration-file#rules) in the NLog-Configuration.

You can ofcourse create your own wrapper around the `NLogLoggerProvider´, where you can explicit specify the LogLevel.

**Comment by ddemland** [comment]
I am sorry, but I do not understand how to make either of these solutions work. First of all, it seems that the NLog-LoggingRules assume NLog level settings. Based off of the information at: https://www.entityframeworktutorial.net/efcore/logging-in-entityframework-core.aspx Entity Framework filtering of:

DbLoggerCategory.Database.Command
DbLoggerCategory.Database.Connection
DbLoggerCategory.Database.Transaction
DbLoggerCategory.Infrastructure
DbLoggerCategory.Migrations
DbLoggerCategory.Model
DbLoggerCategory.Query
DbLoggerCategory.Scaffolding
DbLoggerCategory.Update

is based off of object types. I do not see how NLog can map from these object types to NLog levels. Also, I do not understand how creating a wrapper around the NLogLoggerProvider will allow NLog to see these objects types as NLog levels either. Could you please explain how I can achieve either of these mappings so that I can control the logging level within Entity Framework?

**Comment by snakefoot** [comment]
NLog LoggingRules depends on the Logger-names and the LogLevel-severity. Ex:

```xml
<nlog>
<targets>
       <target name="logconsole" xsi:type="Console" />
</targets>
<rules>
       <logger name="LoggerName*" minlevel="Info" writeTo="logconsole" />
</rules>
</nlog>
```

Look at the output of the `${logger}` to recognize what Logger-names that EF-Core is using, then update the `<rules>` to match those Logger-names.

**Comment by snakefoot** [comment]
`NLogLoggerProvider` implements `ILoggerProvider`. If going down the road of creating your own wrapper with implicit LogLevel-filter, then would do like this:

```c#
class MyWrapperProvider : ILoggerProvider
{
    public MyLoggerProvider(NLogLoggerProvider wrapped, LogLevel filterLevel)
    {
    }
}
```

And then override the necessary methods for performing filtering according to the input `filterLevel`, and when the LogEvents matches the filter, then forward to the `wrapped`-loggerprovider.

**Comment by ddemland** [comment]
Thank you so much. I have it figured out and I can now log EF message I want when I want. You have been a life save.

David

**Comment by snakefoot** [comment]
Closing issue as resolved
