### ISSUE TITLE
.NET Core Console App

### ISSUE THREAD

**Issue by flow-time** [NLog/NLog#4495]
Hi!

If you have a question that the logging isn't working, check the [troubleshooting guide](https://github.com/nlog/nlog/wiki/Logging-troubleshooting) first before posting.
Almost every case is solveble with the internal log

Are you searching for a layout or layout renderer? You could find them [here](https://nlog-project.org/config/)

Stackoverflow is recommend for questions. You could expect a faster response there (but do include all the info below) and the search is better.

For the stackoverfolow the following is recommend:

- Use the tag "nlog"
- Include versions of NLog/NLog.AspNetCore etc.
- Include the platform (.NET 4.5, ASP.NET Core 3 etc)
- Include the current config (xml or code)
- Explain current result
- Explain desired result
- Please post full exception details (message, stacktrace, inner exceptions) in case of an error

**Comment by snakefoot** [comment]
@304NotModified Looks like a bug in the spelling:

> **Stackoverflow** is recommend for questions

> For the **stackoverfolow** the following is recommend:

Maybe also consider changing to StackOverflow.com so people will recognize it as the web-site.

**Comment by 304NotModified** [comment]
@snakefoot feel free to update https://github.com/NLog/NLog/blob/dev/.github/ISSUE_TEMPLATE/question.md :)

**Comment by snakefoot** [comment]
Created #4569
