### ISSUE TITLE
How can i set aspnet-request-port like aspnet-request-url

### ISSUE THREAD

**Issue by pccai** [NLog/NLog#4498]
Hi!

How can i set ${aspnet-request-port} like ${aspnet-request-url} when application url like "http://**.com:8080"?
nlog cannot record 8080 in url.

**Comment by snakefoot** [comment]
Have you tried: `${aspnet-request-url:includePort=true}` ? See also https://github.com/NLog/NLog/wiki/AspNetRequest-Url-Layout-Renderer
