### ISSUE TITLE
JsonLayout includeAllProperties using original object instead of the object transformed by RegisterObjectTransformation 

### ISSUE THREAD

**Issue by prakashguru** [NLog/NLog#4500]
**NLog version**: 6.0.2

**Platform**: .NET Core 5

**Current NLog config** 

```xml
<?xml version="1.0" encoding="utf-8"?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:sl="http://www.nlog-project.org/schemas/NLog.Targets.Syslog.xsd" autoReload="true" internalLogLevel="Warn" internalLogToConsole="true" internalLogFile="./logs/internal-nlog.txt">
    <!-- enable asp.net core layout renderers -->
    <extensions>
        <add assembly="NLog.Web.AspNetCore" />
    </extensions>
    <!-- the targets to write to -->
    <targets>
        <!-- write logs to file  -->
        <target xsi:type="File" name="jsonfile" fileName="./logs/service-json.log" archiveFileName="./logs/archive/app-service-json-${shortdate}.zip" maxArchiveFiles="60" archiveEvery="Day" enableArchiveFileCompression="true">
            <layout xsi:type="JsonLayout" includeAllProperties="true" excludeProperties="EventId,EventId_Id,EventId_Name">
                <attribute name="DateTime" layout="${date:format=o}" />
                <attribute name="Level" layout="${level:upperCase=true}" />
                <attribute name="Application" layout="companyapp" />
                <attribute name="EventId" layout="${event-properties:item=EventId_Id}" />
                <attribute name="EventName" layout="${event-properties:item=EventId_Name}" />
                <attribute name="Category" layout="${logger}" />
                <attribute name="User" layout="${aspnet-user-identity}" />
                <attribute name="OriginIp" layout="${aspnet-request-ip}" />
                <attribute name="Message" layout="${message} ${exception:format=tostring}" />
            </layout>
        </target>
    </targets>
    <!-- rules to map from logger name to target -->
    <rules>
        <logger name="Quartz.*" maxlevel="Info" final="true" />
        <logger name="Microsoft.Hosting.Lifetime" minlevel="Info" writeTo="console" />
        <logger name="Microsoft.*" maxlevel="Info" final="true" />
        <logger name="*" minlevel="Trace" writeTo="jsonfile" />
    </rules>
</nlog>
```

**C# Configuration**
```csharp
public record StudentData(string Name, string Id);

NLog.LogManager.Setup().SetupSerialization(d => d.RegisterObjectTransformation<StudentData>(
    data => new StudentData(data.Name  + "-Modified", data.Id + "-changed" )
));
```

**C# Code To generate the log**
```csharp
logger.LogInformation("Student data {@data}", new Startup.StudentData("jack", "10"));
```

- What is the current result?
  - { "DateTime": "2021-07-23T21:13:36.8439246+05:30", "Level": "INFO", "Application": "companyapp", "Category": "SyskeySoftlabs.AssetManager.ApiService.Controllers.ConfigController", "User": "Admin", "OriginIp": "127.0.0.1", "Message": "Student data {\"Name\":\"jack-Modified\", \"Id\":\"10-changed\"} ", "data": {"Name":"**jack**", "Id":"**10**"} }
- What is the expected result?
  - { "DateTime": "2021-07-23T21:13:36.8439246+05:30", "Level": "INFO", "Application": "companyapp", "Category": "SyskeySoftlabs.AssetManager.ApiService.Controllers.ConfigController", "User": "Admin", "OriginIp": "127.0.0.1", "Message": "Student data {\"Name\":\"jack-Modified\", \"Id\":\"10-changed\"} ", "data": {"Name":"**jack-modified**", "Id":"**10-changed**"} }
- Are there any workarounds? no

Since I am transforming the object, I would expect the transformed one should be used in the generated logs. I am planning to use the `RegisterObjectTransformation` to strip out the sensitive data from objects before logging. 

Is there any configuration I have to tweak to get the desired behavior?

**Comment by snakefoot** [comment]
[JsonLayout](https://github.com/NLog/NLog/wiki/JsonLayout) has the option `MaxRecursionLimit` where the default value is `0` (zero).

`0` (zero) means that it should not perform object-reflection and only call `ToString()`. Try changing to this instead:

```xml
<layout xsi:type="JsonLayout" maxRecursionLimit="10" includeAllProperties="true" excludeProperties="EventId,EventId_Id,EventId_Name">
  <attribute name="DateTime" layout="${date:format=o}" />
  <attribute name="Level" layout="${level:upperCase=true}" />
  <attribute name="Application" layout="companyapp" />
  <attribute name="EventId" layout="${event-properties:item=EventId_Id}" />
  <attribute name="EventName" layout="${event-properties:item=EventId_Name}" />
  <attribute name="Category" layout="${logger}" />
  <attribute name="User" layout="${aspnet-user-identity}" />
  <attribute name="OriginIp" layout="${aspnet-request-ip}" />
  <attribute name="Message" layout="${message} ${exception:format=tostring}" />
</layout>
```

**Comment by prakashguru** [comment]
@snakefoot Thanks for the swift response! 

Unfortunately that does not seems to fix the problem. The issue still exist. (the original object is still written instead of transformed object)  . 

Also found another strange issue, Seems the object transformation is only invoked once per type! 

For the below two calls,
```csharp
logger.Log(LogLevel.Info, "Student Data 1 {@data}", new StudentData("Jack", "10"));
logger.Log(LogLevel.Info, "Student Data 2 {@data}", new StudentData("Jack3", "11"));
```
The output is, 
```json
{ "DateTime": "2021-07-24T11:10:31.0080054+05:30", "Level": "INFO", "Message": "Student Data 1 {\"Name\":\"Jack-Modified\", \"Id\":\"10-changed\"} ", "data": {"Name":"Jack", "Id":"10"} }
{ "DateTime": "2021-07-24T11:10:31.0618770+05:30", "Level": "INFO", "Message": "Student Data 2 {\"Name\":\"Jack3\", \"Id\":\"11\"} ", "data": {"Name":"Jack3", "Id":"11"} }
```

The first output has transformed object in `message` but not as data
The second output does not transformed the object at all !

Created a sample https://github.com/prakashguru/NlogIssue for easier reference.

**Comment by snakefoot** [comment]
Think NLog is confused that you transform the object into the same type, instead try this:

```c#
// StudentDataModifed inherits from StudentData
public record StudentDataModifed(string Name, string Id)
    : StudentData(data.Name  + "-Modified", data.Id + "-changed");

NLog.LogManager.Setup().SetupSerialization(d => d.RegisterObjectTransformation<StudentData>(
    data => new StudentDataModifed(data.Name, data.Id)
));
```

**Comment by prakashguru** [comment]
Thanks for the hint! It worked for different type/ anonymous types. 

Can we add that to the documentation of the `RegisterObjectTransformation` ? That will definitely help someone.

**Comment by snakefoot** [comment]
Have updated:

https://github.com/NLog/NLog/wiki/How-to-use-structured-logging#Customize-Object-Reflection

> Note when making an override for an object-type, then the returned object-type must be of a different object-type. Because NLog caches the reflection of the return object-type, and afterwards NLog skips checking for transformation for already cached object-types.

Closing as resolved.
