### ISSUE TITLE
JsonLayout with non formatted message

### ISSUE THREAD

**Issue by eshref** [NLog/NLog#4510]
Hi!

I have little problem with JsonLayout

NLog version: 4.7.10
Platform: netcoreapp 3.1

Current Nlog config
```
<target name="jsonFileMw" xsi:type="File" fileName="logs\mw.log"
            archiveAboveSize="10240"
            maxArchiveDays="5"
            archiveNumbering="DateAndSequence"
            archiveEvery="Day"
            enableArchiveFileCompression="true">
      <layout xsi:type="JsonLayout" includeAllProperties="true">
        <attribute name="time" layout="${longdate}" />
        <attribute name="level" layout="${level:upperCase=true}"/>
        <attribute name="message" layout="${message}" />
      </layout>
    </target>
```

my logging code 
`_logger.LogInformation("request received. {RequestUrl} {RequestBody}", "some url", "some body");`
 this logging code produces following log line:

`{ "time": "2021-08-02 15:07:30.8198", "level": "INFO", "message": "request received. some url some body", "RequestUrl": "some url", "RequestBody": "some body" }`

As you can see this adds log properties to message also which means logging same information twice. As a result log file size increases. I just want to keep message simple. Desired output is below:

`{ "time": "2021-08-02 15:07:30.8198", "level": "INFO", "message": "request received. {RequestUrl} {RequestBody}", "RequestUrl": "some url", "RequestBody": "some body" }`

How can I achieve this?

**Comment by snakefoot** [comment]
You can do this:

    <attribute name="messagetemplate" layout="${message:raw=true}" />

See also: https://github.com/NLog/NLog/wiki/Message-Layout-Renderer

See also: https://github.com/NLog/NLog/wiki/How-to-use-structured-logging#output-captured-properties
