### ISSUE TITLE
Lost 5% test coverage in dev

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#4511]
We've lost ~5% coverage, which is huge!

[Master](https://sonarcloud.io/dashboard?id=nlog2):

![image](https://user-images.githubusercontent.com/5808377/129108908-e3d7c096-34e9-4d25-a618-41c9defcd35b.png)

[Dev](https://sonarcloud.io/dashboard?branch=dev&id=nlog2)

![image](https://user-images.githubusercontent.com/5808377/129108984-b5b3c548-261f-4be7-9c59-b597ec580938.png)

It looks like at least the coverage is missing from the database target.

- [master - 86%](https://sonarcloud.io/code?id=nlog2&selected=nlog2%3Asrc%2FNLog%2FTargets%2FDatabaseTarget.cs)
- [dev - 0%](https://sonarcloud.io/code?branch=dev&id=nlog2&selected=nlog2%3Asrc%2FNLog.Database%2FDatabaseTarget.cs)

**Comment by 304NotModified** [comment]
maybe move to https://github.com/coverlet-coverage/coverlet (coverlet.msbuild) and  https://github.com/danielpalme/ReportGenerator for merge coverage files

**Comment by 304NotModified** [comment]
Another option is to setup the test and coverage all in Azure Devops (with the above packages)

**Comment by 304NotModified** [comment]
working on azure devops config -> https://dev.azure.com/NLogLogging/NLog/_build/results?buildId=3260&view=logs&j=275f1d19-1bd8-5591-b06b-07d489ea915a&t=208d5d4b-2a54-5647-6e8f-b71866ba95ee

**Comment by snakefoot** [comment]
Was thinking that after the release of NLog ver. 5.0 then all the individual nuget-packages would be moved into their own isolated repositories.

**Comment by 304NotModified** [comment]
This looks OK:

![image](https://user-images.githubusercontent.com/5808377/129253199-abc1bad7-d43a-4c06-be27-761ef06f6477.png)

**Comment by 304NotModified** [comment]
this is fixed
