### ISSUE TITLE
[Question] How to save changes back to NLog.Config ml file

### ISSUE THREAD

**Issue by LiorBanai** [NLog/NLog#4517]
Hi,
I have a need to update target at run time (basically change log file name location).
I have common nlog.config xml file that is shared between 5 c# net5 services.

The way I plan to do it is to load the file, add new FileTarget and rule and save back the new Configuration to the nlog.config (with all the other services will reload the file since I'm using autoReload=true:
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      internalLogLevel="warn"
      internalLogFile="nlog-internal.nlog">

How can I save the saved back to the file? there is no SaveChanges in the XmlLoggingConfiguration class.

**Comment by snakefoot** [comment]
Think the recommended approach is to modify the XML-config-file, and then just reload from XML-config-file. Instead of modifying the current-configuration and saving to XML-config-file.

See also #57 + #1715 +  #2771 about wanting to serialize current configuration.

**Comment by LiorBanai** [comment]
too bad there is no built-in support for this.
Thanks
