### ISSUE TITLE
Use of JetBrains.Annotations namespaces confuses ReSharper

### ISSUE THREAD

**Issue by kit299** [NLog/NLog#452]
**Issue**

Using the JetBrains.Annotations namespace (see src/NLog/Annotations.cs) fools ReSharper into thinking the current project has a reference to JetBrains.Annotations.dll.

This causes it to add annotations (e.g. [NotNull])  when using quickfixes like "Check for null"
Unfortunately the annotations are internal to NLog.dll so now my project doesn't build.

**Recommended Fix**

~~It is not correct for NLog.dll to contain JetBrains.\* namespaces (even marked internally).
The namespace JetBrains.Annotations should be renamed, perhaps to NLog.Annotations.~~
I don't think this is the right solution - not sure what the fix is.

**Repro steps**

Open Visual Studio (I'm using VS2013 with ReSharper 8.2.3)
Create a new project of type Console Application
Click on the 'args' parameter and use the quickfix "Check parameter for null"
_if (args==null) check_ IS added. No annotation is added.
Project builds successfully.
Remove the _if (args==null) check_
Manage NuGet packages for solution -> Add NLog to your project
Click on the 'args' parameter and use the quickfix "Check parameter for null"
_if (args==null) check_ IS added. [NotNull] is added.
Project does not build.
_"JetBrains.Annotations.NotNullAttribute is inaccessible due to its protection level"_

**Comment by 304NotModified** [comment]
http://blog.jetbrains.com/dotnet/2015/08/12/how-to-use-jetbrains-annotations-to-improve-resharper-inspections/

**Comment by 304NotModified** [comment]
This doesn't seem an issue anymore
