### ISSUE TITLE
how can i do like this in nlog?

### ISSUE THREAD

**Issue by iwenr** [NLog/NLog#4522]
**in serilog:**
```
using (LogContext.PushProperty("a", 1))
{
    log.Information("b={b} a={a}");
    using (LogContext.PushProperty("b", 2))
    {
        log.Information("c={c} b={b} a={a}", 3);
    }
}
```

**output:**
```
[16:51:37 inf] b={b} a=1
[16:51:37 inf] c=3 b=2 a=1
```

thanks!!!

**Comment by snakefoot** [comment]
NLog 4.1 introduced [MDLC](https://github.com/NLog/NLog/wiki/MDLC-Layout-Renderer), so you can do this:

```c#
using (MappedDiagnosticsLogicalContext.SetScoped("a", "1")) {
    log.Info("Hello World");
    using (MappedDiagnosticsLogicalContext.SetScoped("b", "2")) {
         log.Info("Hello Again");
    }
}
```

And then you can have the following console-target:

```xml
<target type="console" layout="${time} ${level} ${message} ${all-event-properties} ${mdlc=a}  ${mdlc=b}" />
```

But where Serilog automatically merges LogContext-properties into the LogEvent-properties (using enricher), then NLog keeps them seperate. But yes it could be nice with a `${all-scope-properties}`. Guess it should be added with NLog 5.0

**Comment by iwenr** [comment]
Grateful！！😊

**Comment by snakefoot** [comment]
Closing the question as answered. I guess any feature-request / pull-request to be created separately.
