### ISSUE TITLE
Can I decrease MemoryStream capacity in FileTarget somehow?

### ISSUE THREAD

**Issue by Crashhp** [NLog/NLog#4558]
Hi!

Here is my target configuration
```
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <targets>
      <target name="logfile" xsi:type="AsyncWrapper" queueLimit="5000" overflowAction="Discard">
        <target xsi:type="File" layout="${message}" keepFileOpen="true" openFileCacheTimeout="30" encoding="UTF-8" createDirs="true" fileName="${appsetting:name=LOG_PATH}${appsetting:name=INSTANCE_NAME}/Logs/${shortdate:universalTime=True}/External/${appsetting:name=INSTANCE_NAME}_API/${logger}_${level}.txt"/>
      </target>
    </targets>
    <rules>
      <logger name="*" minlevel="Trace" writeTo="logfile">
      </logger>
    </rules>
    <extensions>
      <add assembly="NLog.Extended"/>
    </extensions>
  </nlog>
```

FileTarget uses ReusableStreamCreator that internally working with MemoryStream. Turns out that when you log big message, capacity of MemoryStream gets increased and that capacity is never being recalculated as far as I can tell, so there will be wasted memory space after unusually big message.

We could always try slicing up long messages to smaller ones on our side of things so that MemoryStream never becomes big at all. So my question, is there another way to free up memory space taken by MemoryStream with configuration or something?

Sorry for the grammar!

**Comment by snakefoot** [comment]
NLog FileTarget attempts to perform the file-write in single operation as this works with atomtic-append.

I guess NLog could change its logic to throw away "very large" file-streams and string-builders. This is already implemented in `StringBuilderPool`.

But usually the idea is to adapt the reusable-objects to match the actual work-load. What is considered a "big message" for you ? (Notice that #3857 has been implemented to avoid huge object, but it will not protect against a single message)

**Comment by snakefoot** [comment]
I guess you could "cheat" and create your own [custom Target](https://github.com/NLog/NLog/wiki/How-to-write-a-custom-target) that did the following:

```c#
[Target("MyFirst")] 
public sealed class MyFirstTarget: TargetWithLayout 
{
        [RequiredParameter] 
        public string FileName { get; set; }

        protected override void Write(LogEventInfo logEvent) 
        { 
                var logFile = RenderLayout(logEvent, FileName);
                var logMessage = RenderLayout(logEvent, Layout);
                using (var textWriter = File.AppendText(logFile))
                {
                    textWriter.WriteLine(logMessage);
                }
       }
}
```

Alternative one could use the [MethodCallTarget](https://github.com/NLog/NLog/wiki/MethodCall-target) with a lambda.

**Comment by Crashhp** [comment]
I'll keep that in mind, thank you!

**Comment by snakefoot** [comment]
NLog v5.3.3 introduces an upper-limit for the reusable MemoryStream / StringBuilder inside the NLog FileTarget. Thus memory usuage should remain below 15 MByte even after handling a huge LogEvent:

- https://www.nuget.org/packages/NLog/5.3.3
