### ISSUE TITLE
Looks like GlebKdnv have made unwanted wiki changes

### ISSUE THREAD

**Issue by snakefoot** [NLog/NLog#4559]
Example of change made by @GlebKdnv

https://github.com/NLog/NLog/wiki/How-to-write-a-custom-target

![image](https://user-images.githubusercontent.com/11509660/133110595-578d485b-fa35-473f-933f-af1f8bff16e9.png)

Curious if there has been more.

**Comment by GlebKdnv** [comment]
I'm really sorry, my bad, that was definitely unintentional. I don't think there's more.

> Example of change made by @GlebKdnv
> 
> https://github.com/NLog/NLog/wiki/How-to-write-a-custom-target
> 
> ![image](https://user-images.githubusercontent.com/11509660/133110595-578d485b-fa35-473f-933f-af1f8bff16e9.png)
> 
> Curious if there has been more.

**Comment by snakefoot** [comment]
Yes it looks like the only commit:

![image](https://user-images.githubusercontent.com/11509660/133581368-9e37c6c2-b5bf-4f3a-8c97-fc5750a35a49.png)

Will close this as resolved, since the reverted changes has been reverted again.
