### ISSUE TITLE
3.2.0 release (next release)

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#456]
Is there an estimate when 3.1.1 will be released?

Also I'm doubting if 3.1.1 is still an appropriate new version number for the upcoming release; there are a lot of issues solved, even some issues which weren't bugs. Also the release of 3.1.0 is a while ago. IMO it should be 3.2.0.

**Comment by Xharze** [comment]
It has not been released on nuget yet. I'll release it later today. I'm
also update the website.

**Comment by Xharze** [comment]
Version 3.2 have been released on NuGet I'm in the process of updating the website and posting the binarires here on Github

**Comment by 304NotModified** [comment]
:+1:
