### ISSUE TITLE
aspnet-request-headers SingleAsArray=false is not working

### ISSUE THREAD

**Issue by questionablequestion** [NLog/NLog#4562]
**NLog version**: 4.7.11

**NLog.Web.AspNetCore version**: 4.14.0

**Platform**: .NET Core 3

**Current NLog config** (xml or C#, if relevant)

```xml
layout="${aspnet-request-headers:OutputFormat=JSON:SingleAsArray=false}"
```

- What is the current result?
It displays as when SingleAsArray is true.

- What is the expected result?
For headers to be displayed in a single object.

- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
Nothing there.

- Please post full exception details (message, stacktrace, inner exceptions)
/

- Are there any workarounds? yes/no
No

- Is there a version in which it did work? 
Haven't tried older versions.

- Can you help us by writing an unit test?
/

**Comment by snakefoot** [comment]
Yes it could make sense to have an option called `ObjectProperties`, so all headers are formatted as properties for a single object.

**Comment by snakefoot** [comment]
Created https://github.com/NLog/NLog.Web/pull/697

**Comment by questionablequestion** [comment]
You are awesome @snakefoot !
Thank you very much

**Comment by snakefoot** [comment]
[NLog.Web.AspNetCore version: 5.0.0 Preview 3](https://www.nuget.org/packages/NLog.Web.AspNetCore/5.0.0-preview.3) has been released. See also [NLog 5.0 Release Notes](https://nlog-project.org/2021/08/25/nlog-5-0-preview1-ready.html).
