### ISSUE TITLE
Create NLog 5 API docs

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#4567]
https://nlog-project.org/documentation/

For NLog 5

**Comment by 304NotModified** [comment]
Maybe another option is to redirect to fuget

**Comment by snakefoot** [comment]
Some of the "old" targets includes this xml-docs:

```c#
    /// <summary>
    /// Writes log messages to the console.
    /// </summary>
    /// <seealso href="https://github.com/nlog/nlog/wiki/Console-target">Documentation on NLog Wiki</seealso>
```

That gives this result (all the way to the bottom):

![image](https://user-images.githubusercontent.com/11509660/133737767-7439b8ac-5dc3-445e-b319-3996d89f6f04.png)

Think it would be nice to just have the link directly in the Summary:

```c#
    /// <summary>
    /// Writes log messages to the console. <a href="https://github.com/nlog/nlog/wiki/Console-target">See Wiki</a>
    /// </summary>
```

![image](https://user-images.githubusercontent.com/11509660/133738049-4aaae146-4529-4d62-8799-2ac8cce5496e.png)

**Comment by snakefoot** [comment]
I guess I like SandCastle detail level a little better:

https://nlog-project.org/documentation/v4.7.0/html/P_NLog_Config_LoggingRule_LoggerNamePattern.htm

Compared to [fuget.org](https://www.fuget.org/packages/NLog/4.7.11/netstandard2.0/lib/NLog.dll/NLog.Config/LoggingRule#LoggingRule):

![image](https://user-images.githubusercontent.com/11509660/133751441-89b29e0f-3e5a-4f74-b0c1-0d1518f23796.png)

But I do like the direct link to source-code that fuget.org gives.

**Comment by 304NotModified** [comment]
it's live! Thanks @snakefoot 

See https://nlog-project.org/documentation/ and https://nlog-project.org/documentation/v5.0.0
