### ISSUE TITLE
How to configure BufferingWrapper for File output?

### ISSUE THREAD

**Issue by CrazzyMann99** [NLog/NLog#4570]
Hi!

I have a question about log message writing to file. The problem is the message buffer is not working in my project. I think it should work like this: "wait for N messages and then write to the log file".

There's a line in my NLog.config

`<target xsi:type="BufferingWrapper" name="allasync" slidingTimeout="true" bufferSize="1000" flushTimeout="60000">`

So it means we have a 1KB buffer and a 1 minute flash time. If the logger gets some small message less than 1000 bytes in size, it does not write it into the file until a 60 second delay. Right? But in my project, it writes in the log file immediately. Maybe somebody knows what I do wrong?

**Comment by snakefoot** [comment]
Check that your different logging-rules are not writing directly to the file-target, but to the buffering-wrapper named: `allasync`

**Comment by CrazzyMann99** [comment]
it's no logging at all now. Loks like there's something still wrong in my config file 
NLog.config:

  <targets>
    <target xsi:type="BufferingWrapper" name="allasync" slidingTimeout="true" bufferSize="300" flushTimeout="60000">
      <target
      xsi:type="File"
      name="target_trace"
      fileName="${basedir}/Logs_all/Logs_Trace/Trace_${shortdate}.log"
      archiveFileName="${basedir}/Logs_archive/trace_archive_${shortdate}.txt"
      archiveEvery= "Day"
      archiveAboveSize="1000000"
      layout="${longdate} ${uppercase:${level}} ${message}" />
      
      <target xsi:type="Console"
        name="console"
        layout="${longdate} ${uppercase:${level}} ${message}"
        footer="${longdate} ${uppercase:${level}} ${message}"
        header="${longdate} ${uppercase:${level}} ${message}"
        encoding="Encoding"/>
    
    </target>
  </targets>

  <rules>
    <logger name="logger_trace" level="Trace" writeTo="allasync,console" />
  </rules>
  
</nlog>

**Comment by CrazzyMann99** [comment]
`
  <targets>

    
    
    
    <target xsi:type="BufferingWrapper" name="allasync" slidingTimeout="true" bufferSize="300" flushTimeout="60000">
      
      <target
      xsi:type="File"
      name="target_trace"
      fileName="${basedir}/Logs_all/Logs_Trace/Trace_${shortdate}.log"
      archiveFileName="${basedir}/Logs_archive/trace_archive_${shortdate}.txt"
      archiveEvery= "Day"
      archiveAboveSize="1000000"
      layout="${longdate} ${uppercase:${level}} ${message}" />
      
      <target xsi:type="Console"
        name="console"
        layout="${longdate} ${uppercase:${level}} ${message}"
        footer="${longdate} ${uppercase:${level}} ${message}"
        header="${longdate} ${uppercase:${level}} ${message}"
        encoding="Encoding"/>
     
    </target>

  </targets>


  <rules>

    <logger name="logger_trace" level="Trace" writeTo="allasync,console" />
 
  </rules>
  
`

**Comment by CrazzyMann99** [comment]
it's no logging at all now. Loks like there's something still wrong in my config file
NLog.config:

`
<?xml version="1.0" encoding="utf-8" ?>

<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="false"
      internalLogLevel="Off" internalLogFile="c:\temp\nlog-internal.log">
  
  <variable name="myvar" value="myvalue"/>

  <targets>

    
    
    
    <target xsi:type="BufferingWrapper" name="allasync" slidingTimeout="true" bufferSize="300" flushTimeout="60000">
      
      <target
      xsi:type="File"
      name="target_trace"
      fileName="${basedir}/Logs_all/Logs_Trace/Trace_${shortdate}.log"
      archiveFileName="${basedir}/Logs_archive/trace_archive_${shortdate}.txt"
      archiveEvery= "Day"
      archiveAboveSize="1000000"
      layout="${longdate} ${uppercase:${level}} ${message}" />
      
      <target xsi:type="Console"
        name="console"
        layout="${longdate} ${uppercase:${level}} ${message}"
        footer="${longdate} ${uppercase:${level}} ${message}"
        header="${longdate} ${uppercase:${level}} ${message}"
        encoding="Encoding"/>
     
    </target>

  </targets>


  <rules>

    <logger name="logger_trace" level="Trace" writeTo="allasync,console" />
 
  </rules>
  
</nlog>

`

**Comment by snakefoot** [comment]
I can recommend that you enable `throwConfigExceptions="true"`, then you will get an error when using invalid NLog.config.

Notice that `BufferingWrapper` can only wrap a single-target. Now you attempt to wrap both `target_trace` + `console`.

**Comment by CrazzyMann99** [comment]
Yeah. Thank you. I had errors in my config file. Parameter throwConfigExceptions="true" helped me see that. This works:

`
<?xml version="1.0" encoding="utf-8" ?>

<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="false"
      internalLogLevel="Off" internalLogFile="c:\temp\nlog-internal.log"
      throwConfigExceptions="true">
  
  <variable name="myvar" value="myvalue"/>

  <targets>

    
    
    
    <target xsi:type="BufferingWrapper" name="allasync" slidingTimeout="true" bufferSize="50" flushTimeout="500">
      
      <target
      xsi:type="File"
      name="target_trace"
      fileName="${basedir}/Logs_all/Logs_Trace/Trace_${shortdate}.log"
      archiveFileName="${basedir}/Logs_archive/trace_archive_${shortdate}.txt"
      archiveEvery= "Day"
      archiveAboveSize="1000000"
      layout="${longdate} ${uppercase:${level}} ${message}" />
      
      
     
    </target>

  </targets>


  <rules>

    <logger name="logger_trace" level="Trace" writeTo="allasync" />
 
  </rules>
  
</nlog>


`
So it writes to file when there are 50 messages in buffer or untill 0.5 second

**Comment by CrazzyMann99** [comment]
Yeah. Thank you. I had errors in my config file. Parameter throwConfigExceptions="true" helped me see that. This works:


`<?xml version="1.0" encoding="utf-8" ?>

<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="false"
      internalLogLevel="Off" internalLogFile="c:\temp\nlog-internal.log"
      throwConfigExceptions="true">
  
  <variable name="myvar" value="myvalue"/>

  <targets>

    
    
    
    <target xsi:type="BufferingWrapper" name="allasync" slidingTimeout="true" bufferSize="50" flushTimeout="500">
      
      <target
      xsi:type="File"
      name="target_trace"
      fileName="${basedir}/Logs_all/Logs_Trace/Trace_${shortdate}.log"
      archiveFileName="${basedir}/Logs_archive/trace_archive_${shortdate}.txt"
      archiveEvery= "Day"
      archiveAboveSize="1000000"
      layout="${longdate} ${uppercase:${level}} ${message}" />
      
      
     
    </target>

  </targets>


  <rules>

    <logger name="logger_trace" level="Trace" writeTo="allasync" />
 
  </rules>
  
</nlog>
`

So it writes to file when there are 50 messages in buffer or untill 0.5 second

**Comment by CrazzyMann99** [comment]
Yeah. Thank you. I had errors in my config file. Parameter throwConfigExceptions="true" helped me see that. This works:

`
<?xml version="1.0" encoding="utf-8" ?>

<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="false"
      internalLogLevel="Off" internalLogFile="c:\temp\nlog-internal.log"
      throwConfigExceptions="true">

 <variable name="myvar" value="myvalue"/>

  <targets>

    
    
    
    <target xsi:type="BufferingWrapper" name="allasync" slidingTimeout="true" bufferSize="50" flushTimeout="500">
      
      <target
      xsi:type="File"
      name="target_trace"
      fileName="${basedir}/Logs_all/Logs_Trace/Trace_${shortdate}.log"
      archiveFileName="${basedir}/Logs_archive/trace_archive_${shortdate}.txt"
      archiveEvery= "Day"
      archiveAboveSize="1000000"
      layout="${longdate} ${uppercase:${level}} ${message}" />
      
      
     
    </target>

  </targets>


  <rules>

    <logger name="logger_trace" level="Trace" writeTo="allasync" />
 
  </rules>
  
</nlog>

`
So it writes to file when there are 50 messages in buffer or untill 0.5 second

**Comment by CrazzyMann99** [comment]
Yeah. Thank you. I had errors in my config file. My Console logging is not valid with BufferingWrapper. Parameter throwConfigExceptions="true" helped me see that with it's exception. This works now. So it writes log to file when there are 50 messages in buffer or untill 0.5 second

`<?xml version="1.0" encoding="utf-8" ?>

<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="false"
      internalLogLevel="Off" internalLogFile="c:\temp\nlog-internal.log"
      throwConfigExceptions="true">
  
  <variable name="myvar" value="myvalue"/>

  <targets>

    
    
    
    <target xsi:type="BufferingWrapper" name="allasync" slidingTimeout="true" bufferSize="50" flushTimeout="500">
      
      <target
      xsi:type="File"
      name="target_trace"
      fileName="${basedir}/Logs_all/Logs_Trace/Trace_${shortdate}.log"
      archiveFileName="${basedir}/Logs_archive/trace_archive_${shortdate}.txt"
      archiveEvery= "Day"
      archiveAboveSize="1000000"
      layout="${longdate} ${uppercase:${level}} ${message}" />
      
      
     
    </target>

  </targets>


  <rules>

    <logger name="logger_trace" level="Trace" writeTo="allasync" />
 
  </rules>
  
</nlog>
`

**Comment by CrazzyMann99** [comment]
`<?xml version="1.0" encoding="utf-8" ?>

<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="false"
      internalLogLevel="Off" internalLogFile="c:\temp\nlog-internal.log"
      throwConfigExceptions="true">
  
  <variable name="myvar" value="myvalue"/>

  <targets>

    
    
    
    <target xsi:type="BufferingWrapper" name="allasync" slidingTimeout="true" bufferSize="50" flushTimeout="500">
      
      <target
      xsi:type="File"
      name="target_trace"
      fileName="${basedir}/Logs_all/Logs_Trace/Trace_${shortdate}.log"
      archiveFileName="${basedir}/Logs_archive/trace_archive_${shortdate}.txt"
      archiveEvery= "Day"
      archiveAboveSize="1000000"
      layout="${longdate} ${uppercase:${level}} ${message}" />
      
      
     
    </target>

  </targets>


  <rules>

    <logger name="logger_trace" level="Trace" writeTo="allasync" />
 
  </rules>
  
</nlog>
`

**Comment by CrazzyMann99** [comment]
Yeah thank you. It was because of console logging. I have deleted that part of code and it works now.

**Comment by snakefoot** [comment]
Happy that your question could answered. Closing the issue as resolved.
