### ISSUE TITLE
Wikis are super difficult to use

### ISSUE THREAD

**Issue by wf-soft** [NLog/NLog#4581]
I think we should first have a configuration description that can work normally, and then introduce how to configure configurations such as mysql. After watching for a long time, it can hardly work normally. It's a mess, and the provided SQL script can't work normally

**Comment by snakefoot** [comment]
Is there a certain wiki-page you would like to improve?

You are very welcome to create a new wiki-page that shows your ideas, and if it is awesome then lets fix those dificult wiki-pages.
