### ISSUE TITLE
How do you DISABLE NLog internal logging?

### ISSUE THREAD

**Issue by nmg196** [NLog/NLog#4615]
Hi

How do you DISABLE NLog internal logging?  Even if I set it to "Off" it still updates the log file with Trace and Debug level logs.

Here's the start of my NLog.config:
```
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="true"
      internalLogLevel="Off" internalLogFile="${basedir}\App_Data\Logs\nlog-internal.log">

```

Thanks
Nick

**Comment by snakefoot** [comment]
@JettaWan Please create new issue if you have found bug in NLog, and please also fill out the bug-template with the details about how to reproduce.

General questions about NLog are best handled at StackOverflow.com, which has a larger audience.
