### ISSUE TITLE
Formatting lost when logging exception text to a database

### ISSUE THREAD

**Issue by stuarthallows** [NLog/NLog#462]
When logging exceptions to SQL Server formatting is lost on the exception text. Using this directive to format the exception the text is written into the database as a one line string, all newlines being removed.

    <parameter name="@Exception" layout="${exception:format=ToString:maxInnerExceptionLevel=5}" />

However, the same format string used to log to a file preserves the exception formatting, and so keeps things readable.
Losing the formatting makes it much harder to read the exception details.

**Comment by 304NotModified** [comment]
I will look at this, this week.

**Comment by 304NotModified** [comment]
Hi @stuarthallows 

I think this already possible with the `Separator` parameter. (default: space).
