### ISSUE TITLE
WebService target unable to set url from configsetting

### ISSUE THREAD

**Issue by iz0mb** [NLog/NLog#4657]
**NLog version**:  4.7.12
**NLog.Extended**: 4.7.12

**Platform**: .NET 5

**Current NLog config**: XML

```xml
<target type="WebService"
	     name="api"
	     url="${configsetting:name=API.LoggerURL}"
	     protocol="JsonPost" 
	     encoding="UTF-8">
	<parameter name='UserId' type='System.String' layout='${event-properties:UserId}'/>
	<parameter name='EventKey' type='System.String' layout='${event-properties:EventId_Id}'/> 
	<parameter name='Message' type='System.String' layout='${message}'/> 
</target>

```
**appsettings.json:**
```json
{
"API": {
	"BaseURL": "https://localhost:44306/api",
	"LoggerURL":  "https://localhost:44306/api/logger/log"
     }
}
```
**Program.cs:**
```csharp
var _logger = NLog.Web.NLogBuilder.ConfigureNLog("nlog.config").Setup().LoadConfigurationFromAppSettings().GetCurrentClassLogger();
```

- What is the current result?: 
```
Error when setting property 'Url' on WebServiceTarget - UriFormatException: Invalid URI: The URI scheme is not valid. 
```
I know that the value is pulling correctly, because I logged it to a file just fine. It just simply is not working as a URL for the WebService.

- What is the expected result?: Would expect the URL for the target to set to the same as what is found in appsettings.json, the URL works if I hard code it in vs using the configsetting.

**Comment by snakefoot** [comment]
Think it has been resolved with #4291 and available with [NLog 5.0](https://nlog-project.org/2021/08/25/nlog-5-0-preview1-ready.html) (Current [Preview 3](https://www.nuget.org/packages/NLog/5.0.0-preview.3))

**Comment by iz0mb** [comment]
After upgrading to the specified version, I can confirm that this is now working as intended. Thank you for the swift response and for the support of setting the WebTarget URL from the config.

**Comment by snakefoot** [comment]
Thank you for the confirmation that all works with NLog 5.0-preview-3
