### ISSUE TITLE
NLog Integration to S3

### ISSUE THREAD

**Issue by sravi12** [NLog/NLog#4659]
Do you support integrating to AWS S3? If not any plan to support S3 in your road map? Also if we need to integrate to S3 what is your guidance?

**Comment by snakefoot** [comment]
NLog-repository doesn't contain any vendor specific integrations. But if you cannot find anything with google, then one create a [custom target](https://github.com/NLog/NLog/wiki/How-to-write-a-custom-target) and use the `AmazonS3Client`.

**Comment by sravi12** [comment]
sure @snakefoot

**Comment by snakefoot** [comment]
Closing question as resolved. If you find (or build) a nuget-package then you can always post a link here.
