### ISSUE TITLE
Please add Layout Renderer for app settings.

### ISSUE THREAD

**Issue by Petoj87** [NLog/NLog#466]
Please add a Layout Renderer for app settings in the app.config/web.config file.

**Comment by 304NotModified** [comment]
@Petoj87  Can you clarify this request?

**Comment by 304NotModified** [comment]
Proposal: `${aspnet-aspnet:key=test}`

**Comment by 304NotModified** [comment]
I see it's already here: 

` ${appsetting:name=mysetting:default=mydefault} - produces "mydefault" if no appsetting`

In the NLog.Extended, added in NLog 3.0 

So closing this out.

**Comment by Petoj87** [comment]
Oh sorry didn't know about that one, guess it was missing from the documentation but i see now that its added! thanks alot for your effort!

**Comment by 304NotModified** [comment]
Yeah, I recreated it first and then I detected it was already there :P
