### ISSUE TITLE
How to Disable Hangfire logging in NLog?

### ISSUE THREAD

**Issue by Hussein-Dahir** [NLog/NLog#4664]
I am trying to disable Logging with NLog for Hangfire jobs, I tried this but it didn't work:

```
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Hangfire" : "None"
    }
```
I am using ASP.NET Core 3.1 Web API Project

NLog version: 4.7.6

NLog.Web.AspNetCore version: 4.10.0

Hangfire version: 1.7.27

Cannot I disable it from appsettings.json? Instead of using [NLog Logging Rules & Filters](https://github.com/NLog/NLog/wiki/Configure-from-code), or using some custom NoOpLogger for Hangfire like [this](https://stackoverflow.com/questions/52251508/is-there-a-way-to-turn-off-logging-that-hangfire-does-with-serilog/52400244#52400244)??

Note: I am using only one rule for my NLog target:
`var rule= new LoggingRule("*", LogLevel.Trace, LogLevel.Fatal, myCustomTarget)`

StackOverFlow Question:
https://stackoverflow.com/questions/69936676/how-to-disable-hangfire-logging-in-nlog

**Comment by snakefoot** [comment]
This is the NLog-core-repo, and it sounds like a Hangfire support question:

https://docs.hangfire.io/en/latest/configuration/configuring-logging.html

Though I have never used Hangfire then I will be nice. How to do setup Hangfore for logging?

Using this:

`services.AddHangfire(config => config.UseXXXStorage());`

Or this:

`GlobalConfiguration.Configuration.UseNLogLogProvider()`

**Comment by Hussein-Dahir** [comment]
@snakefoot thanks for your help

I used this method:
`services.AddHangfire(config => config.UseSqlServerStorage(Configuration.GetConnectionString("HangfireConnection"));`

and did NOT add any extra config for NLog support like the line you mentioned
`GlobalConfiguration.Configuration.UseNLogLogProvider()`

However, hangfire supports NLog automatically, which mentioned [here](https://docs.hangfire.io/en/latest/configuration/configuring-logging.html#net-framework).

> If your application uses one of the following libraries, no manual action is required in the most cases. Hangfire knows about these loggers and uses reflection to determine the first available one (in the order defined below) and to call the corresponding methods when logging. And since reflection is used, there are no unnecessary package or assembly references.
> 
> Serilog
> NLog
> Log4Net
> EntLib Logging
> Loupe
> Elmah

And yes sure, I checked environment-specific appsettings.json, delete all logging and kept it in one file only to avoid surprises.

Forget to mention that the logging disabled for all levels except for Error level (exception).

To be more specific, the name of the logger that keep logging things is `Hangfire.AutomaticRetryAttribute`,  even though I set it  to "None" for Hangfire in appsettings.

Found its code [here](https://github.com/HangfireIO/Hangfire/blob/master/src/Hangfire.Core/AutomaticRetryAttribute.cs), the log statement is at line 280:

```
_logger.WarnException(
                    $"Failed to process the job '{context.BackgroundJob.Id}': an exception occurred. Retry attempt {retryAttempt} of {Attempts} will be performed in {delay}.",
                    failedState.Exception);
```

I can easily turn it off using some _loggerNamePattern_ with Logging Rules, but I am really wondering why it is acting like this, and suspected it may be a bug in NLog, that's why I opened the issue here, not on Hangfire repo.

**Comment by snakefoot** [comment]
If the logging goes through LibLog instead of Microsoft LoggerFactory, then Microsoft LoggerFactory-filters will not apply.

If you have ideas or suggestions for how to improve NLog, then you are more than wellcome to create pull-requests and share your ideas.

Notice that with NLog 5.0 then NLog will actually try to ignore all Microsoft LoggerFactory-filters by default, and only respect the NLog loggingrules. One can still explicitly enable the old behavior by setting `NLogAspNetCoreOptions.RemoveLoggerFactoryFilter  = false`

**Comment by snakefoot** [comment]
Closing issue since for Hangfire and not for NLog-core. Better to continue the discussion at https://github.com/HangfireIO/Hangfire/issues/1809
