### ISSUE TITLE
How to create CsvLayout with dynamic number of columns

### ISSUE THREAD

**Issue by xiangzi-lucky** [NLog/NLog#4666]
**Nlog.config：**
```xml
    <layout xsi:type="CSVLayout" delimiter="Auto" withHeader="true" >
        <column  name="Index" layout="${event-properties:Index}" />
        <column  name="RecordTime" layout="${event-properties:RecordTime}"/>
        <column  name="CpuUtilization" layout="${event-properties:CpuUtilization}"/>
        <column  name="MemoryUtilization" layout="${event-properties:MemoryUtilization}"/>
```

**code：**
```c#
public static void Info(string dataIndex, string recordTime, string allCpuUtilization, string 
 allMemoryUtilization,Dictionary<string,string> dic)
        {
            LogEventInfo ei = new LogEventInfo(LogLevel.Info, "", "");
            FileTarget ft = new FileTarget("sysinfocsv");
            ei.Properties["Index"] = dataIndex;
            ei.Properties["RecordTime"] = recordTime;
            ei.Properties["CpuUtilization"] = allCpuUtilization;
            ei.Properties["MemoryUtilization"] = allMemoryUtilization;
            CsvLayout csvLayout = new CsvLayout(); ; 
            foreach (KeyValuePair<string,string> item in dic)
            {
                NLog.Layouts.CsvColumn csvColumn = new NLog.Layouts.CsvColumn();
                csvColumn.Name = item.Key;
                csvColumn.Layout = item.Value;
                csvLayout.Columns.Add(csvColumn);
                ei.Properties[item.Key] = item.Value;
            }
            ft.Layout = csvLayout;
            _logger.Log(ei);
```

**issue:**
it show the columns in Nlog.files only ，How to solve this problem，thanks !

**Comment by snakefoot** [comment]
I have no idea what you are trying to accomplish here. Why are you creating a FileTarget dynamically together with the LogEvent?

You should avoid updating the NLog configuration while logging. It should only happen at application-startup, either from NLog.config-file or from building it at runtime.

**Comment by xiangzi-lucky** [comment]
> I have no idea what you are trying to accomplish here. Why are you creating a FileTarget dynamically together with the LogEvent?
> 
> You should avoid updating the NLog configuration while logging. You should only initialize NLog configuration at application-startup, either from NLog.config-file or creating it at runtime.

Before running, I don't know how many columns need to be added to the table. I can only add them at run time, but I don't know how to output the added columns to the CSV file together with the existing columns in the configuration file

**Comment by snakefoot** [comment]
To dynamically add a NLog Target with a custom NLog Layout, then you have to perform 3 steps:
1. Create the custom NLog Layout 
2. Create the NLog Target and assign the custom NLog Layout
3. Add LoggingRule that references the custom NLog Target.

You should make sure not to create many NLog Targets pointing to the same file/resource.

You can also do a combination, where you have the NLog Target defined in NLog.config
1. Lookup the NLog Target from NLog config using `NLog.LogManager.Configuration.FindTargetByName<FileTarget>("myTargetName")`
2. Create the custom NLog Layout and assign to the found NLog Target.

See also: https://github.com/NLog/NLog/wiki/Configure-from-code

**Comment by xiangzi-lucky** [comment]
> To dynamically add a NLog Target with a custom NLog Layout, then you have to perform 3 steps:
> 
> 1. Create the custom NLog Layout
> 2. Create the NLog Target and assign the custom NLog Layout
> 3. Add LoggingRule that references the custom NLog Target.
> 
> You should make sure not to create many NLog Targets pointing to the same file/resource.
> 
> You can also do a combination, where you have the NLog Target defined in NLog.config
> 
> 1. Lookup the NLog Target from NLog config using `NLog.LogManager.Configuration.FindTargetByName<FileTarget>("myTargetName")`
> 2. Create the custom NLog Layout and assign to the found NLog Target.
> 
> See also: https://github.com/NLog/NLog/wiki/Configure-from-code

thanks  you very much。
