### ISSUE TITLE
File target with archive="Hour" isn't starting a new file each hour

### ISSUE THREAD

**Issue by richardcox13** [NLog/NLog#4668]
Hi! Thanks for reporting this bug! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

**NLog version**: (e.g. 4.4.13)
4.7.10
**Platform**: .Net 3.5 / .Net 4.0 / .Net 4.5 / Mono 4 / Xamarin Android / Xamarin iOs / .NET Core 1 / .NET Core 2 / .NET Core 3
.NET 5, on a Linux instance in Azure App Services
**Current NLog config** (xml or C#, if relevant)

### `nlog.common.config`
```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      internalLogLevel="Warn">

  <variable name="FileLayout" value="${longdate:universalTime=true} | ${logger} ${event-properties:item=EventId_Id}| ${uppercase:${level}} | ${when:when='${aspnet-item:variable=__requestSeqNo}'!='':inner=#${aspnet-item:variable=__requestSeqNo} }${message} ${exception:format=tostring}" />
  <variable name="ConsoleLayout" value="${Time} ${logger} ${level}: ${when:when='${aspnet-item:variable=__requestSeqNo}'!='':inner=#${aspnet-item:variable=__requestSeqNo} }${message} ${exception:format=tostring}" />
  <variable name="DebuggerLayout" value="${logger}/${level} ${when:when='${aspnet-item:variable=__requestSeqNo}'!='':inner=#${aspnet-item:variable=__requestSeqNo} }${message} ${exception:format=tostring}" />

  <targets>
    <target xsi:type="File" name="ownFile" fileName="${BaseDir}/web.log"
            archiveFileName="${BaseDir}/web-{####}.log"
            archiveEvery="Hour"
            archiveNumbering="Sequence"
            maxArchiveFiles="100"
            keepFileOpen="true"
            bufferSize="64"
            encoding="utf-8"
            layout="${FileLayout}" />

    <target xsi:type="ColoredConsole"
        name="console"
        layout="${ConsoleLayout}"
        useDefaultRowHighlightingRules="true"
        detectConsoleAvailable="true"
        DetectOutputRedirected="true">
      <!--<highlight-row backgroundColor="Black" condition="level == LogLevel.Info" foregroundColor="Yellow"/>-->
    </target>
    <target xsi:type="Debugger" name="debug" layout="${DebuggerLayout}" />
  </targets>
</nlog>
```

### `nlog.Prod-Azure.config`

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      internalLogFile="/home/LogFiles/ExultantProduction/web-nlog.log">

  <!-- This is used in the included file so needs to be before the include -->
  <variable name="BaseDir" value="/home/LogFiles/ExultantProduction" />

  <include file="nlog.common.config" />

  <targets>
    <target xsi:type="Console"
            name="stdout"
            layout="${ConsoleLayout}" />
  </targets>

  <rules>
    <!-- How to ignore a source at a level -->
    <!--<logger name="DatabaseAccessor" maxlevel="trace" final="true" />-->

    <!--<logger name="*" minlevel="Trace" final="true" />-->
    <logger name="Microsoft.AspNetCore*" minlevel="Trace" final="true" />
    <logger name="*" minlevel="Info" writeTo="stdout" />
    <logger name="*" minlevel="Trace" writeTo="ownFile" />
<!-->
    <logger name="*" minlevel="Trace" writeTo="ownFile,debug" />
  -->
  </rules>
</nlog>
```

- What is the current result?

Logging is being written to the expected file

`/home/LogFiles/ExultantProduction/web.log`

but an archive file is only created sometimes:
```
-rwxrwxrwx 1 nobody nogroup  7820497 Oct  7 03:57 web-0000.log
-rwxrwxrwx 1 nobody nogroup 15458235 Oct 12 16:56 web-0001.log
-rwxrwxrwx 1 nobody nogroup  2410960 Oct 13 11:57 web-0002.log
-rwxrwxrwx 1 nobody nogroup  4570150 Oct 15 00:58 web-0003.log
-rwxrwxrwx 1 nobody nogroup   664175 Oct 15 07:57 web-0004.log
-rwxrwxrwx 1 nobody nogroup  8803684 Oct 19 03:57 web-0005.log
-rwxrwxrwx 1 nobody nogroup  9152474 Oct 22 10:55 web-0006.log
-rwxrwxrwx 1 nobody nogroup 11688278 Oct 26 19:56 web-0007.log
-rwxrwxrwx 1 nobody nogroup 13624803 Oct 31 14:59 web-0008.log
-rwxrwxrwx 1 nobody nogroup 38412297 Nov 11 13:58 web-0009.log
-rwxrwxrwx 1 nobody nogroup  1331319 Nov 12 01:58 web-0010.log
-rwxrwxrwx 1 nobody nogroup   564008 Nov 12 07:58 web-0011.log
-rwxrwxrwx 1 nobody nogroup 10596212 Nov 16 05:57 web-0012.log
-rwxrwxrwx 1 nobody nogroup     1555 Nov 16 13:38 web-nlog.log
-rwxrwxrwx 1 nobody nogroup  1368338 Nov 16 17:00 web.log
```

Some of these coincide with logging into `web-nlog.log` (I have some redundant targets), others seem to be random times. Definitely not hourly!

This config (with a slightly different `$BasePath` works fine on Windows (I have a different config file loaded, but uses the same `nlog.common.config`).

The content of the files is as expected, all the logging seems to be working fine.

- What is the expected result?

A new file each hour, with only 100 kept.

- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?

Yes. On each start (there have only been a few) get:

```
2021-11-16 13:38:13.1300 Info Message Template Auto Format enabled
2021-11-16 13:38:13.7896 Warn Unused target detected. Add a rule for this target to the configuration. TargetName: console
2021-11-16 13:38:13.7998 Warn Unused target detected. Add a rule for this target to the configuration. TargetName: debug
```

- Please post full exception details (message, stacktrace, inner exceptions)

No errors

- Are there any workarounds? yes/no

No

- Is there a version in which it did work? 

This same configuration worked on a deployment under Windows (IIS) previously (on a local machine).

- Can you help us by writing an unit test?

Perhaps? But this does not seem to have a simple reproduction.

**Comment by snakefoot** [comment]
Is the application running continuously or stopping and starting?

Think changing to `internalLogLevel="Debug"` might give a better clue on why archive is not doing as expected.

Notice some Linux-platforms does not support the concept of File-BirthTime/File-CreatedTime, but only File-ModifiedTime.

**Comment by richardcox13** [comment]
> Is the application running continuously or stopping and starting?

No,. Since 2021-10-09 there have been only four starts.

Will look at more debugging tomorrow (I'm on UK time).

> Notice some Linux-platforms does not support the concept of File-BirthTime/File-CreatedTime,

I'll also try archive based on size...

**Comment by richardcox13** [comment]
Switching to `archiveAboveSize` worked. (And also set a larger buffer size: hold over from wanting to see output quickly when debugging).

Suggestion: docs for `archiveEvery` should point out it doesn't work when Unix style platforms!

**Comment by snakefoot** [comment]
If you find something missing in the Wiki-docs, then they are open for editing. I guess you should precise that Linux without support for File-BirthTime is not supported. See also #2745 + #2737

**Comment by snakefoot** [comment]
Created #4675 with better fallback for Linux without BirthTime
