### ISSUE TITLE
NLog reference issue

### ISSUE THREAD

**Issue by nijaguna2018** [NLog/NLog#4674]
I am using NLog ver 4.7.12 in my ASP.NET application running on VS2019 (.net ver 4.7.2). I can build correctly and all is fine,
However when I push the code to GIT and get the code from GIT again the reference in the project shows the Yellow triangle. 

When I build the project the DLL is available and all is fine.

Why is the reference error shown every time?

Thanks

**Comment by snakefoot** [comment]
Think that is nature of Visual Studio + Nuget + Git-Repository. Think package-reference are yellow until Visual Studio have performed initial package-restore.

Pretty sure there is no solution to this behavior, but you are welcome to create an question on Stackoverflow.com or [create feedback issue for Visual Studio](https://developercommunity.visualstudio.com/home).
