### ISSUE TITLE
Internal logging of Failed Watching path when using relative parent directory to basedir

### ISSUE THREAD

**Issue by Tasteful** [NLog/NLog#4678]
When using relative parent path for the basedir .NET5 logging exceptions in the internal logging file, throwing this over and over again most probably have impact on performance.

**NLog version**: 4.7.8

**Platform**: .NET 5, running on Windows 11

**Current NLog config** (xml or C#, if relevant)

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	  autoReload="true"
      throwExceptions="true"
      internalLogLevel="Fatal"
      internalLogFile="../nlog-internal.log"
      >

    <!-- 
    See https://github.com/NLog/NLog/wiki
    for information on customizing logging rules and outputs.
    -->

    <variable name="logDirectory" value="${basedir}.."/>

    <targets async="true">

        <target xsi:type="File"
                name="file"
                fileName="${logDirectory}${dir-separator}messages.log"
                archiveAboveSize="10240000"
                maxArchiveFiles="2"
                maxArchiveDays="1"
                archiveNumbering="Sequence"
		        autoFlush="false"
                cleanupFileName="false"
		        concurrentWrites="false"
		        keepFileOpen="true"
		        openFileCacheTimeout="15"
                openFileFlushTimeout="1"
                layout="${longdate} [App:${appdomain:format=short}] [${activityid}] [${pad:padding=-5:inner=${uppercase:${level}}}] [${threadname}] ${logger} - ${message} ${exception:format=tostring}" />
    </targets>
    <rules>
        <logger name="*" minlevel="Trace" writeTo="file" />
    </rules>

</nlog>
```

- What is the current result?
```
2021-11-24 14:48:57.5853 Error Failed Watching path 'D:\SysWeb\site\wwwroot\..' with file 'D:\SysWeb\site\wwwroot\..\messages.log' for changes. Exception: System.IO.FileNotFoundException: Error reading the D:\SysWeb\site\wwwroot\.. directory.
   at System.IO.FileSystemWatcher.StartRaisingEvents()
   at System.IO.FileSystemWatcher.StartRaisingEventsIfNotDisposed()
   at System.IO.FileSystemWatcher.set_EnableRaisingEvents(Boolean value)
   at NLog.Internal.MultiFileWatcher.Watch(String fileName)
```
Related code https://github.com/NLog/NLog/blob/02c0c9a0e96a97503f3bbcbee02a79584143a0d0/src/NLog/Internal/Files/MultiFileWatcher.cs#L130

- What is the expected result? No error logged and a watcher that are created correctly
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)? Yes, this is from the internal log
- Please post full exception details (message, stacktrace, inner exceptions)
- Are there any workarounds? Maybe, using path that not are outside the current base directory
- Is there a version in which it did work? I haven't try in other versions
- Can you help us by writing an unit test? If I can get a pointer of where the unit test should be placed

**Comment by snakefoot** [comment]
Seems the `FileNotFoundException` comes from non-existing directory:

https://referencesource.microsoft.com/#System/services/io/system/io/FileSystemWatcher.cs,991

```c#
            if (IsHandleInvalid) {
                throw new FileNotFoundException(SR.GetString(SR.FSW_IOError, directory));
            }
```

**Comment by snakefoot** [comment]
Can you reproduce the issue with this pre-release-build (Just put it in local nuget-repository-folder):

https://ci.appveyor.com/project/nlog/nlog/builds/41692202/job/jbu5n8u1n8t388u4/artifacts

If you can, then please post the output from the NLog InternalLogger.

**Comment by Tasteful** [comment]
I have try to reproduce the issue with the `NLog.5.0.0.449-PR4677.nupkg` package but everything looks working there.

Thanks for the fast help and looking forward for the 5.0 release.

**Comment by snakefoot** [comment]
Thank you for testing. Yes also looking forward to getting NLog 5.0 RTM out.
