### ISSUE TITLE
Dynamically create separate NLog files on app startup.

### ISSUE THREAD

**Issue by LeoRis** [NLog/NLog#4679]
Hi all :)

I have a WPF application that has separate classes that represent certain devices.
Each device has 2 buttons - start and stop button.
When clicked, those buttons trigger a method called WriteToFile() that takes a certain message and the device ID as a parameters:

        public static void WriteToFile(string Message, int deviceID)
        {
            switch (deviceID)
            {
                case 1:
                    {
                        deviceOneLogger.Info(Message);
                    }
                    break;
                case 2:
                    {
                        deviceTwoLogger.Info(Message);
                    }
                    break;
                case 3:
                    {
                        deviceThreeLogger.Info(Message);
                    }
                    break;
                case 4:
                    {
                        deviceFourLogger.Info(Message);
                    }
                    break;
                case 5:
                    {
                        deviceFiveLogger.Info(Message);
                    }
                    break;
                default:
                    break;
            }
        }

For the purpose of writing down each event into a log file, I have created the following loggers, and the logfiles are created each time when the application starts based on the number of devices:

NLog.config file:

<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
	  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	  xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
	  autoReload="true"
	  throwExceptions="false"
	  internalLogLevel="Off" internalLogFile="c:\temp\nlog-internal.log">

	<targets>
		<target name="deviceOne"
				xsi:type="File"
				fileName="C:\Loggers\DeviceOneLogger.log"
				layout="${message}${newline}" />
		<target name="deviceTwo"
				xsi:type="File"
				fileName="C:\Loggers\DeviceTwoLogger.log"
				layout="${message}${newline}" />
		<target name="deviceThree"
				xsi:type="File"
				fileName="C:\Loggers\DeviceThreeLogger.log"
				layout="${message}${newline}" />
		<target name="deviceFour"
				xsi:type="File"
				fileName="C:\Loggers\DeviceFourLogger.log"
				layout="${message}${newline}" />
		<target name="deviceFive"
				xsi:type="File"
				fileName="C:\Loggers\DeviceFiveLogger.log"
				layout="${message}${newline}" />
	</targets>

	<rules>
		<logger minlevel="Trace" name="deviceOneLogger" writeTo="deviceOne"/>
		<logger minlevel="Trace" name="deviceTwoLogger" writeTo="deviceTwo"/>
		<logger minlevel="Trace" name="deviceThreeLogger" writeTo="deviceThree"/>
		<logger minlevel="Trace" name="deviceFourLogger" writeTo="deviceFour"/>
		<logger minlevel="Trace" name="deviceFiveLogger" writeTo="deviceFive"/>
	</rules>
</nlog>

And my working class with the loggers:

        private static Logger deviceOneLogger = LogManager.GetLogger("deviceOneLogger");
        private static Logger deviceTwoLogger = LogManager.GetLogger("deviceTwoLogger");
        private static Logger deviceThreeLogger = LogManager.GetLogger("deviceThreeLogger");
        private static Logger deviceFourLogger = LogManager.GetLogger("deviceFourLogger");
        private static Logger deviceFiveLogger = LogManager.GetLogger("deviceFiveLogger");

Everything works smooth.
BUT here, there are only 5 devices now. In some point, I will have 100 devices, and it's redundant to type 100 targets, rules and loggers.
**I am trying to do this dynamically, so every time when a device gets added, the logfile will be dynamically created.**

In my worker class, I tried creating a method, but it's not working:

        public static LoggingConfiguration config = new LoggingConfiguration();
        public static FileTarget fileTarget = new FileTarget();
        public static LoggingRule rule = new LoggingRule("*", LogLevel.Info, fileTarget);

        // Option 1
        public static void NLoggerMethod()
        {
            config.AddTarget("file", fileTarget);

            fileTarget.FileName = "${basedir}/device.log";
            fileTarget.Layout = "${message}${newline}";
            config.LoggingRules.Add(rule);

            LogManager.Configuration = config;
        }

        // Option 2
        public static void NLoggerMethod()
        {
            var logNviewerTarget = new NLogViewerTarget();
            logNviewerTarget.Name = "target";

            // Rule for mapping loggers to target                        
            config.AddTarget(logNviewerTarget);
            config.AddRule(LogLevel.Info, LogLevel.Fatal, logNviewerTarget, loggerNamePattern: "DEVICE"); 

            LogManager.Configuration = config;
        }

Any help would be highly appreciated.

Many thanks and Happy Friday :)

**Comment by snakefoot** [comment]
You should avoid re-assign the existing configuration, since closing/initializing NLog config can cause LogEvents to be dropped
```c#
LogManager.Configuration = config;
```

Instead you should try to "amend" the existing configuration like this:
```c#
// Option 3
public static void AddDeviceTarget(string deviceName)
{
   var fileTarget = new NLog.Targets.FileTarget() { Name = deviceName };
   fileTarget.FileName = "${basedir}/deviceName.log";
   fileTarget.Layout = "${message}${newline}";
   NLog.LogManager.Configuration.AddRule(LogLevel.Info, LogLevel.Fatal, fileTarget, loggerNamePattern: deviceName); 
   NLog.LogManager.ReconfigExistingLoggers();  // "Commit" the update, so the amend takes effect
}
```

**Comment by LeoRis** [comment]
Hello @snakefoot . Thank you very much for your assistance - I've realized that I am doing a re-assign of the existing config and that messes up everything.
My next step would be to find a way to create those files separately for each device. I tried adding the AddDeviceTarget() method in the constructor, but I also need to access the WriteToFile() method each time when a device needs to write down a log. That's a bit tricky, but will keep fighting :)
Thank you one more time!
P.S. if you happen to have any ideas on how to achieve my last question, they would be most welcomed :)

**Comment by snakefoot** [comment]
Guess you could do this, and give the returned Logger-object to the device for logging:

```c#
// Option 3
public static Logger AddDeviceTarget(string deviceName)
{
   var fileTarget = new NLog.Targets.FileTarget() { Name = deviceName };
   fileTarget.FileName = "${basedir}/deviceName.log";
   fileTarget.Layout = "${message}${newline}";
   NLog.LogManager.Configuration.AddRule(LogLevel.Info, LogLevel.Fatal, fileTarget, loggerNamePattern: deviceName); 
   NLog.LogManager.ReconfigExistingLoggers();  // "Commit" the update, so the amend takes effect
   return NLog.LogManager.GetLogger(deviceName); // Give this Logger-object to the device-manager
}
```

Alternative you could use a `ConcurrentDictionary` to map from whatever device-id to the device-logger:

```c#
public static void WriteToFile(string Message, int deviceID)
{
     if (_deviceLoggers.TryGetValue(deviceID, out var logger))
     {
          logger.Info(Message);
     }
}
```

But I think you should continue this adventure with your co-worker, or find some soulmates on StackOverflow.
