### ISSUE TITLE
 LayoutRenderer cannot be found: 'aspnet-user-identity'

### ISSUE THREAD

**Issue by jkmuka** [NLog/NLog#468]
I am getting the error below, I saw this was a previous issue but I am using 3.1.0.0 so I thought the issue should be resolved.

 System.ArgumentException: LayoutRenderer cannot be found: 'aspnet-user-identity'

Here's where I am referencing the layout. I am using ASP.NET MVC 5

<parameter name="@UserName" layout="${aspnet-user-identity}" />

**Comment by Xharze** [comment]
Could you provide the output from the internal debug log?

**Comment by 304NotModified** [comment]
Closing this because of missing information.  Feel free to reopen it this problem still persists.
