### ISSUE TITLE
NuGet server returned 403: The specified API key is invalid, has expired

### ISSUE THREAD

**Issue by snakefoot** [NLog/NLog#4683]
AppVeyor Builds running on dev-branch fails:

`Error publishing package. NuGet server returned 403: The specified API key is invalid, has expired, or does not have permission to access the specified package.`

https://ci.appveyor.com/project/nlog/nlog/builds/41684678/job/qq2fg31w3pkwhos8

**Comment by 304NotModified** [comment]
I will update the key soon :)
