### ISSUE TITLE
.NET 6.0 Version

### ISSUE THREAD

**Issue by robertjb20** [NLog/NLog#4709]
Hi! Thanks for reporting this feature!

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

**NLog version**: Latest

**Platform**: .Net 6.0

 - Why do we need it? Upgrading to the latest .Net version. Does not compile under .Net 6.0 and binaries are too old to be used (.Net 4.5)

**Comment by snakefoot** [comment]
Yes you cannot use NLog.dll built for Net45 with Net60

But when using `<packagereference>` in your csproj-file, then it will automatically use the NLog.dll built for NetStandard2.0 (found inside the NLog-nuget-package), and this works great with Net60.

See also: https://github.com/NLog/NLog/wiki/Getting-started-with-ASP.NET-Core-6

**Comment by robertjb20** [comment]
Good morning.




I cannot compile the source code into binaries (.dll) files. When I open the source code project, it is stuck on .net 4.5 and .net cpre 2.0. Visual Studio deleted these now unsupported versions of .net from my computer and can no longer find them. How can I change the target settings in Visual studio version 2022 so that I can compile your software?




Also, I do not use ASP.Net. I use C# for Desktop applications. It is great and easy to incorporate into them. Can you show an example of this please? Thank you.




Regards,




Robert












Original



From:"Rolf Kristensen"< ***@***.*** &gt;;

Date:2021/12/10 14:28

To:"NLog/NLog"< ***@***.*** &gt;;

CC:"Robert Berridge"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

Subject:Re: [NLog/NLog] .NET 6.0 Version (Issue #4709)







Yes you cannot use NLog.dll built for Net45 with Net60

But when using <packagereference&gt; in your csproj-file, then it will automatically use the NLog.dll built for NetStandard2.0 (found inside the NLog-nuget-package), and this works great with Net60.

See also: https://github.com/NLog/NLog/wiki/Getting-started-with-ASP.NET-Core-6

&amp;mdash;
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by snakefoot** [comment]
The target NetStandard2.0-API is different from NetCore2-platform. The NetStandard2.0-API is "forever", but the NetCore-platfroms will expire after 2 years.

These are the targets NLog currently supports:

https://github.com/NLog/NLog/blob/7701eef6797f409d3c9676416518582533ca230d/src/NLog/NLog.csproj#L6

NLog compiles just fine with VS2022 as shown by AppVeyor-build-server:

https://ci.appveyor.com/project/nlog/nlog/builds/41792993

**Comment by snakefoot** [comment]
Closing question as answer due to inactivity.
