### ISSUE TITLE
Does Log4j impact on Nlog for .Net application?

### ISSUE THREAD

**Issue by ansit2010** [NLog/NLog#4712]
Hi, As currently seen Log4j vulnerability and  Nlog had reference of Log4j. want to know that does it also impact my application as I used Nlog in my application in  .NET and my application is very old using Nlog version 1.0.0.505.
if does then what are the ways to fix it?

**Comment by snakefoot** [comment]
Guess duplicate of #4710

**Comment by 304NotModified** [comment]
See https://github.com/NLog/NLog/security/policy

Highly recommend to update NLog. There are no signs that NLog 1.x is infected, but it also out of support, also for security fixes.
