### ISSUE TITLE
How to write NLog configuration to app.config programmatically with C#

### ISSUE THREAD

**Issue by Stryno** [NLog/NLog#4722]
I need to check whether NLog section exists in my app.config and add it if it doesn't.

The app.config should contain a simple NLog configuration like

<configSections>
<section name="nlog" type="NLog.Config.ConfigSectionHandler, NLog" />
</configSections>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd" autoReload="true" throwExceptions="true" internalLogLevel="Debug" internalLogFile="d:\tmp\nlog-internal.log">

<variable name="myvar" value="myvalue" />
<variable name="globalLevel" value="debug" />

<targets async="true">
    <target name="logfile" xsi:type="File" fileName="${basedir}/logs/${shortdate} mylogfile ${environment:COMPUTERNAME}.log" />
</targets>

<rules>
    <logger name="*" minlevel="${globalLevel}" writeTo="logfile" layout="${longdate} ${level} ${message}" />
</rules>

I cannot seem to find a method in NLog API which writes to config file. I can load the Config in many ways, for example

var config = new NLog.Config.XmlLoggingConfiguration("NLogTest.exe.config");
Then I can add/modify the config adding targets, rules, etc., but how do I write it to my config file?

If there is no method for that, could you provide a class for the nlog CustomSection?

Thank you

**Comment by Stryno** [comment]
It didn't accept the config sample but it's pretty standard

**Comment by snakefoot** [comment]
Thers also wish to serialize the in-memory NLog-configuration and save to file: #4517 

I would probably focus on saving NLog-config-variables into a custom NLog-user.config and then have standard NLog.config including the user-file: github.com/NLog/NLog/wiki/XML-config-include-Example
