### ISSUE TITLE
Skip generating complex log-output unlesss loglevel is enabled

### ISSUE THREAD

**Issue by SuRGeoNix** [NLog/NLog#4753]
Hi,

I'm considering integrating one of my libraries with NLog. My only hesitation is that it might add a lot of performance weight. It would be great if it already supports the following. 

Let's say I've my loglevel configuration to Info and there is a part of the code that logs this:

```csharp
logger.Trace(CalculateComplexString());
```

Is it possible to avoid the calculation of that complex string as the log level is higher from the requested and it should not execute at all?

It could be solved by check everytime the log level by the user or even more efficiently with a function parameter and checked from the library, eg:

```csharp
Log(() => CalculateComplexString());

public void Log(Func<string> test)
{
	if (false) // Log Level check
		System.Diagnostics.Debug.WriteLine(test());
}

public string CalculateComplexString()
{
	return "test";
}
```

Just wondering if you have already some kind of similar implementation.

**Comment by snakefoot** [comment]
Yes this already exists in NLog with the Logger-methods taking `LogMessageGenerator`-delegate as input.
```c#
logger.Trace(() => CalculateComplexString());
```

Ofcourse there is still the delegate-instance-allocation that also gives an overhead (unless `CalculateComplexString` is a static method).

To also get rid of the allocation of delegate-instance, then one can do this:
```c#
if (logger.IsTraceEnabled)
    logger.Trace(CalculateComplexString());
```

**Comment by SuRGeoNix** [comment]
That sounds great. Thanks @snakefoot
