### ISSUE TITLE
forum (Google group) vs github

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#477]
NLog has now a Google group as well as the GitHub issue tracker.  Questions are also posted on GitHub. 

I think there is no use for the Google group now. Also questions are scattered across both places. This is inconvenient for users as well for the admins. 

Maybe the Google group should be closed? 

Ps: there are a lot of questions that could be closed on GitHub - a lot of open issues looks bad.

**Comment by Xharze** [comment]
You are correct maybe we should close the Google group. I'll think about it. 
Yes you are correct a lot of the issues have been converted from codeplex, and I haven't got time to go through all of the old issues

**Comment by 304NotModified** [comment]
Any idea what to do with this? Maybe we could discuss this point (with other about NLog future) by email?

**Comment by Xharze** [comment]
I think it would be a good idea to close the group, and use github instead.
I think we should create a post at the group describing this change before
closing, also the website should be updated and possibly the wiki

**Comment by 304NotModified** [comment]
@Xharze If you post at the Google group, then I will handle the wiki and site.

**Comment by Xharze** [comment]
I'll do that

**Comment by 304NotModified** [comment]
Kim, related to this discussion: 

On the [news posts](http://nlog-project.org/2015/01/12/nlog-3-2-0-is-released.html)
users also post questions, but really infrequently.  Those questions are most of the time not ananswered, or al least not there. 

I would like to propose: remove this 'comment section' and add a default text referencing to the github issue list.

**Comment by 304NotModified** [comment]
Also: Is the developers Google group still active?

**Comment by Xharze** [comment]
Removing the comments section would be fine by me. Yes the developer group
is still "active" meaning I've got nobody to communicate with in it, but
I'll add you which allows us to communicate outside github issues. Could be
useful sometimes. I totally forgot about this group.

**Comment by 304NotModified** [comment]
:+1:

**Comment by ilya-g** [comment]
> Yes the developer group is still "active" meaning I've got nobody to communicate with in it, but
I'll add you which allows us to communicate outside github issues.

Did you mean the NLog-Development group? It has quite restricted access now. It looks strange that the open source project has development discussion group closed from it's community.
Would it be reasonable to open this group for everyone, at least for read-only access?

**Comment by Xharze** [comment]
Yes that's the one. Yeah, it could be opened up, I'll look into that.

**Comment by 304NotModified** [comment]
Proposal PR:

https://github.com/NLog/NLog.github.io/pull/12

**Comment by 304NotModified** [comment]
Website updated:

- removed forum link
- renamed 'issue' link -> 'support'
- updated text on 'support' section

**Comment by 304NotModified** [comment]
SIte up-to-date. Development group discussion split into new ticket
