### ISSUE TITLE
Why is file truncated after each LogEvent ?

### ISSUE THREAD

**Issue by As1w** [NLog/NLog#4774]
Hi, guys!
I write program on c# with use Windows Form. 

My config Nlog FIle: 

```
 <target name="files_info"
            xsi:type="File"
            fileName="${basedir}/info/info.${longdate:cached=true}.txt"
            layout="${longdate}|${callsite}|${level:uppercase=true}|${logger}|${message}"
            archiveFileName="${basedir}/info/archives/log.${shortdate}.{#}.txt"
            archiveAboveSize="5242880"
            archiveEvery="Day"
            archiveNumbering = "Rolling"
            maxArchiveFiles="3"
            maxArchiveDays="30"
    />
```
My element program: 

```
namespace Test
{
    public partial class FormTest: Form
    {
        private static Logger logger;

        private void FormTest_Load(object sender, EventArgs e)
        {
            if (logger == null) logger = LogManager.GetCurrentClassLogger();
        } 
       private void ButtonTest_Click(object sender, EventArgs e)//My Button Click 
       {
               DateTime theDate = DateTime.Now;
               logger.Info("My DATE :" +  theDate);
       }
   }
}
```
I want the rows in My file to follow each other with time IF I click MY button: 

```
My DATE :.....
My DATE :.....
My DATE :.....
```
but  each time the old record is deleted in the file and a new one is written: 

```
`My DATE :.....`
```

**Comment by snakefoot** [comment]
That sounds strange. What version of NLog are you using? What operating system?

Can you re-produce the issue in a small console application, and attach it to the issue? (Or share link to repository)

**Comment by As1w** [comment]
> That sounds strange. What version of NLog are you using? What operating system?
> 
> Can you re-produce the issue in a small console application, and attach it to the issue? (Or share link to repository)
> 
> Can you include the output from the [NLog InternalLogger](https://github.com/NLog/NLog/wiki/Internal-Logging) on Debug-Level?

Nlog version 4.7.13

Windows 7 SP1, Windows 8.1
