### ISSUE TITLE
No output after NLog5 migration

### ISSUE THREAD

**Issue by topsterde** [NLog/NLog#4782]
**NLog version**: 4.7.13 and 5.0.0-rc2

**Platform**: .NET 6

**Current NLog config** (xml or C#, if relevant)

This works with both NLog4 and NLog5:

```var config = new LoggingConfiguration();
var target = new FileTarget("logfile") { FileName = "log.txt" };
config.AddRule(NLog.LogLevel.Debug, NLog.LogLevel.Fatal, target);
var logFactory = new LogFactory(config);

var logger = logFactory.GetCurrentClassLogger();
logger.Error("Test");
```

**With NLog5 this LogFactory constructor is now obsolete.**

If I change the code as suggested, then I get no more log output.
```var logFactory = new LogFactory();
var config = new LoggingConfiguration(logFactory);
var target = new FileTarget("logfile") { FileName = "log.txt" };
config.AddRule(NLog.LogLevel.Debug, NLog.LogLevel.Fatal, target);

var logger = logFactory.GetCurrentClassLogger();
logger.Error("Test");
```

I have not found any information here:
https://nlog-project.org/2021/08/25/nlog-5-0-preview1-ready.html

**How do I get this code with NLog5 to work?**
I cannot use the static NLog.LogManager.Configuration, because I need multiple instances of the LogFactory for different use cases.

**Comment by snakefoot** [comment]
Yes the constructor `LogFactory(config);` is now obsolete, as one should first create the LogFactory, and then create the LoggingConfiguration from the LogFactory.

I suggest you do this instead:

```c#
var logFactory = new NLog.LogFactory().Setup().LoadConfiguration(builder => {
      var target = new FileTarget("logfile") { FileName = "log.txt" };
      builder.Configuration.AddRule(NLog.LogLevel.Debug, NLog.LogLevel.Fatal, target);
}).LogFactory;
```

**Comment by snakefoot** [comment]
Closing question as resolved
