### ISSUE TITLE
Implement Nlog logging for a solution containing multiple executable services

### ISSUE THREAD

**Issue by mithunmithu** [NLog/NLog#4783]
Hello Team , 
I wanted to implement Nlog in my project .
This project solution consists of more than 20 individual executable services .
These services are consuming 4 layers, which are basically class libraries common,models ,repository , and services . These are added to each service as project reference.

I would like to have Nlog to be configured in common layer and then other services can use Nlog for logging purpose by using common project as reference .

I would also need to have each service should have their own Nlog config file(in future this solution will be decoupling and separate solutions will be creating for each service, so I do not want a common application level nlog config file ,but would like to have service level config file .)

Team please advice how can I achieve this in a better design .?
Can we have logger instantiating only in common and using that in every service ?

**Comment by snakefoot** [comment]
Having NLog as reference in the Common-project, will ensure that all your service-solution-projects will have access to the NLog-Logger. So ALL your custom classes can just do this:

```c#
class MyClass
{
    private static readonly NLog.Logger Logger = NLog.LogManager.GetCurrentClassLogger();
}
```

But you are ofcourse free to build your own Logger-wrapper in the your Common-project, if you don't like using the NLog-Logger directly.

**Comment by snakefoot** [comment]
Closing question as answered, due to inactivity.
