### ISSUE TITLE
No debug out in Visual Studio 2022

### ISSUE THREAD

**Issue by tobe83** [NLog/NLog#4797]
Hello,

I am porting my project to Visual Studio 2022, and now there is no NLog to the output window anymore.

Has anyone similiar experiences?

regards,
Tobias

**Comment by snakefoot** [comment]
What target are you using right now?

[Debugger-target](https://github.com/NLog/NLog/wiki/Debugger-target) for output to System.Diagnostics.Debugger.Log
[Trace-target](https://github.com/NLog/NLog/wiki/Trace-target) for output to System.Diagnostics.Trace
[DebugSystem-target](https://github.com/NLog/NLog/wiki/DebugSystem-target) for output to System.Diagnostics.Debug
[OutputDebugString-target](https://github.com/NLog/NLog/wiki/OutputDebugString-target) for output to OutputDebugString Win32 API

Are you using ASP.NET Core 6 ?  https://github.com/NLog/NLog.Web/wiki/Missing-trace%5Cdebug-logs-in-ASP.NET-Core-6%3F

**Comment by tobe83** [comment]
Thank you. I added the Debugger target and now it works.
