### ISSUE TITLE
CookieContainer for WebServiceTarget can not be set

### ISSUE THREAD

**Issue by Xharze** [NLog/NLog#48]
>
I am using webService target for auditing users from my winform applications, which is based on massive webService communication with my central server. At first, they login through a webService and if successfull, then create Authentication cookie through `FormsAuthentication.SetAuthCookie(userName, false);` This is stored in my application in `CookieContainer` variable, so every next webService request is done in the same authorized user context and I can get the user in webservice.

> What I need is to pass the `CookieContainer` used by my application to NLog webService "engine" calling my Audit web method, so inside of that, I can get the user for which I am writing the audit.

> This is very easily solvable by publishing `new private CookieContainer _cookieContainer` property in `NLog-1.0-Refresh\src\NLog\Targets\WebService.cs file`, and then assigning to the `HttpWebRequest.CookieContainer property in InvokeSoap11()` method as I have done for my self. For more details please see attached edited file.

**Comment by 304NotModified** [comment]
This is fixed? Check in 4.1

**Comment by 304NotModified** [comment]
Fixed in in 4.1
