### ISSUE TITLE
Unit Tests with Side-Effects

### ISSUE THREAD

**Issue by ie-zero** [NLog/NLog#480]
This is not directly a NLog issue but it might affect the development and most importantly the stability of the end product. 

Earlier today (27/Dec) I was adding some Unit Tests for LogManager class. I noticed that `public void GlobalThresholdTest()` did not have a `[Fact]` attribute associated with it. 

When I enabled the unit test I noticed the following whenever I executed all the unit tests as a single batch  
1. The test executed successfully.
2. An additional 30 unit tests, which previously completed successfully, failed.

Obviously, however wrote this test in the first instance noticed this behaviour and very logically disabled the test.

It seems to me that xUnit for some reason, either by design or due to en error, does not enforce the boundaries of each unit test. This means one unit test can affect others even if they are not directly related.  

Once we identify the source of this behaviour we ought to write some guidelines on how we need to form each unit test to avoid side-effects. 

Can anyone help me throw some light into this please?

**Comment by snakefoot** [comment]
Resolved by #4840 

See also: #4764 + #4762 + #4760 + #4759 + #4758 + #4752 + #4750 + #4749 + #4748 + #4747 + #4746 + #4745 + #4744 + #4743 + #4742 + #4741 + #4739 + #4738 + #4737 + #4736 + #4735 + #4734 + #4733 + #4732 + #4731 + #4729 + #4728 + #4727 + #4726 + #4724+ #4723

More refactoring of unit-tests can still be made, so all uses isolated LogFactory when possible.
