### ISSUE TITLE
LogFactory: SuspendLogging() does not suspend if ResumeLogging() was called before

### ISSUE THREAD

**Issue by TobiasKnauss** [NLog/NLog#4817]
**NLog version**: 5.0.0-RC2 (the GitHub code as of 2022-March-01)

**Platform**: .NET 5

- What is the current result?
Multiple (accidental) calls to `ResumeLogging()` increase the internal `_logsEnabled` counter to values above 0. It should be 0 maximum.
As a consequence, a call to `SuspendLogging()` does not suspend.

- What is the expected result?
`SuspendLogging()` should always suspend, no matter how often `ResumeLogging()` was called before.

- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
No, I checked the source code.

- Are there any workarounds?
no

- Is there a version in which it did work? 
Don't know.

- Suggested fix:
```
        public void ResumeLogging()
        {
            lock (_syncRoot)
            {
                _logsEnabled = Math.Min (0, _logsEnabled + 1);
                if (_logsEnabled == 0)
                {
                    ReconfigExistingLoggers();
                }
            }
        }
```

- Can you help us by writing an unit test?
I could, but this would take much more time than if you wrote it your self. Here's the logic for it:
```
private static void NLogUnitTest_ResumeLogging_SuspendLogging_1 ()
{
  // ----- arrange -----
  const int maxSuspendDepth = 100;

  var logFactory = NLog.LogManager.LogFactory;

  // ----- act & assert -----
  // check initial state
  Assert.IsTrue (logFactory.IsLoggingEnabled ());

  // suspend and resume once
  logFactory.SuspendLogging ();
  Assert.IsFalse (logFactory.IsLoggingEnabled ());
  logFactory.ResumeLogging ();
  Assert.IsTrue (logFactory.IsLoggingEnabled ());

  // suspend multiple times and resume by the same number
  for (int counter = 1; counter <= maxSuspendDepth; counter++)
  {
    logFactory.SuspendLogging ();
    Assert.IsFalse (logFactory.IsLoggingEnabled ());
  }
  for (int counter = 1; counter <= maxSuspendDepth; counter++)
  {
    Assert.IsFalse (logFactory.IsLoggingEnabled ());
    logFactory.ResumeLogging ();
  }
  Assert.IsTrue (logFactory.IsLoggingEnabled ());

  // resume without suspend; subsequent SuspendLogging() call must still suspend.
  logFactory.ResumeLogging ();
  Assert.IsTrue (logFactory.IsLoggingEnabled ());

  logFactory.SuspendLogging ();
  Assert.IsFalse (logFactory.IsLoggingEnabled ());
  logFactory.ResumeLogging ();
  Assert.IsTrue (logFactory.IsLoggingEnabled ());

  for (int counter = 1; counter <= maxSuspendDepth; counter++)
  {
    Assert.IsFalse (logFactory.IsLoggingEnabled ());
    logFactory.ResumeLogging ();
  }
  logFactory.SuspendLogging ();
  Assert.IsFalse (logFactory.IsLoggingEnabled ());
  logFactory.ResumeLogging ();
  Assert.IsTrue (logFactory.IsLoggingEnabled ());
}
```

**Comment by TobiasKnauss** [comment]
If the current behaviour is intended, I would suggest adding 2 more methods
`ResumeLoggingNow()`, which sets the internal counter to `Math.Max (0, _logsEnabled + 1)`
`SuspendLoggingNow()`, which sets the internal counter to `Math.Min (-1, _logsEnabled - 1)`
Alternatively, add an overload with `bool force` to each.

Maybe also a 3rd method
`ResetLoggingSuspension()`, which sets the internal counter to 0.

**Comment by snakefoot** [comment]
Not a big user of `SuspendLogging()` and `ResumeLogging()`, but I agree that it can be confusing when calling "ResumeLogging()" too much (maybe as a precaution), and then suddenly first call to `SuspendLogging()` doesn't have any effect.

Have no issue with adding `SuspendLogging()` and `ResumeLogging()` with `bool force`-parameter. Pull-request are welcome.

**Comment by snakefoot** [comment]
Closing issue, due to inactivity.
