### ISSUE TITLE
Configuration in applicationname.exe.nlog files do not load when single file publish is used

### ISSUE THREAD

**Issue by bernhardbreuss** [NLog/NLog#4818]
**NLog version**: 4.7.14

**Platform**: .NET 6

**Current NLog config**
```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      throwExceptions="true" throwConfigExceptions="true">

  <targets>
    <target name="file" xsi:type="File"
            layout="${longdate} ${level} ${logger}: ${message} ${exception:format=ToString}"
            fileName="LogFiles/${shortdate}_LogFile.txt" keepFileOpen="true" encoding="utf-8"/>

    <target name="console" xsi:type="ColoredConsole"
            layout="${longdate} ${logger} ${level}: ${message} ${exception:format=ToString}"
            detectConsoleAvailable="true" />
  </targets>

  <rules>
    <logger name="*" minlevel="Debug" writeTo="file,console" />
  </rules>
</nlog>
```

- What is the current result?
According to https://github.com/nlog/nlog/wiki/Configuration-file#file-locations it should be possible to have a configuration in a file called `program.exe.nlog` where `program.exe` is the executable for my program.
When the config file is in the `applicationname.exe.nlog` file, it does not work as expected when the application is published as single file.

Create a console application with the following Program.cs
```
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");

            foreach (var target in LogManager.Configuration.AllTargets)
                Console.WriteLine("Target: {0}", target.Name);
        }
    }
```
Publish the program with `dotnet publish -c Release -r win-x64 --no-self-contained` and run the executable. As this is not a single file publish the configuration from `applicationname.exe.nlog` is correctly loaded.
Publish the program as single file with `dotnet publish -c Release -r win-x64 --no-self-contained -p:PublishSingleFile=true` and run the executable. The configuration from `applicationname.exe.nlog` is not loaded.

- What is the expected result?
Also for single file published applications the configuration from `applicationname.exe.nlog` should be loaded.

- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
```
2022-03-02 07:59:43.0720 Warn Ignoring assembly location because location is empty: program, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
```

**Comment by snakefoot** [comment]
Because single-file-publish is special, then NLog 4 has support for the following order:

- AppDomainBaseDirectory\nlog.config (Temp-folder)
- EntryAssemblyDirectory\nlog.config (Temp-folder)
- ProcessDirectory\process-exe-nlog (Publish-folder)
- EntryAssemblyDirectory\process-exe-nlog (Temp-folder)

See also: #3517. The order is updated with NLog 5.0, so single-file-publish-with-temp-path works better.

**Comment by snakefoot** [comment]
Looks like .NET6 has made a change to this:

`System.Reflection.Assembly.GetEntryAssembly()`

It returns an Assembly-object, but its Location-property returns empty string. Which hurts NLog because it cannot extract the application-filename.

**Comment by bernhardbreuss** [comment]
Thank you for your fast response! Impressive how fast a fix is prepared.

**Comment by snakefoot** [comment]
Happy to get feedback, to ensure a good experience. While waiting for an official release, then I guess using `NLog.config` (instead `applicationname.exe.nlog`) should work.

**Comment by snakefoot** [comment]
NLog v4.7.15 is now available: https://www.nuget.org/packages/NLog/4.7.15
