### ISSUE TITLE
Nlog to aws cloudwatch not working when passing lookup values

### ISSUE THREAD

**Issue by hareeshmakani** [NLog/NLog#4841]
```xml
<?xml version="1.0" encoding="utf-8"?>

<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      internalLogLevel="info"
      internalLogFile="c:\LogsDemo\NLogs\internal-nlog.txt">
	
	<extensions>
		<add assembly="NLog.AWS.Logger" />
	</extensions>
	
	<targets>
		<target name="aws" type="AWSTarget" logGroup="NLog.ConfigExample2" profile="'${var:profile}'" region="'${var:region}'"/>		
	</targets>
	
	<rules>
		<logger name="*" minlevel="Info" writeTo="aws" />
	</rules>
</nlog>

```
The above code to log data into aws cloudwatch is not working when I try to pass region & profile values from startup class.

            LogManager.Configuration.Variables["region"] = "ap-south-1";
            LogManager.Configuration.Variables["profile"] = "default";

However when I hardcoded the values it's working. 

```xml
<target name="aws" type="AWSTarget" logGroup="NLog.ConfigExample2" profile="default" region="ap-south-1"/>
```

**Comment by snakefoot** [comment]
Think this issue is for https://github.com/aws/aws-logging-dotnet

But yes the AWS-Core-engine (used by the NLog-target) doesn't support dynamic change of settings.

See also https://github.com/aws/aws-logging-dotnet/issues/51#issuecomment-440839779 and https://github.com/aws/aws-logging-dotnet/issues/131#issuecomment-690771411

With NLog 5.0 you can do this:

```c#
LogManager.Configuration.Variables["region"] = "ap-south-1";
LogManager.Configuration.Variables["profile"] = "default";
LogManager.Configuration = LogManager.Configuration.Reload();
```

**Comment by hareeshmakani** [comment]
Is it something like we need to hardcode the profile and region values in config as below.

<target name="aws" type="AWSTarget" logGroup="NLog.ConfigExample2" profile="default" region="ap-south-1"/>

My requirement is to assign profile and region values from appsetting.json which varies based on environment. 

When I hardcode the value the logging mechanism is working but when I try to assign the value from variable getting below exception.

<target name="aws" type="AWSTarget" logGroup="NLog.ConfigExample2" profile="'${var:profile}'" region="'${var:region}'"/>

Error AWSTarget Target[aws]: Error initializing target Exception: Amazon.Runtime.AmazonClientException: No RegionEndpoint or ServiceURL configured

Any work around would be helpful.

**Comment by snakefoot** [comment]
Can only repeat that this issue belongs to https://github.com/aws/aws-logging-dotnet

But instead of manually getting values from appsettings.json and assigning them to NLog. Then you should try and use [${configsetting}](https://github.com/NLog/NLog/wiki/ConfigSetting-Layout-Renderer)

**Comment by hareeshmakani** [comment]
```xml
<?xml version="1.0" encoding="utf-8"?>

<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      internalLogLevel="info"
      internalLogFile="c:\LogsDemo\NLogs\internal-nlog.txt">
	
	<extensions>
                <add assembly="NLog.Web.AspNetCore"/>
		<add assembly="NLog.AWS.Logger" />
	</extensions>
	
	<targets>
		<target name="aws" type="AWSTarget" logGroup="NLog.ConfigExample3" profile="${var:profile}" region="${var:region}"/>
		
	</targets>
	
	<rules>
		<logger name="*" minlevel="Info" writeTo="aws" />
	</rules>
</nlog>
```

I tried above suggestion by updating the nuget to 5.x and added following code

            LogManager.Configuration.Variables["region"] = "ap-south-1";
            LogManager.Configuration.Variables["profile"] = "default1";
            LogManager.Configuration = LogManager.Configuration.Reload();

Below error is logged in log file.

Info Message Template Auto Format enabled
Info Loading assembly: NLog.AWS.Logger
Info Adding target AWSTarget(Name=aws)
Info Validating config: TargetNames=aws, ConfigItems=10, FilePath=C:\Users\gh\source\projects\logging-tutorial\LoggingTutorial\bin\Debug\netcoreapp3.1\nlog.config
Error AWSTarget(Name=aws): Exception in Initialize Exception: Amazon.Runtime.AmazonClientException: No RegionEndpoint or ServiceURL configured
   at Amazon.Runtime.ClientConfig.Validate()
   at Amazon.Runtime.AmazonServiceClient..ctor(AWSCredentials credentials, ClientConfig config)
   at Amazon.CloudWatchLogs.AmazonCloudWatchLogsClient..ctor(AWSCredentials credentials, AmazonCloudWatchLogsConfig clientConfig)
   at AWS.Logger.Core.AWSLoggerCore..ctor(AWSLoggerConfig config, String logType)
   at NLog.AWS.Logger.AWSTarget.InitializeTarget()
   at NLog.Targets.Target.Initialize(LoggingConfiguration configuration)
Info Configuring from an XML element in C:\Users\I34281\source\projects\logging-tutorial\LoggingTutorial\bin\Debug\netcoreapp3.1\nlog.config...
Info Message Template Auto Format enabled
Info Loading assembly: NLog.AWS.Logger
Info Adding target AWSTarget(Name=aws)
Info Closing old configuration.
Warn Flush failed for target NLog.AWS.Logger.AWSTarget(Name=aws) Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at NLog.AWS.Logger.AWSTarget.FlushAsync(AsyncContinuation asyncContinuation)
Warn Flush completed with errors Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at NLog.AWS.Logger.AWSTarget.FlushAsync(AsyncContinuation asyncContinuation)
Info Validating config: TargetNames=aws, ConfigItems=10, FilePath=C:\Users\gh\source\projects\logging-tutorial\LoggingTutorial\bin\Debug\netcoreapp3.1\nlog.config
Error AWSTarget(Name=aws): Exception in Initialize Exception: Amazon.Runtime.AmazonClientException: No RegionEndpoint or ServiceURL configured
   at Amazon.Runtime.ClientConfig.Validate()
   at Amazon.Runtime.AmazonServiceClient..ctor(AWSCredentials credentials, ClientConfig config)
   at Amazon.CloudWatchLogs.AmazonCloudWatchLogsClient..ctor(AWSCredentials credentials, AmazonCloudWatchLogsConfig clientConfig)
   at AWS.Logger.Core.AWSLoggerCore..ctor(AWSLoggerConfig config, String logType)
   at NLog.AWS.Logger.AWSTarget.InitializeTarget()
   at NLog.Targets.Target.Initialize(LoggingConfiguration configuration)
Info Validating config: TargetNames=aws, ConfigItems=10, FilePath=C:\Users\gh\source\projects\logging-tutorial\LoggingTutorial\bin\Debug\netcoreapp3.1\nlog.config

**Comment by snakefoot** [comment]
Try doing this:

```xml
<?xml version="1.0" encoding="utf-8"?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      internalLogLevel="info"
      internalLogFile="c:\LogsDemo\NLogs\internal-nlog.txt">
	
	<extensions>
                <add assembly="NLog.Web.AspNetCore"/>
		<add assembly="NLog.AWS.Logger" />
	</extensions>
	
	<targets>
		<target name="aws" type="AWSTarget" logGroup="NLog.ConfigExample3" profile="${var:profile:whenEmpty=Default}" region="${var:region:whenEmpty=Default}"/>
	</targets>
	
	<rules>
		<logger name="*" minlevel="Info" writeTo="aws" />
	</rules>
</nlog>
```

**Comment by hareeshmakani** [comment]
Thanks
