### ISSUE TITLE
${aspnet-request-posted-body} not returning data for long requests

### ISSUE THREAD

**Issue by mrdaghestani** [NLog/NLog#4844]
Hi,
When I'm calling my API with a small `body` it writes the body correctly, but if I call the API using more than 1MB JSON body, there's no `request_body` field in my logs.

**NLog version**: 4.14.0

**Platform**: .NET Core 3

**Current NLog config** (xml or C#, if relevant)

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="false"
      internalLogLevel="Warn" internalLogFile="c:\temp\nlog-internal.log">

	<extensions>
		<add assembly="NLog.Web.AspNetCore"/>
	</extensions>

	<targets>
		<target xsi:type="Console" name="console">
			<layout xsi:type="JsonLayout" includeAllProperties="true">
				<attribute name="date" layout="${date:format=yyyy-MM-ddTHH\:mm\:ss.fffffffZ}" />
				<attribute name="level" layout="${level:upperCase=true}"/>
				<attribute name="logger" layout="${logger}"/>
				<attribute name="message" layout="${message}" />
				<attribute name="exception" layout="${exception:format=tostring}" />
				<attribute name="request_body" layout="${aspnet-request-posted-body}" />
			</layout>
		</target>
	</targets>

	<rules>
		<logger name="*" minlevel="Warn" writeTo="console" />
	</rules>
</nlog>


```

- What is the current result? No `request_body` field in my log lines when the body is large.
- What is the expected result? It should write the `request_body` in logs
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)? Yes, no errors/warns
- Please post full exception details (message, stacktrace, inner exceptions) N/A
- Are there any workarounds? No
- Is there a version in which it did work? No
- Can you help us by writing an unit test? Yes

**Comment by snakefoot** [comment]
Notice `${aspnet-request-posted-body}` is been deprecated with NLog 5.0. See also https://github.com/NLog/NLog.Web/pull/754

**Comment by snakefoot** [comment]
Thanks to @bakgerman now NLog.Web.AspNetCore v5.1 re-introduces [${aspnet-request-posted-body}](https://github.com/NLog/NLog/wiki/AspNet-Request-posted-body-layout-renderer) with help from middleware:
```c#
app.UseMiddleware<NLog.Web.NLogRequestPostedBodyMiddleware>();
```
It is no longer necessary to call `context.Request.EnableBuffering();` as it is handled by the middleware.
