### ISSUE TITLE
Unknown property 'default=' for ${aspnet-appbasepath} 

### ISSUE THREAD

**Issue by garnevicius23** [NLog/NLog#4847]
**NLog version**: 5.0.0-rc2

**Platform**: .NET 6

**Current NLog config** (xml or C#, if relevant)

```xml
<nlog>
   <variable name="textFileLayout" value="### ${date:format=yyyy-MM-dd HH\:mm\:ss} | ${machinename} | ${aspnet-appbasepath:default=${currentdir:dir}} | ${processid} | ${pad:padding=6:inner=${level:uppercase=true}} | ${aspnet-Request-IP} | ${callsite}${newline}${stacktrace:format=DetailedFlat}${newline}${message}${newline} | ${exception:format=ToString,Message,Method,StackTrace,Data:maxInnerExceptionLevel=5}"/>

</nlog>

```

- What is the current result?
        When loading nlog config with specified variable, error is raised:
        
```text
Error Failed loading from config file location: C:\Users\aurgrn_adm\source\Tv.DhcpClientService\Tv.DhcpClientService\bin\Debug\net6.0\NLog.config Exception: NLog.NLogConfigurationException: Exception when loading configuration C:\Users\aurgrn_adm\source\Tv.DhcpClientService\Tv.DhcpClientService\bin\Debug\net6.0\NLog.config
 ---> NLog.NLogConfigurationException: Unknown property 'default=' for ${aspnet-appbasepath} (NLog.Web.LayoutRenderers.AspNetAppBasePathLayoutRenderer)
   at NLog.Layouts.LayoutParser.ParseLayoutRenderer(ConfigurationItemFactory configurationItemFactory, SimpleStringReader stringReader, Nullable`1 throwConfigExceptions)
   at NLog.Layouts.LayoutParser.CompileLayout(ConfigurationItemFactory configurationItemFactory, SimpleStringReader sr, Nullable`1 throwConfigExceptions, Boolean isNested, String& text)
   at NLog.Layouts.LayoutParser.CompileLayout(String value, ConfigurationItemFactory configurationItemFactory, Nullable`1 throwConfigExceptions, String& text)
```

- What is the expected result?
     NLog config loaded successfully.

**Comment by snakefoot** [comment]
When looking at the wiki, then there is no mention of a `Default=`-option;

https://github.com/NLog/NLog/wiki/AspNet-AppBasePath-layout-renderer

Maybe try this instead:

> `${aspnet-appbasepath:whenEmpty=${currentdir:dir}}`

**Comment by garnevicius23** [comment]
Yep, that works. But its strange because there are few .NET 5 services with same variable and everything works.
Thanks!

**Comment by snakefoot** [comment]
Probably running NLog 4.7 and not NLog 5.0RC2



Sent from my Galaxy



-------- Original message --------
From: Aurimas ***@***.***>
Date: 23/03/2022 09:39 (GMT+01:00)
To: NLog/NLog ***@***.***>
Cc: Rolf Kristensen ***@***.***>, Comment ***@***.***>
Subject: Re: [NLog/NLog] Unknown property 'default=' for ${aspnet-appbasepath} (Issue #4847)


Yep, that works. But its strange because there are few .NET 5 services with same variable and everything works.
Thanks!
