### ISSUE TITLE
internalLogFile Appdatadir on Linux & osx

### ISSUE THREAD

**Issue by Apfelwurm** [NLog/NLog#4861]
**NLog version**: 4.7.15

**Platform**: .Net 6.0 

**Current NLog config** only as an example, our config has many targets configured for different purposes

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      internalLogLevel="Info"
      internalLogFile="${specialfolder:folder=ApplicationData}/ApplicationName/logs/internal.log">

  <targets>
    <target xsi:type="File" name="allfile" fileName="${specialfolder:folder=ApplicationData}/ApplicationName/logs/all.log"
            layout="${longdate}|${event-properties:item=EventId_Id}|${uppercase:${level}}|${logger}|${message} ${exception:format=tostring}"
            archiveEvery="Day"
            archiveFileName="${specialfolder:folder=ApplicationData}/ApplicationName/logs/all.{#}.log"
            archiveNumbering="DateAndSequence"
            archiveDateFormat="yyyy-MM-dd"
            archiveAboveSize="50857600"
            maxArchiveFiles="7"
            />
  </targets>
</nlog>

```

Hello, we are building an application for multiple operating systems.

Every logfile gets saved in ´´´fileName="${specialfolder:folder=ApplicationData}/ApplicationName/logs/*.log"´´´
but the internalLogFile seems to ignore that variable resolution intentionally (like mentioned in a few older issues).

Regarding to the documentation it is possible to use %appdata%, but this does only apply to windows and not to linux or osx.

Also ${currentdir}, ${basedir}, ${tempdir} or ${processdir} are not really options for us since this would also change the location on all the windows machines that are already running.

Do you see any way that an ${appdatadir} (or similar) could be implemented in the future to enable the same logging behavior within all operating systems?
Thanks!

**Comment by snakefoot** [comment]
Created #4863 that adds specialfolder support for InternalLogFile

**Comment by Apfelwurm** [comment]
> Created #4863 that adds some specialfolder support for InternalLogFile

Thank you very much @snakefoot for such a fast action on this one :)

**Comment by snakefoot** [comment]
It has been rolled into the NLog 5.0 feature-list, so it will be available when NLog 5.0 is released.

**Comment by snakefoot** [comment]
Created #4868 that changes it to `${UserApplicationDataDir}` to make it more explicit that it is the user-specific applicationdata-dir

**Comment by snakefoot** [comment]
NLog 5.0 has been released with support for `${UserApplicationDataDir}`
