### ISSUE TITLE
WindowsIdentityLayoutRenderer not disposing WindowsIdentity

### ISSUE THREAD

**Issue by 11v1** [NLog/NLog#4865]
Hi! 

I think WindowsIdentityLayoutRenderer should dispose WindowsIdentity instance in Append method.

**NLog version**: 
4.7.15

**Platform**: 
.Net 4.5

**Comment by snakefoot** [comment]
Yes always wondered why it was never diposed, since it would leak SafeHandles, that would fill the finalizer queue.

> WindowsIdentity.GetCurrent() returns an instance which you should dispose, otherwise you temporarily leak a user handle. (Its a safehandle so its not a huge deal). Infact, most times you use WindowsIdentity it is good to dispose of the item. Except for one case.

> If you call Impersonate() on a WindowsIdentity instance, disposing it will cause hard to diagnose crashes.

Have now created #4867
