### ISSUE TITLE
Throw Exceptions Intention - Clarification Required

### ISSUE THREAD

**Issue by ie-zero** [NLog/NLog#488]
I am aware the `LogManager` class has the `ThrowExceptions` property which enables/disables if an exception will be thrown. I am know that specific Exceptions get the `MustBeRethrown` property through an the extension.

In my understanding the intention is that when `ThrowExceptions = false` than the all other exceptions except the ones with `MustBeRethrown = true` should be recorded in internal logger and NOT be thrown.

Can someone kindly clarify for me if my understanding is correct please?

**Comment by Xharze** [comment]
Sorry for the late reply, that would be correct in my opinion.

**Comment by ilya-g** [comment]
You can also refer to http://nlog-project.org/2010/09/05/new-exception-handling-rules-in-nlog-2-0.html
