### ISSUE TITLE
Error Id to be shared to end user

### ISSUE THREAD

**Issue by jayantsatkar** [NLog/NLog#4889]
I'm using this NLog in .Net 5. We wanted to show the error id which is inserted in database. In current version all the methods are with return type Void. We are expecting that it should return Error ID as Integer or string (Unique identifier)

**Comment by snakefoot** [comment]
I don't understand the question:
- Please include your NLog.config
- Please include example of how you perform the logging,
- Please tell where you are missing the expected output.

Are you interested in the return value from the NLog DatabaseTarget. Ex. #2049 and #2671
