### ISSUE TITLE
Update nlog.xsd

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#4892]
for NLog 5

**Comment by snakefoot** [comment]
One might consider to have a dedicated NLog4.xsd, since I have changed so obsolete properties are not included in the NLog.xsd.

**Comment by 304NotModified** [comment]
Ow maybe we need a nlog5.xsd then?

(Or nlog.xsd + nlog4.xsd. doubting...)

**Comment by snakefoot** [comment]
I prefer that NLog.xsd is the latest official version. But not going to cry if you prefer having NLog3.xsd + NLog4.xsd + NLog5.xsd

But most documentation recommends using NLog.xsd with latest NLog-build.

**Comment by 304NotModified** [comment]
Ok nlog.xsd + nlog4.xsd then :)

**Comment by snakefoot** [comment]
Resolved by https://github.com/NLog/NLog.github.io/pull/191
