### ISSUE TITLE
Trace logging from WinForms?

### ISSUE THREAD

**Issue by rrgjt** [NLog/NLog#4896]
I posted an issue on StackOverfow (https://stackoverflow.com/questions/72063059/nlog-in-net-6-winforms-app-not-logging-unless-on-demand), but it's not been receiving any love at all, but am now wondering if it's simply a limitation, that Trace and Debug levels are not supported under WinForms, and if logging at these levels from business DLLs that normally work, is being blocked since they are being called from WinForms.  Can I get clarification one way or another that nLog under WinForms supports Trace logging?

Thanks

**Comment by snakefoot** [comment]
NLog doesn't have any special limitation for WinForms. And the output from the NLog InternalLogger says:

`Debug logNamePattern: (:All) levels: [ Trace Debug Info Warn Error Fatal ] writeTo: [ file ]`

Any filtering regarding Trace + Debug probably comes from Microsoft Extension Logging LoggerFactory.

Are you writing using NLog Logger, or using Microsoft ILogger-interface? (The StackOverflow-question is giant mixture of everything, without any details about how logger is created and logging is performed).

**Comment by rrgjt** [comment]
The main application uses iLogger, and the only event being logged is the one below:

```
        public HealthCheckMain(ILogger<HealthCheckMain> logger)
        {
            _logger = logger;
            InitializeComponent();

            _logger.LogInformation("Logger initialized", DateTime.UtcNow);

....

```
I tried adding the "RemoveLoggerFactoryFilter" as outlines above and it did not make any difference.  I see you have requested the nlog.config, even though it is included in the Stackoverflow post:

```
<?xml version="1.0" encoding="utf-8" ?>
<nlog internalLogFile="${tempdir}\logs\NLog_internal_log.txt" internalLogLevel="Trace" xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

	<!-- enable asp.net core layout renderers -->
	<extensions>
		<add assembly="NLog.Web.AspNetCore"/>
	</extensions>

	<!-- the targets to write to -->
	<targets>
		<target name="file"
				xsi:type="File"
				encoding="UTF8"
				layout="${longdate} ${logger} ${message} ${exception:format=ToString} ${stacktrace:format=DetailedFlat:separator=&#xD;&#xA;}"
				fileName="${tempdir}\logs\LIMS3_HealthCheck_current_log.txt"
				archiveFileName="${tempdir}\logs\LIMS3_HealthCheck_archive_log.{#}.txt"
				archiveNumbering="DateAndSequence"
				maxArchiveFiles="2"
				archiveAboveSize="2000000"
				archiveDateFormat="yyyyMMdd"
				archiveEvery="Day" />
	</targets>

	<!-- rules to map from logger name to target -->
	<rules>
		<logger name="*" minlevel="Trace" writeTo="file" />
	</rules>
</nlog>

```

**Comment by snakefoot** [comment]
Still don't know from the above code how you acquire the ILogger-object.

This also looks like a bug, since you are missing a string-format-placeholder, but you have provided a string-format-parameter.
```
_logger.LogInformation("Logger initialized", DateTime.UtcNow);
```

**Comment by kyleschwenn** [comment]
I can elaborate a little on that LogInformation line. That was added in just to see if NLog was being initalized correctly, so its not necessary at all. Does Debug and Trace require anything to begin logging?

**Comment by snakefoot** [comment]
Nope like I said initially then NLog does not have any special behaviour for WinForms. And your NLog InternalLogger output shows all levels (including Debug + Trace) are writing to file.

Would probably focus on Microsoft ILogger IsEnabled() since NLog looks good.

Sent from my Galaxy



-------- Original message --------
From: kyleschwenn ***@***.***>
Date: 02/05/2022 21:38 (GMT+01:00)
To: NLog/NLog ***@***.***>
Cc: Rolf Kristensen ***@***.***>, Comment ***@***.***>
Subject: Re: [NLog/NLog] Trace logging from WinForms? (Issue #4896)


I can elaborate a little on that LogInformation line. That was added in just to see if NLog was being initalized correctly, so its not necessary at all. Does Debug and Trace require anything to begin logging?

**Comment by rrgjt** [comment]
I added "if (_logger.IsEnabled(LogLevel.Trace))" prior to the _logger.LogInformation line, and it shows it's enabled at the Trace level.

**Comment by snakefoot** [comment]
And you only see output when using `_logger.LogInformation` and more severe?

**Comment by kyleschwenn** [comment]
![image](https://user-images.githubusercontent.com/27366002/166332372-152b38b7-b3be-4d31-b70e-415184e1c8ec.png)
Only provider is the NLogLoggerProvider. Should there only be 1 provider as well? Currently there are 3.

**Comment by rrgjt** [comment]
To answer your first question... This is the only entry in the log file, even after triggering the business layers objects and creating error conditions:

2022-05-02 13:06:19.0785 HealthCheck.HealthCheckMain Logger initialized  [System.Object Invoke(System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)]
[System.Object InvokeMethod(System.Object, System.Span`1[System.Object] ByRef, System.Signature, Boolean, Boolean)]
[Void .ctor(Microsoft.Extensions.Logging.ILogger`1[HealthCheck.HealthCheckMain])]

**Comment by snakefoot** [comment]
So until now we have just been debugging code, where everything is working as expected and all is great.

And for some reason you have decided to keep the source-code with the actual problem out of the scope, when I asked for "details about how logger is created and logging is performed". Strange journey you have taken me on.

**Comment by rrgjt** [comment]
Wow, I appreciate your time and suggestions, but please lose the condescending attitude.  There are two of us working on this with you and if we have missed something, then it seems obvious that the request was vague enough that both of us missed it.  Between the StackOverflow post mentioned in the first line of this post and the information presented here, we have provided every scrap of code and configuration, and followed every suggestion and answered every question to try to get Trace logging working in this WinForms app.  If there is a better way of presenting the information, we are open to constructive feedback.  Nothing has been deliberately held "out-of-scope".  If you think there is an issue with the business layer DLLs themselves, then we'd be happy to pass that information along to the developers, but that does not explain (to me anyway), why the WinForms app does not do any Trace logging even before the business layer methods are called..

**Comment by snakefoot** [comment]
I was hoping that the pieces of information you presented would be enough to diagnose the issue. I got disappointed that all evidence you put together was just showing everything works.

Have lots of unit tests showing that NLog is working fine with Microsoft LoggerFactory when using Debug and Trace.

I think you should make a very small solution where Trace and Debug is not working for you. Then provide a link to that source code. Remember to use RemoveLoggerFactoryFilter


Sent from my Galaxy



-------- Original message --------
From: rrgjt ***@***.***>
Date: 03/05/2022 14:59 (GMT+01:00)
To: NLog/NLog ***@***.***>
Cc: Rolf Kristensen ***@***.***>, Comment ***@***.***>
Subject: Re: [NLog/NLog] Trace logging from WinForms? (Issue #4896)


Wow, I appreciate your time and suggestions, but please lose the condescending attitude. There are two of us working on this with you and if we have missed something, then it seems obvious that the request was vague enough that both of us missed it. Between the StackOverflow post mentioned in the first line of this post and the information presented here, we have provided every scrap of code and configuration, and followed every suggestion and answered every question to try to get Trace logging working in this WinForms app. If there is a better way of presenting the information, we are open to constructive feedback. Nothing has been deliberately held "out-of-scope". If you think there is an issue with the business layer DLLs themselves, then we'd be happy to pass that information along to the developers, but that does not explain (to me anyway), why the WinForms app does not do any Trace logging even before the business layer methods are called..
