### ISSUE TITLE
Can w write the byte array directly into file target without converting it in to string

### ISSUE THREAD

**Issue by harishrajput4** [NLog/NLog#4901]
Hi!

If you have a question that the logging isn't working, check the [troubleshooting guide](https://github.com/nlog/nlog/wiki/Logging-troubleshooting) first before posting.
Almost every case is solveble with the internal log

Are you searching for a layout or layout renderer? You could find them [here](https://nlog-project.org/config/)

StackOverflow.com is recommended for questions. You could expect a faster response there (but do include all the info below) and the search is better.

Important details when asking question on StackOverflow.com:

- Use the tag "nlog"
- Include versions of NLog/NLog.AspNetCore etc.
- Include the platform (.NET 4.5, ASP.NET Core 3, Xamarin etc)
- Include the current config (xml or code)
- Explain current result
- Explain desired result
- Please post full exception details (message, stacktrace, inner exceptions) in case of an error

**Comment by snakefoot** [comment]
I guess you could make your own custom FileTarget that inherits from NLog FileTarget, and then override this method:
```c#
        protected override void RenderFormattedMessageToStream(LogEventInfo logEvent, StringBuilder formatBuilder, char[] transformBuffer, MemoryStream streamTarget)
        {
            if (logEvent.Parameters?.Length == 1 && logEvent.Parameters[0] is byte[] logArray)
               streamTarget.Write(logArray, 0, logArray.Length);
            else
               base.RenderFormattedMessageToStream(logEvent, formatBuilder, transformBuffer, streamTarget);
        }
```
Then it will check if the NLog LogEventInfo has been initialized using a single byte[]-array.

**Comment by harishrajput4** [comment]
Thanks for the prompt reply, the solution you suggested worked for me..
