### ISSUE TITLE
ubuntu  specify the log path not work ,please fixed it

### ISSUE THREAD

**Issue by qiqisteve** [NLog/NLog#4902]
```c#
            var loggerFactory = NLog.Web.NLogBuilder.ConfigureNLog("nlog.config");

            var dataPath = Environment.GetEnvironmentVariable("DATAPATH");
            Console.WriteLine(@dataPath);
            if (!string.IsNullOrEmpty(dataPath))
            {
                    Console.WriteLine(@dataPath);
                    NLog.GlobalDiagnosticsContext.Set("aaa",@dataPath);
            }
```

**Comment by qiqisteve** [comment]
1 .use the command `dotnet run  -c release ` ，the gdc item configuration works，
2. use the command `dotnet build -c release ', then run the build output file, the gdc config item not works, the log file wasnot created
![image](https://user-images.githubusercontent.com/15710782/167242984-a79dd286-7690-42af-a3fc-b24acfc1a5a6.png)

![image](https://user-images.githubusercontent.com/15710782/167242996-c30de298-2644-462f-94e9-b2de04525fbb.png)

**Comment by snakefoot** [comment]
Try enabling https://github.com/NLog/NLog/wiki/Internal-logging (using `internalLogLevel="Debug"`), and compare the output from when it works and when it doesn't work.

**Comment by qiqisteve** [comment]
> Try enabling https://github.com/NLog/NLog/wiki/Internal-logging (using `internalLogLevel="Debug"`), and compare the output from when it works and when it doesn't work.
> 
> Maybe the nlog.config cannot be loaded, maybe because the file is missing (Action = `Copy if newer`)

![image](https://user-images.githubusercontent.com/15710782/167333304-5d10c0c7-3760-4c67-bc8b-bb2ce6c2f968.png)

**Comment by qiqisteve** [comment]
[internal-nlog.txt](https://github.com/NLog/NLog/files/8648510/internal-nlog.txt)
[internal-nlog (2).txt](https://github.com/NLog/NLog/files/8648511/internal-nlog.2.txt)

**Comment by snakefoot** [comment]
Both looks great. I'm guessing your problem is that LogLevel-filtering has changed between the two scenarios:

Check `appsettings.json` and also any environment-specific like `appsettings.development.json`. See also: https://github.com/NLog/NLog.Web/wiki/Missing-trace%5Cdebug-logs-in-ASP.NET-Core-6%3F
