### ISSUE TITLE
Configurable Option for max queue size limit on AsyncTargetWrapperOverflowAction.Grow

### ISSUE THREAD

**Issue by ashenone85** [NLog/NLog#4909]
**NLog version**: 5.0.3

**Platform**: .Net 5

 - Why do we need it?
 Grow - The application-thread will ignore the limit, and will just allocate more memory. Can cause the entire application to experience out-of-memory-issues.

We would like to use this option on a production system, but this would only be feasible if there was an option to limit the max queue size.

**Comment by snakefoot** [comment]
Closing issue as answered, due to inactivity.
