### ISSUE TITLE
RichTextBox target breaks row coloring when using MaxLines

### ISSUE THREAD

**Issue by ehoeks** [NLog/NLog#492]
Using NLog 3.2.0.0 and .Net Framework 4.0 (C#) 

I experience Issues using the MaxLines feature on the RichTextBoxTarget.

It looks like the code breaks the Rtf behaviour when removing parts with
`rtbx.Text = rtbx.Text.Remove(...);`
while the old implementation
`rtbx.SelectedText = string.Empty;`
does not work when the RichTextBox is ReadOnly

I suggest to use:
`rtbx.SelectedRtf = "{\\rtf1\\ansi}";`
which works on ReadOnly RichTextBox and does not break the coloring

See [stackoverflow remove-text-from-a-readonly-richtextbox](http://stackoverflow.com/questions/13318238/how-can-i-programmatically-remove-text-from-a-readonly-richtextbox)

I've tested the change with C# visualstudio 2013 .NET 4.0 and it works for that use-case.

related to #17 #324 #362 "RichTextBox target doesn't respect maxlines(keeps adding more and more lines)"

**Comment by Xharze** [comment]
Thanks for the issue and suggested fix. I'll take a look at using your suggestion.

**Comment by ehoeks** [comment]
Hi Hharze. I wouldn't mind getting involved in NLog development myself. I do not have much experience in submitting patches via GitHub so please don't mind the 'code in comment field' solution for now.

**Comment by Xharze** [comment]
No problem

**Comment by 304NotModified** [comment]
@ehoeks I appreciate your help :+1:

**Comment by 304NotModified** [comment]
PR is merged so this can be closed :)
