### ISSUE TITLE
Inaccurate time for layout ${longdate}.

### ISSUE THREAD

**Issue by dxh-sc** [NLog/NLog#4928]
Hello,

When i use the AsyncTargetWrapper to set the layout "${hostname}|${longdate}|${threadid}|${level}|${message} ${exception:format=toString,Data}", but i found that the time(${longdate}) is not the calling time. 

**NLog version: 5.0.0**

**Platform: .NET48**

![image](https://user-images.githubusercontent.com/54095220/168995136-b595c5cb-777e-4d99-8f75-4ff6a1dc3ed6.png)

![image](https://user-images.githubusercontent.com/54095220/168990231-895ccb3c-20d9-48a8-a348-c672762e58cc.png)

The red area is my calling time.

but you see the layout ${longdate}  is always the first message time (2022-05-18 15:39:30.**7686**).

So how i can set my calling time with the layout ${longdate} ?

Many thanks for help.

**Comment by snakefoot** [comment]
NLog uses Local DateTime by default, which is slow and therefore also applies some caching:

See also: https://github.com/NLog/NLog/wiki/Time-Source

If you change your TimeSource to AccurateUTC, then it should be fast and precise (but in UTC):

```c#
NLog.LogManager.Setup().LoadConfiguration(builder => builder.SetTimeSource(new NLog.Time.AccurateUtcTimeSource()));
```

**Comment by dxh-sc** [comment]
ok, thanks!
