### ISSUE TITLE
Support for MVC Asp.net 6

### ISSUE THREAD

**Issue by jersiovic** [NLog/NLog#493]
Do you plan to support MVC Asp.net  6? At any estimated date?

**Comment by Xharze** [comment]
Yes support for MVC 6 will be implemented, although I can't say when. Any specific features you are looking for?

**Comment by jersiovic** [comment]
Not anyone in concrete just to know it is was in your roadmap. Indeed it was related with this other one http://orchard.codeplex.com/discussions/574334

**Comment by 304NotModified** [comment]
Is Log4Net actively maintained?  ;)

**Comment by jersiovic** [comment]
Well last log4net trunk buil was ... one year ago  :-1:  https://builds.apache.org/job/log4net-trunk-build/

**Comment by 304NotModified** [comment]
fail.... don't get it why it's more popular. (according to nuget stats)

**Comment by MattGal** [comment]
Is this actively in development?  I'd be very willing to helping the port to the ASPNETCORE50 profile if needed.  NLog 3.2.0.0 seems to work just fine in ASPNET50 (Desktop profile) today.

**Comment by 304NotModified** [comment]
Well NLog is actively maintained but we don't haven't specific steps to support mvc 6 yet. 

PR's will be appreciated and merged: )

**Comment by 304NotModified** [comment]
FYI

CoreCLR is now in alpha stage, and there is a package for ASPNET5 (including MVC6 support)

See: 
- https://www.nuget.org/packages/NLog.Extensions.Logging  (see also [GitHub](https://github.com/NLog/NLog.Extensions.Logging))
- https://www.nuget.org/packages/NLog.Web.ASPNET5 (see also [GitHub](https://github.com/NLog/NLog.Web))

**Comment by 304NotModified** [comment]
As there is not really something to do here, I will close this on. MVC Core is supported in 4.4 (beta)
