### ISSUE TITLE
Probabilistic loss log when creating Archive

### ISSUE THREAD

**Issue by 0611163** [NLog/NLog#4930]
**NLog version**: 4.7.11

**Platform**: .Net Framework 4.5.2

**Current NLog config** (xml or C#, if relevant)

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="false"
      internalLogLevel="Off"
      internalLogFile="d:\nlog\nlog-internal.log">

  <!-- optional, add some variables
  https://github.com/nlog/NLog/wiki/Configuration-file#variables
  -->
  <!--<variable name="myvar" value="myvalue"/>-->

  <variable name="logDir" value="${basedir}/nlog"/>
  <variable name="logFileName" value="${date:format=yyyyMMdd_HHmmss}.txt"/>
  <variable name="logArchiveFileName" value="${date:format=yyyyMMdd_HHmmss}_{#}.txt"/>
  <variable name="logLayout" value="${date:format=yyyy-MM-dd HH\:mm\:ss.fff} [${level}] ${message}"/>

  <!--
  See https://github.com/nlog/nlog/wiki/Configuration-file
  for information on customizing logging rules and outputs.
   -->

  <targets>

    <!--
    add your targets here
    See https://github.com/nlog/NLog/wiki/Targets for possible targets.
    See https://github.com/nlog/NLog/wiki/Layout-Renderers for the possible layout renderers.
    -->

    <!--
    Write events to a file with the date in the filename.
    <target xsi:type="File" name="f" fileName="${basedir}/logs/${shortdate}.log"
            layout="${longdate} ${uppercase:${level}} ${message}" />
    -->

    <target xsi:type="File" name="info"
            layout="${logLayout}"
            fileName="${logDir}/info/${logFileName}"
            archiveFileName="${logDir}/info/${logArchiveFileName}"
            archiveAboveSize="10240"
            archiveNumbering="Sequence"
            maxArchiveFiles="100"
            concurrentWrites="true"
            keepFileOpen="true"
            openFileCacheTimeout="30"
            encoding="UTF-8" />

    <target xsi:type="File" name="debug"
            layout="${logLayout}"
            fileName="${logDir}/debug/${logFileName}"
            archiveFileName="${logDir}/debug/${logArchiveFileName}"
            archiveAboveSize="10240"
            archiveNumbering="Sequence"
            maxArchiveFiles="100"
            concurrentWrites="true"
            keepFileOpen="true"
            openFileCacheTimeout="30"
            encoding="UTF-8" />

    <target xsi:type="File" name="error"
            layout="${logLayout}"
            fileName="${logDir}/error/${logFileName}"
            archiveFileName="${logDir}/error/${logArchiveFileName}"
            archiveAboveSize="10240"
            archiveNumbering="Sequence"
            maxArchiveFiles="100"
            concurrentWrites="true"
            keepFileOpen="true"
            openFileCacheTimeout="30"
            encoding="UTF-8" />

  </targets>

  <rules>
    <!-- add your logging rules here -->

    <!--
    Write all events with minimal level of Debug (So Debug, Info, Warn, Error and Fatal, but not Trace)  to "f"
    <logger name="*" minlevel="Debug" writeTo="f" />
    -->

    <logger name="*" minlevel="Info" maxlevel="Info" writeTo="info" />

    <logger name="*" minlevel="Debug" maxlevel="Debug" writeTo="debug" />

    <logger name="*" minlevel="Error" maxlevel="Error" writeTo="error" />

  </rules>
</nlog>

```

- What is the current result?
- Multi process or single process lost logs
- What is the expected result?
- Multi process or single process do not lose logs
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
- Yes
- Please post full exception details (message, stacktrace, inner exceptions)
- 未能找到文件“D:\_程序\LogUtilGitee\LogUtil\bin\Debug\nlog\info\20220520_092711.txt”。
- console：
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   在 NLog.Targets.FileTarget.ArchiveFileAppendExisting(String fileName, String archiveFileName)
   在 NLog.Targets.FileTarget.ArchiveFile(String fileName, String archiveFileName)
   在 NLog.Targets.FileTarget.DoAutoArchive(String fileName, LogEventInfo eventInfo, DateTime previousLogEventTimestamp, Boolean initializedNewFile)
   在 NLog.Targets.FileTarget.ArchiveFileAfterCloseFileAppender(String archiveFile, LogEventInfo ev, Int32 upcomingWriteSize, DateTime previousLogEventTimestamp)
   在 NLog.Targets.FileTarget.TryArchiveFile(String fileName, LogEventInfo ev, Int32 upcomingWriteSize, DateTime previousLogEventTimestamp, Boolean initializedNewFile)
   在 NLog.Targets.FileTarget.ProcessLogEvent(LogEventInfo logEvent, String fileName, ArraySegment`1 bytesToWrite)
   在 NLog.Targets.FileTarget.Write(LogEventInfo logEvent)
   在 NLog.Targets.Target.Write(AsyncLogEventInfo logEvent)
   在 NLog.Targets.Target.WriteAsyncThreadSafe(AsyncLogEventInfo logEvent)
   在 NLog.Targets.Target.WriteAsyncLogEvent(AsyncLogEventInfo logEvent)
   在 NLog.LoggerImpl.WriteToTargetWithFilterChain(Target target, FilterResult result, LogEventInfo logEvent, AsyncContinuation onException)
   在 NLog.LoggerImpl.Write(Type loggerType, TargetWithFilterChain targetsForLevel, LogEventInfo logEvent, LogFactory factory)
   在 NLog.Logger.WriteToTargets(LogEventInfo logEvent, TargetWithFilterChain targetsForLevel)
   在 NLog.Logger.WriteToTargets(LogLevel level, IFormatProvider formatProvider, String message)
   在 NLog.Logger.Info(String message)
   在 LogUtil.Test3.Program.<>c__DisplayClass2_0.<Main>b__0() 位置 D:\_程序\LogUtilGitee\LogUtil\LogUtil.Test3\Program.cs:行号 33
   在 LogUtil.Test3.Program.<>c__DisplayClass3_0.<TaskRun>b__0() 位置 D:\_程序\LogUtilGitee\LogUtil\LogUtil.Test3\Program.cs:行号 69
nlog-internal：
2022-05-20 09:33:29.0192 Debug Creating file appender: D:\_程序\LogUtilGitee\LogUtil\bin\Debug\nlog\info\20220520_093329.txt
2022-05-20 09:33:29.0192 Debug Watching path 'D:\_程序\LogUtilGitee\LogUtil\bin\Debug\nlog\info' filter '20220520_093329.txt' for changes.
2022-05-20 09:33:29.0182 Debug Watching path 'D:\_程序\LogUtilGitee\LogUtil\bin\Debug\nlog\info' filter '20220520_093329.txt' for changes.
2022-05-20 09:33:29.0182 Debug FileTarget(Name=info): Start archiving 'D:\_程序\LogUtilGitee\LogUtil\bin\Debug\nlog\info\20220520_093329.txt' because FileSize=10244 + 52 is larger than ArchiveAboveSize=10240
2022-05-20 09:33:29.0182 Debug FileAppender Closing Invalidate - D:\_程序\LogUtilGitee\LogUtil\bin\Debug\nlog\info\20220520_093329.txt
2022-05-20 09:33:29.0192 Debug Stopping file watching for path 'D:\_程序\LogUtilGitee\LogUtil\bin\Debug\nlog\info' filter '20220520_093329.txt'
2022-05-20 09:33:29.0172 Warn FileTarget(Name=info): Archiving failed. Checking for retry move of D:\_程序\LogUtilGitee\LogUtil\bin\Debug\nlog\info\20220520_093329.txt to D:\_程序\LogUtilGitee\LogUtil\bin\Debug\nlog\info\20220520_093329_0.txt. Exception: System.IO.FileNotFoundException: 未能找到文件“D:\_程序\LogUtilGitee\LogUtil\bin\Debug\nlog\info\20220520_093329.txt”。
文件名:“D:\_程序\LogUtilGitee\LogUtil\bin\Debug\nlog\info\20220520_093329.txt”
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   在 NLog.Targets.FileTarget.ArchiveFileMove(String fileName, String archiveFileName)
2022-05-20 09:33:29.0182 Debug FileTarget(Name=info): Do archive file: 'D:\_程序\LogUtilGitee\LogUtil\bin\Debug\nlog\info\20220520_093329.txt'
2022-05-20 09:33:29.0172 Warn FileTarget(Name=info): Failed to archive file 'D:\_程序\LogUtilGitee\LogUtil\bin\Debug\nlog\info\20220520_093329.txt'. Exception: System.IO.FileNotFoundException: 未能找到文件“D:\_程序\LogUtilGitee\LogUtil\bin\Debug\nlog\info\20220520_093329.txt”。
文件名:“D:\_程序\LogUtilGitee\LogUtil\bin\Debug\nlog\info\20220520_093329.txt”
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   在 NLog.Targets.FileTarget.ArchiveFileMove(String fileName, String archiveFileName)
   在 NLog.Targets.FileTarget.ArchiveFile(String fileName, String archiveFileName)
   在 NLog.Targets.FileTarget.DoAutoArchive(String fileName, LogEventInfo eventInfo, DateTime previousLogEventTimestamp, Boolean initializedNewFile)
   在 NLog.Targets.FileTarget.ArchiveFileAfterCloseFileAppender(String archiveFile, LogEventInfo ev, Int32 upcomingWriteSize, DateTime previousLogEventTimestamp)
2022-05-20 09:33:29.0332 Info FileTarget(Name=info): Archiving D:\_程序\LogUtilGitee\LogUtil\bin\Debug\nlog\info\20220520_093329.txt to D:\_程序\LogUtilGitee\LogUtil\bin\Debug\nlog\info\20220520_093329_1.txt
2022-05-20 09:33:29.0332 Debug FileTarget(Name=info): Move file from 'D:\_程序\LogUtilGitee\LogUtil\bin\Debug\nlog\info\20220520_093329.txt' to 'D:\_程序\LogUtilGitee\LogUtil\bin\Debug\nlog\info\20220520_093329_1.txt'
2022-05-20 09:33:29.0332 Debug FileTarget(Name=info): Preparing for new file 'D:\_程序\LogUtilGitee\LogUtil\bin\Debug\nlog\info\20220520_093329.txt'
2022-05-20 09:33:29.0332 Debug Creating file appender: D:\_程序\LogUtilGitee\LogUtil\bin\Debug\nlog\info\20220520_093329.txt
2022-05-20 09:33:29.0362 Debug FileTarget(Name=info): Skip archiving 'D:\_程序\LogUtilGitee\LogUtil\bin\Debug\nlog\info\20220520_093329.txt' because no longer necessary
2022-05-20 09:33:29.0362 Debug FileTarget(Name=info): Preparing for new file 'D:\_程序\LogUtilGitee\LogUtil\bin\Debug\nlog\info\20220520_093329.txt'
2022-05-20 09:33:29.0362 Debug Creating file appender: D:\_程序\LogUtilGitee\LogUtil\bin\Debug\nlog\info\20220520_093329.txt
2022-05-20 09:33:29.0332 Debug Watching path 'D:\_程序\LogUtilGitee\LogUtil\bin\Debug\nlog\info' filter '20220520_093329.txt' for changes.
2022-05-20 09:33:29.0362 Debug Watching path 'D:\_程序\LogUtilGitee\LogUtil\bin\Debug\nlog\info' filter '20220520_093329.txt' for changes.
2022-05-20 09:33:29.0412 Debug Creating file appender: D:\_程序\LogUtilGitee\LogUtil\bin\Debug\nlog\info\20220520_093328.txt
2022-05-20 09:33:29.0412 Debug Watching path 'D:\_程序\LogUtilGitee\LogUtil\bin\Debug\nlog\info' filter '20220520_093329_*.txt' for changes.
2022-05-20 09:33:29.0412 Debug Watching path 'D:\_程序\LogUtilGitee\LogUtil\bin\Debug\nlog\info' filter '20220520_093328.txt' for changes.
2022-05-20 09:33:29.0412 Debug FileTarget(Name=info): Preparing for new file 'D:\_程序\LogUtilGitee\LogUtil\bin\Debug\nlog\info\20220520_093329.txt'
2022-05-20 09:33:29.0362 Debug FileTarget(Name=info): Start archiving 'D:\_程序\LogUtilGitee\LogUtil\bin\Debug\nlog\info\20220520_093329.txt' because FileSize=10244 + 52 is larger than ArchiveAboveSize=10240
2022-05-20 09:33:29.0412 Debug FileTarget(Name=info): Start archiving 'D:\_程序\LogUtilGitee\LogUtil\bin\Debug\nlog\info\20220520_093329.txt' because FileSize=10244 + 52 is larger than ArchiveAboveSize=10240
2022-05-20 09:33:29.0362 Debug FileAppender Closing Invalidate - D:\_程序\LogUtilGitee\LogUtil\bin\Debug\nlog\info\20220520_093329.txt
2022-05-20 09:33:29.0412 Debug Stopping file watching for path 'D:\_程序\LogUtilGitee\LogUtil\bin\Debug\nlog\info' filter '20220520_093328.txt'
- Are there any workarounds? yes/no
- no
- Is there a version in which it did work? 
- I don't know，Not tried
- Can you help us by writing an unit test?
- Maybe can
-

**Comment by 0611163** [comment]
about nlog-internal can be modified as：
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="true"
      internalLogLevel="Debug"
      internalLogFile="d:\nlog\nlog-internal.log">
......

**Comment by 0611163** [comment]
To show nlog-internal config：
```xml
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="true"
      internalLogLevel="Debug"
      internalLogFile="d:\nlog\nlog-internal.log">
......

```

**Comment by 0611163** [comment]
test code：
```C#
using NLog;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace LogUtil.Test3
{
    class Program
    {
        private static Logger _log = NLog.LogManager.GetCurrentClassLogger();

        private static int n = 30000;

        static void Main(string[] args)
        {
            try
            {
                Log("==== 开始 ========");
                Stopwatch stopwatch = new Stopwatch();
                stopwatch.Start();
                List<Task> taskList = new List<Task>();
                Task tsk = null;
                int taskCount = 0;

                tsk = TaskRun(() =>
                {
                    for (int i = 0; i < n; i++)
                    {
                        _log.Info("测试日志 " + i.ToString("000000"));
                        Interlocked.Increment(ref taskCount);
                    }
                });
                taskList.Add(tsk);

                tsk = TaskRun(() =>
                {
                    for (int i = 0; i < n; i++)
                    {
                        _log.Info("测试日志 " + i.ToString("000000"));
                        Interlocked.Increment(ref taskCount);
                    }
                });
                taskList.Add(tsk);

                Task.WaitAll(taskList.ToArray());
                Log("Task Count=" + taskCount);

                Log("==== 结束 " + "，耗时：" + stopwatch.Elapsed.TotalSeconds.ToString("0.000") + " 秒 ========");
                stopwatch.Stop();
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message + "\r\n" + ex.StackTrace);
            }

            Console.Read();
        }

        private static Task TaskRun(Action action)
        {
            return Task.Run(() =>
            {
                try
                {
                    action();
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.Message + "\r\n" + ex.StackTrace);
                }
            });
        }

        #region Log
        private static void Log(string log)
        {
            Console.WriteLine(DateTime.Now.ToString("HH:mm:ss.fff") + " " + log);
        }
        #endregion

    }
}

```

**Comment by 0611163** [comment]
Test code for Single process：
```C#
//对比NLog
private void button3_Click(object sender, EventArgs e)
{
    Task.Run(() =>
    {
        Log("==== 开始 ========");
        Stopwatch stopwatch = new Stopwatch();
        stopwatch.Start();
        List<Task> taskList = new List<Task>();
        Task tsk = null;
        int taskCount = 0;

        tsk = TaskRun(() =>
        {
            for (int i = 0; i < n; i++)
            {
                _log.Info("测试日志 " + i.ToString("000000"));
                Interlocked.Increment(ref taskCount);
            }
        });
        taskList.Add(tsk);

        tsk = TaskRun(() =>
        {
            for (int i = 0; i < n; i++)
            {
                _log.Info("测试日志 " + i.ToString("000000"));
                Interlocked.Increment(ref taskCount);
            }
        });
        taskList.Add(tsk);

        Task.WaitAll(taskList.ToArray());
        Log("Task Count=" + taskCount);

        Log("==== 结束 " + "，耗时：" + stopwatch.Elapsed.TotalSeconds.ToString("0.000") + " 秒 ========");
        stopwatch.Stop();
    });
}

private Task TaskRun(Action action)
{
    return Task.Run(() =>
    {
        try
        {
            action();
        }
        catch (Exception ex)
        {
            Log(ex.Message + "\r\n" + ex.StackTrace);
        }
    });
}
```

**Comment by 0611163** [comment]
My LogUtil and NLog，this NLog config is OK(Big archiving file size)：
[https://gitee.com/s0611163/LogUtil](https://gitee.com/s0611163/LogUtil)

**Comment by snakefoot** [comment]
@0611163 You should not use `throwExceptions="true"`. Please capture NLog-InternalLogger output again, but using `throwExceptions="false"`.

Notice that you are mixing [static- and dynamic-archive-mode](https://github.com/NLog/NLog/wiki/File-target#dynamic-vs-static-archive-logic), which is not supported:

```xml
  <variable name="logFileName" value="${date:format=yyyyMMdd_HHmmss}.txt"/>
  <variable name="logArchiveFileName" value="${date:format=yyyyMMdd_HHmmss}_{#}.txt"/>
```

So please remove `archiveFileName` from NLog.config:

```xml
    <target xsi:type="File" name="info"
            layout="${logLayout}"
            fileName="${logDir}/info/${logFileName}"
            archiveAboveSize="10240"
            maxArchiveFiles="100"
            concurrentWrites="true"
            keepFileOpen="true"
            openFileCacheTimeout="30"
            encoding="UTF-8" />

    <target xsi:type="File" name="debug"
            layout="${logLayout}"
            fileName="${logDir}/debug/${logFileName}"
            archiveAboveSize="10240"
            maxArchiveFiles="100"
            concurrentWrites="true"
            keepFileOpen="true"
            openFileCacheTimeout="30"
            encoding="UTF-8" />

    <target xsi:type="File" name="error"
            layout="${logLayout}"
            fileName="${logDir}/error/${logFileName}"
            archiveAboveSize="10240"
            maxArchiveFiles="100"
            concurrentWrites="true"
            keepFileOpen="true"
            openFileCacheTimeout="30"
            encoding="UTF-8" />
```

**Comment by 0611163** [comment]
I'm really sorry. I made a mistake.Set maxArchiveFiles larger is OK.When I set maxArchiveFiles to 1000,no logs lost.
