### ISSUE TITLE
Use Layout Variables inside Compound Layouts?

### ISSUE THREAD

**Issue by RyanGaudion** [NLog/NLog#4936]
In my NLog Config I have a variable to hold my JsonLayout:

```
<variable name="jsonLayoutv0.1">
    <layout type="JsonLayout">
      <attribute name="time" layout="${longdate}" />

    </layout>
  </variable>
```

I then want to place this layout inside a compoundLayout later on in my NLog config without having to re-write the whole jsonLayout again:
```
<sl:layout xsi:type="CompoundLayout">
    <layout xsi:type="SimpleLayout" text="@cee: " />
    <INSERT HERE/>
</sl:layout>
```

How can I go about re-using the variable inside a CompoundLayout?

**Comment by snakefoot** [comment]
Think you have found a soft spot in the NLog v5 implementation of NLog Config Variables and reusable Layout-variables.

Can see the config-parser-logic for creating Layout-instances to insert into `IList<Layout>`-collection, fails to check the NLog-Config-Variables.

**Comment by RyanGaudion** [comment]
@snakefoot - if this was to be implemented - what would be the preferred syntax?

**Comment by snakefoot** [comment]
I guess one could do this, where it then validates if the NLog-config-variable is of type JsonLayout:

```xml
      <layout type='CompoundLayout'>
        <layout type='SimpleLayout' text='@cee: ' />
        <layout type='JsonLayout' text='${jsonLayoutv0.1}' />
      </layout>
```

And maybe if possible then one could do this (Skipping Layout-type validation):

```xml
      <layout type='CompoundLayout'>
        <layout type='SimpleLayout' text='@cee: ' />
        <layout type='Layout' text='${jsonLayoutv0.1}' />
      </layout>
```

**Comment by snakefoot** [comment]
I guess one could do this, where it then validates if the NLog-config-variable is of type JsonLayout:

```xml
      <layout type='CompoundLayout'>
        <layout type='SimpleLayout' text='@cee: ' />
        <layout type='JsonLayout' text='${jsonLayoutv0.1}' />
      </layout>
```

And maybe if possible then one could do this (Skipping Layout-type validation):

```xml
      <layout type='CompoundLayout'>
        <layout type='SimpleLayout' text='@cee: ' />
        <layout type='Layout' text='${jsonLayoutv0.1}' />
      </layout>
```

@304NotModified Any thoughts? Guess we also have to consider appsettings.json.

**Comment by 304NotModified** [comment]
> I guess one could do this, where it then validates if the NLog-config-variable is of type JsonLayout:
> 
> ```
>       <layout type='CompoundLayout'>
>         <layout type='SimpleLayout' text='@cee: ' />
>         <layout type='JsonLayout' text='${jsonLayoutv0.1}' />
>       </layout>
> ```
> 
> And maybe if possible then one could do this (Skipping Layout-type validation):
> 
> ```
>       <layout type='CompoundLayout'>
>         <layout type='SimpleLayout' text='@cee: ' />
>         <layout type='Layout' text='${jsonLayoutv0.1}' />
>       </layout>
> ```
> 
> @304NotModified Any thoughts? Guess we also have to consider appsettings.json.

I think the first example is nice. The 2nd is maybe better, but its important that this won't result in much more code in NLog. 

And yes, would be great to support in appsettings. I don't know the needed steps for that.

**Comment by 304NotModified** [comment]
The type is the value? Looks a bit confusing

**Comment by snakefoot** [comment]
More like the type comes from a config-variable.

**Comment by snakefoot** [comment]
NLog 5.0.1 is now available: https://www.nuget.org/packages/NLog/5.0.1

**Comment by RyanGaudion** [comment]
@snakefoot - thank you for your help. All working as expected with the new package
