### ISSUE TITLE
LogFactory-constructor with LoggingConfiguration-input-parameter is obsolete in NLog 5

### ISSUE THREAD

**Issue by vuplea** [NLog/NLog#4937]
I'm using different `NLogTraceListener` instances in the same app, each with different configuration files.
This seems to work:
`var listener1 = new NLogTraceListener { LogFactory = new LogFactory(new XmlLoggingConfiguration("NLog1.config")) };`

Now, since 5.0, the `LogFactory(configuration)` constructor is deprecated.
How would I acheive the same effect without using the deprecated API?

Thanks!

**Comment by snakefoot** [comment]
Closing question as answered, due to inactivity.
