### ISSUE TITLE
3.2.0 release notes - fluent interface 

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#494]
In my opinion the [fluent interface](https://github.com/NLog/NLog/pull/382) should be introduced in [the release notes](http://nlog-project.org/2015/01/12/nlog-3-2-0-is-released.html)

**Comment by Xharze** [comment]
It should, I had mislabeled the issue which made it disappear in my filtering. 
I'll update the post

**Comment by 304NotModified** [comment]
:+1:

**Comment by 304NotModified** [comment]
FYI: I will post a new message next week,  including examples

**Comment by Xharze** [comment]
That would be awesome, thank you very much

**Comment by 304NotModified** [comment]
Almost done. Preview: https://304notmodified.github.io/2015/01/20/have-you-seen-our-new-fluent-interface.html.

Will post it tomorrow.

**Comment by Xharze** [comment]
Looks very good

**Comment by 304NotModified** [comment]
https://github.com/NLog/NLog.github.io/pull/9
