### ISSUE TITLE
Can't use NLog-Config-Variables to control the enabled-flag for relevant Logging Rules

### ISSUE THREAD

**Issue by adimoi** [NLog/NLog#4948]
I need to use an NLog config variables to control the enabled-flag for logging rules. My intention is to assign the values of those NLog config variables from the appsettings.json, which allows me to override them using stage-based environment variables in my CI/CD Pipeline.

The following snippet of the  NLog config works as expected by instructing NLog to not log to the file target
```
    <rules>
		<logger name="*" minlevel="debug" writeTo="file" enabled="false"/>
    </rules>
```
while the following snippet returns the error: "Warn Error has been raised. Exception: NLog.NLogConfigurationException: 'enabled' hasn't a valid boolean value '${fileLogEnable}'."
```
    <variable name="fileLogEnable" value="false" />
    
    <rules>
		<logger name="*" minlevel="debug" writeTo="file" enabled="${fileLogEnable}"/>
    </rules>
```

**NLog version**: 5.0.0

**Platform**:  .NET6

**Current NLog config**

```xml
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
	  internalLogToConsole="true" 
	  internalLogFile="/LogFiles/NLog_internal.log" 
	  internalLogLevel="Warn"
	  >

    <extensions>
		<add assembly="NLog.Web.AspNetCore"/>
    </extensions>
    
    <targets async="true">
		
        <target 
			xsi:type="File"
			name="file"
			fileName="/LogFiles/Test_NLog_Rules.log"
			layout="${longdate}|${event-properties:item=EventId.Id}|${machinename}|${aspnet-request-ip}|${aspnet-request-host}|${aspnet-request-method}|${uppercase:${level}}|${logger}|${message} ${exception}"
			archiveFileName="/LogFiles/Test_NLog_Rules{#}.log"
			archiveNumbering="DateAndSequence"
			archiveAboveSize="10485760"
			maxArchiveDays="14"
			maxArchiveFiles="14"
		/> 
      
    </targets>
    
    <!--<variable name="fileLogEnable" value="${configsetting:item=EnableLogTarget.File}" />-->
    <variable name="fileLogEnable" value="false" />
    
    <rules>
		<logger name="*" minlevel="debug" writeTo="file" enabled="${fileLogEnable}"/>
		<!--<logger name="*" minlevel="debug" writeTo="file" enabled="false"/>-->
    </rules>
</nlog>
```

- What is the current result? Rules logger's enabled flag of true/false cannot be controlled from a NLog config variable
- What is the expected result? Control the rules logger's enabled flag from a NLog config variable
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)? Yes
- Please post full exception details (message, stacktrace, inner exceptions) See attached "NLog_internal.log"
- Are there any workarounds? Unknown
- Is there a version in which it did work? Unknown
- Can you help us by writing an unit test? .NET Core API Project attached

[NLog_internal-when_enabled_is_assigned_false.log](https://github.com/NLog/NLog/files/8793971/NLog_internal-when_enabled_is_assigned_false.log)
[NLog_internal-when_enabled_is_assigned_fileLogEnable_variable.log](https://github.com/NLog/NLog/files/8793954/NLog_internal-when_enabled_is_assigned_fileLogEnable_variable.log)
[Test_NLog_Rules.zip](https://github.com/NLog/NLog/files/8793958/Test_NLog_Rules.zip)

**Comment by snakefoot** [comment]
You can use NLog-variables for `minlevel="..."` where `Off` / `None` means the same as enabled=false.

**Comment by adimoi** [comment]
I'll use that then. It works. Thank you!
