### ISSUE TITLE
ActiveMQ Integration

### ISSUE THREAD

**Issue by olitazl** [NLog/NLog#495]
Is there a plan for a ActiveMQ target? 

There is an commit on https://github.com/jkowalski/NLog/pull/20 which could be the solution. Is an integration planned?

**Comment by 304NotModified** [comment]
It think it should be added to the [NLog Contrib repository ](https://github.com/NLog/NLog-Contrib)

Don't know if we can easily move the PR

**Comment by Xharze** [comment]
I'll try to move the code to the Contrib repository

**Comment by Xharze** [comment]
A pull request for the ActiveMQ target have been created in the contrib repository.

**Comment by 304NotModified** [comment]
link: https://github.com/NLog/NLog-Contrib/pull/19

**Comment by 304NotModified** [comment]
moved to https://github.com/NLog/NLog.Contrib.ActiveMQ

closing out
