### ISSUE TITLE
Add message template syntax support for `ILogger.BeginScope` overloads

### ISSUE THREAD

**Issue by Strandedpirate** [NLog/NLog#4955]
**NLog version**:  5.0.0.0

**Platform**: .NET6

Add support for message template syntax when using `ILogger.BeginScope` so that we can control formatting of data added at that level. I want to pepper every log with searchable JSON data using scope level key/values, however it currently doesn't support [this](https://stackoverflow.com/questions/72435251/nlog-formatting-as-json-using-beginscope)

Currently we can control formatting at an individual log message level, which is great, but that produces extreme amounts of noise in many cases, because a log's message and its associated structured JSON data show up appended to one another in whatever UI you use. Having scoped level data that we can control the formatting of, eliminates this log noise in many instances.

example of log noise:
![image](https://user-images.githubusercontent.com/1452996/171323388-6a9d2a06-9b00-49af-9b3b-d023f881e4ed.png)

example of desired scope level usage:
```
using (_logger.BeginScope(new Dictionary<string, object>
{
	["OrderId"] = 3456,
	["{@Order}"] = myOrderObject
}))
{
	_logger.LogInformation("Placing order...");
}
```
![image](https://user-images.githubusercontent.com/1452996/171324889-2304e7c6-fb74-40c6-bdd1-29f53b33a919.png)

**Comment by snakefoot** [comment]
You are right that message-template-logic has not been implemented for the NLog ScopeContext-Dictionary.

NLog JsonLayout in NLog v5 will by default attempt to serialize the first-level of object-properties (`MaxRecursionLimit=1`). So if using `IncludeScopeProperties=true` then it will serialize the object-properties (Independent of using `"@Order"` or `"Order"` as key).

It would also be a breaking change if it suddenly stripped aways the `@` for the keys in NLog ScopeContext-Dictionary.

Closing the issue as won't fix.
