### ISSUE TITLE
Error Error parsing layout +U36A/^e will be ignored. Exception: System.ArgumentException: LayoutRenderer cannot be found: '+U36A/^e'

### ISSUE THREAD

**Issue by HJami** [NLog/NLog#4962]
Hi! Thanks for reporting this bug! 

NLog version:  4.7.9

Platform: .Net 4.8 

I guess this is happening because my connection string db has a password o*LSG|${+U36A/^e which causes problem for NLog. Seems like the + in the password maybe the issue based on the error log.

**Comment by snakefoot** [comment]
Not sure what the problem is. But you are always wellcome to provide a pull-request with unit-test and code-fix.
