### ISSUE TITLE
AsyncWrapper writing in slow batches after upgrade to v5.0

### ISSUE THREAD

**Issue by ssteiner** [NLog/NLog#4977]
I've recently upgraded from the 4.7 train to 5.0. I'm using `AsyncTargetWrapper` for log targets so as to not clog up the application if there's a lot of logging going on (e.g. if debug logging is active). Since the upgrade to 5.0, I've noted that my logfiles get updates a lot more sparsely.. it can take minutes until the logfile is updated. when I add a console output, I see the log messages appear in the console instantaneously, but not in the file. This used to be different prior to the upgrade from 4.7.15 to 5.0 (and the issue persists in 5.0.1).

**NLog version**: 5.0.1

**Platform**: ..NET6

**Current NLog config** (xml or C#, if relevant)

```csharp
	var logFactory = new LogFactory();
	var logConfig = new NLog.Config.LoggingConfiguration();
	var logFile = new NLog.Targets.FileTarget("logfile")
	{
		FileName = "mylogfile.txt",
		ArchiveNumbering = NLog.Targets.ArchiveNumberingMode.Rolling,
		ArchiveEvery = NLog.Targets.FileArchivePeriod.None,
		MaxArchiveFiles = 10,
		ArchiveAboveSize = 5 * 1024,
	};
	logFile.Layout = "${longdate}|${level:uppercase=true}|${message}";
	var wrapper = new AsyncTargetWrapper(logFile, 5000, AsyncTargetWrapperOverflowAction.Grow);
	logFileRule = new NLog.Config.LoggingRule("*", NLog.LogLevel.Info, NLog.LogLevel.Fatal, wrapper);
	logConfig.LoggingRules.Add(logFileRule);
	logFactory.Configuration = logConfig;
	logger = logFactory.GetLogger("logger");

```

- What is the current result?

Logging to `mylogfile.txt` is done in batches - it can take minutes for the data that the application wants to log to actually show up in the logfile.

- What is the expected result?
`logger.Log()` should write to Logfile near immediately.

- Are there any workarounds? yes/no

Downgrade to the latest release of the 4.x train.

- Is there a version in which it did work? 

It worked fine up to 4.7.15

**Comment by snakefoot** [comment]
Make sure you are using .NET6 ver. 6.0.200 (or newer). See also https://github.com/dotnet/runtime/issues/61804 (New portable Thread-Dispatcher ignores background-timer events on high load).

**Comment by ssteiner** [comment]
I ran this on .NET 6.0.6. And as I said, it doesn't happen with 4.7.15. In fact, I reverted our software to 4.7.15 this afternoon, installed it on two sites, and it works as expected.

**Comment by snakefoot** [comment]
Maybe it is because NLog 5 changes default-value for FileTarget `KeepFileOpen = true`, and your current file-viewer-tool doesn't like this.

What happesn if you change to this:

```c#
	var logFile = new NLog.Targets.FileTarget("logfile")
	{
		FileName = "mylogfile.txt",
		ArchiveNumbering = NLog.Targets.ArchiveNumberingMode.Rolling,
		ArchiveEvery = NLog.Targets.FileArchivePeriod.None,
		MaxArchiveFiles = 10,
		ArchiveAboveSize = 5 * 1024,
                KeepFileOpen = false,   // Change to NLog 4 default value
	};
```

**Comment by ssteiner** [comment]
@snakefoot I thought about that, too. I've yet to test if changing that flag changes anything, but I've looked at the logfile in various editors, as well as from Windows Explorer, and no editor shows updated data. the last changed date is also not updated.. only minutes after the fact. My guess would be that some buffer in NLog 5 only gets flushed every now and then (based on a timer, or number of log entries). In NLog 4, log entries weren't written to the logfile line per line, too... if the app would push log entries too quickly, it would could take a bit (I'd say maybe a handful of seconds, tops) until the logfile would show up as changed in explorer.
I'll test if `KeepFileOpen` changes anything.

**Comment by ssteiner** [comment]
I'm on Win11 Pro with NET 6.0.6. Files are written to the local hard drive. I'm using [Tail for Win32](http://tailforwin32.sourceforge.net/) and I tried the trusted old notepad to open the files. And looking at the files in Windows Explorer, I did not see the 'date modified' nor the size change. if I deleted the logfile, started my app, a 0 byte file would appear, and remain at 0 bytes (despite furiously refresh) until that point where Tail for Win 32 picked up the changes. It all came at the same time: tail would show an update, the file size would increase, last modified would be changed, and notepad would show the new lines. But it really felt like nothing was being written for a while. I'm happy to try other file editors if what I'm describing sounds like a possible bug.

**Comment by snakefoot** [comment]
[Tail for Win32 stopped working correctly since Windows Vista](https://github.com/NLog/NLog/wiki/AssemblyVersion-Layout-Renderer). 

Windows Explorer does a lot of caching, even if you refresh teh folder. But if you right-click the log-file in Windows Explorer and choose "Properties", then it will force a cache-refresh, and will show the expected file-size (and modified-timestamp).

Curious about Notepad not working, since it has always been working for me. Though a little tedious tool for doing file-monitor, as you have to open/close the file constantly to see latest changes.

**Comment by snakefoot** [comment]
Closing issue as resolved, due to inactivity
