### ISSUE TITLE
InstallNlogConfig.exe missing from nupkeg

### ISSUE THREAD

**Issue by aggieben** [NLog/NLog#498]
Hopefully I've just missed something silly, but I have the `NLog.3.2.0.0` nupkeg installed in my project, and the `InstallNLogConfig.exe` tool isn't in the package folder.  Has it been removed/moved from the package, or is there another package I should get that has it?

**Comment by 304NotModified** [comment]
Regression of #200

**Comment by 304NotModified** [comment]
Kim, can you answer this one? Dunno what the `InstallNLogConfig.exe` should do...

**Comment by 304NotModified** [comment]
related #199

**Comment by 304NotModified** [comment]
Bump @Xharze

**Comment by Xharze** [comment]
I'll create a separate repository of InstallNLogConfig

**Comment by aggieben** [comment]
@Xharze is there a reason it shouldn't be installed with NLog?  I very much like the idea of it being part of the whole, and not separate.

**Comment by 304NotModified** [comment]
Well I think not everyone needs the installer. The 4.0 release of NLog should be much modular then previous versions. 

And with Nuget, installing isn't more work. Just install `NLog.InstallNLogConfig` instead of `NLog` (because of dependencies)  - I will amuse we will create a Nuget package for this @Xharze ?

**Comment by Xharze** [comment]
Yes I'm in the process of creating the package. I'm almost done just need
the last couple of things completed.

**Comment by Xharze** [comment]
The tool has been moved to the NLog/NLog.InstallNLogConfig repository. It has been merged in NLog/NLog.InstallNLogConfig#1.
