### ISSUE TITLE
LayoutRenderer exception when using variable reference in another variable

### ISSUE THREAD

**Issue by Fluttercom** [NLog/NLog#4984]
Moving our NLog config from XML to json.
Had this approach that worked:
```xml
  <variable name="appMode" value="DBProc" />
  <variable name="logDirectory" value="${basedir}/../../Logs/${appMode}"/>
```
Once moved to json, it throws exception "LayoutRenderer type-alias is unknown: 'serviceName'":
```json
"variables": {
      "serviceName": "DBProc",
      "logDirectory": "${baseDir}\\..\\..\\Logs\\${serviceName}"
    },
```

**Comment by snakefoot** [comment]
Yes Microsoft Json Parser is a little special, so when reading a json-document, then properties are always received in order sorted-by-key. Which means `"logDirectory"` is read before `"serviceName"`. 

If you renamed  `"serviceName"` to `"appName"` then the nlog-config-variables will be parsed without issues.

**Comment by snakefoot** [comment]
Closing issue as resolved, due to inactivity.
