### ISSUE TITLE
NLog xsi:type or type attribute

### ISSUE THREAD

**Issue by ThomasArdal** [NLog/NLog#4986]
I'm interested (and maybe a bit confused) about the use of the `xsi:type` when configuring NLog targets in XML-based config files:

```xml
<target name="logconsole" xsi:type="Console" />
```

This is how it is recommended in the documentation and how I have configured NLog in the past as well. My confusion is around using the `type` attribute (no namespace) which also seems to work and which multiple samples around the web uses.

Would it make sense to document the thoughts behind this somewhere? The use of `xsi:type` over `type` is currently causing a bit of a problem with IntelliSense (https://github.com/NLog/NLog/issues/4978), which could potentially be avoided if possible values for types would be defined in NLog's schema and not the xsi one. So, there must be some other advantages or reasons to use `xsi:type`?

**Comment by snakefoot** [comment]
Think it is a great idea to find someone that knows everything about using XSD and how to make best use of `xsi:type`.

Until that person arrive, then you are more than wellcome to update the NLog Wiki-pages with all the details you have :)

**Comment by ThomasArdal** [comment]
I wouldn't mind writing something on the wiki at all. But my point is that I don't understand why `xsi:type` is used rather than just having a `type` attribute. Is it because that provides some advantages within NLog when needing to resolve targets?

**Comment by snakefoot** [comment]
When the NLog Schema is loaded correctly, then suddenly you have intellisense like this:

![image](https://user-images.githubusercontent.com/11509660/175108541-10e2c0fd-b54a-4383-9f1b-1df2ace9158f.png)

And it only works when using `xsi:type` as it is used for looking in NLog.xsd.

**Comment by ThomasArdal** [comment]
Ah I see. Thanks.
