### ISSUE TITLE
nuget tags

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#499]
Please tag the packages on nuget.com, like log4net for example.

**Comment by Xharze** [comment]
The releases should have been tagged, which ones aren't?

**Comment by 304NotModified** [comment]
![image](https://cloud.githubusercontent.com/assets/5808377/5768257/55de0de0-9d0f-11e4-952c-f1c9801a647b.png)

Compare left and right side. 

NLog is more difficult to find without those tags.

**Comment by Xharze** [comment]
Now I understand, I thought about Git tags. Of course NLog should've been
tagged. I believe this is done on package level in the nuspec file, if so
I'll fix it in the next release.
Den 15/01/2015 23.37 skrev "Julian" <notifications@github.com>:

**Comment by Xharze** [comment]
I've also updated the tags for the current packages

**Comment by 304NotModified** [comment]
:+1: :+1:
