### ISSUE TITLE
ArgumentException: Target type-alias is unknown: 'Database'. Extension NLog.Database not included?

### ISSUE THREAD

**Issue by lovachen** [NLog/NLog#4991]
Hi! Thanks for reporting this bug! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

**NLog version**: (e.g. 4.4.13)

**Platform**: .Net 3.5 / .Net 4.0 / .Net 4.5 / Mono 4 / Xamarin Android / Xamarin iOS / .NET Core / .NET5 / .NET6

**Current NLog config** (xml or C#, if relevant)

```xml
<nlog>
  <targets>
<target name="database" xsi:type="Database" dbProvider="Npgsql.NpgsqlConnection, Npgsql" >
			<connectionString>Server=127.0.0.1;port=5432;database=test;user id=postgres;password=123456;</connectionString>
			<!--<connectionString>${var:connectionString}</connectionString>-->
			<commandText>
				insert into nlog (
				machine, logged, level, message,
				logger, callsite, exception,application
				) values (
				@machine, @logged, @level, @message,
				@logger, @callsite, @exception,@application
				);
			</commandText>
			<parameter name="@machine" layout="${machinename}" />
			<parameter name="@logged" layout="${date}" />
			<parameter name="@level" layout="${level}" />
			<parameter name="@message" layout="${message}" />
			<parameter name="@logger" layout="${logger}" />
			<parameter name="@callsite" layout="${callsite}" />
			<parameter name="@exception" layout="${exception:tostring}" /> 
			<parameter name="@application" layout="pms.api" />
		</target>
  </targets>
  <rules>
<logger name="*" minlevel="Error" writeTo="database" />
  </rules>
</nlog>

```

- What is the current result?
- What is the expected result?
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
- Please post full exception details (message, stacktrace, inner exceptions)
- Are there any workarounds? yes/no
- Is there a version in which it did work? 
- Can you help us by writing an unit test?

**Comment by snakefoot** [comment]
NLog 5.0 introduces several breaking changes. And NLog DatabaseTarget has been [extracted into a seperate nuget-package](https://nlog-project.org/2021/08/25/nlog-5-0-preview1-ready.html#nlog-targets-extracted-into-their-own-nuget-packages).

Add the nuget-package [NLog.Database](https://www.nuget.org/packages/NLog.Database) to your solution, and things should work again.

**Comment by VassilSanych** [comment]
Why not yet for Core?

**Comment by snakefoot** [comment]
@VassilSanych Please create new issue, instead of waking up old ones.
