### ISSUE TITLE
Incorrect relative log path when starting with UNC path

### ISSUE THREAD

**Issue by Fluttercom** [NLog/NLog#5007]
**NLog version**: 5.0.1

**Platform**: .NET5

**Current NLog config** 

```xml
	<!-- the targets to write to -->
  <targets>
    <target xsi:type="File" name="info" fileName="${basedir}/../../Logs/info.log" />
  </targets>

  <!-- rules to map from logger name to target -->
  <rules>
    <logger name="*" minlevel="Info" writeTo="info" />
  </rules>

```
This simple config should save the log two folder levels up, i.e. if we place the app in
C:\software\nlogApp\nlogApp.exe
the logger will create the Log folder in C:\

But if we start the app this way:
\\\myserver\software\nlogApp\nlogApp.exe
The Log folder is created in software folder

**Comment by snakefoot** [comment]
Can you provide the [NLog Internal logger](https://github.com/NLog/NLog/wiki/Internal-Logging) output at Debug-Level for the two scenarios ?

**Comment by Fluttercom** [comment]
Internal log looks ok to me, but final path is \\d08cl0033\TPS.Net\Logs\info.log in this case
[nlog-internal.txt](https://github.com/NLog/NLog/files/9190339/nlog-internal.txt)

**Comment by snakefoot** [comment]
The filename `\\d08cl0033\TPS.Net\NLogBench\..\..\Logs\info.log`  is the input-parameter to the FileStream-constructor:

```
2022-07-26 16:44:30.6078 Trace FileTarget(Name=info): Opening \\d08cl0033\TPS.Net\NLogBench\..\..\Logs\info.log with allowFileSharedWriting=False
```

If it fails to create the log-file the correct location, then I guess you should create a small reproducable case for Microsoft showing that FileStream-constructor is not behaving as expected.

**Comment by Fluttercom** [comment]
Raised issue in .net core:
https://github.com/dotnet/runtime/issues/73075

**Comment by Fluttercom** [comment]
Ok, seems it is related to Windows security, closing this.
