### ISSUE TITLE
Can't disable matching rule

### ISSUE THREAD

**Issue by joaoportela** [NLog/NLog#501]
I'm trying to make messages from loggers matching a specific pattern be ignored, without success.
I tried doing:

```xml
<logger name="HighThroughputLog.*" enabled="false" final="true" />
<logger name="*" minLevel="Trace" writeTo="logFile" />
```

Expecting that when a log name matches `HighThroughputLog.*` (at any log level), the `enable=false` kicks in, which makes it not write anything. The `final="true"` should make all the following rules be ignored.

Therefore making that log messages written to a logger  matching `HighThroughputLog.*` would not appear on the log file. Am I misunderstanding how this works?

Tried with 2.1.0 and 3.2.0

**Comment by ilya-g** [comment]
`enable="false"` makes this rule ignored. So the effect is the same as if this rule was not present.
To get what you need you should write this rule with `enabled="true"` or without `enabled` attribute:

```xml
    <logger name="HighThroughputLog.*" final="true" />
    <logger name="*" minLevel="Trace" writeTo="logFile" />
```

**Comment by joaoportela** [comment]
Yeah, making the rule without the writeTo should work. I should have though of that.

Thanks.
