### ISSUE TITLE
Communication improvement proposal

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#502]
As a regular user of NLog I really like this library. The library has a lot of great features and is actively maintained, which is important for us as users.

But I noticed some areas that can be improved in the NLog project, mainly in the communication part; the announcements are often delayed and there are a lot of unnecessary open issues on GitHub. I would like to help on this part, as I think that effective communication is essential for a library.
So I would like to volunteer to:

-	Write news posts and keep the NLog website up-to-date
-	Label issues on GitHub and close them if possible

**Comment by Xharze** [comment]
Hi Julian,

That would be great, as the only active project maintainer, I'm a bit
stretched in resources. And would greatly appreciate any help I can get. I
can add you as a member of the Nlog organization allow you to work easily
with the points you've described. How does this sound?
Den 16/01/2015 19.50 skrev "Julian" <notifications@github.com>:

**Comment by Xharze** [comment]
Just to explain, I totally agree with you the communication is pretty bad, and it's my fault. Personally I hate the missing communication. That's is the reason why I'm very happy you are willing to help.

**Comment by 304NotModified** [comment]
Hi Kim, 

I'm glad to help! Just add me and I will contribute on the next few days. I have (of course) a fulltime job but I'm pretty sure I can be helpful :)
