### ISSUE TITLE
nLog target to .Net 4.8

### ISSUE THREAD

**Issue by jc229** [NLog/NLog#5021]
Hi! Thanks for reporting this feature!

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

**NLog version**: 5019

**Platform**: .Net 4.8

Support for .NET Framework 4.5.2, 4.6, and 4.6.1 ended on April 26, 2022. Would it be possible that all projects targeted to net48;netstandard2.1;netcoreapp3.1 ? Thanks!

**Comment by snakefoot** [comment]
> Would it be possible that all projects targeted to net48;netstandard2.1;netcoreapp3.1 ?

What is the goal of changing the target-platforms for the NLog-project ?

**Comment by jc229** [comment]
The goal is get nLog.DLL with net48. I am able to add it. No issues. Thanks!

**Comment by snakefoot** [comment]
Yes the nuget-website now have a supported-frameworks-page:

https://www.nuget.org/packages/NLog#supportedframeworks-body-tab

**Comment by jc229** [comment]
Many Thanks!
