### ISSUE TITLE
Json loggin

### ISSUE THREAD

**Issue by Neolinsky** [NLog/NLog#5030]
Hi!

I don't know if it's a thing or not, but can I (would be nice) configure Nlog so that every time I Log something it converts to JSON format without me having to JsonLayout.Render() it? Doesn't really matter what json layout I have, just in general.

Because right now I haven't found a way to do so. I made something similar to what I want in my own project, but still maybe you already have a way to do so.

**NLog version**: (e.g. 5.0.2)

Platform: .NET6

By the way, please don't mind me if I made mistakes, English isn't my main language. If you did not understand me, please don't hesitate to let me know. Be safe!🙃

**Comment by snakefoot** [comment]
Maybe something like this:

```xml
<target name="jsonFile" type="File" fileName="AppLogFile.json" >
      <layout type="MicrosoftConsoleJsonLayout" />
</target>
```

See also: https://github.com/NLog/NLog/wiki/MicrosoftConsoleJsonLayout

**Comment by Neolinsky** [comment]
> Maybe something like this:
> 
> ```xml
> <target name="jsonFile" type="File" fileName="AppLogFile.json" >
>       <layout type="MicrosoftConsoleJsonLayout" />
> </target>
> ```
> 
> See also: https://github.com/NLog/NLog/wiki/MicrosoftConsoleJsonLayout

Thank u

**Comment by snakefoot** [comment]
Closing issue as resolved.
