### ISSUE TITLE
NLog auto-reload is spuriously reloading

### ISSUE THREAD

**Issue by jbayardo** [NLog/NLog#5041]
**NLog version**: 4.7.7 onwards for sure. Not clear when it started

**Platform**: All platforms should be affected

**Current NLog config** irrelevant. We do have config autoreload enabled.

- What is the current result? NLog reloads configuration on any change to a configuration file, regardless of whether the change is a material change in what NLog is expected to be doing or not. 
- What is the expected result? NLog reload should reload only on material changes to configuration files
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)? yes, no errors displayed ther
- Please post full exception details (message, stacktrace, inner exceptions): as far as we could tell, the problem is this line of code: https://github.com/NLog/NLog/blob/dev/src/NLog/Config/LoggingConfigurationWatchableFileLoader.cs#L166, it seems to be comparing the old/new configuration via `ReferenceEquals` instead of `Equals`.
- Are there any workarounds? no
- Is there a version in which it did work? unsure
- Can you help us by writing an unit test? not at this time

**Comment by snakefoot** [comment]
The `if (!ReferenceEquals(_logFactory._config, oldConfig))` is only to protect against the Microsoft-FileWatcher that can trigger many file-changed-events for a single file-modifications.

There have never been any validation whether a file-modification resulted in the NLog-configuration being unchanged.

My suggestion is stop the user/application that triggers file-modification-events, unless there is a real file-change.

**Comment by jbayardo** [comment]
We indeed have stopped using autoReload="true", as we found out it was causing us to keep stopping and starting NLog all the time, which was creating an interesting set of issues. 

Unfortunately for us, we don't control the deployment system that places the NLog.config file on disk, and it seems this system likes to keep rewriting the file even without any changes (which is what I guess is causing the constant restarts).

In any case, thank you for the prompt reply and for NLog!

**Comment by snakefoot** [comment]
>  Causing stopping and starting of NLog all the time, which was creating an interesting set of issues.

Yes it is a non-trivial operation to replace the NLog-configuration, while all Loggers are still firing LogEvents. 

And it is expected that LogEvents are lost in during the transition from closing old targets and initializing new targets.

So I guess the AutoReload-feature is mostly for long-running-applications where restarting/deploying is not an option.

**Comment by snakefoot** [comment]
Closing the issue as answered.
