### ISSUE TITLE
[Regression] Publishing trimmed app depending on NLog 5.0.3 causes additional IL2007 warnings

### ISSUE THREAD

**Issue by JustArchi** [NLog/NLog#5050]
**NLog version**: 5.0.3

**Platform**: .NET6

**Current NLog config**: Irrelevant

- What is the current result?

Publishing trimmed app with NLog dependency causes new `IL2007` warnings, I've posted example log further below. While those do not fail the build in default settings, they can if `<TreatWarningsAsErrors>` is used, like in my case.

See https://github.com/JustArchiNET/ArchiSteamFarm/pull/2696 for more details, which is the source of this report.

- What is the expected result?

I'd expect no additional IL warnings from the libraries I'm using, just like in version 5.0.2, but I don't know if it's possible.

- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?

Irrelevant, it's a build failure.

- Please post full exception details (message, stacktrace, inner exceptions)

```
Error: resource ILLink.Descriptors.xml in NLog, Version=5.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c(15,4): error IL2007: Could not resolve assembly 'NLog.Windows.Forms'. [/Users/runner/work/ArchiSteamFarm/ArchiSteamFarm/ArchiSteamFarm/ArchiSteamFarm.csproj]
Error: resource ILLink.Descriptors.xml in NLog, Version=5.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c(11,4): error IL2007: Could not resolve assembly 'NLog.OutputDebugString'. [/Users/runner/work/ArchiSteamFarm/ArchiSteamFarm/ArchiSteamFarm/ArchiSteamFarm.csproj]
Error: resource ILLink.Descriptors.xml in NLog, Version=5.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c(3,4): error IL2007: Could not resolve assembly 'NLog.Targets.AppCenter'. [/Users/runner/work/ArchiSteamFarm/ArchiSteamFarm/ArchiSteamFarm/ArchiSteamFarm.csproj]
Error: resource ILLink.Descriptors.xml in NLog, Version=5.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c(5,4): error IL2007: Could not resolve assembly 'NLog.Database'. [/Users/runner/work/ArchiSteamFarm/ArchiSteamFarm/ArchiSteamFarm/ArchiSteamFarm.csproj]
Error: resource ILLink.Descriptors.xml in NLog, Version=5.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c(6,4): error IL2007: Could not resolve assembly 'NLog.DiagnosticSource'. [/Users/runner/work/ArchiSteamFarm/ArchiSteamFarm/ArchiSteamFarm/ArchiSteamFarm.csproj]
Error: resource ILLink.Descriptors.xml in NLog, Version=5.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c(8,4): error IL2007: Could not resolve assembly 'NLog.Etw'. [/Users/runner/work/ArchiSteamFarm/ArchiSteamFarm/ArchiSteamFarm/ArchiSteamFarm.csproj]
Error: resource ILLink.Descriptors.xml in NLog, Version=5.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c(13,4): error IL2007: Could not resolve assembly 'NLog.WindowsEventLog'. [/Users/runner/work/ArchiSteamFarm/ArchiSteamFarm/ArchiSteamFarm/ArchiSteamFarm.csproj]
Error: resource ILLink.Descriptors.xml in NLog, Version=5.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c(16,4): error IL2007: Could not resolve assembly 'NLog.Wcf'. [/Users/runner/work/ArchiSteamFarm/ArchiSteamFarm/ArchiSteamFarm/ArchiSteamFarm.csproj]
Error: resource ILLink.Descriptors.xml in NLog, Version=5.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c(14,4): error IL2007: Could not resolve assembly 'NLog.WindowsIdentity'. [/Users/runner/work/ArchiSteamFarm/ArchiSteamFarm/ArchiSteamFarm/ArchiSteamFarm.csproj]
Error: resource ILLink.Descriptors.xml in NLog, Version=5.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c(10,4): error IL2007: Could not resolve assembly 'NLog.MSMQ'. [/Users/runner/work/ArchiSteamFarm/ArchiSteamFarm/ArchiSteamFarm/ArchiSteamFarm.csproj]
Error: resource ILLink.Descriptors.xml in NLog, Version=5.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c(4,4): error IL2007: Could not resolve assembly 'NLog.Targets.MauiLog'. [/Users/runner/work/ArchiSteamFarm/ArchiSteamFarm/ArchiSteamFarm/ArchiSteamFarm.csproj]
Error: resource ILLink.Descriptors.xml in NLog, Version=5.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c(12,4): error IL2007: Could not resolve assembly 'NLog.PerformanceCounter'. [/Users/runner/work/ArchiSteamFarm/ArchiSteamFarm/ArchiSteamFarm/ArchiSteamFarm.csproj]
Error: resource ILLink.Descriptors.xml in NLog, Version=5.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c(9,4): error IL2007: Could not resolve assembly 'NLog.MailKit'. [/Users/runner/work/ArchiSteamFarm/ArchiSteamFarm/ArchiSteamFarm/ArchiSteamFarm.csproj]
```

- Are there any workarounds? yes/no

Downgrading to 5.0.2 fixes the issue.

- Is there a version in which it did work? 

Yes, 5.0.2.

- Can you help us by writing an unit test?

Sorry, I'm out of time lately. But idea for unit test would be attempting to publish trimmed app depending on NLog with `<TreatWarningsAsErrors>true</TreatWarningsAsErrors>`

### Additional info

I believe the regression was introduced in https://github.com/NLog/NLog/pull/5034. Now I don't know if it's actually possible for you to avoid this warning, it doesn't cause a build failure unless `<TreatWarningsAsErrors>` is used. For my own usage I simply added it as `<WarningsNotAsErrors>`, but I thought you might be interested in evaluating whether it's intended or possible to correct. It's completely fine to close this report as-is if you determine it's intended and there is no way to improve it, but perhaps there is something to avoid it for the consumers if possible.

As usual I'd like to use this opportunity to thank you for marvelous work on this beautiful library.

**Comment by snakefoot** [comment]
Thank you for reporting this. The reason for adding the extra assemblies was to ensure they were not trimmed away, when used by the host-application.

The intention was not to produce build-warnings about assemblies not being used by the host-application.

Will fix `ILLink.Descriptors.xml` so it only includes NLog-core-assembly, and nothing else.

**Comment by snakefoot** [comment]
Thank you again for taking the time to report this issue. 

New release has been made with updated ILLink.Descriptors.xml:
- https://www.nuget.org/packages/NLog v5.0.4
- https://www.nuget.org/packages/NLog.Extensions.Logging v5.0.4
- https://www.nuget.org/packages/NLog.Web.AspNetCore v5.1.4

Hopefully this should resolve error IL2007

**Comment by JustArchi** [comment]
Thanks a lot, I really appreciate it, and I didn't expect so swift reply, all the best! :tada:

**Comment by snakefoot** [comment]
Notice that you have just merged v5.1.2 with the unwanted warning ignore. Could interesting if you could try v5.1.4 and not ignore the new warning.

**Comment by JustArchi** [comment]
If you mean my project @snakefoot then I'm using 5.1.4. as you can see **[here](https://github.com/JustArchiNET/ArchiSteamFarm/blob/main/Directory.Packages.props#L14)** and I've removed ignore of the warning, all is fine, thanks :slightly_smiling_face:

**Comment by snakefoot** [comment]
@JustArchi Not sure why that comment suddenly appeared. Guess GitHub somehow fixed its mail-queue, and suddenly stale comments are appearing.
