### ISSUE TITLE
The API reference is out-to-date

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#506]
The [API reference](http://nlog-project.org/documentation/) is very useful but out-dated. The API version is still on 2.0.1 while 3.2.0 is just released. The wiki links to this documentation.

Can this be updated?

**Comment by Xharze** [comment]
Ahh it stills links to the documentation. I'll check if it is possible to update. It was a part of the old build steps, before moving to Github, so I'll have to track back a bit to see how it was done.

**Comment by 304NotModified** [comment]
It think [Sandcastle Help File Builder](http://shfb.codeplex.com/) is used before. Sandcastle look alive again.

**Comment by 304NotModified** [comment]
If you gonna work with Sandcastle Help File Builder, it would be great to check in also the `.shfbproj` file.

**Comment by 304NotModified** [comment]
Any success on this @Xharze ?

**Comment by Xharze** [comment]
Actually I'm looking into this right now, there is an existing Msbuild
target to generate the documentation, I just have to figure out how to get
it working again.

**Comment by 304NotModified** [comment]
Well it tried the Sandcastle Help File Builder and it's working well. But there are a lot of configuration options and I don't know what to choose.

**Comment by Xharze** [comment]
I got it working. The documentation for v3.2 will be available later today,
I just need to fix the casing of two files as the webserver appears to be
case sensitive.

**Comment by Xharze** [comment]
The API documentation has been updated at http://nlog-project.org/documentation/v3.2.0/

**Comment by 304NotModified** [comment]
Great! I will add also a reference on the website for this (and remove the redirect to 2.0 documentation)

**Comment by 304NotModified** [comment]
One question, do you have any idea why the code filter isn't working? When I untick everything except c#, it works, but after a click if reset to default.

Tested in Firefox, IE11 and Chrome. 


![image](https://cloud.githubusercontent.com/assets/5808377/5901632/411ea10e-a574-11e4-877c-20a201eb96ac.png)

**Comment by Xharze** [comment]
I have no idea, but the version of sandcastle included in the repository is
probably very old, so updating might fix the problem.

**Comment by 304NotModified** [comment]
Sandcastle is not maintained anymore...is it possible to commit the sandcastle project file somewhere?

**Comment by Xharze** [comment]
It is committed in the current repository, it's placed in src/documentation

**Comment by 304NotModified** [comment]
@Xharze 
Something went wrong with the latest documentation generator. The `Logger` class doesn't have **members** (properties/methods) according to the api doc now.

[logger 2.0.1 api doc](http://nlog-project.org/documentation/v3.2.0/html/T_NLog_Logger.htm)
[logger 3.2.0 api doc](http://nlog-project.org/documentation/v2.0.1/html/T_NLog_Logger.htm)

**Comment by Xharze** [comment]
I'll take a look at it, and update the documentation when I figure it out

**Comment by 304NotModified** [comment]
Bump

**Comment by 304NotModified** [comment]
Close as we have the issue reported by an user: #578
