### ISSUE TITLE
NLog.NLogConfigurationException: LoggingRule where all filters and FilterDefaultAction=Ignore 

### ISSUE THREAD

**Issue by francis2** [NLog/NLog#5064]
**NLog version**: 5.0.4

**Platform**: .Net 4.8

**Current NLog config**

```xml
    <logger name="RejectedOrderLogger"                writeTo="rejectedordermail">
		<filters>
            <whenRepeated layout="${message}" timeoutSeconds="10" action="Ignore" >
                 <FilterCountMessageAppendFormat>--------------- The previous message occurred {0} times ---------------</FilterCountMessageAppendFormat>
            </whenRepeated>
         </filters>	
	</logger>
	
			<target name="rejectedordermail" xsi:type="AsyncWrapper" queueLimit="10" overflowAction="Discard">
				<target xsi:type="RetryingWrapper">
					<target xsi:type="Mail" 
					SmtpServer="smtp.sendgrid.net" 
					smtpUserName="mykey" 
					smtpPassword="mypw" 
					timeout="30" 
					enableSsl="False" 
					smtpAuthentication="Basic" 
					encoding="UTF-8"
					smtpPort="587" 
					from="help@mysite.com" 
					to="me@mysite.com" 
					subject="Rejected Order: ${var:AppName} ${var:BrokerID}"/>
				</target>			
			</target>
```

- Current result:
NLog.NLogConfigurationException: LoggingRule where all filters and FilterDefaultAction=Ignore : logNamePattern: (RejectedOrderLogger:Equals) levels: [ Trace Debug Info Warn Error Fatal ] writeTo: [ rejectedordermail ]

- Expected result:
 No error
 
- Is there a version in which it did work? 
No errors in previous builds up to 5.0.0

**Comment by snakefoot** [comment]
NLog v5 introduces the following breaking change:

- [LoggingRule Filters DefaultAction changed to FilterResult.Ignore](https://nlog-project.org/2021/08/25/nlog-5-0-preview1-ready.html#loggingrule-filters-defaultaction-changed-to-filterresultignore)

This means your current logging-rule will always have "ignore" as filter-result. NLog v5 uses the error-message to warn you that you will get unexpected result.

The solution is fixing the logging-rule like this (Adding `defaultAction="Neutral"`):

```xml
    <logger name="RejectedOrderLogger" writeTo="rejectedordermail">
	<filters defaultAction="Neutral">
            <whenRepeated layout="${message}" timeoutSeconds="10" action="Ignore" >
                 <FilterCountMessageAppendFormat>--------------- The previous message occurred {0} times ---------------</FilterCountMessageAppendFormat>
            </whenRepeated>
         </filters>
    </logger>
```

**Comment by snakefoot** [comment]
Closing question as answered due to inactivity.
