### ISSUE TITLE
NLogConfigurationException : Unrecognized element 'variable(Name=connectionString)' in section 'targets'

### ISSUE THREAD

**Issue by EmmanuelleVilleQC** [NLog/NLog#5066]
Hi!
Since version 5.0.0, I cannot set my connectionstring into LogManager because I have this error 
NLogConfigurationException : Unrecognized element 'variable(Name=connectionString)' in section 'targets'

when executing this line: LogManager.Configuration.Variables["connectionString"] = "My connection string"

Everything was going fine in previous versions 

**NLog version**: (5.0.0)
**Platform**: .Net Framework 48, C# language version 8

Here is my NLog.config file
![image](https://user-images.githubusercontent.com/114103869/191586436-6729e972-0a2b-4f69-b5ed-1c7db0ccb845.png)

**Comment by snakefoot** [comment]
NLog v5 tries to improve the validation of parsing NLog-configuration.

Your NLog.config has the following structure:
```xml
<targets async="true">

     <variable name="connectionString" value="" />

</targets>
````

But `<variable>`-elements cannot be parsed when inside the `<targets>`-section.

Instead consider removing the `<variable>`-element, or move it outside the `<targets>`-section. Ex:

```xml
<variable name="connectionString" value="" />

<targets async="true">

</targets>
````
If you don't like the improved validation of NLog-configuration, then you can just use `throwConfigExceptions="false"`

**Comment by EmmanuelleVilleQC** [comment]
Hi! 
Thanks for your rapid response! It work just fine. Now I just have to include Targets package and everything should be ok.

Thanks again!
