### ISSUE TITLE
NLog optional or empty mail recipient

### ISSUE THREAD

**Issue by tino1986** [NLog/NLog#507]
In my NLog Mail target configuration, the values for the `to` and `cc` parameters are being set dynamically, and sometimes, the value for `cc` will be empty. This results in no mail being sent, even though the `to` parameter contains a valid email address. Furthermore, there are no errors to be found in NLog's internal log file.

An example configuration:

    <variable name="to" value="test@test.com"/>
    <variable name="cc" value=""/>

    <target
        ...
        to="${to}"
        cc="${cc}"

NLog's internal log:

    2015-01-19 14:55 Debug Setting 'MailTarget.name' to 'mail'
    2015-01-19 14:55 Debug Setting 'MailTarget.smtpServer' to 'smtp'
    2015-01-19 14:55 Debug Setting 'MailTarget.to' to 'test@test.com'
    2015-01-19 14:55 Debug Setting 'MailTarget.cc' to ''
    2015-01-19 14:55 Debug Setting 'MailTarget.from' to 'from@test.com'

Note: I'm currently using a workaround, but it feels a bit dirty and I would prefer not to use it in a production environment.

    <variable name="cc" value="a@b"/>

**Comment by 304NotModified** [comment]
This should really be fixed.

**Comment by Xharze** [comment]
I'll look into this and it will be fixed in the next version if possible
