### ISSUE TITLE
How does NLog deal with orphaned log files

### ISSUE THREAD

**Issue by michaeldreams** [NLog/NLog#5071]
Hello,

I am programmer in C# and a new user of `NLog`. I really like the log file auto archive and auto rotation feature! Currently I have a question:

I used `NLog` in my app to log some information and save the log file into local disk, to save space, I enabled auto file archive and file deletion. I am wondering, say, if my app crushed for some reason and then restarted, how would `NLog` deal with the old orphaned log files? Would they still got deleted/rotated?

This is my inline logger config:

```
var fileTarget = new NLog.Targets.FileTarget
            {
                FileName = @"var/output/logs/${date:format=yyyy-MM-dd-HH}.log",
                ArchiveFileName = @"var/output/logs/archived/${date:format=yyyy-MM-dd-HH}.log",
                ArchiveNumbering = NLog.Targets.ArchiveNumberingMode.Sequence,
                ArchiveEvery = NLog.Targets.FileArchivePeriod.Day,
                MaxArchiveDays = 7,
                ArchiveAboveSize = 40960,
                Layout = "${longdate}|${level:uppercase=true}|${logger}|${message}",
                Encoding = Encoding.UTF8,
            };
```

Suggestions appreciated,
Thanks!

**Comment by snakefoot** [comment]
You have correctly identified that NLog does [not support mixing dynamic- and static-archive-logic](https://github.com/NLog/NLog/wiki/File-target#dynamic-vs-static-archive-logic).

You should avoid mixing dynamic `FileName = @"var/output/logs/${date:format=yyyy-MM-dd-HH}.log",` with `ArchiveFileName = "...",`. Also never specify `${date}` / `${shortdate}` / etc. in the `ArchiveFileName = "...",`

Instead you should use dynamic-configuration:
```
var fileTarget = new NLog.Targets.FileTarget
            {
                FileName = @"var/output/logs/app.${date:format=yyyy-MM-dd-HH}.log",
                MaxArchiveDays = 7,
                ArchiveAboveSize = 40960,
                Layout = "${longdate}|${level:uppercase=true}|${logger}|${message}",
                Encoding = Encoding.UTF8,
            };
```

Or static-configuration:
```
var fileTarget = new NLog.Targets.FileTarget
            {
                FileName = @"var/output/logs/app.log",
                ArchiveFileName = @"var/output/logs/archived/app.{#}.log",
                ArchiveNumbering = NLog.Targets.ArchiveNumberingMode.DateAndSequence,
                ArchiveEvery = NLog.Targets.FileArchivePeriod.Day,
                MaxArchiveDays = 7,
                ArchiveAboveSize = 40960,
                Layout = "${longdate}|${level:uppercase=true}|${logger}|${message}",
                Encoding = Encoding.UTF8,
            };
```

**Comment by michaeldreams** [comment]
> You have correctly identified that NLog does [not support mixing dynamic- and static-archive-logic](https://github.com/NLog/NLog/wiki/File-target#dynamic-vs-static-archive-logic).
> 
> You should avoid mixing dynamic `FileName = @"var/output/logs/${date:format=yyyy-MM-dd-HH}.log",` with `ArchiveFileName = "...",`. Also never specify `${date}` / `${shortdate}` / etc. in the `ArchiveFileName = "...",`
> 
> Instead you should use dynamic-configuration:
> 
> ```
> var fileTarget = new NLog.Targets.FileTarget
>             {
>                 FileName = @"var/output/logs/app.${date:format=yyyy-MM-dd-HH}.log",
>                 MaxArchiveDays = 7,
>                 ArchiveAboveSize = 40960,
>                 Layout = "${longdate}|${level:uppercase=true}|${logger}|${message}",
>                 Encoding = Encoding.UTF8,
>             };
> ```
> 
> Or static-configuration:
> 
> ```
> var fileTarget = new NLog.Targets.FileTarget
>             {
>                 FileName = @"var/output/logs/app.log",
>                 ArchiveFileName = @"var/output/logs/archived/app.{#}.log",
>                 ArchiveNumbering = NLog.Targets.ArchiveNumberingMode.DateAndSequence,
>                 ArchiveEvery = NLog.Targets.FileArchivePeriod.Day,
>                 MaxArchiveDays = 7,
>                 ArchiveAboveSize = 40960,
>                 Layout = "${longdate}|${level:uppercase=true}|${logger}|${message}",
>                 Encoding = Encoding.UTF8,
>             };
> ```

Thanks for mentioning that @snakefoot , very informative. However, this seems not answering my question, if my app crushed, would `NLog` clean up the orphaned logs on next app restart?

Thank you

**Comment by snakefoot** [comment]
Yes. If you use the 2 examples that I provided. But not if you use the example that you provided initially.

**Comment by michaeldreams** [comment]
Thanks, @snakefoot , I will change to use the example you provided.

**Comment by snakefoot** [comment]
Closing question as answered.
