### ISSUE TITLE
ASP.NET Core Render Layout in .NET 6 not working

### ISSUE THREAD

**Issue by Shoogn** [NLog/NLog#5072]
I'm using NLog version 5.0.1 with aspnet core app under .NET6 
When I'm trying to log to the Database, I use the Layout that target the aspnet core 6. (https://nlog-project.org/config/?tab=layout-renderers)
The problem is that, any layout-renderers throw exception when I run the application.

**NLog version**: (5.0.4)
**NLog.Extensions.Logging version**: (5.0.4)
**NLog.Web.AspNetCore version**: (5.1.4)
**NLog.Database version**: (5.0.4)
**System.Data.SqlClient version**: (5.8.3)

**Platform**:  .NET6

**Current NLog json**

```json
{
  "NLog": {
    "throwConfigExceptions": true,
    "targets": {
      "async": true,
      "database": {
        "type": "Database",
        "dbProvider": "System.Data.SqlClient",
        "connectionString": "Data Source=.;Initial Catalog=PlatformNet6_Db;Trusted_Connection=True;MultipleActiveResultSets=true",
        "keepConnection": "true",
        "commandText": "insert into dbo.AppLogs (Added_Date,LogLevel,Message,StackTrace,Exception,Logger,RequestUrl,RequestType) values (@addeddate, @level, @message, @stackTrace, @logger, @exception, @requestUrl, @requestType);",
        "parameters": [
          {
            "name": "@addeddate",
            "layout": "${date}"
            //"dbType": "DbType.DateTime"
          },
          {
            "name": "level",
            "layout": "${level}"
          },
          {
            "name": "message",
            "layout": "${message}"
          },
          {
            "name": "stackTrace",
            "layout": "${stacktrace}"
          },
          {
            "name": "logger",
            "layout": "${logger}"
          },
          {
            "name": "exception",
            "layout": "${exception:tostring}"
          }
          //,
          //{
          //  "name": "requestUrl",
          //  "layout": "${aspnet-request-url}"
          //},
          //{
          //  "name": "requestType",
          //  "layout": "${aspnet-request-method}"
          //}
        ]
      },
      "logconsole": {
        "type": "Console"
      }
    },
    "rules": [
      {
        "logger": "*",
        "minLevel": "Info",
        "writeTo": "logconsole"
      },
      {
        "logger": "*",
        "minLevel": "Debug",
        "writeTo": "database"
      }
    ]
  }
}
```

 **InnerException**
  {"Failed to parse layout containing type: aspnet-request-url"} | System.Exception {NLog.NLogConfigurationException}

**Message**
'DatabaseParameterInfo' cannot assign property 'Layout'='${aspnet-request-url}'. Error: Failed to parse layout containing type: aspnet-request-url

**Stacktrace**
-    at NLog.Internal.PropertyHelper.SetPropertyFromString(Object targetObject, PropertyInfo propInfo, String stringValue, ConfigurationItemFactory configurationItemFactory)
   at NLog.Internal.PropertyHelper.SetPropertyFromString(Object targetObject, String propertyName, String stringValue, ConfigurationItemFactory configurationItemFactory)
   at NLog.Config.LoggingConfigurationParser.SetPropertyValueFromString(Object targetObject, String propertyName, String propertyValue, ValidatedConfigurationElement element)
   at NLog.Config.LoggingConfigurationParser.ConfigureObjectFromAttributes(Object targetObject, ValidatedConfigurationElement element, Boolean ignoreType)
   at NLog.Config.LoggingConfigurationParser.ConfigureFromAttributesAndElements(Object targetObject, ValidatedConfigurationElement element, Boolean ignoreTypeProperty)
   at NLog.Config.LoggingConfigurationParser.AddArrayItemFromElement(Object o, PropertyInfo propInfo, ValidatedConfigurationElement element)
   at NLog.Config.LoggingConfigurationParser.SetPropertyValuesFromElement(Object o, ValidatedConfigurationElement childElement, ILoggingConfigurationElement parentElement)
   at NLog.Config.LoggingConfigurationParser.ParseTargetElement(Target target, ValidatedConfigurationElement targetElement, Dictionary`2 typeNameToDefaultTargetParameters)
   at NLog.Config.LoggingConfigurationParser.ParseTargetsElement(ValidatedConfigurationElement targetsElement)
   at NLog.Config.LoggingConfigurationParser.ParseNLogSection(ILoggingConfigurationElement configSection)
   at NLog.Config.LoggingConfigurationParser.LoadConfig(ILoggingConfigurationElement nlogConfig, String basePath)
   at NLog.Extensions.Logging.NLogLoggingConfiguration.LoadConfigurationSection(IConfigurationSection nlogConfig)
   at NLog.Extensions.Logging.SetupBuilderExtensions.LoadConfigurationFromSection(ISetupBuilder setupBuilder, IConfiguration configuration, String configSection)
   at Program.<Main>$(String[] args) in C:\Users\Mohammed\source\repos\PlatformNet6\PlatformNet6\Program.cs:line 23

**Comment by snakefoot** [comment]
The inner-exception probably has the following message:
```
ArgumentException: LayoutRenderer type-alias is unknown: 'aspnet-request-url'. Extension NLog.Web.AspNetCore not included?
```
I suggest that you load the NLog-configuration like this (Automatically registers needed extensions):
```csharp
var logger = LogManager.Setup()
                       .LoadConfigurationFromAppSettings()
                       .GetCurrentClassLogger();
```
Alternative update appsettings.json to include the required `extensions`:
```json
{
  "NLog": {
    "extensions": [
      { "assembly": "NLog.Extensions.Logging" },
      { "assembly": "NLog.Web.AspNetCore" }
    ],
   }
}
```
See also: https://github.com/NLog/NLog.Extensions.Logging/wiki/NLog-configuration-with-appsettings.json

**Comment by Shoogn** [comment]
Thanks now it's working after adding this to my my loggerappsettings.json file
``` json
 "extensions": [
      { "assembly": "NLog.Extensions.Logging" },
      { "assembly": "NLog.Web.AspNetCore" }
    ],
```

But to be clear in the previous version it's working normally without adding the extensions element, I wrote an article explain how to use NLog and I used the version 4.7.14 with aspnet core 6  `https://dev.to/mohammedahmed/store-log-messages-in-sql-server-for-your-aspnet-core-60-by-using-nlog-3dpb`

**Comment by snakefoot** [comment]
Yes NLog v5 has a breaking change where it no longer scans and loads assemblies where filename begins with NLog (I recommend you read the NLog v5 news post)

Besides being slow then the assembly scanning was not always working. When using LoadConfigurationFromAppSettings or UseNLog / AddNLogWeb then these methods will ensure extension registration happens correctly.

I cannot see any of those methods being mentioned in the callstack you initially provided.


Sent from my Galaxy



-------- Original message --------
From: Mohammed Ahmed Hussien ***@***.***>
Date: 28/09/2022 11:00 (GMT+01:00)
To: NLog/NLog ***@***.***>
Cc: Rolf Kristensen ***@***.***>, Comment ***@***.***>
Subject: Re: [NLog/NLog] ASP.NET Core Render Layout in .NET 6 not working (Issue #5072)


Thanks now it's working after adding this to my my loggerappsettings.json file

 "extensions": [
      { "assembly": "NLog.Extensions.Logging" },
      { "assembly": "NLog.Web.AspNetCore" }
    ],

But to be clear in the previous version it's working normally without adding the extensions element, I wrote an article explain how to use NLog and I used the version 4.7.14 with aspnet core 6 https://dev.to/mohammedahmed/store-log-messages-in-sql-server-for-your-aspnet-core-60-by-using-nlog-3dpb

**Comment by snakefoot** [comment]
Btw. tried the example from your article and the `LoadConfigurationFromAppSettings()` works just fine with NLog v5.

Ofcourse one is required to install NLog.Database-nuget-package to make the Database-Target work in NLog v5.

**Comment by Shoogn** [comment]
Yeah, I installed the NLog.Database also.
I load the configuration from another json file named, 'nloggerappsettings.json'
And in my Program.cs I configure the NLog  like so
``` C#
IConfiguration config = new ConfigurationBuilder()
    .SetBasePath(System.IO.Directory.GetCurrentDirectory())
    .AddJsonFile("nloggerappsettings.json", optional: true, reloadOnChange: true)
    .Build();

var logger = LogManager.Setup().LoadConfigurationFromSection(config).GetCurrentClassLogger();

try
{
 var builder = WebApplication.CreateBuilder(args);
    logger.Info("Program is start");
    builder.Configuration.AddJsonFile("nloggerappsettings.json", optional: true, reloadOnChange: true).Build();

 builder.Logging.ClearProviders();
    builder.Logging.AddConsole();
    builder.Host.UseNLog();

// other implementations goes here
}
```

So, the ``` C# LoadConfigurationFromSection( ) ``` method search for element is name NLog by default in the ```.json``` file

**Comment by snakefoot** [comment]
You can consider doing this:

```c#
IConfiguration config = new ConfigurationBuilder()
    .SetBasePath(System.IO.Directory.GetCurrentDirectory())
    .AddJsonFile("nloggerappsettings.json", optional: true, reloadOnChange: true)
    .Build();

var logger = LogManager.Setup()
    .SetupExtensions(e => e.RegisterNLogWeb());   // Loads extensions for NLog v5
    .LoadConfigurationFromSection(config)
    .GetCurrentClassLogger();
```

But yes when using special config-file-location for the nlog-config, then some of the auto-magic disappear.

**Comment by Shoogn** [comment]
Should I need to load NLog.Web-extension from ```program.cs``` even if I load it from the ```nloggerappsettings.json``` file:
```
   "extensions": [
      { "assembly": "NLog.Extensions.Logging" },
      { "assembly": "NLog.Web.AspNetCore" }      // for what I inject this here, For rendering Layout?
    ],
```

And the signature of  ```LoadConfigurationFromSection( )``` method like so:
```
        public static ISetupBuilder LoadConfigurationFromSection(this ISetupBuilder setupBuilder, Microsoft.Extensions.Configuration.IConfiguration configuration, string configSection = "NLog")
        {
            // s.RegisterConfigSettings I think it loads all the assemblies under the extensions element in 
            //nloggerappsettings.json 
            setupBuilder.SetupExtensions(s => s.RegisterConfigSettings(configuration));  
            if (!string.IsNullOrEmpty(configSection))
            {
                var nlogConfig = configuration.GetSection(configSection);
                if (nlogConfig?.GetChildren()?.Any() == true)
                {
                    setupBuilder.LogFactory.Configuration = new NLogLoggingConfiguration(nlogConfig, setupBuilder.LogFactory);
                }
                else
                {
                    Common.InternalLogger.Debug("Skip loading NLogLoggingConfiguration from empty config section: {0}", configSection);
                }
            }
            return setupBuilder;
        }
```
