### ISSUE TITLE
ReplaceNewLinesLayoutRendererWrapper fail if replacement contains new line char

### ISSUE THREAD

**Issue by Orace** [NLog/NLog#5079]
**NLog version**: 5.0.4
**Platform**: all

My goal is to align multi line error message.

For example this:
```
2022-09-30 12:57:49.0158|INFO |EMITTER | MESSAGE LINE 1
MESSAGE LINE 2
```

Became this:
```
2022-09-30 12:57:49.0158|INFO |EMITTER | MESSAGE LINE 1
                                       | MESSAGE LINE 2
```

The [replace-newlines](https://github.com/NLog/NLog/wiki/Replace-NewLines-Layout-Renderer) renderer is a good candidate.

I tried:
```xml
<variable name="pretty" value="${replace-newlines:replacement=\r\n                                       | :${layout}}" />
```

- What is the current result?

The replacement method is called twice, hence, inserted newlines are re-replaced.
https://github.com/NLog/NLog/blob/6f246d36ee4b796bed15061d8cae9deb4fdc8f86/src/NLog/LayoutRenderers/Wrappers/ReplaceNewLinesLayoutRendererWrapper.cs#L68-L70

The actual result is:
```
2022-09-30 12:57:49.0158|INFO |EMITTER | MESSAGE LINE 1

                                       |                                        | MESSAGE LINE 2
```

- What is the expected result?

The replacement method should be called once (at least with the replacement string).

- A workaround is to replace Windows new lines to Unix new lines, then replace all new lines by the replacement string:

```C#
string str = builder.ToString(orgLength, builder.Length - orgLength)
                    .Replace(WindowsNewLine, UnixNewLine)
                    .Replace(UnixNewLine, Replacement);
```

**Comment by snakefoot** [comment]
NLog 5.0.5 now released - https://www.nuget.org/packages/NLog/5.0.5#release-body-tab
