### ISSUE TITLE
EventLogTarget.Source should be of type `Layout`, not `string` - and therefore will be layout-able

### ISSUE THREAD

**Issue by Gitgiddy** [NLog/NLog#508]
I have a windows service which is installed from the same assembly path as multiple instances (differentiated only by service account and service name).  I use the FileTarget log and archive paths with `${windows-identity}` successfully but `EventLogTarget.Source` member does not get expanded in the same way and so the source's Layout string shows up literally, assuming the user account has rights to create new Event Sources in Windows.

(Haters note: I'm not particularly happy with the choice of installing the same service multiple times, but that wasn't up to me.  But as I must stick to that, installing the service multiple times from the same binary is certainly preferable to having to create different builds for each one!)

**Comment by 304NotModified** [comment]
To be clear: you would like to use *layout renderers* inside the `EventLogTarget.Source` property?

Ps:
You can set the source from the api as work around.

**Comment by Gitgiddy** [comment]
Yes, I would like to use layout renderers inside the EventLogTarget.Source property.

I am currently setting the source using the API, but because I'm using the NLogTraceListener instead of any explicit NLog calls, I don't think that `ReconfigureExistingLoggers()` works (? the docs for that method doesn't imply that it should work and I don't think it does here, not 100% confident on that though) and so I have to add the new NLogTraceListener programmatically after changing the EventSource - relatively drastic.

**Comment by 304NotModified** [comment]
I don't fully understand your 2nd paragraph. But I think I should work as described at this article: 
https://github.com/NLog/NLog/wiki/Configuration-API

**Comment by Gitgiddy** [comment]
Yes, it works if the whole configuration is done programmatically but I can't seem to use the API to merely update the source name (and then call `ReconfigureExistingLoggers()`) and expect the .config-file-configuration-specified NLogTraceListener's output source to be corrected.

**Comment by 304NotModified** [comment]
Looked at this. It seems to have low impact. Because of compatibility change it is planned for the new main release.

**Comment by 304NotModified** [comment]
@Xharze is a an way to detect that the `Layout` is just a string in the config? (so no `Layout Renderers` used?)

**Comment by 304NotModified** [comment]
Maybe fixing it with an extra property (`SourceLayout` or `SourceIsLayout (bool)) - otherwise the install tries to create the unmerged layout as Source. (e.g.` ${source}`)

**Comment by ilya-g** [comment]
@304NotModified 
> is a an way to detect that the Layout is just a string in the config? (so no Layout Renderers used?)

`SimpleLayout` (the layout with LayoutRendereres) contains internal field `fixedText`. When this field is not null, it means that this layout doesn't contain any volatile renderers.
You can expose the value of `fixedText == null` as a property, say `IsFixed` or `IsConstant`, and use `fixedText` value when that property is true.
Then you can limit `IInstallable` implementation to install eventlog only if the source is fixed.

**Comment by 304NotModified** [comment]
@ilya-g thanks! :+1: :+1: :+1: 

So to summarize, I propose:

- `Source` property will be `Layout`
- The install/uninstall will only create/remote an eventsource if and only if the source is a fixed text (no layout renderers used)

**Comment by Gitgiddy** [comment]
Why can't the installer unroll this?  The installer is the only runtime session that is expected to have the Admin rights to add the event source.

**Comment by 304NotModified** [comment]
@Gitgiddy because we don;t have the `LogEventInfo` object at the install method -  this is needed with the `Layout.Render`.

I don't know _when_  `install` is run, so maybe this structural problem can be solved.

**Comment by 304NotModified** [comment]
@ilya-g 
Any idea what `isInstalled` should return in case of a Layout renderer used?

code, see TODO
```
    public bool? IsInstalled(InstallationContext installationContext)
        {
            var fixedSource = GetFixedSource();

            if (!string.IsNullOrEmpty(fixedSource))
            {
                return EventLog.SourceExists(fixedSource, this.MachineName);
            }
            return false; //TODO unclear! 
        }
```

**Comment by ilya-g** [comment]
According to `IsInstalled` return value specification it is the "value indicating whether the item is installed or null if it is not possible to determine."
So in case if one have used layoutrenderers in source property, we are unable to determine what the source is, then the best return value would be `null`

**Comment by 304NotModified** [comment]
Thanks @ilya-g
