### ISSUE TITLE
Logger does not log any exception details

### ISSUE THREAD

**Issue by HackworthCForge** [NLog/NLog#5081]
**NLog version**: 5.0.4

**Platform**: .NET6

**Current NLog config**             
            string targetName = "logconsole";
            logger = LogManager.GetLogger(targetName);
            var _logLayout = "${message} | ${exception:format=tostring} #";
            var _config = new NLog.Config.LoggingConfiguration();
            var _logConsole = new NLog.Targets.ConsoleTarget(targetName) { Layout = _logLayout };
            _config.AddRule(LogLevel.Info, LogLevel.Fatal, _logConsole);
            NLog.LogManager.Configuration = _config;
- What is the current result? 
     Console output "123 | #"
- What is the expected result? 
     Console output with "123" and also exception details from exception.ToString or any other format
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)? 
    Yes, internal logging works, nothing relevant displayed on test
- Please post full exception details (message, stacktrace, inner exceptions)
    No exception
- Are there any workarounds? yes/no
    no
- Is there a version in which it did work? 
  unknown
- Can you help us by writing an unit test?

            //Cause exception
            try
            {
                string s = null;
                bool b = s.Contains('a');
            }
            catch (Exception exc)
            {
                //Console output: "123 | #"
                logger.Error("123", exc);
                Console.ReadLine();
            }

**Comment by snakefoot** [comment]
See also: https://stackoverflow.com/questions/74055684/nlog-5-0-4-does-not-log-exceptions

Notice [breaking change in NLog v5](https://nlog-project.org/2021/08/25/nlog-5-0-preview1-ready.html) where obsolete logging-methods have been removed, so now defaulting to `Logger.Error<T>(string message, T argument)`.
