### ISSUE TITLE
Nlog.Targets.DatabaseTarget does not exist anymore ?

### ISSUE THREAD

**Issue by wanao-pd** [NLog/NLog#5082]
**NLog version**: 5.0.4

**Platform**:  .NET6

![image](https://user-images.githubusercontent.com/70882699/196139077-cd2c101b-fdc8-4615-8dc0-5ac49233297e.png)

Hello !
I am trying to use configuration through code. I used MailTarget and FileTarget which works very well but I have à problem with DatabaseTarget.
Nlog.Targets.DatabaseTarget does not exist anymore ? I found several examples using it but I can't seem to use it ! 

Thanks !

**Comment by snakefoot** [comment]
Closing question as answered due to inactivity.
