### ISSUE TITLE
SetupInternalLogger does not take into account "${basedir}"

### ISSUE THREAD

**Issue by RyanGaudion** [NLog/NLog#5083]
**NLog version**: 5.1.4

**Platform**: .NET6

**Current NLog config** (xml or C#, if relevant)

```xml
.SetupInternalLogger(intern =>
{
    intern.LogToFile("${basedir}/logs/nlog-internalNLogs.txt").SetMinimumLogLevel(LogLevel.Info);
})
```

This does not log to a log file. However, if I change the path to "C:/logs/nlog-internalNLogs.txt" then it does log.

How can I use the `${basedir}` variable inside the "LogToFile" method.

Non-programmatically, it works like this:
```
<nlog ...
      internalLogFile="${basedir}/logs/nlog-internalNLogs.txt"
      internalLogLevel="Info" >
```

**Comment by snakefoot** [comment]
I'm guessing the idea is that when assigning the value directly, then it was not necessary to use "magic" tokens.

But I agree that it would give better consistency, that the magic from the NLog-config-parser was moved into the actual property.

**Comment by RyanGaudion** [comment]
@snakefoot agreed.

It seems to work on FileTargets but not internal logger.

Having them all consistent would be great.

**Comment by snakefoot** [comment]
There is a huge difference between NLog Layout used in FileTarget-FileName and the NLog InternalLogger. 

Because the NLog InternalLogger is extremely primitive, to ensure that it always works, since it is the troubleshooter-tool.

**Comment by RyanGaudion** [comment]
@snakefoot I presume this would use `ExpandFilePathVariables` from `LoggingConfigurationParser.cs`. If so, would it make sense for this to be run in the `LogToFile` extension method in `SetupInternalLoggerBuilderExtensions`?

**Comment by snakefoot** [comment]
Was thinking the logic should be moved into the InternalLogger class for the Logfile-property-setter.



Sent from my Galaxy



-------- Original message --------
From: Ryan Gaudion ***@***.***>
Date: 24/10/2022 13:22 (GMT+01:00)
To: NLog/NLog ***@***.***>
Cc: Rolf Kristensen ***@***.***>, Mention ***@***.***>
Subject: Re: [NLog/NLog] SetupInternalLogger does not take into account "${basedir}" (Issue #5083)


@snakefoot<https://github.com/snakefoot> I presume this would use ExpandFilePathVariables from LoggingConfigurationParser.cs. If so, would it make sense for this to be run in the LogToFile extension method in SetupInternalLoggerBuilderExtensions?

**Comment by snakefoot** [comment]
NLog 5.0.5 now released - https://www.nuget.org/packages/NLog/5.0.5#release-body-tab
