### ISSUE TITLE
Introduce event handler LogEventDropped for NetworkTarget

### ISSUE THREAD

**Issue by POnakS** [NLog/NLog#5084]
I'm using NetworkTarget, and there is no way to have handle backpressure in logger. There is `NetworkTargetQueueOverflowAction` - `Grow` and `Block` will break your applications, so only reasonable selection is `Discard`.

While using `Discard` there is no way to have a notification that my application is discarding logs. I see that I'm dropping lots of log entries on production, but I cannot setup monitoring for that. Only hack I've found out is this:
```
InternalLogger.LogLevel = LogLevel.Debug;
InternalLogger.LogMessageReceived += (sender, eventArgs) =>
{
  if (eventArgs.Message == "NetworkQueue - Discarding single item, because queue is full")
  {
    // Log dropped
  }
};
```
but this solution is flimsy (depends on log message), and need debug logs configured in InternalLogger.

**NLog version**: 5.0.0

**Platform**: .NET Core / AllPlatforms

**Current NLog config** (xml or C#, if relevant)
Not revelant

 - Why do we need it?

Having such notification is very useful, because then I could send a metric to my statsd collector, setup alerts and notifications when my apps are dropping logs.
In current setup I can only compare logs to traffic levels 

 - An example of the XML config, if relevant.

There are no options in config for changing this, so probably not revelant.

**Comment by snakefoot** [comment]
You are wellcome to create a pull-request, that introduces the following event-handler to NetworkTarget (Just like for AsyncTargetWrapper):

```c#
public event EventHandler<LogEventDroppedEventArgs> LogEventDropped
```

**Comment by POnakS** [comment]
@snakefoot I've prepared the MR #5101

**Comment by snakefoot** [comment]
@POnakS NLog v5.1.0 has been released where NetworkTarget now has LogEventDropped-eventhandler.

Thank you again @ShadowDancer for making the pull-request #5101
