### ISSUE TITLE
Mark SonarQube Security Issue as Safe

### ISSUE THREAD

**Issue by snakefoot** [NLog/NLog#5088]
This "security issue" should be marked as "safe":

https://sonarcloud.io/project/security_hotspots?id=nlog2&branch=dev&hotspots=AYP2NUvbZinl2h1ztXSZ

**Comment by 304NotModified** [comment]
Fixed. You are also owner of the sonarqube projects. (Login with your github account)

**Comment by snakefoot** [comment]
Excellent. Thank you for the help.
