### ISSUE TITLE
${callsite} shows up as empty string after using .NET Reactor

### ISSUE THREAD

**Issue by jyrka98** [NLog/NLog#509]
I tried to use ${callsite} in my app's config. It works before protecting the app with .NET reactor, but not after. I haven't looked at the NLog source code much, so i don't know how you're obtaining this value, but CallerFilePathAttribute works. https://msdn.microsoft.com/en-us/library/hh534540.aspx

**Comment by Xharze** [comment]
This probably has something to do with the obfuscation perform. I'll keep this issue open, so it can be checked

**Comment by 304NotModified** [comment]
@jyrka98 can you give examples of what expected and you've get after .Net reactor? Do you get an exception, empty string or wrong value?

The code for ${callsite} is here:https://github.com/NLog/NLog/blob/master/src/NLog/LayoutRenderers/CallSiteLayoutRenderer.cs

**Comment by jyrka98** [comment]
@304NotModified it shows up as a empty string in the log file.
here's how it looks like before and after using .NET Reactor:
2015-01-21 01:26:27.5773 | INFO | (Program.cs:56) -> Checking if another instance of the application is already running.
2015-01-21 01:26:27.6753 | INFO | (Program.cs:58) -> Starting application.
2015-01-21 01:26:30.2015 | INFO | (MainWindow.xaml.cs:138) -> Successfully enabled shutdown privilege.
2015-01-21 01:27:14.7550 | INFO | (Program.cs:63) -> Exiting application.
2015-01-21 01:30:56.1547 | INFO |  -> Checking if another instance of the application is already running.
2015-01-21 01:30:56.2127 | INFO |  -> Starting application.
2015-01-21 01:30:58.2948 | INFO |  -> Successfully enabled shutdown privilege.
2015-01-21 01:31:50.2448 | INFO |  -> Exiting application.

 I don't use a .config file, i configure it in code:

´´´
        private static readonly Logger Logger;

        static Program() {
            var config = new LoggingConfiguration();
            var fileTarget = new FileTarget();
            var rule = new LoggingRule("*", LogLevel.Info, fileTarget);
            config.AddTarget("file", fileTarget);
            config.LoggingRules.Add(rule);
            fileTarget.FileName = "C:/ProgramData/Jyrka98/<APPNAME>/Logs/<APPNAME>.log";
            fileTarget.Layout = "${longdate:universalTime=true} | ${uppercase:${level}} | ${callsite:className=false:fileName=false:includeSourcePath=false:methodName=false} -> ${message}";
            fileTarget.KeepFileOpen = true;
            fileTarget.Encoding = Encoding.UTF8;
            LogManager.Configuration = config;
            Logger = LogManager.GetLogger("Program");
        }
´´´

**Comment by 304NotModified** [comment]
It seems that .net reactor [also obfuscated the stacktrace]. (http://www.eziriz.com/help/source/deobfuscator.html) This stacktrace is used in the callsite renderer.

Don't know if it's possible to work around this. It's a feature of .net reactor.

**Comment by 304NotModified** [comment]
Note the caller attributes are compile time added and therefore that will works. Reading the stacktrace is runtime and this is obfuscated by  .Net reactor. 

Adding the caller attributes is possible but a lot of methods have to be changed. Not sure if we should do that as this case is a bit uncommon and the obfuscation is intentional.  If it boosts performance, I'm in. @Xharze your opinion please on this.

**Comment by Xharze** [comment]
This will take a lot of work to be done, and I think we should check the
performance impact and the impact on the API itself. But if it works and
doesn't pollute the API I think it's a good idea. But it requires a proof
of concept first.

**Comment by 304NotModified** [comment]
OK, I will create a new issue for this. That would be more clear IMO.
