### ISSUE TITLE
How to setup nlog.config when we use Azure db?

### ISSUE THREAD

**Issue by bcqfwbs** [NLog/NLog#5106]
Hi team,
Recently I tried to add NLog for my .net core program, but I got a question that argumentException: Target type-alias is unknown: “Database". 
My sqlserver is on Azure, 
Here is the config code. 
**NLog version**: (5.0.5)

**Platform**:  .NET Core 3.1

**Current NLog config** (xml)

```xml
<targets>
			<target name= "db" xsi:type="Database"
				connectionString="${gdc:connectionStringNLog}">
				<commandText>
					INSERT dbo.NLogInfo([Date],[Level], [Message], [Detail]) VALUES(GETDATE(),@level,@message,@detail);
				</commandText>
				<parameter name="@level" layout=" ${level}" />
				<parameter name="@message" layout="${message}"/>
				<parameter name="@detail" layout="${detail}" />
			</target>
		</targets>

```
I had to try to add System.Data.Sqlclient, but seems not working. Could you please give me some advise?

**Comment by bcqfwbs** [comment]
![image](https://user-images.githubusercontent.com/37373330/202988132-b8ba6d47-3a6f-4f52-82ee-00575ac42756.png)

**Comment by snakefoot** [comment]
Yes NLog v5 have move NLog DatabaseTarget into its own [NLog.Database](https://www.nuget.org/packages/NLog.Database)-nuget-package.

Make sure to add [NLog.Database](https://www.nuget.org/packages/NLog.Database)-nuget-package to your project.

**Comment by bcqfwbs** [comment]
> Yes [NLog v5](https://nlog-project.org/2021/08/25/nlog-5-0-preview1-ready.html) have moved NLog DatabaseTarget into its own [NLog.Database](https://www.nuget.org/packages/NLog.Database)-nuget-package.
> 
> Make sure to add [NLog.Database](https://www.nuget.org/packages/NLog.Database)-nuget-package to your project.

Yes, I still use old solution: System.Data.SqlClient,  it's working fine when I add [NLog.Database] package to my project. 
very appreciate for your reply.
