### ISSUE TITLE
Routing System.Diagnostics.Trace and System.Diagnostics.TraceSource logs through NLog

### ISSUE THREAD

**Issue by AidanMcD** [NLog/NLog#5107]
Hi

sry if this is not the correct layout my first bug

see https://nlog-project.org/2010/09/02/routing-system-diagnostics-trace-and-system-diagnostics-tracesource-logs-through-nlog.html

**NLog version**: 5.0.5

**Platform**: Windows .NET Core 3.1

**Current NLog config** (xml or C#, if relevant)

```xml
<configuration>
	<nlog>
		<targets>
			<target name="console" type="ColoredConsole" layout="${longdate}|${windows-identity}|${event-properties:item=EventId_Id:whenEmpty=0}|${level:uppercase=true}|${logger}|${message} ${exception:format=tostring}" />
			<target name="file" type="File" fileName="D:/Logs/log.txt" layout="${longdate}|${windows-identity}|${event-properties:item=EventId_Id:whenEmpty=0}|${level:uppercase=true}|${logger}|${message} ${exception:format=tostring}" />
		</targets>
		<rules>
			<logger name="*" minlevel="Trace" writeTo="console,file" />
		</rules>
	</nlog>
</configuration>

```
```
static void Main(string[] args)
        {
            Trace.Listeners.Clear();
            Trace.Listeners.Add(new NLogTraceListener());
         
                 
            NLog.Common.InternalLogger.LogLevel = NLog.LogLevel.Trace;
            NLog.Common.InternalLogger.LogToConsole = true;
            NLog.Common.InternalLogger.LogFile = @"C:\temp\nlog-internal.txt";

// This logs ok
          Trace.Write("Hello World");

// Should the exception thrown by below log




            Trace.Write("Hello World");

            var webClient = new WebClient();
            webClient.DownloadString("http://somehost/nosuchfile.txt");
        

}
```

- What is the current result?
Exception thrown by webClient is not logged 

- What is the expected result?
Exception thrown by webClient be logged 

[nlog-internal.txt](https://github.com/NLog/NLog/files/10086633/nlog-internal.txt)
logs are attached

- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
- Please post full exception details (message, stacktrace, inner exceptions)
- 
- Are there any workarounds? yes/no
- no
- Is there a version in which it did work?
- ????
- see  https://nlog-project.org/2010/09/02/routing-system-diagnostics-trace-and-system-diagnostics-tracesource-logs-through-nlog.htm
- Can you help us by writing an unit test?

**Comment by snakefoot** [comment]
If `Trace.Write("Hello World")` gives the expected output, then I think NLog NLogTraceListener is working.

NLog is not responsible for whatever happens inside `WebClient`.

**Comment by AidanMcD** [comment]
Is the tutorial  out of date ?
https://nlog-project.org/2010/09/02/routing-system-diagnostics-trace-and-system-diagnostics-tracesource-logs-through-nlog.html

**Comment by snakefoot** [comment]
> Is the tutorial out of date ?

NLog `NLogTraceListener` works just fine with `System.Diagnostics.Trace`, but pretty sure .NET Core doesn't route any logging through `System.Diagnostics.Trace` .

The tutorial is 12 years old, and original made for .NET Framework where `System.Diagnostics.Trace` was the default Microsoft-Logging-Framework.

Microsoft introduced Microsoft.Extensions.Logging with .NET Core, where [NLog ](https://github.com/NLog/NLog.Extensions.Logging) also exists.

**Comment by AidanMcD** [comment]
I'm working on a test framework and want the users of the framework to enable a more verbose logging 
May be some thing like 
```

  if(diagnosticMode) 
  {
      change the layouts of all targets
  } 

```

**Comment by snakefoot** [comment]
Sounds a lot like LogLevel-filtering, where you enable Trace/Debug for verbose logging:

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/logging

**Comment by AidanMcD** [comment]
NLog LoggingRule has ability to dynamically enable/disable logger-output is perfect 
Thanks for your help on this
