### ISSUE TITLE
Derive from ConfigurationSection (replace IConfigurationSectionHandler )

### ISSUE THREAD

**Issue by werker** [NLog/NLog#511]
> IConfigurationSectionHandler is deprecated in .NET Framework 2.0 and above. But, because it is used internally, it has been kept.
> ...
> In .NET Framework version 2.0 and above, you must instead derive from the ConfigurationSection class to implement the related configuration section handler.

From: https://msdn.microsoft.com/de-de/library/system.configuration.iconfigurationsectionhandler(v=vs.110).aspx

**Comment by 304NotModified** [comment]
English version ;)
https://msdn.microsoft.com/en-us//library/system.configuration.iconfigurationsectionhandler(v=vs.110).aspx

**Comment by 304NotModified** [comment]
Maybe related http://raph.es/blog/2011/05/manually-caching-configuration-sections-to-avoid-the-.net-4-bug/

**Comment by 304NotModified** [comment]
fixed by https://github.com/NLog/NLog/pull/3355
