### ISSUE TITLE
Consider adding Zstandard and CLP compression

### ISSUE THREAD

**Issue by Cjewett** [NLog/NLog#5123]
Recently came across this [blog post ](https://www.uber.com/blog/reducing-logging-cost-by-two-orders-of-magnitude-using-clp/) by Uber and wanted to start a discussion. I noticed that there is compression for GZip and zip archive files. Has there been any consideration to add Zstandard or CLP to NLog?

**Comment by snakefoot** [comment]
Think it is possible to plugin whatever compression algorithm that you would like on the FileTarget by implementing a the [IFileCompressor](https://nlog-project.org/documentation/v5.0.0/html/T_NLog_Targets_IFileCompressor.htm)-interface, and assigning [FileTarget.FileCompressor](https://nlog-project.org/documentation/v5.0.0/html/P_NLog_Targets_FileTarget_FileCompressor.htm)-property.

**Comment by snakefoot** [comment]
Closing issue as answered due to inactivity.
