### ISSUE TITLE
How to Use NlogViewer in Nlog 5.0 with Fluent Configuration API , Better with MVVM pattern

### ISSUE THREAD

**Issue by dongfengxin** [NLog/NLog#5132]
As NLog Update to Nlog 5.0, How to use  Fluent Configuration API to binding NlogViewer ?

like this way:

```c#
NLog.LogManager.Setup().LoadConfiguration(builder => {
   builder.ForLogger().FilterMinLevel(LogLevel.Info).WriteToConsole();
   builder.ForLogger().FilterMinLevel(LogLevel.Debug).WriteToFile(fileName: "file.txt");
});
```

**Comment by snakefoot** [comment]
You can create a NLog target-instance, and assign the wanted [properties](https://nlog-project.org/documentation/v5.0.0/html/T_NLog_Targets_NLogViewerTarget.htm):

```c#
NLog.LogManager.Setup().LoadConfiguration(builder => {
   builder.ForLogger().FilterMinLevel(LogLevel.Debug).WriteToTarget(new NLogViewerTarget { Address = "udp://localhost:4000" });
});
```

Notice that [NLogViewerTarget](https://github.com/NLog/NLog/wiki/NLogViewer-target) uses a non-standard Log4J XML output, and it is recommended to instead use [ChainsawTarget](https://github.com/NLog/NLog/wiki/Chainsaw-target)

See also: https://github.com/NLog/NLog/wiki/Fluent-Configuration-API

**Comment by dongfengxin** [comment]
Thank you, and how to bing NlogViewer in wpf userControl ? 

    <Grid>
        <nlog:NlogViewer x:Name="logCtrl" TimeWidth="AUTO" LoggerNameWidth="0" LevelWidth="auto" ExceptionWidth="auto" MessageWidth="auto" ScrollViewer.VerticalScrollBarVisibility="Auto" />
    </Grid>

**Comment by snakefoot** [comment]
No idea. It is not part of this NLog-repo

Maybe try Stackoverflow or look at existing  examples.


Sent from my Galaxy



-------- Original message --------
From: dongfengxin ***@***.***>
Date: 22/12/2022 10:22 (GMT+01:00)
To: NLog/NLog ***@***.***>
Cc: Rolf Kristensen ***@***.***>, Comment ***@***.***>
Subject: Re: [NLog/NLog] How to Use NlogViewer in Nlog 5.0 with Fluent Configuration API , Better with MVVM pattern (Issue #5132)


Thank you, and how to bing NlogViewer in wpf userControl ?

<Grid>
    <nlog:NlogViewer x:Name="logCtrl" TimeWidth="AUTO" LoggerNameWidth="0" LevelWidth="auto" ExceptionWidth="auto" MessageWidth="auto" ScrollViewer.VerticalScrollBarVisibility="Auto" />
</Grid>

**Comment by snakefoot** [comment]
Sorry about the confusion. Now I understand you are looking for advice with the [NlogViewer](https://github.com/erizet/NlogViewer) WPF-Control.

The [NLogViewer](https://www.nuget.org/packages/NlogViewer/)-nuget-package comes with its own target, which you can setup like this:
```c#
NLog.LogManager.Setup().LoadConfiguration(builder => {
   builder.ForLogger().FilterMinLevel(LogLevel.Debug).WriteTo(new NlogViewer.NlogViewerTarget());
});
```

But I don't know anything about now to integrate the `nlog:NlogViewer`-control. Think StackOverflow or self-study will be the best approach.

**Comment by snakefoot** [comment]
@dongfengxin Maybe https://github.com/dojo90/NLogViewer is a better alternative ?

**Comment by snakefoot** [comment]
Closing question, since not for this NLog-repo. Probably better to try StackOverflow.com or self-study.
