### ISSUE TITLE
Porting from SimpleLogger to NLog

### ISSUE THREAD

**Issue by ajtruckle** [NLog/NLog#5133]
Hi

I am new to NLog and I am trying to port over from SimpleLogger.

I can port over most of the code but I can't see the equivalents for these API calls:

* ShowLogFile (this displays the current log file to the user).
* SetLogFile (this lets us pass a string to indicate the location for the log file if we want to)
* GetFilename (this returns the location/filename of the error log file being used).

Does Nlog already support these features, and if so, how? Otherwise, can a feature request be made for them?

I would ask on SO but these are 3 API items and that would warrant 3 separate questions.

Thank you.

**Comment by snakefoot** [comment]
SImpleLogger can output to a single file, but NLog can output to mulitple files / console / eventlog / database / email / etc.

I cannot guess how you are planning to use NLog, but lets say you want to configure from code:

```c#
var logDirectory = Directory.GetCurrentDirectory();

var logger = NLog.LogManager.Setup().LoadConfiguration(builder => {
      builder.ForLogger().FilterMinLevel(LogLevel.Debug).WriteToFile(fileName: System.IO.Path.Combine(logDirectory, "App_${shortdate}.txt"));;
}).GetCurrentClassLogger();
```

- SetLogFile - Is configured by assigning the NLog FileTarget FileName-option. The FileName is NLog Layout that can use any number of NLog LayoutRenderers (Ex. `${shortdate}`)
- GetFilename - You can scan the active NLog.LogManager.Configuration for NLog FileTarget and return the FileName-option (Ex. `fileTarget.FileName.Render(NLog.LogEventInfo.CreateNullEvent())` to render the NLog Layout)
- ShowLogFile - NLog does not have the ability to copy/read/show the output logfile-content But it should be a simple matter of copying the code.

See also: https://github.com/NLog/NLog/wiki/Fluent-Configuration-API

See also: https://github.com/NLog/NLog/wiki/Tutorial

**Comment by ajtruckle** [comment]
Thanks for this information. I have managed to put this together in a test console application:

```
using NLog;

namespace TestConsoleNlog
{
    internal class Program
    {
        static void Main(string[] args)
        {
            Logger logger = null;
            string logDirectory = "d:\\My Debug";
            SetLogPath(ref logger, logDirectory, "TestApp");

            if(logger != null)
            {
                logger.Info("This is a note");

                var fileTarget = NLog.LogManager.Configuration.FindTargetByName("targetFile");
            }
        }

        static void SetLogPath(ref Logger logger, string logPath, string appName)
        {
            logger = NLog.LogManager.Setup().LoadConfiguration(builder =>
            {
                builder.ForLogger().FilterMinLevel(LogLevel.Debug).WriteToFile(fileName: System.IO.Path.Combine(logPath, appName + "_${shortdate}.txt")); ;
            }).GetCurrentClassLogger();

        }
    }
}
```

I could not work out how to have the `m_logger` as a global variable to be used by all the other functions. In my real application I will have other functions that need to log. Am I going about that wrong? The tutorial suggested:

`private static readonly NLog.Logger Logger = NLog.LogManager.GetCurrentClassLogger();`

But then I don't know how to subsequently set the path to that particular logger?

But, I do confirm that I can pass in a folder and using your example specify the log file name. As a result I don't need a `GetFilename` function, as I have specified what it is myself at runtime. And, as you say, I just need to get my main application to take the log file and display it.

That said, I did try to follow your second suggestion for `GetFilename` but I couldn't work out how you got the `fileTarget` object.

**Comment by snakefoot** [comment]
NLog LogManager is wrapper around a singleton LogFactory. From a single LogFactory one can create many Logger-objects, where all of them are controlled by the same LogFactory and its configuration.

The idea is to assign the NLog configuration at application startup, and then all Logger-objects (existing or new) will automatically use that configuration.

When having a "large" application with many classes, since it is common to have this line in every class. The `GetCurrentClassLogger` is special as it generates a Logger-named after each class-type-name.

```c#
class MyClass
{
    private readonly NLog.Logger Logger = NLog.LogManger.GetCurrentClassLogger(); // Logger with name "MyClass"
}
```

Again all this can be read from the[ NLog tutorial](https://github.com/NLog/NLog/wiki/Tutorial).

**Comment by snakefoot** [comment]
Again NLog can output to mulitple files / console / eventlog / database / email / etc. so NLog Targets are generic in NLog.

But after having assigned NLog configuration, then it is possible to probe the configuration if you want:
```c#
var fileTarget = NLog.LogManager.Configuration?.AllTargets.OfType<NLog.Targets.FileTarget>().FirstOrDefault();
if (fileTarget != null)
{
      var fileName = fileTarget.FileName.Render(NLog.LogEventInfo.CreateNullEvent())
}
```

**Comment by ajtruckle** [comment]
Sorry if I overlooked the obvious! Based on the various snippets I have been able to put the important bits together:

```
using NLog;
using System;
using System.Linq;

namespace TestConsoleNlog
{
    internal class Program
    {
        private static readonly NLog.Logger Logger = NLog.LogManager.GetCurrentClassLogger();

        static void Main(string[] args)
        {
            string logDirectory = "d:\\My Debug";
            SetLogPath(logDirectory, "TestApp");

            if(Logger != null)
            {
                Console.WriteLine(GetLogPath());
                Logger.Info("This is a note");
                try
                {
                    Logger.Info("Hello world");
                    System.Console.ReadKey();
                }
                catch (Exception ex)
                {
                    Logger.Error(ex, "Goodbye cruel world");
                }
            }
        }

        static void SetLogPath(string logPath, string appName)
        {
            var logger = NLog.LogManager.Setup().LoadConfiguration(builder =>
            {
                builder.ForLogger().FilterMinLevel(LogLevel.Debug).WriteToFile(fileName: System.IO.Path.Combine(logPath, appName + "_${shortdate}.txt")); ;
            }).GetCurrentClassLogger();
        }

        static string GetLogPath()
        {
            var fileTarget = NLog.LogManager.Configuration?.AllTargets.OfType<NLog.Targets.FileTarget>().FirstOrDefault();
            if (fileTarget != null)
            {
                var fileName = fileTarget.FileName.Render(NLog.LogEventInfo.CreateNullEvent());
                return fileName;
            }
            return null;
        }
    }
}
```

**Comment by snakefoot** [comment]
Your example-code looks good. Notice that `if(Logger != null)` is not needed, as `NLog.LogManager.GetCurrentClassLogger()` and `NLog.LogManager.GetLogger("MyLogger")`  will always return a Logger-instance.

I guess the `ShowLogFile` can be implemented like this:
```
        static void ShowLogFile()
        {
            var fileName = GetLogPath();
            if (string.IsNullOrEmpty(fileName))
                  return;

            if (!File.Exists(fileName))
                  return; 

            // Let system choose application to start
            Process.Start(fileName);

            // Wait a little to give application time to open
            Thread.Sleep(2000);
        }
```

**Comment by ajtruckle** [comment]
Thanks. The code works well. I think from the perspective of writing to the simple layout then we have all the bases covered. So I will close this ticket. Thank you.
