### ISSUE TITLE
ArchiveOldFileOnStartup and FileArchivePeriod

### ISSUE THREAD

**Issue by contento** [NLog/NLog#514]
Are ArchiveOldFileOnStartup and FileArchivePeriod linked to each other? Is this only to make sure we archive, for example, something on Monday when the application did not run for the weekend?

I am looking for a ArchiveFileOnStartup which would archive the file regardless of the rules. It would be useful mostly for testing/developing purposes. 

BTW. I already mentioned something like this before https://github.com/NLog/NLog/issues/420#issuecomment-55521176

**Comment by 304NotModified** [comment]
This is a old question, but nonetheless, no there are not linked. `ArchiveOldFileOnStartup ` always works the same, independent of FileArchivePeriod  and visa versa.

**Comment by 304NotModified** [comment]
Answered and closing.
