### ISSUE TITLE
示例项目有错误

### ISSUE THREAD

**Issue by chbacheng** [NLog/NLog#5142]
请检查一下示例项目，示例项目有错误，我用的是“ASP.NET Core 6 NLog Example”这个示例项目。

**Comment by snakefoot** [comment]
My chineese is a little rusty, so I used Google Translate:

> **The example project has errors**
> Please check the example project, there is an error in the example project, I am using the example project "ASP.NET Core 6 NLog Example".

Thank you for reporting the issue. Can you show us, where the [ASP.NET Core 6 NLog Example Project](https://github.com/NLog/NLog.Web/tree/master/examples/ASP.NET%20Core%206/ASP.NET%20Core%206%20NLog%20Example-project) fails?

**Comment by chbacheng** [comment]
> 我的中文有点生疏，所以我用了谷歌翻译：
> 
> > 示例项目有错误请检查示例项目，示例项目中存在**错误**，我正在使用此示例项目“ASP.NET Core 6 NLog 示例”。
> 
> 感谢您报告此问题。你能告诉我们，[ASP.NET Core 6 NLog示例项目](https://github.com/NLog/NLog.Web/tree/master/examples/ASP.NET%20Core%206/ASP.NET%20Core%206%20NLog%20Example)在哪里失败了吗？

rzc rewritecss exited with code 1.	ASP.NET Core 6 NLog Example	C:\Program Files\dotnet\sdk\7.0.102\Sdks\Microsoft.NET.Sdk.Razor\targets\Microsoft.NET.Sdk.Razor.ScopedCss.targets	170

**Comment by snakefoot** [comment]
Sounds like an external issue, where something is wrong with the build-environment (Maybe conflict between .NET6 and .NET7 SDK)
