### ISSUE TITLE
The Format-option is not working for the LongDate Layout Renderer

### ISSUE THREAD

**Issue by Nanopixel** [NLog/NLog#5145]
My layout in target:
`layout="${longdate:universalTime=true:format=yyyy-MM-ddTHH\:mm\:ss.fffZ} ${level} ${message} ${machinename}"`
Output in Log:
2023-01-31 16:16:31.9660 Info [...] _rest censored ;-)_
So the T and the Z is missing.
When changing the format string by deleting seconds and milliseconds for example "format=yyyy-MM-ddTHH\:mmZ" the output in the log is the same.
The format is obviously ignored - whats going wrong?

**Comment by snakefoot** [comment]
[${longdate}](https://github.com/NLog/NLog/wiki/LongDate-Layout-Renderer) only provides a fixed date-format (`yyyy-MM-dd HH:mm:ss.ffff`), that is optimized for reduced string-allocation.

Maybe [${date}](https://github.com/NLog/NLog/wiki/Date-Layout-Renderer) is the one you are looking for ?

It is a good idea to check the [NLog InternalLogger](https://github.com/NLog/NLog/wiki/Internal-Logging) when NLog is not working as expected. It is also recommended to enable `throwConfigExceptions="true"` to catch NLog-configuration issues, but it works best with NLog v5.

**Comment by Nanopixel** [comment]
You are right, by using _date_ instead of _longdate_ it works as expected. Thanks!
And you are also right, I could have found the problem myself if I checked the InternalLogger... sorry
