### ISSUE TITLE
Nlog 5 dosen't work with Graylog

### ISSUE THREAD

**Issue by Narutofox** [NLog/NLog#5147]
Good day
I used NLog 4 to log information to Graylog and also write it in a file in file system and it worked great.
However with Nlog 5 the logged information only gets written on file system but not on Graylog.
Can you please look into it.
Thank you

**Comment by snakefoot** [comment]
Have you tried to use [NLog.GelfLayout](https://www.nuget.org/packages/NLog.GelfLayout) like this (Supports TCP / UDP / HTTP):
```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" throwConfigExceptions="true">
  <extensions>
    <add assembly="NLog.Layouts.GelfLayout" />
  </extensions>
  
  <targets async="true">
	<target xsi:type="Network" name="GelfHttp" address="http://localhost:12201/gelf">
		<layout type="GelfLayout">
			<field name="threadid" layout="${threadid}" />
		</layout>
	</target>
  </targets>

  <rules>
    <logger name="*" minlevel="Debug" writeTo="GelfHttp" />
  </rules>
</nlog>
```
See more examples here:  https://github.com/farzadpanahi/NLog.GelfLayout#sample-usage-with-nlog-network-target-and-http

**Comment by Narutofox** [comment]
Good day
Using [NLog InternalLogger](https://github.com/NLog/NLog/wiki/Internal-Logging) I found the problem.
It was in configuration related to breaking changes made in NLog 5 compare to NLog 4 [LoggingRule Filters DefaultAction changed to FilterResult.Ignore](https://nlog-project.org/2021/08/25/nlog-5-0-preview1-ready.html#loggingrule-filters-defaultaction-changed-to-filterresultignore)
Thank you for help
