### ISSUE TITLE
NLog is not transforming from nlog.release.config at publish .net 6 core

### ISSUE THREAD

**Issue by ttaylor29** [NLog/NLog#5160]
Hello, 

I have my nlog.release.config setup to change when we publish in VS 2022 .net 6 app that is blazor.

The nlog.config is the debug version after the publish is completed.

What could be the issue?

Files attached.

[nlog.config_debug.txt](https://github.com/NLog/NLog/files/10778161/nlog.config_debug.txt)
[nlog.config_release.txt](https://github.com/NLog/NLog/files/10778162/nlog.config_release.txt)

**Comment by snakefoot** [comment]
Think you will find more help at StackOverflow.com It doesn't seem like an issue about NLog, but about how to publish application configuration-files

See also: https://github.com/NLog/NLog/wiki/Environment-specific-NLog-Logging-Configuration (Alternative ways of doing environment specific configuration for NLog)

**Comment by ttaylor29** [comment]
Hello,

Thank you for the suggestion.

I was able to add my NLog config into my appsettings.json file and then update the Asp.net Blazor application "_Host.cshtml" file with the proper environment that I was deployed to:

`<environment include="Staging,Release">
    <component render-mode="ServerPrerendered" type="typeof(App)" />
</environment>
<environment include="Development">
    <component render-mode="Server" type="typeof(App)" />
</environment>
`

Nlog worked as expected after that!
