### ISSUE TITLE
Mail target - send to recipient mail server - add message-id header [Feature reqeust] 

### ISSUE THREAD

**Issue by mnemanov** [NLog/NLog#5161]
Hi! Thanks for reporting this feature!

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

**NLog version**: 4.7.9

**Platform**: .Net 4.5

Currently to send email using a gmail account, we must include the username and password in the config file.

If we are only sending to a gmail user (or other account using google workspace) we could avoid putting the credentials in the config by sending the email directly to the google incoming mx server aspmx.l.google.com, the only problem currently is that nlog does not generate a message-id header and google rejects the email (unless coming from a trusted ip).

If there was an option to indicate that we are sending to the destination server instead of a mta and have nlog generate a message-id it would allow us to deploy nlog without exposing gmail credentials.

**Comment by snakefoot** [comment]
NLog [Mail-Target](https://github.com/NLog/NLog/wiki/Mail-target) and [MailKit](https://www.nuget.org/packages/NLog.MailKit)-Target both supports Username and Password as [NLog Layout](https://github.com/NLog/NLog/wiki/Layouts).

NLog Layout allows you to retrieve value from any location you like with help from [NLog LayoutRenderers](https://nlog-project.org/config/?tab=layout-renderers).

**Comment by snakefoot** [comment]
But you are ofcourse wellcome to create a pull-request to add the MessageId-Header-support:

See also: https://stackoverflow.com/questions/6874964/why-emails-sent-by-net-smtpclient-are-missing-message-id

**Comment by mnemanov** [comment]
Yes I am aware of that option.

But nevertheless it would be more convenient if I didn't have to deal with credentials at all.

**Comment by snakefoot** [comment]
NLog v5.1.3 has been released - https://www.nuget.org/packages/NLog#release-body-tab where you can do this:
```xml
<target xsi:type="Mail" name="MailTarget" />
     <mailHeader name="Hello" layout="World" />
</target>
```

**Comment by mnemanov** [comment]
Thank you very much.

**Comment by mnemanov** [comment]
Ok, I'm sure this is a very dumb question, but what is the correct way to add this in nlog config?

I'm getting an error: 'MailTarget' cannot assign property 'MailHeaders', because property of type array and not scalar value

**Comment by snakefoot** [comment]
Have you tried using "mailheader" (without "s")?  As shown in the example?

Else please post your NLog.config then I will take a look later.

**Comment by mnemanov** [comment]
I figured it out thank you.
