### ISSUE TITLE
Excessive memory usage growth and increated GC time when using padding formatter

### ISSUE THREAD

**Issue by ikkentim** [NLog/NLog#5164]
**NLog version**: 5.1.2

**Platform**: .Net Framework 4.8

**Current NLog config** (xml or C#, if relevant)

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

   <variable name="fileformat" value="${longdate} ${pad:padding=5:inner=${level:uppercase=true}} t=${pad:padding=5:inner=${threadid}}, m=${message}" />

    <targets>
        <target xsi:type="ColoredConsole" name="colouredConsole" layout="${fileformat}">
        </target>
    </targets>

    <rules>
        <logger name="*" minlevel="Trace" writeTo="colouredConsole" />
    </rules>
</nlog>

```

Due to a problem in .NET Framework, the StringBuilder will allocate excessive memory when repeatedly using `.Insert` and `.Clear` on a `StringBuilder`.

The problem can be reproduced using the following code:

```cs
internal class Program
{
    private static readonly NLog.Logger Logger = NLog.LogManager.GetCurrentClassLogger();

    public static void Main()
    {
        while (true)
        {
            Logger.Info("This is a sample log message");
        }
    }
}
```

![image](https://user-images.githubusercontent.com/2820647/221231607-5a271f9d-9982-4bd8-a9dd-4f4959ef97a6.png)

![image](https://user-images.githubusercontent.com/2820647/221231975-dde65b59-dfe3-4526-b9ed-8dd03441ae21.png)

In our production environment, the process ended up using over 80% of its CPU time in GC.

Please note the problem has already been fixed in .NET Core in this PR https://github.com/dotnet/coreclr/pull/16926 . The problem is however still present in .NET Framework.

It would be nice if the StringBuilderPool could be disabled on .NET Framework.

The following code code reproduces the underlying issue in .NET Framework:

``` cs
var sb = new StringBuilder(16);
while (true)
{
    sb.Append("abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz");

    for (var i = 0; i < 4; i++)
        sb.Insert(1+i, ' ');
    
    Console.WriteLine(sb.Capacity + " " + sb.ToString());

    sb.Clear();
    
}
```

I know, ideally, this should be fixed in .NET Framework, but it might take a long time for Microsoft to fix this issue, and for all clients to have received the update.

For the moment, I have disabled padding in my NLog configuration as a workaround.

EDIT: I've also created this post on the .NET Developer community: https://developercommunity.visualstudio.com/t/NET-Framework:-StringBuilder-unbounded/10291174

**Comment by snakefoot** [comment]
Thank you for reporting this issue. The unwanted behavior was introduced here #4672

Will try and make a fix for NLog padding logic, so it will not use StringBuilder.Insert

**Comment by ikkentim** [comment]
Thank you @snakefoot ! 👍

**Comment by ikkentim** [comment]
I see this has been fixed in #5165 , I'll close this issue

**Comment by snakefoot** [comment]
NLog v5.1.3 has been released - https://www.nuget.org/packages/NLog#release-body-tab

**Comment by ikkentim** [comment]
Thanks for the heads up!
