### ISSUE TITLE
I would like to replace the last line of file log, for making a progress bar behave in the file

### ISSUE THREAD

**Issue by AntonioGomes42** [NLog/NLog#5170]
Good afternoon, everyone! I would like to create a kind of progress bar bahiviour on my logging file. I have one worker that process more than 1 million rows of data, and now it's diplaying each one in the log. I would like to know how to just replace the last or to have that feature that makes possible that beaheve of progress bar because the log file is getting to long because of that.

**Comment by snakefoot** [comment]
NLog FileTarget doesn't have support for re-writing the same line, and it not easy to make it append to existing line.

I suggest that the application writes a progress-status-line every 10 secs, and then a final status-line on completetion with timings + file-size + record-count + etc.

**Comment by snakefoot** [comment]
Closing issue as resolved, due to inactivity
