### ISSUE TITLE
whenRepeated FilterCountPropertyName is not being populated with a value

### ISSUE THREAD

**Issue by bilago** [NLog/NLog#5173]
NLog nuget v 5.1.2

My Logger rule:

```xml
<logger name="*" minlevel="Debug" maxLevel="Error" writeTo="cons,asyncConsole,asyncOracle,asyncDebugFile" >
      <filters defaultAction="Log">        
        <whenRepeated layout="${event-properties:item=id}${event-properties:item=detail_error}${exception:innerFormat=Message}${event-properties:item=state_object}" 
                      timeoutSeconds="2" action="Ignore" MaxFilterCacheSize="500" 
                      FilterCountPropertyName="filtered" FilterCountMessageAppendFormat=" (Hits: {0})"/>
      </filters>
</logger> 
```

Target using "filtered" (this is a test target, because I'm using asyncwrapper on my real console target, but I removed that to make sure it wasn't an async issue:

```xml
    <target name="cons" xsi:type="ColoredConsole"
            layout="[${level:uppercase=true:padding=-5}] ${date:format=HH\:mm\:ss}: ${event-properties:item=id:uppercase=true:padding=-12}|${callsite:methodName=true:includeNamespace=false:className=false}|${event-properties:item=detail_error}${event-properties:item=filtered}|${exception:format=ToString}">
    </target>
```
I've also tried using and do not get the number of filtered counts

```
layout="${mdlc:item=filtered}"
layout="${event-context:item=filtered}"
```
I've even tried layout=${all-event-properties}  which outputs every property I set, just doesnt show a key value pair for filtered.

My C# code to test this functionality:

```
_log.Debug("Hello Debug");
_log.Debug("Hello Debug");
_log.Debug("Hello Debug");
_log.Debug("Hello Debug");
_log.Debug("Hello Debug");
_log.Debug("Hello Debug");
Thread.Sleep(10000);
_log.Debug("Hello Debug");
```

The current nlog config correctly skips the duplicate log messages, the console output correctly shows:

```
[DEBUG] 13:58:44: |<Main>$|Hello Debug|
[DEBUG] 14:08:44: |<Main>$|Hello Debug|
```

but I'm expecting the log to look like:

```
[DEBUG] 13:58:44: |<Main>$|Hello Debug|
[DEBUG] 14:08:44: |<Main>$|Hello Debug (Hits: 4)|
```

**Comment by bilago** [comment]
I just went through the NLog source code and apparently the format string gets appended to the message. I tried using that in my target as a test:

    <target name="cons" xsi:type="ColoredConsole"
            layout="${message}">
    </target>
    
    and the console output is:
    
    
Hello Debug
Hello Debug

so it's not being appended to the message either.

**Comment by snakefoot** [comment]
If you can reproduce the issue in an unit-test, with the following logging-rule, then it would be great (Notice I have simplified the filter-layout, since I think that is your issue):
```xml
<logger name="*" minlevel="Debug" maxLevel="Error" writeTo="cons,asyncConsole,asyncOracle,asyncDebugFile" >
      <filters defaultAction="Log">        
            <whenRepeated layout="${message}"
                  timeoutSeconds="2" action="Ignore" MaxFilterCacheSize="500" 
                  FilterCountPropertyName="filtered" FilterCountMessageAppendFormat=" (Hits: {0})"
      </filters>
</logger> 

```

**Comment by snakefoot** [comment]
Closing issue as resolved, due to inactivity.
