### ISSUE TITLE
LogManager.Configuration.Variables not available in 3.2.0 

### ISSUE THREAD

**Issue by rubenwe** [NLog/NLog#518]
Hey.

I was very happy when I read about this feature in the 3.2.0 announcement. But it seems it is not available in the package. (nuget)

Could someone update the packages if it is indeed available in the code base?

Thanks

**Comment by Xharze** [comment]
I'll look into why it isn't available in the package and release a new if necessary.

**Comment by 304NotModified** [comment]
@Xharze I have looked at this in short. It seems a news post 'bug'?

**Comment by 304NotModified** [comment]
@Xharze The 'Variables' are added to `XmlLoggingConfiguration` but the `Logmanager.Config` is of the type `LoggingConfiguration`.

**Comment by Xharze** [comment]
Ahh, it should of course be added on LogManager too. This should be fixed,
I'll create a new release package based on 3.2 containing this fix.

**Comment by 304NotModified** [comment]
@Xharze I added a new milestone for this so it's clear we will patch this bug In 3.2. 

Feel free to change it if you had other plans.

**Comment by Xharze** [comment]
Sounds good. It should be fixed.

**Comment by 304NotModified** [comment]
PR merged. DOne
