### ISSUE TITLE
FinalMinLevel documentation

### ISSUE THREAD

**Issue by Aaronmsv** [NLog/NLog#5184]
I thought it would be useful to have a page fully describing how FinalMinLevel works. It would have helped me before, so I wrote one: https://github.com/Aaronmsv/NLog/wiki/FinalMinLevel Do you think it would be good to include it in the NLog wiki?

Since NLog's documentation is in Wikis I can't make a PR for this.

Edit: I haven't tested the examples yet.

**Comment by stil** [comment]
I was actually looking today for a documentation of finalMinLevel.
It's still quite confusing to me. Consider this rules sequence:

```xml
        <logger name="Microsoft.EntityFramework*" finalMinLevel="Warn" writeTo="console" />
        <logger name="Microsoft*" finalMinLevel="Info" writeTo="console" />
```

I'd expect it to have the following behavior:
- Log `Microsoft.EntityFrameworkCore.Database.Command` if `Warn` or more severe, ignore if `Info` or less severe
- Log `Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor` if `Info` or more severe, ignore if `Debug` or less severe

But it actually logs `Microsoft.EntityFrameworkCore.Database.Command` logs even in `Info` severity.
What am I missing?

**Comment by snakefoot** [comment]
@Aaronmsv Yes right now one can only find this as docs:

- https://nlog-project.org/2021/08/25/nlog-5-0-preview1-ready.html#nlogextensionslogging-without-any-filter

And the currenct config-api docs, only mentions that `finalMinLevel` exists:

- https://github.com/NLog/NLog/wiki/Configuration-file#rules

I like the idea with some breakout-page that explains with more examples. Same could be useful for `minLevel` + `maxLevel` + `final` + `logger`-name-pattern.

The docs page looks great. I only found one place, that needs to be fixed:

> It can be simplified with FinalMinLevel and the order wouldn't matter between the first two:
>
>     <logger name="Microsoft.*" finalMinLevel="Warn" />
>     <logger name="Microsoft.Hosting.Lifetime*" finalMinLevel="Info" />

The order of NLog logging-rules are very important. And `finalMinLevel` will override any previous rules, and the following will cause `Microsoft.Hosting.Lifetime`-loggers to have `finalMinLevel="Warn"`
```xml
    <logger name="Microsoft.Hosting.Lifetime*" finalMinLevel="Info" />
    <logger name="Microsoft.*" finalMinLevel="Warn" /> <!-- Changes minLevel for all loggers matching including the above  -->

**Comment by Aaronmsv** [comment]
> The docs page looks great. I only found one place, that needs to be fixed:
> 
> > 
> >     It can be simplified with FinalMinLevel and the order wouldn't matter between the first two:
> > 
> >     <logger name="Microsoft.*" finalMinLevel="Warn" />
> >     <logger name="Microsoft.Hosting.Lifetime*" finalMinLevel="Info" />
> 
> The order of NLog logging-rules are very important. And finalMinLevel will override any previous rules, and the following will cause Microsoft.Hosting.Lifetime-loggers to have finalMinLevel="Warn"

Fixed and also added a few more details.

**Comment by snakefoot** [comment]
> Fixed and also added a few more details.

Looks great. Notice NLog Wiki is open for editing - https://github.com/NLog/NLog/wiki/_new 

You are wellcome to create a new page with title "Logging Rules FinalMinLevel"

**Comment by snakefoot** [comment]
Thank you very much for creating

https://github.com/NLog/NLog/wiki/Logging-Rules-FinalMinLevel


Sent from my Galaxy



-------- Original message --------
From: Aaron Mousavi ***@***.***>
Date: 31/03/2023 14:15 (GMT+02:00)
To: NLog/NLog ***@***.***>
Cc: Rolf Kristensen ***@***.***>, Comment ***@***.***>
Subject: Re: [NLog/NLog] FinalMinLevel documentation (Issue #5184)


Done!

**Comment by snakefoot** [comment]
Have updated [NLog Config Tutorial](https://github.com/NLog/NLog/wiki/Configuration-file#rules) with link to the new wiki-page.

Thank you again.
