### ISSUE TITLE
FileTarget - new property autoConcurrentWrites="Boolean"

### ISSUE THREAD

**Issue by MarekPokorny** [NLog/NLog#5192]
**NLog version**: (5.x.x.x)

**Future possible NLog.config fragment:**
```xml
<nlog>
  <targets>
    <target xsi:type="File" autoConcurrentWrites="true">
    </target>
  </targets>
</nlog>
```
When setting new property **autoConcurrentWrites** = **"true"** it:
- sets **ConcurrentWrites** = **"false"** and **performance of logging is much better**
- it monitors exceptions in _FileTarget_
- when it detects exception **that other proccess is trying to write to same file** then it sets **ConcurrentWrites = true**

Sometimes we do not know how to set **ConcurrentWrites**. Using this new property **autoConcurrentWrites** it sets **ConcurrentWrites = true** only when needed.

**Comment by snakefoot** [comment]
Sounds like an exciting idea for a new FileTarget-nuget-package. But not planning any more features of the existing NLog FileTarget.

If you are missing the ability to easily override behavior of the existing NLog FileTarget, then pull-requests are always wellcome.

**Comment by MarekPokorny** [comment]
**Thank you very much** for all your answers and your help!

**Comment by snakefoot** [comment]
Closing issue as resolved, due to inactivity

**Comment by snakefoot** [comment]
NLog v6-preview1 has been released, that includes AtomicFileTarget, that supports ConcurrentWrites without using global-mutex:

- https://www.nuget.org/packages/NLog.Targets.AtomicFile

See also: https://nlog-project.org/2025/04/29/nlog-6-0-major-changes.html
