### ISSUE TITLE
How to switch to appsettings.json via UseNlog?

### ISSUE THREAD

**Issue by davidblagojevic** [NLog/NLog#5194]
https://stackoverflow.com/questions/74016396/how-to-overwrite-nlog-config-when-using-nlogaspnetcoreoptions

**Comment by snakefoot** [comment]
Maybe this tutorial can help - https://github.com/NLog/NLog/wiki/Getting-started-with-ASP.NET-Core-6

Along with this guide for using appsettings.json for nlog-config - https://github.com/NLog/NLog.Extensions.Logging/wiki/NLog-configuration-with-appsettings.json

**Comment by snakefoot** [comment]
Closing issue as resolved, due to inactivity.
