### ISSUE TITLE
Release NLog v6 without trim warnings and post-pone core-package to NLog v7 ?

### ISSUE THREAD

**Issue by snakefoot** [NLog/NLog#5198]
Preparing pull-request that will obsolete the following parts with NLog v5.3:

- `ConfigurationItemFactory`
   - `ConfigurationItemFactory(params Assembly[] assemblies)`-constructor
   - `INamedItemFactory<Target, Type> Targets`-property
   - `INamedItemFactory<Filter, Type> Filters`-property
   - `public INamedItemFactory<LayoutRenderer, Type> LayoutRenderers`-property
   - `public INamedItemFactory<Layout, Type> Layouts`-property
   - `public INamedItemFactory<LayoutRenderer, Type> AmbientProperties`-property
   - `public INamedItemFactory<TimeSource, Type> TimeSources`-property
   - `INamedItemFactory<MethodInfo, MethodInfo> ConditionMethods`-property
   - `RegisterItemsFromAssembly(Assembly assembly)`-method
   - `RegisterItemsFromAssembly(Assembly assembly, string itemNamePrefix)`-method
   - `PreloadAssembly(Type[] typesToScan)`-method
   - `RegisterType(Type type, string itemNamePrefix)`-method
- `interface INamedItemFactory<TInstanceType, TDefinitionType>`
- `SimpleConfigurator`
   - `ConfigureForConsoleLogging()`-method
   - `ConfigureForTargetLogging()`-method
   - `ConfigureForFileLogging()`-method
- `LogFactory` / `LogManager`
   - `Logger GetLogger(string name, Type loggerType)`-method
   - `virtual void OnConfigurationReloaded(LoggingConfigurationReloadedEventArgs e)`-method
   - `event EventHandler<LoggingConfigurationReloadedEventArgs> ConfigurationReloaded`
   - `IEnumerable<string> GetCandidateConfigFilePaths()`-method
   - `void SetCandidateConfigFilePaths(IEnumerable<string> filePaths)`-method
   - `ResetCandidateConfigFilePath()`-method
   - `LogFactory LoadConfiguration(string configFile)`-method
- `LoggingConfiguration`
   - `virtual IEnumerable<string> FileNamesToWatch`-property
- `Target`
   - `public static void Register<T>(string name)`-method
   - `public static void Register(string name, Type targetType)`-method
- `Layout`
   - `public static void Register<T>(string name)`-method
   - `public static void Register(string name, Type layoutType)`-method
- `Layout`
   - `public static void Register<T>(string name)`-method
   - `public static void Register(string name, Type layoutRendererType)`-method
- `NLog.Web.NLogBuilder`
   - `public static LogFactory ConfigureNLog(string configFileName)`
   - `public static LogFactory ConfigureNLog(LoggingConfiguration configuration)`
- `NLog.Web.AspNetExtensions`
   - `public static ILoggingBuilder AddNLog(this ILoggingBuilder builder, ...)`

Instead LogManager.Setup()-extension-methods. should be used to register NLog-extensions, and load NLog-config from file.

The goal is to make the NLog-package the very minimum for creating a Logger / Target / Layout and very little else. This means extracting the folowing out of the core NLog-core:
- Type-reflection-Logic
- File-acces-logic like the loading NLog-config from file
- All targets except maybe a basic target for writing to Stream
- All non-basic layoutrenderers.

Have been testing with AOT- / Trimming and it seems without too many modifications, then NLog will support trimming out of the box (but will require some breaking changes). The question is whether
- Should NLog v6 should become NLog that supports trimming without warnings (looks reachable now, and requires few breaking changes) ?
- Post-pone the core-NLog-package to NLog v7 (requires lots of preparations and lots of breaking changes) ?

What are your thoughts ? Have other ideas / suggestions ?

**Comment by topsterde** [comment]
I think it is generally good when unnecessary methods are marked as Obsolete and removed in the future. This way, less maintenance has to be done in the future.
Both trimming and splitting are very useful. No matter in which order it is done, I would find it great if there were preview versions of V6/V7 to give feedback like in NLog V5.

**Comment by snakefoot** [comment]
It is not because the code is not needed, but because the existing reflection logic is not compatible with triming. So it needs a rewrite, where the old api becomes obsolete. Using NLog v5.2 for guiding people to new api, and remove old api with NLog v6



Sent from my Galaxy




-------- Original message --------
From: topsterde ***@***.***>
Date: 03/05/2023 05:54 (GMT+01:00)
To: NLog/NLog ***@***.***>
Cc: Rolf Kristensen ***@***.***>, Author ***@***.***>
Subject: Re: [NLog/NLog] Release NLog v6 with support for trimming, and post-pone core-package to NLog v7 ? (Issue #5198)

-------- Original message --------
From: topsterde ***@***.***>
Date: 03/05/2023 05:54 (GMT+01:00)
To: NLog/NLog ***@***.***>
Cc: Rolf Kristensen ***@***.***>, Author ***@***.***>
Subject: Re: [NLog/NLog] Release NLog v6 with support for trimming, and post-pone core-package to NLog v7 ? (Issue #5198)


I think it is generally good when unnecessary methods are marked as Obsolete and removed in the future. This way, less maintenance has to be done in the future.
Both trimming and splitting are very useful. No matter in which order it is done, I would find it great if there were preview versions of V6/V7 to give feedback like in NLog V5.

**Comment by snakefoot** [comment]
Looks like this is a non-issue, since NLog v5 can be modified to include trimming annotations, and just obsolete the old assembly-loading logic (with triming-warning suppressions).

NLog v5.2 will obsolete a lot of stuff, but will add the same time add new api-methods with triming annotations. Will have to author a news-blog-post about the changes.

**Comment by snakefoot** [comment]
Created draft for news-post about NLog v5.2:

https://github.com/snakefoot/NLog.github.io/blob/master/_posts/2023-05-16-nlog-5-2-trim-warnings.md

**Comment by snakefoot** [comment]
NLog v5.2 becomes the hybrid that supports old and new style, but defaults to new style (without assembly reflection). See also #5191
