### ISSUE TITLE
Document NLog time stamp / time source on Wiki

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#520]
Document NLog time stamp / time source on the Wiki. Discussed at #512 

Based on the following information: 

> Robert Važan, the author of this feature, has covered this topic in three articles in his blog:
> 
>  - [NLog timestamps with millisecond accuracy](http://blog.angeloflogic.com/2013/10/nlog-timestamps-with-millisecond.html)
>  - [How to configure NLog time source](http://blog.angeloflogic.com/2013/10/how-to-configure-nlog-time-source.html)
>  - [How to write custom NLog time source](http://blog.angeloflogic.com/2013/10/how-to-write-custom-nlog-time-source.html)

**Comment by kevindaub** [comment]
I've documented these changes here.  I didn't want to just add them directly to the wiki, but I can.
The changes are in this commit: kevindaub/NLog-wiki@30083d802103cdcb5087be82ed5e3629c7b92a2e

**Comment by 304NotModified** [comment]
Great!

I cannot see a preview, can't I?

**Comment by kevindaub** [comment]
If you select View on the right of each file, but here's a link to each file:
* [Home.md](https://github.com/kevindaub/NLog-wiki/blob/30083d802103cdcb5087be82ed5e3629c7b92a2e/Home.md)
* [TimeSource.md](https://github.com/kevindaub/NLog-wiki/blob/30083d802103cdcb5087be82ed5e3629c7b92a2e/TimeSource.md)
* [_Sidebar.md](https://github.com/kevindaub/NLog-wiki/blob/30083d802103cdcb5087be82ed5e3629c7b92a2e/_Sidebar.md)

**Comment by 304NotModified** [comment]
Thanks, yes I missed the view button.

Can you use syntax highlighting? (https://help.github.com/articles/github-flavored-markdown/#syntax-highlighting) - xml and c# are available

**Comment by kevindaub** [comment]
Added Syntax Highlighting:
* [Home.md](https://github.com/kevindaub/NLog-wiki/blob/master/Home.md)
* [TimeSource.md](https://github.com/kevindaub/NLog-wiki/blob/master/TimeSource.md)
* [_Sidebar.md](https://github.com/kevindaub/NLog-wiki/blob/master/_Sidebar.md)

**Comment by 304NotModified** [comment]
Looks good! I can be online! :) :+1:

**Comment by kevindaub** [comment]
Done.

**Comment by 304NotModified** [comment]
Great!!

**Comment by 304NotModified** [comment]
This is done and so we close the ticket :)
