### ISSUE TITLE
Add variables element to NLog.xsd schema

### ISSUE THREAD

**Issue by michaelplavnik** [NLog/NLog#5201]
<variables></variables> parsing is supported in NLog5, but NLog.xsd schema does not support it.

Suggested changes:

1. Add
```xml
<xs:element name="variables" type="NLogVariables" />
```

2. Add near NLogVariable
```xml
  <xs:complexType name="NLogVariables">
    <xs:sequence minOccurs="0" maxOccurs="unbounded">
      <xs:element name="variable" type="NLogVariable" />
    </xs:sequence>
  </xs:complexType>
```

**Comment by snakefoot** [comment]
You are very wellcome to make a pull-request to improve `TemplateXSD.xml`:

https://github.com/NLog/NLog/blob/dev/tools/MakeNLogXSD/TemplateXSD.xml

**Comment by michaelplavnik** [comment]
https://github.com/NLog/NLog/pull/5205 is ready.

**Comment by snakefoot** [comment]
NLog.Schema v5.1.4 has been released - https://www.nuget.org/packages/NLog.Schema/5.1.4
