### ISSUE TITLE
Make LoggingConfigurationParser.ParseRulesElement overridable

### ISSUE THREAD

**Issue by michaelplavnik** [NLog/NLog#5202]
**NLog version**: (e.g. 5.1.3)

**Platform**: All

 - Why do we need it?
 
I would like to implement some extension for NLog configuration by sub-classing XmlLoggingConfiguration.
I am able to do it for all elements except for rules section.
Such extension include environment specific sections and variable substitution on target names.
Without treating all sections uniformly I am not able to achieve it.

**Comment by snakefoot** [comment]
See also: https://github.com/NLog/NLog/wiki/Environment-specific-NLog-Logging-Configuration

Along with include-files: https://github.com/nlog/nlog/wiki/XML-config-include-example

**Comment by michaelplavnik** [comment]
Approach you describe is coming from configuration extensions. It can be compared with approach taken by Spring Boot with yaml files, where you can define profile based configuration in the same file. There is a whole class of use cases where such approach is beneficial.

For example, modular system. Well designed logging will have little difference in configuration between different deployment environments. For a system with 50 modules, approach described above will result in 200 logging configuration files with an average 2-3 lines of meaningful information. At that scale 50 and 200 becomes meaningful differentiator. Another, advantage of single file approach is that environments matching rules can include aliases of the form: any-lower, any-prod without starting to refactor/delete/create multiple files.

Include files are orthogonal to this request, and generally will not be a good solution for an open system.

**Comment by snakefoot** [comment]
Still curious about what you want to do in the rules? Notice that Logging-Rule-LogLevels has support for NLog Layout:

https://github.com/NLog/NLog/wiki/Filtering-log-messages#semi-dynamic-routing-rules

This makes it easier to override Logging-Rule-LogLevel-Filtering at runtime.

**Comment by michaelplavnik** [comment]
Semi-dynamic rules was an excellent addition. Consider, it was not implemented, and someone wants to implement it for his own project. What options does one have? 

To make the argument obvious, targets cannot include variables. So I solved it with implementing my own Group target that can reference other targets. Why? To create abstraction over target names for different configurations. 

One can override parsing of all sections, except for rules and include (possible with copy & paste of some code only). 
**So real question is, why such asymmetry?**

**Comment by snakefoot** [comment]
> So real question is, why such asymmetry?

I guess in a special world then all methods should be `protected virtual`, but I prefer windows over doors. I  only opened what was absolutely necessary to split `XmlLoggingConfiguration.cs` into `LoggingConfigurationParser.cs` so it could be used for loading NLog.config from appsettings.json.

Notice NLog-Config-Variables are constantly expanded when parsing config-values, and there also exists [SplitGroupTarget](https://github.com/nlog/nlog/wiki/SplitGroup-target)

**Comment by michaelplavnik** [comment]
I agree with you about windows and doors... Though, the asymmetry will make me pause. The list in above reply is long, but in reality all Parse methods are dispatched from `protected virtual bool ParseNLogSection(ILoggingConfigurationElement)`, except for `ParseExtensionsElement` and `ParseRulesElement`. That is the reason for calling it asymmetry.

Back to Why. What to do if desirable extension is not candidate for general NLog feature for whatever reason?

In regards with SplitGroupTarget. I did not find a way to do below with it

```
	<targets> 
		<target xsi:type="Group" name="mainTargets" writeTo="kegOrFileFallback"/>
		<target xsi:type="Group" name="allTargets" writeTo="kegOrFileFallback,email"/>
	</targets>
```

**Comment by snakefoot** [comment]
Created  #5210

**Comment by snakefoot** [comment]
> In regards with SplitGroupTarget. I did not find a way to do below with it

I believe you can do this using `target-ref`:

```xml
<targets>  
   <target name='email' xsi:type='mail' />
   <target name='kegOrFileFallback' xsi:type='file' />

   <target name="mainTargets" xsi:type="SplitGroup">
        <target-ref name="kegOrFileFallback" />
    </target >

   <target name="allTargets" xsi:type="SplitGroup">
        <target-ref name="kegOrFileFallback" />
        <target-ref name="mail" />
   </target>
</targets>
```

**Comment by snakefoot** [comment]
Closing as NLog v5.1.5 has been released that support use of NLog-Config-Variables for the `writeTo="..."`.

**Comment by michaelplavnik** [comment]
Thank you for handling this issue! Did not have time to express my appreciation earlier.
