### ISSUE TITLE
No file output after deleting log files

### ISSUE THREAD

**Issue by topsterde** [NLog/NLog#5203]
During the runtime of the program log files are deleted so that only new entries are logged. The deletion is done by the user via Windows Explorer.

**NLog version**: 5.1.3

**Platform**: .NET 6

**Current NLog config** (xml or C#, if relevant)

```cs
var configuration = new NLog.Config.LoggingConfiguration();
var logfile = new NLog.Targets.FileTarget("logfile") { FileName = "logfile.txt", };
configuration.AddRule(NLog.LogLevel.Trace, NLog.LogLevel.Fatal, logfile);
NLog.LogManager.Configuration = configuration;

NLog.Common.InternalLogger.LogToConsole = true;
NLog.Common.InternalLogger.LogLevel = NLog.LogLevel.Debug;

var logger = NLog.LogManager.GetCurrentClassLogger();

logger.Warn("A");
await Task.Delay(100);
logger.Warn("B");
await Task.Delay(100);

// Simulate the deletion of log files
File.Delete("logfile.txt");

logger.Warn("C");
await Task.Delay(100);
logger.Warn("D");
await Task.Delay(100);

NLog.LogManager.Shutdown();
```

- What is the current result?
After deleting the log file, the following log entries are not logged

- What is the expected result?
The last two log entries should be logged

- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
Yes 

- Please post full exception details (message, stacktrace, inner exceptions)
There is no exception.

- Are there any workarounds? 
No. I do not want to set EnableFileDelete to false because I need the feature to delete log files via Windows Explorer.

- Is there a version in which it did work? 
I don't know

- Can you help us by writing an unit test?

**Comment by snakefoot** [comment]
NLog FileTarget uses the FileStream-object that has an internal buffer to optimize file-write-performance. NLog will automatically re-create the FileStream-object, when it is failing to write.

When the internal-buffer in FileStream-object is filled, then it is written to disk. This means that FileStream-object only detects that the file-handle has become broken, when the internal buffer has been filled. 

NLog also performs a `File.Exists`-check every 1 second, and if no file detected then re-creates the FileStream-object.

NLog FileTarget with `FileTarget.ConcurrentWrites = true` will use a Windows-FileWatcher to listen on File-Events from the underlying file, and re-creates the FileStream-object if so.

NLog FileTarget with `KeepFileOpen = false` will always create new FileStream-object for every file-write (Performance hit)

**Comment by topsterde** [comment]
Thanks for the fast reply and the internal details of FileTarget.
I have adapted the sample program to your description. The same FileTarget properties are now used as in my real application.
Now 1000 more messages are written. And 100 seconds passed.
And still there is no log file. Do you have any idea what this could be?

```cs
using NLog;
using NLog.Common;
using NLog.Config;
using NLog.Targets;
using System.Text;

var configuration = new LoggingConfiguration();
var logfile = new FileTarget("logfile")
{
    FileName = "logfile.txt",
    ConcurrentWrites = true,
    MaxArchiveFiles = 10,
    ArchiveNumbering = ArchiveNumberingMode.Rolling,
    ArchiveAboveSize = 1024 * 1024,
    Encoding = Encoding.UTF8,
    WriteBom = true
};
configuration.AddRule(LogLevel.Trace, LogLevel.Fatal, logfile);
configuration.AddRule(LogLevel.Trace, LogLevel.Fatal, new ConsoleTarget("console"));
LogManager.Configuration = configuration;

InternalLogger.LogToConsole = true;
InternalLogger.LogLevel = LogLevel.Debug;

var logger = LogManager.GetCurrentClassLogger();

logger.Warn("Logged to file");
await Task.Delay(3000);

// Simulate the deletion of log files
File.Delete("logfile.txt");

for (var i = 0; i < 1000; i++)
{
    logger.Warn("Not logged to file");
    await Task.Delay(100);
}

LogManager.Shutdown();
```

**Comment by snakefoot** [comment]
Can you add a File.Exists check before and after the for-loop? (And output if file is detected)



Sent from my Galaxy



-------- Original message --------
From: topsterde ***@***.***>
Date: 27/04/2023 07:49 (GMT+01:00)
To: NLog/NLog ***@***.***>
Cc: Rolf Kristensen ***@***.***>, Comment ***@***.***>
Subject: Re: [NLog/NLog] No file output after deleting log files (Issue #5203)


Thanks for the fast reply and the internal details of FileTarget.
I have adapted the sample program to your description. The same FileTarget properties are now used as in my real application.
Now 1000 more messages are written. And 100 seconds passed.
And still there is no log file. Do you have any idea what this could be?

using NLog;
using NLog.Common;
using NLog.Config;
using NLog.Targets;
using System.Text;

var configuration = new LoggingConfiguration();
var logfile = new FileTarget("logfile")
{
    FileName = "logfile.txt",
    ConcurrentWrites = true,
    MaxArchiveFiles = 10,
    ArchiveNumbering = ArchiveNumberingMode.Rolling,
    ArchiveAboveSize = 1024 * 1024,
    Encoding = Encoding.UTF8,
    WriteBom = true
};
configuration.AddRule(LogLevel.Trace, LogLevel.Fatal, logfile);
configuration.AddRule(LogLevel.Trace, LogLevel.Fatal, new ConsoleTarget("console"));
LogManager.Configuration = configuration;

InternalLogger.LogToConsole = true;
InternalLogger.LogLevel = LogLevel.Debug;

var logger = LogManager.GetCurrentClassLogger();

logger.Warn("Logged to file");
await Task.Delay(3000);

// Simulate the deletion of log files
File.Delete("logfile.txt");

for (var i = 0; i < 1000; i++)
{
    logger.Warn("Not logged to file");
    await Task.Delay(100);
}

LogManager.Shutdown();

**Comment by topsterde** [comment]
The file still does not exist even after 100 seconds, `LogManager.Shutdown();` and program exit.

**Comment by snakefoot** [comment]
Strange since NLog has the following unit-test that verifies new file is created after File.Move:

https://github.com/NLog/NLog/blob/360ca80c857c98cae0d19dd2a894c91c0f44068d/tests/NLog.UnitTests/Targets/FileTargetTests.cs#L146

**Comment by snakefoot** [comment]
But I think it would be nice if the FileTarget emitted a Debug-event when it "recreated" the file.

**Comment by topsterde** [comment]
When I run your code, I get the same output. After about 10 log entries the log file is created.
You are right, the unit test is similar.
In my real application and in the first code example, unfortunately, no log file is created after deletion. All this is very strange.

**Comment by snakefoot** [comment]
@topsterde If you are able to provide example-code that reproduces the issue, then I don't mind taking a look.

I have now created  #5206 to improve the InternalLogger-output when using `KeepFileOpen=true` and `ConcurrentWrites = false`

**Comment by topsterde** [comment]
Here is another example. It occurs when `ConcurrentWrites = true` and `ArchiveAboveSize `is set.

```cs
using NLog;
using NLog.Targets;

var configuration = new NLog.Config.LoggingConfiguration();
var logfile = new FileTarget("logfile")
{
    FileName = "logfile.txt",
    ConcurrentWrites = true,
    ArchiveAboveSize = 1024 * 1024,
};
configuration.AddRule(LogLevel.Trace, LogLevel.Fatal, logfile);
configuration.AddRule(LogLevel.Trace, LogLevel.Fatal, new ConsoleTarget("console"));
LogManager.Configuration = configuration;


var logger = LogManager.GetCurrentClassLogger();

for (var i = 0; i < 2; i++)
{
    logger.Warn("File Exists: {0}", File.Exists("logfile.txt"));
    await Task.Delay(100);
}

// Simulate the deletion of log files
File.Delete("logfile.txt");

logger.Warn("File Exists: {0}", File.Exists("logfile.txt"));

for (var i = 0; i < 1000; i++)
{
    logger.Warn("File Exists: {0}", File.Exists("logfile.txt"));
    await Task.Delay(100);
}

logger.Warn("File Exists: {0}", File.Exists("logfile.txt"));

LogManager.Shutdown();
```

**Comment by snakefoot** [comment]
Thank you for the updated example. I can see there is very special logic here:

https://github.com/NLog/NLog/blob/c3426d0505bb99b07e0e370bde9b7e07210ba8fb/src/NLog/Internal/FileAppenders/FileAppenderCache.cs#L92

Believe the logic expects that logging-folder and archive-folder are two different folders. Which is also the recommended configuration before NLog v4.5.

**Comment by snakefoot** [comment]
Created  #5207 to improve the NLog FileTarget recovery-logic after file-delete. Seems there were an optimization to ignore certain file-operations in the archive-folder-destination-folder

**Comment by topsterde** [comment]
Thank you for the quick troubleshooting.
