### ISSUE TITLE
enableArchiveFileCompression="false" ignored on Linux

### ISSUE THREAD

**Issue by MartinM85** [NLog/NLog#5204]
**NLog version**:  5.1.1

**NLog.Extensions.Logging version**: 5.2.1

**Platform**: .NET6

**Current NLog config** (xml or C#, if relevant)

```xml
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <targets async="true">
        <target name="logfile" xsi:type="File"
                fileName="foo.log"
                keepFileOpen="true"
                autoFlush="false"
                openFileFlushTimeout="20"
                archiveAboveSize="10000000"
                archiveEvery="None"
                enableArchiveFileCompression="false"
                archiveFileName="foo.{#}.log"
                archiveNumbering="Rolling"
                archiveDateFormat="yyyyMMdd"
		maxArchiveFiles="10"
                layout="${message}"/>
    </targets>
    <rules>
        <!-- file logs -->
        <logger name="Foo.*" minlevel="Debug" writeTo="logfile" />
    </rules>
</nlog>

```

- What is the current result?
***Windows***
No zip archives are created. It creates files like `foo.log` and `foo.0.log`.
***Linux - debian***
Zip archives are created in spite of `enableArchiveFileCompression` is set to `false`. It creates files like `foo.log` and `foo.20230426.0.zip`

- What is the expected result?
No zip archives are created on Linux

- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
yes
- Please post full exception details (message, stacktrace, inner exceptions)
- Are there any workarounds? 
no

**Comment by snakefoot** [comment]
I'm guessing deployment issue of NLog.config. Can you include the [NLog InternalLogger](https://github.com/NLog/NLog/wiki/Internal-Logging)-output from Windows and Linux ?

**Comment by MartinM85** [comment]
deployment issue
