### ISSUE TITLE
I can't print logs with this configuration

### ISSUE THREAD

**Issue by 510463496** [NLog/NLog#5217]
```xml
 <targets async="true">
        <target  xsi:type="LimitingWrapper" interval="5" optimizeBufferReuse="true">
            <target xsi:type="AsyncWrapper" batchSize="2000">
                <target name="GFGLogInfo" xsi:type="File"
                        openFileCacheTimeout="10"
                        keepFileOpen="true"
                        archiveNumbering="Date"
                        archiveEvery="Hour"
                        archiveDateFormat="yyyyMMddHH"
                        archiveFileName="${basedir}/../GFGLogs/{#}.log"
                        fileName="${basedir}/../GFGLogs/${date:format=yyyyMMddHH}.log"
                        bufferSize="10485760"
                        layout="${message}" />
            </target>
        </target>
    </targets>
```

**Comment by 510463496** [comment]
`  <targets async="true">
        <target  xsi:type="LimitingWrapper" interval="5" optimizeBufferReuse="true">
            <target xsi:type="AsyncWrapper" batchSize="2000">
                <target name="GFGLogInfo" xsi:type="File"
                        openFileCacheTimeout="10"
                        keepFileOpen="true"
                        archiveNumbering="Date"
                        archiveEvery="Hour"
                        archiveDateFormat="yyyyMMddHH"
                        archiveFileName="${basedir}/../GFGLogs/{#}.log"
                        fileName="${basedir}/../GFGLogs/${date:format=yyyyMMddHH}.log"
                        bufferSize="10485760"
                        layout="${message}" />
            </target>
        </target>
    </targets>`

**Comment by 510463496** [comment]
![image](https://github.com/NLog/NLog/assets/33546202/549b7671-3f03-4b30-b128-e88c2724c887)
Unable to print log

**Comment by 510463496** [comment]
I want to set a buffer size limit, and if there are more than 2000 logs, I will print them once. At the same time, if there are not enough logs after 5 seconds, I will also print them once.

**Comment by 510463496** [comment]
![image](https://github.com/NLog/NLog/assets/33546202/58b836c7-9168-4771-8e66-dcdc7d4e09d3)

**Comment by snakefoot** [comment]
Sounds like you could use the [BufferingWrapper](https://github.com/NLog/NLog/wiki/BufferingWrapper-target):
```xml
            <target xsi:type="BufferingWrapper" bufferSize="2000" flushTimeout="5000">
                <target name="GFGLogInfo" xsi:type="File"
                        openFileCacheTimeout="10"
                        keepFileOpen="true"
                        archiveNumbering="Date"
                        archiveEvery="Hour"
                        archiveDateFormat="yyyyMMddHH"
                        archiveFileName="${basedir}/../GFGLogs/{#}.log"
                        fileName="${basedir}/../GFGLogs/${date:format=yyyyMMddHH}.log"
                        bufferSize="10485760"
                        layout="${message}" />
            </target>
```
You can then decide if you want to use the `slidingTimeout="false"`

**Comment by 510463496** [comment]
OK，I am deeply grateful.

**Comment by 510463496** [comment]
Quote reply

**Comment by 510463496** [comment]
I would like to ask how to set up a log file every 10 minutes. Currently, I have one log file every hour

**Comment by snakefoot** [comment]
@510463496 Please create new issue, instead of waking up old ones.
