### ISSUE TITLE
ScopeContext.PushProperties without being wrapped in using statement

### ISSUE THREAD

**Issue by frozzen10** [NLog/NLog#5221]
**NLog version**: 5.1.4

**Platform**:  .NET6

**Current NLog config**: I am using appsettings.json file

```json
"NLog": {
    "autoReload": true,
    "throwConfigExceptions": true,
    "internalLogLevel": "Debug",
    "internalLogFile": "${basedir}/internal-nlog.txt",
    "targets": {
      "async": true,
      "logfile": {
        "type": "File",
        "fileName": "${basedir}/logs/${shortdate}.txt",
        "layout": "${longdate} | ${uppercase:${level}} | ${logger} | CorrelationId: ${scopeproperty:item=correlationId} | ${message}",
        "concurrentWrites": true
      },
      "logconsole": {
        "type": "Console",
        "layout": "${longdate} | ${uppercase:${level}} | ${logger} | CorrelationId: ${scopeproperty:item=correlationId} | ${message}"
      },
     
    },
    "rules": [
      {
        "logger": "*",
        "minLevel": "Info",
        "writeTo": "logfile,logconsole"
      }
    ]
  },

```

- What is the current result? 
I think for now it's good but I am afraid that it can cause some memory leaks or other issues that I am not able to see right now
- What is the expected result?
Logging property pushed to the ScopeContext (it works for now).
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
Nothing helpful in this case is there
- Please post full exception details (message, stacktrace, inner exceptions)
There is no exceptions - it looks like it is working but as I mentioned above something may not be as good as it looks.
- Are there any workarounds? yes/no
I think my current implementation is workaround.
- Is there a version in which it did work? 
As told earlier.
- Can you help us by writing an unit test?

So, I have some extension method that creates Autofac's ILifetimeScope and before returning scope I have line:
```c#
ScopeContext.PushProperties(CreateFromCorrelationContext(context));
```
and it's logging my property (some guid) as it should but I am not wrapping it in using statement and there is my question how it is disposed?
```c#
public static ILifetimeScope BeginScopeWithCorrelationContext(this ILifetimeScope @this)
{
    ICorrelationContext context = ...; // context creation

    var scope = @this.BeginLifetimeScope();
    ScopeContext.PushProperties(CreateFromCorrelationContext(context));
    return scope;
}
```
and this is called inside in two places: middleware and a while loop inside scheduler class when scope is created for task that will be executed.

middleware:
extension method is used in two places in middleware:
```c#
public async Task Invoke(HttpContext context)
{
    using var customRequestScope = scope.BeginScopeWithCorrelationContext();

    await next(context);
}
```
and loop:
```c#
private async Task DoSth(ParameterX parameterX, CancellationToken cancellationToken)
{
    while (!cancellationToken.IsCancellationRequested)
    {
        using (var scope = _rootScope.BeginScopeWithCorrelationContext("))
        {
            // here is code that execute other clasess objects that contains logger as property
        }
    }
}
```

EDIT: From https://github.com/NLog/NLog/issues/4992#issuecomment-1167683800 this comment I am aware that ScopeContext is related to thread execution context so I think this might be important.
END EDIT:
I am not sure it this is also important but this is how method with loop is called
```C#
public async Task StartAsync(CancellationToken cancellationToken)
{
    var workers = new List<Task>();

    foreach (ParameterX parameterX in _parametersX)
    {
        workers.Add(Task.Run(() => DoSth(parameterX, cancellationToken), cancellationToken));
    }
    await Task.WhenAll(workers);
}
```

From my observation it looks good but as I mentioned above I am afraid that it can cause some memory leaks or other issues that I am not able to see right now.

**Comment by snakefoot** [comment]
It is correct that NLog ScopeContext lives in the execution-context of the active thread. And it returns an IDisposable handle for removing the scope-properties when no longer relevant.

The recommended way is to setup the scope first, and then create the child-tasks (that will "inherit" the active ScopeContext-properties):
```c#
public async Task StartAsync(HttpContext context, CancellationToken cancellationToken)
{
    var workers = new List<Task>();
 
    using (ScopeContext.PushProperties(CreateFromCorrelationContext(context))
    {
        foreach (ParameterX parameterX in _parametersX)
        {
            workers.Add(Task.Run(() => DoSth(parameterX, cancellationToken), cancellationToken));
        }
    }
    await Task.WhenAll(workers);
}
```
But NLog `ScopeContext.PushProperties` is performing some tricks, where it "collapses" the scope-properties. So if you call `ScopeContext.PushProperties` in a tight loop, then you will notice it is allocates but without holding on to previous allocations (garbage collector can cleanup without memory leaks).

**Comment by frozzen10** [comment]
Thanks for fast response!
But what about my implementation? Because I don't know if when I push properties inside my extension method, how it will be disposed. There is no wrap in using statement but it looks like it's working.

**Comment by snakefoot** [comment]
Yes when calling `ScopeContext.PushProperties` (without disposing), then NLog will "collapse" the scope-properties (garbage collector can cleanup without memory leaks)

**Comment by frozzen10** [comment]
@snakefoot So it looks like it should behave correctly, even without wrapping in using - nice! If I encounter any problems, I will promptly inform you. As I mentioned earlier, in reference to your response, it appears that the code I presented is functioning correctly.

**Comment by snakefoot** [comment]
Closing as resolved due to inactivity.
