### ISSUE TITLE
${all-event-properties} are not printed to File target

### ISSUE THREAD

**Issue by FixRM** [NLog/NLog#5231]
Hi! Thank you for making NLog! 

**NLog version**: 5.1.4

**Platform**: ..Net Framework 4.7.1 

**Current NLog config** (xml or C#, if relevant)

```xml
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" autoReload="true">
    <extensions>
        <add assembly="NLog.Targets.ElasticSearch"/>
    </extensions>
    <variable name="projectName" value="WebApi" />
    <variable name="environment" value="${appsetting:item=Environment}"/>
    <targets async="true">
        <target name="file" xsi:type="File" fileName="C:\Logs\${projectName}\file.log"
                layout="${date} | ${level} | ${message} | ${all-event-properties}" />
        <target name="elastic" xsi:type="BufferingWrapper" flushTimeout="5000">
            <target xsi:type="ElasticSearch"
                    includeAllProperties="true"
                    index="${environment}-${lowercase:${projectName}}-${date:format=yyyy.MM.dd}"
                    uri="http://localhost:9200"
                    layout="${message}">
            </target>
        </target>
    </targets>
    <rules>
    <logger name="*" minlevel="Info" writeTo="file,elastic"/>   
    </rules>
</nlog>
```
I use Fluent API to write properties to the log and I can see them in elastic, but for some reasons I can't see them in file. Only spaces are rendered after delimiter. I also tried to print properties separately with same results. Internal logging show no errors.

**Comment by snakefoot** [comment]
Can you update your question with an example of how your capture the LogEvent-properties, along with example of property-class-types ?

You are also wellcome to create a pull-request for this repository, that reproduces the unexpected behavior.

**Comment by FixRM** [comment]
Hello, sure, they are all string types:

```C#
            logEventBuilder.Message("Method {method} returned {statusCode}", methodName, responseStatusCode)
                    .Property("requestContent", requestContent)
                    .Property("responceContent", responceContent)
                    .Property("requestUri", requestUri)
                    .Log();
```
Will come back with PR soon

**Comment by FixRM** [comment]
Case closed, I'm stupid, sorry for wasting your time 😢 We put logs to a different files based on ${callsite} and all structured part went not to the file a was looking in.

**Comment by snakefoot** [comment]
Glad the mystery was resolved, always great to get confirmation that things works as expected :)

**Comment by FixRM** [comment]
Thank you for your time @snakefoot
