### ISSUE TITLE
NLog does not output anything on webgl platform

### ISSUE THREAD

**Issue by wintersunrain** [NLog/NLog#5239]
We use Unity IL2CPP to compile codes (include NLog) in csharp to c++(il2cpp), and then use emscripten to compile codes to the final wasm. There are no errors either in compilation time or in the runtime, but nothing outputs. Does NLog support webgl platform?

**Comment by snakefoot** [comment]
Have you tried to enable [NLog InternalLogger](https://github.com/NLog/NLog/wiki/Internal-Logging) from code, and checked the output ? Maybe it is just something simple like not able to find NLog.config. See also: https://github.com/NLog/NLog/wiki/Logging-Troubleshooting

I have not used NLog with WebGL or IL2CPP, so I think you have to do your own investigations. If you see that code-changes are required for a better experience with WebGL, then pull-requests are always wellcome.

**Comment by wintersunrain** [comment]
We finally get the outputs from the web console by providing a custom target, and in the target's Write method we send the message to UnityEngine's log system. In this way all the codes can be compiled to wasm and run successfully.

**Comment by snakefoot** [comment]
Thank you for sharing your experience. Good to know that NLog doesn't explode when running with WebGL / WASM.

**Comment by snakefoot** [comment]
Closing issue as resolved, due to inactivity

**Comment by snakefoot** [comment]
NLog 6.0 has been released, with reduced dependencies, so working better on minimal platforms:

- https://www.nuget.org/packages/NLog/6.0.0#releasenotes-body-tab

See also: https://nlog-project.org/2025/04/29/nlog-6-0-major-changes.html
