### ISSUE TITLE
about nlog.config file location

### ISSUE THREAD

**Issue by wang9th** [NLog/NLog#5246]
Hi! Thanks for reporting this bug! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

**NLog version: 5.2.0

**Platform**:  .NET6

**Current NLog config** (xml or C#, if relevant)

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

	<targets>
		<target name="logfile" xsi:type="File" fileName="${basedir}/logs/${shortdate}.log" />
		<target name="logconsole" xsi:type="Console" />
	</targets>

	<rules>
		<logger name="*" minlevel="Info" writeTo="logconsole" />
		<logger name="*" minlevel="Debug" writeTo="logfile" />
	</rules>
</nlog>

```

- What is the current result?
- A : I create a winform project for .Net6.0, and create a folder as Config at root directory, I put nlog.config file in that.
- Then write `nlogger.Debug("Program Start");` code in my form1_Shown function,
- It was run as normally, there is nlog.cong file at bin/debug/.net6.0windows/config/, but no logs directory be created.
- when I move nlog.config file to root directory, there is logs directory be created,and log file in there.
- What is the expected result?
- put nlog.config file in Config directory and log is normally.
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
- A : no
- Please post full exception details (message, stacktrace, inner exceptions)
- A : no any error in ouput window
- Are there any workarounds? yes/no
- A : Yes
- Is there a version in which it did work? 
- A : Yes
- Can you help us by writing an unit test?
- A : No

**Comment by snakefoot** [comment]
NLog will by default scan [multiple locations](https://github.com/NLog/NLog/wiki/Configuration-file#file-locations) for the `nlog.config`-file.

If you want to load the NLog.config from your own special location, then you can do this:
```c#
NLog.LogManager.Setup().LoadConfigurationFromFile(myCustomPath);
```

See also: https://github.com/NLog/NLog/wiki/Fluent-Configuration-API

**Comment by wang9th** [comment]
I write code in program.cs at main function first line, but there is still no log generation.
`NLog.LogManager.Setup().LoadConfigurationFromFile("Config/nlog.congfig");`

**Comment by snakefoot** [comment]
This looks like a spelling error `"Config/nlog.congfig"`. Maybe try this:
```c#
NLog.LogManager.Setup().LoadConfigurationFromFile(Path.Combine("Config", "nlog.config"));
```
Or this:
```c#
NLog.LogManager.Setup().LoadConfigurationFromFile(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "Config", "nlog.config"));
```

**Comment by wang9th** [comment]
> This looks like a spelling error `"Config/nlog.congfig"`. Maybe try this:
> 
> ```cs
> NLog.LogManager.Setup().LoadConfigurationFromFile(Path.Combine("config", "nlog.config"));
> ```
> 
> Or this:
> 
> ```cs
> NLog.LogManager.Setup().LoadConfigurationFromFile(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "config", "nlog.config"));
> ```

config file was loaded, but no log file was created

**Comment by snakefoot** [comment]
There is a [Logging Troubleshooting Guide](https://github.com/NLog/NLog/wiki/Logging-troubleshooting), but often one can find the issue by checking [NLog InternalLogger](https://github.com/NLog/NLog/wiki/Internal-logging)

**Comment by wang9th** [comment]
> There is a [Logging Troubleshooting](https://github.com/NLog/NLog/wiki/Logging-troubleshooting)-guide, but often one can find the issue by checking [NLog InternalLogger](https://github.com/NLog/NLog/wiki/Internal-logging)

When I deleted the debug folder to observe the changes after modifying the code, 
I accidentally deleted all the files in the code root directory.
 I had to recreate a winform project, create a config folder and create a "nlog.config" file in it,
 and then write `NLog.LogManager.Setup () .LoadConfigurationFromFile ("config", "nlog.config") ` in the program.cs file, successfully call logger in form_shown to output information.

**Comment by snakefoot** [comment]
Closing question as resolved, due to inactivity.
