### ISSUE TITLE
Marked ConfigurationItemFactory.CreateInstance obsolete #5191: No documented alterative approach.

### ISSUE THREAD

**Issue by mhsimkin** [NLog/NLog#5247]
In 5.2 some of the configuration methods were made obsolete, without providing a documented alternative approach.

I have code that does the following:

```c#
    private static void LoadConfiguration(JsonNode jsonNode, LogFactory logFactory)
    {
        // it is, let's get the common config folder.
        if (!jsonNode.GetNodeValue("CommonConfigFolder", out string commonConfigFolder))
            return;

        // does the folder exist?
        if (!Directory.Exists(commonConfigFolder))
            throw new DirectoryNotFoundException(
                $"The specified common config folder {commonConfigFolder} was not found.");

        // let's update the places NLog looks for it's configuration file.
        var currentFilePaths = logFactory.GetCandidateConfigFilePaths().ToList();

        // add the common config file location.
        currentFilePaths.Add(Path.Combine(commonConfigFolder, "nlog.config"));

        // reset the config paths.
        logFactory.ResetCandidateConfigFilePath();
        logFactory.SetCandidateConfigFilePaths(currentFilePaths);
    }
```

The GetCandidateConfigFilePaths(), ResetCandidateConfigFilePath(), and SetCandiadateConfigFilePaths() are now marked as obsolute.

I was using these methods to add an additional location for NLog to search for the nlog.config file.  Since I'm building a library that will be used to bootstrap the development of .NET 7 services that can run on multiple OS platforms, I am leaving the location of the NLog.Config file up to the implementor. I just need to add an additional location to be searched.

While I can use the new LogFactory.Setup().LoadConfigurationFromFile() method and pass the a new location, it will then expect to load the file from that location.

For example, a group of services that are designed as a processing pipeline might have a common configuration folder as they share a significant group of settings, while a standalone service will have the configuration information in the application's folder.

Having a common configuration folder, doesn't prevent the implementor from placing the NLog.Config file in the application's folder.  If I need to change logging on one specific instance, I can just drop an updated NLog.Config in the application folder, while all the other services in the group would use the common NLog.Config file.

How can I add a new location to be searched, while still allowing the default locations to be searched?

Thank you.

-marc

**Comment by snakefoot** [comment]
Was thinking one could `LogManger.Setup().LoadConfigurationFromFile()` and chain them together:
```c#
LogManger.Setup()
         .LoadConfigurationFromFile()
         .LoadConfigurationFromFile(Path.Combine(commonConfigFolder, "nlog.config")); // extra fallback
```
`LoadConfigurationFromFile` has the parameter `optional` that is true by default, and configuration is already loaded then it will skip config-loading.

**Comment by mhsimkin** [comment]
Thank you. I will give that a try.

**Comment by snakefoot** [comment]
Closing as resolved, due to inactivity.
