### ISSUE TITLE
PerfCounter remarks / questions

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#525]
Moved remarks from wiki page: https://github.com/NLog/NLog/wiki/PerfCounter-target. Can we answer these?

> TODO: 
1. Unable to create a category allowing multiple counter instances (.Net 2.0 API only, probably) 
2. Is there any way of adding new counters without deleting the whole category? 
3. There should be some mechanism of resetting the counter (e.g every day starts from 0), or auto-switching to another counter instance (with dynamic creation of new instance). This could be done with layouts.

**Comment by Xharze** [comment]
I have to look into this, I'll try to take a look at it this week.

**Comment by Xharze** [comment]
@304NotModified This seems to be internal notes, when this target was develop. I can't find anyway to do was is described.
