### ISSUE TITLE
Option to have unique log file names without breaking archiving?

### ISSUE THREAD

**Issue by adamstyl** [NLog/NLog#5250]
**NLog version**: 5.2.0

**Platform**: .Net 4.8

**Current NLog config**

```xml
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

  <targets>
    <target name="logfile" xsi:type="File" encoding="utf-8"
            layout="${longdate} | ${processid} |${level:uppercase=true:padding=-8}| ${logger:padding=-7}|${message}${onexception:${newline}}${exception:format=tostring}"
            archiveOldFileOnStartup="true"
            archiveNumbering="DateAndSequence"
            archiveFileName="logs/editor${LogDay}.{###}.log"
            keepFileOpen="true"
            concurrentWrites="true"
            fileName="editor.log" />
  </targets>

  <rules>
    <logger name="*" writeTo="logfile" />
  </rules>
</nlog>

```

My issue is very similar to this one #3496. I tried to use `${processid}` but then this breaks archiving. Is it possible to have unique log file names while still support archiving? Otherwise the main directory is littered and I'd like to keep there only the logs of the last run.

One other thing that boggles me is that I tried to use ${processid}` in the layout in order to have all instances of the same application writing to the same file. Instead of having the file appended though, it is overwritten. `keepFileOpen="true"` and `concurrentWrites="true"` are already set so I don't what am I missing or if this is a bug. But to be honest this would be my last resort. If any of the users run 2 (or more instances) of the same app, I would use grep to get 2 separate files instead of one.

**UPDATE**
Actually it's different than I thought: the new instance of the application archives the existing `editor.log`  (that's why I thought it was overwritten) and then the file is appended by both processes.

**Comment by snakefoot** [comment]
There static archive logic requires that the filename is static. See also https://github.com/NLog/NLog/wiki/File-target#dynamic-vs-static-archive-logic

Instead of using "volatile" token like process-id, then maybe consider introducing an instance-name, that you assign to NLog GDC and reference in FileTarget-FileName.

**Comment by adamstyl** [comment]
@snakefoot  Hello Rolf. Thanks for getting back to me (and for pointing me to a part of the documentation I was oblivious of...)

GDC sounds like a good suggestion but then again the -1 -2 -N files won't be archived any time soon. Though I think I could live with it.

Anyway, I'm afraid that I'm barking up the wrong tree here. The problem stems from the fact that I am trying to achieve "one file per program run" and this might not be immediately obvious. My current setup apparently doesn't help _when multiple instances are running_. I might have to reconsider the logging and archiving policy.

**Comment by snakefoot** [comment]
Closing question as resolved due to inactivity.
