### ISSUE TITLE
GetLogger<T> throws exception when instantiating class without default constructor

### ISSUE THREAD

**Issue by mhsimkin** [NLog/NLog#5252]
**_Question_**

Prior to NLog 5.2, it looks like calls to _GetLogger<T>_, _GetLogger(string name)_, and _GetLogger(string name, Type loggerType)_ did not try to create a new instance of **loggerType**. 

However, as of 5.2, it appears that all these now attempt to create an instance of **loggerType**.  Why?

This breaks if the **loggerType** does not have a default constructor when the type is only meant to be created via dependency injection.

I've run into an issue where our internal logging framework has stopped working after updating to NLog 5.2.    

How can I resolve the issue without adding default constructors to all the classes and expecting the users of my library to always have default constructors on all their classes.

My code does some of the same steps that NLog does, in order to determine the correct logger name and type at run time. It is also aware of which class names that might be on the call stack should be skipped to find the true calling class name.

At the point the code is failing, it no longer has access to any service collection that can be used to resolve the for **loggerType**.  

The library uses the Microsoft.Extensions.DependencyInjection interfaces, but leaves it up to the developer/project team to determine the actually DI framework (MS, Autofac, StructureMap, etc.).

Also, the library is based upon the Microsoft.Extensions.Logging interfaces, with specific implementations for NLog, Log4Net, SeriLog, etc.  Again, the specific underlying logging framework is left to the developer/project team.

(Note: Discussion on whether it is good/bad to support different DI/Logging frameworks are irrelevant. The decision was above my level and was a compromise.)

Thank you for your time and guidence.

-marc

**Comment by mhsimkin** [comment]
I am not using a custom logger.  I have a set of classes that support the two legacy logging APIs as extension classes of Microsoft.Extensions.Logging.ILogger.  Those classes then use an implementation specific wrap around the underlying logging framework.

I never implemented a custom logger, as I am not logging to replace the functionality of NLog.  I just need to allow a transparent way to migrate away from the internally developed legacy logging framework.

Here is the code that is going me the problem:

```
        private NLog.ILogger GetNLogLogger([NotNull] Microsoft.Extensions.Logging.ILogger logger)
        {
            // find the MSLogger's category.
            var loggerType = logger.GetType();

            if (!loggerType.IsGenericType)
                switch (loggerType.FullName)
                {
                    // let's see if we can grab the info from a registered logger.
                    case Constants.MSLoggerFullClassName:
                        return GetMsLoggerCategoryAndCreateLogger(logger);

                    case Constants.NLogMSILoggerFullClassName:
                        return GetNlogLoggerCategoryAndCreateLogger(logger);

                    default:
                        return LogManager.GetCurrentClassLogger();
                }

            // is generic
            var categoryType = loggerType.GenericTypeArguments[0];
            if (!_additionalData.ContainsKey(Constants.CallerFullClassNameKey))
                return LogManager.LogFactory.GetCurrentClassLogger(categoryType);

            var className = _additionalData[Constants.CallerFullClassNameKey] as string;
            return LogManager.GetLogger(className, categoryType);
        }
```

I'm am not opposed to a custom logger, however, I need an approach that will work for all the logging frameworks, not just NLog. At the time, using a wrapper seemed to simplest to implement and to maintain going forward.

-marc

**Comment by snakefoot** [comment]
The type-parameter of Microsoft Extension ILogger<T> is the Category-Name. Believe the logic should be like this:
```c#
        private NLog.ILogger GetNLogLogger([NotNull] Microsoft.Extensions.Logging.ILogger logger)
        {
            // find the MSLogger's category.
            var loggerType = logger.GetType();

            if (!loggerType.IsGenericType)
                switch (loggerType.FullName)
                {
                    // let's see if we can grab the info from a registered logger.
                    case Constants.MSLoggerFullClassName:
                        return GetMsLoggerCategoryAndCreateLogger(logger);

                    case Constants.NLogMSILoggerFullClassName:
                        return GetNlogLoggerCategoryAndCreateLogger(logger);

                    default:
                        return LogManager.GetCurrentClassLogger();
                }

            // is generic
            var categoryType = loggerType.GenericTypeArguments[0];
            if (_additionalData.TryGetValue(Constants.CallerFullClassNameKey, out var overrideLoggerName))
                return LogManager.GetLogger(overrideLoggerName);

            return LogManager.LogFactory.GetLogger(categoryType.ToString());
      }
```

**Comment by mhsimkin** [comment]
@snakefoot 

Thank you for the response. 

It looks to me that the only difference is that I should be passing the category name as a string and not pass an object type.

I gave it a quick test and it seems to work.  I will need to do more complete testing tomorrow.

I'm not sure about your last comment.

Thank you for the help.

-marc
