### ISSUE TITLE
log file output does not work with an exception: Warn Error has been raised. Exception: NLog.NLogConfigurationException: 'SimpleLayout' cannot assign property 'Text'

### ISSUE THREAD

**Issue by JimGolden** [NLog/NLog#5265]
Hi! Thanks for reporting this bug! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

**NLog versions**
- NLog  5.1.1
- NLog.Web.AspNetCore  5.2.1

**Platform**:  is  .NET6

**Current NLog config** (xml or C#, if relevant)
See attached config files:
- [NLog.config](https://github.com/NLog/NLog/files/11791148/NLog.Log)
- [NLog.WebExtensions.config](https://github.com/NLog/NLog/files/11791149/NLog.WebExtensions.Log)

**What is the current result?**

Logging works correctly only when no "when condition" filters are applied within the logFile logger. Once filters are added, we get an exception.

```
2023-06-19 13:34:45.6069 Warn Error has been raised. Exception: NLog.NLogConfigurationException: 'SimpleLayout' cannot assign property 'Text'
 ---> NLog.NLogConfigurationException: 'WhenLayoutRendererWrapper' has same property 'Inner=' assigned twice
   at NLog.Layouts.LayoutParser.ValidatePreviousParameterName(String previousParameterName, String parameterName, LayoutRenderer layoutRenderer, Nullable`1 throwConfigExceptions)
   at NLog.Layouts.LayoutParser.ParseLayoutRenderer(ConfigurationItemFactory configurationItemFactory, SimpleStringReader stringReader, Nullable`1 throwConfigExceptions)
   at NLog.Layouts.LayoutParser.CompileLayout(ConfigurationItemFactory configurationItemFactory, SimpleStringReader sr, Nullable`1 throwConfigExceptions, Boolean isNested, String& text)
   at NLog.Layouts.LayoutParser.CompileLayout(String value, ConfigurationItemFactory configurationItemFactory, Nullable`1 throwConfigExceptions, String& text)
   at NLog.Layouts.SimpleLayout.SetLayoutText(String value, Nullable`1 throwConfigExceptions)
   at NLog.Layouts.SimpleLayout.set_Text(String value)
```

**We cannot find what syntax error the exception is complaining about:** 

```
 layout xsi:type="SimpleLayout" text="[${level:upperCase=true}] ${logger}${when:when=length('${event-properties:item=Method}')>0:Inner=.${event-properties:item=Method}}: ${message}${when:when=length('${all-event-properties}')>0:Inner=${newline}Properties: ${all-event-properties}}${onexception:inner=${newline}Exception: ${exception:format=tostring}}"
```

When the entire target `Debugger` is excluded, no errors are logged but also there is no NLog trace output logged.
When the `logFile` logger does not contain filters, logging works correctly.

**What is the expected result?**
We need to find a way to log tracing where filters can be applied in order to filter out namespaces that make the file output too chatty.
[NLog-Internal_(Exclude Target Debugger, no output).log](https://github.com/NLog/NLog/files/11791113/NLog-Internal_.Exclude.Target.Debugger.no.output.log)

**Did you checked the Internal logger?**

Yes, attached are Internal-Logging files which have been renamed in order to provide examples for each scenario.

- [NLog-Internal_(Exclude Target Debugger, no output).log](https://github.com/NLog/NLog/files/11791146/NLog-Internal_.Exclude.Target.Debugger.no.output.log)
- [NLog-Internal_(Exception when Filters are added).log](https://github.com/NLog/NLog/files/11791150/NLog-Internal_.Exception.when.Filters.are.added.log)
- [NLog-Internal_(No file output, throwConfigExceptions = false).log](https://github.com/NLog/NLog/files/11791839/NLog-Internal_.No.file.output.throwConfigExceptions.false.log)

**Comment by JimGolden** [comment]
The Debugger target that displays in the logged exception xml didn't get retained in the issue email above. We cannot find a syntax issue in the SimpleLayout expression below:

<layout xsi:type="SimpleLayout" text="[${level:upperCase=true}] ${logger}${when:when=length('${event-properties:item=Method}')>0:Inner=.${event-properties:item=Method}}: ${message}${when:when=length('${all-event-properties}')>0:Inner=${newline}Properties: ${all-event-properties}}${onexception:inner=${newline}Exception: ${exception:format=tostring}}" />

Thank you

**Comment by JimGolden** [comment]
I found the article on the filter breaking change, thanks.
https://nlog-project.org/2021/08/25/nlog-5-0-preview1-ready.html#loggingrule-filters-defaultaction-changed-to-filterresultignore

**Comment by snakefoot** [comment]
NLog Layout parser doesn't like unescaped `:´, because they have special meaning and signals option-name:

Changing from this:
```
layout xsi:type="SimpleLayout" text="[${level:upperCase=true}] ${logger}${when:when=length('${event-properties:item=Method}')>0:Inner=.${event-properties:item=Method}}: ${message}${when:when=length('${all-event-properties}')>0:Inner=${newline}Properties: ${all-event-properties}}${onexception:inner=${newline}Exception: ${exception:format=tostring}}" 
```
To this should fix it:
```
layout xsi:type="SimpleLayout" text="[${level:upperCase=true}] ${logger}${when:when=length('${event-properties:item=Method}')>0:Inner=.${event-properties:item=Method}}\: ${message}${when:when=length('${all-event-properties}')>0:Inner=${newline}Properties\: ${all-event-properties}}${onexception:inner=${newline}Exception\: ${exception:format=tostring}}" 
```
But I can recognize that it doesn't make much sense to recognize option-delimiter for SimpleLayout, as there are no options for SimpleLayout. Also the current error-message is not that helpful in telling what is wrong.

Did the layout work with a previous version of NLog ?

**Comment by snakefoot** [comment]
Notice that `filters` should only be used when filtering on Logger-name and LogLevel-severity is not enough:

This filter:
```xml
    <logger name="Microsoft.*" minlevel="Info" writeTo="colorconsole" />
    <logger name="System.*" minlevel="Info" writeTo="colorconsole" />
    <logger name="*" minlevel="Debug" writeTo="colorconsole">
      <when condition="starts-with(logger, 'Microsoft')" action="Ignore" />
      <when condition="starts-with(logger, 'System')" action="Ignore" />
    </logger>
```
Can be rewritten with these rules:
```xml
    <logger name="Microsoft.*" finalMinLevel="Info"  />
    <logger name="System.*" finalMinLevel="Info"  />
    <logger name="*" minlevel="Debug" writeTo="colorconsole" />
```


And these filters:
```xml
    <logger name="BSTGlobal.*" minlevel="Trace" writeTo="logFile">
      <filters>
        <when condition="level >= LogLevel.Warn" action="LogFinal" />
        <when condition="equals(logger, 'BSTGlobal.Framework.Common.LocalCacheManager')" action="Ignore" />
        <when condition="equals(logger, 'BSTGlobal.Framework.Contracts.Models.ModelCatalog')" action="Ignore" />
        <when condition="equals(logger, 'BSTGlobal.Framework.Contracts.Models.Resolver')" action="Ignore" />
        <when condition="equals(logger, 'BSTGlobal.Framework.Contracts.Models.ResolverExtensions')" action="Ignore" />
        <when condition="equals(logger, 'BSTGlobal.Framework.Document')" action="Ignore" />
        <when condition="starts-with(logger, 'BSTGlobal.DesignStudio.Plugin.Models.ModelProject')" action="Ignore" />
        <when condition="starts-with(logger, 'BSTGlobal.Framework.DomNode')" action="Ignore" />
        <when condition="starts-with(logger, 'BSTGlobal.Framework.Common.WeakEvents')" action="Ignore" />
        <when condition="starts-with(logger, 'BSTGlobal.Framework.Design.ComponentModel.ModelTypeDescriptionProvider')" action="Ignore" />
        <when condition="starts-with(logger, 'BSTGlobal.Framework.ComponentModel.DocumentCollectionTypeDescriptionProvider')" action="Ignore" />
        <when condition="starts-with(logger, 'BSTGlobal.Framework.ComponentModel.DocumentTypeDescriptionProvider')" action="Ignore" />
        <when condition="starts-with(logger, 'BSTGlobal.Framework.ComponentModel.PropertyGroupTypeDescriptionProvider')" action="Ignore" />
        <when condition="starts-with(logger, 'BSTGlobal.Common.Diagnostics.Telemetry.')" action="Ignore" />
        <when condition="equals('${event-properties:item=Method}', 'CreatePropertyDescriptor')" action="Ignore" />
        <when condition="equals('${event-properties:item=Method}', 'CreatePropertyModelDescriptor')" action="Ignore" />
      </filters>
    </logger>
```
Can be rewritten to these rules:
```xml
    <logger name="BSTGlobal.Framework.Common.LocalCacheManager" finalMinLevel="Warn" />
    <logger name="BSTGlobal.Framework.Contracts.Models.ModelCatalog" finalMinLevel="Warn" />
    <logger name="BSTGlobal.Framework.Contracts.Models.Resolver" finalMinLevel="Warn" />
    <logger name="BSTGlobal.Framework.Contracts.Models.ResolverExtensions'" finalMinLevel="Warn" />
    <logger name="BSTGlobal.Framework.Document" finalMinLevel="Warn" />
    <logger name="BSTGlobal.DesignStudio.Plugin.Models.ModelProject*" finalMinLevel="Warn" />
    <logger name="BSTGlobal.Framework.DomNode*" finalMinLevel="Warn" />
    <logger name="BSTGlobal.Framework.Common.WeakEvents*" finalMinLevel="Warn" />
    <logger name="BSTGlobal.Framework.Design.ComponentModel.ModelTypeDescriptionProvider*" finalMinLevel="Warn" />
    <logger name="BSTGlobal.Framework.ComponentModel.DocumentCollectionTypeDescriptionProvider*" finalMinLevel="Warn" />
    <logger name="BSTGlobal.Framework.ComponentModel.PropertyGroupTypeDescriptionProvider*" finalMinLevel="Warn" />
    <logger name="BSTGlobal.Common.Diagnostics.Telemetry.*" finalMinLevel="Warn" />
    <logger name="BSTGlobal.*" minlevel="Trace" writeTo="logFile" defaultAction="Neutral">
        <when condition="equals('${event-properties:item=Method}', 'CreatePropertyDescriptor')" action="Ignore" />
        <when condition="equals('${event-properties:item=Method}', 'CreatePropertyModelDescriptor')" action="Ignore" />
    </logger>
```

See also: https://github.com/NLog/NLog/wiki/Logging-Rules-FinalMinLevel

**Comment by JimGolden** [comment]
Thank you! I also found that the previous version filter default had changed. Which also seems to fix this issue.

https://nlog-project.org/2021/08/25/nlog-5-0-preview1-ready.html#loggingrule-filters-defaultaction-changed-to-filterresultignore

<filters defaultAction="Log">
