### ISSUE TITLE
FileTarget with enableArchiveFileCompression does not compress files from yesterday

### ISSUE THREAD

**Issue by fancky2019** [NLog/NLog#5286]
Hi! Thanks for reporting this feature!

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

**NLog version**: (e.g. 5.0.0.0)

**Platform**: .Net 3.5 / .Net 4.0 / .Net 4.5 / Mono 4 / Xamarin Android / Xamarin iOS / .NET Core / .NET5 / .NET6

**Current NLog config** (xml or C#, if relevant)

```xml
<target name="SyncLog" xsi:type="File"
             fileName="${basedir}/logs/${date:yyyy-MM}/${date:yyyy-MM-dd}/SyncLog - ${shortdate}.log"
             layout="${longdate}|${message}"
             keepFileOpen="true"
             archiveAboveSize="10"
             maxArchiveDays="365"
             maxArchiveFiles="10"		
             archiveOldFileOnStartupAboveSize="10"
             archiveNumbering="Date"
             archiveEvery="Day"
             archiveFileName="${basedir}/logs/${date:yyyy-MM}/${date:yyyy-MM-dd}/Log - ${shortdate}.zip"
             enableArchiveFileCompression="true"
/>
```

hi, i want to zip my history logs ,i configure above. I find that Nlog can only zip current date log file and can't zip logs the day before current date . Can you help me what should i do. thanks!

**Comment by snakefoot** [comment]
`enableArchiveFileCompression` only works with [static filename](https://github.com/NLog/NLog/wiki/File-target#dynamic-vs-static-archive-logic) where `archiveFileName` should contain `{#}` with help from `archiveDateFormat`.
