### ISSUE TITLE
Nullable value types are skipped when checking if required parameters have been set

### ISSUE THREAD

**Issue by Humandoodlebug** [NLog/NLog#5288]
NLog does not check if required parameters with nullable value types (such as `int?`) are set on layout renderers.

It looks to be because of this change: https://github.com/NLog/NLog/commit/463c9679c0d7e92266a4cff21fff56c35b8dca0b#diff-da7069c83cce16c3a2cc66eb40f57552809453ed5f8ac368e5fb9fcc0fa71319R226

**NLog version**: 5.2.2

**Platform**: .Net 4.8

**Current NLog config** (xml or C#, if relevant)

The following NUnit test fails as-is, but will pass if `TestProp`'s type is changed from `double?` (`Nullable<double>` - a nullable value type) to `object` (a reference type).

```csharp
using System.Text;

using global::NLog;
using global::NLog.Config;
using global::NLog.LayoutRenderers;
using global::NLog.Targets;

using NUnit.Framework;

public class ExampleLayoutRenderer : LayoutRenderer
{
    [RequiredParameter]
    public double? TestProp { get; set; }

    protected override void Append(StringBuilder builder, LogEventInfo logEvent)
    {
    }
}

public class ExampleLayoutRendererTests
{
    [Test]
    public void Test_RequiredPropNotSet()
    {
        using (new NLogTestingContext())
        {
            LogManager.Setup().SetupExtensions(
                ext => ext.RegisterLayoutRenderer<ExampleLayoutRenderer>("example-layout-renderer")
            );

            using (var debugTarget = new DebugTarget
            {
                Layout = "${example-layout-renderer} ${message}",
            })
            {
                Assert.Throws<NLogConfigurationException>(
                    () =>
                    {
                        var loggingConfiguration = new LoggingConfiguration();
                            loggingConfiguration.AddRule(
                            global::NLog.LogLevel.Trace,
                            global::NLog.LogLevel.Fatal,
                            target
                        );

                        using (new LogFactory
                        {
                            ThrowConfigExceptions = true,
                            ThrowExceptions = true,
                            Configuration = loggingConfiguration,
                        })
                        {
                        }
                    }
                );
            }
        }
    }
}
```

- What is the current result?
No configuration exception is thrown.

- What is the expected result?
A configuration exception should be thrown, since the required property `TestProp` has not been specified.

- Is there a version in which it did work? 
This previously worked as expected in 4.7.13.

**Comment by snakefoot** [comment]
Thank you for reporting this. Have created #5289 together with unit-test to ensure required-attribute works for Nullable-types in NLog v5.

**Comment by snakefoot** [comment]
NLog v5.2.3 has been released - https://www.nuget.org/packages/NLog

**Comment by snakefoot** [comment]
Notice NLog v6 will obsolete `[RequiredParameter]`, instead one should implement any additional option-validation in `InitializeTarget` / `InitializeLayout`.

NLog v6 adopts nullable-support, and will apply empty (non-null) values where possible. This reduces the usefulness of  `[RequiredParameter]`, that also infers an overhead as it requires additional object-reflection.

See also: https://nlog-project.org/2025/04/29/nlog-6-0-major-changes.html
