### ISSUE TITLE
NLog Documentation Site Broken in Vivaldi

### ISSUE THREAD

**Issue by 240026763** [NLog/NLog#5292]
The documentation site seems broken right now. It used to pull up the targets and config options but now stays blank.
I'm using Vivaldi, a chrome-variant browser. I have tried disabling all plugins & extensions and loading the page in a vanilla private window.
![image](https://github.com/NLog/NLog/assets/49650352/a872beda-c9f0-482c-8b0b-63f9b836a14f)

The issue doesn't appear to be an issue in Edge or Chrome.

**Comment by snakefoot** [comment]
Are you able to enable developer-console to see why Vivaldi is not happy ?

Pull-request that improves are most welcome: https://github.com/NLog/NLog.github.io

**Comment by 240026763** [comment]
The issue appears to be the built-in ad blocker on Vivadi. The developer tools inspect gave the error: `net::ERR_BLOCKED_BY_CLIENT`. Once I put in a whitelist for nlog-project.org. Vivaldi was happy again.
