### ISSUE TITLE
What is SilverlightApplicationInfoLayoutRenderer used for in NLog v2 ?

### ISSUE THREAD

**Issue by mahenderkk08** [NLog/NLog#5295]
Hi Team 

My name is Mahender, and I am currently working on a project that involves using NLog for logging functionalities. I have come across two LayoutRenderers files in NLog version 2.0.0.0- "SilverlightApplicationInfoLayoutRenderer.cs" and "SilverlightApplicationInfoOption.cs" and would like to seek clarification on their usage and compatibility in NLog 2.0.0.0.

1. Why are "**SilverlightApplicationInfoLayoutRenderer.cs**" and "**SilverlightApplicationInfoOption.cs**" used in NLog version 2.0.0.0 ?

2. Is Silverlight supported in NLog 2.0.0.0? If yes, could you provide guidance on how safe it is to use NLog 2.0.0.0? If Silverlight is not supported, could you please clarify the purpose of "**SilverlightApplicationInfoLayoutRenderer.cs**" and "**SilverlightApplicationInfoOption.cs**"?

Understanding the rationale behind using these components and their compatibility with Silverlight in NLog 2.0.0.0 is crucial to making informed decisions for our project.

Thank you for your time and expertise. I greatly appreciate your assistance in providing clarity on these matters.

Looking forward to your response.

Thanks.

**Comment by snakefoot** [comment]
See also: https://stackoverflow.com/q/76771201/193178

**Comment by snakefoot** [comment]
There is a [wiki-page](https://github.com/NLog/NLog/wiki/SL-AppInfo-Layout-Renderer) and you can also look at the source-code here [SilverlightApplicationInfoLayoutRenderer.cs](https://github.com/NLog/NLog/blob/master/src/NLog/LayoutRenderers/SilverlightApplicationInfoLayoutRenderer.cs) 

Notice that NLog v5 no longer supports Silverlight. The lastest version supporting Silverlight is NLog v4.7.15

Also notice Silverlight reached end-of-life at October 12, 2021

**Comment by snakefoot** [comment]
Closing issue as resolved due to inactivity.
