### ISSUE TITLE
Can you please add nlog-kafka-target into targets page of n-log website?

### ISSUE THREAD

**Issue by hayrullahcansu** [NLog/NLog#5304]
Hi! Thanks for reporting this feature!

sorry i couldn't reach you to via email this is why i'm creating this issue. 

i'm own this repository that helps to write logs into kafka with custom topics.  It would be really good if you add this project to targets page. 

https://github.com/hayrullahcansu/nlog-kafka-target

**Comment by snakefoot** [comment]
You are very wellcome to create a pull-request here:

https://github.com/NLog/NLog.github.io/pulls

Similar to this pull-request: https://github.com/NLog/NLog.github.io/pull/231

**Comment by hayrullahcansu** [comment]
@snakefoot thank you, i created PR
https://github.com/NLog/NLog.github.io/pull/242
