### ISSUE TITLE
Network target not working with AutoFlushWrapper and BufferingWrapper

### ISSUE THREAD

**Issue by FixRM** [NLog/NLog#5305]
Hello! Thank you for supporting NLog!

**NLog version**: 5.2.2

**Platform**: .Net 4.6.2

**Current NLog config** (xml or C#, if relevant)

```xml
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	  autoReload="true"
	  internalLogToConsole="true" 
	  internalLogLevel="Info">
	<targets>
		<target name="Logstash" xsi:type="AutoFlushWrapper" condition="level >= LogLevel.Error" flushOnConditionOnly="true">
			<target xsi:type="BufferingWrapper" bufferSize="5" overflowAction="Discard">
				<!--<target xsi:type="Console" layout="${message}"/>-->
				<!--<target xsi:type="File" layout="${message}" fileName="log.txt"/>-->
				<target name="Network" xsi:type="Network" layout="${message}" address="tcp://localhost:9045" newLine="true" />
			</target>
		</target>
	</targets>
	<rules>
		<logger name="*" minlevel="Info" writeTo="Logstash" />
	</rules>
</nlog>
```

Program.cs:
```C#
var logger = LogManager.GetCurrentClassLogger();

for (int i = 0; i < 10; i++)
{
    logger.Info($"I'm {i}");
}

logger.Error("Error");
```
This config works as expected with Console or File targets, but seems not working with Network target. Unwrapped Network target with the same settings works as expected. Internal log show no errors or something suspicious .

**Comment by FixRM** [comment]
Thanks, @snakefoot. How can I make sure if it has enough time? I tried to add LogManager.Flush, but I guess AutoFlushWrapper is instructed to ignore it.

**Comment by snakefoot** [comment]
Yes when AutoFlushWrapper has `flushOnConditionOnly="true"`, then it will ignore explicit flush / shutdown.

I guess one could extend AutoFlushWrapper, so instead of ignoring explicit flush, then explicit flush will "wait" for any pending flush.

**Comment by snakefoot** [comment]
Yes NLog InternalLogger usually only produces output when something interesting happens. Maybe if you change to `internalLogLevel="Trace"`, then you will get more output.

**Comment by snakefoot** [comment]
Created pull-request #5308 that tries to improve AutoFlushWrapper handling of explicit-flush when using `flushOnConditionOnly="true"`. The explicit-flush will await any pending async-flush-operations, before signaling completion.

**Comment by snakefoot** [comment]
NLog v5.2.3 has been released - https://www.nuget.org/packages/NLog

**Comment by FixRM** [comment]
Thanks @snakefoot, new version works! So it was a bug really? Because I was plying with [network-tracing](https://learn.microsoft.com/en-us/dotnet/framework/network-programming/network-tracing ) and I saw that NLog was sending network requests. I thought that problem was with "batching" of requests (with possible breaking of message struct) or with a receiving party.

**Comment by snakefoot** [comment]
Excellent. Happy that I guessed correctly about what the issue was. I guess you felt it was a bug,  but `flushOnConditionOnly="true"` means ignore explict flush, and that was exactly what it did :)

Have now changed to so explicit flush is not completely ignored, and hopefully this gives a better behavior when using `flushOnConditionOnly="true"` together with async-targets (Like the network-target).

**Comment by FixRM** [comment]
Thanks again! May be I didn't understand the Idea behind this config, I took it from from the documentation... The problem that I'm trying to solve is the following:.. We have classic desktop application (we have to) that is installed on hundreds of stations and it's really over logging as we may don't know what may help us to understand the issue of particular user. So I want NLog to collect last X of log messages and push them only when first error occurs.

**Comment by snakefoot** [comment]
Then the combination of AutoFlushWrapper and BufferingWrapper with discard should give that behavior. And with NLog v5.2.3 then it has better support for asyn-targets like the NetworkTarget.
