### ISSUE TITLE
Plan: Remove Obsolete

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#531]
Proposal for NLog 4, remove the `Obsolete` marked classes & methods:

| What | Alternative | Obsolete since (in code) | Marked as Obsolete in wiki | comments | obsolete text has NLog version |
| --- | --- | --- | --- | --- | --- |
| `GDC` type | `GlobalDiagnosticsContext` type | 2.0 | yes |  |  |
| `MDC type` | `MappedDiagnosticsContext` type | 2.0 | yes |  |  |
| `NDC type` | `NestedDiagnosticsContext` type | 2.0 | yes |  |  |
| `EventContextLayoutRenderer` type | `EventPropertiesLayoutRenderer` type | 2.0 | yes (but recently) |  |  |
| `LogEventInfo.Context` | `LogEventInfo.Properties` | 2.0 | ? |  |  |
| `LoggerShortName` | ?? | 2.0 | ? |  |  |
| `ExceptionLoggingOldStyle` | new loggingstule | 4.1 | not on wiki | added in 4.1 to make move easier from 3 to 4 |  |
| `DisableLogging()` in LogFactory | `SuspendLogging()` | 4.0 |  |  |  |
| `EnableLogging()` in LogFactory | `ResumeLogging()` | 4.0 |  |  |  |
| `FileTarget.maxLogFilenames` | `FileTarget.maxLogFilenames` | not yet | no impact on nlog XML config |  |  |
| `DatabaseTarget.UseTransactions` | don't use it | 4.2.1 | 4.0 | restored with warning in 4.2.1 | yes |

**Comment by Xharze** [comment]
I think it would be a great idea to remove these classes. Hopefully all has either an alternative or shouldn't be used anymore.

**Comment by 304NotModified** [comment]
Updated with listing the alternatives

**Comment by 304NotModified** [comment]
Note: https://github.com/NLog/NLog/wiki/EventContext-Layout-Renderer not documented as obsolete in wiki

**Comment by ie-zero** [comment]
My proposal is to document the version a function/class or feature became obsolete and agree a certain number of minor version which will remain for example three. 

After the agreed number of version elapse the feature can be removed at any time.

**Comment by 304NotModified** [comment]
Thanks for your input!

According to semver, it's only allowed to remove stuff with a major version. 

But we have to sum up what's obsolete (and what is already proper communicated, like wiki and news post)

**Comment by ie-zero** [comment]
Thanks for your comment. I still learning new things about this project everyday. 

It is only logical to remove members of the public interface only on major versions as they are breaking changes. 

My reasoning behind documenting the version a feature became obsolete is the following: when we mark a feature obsolete on version 4.3 and the next version is 5.0 then it reasonable to remove this feature with such a short notice?

**Comment by 304NotModified** [comment]
Good point.  I was thinking to remove only obsolete (public)  code when it's obsolete for at least 1 major version (so nlog 5 can remove stiff of NLog 1-3).

**Comment by ie-zero** [comment]
**Properties**
`ExceptionLoggingOldStyle` in LoggingConfiguration - alternative *unknown*

**Methods**
`DisableLogging()` in LoggingConfiguration - alternative `SuspendLogging()` 
`EnableLogging()` in LoggingConfiguration - alternative `ResumeLogging()`

**Comment by ie-zero** [comment]
We might wish to consider if the methods and properties related to NLog 1 in `Logger` and `ILogger` are still required.

**Comment by 304NotModified** [comment]
> We might wish to consider if the methods and properties related to NLog 1 in Logger and ILogger are still required.

Can you give some examples of methods/properties?

**Comment by 304NotModified** [comment]
Proposal:

- [ ] 1. Finding all current `Obsolete` attribute usages
- [ ] 2. Find alternatives for the obsoletes 
- [ ] 3. Find out in which NLog version there are marked as obsolete
- [ ] 4. Alter the message in the Obsolete Attribute. Proposal: "Deprecated since NLog X, use Y, this will be used is NLog Z", where `Z > X+1`
- [ ] 5. Find new possibilities to mark as obsolete. 
- [ ] 6. Mark them as proposed in 4.

**Comment by 304NotModified** [comment]
added table for 1.
