### ISSUE TITLE
ObjectPath renders attribute with value even if value is empty

### ISSUE THREAD

**Issue by cristiz1992** [NLog/NLog#5311]
**NLog version**: (e.g. 4.4.13)
5.2.3

**Platform**: .Net 3.5 / .Net 4.0 / .Net 4.5 / Mono 4 / Xamarin Android / Xamarin iOS / .NET Core / .NET5 / .NET6
.NET6

**Current NLog config** (xml or C#, if relevant)

```xml
{
  "Logging": {
    "NLog": {
      "IncludeScopes": true
    }
  },
  "NLog": {
    "autoReload": false,
    "throwConfigExceptions": true,
    "extensions": [
      {
        "assembly": "NLog.Extensions.Logging"
      }
    ],
    "targets": {
      "async": false,
      "eventTarget": {
        "type": "Console",
        "layout": {
          "type": "JsonLayout",
          "includeEventProperties": true,
          "excludeEmptyProperties": true,
          "Attributes": [
            {
              "name": "exceptionData",
              "layout": "${object-path:${exception}:path=Data:format=@}",
              "encode": false
            }
          ]
        }
      }
    },
    "rules": {
      "0": {
        "logger": "LogDemoConsole.*",
        "minLevel": "Info",
        "writeTo": "eventTarget",
        "final": true
      }
    }
  }
}

```

This is the code triggering the behavior in C#
```
try
    {
        throw new ApplicationException("Something unfortunate occured")
        {
            Data =
            {
                ["employeeId"] = 32768
            }
        };
    }
    catch (Exception ex)
    {
        logger.LogError(ex, "Something something something darkside");
    }
```

- What is the current result?
When I'm NOT logging an exception it will render { "exceptionData": null }.
- What is the expected result?
I would expect the object to be empty { }. Basically I'm expecting NLog to exclude empty/null attributes in json.
I tried with ${exception:objectPath=Data:format=@} and it didn't display when no exception was logged, BUT when I use an exception the serialized value is NOT a valid json: { "exceptionData": "employeeId"=32768 }. I would expect the value to be { "exceptionData": { "employeeId": 32768 } }.
I also tried setting on the layout the property excludeEmptyProperties to true but it didn't have any effect.

**Comment by snakefoot** [comment]
Actually think it is a bug, since failing to lookup a property should cause it to render the value of the non-existing property.

Have created #5316 to resolve this.

Regarding `${exception:objectPath=Data:format=@}` and `${object-path:${exception}:path=Data:format=@}`, then there is a clash between both `${exception}` and `${object-path}` has a `Format`-option.

**Comment by snakefoot** [comment]
NLog v5.2.4 has been released - https://www.nuget.org/packages/NLog
