### ISSUE TITLE
Expose ConfigurationBuilder (for UserSecrets)

### ISSUE THREAD

**Issue by Edgaras91** [NLog/NLog#5320]
**NLog version**: 5.3.3 (Web)

**Platform**: .NET6

I am using appsettings.json to configure NLog.
I have a problem, where "UserSecrets" are not overwriting configs used by NLog. Let me know if this is possible already, otherwise, here is my suggestion.

The current ASP NET 6 NLog documentation suggests to initialise like this:

```
var logger = LogManager.Setup().LoadConfigurationFromAppSettings().GetCurrentClassLogger();
logger.Debug("init main");
```
However, this is what the method does:

```
            var builder = new ConfigurationBuilder()
                // Host Configuration
                .SetBasePath(currentBasePath)
                .AddEnvironmentVariables(prefix: "ASPNETCORE_")
                .AddEnvironmentVariables(prefix: "DOTNET_")
                // App Configuration
                .AddJsonFile("appsettings.json", optional, reloadOnChange)
                .AddJsonFile($"appsettings.{environment}.json", optional: true, reloadOnChange: reloadOnChange)
                .AddEnvironmentVariables();

            var config = builder.Build();
```

I would like to be able to use the above method and UserSecrets, by doing something like this:

`builder.AddUserSecrets<Program>()`

Are we able to expose this `ConfigurationBuilder` (`Action<ConfigurationBuilder>`) as a parameter to the above method? I would not like to clone the `LoadConfigurationFromAppSettings` method just to add my bit of code there.

**Comment by snakefoot** [comment]
The `LoadConfigurationFromAppSettings`-extension-method is very generic, and not at all optimal. It contains all kind of probing logic to guess where the user has hidden their NLog-configuration. But it is good enough for most users, that doesn't care much about such details.

If you actually know where you have stored the NLog-configuration, then I really recommend that you just copy the basic bits that you need from `LoadConfigurationFromAppSettings`, as you will get a more predictable experience.

Also if you only need logging to work within the host-builder, then I recommend to skip the `LoadConfigurationFromAppSettings`-extension-method, since it is only useful for logging before the HostBuilder is completed.

**Comment by Edgaras91** [comment]
Thank you for explaining the `LoadConfigurationFromAppSettings` and suggestions.
Could you provide an example, of how I could skip this extension? From the documented example, I only use "IHostBuilder.UseNLog()". Are you saying I don't need the `LogManager.Setup().LoadConfigurationFromAppSettings()` if I don't want to wrap host builder in try cache? And I don't need LogManager.Shutdown() in "finally" block?

All I really want is for NLog to read my host configurations, which already have ".AddEnvironmentVariables()" and more.

Sorry, I am a bit lost on how NLog is being configured.

If there is still value in LogManager.Shutdown() and try caching the host builder, I still think exposing an optional ConfigurationBuilder action would be a better approach for me, so a user doesn't need to dissect the documented method (the way I did) and let NLog maintain the environments and other stuff the extension does.

**Comment by snakefoot** [comment]
You could do this:
```csharp
        public static void Main(string[] args)
        {
            try
            {
                CreateHostBuilder(args).Build().Run();
            }
            finally
            {
                LogManager.Shutdown();
            }
        }

        public static IHostBuilder CreateHostBuilder(string[] args)
        {
            return Host.CreateDefaultBuilder(args)
                .ConfigureLogging((hostingContext, logging) =>
                {
                    logging.ClearProviders();
                })
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                })
                .UseNLog();
        }
```

**Comment by Edgaras91** [comment]
Thank you, that worked very well! 
Removing the static setup line, the `.UseNLog` was able to get my configurations including `.AddUserSecrets()`.

This is a better approach instead of me configuring `ConfigurationBuilder` in 2 places.

Wish I could still log the **catch** in try catch finally block, but I don't see how that would be possible.

**Comment by snakefoot** [comment]
If the exception occurs after having loaded NLog-configuration, then `LogManager.GetLogger` should work (I have updated the example code)

**Comment by Edgaras91** [comment]
Thank you. I tested that GetLogger will always return a logger and not null or throw an exception - even if an exception is thrown before the application is built. I am closing this ticket, as I am happy with the result.
