### ISSUE TITLE
Assembly Version the same for all major versions

### ISSUE THREAD

**Issue by deenairn** [NLog/NLog#5329]
Hi! Thanks for reporting this bug! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

**NLog version**: 5.0.0.0+

**Platform**: .Net 3.5 / .Net 4.0 / .Net 4.5

It appears that the NLog assemblies are stamped with an assembly version matching the major revision number (i.e. 4.0.0.0 or 5.0.0.0). I believe this could cause issues with assembly binding redirects.

See the image below for the latest v5.0.0.0 project.
<img width="650" alt="image" src="https://github.com/NLog/NLog/assets/3931242/2554c705-11b2-4f2c-ac22-8cfa88b911ca">

When looking at a .NET framework assembly binding redirects this has is logged as the following, not matter the version number.

      <dependentAssembly>
        <assemblyIdentity name="NLog" publicKeyToken="5120e14c03d0593c" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.0.0.0" newVersion="5.0.0.0" />
      </dependentAssembly>

I was expecting this to be 5.2.0.0. I don't believe this is the intended behaviour, and I am not certain if there were assemblies referencing multiple 5+ < 6 NLog assemblies what assembly binding redirects would be. I would be expecting this to be the following, and I think this could be achieved by using the `$(ProductVersion)` variable.

      <dependentAssembly>
        <assemblyIdentity name="NLog" publicKeyToken="5120e14c03d0593c" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.2.0.0" newVersion="5.2.0.0" />
      </dependentAssembly>

**Comment by snakefoot** [comment]
It is intentional that strong-version only changes on major-version-change. Believe there was incident caused by unexpected change of assembly-version:

https://nlog-project.org/2015/09/12/nlog-4-1-1-has-been-released.html

There are lots of pitfalls with strong-version-assemblies, but keeping the assembly-version static, seems to handle most of them. (As long one doesn't register NLog in the GAC).

**Comment by snakefoot** [comment]
Closing issue as answered due to inactivity.

**Comment by deenairn** [comment]
Sorry, I never got back to your original response. If it's the projects intention, then I've no problem with it, I don't have a specific problem I'm trying to solve. I just noticed this behaviour and didn't expect it after upgrading a package. TBH I hate these agent binding redirects in .NET Framework 😅
