### ISSUE TITLE
Custom layout renderer not working when using multiple versions of NLog simultaneously

### ISSUE THREAD

**Issue by tino1986** [NLog/NLog#536]
I've created a custom NLog extension, which makes use of **NLog 3.1**. It contains, amongst other things, a layout renderer "iis-sitename", for retrieving the site name of IIS websites.

I've added the extension to the NLog configuration file of a .NET web service.

    <extensions>
        <add assemblyFile="NLog.Extensions.dll"/>
    </extensions>

The web service can use the layout renderer from the extension just fine, as long as it also uses **NLog 3.1**. But when I upgrade NLog in the web service to **3.2**, I get an error.

> Layout Renderer cannot be found: 'iis-sitename'.

I'm assuming this has something to do with a version conflict, as only the NLog **version** has changed. The code in both the extension and the web service have remained unaltered.

Is there a way this can be resolved without upgrading the extension to NLog 3.2 and keep using 3.2 for the web service?

Note: I can't upgrade NLog in the extension to 3.2 (yet), because other applications/services which also make use of the extension, are currently still using NLog 3.1.

In short, how can set up an NLog extension DLL so it can be used by projects using either NLog 3.1 or 3.2?

> **Kim Christensen**: I'll have to look into that, especially when you get an error like that.

Is what I'm trying to do possible? Or should the NLog version in a project always be equal to the NLog version of my extension? Is there any way I can work around this?

> **Kim Christensen**: I'll have to look into what happens with different version of NLog and the extension. You can probably get around it most of the time by using assembly binding redirects,but the best scenario would be updating the extension.

Assembly binding redirection in the extension project or in all other projects using NLog?
I've tried this in the extension project, but it didn't work. Although I might have done something wrong, as I'm not too familiar with it. Is there a clear example somewhere on how to do this?
I can't use assembly binding redirection in my other 100+ projects. There's simply no time to implement it.

**Comment by 304NotModified** [comment]
Without special tricks, this isn't possible. Because the binary is in your `bin` folder, only one version can be there.

But this problem is also with ASP.Net MVC, when a base library uses another version. This is solved with `assemblyBinding` in your config, eg, if we would like to use ASP.Net MVC 3.0.0.1, but your base library uses 2.0:

```xml
<runtime>
  <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
    <dependentAssembly>
      <assemblyIdentity name="System.Web.Mvc" publicKeyToken="31bf3856ad364e35" />
      <bindingRedirect oldVersion="0.0.0.0-3.0.0.1" newVersion="3.0.0.1" />
    </dependentAssembly>
  </assemblyBinding>
</runtime>
```

So for NLog, you can try this: 
(Dunno the `publicKeyToken`)

```xml
<runtime>
  <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
    <dependentAssembly>
      <assemblyIdentity name="NLog" publicKeyToken="...." />
      <bindingRedirect oldVersion="0.0.0.0-3.3.0.0" newVersion="3.3.0.0" />
    </dependentAssembly>
  </assemblyBinding>
</runtime>

``` 
Please let us know if this works.

**Comment by tino1986** [comment]
After going over this again and again this will probably be my solution. The extension can keep using NLog 3.1 so all existing applications/services can keep using it without a change. When a project updates to NLog 3.2, it can make use of assembly binding redirection.
However, I assume I will be facing some issues when my extension needs an update to NLog 3.1+...

**Comment by 304NotModified** [comment]
It not clear to me. This binding redirection doesn't work?
You can so 'downgrade':
```   <bindingRedirect oldVersion="0.0.0.0-3.3.0.0" newVersion="3.2.0.0" />```

**Comment by tino1986** [comment]
The binding redirection works when using it in 1 of the 100+ projects. It doesn't work when **only** using it in the extension. Neither `<bindingRedirect oldVersion="0.0.0.0-3.2.0.0" newVersion="3.2.0.0" />` or `<bindingRedirect oldVersion="0.0.0.0-3.2.0.0" newVersion="3.1.0.0" />`.

**Comment by 304NotModified** [comment]
Well of course, this is needed in the calling project. I you have 100 projects, this should be in 100 projects. 

This is a really general .Net issue (not NLog) and can be solved in the following ways:
- Use the GAC, which support multiple versions
- Use the `assemblyBinding` in your config
- Just do versioning right; if your library breaks (some of) your applications, you should do better versioning.

**Comment by ilya-g** [comment]
@304NotModified ,
> Just do versioning right; if your library breaks (some of) your applications, you should do better versioning.

Because it's NLog library, who breaks the versioning, the last advice should be applied to ourselves :)
Maybe the `AssemblyVersion` of NLog should not be changed with every release, and only change it if there are some breaking changes?
To indicate release version the `AssemblyFileVersion` attribute can be used. Take Json.Net as an example. While its AssemblyFileVersion was incremented with every release AssemblyVersion remained the same for a long period. Here are assembly version attributes from the one of its 5.0.x releases.
````C#
AssemblyVersion("4.5.0.0")
AssemblyFileVersion("5.0.8.16617")
`````

**Comment by 304NotModified** [comment]
@ilya-g I have to admit that the `AssemblyVersion` and AssemblyFileVersion` is confusing me every time. 

I would be great if we could improve the versioning at NLog's site. 

So the `AssemblyVersion` should only be changed with a major release? for example, for every 3.x release it would be nice if it stays `AssemblyVersion("3.0.0.0")`? Of even  `AssemblyVersion("3")`?

reading now: https://stackoverflow.com/questions/64602/what-are-differences-between-assemblyversion-assemblyfileversion-and-assemblyin

**Comment by Xharze** [comment]
We could try a figure out how this can be done, well it is easy to do, but
what is the consequences? Apart from causing some confusion, when the
number stays the same, which can be handle easily.

**Comment by ilya-g** [comment]
I think some api comparison tool like [BitDiffer](http://www.bitwidgets.com/) should be used to compare public api changes between successive releases. Then based on this comparison result you can decide whether it is required to change the AssemblyVersion, and what version (AssemblyFileVersion) to give to the release, according to semantic versioning rules.

Also here is another question on stackoverflow with a great answer about what AssemblyVersion is needed for: http://stackoverflow.com/questions/3768261/best-practices-guidance-for-maintaining-assembly-version-numbers

**Comment by Xharze** [comment]
It sounds like a good idea, at least to try out when releasing the next
version, which will contain a lot of breaking changes, and then more
forward with the suggested method.
