### ISSUE TITLE
JsonLayout - Structured fields not logged if they end with a quote

### ISSUE THREAD

**Issue by andrewdonkin** [NLog/NLog#5364]
**NLog version**: 5.2.4

**Platform**: .Net Framework 4.7.2 and 4.8.

**Current NLog config**

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      internalLogLevel="Trace"
      internalLogFile="internal.txt">

  <targets>
    <target name="logconsole" xsi:type="Console" />
    <target xsi:type="File"
            name="jsonLog"
            fileName="json.log">
      <layout type="JsonLayout"
              IncludeAllProperties="true"
              ExcludeEmptyProperties="true"
              />
    </target>
  </targets>

  <rules>
    <logger name="*" minlevel="Info" writeTo="logconsole" />
    <logger name="json" writeTo="jsonLog"/>
  </rules>
</nlog>

```

**Source code**
```csharp
private static readonly Logger Logger = LogManager.GetCurrentClassLogger();
static readonly Logger jsonlog = LogManager.GetLogger("json");
static void Main() {
    try {
        Logger.Info("Hello world");
        var accessLogEventInfo = new LogEventInfo(LogLevel.Info, null, null);
        accessLogEventInfo.Properties["noquote"] = "No quote:";
        accessLogEventInfo.Properties["endquote"] = "I quote: \"";
        jsonlog.Log(accessLogEventInfo);
    }
    catch (Exception ex) {
        Logger.Error(ex, "Goodbye cruel world");
    }
}
```

- What is the current result?
`{ "noquote": "No quote:" }`
- What is the expected result?
`{ "noquote": "No quote:", "endquote": "I quote: \"" }`

- The workaround is to configure `ExcludeEmptyProperties="false"`.

- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?  Yes:  the two "internal.txt"s from runs with ExcludeEmptyProperties true and false are identical.

- This did not work in version 4, either.  I am not aware of a version where it did.

- Can you help us by writing an unit test?  I could, but have not yet.

I feel like I'm missing something obvious here, since it's unlikely I'm the first to strike this problem.  So if this is a misconfiguration rather than a bug, apols.

**Comment by Aragorn159** [comment]
Hi, I can look at it if I may.

**Comment by snakefoot** [comment]
@Aragorn159 You don't have to ask for permission to make an investigation.

Anyway it looks like the result is this:
```json
{{ "noquote": "No quote:", "endquote": "I quote: \""}
```
And then there is this validation, which make faulty decision:
```c#
            if (ExcludeEmptyProperties && (sb[sb.Length-1] == '"' && sb[sb.Length-2] == '"'))
            {
                sb.Length = initialLength;
            }
```

**Comment by snakefoot** [comment]
Created bug-fix #5365

**Comment by snakefoot** [comment]
Thank you for reporting this bug, and providing the wonderful details. Fix will be included in the next release of NLog.

**Comment by snakefoot** [comment]
NLog v5.2.5 has been released - https://www.nuget.org/packages/NLog/5.2.5#release-body-tab
