### ISSUE TITLE
ExceptionLayoutRendererTests.cs vs ExceptionTests.cs

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#537]
Hi @Xharze 
The folder `LayoutRenderers` under project 'NLog.UnitTests.netfx45' has a file 
`ExceptionLayoutRendererTests.cs` and `ExceptionTests.cs`

I think those file should be merged? (`ExceptionLayoutRendererTests.cs` is inconsistent named)

**Comment by Xharze** [comment]
Yes, these files should be merged to have consistent test names
