### ISSUE TITLE
AppVeyor: Automatic publishing of NuGet projects

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#539]
Maybe this is interesting? 

[AppVeyor: Automatic publishing of NuGet projects](http://www.appveyor.com/docs/nuget#auto-package)

**Comment by Xharze** [comment]
This is what I'm doing with most of the new repositories. It is a bit
harder to do with NLog core, but by splitting up stuff in logical bits,
hopefully it will be easy soon.

**Comment by 304NotModified** [comment]
:+1:
