### ISSUE TITLE
Why aren't nLog custom event properties rendering through an email target?

### ISSUE THREAD

**Issue by kishoregolla81** [NLog/NLog#5400]
When I write nLog events to a file or to the database target, the LongMessage field renders correctly. But when I write to email, I get an empty string where my long message should be. Any ideas why outputting properties would work in a database target but not work in an email target?

**Comment by kishoregolla81** [comment]
<target name="mail" 
              xsi:type="Mail"
              smtpServer="smtp.abc.com"
              smtpPort="25"
              html="true"
              addNewLines="true"
              encoding="UTF-8"
              priority="High"
              replaceNewlineWithBrTagInHtml="true"
              smtpUserName="user.name"
              smtpPassword="password"
              subject="Your report request number ${event-properties:ReportRequestId}"
              from="noreply@abc.com"
              to="{all-event-properties:format=[key]\=[ToEmail]:separator=,:includeCallerInformation=true"

**Comment by kishoregolla81** [comment]
How to send Custom value as TO email id to the target ?

**Comment by snakefoot** [comment]
The value assigned `to="{all-event-properties:format=[key]\=[ToEmail]:separator=,:includeCallerInformation=true"` is not a valid NLog Layout, so it will just be used as literal-text.

Can you provide an example of how you are calling the NLog Logger, and gives the custom value for use in the `to="..."` ?

See also: https://github.com/NLog/NLog/wiki/Context

See also: https://github.com/NLog/NLog/wiki/Layouts

**Comment by snakefoot** [comment]
Closing issue as answered, due to inactivity.
