### ISSUE TITLE
Target for Opensearch

### ISSUE THREAD

**Issue by Kundashree** [NLog/NLog#5403]
Hello,
Is there any Target Which supports AWS OpenSearch? 
Since OpenSearch is forked out of ElasticSearch, Does NLog.Targets.ElasticSearch supports OpenSearch?

NLog version: 4.4.12
Platform: ,Net Framework 4.8
Current NLog config: xml

See also: https://stackoverflow.com/questions/77451115/nlog-target-for-opensearch

**Comment by snakefoot** [comment]
Not that I'm aware of. Beside [NLog.Targets.OpenSearch](https://www.nuget.org/packages/NLog.Targets.OpenSearch)

**Comment by Kundashree** [comment]
Hello, 

When can we expect the official target for OpenSearch? 
The Nlog target mentioned above does not allow AWS IAM based authentication. Does the official target support role-based authentication in AWS?

Thanks for your response.
