### ISSUE TITLE
Auto reload of .nlog configuration file works only once.

### ISSUE THREAD

**Issue by aspi-dwtt** [NLog/NLog#5405]
**NLog version**: 5.2.5

**Platform**:  .NET6

**Current NLog config** XML
<?xml version="1.0" encoding="utf-8" ?>
<nlog
  xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  throwExceptions="true"
  internalLogFile="c:\Logs\internallog.txt" internalLogLevel="Debug">

	<variable name="logDirectory" value="C:/Logs/" />
	<variable name="logFileName" value="DxServerClientApi" />

	<targets>
		<target
		  xsi:type="ColoredConsole"
		  name="console"
		  detectConsoleAvailable ="true"
		  layout="${longdate}|${level:uppercase=true}|${logger}|${message}" />
	
		<target 
			xsi:type="File"
			name="file"
			layout="${longdate} ${pad:padding=-5:inner=${uppercase:${level}}} ${pad:padding=-8:inner=${uppercase:${logger}}} ${message}"
            fileName="${logDirectory}${logFileName}.log"
            keepFileOpen="true" />
		
	</targets>
	
	<rules>
		<logger name="DX_HNDLR" minlevel="Trace" writeTo="console,file" />
		<logger name="HIST_LOG" minlevel="Trace" writeTo="console,file" />
		<logger name="DXSERVER" minlevel="Trace" writeTo="console,file" />

		
	</rules>
</nlog>

- What is the current result?
After program start NLOG configuration is picked up as intended from"MyApplication.nlog" file.
First change to this file is also picked up correct.
All subsequent changes are NOT picked up anymore.

**Comment by snakefoot** [comment]
I cannot reproduce your issue. I'm using the following `NLog.config`:
```xml
<?xml version="1.0" encoding="utf-8"?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      internalLogToConsole="true"
      internalLogLevel="Debug"
      autoReload="true">
  <variable name="logDirectory" value="C:/Logs/" />
  <variable name="logFileName" value="DxServerClientApi" />

  <targets>
    <target
      xsi:type="ColoredConsole"
      name="console"
      detectConsoleAvailable ="true"
      layout="${longdate}|${level:uppercase=true}|${logger}|${message}" />

  </targets>

  <rules>
    <logger name="DX_HNDLR" minlevel="Trace" writeTo="console" />
    <logger name="HIST_LOG" minlevel="Trace" writeTo="console" />
    <logger name="DXSERVER" minlevel="Trace" writeTo="console" />

    <!-- logger name="*" minlevel="Trace" writeTo="console,file " / -->
  </rules>
</nlog>
```
And the NLog InternalLogger writes the following during startup:
```
2023-11-13 19:30:15.6134 Debug Watching file-filter 'NLog.config' in directory: C:\Users\snakefoot\source\repos\NLog.Extensions.Logging\Examples\NetCore2\ConsoleExample\bin\Debug\net6.0
```
And when I open the `NLog.config` in Notepad, then the following is printed every time I press "Save" (Tried 5 times in a row):
```
2023-11-13 19:30:59.1341 Info Configuration file change detected! Reloading in 1000ms...
2023-11-13 19:31:00.1478 Info Reloading configuration...
```

**Comment by snakefoot** [comment]
Closing issue as resolved, due to inactivity.
