### ISSUE TITLE
How to compile NLog NLog-5.2.2?

### ISSUE THREAD

**Issue by hkumar0520** [NLog/NLog#5411]
In our product we are using Nlog 2.0 version which is quite old and now we trying to upgrade it to Version NLog-5.2.2. but facing build issues. Can you please suggest/ share steps to follow if any ? to successfully build in Visual Studio 2015.

Followed steps: 
Step 1: Downloaded source from https://github.com/NLog/NLog/releases/tag/v5.2.2 
Step 2: Opened NLog.sln and started compiling locally but the build is failing with multiple compilation errors:

Can you please suggest/ share steps to follow if any ? to successfully build NLog.proj in locally .

Getting below errors(highling in red border)

<img width="960" alt="Screenshot (10051)" src="https://github.com/NLog/NLog/assets/53545303/ba72365d-181f-4cbd-821b-30ab3341651e">

<img width="295" alt="Screenshot (10052)" src="https://github.com/NLog/NLog/assets/53545303/017ad127-0228-4008-bb45-4a03a50621fe">

**Comment by snakefoot** [comment]
Yes NLog-project is built using VS2022 (Visual Studio Version 17) to ensure everything builds with supported NetCore-platform (NetCoreApp21 + NetCoreApp31 + Net5 are no longer supported)

I have now created #5412 for NLog v5.2.6, that attempts to make the NLog-source-code compatible with older versions of VisualStudio.

**Comment by snakefoot** [comment]
You are wellcome to test if the latest dev-source now is working: https://github.com/NLog/NLog/archive/refs/heads/dev.zip

**Comment by snakefoot** [comment]
Closing issue as resolved, due to inactivity.
