### ISSUE TITLE
Debug logs are attributed as Info on Android

### ISSUE THREAD

**Issue by taori** [NLog/NLog#5423]
Hi! Thanks for reporting this bug! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

**NLog version**: (e.g. 4.4.13)
5.2.5

**Platform**: .Net 3.5 / .Net 4.0 / .Net 4.5 / Mono 4 / Xamarin Android / Xamarin iOS / .NET Core / .NET5 / .NET6
MAUI/Xamarin.Android

**Current NLog config** (xml or C#, if relevant)

```xml
	<targets>
		<target xsi:type="Console" name="console" layout="${longdate} ${pad:padding=50:inner=${logger}} ${pad:padding=5:inner=${level}} ${message}" />
	</targets>
	<rules>

		<logger name="*" minlevel="Debug" writeTo="console" />
	</rules>

```

Screenshot:
![grafik](https://github.com/NLog/NLog/assets/5545184/2fc16f6b-6bf8-49e5-932a-738551227d9a)

- What is the current result?
Debug is attributed as Info on Android
- What is the expected result?
I would expect it to be Debug
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
No
- Please post full exception details (message, stacktrace, inner exceptions)
No exception. Just a mismatch depending on platform
- Are there any workarounds? yes/no
Not that i am aware of. I would imagine on android it just needs to call a different API
- Is there a version in which it did work? 
Not that i know
- Can you help us by writing an unit test?
Probably. But it's easiest to run a maui app with rider and look into logcat

**Comment by snakefoot** [comment]
Yes it is probably hard to decipher the LogLevel from the raw console-output, so everything just becomes "Info".

Maybe [NLog.Targets.MauiLog](https://github.com/NLog/NLog.Targets.MauiLog) can give what you need?

**Comment by taori** [comment]
I think you might be right. That implementation appears to be doing it right. I will give it a shot and close if it solves everything :) Thank you!

**Comment by taori** [comment]
I tried MauiLog previously. Something appears to be wrong with the subcomponent but i will address it in that repo. Thank you.
