### ISSUE TITLE
Target for Opensearch

### ISSUE THREAD

**Issue by Kundashree** [NLog/NLog#5424]
Hello,

When can we expect the NLog official target for OpenSearch?
The third party Nlog target (https://www.nuget.org/packages/NLog.Targets.OpenSearch) does not allow AWS IAM based authentication. Does the official target support role-based authentication in AWS?

Related issue: https://github.com/NLog/NLog/issues/5403

NLog version: 4.4.12
Platform: ,Net Framework 4.8
Current NLog config: xml

**Comment by snakefoot** [comment]
The main focus for the NLog-project is to maintain the NLog-library, and not creating target-extensions for 3rdParty-API.

But you are more than wellcome to start a git-repo, or maybe make pull-requests for the existing: https://github.com/TTYLeaf/NLog.Targets.OpenSearch

**Comment by snakefoot** [comment]
Closing issue as answered, due to inactivity.
