### ISSUE TITLE
SetCreationTimeUtc blocked and throwing exception on locked stream in TryCreateDirectoryFileStream

### ISSUE THREAD

**Issue by BooTeK** [NLog/NLog#5426]
**NLog version**: 5.2.6

**Platform**: .Net 4.8

**Current NLog config** (xml or C#, if relevant)

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      internalLogFile="C:\Logs\Nlog\interface.log.txt"
      autoReload="true">
  <variable name="logDirectory" value="C:\Logs\" />
  <variable name="archiveDirectory" value="${logDirectory}\Archives\Interface" />

  <targets async="true">
    <target name="fullrolling" xsi:type="File"
            layout="${longdate} - ${message}"
            fileName="${logDirectory}\log.txt"
            archiveFileName="${archiveDirectory}\{#}.log.txt"
            archiveEvery="Day" archiveNumbering="Date" archiveDateFormat="yyyyMMddHHmm" maxArchiveFiles="31"
            concurrentWrites="true" keepFileOpen="false" encoding="utf-8"
            header="${processname} - ${assembly-version}" />
  </targets>

  <rules>
    <logger name="*" writeTo="fullrolling" enabled="true" />
  </rules>
</nlog>

```
The new fixWindowsFileSystemTunneling behavior causes strange behaviour with our nlog configuration.

The problem seems to be cause in BaseFileAppender.cs in the new (in 5.2.6) method TryCreateDirectoryFileStream

`var fileStream = TryCreateFileStream(allowFileSharedWriting, overrideBufferSize);` line is called with allowFileSharedWriting set to false. this cause the finally clause to fail as the file is locked.

Theorizing on this it seems to cause issues when the file is archived on for example 23:59:59 all new log message (or at least a set of them every minute) are archived to a new file because the system thinks the creationdate is too old and should do a rollover (as it couldn't update it on the creation).

It seems .net core reimplementation is a little different and either doesn't have the locking issue and handles the internals differently as a similar project running in .net 8.0 didn't show this issue (yet) but the logging intensity is also a lot lower.

- What is the current result?
Archiving is borked and every minute files are archived.

- What is the expected result?
Archiving working as intended only archive one a day. No exception on the creation time update would probably solve the problem.

- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
Yes, because of a locked filestream the SetCreationTimeUtc can not be executed.

2023-11-28 11:41:55.7015 Debug FileTarget(Name=interface_wrapped): Failed to update File.SetCreationTimeUtc for FileName: C:\Logs\log.txt Exception: System.IO.IOException: The process cannot access the file 'C:\Logs\log.txt' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.IO.File.OpenFile(String path, FileAccess access, SafeFileHandle& handle)
   at System.IO.File.SetCreationTimeUtc(String path, DateTime creationTimeUtc)
   at NLog.Internal.FileAppenders.BaseFileAppender.TryCreateDirectoryFileStream(Boolean allowFileSharedWriting, Int32 overrideBufferSize)

- Are there any workarounds? yes/no
Deleting the log file and manually recreating it seems to (sometimes?) fix the issue when I was messing with the configuration. As it sets a new creation time this seems a plausible reason. I.e. the exception is no longer happening.

- Is there a version in which it did work? 
5.2.5 and earlier

**Comment by snakefoot** [comment]
Thank you for reporting this bug. Can see the implementation of `SetCreationTimeUtc` expects to open FileStream like this:
```c#
FileStream fs = new FileStream(path, FileMode.Open, FileAccess.Write, FileShare.ReadWrite, 1);
```
Which doesn't work together with NLog opening file like this:
```
FileShare fileShare = allowFileSharedWriting ? FileShare.ReadWrite : FileShare.Read;
```
Will try and make an unit-test that reproduces the issues, and then make the bug-fix.

**Comment by snakefoot** [comment]
Thank you again for providing this very detailed bug-report. 

NLog v5.2.7 has now been released - https://www.nuget.org/packages/NLog/5.2.7
