### ISSUE TITLE
Intended use of NLog

### ISSUE THREAD

**Issue by carsten-riedel** [NLog/NLog#5435]
### Intended use of NLog

"I'm currently using NLog in a console application and have set it up without using dependency injection, as shown in my code example. I've noticed that many examples and documentation focus on using NLog with dependency injection. My question is two-fold:

Is using NLog without dependency injection, as I have done, a supported and intended use case, especially in other project types like console applications , generic classes, visual studio extensions, source generators, analyzers etc... ?

How does NLog's functionality and integration differ across various project types, such as desktop applications, and windows services? (Where it not so typical to use dependency injection).  Are there specific considerations or best practices for using NLog in these different environments, particularly regarding the use or omission of dependency injection?"

**If they are all intended use cases, documentation for this use cases can and should be improved.**

```
using NLog;
using NLog.Config;
using NLog.Targets;

namespace ConsoleApp
{
    internal class Program
    {
        private static Logger logger = LogManager.GetCurrentClassLogger();

        private static readonly LogFactory _ = NLog.LogManager.Setup(SetupBuilder => {
            SetupBuilder.LoadConfiguration(LoadConfigurationBuilder => {
                LoadConfigurationBuilder.Configuration = new LoggingConfiguration();
                LoadConfigurationBuilder.Configuration.AddRuleForAllLevels(new ConsoleTarget() { Name = "Console" });
                LoadConfigurationBuilder.Configuration.AddRuleForAllLevels(new FileTarget()
                {
                    Name = "File",
                    ConcurrentWrites = true,
                    MaxArchiveFiles = 24,
                    FileName = "${processname}.log",
                    KeepFileOpen = true,
                    ArchiveFileName = "archive\\${processname}.{#}.log",
                    ArchiveNumbering = ArchiveNumberingMode.Date,
                    ArchiveEvery = FileArchivePeriod.Day,
                    ArchiveOldFileOnStartup = true,
                });
            });
        });

        private static void Main(string[] args)
        {
            Console.WriteLine("Hello, World!");
            logger.Info("Hello, World!");
        }
    }
}

```

**Comment by snakefoot** [comment]
Both use-cases are fully supported by NLog. One is encouraged to choose the one that suits you best:
- Use NLog Logger everywhere 
- Use Microsoft.Extensions.Logging-ILogger everywhere (Either with dependency injection with own singleton)

Here is a section from [NLog.Extensions.Logging](https://github.com/NLog/NLog.Extensions.Logging)-page:
> Notice the standard [NLog NuGet package](https://www.nuget.org/packages/NLog) is enough for using NLog Logger with simple console application on the .NET Core platform. Just add NLog.config file to the project, and follow the [tutorial](https://github.com/NLog/NLog/wiki/Tutorial#configure-nlog-targets-for-output) for using GetCurrentClassLogger().

Here is a section from [NLog.Extensions.Logging](https://github.com/NLog/NLog/wiki/Getting-started-with-.NET-Core-2---Console-application)-tutorial:
> Notice that NLog can be used on .NET Core without help from Microsoft Extension Logging and NLog.Extension.Hosting. See standard [NLog Tutorial](https://github.com/NLog/NLog/wiki/Tutorial).

Here is a section from [NLog GetCurrentClassLogger and Microsoft ILogger](https://github.com/NLog/NLog.Extensions.Logging/wiki/NLog-GetCurrentClassLogger-and-Microsoft-ILogger)-wiki-page:
> - Pros of using NLog directly
> - Pros of using NLog via Microsoft.Extensions.Logging:

**Comment by carsten-riedel** [comment]
Thx for the detailed answer.
