### ISSUE TITLE
ClamAV detecting NLog.dll as infected with Win.Packed.Msilheracles-10017861-0

### ISSUE THREAD

**Issue by schmidt-calvin** [NLog/NLog#5456]
Hi! Thanks for reporting this bug! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

**NLog version**: Seeing this in both versions 5.2.6 and 5.2.8

**Platform**:  .NET Core

**Current NLog config** (xml or C#, if relevant)

```
/var/lib/docker/overlay2/024ba70fe42c947aa6a614d025c586353ee4b1cd316a054375dd45fd9d423a49/merged/usr/src/app/compiled/NLog.dll: Win.Packed.Msilheracles-10017861-0 FOUND
```
Not sure if better to submit here or directly to ClamAV. I uploaded the NLog.dll to virustotal and it shows only ClamAV and Google as seeing an issue:
https://www.virustotal.com/gui/file/f8fdd998b9846c4a30894ff11f8dd934647f824bfb041efb9a7bc0943b6acd4c?nocache=1

**Comment by snakefoot** [comment]
I'm guessing it is false positive, but I'm not the owner of Google ClamAV.

See also: 

- https://www.reddit.com/r/radarr/comments/18v0ey2/clam_av_tripped_on_the_latest_linuxserverio/
- https://www.reddit.com/r/qnap/comments/18vk0j5/antivirus_false_positive/

**Comment by snakefoot** [comment]
Looks like issue has been resolved with latest release:

- https://lists.clamav.net/pipermail/clamav-virusdb/2024-January/008529.html

> Dropped Detection Signatures:
> - Win.Packed.Msilheracles-10017861-0

**Comment by snakefoot** [comment]
Closing issue as resolved
