### ISSUE TITLE
NLogViewer target

### ISSUE THREAD

**Issue by magnusdanielson** [NLog/NLog#5464]
Hi! Thanks for reporting this bug! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

**NLog version**: 5.2.8

**Platform**:  .NET Core

**Current NLog config** (xml or C#, if relevant)

```xml
<extensions>
    <add assembly="NLog.Web.AspNetCore"/>
  </extensions>
<target name="network" xsi:type="Network" address="udp4://localhost:9999" >
      <layout xsi:type="SimpleLayout" text="Hello ${threadid}|${threadname}|${message}|${exception:format=tostring}|${callsite}" />
    </target>

    <target name="sentinel" xsi:type="NLogViewer" address="udp4://localhost:9998" >
      <layout xsi:type="SimpleLayout" text="Hello ${threadid}|${threadname}|${message}|${exception:format=tostring}|${callsite}" />
    </target>
  <rules>
    <logger name="Microsoft.*" minlevel="Warning"  writeTo="console" />
    <logger name="AIPBot.*" minlevel="Trace" writeTo="network,console,sentinel" />
    <logger name="Infra.*" minlevel="Trace" writeTo="network,console,sentinel" />
    <logger name="Media.*" minlevel="Trace" writeTo="network,console,sentinel" />
  </rules>
```

```c#
this.log = NLogBuilder.ConfigureNLog(@"nlog.config").GetCurrentClassLogger();
```

- What is the current result?
When using Log2Console on the Network target I get the message with the layout starting with "Hello"
When using Sentinel on the NLogViewer target I just get the ${message} in the log.

The end goal is to use Sentinel because it has better filtering.

I have also tried but failed to:
-use Network target to Sentinel.
-use NLogViewer target to Log2Console.

- What is the expected result?
I want NLogViewer to also accept the <layout> configuration

- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
Yes, no errors or warnings or anything I can see help

- Please post full exception details (message, stacktrace, inner exceptions)
![image](https://github.com/NLog/NLog/assets/12081481/2134f681-998a-4b19-8a80-58be6c97fe6b)

Image above shows the green message in Log2Console from the Network target.
The blue message is from Sentinel from the NLogViewer.

- Are there any workarounds? yes/no
No
- Is there a version in which it did work? 
I don't know
- Can you help us by writing an unit test?

**Comment by snakefoot** [comment]
The [NLog NetworkTarget](https://github.com/NLog/NLog/wiki/Network-target) supports sending any raw payload over the network.

The  [NLog LogViewerTarget](https://github.com/NLog/NLog/wiki/NLogViewer-target) is a legacy NLog-target that will send non-standard Log4J-XML-payload over the network.

**Comment by magnusdanielson** [comment]
Cool. I will test that when the PR is approved.

I actually got below to work. Maybe not pure "NLog" style but it works.

```
[Layout("Log4JXmlEventLayoutEx")]
    public class Log4JXmlEventLayoutEx : Log4JXmlEventLayout
    {
        protected override void RenderFormattedMessage(LogEventInfo logEvent, StringBuilder target)
        {
            logEvent.Properties["threadid"] = System.Threading.Thread.CurrentThread.ManagedThreadId;
            logEvent.Properties["threadname"] = System.Threading.Thread.CurrentThread.Name; 
            var msg = SimpleLayout.Evaluate("YO ${threadid}|${threadname} " + logEvent.Message, logEvent);

            logEvent.Message = msg;
            var layou = new Log4JXmlEventLayout();
           
            layou.Render(logEvent, target);
        }

    }

    [Target("NLogViewerEx")]
    public class NLogViewerTargetEx : NLogViewerTarget
    {
        private readonly Log4JXmlEventLayoutEx layout = new Log4JXmlEventLayoutEx();
        public override Layout Layout 
        { 
            get 
            { 
                return layout; 
            } 
            set { } 
        }
    }
```

An then update the nlog.config to:

```
<extensions>
     <add assembly="your-assembly"/>
  </extensions>
<target name="sentinel" xsi:type="NLogViewerEx" ...
```

**Comment by snakefoot** [comment]
The idea is that the `LogEventInfo logEvent` should not be modifed by the Target-Write-method. Since the same LogEvent is given to all configured NLog-target.

**Comment by magnusdanielson** [comment]
Good catch. Learning new things everyday. I have just used the nlog.config options so far so a bit new to creating custom Layouts in c#. I will read the documentation.

**Comment by snakefoot** [comment]
[NLog.Extensions.Logging v5.3.1](https://www.nuget.org/packages/NLog) has been released, that support overriding the `FormattedMessage`-option for the NLogViewer-target.
