### ISSUE TITLE
How to override a configured rule?

### ISSUE THREAD

**Issue by sbeaudoin** [NLog/NLog#549]
Hi,

I configured NLog to write to the event log.  By default, the configuration says to log only messages of level Error and above.

But, for some messages, from the code, I want to override this rule and write explicitly to the event log.  Is there a way I can do this.

**Comment by 304NotModified** [comment]
Do like to configure this in the config or programmatically?

**Comment by sbeaudoin** [comment]
I want to override it programmatically from some messages only.











De : Julian
Envoyé : ‎mardi‎, ‎3‎ ‎février‎ ‎2015 ‎15‎:‎28
À : NLog/NLog
Cc : Steve Beaudoin





Do like to configure this in the config or programmatically?

**Comment by 304NotModified** [comment]
You can use the [When filter](https://github.com/NLog/NLog/wiki/When-filter) for this. 

In code:
```
LogManager.Configuration.LoggingRules[0].Filters.Add(...);
```

**Comment by sbeaudoin** [comment]
The problem is, adding a filter surely have a performance impact and this, for only one line who will be added maybe once a month.


I thought there was a method I could call to override the default only one time.


Thank you for your help.  I will wee what I can do.






Envoyé depuis Windows Mail





De : Julian
Envoyé : ‎vendredi‎, ‎6‎ ‎février‎ ‎2015 ‎14‎:‎56
À : NLog/NLog
Cc : Steve Beaudoin





You can use the When filter for this. 

In code:
LogManager.Configuration.LoggingRules[0].Filters.Add(...);

**Comment by ilya-g** [comment]
@sbeaudoin In this situation you'd better use separate Logger with a distinct name for such events. Then you can setup individual rules for this logger in configuration.

**Comment by sbeaudoin** [comment]
I’ll do that.  Thank you.






Envoyé depuis Windows Mail





De : ilya-g
Envoyé : ‎samedi‎, ‎7‎ ‎février‎ ‎2015 ‎11‎:‎24
À : NLog/NLog
Cc : Steve Beaudoin





@sbeaudoin In this situation you'd better use separate Logger with a distinct name for such events. Then you can setup individual rules for this logger in configuration.
