### ISSUE TITLE
File log are deleted when MaxArchiveFiles is less than total number of multiple targets

### ISSUE THREAD

**Issue by VladiRanchev** [NLog/NLog#5494]
**NLog version**: (e.g. 5.2.8)

**Platform**:  .Net 4.5 

**Current NLog config** (xml or C#, if relevant)
```c#
for( int i=0;i<120;i++)
{
            String Name = "[V"+i.ToString("000") + "]"
            Logger oLogger = LogManager.GetLogger(Name);
            NLog.Targets.FileTarget logfile = new NLog.Targets.FileTarget(Name) { FileName = "..\\SBC_Logs\\" + Name + ".csv" , KeepFileOpen = false};
            logfile.MaxArchiveFiles = 10;
            logfile.ArchiveOldFileOnStartup = true;

            var configuration = LogManager.Configuration;
            configuration.AddRuleForAllLevels(logfile, Name,true);
            LogManager.ReconfigExistingLoggers(); // Magic method
            //oLogger.Info("Test");
}
```
- What is the current result?
      Some of the created log files are deleted when new log is made for newly created logged
- What is the expected result?
     The current and last 10 archives for each file target are kept
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
Yes Nothing logged to observed behaviours
 - Please post full exception details (message, stacktrace, inner exceptions)
- Are there any workarounds? yes
  Increase MaxArchiveFiles  bigger than the number of created targets/rules
- Is there a version in which it did work? 
      No
- Can you help us by writing an unit test?
   Abstract Unit tests added in the description above

**Comment by snakefoot** [comment]
The dynamic archive cleanup turns all non-letters (ex. digits) into wildcard for cleanup.

If you change to [static archive-cleanup](https://github.com/NLog/NLog/wiki/File-target#dynamic-vs-static-archive-logic) then the cleanup-wildcard is less aggressive.

See also: https://github.com/NLog/NLog/wiki/FileTarget-Archive-Examples

**Comment by snakefoot** [comment]
Closing issue as resolved due to inactivity
