### ISSUE TITLE
Set license expression on packages

### ISSUE THREAD

**Issue by thompson-tomo** [NLog/NLog#5499]
### Summary
I wish for the nuget packages to have the licence expression property set correctly or atleast the url property.

### Details

The licence expression property should be set to the correct licence type (depending on the repo) as this will enable analysis of licences in use to occur in external tools & the license type will be shown in Nuget etc. Or alternatively the license url property.

### Impacted packages
- NLog.Schema
- NLog.ManualFlush
- NLog.Contrib.ActiveMQ

**Comment by snakefoot** [comment]
Pull-requests are always wellcome to improve [NLog.Schema](https://github.com/NLog/NLog/tree/dev/src/NuGet/NLog.Schema)-nuget-package.

The other nuget-packages should probably be marked as deprecated.
