### ISSUE TITLE
Add additional TFM to reduce dependencies

### ISSUE THREAD

**Issue by thompson-tomo** [NLog/NLog#5500]
### Is your feature request related to a problem? Please describe.
I want to minimise dependencies in my project by utilising framework dependencies wherever possible

### Describe the solution you'd like
Packages should not have any dependency which can be provided by the framework and if necessary additional frameworks should be added.

### Describe alternatives you've considered
Accept the additional dependency

### Additional context
n/a

### packages impacted
- NLog.WindowsRegistry

**Comment by snakefoot** [comment]
Pull-request are always wellcome. 

But it seems to be a crazy game to chase net6,net7,net8,net9 instead of just depending on netstandard2 :)

**Comment by thompson-tomo** [comment]
I am not a fan of chasing all TFM'S just interested in one's where there is a benefit ie new feature or a needed dependency gets included in the framework.

**Comment by thompson-tomo** [comment]
But yes I will submit or for it.

**Comment by snakefoot** [comment]
Well you cannot choose one TFM as they frequently expire, so it will become an ongoing chase to stay away from unsecure packages.

Suddenly one cannot use a nuget-package because it points to a TFM that is no longer installed on the docker-image.

**Comment by thompson-tomo** [comment]
I think you have missed my point, what I am proposing is to add an additional TFM ie net 5/6 to the mentioned projects so that there is less dependencies for that framework just like has been done for https://www.nuget.org/packages/NLog.Web.AspNetCore.

**Comment by snakefoot** [comment]
> just like has been done for https://www.nuget.org/packages/NLog.Web.AspNetCore.

My comments comes directly from my experience with maintaining NLog.Web.AspNetCore (And other NLog-projects). There Microsoft is forcing one to ride the NET-train (Ex. NET5 is now obsolete, NET7 becomes obsolete this summer. NET6 becomes obsolete this winter, etc.). Hopefully one day a NLog-maintainer will arrive that loves to tweak build-pipelines, but I have little interest besides keeping the work to a minimum.

For my own personal stuff then I only use one NET-target, and I can move when I feel like it. But when maintaining a shared-library, then suddenly one have to cater for a huge user-base. It is ofcourse interesting to learn the ups and downs of open-source-development for a widely used project. But it also a lot of baggage coming from keeping everyone happy, so they get their exaxt personal wishes.

**Comment by snakefoot** [comment]
Closing as work continues here: https://github.com/NLog/NLog.WindowsIdentity/pull/10
