### ISSUE TITLE
NetworkTarget with GELF fails when sending UDP message larger than MaxMessageSize

### ISSUE THREAD

**Issue by UseMuse** [NLog/NLog#5507]
Hello everyone, I have the same problem: when sending a large data packet via UDP, I receive truncated json as a result. I tried all combinations of settings from NetworkTarget Properties (https://nlog-project.org/documentation/v4.7.0/html/Properties_T_NLog_Targets_NetworkTarget.htm), but I still couldn’t find any suitable ones. With a smaller size, no problem

The logs show that the data is arriving, that is, the chunks are working, but they are not perceived as one whole, unlike the behavior when using https://github.com/infobip/NLog.Targets.Gelf

**NLog version**: 4.7.0 (but tested on the latest version), NLog.Web.AspNetCore - 4.9.1

**Platform**: .NET Core 3

**Current NLog config** (xml or C#, if relevant)

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog
	xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" >
	<extensions>
		<add assembly="NLog.Web.AspNetCore" />
	</extensions>
	<targets async="true">
		<target xsi:type="Network" name="gelfUdpRequestResponse" address="udp://ip:12201" onOverflow="Split" maxMessageSize="8192">
			<layout xsi:type="JsonLayout" includeEventProperties="true" suppressSpaces="false">
				<attribute name="version" layout="1.1" />
				<attribute name="host" layout="${event-properties:Host}"/>
				<attribute name="message" layout="${message}"/>
				<attribute name="lang" layout="dotnet" />
				<attribute name="facility" layout="${aspnet-environment}" />
				<attribute name="source" layout="${moduleNameForGelfSource}" />
				<attribute name="longdate" layout="${longdate}" />
				<attribute name="UserName" layout="${username}"/>
				<attribute name="levelText" layout="${level}"/>
				<attribute name="LoggerName" layout="requestResponseElk"/>
			</layout>
		</target>
	</targets>
	<rules>
		<logger name="requestResponseDbLog" minlevel="Info" writeTo="gelfUdpRequestResponse" />
	</rules>
</nlog>
```

- What is the current result?
trimmed json
- What is the expected result?
I expect the package to be sent successfully, even a large one
- Did you check the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
- 
without maxMessageSize
```
2024-04-12 19:35:03.3516 Trace AsyncWrapper(Name=gelfUdpRequestResponse): Throttled timer scheduled
2024-04-12 19:35:03.3652 Trace AsyncWrapper(Name=gelfUdpRequestResponse): Writing 1 events (Timer)
2024-04-12 19:35:03.3652 Trace NetworkTarget(Name=gelfUdpRequestResponse_wrapped): Sending to address: 'udp://ip:12201'
2024-04-12 19:35:03.3652 Trace NetworkTarget(Name=gelfUdpRequestResponse_wrapped): Sending { there was a lot of data here }
2024-04-12 19:35:03.3652 Trace NetworkTarget(Name=gelfUdpRequestResponse_wrapped): Sending chunk, position: 0, length: 21358
```
with maxMessageSize="8192"
```
2024-04-12 19:56:33.0795 Trace AsyncWrapper(Name=gelfUdpRequestResponse): Throttled timer scheduled
2024-04-12 19:56:33.0945 Trace AsyncWrapper(Name=gelfUdpRequestResponse): Writing 1 events (Timer)
2024-04-12 19:56:33.0945 Trace NetworkTarget(Name=gelfUdpRequestResponse_wrapped): Sending to address: 'udp://ip:12201'
2024-04-12 19:56:33.0945 Trace NetworkTarget(Name=gelfUdpRequestResponse_wrapped): Sending: {there was a lot of data here}
2024-04-12 19:56:33.0945 Trace NetworkTarget(Name=gelfUdpRequestResponse_wrapped): Sending chunk, position: 0, length: 21072
2024-04-12 19:56:33.0945 Trace NetworkTarget(Name=gelfUdpRequestResponse_wrapped): Sending chunk, position: 8192, length: 12880
2024-04-12 19:56:33.0945 Trace NetworkTarget(Name=gelfUdpRequestResponse_wrapped): Sending chunk, position: 16384, length: 4688
2024-04-12 19:56:33.0945 Trace NetworkTarget(Name=gelfUdpRequestResponse_wrapped): Sending chunk, position: 21072, length: 0
```

- Please post full exception details (message, stacktrace, inner exceptions)
- Are there any workarounds? yes/no
create a class derived from TargetWithLayout in order to implement your own udp Transport in it. As it is implemented in https://github.com/infobip/NLog.Targets.Gelf, sending a large amount of data via udp works fine there, but I would not like to have third-party dependencies, since I was able to successfully send via udp using what nlog has
- Is there a version in which it did work?
no
- Can you help us by writing an unit test?
I don't know how to write tests

**Comment by snakefoot** [comment]
Your observations are completely correct. The special GELF-chunking logic is not implement by the generic NLog NetworkTarget.

If you are lucky then maybe enabling GZip compression will solve your issue together with jumbo-packages (compressing everything into a single chunk). Alternative you have to implement your own custom NLog NetworkTarget that supports GELF-chunking-logic.

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" >
  <extensions>
    <add assembly="NLog.Layouts.GelfLayout" />
  </extensions>
  
  <targets async="true">
	<target xsi:type="Network" name="GelfUdp" address="udp://graylog:12201" layout="${gelf}" compress="GZip" compressMinBytes="1000" maxMessageSize="8150" />
  </targets>

  <rules>
    <logger name="*" minlevel="Debug" writeTo="GelfUdp" />
  </rules>
</nlog>
```
See also: https://github.com/farzadpanahi/NLog.GelfLayout?tab=readme-ov-file#sample-usage-with-nlog-network-target-and-udp

**Comment by UseMuse** [comment]
@snakefoot Thanks for the answer, I'm using logstash (not graylog), I tried your suggestion when I applied your extension, unfortunately it didn't work for me. I copied your project and implemented UdpTransport from NLog.Targets.Gelf into it, I would like to show this solution, maybe you will like it and you could make a separate branch and somehow develop this, I tested this solution locally and it works as I need, with a large udp packet

**Comment by snakefoot** [comment]
There is already very crowded under my umbrella, so not planning to take ownership of a dedicated GELF-network-target.

I'm always happy to give advice and recommendation. But I feel it is better that ownership is given to people that actually use and cares about the actual nuget-package.

**Comment by UseMuse** [comment]
@snakefoot I apologize, I misled you, I didn’t pay attention to the fact that the version should be >=5.0.0, this will fix the problem

> Your observations are completely correct. The special GELF-chunking logic is not implement by the generic NLog NetworkTarget.
> 
> If you are lucky then maybe enabling GZip compression will solve your issue together with jumbo-packages (compressing everything into a single chunk). Alternative you have to implement your own custom NLog NetworkTarget that supports GELF-chunking-logic.
> 
> ```
> <?xml version="1.0" encoding="utf-8" ?>
> <nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" >
>   <extensions>
>     <add assembly="NLog.Layouts.GelfLayout" />
>   </extensions>
>   
>   <targets async="true">
> 	<target xsi:type="Network" name="GelfUdp" address="udp://graylog:12201" layout="${gelf}" compress="GZip" compressMinBytes="1000" maxMessageSize="8150" />
>   </targets>
> 
>   <rules>
>     <logger name="*" minlevel="Debug" writeTo="GelfUdp" />
>   </rules>
> </nlog>
> ```
> 
> See also: https://github.com/farzadpanahi/NLog.GelfLayout?tab=readme-ov-file#sample-usage-with-nlog-network-target-and-udp

thank you

**Comment by snakefoot** [comment]
Happy that GZip compression was able to reduce the message-size, and allow GELF-packages to pass through without being truncated.

**Comment by UseMuse** [comment]
@snakefoot Why were these specific characteristics chosen? 
> compress="GZip" compressMinBytes="1000" maxMessageSize="8150"
and not for example
> compress="GZip" compressMinBytes="1000" maxMessageSize="8192"

**Comment by UseMuse** [comment]
@snakefoot the problem is that some udp do not reach as expected and lead to the problem:

2024-04-14T12:43:40,587][WARN ][logstash.inputs.gelf ][apps][gelf-udp] Gelfd failed to parse a message skipping {:exception=>#<Gelfd2::DecodeError: Failed to decode data: Unexpected end of ZLIB input stream>, :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/2.6.0/gems/gelfd2-0.4.1/lib/gelfd2/gzip_parser.rb:11 :in parse'", "/usr/share/logstash/vendor/bundle/jruby/2.6.0/gems/gelfd2-0.4.1/lib/gelfd2/parser.rb:12:in parse'", "/usr /share/logstash/vendor/bundle/jruby/2.6.0/gems/logstash-input-gelf-3.3.2/lib/logstash/inputs/gelf.rb:197:in udp_listener'", "/usr/share/ logstash/vendor/bundle/jruby/2.6.0/gems/logstash-input-gelf-3.3.2/lib/logstash/inputs/gelf.rb:79:in block in run'"]}

rare, but it does exist, I would be grateful for any opinion on this matter

**Comment by snakefoot** [comment]
I'm not an expert on UDP network traffic. I guess one is only required to specify `maxMessageSize="8150"` if going through a switch/router that has DontFragment enabled, but still allows Jumbo Frames enabled (And you are probably right that with mtu=9000, then `maxMessageSize="8900"` is probably better).

But if the switch/router doesn't have DontFragment enabled, then I guess one can just skip specifying the value (and just rely on the default value of `maxMessageSize="65.536"`)

**Comment by UseMuse** [comment]
@snakefoot 

> compress="GZip" maxMessageSize="8192"

leads to the same errors on udp, most likely I’ll just switch to tcp

**Comment by snakefoot** [comment]
Maybe just remove maxMessageSize, and rely on IP fragmentation.

But yes TCP is much more reliable

Sent from my Galaxy



-------- Original message --------
From: John Flow ***@***.***>
Date: 16/04/2024 10:40 (GMT+01:00)
To: NLog/NLog ***@***.***>
Cc: Rolf Kristensen ***@***.***>, Mention ***@***.***>
Subject: Re: [NLog/NLog] NetworkTarget udp does not deliver a large volume of packages and there is no way to influence this (Issue #5507)


@snakefoot<https://github.com/snakefoot>

compress="GZip" maxMessageSize="8192"

leads to the same errors on udp, most likely I’ll just switch to tcp

**Comment by snakefoot** [comment]
Created https://github.com/farzadpanahi/NLog.GelfLayout/pull/35 that tries to improve documentation about UDP.

**Comment by UseMuse** [comment]
It seems to work for me, errors are minimized to 0, when logging all Requests, all were processed
```
	<target xsi:type="Network" name="gelfUdpRequest" address="udp://ip:12201" compress="GZip" compressMinBytes="1000">
```

**Comment by snakefoot** [comment]
Excellent. Thank you for the feedback about IP-fragmentation working for large UDP-network-packets.

**Comment by snakefoot** [comment]
Closing issue as resolved due to inactivity.
