### ISSUE TITLE
Logging inside a TransactionScope

### ISSUE THREAD

**Issue by braddabug** [NLog/NLog#551]
I've got some code where I'm trying to write to a database log within a TransactionScope, then the transaction is being rolled back, which rolls back the write to the log.

On September 19, 2014, there was a commit that should have fixed that (https://github.com/NLog/NLog/commit/1c85dbd8c7bac7ab0194808f3e251967b1a7301a), but it wasn't included in the 3.2 release. Does anyone know why?

**Comment by 304NotModified** [comment]
it's indeed missing in [3.2.0](https://github.com/NLog/NLog/blob/v3.2.0.0/src/NLog/Targets/DatabaseTarget.cs), but it's in in the master. 

Dunno what happened.
