### ISSUE TITLE
.Net Compact framework 3.5

### ISSUE THREAD

**Issue by mandm-pt** [NLog/NLog#553]
Hi, 

I am trying to use the NLog library in my project made in .net compact framework 3.5 and I saw that the NLog supports this framework.
I downloaded all the code to my pc but I can't find the "NLog.netcf35.csproj" that is referenced in the "SampleExtensions.netcf35" project.
If I check the packages inside the nuget there's no dll compiled for CF and in NLog website, download binaries same thing.

Thanks

**Comment by YuLad** [comment]
As of version 3.0 NLog dropped support of the compact framework - [announcement](http://nlog-project.org/2014/06/02/nlog-3-0-is-released.html). You can download version 2.0 [from codeplex](https://nlog.codeplex.com/releases/view/32639), which is [compatible](http://nlog-project.org/nlog-2-0-release-notes#compatibility) with compact framework 2.0 & 3.5.

**Comment by 304NotModified** [comment]
OK, so this is wrong on the website... :( 

Will fix that

**Comment by 304NotModified** [comment]
@Xharze is Mono still supported?

**Comment by mandm-pt** [comment]
Ok thanks.

**Comment by Xharze** [comment]
@304NotModified Mono is not supported official, meaning the build server never has builded or run unit tests for mono. But it is in the works.

**Comment by 304NotModified** [comment]
removed claim about .Net compact, Mono is still there
https://github.com/NLog/NLog.github.io/commit/16d13d29ba279d257bd54f7ca57f7e06018da4c7

**Comment by 304NotModified** [comment]
https://appveyor.uservoice.com/forums/188052-general/suggestions/6095313-add-support-for-mono-builds

**Comment by michelverhagen** [comment]
Hi, I'm looking for NLog 2.0, I need it with .NET CF on an old project. The website https://archive.codeplex.com/?p=nlog offers a download of the github archive, but this does not contain source code or a release of NLog 2.0. In fact, Chrome doesn't let you download the 248 MB zip because it deems it dangerous, and Edge happily downloads it but it does not contain the correct files.

Does anybody know where to download or get NLog 2.0?

**Comment by 304NotModified** [comment]
https://www.nuget.org/packages/NLog/2.0.0.2000

![image](https://user-images.githubusercontent.com/5808377/39581736-8b8905a2-4eec-11e8-94e2-55e490d3c4dd.png)

**Comment by michelverhagen** [comment]
Thanks!
