### ISSUE TITLE
Layout.FromMethod that supports typed Layout

### ISSUE THREAD

**Issue by snakefoot** [NLog/NLog#5532]
Implement helper to return type `Layout<T>`

```c#
public static Layout<T> FromMethod<T>(Func<LogEventInfo, T> layoutMethod, LayoutRenderOptions options = LayoutRenderOptions.None)
{
   ...
}
```

**Comment by smnsht** [comment]
@snakefoot 
Am I understanding correctly?

  * A helper method should be added to the typed layout class `Layout<T>`

   * The returned layout object should *not* be a fixed layout

   * The signature **Func<LogEventInfo, T> layoutMethod** is the right one. There is no intention to mask the existing method of Layout (untyped) with the signature **Func<LogEventInfo, object> layoutMethod**
`

**Comment by snakefoot** [comment]
The idea with `Layout<T>` is to provide exact type, instead of having to guess/cast/convert the returned value.

The final goal should be that when using `Layout<T>.FromMethod` then no boxing will occur. Thus the `Func`-method should return the exact type (and not `object`).

Ofcourse in the initial versions then I guess it is okay with some boxing, as it require quite an effort in changing `Layout<T>` to handle 2 implementation for how to render values (Either from Layout-string-value or from Func-method) while supporting its current API-methods.

**Comment by smnsht** [comment]
@snakefoot 
Well, if restrictions are not very tight, I think I have got something that looks like an "initial version" - please see  the draft.

It looks very simple, too good to be true, I think.

How does it look?
