### ISSUE TITLE
Reactivate NLog-Development group

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#554]
Reactivate NLog-Development group and allow reading for the public. As discussed at #477

**Comment by Xharze** [comment]
I'm not administrator of the group so I can't open it up. I could talk with Jarek which should be administrator, but maybe it isn't worth it.
Maybe we should just take the discussions here as @304NotModified originally suggested?

**Comment by 304NotModified** [comment]
Discussion over here is fine.  We need to discuss about accepting PR's, answering questions, releases and roadmaps
