### ISSUE TITLE
usage of finalMinLevel does not give me expected log level filtering

### ISSUE THREAD

**Issue by shvez** [NLog/NLog#5545]
NLog version: 5.3.2
Platform .net 4.7.2

@snakefoot you invited me to add issue if I have something and found something that bothering me. 

I have next set of rules in nlog.config:

```
1)    <logger name="*" finalMinLevel="Warn" />
    
3)    <logger name="Company.SubSystem.Class" finalMinLevel="Warn" />
4)    <logger name="Company.SubSystem" finalMinLevel="Info" />
    
5)    <logger name="*" writeTo="logfile" />
    
6)    <logger name="*" minLevel="Warn" writeTo="logconsole" />
```
I get that despite fact that I use finalMinLevel for rule 3) rule 4) overrides its logging level and I get `Info` level logs for Company.SubSystem.Class in 'logfile' target although I would expect it to be Warn because of finalMinLevel

I thought that order matters in this case but NO. if I place 3) after 4) it still works the same way and I see in nlog-error.log that Info is allowed for `Company.SubSystem.Class`
the information about what level is active for class I took from internal log

I understand that I could change rule 3) to something like:
`<logger name="Company.SubSystem.Class" finalMinLevel="Warn" writeto="logfile" final="true" />` but that is too much typing.  

We are transiting from log4net configs. As you know they have quite simple and flexible logic to define log levels. You start from 'root' and later you can specify levels and targets(appenders) for any sub-namespace and sub-classes. and you set some level for sub-system than it is not overridden by more broad setting. I mean if you set level for Company.SubSystem.Class then setting level for 'Company.SubSystem' will not override it.

I'm asking for this because later I'll need to explain all this to our devops team, so that they also understand what they have to do 

Update:
I realized that is very good idea to provide ready to use config. here it is:
```
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      internalLogFile="nlog-error-log.log" internalLogLevel="debug"
      autoReload="true"
      >

  <targets>
    <target name="logconsole" xsi:type="Console" />

    <target name="logfile" xsi:type="File" fileName="${baseDir}/log.log"
            layout="${longdate} ${level} ${logger} - ${message}${exception:format=ToString} AppId:${event-properties:AppId}/${event-properties:AppVer},ClientVer:${event-properties:ClientVer},SdkId=${event-properties:SdkId}, ProtocolType=${event-properties:ProtocolType},NetworkType=${event-properties:NetworkType},PeerType=${event-properties:PeerType}"
            archiveAboveSize = "20000000"
            maxArchiveFiles = "20"
            archiveNumbering = "Rolling"
    />

  </targets>

  <rules>
    <logger name="*" finalMinLevel="Warn" />
    
    <logger name="Company.SubSystem.Class" finalMinLevel="Warn" />
    <logger name="Company.SubSystem*" finalMinLevel="Info" />
    
    <logger name="*" writeTo="logfile" />
    
    <logger name="*" minLevel="Warn" writeTo="logconsole" />

  </rules>
</nlog>
```

I can also add simple console application.

I sort of understand that it might be that there is no way out of this issue. it is by design.

As an proposal I would say that library could have beside 'logger' rules different key word that defines rules in a way more closer to what log4net does

best,
ilya

**Comment by shvez** [comment]
I tried next workaround and it does not work too.
here is config
```
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      internalLogFile="nlog-error-log.log" internalLogLevel="debug"
      autoReload="true"
      >

  <targets>
    <target name="logconsole" xsi:type="Console" />

    <target name="logfile" xsi:type="File" fileName="${baseDir}/log.log"
            layout="${longdate} ${level} ${logger} - ${message}${exception:format=ToString} AppId:${event-properties:AppId}/${event-properties:AppVer},ClientVer:${event-properties:ClientVer},SdkId=${event-properties:SdkId}, ProtocolType=${event-properties:ProtocolType},NetworkType=${event-properties:NetworkType},PeerType=${event-properties:PeerType}"
            archiveAboveSize = "20000000"
            maxArchiveFiles = "20"
            archiveNumbering = "Rolling"
    />

  </targets>

  <rules>
    <logger name="*" finalMinLevel="Warn" />
    
    <logger name="Company.SubSystem.Class" finalMinLevel="Warn" writeTo="logfile" final="true"/>
    <logger name="Company.SubSystem*" finalMinLevel="Info" />
    
    <logger name="*" writeTo="logfile" />
    
    <logger name="*" minLevel="Warn" writeTo="logconsole" />

  </rules>
</nlog>
```

here is line with change:
```
    <logger name="Company.SubSystem.Class" finalMinLevel="Warn" writeTo="logfile" final="true"/>
```

even marking rule as 'final' does not filter out 'Info' messages for Company.SubSystem.Class. 
That is nasty

**Comment by snakefoot** [comment]
I have the following code:
```
            var subSystem = LogManager.GetLogger("Company.SubSystem");
            subSystem.Info("Info Company.SubSystem");
            subSystem.Warn("Warn Company.SubSystem");
            var subSystemClass = LogManager.GetLogger("Company.SubSystem.Class");
            subSystemClass.Info("Info Company.SubSystem.Class");
            subSystemClass.Warn("Warn Company.SubSystem.Class");
```

**Initial configuration**
Where `"Company.SubSystem*"` is last so overrides so everything becomes `finalMinLevel="Info"`:
```
    <logger name="*" finalMinLevel="Warn" />
    <logger name="Company.SubSystem.Class" finalMinLevel="Warn" />
    <logger name="Company.SubSystem*" finalMinLevel="Info" />
    <logger name="*" writeTo="logfile" />
    <logger name="*" minLevel="Warn" writeTo="logconsole" />
```
Gives me this in console (because of `minLevel="Warn"`):
```
2024/07/13 08:03:42.392|WARN|Warn Company.SubSystem |Company.SubSystem|
2024/07/13 08:03:42.392|WARN|Warn Company.SubSystem.Class |Company.SubSystem.Class|
```
And this in logfile (Includes both INFO-events):
```
2024/07/13 08:03:42.363|INFO|Info Company.SubSystem |Company.SubSystem|
2024/07/13 08:03:42.392|WARN|Warn Company.SubSystem |Company.SubSystem|
2024/07/13 08:03:42.392|INFO|Info Company.SubSystem.Class |Company.SubSystem.Class|
2024/07/13 08:03:42.392|WARN|Warn Company.SubSystem.Class |Company.SubSystem.Class|
```

**Moving Company.SubSystem.Class down **
Where `"Company.SubSystem.Class"` now overrides correctly (because last) so becomes `finalMinLevel="Warn"`:
```
    <logger name="*" finalMinLevel="Warn" />
    <logger name="Company.SubSystem*" finalMinLevel="Info" />
    <logger name="Company.SubSystem.Class" finalMinLevel="Warn" />
    <logger name="*" writeTo="logfile" />
    <logger name="*" minLevel="Warn" writeTo="logconsole" />
```
Gives me this in console:
```
2024/07/13 08:07:34.845|WARN|Warn Company.SubSystem |Company.SubSystem|
2024/07/13 08:07:34.864|WARN|Warn Company.SubSystem.Class |Company.SubSystem.Class|
```
And this in logfile (Not showing INFO from `Company.SubSystem.Class`):
```
2024/07/13 08:07:34.750|INFO|Info Company.SubSystem |Company.SubSystem|
2024/07/13 08:07:34.845|WARN|Warn Company.SubSystem |Company.SubSystem|
2024/07/13 08:07:34.864|WARN|Warn Company.SubSystem.Class |Company.SubSystem.Class|
```

If you are looking the internal-logger output for the console, then you will see this:
```
2024-07-13 08:12:14.5627 Debug logNamePattern: (:All) levels: [ Trace Debug Info ] writeTo: [ ] finalMinLevel: Warn
2024-07-13 08:12:14.5627 Debug logNamePattern: (Company.SubSystem:StartsWith) levels: [ Trace Debug ] writeTo: [ ] finalMinLevel: Info
2024-07-13 08:12:14.5627 Debug logNamePattern: (Company.SubSystem.Class:Equals) levels: [ Trace Debug Info ] writeTo: [ ] finalMinLevel: Warn
2024-07-13 08:12:14.5627 Debug logNamePattern: (:All) levels: [ Trace Debug Info Warn Error Fatal ] writeTo: [ logfile ]
2024-07-13 08:12:14.5627 Debug logNamePattern: (:All) levels: [ Warn Error Fatal ] writeTo: [ logconsole ]
```
- `logNamePattern: (:All) levels: [ Trace Debug Info ] writeTo: [ ] finalMinLevel: Warn`
   - Means that `Trace Debug Info` stops here (final) and will not reach any target, hence empty `writeTo: [ ]`
- `logNamePattern: (Company.SubSystem:StartsWith) levels: [ Trace Debug ] writeTo: [ ] finalMinLevel: Info`
   - Means that `Trace Debug` stops here (final) and will not reach any target, hence empty `writeTo: [ ]`
- `logNamePattern: (Company.SubSystem.Class:Equals) levels: [ Trace Debug Info ] writeTo: [ ] finalMinLevel: Warn`
   - Means that `Trace Debug Info` stops here (final) and will not reach any target, hence empty `writeTo: [ ]`
- `logNamePattern: (:All) levels: [ Trace Debug Info Warn Error Fatal ] writeTo: [ logfile ]`
   - Means that ` Trace Debug Info Warn Error Fatal` will reach `writeTo: [ logfile ]`
- `logNamePattern: (:All) levels: [ Warn Error Fatal ] writeTo: [ logconsole ]`
   - Means that ` Warn Error Fatal` will reach `writeTo: [ logconsole ]`

The NLog InternalLogger also shows the indiviaul Logger-outputs. Where `Company.SubSystem.Class` has no Info-output:
```
2024-07-13 08:12:14.6280 Debug Targets configured when LogLevel >= Warn for Logger: ConsoleExample.Program
2024-07-13 08:12:14.6280 Debug Logger ConsoleExample.Program [Warn] => logfile logconsole
2024-07-13 08:12:14.6280 Debug Logger ConsoleExample.Program [Error] => logfile logconsole
2024-07-13 08:12:14.6280 Debug Logger ConsoleExample.Program [Fatal] => logfile logconsole

2024-07-13 08:12:14.6404 Debug Targets configured when LogLevel >= Info for Logger: Company.SubSystem
2024-07-13 08:12:14.6404 Debug Logger Company.SubSystem [Info] => logfile
2024-07-13 08:12:14.6404 Debug Logger Company.SubSystem [Warn] => logfile logconsole
2024-07-13 08:12:14.6404 Debug Logger Company.SubSystem [Error] => logfile logconsole
2024-07-13 08:12:14.6404 Debug Logger Company.SubSystem [Fatal] => logfile logconsole

2024-07-13 08:12:14.6885 Debug Targets configured when LogLevel >= Warn for Logger: Company.SubSystem.Class
2024-07-13 08:12:14.6885 Debug Logger Company.SubSystem.Class [Warn] => logfile logconsole
2024-07-13 08:12:14.6885 Debug Logger Company.SubSystem.Class [Error] => logfile logconsole
2024-07-13 08:12:14.6885 Debug Logger Company.SubSystem.Class [Fatal] => logfile logconsole
```

**Comment by shvez** [comment]
@snakefoot sorry. I got it now working as expected if 'class' rule is moved after 'subsystem' rule. Not sure why it was not working correctly before.

I was thinking about my proposal for different key word for rules that act similar (not exactly) to what log4net does. and realized that this can be just flag for 'rules' section. this flag is default to what we have now. 

Why I'm talking about this because in our practice we had quite big log4net configuration and I say that under stress some rules were added twice in two different places of the file. In log4net it is not so critical because order does not matter, but for nlog this kind of errors might lead to wrong logging.

well, anyway it is up to you. it is difficult to say how important this feature might be

**Comment by snakefoot** [comment]
Happy that the `finalMinLevel` is working as expected.

Think you need to be more precise of what you are looking for, maybe with some examples. I'm not an expert on log4net, and how you are using it.

**Comment by shvez** [comment]
here is typical log4net.config with my comments
```
<?xml version="1.0" encoding="utf-8" ?>
<log4net debug="false">

  <!-- "normal" log file appender(target) --> 
  <appender name="LogFileAppender" type="log4net.Appender.RollingFileAppender">
    <file type="log4net.Util.PatternString" value="logFile.log" />
    <param name="AppendToFile" value="true" />
    <param name="MaxSizeRollBackups" value="50" />
    <param name="MaximumFileSize" value="20MB" />
    <param name="RollingStyle" value="Size" />
    <param name="PreserveLogFileNameExtension" value="true" />
    <param name="LockingModel" type="log4net.Appender.FileAppender+MinimalLock" />
    <layout type="log4net.Layout.PatternLayout">
      <param name="ConversionPattern" value="%d [%t] %-5p %c - %m %n" />
    </layout>
    
  </appender>


  <!-- "OperationLogAppender" log file appender -->
  <appender name="OperationLogAppender" type="log4net.Appender.RollingFileAppender">
    <file type="log4net.Util.PatternString" value="SpecailClass.log" />
    <param name="AppendToFile" value="true" />
    <param name="MaxSizeRollBackups" value="1" />
    <param name="MaximumFileSize" value="100MB" />
    <param name="RollingStyle" value="Size" />
    <param name="PreserveLogFileNameExtension" value="true" />
    <param name="LockingModel" type="log4net.Appender.FileAppender+MinimalLock" />
    <layout type="log4net.Layout.PatternLayout">
      <param name="ConversionPattern" value="%d [%t] %-5p %c [%x] - %m%n" />
    </layout>
  </appender>
  
 

  <!-- logger -->
  <!-- this part is about logging rules -->
  <!-- here we set default behaviour -->
  <!-- all loggers will by defult write to file (LogFileAppender) with LogLevel='Info' -->
  
  <root> 
    <level value="INFO" />
    <appender-ref ref="LogFileAppender" />
  </root>

  <!-- here we setup that 'SpecialClass will be logged to differet appender (target) by setting additivity=false -->
  <!-- if we would not set it it would log to both LogFileAppender and OperationLogAppender -->
  <logger name="SpecialClass" additivity="false">
    <level value="INFO" />
    <appender-ref ref="OperationLogAppender" />
  </logger>


  <!-- here we see that all loggers except Class1 logger will log WARN messages only -->
  <!-- Class1 and all under it (Class1.Subclass) will log info -->
  <logger name="Company.SubSystem">
    <level value="WARN" />
  </logger>

  <logger name="Company.SubSystem.Class1">
    <level value="INFO" />
  </logger>

<!-- we have more entries like this -->
  <logger name="Company.SubSystem2">
    <level value="INFO" />
  </logger>

  <logger name="Company.SubSystem2.Class">
    <level value="INFO" />
  </logger>

</log4net>
```

You might notice that we repeat the INFO level when it doesn't really make sense. For example, the two last loggers. This approach makes sense for us because it allows us to quickly activate Debug logging for "Company.SubSystem2" even if the "Company.SubSystem2.Class" still has the INFO level.

We have some templates in the log4net.config file that help us quickly activate debug logging for specific parts of our system, while also ensuring that the most noisy parts are turned off.

The main idea behind the log4net config, as I see it, is to set the default configuration at the beginning and then fine-tune it. More specific tuning overrides the more general settings.

While I was writing this answer, I realized that with NLog, we can achieve a similar result in two ways:

1. The first method is similar to what we did here using loggers.
2. We could also use the <when> filter in the "Company.SybSystem" logger rule.

Which approach do you think is better?

**Comment by snakefoot** [comment]
Not sure if `additivity="false"` will work well with NLog LoggingRules top-to-bottom evaluation. Already think `finalMinLevel` is already bending the NLog Logging Rules with its ability to override previous rules.

Before NLog v5 and `finalMinLevel`, then one would insert `final`-logging-rules at the top like this:
```xml
<logger name="SpecialClass" minLevel="Debug" writeTo="LogFileAppender" /> <!-- Specific target for the logger -->
<logger name="SpecialClass" maxLevel="Fatal" final="true" />  <!-- Blackhole for the logge -->
```

Notice that you can use NLog Config Variables for [semi-dynamic configuration](https://github.com/NLog/NLog/wiki/Filtering-log-messages#semi-dynamic-routing-rules) of NLog LoggingRules LogLevels.

If performance is important to you, then `<filters>` should be avoided, so I recommend depending on the NLog LoggingRules Level-routing.

**Comment by shvez** [comment]
I do not say that we need to use `additivity` flag as in log4net. It was just sample how it is done in log4net config.
I thought rather about flag for <rules> section that might change how rules are merged. Currently more generic rule that was found last will overwrite everything what was before, I think about changing this to opposite using such flag. That is it. Not sure if that is really possible. 

>Before NLog v5 and finalMinLevel, then one would insert final-logging-rules at the top like this:

this looks terrible :). good that you fixed it.

**Comment by snakefoot** [comment]
> Currently more generic rule that was found last will overwrite everything what was before, I think about changing this to opposite using such flag. That is it. Not sure if that is really possible.

So having a strict-mode on the `<rules>`-section so it is not possible to make overrides that matches using a more generic-wildcard?

**Comment by shvez** [comment]
yeah, it looks close to what I proposed

**Comment by snakefoot** [comment]
Well I guess if someone can find an elegant way of deciding if one logging-rule is less generic than the other, together with supporting dynamic-filtering, then pull-request are wellcome.

**Comment by snakefoot** [comment]
Closing issue as resolved, due to inactivity.
