### ISSUE TITLE
Buffered Email Not Buffering

### ISSUE THREAD

**Issue by AdamDunn** [NLog/NLog#557]
Hoping I could get some experts to look over my config file, as it doesn't seem to be working the way I was expecting. I'm using NLog 3.2.0 (the latest on NuGet) on an ASP.NET 3.5 website. I've got a mail target wrapped inside a BufferingWrapper, and was hoping it would take multiple NLog messages and put them into a single email (within the flushTimeout window). Instead I'm getting many emails with a single NLog line in each one (the NLog timestamp will be within a few hundred milliseconds among 20-30 emails). Are my expectations wrong, or is there something wrong with my config? I don't have any Flush() calls in my code. Are they necessary like in issue #171 ?

My NLog.config:
```xml
<targets async="true">
	<target xsi:type="BufferingWrapper" name="bufferedexchange" bufferSize="100" flushTimeout="5000">
		<target xsi:type="FallbackGroup" name="exchangefallback" returnToFirstOnSuccess="true">
			<target xsi:type="Mail" name="exchange"
				  smtpUserName="nlog@company.com"
				  smtpPassword="MyP@ssword"
				  smtpServer="smtp.company.com"
				  smtpPort="25"
				  smtpAuthentication="Basic"
				  enableSsl="true"
				  from="nlog@company.com"
				  to="developer@company.com"
				  subject="NLog Message"
				  body="${longdate} ${uppercase:${level}} ${message} ${newline}"
			/>
			<target xsi:type="Mail" name="exchange"
				  smtpUserName="nlog@company.com"
				  smtpPassword="MyP@ssword"
				  smtpServer="smtp2.company.com"
				  smtpPort="25"
				  smtpAuthentication="Basic"
				  enableSsl="true"
				  from="nlog@company.com"
				  to="developer@company.com"
				  subject="NLog Message (using smtp2)"
				  body="${longdate} ${uppercase:${level}} ${message} ${newline}"
			/>
		</target>
	</target>
</targets>

<rules>
	<logger name="*" minlevel="Warn" writeTo="bufferedexchange" />
</rules>
```

Thanks for your eyeballs.

**Comment by Xharze** [comment]
The buffering target doesn't combine logs, it just buffers them and flushes them at specified intervals or size. There is currently no way to achieve what you what, without creating a custom target.

**Comment by 304NotModified** [comment]
I have to mention that the docs are  confusing bout this:

https://github.com/nlog/nlog/wiki/Targets
>BufferingWrapper - A target that buffers log events and sends them in batches to the wrapped target. Useful in combination with Mail target.

**Comment by snakefoot** [comment]
@dyardyGIT Please create new issue for your questions. But the reason why it is not working here is because FallbackGroup is used. BufferingWrapper writing directly to Mail will work.
