### ISSUE TITLE
File Target new options not available

### ISSUE THREAD

**Issue by olcayseker** [NLog/NLog#558]
Newly introduced beauties for file target ArchiveNumberMode  and archiveOldFileOnStartup options are
 not available with 3.2.  Need to check this release i think.
Ref. http://nlog-project.org/2015/01/12/nlog-3-2-0-is-released.html

![capture](https://cloud.githubusercontent.com/assets/776387/6056838/4229283c-ad1f-11e4-924d-613deb63379c.PNG)

**Comment by Xharze** [comment]
What unit tests are you running? One included in NLog? Could you provide a sample project?

**Comment by olcayseker** [comment]
The unit test is just for trying new file target options which is written on "http://nlog-project.org/2015/01/12/nlog-3-2-0-is-released.html". It turns out that a typo and archiveNumberMode='DateAndSequence' must be archiveNumbering='DateAndSequence'.
Sample project already included for refrence here https://github.com/olcayseker/NLogFileTargetSample.
But this raises another question. How can i provide folder for archive files. I couldnt find a way.

**Comment by Xharze** [comment]
I'll update the website with the correct sample.
You should be able to define the archiveFileName for this, see for example https://github.com/NLog/NLog/wiki/File-target#size-based-file-archival

**Comment by olcayseker** [comment]
For archive folder  archiveFileName="${basedir}/archives/log.${level}.{#####}.txt" line did the trick. All is fine now.
