### ISSUE TITLE
Provide conditional Logging

### ISSUE THREAD

**Issue by amruthayeluri** [NLog/NLog#5595]
It would be better to have conditional logging(to log only if particular condition is met)
Eg: I would only like to log when a particular config field is set true.

```csharp
bool Flag=true
Logger.Info(Flag==true,"this is conditional log"); /* this should first check the first parameter and if it gives true only then print second parameter otherwise don't print any log.*/
```

**Comment by snakefoot** [comment]
You can do this:
```c#
var logLevel = flag ? NLog.Level.Info : NLog.Level.Trace;
Logger.Log(flag, "this is conditional log");
```
Or you can do this:
```c#
if (flag) Logger.Info("this is conditional log");
```
Or you can do this:
```c#
if (!flag)
    LogManager.GlobalThreshold = LogLevel.Error;
Logger.Info("this is conditional log");
```

See also: https://github.com/NLog/NLog/wiki/Filtering-log-message

**Comment by amruthayeluri** [comment]
Hello @snakefoot ,

Thank you for the suggestions! The reason I raised the request is to avoid having to use explicit if conditions. Ideally, I would like to use a method like:

```csharp
Logger.IfFlagIsTrue("conditional log");
```
This would streamline the logging process by directly evaluating the condition within the logger without needing separate conditional logic.

Does this make sense, or would something similar be possible?

**Comment by snakefoot** [comment]
You can always add your own extension methods to the NLog ILogger-interface.



Sent from my Galaxy



-------- Original message --------
From: amruthayeluri ***@***.***>
Date: 10/09/2024 11:01 (GMT+01:00)
To: NLog/NLog ***@***.***>
Cc: Rolf Kristensen ***@***.***>, Mention ***@***.***>
Subject: Re: [NLog/NLog] Provide conditional Logging (Issue #5595)


Hello @snakefoot<https://github.com/snakefoot> ,

Thank you for the suggestions! The reason I raised the request is to avoid having to use explicit if conditions. Ideally, I would like to use a method like:

Logger.IfFlagIsTrue("conditional log");

This would streamline the logging process by directly evaluating the condition within the logger without needing separate conditional logic.

Does this make sense, or would something similar be possible?

**Comment by amruthayeluri** [comment]
Yeah, I have been doing that, but I thought if we have any functionality provided from NLog, it would be more dependency injection friendly.

**Comment by snakefoot** [comment]
I have already presented 4 ways. And actually there are one more, that uses DEBUG define to enable /disable logging

Not planning to extend the API any further, but if you have ideas for how to improve the existing API then pull requests are welcome to show your ideas.



Sent from my Galaxy



-------- Original message --------
From: amruthayeluri ***@***.***>
Date: 11/09/2024 10:48 (GMT+01:00)
To: NLog/NLog ***@***.***>
Cc: Rolf Kristensen ***@***.***>, Mention ***@***.***>
Subject: Re: [NLog/NLog] Provide conditional Logging (Issue #5595)


Yeah, I have been doing that, but I thought if we have any functionality provided from NLog, it would be more dependency injection friendly.

**Comment by snakefoot** [comment]
Added one more conditional-option using `LogManager.CreateNullLogger()`.
