### ISSUE TITLE
Logging cuts of float values

### ISSUE THREAD

**Issue by BlackFLX** [NLog/NLog#5598]
**NLog version**: 5.3.3

**Platform**: .Net Framework 4.7.2

**Current NLog config**

```xml
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <targets async="true">
    <target name="console" xsi:type="Console" layout="${date:universalTime=true:format=yyyy-MM-ddTHH\:mm\:ss.fffZ} ${pad:padding=5:${level:uppercase=true}} ${threadname} ${logger} ${message} ${exception:format:toString}">
    </target>
  </targets>
  <rules>
    <logger name="*" minlevel="Debug" writeTo="console" />
  </rules>
</nlog>

```

Hey,
I ran into the following issue on my own project but for testing reasons I set up a simple ConsoleApp with .Net Framework 4.7.2 and installed NLog nuget package.
Here is the simple code snipped to reproduce the error:

```
internal class Program
{
 private static readonly NLog.Logger _logger = NLog.LogManager.GetCurrentClassLogger();
 static void Main(string[] args)
 {
  var value1 = 80.0003f;
  var value2 = 100.000031f;
  var value3 = 200.000031f;

  _logger.Error(value1);
  _logger.Error(value2);
  _logger.Error(value3);

  Console.ReadLine();
 }
}
```

- What is the current result?
The log entires are:
2024-09-11T09:15:52:862Z ERROR ConsoleApp5.Program 80,00003
2024-09-11T09:15:52:882Z ERROR ConsoleApp5.Program 100
2024-09-11T09:15:52:892Z ERROR ConsoleApp5.Program 200

- What is the expected result?
The log entries should be:
2024-09-11T09:15:52:862Z ERROR ConsoleApp5.Program 80,00003
2024-09-11T09:15:52:882Z ERROR ConsoleApp5.Program 100,000031
2024-09-11T09:15:52:892Z ERROR ConsoleApp5.Program 200,000031

- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
Yes but I could not find any helpful log entry. I also search on reddit, github PR + Issues, stackoverflow and much more but I could not find a topic there.
- Please post full exception details (message, stacktrace, inner exceptions)
There is no exception
- Are there any workarounds?
Yes, you have to use _logger.Error(value2.ToString("G9"); But I don't want to search my full codebase and find all sections where I have to do a manually string format.
- Is there a version in which it did work? 
No
- Can you help us by writing an unit test?
No

I hope you can help me with that issue.
Have a nice day and thank you :)

**Comment by snakefoot** [comment]
NLog calls `string.Format("{0}", value)` and outputs the returned string-value.

I get the following output with NET6
```c#
2024/09/11 20:09:52.977|ERROR|80,0003 |ConsoleExample.Program|
2024/09/11 20:09:52.998|ERROR|100,00003 |ConsoleExample.Program|
2024/09/11 20:09:52.998|ERROR|200,00003 |ConsoleExample.Program|
```
And when I do this:
```c#
        Console.WriteLine($"{value1}");
        Console.WriteLine($"{value2}");
        Console.WriteLine($"{value3}");
```
Then I get the following output in NET6:
```
80,0003
100,00003
200,00003
```
When changing to NET48 then I get the same output as you:
```
80,0003
100
200
```
NLog is limited by the abilities of `string.Format`. There are no plans to replace `string.Format`.

If you remove the `f`-flag (forces single float), so the values instead becomes double:
```c#
  var value1 = 80.0003;
  var value2 = 100.000031;
  var value3 = 200.000031;
```
Then all decimals are shown in output.

**Comment by BlackFLX** [comment]
Thank you very much for your quick replay. 😊
Thats interesting that there is a different behavior between .Net Framework and the new .Net.
For me its now ok and I will close this issue.

Have a nice day 🫡

**Comment by snakefoot** [comment]
Also notice float has a precision of 6-9 digits, and double has a precision of 15-17 digits, and decimal has a precision of 28-29 digits


Sent from my Galaxy



-------- Original message --------
From: BlackFLX ***@***.***>
Date: 12/09/2024 08:52 (GMT+01:00)
To: NLog/NLog ***@***.***>
Cc: Rolf Kristensen ***@***.***>, Comment ***@***.***>
Subject: Re: [NLog/NLog] Logging cuts of float values (Issue #5598)


Thank you very much for your quick replay. 😊
Thats interesting that there is a different behavior between .Net Framework and the new .Net.
For me its now ok and I will close this issue.

Have a nice day 🫡
