### ISSUE TITLE
Fortify Scan

### ISSUE THREAD

**Issue by hw2013** [NLog/NLog#564]
src\NLog\Targets\MailTarget.cs
```
            else if (this.SmtpAuthentication == SmtpAuthenticationMode.Basic)
            {
                string username = this.SmtpUserName.Render( lastEvent );
                string password = this.SmtpPassword.Render( lastEvent );

                InternalLogger.Trace( "  Using basic authentication: Username='{0}' Password='{1}'", username, new string( '*', password.Length ) );
                client.Credentials = new NetworkCredential( username, password );
            }

  InternalLogger.Trace( "  Using basic authentication: Username='{0}' Password='{1}'", username, new string( '*', password.Length ) );
```

Abstract:

The method Write() in InternalLogger.cs mishandles confidential information, which can compromise user privacy and is often illegal.

Explanation:

Privacy violations occur when:

1. Private user information enters the program.

2. The data is written to an external location, such as the console, file system or network.

**Comment by 304NotModified** [comment]
Can you write some context information on this? And why are you posting this?

**Comment by sgdowney** [comment]
I think perhaps @hw2013 is referring to the InternalLogger writing the SMTP username and password to the Trace log.  The exposure of this information may be considered a privacy violation.  However, is the username and password information being referenced here actually part of the logger configuration and not user information that may have been entered by a user?

**Comment by 304NotModified** [comment]
The password isn't logged? Only the length is "leaked" by the `*****`

**Comment by 304NotModified** [comment]
The intention of this issue is unclear.  Nobody benefits from guessing. Closing for now. 

@hw2013 Feel free to reopen and clarify your post.
