### ISSUE TITLE
Nlog for otel not working as expected

### ISSUE THREAD

**Issue by ashwinpagarkhed** [NLog/NLog#5642]
We have a central otel collector in a k8s cluster which is collecting metrics and logs from miccroservices from other k8s cluster. This works fine. However we have a few apps which have nlog logging all application logs to a storage account/eventhub. We want to get all the nlog logs through otel

**NLog version**: 4.7.15

**Platform**: .NET Framework 4.8

This is the `nlog.config` file for the xml config for the otel collector as per [this](https://github.com/juliuskoval/NLog.Targets.OpenTelemetryProtocol):

**Current NLog config** (xml)

```
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      internalLogFile="C:/home/LogFiles/NLog/Internal-otel-final.txt" 
      internalLogLevel="Trace">
 <extensions>
        <add assembly="NLog.Targets.OpenTelemetryProtocol"/>
 </extensions>
<targets>
        <target xsi:type="OtlpTarget"
        name="otlp"
        endpoint="http://nlog.istio.acs314159.com"
        usehttp="true"
        servicename="Bkg"
        resources="process.name=${processname};process.id=${processid};deployment.environment=ashwindev"
        attributes="thread.id=${thread.id}"
        scheduledDelayMilliseconds="1000"
        useDefaultResource="false"
        includeFormattedMessage="true"/>
</targets>
 <rules>
       <logger name="*" minlevel="Debug" writeTo="otlp"/>
</rules>
</nlog>
```
the internal log file for nlog (used to troubleshoot nlog config errors) shows no error with this current config values .
By the current config we are not recieving any msges in the otel pods, and as a expected result we would want to see the nlog msges in the otel collector. There is no workaround at the moment apart from changing the target to blob or eventhub (which we dont want)

**Comment by snakefoot** [comment]
Sounds like an issue with [NLog.Targets.OpenTelemetryProtocol](https://github.com/juliuskoval/NLog.Targets.OpenTelemetryProtocol) please post your question for support there instead. Or maybe try StackOverflow.com ?

Issues here are for the NLog-core-package, and not for custom extensions created by others.

**Comment by ashwinpagarkhed** [comment]
closing this issue.. Will track here https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/35732

**Comment by snakefoot** [comment]
Notice [NLog.Targets.OpenTelemetryProtocol v1.1.6](https://www.nuget.org/packages/NLog.Targets.OpenTelemetryProtocol/1.1.6) has been released that should produce more [NLog InternalLogger](https://github.com/NLog/NLog/wiki/Internal-Logging)-output. See also https://github.com/juliuskoval/NLog.Targets.OpenTelemetryProtocol/pull/19
