### ISSUE TITLE
Make a seperate NLog project for WPF.

### ISSUE THREAD

**Issue by jyrka98** [NLog/NLog#566]
Hi. Would it be possible to make a seperate NLog project for WPF, so that there's no dependency on System.Windows.Forms.dll ?

**Comment by Xharze** [comment]
There's a pull request for this, see #497. And separate project has been created and release see NLog/NLog.Windows.Forms

**Comment by Xharze** [comment]
The targets have been moved to NLog/NLog.Windows.Forms, and the old code removed from NLog/NLog
