### ISSUE TITLE
RegisterLayoutRenderer will not work if done before applying configuration

### ISSUE THREAD

**Issue by MagnusMalmqvist** [NLog/NLog#5662]
**NLog version**: 5.3.4

**Platform**: .NET8

**Current NLog config** (xml or C#, if relevant)

```json
      "Targets": {
        "File": {
          "Type": "File",
          "FileName": "MyLog.log",
          "Layout": "${longdate} ${level:uppercase=true} [${trace}] ${logger}: ${message}"
        }
```

In my hostbuilder under .Configurelogging - if I register my Custom LayoutRenderer like this, it will not append the trace from TraceRenderer.

```csharp
        var host = Host.CreateDefaultBuilder(args)
            .ConfigureLogging((hostContext, logging) =>
            {
                LogManager.Configuration = new NLogLoggingConfiguration(hostContext.Configuration.GetSection("Logging:NLog"));

                LogManager.Setup().SetupExtensions(ext => {
                    ext.RegisterLayoutRenderer<TraceRenderer>();
                });

                logging.ClearProviders();
                logging.AddNLog();
                logging.AddConsole();
            })
```
But if I register it before I do LogManager.Configuration it works -- this took us quite some time to figure out and we started looking into different solutions before we discovered this by coincidence.

If it is not technically possible to have this order agnostic -- it should at least be made clear in the documentation.

**Comment by snakefoot** [comment]
It is correct that custom NLog LayoutRenders and custom NLog Targets must be registered before they can be used by NLog LoggingConfiguration. Something like this:
```c#
                LogManager.Setup().SetupExtensions(ext => {
                    ext.RegisterLayoutRenderer<TraceRenderer>();
                })
                .LoadConfigurationFromSection(hostContext.Configuration, "Logging:NLog");
```
Notice when [troubleshooting NLog](https://github.com/NLog/NLog/wiki/Logging-troubleshooting) then it is a good idea to enable `"throwConfigExceptions": true` and check the [NLog InternalLogger](https://github.com/NLog/NLog/wiki/Internal-Logging).

**Comment by MagnusMalmqvist** [comment]
Thank you for the clarification

Perhaps this page could be updated to include this and with some updated examples
https://github.com/NLog/readthedocs/blob/master/docs/Register-your-custom-component.md

**Comment by snakefoot** [comment]
> Perhaps this page could be updated to include this and with some updated examples
https://github.com/NLog/readthedocs/blob/master/docs/Register-your-custom-component.md

That page is a 5 year old clone of the [current Wiki-page](https://github.com/NLog/NLog/wiki/Register-your-custom-component). Maybe an experiment by @304NotModified to play with [ReadTheDocs](https://docs.readthedocs.io/en/stable/intro/add-project.html)

**Comment by MagnusMalmqvist** [comment]
Ah, of course, thank you! the ReadTheDocs page is first result when googling NLog Layoutrenderer. I added an edit on the current wiki page with a note on the ordering.

**Comment by 304NotModified** [comment]
> > Perhaps this page could be updated to include this and with some updated examples
> > https://github.com/NLog/readthedocs/blob/master/docs/Register-your-custom-component.md
> 
> That page is a 5 year old clone of the [current Wiki-page](https://github.com/NLog/NLog/wiki/Register-your-custom-component). Maybe an experiment by @304NotModified to play with [ReadTheDocs](https://docs.readthedocs.io/en/stable/intro/add-project.html)

Yes it was a experiment. Maybe it should be removed.

**Comment by 304NotModified** [comment]
> Thank you for the clarification
> 
> Perhaps this page could be updated to include this and with some updated examples https://github.com/NLog/readthedocs/blob/master/docs/Register-your-custom-component.md

FYI, this old repo had been deleted
