### ISSUE TITLE
How to config a real-time nlogger for RichTextBoxTarget?

### ISSUE THREAD

**Issue by changchengxc** [NLog/NLog#567]
Here is my code: 
it works but all logs display when process is done. I hope it can works well like console target. how should I change the config? thanks a lot !
-------------------------------------------
            LoggingConfiguration changedConfig = new LoggingConfiguration();
            
            RichTextBoxTarget richTextBoxTarget = new RichTextBoxTarget();
            richTextBoxTarget.Name = "RichTextBox";
            richTextBoxTarget.Layout = RichTextBoxTraceLayout;
            richTextBoxTarget.FormName = RichTextBoxTargetFormName;
            richTextBoxTarget.ControlName = RichTextBoxTargetControlName;
            richTextBoxTarget.AutoScroll = true;

            richTextBoxTarget.UseDefaultRowColoringRules = false;
            richTextBoxTarget.RowColoringRules.Add(new RichTextBoxRowColoringRule("level == LogLevel.Debug", "Gray", "Control"));
            richTextBoxTarget.RowColoringRules.Add(new RichTextBoxRowColoringRule("level == LogLevel.Info", "ControlText", "Control"));
            richTextBoxTarget.RowColoringRules.Add(new RichTextBoxRowColoringRule("level == LogLevel.Warn", "DarkRed", "Control"));
            richTextBoxTarget.RowColoringRules.Add(new RichTextBoxRowColoringRule("level == LogLevel.Error", "White", "DarkRed", FontStyle.Bold));
            richTextBoxTarget.RowColoringRules.Add(new RichTextBoxRowColoringRule("level == LogLevel.Fatal", "Yellow", "DarkRed", FontStyle.Bold));

            richTextBoxTarget.UseDefaultRowColoringRules = false;
            LoggingRule richTextBoxRule = new LoggingRule("*", richTextBoxTarget);
            richTextBoxRule.EnableLoggingForLevel(LogLevel.Debug);
            richTextBoxRule.EnableLoggingForLevel(LogLevel.Error);
            richTextBoxRule.EnableLoggingForLevel(LogLevel.Fatal);
            richTextBoxRule.EnableLoggingForLevel(LogLevel.Info);
            richTextBoxRule.EnableLoggingForLevel(LogLevel.Trace);
            richTextBoxRule.EnableLoggingForLevel(LogLevel.Warn);

            changedConfig.AddTarget("RichTextBox", richTextBoxTarget);
            changedConfig.LoggingRules.Add(richTextBoxRule);

            LogManager.Configuration = changedConfig;
            LogManager.ReconfigExistingLoggers();

**Comment by 304NotModified** [comment]
You needs threads for this.

**Comment by 304NotModified** [comment]
I will assume your question is answered. If not, feel free to re-open.
