### ISSUE TITLE
Enable Serialization of current LoggingConfiguration

### ISSUE THREAD

**Issue by ghost** [NLog/NLog#57]
<p>After programmatically adding targets, rules, etc. it would be nice to be able to serialize the result to XML. I may have missed it but attempting to use XmlSerializer gives an error due to no parameter-less constructor. I am assuming that such code exists somewhere in NLog but is not exposed. I am using the latest NLog 2.0 due to my need for the ReplaceLayoutRendererWrapper.</p>

**Comment by 304NotModified** [comment]
This is not planned
