### ISSUE TITLE
Need a way ensure the integrity and authenticity of log messages written using NLog

### ISSUE THREAD

**Issue by sulochane** [NLog/NLog#570]
How to ensure the *integrity* and *authenticity* of log messages written using NLog? Once the log file is released for investigation, there is no way to confirm that the file is unaltered from its original version. Due to increased security demand, it would be beneficial to have a feature to include MAC or HMAC to the messages written to the log file. So that the validity of log file could be checked before continue to investigate the contents in the log file.
Suggesting to have a **MAC** for each log line and be appended to the end of line. A *Key* should be used to generate the hash value. This could either be given as a parameter or saved to a file and then read the key value from the file. 

It is also important to have a line number in each record line. Then removal of any line from the log file will be detected.  
Current NLog Version: 3.2.0
Example Config :
`
<nlog>
    <targets>
      <target name ="file" xsi:type="File" fileName ="${ basedir}/file.log" hashkey ="<secret key for hash> or <file path for the secret key>"
            layout="${counter}: ${date}: ${message} : {hash}" />
  </targets>
  <rules>
    <logger name="*" minlevel ="Trace" writeTo="file" />
  </rules>
</nlog>
`

**Comment by 304NotModified** [comment]
I had to think about this. This is possible to implement with nested layout renderers within a custom layout renderer.  

I think there is no demand for this feature, so I don't think this will be implemented at our site.

**Comment by Xharze** [comment]
I agree with @304NotModified, I think it is a special feature, which won't be used widely
