### ISSUE TITLE
Normalize line endings across the code base

### ISSUE THREAD

**Issue by ilya-g** [NLog/NLog#572]
I've noticed that some of the source files use CRLF as the line delimiter, some LF only and some mix LF with CRLF.
What is the recommened line delimiter for NLog repository?

**Comment by ilya-g** [comment]
I've found commit f2e44e586312efdc70131f2cdac8de12e687d5e5 where @jkowalski have replaced all CRLFs with LFs, so it would be reasonable to assume that LF is preferred.

I think some settings in `.gitattributes` file should be made enforcing this delimiter for this repository, such as described here: https://help.github.com/articles/dealing-with-line-endings/#per-repository-settings

**Comment by Xharze** [comment]
That would be a good idea, although we'll have to try and make sure
everybody with existing forks knows how to handle this before the change.

**Comment by 304NotModified** [comment]
I vote for the line endings that bythe github editor uses.  Dunno if it's LF

**Comment by ilya-g** [comment]
I've created an experimental branch (https://github.com/ilya-g/NLog/tree/eol-normalize) to see how it can be done. I'm intentionally not proposing it as a pull request, in order you, guys, could review the changes and consider the consequences.

In the first commit I've set up `.gitattributes`: turned on text file autodetection for all files and told git which files are definitely text and which are not. I've used this [`.gitattributes`](https://github.com/libgit2/libgit2sharp/blob/4f23c3488f581191d1f4e14fcfa4623298bd6081/.gitattributes) file as an example.
Now all files considered as text are subject to be eol-normalized before being commited to the repository – they will go in the repository with LF as a line delimiter. Thus anyone who touches files with inconsistent line endings will trigger it normalization on commit.

In order not to scare commiters with the whole file being changed when they change only one line, I've followed further [recommendation](http://git-scm.com/docs/gitattributes#_end_of_line_conversion) of how to convert inconsistent line endings: 

`````
$ rm .git/index     # Remove the index to force Git to
$ git reset         # re-scan the working directory
`````

After that all such files became marked as modified and I was able to commit them making the normalization to happen. In the second commit you can find all that files, although to see the changes you might require a tool, that shows differences in line-endings. I use TortoiseGitMerge from Tortoise Git client.

As for the merges after that change: as expected an automatic merge of a branch that was created before the change and have the same files changed would result in a conflict. But this conflict can be  easily resolved with the merge tool smart enough not to treat eol-changes as conflicting.

**Comment by ilya-g** [comment]
Proposed the first commit with .gitattributes as PR #583
