### ISSUE TITLE
Roadmap 4.0

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#574]
Do we have a roadmap for the next release? (4.0)  Or do we use time boxing?

**Comment by Xharze** [comment]
I don't have anything specific planned for this release. Although it should
probably not be too long before a pre release is created and published.

**Comment by 304NotModified** [comment]
I did a proposal for 4.0 and 3.2.1
https://github.com/NLog/NLog/milestones

What do you think?

**Comment by Xharze** [comment]
I think we should go with it. It looks good.

**Comment by 304NotModified** [comment]
I was thinking about this, and I think this isn't good enough. People are asking when the new version will be released, and even I don't know. 

Because we are an open-source product with unknown amount of contributors, we should plan agile. 

I will propose the following:

- We use time boxing: this means that we should pick a date when we will release.
- We will label the issues with the [MoSCoW method](https://en.wikipedia.org/wiki/MoSCoW_method). In short this means
 - We will label them with *Must have*, *Should have*, *Could have* and *Wont have this time around* 
 - The release **must** contains the *must haves*. We will move the release date if not all must haves are implemented. 
 - The release *should* contains the *should haves*. But we will release even if not all should haves are implemented.
 - Could haves would be nice, but only if we have enough time, according to the planned release date. 

Then It is advised to:

- Don't label too much must haves. 3 large **must haves** should be the max.
- Issues which have workarounds should be labeled as *should have*

**Comment by Xharze** [comment]
Sounds reasonable, but what I don't like is the part where we pick a date.
As you say the must have must be in the release, meaning the date doesn't
matter that much

**Comment by 304NotModified** [comment]
Well thats timeboxing 

http://www.stevepavlina.com/blog/2004/10/timeboxing/

Without a fixed date it's unclear when something is released - this is also important for PR's.   Also it will prevent infrequent releases. 

IMO timeboxing is required for projects which has an unclear amount of developers/development time.

**Comment by Xharze** [comment]
Let's try it and see how it goes

**Comment by 304NotModified** [comment]
:+1: 

I created the labels. Feel free to label the issues with `Must have`, `Should have`, I will also label some and then we can discuss the labels and the fixed date.

**Comment by 304NotModified** [comment]
My proposal is done

* [4 must haves](https://github.com/NLog/NLog/issues?q=is%3Aopen+is%3Aissue+milestone%3A4.0+label%3A%22Must+have%22)
* [6 should haves](https://github.com/NLog/NLog/issues?q=is%3Aopen+is%3Aissue+milestone%3A4.0+label%3A%22Should+have%22+)
* [9 could haves](https://github.com/NLog/NLog/issues?q=is%3Aopen+is%3Aissue+milestone%3A4.0+label%3A%22Could+have%22+)

We should pick a date so we can: fix for sure the must have, fix preferable the should haves, almost no time planned for the could haves.

**Comment by Xharze** [comment]
Sounds good to me. About the release date... I don't really know, although
as said before I think we should release the next version soon. What about
in 2 months? I'm on holiday most of this month so I don't have a lot of
time.

**Comment by 304NotModified** [comment]
The next version, it that 4.0 or 3.2.1?

**Comment by 304NotModified** [comment]
I moved the 3.2.1 discussion to a new issue.

I you we're talking about 4.0, then I think 2 Jun would be perfect. That are 3 months.

**Comment by Xharze** [comment]
The next real release is 4.0. 3.2.1 is just a bug release

**Comment by Xharze** [comment]
That sounds feasible, let's stick with this date. Maybe we should create a
news post about this?

**Comment by 304NotModified** [comment]
Yes I will create on this or next week. First the 3.2.1 post.: )

**Comment by 304NotModified** [comment]
@Xharze with this clear roadmap, maybe we could search for new developers?

**Comment by Xharze** [comment]
Sounds like a very good idea, it works be nice with more developers

**Comment by 304NotModified** [comment]
I will create a news post. This or next week.

**Comment by 304NotModified** [comment]
News post posted.

http://nlog-project.org/2015/03/27/NLog-4-0-roadmap-and-release-date.html

**Comment by 304NotModified** [comment]
Note: I will create a separate post for the search for developers.

**Comment by 304NotModified** [comment]
@Xharze sorry for the delay of the new-developers-post.

**Comment by 304NotModified** [comment]
@ilya-g aren't you interested in being part of the NLog developers? I was very impressed by your knowledge and code quality!
