### ISSUE TITLE
Documentation: logger has no information on members

### ISSUE THREAD

**Issue by mmcconna** [NLog/NLog#578]
The auto generated code documentation is missing any info on logger methods
http://nlog-project.org/documentation/v3.2.0/html/T_NLog_Logger.htm 

Unless I am missing something? The documentation seems to be in the source so not sure why it is not being generated.

Compare http://nlog-project.org/documentation/v2.0.1/html/AllMembers_T_NLog_Logger.htm

**Comment by Xharze** [comment]
I'll update the documentation as soon as I figure out why this happens

**Comment by 304NotModified** [comment]
It would be great if we create the documentation with 

Sandcastle Help File Builder (SHFB) https://github.com/EWSoftware/SHFB

**Comment by 304NotModified** [comment]
Fixed with 3.2.1 docs. http://nlog-project.org/documentation/v3.2.1/html/R_Project_NLog.htm
