### ISSUE TITLE
Find calling method on stack trace broke with 3.2.0

### ISSUE THREAD

**Issue by JueSte** [NLog/NLog#579]
We use our own Logwrapper and our Test looks like this: 

```Vb.net

    <TestMethod()>
    Public Sub CallsiteTest()

        Dim debugTarget = TestObjects.GetConfiguredDebugTarget()
        Dim target = New LogWrapper.Logger("test")

        target.Log(LogWrapper.LogLevel.Fatal, "TestTestTest")

        Dim expected = "Logima.LogWriterNlog_Test.LogWrapperTest.CallsiteTest"
        Dim actual = debugTarget.LastMessage.Split(CChar("|"))(3)
        Assert.AreEqual(expected, actual)

    End Sub
```

With Nlog 3.1 this test passes. 
With Nlog 3.2 this tests fails because actual is the log method of our wrapper class instead of the test method.

**Comment by 304NotModified** [comment]
Is this a duplicate of #541 ?

**Comment by JueSte** [comment]
Yes it is. It seems to me, that I used the wrong key words while searching for an open ticket.

**Comment by 304NotModified** [comment]
No problem. Thanks for verifying. At least this issue is now more on the agenda.
