### ISSUE TITLE
NLog ShortDate

### ISSUE THREAD

**Issue by JinPachi** [NLog/NLog#580]
Hi all. Please help me.
My archive files is current:

```
log.file-2015-02-17.log
log.file-2015-02-16.log
log.file-2015-02-15.log

lof.file.Today.log
```

But for example in log.file-2015-02-16.log is store log info about  2015-02-15.

Can i change my config that in log.file-2015-02-16.log was contain information log with the same data(2015-02-16)?

My config:

```xml
  <targets>
    <target name="rotationByDate" xsi:type="File" layout="${verbose_inline}"
            fileName="${basedir}/logs/log.file-Today.log"
            archiveFileName ="${basedir}/logs/log.file-${shortdate}.log"
            archiveEvery="Day"
            archiveNumbering = "Rolling"
            maxArchiveFiles="3"/>
  </targets>
```

Cheers,
JinPachi.

**Comment by 304NotModified** [comment]
This is default behavior and can't be configured (yet)
