### ISSUE TITLE
internalLogFile: NLog variables

### ISSUE THREAD

**Issue by contento** [NLog/NLog#581]
Is there any way I could specify a variable in the <nlog /> attributes?

I know you cannot use layout variables, but it would be wonderful to be able to write in the .config something like: 
 ` internalLogFile="c:/logs/Nlog.${processname}.log" `

BTW: the issue has been mentioned in StackOverflow
  http://stackoverflow.com/questions/9428724/nlog-internal-log-not-working-with-asp-net-mvc

**Comment by 304NotModified** [comment]
As answered at Stackoverflow this isn't possible. 

Also it would be strange if this could work, the internal logfile should be as stable as possible (a so no fancy features). Also I think thank the internal log should only be used in rare cases.

**Comment by Niklas-Peter** [comment]
What is about environment variables?

**Comment by 304NotModified** [comment]
Right now it's just a plain string. So also no environment variables.

**Comment by Niklas-Peter** [comment]
I know. That was rather a feature request ;)

**Comment by 304NotModified** [comment]
@Niklas-Peter Why would you need it? We think that the internal logger should be as simple as possible.

**Comment by Niklas-Peter** [comment]
It is hard to choose a fixed path. Most appropriate folders are in 
different locations depending on the Windows version, but share the same 
environment variable name.

**Comment by 304NotModified** [comment]
But it's only needed in rare cases? 

For other cases, just use the FileTarget?

**Comment by Niklas-Peter** [comment]
Probably you are right.
You should evaluate, how much effort and instability such an 
implementation requires and then balance pros and cons.
I think it will require just a few commands, but, of course, these few 
can fail, too.

**Comment by 304NotModified** [comment]
Yes, that's the case. And then we should write an internal-internal-logger ;)

If there is a really great benefit to implement, we will add it as feature request.
