### ISSUE TITLE
Get Name process

### ISSUE THREAD

**Issue by JinPachi** [NLog/NLog#586]
Hi All! 

Which symbol in NLog is mean many symbols?  What I need write instead of '*' in regex?

  <variable name ="Service_name" value="${replace:inner=${callsite}:searchFor=Server.*Service*:replaceWith=*Service:regex=true}"/>

Cheers,
JinPachi.

**Comment by 304NotModified** [comment]
Hi,

I don't understand your question. Can you explain a bit more and give an example?

**Comment by JinPachi** [comment]
<variable name ="Service_name" value="${replace:inner=${callsite}:searchFor=Server.*Service*:replaceWith=*Service:regex=true}"/>
  

  <targets>
    <target name="rotationByDate" xsi:type="File" layout="${verbose_inline}"
            fileName="${basedir}/base_dir_NLog/Node_name/IceBox_name/current_log.log"
            archiveFileName ="base_dir_NLog/Node_name/IceBox_name/${Service_name}.{##}"
            archiveAboveSize="10000"
            archiveNumbering = "Rolling"
            maxArchiveFiles="10"/>
  </targets>

**Comment by 304NotModified** [comment]
But what are you trying to achieve?

**Comment by JinPachi** [comment]
I try archive file with name from something namespace by using callsite and I try replace symbol in this name of file.

**Comment by JinPachi** [comment]
How replace string1="Something symbol Hello World" on the string2="HelloWorld" ?

**Comment by 304NotModified** [comment]
Well you can use just .Net regex syntaxis. You need to escape the `}` with `\}`

https://github.com/NLog/NLog/wiki/Replace-Layout-Renderer

https://msdn.microsoft.com/en-us/library/hs600312%28v=vs.110%29.aspx

If you need to find the correct regular expression, I would recommend this tool: [Expresso 3.0](http://www.ultrapico.com/Expresso.htm)

Some examples in our unit tests: https://github.com/NLog/NLog/blob/master/tests/NLog.UnitTests/LayoutRenderers/Wrappers/ReplaceTests.cs
