### ISSUE TITLE
Get Name process

### ISSUE THREAD

**Issue by JinPachi** [NLog/NLog#587]
Hi All! 

Which symbol in NLog is mean many symbols?  What I need write instead of '*'?

  <variable name ="Service_name" value="${replace:inner=${callsite}:searchFor=Server.*Service*:replaceWith=*Service:regex=true}"/>

Cheers,
JinPachi.

**Comment by JinPachi** [comment]
<variable name ="Service_name" value="${replace:inner=${callsite}:searchFor=Server.*Service*:replaceWith=*Service:regex=true}"/>

**Comment by 304NotModified** [comment]
duplicate of #586
