### ISSUE TITLE
Explanation how issues are labeled @GitHub

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#588]
I'm trying to label every issue on GitHub. Because I like transparency, I will explain how I work:

* preferably, each issue has a label, although this isn't a goal. The goals is to get a nice overview where we stand & if there a lot of issues.
* Bug-reports, even non-confirmed bugs are labels under `bug`.
* Functional changes are labeled under 'feature'. Even small `features`.
* Non-functional changes  are labeled under `enhancement`.
* Issue's that have missing info are labeled under `incomplete info`. If we don't get a response withing 14 days, I will **close** the issue.
* answered questions are **closed** after 3 days. 
* Issues which have PR's are labeled under `almost ready`
* The rest of the labels should be straightforward ;) 

Any comments or suggestions are welcome :)

**Comment by Xharze** [comment]
Sounds good and reasonable

**Comment by ilya-g** [comment]
There are a plenty of issues regarding `FileTarget`, the most important logging target, IMO.
It would be nice if we could filter such groups of issues not only with the text search.
What do you think about some functional area tags?

**Comment by 304NotModified** [comment]
Good idea @ilya-g. But don't we get a label explosion when creating those label? Creating a label for every target etc would be unwise. So which labels we should create and which don't?

**Comment by 304NotModified** [comment]
added to https://github.com/NLog/NLog/blob/master/issue-labeling.md and link from https://github.com/NLog/NLog/blob/master/CONTRIBUTING.md
