### ISSUE TITLE
How to handle old issues?

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#589]
There a lot of issues on GitHub. (+25 of 2012). I don't like open issues, and especially I dislike open bug reports.

What should be do with those old bug reports? Maybe we have to make them top priority?

**Comment by Xharze** [comment]
I don't know how many that still is an issue. Most of them are migrated
from the old codeplex account. I think we should either check if they're
still an issue or close them

**Comment by Ninja4Code** [comment]
I'm interested in contributing to the project, either in coding or documentation. What's the best way to get my feet wet. I am a C# developer. I've been using NLog for several years.

Charles

**Comment by osintra** [comment]
Same situation here

**Comment by 304NotModified** [comment]
Great! 

I will post some stuff where you could get started with later this day.

**Comment by 304NotModified** [comment]
Hi @Ninja4Code and @osintra 

Thanks for your interest in contributing to NLog. Contributions are really appreciated! 

The following GitHub issues are nice to start with:

- If you like to work with Mono: #648
- This issue would be great if it get fixed (and unit tested): #273
- If you like to create an layout renderer (small task): #86
- If you good in writing English or just like writing English:  #595, #520
- If you like to work with Sandcastle Help File Builder (SHFB): #655

**Comment by Ninja4Code** [comment]
Thanks for responding...
 
I'm assuming I need to check out the code and build it locally? Is there a set of instructions for that with coding conventions, etc? Could I get the code base working in Visual Studio, etc?
 
Thanks
Chuck
 
Date: Mon, 30 Mar 2015 08:13:36 -0700

**Comment by 304NotModified** [comment]
The best way to get started (flow)

- Fork the NLog repos. (eg. Ninja4Code/NLog)
- Create a new branch in you current repos (Ninja4Code/NLog) from the 'master' branch.
- 'Check out' the code with Git or [GitHub for Windows](https://windows.github.com/)

**Comment by 304NotModified** [comment]
@Ninja4Code if you need some more info, feel free to ask. 

Maybe good to know, are you a  Windows user? Are you experienced with Git and Github? (no problem if not)

**Comment by Ninja4Code** [comment]
Julian,
 
Thanks for the info.  I'll give you an update in 24 hours.
 
Chuck
 
Date: Mon, 30 Mar 2015 08:22:14 -0700

**Comment by Ninja4Code** [comment]
I have developed both on Windows and Linux environments, but mostly Windows.  My development has spanned most of the .NET Projects (MVC, SOA, WPF, etc). Yes, I have just installed the Windows GIT Client.
 
Thanks,
Chuck
 
Date: Mon, 30 Mar 2015 08:29:02 -0700

**Comment by Ninja4Code** [comment]
I was able to fork and clone the repository successfully.  
 
Charles
 
Date: Mon, 30 Mar 2015 08:29:02 -0700

**Comment by 304NotModified** [comment]
Any success with the code @ninja4code?

**Comment by Ninja4Code** [comment]
I have been engulfed in a few courses I am taking.  I have downloaded the code into a local Git repository.  I would like to start on something this weekend.

Charles

**Comment by 304NotModified** [comment]
Closing this discussion ("How to handle old issues?"). If you need some help @Ninja4Code , feel free to post in the referenced issues or contact me at Gitter (https://gitter.im/NLog/NLog)

**Comment by Ninja4Code** [comment]
I apologize I haven't contributed yet but I definitely intend to in the near future.  I'll contact you again when I get involved in the code.  I had to spend a lot of time finishing up my schoolwork for the semester.
 
Charles
 
Date: Thu, 14 May 2015 02:40:40 -0700

**Comment by 304NotModified** [comment]
@Ninja4Code No problem. Some things have to be done. 

We will appreciate any contributions like code, (unit) tests or other feedback. On the [readme](https://github.com/NLog/NLog/blob/master/README.md#contributing) I have added the Github issues if you like to start with something.

**Comment by Ninja4Code** [comment]
I know I didn’t contribute last time, but I’m making a humble request to try again. What’s the best way for me to start? Should I open the code in Visual Studio 2013 or 2015? Again, my apologies for inactivity in the past.


Charles Owen






Sent from Windows Mail





From: Julian Verdurmen
Sent: ‎Wednesday‎, ‎April‎ ‎15‎, ‎2015 ‎4‎:‎02‎ ‎PM
To: NLogNLog
Cc: Charles Owen





Any success with the code @ninja4code?

**Comment by 304NotModified** [comment]
hey! NP! We are aware helping takes some free time, and sometimes there is less then planned.

We still try to keep the code VS2013 compatible, but we will move soon to VS2015 (guess after 4.4)

There is some info on contributing over here: https://github.com/NLog/NLog#contributing

I think the following would be nice to do IMO:

- https://github.com/NLog/NLog/issues/1436
- https://github.com/NLog/NLog/issues/1406
- https://github.com/NLog/NLog/issues/1181

**Comment by Ninja4Code** [comment]
Thanks, I will try to work on the issues at the bottom


Charles






Sent from Windows Mail





From: Julian Verdurmen
Sent: ‎Saturday‎, ‎August‎ ‎13‎, ‎2016 ‎6‎:‎52‎ ‎PM
To: NLogNLog
Cc: Charles Owen, Mention





hey! NP! We are aware helping takes some free time, and sometimes there is less then planned.

We still try to keep the code VS2013 compatible, but we will move soon to VS2015 (guess after 4.4)

There is some info on contributing over here: https://github.com/NLog/NLog#contributing

I think the following would be nice to do IMO:
#1436
#1406
#1181
