### ISSUE TITLE
Supporting partners nlog-project.org

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#591]
We have now banners on http://nlog-project.org/.

But could be explained how those guys are supporting us? That's now unclear.

**Comment by Xharze** [comment]
That would be a good idea.
Loupe will, if needed, support us with some money for hosting servers. Although is hasn't been necessary yet. I'm also communicating with the about introducing some features from their products into NLog.
NDepend supports us with an open source license to NDepend.
Papertrail has provided us with an account we can use to test logging to
The TeamCity part is for using Codebetters Teamcity servers. We don't use them that much anymore, but they support some stuff Appveyor doesn't support yet.

**Comment by 304NotModified** [comment]
Yes, Teamcity support Mono as far as I known.
