### ISSUE TITLE
Google analytics stats - nlog-project.org

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#592]
@Xharze 

Do you have access to the Google Analytics statistics of nlog-project.org?

**Comment by Xharze** [comment]
Yes I do, I'll share it with you if you want to?

**Comment by 304NotModified** [comment]
Yes please :+1: 

Not sure if you need my email address? Not sure how to give it without posting it in the public.

**Comment by Xharze** [comment]
Just send me an email: kimworking at gmail.com
And I'll add you

**Comment by 304NotModified** [comment]
Great, the email is sent

**Comment by 304NotModified** [comment]
@Xharze did you received my email?
I don;t see the changes, yet

**Comment by Xharze** [comment]
Ahh sorry I'll add you today
