### ISSUE TITLE
NLog-Contrib should be renamed to NLog.Contrib?

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#593]
The repository [NLog-Contrib](https://github.com/NLog/NLog-Contrib) should be renamed to NLog.Contrib. That would be more consistent.

**Comment by Xharze** [comment]
Hopefully the NLog-Contrib repository will be remove completely and move it different repositiories only containing the targets code needed for the specific feature

**Comment by 304NotModified** [comment]
I even like that more!
