### ISSUE TITLE
document escaping layout renderers

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#595]
Example 

https://github.com/NLog/NLog/pull/544/files

**Comment by 304NotModified** [comment]
@Xharze 
Why do we need sometimes escaping, and sometimes not?

fails: `${appdomain:format={1}{0}}`

passes `${appdomain:format={1\}{0\}}`

passes: `${rot13:inner=${ndc:topFrames=3:separator=x}}` (no escaping needed)

**Comment by Xharze** [comment]
It is because of the $ sign

**Comment by 304NotModified** [comment]
So nested layout renderers don't need escaping?

**Comment by Xharze** [comment]
That is correct

**Comment by 304NotModified** [comment]
added https://github.com/NLog/NLog/wiki/Configuration-file#content-escaping

**Comment by Niklas-Peter** [comment]
What am I doing wrong? Is it not the same as in your example above?

    ${registry:value=ABCD:key=HKLM/NOT_EXISTENT:defaultValue=${specialfolder:folder=DesktopDirectory}}
outputs `${specialfolder}`
If I escape the `:` after `${specialfolder` it gets `${specialfolder:folder=DesktopDirectory}`.
If I set an existing registry key and value the output is still not correct, it appends an `}`:

    ${registry:value=EXISTS:key=HKLM/EXISTS:defaultValue=${specialfolder:folder=DesktopDirectory}}
is rendered as `C:\temp\myLogDir}` with HKLM/EXISTS/EXISTS set to `C:\temp\myLogDir`

**Comment by 304NotModified** [comment]
Well we don't need to escape the `{`, but we do has to escape the `:` because of this bug: https://github.com/NLog/NLog/issues/444

**Comment by Niklas-Peter** [comment]
Yes, but as I said escaping the colon does not really make it better. The layout renderer is still not rendered.

**Comment by 304NotModified** [comment]
You tried this work around? 

https://github.com/NLog/NLog/issues/444#issuecomment-63930649

**Comment by Niklas-Peter** [comment]
I think this workaround does solve another problem. I do not want to output a colon. The problem is obviously specific to ${registry}, because ${literal} nested in ${when} works. That means:
*Case 1* (wrong)
Layout: `${registry:key=HKLM/ABCDE:defaultValue=${literal:text=AA}}`
Output in log file: ${literal}

*Case 2* (wrong)
Layout: ${registry:key=HKLM/ABCDE:defaultValue=${literal\:text=AA}}
Output in log file: ${literal:text=AA}

*Case 3* (correct)
Layout: ${when:when=1 == 1:inner=${literal:text=AA}}
Output in log file: AA

**Comment by 304NotModified** [comment]
Ow yes, I see. I will try to find out which syntax you need.

I think you can work around this by making a variable, see https://github.com/NLog/NLog/wiki/Configuration-file#variables

**Comment by Niklas-Peter** [comment]
> I think you can work around this by making a variable
How? I tried `${registry:key=HKLM/ABCDE:defaultValue=${var}}`, but of course that does not work, either.

**Comment by 304NotModified** [comment]
I see the problem. `defaultValue` of [`${registry`](https://github.com/NLog/NLog/wiki/Registry-Layout-Renderer) is a `string` and not a `Layout`. So this is not a bug, but a missing feature.

**Comment by Niklas-Peter** [comment]
Are there any plans to add this feature or reasons why not to do so?
Any workaround?

**Comment by 304NotModified** [comment]
We can add this feature to the next release. 

The only work around is to use the api for now.

**Comment by 304NotModified** [comment]
Another way is to create your own LayoutRenderer.  It's really easy :)

**Comment by Niklas-Peter** [comment]
> We can add this feature to the next release.
That would be a good idea.
