### ISSUE TITLE
MailTarget: remove mandatory To requirement 

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#599]
In the code we get an error when 'To' is empty when sending a mail.

But why? I think is also acceptable to send an mail with only a CC or BCC?

See `MailTarget.SetupMailMessage`

**Comment by 304NotModified** [comment]
related #596

**Comment by Xharze** [comment]
I've never send an email without a To recipient, it doesn't make sense in my opnion. A CC is a copy and BCC is a "private" copy of the email.

**Comment by 304NotModified** [comment]
Well at our company we use it sometimes. Also is see those on the bug reports.    IMO it should not be forced without very good reason.

**Comment by Xharze** [comment]
It's fine by me implementing this. But then we have to make sure either To,
CC or BCC has been defined

**Comment by 304NotModified** [comment]
Agree on that
