### ISSUE TITLE
Add a Unique ID per log event visible by a Layout Renderer

### ISSUE THREAD

**Issue by ghost** [NLog/NLog#60]
<p>When logging to various targets there isn&#39;t a specific way (that I&quot;m aware of) to link the log events together. The ${guid} layout renderer generates a unique id for each layout. So could we get a single unique reference id that all targets could expose?</p>

<p>&nbsp;</p>

<p>I&#39;d be happy to look into an implementation of this and provide a patch if needed.</p>

**Comment by 304NotModified** [comment]
Is an ´eventinfo´ with a property with a guid, a workaround for this?
