### ISSUE TITLE
longdate is printing 0000-00-00

### ISSUE THREAD

**Issue by gr8tushar** [NLog/NLog#611]
Hi,
I am using {longdate} in the file name and the csv column. But is is not working. It is printing 0000-00-00_00. Here is my config. 

```Xml
<target name="csv" xsi:type="File" fileName="${basedir}/../logs/${date:universalTime=True:format=yyyy-MM-dd_HH}.csv">
			<layout xsi:type="CSVLayout">
				....
....
				<column name="Level" layout="${level}"/>
				<column name="TxnDate" layout="${longdate}" />
....
....
</target>
```
I am using NLog 3.1 on Windows Server 2012.

**Comment by 304NotModified** [comment]
@gr8tushar 

Do you know if this is working with a file target?

**Comment by gr8tushar** [comment]
Yes, it does work on a file target in the Layout renderer. The dates in the file targets are printed as expected. However, if I use the date in the filename, at times it prints it as 0000-00-00. I think the issue in the file name pops up in case I change the config and some process is writing to the file.

**Comment by 304NotModified** [comment]
Do you use the `LogEventInfo()` constructor?

**Comment by 304NotModified** [comment]
possible related #614

**Comment by 304NotModified** [comment]
if this is still a problem, please submit the requested info and re-open this issue.
