### ISSUE TITLE
Cached Layout Renderer is reevaluated when LoggingConfiguration is changed

### ISSUE THREAD

**Issue by Quergo** [NLog/NLog#612]
Hi,

I use Cached Layout Renderer to generate a separate log file each time my application starts. This is done by caching the date of the first logging call. 

The target definition i use is:
```xml
<target name="default_logfile" xsi:type="File" fileName="${basedir}\${date:cached=True:format=yyyy-MM-dd_HH-mm-ss}_Log.txt" />
```

This works fine until i start to add new logging targets at runtime. I make changes to the LoggingConfiguration like this:

```C#
LoggingConfiguration config = LogManager.Configuration;

var logFile = new FileTarget();
config.AddTarget(dynamicTargetName, logFile);

logFile.FileName = dynamicFilePath + "_Ext.log";
logFile.Layout = @"|${level:uppercase=true} @ ${logger:shortName=true}|:${date:format=yyyy-MM-dd HH\:mm\:ss} ${message} ${exception:stacktrace:separator=*}";

var rule = new LoggingRule("*", LogLevel.Trace, logFile);
config.LoggingRules.Add(rule);

LogManager.Configuration = config;
```

On the one hand it correctly generates my dynamic logging target. But on the other, this seems to reevaluate the ${date:cached=True:format=yyyy-MM-dd_HH-mm-ss} expression which in consequence will generate a complete new logfile for my "default_logfile" target. The date used for the new logfile is the one of the first logging call after LoggingConfiguration reassignment.

I also tested this:
```C#
LogManager.Configuration = LogManager.Configuration
```
which also triggers the reevaluation of cached layout render.

I don't know if this is a bug or I am just doing something wrong with the dynamic logfile generation.

**Comment by 304NotModified** [comment]
I don't think this is bug

**Comment by Quergo** [comment]
In the class CachedLayoutRendererWrapper.cs if found these two methods getting called if LoggingConfiguration is reassigned:
```C#
        /// <summary>
        /// Initializes the layout renderer.
        /// </summary>
        protected override void InitializeLayoutRenderer()
        {
            base.InitializeLayoutRenderer();
            this.cachedValue = null;
        }

        /// <summary>
        /// Closes the layout renderer.
        /// </summary>
        protected override void CloseLayoutRenderer()
        {
            base.CloseLayoutRenderer();
            this.cachedValue = null;
        }
```
Both times the cached value is cleared and will be reevaluated when the wrapped content is rendered again.

Removing the null assginments in both methods fixed the problem for me as the cached value won't change in case of a LoggingConfiguration update.

**Comment by 304NotModified** [comment]
Well found. As expected this is on purpose. But I think it would be nice if it's configurable. 

I will tag it with feature. I'm not sure if this will be implemented In 4.0. But a PR would be accepted for 4.0

**Comment by 304NotModified** [comment]
I propose a new property for `CachedLayoutRendererWrapper` to handle your case. Something like `ClearCache=onInitialize` ?

**Comment by bhaeussermann** [comment]
Can this be closed?

**Comment by 304NotModified** [comment]
Yes it does. I was under the impression it was closed automatically. (because of 'fixes' message. But it was 'fixes issue', while Github is listening to 'fixes #...'. See https://help.github.com/articles/closing-issues-via-commit-messages/

Thanks for pointing out!
