### ISSUE TITLE
NLog.NLogConfigurationException: Target logfile not found.

### ISSUE THREAD

**Issue by tiger2014** [NLog/NLog#615]
The NLog.config:

```Xml
<target xsi:type="Database" name="LogOnlog" connectionStringName ="DataBase" >
      <commandText>
        Insert into MyLog(Operator_name,Operator_Type,IP,DateTime,Operation) Values(@Operator_name,@Operator_Type,@IP,@DateTime,@Operation);
      </commandText>
      <parameter name = "@Operator_name" layout = "${event-context;item=Operator_name}"/>
      <parameter name = "@Operator_Type" layout = "${event-context;item=Operator_Type}"   />
      <parameter name = "@DateTime" layout = "${event-context;item=DateTime}"/>
      <parameter name = "@IP" layout = "${event-context;item=IP}" />
      <parameter name = "@Operation" layout = "${event-context;item=Operation}"   />

    </target>

  </targets>

  <rules>
     <logger name="*" minlevel="Trace " writeTo="LogOnlog"/>
  </rules>
```

I use the Logger as this :

```Csharp 
            Logger logger = LogManager.GetCurrentClassLogger();  
            LogEventInfo lei = new LogEventInfo();
            lei.Properties["Operator_name"] = Opeator_Name;
            lei.Properties["Operator_Type"] = Operator_Type;
            lei.Properties["DateTime"] = DateTime.Now;
            lei.Properties["IP"] = GetClientIPOrAdd.GetIP();
            lei.Properties["Operation"] = Operation;
            lei.Level = LogLevel.Info;
            logger.Log(lei);
```

But at 'Logger logger = LogManager.GetCurrentClassLogger();',It had an erro 

`'NLog.NLogConfigurationException: Target logfile not found.'
`

Why such an erro ?

**Comment by tiger2014** [comment]
The NLog.config is :
<target xsi:type="Database" name="LogOnlog" connectionStringName ="DataBase" >
      <commandText>
        Insert into MyLog(Operator_name,Operator_Type,IP,DateTime,Operation) Values(@Operator_name,@Operator_Type,@IP,@DateTime,@Operation);
      </commandText>
      <parameter name = "@Operator_name" layout = "${event-context;item=Operator_name}"/>
      <parameter name = "@Operator_Type" layout = "${event-context;item=Operator_Type}"   />
      <parameter name = "@DateTime" layout = "${event-context;item=DateTime}"/>
      <parameter name = "@IP" layout = "${event-context;item=IP}" />
      <parameter name = "@Operation" layout = "${event-context;item=Operation}"   />

    </target>

  </targets>

  <rules>
     <logger name="*" minlevel="Trace " writeTo="LogOnlog"/>
  </rules>

**Comment by 304NotModified** [comment]
Are you sure there aren't m multiple nlog.config files, e.g. in the "bin" folder?

**Comment by tiger2014** [comment]
I have another NLog.config  file in another project in the same solution .Now I delete the NLog.config in another project . But when  running  the solution , 'Logger logger = LogManager.GetCurrentClassLogger();' has another erro :

‘LayoutRenderer cannot be found: 'event-context;item=Operator_name'’

**Comment by 304NotModified** [comment]
You need a `:` instead of `;`

**Comment by tiger2014** [comment]
I have replaced them already ,But still the erro .
And I finally find the reason by accident .The reason is that I must restart VS after I modified the NLog.config !! What a mess !

**Comment by tiger2014** [comment]
Is there any way to escape from restarting VS ?

**Comment by 304NotModified** [comment]
Restart is certainly not necessary. You can even [autoreload](https://github.com/nlog/nlog/wiki/Configuration-file#automatic-reconfiguration) the config

**Comment by tiger2014** [comment]
I add the 'autoReload' like this : 
'<nlog autoReload="true"
      xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">'
but if I modified the NLog.config ,I still need to recompile the solution to make it work .(I find restarting VS is not the  real cause, and real cause is must to recompile the solution)
