### ISSUE TITLE
Set property fileName in target by code

### ISSUE THREAD

**Issue by JinPachi** [NLog/NLog#620]
Hi all! Please help me.
How  set property fileName and archiveFileName from config Nlog by code?

**Comment by 304NotModified** [comment]
See 

https://github.com/nlog/nlog/wiki/Configuration-API

**Comment by JinPachi** [comment]
Thank you very much. But the only question:

root(see below, something direction), for example

<variable name = "root" value ="${basedir}"/>

  <targets>
    <target name="rotationByDate" xsi:type="File" layout="${verbose_inline}"
            
            fileName="root/"
            
            archiveFileName ="root/"
            archiveAboveSize="10000"
            archiveNumbering = "Rolling"
            maxArchiveFiles="10"/>
  </targets>


and then in code i try change root add part of path with file:
{
...
NLog.Layouts.Layout changeRoot = fileTarget.FileName + "\\" + "folder1" + "\\" + folder2+ "\\"  + nameFile + "--Today.log"; 

fileTarget.FileName = changeRoot;
}

**Comment by 304NotModified** [comment]
@JinPachi  please use [fenced code blocks](https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks) (syntax highlighting is preferred) in the GitHub issues. Thanks

**Comment by 304NotModified** [comment]
Closing this due to the lack of activity. Feel free to re-open.
