### ISSUE TITLE
Why <nlog autoReload="true"> not work ?

### ISSUE THREAD

**Issue by tiger2014** [NLog/NLog#621]
I add the 'autoReload' like this : 
'<nlog autoReload="true"
      xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">'
but if I modified the NLog.config ,I still need to recompile the solution to make it work .(I find restarting VS is not the  real cause, and real cause is must to recompile the solution)

I have mentioned it at https://github.com/NLog/NLog/issues/615

**Comment by Xharze** [comment]
Are you changing the config file through visual Studio?

**Comment by 304NotModified** [comment]
Your are probably editing the wrong file. (see also #615). Check your "bin" folder.

See also: https://github.com/nlog/nlog/wiki/Configuration-file#configuration-file-locations

**Comment by tiger2014** [comment]
Yes ,I changed the config file through visual Studio.

**Comment by tiger2014** [comment]
NLog.config in 'bin' had been edited also.

**Comment by Xharze** [comment]
Have the config in the bin folder been edited before the build?

**Comment by tiger2014** [comment]
I changed the config file through visual Studio. The config in the bin folder have not been edited before the rebuild.

**Comment by 304NotModified** [comment]
please read:
https://github.com/nlog/NLog/wiki/Configuration-file#configuration-file-locations

If you edit the nlog.config in visual studio, and on built it will be moved to the `bin` folder, that latter file will be read. Then editing the file, which is also in the `bin` folder, have only effect after an build.

**Comment by tiger2014** [comment]
Thank you ！

**Comment by 304NotModified** [comment]
No problem. I'm glad that the problem has been solved
