### ISSUE TITLE
Undocumented code

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#622]
I see a lot of documented code. A lot of methods don't have any documentation, even not the public ones. 

What are the guidelines? Is undocumented code fine? Or should be reject PR's with undocumented code?  Or do we only care if it has unit tests?

My proposal: public methods/properties should document: summary, parameters, output.. This will also count for methods that get touched in a PR (not only new). 
PR should keep to this guideline, otherwise reject. 

Your opinion please! :)

**Comment by Xharze** [comment]
I agree all public methods should have summary etc.

**Comment by 304NotModified** [comment]
added to https://github.com/NLog/NLog/blob/master/CONTRIBUTING.md
