### ISSUE TITLE
Release 3.2.1

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#623]
Split of from https://github.com/NLog/NLog/issues/574

Release 3.2.1 is a small patch release which is almost ready. 

See GitHub milestone:
https://github.com/NLog/NLog/milestones/3.2.1

**Comment by 304NotModified** [comment]
news post ready, preview:

https://github.com/NLog/NLog.github.io/pull/14

Comments/suggestions are welcome!

**Comment by Xharze** [comment]
Because of the issues with the stacktrace fix (#584) for v3.2.1 I was thinking about releasing with just #600 ? What do you think?

**Comment by 304NotModified** [comment]
I think #584 is far more important than #600 thus we should create a new PR

**Comment by 304NotModified** [comment]
new PR is created: #645

**Comment by 304NotModified** [comment]
@Xharze 

Can you release 3.2.1? All fixes are merged. Also I fixed the SMTP bug on this release. See https://github.com/NLog/NLog/issues?q=milestone%3A3.2.1+is%3Aissue+is%3Aclosed

I will create a news post for 3.2.1 when it's released.

**Comment by 304NotModified** [comment]
@Xharze are you still on vacation?

**Comment by Xharze** [comment]
@304NotModified Sorry, I missed the message about the last bugfixes were done. I'll try to create the release tomorrow.

**Comment by 304NotModified** [comment]
@Xharze maybe it's a idea to write down the steps to publish a release? So I could help in publishing a new release.

**Comment by 304NotModified** [comment]
3.2.1 has been released
