### ISSUE TITLE
Windows Phone 8.1 support?

### ISSUE THREAD

**Issue by WiteCastle** [NLog/NLog#624]
I haven't been able to find any reliable information on this, but does/will nLog support Windows Phone 8.1 (WinRT)? I've read some blog posts that say it's kind of difficult and some people have said to just use System.Diagnostics.WriteLine(). I've also tried installing the newest version but it doesn't target WP8.1. Any word on support?

**Comment by 304NotModified** [comment]
Windows phone (8) support will be in 4.0 https://github.com/NLog/NLog/pull/389
