### ISSUE TITLE
wpf application with logfile per layer & static log

### ISSUE THREAD

**Issue by Anatl** [NLog/NLog#625]
1) I have an WPF application with multiple code layers.I want each layer to have a different log file. 
 I understant that NLog does not support multiple Nlog config files. 
so how can I achieve that?

2) I want my Converter classes (in Wpf) to have access to NLog class (maybe static - because the converter does not have a constructor) - how can I achieve that? 

Thank you very much, Anat

**Comment by 304NotModified** [comment]
2) 

You can create a `static` field?

```c#
private static readonly Logger _logger = LogManager.GetCurrentClassLogger();
```

**Comment by 304NotModified** [comment]
Another example for 1

https://github.com/NLog/NLog/wiki/File-target#per-level-log-files

You can use any layout renderer for this!

**Comment by Anatl** [comment]
Hi, 
thank you for the reply!
I know I can have multiple targets. the problem is if I have two targets with the same minimum level, there will be multiple prints in both files. I want two different files entirely, each file print logs of a different code level.

**Comment by 304NotModified** [comment]
Thats also possible with the maxlevel attribute. See wiki.

**Comment by 304NotModified** [comment]
https://github.com/NLog/NLog/wiki/Configuration-file#rules

**Comment by Anatl** [comment]
so the only way to have separate logs is  to limit each log to one level?

**Comment by 304NotModified** [comment]
You can create multiple log files on many conditions, not only levels. 

There are 3 options:

1. Use one or multiple [layout renderes](https://github.com/NLog/NLog/wiki/Layout-Renderers) in your filename. E.g. `  <target name="f2" xsi:type="File" fileName="${logger}.txt"/>  `
2. Use multiple targets with multiple loggerrules
E.g. 
```
 <target name="f1" xsi:type="File" fileName="file1.txt"/>
  <target name="f2" xsi:type="File" fileName="file2.txt"/>  

...
 <logger name="*" minlevel="Trace" maxlevel="Error" writeTo="f1"/>
 <logger name="*" writeTo="f2" />

```
Then [final](https://github.com/NLog/NLog/wiki/Configuration-file#rules) attribute and the [where filters](https://github.com/NLog/NLog/wiki/When-filter) can be usefull.

3. Use a combination of 1 and 2!

**Comment by joshgo** [comment]
If you set the *name *of the logger to the fully qualified name of a class,
you can direct logs of a specific class to a specific file.

Example

<target name="f1" xsi:type="File" fileName="file1.txt"/>
<target name="f2" xsi:type="File" fileName="file2.txt"/>
<target name="f3" xsi:type="ColoredConsole" />
...

<logger name="Name.Space.Class1" levels="Debug,Error" writeTo="f1" />
 <--- Class1 will go to file1.txt
<logger name="Name.Space.Class2" levels="Debug,Error" writeTo="f2" />
 <--- Class2 will go to file2.txt
<logger name="Name.Space.*" levels="Debug,Error" writeTo="f3" />
<--- Class1 and Class2 will also log to console




On Thu, Mar 5, 2015 at 8:35 AM, Julian Verdurmen <notifications@github.com>
wrote:

> You can create multiple log files on many conditions, not only levels.
>
> There are 3 options:
>
>    1. Use one or multiple layout renderes
>    <https://github.com/NLog/NLog/wiki/Layout-Renderers> in your filename.
>    E.g. <target name="f2" xsi:type="File" fileName="${logger}.txt"/>
>    2. Use multiple targets with multiple loggerrules E.g.
>
>  <target name="f1" xsi:type="File" fileName="file1.txt"/>
>   <target name="f2" xsi:type="File" fileName="file2.txt"/>
>
> ...
>  <logger name="*" minlevel="Trace" maxlevel="Error" writeTo="f1"/>
>  <logger name="*" writeTo="f2" />
>
>
> Then final <https://github.com/NLog/NLog/wiki/Configuration-file#rules>
> attribute and the where filters
> <https://github.com/NLog/NLog/wiki/When-filter> can be usefull.
>
>    1. Use a combination of 1 and 2!
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/NLog/NLog/issues/625#issuecomment-77364100>.
>



-- 
"Collecting data is only the first step toward wisdom,
 but sharing data is the first step toward community,"
  - Henry Louis Gates Jr (Harvard scholar)

**Comment by Anatl** [comment]
thank you joshgo!

can i do the same thing to a project?
My solution has more than one project, I want to log each project to a different path.
 can I write in the "name" field the path to a project?

thanks.

**Comment by 304NotModified** [comment]
Yes you can use `*` for that. 

E.g. `name="mylib1.*"`

**Comment by 304NotModified** [comment]
https://github.com/nlog/nlog/wiki/Configuration-file#example-rules

**Comment by Anatl** [comment]
thanks.
Now I ran into another problem:
as I said I have more then one project in the same solution.
in one of the projects I do the following (building the config file) -
LoggingConfiguration config = new LoggingConfiguration();
NLog.Configuration = config ;

then while the app is running I get to the a different project where i check if NLog.Configuration is null (because i need to add rules to the config). but for some reason it returns null. I understand that there is only one config file that i already built before so what have i done wrong?

**Comment by Anatl** [comment]
FileTarget myFileTarget= new FileTarget.....
LoggingRule rule = new LoggingRule("MyNameSpace.*", LogLeve.Info, myFileTarget)

now no log is printed!
what have I done wrong?

**Comment by 304NotModified** [comment]
Please try without namespace filter first.

**Comment by 304NotModified** [comment]
Closing the issue because of inactivity. If the issue isn't resolved, feel free to re-open.
