### ISSUE TITLE
Add args overload to the Exception methods

### ISSUE THREAD

**Issue by Xharze** [NLog/NLog#63]
All of the logger methods have an overload for (string message, params object[] args) EXCEPT the various Exception methods. That means I have to code something like this:

```
logger.FatalException(string.format("asfaf{0} {1}", var1, var2), exceptionVariable)
```

I'd prefer to have an overload of (Exception exception, string message, params object[] args). Then I could write my exception logging like this:

```
logger.FatalException(exceptionVariable, "asfaf{0} {1}", var1, var2)
```

I assume this overload is not present to avoid possible FormatException errors in the Exception logging process. That is to prevent problems in case the developer doesn't have the correct number of args like this:

```
logger.FatalException(exceptionVariable, "asfaf{0} {1} {2}", var1, var2)
```

or typos a brace like this:

```
logger.FatalException(exceptionVariable, "asfaf{0} {1]", var1, var2)
```

Those issues could be handled with a wrapper similar to the code below.

```c#
//wrapper to prevent string format mask/argument errors
private static string SafeStringFormat(string formatMask, params object[] formatArgs)
{
    string toReturn = string.Empty;
    try
    {
        toReturn = string.Format(formatMask, formatArgs);
    }
    catch (FormatException ex)
    {
        int index = 0;
        StringBuilder sb = new StringBuilder();
        sb.AppendFormat("Format Mask: {0}\n", formatMask);
        foreach (object arg in formatArgs)
        {
            sb.AppendFormat("{0}: {1}\n", index, arg.ToString());
            index += 1;
        }
        toReturn = sb.ToString();
        logger.Error("FormatMask or args are incorrect (check for matching braces)\n {0}", toReturn);
    }
    return toReturn;
}
```

**Comment by 304NotModified** [comment]
This is implemented by #691
