### ISSUE TITLE
When the filter is set to 'log' it's always logging regardless of the condition

### ISSUE THREAD

**Issue by jweidner711** [NLog/NLog#633]
I'm trying to apply a filter as shown below:

    <logger name="*" minlevel="Debug" writeTo="logfile">
       <filters>
         
         <when condition="length('${message}') > 10" action="LogFinal" />
       </filters>
    </logger>

If I set the action to Ignore then it works.  All log entries that meet the condition are ignored.  But when I set the action to Log or LogFinal, it logs everything.  For example, I have a log message that outputs "123456789".  That message is logged even though the length is < 10.  Also for the condition above that is filtered out, it doesn't matter what the text begins with.  Everything is logged even though I'm only asking for the entries that begin with button.  And yes, my 2nd length condition was NOT in the config file when testing the first.  All other loggers have been commented out as well.

**Comment by 304NotModified** [comment]
Is it possible to create a unit test for this? That would really help to fix the bug.

**Comment by ilya-g** [comment]
I don't think it's a bug.

When an event is not matched by any of `when` filters, it's classified as `FilterResult.Neutral` thus being logged.

To log only those events that match some condition, add a match-all condition as the last, having its action set to `Ignore` or `IgnoreFinal`:

     <when condition="true" action="Ignore" />

**Comment by 304NotModified** [comment]
I think @ilya-g is correct. Thanks!

**Comment by jweidner711** [comment]
Yep.  That's what is was.  I had no idea that it worked that way - good to know.  Thanks ilya-g!
