### ISSUE TITLE
DatabaseTarget tries to connect to local MSSQL DB if no connection string is configured

### ISSUE THREAD

**Issue by realityexists** [NLog/NLog#634]
NLog 3.2.0

If I configure a DatabaseTarget without a connectionString nor a connectionStringName, like this:
```xml
    <target name="database" xsi:type="Database" keepConnection="true" commandText="..." />
```
there is a noticeable delay when I try to log. It turns out that it's trying to connect using provider name "sqlserver" and connection string "Server=.;Trusted_Connection=SSPI;"! I would expect this to throw a configuration exception.

**Comment by 304NotModified** [comment]
I think this the default of ado.net or the first  connectionstring (possible inherited) in your config.

**Comment by realityexists** [comment]
I don't have any MSSQL connection strings, so yes, it probably is some ADO.NET default. But it's undoubtedly unexpected behaviour. The delay as it times out is bad enough, but what if that database actually existed and suddenly it had log messages in it, without the user configuring them to go there?

**Comment by 304NotModified** [comment]
Just looked at this.

We cannot easily require `connectionString` because a use could use other properties for that like `DBUserName` etc

Current code

```c#
       private string BuildConnectionString(LogEventInfo logEvent)
        {
            if (this.ConnectionString != null)
            {
                return this.ConnectionString.Render(logEvent);
            }

            var sb = new StringBuilder();

            sb.Append("Server=");
            sb.Append(this.DBHost.Render(logEvent));
            sb.Append(";");
            if (this.DBUserName == null)
            {
                sb.Append("Trusted_Connection=SSPI;");
            }
            else
            {
                sb.Append("User id=");
                sb.Append(this.DBUserName.Render(logEvent));
                sb.Append(";Password=");
                sb.Append(this.DBPassword.Render(logEvent));
                sb.Append(";");
            }

            if (this.DBDatabase != null)
            {
                sb.Append("Database=");
                sb.Append(this.DBDatabase.Render(logEvent));
            }

            return sb.ToString();
        }

```

**Comment by realityexists** [comment]
Looks like DBDatabase doesn't have a default, so perhaps it would make sense to throw an exception if ConnectionStringName, ConnectionString and DBDatabase are all null/empty?

I don't know whether the MSSQL provider has some default database when connecting via "Trusted_Connection=SSPI;", but I'd be very surprised if any user relied on their NLog database target working without setting any connection properties at all! Even if it's technically possible for it to work, I'd say there's a 99% chance they simply forgot to configure it (like I did).

**Comment by 304NotModified** [comment]
Well I'm also not sure if empty values could be used.

**Comment by 304NotModified** [comment]
Thanks for the report, but due to unknown impact we will not change this behavior.

Also from the wiki:

> connectionString - Connection string to run the command against. If not provided, connection string from the target is used. 

With a wrong connectionstring (not only empty), you get also a delay. We cannot prevent that.
