### ISSUE TITLE
File missing for NLog2 Mono build

### ISSUE THREAD

**Issue by MichaelGG** [NLog/NLog#635]
On the downloads page at https://github.com/NLog/NLog/downloads, the link for Mono goes to https://github.com/downloads/NLog/NLog/NLog2.mono2.zip which does not seem to exist.

NLog 3.2 "doesn't work" out of the box on Mono, at least using the normal .NET build. V2 appears to work fine using the .NET v4 binaries. I installed Mono on a Windows machine to try to build, but couldn't figure out how to set the install directory properly.

I'm thinking that perhaps there should be a note added that for Mono, one can use the net4 NLog2 binaries. Or, if someone has a working v3.2 build of NLog, a link to that would be rather helpful.

**Comment by 304NotModified** [comment]
It's bit strange that the file is gone.

Too bad you build server wont run Mono, yet. I also don't know to run Mono (Windows, VIsual studio?)

**Comment by 304NotModified** [comment]
You can find the mono builds overhere:

https://nlog.codeplex.com/releases/view/32639

@Xharze can you upload this to github? Or can I do that?

**Comment by 304NotModified** [comment]
We should create a new issue for "NLog 3.2 "doesn't work" out of the box on Mono"

**Comment by MichaelGG** [comment]
Thanks for the pointer to the builds; I will try them out. If you need access to a Linux machine setup with Mono 3.12 I'd be happy to cover it for a few months.

**Comment by 304NotModified** [comment]
I tried mono on Windows today, but got strange errors. Something missing  in the solution file.

**Comment by MichaelGG** [comment]
I’d suggest building in Visual Studio, then just running/deploying with Mono. No need to deal with xbuild and all that. I’ve been doing that in production for many years and it seems much easier than using Mono’s build tools.

**Comment by 304NotModified** [comment]
Well I like built errors rather than runtime errors.

**Comment by MichaelGG** [comment]
Sure but solution-related errors, at least in my experience, aren’t actually runtime errors. I recently moved an app over from IIS to FastCGI and none of the myriad issues would have been caught by compiling for Windows. But I certainly won’t object to having a full Mono native build ! :)

**Comment by 304NotModified** [comment]
I have removed the broken links on the Github downloads section (which is legacy).

Note: the nlog website links (correctly) to Codeplex for the old downloads: http://nlog-project.org/download/

I will create a new ticket for the Mono build, so I can close this one.

**Comment by MichaelGG** [comment]
Thank you!
