### ISSUE TITLE
Trying to use length condition doesn't allow less than '<'

### ISSUE THREAD

**Issue by jweidner711** [NLog/NLog#636]
When trying to use the length condition as follows:

```
<when condition="length('${message}') < 10" action="Log"/>
````

I get an error in my config file.  It doesn't like the less than character because it thinks its a beginning of a new tag and I obviously haven't yet closed my beginning tag from the 'when'.  Changing this to a greater than character works fine.

**Comment by 304NotModified** [comment]
Please use 

https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks

**Comment by jweidner711** [comment]
I'm not sure what you are suggesting.  Below is my code example from my XML config file:

<when condition="length('${message}') < 10" action="Log" />

This should be a valid condition.  But Intellisense is compaining with the less than '<'.  It's confusing it with an opening tag.  The following statement works:

<when condition="length('${message}') > 10" action="Log" />

Intellisense has no issue with this because I assume it thinks the the greater than symbol is a close tag.

**Comment by 304NotModified** [comment]
Just use the backticks. I edited your post, but that was difficult from mobile yesterday.

Is Intellisense just buggy, or isn't not working?

**Comment by jweidner711** [comment]
It isn't working.  For this example, I'l logging the word 'short'.  If I change the < 10 to  = 5 it works.  Otherwise with the < 10 I get no log file at all.  So I'm assuming the "error" in the config file causes nothing to be logged.

**Comment by 304NotModified** [comment]
And does `>` work?

**Comment by jweidner711** [comment]
Yes.  Greater than works fine.

**Comment by 304NotModified** [comment]
Did you checked the internal log file? 

This is a weird bug and I don't get it why Intellisense would complain.

**Comment by jweidner711** [comment]
Where is the internal log file?

**Comment by 304NotModified** [comment]
https://github.com/nlog/nlog/wiki/Logging-troubleshooting#internal-logging

**Comment by jweidner711** [comment]
I ran it with the following settings:

`<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
`      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
`      internalLogFile="c:\internal_log_file.txt"
`      internalLogLevel="Trace"
`      internalLogToConsole="true">

I got no log file and nothing was written to the console.

**Comment by 304NotModified** [comment]
On trace level, nlog writes a lot to the internal log. So maybe your config is xml invalid or this is a permission problem?

**Comment by jweidner711** [comment]
The 'less than' error is causing the log not to be created.  I came in this morning and the ONLY change I made was replacing the less than with the greater than.  I reran my test and got the trace messages in the console as well as the interal_log_file.txt file.  Apparently, the error in the config file (the less than symbol), causes NLog to not do anything.

**Comment by 304NotModified** [comment]
You need to escape the `<`  I was under the impression this wasn't needed with attributes, but I was wrong. 

http://stackoverflow.com/questions/5709232/how-do-i-include-etc-in-xml-attribute-values

**Comment by jweidner711** [comment]
Thank you!  That worked!  Thanks for all your time.

**Comment by 304NotModified** [comment]
NP!

It would be great if you could improve the wiki docs :)

**Comment by jweidner711** [comment]
I added a note on the conditions page.

**Comment by 304NotModified** [comment]
Thanks!
