### ISSUE TITLE
Problem same as #110: Exception are swallowed even if throwExceptions = true with LogReceiverService

### ISSUE THREAD

**Issue by pmarcinkowski** [NLog/NLog#637]
I have NLog 3.2.0.0 and same problem as in https://github.com/NLog/NLog/issues/110.
Has this issue been already fixed ?

**Comment by 304NotModified** [comment]
It should be

This case would be easy to write an unit test to confirm it. Could you do that?

**Comment by Xharze** [comment]
Could you explain when the exception is swallowed? I can't locate the code responsible for swallowing the exception, making it hard to fix without more information

**Comment by 304NotModified** [comment]
note: when `throwExceptions = true`, then most of the time the exception is not logged to the internal log.

**Comment by 304NotModified** [comment]
I think the issue is in LogReceiverWebServiceTarget? There are two `catch`es and the rethrow in not all the cases and it's unclear how the "continuations" are handling the exceptions (throwing? Logging?)
