### ISSUE TITLE
How to remove line breaks from a stack trace output?

### ISSUE THREAD

**Issue by aturlov** [NLog/NLog#640]
When logging a stack trace together with an exception the most useful output is produced by `${exception:format=StackTrace}`. In the output all the stack trace steps are separated by a line break which is OK for human reading but presents problems with machine parsing like LogEntries, for example that treats a line break in the log file like a new log entry (wrong in this case). 

I would like to completely remove from or replace the line breaks in the stack trace output. I have tried to use the `${replace}` layout wrapper but unsuccessfully because it does not recognize `\\n\r` as special characters even when in regex mode. I don't want to develop my own layout renderer for that as it seems like an overkill. Any suggestions?

**Comment by 304NotModified** [comment]
Check the format option. It's already implemented :)
https://github.com/nlog/NLog/wiki/Stack-Trace-Layout-Renderer

**Comment by aturlov** [comment]
Thanks for a reminder which is not necessary assuming one takes time to read the documentation. Both options *Flat* and *DetailedFlat* do not generate **USEFUL** output (read the original question carefully). The *RAW* option (which is useful) is a multiline string which is my problem exactly. The option *separator* does not affect the *RAW* output and the ${replace} wrapper is not helpful as mentioned above. Suggestions?

**Comment by 304NotModified** [comment]
What do you mean with your first sentence?

I'm pretty sure that the `${replace}` with newlines should work. I think `\n` should be enough. If not, I will unit test this and it should be fixed.

**Comment by aturlov** [comment]
I have tested `${replace}` with many different patters including `\n` but it looks for the string `\n` instead of a special character. I was not able to find a `searchFor` value that removed line breaks from the output that's why I am saying it'snot helpful. If you can suggest a pattern that works I'll be happy to try and report back.

First sentence has no hidden meaning. I thanked you for a reminder to check out the docs before asking a question and also suggested the default assumption should be that one does that and not the opposite.

**Comment by 304NotModified** [comment]
Assumptions are the root of all evil.

I try to be as helpfull as possible but I'm limited in time.

**Comment by 304NotModified** [comment]
Can you try `\\n`?

See https://github.com/NLog/NLog/blob/master/tests/NLog.UnitTests/LayoutRenderers/Wrappers/ReplaceTests.cs

**Comment by 304NotModified** [comment]
Related feature request: https://github.com/NLog/NLog/issues/86

**Comment by 304NotModified** [comment]
`\\n` works, as seen in the unit test. Closing this one.
