### ISSUE TITLE
How to log Exception.Data

### ISSUE THREAD

**Issue by AMgdy** [NLog/NLog#642]
How can I let NLog layout out of the box to log the exception data?

```csharp
try
{
    var fileNotFoundException = new FileNotFoundException("Can't locate the file");
    fileNotFoundException.Data["FilePath"] = "PATH TO THE FILE";
    fileNotFoundException.Data["UserNmae"] = "MyUserName";
    fileNotFoundException.Data["TimeStamp"] = DateTime.Now.ToString("O");
    throw fileNotFoundException;
}
catch (Exception e)
{
    Logger.Fatal("Unexpected error: " + e.Message, e);
    throw;
}
```

**Comment by aturlov** [comment]
Your example is good enough and should work. Read about a recommended approach here https://github.com/NLog/NLog/wiki/How-to-log-exceptions

**Comment by AMgdy** [comment]
@aturlov this method does not log the [Exception.Data] (https://msdn.microsoft.com/en-us/library/system.exception.data.aspx)

**Comment by aturlov** [comment]
You can also log separate parts of an exception object using different formats with the `${exception}` layout renderer like this `${exception:format=Data}`. Look here for more information https://github.com/nlog/NLog/wiki/Exception-Layout-Renderer

**Comment by 304NotModified** [comment]
Thanks @aturlov !

**Comment by AMgdy** [comment]
Thank you @aturlov
