### ISSUE TITLE
Unable to log to Kestrel console on Linux (Mono)

### ISSUE THREAD

**Issue by sjwoodard** [NLog/NLog#647]
I'm using NLog 3.2.0.0 from NuGet on Visual Studio CTP 6 and everything works properly on Windows, but when I try to log to console on Linux using Kestrel and the .NET 5 Docker container (runs on Mono) then nothing happens. Using Console.WriteLine works as expected though.

I haven't had a chance to dive in to this yet, but I wanted to open an issue for future use.

**Comment by 304NotModified** [comment]
Hi,

NLog currently won't work on Mono. Also, to bad, I haven't any experience with Mono. If you would try to get the code building on Mono, please create a PR!

See also https://github.com/NLog/NLog/issues/648

**Comment by sjwoodard** [comment]
OK, thanks. Just to clarify, .NET 5 is actually supposed to run native on Linux, and using Mono is a temporary solution for testing until the full release. I will look into this though.

**Comment by 304NotModified** [comment]
Correct me if wrong, but for .NET 5 on Mono we need CoreCLR support? (note #641)

**Comment by sjwoodard** [comment]
Yes, you're right - this is a bigger issue than I realized. I originally thought the full .NET 5 stack was going to be available on Linux. I'm just having my first look at the Core CLR, and see if I can contribute anything.

I'm going to close this in favor of #641, since I think resolving that would resolve this issue as well. Thanks!
