### ISSUE TITLE
API documentation with Sandcastle Help File Builder

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#655]
Create the API documentation with Sandcastle Help File Builder (SHFB) instead of the old Sandcastle.

Should fix: #578

**Comment by sean-gilliam** [comment]
@304NotModified Do you want a shfbproj targeting each solution file (mono2, netfx35, netfx40...) or for an overall solution (e.g. netfx45)?

**Comment by 304NotModified** [comment]
Good question. 

A different for mono and .Net would be great. But the mono build isn't working  yet

**Comment by 304NotModified** [comment]
So I think first netfx45 would be a good start

**Comment by 304NotModified** [comment]
3.2.1 docs are with SHFB. http://nlog-project.org/documentation/v3.2.1/html/R_Project_NLog.htm

Next step is to make the config reusable and commit to GitHub

**Comment by 304NotModified** [comment]
Also nice to have: logo + more namespace descriptions

**Comment by 304NotModified** [comment]
To do:  fix link to wiki.  example link below at
http://nlog-project.org/documentation/v3.2.1/html/T_NLog_Targets_DatabaseTarget.htm

**Comment by ie-zero** [comment]
I also spotted that the class version appears as below
```Assembly: NLog (in NLog.dll) Version: 0.0.0.0```

**Comment by 304NotModified** [comment]
Yes,  good notoced

That's because in history we used a msbuild project to call shfb.  

I haven't much experience with msbuild projects, but maybe we should fix it.

**Comment by ie-zero** [comment]
I have not got much experience msbuild projects but it would be useful to learn.  

I would like to see your build if you do not mind in case I can help.

**Comment by 304NotModified** [comment]
:)

I will give you more info this weekend.

**Comment by 304NotModified** [comment]
The information :)

The current Sandcastle Help File Builder files are at:
`NLog\src\Docs\Frameworks`

You can build the docs with 
`msbuild NLog.proj /t:rebuild /t:BuildIndividualDocumentation  /p:BuildLastMajorVersion=4.0.0 /p:AssemblyFileVersion=4.1.2 /p:BuildVersion=4.1.2 /p:configuration=release /p:BuildLabelOverride=NONE
`

The target
```xml
  <Target Name="BuildIndividualDocumentation">
    <Exec Command='"$(WinDir)\Microsoft.NET\Framework\v3.5\MSBuild.exe" Docs\NLog.shfbproj /p:Framework="%(TargetFramework.Identity)" /p:Configuration=$(Configuration) /p:BuildLabel="$(BuildLabel)" /p:BuildVersion="$(BuildVersion)"' ContinueOnError="$(BuildAllFrameworks)" />
  </Target>
```

My tryout was: https://github.com/304NotModified/NLog/blob/new-SHFB/src/Docs/NLog%204.0.shfbproj

But it was missing the variables (didn't know how to build the docs firstly).

Also it's not integrated in the .proc, which is preferred after all.

**Comment by 304NotModified** [comment]
This is done already
