### ISSUE TITLE
Not logging when user not authenticated

### ISSUE THREAD

**Issue by SergeyBan** [NLog/NLog#658]
I have the issue. I'm using NLog on my web site. There is required to authenticate on site to use it. But there is one URL which can be opened without authentication (this is work flow). When user not authenticated, then logging is not working. No items saved to DB. What's wrong?

**Comment by 304NotModified** [comment]
Hi,

What authentication method do you use? (forms, windows). Do you use impersonation? 

And did you checked the internal log?

**Comment by SergeyBan** [comment]
I use forms authentication.
What do you mean by internal log?

**Comment by 304NotModified** [comment]
https://github.com/NLog/NLog/blob/master/CONTRIBUTING.md#bug-reports

**Comment by 304NotModified** [comment]
Closing this issue due to the lack of activity. Feel free to re-open.
