### ISSUE TITLE
Custom log type (ex. Fluent.Log.Feature("x"))

### ISSUE THREAD

**Issue by niemyjski** [NLog/NLog#659]
I was trying to extend nlog and add our own fluent extension method but can't because the log class is static

```csharp
        public static LogBuilder Feature(this Log log, string feature) {
            var builder = new LogBuilder(LogManager.GetCurrentClassLogger());
            builder.ContextProperty("@type", "feature");
            builder.Message(feature);
            return builder;
        }
```

Is there a good way to go about extending this?

**Comment by 304NotModified** [comment]
Yup should extend the logbuilder In the fluent namespace. see: https://github.com/NLog/NLog/blob/master/src/NLog/Fluent/LogBuilder.cs

**Comment by niemyjski** [comment]
Yeah I've done that in other spots, but I don't want to do Log.Info().Feature("x"), I want to be able to just do Log.Feature("x") to create the builder.

**Comment by 304NotModified** [comment]
Or just extensions on Logger is also possible

**Comment by niemyjski** [comment]
Do you have an example of this?

Thanks
-Blake Niemyjski

**Comment by 304NotModified** [comment]
Not in GitHub or easy with typing on mobile ;)

**Comment by 304NotModified** [comment]
An example:

Extension:

```C#
public static Logger AddToThreadContext(this Logger logger, string key, object value)
{
    MappedDiagnosticsContext.Set(key, value == null ? null : value.ToString());
    return logger;
}
```

Call

```C#
var logger = LogManager.GetCurrentClassLogger();
logger.AddToThreadContext("sessionGuid", g);
logger.Debug("test");

```

**Comment by niemyjski** [comment]
I'm using the fluent logger though, NLog.Fluent.Log.Feature("You can't do this").Write();

**Comment by 304NotModified** [comment]
Yes, you are right. I will create a new example.

**Comment by 304NotModified** [comment]
What about this?

Extension:

```C#
public static LogBuilder FeatureX(this ILogger logger, string feature)
{
    var logLevel = feature == "noproblem" ? LogLevel.Trace : LogLevel.Error;
    var builder = new LogBuilder(logger, logLevel);
    return builder;
}
```

Call

```C#

var logger = LogManager.GetCurrentClassLogger();
logger.FeatureX("test").Property("a", "b").Write();
        

```

**Comment by 304NotModified** [comment]
Does the example resolve your question?

**Comment by niemyjski** [comment]
That would work but we don't use it that way. We use NLog.Fluent.Log without getting the current logger from the log manager, which is much cleaner.

**Comment by 304NotModified** [comment]
That's possible but you lose control of the logger name. It won't recommend it.

**Comment by niemyjski** [comment]
Can you show me how you did it? It's a static class and so I couldn't get the extension method to work. I don't know why I would care about the logger name as I only have a single app I'm integrating with.

**Comment by 304NotModified** [comment]
Sorry for closing, But I was under the impression that you solved it:
> We use NLog.Fluent.Log without getting the current logger from the log manager, which is much cleaner.

The usage of one Logger is easy possible with some C#

E.g. Create a static public property in a public static class.

```C#

public static class GlobalLogging
{
    public static Logger Logger = LogManager.GetCurrentClassLogger();
}

public class Test
{
    public void TestMethod()
    {
        GlobalLogging.Logger.FeatureX("test").Property("a", "b").Write();
    }
}

```

**Comment by niemyjski** [comment]
Yes, I could do this but I'm using the built in functionality and want
to extend an already singleton (leaving my code cleaner)

On 4/23/15, Julian Verdurmen <notifications@github.com> wrote:
> Sorry for closing, But I was under the impression that you solved it:
>> We use NLog.Fluent.Log without getting the current logger from the log
>> manager, which is much cleaner.
>
> The usage of one Logger is easy possible with some C#
>
> E.g. Create a static public property in a public static class.
>
> ```C#
>
> public static class GlobalLogging
> {
>     public static Logger Logger = LogManager.GetCurrentClassLogger();
> }
>
> public class Test
> {
>     public void TestMethod()
>     {
>         GlobalLogging.Logger.FeatureX("test").Property("a", "b").Write();
>     }
> }
>
> ```
>
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/NLog/NLog/issues/659#issuecomment-95687502


-- 
Thanks
-Blake Niemyjski

**Comment by 304NotModified** [comment]
Extending the current class is in my opinion not clean. It will be too much coupled.

**Comment by 304NotModified** [comment]
I would recommend to read:
https://en.wikipedia.org/wiki/Cross-cutting_concern

And then you will see that using `LogManager.GetCurrentClassLogger()` in every `class` would be wise (just one, as a `static` `private` property)

**Comment by niemyjski** [comment]
I'm trying to put my extensions on a fluent class that everyone is
already using. We distribute our module on nuget and people want to
use it in this manner.. This is why I'm asking.

On 4/23/15, Julian Verdurmen <notifications@github.com> wrote:
> Extending the current class is in my opinion not clean. It will be too much
> coupled.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/NLog/NLog/issues/659#issuecomment-95689742


-- 
Thanks
-Blake Niemyjski

**Comment by 304NotModified** [comment]
Can you post some more examples what you're trying to achieve?

Because I don't fully understand why the previous posted solutions aren't sufficient.

**Comment by niemyjski** [comment]
We have a service called Exceptionless that has many clients that report logs, feature usages and errors to us. We have an nlog target and extensions (https://github.com/exceptionless/Exceptionless.Net/blob/master/Source/Platforms/NLog/LogBuilderExtensions.cs) that reports to us and we use it for that same purpose too: https://github.com/exceptionless/Exceptionless/blob/master/Source/Api/Controllers/EventController.cs#L142-L148

This works great for for logging log messages and errors (Log.Error().Exception(ex).Write()) but really fails when I want to log a feature... To me it's really ugly to have to do something like Log.Info().Feature("x").Write(); It would be much prettier to be able to do Log.Feature("x").Write() even if that under the hood was calling Log.Info();

**Comment by 304NotModified** [comment]
Is `Log` a variable or (static?) class?

**Comment by 304NotModified** [comment]
Ok it's the static class in NLog.  Now I'm confused: you are trying to write custom logic, but don't using an own (static) class.  You can't do both.  

IMO you should:

- create your own static class and probably delegate the current Log class. This could be also `Log` but n your namespace.  Or
- write extensions on LogBuilder, or
- write extentions on Logger

You can't extend the Log class because it's static, and that's a good thing (from the point of view of encapsulation)

**Comment by 304NotModified** [comment]
PS It would be possible if we could write extensions methods on static classes in C#

**Comment by niemyjski** [comment]
Yes I know this but end users are still using this old static class and I just wanted it to feel natural. I guess I should close this cause it won't be possible. Thanks for your help.

**Comment by 304NotModified** [comment]
OK, NP
