### ISSUE TITLE
Missing C++ Header

### ISSUE THREAD

**Issue by AlexandrePTJ** [NLog/NLog#660]
Hi,

From the website, there is some information telling C++ and even COM is supported. However I don't find any headers or documentation about it.

Thanks for help.

**Comment by 304NotModified** [comment]
I'm sorry but the website info is old dated.

Version 2 is the latest version with support for C++

https://github.com/NLog/NLog/tree/v2.0.1/src/NLogC

**Comment by AlexandrePTJ** [comment]
Oh I see. Would it be very complicated to port to 3.x ?

**Comment by 304NotModified** [comment]
I don't think so, but the build server won't build c++ projects afaik.

**Comment by 304NotModified** [comment]
PS the site is updated

**Comment by Xharze** [comment]
I don't know how much work is required to support C++ again. The reason support was dropped was that this feature wasn't used that much, and the amount of work in maintaining it didn't match the usage.
I think the best way to support C++ again, is to create a new repository with the needed implementations, but I don't think it will be an official NLog repository, as this would require maintenance by the NLog team

**Comment by AlexandrePTJ** [comment]
I understand. However I create a light wrapper to call only functions I need. Thanks for your help.
