### ISSUE TITLE
NuGet package version mismatch 3.2.0 vs 3.2.0.0

### ISSUE THREAD

**Issue by niklaslundberg** [NLog/NLog#661]
The package is defined as 3.2.0 at nuget.org but when downloading the NuGet package from the NuGet.exe command line tool, version 2.8.60318.667, the version defined in the NLog.nuspec file within the NuGet file has version 3.2.0.0. It should be 3.2.0.

**Comment by 304NotModified** [comment]
Thanks for the report. We don't like to change the nuget package, but we won't make the same mistake with 3.2.1

**Comment by Xharze** [comment]
As @304NotModified described this will be corrected in future versions
