### ISSUE TITLE
NLog 3.2.0.0 does not work with two log wrappers

### ISSUE THREAD

**Issue by AceHack** [NLog/NLog#662]
If you write a log wrapper and give it the correct declaring type it works fine as long as there is only one wrapper.  If you have two wrappers it stops at the first one even if you give it a declaring type of the second one.  This does not happen on v3.1.0.0.  Please fix.

**Comment by 304NotModified** [comment]
Hi, 

can you please give a config example etc, described at https://github.com/NLog/NLog/blob/master/CONTRIBUTING.md#bug-reports ?

**Comment by 304NotModified** [comment]
Closing this because we need more info. Feel free to re-open.

**Comment by AceHack** [comment]
class InnerLoggerWrapper
    {
        public Type BoundaryType { get; set; }
        private readonly Logger _logger;

        public InnerLoggerWrapper(string name)
        {
            BoundaryType = typeof (InnerLoggerWrapper);
            _logger = LogManager.GetLogger(name);
        }

        public void Log(string message)
        {
            _logger.Log(BoundaryType, new LogEventInfo(LogLevel.Debug, _logger.Name, message));
        }
    }
    class OuterLoggerWrapper
    {
        private readonly InnerLoggerWrapper _inner;

        public OuterLoggerWrapper(string name)
        {
            _inner = new InnerLoggerWrapper(name) {BoundaryType = typeof (OuterLoggerWrapper)};
        }

        public void Log(string message)
        {
            _inner.Log(message);
        }
    }
    class Program
    {
        static void Main(string[] args)
        {
            var l = new OuterLoggerWrapper("test");
            l.Log("test");
            Console.ReadKey(true);
        }
    }

This output's "ConsoleApplication1.Program.Main test" with nlog version 3.1 which is correct.

This output's "ConsoleApplication1.InnerLoggerWrapper.Log test" with nlog version 3.2 which is wrong.

**Comment by AceHack** [comment]
I'm not sure how to re-open, I will create another ticket.
