### ISSUE TITLE
How to reset the configuration for its default values in nlog.config

### ISSUE THREAD

**Issue by ronydj** [NLog/NLog#663]
Hi Guys,

I have the following scenario:

I am logging with the configuration automatically loaded from the config file. At runtime I change the fileName configuratio. After some time I want to reset the configuration fot its default values from the nlog.config.

How can I do it? In log4net there is a method called reset that does it. I was looking for something similar.

**Comment by 304NotModified** [comment]
`XmlLoggingConfiguration.reload()` should do the trick

See http://nlog-project.org/documentation/v3.2.0/html/M_NLog_Config_XmlLoggingConfiguration_Reload.htm

**Comment by ronydj** [comment]
did'nt work. Any other idea?

**Comment by 304NotModified** [comment]
Can you post the code you tried?

**Comment by 304NotModified** [comment]
Depending of your situation:

```c#
     LogManager.Configuration.Reload();
            //OR
            LogManager.Configuration = new XmlLoggingConfiguration("path to .config");
```

**Comment by 304NotModified** [comment]
I will assume your question is answered. If not, feel free to re-open.
