### ISSUE TITLE
Missing Files & Framework on chat secure-ios

### ISSUE THREAD

**Issue by arivirinchi** [NLog/NLog#665]
how to get complete source code of chat secure-ios , which is missing like  these files
OTR_Codesigning.xcconfig
OTRSecrets.m
Pods.debug.xcconfig
Pods.release.xcconfig
Pods.beta.xcconfig

and make it runnable source code.

**Comment by 304NotModified** [comment]
Download It

From the correct repository

**Comment by arivirinchi** [comment]
I have tried to download correct repositry with using terminal
Download the source code and with the submodules as well.
$ git clone https://github.com/chrisballinger/ChatSecure-iOS.git 
$ cd ChatSecure-iOS/ 
$ git submodule update --init --recursive 
$ pod install
but stil we have missing these files
OTRSecrets.m
Please help me....
https://github.com/ChatSecure/ChatSecure-iOS
