### ISSUE TITLE
NLog.Extended not copying 

### ISSUE THREAD

**Issue by knarunkumar** [NLog/NLog#666]
Hi i have two projects, 
1. Utility - Class library project
2. MVC Web Application
in that utility project i added NLog, NLog.Config, Nlog.Schema and Nlog. Extended. All these are 3.2.0.0 version.
I referred this utility in my MVC project, i can see that only NLog.dll alone copied in to my MVC application, and getting error, NLog.Extended is not loaded.
Not only in MVC web application, even i tried the same in console app and unit test project too. there also this NLog.Extended not copied in that bin folder and getting the same error.

could you please guide me how can i fix this issue

**Comment by 304NotModified** [comment]
Is "copy local" enabled (in visual studio)

**Comment by 304NotModified** [comment]
?

**Comment by knarunkumar** [comment]
Yes its enabled


ARUNKUMAR NAGARATHINAM
Senior Development Engineer

Tel. +914226659000 | Coimbatore, India | Twitter<https://twitter.com/symphony_teleca>

[www.symphonyteleca.com]<http://www.symphonyteleca.com/company/newsroom/video-library/>

Please consider the environment before you print.

Notice to recipient: This e-mail (including any attachments) is meant for the intended recipient only, may contain confidential and proprietary information, and is protected by law. If you received this e-mail in error, please immediately notify the sender of the error by return e-mail, delete this communication and any attachments, and shred any printouts. Unauthorized review, use, dissemination, distribution, copying or taking of any action based on this communication is strictly prohibited.

On Apr 16, 2015 1:29 AM, Julian Verdurmen <notifications@github.com> wrote:

Is "copy local" enabled (in visual studio)

**Comment by 304NotModified** [comment]
And it the file in the bin folder after build?

**Comment by knarunkumar** [comment]
Yes I can see the NLog.Extended DLL in utility project bin folder after build, but the same not coming into the web project bin folder


ARUNKUMAR NAGARATHINAM
Senior Development Engineer

Tel. +914226659000 | Coimbatore, India | Twitter<https://twitter.com/symphony_teleca>

[www.symphonyteleca.com]<http://www.symphonyteleca.com/company/newsroom/video-library/>

Please consider the environment before you print.

Notice to recipient: This e-mail (including any attachments) is meant for the intended recipient only, may contain confidential and proprietary information, and is protected by law. If you received this e-mail in error, please immediately notify the sender of the error by return e-mail, delete this communication and any attachments, and shred any printouts. Unauthorized review, use, dissemination, distribution, copying or taking of any action based on this communication is strictly prohibited.

On Apr 17, 2015 2:34 AM, Julian Verdurmen <notifications@github.com> wrote:

And it the file in the bin folder after build?

**Comment by 304NotModified** [comment]
Just tried it local and it just works. You can try re-installing the nuget package.

nuget:

`  update-Package  NLog.Extended -reinstall` 

Tested it with: Visual Studio 2013, x64 Windows, Any CPU release, Publish profile, NLog 3.2.0

**Comment by 304NotModified** [comment]
Please reopen if your issues isn't resolved. Closing for now.
