### ISSUE TITLE
configure a file-target for each different thread

### ISSUE THREAD

**Issue by mdissel** [NLog/NLog#667]
How can i group all the log messages from a specific thread into a single file-target?

Nlog in used inside a windows service where multiple threads are created to handle specific tasks.

**Comment by 304NotModified** [comment]
With a filter or just use https://github.com/NLog/NLog/wiki/ThreadId-Layout-Renderer in the file name

**Comment by 304NotModified** [comment]
I assume that your question is answered. If not, feel free to re-open.

**Comment by mdissel** [comment]
Thanks! Is it possible to use a PostFilteringWrapper in combination with a filter on the threadid equals threadid from the exception?
I want to create an email target that will send an email when an exception is logged and it should contain the buffered log messages from all levels from the same threadid
