### ISSUE TITLE
Should regular `strings` get expanded?

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#673]
As reported at #669 and unit tested with #670

Should regular `strings` (So not `Layouts`) get expanded by variables? E.g.

```xml
<variable name="test" value="hello"/>
...
<target xsi:type="EventLog"      ...        source="${test}"/>  
```

Should the `source` be `${test}` or `hello`? The current code (3.2.0) will result in `hello`

**Comment by 304NotModified** [comment]
Partial discussed at #670

I'm not keen in changing things non-backwards-compatible and it's unclear if this is an feature or a bug. I think, if we fix this, this should be an option. 

Also, this wasn't submitted as bug, but more as side notice. I also think "wontfix" is also good for now.

**Comment by Xharze** [comment]
I agree, I'll add the tag and close the issue
