### ISSUE TITLE
Ability to change Encoding in ConsoleTarget and ColoredConsoleTarget

### ISSUE THREAD

**Issue by Anatos** [NLog/NLog#676]
It's rather good for debugging to support more languages which based on encoding. MSDN recommend to use Unicode encoding (not Default), but it's nice when you can choose it for your-self, as in FileTarget.cs (https://msdn.microsoft.com/en-us/library/system.text.encoding.default%28v=vs.110%29.aspx). It's frustrating when some messages become "question mark" array. So please, fix it.

**Comment by 304NotModified** [comment]
We labeled this a feature request. 

The 4.0 release a enough features request, but maybe we have time to implement it.

PR's will be accepted for this.
