### ISSUE TITLE
Advice on custom use of Nlog

### ISSUE THREAD

**Issue by OlinCamber** [NLog/NLog#677]
Hi all, 

A few days ago, i've decided to implement Nlog into my work mproject to remove old homemade logger.
Due to business reason we log into several files different type of informations in Csv format.

I've made a static class which add extension methods to Nlog to directly specify i'm writing into a specific file like 

```
_log.Network(....) or _log.Archive(....)
```

Theses methods build an LogEventInfo containing everything i need (with several logEvent.Properties to manage each csv column, I currently use 5 properties, a message and  sometimes an exception)
One of the properties is used by filters to write on one or more files.

My logger is declared in most of my classes like this:

```
private readonly Logger _log = LogManager.GetCurrentClassLogger()
```

Could it be a bad idea to have several field _log in my whole software ?
Could the properties generate slowness in the logger ?

Thanks a lot for incoming response!

**Comment by 304NotModified** [comment]
I don't see any problem with that, also not in performance.

**Comment by 304NotModified** [comment]
I will amuse that you question is answered so closing this. Feel free to re-open.
