### ISSUE TITLE
Unable to write to file share on Load Balanced Web servers.

### ISSUE THREAD

**Issue by shahjn** [NLog/NLog#678]
Nlog writes fine to a local path on a (Load Balanced) server. eg; d:\test\log-4-22-2015 works well.
However something like this:- `\\Server\remote_content\logs\log-4-22-2015.txt` does not work. Has anybody gotten this to work, are we missing something ?
Version: 2.0 (tried 3.2 as well)

```
<targets async="true">
   <target xsi:type="File" name="file" fileName="\\Server\Content\Test\logs\${shortdate}.log" layout="${longdate} ${uppercase:${level}} ${message}" />
    </target>
 </targets>
```

Thanks,
JS

**Comment by 304NotModified** [comment]
Hi,

this should be working. We use it sometimes. Probably it's a permission thing (NTFS). Did you checked the internal log? (https://github.com/NLog/NLog/blob/master/CONTRIBUTING.md#bug-reports)

**Comment by 304NotModified** [comment]
Please keep in mind that:

- Writing to the same log file from multiple servers is not recommend. 
- Writing over the network can slow things down.

When I'm using NLog with load balanced servers, I just write them locally

**Comment by 304NotModified** [comment]
I amuse that you question is answered, so closing this. If not, feel free to re-open

**Comment by shahjn** [comment]
Yes that, we solved it by mapping a drive letter and logging it local to each server.

Thanks....

On May 8, 2015 6:28 PM, Julian Verdurmen <notifications@github.com> wrote:
I amuse that you question is answered, so closing this. If not, feel free to re-open

---

**Comment by 304NotModified** [comment]
Thanks for the feedback!
