### ISSUE TITLE
Using Nlog variable to declare CsvLayout

### ISSUE THREAD

**Issue by OlinCamber** [NLog/NLog#680]
Hi,

I've a Csv template:
```
 <layout xsi:type="CSVLayout" delimiter="Tab">
        <column name="date" layout="${dateLayout}" />
        <column name="time" layout="${timeLayout}" />
        <column name="level" layout="${level}"/>
        <column name="Category" layout="${event-context:item=Category}"/>
        <column name="Message" layout="${message}" />
        <column name="Value" layout="${event-context:item=Value}"/>
        <column name="exception" layout="${exception_inline}" />
        <column name="logger" layout="${logger}"/>
      </layout>
```
I would like to know if its possible to use a `<variable ... /> ` syntax to declare it and use it for several targets without redeclaring it.

Thanks the incoming help.

Sincerely

**Comment by 304NotModified** [comment]
Hi, 

With the `<variable ... />` you can reuse the content of a `layout` attribute. The `<variable ... />` can be used in multiple targets.

**Comment by OlinCamber** [comment]
Could you give me the valid syntax to put my layout into a variable ?

Thanks for the help!

**Comment by 304NotModified** [comment]
https://github.com/nlog/nlog/wiki/Configuration-file#variables

**Comment by OlinCamber** [comment]
So could I do this :
```
  <variable name="csvLayout">
<layout xsi:type="CSVLayout" delimiter="Tab">
        <column name="date" layout="${dateLayout}" />
        <column name="time" layout="${timeLayout}" />
        <column name="level" layout="${level}"/>
        <column name="Category" layout="${event-context:item=Category}"/>
        <column name="Message" layout="${message}" />
        <column name="Value" layout="${event-context:item=Value}"/>
        <column name="exception" layout="${exception_inline}" />
        <column name="logger" layout="${logger}"/>
      </layout>
<value>
</value
</variable
``` 
And then use the variable as layout ?

**Comment by 304NotModified** [comment]
I misunderstood your question. Your example probably won't gonna work. This is not supported.  

I would advice to use the api or T4 templates to do this.

**Comment by OlinCamber** [comment]
Oh that's unfortunately :(

Thanks for the answer!

**Comment by snakefoot** [comment]
#3459 adds support for having complex layout-types like CSVLayout inside NLog-varaibles
