### ISSUE TITLE
Issues with Internal Logging

### ISSUE THREAD

**Issue by OlinCamber** [NLog/NLog#682]
Hi,

I've two problem using Nlog internal logging.
Firstly  while starting I execute the following code:
```
 LogManager.Configuration = new NLog.Config.XmlLoggingConfiguration("NLog.debug.config", true);
            LogManager.ReconfigExistingLoggers();
            InternalLogger.LogToConsole = true;
            InternalLogger.LogToConsoleError = true;
            InternalLogger.LogLevel = LogLevel.Trace;
            LogManager.ThrowExceptions = true;
InternalLogger.LogFile = Path.Combine(ConfigurationManager.AppPath, "Nlog.log");
```
My first problem is the logToconsole do not display in my Visual output. Is that normal ?

My second issue is when I try to log on C:\log.txt (to test internal log)
This should crash because Nlog cannot create files at the root of C:\.
Unfortunaly It do not crash (and do not create the file) (it works with C:\test\log.txt for example).

Here my internal Nlog.log content:
2015-04-23 18:44:09.8593 Debug TestManager.Info Rejecting message because of a filter.
2015-04-23 18:44:09.8593 Debug TestManager.Info Rejecting message because of a filter.
2015-04-23 18:44:09.8593 Debug TestManager.Info Rejecting message because of a filter.
2015-04-23 18:44:09.8593 Debug TestManager.Info Rejecting message because of a filter.
2015-04-23 18:44:09.8593 Trace Opening C:test.log with concurrentWrite=False

Rejected is normal (I've several targets)

So Why haven't I exception and no trace ?

Thanks a lot for the incoming help

**Comment by 304NotModified** [comment]
Hi,

Why are you trying to log to the internal logger? This is only needed for checking what NLog is doing. You need probably you a regular logger and simple config.

**Comment by OlinCamber** [comment]
My goal is to save warning and error in debug mode, and error in release from Nlog to understand reason of log fail.

**Comment by 304NotModified** [comment]
I'm sorry but I don't get it. Is NLog not working correctly? Only then you will need the internal logger.

**Comment by OlinCamber** [comment]
I want to avoid any production error and keep track of any problem
Like rights errors while logging which unfortunately could happen

But like in my example I'm not able to get the error (thrown by the logger) or tracked  in the nlog internal log...

that's why i'm looking for some help

**Comment by 304NotModified** [comment]
Please check https://github.com/NLog/NLog/blob/master/CONTRIBUTING.md#questions

It's unclear to me what result you're expecting.

**Comment by OlinCamber** [comment]
I just found out concerning exceptions.
I logger attempt to log into C:\myfile.txt
il fails if file do not exist because Nlog cannot create the file (because its the Windows root)
but no exception happens.

It was my issue.
But If I try to log into a file in an other place and lock the file to simulate an access error, the exception is raised.
So I think its just a particular case concerning file creation and exception throwing system.

**Comment by Xharze** [comment]
Can this question be closed?

**Comment by OlinCamber** [comment]
Yes thanks for the help !
