### ISSUE TITLE
GetCurrentClassLogger in base class wrong Class logger

### ISSUE THREAD

**Issue by giammin** [NLog/NLog#683]
public abstract class BaseClass
    {
        private Logger _logger;
        protected Logger Logger
        {
            get { return _logger ?? (_logger = LogManager.GetCurrentClassLogger()); }
        }
    }

    public class Derived : BaseClass
    {
        public Derived()
        {
            Logger.Info("test");
            // Logger "BaseClass"
            // Expected "Derived"  
        }
    }

Workaround:
_logger = LogManager.GetLogger(GetType().Name)

**Comment by 304NotModified** [comment]
I would expect "baseclass" because it's defined in baseclass.

This is expected behavior.

**Comment by 304NotModified** [comment]
What would you expect with `class Derived2: BaseClass `...?

**Comment by giammin** [comment]
>What would you expect with class Derived2: BaseClass...?
logger: Derived2

**Comment by 304NotModified** [comment]
Yes but the method is not `abstract`

**Comment by giammin** [comment]
the method says: GetCurrentClassLogger

I expect the current instantiated class, maybe I'm wrong...

**Comment by giammin** [comment]
So what is the best practice if i want to have a base abstract class with a logger?

**Comment by 304NotModified** [comment]
The best practice it to create a private field for each class. So each class have:

```
private Logger _logger = LogManager.GetCurrentClassLogger(); //or static if desired. 
```

There is no benefit creating this in an abstract class IMO

**Comment by giammin** [comment]
the benefit is to not have to implement a logger in all derived classes

**Comment by 304NotModified** [comment]
It saves 1 line of code for each class, yes.

`LogManager.GetLogger(GetType().Name)` looks fine to me.

**Comment by Xharze** [comment]
Closed as this seems answered, please reopen if needed
