### ISSUE TITLE
Is it possible to write rows into Logfile in Hierarchical way?

### ISSUE THREAD

**Issue by laantmik** [NLog/NLog#686]
Hello,

Does NLog support any kind of Hierarchical way on logging into file?
I mean something like this kind of two level logfile.

Init done.
Read done.
------Error: Wrong password. 
Read done.
Start copying
------Error: Access Denied.
Start copying
End Copying

So, can this be done with "levels" or templates or some other way.

Best Regards,

Lamik

**Comment by 304NotModified** [comment]
That's possible with [When-Layout-Renderer](https://github.com/nlog/nlog/wiki/When-Layout-Renderer) and [Pad-Layout-Renderer](https://github.com/nlog/nlog/wiki/Pad-Layout-Renderer), but it will get messy soon.

**Comment by laantmik** [comment]
Thanks for reply. Are there any samples how to use When-Layout-Renderer and Pad-Layout-renderer?

Best Regards,

Lamik

**Comment by 304NotModified** [comment]
Currently no. It will be great if you post your config when you got it working.

**Comment by Xharze** [comment]
Closed as this question is answer, please reopen as needed
