### ISSUE TITLE
WebserviceTarget - HttpPost, need for other encoding types (JSON and/or XML)

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#700]
The current implementation of `WebServiceTarget` posts the content as "application/x-www-form-urlencoded". We need therefor the `[FromBody]` attribute on an REST api. 

Posting XML of JSON would be more conventional.

See unit test `WebServiceTargetTests.WebserviceTest_restapi_httppost` and #699

**Comment by 304NotModified** [comment]
Steps:
- add option to `WebServiceTarget` for UrlEncoding. Create or find an enum with the values: FormUrlencoded, JSON, XML (names can be different)
- added tests for other UrlEncoding's

**Comment by RichiCoder1** [comment]
I may grab this is no one else has.

**Comment by 304NotModified** [comment]
No one is working on this atm, so have fun :)

**Comment by RichiCoder1** [comment]
Any particular reason that there's a `GET` target? And it's sending it's stuff through the body rather than the URL? Both seem rather odd.

**Comment by 304NotModified** [comment]
GET and body is unusual.  But to be backwards compatible,  don't remove it.

**Comment by RichiCoder1** [comment]
Agreed. I'll just leave it out and add a comment.

**Comment by 304NotModified** [comment]
Your contenttype proposal looks good.  I prefer an enum. Please keeps things backwards compatible (so default form encoded)

**Comment by 304NotModified** [comment]
Ps There are some unit tests for webservice.  You can easily copy/expand/enable them.

**Comment by a8861505** [comment]
Hey,Is this one supported yet?  I really need webservice target that can send json.

Thanks

**Comment by 304NotModified** [comment]
Too bad this well issue isn't implemented yet. Also not sure if we could expect it for 4.4 as no one is working on this. 

I could give you Done guidance to implement (and contribute) it, but personally I don't have time for fully implementing it.
