### ISSUE TITLE
Flush synchronously

### ISSUE THREAD

**Issue by migig** [NLog/NLog#702]
I need to flush synchronously, so I have access to some events once I've written them.

How do I do that? I need something like:

    public void flush() {
      LogManager.Flush(/* how do I do this? */);
    }

I see `Flush` takes a delegate as an argument. How do I get sync behavior via a callback or something similar?

**Comment by Xharze** [comment]
When you call `LogManager.Flush()` without parameters, it will flush synchronously.

**Comment by migig** [comment]
Missed that in the docs... sorry! And thanks! :)
