### ISSUE TITLE
Protect GetCurrentClassLogger from returning null ?

### ISSUE THREAD

**Issue by OlinCamber** [NLog/NLog#708]
Hi, 

I Would like to know if its possible that LogManager.GetCurrentClassLogger returns null value.
I've seen it in some example, but it seems weird.

Thanks for the incoming help ! 

Sincerely

**Comment by 304NotModified** [comment]
That should be a bug. It should never return `null`. There was an concurrency problem in NLog - which could lead to `null`, that will be fixed in 4.0

**Comment by OlinCamber** [comment]
Ok thanks!

Have you a date for the 4.0 release ?

Thanks

**Comment by 304NotModified** [comment]
2 June. So almost there!

**Comment by 304NotModified** [comment]
Only in rare cases you should check. I would advise to not check it.
