### ISSUE TITLE
FileTarget.FileName.ToString() returns value enclosed in single quotes

### ISSUE THREAD

**Issue by grbinho** [NLog/NLog#709]
Hi,

as mentioned in the title, FileTarget.FileName.ToString() returns value enclosed in single quotes.
It's an easy Trim fix, but not expected.

Ivan

**Comment by 304NotModified** [comment]
Hi,

That's because [ FileTarget.FileName](http://nlog-project.org/documentation/v3.2.1/html/P_NLog_Targets_FileTarget_FileName.htm) is a [Layout](http://nlog-project.org/documentation/v3.2.1/html/T_NLog_Layouts_Layout.htm), and the ToString of that quotes a fixed value (no layout renderers used)
