### ISSUE TITLE
Not getting an internal log message when email fails to send

### ISSUE THREAD

**Issue by attrib75** [NLog/NLog#710]
We're experiencing some intermittent email delivery issues in a production environment which led us to discover that NLog is not logging internally when there is an exception sending an email.  To test this, I purposefully set the wrong SMTP address in the NLog config file.  I expected to see an internal NLog message saying there was an exception sending to that mail server.  In the NLog source, it looks like there's a try {send mail} catch {always log}.  Is there a way we can see exceptions when sending email?

**Comment by 304NotModified** [comment]
This is probably solved in 4.0(and so in the master). I have to check that.

**Comment by attrib75** [comment]
Ok thanks!  We'll stand by.  Is there a target release date for 4.0?

**Comment by 304NotModified** [comment]
Yes 2 June. But first a beta release

**Comment by 304NotModified** [comment]
Confirm. this is fixed in 4.0. 

See line 324 in [v3.2.1](https://github.com/NLog/NLog/blob/v3.2.1/src/NLog/Targets/MailTarget.cs)


and line 306 in [master](https://github.com/NLog/NLog/blob/master/src/NLog/Targets/MailTarget.cs)

**Comment by 304NotModified** [comment]
So thanks for the report. Marking this a duplicate and closing as it has been resolved in 4.0.

**Comment by 304NotModified** [comment]
duplicate of #261

**Comment by attrib75** [comment]
Ok thank you
