### ISSUE TITLE
Replacing newlines with replace wrapper (NLog 2)

### ISSUE THREAD

**Issue by MikeGale** [NLog/NLog#719]
I'm using NLog 2 in an existing project.

I'd like to add a replace wrapper in the configuration to replace newlines in messages.

What syntax do I use to define "\r\n" etc. in the search for parameter.

**Comment by 304NotModified** [comment]
You need `\\n` in the XML config

**Comment by MikeGale** [comment]
Thanks.  That did what I wanted.
For anybody else who's looking something like:
**<variable name="replacedname" value="${date:format=yyyy-MM-dd HH\:mm\:ss.fffffff:universalTime=true}~${replace:searchFor=[\\n]+:replaceWith=whatever:regex=true:inner=${message}}~...>**
works well.

**Comment by 304NotModified** [comment]
Thanks for the feedback.

I added a striped down version to the wiki: https://github.com/NLog/NLog/wiki/Replace-Layout-Renderer

I don't think the `[` and `]` are needed in the regex.

**Comment by MikeGale** [comment]
Hi,

 

Absolutely correct with that particular replacement.  However it does work.

 

I had been working with a set of characters, and left it like that.

 

Great work on updating the online help, so quickly.

 

Regards,

 

Mike Gale

 

CAUTION - This message may contain privileged and confidential information intended only for the use of the addressee/s.

 

If you are not the intended recipient of this message you are hereby notified that any use, dissemination, distribution or reproduction of this message is prohibited without prior written consent.  Any views expressed in this message may not reflect the views of Decision Engineering.
