### ISSUE TITLE
Date Based File Archiving : Archived Files Date Labels Become Wrong 

### ISSUE THREAD

**Issue by lesserhippias** [NLog/NLog#720]
Suppose that we try to use Nlog with following target:

 < target name="filelog"
            xsi:type="File"
            fileName="${basedir}/Logs/log.txt"
            layout="${longdate} ${message}"
            archiveEvery="Day"
            archiveFileName="${basedir}/Logs/Archives/{#}.txt"
            archiveNumbering="Date"
            archiveDateFormat="yyyy-MM-dd"
            maxArchiveFiles="7" 
/>
			
It work fine while your application works.
Suppose that you application worked for May 10, May 11, May 12, May 13  continuously [ application never stop]

At  May 13 

You will have 3  Archived Files At  Logs/Archives

          2015-05-10.txt  [ Evething is okey. All logs messages date are also 2015-05-10]
          2015-05-11.txt  [ Evething is okey. All logs messages date are also 2015-05-11]
          2015-05-12.txt  [ Evething is okey. All logs messages date are also 2015-05-12]

And One File 

               log.txt  [ [ Evething is okey. All logs messages date are also 2015-05-13]]

Then your application is stopped.No body use it for May 14 , May 15 ...And somebody then At May 16 will start to use you application:

Then Your Archived Files Labels Becomes Buggy:

**Nlog Create New Archive File Label It As : 2015-05-15.txt [ In this file there is logs belong to 2015-  05-13 date, infact we should not have any log at 2015-05-15.]**
                 
                 2015-05-15.txt [ messages date are 2015-  05-13 ]

You can simply try this by just changing your windows date time....

**Comment by 304NotModified** [comment]
It's not fully clear to me. What did you expected and what is the current result? 

See also: https://github.com/NLog/NLog/blob/master/CONTRIBUTING.md#bug-reports

**Comment by lesserhippias** [comment]
I expect that NLog Archive the log file which contains 2015- 05-13 day log messages into 2015- 05-13.txt log file not 2015- 05-15.

NLog should be clever to figure out that this : May use file creation date or simply message dates in that file...

How can I be more clear ?

**Comment by lesserhippias** [comment]
NLog, blindly assume that it should give current log file label as "yesterday date" when archive it.This assumtion is not true simply....

**Comment by lesserhippias** [comment]
![nlogproblem](https://cloud.githubusercontent.com/assets/12625093/7835485/08f67708-0482-11e5-8358-67fe1cb54c31.png)

Just add a drawing to make clear

**Comment by 304NotModified** [comment]
Thanks for the graphic!

I think that this is behavior we can't fix. I'm not sure how NLog should know that the file should be named 2015-05-13. It can't remember things as the application is shutdown.

Scanning the old log file seems a bit wrong.

**Comment by lesserhippias** [comment]
**How NLog should know that the file should be named  based on date label?** 
That is the real question...There are some alternatives 

**First** 
NLog can just look at the file creation date from OS, and simply convert this date in to user defined date label. Infact you can add such a configuration to NLog: Suppose that  

                  archiveDateFormatMethod="Automatic" [ which does default behaviour ]
   and 

                  archiveDateFormatMethod="FileCreationDate" [ which use file creation dates ]


**Second**
Nlog simply write date Value to start of each  created log file : Suppose that at Day 13, there is a simple log.txt which contains some debugging info and your special date. So at  DAY 16 you simply look special date info at the start of that log.txt file and do the right date labeling:

![sd](https://cloud.githubusercontent.com/assets/12625093/7856085/0b449d52-052f-11e5-9cdb-5528d4dec2ac.png)

**Comment by 304NotModified** [comment]
Thanks! We are a bit busy with the release of 4.0 now, but I will try to look into detail of this, probably next week.

**Comment by lesserhippias** [comment]
Thanks for your interest.
Best Wishes

**Comment by lesserhippias** [comment]
Can able to discuss this issue ?

2015-05-28 14:48 GMT+03:00 Julian Verdurmen <notifications@github.com>:

**Comment by 304NotModified** [comment]
I think the OS creation date is the most suitable idea. It isn't always correct, but it's better than now.

**Comment by lesserhippias** [comment]
So, you will add this feature in near future  or has no plan?

2015-06-08 21:52 GMT+03:00 Julian Verdurmen <notifications@github.com>:

**Comment by 304NotModified** [comment]
I think this will be nice for the next release, 4.1 

@Xharze do you agree?

**Comment by lesserhippias** [comment]
When you plan to relase 4.1 ? Or You decide to add this to 4.1 ?

2015-06-09 21:30 GMT+03:00 Julian Verdurmen <notifications@github.com>:

**Comment by 304NotModified** [comment]
We will add this to 4.1 (should have)

**Comment by 304NotModified** [comment]
4.1 is not planned yet.

**Comment by lesserhippias** [comment]
Ok. Thanks for adding this to 4.1  as a [ should have ].
Best Wishes

**Comment by 304NotModified** [comment]
same issue: https://github.com/NLog/NLog/issues/367

**Comment by 304NotModified** [comment]
We will move this to the next version as this is more work than planned for 4.1

**Comment by 304NotModified** [comment]
I'm gonna work on this :)

**Comment by 304NotModified** [comment]
@bhaeussermann I this something you can fix / check?

**Comment by 304NotModified** [comment]
This should be fixed in 4.3
