### ISSUE TITLE
LogManager threw an exception in a static constructor

### ISSUE THREAD

**Issue by VerdonTrigance** [NLog/NLog#721]
Hello. I'm going to use NLog with SharePoint 2010.
I have my custom TimerJob that I want to log.
In a static constructor I tries to set config throught Configuration API and implenet Logger like that:

```c#
static TimerJob()
        {            
            // Step 1. Create configuration object 
            var config = new LoggingConfiguration();

            // Step 2. Create targets and add them to the configuration 
            var eventLogInfoTarget = new EventLogTarget();
            config.AddTarget("eventLogInfoTarget", eventLogInfoTarget);

            // Step 3. Set target properties 
            eventLogInfoTarget.Layout = "${longdate}\n${logger}\n${level:uppercase=true}\n${message}";
            eventLogInfoTarget.Source = typeof(TimerJob).Namespace;
            eventLogInfoTarget.EventId = "1";

            // Step 4. Define rules
            var rule1 = new LoggingRule(typeof(TimerJob).FullName, LogLevel.Info, eventLogInfoTarget);
            config.LoggingRules.Add(rule1);

            // Step 5. Activate the configuration
            LogManager.Configuration = config;
            Logger = LogManager.GetCurrentClassLogger();
        }


```

Application compiles well, but when I deploy it to my SharePoint Application I get:
Error occurred in deployment step 'Add Solution': The type initializer for 'TimerJob' threw an exception.
I also tried to add:
InternalLogger.LogFile = @"C:\NLOG.txt";
InternalLogger.LogLevel = LogLevel.Trace;
LogManager.ThrowExceptions = true;
But nothing happened.
Anyone knows why LogManager act like this in a static context?

**Comment by 304NotModified** [comment]
This is bug which is probably solved in 4.0. Do you have the full exception message with stack trace? Check https://github.com/NLog/NLog/blob/master/CONTRIBUTING.md

The RC of 4.0 is also published. Could you check if it's solved in that version?

**Comment by VerdonTrigance** [comment]
Thank for replay.
I haven't StackTrace. This message is everything what I have.
But I'll try 4.0 RC.

**Comment by 304NotModified** [comment]
Do you have problems when using the Nuget package of NLog 4.0 RC (with .Net 3.5)? Or do you build manually?

**Comment by 304NotModified** [comment]
Please capture the stacktrace. That would really help. It should be in the internal log or if you capture it with visual studio, in details

**Comment by VerdonTrigance** [comment]
I have build NLog 4.0 RC manually from the source code. And I dunno how to get StackTrace, because   it's not possible to enable debug while deploying and internal log not creates as I told in my 1st post (maybe I should configure NLog in other way to write log?)

**Comment by 304NotModified** [comment]
The error "The type initializer for 'TimerJob' threw an exception" don't tell us much. This errors means that creating the static "instance" of `TimerJob` failed. The cause of this exception is in the innerexception / stacktrace of the Exception. 

There is a big change that the exception is raised before even creating the Logconfiguration and so nothing is logged to NLog.

This should be really easy to debug in Visual Studio. 

For example:

This will raise the same Exception and won't ever reach the static contructor.
```c#

    public class TimerJob
    {
        static TimerJob()
        {
            // Step 1. Create configuration object 
            var config = new LoggingConfiguration();

            // Step 2. Create targets and add them to the configuration 
            var eventLogInfoTarget = new EventLogTarget();
            config.AddTarget("eventLogInfoTarget", eventLogInfoTarget);

            // Step 3. Set target properties 
            eventLogInfoTarget.Layout = "${longdate}\n${logger}\n${level:uppercase=true}\n${message}";
            eventLogInfoTarget.Source = typeof(TimerJob).Namespace;
            eventLogInfoTarget.EventId = "1";

            // Step 4. Define rules
            var rule1 = new LoggingRule(typeof(TimerJob).FullName, LogLevel.Info, eventLogInfoTarget);
            config.LoggingRules.Add(rule1);

            // Step 5. Activate the configuration
            LogManager.Configuration = config;
            Logger = LogManager.GetCurrentClassLogger();
        }

        public static Logger Logger { get; set; }

        public static String x = Logger.ToString();
    }
```

![image](https://cloud.githubusercontent.com/assets/5808377/7891549/d5bc3062-064d-11e5-9683-cfca2d6f999c.png)

**Comment by 304NotModified** [comment]
Is your issue solved?

**Comment by VerdonTrigance** [comment]
Nope. I've decided to use another framework.

2015-06-08 23:39 GMT+03:00 Julian Verdurmen <notifications@github.com>:
