### ISSUE TITLE
Support JSON with objects (not only flat key-value)

### ISSUE THREAD

**Issue by di97mni** [NLog/NLog#723]
Version: NLog 4.0 RC

From [this post](https://github.com/NLog/NLog/issues/722#issuecomment-107054041):

This configuration

```xml
<target name="jsonFile" xsi:type="File" fileName="${basedir}/logs/${shortdate}.json">
	<layout xsi:type="JsonLayout">
		<attribute name="time" layout="${longdate}" />
		<attribute name="level" layout="${level:upperCase=true}"/>
		<attribute name="message" layout="${message}" />
		<attribute name="properties" layout="${all-event-properties}" />
	</layout>
</target>
```

Generates this. Notice `properties`

```json
{
  "time": "2015-05-30 17:11:50.7131",
  "level": "INFO",
  "message": "Start",
  "properties": "CallerMemberName=Main, CallerFilePath=C:\\Temp\\NLogJson\\ConsoleApplication1\\ConsoleApplication1\\Program.cs, CallerLineNumber=13"
}
```

Instead of a key value string, create a JSON array.

```json
{
  "time": "2015-05-30 17:27:55.0730",
  "level": "INFO",
  "message": "Start",
  "properties": {
    "CallerMemberName": "Main",
    "CallerFilePath": "C:\\Temp\\NLogJson\\ConsoleApplication1\\ConsoleApplication1\\Program.cs",
    "CallerLineNumber": "13"
  }
}
```

Maybe this is also needed for other event properties?

**Comment by 304NotModified** [comment]
note: the proposal isn't a JSON array, but a JSON object.

**Comment by di97mni** [comment]
Ah, you're right. Of course it is. My mistake.

**Comment by 304NotModified** [comment]
This is difficult issue, because the JSONlayout isn't aware of the `${all-event-properties}` and visa versa. 

Any idea how we could solve this?

**Comment by VictorNicollet** [comment]
I can imagine three ways of doing this. 

The dirtiest but easiest version would be to allow a parameter `${all-event-properties:format=JSON}` where the output is `{"key":value}` instead of the standard `key=value` format. Then, a `raw` tag in the XML configuration file would tell the JSON layout that the value should not be output as string, but rather as raw JSON (which may include a syntax check). 

    <attribute name="properties" layout="${all-event-properties}" raw />

A cleaner (but quite limited) alternative would be to recognize that some layout renderers (such as `${event-properties}`) act as dictionaries ; ${event-properties:item=X}` is not specifying a _rendering option_, but a _key to be rendered_. Such dictionaries could be displayed with:

    <attributes name="properties" layout="${event-properties}" each="item" />

At the layout renderer level, a new function would be required to enumerate those values: 

    [EnumerableParameter]
    [RequiredParameter]
    public string Item { get; set; }

    public override IEnumerable<string> GetEach(string which) 
    {
        if (which == "Item") 
            // enumerate all possible values of "Item", based on the values provided 
            // for the other parameters
        else
            throw new ArgumentException("Not enumerable: " + which, "which");
    }

Thus, `<attributes>` would instantiate the layout renderer with whatever parameters are provided in the `layout=`, call `GetEach` with the value provided in `each=`, and then output key-value pairs by setting `Item` to each value returned by `GetEach`.

The cleanest would be to allow renderers to return a certain number of non-string types, including JSON ones (arrays, dictionaries) but also non-JSON (`DateTime`), when those types are a better representation of what is being output. The layout itself would then decide whether to convert these to strings, JSON, XML, and so on. This might be a bit overengineered, though.

**Comment by 304NotModified** [comment]
Thanks! I will think about the solutions.

**Comment by Page-Not-Found** [comment]
>The dirtiest but easiest version would be to allow a parameter ${all-event-properties:format=JSON} where the output is {"key":value}

I was looking into this item and in my opinion the first solution looks more clean as well as matching other formatting layouts which we already have in place. For Eampple we specify "toString", "mm/dd/yyyy" for dates.

**Comment by Page-Not-Found** [comment]
Can we use Newtonsoft serialize? [JSON.NET](http://www.newtonsoft.com/json)

**Comment by 304NotModified** [comment]
Thanks Sree, 

Yes I like that one also the best one. But do we need the `raw` attribute? It can be a property of the layout renderer?

**Comment by Page-Not-Found** [comment]
@304NotModified I am not sure how the raw attribute will be used with toJSON formatting. What I was thinking is if the format is set to toJSON, then we can render as depicted in the initial comment of this ticket.

**Comment by Page-Not-Found** [comment]
Do any one have any other suggestions on this?

**Comment by 304NotModified** [comment]
note to others: this has been discussed on the chat.

The proposal of @Page-Not-Found  by including the javascript serializer code from coreFX is the best one :)

**Comment by 304NotModified** [comment]
@Page-Not-Found are you still working on this? I would to release this in 4.3 (1-2 weeks from now)

**Comment by Page-Not-Found** [comment]
Yes was working in this, but did not find time. May be we can think this
for version 5?

**Comment by Page-Not-Found** [comment]
@304NotModified Do you think other wise? I am in middle of the implementation, trying to get the the unit testing completed.

**Comment by 304NotModified** [comment]
@Page-Not-Found any success on this?

**Comment by Page-Not-Found** [comment]
With the way it is done right now. It is getting tough to put in any new
change but I am almost there to completion stage just not able to find
enough time to do self review and unit testing.
On Feb 3, 2016 6:12 PM, "Julian Verdurmen" <notifications@github.com> wrote:

@Page-Not-Found <https://github.com/Page-Not-Found> any success on this?

—
Reply to this email directly or view it on GitHub
<https://github.com/NLog/NLog/issues/723#issuecomment-179522941>.

**Comment by 304NotModified** [comment]
Well you can PR it and we can review it of course. Not problem that it's WIP. If you write 1 unit test, then we can easily create more.

**Comment by Page-Not-Found** [comment]
I will try to get this out this week.

**Comment by 304NotModified** [comment]
Cool :)

**Comment by Page-Not-Found** [comment]
I am making some progress here. Would be able to get some base beta version my upcoming week. Sorry I am keep extending the time, is because with the current code it is getting harder to add additional things to one area without affecting others.

**Comment by 304NotModified** [comment]
This is supported by nesting JsonLayouts. See https://github.com/NLog/NLog/wiki/JsonLayout#advanced-examples

**Comment by gpolaert** [comment]
Hi @304NotModified,
I've closed this issue, but did you solve it? I try to generate a Json object from the properties array set in my code. 

How can I achieve that with the `all-event-properties` layout render? I don't want to specify all the potential properties in a nested layout.

Thanks ;)

**Comment by 304NotModified** [comment]
@gpolaert 

This is solved in two ways:

1. You can define an object with nested ` <attribute`
2. and/or you can use `encode="false"` and `${Json-Encode-Layout-Renderer}`

Too bad, the all-event-properties isn't aware of JSON, so it's printing a (non-JSON) string. 

We like to fix this, but we need an approach which works for (almost) every layout renderer. If you think this is needed/desired, please create a new issue. :)

**Comment by gpolaert** [comment]
Thanks. I think it's very useful features, especially if you have a log management solution :) (I'm coming from [ Logmatic.io](http://logmatic.io) ^^)

I don't know .Net to be honest but I will check how can we handle that. 
If I have a proposal, I will open an issue. What are the main difficulties about serialize in Json the renderer?

**Comment by jholovacs** [comment]
I don't see how this is supported by JsonNestingLayouts, and the example in the link doesn't address the situation very well.  The example specifies an exception, that has two well-known properties, not a dynamic list of key-value pairs of type string, object.  Can we either A) update the documentation with an example of how to make this work, or B) reopen this issue?

**Comment by 304NotModified** [comment]
Please open a new issue on github or (preferred) stackoverflow.

**Comment by jholovacs** [comment]
http://stackoverflow.com/questions/44048187/layout-nlog-properties-as-json

**Comment by 304NotModified** [comment]
Ah, I now fully understand your question,

There is a new option `includeAllProperties` on the `JsonLayout`

e.g.

```
<target name="jsonFile" xsi:type="File" fileName="${basedir}/logs/${shortdate}.json">
    <layout xsi:type="JsonLayout" includeAllProperties="true">
        <attribute name="time" layout="${longdate}" />
        <attribute name="level" layout="${level:upperCase=true}"/>
        <attribute name="message" layout="${message}" />
        <attribute name="properties" layout="${all-event-properties}" />
    </layout>
</target>
```

You could also skip some properties with `excludeProperties="exclude1, exclude2"`

**Comment by 304NotModified** [comment]
also posted on StackOverflow

**Comment by jholovacs** [comment]
I'm still getting this sort of thing:

`{ "timestamp": "2017-05-18 15:47:50.1177", "level": "ERROR", "message": "PushAdvertiserConversionRule", "properties": "properties=System.Collections.Generic.Dictionary`2[System.String,System.Object], tags=System.Collections.Generic.List`1[System.String]", "properties": "System.Collections.Generic.Dictionary`2[System.String,System.Object]", "tags": "System.Collections.Generic.List`1[System.String]" }`

it's basically taking the object and doing `.ToString()` on it, instead of serializing to JSON.

**Comment by 304NotModified** [comment]
Unfortunately, it was thinking that was fixed already.

**Comment by 304NotModified** [comment]
We have a ijsonserializer, that one should be used

**Comment by jholovacs** [comment]
Thanks

**Comment by 304NotModified** [comment]
@jholovacs created a new issue for it. https://github.com/NLog/NLog/issues/2127
