### ISSUE TITLE
Breaking Change: NLog 4.0 build is missing NLog.Fluent.Log

### ISSUE THREAD

**Issue by niemyjski** [NLog/NLog#729]
![image](https://cloud.githubusercontent.com/assets/1020579/8011135/b39774fa-0b7b-11e5-9948-acb5c1fdd3a9.png).

I'm not sure when this started occurring as I just noticed it. I wonder what else is missing. The 3.5 build is also missing this class as well.

**Comment by 304NotModified** [comment]
Thanks for reporting! 

Not sure what went wrong

**Comment by niemyjski** [comment]
It was broke in 3.2.0 as well. I haven't checked the builds before that

**Comment by 304NotModified** [comment]
But it works in. Net 4.5?

**Comment by niemyjski** [comment]
Yup

**Comment by Xharze** [comment]
Thanks for reporting, this will be fixed before releasing the final 4.0
version.
Den 05/06/2015 23.04 skrev "Blake Niemyjski" <notifications@github.com>:

**Comment by Xharze** [comment]
I've just looked at the code, the reason seems to be that the [CallerPathAttribute ](https://msdn.microsoft.com/en-us/library/system.runtime.compilerservices.callerfilepathattribute%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396) is used, which is only supported in .NET 4.5 and above. Unfortunately this also means that it can't be fixed in versions below .NET 4.5

**Comment by niemyjski** [comment]
Why can't you just use a compiler directive to exclude the attribute on the platforms that don't support it or change the internal implementation to use a different logger?

**Comment by niemyjski** [comment]
Seems that this is something that should be supported.

**Comment by 304NotModified** [comment]
This would be possible, but what's the benefit of `Log` above `LogBuilder`, or use `LogManager.GetCurrentClassLogger().Trace().Message("etc")`?

**Comment by niemyjski** [comment]
Because it's one class that won't break people who switch between versions.

**Comment by 304NotModified** [comment]
With your proposal it will also breaks (different behavior), but this time the compiler won't alerts you.

**Comment by niemyjski** [comment]
yes, but it could be a known behavior and if you wanted. you would still
pass in the log source.

Thanks
-Blake Niemyjski

**Comment by 304NotModified** [comment]
That's essensially the same as `LogManager.GetLogger(name).Info().Message("etc")`?
