### ISSUE TITLE
Using external non .net binaries to log with NLog

### ISSUE THREAD

**Issue by hdsoftware** [NLog/NLog#733]
Hi all
We develope most of Our software in a Win32 Developer Language called Clarion for Windows. Now, this Language has no .NET support, nor is it .NET compatible in any way other than that it supports standard Win32 API Calls.  Now, I have created a wrapper that lets me Call exported .NET Methods and vice versa.  This lets me do some fancy integration between Our Clarion programs and Our C# programs. 

 Ok.  But now, we are in the nead of a good logging tool.  I was about to create one my selfe, but I then came over NLog and it seems to be exactly what I nead plus more.  Hers the problem, or at least, i think it is a problem:

To be able to logg anything from Our Clarion Applications I nead to create some static Methods and export them.  This means that all Calls to thouse Methods will for NLog originate from the main DLL holding the API.  What I really woudl like is to tell NLog the name of the compionent sending the Messages.  Is this possible?

Regards
Ole Morten Heien

**Comment by 304NotModified** [comment]
Hi,

this is possible, but you can't use `LogManger.GetCurrentClassLogger()`. `LogManager.GetLogger("some name")` should be no problem

**Comment by hdsoftware** [comment]
Thanx. Il try that

**Comment by Xharze** [comment]
I assumed this question has been answered, if not please reopen
