### ISSUE TITLE
Logger not logging to file

### ISSUE THREAD

**Issue by lkinsella** [NLog/NLog#737]
I've been using NLog for years however I've ran into an issue today that has me truly baffled.

In my set up NLog is configured to log to a file and I've wrapped the Logger class in my own ILog interface/abstraction for dependency injection.

I've hooked up various events like UnhandledException and it's catching and logging nicely, as I've always done.

In this current application I dynamically load an assembly using reflection and pass the ILog instance into it. When an issue arises I can then call one of the ILog methods.

When debugging in Visual Studio if I break point in all of these methods, they are all getting called and everything appears to be working. Except nothing gets logged.

Can anyone think of a reason for this? It's logging from everywhere else just fine.

I've tried turning on ThrowExceptions etc to no avail.

**Comment by 304NotModified** [comment]
Hi,

which version of NLog? Did you also checked in internal log? See https://github.com/NLog/NLog/blob/master/CONTRIBUTING.md

I sounds like a the assembly won't load (the same version) of NLog.

**Comment by lkinsella** [comment]
I hadn't tried the internal log but just did. It logs the other calls fine but again, with this particular call nothing happens even though it does hit for example Logger.Error() there's no logs generated internally or otherwise.

This is NLog 4.0.0. I've updated all projects to use the latest from NuGet.

**Comment by 304NotModified** [comment]
Please check the internal log.

**Comment by lkinsella** [comment]
I resolved this. The issue wasn't with NLog per-say but a runtime binding issue as initially suspected. Cleaning the solution and rebuilding after updating all references seems to have calmed things down.

**Comment by 304NotModified** [comment]
Good to hear!
