### ISSUE TITLE
GlobalDiagnosticsContext, MappedDiagnosticContext and NestedDiagnosticsContext should support object as value.

### ISSUE THREAD

**Issue by williamb1024** [NLog/NLog#738]
The GlobalDiagnosticsContext, MappedDiagnosticsContext and NestedDiagnosticsContext should provide overloads for `Set` (etc) that accept `object` as the `value` parameter. When rendered, the value's `ToString` method should be used to determine the string content for rendering.

I do not believe this would be a breaking change in the API as existing code will still bind to the string overloads.

**Comment by 304NotModified** [comment]
I agree.  PR would be accepted.

**Comment by 304NotModified** [comment]
Merged
