### ISSUE TITLE
enableArchiveFileCompression error

### ISSUE THREAD

**Issue by DataCrypt** [NLog/NLog#740]
After upgrading to v4.0, NLog keeps erroring saying it doesn't support the new  enableArchiveFileCompression in the file target.  Not sure how to resolve this.

**Comment by 304NotModified** [comment]
Which. Net version? It's only 4.5

**Comment by DataCrypt** [comment]
Ah, that must be the issue of the error.  I'm using .NET 4.  Wish NLog would just skip or ignore this rather than stopping all logging.  Thank you for the response.

**Comment by DataCrypt** [comment]
Ah, that must be the issue of the error.  I'm using .NET 4.  Wish NLog would just skip or ignore this rather than stopping all logging.  Thank you for the response.

**Comment by 304NotModified** [comment]
I see that I didn't told the .Net 4.5 requirement in the news post. I will update it :)
