### ISSUE TITLE
No RichTextBoxTarget found in NLog 4.0

### ISSUE THREAD

**Issue by aegoroff** [NLog/NLog#748]
And no mention about deprecating it and it's still present in wiki

**Comment by 304NotModified** [comment]
We're sorry. Something went wrong with publishing and communicating the new packages. 

You need 
https://www.nuget.org/packages/NLog.Windows.Forms/

But it needs an update for NLog 4.0. We are working on that. This should be fixed tomorrow.

**Comment by 304NotModified** [comment]
Related #741

**Comment by 304NotModified** [comment]
The nuget packages had been updated (version 2.0 for the use with NLog 4.0). 

So this has been resolved. If you have any problems, feel free to-open this issue, or create a new one.

**Comment by 304NotModified** [comment]
The wiki is also updated to make this more clear: https://github.com/NLog/NLog/wiki/Targets
