### ISSUE TITLE
Incorrect overload reference in ObsoleteAttribute after upgrading from 3.2 to 4.0

### ISSUE THREAD

**Issue by Dennis-Petrov** [NLog/NLog#757]
Hi.
I've upgraded NLog nuget-package from v. 3.2 to 4.0. As a result, this method call:

    Logger.Error(ex.Message, ex)

generates a warning:

> NLog.Logger.Error(string, System.Exception)' is obsolete: 'Use Error(LogLevel level, Exception 
> exception, string message, params object[] args) method instead.

While the warning text is absurd itself (I can't imagine `Error(LogLevel.Information, ...)` call), there's no such overload, which accepts `LogLevel level` as a first argument.

**Comment by Xharze** [comment]
Thanks for reporting, this is indeed incorrect the recommend overload is `Error(Exception exception, string message, params object[] args)`. The warning will be fixed in 4.0.1
