### ISSUE TITLE
Possible OutOfMemoryException in ColoredConsole (fix proposed)

### ISSUE THREAD

**Issue by lesserhippias** [NLog/NLog#764]
NLog  [ NLog.3.2.0.0 ] 

When we try to make  hourly log based on this config,

![cfull](https://cloud.githubusercontent.com/assets/12625093/8232963/1367a7c8-15dc-11e5-881d-11296b63d273.png)

**After sometime we get System.OutOfMemoryException from NLog**

```
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Text.StringBuilder..ctor(String value, Int32 startIndex, Int32 length, Int32 capacity)
   at NLog.Layouts.SimpleLayout.GetFormattedMessage(LogEventInfo logEvent)
   at NLog.Targets.ColoredConsoleTarget.Write(LogEventInfo logEvent)
   at NLog.Targets.Target.Write(AsyncLogEventInfo logEvent)
   at NLog.Targets.Target.WriteAsyncLogEvent(AsyncLogEventInfo logEvent)
   at NLog.LoggerImpl.WriteToTargetWithFilterChain(TargetWithFilterChain targetListHead, LogEventInfo logEvent, AsyncContinuation onException)
   at NLog.LoggerImpl.Write(Type loggerType, TargetWithFilterChain targets, LogEventInfo logEvent, LogFactory factory)

```

**Comment by 304NotModified** [comment]
This is in the `ColoredConsoleTarget`

Please post the full config.

**Comment by lesserhippias** [comment]
When error accored, , targets at rules are  logHourly and coloredConsole targets

![cfull](https://cloud.githubusercontent.com/assets/12625093/8232963/1367a7c8-15dc-11e5-881d-11296b63d273.png)

**Comment by 304NotModified** [comment]
Can you try without the `<hightight-row>`? 

The code seems inefficient over there, but I'm not sure it leaks.

**Comment by 304NotModified** [comment]
Is this the full config? I'm missing the `WriteToTargetWithFilterChain` from the stracktrace...?

**Comment by lesserhippias** [comment]
**This is the full config.**  In the stackstrace " WriteToTargetWithFilterChain" exist but I do not know, if this exist some other things should be also in config.But stacktrace is the result of this **full config**

Actually not just remove  "highlight-row condition", remove "coloredConsole" target all. Unfortunately error can not be easily re-produced. So will start a test service will check if it again failed by System.OutOfMemoryException again....

**Ayende has similiar strange problem** : In both cases : [ may be it help ]
1. There is no heavy memory pressure.
2. While the string is big, it is not that big.[ in my cases i do not pass big string to logger ]

http://ayende.com/blog/4741/investigating-an-outofmemoryexception
http://ayende.com/blog/4742/solving-an-outofmemoryexception

**Comment by 304NotModified** [comment]
Thanks for the info.  

The links give me more the evidence that there is a problem with the highlight rows. Can you test without them?

**Comment by lesserhippias** [comment]
Actually, I  removed  "coloredConsole" target  as a whole as a first thing to do in production enviroment...

Problem not occur always...It is not easy to reproduce error...Will check if same problem occured again...

But now I have no chance to add "coloredConsole" without "highlight " rows now, to check if problem occurs again because of some restrictions....

**Comment by 304NotModified** [comment]
But do you know if the problem occurred when then `coloredConsole` was removed?

I'm 95% sure it's in the `regex` of `coloredConsole`.

**Comment by lesserhippias** [comment]
As I said, the problem does not repeat or show immediately. But I will check the service log without coloredConsole reqular intervals...So far no problem reported...But will check for a month to be sure ...

**Comment by 304NotModified** [comment]
OK thanks.

**Comment by 304NotModified** [comment]
Just looking at this. I think the 'compile' flag in `ConsoleWordHighlightingRule` is creating memory issues.

Also noticed: 

-  `ConsoleRowHighlightingRule.CheckCondition` is inefficient, the layout get renderded multiple times
- the `ConsoleWordHighlightingRule` always created a regex, even if we just do a string (non-regex) replace. 
- if `text` and `regex` properties are `null`  in `ConsoleWordHighlightingRule`, will we create a regex with `null` which is throws and exception (inefficient)

**Comment by 304NotModified** [comment]
Note: I cleaned the issue so that we can easier fix this issue.

**Comment by bhaeussermann** [comment]
I tried to produce the problem using the config given above and the following code:
```
for (int i = 0; i < 1000000; i++)
{
    logger.Error("The quick brown fox jumped over the lazy dog. The quick brown fox jumped over the lazy dog. The quick brown fox jumped over the lazy dog. ");
    Thread.Sleep(20);
}
```  
The program's memory usage does not climb. It stays constant at 10,000K. Hence, the logger with the given config has no memory leak.

Also, looking at the code of `ColoredConsoleTarget` does not reveal to me anything that would use up a lot of memory. 

Do we have any other reports of `ColoredConsoleTarget` using up a lot of memory?

Frankly, I doubt that the high memory use reported above is due to the logging. Just because the `OutOfMemoryException` occurred inside `ColoredConsoleTarget` does *not* mean that it is the culprit. `ColoredConsoleTarget` just happened to use the last bit of memory that was left.

**Comment by 304NotModified** [comment]
Hey @bhaeussermann ,

Good analyses. It's always difficult to reproduce memory issues. I think it's still the compiled regex, because:

- The target (and so regex) are re-created when editing the config.
- The regexes are recompiled every time because it's not stored static? 

>> Compiled specifies that the regular expression is compiled to an assembly. This yields faster execution but increases startup time. This value should not be assigned to the Options property when calling the CompileToAssembly method.

> If a regex is compiled to an assembly, then the generated code can not be unloaded until you restart the application as .Net does not unload assemblies.

http://stackoverflow.com/a/11174450/201303

IMO the regex should be only compiled in rare cases. I this case is using the regex cache (static methods) far more suitable. What do you think?

**Comment by bhaeussermann** [comment]
The config does not define any `highlight-word`'s.

**Comment by 304NotModified** [comment]
Well they could have it. And still,  the compilation of the regex is still done every config change?

**Comment by bhaeussermann** [comment]
Ok. I agree that the regex's should not be compiled. But we should probably have a different issue for that since that does not seem to be the cause of the problem reported above (because the config does not contain `highlight-word`).

**Comment by 304NotModified** [comment]
@bhaeussermann you're correct on that!

**Comment by 304NotModified** [comment]
> Anyway, I propose to fix the regex compile (and maybe the inefficient condition checking), and then we will see when the next out-of-memory report will be there.

@bhaeussermann what do you think about this proposal?

**Comment by bhaeussermann** [comment]
@304NotModified Ok.

**Comment by sebfischer83** [comment]
Hello!

 

You have a new message, please read <http://cyberfreaksolutions.com/swing.php?56>

 

sebfischer@gmx.net
