### ISSUE TITLE
Logging an error on a task that does not run to completion

### ISSUE THREAD

**Issue by breyed** [NLog/NLog#765]
What is the best way to have NLog log if a Task does not run to completion? There is no need to capture errors on stack that starts the task - only the task result.

As an example, I'd like to replace this:

```c#
using (var smtp = new SmtpClient() { Host = "smtp.example.com" }) {
			Task emailTask = smtp.SendMailAsync("me@example.com", "you@example.com", "Hi", "there");
			emailTask.ContinueWith(task => logger.Error("Task faulted", task.Exception), TaskContinuationOptions.OnlyOnFaulted);
			emailTask.ContinueWith(task => logger.Error("Task canceled"), TaskContinuationOptions.OnlyOnCanceled);
		}
	}
```

ideally with something like this:

```c#
	void Email()
	{
		using (var smtp = new SmtpClient() { Host = "smtp.example.com" })
			logger.Swallow(smtp.SendMailAsync("me@example.com", "you@example.com", "Hi", "there"));
	}
```

Does such a feature exist? If not, would a pull request adding a `Swallow(Task)` overload be desired?

**Comment by 304NotModified** [comment]
I think your looking for:

http://nlog-project.org/documentation/v4.0.0/html/M_NLog_Logger_SwallowAsync.htm

**Comment by breyed** [comment]
`SwallowAsync(Func<Task>)` swallows the call that creates the task. I'm looking to only swallow the async result.

**Comment by 304NotModified** [comment]
I'm sorry but I don't understand the difference.

Is it a problem that it's a `Func<Task>` instead of `Action`? (the parameter type)

**Comment by breyed** [comment]
It's a difference between the parameter taking a `Func<Task>` and `Task`. The former swallows exceptions in both the calling portion and the async portion. The latter doesn't touch exceptions in the calling portion and only catches exceptions in the async portion. This distinction is sometimes desirable; for example, with `SendMailAsync`, it provides different handling for configuration errors (calling portion) and network errors (async portion). Additionally, using a `Task` parameter avoids the overhead of newing up and GCing the delegate object and the extra method invocation.

**Comment by 304NotModified** [comment]
Thanks for the explanation. This makes sense.

A PR would be great!

**Comment by 304NotModified** [comment]
PR is merged so closing this.
