### ISSUE TITLE
Wrong changelog for 4.0.1

### ISSUE THREAD

**Issue by akamyshanov** [NLog/NLog#771]
Hi,

not sure if this should be an issue, but the changelog for ver `4.0.1` is a bit wrong:
What it is now: `Loading the NLog config from an embedded resource is now working`
What it should be: `Loading the NLog assembly from an embedded resource is now working`
ref: https://github.com/NLog/NLog/pull/746

**Comment by 304NotModified** [comment]
the whole Nlog assemlby is the embedded resources? Really? I didn't understood that before..

**Comment by 304NotModified** [comment]
thanks!
