### ISSUE TITLE
Fluent logger uses caller attributes but non-fluent not

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#775]
from https://github.com/NLog/NLog/issues/768

> As a side remark, it's a bit weird that the fluent API includes caller info like this but the regular one doesn't. You might want to think about how to harmonize this behavior across the board

We should fix this, because it's inconsistent.

**Comment by 304NotModified** [comment]
Does anyone have any ideas how to fix this? (@gab ?)

**Comment by snakefoot** [comment]
After #2386 has been implemented, then it is a matter of removing the artificial callsite-LogEventInfo-properties.
