### ISSUE TITLE
${callsite-linenumber}  not proper merged in 4.0

### ISSUE THREAD

**Issue by ray-pixar** [NLog/NLog#778]
It seems that ``${callsite-linenumber} `` has been removed from ``layout``. please check it.

https://github.com/NLog/NLog/wiki/Callsite-line-number-layout-renderer

**Comment by 304NotModified** [comment]
Yes, it was merged but I seems to be gone.

merged:
https://github.com/NLog/NLog/pull/521

**Comment by 304NotModified** [comment]
This seems to be accidentally  reverted by. 945d35a23fcf2753e3ec6e81a332cbec830a94f2. Not sure what went wrong. 

I have hidden the link to the wiki and prepare a new PR.
