### ISSUE TITLE
NLog.Extended nuget-package is fixed to NLog 4.0.0

### ISSUE THREAD

**Issue by mckn** [NLog/NLog#782]
Hi,

The NLog.Extended nuget-package is depending on the exact version 4.0.0 of NLog. This causes issues when you have a dependency on NLog.Extended and you tries to upgrade NLog to 4.0.1.

Please fix this! Thanks!

**Comment by 304NotModified** [comment]
This is indeed wrong! We will fix this.

**Comment by 304NotModified** [comment]
Hi, this is fixed with NLog.Extended 4.0.0.1

https://www.nuget.org/packages/NLog.Extended/4.0.0.1

**Comment by 304NotModified** [comment]
note @Xharze .nuspec files are updated.
