### ISSUE TITLE
LogReceiverWebServiceTarget backwards compatible problem

### ISSUE THREAD

**Issue by tryhp3** [NLog/NLog#783]
After the update (to NLog 4.0) I have a serious problem:
1. 'NLog.CustomExtendedService.LogReceiverSecureService.CreateWcfLogReceiverClient()': return type must be 'NLog.LogReceiverService.WcfLogReceiverClientFacade' to match overridden member 'NLog.Targets.LogReceiverWebServiceTarget.CreateWcfLogReceiverClient()'	
2. New class WcfLogReceiverClientFacade does not include: ClientCredentials and Endpoint.
![przechwytywanie](https://cloud.githubusercontent.com/assets/4246990/8451869/c678f2cc-1fe6-11e5-9056-e5c8f9726a2b.PNG)

**Comment by 304NotModified** [comment]
Hi,


- I don't fully understand the problem of point 1. Yes it is a breaking change, but what is the serious problem?
-  The `ClientCredentials` was also not in 3.2.0 and before? (in don't see them in `WcfLogReceiverClient` (https://github.com/NLog/NLog/blob/v3.2.0.0/src/NLog/LogReceiverService/WcfLogReceiverClient.cs)
- There is an endpoint address in the `LogReceiverWebServiceTarget`. Could that help?

**Comment by 304NotModified** [comment]
PS: I noticed that `WcfLogReceiverClientFacade ` is a mess and should be refactored. See #784

**Comment by 304NotModified** [comment]
I see the problem: 

- WcfLogReceiverClientFacade won't inherit from `ClientBase<...>`. But in 3.2.0 `WcfLogReceiverClient` was returned, and this class did implement  `ClientBase<...>` (which contains 'Endpoint` and `ClientCredentails` properties). Thus: WcfLogReceiverClientFacade  should inherit from `ClientBase<..>`

**Comment by 304NotModified** [comment]
fixed by #874
