### ISSUE TITLE
The “consistent logging of exceptions” breaking change  = upgrade issue

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#785]
The “consistent logging of exceptions” breaking change (https://github.com/NLog/NLog/pull/691) gives "nightmares" and is seen as problematic. 

See
https://twitter.com/GraemeF/status/613680899666890752

I think we should fix this and I think this should be possible. 

But first we should discuss to where the problem exactly lies and how we could solve this.

**Comment by shiggan** [comment]
I think the main problem is that everybody depends on a very 'fat' API that is ILogger; as soon as that changes the world breaks. 

i would suggest a few things
* Obsolete the old V3 API's (i actually thought we done this looking at the code; but if were running into this issue then mabye not enough)
* Seriously think about Obsoleting _all_ of the Log* API's in ILogger
* Surface a single method (or at least one with a very limited number of overloads) entrypoint to call into LoggerImpl.Write directly through ILogger (like ILogger.Write); and likely GetTargetsForLevel
* Rewrite the API's new in V4 as Extension methods that use the slimmed down ILogger

in the next major version release we pull the Obsoleted API's; and introduce NLog.Compatibility.SomeVersion which has Extension Methods on ILog which *replecate* the old API.

Any Log methods end up beign extension methods on ILogger; old versions can be moved to a compatability namespace once they have been obsoleted.

This will still cause heartbreak; anybody inheriting directly from ILogger will break (does anybody seriously do that and get everything right; i know i support code where people do this but they always manage to screw up the stack tracing.. or was that Log4Net... i forget).

The idea is to make the ILogger API as thin as possible; at any time in the future people who need compatability can still get it through the versioned extension methods; people who need a slightly custom Log method can still do it easy enough (like a LogSomeSpecialObject).

**Comment by 304NotModified** [comment]
Thanks for your input.

First of all, I think we should not change the `ILogger` interface until NLog 5.0. Second: my idea of this "issue" was to discuss the (non-backwards compatible) changes from NLog 3 to 4. 

Your suggestions
---
Of course thanks for your input. About your suggestions:

>Obsolete the old V3 API's (i actually thought we done this looking at the code; but if were running into this issue then mabye not enough)

What is the V3 API in you opinion? The `Logger` class? Because `ILogger` is introduced in NLog 4.0 

> Seriously think about Obsoleting all of the Log* API's in ILogger

Do you mean the `Log(..)` methods in `Logger` or `ILoggerBase`? What would be the benefit? 

>Surface a single method (or at least one with a very limited number of overloads) entrypoint to call into LoggerImpl.Write directly through ILogger (like ILogger.Write); and likely GetTargetsForLevel

I don't understand this. There is one "write" entrypoint in `LoggerImpl`?

>I think the main problem is that everybody depends on a very 'fat' API that is ILogger; as soon as that changes the world breaks. 
...
> Rewrite the API's new in V4 as Extension methods that use the slimmed down ILogger

I don't think `ILogger` is too fat. Yes, I had  a lot of overloads and many of them can be replaced with the generic version(s), (like `Debug<TArgument>`). But we are also aware that the generic version is slower. Also, I don't see the the benefit too cut the number of methods here. There are just overloads. Can you give a specific example and why it would be beneficial? 
The only issue I have with `ILogger` are the `params` arguments. They make it difficult to create good overloads. 

The breaking changes from NLog 3 to 4
===
I think is more important to discuss the "nightmares" of the breaking changes (from NLog 3 to 4). I don't know If you one of the guys who posted on Twitter.
But I think to only "nightmare" breaking change is: 
> removed “exceptionCandidate” hack: Log(string message, Exception ex) would write to exception property instead of message. This is non-backwards compatible in behaviour!

Is this correct? 

I will assume that obsoleting methods is not a nightmare, as you can still use them.

**Comment by GraemeF** [comment]
Yes, that's the one - any use of Log(string message, Exception ex) will compile happily but not do the right thing (as far as 3.x code is concerned) anymore.

**Comment by 304NotModified** [comment]
@GraemeF 

Thanks for the feedback. I think a configuration option for the old behavior would reduce the upgrade pain. See https://github.com/NLog/NLog/pull/789

What do you think? Should be also (configurable) log (to the internal log), the obsolete calls for this? N.B. we cannot use the `[Obsolete]` attribute for this :(

**Comment by 304NotModified** [comment]
This one is also related: https://github.com/NLog/NLog/issues/787. Maybe we should solve them both in the same way.

**Comment by GraemeF** [comment]
Yeah, I gathered `[Obsolete]` would not be an option :/

It's going to be tough to ever say a bunch of code has been 100% updated to the new API because with these changes you will only find out at runtime. And because this is specifically for logging exceptions - some of which may rarely or never happen - you may never actually run the code. That means source inspection is going to be the only way to do it reliably, which obviously isn't ideal.

So I think that these suggestions will help, but won't make the problem go away. We'd probably end up using the old API forever (which we are currently doing by trying not to upgrade!).

**Comment by 304NotModified** [comment]
> It's going to be tough to ever say a bunch of code has been 100% updated to the new API because with these changes you will only find out at runtime. And because this is specifically for logging exceptions - some of which may rarely or never happen - you may never actually run the code. That means source inspection is going to be the only way to do it reliably, which obviously isn't ideal.

You can just "find all references" in visual studio of the changed method? So I don't agree this is an run-time problem. But I will take some migration time.

But due to   #787 I'm a bit in dubio: I still agree the previous behavior was nontransparent and built with quirks. We have removed them in 4.0.
But we can do two things:

Best performance
===
Choose the option which guarantee the best performance: this is the current approach in NLog 4. With an option we can allow the old behavior of NLog 3 (and we will remove this option in NLog 5) 

Relax approach
===
**OR** we choose for the most forgiving approach "relax mode", to be specific: every method will handle the `Exception` type. So for example: `logger.Error("there is a error {0}, ex"), will:

 - format the message use the exception as message argument. 
 - will also keep the Exception for `${exception}`.
 - for methods with multiple parameters, pick the first Exception for the ${exception}`. 

This has to following advantages:

- It solves the breaking change described above (but the effect is not 100% the same compared to NLog 3)
- We can use all the methods for exception logging.
- we can use `${message}` and `${exception}`. almost "exchangeable"
- it would also fix #787.
- I think it's more easy to work with. 

Downsides:

- What the use of the new Exception methods in NLog 4?
- it's sometimes magic? With `Error(messageVar, ex1, ex2)` we only picking the first `Exception` for ${exception}`. 
- I could hurt the performance. We should check every argument if it's a subtype of `Exception`

Your opinion please :)

**Comment by GraemeF** [comment]
Yes, you're right - find refs on the will help a lot, so it is just a time/ensuring completeness thing. I think, given that, I'm in favour of the simplest approach. However, if the other reasons for taking the relaxed approach justify it then by all means. :smiley: 

I think that in my case I'll just have to suck it up and spend a day going through everything.

**Comment by 304NotModified** [comment]
Simplest approach for the end user or within the code?

**Comment by GraemeF** [comment]
Simplest API so probably both. Best to avoid magic IMO.




On Tue, Jul 7, 2015 at 12:29 PM -0700, "Julian Verdurmen" <notifications@github.com> wrote:












Simplest approach for the end user or within the code?

**Comment by 304NotModified** [comment]
Closing this due inactivity
