### ISSUE TITLE
Problem with RichTextBoxTarget

### ISSUE THREAD

**Issue by Xharze** [NLog/NLog#79]
<p>Hello together;</p>
<p>&nbsp;</p>
<p>One Problem with RichTextBoxTarget :</p>
<p>in Nlog V1 the Messages are displayed in Realtime.</p>
<p>NlogV2 seems to buffer the messages ?</p>
<p>or do something wrong ?</p>
<p>&nbsp;</p>
<p>I use a mix of Configfile and Config API:</p>
<p>when i find the RTB in the Config file then i use this one otherwise i create a new one.</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>Codesnippet:</p>
<p>&nbsp;</p>
<p> Dim target As NLog.Targets.RichTextBoxTarget</p>
<p> Try</p>
<p> target = lg.FindTargetByName(&quot;RTB_Name&quot;)</p>
<p> If IsNothing(target) Then</p>
<p> &#39; Create new Target</p>
<p> target = New NLog.Targets.RichTextBoxTarget</p>
<p> target.FormName = &quot;Form_Name&quot;</p>
<p> target.Name = &quot;RTB_Name&quot;</p>
<p> target.UseDefaultRowColoringRules = True</p>
<p> &#39;target.AutoScroll = True</p>
<p> &#39;target.ToolWindow = True</p>
<p> lg.AddTarget(target.Name, target)</p>
<p> End If</p>
<p>&nbsp;</p>
<p> Catch ex As Exception</p>
<p>&nbsp;</p>
<p> End Try</p>
<p>&nbsp;</p>
<p> LogManager.Flush()</p>
<p> LogManager.ReconfigExistingLoggers()</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>I hope you can Help me.</p>
<p>&nbsp;</p>
<p>Thank a lot in advance</p>
<p>&nbsp;</p>
<p>Klaus</p>

**Comment by 304NotModified** [comment]
Old question. Closing it
