### ISSUE TITLE
How to use Nlog in more than one project ?

### ISSUE THREAD

**Issue by tiger2014** [NLog/NLog#791]
My solution has several project , each project need NLog , and I do not want to reference Nlog in each project .Is there some mothed to resovle it ?

**Comment by 304NotModified** [comment]
The reference is the only way to go. You can do some tricks with dynamic assembly bindings but that's a lot of hassle. 

With nuget it's easy to add the NLog?

**Comment by tiger2014** [comment]
My solution has 23 projects . what a mass to reference Nlog in every project !

**Comment by 304NotModified** [comment]
You can set then all 23 in one dialog

**Comment by 304NotModified** [comment]
Check "Managing Packages for the Solution"  https://docs.nuget.org/consume/package-manager-dialog

**Comment by 304NotModified** [comment]
I assume that your question has been answered. If not, let me know.

**Comment by tiger2014** [comment]
Sorry ,I have soleved it ,But forget to let you know

**Comment by 304NotModified** [comment]
No problem
