### ISSUE TITLE
Nlog.Windows.Forms License

### ISSUE THREAD

**Issue by ianitor** [NLog/NLog#792]
Hello. I want to ask why NLog and Nlog.Windows.Forms have different licenses?
NLog: https://raw.githubusercontent.com/NLog/NLog/master/LICENSE.txt
NLog.Windows.Forms: GNU GENERAL PUBLIC LICENSE: https://raw.githubusercontent.com/NLog/NLog.Windows.Forms/master/LICENSE

Perhaps this is a mistake?

**Comment by 304NotModified** [comment]
Yes it is. Gpl is evil IMO 

See https://github.com/NLog/NLog.Windows.Forms/issues/2

**Comment by snakefoot** [comment]
Think this has been resolved with https://github.com/NLog/NLog.Windows.Forms/pull/26

**Comment by 304NotModified** [comment]
:) thx!
