### ISSUE TITLE
Invalid path exception when NLog assembly is under a UNC path

### ISSUE THREAD

**Issue by mikeobrien** [NLog/NLog#793]
~~Let's say there is an IIS site running under `D:\Websites\PlanetExpress`. [This](https://github.com/NLog/NLog/blob/master/src/NLog/Config/ConfigurationItemFactory.cs#L267) will return `\Websites\PlanetExpress` and when [this](\Websites\PlanetExpress) is called, the path is relative to the system drive. So if that's `C:` you will get a `DirectoryNotFoundException: Could not find a part of the path 'C:\Websites\PlanetExpress'.` Any interest in a PR? Also is there any reason not to have `GetNLogAssemblyLocation` not return a full path?~~

**Comment by mikeobrien** [comment]
Actually, that's not exactly right. Took a closer look and figured it out. I'm running the IIS site on a parallels shared drive. [`nlogAssembly.CodeBase`](https://github.com/NLog/NLog/blob/master/src/NLog/Config/ConfigurationItemFactory.cs#L269) is returning the unc path of the shared drive: `file://psf/Data/...`. The `Uri.UnescapeDataString` call returns `/Data/...`. Then the call to `Path.GetDirectoryName` returns `C:\Data\...`. 

The solution is to simply replace `GetNLogAssemblyLocation` [here](https://github.com/NLog/NLog/blob/master/src/NLog/Config/ConfigurationItemFactory.cs#L239) with  [`Uri.LocalPath`](https://msdn.microsoft.com/en-us/library/system.uri.localpath%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396) as this returns the correct path either way:

```csharp
var assemblyLocation = new Uri(nlogAssembly.CodeBase).LocalPath;
```

**Comment by 304NotModified** [comment]
Let continue the discussion about this in #794

**Comment by 304NotModified** [comment]
PR merged

**Comment by Tanzy** [comment]
rather than releasing this in 4.1 is it possible to hotfix it? I've just come up against this problem and I now have 2 options. Work from source (aka, compile my own version of Nlog) or roll back to version 3.2 of Nlog Nuget package

**Comment by 304NotModified** [comment]
There is no 4.0.2 release planned.  The release is needs some manual work (checking Silverlight etc),  and both of us are too busy these weeks too bad. 

The release of 4.1 is planned in 3 weeks.  

We try to release more often in the future, but the build scripts are not "upgraded"  yet. 

Thanks for the confirmation  of the fix.

**Comment by 304NotModified** [comment]
4.1 has been released!

**Comment by mikeobrien** [comment]
Woohoo, thx!

**Comment by mikeobrien** [comment]
Tested locally, works great, thx again!

**Comment by 304NotModified** [comment]
Thanks for the feedback!
