### ISSUE TITLE
Separate log file for specific class instance using NLog

### ISSUE THREAD

**Issue by da-sann** [NLog/NLog#796]
Hi. I need to write event log for every instance of class to separate file.
Currently I'm getting instance of logger like this:
```cs
public static Logger GetInstanceLogger(string name, bool init = false)
    {
        if (!LogManager.Configuration.AllTargets.Any(t => t.Name == name))
        {
            var target = new FileTarget();

                target.Name = name;
                target.FileName = string.Format("logs/{0}.${{shortdate}}.log", name);

            target.Layout =
           "${date:format=dd.MM.yyyy HH\\:mm\\:ss.fff} thread[${threadid}] ${logger} (${level:uppercase=true}): ${message}. ${exception:format=ToString}";
            var config = init ? new LoggingConfiguration() : LogManager.Configuration;
            config.AddTarget(name, target);

            var ruleInfo = new LoggingRule("*", LogLevel.Trace, target);

            config.LoggingRules.Add(ruleInfo);

            LogManager.Configuration = config;

            LogManager.ReconfigExistingLoggers();
        }

        var logger = LogManager.GetLogger(name);

        return logger;
    }
```
Right now it's writing same log into all files (I suppose it's caused by the log level). Is there a way to accomplish this task using NLog?

Thanks.

**Comment by 304NotModified** [comment]
Hi,

Some questions:

- I don't fully understand what you're to achieve. Can you give some examples?  
- Is it required that the config in programmatically? Or is a config file also fine?

**Comment by da-sann** [comment]
Say I have client-server application and I want to write events for every client connection in separate file. Also I want to write server log separately.  I don't know how many client will connect, so I need to be able to re-configure logger in runtime.

**Comment by 304NotModified** [comment]
You can use a event properties  of an other layout renderer in the filename.  

See
https://github.com/nlog/nlog/wiki/EventProperties-Layout-Renderer

https://github.com/nlog/nlog/wiki/File-target#per-level-log-files

Let me know if this answers your question :)

**Comment by da-sann** [comment]
This solution will suit in my situation.
Thanks a lot!
