### ISSUE TITLE
 Internal Logger should create directories when needed

### ISSUE THREAD

**Issue by hhyyg** [NLog/NLog#802]
Hi,

I'm using Internal Logging with following NLog.config.

	<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" 
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	      internalLogFile="c:\Logs\InternalLog.log" 
	      internalLogLevel="Trace">
	...
	</nlog>

If the folder "c:\Logs" already exists, Internal Logging is appending.
But, if the folder doesn't exist, it not appending.

I hope insert this code before 
https://github.com/NLog/NLog/blob/4.0.1/src/NLog/Common/InternalLogger.cs#L323

`Directory.CreateDirectory(Path.GetDirectoryName(filename));`

The current NLog version: 4.0.1

Thanks,

**Comment by 304NotModified** [comment]
I think it should be in the static constructor (performance) with a try catch. 

What do you think?

**Comment by hhyyg** [comment]
That's better.

**Comment by 304NotModified** [comment]
I will try to look at this,  but there are issues with more priority right now. 

If you could send a PR,  that would be nice.
