### ISSUE TITLE
LogLevel.FromString cause vs2013 collapse

### ISSUE THREAD

**Issue by zhll912** [NLog/NLog#806]
The issue like this:
Nlog 4.0.1 was Added by Nuget GUI.It was user like(C# Code:):

            private static Logger logger = LogManager.GetCurrentClassLogger();
            ....
            LogEventInfo lei = new LogEventInfo();
            lei.Properties["Operator_name"] = Session["adm_login"];
            lei.Level = LogLevel.Info;//collapse happend here

when LogLevel.FromString was used here,the vs2013 collapsed.So i want to know why?Thks,Anyone.
Tips:my English Capbility is low,plz.

**Comment by 304NotModified** [comment]
What do you mean with "vs2013 collapsed"? A crash of visual studio?

**Comment by zhll912** [comment]
This issue happened at my PC,but others,So it's my issue,thks!
