### ISSUE TITLE
Stack trace not what I was when expecting when using log.Error(exception, message)

### ISSUE THREAD

**Issue by srqdev** [NLog/NLog#807]
When using this method to log an exception I would expect the Stack Trace used to be that from the exception being logged and not the stack trace of the method calling log.Error. This is crucial when capturing unhandled exceptions in any app. In my WPF app I have a DispatcherUnhandledException method to catch any unhandled exceptions. I log the exception passed to this method, but the stack trace is for this method and not the stack trace of the exception i.e. the cause of the failure, making it difficult to debug the actual cause.

**Comment by 304NotModified** [comment]
Hi,

The stracktrace is recorded. Maybe you did not print it well or used the wrong logging method? Did you see https://github.com/NLog/NLog/wiki/How-to-log-exceptions?

**Comment by srqdev** [comment]
I'm using a database target, and coding the target as follows

// Create database target
var databaseTarget = new DatabaseTarget
{
	ConnectionString = CurrentDBConnection,
	CommandText = "INSERT INTO LogEntry(LogDate,LogLevel,LogLogger,LogMessage,LogMachineName,LogUserName,LogCallSite,LogThread,LogException,LogStacktrace)" +
	  "VALUES(@time_stamp,@level,@logger,@message,@machinename,@username,@callsite,@threadid,@logexception,@stacktrace);"
};

// Add parameters
databaseTarget.Parameters.Add(new DatabaseParameterInfo { Name = "@time_stamp", Layout = "${longdate}" });
databaseTarget.Parameters.Add(new DatabaseParameterInfo { Name = "@level", Layout = "${level}" });
databaseTarget.Parameters.Add(new DatabaseParameterInfo { Name = "@logger", Layout = "${logger}" });
databaseTarget.Parameters.Add(new DatabaseParameterInfo { Name = "@message", Layout = "${message}" });
databaseTarget.Parameters.Add(new DatabaseParameterInfo { Name = "@machinename", Layout = "${machinename}" });
databaseTarget.Parameters.Add(new DatabaseParameterInfo { Name = "@username", Layout = "${windows-identity:domain=true}" });
databaseTarget.Parameters.Add(new DatabaseParameterInfo { Name = "@callsite", Layout = "${callsite}" });
databaseTarget.Parameters.Add(new DatabaseParameterInfo { Name = "@threadid", Layout = "${threadid}" });
databaseTarget.Parameters.Add(new DatabaseParameterInfo { Name = "@logexception", Layout = "${exception}" });
databaseTarget.Parameters.Add(new DatabaseParameterInfo { Name = "@stacktrace", Layout = "${stacktrace}" });

// Set configuration
SimpleConfigurator.ConfigureForTargetLogging(databaseTarget, CurrentLogLevel);

// Return new logger
log = LogManager.GetCurrentClassLogger();

It may be incorrect. Let me know.

Thanks

**Comment by 304NotModified** [comment]
I see the problem.  You need `${exception:format=stacktrace}`. 

See https://github.com/NLog/NLog/wiki/Exception-Layout-Renderer

**Comment by 304NotModified** [comment]
I assume you question has been answered. If not, let us know!

**Comment by srqdev** [comment]
Julian,

Yes that all worked. I thought I had replied, obviously I did not.

Colin

Sent from my Windows Phone
________________________________

**Comment by 304NotModified** [comment]
OK, No problem!
