### ISSUE TITLE
Consuming Application crashes when consuming nLog.dll with another .dll in the same directory that "StartsWith" 'nLog'

### ISSUE THREAD

**Issue by MATT031389** [NLog/NLog#810]
I had an application which at one point we had a wrapper class for logging, after switching to nLog we just used nLog inside that wrapper class and left a lot of the calling code the same.

Everything worked fine until I upgraded to nLog 4.  

As it turns out, becuase of the fact that there is another dll in the same directory that starts with 'nLog' (NLogLogger.dll) the TypeInitializer throws an exception and the application crashes.

This is easily reproduced by creating any file in the same directory as your nLog.dll and nLog.config files and call that file NLogLogger.dll. When the app starts it will throw a TypeInitializerException.

I have easily worked around this by changing the name of that assembly, but I thought it would be good to post in case anyone else is having a similar issue :)

Happy Coding!

Matt

**Comment by 304NotModified** [comment]
Thanks for the report. This has to due with the auto loading feature added in NLog 4. 

We will think for a solution. I'm not sure if a try-catch when loading the DLL is a good solution.
