### ISSUE TITLE
Attempted to access an unloaded AppDomain in ReloadConfigOnTimer

### ISSUE THREAD

**Issue by cjlpowers** [NLog/NLog#819]
When we use MSDeploy to deploy our apps we frequently see the following errors logged in the Event Viewer.

    An unhandled exception occurred and the process was terminated.
    Application ID: DefaultDomain
    Process ID: 4436
    Exception: System.AppDomainUnloadedException
    Message: Attempted to access an unloaded AppDomain.
    StackTrace: 

Followed by

    Application: w3wp.exe
    Framework Version: v4.0.30319
    Description: The process was terminated due to an unhandled exception.
    Exception Info: NLog.NLogConfigurationException
    Stack:
    at NLog.LogFactory.ReloadConfigOnTimer(System.Object)
    at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
    at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
    at System.Threading.TimerQueueTimer.CallCallback()
    at System.Threading.TimerQueueTimer.Fire()
    at System.Threading.TimerQueue.FireNextTimers()

I assume what is happening is we configured NLog with autoReload="true" and when MSDeploy writes a new NLog.config file, ReloadConfigOnTimer fires due to the file watcher but the AppDomain is shutting down because of the other files being deployed. 

Perhaps NLog could catch these unhandled exceptions or check whether the AppDomain is unloading via the IsFinalizingForUnload method. 

Using NLog 3.1.0.0 with .NET 4.5.1

**Comment by 304NotModified** [comment]
Thanks for the report! 

Did you have throwErrors set? Which value?

**Comment by 304NotModified** [comment]
The PR should do the trick, I think

**Comment by snakefoot** [comment]
There is a potential race-condition in ReloadConfigOnTimer(). The timer-event can be activated white you are diposing the timer. Should change ReloadConfigOnTimer() so after it has taken the syncRoot-lock, then it should check if reloadTimer-object already has been disposed, and if so then perform an early exit.

**Comment by 304NotModified** [comment]
LOL my lasted commit breaks a lot of stuff  :P

**Comment by 304NotModified** [comment]
Any idea how to fix the potential race-condition in another way?

**Comment by snakefoot** [comment]
Alternative solution is to Dispose the timer with a wait-handle, so you wait for any pending timer-events to complete before completing the Dispose-call.

WaitHandle waitHandle = new AutoResetEvent(false);
this.reloadTimer.Dispose(waitHandle);
WaitHandle.WaitAll(new[] { waitHandle }, TimeSpan.FromMinutes(2));

Then the ReloadConfigOnTimer needs a if(Monitor.TryEnter(syncRoot)) with a finally Monitor.Exit(_syncRoot). Any timer-events that fires while holding the lock in the dispose-call will just perform early exit. The self-dispose performed by the ReloadConfigOnTimer() should dispose without wait-handle.
