### ISSUE TITLE
Question: Regions

### ISSUE THREAD

**Issue by BrandonLegault** [NLog/NLog#822]
Is there any opposition to, as I'm editing the files for a pull request, `Region`ing the code to organize the file a little more? I was thinking something simple like the following (don't mind my cool color scheme):

![Regions](http://i.imgur.com/SvMMtqV.png)

I know some developers are not fond of regions so I figured it better to ask.

**Comment by 304NotModified** [comment]
Well I like them,  but we can only use them if there are used in others parts. (consistently) . 

I don't think we use them much. 

Most people don't like regions,  because regions are used in too fat classes/files etc.

**Comment by BrandonLegault** [comment]
Damn. Alright, I'll leave the files as is.
