### ISSUE TITLE
NLOG + WebApi with OWIN

### ISSUE THREAD

**Issue by daniel-tiziani-tzn** [NLog/NLog#824]
Hi,

We've been using NLOG in a WebApi 2.2 project that is hosted on OWIN, but it conflicts. 
The basic scenario to reproduce the problem is the following:

* 1 WebApi Controller with a NLog instance:
private static Logger logger = LogManager.GetCurrentClassLogger();
* 2 consecutive calls to any service in the controller

For each request to a service in the Controller, Global.asax/Application_start and OWIN Startup get's called, like the context has been reseted. If I comment the logger line, the issue goes away.

I think it's related to how the Logger is discovered, but I couldn't find any Exceptions thrown in this scenario.

**Comment by 304NotModified** [comment]
Can you explain in more detail what is going wrong? What do you mean with "context has been reseted “? Did you have checked the internal
Logging? 
 
Is it possible to create an example project? 

Last but not least,  which NLog and. Net version?

**Comment by 304NotModified** [comment]
We cannot look at this if we don't have the requested info.

**Comment by 304NotModified** [comment]
Closing this.  Feel free to reopen.
