### ISSUE TITLE
LogManager.ReconfigExistingLoggers throws 'System.InvalidOperationException'

### ISSUE THREAD

**Issue by gillima** [NLog/NLog#826]
When a new logger is created while ReconfigExistingLoggers is in progress, the iterator throws an InvalidOperationException (Collection was modified; enumeration operation may not execute.)

Locking syncRoot while iterating through the loggers will solve the issue:
```c#
public void ReconfigExistingLoggers()
{
  if (this.config != null)
  {
    this.config.InitializeAll();
  }

  lock (this.syncRoot)
  {
    foreach (var logger in loggerCache.Loggers)
    {
      logger.SetConfiguration(this.GetConfigurationForLogger(logger.Name, this.config));
    }
  }
}
```

**Comment by 304NotModified** [comment]
Or a new list creation would also work. I think the latter is the best?
