### ISSUE TITLE
NLog is Looking for Developers

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#828]
This year the NLog project has grown a lot:
- We have released more often (and  NLog 4.1 is on its way)
- We have redesigned and improved the website (nlog-project.org)
- The process of giving support and handling issues has been improved
- A lot of old issues are fixed/closed.
- The website is fully up-to-date, the wiki has been expanded and old forums have been closed.
- Twitter and Gitter have been set up.

However, we want to grow even more. We’d like to:
-  Release even more often
-  Fix more bugs
-  Add more features
-  Improve the support for other platforms like Mono, PCL, Xamarin
-  Improve the automatic release management
-  Measure, and improve, the code coverage of the unit tests. 

Currently the NLog team consists of two people. If we want to develop NLog further, we need more horsepower!
And so we are looking for developers! 

If you are interested in contributing to one of the most popular .Net libraries --we are ranked in the [top 100 of NuGet](https://www.nuget.org/stats/packages), and when excluding the non-.Net and Microsoft packages, we rank in the top 10.-- then get in touch with us on Gitter or Github :)

Get in touch with us on [Gitter](https://gitter.im/NLog/NLog) or Github :)
# What do we expect?

As most of the people have full-time jobs, we don't expect you to work on NLog every week. What we do expect:
- Professional attitude 
- Experience in C#
- At least one contribution once a month. E.g. writing code, writing unit tests, responding to GitHub issues and/or writing docs or other posts.

Experience with Git/GitHub/open source projects is not needed, we will help you with those :)

**Comment by tekoscott** [comment]
I am a .net developer of 10 years experience and would like to be involved. Where to I start.

Kind Regards

**Comment by 304NotModified** [comment]
Great! I will add you to https://gitter.im/NLog/devs

**Comment by 304NotModified** [comment]
Hi @tekoscott Do you see the Gitter messages?

**Comment by BrutalCode** [comment]
@304NotModified I just tried to join by your gitter link. But I see that message: 
"404. This is not the chat you're looking for. Sorry. :("

**Comment by 304NotModified** [comment]
I will invite you :)

**Comment by tekoscott** [comment]
OK thanks for that

**Comment by 304NotModified** [comment]
@tekoscott  I did already added you to the room. Can you follow https://gitter.im/NLog/devs?

**Comment by tekoscott** [comment]
Yes thanks



Sent by Outlook for Android





On Thu, Aug 27, 2015 at 12:54 PM -0700, "Julian Verdurmen" <notifications@github.com> wrote:
@tekoscott  I did already added you to the room. Can you follow https://gitter.im/NLog/devs?

---

**Comment by 304NotModified** [comment]
@tekoscott I don't see any chat messages of you in Gitter? Can you see mine?

**Comment by tekoscott** [comment]
Yeah I saw them. Sorry I couldn't stay. Have a few clients to see this morning.


Sent by Outlook for Android





On Thu, Aug 27, 2015 at 1:40 PM -0700, "Julian Verdurmen" <notifications@github.com> wrote:
@tekoscott I don't see any chat messages of you in Gitter? Can you see mine?

---

**Comment by 304NotModified** [comment]
@tekoscott I'm confused. After all you weren't interested?

**Comment by dnlgmzddr** [comment]
Hi @304NotModified, 

I'm a happy nLog user for quite some time, and I will love to contribute.

Have a good day, and let me know what is the next step.

**Comment by 304NotModified** [comment]
@dnlgmzddr great to hear!  I'm now in holiday, but I will be back this weekend and will give you some more info then :)

**Comment by dnlgmzddr** [comment]
No worries, have anice holiday.

**Comment by 304NotModified** [comment]
Hey @dnlgmzddr please join on on Gitter. I will invite you. Your CV looks really nice :)

**Comment by SreenathSanthanam** [comment]
@304NotModified 
I have been using NLog for about an year or so. I have about 7 years of experience in .Net, how can I help you?

**Comment by 304NotModified** [comment]
Great to hear! I will invite you to the Gitter chat room this weekend :)

**Comment by bhaeussermann** [comment]
Hi! I would like to make more contributions to the project and I'm hoping you'd have some suggestions for issues to look at next. May I join on Gitter?

**Comment by SreenathSanthanam** [comment]
Hi,

Did you send me the invite or were you able to add me to the chat room?

**Comment by 304NotModified** [comment]
@bhaeussermann Great! You can join us on the public chat: https://gitter.im/NLog/NLog

**Comment by 304NotModified** [comment]
@SreenathSanthanam. You have been added to the dev channel :) I was a bit (unexpected) busy this weekend. Just chat to use when you have time.

**Comment by 304NotModified** [comment]
@epignosisx

Can you login on Gitter? Then we can add you to the dev chat channel :)

**Comment by epignosisx** [comment]
I'm in!

**Comment by mustafadinler** [comment]
Hello there! I want to be a contributor. Could you send me an invitation?

**Comment by 304NotModified** [comment]
Hey! That would be great!

**Comment by 304NotModified** [comment]
If have send a Gitter invitation.
