### ISSUE TITLE
Add a ProcMon target

### ISSUE THREAD

**Issue by zippy1981** [NLog/NLog#829]
[Sysinternals Process Monitor](https://technet.microsoft.com/en-us/Library/bb896645.aspx) has the ability to recieve text string to display in the output grid. [I've implemented log4net support](https://github.com/Wintellect/ProcMonDebugOutput/tree/master/Source/Sysinternals.log4net). NLog seems natural.

**Comment by 304NotModified** [comment]
It sounds like a good idea, but we cannot include this in NLog core (because of the externals)

I would recommend to create a separate (Github) repository for it.

**Comment by zippy1981** [comment]
There is no need for external dependencies. We can copy one .cs file with the PInvoke calls (@johnrobbins has said he was ok with that kind of thing in the past). However, if you don't want to do that I could create the extension in ProcMonDebugOutput. John will likely accept that patch.

If I were to add this to a separate assembly, and come across some .net executable (that I don't have the source of) that used nlog with an xml confiuration, could the xml configuration cause nlog to load my assembly via reflection and add this ProcMon Target?

**Comment by 304NotModified** [comment]
I'm sorry, who is @johnrobbins?

We prefer the separate assembly. NLog can load that assembly (manual or automatic). See https://github.com/nlog/nlog/wiki/Extending%20NLog#how-to-use-the-custom-target--layout-renderer

**Comment by 304NotModified** [comment]
Has you questions being answered?

**Comment by 304NotModified** [comment]
Closing this due inactivity.
