### ISSUE TITLE
Documentation that describe file target archiveNumbering="DateAndSequence" behavior

### ISSUE THREAD

**Issue by pocheptsov** [NLog/NLog#832]
It will be great to have documentation in https://github.com/nlog/nlog/wiki/File-target that describe file target archiveNumbering="DateAndSequence" behavior. It was added at https://github.com/NLog/NLog/pull/449 PR and still not documented. I found it accidentally with nlog API code.

**Comment by 304NotModified** [comment]
Agree.  Can you do that? We're busy with preparing the upcoming release.

**Comment by 304NotModified** [comment]
This is done

**Comment by 304NotModified** [comment]
Also some examples are added:

https://github.com/NLog/NLog/wiki/File-target#archive-numbering-examples
