### ISSUE TITLE
High-performance branch of NLog

### ISSUE THREAD

**Issue by georgiosd** [NLog/NLog#838]
Hey all,

This may fit nicely with the "looking for developers" post. 

I am currently working on a very high performance application that I inherited from someone else who used a very simple, yet effective logger, with a circular non-locking buffer on the backend with a separate thread that wrote entries to file.

I tried to migrate to NLog in order to get all the added features but unfortunately I found that it took 3-5x to get off the calling thread than the original solution, even with an async wrapper. It turns out that in that case, most energy is consumed by filtering and routing. 

Have you considered a high performance branch (if modifications that don't fit to the main branch are required)? 

Georgios

**Comment by 304NotModified** [comment]
Hi,

did you have seen this?

https://github.com/NLog/NLog/wiki/performance

**Comment by georgiosd** [comment]
Thank you - I hadn't actually seen it but it doesn't really change anything for this use case.

It's not a particular high volume of messages - just a requirements for getting off the calling thread as soon as possible.

**Comment by 304NotModified** [comment]
I understand it know :) 

I think this can be an option in NLog? I think we could create a separate thread for handling the routes and filtering.

**Comment by georgiosd** [comment]
Is there a benchmarking project for NLog? I could take a look at making some optimizations.

**Comment by 304NotModified** [comment]
No there isn't. A benchmark would be cool :)

**Comment by 304NotModified** [comment]
What are the next steps for this? I think this issue can be closed?

**Comment by georgiosd** [comment]
I've forked the branch today - I'll start writing some benchmarking code.

If you have any thoughts on suitable tests, let me know.

**Comment by 304NotModified** [comment]
I think we should start with the most basic case. And then introduce features etc.

**Comment by georgiosd** [comment]
Agreeg - will send you a pull request once I've created something of satisfaction.

**Comment by 304NotModified** [comment]
Nice! 

I will close this issue because there is no action from our site needed.

**Comment by 304NotModified** [comment]
If you have any question, just let them know.
