### ISSUE TITLE
File target doesn't duplicate header in archived files for custom target

### ISSUE THREAD

**Issue by hariniyedururi** [NLog/NLog#841]
Continuation of discussion from https://github.com/NLog/NLog/issues/245
> Has this issue been fixed? I see the changes made as suggested in above issue in NLog FileTarget.cs but still have the issue if missing header. I tried 3.2.

I have a custom logger called customFileLogger which extends from FileTarget

```xml
<logger name=" customFileLogger " levels="Debug" writeTo=" customFileLogger " />

<target name=" customFileLogger " xsi:type=" customFileLogger " archiveAboveSize="1000000" archiveFileName="${basedir}/../logs/Metrics/archive/${event-context:item=ProcessName}.${event-context:item=HostSystemFileName}.${date:format=yyyyMMddHHmmssfff}.csv" maxArchiveFiles="100" fileName="${basedir}/../logs/Metrics/${event-context:item=ProcessName}.${event-context:item= HostSystemFileName }.csv" layout="${message}"/>
```
And my customFileTarget code is as follows
```c#
[Target("customFileLogger")]
    public class NLogCustomFileTarget : FileTarget
    {
        public string Message { get; set; }
        protected override void Write(LogEventInfo logEvent)
        {
            SetHeaderAndMessage(logEvent);
            base.Write(logEvent);
        }
        public void SetHeaderAndMessage(LogEventInfo logEvent)
        {
            if (logEvent == null) return;
            if (logEvent.Properties.Count > 0 && logEvent.Properties["Header"] != null)
                this.Header = logEvent.Properties["Header"].ToString();
        }
    }
```

> "The header trick in you custom logger won't work. When we archive the file, we don't have any logEvents.You can test it by giving the Header an initial value in the contructor of NLogCustomFileTarget . Closing this. If you need some help, please open a new ticket as this bug has been fixed. " https://github.com/NLog/NLog/issues/245#issuecomment-128516406

As per below suggested, I tried assigning this.header value in the constructor of NLogCustomFileTarget . But it doesn't seem to work. Not sure if I’m missing some other flag

**Comment by 304NotModified** [comment]
Can you try setting the header in `InitializeTarget`?

```c#

        /// <summary>
        /// Initializes file logging by creating data structures that
        /// enable efficient multi-file logging.
        /// </summary>
        protected override void InitializeTarget()
        {
            base.InitializeTarget();

            Header = "testheader";
        }
```

**Comment by 304NotModified** [comment]
Did this work?

**Comment by hariniyedururi** [comment]
It worked for me when I added the following line to write method.

 
protected override void Write(LogEventInfo logEvent)
        {
this.CleanupInitializedFiles(DateTime.Now);

            SetHeaderAndMessage(logEvent);
            base.Write(logEvent);
        }
