### ISSUE TITLE
How to log the full URL in NLog 4 with NLog.Web

### ISSUE THREAD

**Issue by AMgdy** [NLog/NLog#842]
Hello, How can I log the full URL including the querystring in NLog v4 using NLog.Web in a simple way?

If I use `${aspnet-request:serverVariable=HTTP_URL}` it logs only the page without the querystring.

If the is the URL of the page `http://localhost:62417/?id=512` then logs like:

`${aspnet-request:serverVariable=HTTP_URL}` logs `/default.aspx`

**Comment by 304NotModified** [comment]
Hi,

What do you mean with the full URL?

1. http://localhost:62417/default.aspx?id=512 
2. http://localhost:62417/default.aspx
3. default.aspx?id=512

**Comment by 304NotModified** [comment]
Has your question being answered?

**Comment by AMgdy** [comment]
Yes, Thanks.

**Comment by 304NotModified** [comment]
Thanks for the confirmation!
