### ISSUE TITLE
Document NDC usage

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#846]
Describe when to use the NDC, and how. (also from API)

Example:
http://stackoverflow.com/questions/334367/when-to-use-nested-diagnostic-context-ndc

To here: 
https://github.com/NLog/NLog/wiki/Ndc-Layout-Renderer

Also:
- [ ] refer from NDC, to GDC, MDC and event-properties (and visa versa)

**Comment by 304NotModified** [comment]
See also https://github.com/NLog/NLog/pull/743

**Comment by snakefoot** [comment]
NDC has been replaced by ScopeContext Nested States: https://github.com/NLog/NLog/wiki/ScopeNested-Layout-Renderer
