### ISSUE TITLE
MaxArchiveFiles deleting old files in the wrong order

### ISSUE THREAD

**Issue by Addi-B** [NLog/NLog#847]
When using the following code the MaxArchiveFiles function starts to delete the files starting from sequence number 10 after deleting number 1 instead of continuing to delete the single digit numbers.

    fileTarget.ArchiveFileName = filePath + LogName  +".{##}.log";
    fileTarget.KeepFileOpen = false;
    fileTarget.ArchiveNumbering = ArchiveNumberingMode.DateAndSequence;
    fileTarget.ArchiveEvery = FileArchivePeriod.Day;
    fileTarget.MaxArchiveFiles = 30;
    fileTarget.ArchiveAboveSize = 1048576; // 1 MB
    fileTarget.Layout = "${longdate}|${message}"; 

The resulting logfile names are:

    something.20150812.0.log
    ...
    something.20150812.9.log
    something.20150812.10.log
    ...

After all the files from number 10 to 19 are deleted it deletes the log with sequence number 2 and continues deleting the logs with numbers 20-29.
The pattern seems to be:
1 - 10 - 11 ... 19 - 2 - 20 - 21 ... 29 - 3 - 30 - 31 ... 39 ...

**Comment by Addi-B** [comment]
Please comment if any additional information is needed!

**Comment by 304NotModified** [comment]
So it occurs after deleting minimal  12 files? 

This could be easy unit tested :) . There are already unit tests for archiving.  Do you have time to do that?

**Comment by 304NotModified** [comment]
bug confirmed. Thanks! 

Now have to fix it ;)

**Comment by 304NotModified** [comment]
fix done!
