### ISSUE TITLE
Make NLog.Internal.PropertyHelper public

### ISSUE THREAD

**Issue by czema** [NLog/NLog#849]
I am working on a JsonLoggerConfiguration which will work with ASP.NET 5 IConfiguration interface.  It works like XmlLoggerConfiguration, however I had to fork PropertyHelper because it is marked internal.  Any chance we could make it public?

XmlLoggingConfiguration.ConfigureObjectFromAttributes uses PropertyHelper to convert the value strings into proper NLog values.

**Comment by 304NotModified** [comment]
Well, a lot of things have to be public for that. I'm doubting. The `JsonLoggerConfiguration` sounds nice. Can't we have it merged with NLog (this repo)?

**Comment by 304NotModified** [comment]
The real benefit of the `internal` is that we can change everything without backwardscomp problems :)

**Comment by czema** [comment]
That makes sense.

I would be willing to merge it.  However, it requires a reference to Microsoft.Framework.Configuration in .NET 4.6, so I would think NLog would then require a dependency on that, right?

**Comment by 304NotModified** [comment]
We use compilation symbols for that,  see https://github.com/NLog/NLog/blob/master/CONTRIBUTING.md#multiple-net-versions

No problem to create a 4.6. 

So fork and PR :)

**Comment by 304NotModified** [comment]
More in detail:

To create a 4.6 version:

- create separate solution: `NLog.netfx46.sln` (copy of `NLog.netfx45.sln`)
- create separate project file: `NLog.netfx46.csproj`
- create and use `NET4_6` 
- check the code for `NET4_5` code and use `NET4_6` when appropriate
- search in all files for NLog.netfx45.csproj and NLog.netfx45.sln, and change when appropriate

**Comment by czema** [comment]
Will I be able to take out a reference to the Microsoft.Framework.Configuration 1.0.0-beta6 NuGet package?

**Comment by 304NotModified** [comment]
good question. That will be difficult, because the packages.config is shared between all .Net versions. Not sure how to solve that.

**Comment by 304NotModified** [comment]
I'm not sure if you add an `targetFramework="net46"` attribute, other frameworks will ignore this package.

**Comment by 304NotModified** [comment]
any luck with this?

**Comment by 304NotModified** [comment]
I will close this one because we cannot do something with this ticket.

But we are really like a PR (try-out or not) for this feature :)

If you need some help, let us know,
