### ISSUE TITLE
File ArchiveEvery Day/Minute... is ignored when using rolling numbering

### ISSUE THREAD

**Issue by Addi-B** [NLog/NLog#859]
Noticed another possible bug when trying to get around the issue with the wrong archive files getting deleted.

With version 4.0.1 using the following code the log archiving function ignores the rollover from one day to another and continues to write the new log messages into the file started the other day.

    fileTarget.FileName = updateLogDirectory + logName + ".log";
    fileTarget.ArchiveFileName = updateLogDirectory + logName + ".{##}.log";
    fileTarget.KeepFileOpen = false;
    fileTarget.ArchiveNumbering = ArchiveNumberingMode.Rolling;
    fileTarget.ArchiveEvery = FileArchivePeriod.Day;
    fileTarget.MaxArchiveFiles = 30; 
    fileTarget.ArchiveAboveSize = 1048576; // 1 MB
    fileTarget.Layout = "${longdate}|${message}";

**Comment by 304NotModified** [comment]
Thanks for reporting!

Can you give an example? I don't fully understand it. It this also an issue with ArchiveEvery minute (for unit testing)

**Comment by Addi-B** [comment]
It's the same using the minute option.
The created Log looks something like this (just a quick test application):

    2015-08-17 22:54:59.9677|Something_Created : C:\*\*\28995.txt
    2015-08-17 22:54:59.9887|Something_Created : C:\*\*\28996.txt
    2015-08-17 22:54:59.9947|Something_Created : C:\*\*\28997.txt
    2015-08-17 22:55:00.0177|Something_Created : C:\*\*\28998.txt
    2015-08-17 22:55:00.0177|Something_Created : C:\*\*\28999.txt
    2015-08-17 22:55:00.0317|Something_Created : C:\*\*\29000.txt

**Comment by Addi-B** [comment]
Just noticed that it works every other minute but not consistently or remotely predictable.

**Comment by 304NotModified** [comment]
OK clear! Thanks!

**Comment by Addi-B** [comment]
Possibly related to #550

**Comment by 304NotModified** [comment]
Thanks! They seem the same issues indeed
