### ISSUE TITLE
Troubleshooting Hurdles

### ISSUE THREAD

**Issue by AaronLS** [NLog/NLog#862]
.

**Comment by 304NotModified** [comment]
Which NLog version are you using? We fixed some things with the throwExceptions in the last releases.


Troubleshooting on top of troubleshooting:
http://stackoverflow.com/questions/9428724/nlog-internal-log-not-working-with-asp-net-mvc

> I turned throwExceptions on both through the config as well as through code and no exceptions are thrown, even when I have an internal log file configured that it fails to write to.  Seems like if it fails to write the internal log file, and throwExceptions is turned on, then it should throw an exception.

Do you have an example that won't work?



>  I would expect a failure to write the internalLogFile should result in an exception.

I don't. I internallogging should never interrupts logging at all.

- I would suggest adding a internalLogToDebugConsole and clarify in documentation that internalLogToConsole/Error may be silent for some project types because they point to null streams.

> what should `internalLogToDebugConsole ` do? It's not all fully clear. 

> Config file is successfully loading because I can inspect the log manager Configuration and see the targets from the config file.  

I'm sorry, what should I do with this information?

I looks like you are a bit upset, and we are sorry to see that. Your post is a bit unstructured and difficult to follow. We always try to let NLog working smooth and simple for users.

**Comment by AaronLS** [comment]
"I looks like you are a bit upset, and we are sorry to see that"
Nope, just providing suggestions on how to improve NLog. Why do you think I'm upset?  I used no profanity, I did not personally attack the software or the team.  I provided distinct constructive suggestions on how to improve the state of affairs.

"Your post is a bit unstructured and difficult to follow."
Wow you are really trying to attack this thing on a confrontational level?  Why do you persist in this way?  Fine, I'll explain to you the structure of my post.

- I first provided an introduction to the problem, providing an overview.  It is usually a good idea to begin with an introduction that summarizes the issue at hand before delving into the details.  I'm sorry you are unfamiliar with this very common structure.
- I provided, as evidence supporting this, a link to an example showing how much discussion and troubleshooting has to be done to just get internal logging working, and that's before one can actually even troubleshoot the real issue at hand.  That's why I called it "Troubleshooting on top of troubleshooting"
- I provided information on what I tried as per the troubleshooting guide to demonstrate that I had followed that information, yet could not garner any diagnostic information.  This is typical of most bug reports, as a developer typically expects that the user would have followed such guides, and therefore I am demonstrating that I have done that due diligence and it did not lead to any additional diagnostic information.  Sorry that this concept is unfamiliar to you and leads you to believe I am upset.
- I then provided 3 bulletted items that offered suggested improvements.  `internalLogToDebugConsole` would log to Diagnostics.Debug.WriteLine as mentioned in the introductory paragraph.  Again, for web projects stderr/stdout both point to Null streams.
- I then shared my config information and verified it was loading correctly, to show how I configured internalLogging to eliminate the need for followup questions about whether I had configured it properly and eliminate questions regarding whether I verified config file was loading.

I summarized the problem, provided evidence that it is not an isolated problem and others have encountered similar difficulties, demonstrated my due diligence, and concluded by offering suggested improvements.  This is the basic element of good communication.  Describe the problem, provide supporting information, offer a suggested improvements.  What is unstructured about that?

"I'm sorry, what should I do with this information?"

First step in your troubleshooting guide involves determining whether or not the config is loading correctly or not.  So I was eliminating that as a possibility so that you wouldn't have to ask me whether I verified that already.  Had I not shared that information first thing out of your mouth would have been "Did you verify your config file is loading correctly?"  Again this is the basic element of a good bug report, to demonstrate due diligence in eliminating possible issues such as failure to load a config file.   Why do you persist in attacking every element of my post?  If anyone seems upset it is you.

**Comment by 304NotModified** [comment]
I don't like we're this is going. If I cannot tell it's difficult too follow and get things like

**Comment by 304NotModified** [comment]
,

**Comment by 304NotModified** [comment]
We don't like if people are trying to put words in someone mouth. Support stops there.

**Comment by AaronLS** [comment]
Interesting how you deleted this chain to cover up how you turned constructive suggestions into personal attacks.  Fortunately I have the full chain via email so everyone can see the vitriol you dish out.

**Comment by 304NotModified** [comment]
Go trilling
