### ISSUE TITLE
NLog removes archive files

### ISSUE THREAD

**Issue by desember** [NLog/NLog#863]
Hello. I'm facing strange behaviour of NLog library. At midnight it removes all files in log folder except current one. Even if I create file with date as a name maually.

NLog version 4.0.1. 

My configuration is:
```
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" autoReload="true"
      internalLogFile="C:\***\Nlog.txt" internalLogLevel="Trace">

  <targets>

    <target xsi:type="File" 
            name="f" 
            fileName="${basedir}/logs/log.log"
            archiveFileName="${basedir}/logs/log.{#}.log"
            archiveEvery="Day"
            archiveNumbering="Date"
            maxArchiveFiles="30"
            layout="${longdate} {${uppercase:${level}}} ${message} ${exception:format=tostring}"/>
    
    <target xsi:type="File"
            name="res"
            fileName="${basedir}/logs/results.log"
            archiveFileName="${basedir}/logs/results.{#}.log"
            archiveEvery="Day"
            archiveNumbering="Date"
            maxArchiveFiles="30"
            layout="${longdate}: ${message}"/>
  </targets>

  <rules>
    <logger name="results" minlevel="Debug" writeTo="res" final="true" />
    <logger name="*" minlevel="Debug" writeTo="f" />
  </rules>
</nlog>
```
Internal logfile contents:
```
2015-08-17 23:59:14.7843 Trace Opening C:\***\/logs\log.log with concurrentWrite=False
2015-08-17 23:59:42.3019 Trace Opening C:\***\/logs\log.log with concurrentWrite=False
2015-08-17 23:59:44.7120 Trace Opening C:\***\/logs\log.log with concurrentWrite=False
2015-08-18 00:00:13.3857 Trace Opening C:\***\/logs\log.log with concurrentWrite=False
2015-08-18 00:00:16.0328 Trace Opening C:\***\/logs\log.log with concurrentWrite=False
2015-08-18 00:00:46.3106 Trace Opening C:\***\/logs\log.log with concurrentWrite=False
2015-08-18 00:00:49.0217 Trace Opening C:\***\/logs\log.log with concurrentWrite=False
```

**Comment by 304NotModified** [comment]
I think this have to do with the 2 file targets on the same directory.  Can you test with 2 different directories?

**Comment by desember** [comment]
I've tested it. It didn't help.

**Comment by 304NotModified** [comment]
Can you test with one filetarget in total?

That would help writing an unit test

**Comment by desember** [comment]
Same behavior with one target. 
Config:
```
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" autoReload="true"
      internalLogFile="C:\***\Nlog.txt" internalLogLevel="Trace">
  <targets>
    <target xsi:type="File"
            name="f"
            fileName="${basedir}/logs/log.log"
            archiveFileName="${basedir}/logs/log.{#}.log"
            archiveEvery="Day"
            archiveNumbering="Date"
            maxArchiveFiles="30"
            layout="${longdate} {${uppercase:${level}}} ${message} ${exception:format=tostring}"/>
  </targets>
  <rules>
    <logger name="*" minlevel="Debug" writeTo="f" />
  </rules>
</nlog>
```
OS: Windows Server 2012 R2
Nlog version: v 4.0.1

**Comment by kt1996** [comment]
Hey, I am willing to try my best and sort out this one. Just I am running windows 7, and I have no clue how to emulate the midnight condition. Thanks a lot !!

**Comment by bhaeussermann** [comment]
If you want to produce the problem in an application (VS solution), you could look into changing your system time during runtime (perhaps you could do this programmatically in your app).

As for producing the problem in a test (in `FileTargetTest.cs`), you can emulate date/time changes using `TimeSource` (there are other tests which use `TimeSource`).

**Comment by kt1996** [comment]
Sorry for being so vague, I didn't mean that, what I meant to ask was that should I have a program logging through every 1/10th second and then passing the program through midnight time to emulate the situation. Thanks!!

**Comment by bhaeussermann** [comment]
Well, yes. How about setting your system time to just before midnight before starting the logging?

**Comment by kt1996** [comment]
Yeah definitely, of course i'll be doing that. Thanks for confirming that I'll have to run logging 'through' the midnight time.. !!

**Comment by bhaeussermann** [comment]
I couldn't produce the issue. This has probably been fixed since version 4.0.1.

**Comment by kt1996** [comment]
Same here, couldn't reproduce it too...

**Comment by 304NotModified** [comment]
Well that's good news. :) 

Which version have you tested @kt1996

**Comment by kt1996** [comment]
@304NotModified Sorry, but where can I find the version .... I had forked the repository and tested it..

**Comment by 304NotModified** [comment]
That's fine too :) 

master is 4.3

**Comment by desember** [comment]
Sorry for such late answer, but I've figured out reason for this behavior. We had another service application, that backed up logs and configs  and moved them to another server. Backup happened right after midnight. 
Once again, sorry for false alarm. NLog works like a charm.

**Comment by 304NotModified** [comment]
No problem! Thanks for the feedback,  glad everything works fine now :)
