### ISSUE TITLE
Small typo for the longdate layout renderer

### ISSUE THREAD

**Issue by vilhelmericson** [NLog/NLog#864]
Hi,
The 'Layout Renderers' page of the wiki, https://github.com/nlog/NLog/wiki/Layout-Renderers, states that the longdate layout renderer output is formatted as yyyy-MM-dd HH:mm:ss.mmm. The format should be yyyy-MM-dd HH:mm:ss.mmmm as stated in the 'Longdate Layout Renderer' page of the wiki, https://github.com/nlog/NLog/wiki/LongDate-Layout-Renderer.

**Comment by 304NotModified** [comment]
Well I prefer to change the wiki

**Comment by 304NotModified** [comment]
Thanks for the report. This has been fixed. It's also double checked with the current code.
