### ISSUE TITLE
empty trace.axd message when wrapped in async="true"

### ISSUE THREAD

**Issue by AKealey** [NLog/NLog#865]
Hello.
I am having an issue when placing my AspNetTrace type in the ``` <targets async="true">``` wrapper.
target:       

 ```xml
 <target name="traceAXD" 
  type="AspNetTrace" 
  layout="${longdate}${newline}logger: ${logger}${newline}${level:uppercase=true}${newline}${callsite}${newline}${message}${onexception:${newline}${exception:format=tostring:maxInnerExceptionLevel=5}}${newline}---------------------------------------"/>
```

The axd message remains empty when async ="true" but when set to false it properly prints the message.

Also, wrapping the above target in its own ```<target name="asyncTargets" type="AsyncWrapper">``` wrapper will print to the axd page.

Any idea on what it is about the shorthand ```<targets async="true">``` wrapper that stops the AspNetTrace from printing a message?
Thanks.

**Comment by 304NotModified** [comment]
That's strange. I don't know why the behave differently.  We should to investigate this.

**Comment by 304NotModified** [comment]
which NLog version? Did you checked the internal log?

**Comment by AKealey** [comment]
Hello.
I am using NLog version 4.0.30319 and NLog.Web version 2.0.50727.
As far as I can tell there is nothing revealing in the internal log but I wouldn't rule out overlooking something due to my inexperience.

**Comment by BrutalCode** [comment]
I will investigate this issue on Saturday or Sunday.

**Comment by 304NotModified** [comment]
@BrutalCode 

Hint: I could have something todo with assembly versions, so if you can't reproduce the error, we have to look to the versioning.

**Comment by BrutalCode** [comment]
I checked the assembly version of NLog.Web, it is 1.0.0.0 at the [master] (https://github.com/NLog/NLog.Web)

I will try to reproduce the error and let you know.

**Comment by UgurAldanmaz** [comment]
Hi @AKealey .
I tried to reproduce it. But encounter another problem.

To be sure that everything works, I added the file target to the configuration. File target not works when AspNetTrace and File Target config exist together.
When I remove the AspNetTrace target from config, file target does works.
Did you use another target?

BTW, there is no NLog version 4.0.30319 and NLog.Web version 2.0.50727. Could you check again?

**Comment by AKealey** [comment]
Hi.
 Sorry, its NLog version 4 (runtime version 4.0.30319) and NLog.Web version 2.0 (runtime version 2.0.50727).
Unfortunately the project has changed quit a bit since then and I wont be able to rollback the project to test it.

What I do remember is it was only the <targets async="true"> shorthand hat caused empty traces (as opposed to the full declaration).



________________________________

**Comment by 304NotModified** [comment]
What are the version is NuGet?

**Comment by AKealey** [comment]
NLog version as viewed in Nuget is 4.0.1


________________________________

**Comment by UgurAldanmaz** [comment]
Thanks @AKealey I will test again with [latest NLog version] (https://www.nuget.org/packages/NLog/4.2.1). Because maybe this problem does not exist anymore.
I will try to solve it in the development branch, if still exist.

**Comment by AKealey** [comment]
Thanks!

I have also been informed by a colleague who had the same issue a while back that it looks like it tries to write the log to the wrong thread. Although he was unable to diagnose it fully.


________________________________

**Comment by UgurAldanmaz** [comment]
Hi @AKealey 

I have produced the error.

My test code:
```csharp
Trace.Warn("Built-in Trace. This message is not written by NLog.Web -> threadid: " + Thread.CurrentThread.ManagedThreadId);
Logger logger = LogManager.GetLogger("traceAXD");
logger.Debug("warn from nlog web");
logger.Info("warn from nlog web");
logger.Warn("warn from nlog web");
logger.Error("warn from nlog web");
logger.Fatal("warn from nlog web");
```

When using the `async="true"` shorthand, I am getting this result:
![shorthand2](https://cloud.githubusercontent.com/assets/5686267/11571737/82323728-9a06-11e5-8365-cacad0f76e46.PNG)
You said for this case that: 
> The axd message **remains empty** when async ="true" but when set to false it properly prints the message.

I want to be sure if I understand you correctly. Because you said *remains empty*. But in my test result, there is nothing. No message written. Is my result same thing with yours? 


> Also, wrapping the above target in its own <target name="asyncTargets" type="AsyncWrapper"> wrapper will print to the axd page.

Yes, it is same for me:
![wrapped2](https://cloud.githubusercontent.com/assets/5686267/11571811/e4b2005e-9a06-11e5-83ad-af7140544911.PNG)

I am investigating the reason. But I need your answer.

**Comment by AKealey** [comment]
Yes, that seems to be the issue I was having. By empty I mean no data presented, as if nothing happened.

But it looks like you can reproduce the same problem.


________________________________

**Comment by UgurAldanmaz** [comment]
Thank you @AKealey. As we encounter the same problem, I can try to solve it clearly :)

**Comment by 304NotModified** [comment]
This seems to be related

https://github.com/NLog/NLog/issues/1073

**Comment by 304NotModified** [comment]
> I have also been informed by a colleague who had the same issue a while back that it looks like it tries to write the log to the wrong thread. Although he was unable to diagnose it fully.

I'm really curious if you have some more info on this @AKealey !

**Comment by 304NotModified** [comment]
it seems that the AsyncWrapper is not working at all... (but the async attribute is working - well, not in this case) . See #1073

**Comment by 304NotModified** [comment]
@UgurAldanmaz with the async attribute, does the code ever reach `AsyncTargetWrapper.Write(..)`?

**Comment by UgurAldanmaz** [comment]
2 days ago, I have analysed the internal logs of the configuration loading. Noticed that somethings was going wrong while target is wrapping. But I could not figure out what happen, because I am so sleepy. :)

And now, it is weekend, and I am ready to investigate in deepth.

**Comment by 304NotModified** [comment]
I think I know the problem.  The async code is a timer (see async wrapper) . That's in another thread which doesn't have access to the httpruntime.  See Google (now on mobile, difficult to paste :p)

**Comment by 304NotModified** [comment]
That the AsyncWrapper-target is working, but not the async attribute is probably because you need to change the rules on the config when using the async wrapper. (see referenced issue, made the same mistake) . 

So without doing that, the code isn't run async and so no thread issue.

**Comment by UgurAldanmaz** [comment]
As @304NotModified said, logs are written by different thread in async mode, of course.
Tracing can do with the `HttpContext` which is null for the different thread. [If `HttpContext.Current` is null, then trace writing canceled.] (https://github.com/NLog/NLog.Web/blob/master/NLog.Web/Targets/AspNetTrace.cs#L25)

But if AspNetTrace target wrapped by AsyncWrapper -without shorthand, probably different thread problem will not occur. 
We can see it in my second test result which successfully wrote the message: Look at the ThreadId info in the logs. 
* First line was written by standart AspNet tracing which in main thread. ThreadId is 28.
* And following lines was written by AspNetTrace target which was async wrapper. ThreadId is 28 too! 
It seems that thread did not changed, as a result log messages could be written.

This bug should be resolved, but cannot be done in the soonest time. We need to analyse side effects, and seek a solution. We suggest that do not use the async shorthand and wrap it directly. If problem is still continuing despite wrapping, please do not use the async wrapper.

We apologize for it.

Note:
> I have also been informed by a colleague who had the same issue a while back that it looks like it tries to write the log to the wrong thread. Although he was unable to diagnose it fully.

If your colleague can remember details or produce again, please inform us.

Thanks!

**Comment by 304NotModified** [comment]
> But if AspNetTrace target wrapped by AsyncWrapper -without shorthand, probably different thread problem will not occur. 
> We can see it in my second test result which successfully wrote the message: Look at the ThreadId info in the logs.
> 
> First line was written by standart AspNet tracing which in main thread. ThreadId is 28.
> And following lines was written by AspNetTrace target which was async wrapper. ThreadId is 28 too! It seems that thread did not changed, as a result log messages could be written.
> This bug should be resolved,

@UgurAldanmaz , I'm pretty sure this isn't a bug. If you use the async-wrapper, then all the messages should be written to the aync-wrapper (and not the wrapped version). I have tested it that the async attribute is behaving the same as the async wrapper. 



> If your colleague can remember details or produce again, please inform us.

I think this is about the "wrong thread", which is the thread of the timer.

Anyway, concluding, we cannot write async to the aspnettrace. Maybe we if we have a other construct the the `Timer`. I will label this as "known issue".

**Comment by AKealey** [comment]
Hi, thanks for all your help!

Unfortunately, he really cant remember (was quite a while ago).

If this is indeed a known issue then we will continue to use our current setup for now.


________________________________

**Comment by 304NotModified** [comment]
This should be work, we have `IsThreadAgnostic` on Target. 

related https://github.com/NLog/NLog/issues/1136
