### ISSUE TITLE
VS 2015 build log Chinese character change to garbage. 

### ISSUE THREAD

**Issue by LingTec** [NLog/NLog#867]
![image](https://cloud.githubusercontent.com/assets/6530098/9377138/5a218272-4748-11e5-8bdd-44d98bcb66aa.png)

Not sure NLog needs change something or it is VS2015 problem. Please see above log output from two different VS build. 

Many thanks,

**Comment by 304NotModified** [comment]
Hi,

can you give some more information? Is this corretly working in Vs2013? Which NLog version is this? And can you post (relevant parts of) your config and code?

**Comment by LingTec** [comment]
Hi,I create a simple project and do the same thing as my original project.  Guess what it does not happened. This prove I must did something wrong in the big project. So I am going to recreate (install NLog) in that project. Before doing that I want to reply your email first and I want to close that issue since now I prove myself it shall work. Thank you for your fast response and sorry to put false alarm. It is another wonderful day.Cheers!ShulingOn August 20, 2015 at 6:53 PM Julian Verdurmen <notifications@github.com> wrote:Hi,can you give some more information? Is this corretly working in Vs2013? Which NLog version is this? And can you post (relevant parts of) your config and code?—Reply to this email directly or view it on GitHub.

**Comment by 304NotModified** [comment]
OK, no problem!
