### ISSUE TITLE
How to use formatting on custom variables?

### ISSUE THREAD

**Issue by lgmorand** [NLog/NLog#868]
Hi,

I'm using custom variables that I insert in database using event-context. Everything works fine.
Now I have an issue with Datetime variables. With the ${date} variable and format attribute, it is OK but I did not find the syntax to apply a formatting on event-context variables.

Any idea on how to do that?
Thanks

LG

**Comment by 304NotModified** [comment]
Can you post the relevant config? It's easier to explain then. :)

**Comment by lgmorand** [comment]
Hi :)

I have something like that
 <parameter name="@CreationDate" layout="${event-context:item=CreationDate}" />

and I would like to do something like that
${date:format=yyyy-MM-dd HH\:mm\:ss} 

where ${date} is replaced by my variable
The reason is because milliseconds are dropped in database (SQL) if I don't provide the format

**Comment by 304NotModified** [comment]
To bad this is only possible in the API when setting.

So 
```c#
theEvent.Properties["CreationDate"] = CreationDate.ToString("yyyy-MM-dd HH:mm:ss")
```

We can make this to a feature request. it's easy to implement (PR accepted)

**Comment by lgmorand** [comment]
Hi Julian,

At least, I'm not crazy, it was not implemented. I found the workaround using the C# directly but it does not allow me to have a different format by target. Anyway, a feature request would be great but for now, I'll use a workaround. So you can put it in backlog with a low priority (mainly if I'm the first one with this requirement :))

BTW, THANKS for your help

**Comment by 304NotModified** [comment]
Reopen: create feature request issue (up for grabs)

**Comment by 304NotModified** [comment]
Feature request Created.

**Comment by 304NotModified** [comment]
It's already implemented :)

**Comment by 304NotModified** [comment]
Next release. Next week.

**Comment by lgmorand** [comment]
?!!!!

<3 <3 <3 :)

So what would be the format to use a context variable + a format?

**Comment by 304NotModified** [comment]
The format parameter.  

See
https://github.com/NLog/NLog/pull/871

I found the tostring in the api lame :p

**Comment by lgmorand** [comment]
Perfect! will try it as soon as the nugget package is available.

anyway, a BIG thanks!

**Comment by 304NotModified** [comment]
:)
