### ISSUE TITLE
Instance-context instead of thread-local-context?

### ISSUE THREAD

**Issue by SystemKeeper** [NLog/NLog#869]
Hello,

I'm currently using NLog 4.0.1 and want to add additional informations when logging from a specific class. Consider this class for example:
```vbnet
Public Class Device
  Private Shared logger As NLog.Logger = NLog.LogManager.GetCurrentClassLogger()
  Private DeviceId as Integer

  Public Sub New(DeviceId as Integer)
    Me.DeviceId = DeviceId
  End Sub

  Public Sub TestLog()
    logger.Debug("TestLog")
  End Sub
End Class
```
I'm creating multiple instances of this class with a different DeviceId and store the reference in a List:
```vbnet
Dim DeviceList As New List(Of Device)
For i = 0 To 20
  DeviceList.Add(new Device(i))
Next
```
Now all calls to the device-classes are done using the Task-Library:
```vbnet
For Each Dev in DeviceList
  Task.Factory.StartNew(Sub()
      Dev.TestLog()
    End Sub)
Next
```
This works fine so far, but I'm unable to use something like MDC as the Task-Lib is using a ThreadPool and adding the DeviceId to the MDC will result in wrong outputs if the TestLog-Call is done by a different thread.
Therefore I was wondering if it would be possible to add something like a instance-context to the logger - in this case a logger must not be static/shared:
```vbnet
Public Class Device
  Private logger As NLog.Logger = NLog.LogManager.GetCurrentInstanceLogger()
  Private DeviceId as Integer

  Public Sub New(DeviceId as Integer)
    Me.DeviceId = DeviceId
    logger.Context.set("DeviceId", DeviceId)
  End Sub
  (...)
End Class
```
Is something like this possible or is there another way to achieve this? Currently I'm using a string-variable which is set in the constructor of Device and include it in all log-calls. This works, but is not really nice.

Thanks in advance!

**Comment by 304NotModified** [comment]
Too bad that isn't possible (yet). What you can do:

use the GDC and prefix the key with the loggername. You can write some nice C# extensions to keep the code clean.

**Comment by SystemKeeper** [comment]
Thanks for your quick response! Judging by your comment, something like this is on the roadmap for a future version of NLog?

Interesting idea using GDC and using the loggername as prefix - I'll see how this works. Do you have an example of a C# extension method? Currently I don't know what type should be extended and how.

Thanks again!

**Comment by 304NotModified** [comment]
Something like this?

```c#

namespace NLog
{
    internal static class MappedDiagnosticsContextExt
    {
        public static void SetLoggerContext(this ILogger logger, string key, string value)
        {
            GlobalDiagnosticsContext.Set(logger.Name + "-" + key, value);
        }

        public static void Test()
        {
            var logger = LogManager.GetLogger("logger1");
            logger.SetLoggerContext("a", "is not b");

            // print as:
            // "${gdc:item=logger1-a}";
        }
    }
}
```


I'm happy I did not have to write VB.net ;)

**Comment by SystemKeeper** [comment]
Ah, I see now. Indeed this leads to very clean code. Thank you very much for taking the time!
Although most of my code is vb.net, I'm fine with C# as well ;)
