### ISSUE TITLE
NLog ImpersonatingWrapper Example

### ISSUE THREAD

**Issue by wilseq10** [NLog/NLog#876]
Hi, I am attempting to implement error logging using NLog on wfp application, but need write files to a central server/shared drive. I have seen the ImpersonatingWrapper as a potential way I could go about it, but I couldnt find detailed documentation on how to do this. Is there an example out there i could use or anyone who has implement this target type, and how? Please assist. Thanks

**Comment by 304NotModified** [comment]
You can check the unit tests 

https://github.com/NLog/NLog/blob/master/tests/NLog.UnitTests/Targets/Wrappers/ImpersonatingTargetWrapperTests.cs

**Comment by 304NotModified** [comment]
Has you question being answered?

**Comment by wilseq10** [comment]
Not really, I stopped working on this for a bit as i was working on other more time sensitive tasks. But I will be getting back to this shortly. So, what i was looking for was a good example with a detailed configuration that is ready to work, or step by step of how to integrate this target type. I have used the file target type before, which is pretty straightforward and has numerous examples online, but the ImpersonatingWrapper dont seem to have as much. Thank you.

**Comment by 304NotModified** [comment]
It's true that the docs aren't really detailed on this topic. If you get things working, it would be great to extends the docs (wiki)

If you need some more help on this, let us know. I'm closing this issue for now, as we cannot do anything with this.
