### ISSUE TITLE
Replace layout

### ISSUE THREAD

**Issue by rodrigoferrobrti** [NLog/NLog#878]
how to use various substitutions ?

  "variable name="replacedname1" value="${replace:searchFor=ã:replaceWith=a:regex=true:inner=${message}}"/"
" <variable name="replacedname2" value="${replace:searchFor=ç:replaceWith=c:regex=true:inner=${message}}"/"

I need to replace several letters by one, ie "ãâá" by "a"..

Thanks and sorry about my english.

**Comment by 304NotModified** [comment]
It's a bit difficult in .Net to replace diacritics. (http://stackoverflow.com/questions/249087/how-do-i-remove-diacritics-accents-from-a-string-in-net)

But I listing all possibilities is OK, then you can do:

`<variable name="replacedname1" value="${replace:searchFor=[ãâá]:replaceWith=a:regex=true:inner=${message}}`. This needs to be repeated for every char.

**Comment by rodrigoferrobrti** [comment]
Like this ?

  `<variable name="message_en_001" value="${replace:searchFor=[ÁÀÂÃ]:replaceWith=A:regex=true:inner=${message}}"/>
  <variable name="message_en_002" value="${replace:searchFor=[ÉÈÊ]:replaceWith=E:regex=true:inner=${message_en_001}}"/>
  <variable name="message_en_003" value="${replace:searchFor=[Í]:replaceWith=I:regex=true:inner=${message_en_002}}"/>
  <variable name="message_en_004" value="${replace:searchFor=[ÓÒÔÕ]:replaceWith=O:regex=true:inner=${message_en_003}}"/>
  <variable name="message_en_005" value="${replace:searchFor=[ÚÙÛÜ]:replaceWith=U:regex=true:inner=${message_en_004}}"/>
  <variable name="message_en_006" value="${replace:searchFor=[Ç]:replaceWith=C:regex=true:inner=${message_en_005}}"/>
  <variable name="message_en_007" value="${replace:searchFor=[áàâã]:replaceWith=a:regex=true:inner=${message_en_006}}"/>
  <variable name="message_en_008" value="${replace:searchFor=[éèê]:replaceWith=e:regex=true:inner=${message_en_007}}"/>
  <variable name="message_en_009" value="${replace:searchFor=[í]:replaceWith=i:regex=true:inner=${message_en_008}}"/>
  <variable name="message_en_010" value="${replace:searchFor=[óòôõ]:replaceWith=o:regex=true:inner=${message_en_009}}"/>
  <variable name="message_en_011" value="${replace:searchFor=[úùûü]:replaceWith=u:regex=true:inner=${message_en_010}}"/>
  <variable name="message_en" value="${replace:searchFor=[ç]:replaceWith=c:regex=true:inner=${message_en_011}}"/>`

Thanks

**Comment by 304NotModified** [comment]
Looks good! If you can confirm this works well, can you add it to https://github.com/NLog/NLog/wiki/Replace-Layout-Renderer#example?

**Comment by rodrigoferrobrti** [comment]
ok.. i do =]
