### ISSUE TITLE
Release nlog 4.1 extended? 

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#880]
We should think/check if a 4.1 is needed of https://www.nuget.org/packages/NLog.Extended/

**Comment by kevindaub** [comment]
If nothing has changed, which looks to be the cased (besides some minor formatting), there is no reason to update the version.  Also, the core API that it depends on hasn't changed either.

**Comment by 304NotModified** [comment]
OK thanks @kevindaub !
