### ISSUE TITLE
How to config standby target?

### ISSUE THREAD

**Issue by uliian** [NLog/NLog#882]
Hello
I have a question:how to config standby target?
In my project,There are two taggets in <targets>.The one log to db,the other one log to file.Now I want first log to db,if it throw exception,can't log success,then log to file.else if write to db success don't log to file~
how to config it?

sorry,my english very bad~

**Comment by 304NotModified** [comment]
Hi,

You can use the [FallbackGroup target](https://github.com/nlog/nlog/wiki/FallbackGroup-target). See the link for examples.

**Comment by 304NotModified** [comment]
Has you question being answered?

**Comment by 304NotModified** [comment]
Let us know if have still some questions!
