### ISSUE TITLE
System.TypeInitializationException during first GetLogger call (=NLog.Windows.Forms.dll is not signed. )

### ISSUE THREAD

**Issue by mikhail-barg** [NLog/NLog#885]
After updating to NLog 4.0.1 (from 3.2.0) our apps began to crush on one machine where previous versions were working fine.

What we currently know:
* Apps continue working on other machines, so far only one machine is found to have this problem.
* The machine does have .Net v4.5.1 installed.
* The machine runs Win 8.1 (as well as working machines).
* The crash seem to happen at the very first call to NLog, seemingly during the configuration load.
* Enabling internal logging starting from Trace level does not help, as the crash seem to happen before any logging is done.
* Stack trace reported by Windows event log:
```
System.TypeInitializationException
NLog.Config.ConfigurationItemFactory.get_Default()
NLog.Config.XmlLoggingConfiguration..ctor(System.String)
NLog.LogFactory.LoadLoggingConfiguration(System.String)
NLog.LogFactory.get_Configuration()
NLog.LogFactory.GetLogger(LoggerCacheKey)
NLog.LogManager.GetCurrentClassLogger()
OurProject.Program.Main()
```

As our projects include RichTextBox target, I'm planning first check a project without it. Also I'm going to try using *fuslogw* to at least determine the problematic assembly. Aside that, I'm out of ideas for now. 

The machine is a remote one, so trying possibilities takes time, and we'll be grateful for any recommendations on how to troubleshot this.

**Comment by 304NotModified** [comment]
Can you try with the rc of 4.1?
Do you use unc paths? 

We will release 4.1 tomorrow, but we can hold it to fix this problem.

**Comment by 304NotModified** [comment]
Also,  Is there another dll in the bin folder which starts with. "nlog"?

**Comment by mikhail-barg** [comment]
Thanks for the feedback! We finally were able to identify find the workaround.
I've made another test app using only Nlog.dll (4.0.1) and no NLog.Windows.Forms.dll, and it's running fine on this machine. So the problem is indeed in loading of NLog.Windows.Forms.dll.

The problematic machine has "The Publisher Could Not Be Verified" check enabled. If I specify the `<loadFromRemoteSources enabled="true"/>` in the app.config, the application with NLog.Windows.Forms.dll runs fine as well. 

So it seems that the problem is in combination of the machine security settings and the way Nlog additional assemblies are loading. Now I wander, what is the proper way to overcome this problem generally?

**Comment by rcreps** [comment]
NLog.Windows.Forms.dll is not signed.  Someone raised this as an issue on the Windows.Forms project:  https://github.com/NLog/NLog.Windows.Forms/issues/4

**Comment by 304NotModified** [comment]
OK, thanks for the info.

We will discuss at our site how to sign the other NLog assemblies.

**Comment by 304NotModified** [comment]
With the experience of NLog 4.1.0, we have now full confidence that we can handle the strong name shortcomings. 

So maybe a bit late, but the new NLog.Web and NLog.Windows.Forms are now strong named.
