### ISSUE TITLE
Cannot install Nlog Nuget Package 

### ISSUE THREAD

**Issue by thnk2wn** [NLog/NLog#887]
Bound to TFS 2013. Other packages are installing fine.

And in the error list "Could not find a part of the path 'C:\Source2013\CyberCoders.com\LinkedInResumeGenerator\lib"

C:\Source2013\CyberCoders.com\LinkedInResumeGenerator\NLog.4.1.0.nupkg: No file matches.
The item C:\Source2013\CyberCoders.com\LinkedInResumeGenerator\packages\NLog.4.1.0\lib\net35\NLog.dll could not be found in your workspace, or you do not have permission to access it.
The item C:\Source2013\CyberCoders.com\LinkedInResumeGenerator\packages\NLog.4.1.0\lib\net35\NLog.xml could not be found in your workspace, or you do not have permission to access it.
The item C:\Source2013\CyberCoders.com\LinkedInResumeGenerator\packages\NLog.4.1.0\lib\net40\NLog.dll could not be found in your workspace, or you do not have permission to access it.
The item C:\Source2013\CyberCoders.com\LinkedInResumeGenerator\packages\NLog.4.1.0\lib\net40\NLog.xml could not be found in your workspace, or you do not have permission to access it.
The item C:\Source2013\CyberCoders.com\LinkedInResumeGenerator\packages\NLog.4.1.0\lib\net45\NLog.dll could not be found in your workspace, or you do not have permission to access it.
The item C:\Source2013\CyberCoders.com\LinkedInResumeGenerator\packages\NLog.4.1.0\lib\net45\NLog.xml could not be found in your workspace, or you do not have permission to access it.
The item C:\Source2013\CyberCoders.com\LinkedInResumeGenerator\packages\NLog.4.1.0\lib\sl4\NLog.dll could not be found in your workspace, or you do not have permission to access it.
The item C:\Source2013\CyberCoders.com\LinkedInResumeGenerator\packages\NLog.4.1.0\lib\sl4\NLog.xml could not be found in your workspace, or you do not have permission to access it.
The item C:\Source2013\CyberCoders.com\LinkedInResumeGenerator\packages\NLog.4.1.0\lib\sl5\NLog.dll could not be found in your workspace, or you do not have permission to access it.
The item C:\Source2013\CyberCoders.com\LinkedInResumeGenerator\packages\NLog.4.1.0\lib\sl5\NLog.xml could not be found in your workspace, or you do not have permission to access it.
The item C:\Source2013\CyberCoders.com\LinkedInResumeGenerator\packages\NLog.4.1.0\NLog.4.1.0.nupkg could not be found in your workspace, or you do not have permission to access it.
C:\Source2013\CyberCoders.com\LinkedInResumeGenerator\license.txt: No file matches.
C:\Source2013\CyberCoders.com\LinkedInResumeGenerator\NUnit.2.6.4.nupkg: No file matches.
C:\Source2013\CyberCoders.com\LinkedInResumeGenerator\lib\nunit.framework.dll: No file matches.
C:\Source2013\CyberCoders.com\LinkedInResumeGenerator\lib: No file matches.
C:\Source2013\CyberCoders.com\LinkedInResumeGenerator\lib\nunit.framework.xml: No file matches.
GenerateResume.csproj has been automatically checked out for editing.
C:\Source2013\CyberCoders.com\LinkedInResumeGenerator\NLog.4.1.0.nupkg: No file matches.
The item C:\Source2013\CyberCoders.com\LinkedInResumeGenerator\packages\NLog.4.1.0\lib\net35\NLog.dll could not be found in your workspace, or you do not have permission to access it.
The item C:\Source2013\CyberCoders.com\LinkedInResumeGenerator\packages\NLog.4.1.0\lib\net35\NLog.xml could not be found in your workspace, or you do not have permission to access it.
The item C:\Source2013\CyberCoders.com\LinkedInResumeGenerator\packages\NLog.4.1.0\lib\net40\NLog.dll could not be found in your workspace, or you do not have permission to access it.
The item C:\Source2013\CyberCoders.com\LinkedInResumeGenerator\packages\NLog.4.1.0\lib\net40\NLog.xml could not be found in your workspace, or you do not have permission to access it.
The item C:\Source2013\CyberCoders.com\LinkedInResumeGenerator\packages\NLog.4.1.0\lib\net45\NLog.dll could not be found in your workspace, or you do not have permission to access it.
The item C:\Source2013\CyberCoders.com\LinkedInResumeGenerator\packages\NLog.4.1.0\lib\net45\NLog.xml could not be found in your workspace, or you do not have permission to access it.
The item C:\Source2013\CyberCoders.com\LinkedInResumeGenerator\packages\NLog.4.1.0\lib\sl4\NLog.dll could not be found in your workspace, or you do not have permission to access it.
The item C:\Source2013\CyberCoders.com\LinkedInResumeGenerator\packages\NLog.4.1.0\lib\sl4\NLog.xml could not be found in your workspace, or you do not have permission to access it.
The item C:\Source2013\CyberCoders.com\LinkedInResumeGenerator\packages\NLog.4.1.0\lib\sl5\NLog.dll could not be found in your workspace, or you do not have permission to access it.
The item C:\Source2013\CyberCoders.com\LinkedInResumeGenerator\packages\NLog.4.1.0\lib\sl5\NLog.xml could not be found in your workspace, or you do not have permission to access it.
The item C:\Source2013\CyberCoders.com\LinkedInResumeGenerator\packages\NLog.4.1.0\NLog.4.1.0.nupkg could not be found in your workspace, or you do not have permission to access it.

**Comment by thnk2wn** [comment]
I manually added the below to packages.config and then Visual Studio 2015 automatically restored / installed NLog for me:

<package id="NLog" version="4.1.0" targetFramework="net45" />

I don't know why Visual Studio wouldn't automatically add that into packages.config.

**Comment by 304NotModified** [comment]
Thanks for the report. 

I think this is: https://github.com/NuGet/Home/issues/1164

**Comment by thnk2wn** [comment]
Thanks
