### ISSUE TITLE
Archive file size issue on Sequence filename

### ISSUE THREAD

**Issue by arradhakrishnan** [NLog/NLog#888]
In web.config file I set the attributes as below:
archiveAboveSize="10240" archiveEvery="Day" archiveNumbering="Sequence" maxArchiveFiles="10" concurrentWrites="true" keepFileOpen="true"

The issue here is, before completing to 10 kb (10240), it keeps creating multiple files to the max of ten and writes to other files.  During this time there are archive files with less than 5 kb.  I would like to the second log to be created once the first file completed the size specified.

**Comment by 304NotModified** [comment]
Hi, can you give an example?

**Comment by arradhakrishnan** [comment]
Per web.config, archive will be done after 10 kb of each file right?  Before completing upto 10 kb in one file, it creates and writes to other archive file and so on.  I want this to be one after the other.

**Comment by 304NotModified** [comment]
> Per web.config, archive will be done after 10 kb of each file right?

Yes, **and** every day. So if you log one day for 5KB, you get a 5 KB log file.

>  Before completing upto 10 kb in one file, it creates and writes to other archive file and so on. I want this to be one after the other.

Please give a concrete example (file names etc), because I don't understand this.

**Comment by arradhakrishnan** [comment]
The web.config attributes are as below:
archiveAboveSize="10240" archiveNumbering="Sequence" maxArchiveFiles="10" concurrentWrites="true" keepFileOpen="true"

It should create max of ten archive files and the file names would be sequential, right?
Point 2:  Assume that there are no archives and it is going to start with first file by name 00001.
After completing the file 00001 to 10 kb, should create another archive by name 00002 with 10 kb.  In my case, its not happening this way.  It creates multiple archive files and writes randomnly without finishing the first file upto 10 kb, second upto 10 kb, and so on.  These files have only 3 kb or 4 kb.

Hope this will clarify your understanding.

**Comment by 304NotModified** [comment]
Sorry for the late reply.

Is it possible to create an sample application for this? Because I cannot reproduce it. I think it has something to do with multiple threads.

**Comment by 304NotModified** [comment]
Closing this due inactivity

**Comment by 304NotModified** [comment]
We cannot fix this without more info.  Feel free to respond if the problem is still there.
