### ISSUE TITLE
RichTextBoxTarget and MaxLines Attribute

### ISSUE THREAD

**Issue by seph1r0th** [NLog/NLog#891]
A RichTextBoxTarget is acuumulating lines although maxLines is set to a value greater zero. If i log a longer message and my RichTextBox control has set WordWrap=true it will wrap the lines. The current implementation of RichTextBoxTraget removes if necessary only one visible line, but not the additional lines which results from wrapping. This is the current implementation in RichTextBoxTarget:
```
if (MaxLines > 0)
{
	lineCount++;
	if (lineCount > MaxLines)
	{
	    rtbx.SelectionStart = 0;
	    rtbx.SelectionLength = rtbx.GetFirstCharIndexFromLine(1);
	    rtbx.SelectedRtf = "{\\rtf1\\ansi}";
	    lineCount--;
	}
}
```
This removes just one visible line from my RichTextBox even if my log message resulted in many lines.

The following code removes as many lines as there are too much (difference to MaxLines). I used it in my own target and it worked.
```
if (MaxLines > 0)
{
	if (rtbx.Lines.Where(f => !string.IsNullOrEmpty(f)).Any())
	{
		var visibleLineCount = rtbx.GetLineFromCharIndex(rtbx.Text.LastIndexOf(rtbx.Lines.Where(f => !string.IsNullOrEmpty(f)).Last().Last()));
		if (visibleLineCount - MaxLines > 0)
		{
			rtbx.SelectionStart = 0;
			rtbx.SelectionLength = rtbx.GetFirstCharIndexFromLine(visibleLineCount - MaxLines);
			rtbx.SelectedRtf = "{\\rtf1\\ansi}";
		}
	}
}
```

**Comment by 304NotModified** [comment]
Hi,

Thanks for the submit. I don't fully understand the sentence:
>  The current implementation of RichTextBoxTraget removes if necessary only one visible line, but not the additional lines which results from wrapping. 

Can you give an example?

About your code, it looks a bit inefficient (multiple `Lines.Where`). And why is the `rtbx.Text.LastIndexOf` needed?

**Comment by seph1r0th** [comment]
>Can you give an example?

Imagine you have a very long message to log and it doesn´t fit in one line of your RichTextBox. By default it results in more lines because WordWrap property of RichTextBox is true by default.
With maxLines=3 for example:
```
var msg = "This is my very long message. More and More and More and More and More and More and More and More and More and More and More and More Text.";
Logger.LogError(msg);
```
The output in the RichTextBox could be (depends on width of the control, FontSize etc..):

~~This is my very long message. More and~~
More and More and More and More and 
More and More and More and More and 
More and More and More Text.

After the next (same) message the output will be:

~~This is my very long message. More and~~
~~More and More and More and More and~~
More and More and More and More and 
More and More and More Text.
This is my very long message. More and
More and More and More and More and 
More and More and More and More and 
More and More and More Text.

This is how the lines get more and more in the RichTextBox. It happens with large messages when RichTextBox.WordWrap=true and also if RichTextBox.WordWrap=false but with CR/LF in a log message.

>About your code, it looks a bit inefficient (multiple Lines.Where)

You´re right. This is just an example for a workaround - i am sure there are ways to achieve the same result with better performance. You can also write with one where clause:
```
if (MaxLines > 0)
{
	var linesWithContent = rtbx.Lines.Where(f => !string.IsNullOrEmpty(f));
	if (linesWithContent.Any())
	{
		var visibleLineCount = rtbx.GetLineFromCharIndex(rtbx.Text.LastIndexOf(linesWithContent.Last().Last()));
		if (visibleLineCount - MaxLines > 0)
		{
			rtbx.SelectionStart = 0;
			rtbx.SelectionLength = rtbx.GetFirstCharIndexFromLine(visibleLineCount - MaxLines);
			rtbx.SelectedRtf = "{\\rtf1\\ansi}";
		}
	}
}
```

>And why is the rtbx.Text.LastIndexOf needed?

The aim is to get the amount of visible lines.
The function GetLineFromCharIndex() needs an index of a char. So i am looking for the absolute last char in the control. Therefor i use
```
linesWithContent.Last().Last()
```
If this char is the letter "T" for example i want to have the index of the last "T" in the RichTextBox and not an index of another instance of "T".

**Comment by 304NotModified** [comment]
Thanks, I fixed it with some small change of the suggested code.
