### ISSUE TITLE
EventPropertiesLayoutRenderer not marked with ThreadAgnostic

### ISSUE THREAD

**Issue by Aalano** [NLog/NLog#893]
Any reason this class is not marked with ThreadAgnostic?  
Looking at the class there doesn't seem to be any obvious reason for it to not be marked as such.

**Comment by 304NotModified** [comment]
I don't think so.  We will check your out.

**Comment by 304NotModified** [comment]
I checked this, and a lot of Layout renderers (e.g. GuidLayoutRenderer, EventPropertiesLayoutRenderer) are not marked as `ThreadAgnostic`.

I'm not sure what the benefit is of marking them `ThreadAgnostic`.

**Comment by Aalano** [comment]
ThreadAgnostic allows renderers to be used asynchronously.  If they are not marked with the ThreadAgnostic attribute then they are always processed synchronously.  According to the documentation at least

**Comment by 304NotModified** [comment]
Good reason. :) Thanks.

We will fix this soon.
