### ISSUE TITLE
Internal NLog log: path is required since 4.1

### ISSUE THREAD

**Issue by DataCrypt** [NLog/NLog#895]
In the previous version of NLog (v4.01), NLog had the ability to write it's internal log file to the "root" or "base" folder of where my EXE was running by simply giving the log file a name in the NLog.config file as such:

<nlog autoReload="true" throwExceptions="false" internalLogFile="nlog.log" internalLogLevel="Error"

Now with NLog 4.1, NLog immediately generates an error stating that the "Path" to the internalLogFile cannot be blank or whitespaces.  I'm forced to provide a path to this log file (such as "C:\Temp\nlog.log").  How may I have this revert back to saving it's log file to the base/root folder of where the NLog.dll and my EXE are located?

Thank you

**Comment by 304NotModified** [comment]
Thanks for reporting this bug. 

Can you try to work around this with `.\nlog.log`?

**Comment by DataCrypt** [comment]
Yes, using the .\ works.  Just that it wasn't needed before. I'll make sure to update my config files. Not sure if you want to fix this in a future build or leave it as-is so long as developers are aware of the change. Would be nice to either include a path or not (default to local folder). 
Thank you very much!
On Sep 4, 2015 2:51 PM, Julian Verdurmen <notifications@github.com> wrote:Thanks for reporting this bug. 

Can you try to work around this with .\nlog.log?

**Comment by 304NotModified** [comment]
We will fix this, but glad the work around worked :) 

Thanks for testing!

**Comment by 304NotModified** [comment]
Small fixed needed here. It should be unit tested.

**Comment by 304NotModified** [comment]
Bug probably introduced by #818

**Comment by kevindaub** [comment]
See #898

**Comment by 304NotModified** [comment]
Merged so closing this
