### ISSUE TITLE
[Question] Getting user name from NLog to xml

### ISSUE THREAD

**Issue by wdhodges** [NLog/NLog#897]
So I have been searching and searching on a way to get the current user name (environment.username) into a xml format. Currently I'm using this program called Log Viewer from codeplex that allows me to view a xml file. It has a spot for user name (see image below). 
![image](https://cloud.githubusercontent.com/assets/11448029/9703155/fb5372ac-5447-11e5-9ac4-7bd956cee8c4.png)

My current code for this to work is this: 

```xml
<target name ="xmlFileLog" 
  xsi:type="File" 
  fileName="...\XML Log\tracelog.xml"   
  layout="${log4jxmlevent:includeSourceInfo=true:
            includeCallSite=true:
            includeMDC=true:
            appInfo=true:
            includeNDC=true:
            includeNLogData=true:
            includeIdentity=true} ${windows-identity:userName=true:domain=true}"

```

How can I add the ability to get the user name from the environment.username into the that field?

**Comment by 304NotModified** [comment]
Too bad that isn't directly supported in the Log4JXmlEventLayout. But you can work around it by setting the username in the MDC/NDC or event properties. (from C#)

**Comment by wdhodges** [comment]
@304NotModified Could I potentially get this from using the xmlEncode=true layout renderer? I've been searching and searching on how to actually that and found something in the Nlog archives but it doesn't work. Any advice?

**Comment by wdhodges** [comment]
Or do you have any advice on how to set the ndc/mdc in C#? I'm self teaching c# so I haven't learned a lot of it lol just enough to make a WPF quick link application.

**Comment by 304NotModified** [comment]
Do you need XML or Log4J complaint XML?

**Comment by wdhodges** [comment]
XML please sir. And do you have an idea on how to use c# to set mdc/ndc properties?

**Comment by 304NotModified** [comment]
For regular xml you could check https://github.com/loresoft/NLog.Xml/blob/master/README.md

With that library there is no need for ndc/mdc

**Comment by 304NotModified** [comment]
If you still like to use the MDC/NDC, see docs how to use:

https://github.com/NLog/NLog/wiki/Mdc-Layout-Renderer#simple-properties

**Comment by wdhodges** [comment]
I'm checking out the NLog.Xml. Do I use this in extension to NLog.Config?

**Comment by kevindaub** [comment]
It has a dependency on NLog, so it just provides additional functionality.

**Comment by wdhodges** [comment]
This is what I have, I don't have the xml template and I have installed and made sure it's referenced.

![image](https://cloud.githubusercontent.com/assets/11448029/9777693/7e6cce0a-5735-11e5-9ee5-6f70b84e73e6.png)

I feel like I'm doing something wrong, but I'm not sure what I'm doing wrong lol

**Comment by kevindaub** [comment]
I think NLog only shows the items that are in the NLog Schema intellisense.  So it won't appear there, but since it's outside of NLog, it should still work.

https://www.nuget.org/packages/NLog.Schema/

**Comment by wdhodges** [comment]
![image](https://cloud.githubusercontent.com/assets/11448029/9777929/eb84c0e0-5737-11e5-849d-b03930c0af6f.png)

So I went ahead and attempted to type it out, but still got this error. I do have the NLog.Schema installed as well. Still not sure where I'm going wrong

**Comment by kevindaub** [comment]
Have you tried to run it?  That's only a XSD schema error.  The schema from
NLog doesn't know about external targets.

Sincerely,
Kevin Daub

Email: daub815@gmail.com
Mobile: 717.572.4880

**Comment by wdhodges** [comment]
It worked, thank you for your help!

**Comment by 304NotModified** [comment]
No problem! If you have some further questions, just let us know!
