### ISSUE TITLE
Warn NLog.LayoutRenderers.RegistryLayoutRenderer has no default property

### ISSUE THREAD

**Issue by Niklas-Peter** [NLog/NLog#903]
> "defaultValue - Value to be output when the specified registry key or value is not found."

My key and value do certainly not exist. However the defaultValue is obviously not used. Is it a bug or did I get it wrong?
Message in nlog-internal.log:

    Warn NLog.LayoutRenderers.RegistryLayoutRenderer has no default property
minimal NLog.config
```
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      internalLogLevel="Warn" internalLogFile="c:\temp\nlog-internal.log" >

  <targets>
    <target xsi:type="File" name="f" fileName="${registry:value=NOT_EXISTENT:key=HKLM/NOT_EXISTENT:defaultValue=C:/temp}/a.log"
            layout="${message}" />
  </targets>

  <rules>
    <logger name="*" writeTo="f" />
  </rules>
</nlog>
```

**Comment by 304NotModified** [comment]
Hi,

You need to escape the `:` => `\:`, because that's the separator between the keys.

**Comment by Niklas-Peter** [comment]
Thanks, maybe that should be explicitly mentioned anywhere in the Wiki, although it actually is clear.

**Comment by 304NotModified** [comment]
Agree, but I don't now where is a good place. Where do you think it would be nice? 

PS: you can add it self to the wiki if you like :)

**Comment by 304NotModified** [comment]
I'm closing this, but if you have some further questions, just let us know!

**Comment by Niklas-Peter** [comment]
However `:defaultValue=C\:\temp` throws an exception (illegal character in path), but `:defaultValue=C\:/temp` is working, just as information.
