### ISSUE TITLE
Please Review "Configuration Syntax" Descriptor on Database Target

### ISSUE THREAD

**Issue by jerrywiltse** [NLog/NLog#907]
https://github.com/nlog/NLog/wiki/Database-target

This is my first github contribution, so please excuse if I am incorrect, however this looks like someone did a find and replace resulting in the word "Layout" being inserted in a bunch of incorrect places on this page.  

For example, Line 4:              dbUserName="Layout"

Hope that helps. 

Edit: I just checked history, and there have been several edits, none of which changed these fields so they must be correct and I probably just need to understand better. Closing issue.

**Comment by 304NotModified** [comment]
Hi,

Just to respond. 

- I did not see any changes you have made to the link? (the wiki has also version control).
- The difference between a `string` and `layout`: a `layout` can contain layout renders, like `${message}` and those layout renders will be replaced when rendering. In the (xml) configuration it's just a `string`.

**Comment by 304NotModified** [comment]
If you need some help, just let us know :)
