### ISSUE TITLE
RichTextboxTarget fails with NLog 4.1.1

### ISSUE THREAD

**Issue by siemandelc** [NLog/NLog#908]
NLog.Windows.Forms 2.1.0.0 fails with NLog 4.1.1

I get a TypeInitializationException, and a bunch of warnings such as "Reference to type 'NLog.Targets.RichTextboxRowColoringRule' claims it's defined in 'PATH', but it could not be found.

**Comment by 304NotModified** [comment]
I will check this out now.

**Comment by siemandelc** [comment]
It was working on the previous version 4.1.0, let me know if you need more information.

**Comment by 304NotModified** [comment]
I see https://github.com/NLog/NLog/pull/892 broke it. I will fix this in NLog.Windows.Forms

**Comment by 304NotModified** [comment]
This has been fixed in [2.1.1](https://www.nuget.org/packages/NLog.Windows.Forms/2.1.1)

Thanks for the report!

**Comment by siemandelc** [comment]
Thank you for the fast fix!
