### ISSUE TITLE
Log NLog version to internal log. 

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#913]
Log Assembly version and file version to internal log (info) . also of loaded assemblies (NLog.web etc)

**Comment by bhaeussermann** [comment]
What are these loaded assemblies and NLog.web?

**Comment by 304NotModified** [comment]
Those assemblies are installed by the user (eg nuget package) 

When we do the auto load, we like to log the versions.

**Comment by 304NotModified** [comment]
No auto loading is done here: https://github.com/NLog/NLog/blob/eebb37d20904dbf70a919cd6fbc4cdcae7f488d7/src/NLog/Config/ConfigurationItemFactory.cs
