### ISSUE TITLE
archiveFileName {#} placeholder in nested in another layout?

### ISSUE THREAD

**Issue by Niklas-Peter** [NLog/NLog#914]
*Case 1 (Working, but ugly)*

    ${when:when=1 == 1:inner=${RegistryLogDirectory}/Log_${literal:text={#\}}.log}

*Case 2 (Not working, this is a bug)*
According to https://github.com/nlog/NLog/wiki/Configuration-file#content-escaping it should IMHO work, but it does not:

    ${when:when=1 == 1:inner=${RegistryLogDirectory}/Log_{#\}.log}

**Comment by 304NotModified** [comment]
Do you mean:

- "correct" => working
- "wrong" => not working, it's a bug

?

**Comment by 304NotModified** [comment]
related #https://github.com/NLog/NLog/issues/444

**Comment by Niklas-Peter** [comment]
Yes, according to the link case 2 is a bug.

**Comment by 304NotModified** [comment]
OK thanks I updated your post. Technicality this is the same issue as #444, as `{#}` isn't a layout renderer, but OK, it's really annoying it's not working as expected and I needs to be fixed.  We will add this to our unit tests.

Thanks for reporting!
