### ISSUE TITLE
Product released with NLog 4.1.0 has installer issues after upgrading to NLog 4.1.1

### ISSUE THREAD

**Issue by jonreis** [NLog/NLog#919]
Here are the versions:

NLog 4.1.0: Assembly Version: 4.1.0, File version: 4.1.0
NLog 4.1.1: Assembly Version: 4.0.0, File version: 4.0.0

For the installer to work properly, the File Version must be set to 4.1.1. This is the version that the installer looks at when it determines whether a file in the program's directory needs to be updated or not. 

The File version should equal the product version.

**Comment by 304NotModified** [comment]
Thanks for the report. Your are right.  

The file version is empty in our build script and therefore it's copying the assembly version. The assembly version should be 4.0.0,  but the file version not. 

Some excellent info:
http://stackoverflow.com/a/65062

I have to find out how to fix out build script (it's the `nlog.proj` in github)

**Comment by 304NotModified** [comment]
This has been fixed in 4.1.2, which just has been released. A confirm would be great :)

**Comment by jonreis** [comment]
Yes, I confirm this has been fixed. Than you very much for the quick turn-around on this!

**Comment by jonreis** [comment]
Installer functioning properly with the NLog 4.1.2 also.

**Comment by 304NotModified** [comment]
Thanks for the confirmation! :)
