### ISSUE TITLE
NLog 4.1.2 AssemblyVersion is 4.0.0.0 whereas NLog 4.1.0 AssemblyVersion is 4.1.0.0

### ISSUE THREAD

**Issue by DannyVarod** [NLog/NLog#921]
When upgrading from NLog 4.1.0 to 4.1.2 specific version assembly bindings e.g. via Common.Logging.NLog41 break since AssemblyVersion goes down from 4.1.0.0 to 4.0.0.0.

**Comment by 304NotModified** [comment]
Yes,  sorry about that. Bumping the assembly version in 4.1 went wrong with other libraries (due to strong naming) .  See https://github.com/NLog/NLog/issues/918.

**Comment by 304NotModified** [comment]
You can use common.logging.Nlog40?

**Comment by DannyVarod** [comment]
Yes that is what I did, however, anyone thats the 41 version or already has a direct strong version binding elsewhere, has to define an assembly rebinding of 0.0.0.0-**4.1**.0.0 to **4.0**.0.0, which breaks when you update any NuGet (reverted to 0.0.0.0-**4.0**.0.0 to **4.0**.0.0).
If this was intentional, then the Common.Logging project need to be notified that the Common.Logging.NLog41 NuGet needs to be updated to change the default binding.

**Comment by 304NotModified** [comment]
I'm closing this, I will keep an eye on the common logging issue
