### ISSUE TITLE
NLog does not like some config sections

### ISSUE THREAD

**Issue by seiyria** [NLog/NLog#924]
My config file looks like this:

```
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
    <startup> 
        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5" />
    </startup>
	<configSections>
		<section name="mongoSettings" type="System.Configuration.NameValueSectionHandler" />
	</configSections>
	<appSettings>
		<add key="AWSAccessKey" value=""/><!-- Amazon Credentials -->
		<add key="AWSSecretKey" value=""/><!-- Amazon Credentials -->
	</appSettings>
	<mongoSettings configSource="mongo.config" />
</configuration>
```

Seemingly because of that, I get this error: 

![](http://i.imgur.com/oukFtbW.png)

This is incredibly frustrating as it took me about 7 hours to track down why this application was suddenly refusing to start up. All because I have config sections that NLog does not seem to like, but are perfectly valid.

**Comment by 304NotModified** [comment]
In which file is nlog configurated? Not in this one? 

PS: I have removed your credentials from the config.

**Comment by seiyria** [comment]
Whoops, thanks.

NLog is not configured here, it is configured entirely in code, but yet it searches for a config file. I'm more surprised that it's throwing errors for sections in a config file that it probably shouldn't care about.

**Comment by 304NotModified** [comment]
Well I'm not sure if nlog is throwing the error (it's exception from system.configuration). We have to check that.

**Comment by seiyria** [comment]
It happens on this call:

`            var fileTarget                    = new NLog.Targets.FileTarget ();`

So I have to assume that's NLog.

**Comment by 304NotModified** [comment]
Doesn't seem so:

https://github.com/NLog/NLog/search?utf8=✓&q=ConfigurationErrorsException&type=Code

**Comment by 304NotModified** [comment]
Well we are reading the config,  and probably as first progress,  because we have to search for possible configuration data.

**Comment by seiyria** [comment]
Yeah, and I see that, but I'm not sure why that would crash the program. Especially since the config sections in my config file are 100% valid (according to stackoverflow).

**Comment by Oipo** [comment]
From https://msdn.microsoft.com/en-us/library/aa903350%28v=vs.71%29.aspx

> Remarks
> If this element is in a configuration file, it must be the first child element of the <configuration> element.

**Comment by seiyria** [comment]
Welp, that would very likely explain my issue. As for why NLog seemed to be triggering it - that was the first function call in the app. 

¯\_(ツ)_/¯ .NET

**Comment by 304NotModified** [comment]
Thanks @oipo :)
