### ISSUE TITLE
Assembly versioning has regressed in 4.1.2

### ISSUE THREAD

**Issue by CoolDadTx** [NLog/NLog#928]
Using NLog 4.1.0 the assembly version was 4.1.0.0.  In 4.1.2 the assembly version has reverted to 4.0.0.0.  This causes runtime binding failures when you have different projects referencing 4.1.0 and 4.1.2. It should just work but because the assembly version regressed back the assembly binding doesn't work properly.

**Comment by 304NotModified** [comment]
Yes we did that on purpose. See #921 and latest news post. 

It's only trouble if you upgrade from 4.1.0. 

We don't think there is an easier way without breaking other libs build on 4.0 :(

**Comment by 304NotModified** [comment]
PS:

If the assembly version of 4.1.2 was 4.1.2.0, you had the same problems. The only solution is to keep the assembly version the same in NLog.

**Comment by fletchsod-developer** [comment]
How would this work in web.config with NLog 4.1.2?

  <common>
    <logging>
      <factoryAdapter type="Common.Logging.NLog.NLogLoggerFactoryAdapter, Common.Logging.NLog40">
        <arg key="configType" value="INLINE" />
      </factoryAdapter>
    </logging>
  </common>

and
      <dependentAssembly>
        <assemblyIdentity name="NLog" publicKeyToken="5120e14c03d0593c" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.0.0" newVersion="4.0.0.0" />
      </dependentAssembly>

**Comment by fletchsod-developer** [comment]
How would this work in web.config for NLog 4.1.2?

     <common>
       <logging>
         <factoryAdapter type="Common.Logging.NLog.NLogLoggerFactoryAdapter, Common.Logging.NLog40">
           <arg key="configType" value="INLINE" />
         </factoryAdapter>
       </logging>
     </common>

and

     <runtime>
       <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
         <dependentAssembly>
           <assemblyIdentity name="Common.Logging" publicKeyToken="af08829b84f0328e" culture="neutral" />
           <bindingRedirect oldVersion="0.0.0.0-3.3.0.0" newVersion="3.3.0.0" />
         </dependentAssembly>
         <dependentAssembly>
           <assemblyIdentity name="NLog" publicKeyToken="5120e14c03d0593c" culture="neutral" />
           <bindingRedirect oldVersion="0.0.0.0-4.0.0.0" newVersion="4.0.0.0" />
         </dependentAssembly>
     </runtime>

**Comment by 304NotModified** [comment]
Just change old version 4.1.0.0 to 4.0.0.0

So

```xml
<runtime>
   <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
     <dependentAssembly>
       <assemblyIdentity name="Common.Logging" publicKeyToken="af08829b84f0328e" culture="neutral" />
       <bindingRedirect oldVersion="0.0.0.0-3.3.0.0" newVersion="3.3.0.0" />
     </dependentAssembly>
     <dependentAssembly>
       <assemblyIdentity name="NLog" publicKeyToken="5120e14c03d0593c" culture="neutral" />
       <bindingRedirect oldVersion="0.0.0.0-4.1.0.0" newVersion="4.0.0.0" />
     </dependentAssembly>
 </runtime>
```

That's it!

**Comment by 304NotModified** [comment]
Closing this dup
