### ISSUE TITLE
Archive compression and Internal logging

### ISSUE THREAD

**Issue by MrBillium** [NLog/NLog#929]
I have a .Net 4.5.1 App running Nlog 4.1.2.0 and it performs "DateAndSequence" logging to archive.
This works fine.
I just tried to enable ArchiveFileCompression butnew archive files were unchanged ( still .txt files).
Next I turned on Nlog internal logging ( Trace) and to my surprise I see absolutely no mention at all of any logging to archive - not even about  the still working creation of the .txt files. In the Internal log I do see where Nlog parses the instructions to log to archive and to enable Archive File Compression ( no errors) but after that I can see it logs writing to the application logs but nothing about archiving activities that did happen.

So, any ideas why File compression is not happening and why the internal log is not logging anything at all about Archive file creation?
Thanks
Bill

**Comment by 304NotModified** [comment]
Have you tried naming the archive file a `.Zip` in the NLog config?

**Comment by MrBillium** [comment]
Thanks, that got it. 
I think that enabling compression should just override the archive extension  since it is not that obvious ( for me anyway) .
The other issue that none of this was logged in internal log remains.
Thanks
Bill

**Comment by 304NotModified** [comment]
Yes you are not the only one I see. See #922

**Comment by 304NotModified** [comment]
Thanks for the feedback.  I agree the with your comments and so we created some new tickets for that. I will close this one because your issue has been solved.  If you have further questions, just let us know!
