### ISSUE TITLE
ArchiveFileCompression: auto add `.zip` to filename 

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#932]
If not already there. 

See #922 and #929 

This feature only be implemented if `.zip` is the only valid extension (check first)

**Comment by bhaeussermann** [comment]
If `archiveFileName` is not specified, we currently archive to `[logFileName].{#}.[logFileExtension]`  
To my understanding this should be changed to `[logFileName].{#}.[logFileExtension].zip` if `[logFileExtension] != "zip"`

I would suggest that we add the `.zip` extension only when `archiveFileName` is *not* specified. Specifying `archiveFileName` overrides the "default" (as defined above) and should allow to save the archive with a different extension, eg. `serverlog.{#}.logarchive`.

So you agree?

**Comment by 304NotModified** [comment]
Thanks for the proposal. I have to think about this.With your proposal we can't get `[logFileName].{#}.zip`? Also you can still get a .txt file, which is just a .zip and that gives confusion. 

Another option is to:

- always use `.zip`
- add archiveExtension, with default `.zip`

**Comment by bhaeussermann** [comment]
Yes, we can replace the extension by default to go with `[logFileName].{#}.zip`.

However, when specifying `archiveFileName` explicitly, I would expect the archive file to have that name, and not the name with `.zip` added to it, but maybe it's just me.

An `archiveExtension` property would seem arbitrary, because we don't specify file extensions anywhere else in the configuration. How about an `addZipExtensionForCompressedArchive` property that we default to true?

**Comment by 304NotModified** [comment]
I will double check the docs and code this weekend for this.

**Comment by bhaeussermann** [comment]
Is there any feedback on this?  
We have the following suggestions so far: 

- Always add `.zip`
- Add `.zip` only when `archiveFileName` is not set
- Add `archiveExtension` property with default `.zip`.
- Add `addZipExtensionForCompressedArchive` property with default `true`

I would prefer the last option. That way if the user does not want the archive to end with `.zip` for some reason, he/she can simply set this value to `false`.

**Comment by 304NotModified** [comment]
Thanks for the reminder. With GitHub I cannot set messages as unread, so sometimes losing track which needs a response.

I will try to give feedback on this tonight.

**Comment by 304NotModified** [comment]
>  Add `.zip` only when `archiveFileName` is not set

I think this also is the best option :) 

it's inside `GetFileNamePattern` isn't?

**Comment by bhaeussermann** [comment]
Yes.

**Comment by 304NotModified** [comment]
:+1:
