### ISSUE TITLE
How to programmatically show hide RichTextBox target in NLog?

### ISSUE THREAD

**Issue by acidos** [NLog/NLog#935]
I am creating targets/rules programmatically:
```C#
                var config = new LoggingConfiguration();
                var fileTarget = new FileTarget();
                fileTarget.Layout = @"${longdate} - ${message}";
                fileTarget.FileName = @"log.txt";
                fileTarget.KeepFileOpen = false;
                config.AddTarget("file", fileTarget);

                if (Properties.Settings.Default.DebugWindow)
                {
                    var rtTarget = new RichTextBoxTarget();
                    rtTarget.Layout = @"${longdate} - ${message}";
                    config.AddTarget("wnd", rtTarget);

                    var rule2 = new LoggingRule("*", LogLevel.Debug, rtTarget);
                    config.LoggingRules.Add(rule2);
                }

                var rule1 = new LoggingRule("*", LogLevel.Debug, fileTarget);
                config.LoggingRules.Add(rule1);

                LogManager.Configuration = config;
```

Code above works fine, during app initialization. Second target, which is RichTextBox target, is optional and bound to checkbox in app. When ticked I want to add target AND show the built-in RichTextBox window. When untick, I remove target and I want to hide it. If I remove target `config.RemoveTarget("wnd")` the form doesn't disappear. Also when I add target/rule on tick event, the form doesn't appear. What is the procedure on adding/removing RichTextBox target, so the form will appear/disappear?

**Comment by 304NotModified** [comment]
I think you have to create your own `Form` and `RichTextBox`, and hide it with code.

This isn't what NLog can.

**Comment by 304NotModified** [comment]
Has you question being answered?

**Comment by acidos** [comment]
Yes, thank you.
