### ISSUE TITLE
Config File Require Extensions node at specific postion

### ISSUE THREAD

**Issue by pcKris** [NLog/NLog#936]
when I place the `<extensions>` node after rules and targets the custom render I am trying to include is not found.

if the node is above the targets and rules then my render is found

**Comment by 304NotModified** [comment]
Hi, 

This bug had been fixed in 4.1.0

See https://github.com/NLog/NLog/pull/814

**Comment by 304NotModified** [comment]
Thanks for the report, but because this has been fixed already, I will close this.
