### ISSUE TITLE
Add annotations for custom string formatting methods

### ISSUE THREAD

**Issue by StevenLiekens** [NLog/NLog#941]
Logger methods that format strings should be annotated as described in: https://www.jetbrains.com/resharper/help/Code_Analysis__String_Formatting_Methods.html

Example

```C#
[StringFormatMethod("message")]
void Error(Exception exception, [Localizable(false)] string message, params object[] args);
```

**Comment by 304NotModified** [comment]
Thanks for this report!

We had some difficulties with Resharper annotations before (see https://github.com/NLog/NLog/issues/452). I have to check how this is related.
