### ISSUE TITLE
Support Universal App Platform (UAP) / Universal Windows Platform (UWP) apps

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#943]
Support for universal apps on Windows 10. 

note: it's called UAP10 in the nuspec (for Nuget). See [Announcing NuGet 3.1 with Support for Universal Windows Platform](http://blog.nuget.org/20150729/Introducing-nuget-uwp.html).

**Comment by 304NotModified** [comment]
I'm working on this, see https://github.com/304NotModified/NLog/tree/UAP10

**Comment by 304NotModified** [comment]
useful info:
- https://msdn.microsoft.com/en-us/library/mt185490.aspx

**Comment by 304NotModified** [comment]
90% done

**Comment by 304NotModified** [comment]
@phenixdotnet

any idea how to get the MDC working in UWP?

**Comment by 304NotModified** [comment]
@phenixdotnet I will merge first with master, the rename later is easy to do.

**Comment by phenixdotnet** [comment]
Great ! Good luck ^^

**Comment by 304NotModified** [comment]
Thanks!

**Comment by 304NotModified** [comment]
@phenixdotnet almost done.  Broke something with extention loading. Will fix that in a few hours. (dinner time now)

**Comment by 304NotModified** [comment]
See https://github.com/NLog/NLog/pull/1077

Need some small changes before merge. 

I will merge it In a separate branch at nlog, so the NLog team can easily help :)

**Comment by 304NotModified** [comment]
Fixes 
https://github.com/NLog/NLog/issues/943

- [x] Let's see what ApPVeyor thinks
- [x] Review all the changes.

todo
---

- [x] ConfigurationItemFactory: fix xml doc (merge issue)
- [x] Enumhelper: use isEnum method ext
- [x] rename ext to get....
- [x] move classes to separate files.
- [x] LogFactory: fix xml doc (multiple)  (merge issue)
- [x] LogManager: fix xml doc  (merge issue)
- [x] ThreadAgnosticTests: fix comments  (merge issue)
- [x] ConditionParserTests unneeded changes
- [ ] AsyncHelpers: fix run of async
- [ ] UAPP10Helpers.cs: add docs
- [ ] LoggerImpl stacktrace
- [ ] MDC for UAP 
- [ ] RetryingTargetWrapper (thread.sleep)
- [ ] fix SimpleLayoutParserTests (no NDC)
- [ ] ReflectionHelpers add xml docs

changes
---
- getCurrentClassLogger => name of filename instead of class

not working
---
- stacktrace
- MDC, MDLC, NDC

**Comment by 304NotModified** [comment]
Currently not supported:

* Config from appsettings
* MDC, MDLC, NDC
* LayoutRenderer
 * AppDomain
 * AspApplicationValue
 * AspRequestValue
 * AspSessionValue
 * AssemblyVersion
 * BaseDir
 * Identity
 * Log4JXmlEvent
 * MachineName
 * Mdc
 * Ndc
 * NLogDir
 * PerformanceCounter
 * ProcessId
 * ProcessInfo
 * ProcessName
 * QueryPerformanceCounter
 * Registry
 * SpecialFolder
 * ThreadId
 * ThreadName
 * TraceActivityId
 * WindowsIdentity

Targets:
   * Chainsaw
   * ColoredConsole
   * Console
   * Database
   * Debugger
   * EventLog
   * LogReceiverWebService
   * Mail
   * Network
   * NLogViewer
   * OutputDebugString
   * PerformanceCounter
   * Trace
   * ImpersonatingTargetWrapper
   * RetryingTargetWrapper* (no RetryDelayMilliseconds)

**Comment by 304NotModified** [comment]
Waiting on coreclr.

**Comment by Houzvicka** [comment]
I really looking for UWP version, Good luck!

**Comment by 304NotModified** [comment]
This is supported in the beta hence closing this issue

**Comment by davidkaya** [comment]
@304NotModified What is currently the state of UWP support? Is it supported in the beta?

**Comment by 304NotModified** [comment]
beta as we can't get the unit tests running. Also the limited experience isn't helping.

If you could help us with that, that would be nice!

**Comment by davidkaya** [comment]
I would love to, but we can't even get the application running. When I add the reference to NLog, application crashes during startup on some Unhandled exception (from Windows.UI.Xaml.dll), it says that "An application-internal exception has occurred". I tried adding directly .netstandard1.3, .netstandard1.5 and even just the nuget pkg. I do not know whether we have some missconfiguration in the project or what is wrong.

**Comment by 304NotModified** [comment]
Could you try with 4.3.9?

AFAIK netstandard + xamarin is unstable

**Comment by pvanroos** [comment]
Any update on this?  is NLog going to support some version of .NET standard?

**Comment by 304NotModified** [comment]
We support now netstandard 1.3 (NLog 5 beta) end netstandard 2 with NLog 5 rtm

**Comment by snakefoot** [comment]
UWP support will be fixed with #2055

**Comment by snakefoot** [comment]
Resolved with the release of NLog 5.0 BETA7
