### ISSUE TITLE
Proposal: Detach NLog Logging Functionality from Configuration

### ISSUE THREAD

**Issue by ie-zero** [NLog/NLog#951]
We can attempt to detach the logging functionality from the XML configuration. This will allow to minimise the footprint of the library, in case the library is called through code, and it allow creation of alternative configuration methods such as JSON.

Obviously this is a seriously breaking change.

**Comment by 304NotModified** [comment]
Well, we can start with splitting the stuff into different projects, and in a later phase into different (nuget) packages. E.g. The get the packages "NLog" ,"NLog.config.xml" and "NLog.core", If we keep  "Nlog.config.xml" and "NLog.core" as a dependency of "NLog" (for a while), it is backwards compatible. People can choose to just install "NLog.core".

What do you think?

**Comment by ie-zero** [comment]
It looks look a plan.

May I suggest though to isolate configuration into self-contained classes with well defined interface before we move it into a separate project.

This work can start now as it will not affect the users in any way.

**Comment by 304NotModified** [comment]
> May I suggest though to isolate configuration into self-contained classes with well defined interface before we move it into a separate project.

Good idea! 

Also, I think it's a good idea to separate the config and the logging :)

**Comment by ie-zero** [comment]
After a quick look, I believe most code which needs decoupling sits in `LogFactory` class. 

It seems to me the `LogFactory` class is actually a `XmlLogFactory` which is called as default by `LogManager`.

**Comment by 304NotModified** [comment]
I think you mean `LoggingConfiguration` and `XmlLoggingConfiguration`?

Any way, was thinking about this, and moving from 1 dll to 2, could be a breaking change. So this should be NLog 5.

**Comment by ie-zero** [comment]
You are absolutely right on both @304NotModified.

**Comment by 304NotModified** [comment]
Well but maybe we can add the interfaces as proposed in the topic start?

**Comment by 304NotModified** [comment]
This is done already
