### ISSUE TITLE
Add more Layout render helpers

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#953]
In the renderers the following code snippits are used
## 1. Data conversions

Sometimes with try-catch, sometimes with logging (to internallog)

``` c#
Convert.ToInt32(this.EventId.Render(logEvent), CultureInfo.InvariantCulture);
Convert.ToInt16(this.Category.Render(logEvent), CultureInfo.InvariantCulture);

 var renderedPriority = this.Priority.Render(lastEvent);
                try
                {

                    msg.Priority = (MailPriority)Enum.Parse(typeof(MailPriority), renderedPriority, true);
                }
                catch
                {
                    InternalLogger.Warn("Could not convert '{0}' to MailPriority, valid values are Low, Normal and High. Using normal priority as fallback.");
                    msg.Priority = MailPriority.Normal;
                }
```

also
## 2. Checks for empty

``` c#
if (!string.IsNullOrEmpty(layout)) {
   layout.render()
} else {
...
}
//and
if (layout != null) {
   layout.render()
} else {
...
}
```
# Proposal
1. Add helpers for conversion, including logging and default
2. Add "RenderSafe" helper, or other "fluent" helper.

**Comment by Page-Not-Found** [comment]
Is some one working on this already?

**Comment by 304NotModified** [comment]
nope!

**Comment by Page-Not-Found** [comment]
I will start working on this

**Comment by 304NotModified** [comment]
:+1:

**Comment by Page-Not-Found** [comment]
@304NotModified would you mind adding some ore information. When I search for the keywords I feel most of the are good.

**Comment by 304NotModified** [comment]
You have to search for `.Render()`.  For me it the same work, but I'm more busy with bugs and xamarin support this week. 

I think there are maybe 20 cases in the whole code,  but we need more with non-string layouts in the future.

**Comment by 304NotModified** [comment]
Nothing wrong if this isn't a big refactoring :) 

I'm curious how you would create the helpers.

**Comment by Page-Not-Found** [comment]
I am not able to come up with helpers other than the SafeRender as a Extension method.

**Comment by 304NotModified** [comment]
not planned for now
