### ISSUE TITLE
Logger in static class leads to initialization exception

### ISSUE THREAD

**Issue by migig** [NLog/NLog#960]
Stick this into LINQPad as a test case:

    public static class Foo {

      private static readonly NLog.Logger Logger = NLog.LogManager.GetLogger(typeof(Foo).FullName, typeof(Foo));

      static Foo() { }

      public static void dummyToInvokeInitializers() {}

    }

    void Main() {
      Foo.dummyToInvokeInitializers();
    }

This is the sort of setup you typically use with NLog, except here the class is `static`. Because of that a `TypeInitializationException` exception is thrown, with the message:

    The type initializer for 'Foo' threw an exception.

And the inner exception's message:

    Cannot access the constructor of type: Foo. Is the required permission granted?

So I tried to put in a static constructor. But that doesn't help.

I don't want to use magic strings, what are my options?

**Comment by 304NotModified** [comment]
Well `NLog.LogManager.GetLogger(typeof(Foo).FullName` should work?

**Comment by migig** [comment]
@304NotModified  Yes for some reason omitting the type will get it to work. But we use a fancy subclass which I'm worried will try use that missing type later on. So I can't go down that route :sob:

**Comment by migig** [comment]
@304NotModified Do you know why this happens? If I have a basic idea of what's happening and where to look I can try fix it myself and submit a PR.

**Comment by 304NotModified** [comment]
When I check the code, I see:

```c#
        /// <summary>
        /// Gets the specified named logger.
        /// </summary>
        /// <param name="name">Name of the logger.</param>
        /// <param name="loggerType">The logger class. The class must inherit from <see cref="Logger" />.</param>
        /// <returns>The logger reference. Multiple calls to <c>GetLogger</c> with the same argument aren't guaranteed to return the same logger reference.</returns>
        [CLSCompliant(false)]
        public static Logger GetLogger(string name, Type loggerType)
```

I think `Foo` doesn't inherit  from `Logger` ;)

NLog tries to create an instance of `loggerType`, but I cannot handle `static` classes, and with a good reason ;)

**Comment by migig** [comment]
Weird, I thought I could use any type. Been doing it that way for AGES. Now it blows up because of the static class which can't be instantiated. HAHAHA you learn something new every day. :smile: 

Why does it even need that `loggerType`. It doesn't even use it?

**Comment by 304NotModified** [comment]
I does use it, it creates a new LoggerType, so if you have:

```c#
class Logger2 : Logger
{

}
```

Then you can create an instance of `Logger2` with `LogManager` / `LogFactory`

**Comment by migig** [comment]
@304NotModified Ah okay, I never create logger that way, so I'm not worried then. So your idea to use the other overload

    NLog.LogManager.GetLogger(typeof(Foo).FullName)

...works.

So actually this is by design, it's not a bug! :smiley:

**Comment by 304NotModified** [comment]
NP! :beer:

**Comment by 304NotModified** [comment]
We will improve the docs and error message, as I was also not clear to me in the first place ;)

**Comment by shev72** [comment]
I also ran into this issue,  and I understand the solution.  However it is very difficult to debug and I would really recommend that in the exception message  the above workaround is mentioned ie "try NLog.LogManager.GetLogger(typeof(Foo).FullName) for static instantiated classes"

**Comment by 304NotModified** [comment]
yes it's hard to debug and we can't show a better exception message :( 

see http://stackoverflow.com/q/34994470/201303
