### ISSUE TITLE
Introduce maxLogLevel for NLogTraceListener

### ISSUE THREAD

**Issue by tiljanssen** [NLog/NLog#978]
I have a library for which I use NLogTraceListener that issues certain messages at an inappropriate "Warn" level. I would like to limit the logLevel of this library to "Info" without changing the level of "debug" and "trace" messages (which is what forceLogLevel would do).

maxLogLevel would be inferior to forceLogLevel.

Will anyone object to yet another custom attribute?

**Comment by 304NotModified** [comment]
You can't use the `maxLogLevel` attribute in the calling code?

**Comment by tiljanssen** [comment]
I'm not in control of the library source (if I was I would make it use NLog :-). I can request a change, but until that comes through, it will be useful to limit the level.

**Comment by 304NotModified** [comment]
Ah I understand it now.

I think it would be nice to have a filter method? But I have never used `NLogTraceListener`. Can you send me a config/code example?

**Comment by tiljanssen** [comment]
Filtering would remove the message, not change the level, I think.

NLogTraceListener is used to  pass the loggings done with Trace calls of system.Diagnostics through to NLog, similar to adding a  logger to NLog.
You invoke it through App.config. Below an example which sets forceLogLevel.

  <system.diagnostics>
    <sources>
      <source name="exampleLib" switchValue="Verbose">
        <listeners>
          <add name="nlog" />
        </listeners>
      </source>
    </sources>
    <sharedListeners>
      <add name="nlog" type="NLog.NLogTraceListener, NLog" forceLogLevel=”Trace” />
    </sharedListeners>
  </system.diagnostics>

Til

Van: Julian Verdurmen [mailto:notifications@github.com]
Verzonden: woensdag 21 oktober 2015 15:50
Aan: NLog/NLog
CC: Til Janssen
Onderwerp: Re: [NLog] Introduce maxLogLevel for NLogTraceListener (#978)


Ah I understand it now.

I think it would be nice to have a filter method? But I have never used NLogTraceListener. Can you send me a config/code example?

**Comment by 304NotModified** [comment]
> Filtering would remove the message, not change the level, I think.

yes indeed. I was under the impression that you would like to remove the "warn" messages.

**Comment by 304NotModified** [comment]
I think it's a good idea to add this, if we can implement it a more generic/flexible.  (so not only *max* level and maybe also not limited to the level of an event)

**Comment by snakefoot** [comment]
NLogTraceListener now supports filters, so you can now use the System.Diagnostics.Trace-Filtering logic to perform whatever filtering you desire. See also PR #2137

You could use the `System.Diagnostics.EventTypeFilter` for this:

https://docs.microsoft.com/en-us/dotnet/framework/debug-trace-profile/how-to-use-tracesource-and-filters-with-trace-listeners
