### ISSUE TITLE
Support for Entity Framework connection strings

### ISSUE THREAD

**Issue by ghost** [NLog/NLog#98]
<p>Hello. NLog does not currently seem to support Entity Framework connection strings: DatabaseTarget.InitializeTarget() throws an exception because it cannot create a DbProviderFactory from the EF providerName=&quot;System.Data.EntityClient&quot;.</p>

<p>&nbsp;</p>

<p>Unfortunately, because DatabaseTarget is sealed I can&#39;t just customize the connection string behavior as I would with log4net.</p>

<p>&nbsp;</p>

<p>Please consider adding direct support for the EF provider type (might not be too hard, a regular connection string is indeed embedded in there) or unsealing DatabaseTarget.</p>

<p>&nbsp;</p>

<p>Thank you!</p>

**Comment by Misiu** [comment]
I recently found https://github.com/ladenedge/NLog.EntityFramework, cound this be added as official target? Right now my only option is to use than package (last update 4 years ago) or use this as a workaround:

```C#
var entityFrameworkConnection = ConfigurationManager.ConnectionStrings["ApplicationDbContext"].ConnectionString;
var builder = new EntityConnectionStringBuilder(entityFrameworkConnection);
var connectionString = builder.ProviderConnectionString;

var nLogConfig = LogManager.Configuration;
var dbTarget = (DatabaseTarget)nLogConfig.FindTargetByName("db");
dbTarget.ConnectionString = connectionString);
LogManager.ReconfigExistingLoggers();
app.UseNLog();
```

Ideally I would be able to use this inside nlog.config:

```XML
<target xsi:type="EntityFramework" name="db">
```

@304NotModified please consider this, it would be nice addition to already great framework.

**Comment by 304NotModified** [comment]
That depends of the current creator of the extension. 

I think also that it would be a valuable option.

**Comment by Misiu** [comment]
@ladenedge are You willing to add Your project as part of official NLog repository?

**Comment by ladenedge** [comment]
Certainly.  How can I help?

**Comment by 304NotModified** [comment]
I have no problem to move the code to the NLog organisation (and add @ladenedge as admin), but it will be still an separate repository (not in NLog main package due to references). 

Question is what the real benefits would be?

**Comment by Misiu** [comment]
@304NotModified I see those benefits: this will be official package, so possibly more people will use it and more developers will be able to provide feedback. If this will be official then XSD can be changed to include this target.

What do You think?

**Comment by 304NotModified** [comment]
> I see those benefits: this will be official package, so possibly more people will use it and more developers will be able to provide feedback. 

Agree with that

> If this will be official then XSD can be changed to include this target.
Not sure about that. We could add it fixed to the XSD, but then it's strange (IMO), that the XSD autocompletes the target, but it would crash if NLog.EntityFramework isn't included.

Of course it's easier for the NLog team to help with the current implementation of NLog.EntityFramework (make it NLog 4 compatible, add appveyor/codecov etc)

**Comment by Misiu** [comment]
@304NotModified then maybe this can be add to NLog as new target, but without System.Data.Entity. Instead of that just a small parser could be added that would create "normal" connection string from one used by entity framework.
So from: `metadata=res://*/Model.csdl|res://*/Model.ssdl|res://*/Model.msl;provider=System.Data.SqlClient;provider connection string=&quot;data source=192.168.1.100;initial catalog=LogDB;user id=myUser;password=abc123;multipleactiveresultsets=True;application name=EntityFramework&quot;`
it would create:
`data source=192.168.1.100;initial catalog=LogDB;user id=myUser;password=abc123;multipleactiveresultsets=True;application name=EntityFramework`

With that parser that target can be included in XSD.

I might be wrong about that, but in my case I only need to parse that connection string and call stored procedure that adds logs to my db. But full support for EF would be hard and probably not easy to setup in XML config.

**Comment by Misiu** [comment]
@304NotModified also I found out that `DatabaseTarget` is sealed, what are reasons for that? All `EntityFrameworkTarget` does is just parse out normal connection string, so ideally it would extend `DatabaseTarget` and override just one or two methods.

**Comment by ladenedge** [comment]
Aye, that's the reason my little library rewrites `DatabaseTarget` rather than extending it.

**Comment by 304NotModified** [comment]
> @304NotModified also I found out that DatabaseTarget is sealed, what are reasons for that? All EntityFrameworkTarget does is just parse out normal connection string, so ideally it would extend DatabaseTarget and override just one or two methods.

Don't know. I have joined NLog after this. Guess performance.

**Comment by 304NotModified** [comment]
> ut without System.Data.Entity. Instead of that just a small parser could be added that would create "normal" connection string from one used by entity framework.

I would be great if we could support it without the dependency!

**Comment by Misiu** [comment]
@304NotModified I've googled a bit and I found that there is no performance benefits from using sealed - http://stackoverflow.com/a/390627/965722 maybe this could be changed? This way it would be easier to build `EntityFrameworkTarget`

**Comment by 304NotModified** [comment]
> @304NotModified I've googled a bit and I found that there is no performance benefits from using sealed - http://stackoverflow.com/a/390627/965722 maybe this could be changed? This way it would be easier to build EntityFrameworkTarget

Thanks for searching! I have create a new issue for it.

**Comment by 304NotModified** [comment]
> @304NotModified I've googled a bit and I found that there is no performance benefits from using sealed - http://stackoverflow.com/a/390627/965722 maybe this could be changed? This way it would be easier to build EntityFrameworkTarget

See https://github.com/NLog/NLog/pull/1675!

**Comment by 304NotModified** [comment]
Up for graps as long as I won't introduce new dependecies.

**Comment by Misiu** [comment]
@304NotModified  I finally found time to create that target. I've folked main repo and added new target - https://github.com/Misiu/NLog.
I'd like to create PR, but I'd like to ask for guidance. 
Did I add conditional compile variables correctly?
I must add test, but I don't know how they should look. I'll be grateful for help with them. I'm just overriding `InitializeTarget` from `DatabaseTarget` so maybe I can reuse tests for that class?

**Comment by 304NotModified** [comment]
hey!

Great news!

Just create PR, then I can easily give you guidance on the changed code :)

**Comment by Misiu** [comment]
@304NotModified I've created PR: https://github.com/NLog/NLog/pull/2308
I'll be grateful for review  😄

**Comment by 304NotModified** [comment]
review added!
