### ISSUE TITLE
Add "fast modus" to coloredConsoleTarget

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#980]
The [coloredConsoleTarget](https://github.com/NLog/NLog/wiki/ColoredConsole-target) can be slow sometimes.

Besides some performance improvements: #764, we would like to add a "fast" modus to the  
coloredConsoleTarget, which has less features but more performance. So

- no regexes or find text
- only color on status

See for inspiration:  #451

**Comment by dnlgmzddr** [comment]
I'm working on this one.

**Comment by 304NotModified** [comment]
Nice!

Good to know that @bhaeussermann is probably also working on the coloredConsoleTarget  https://github.com/NLog/NLog/issues/764

**Comment by dnlgmzddr** [comment]
@304NotModified Should I look other issue?

**Comment by bhaeussermann** [comment]
@304NotModified I've fixed a bug today in `ConsoleWordHighlightingRule` and made a pull request #996 for that (there was no issue reported for this bug to my knowledge).  
My pull request includes a new `ColoredConsoleTargetTests` test class, but unfortunately I could not find a way to test the colors (see my comment in that pull request).

I'm not working on any other issue related to `ColoredConsoleTarget`.

**Comment by dnlgmzddr** [comment]
@304NotModified whrn you mention 

* only color on status

What exactly do you mean?

**Comment by 304NotModified** [comment]
Well it should support that, and probably not more than that.

**Comment by 304NotModified** [comment]
So change color of the output depending of the level (status)  of a event.
