### ISSUE TITLE
Error System.InvalidOperationException: The SMTP host was not specified.

### ISSUE THREAD

**Issue by Sal420** [NLog/NLog#989]
Target configuration is:

```
  <target xsi:type="Mail"
            name="errorMail"   
            smtpServer="myMompanyServers.com"
            smtpUserName="mylLanId"
            smtpPassword="myLanId"
            useSystemNetMailSettings="true"
            to="myName@myCompany.com"
            cc="myName@myCompany.com}"
            from="myName@myCompany.com"
            subject="Error Alert from NLog"
            />


<logger name="*"   minlevel="Info" writeTo="errorMail" />

```

**Comment by 304NotModified** [comment]
Hi, which NLog version is this? Did you specify `Network` as delivery in `<mailsettings>`?

**Comment by Sal420** [comment]
Hi Thanks for the quick turn around. I have applied your recommendation and received the following error from  NLog-Internal-Log

Error System.Net.Mail.SmtpException: Syntax error in parameters or arguments. The server response was: 5.1.3 Invalid address

NLog Ver 4.1.2
MVC IF Ver 5

 Web.Config change verbatim (masking company, user id and password)
 <system.net>  
<mailSettings>
  <smtp>
    <network host="my.mail.Company.com" password="myLaanId"      userName="myName@myCompany.com" defaultCredentials="true"/>
  </smtp>
</mailSettings>
</system.net>  

***deliveryMethod="network"  results in an blue scribbly line  error and is not part of IntelliSense

No other changes applied

**Comment by 304NotModified** [comment]
Does the host / smtpServer setting has special characters in it? (eg `:`)

**Comment by Sal420** [comment]
Hi,

with rested eyes and your advise to revisit the the code  - detected the typo in the email address .

The 2 recommendations resolved the issue.

thanks you.

BTW - 1 more question - would there be a way to use variables and pull the user credentials from  CredentialCache.DefaultNetworkCredentials
