### ISSUE TITLE
Update inner layout work around on wiki

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#990]
`{literal:text=\:}` is not needed in 4.2 any more. So that should be clear on the wiki

fix on https://github.com/NLog/NLog/wiki/When-Layout-Renderer#remarks

**Comment by 304NotModified** [comment]
See #975

**Comment by dnlgmzddr** [comment]
@304NotModified  Done

**Comment by 304NotModified** [comment]
Thanks @dnlgmzddr !
